' definition of the Item aws-q2-2023/Category/EndUserComputing

sprite $EndUserComputingXs [10x10/16z] OqS03XW0iXX10CpYO828GHaiO34c80_4Oc5bvM25Yi5aOG310W

sprite $EndUserComputingSm [12x12/16z] NOp50S1G24Dnil_2xNTx9uZb2HRntD8kdRUfhXivCrO-xZSnWySTPX2HjHaHptuix0S

sprite $EndUserComputingMd [16x16/16z] PSd70S1020D1ikY_OljosXU3SAU-H_3SgqOVqIrzr6bnsD-mMYB_q1tbvcM8_1zQ1lxHXhNwhxiMxd7uhtlhDPrz

sprite $EndUserComputingLg [20x20/16z] bOw50S0W3C2ge_zVFCETJ4dLzG2i0OTMCtPNh9FeAEPmxW2gMdhZBDU3HFSbwVkg7NFkZ8cUF87S-LgAJaGVx7coMgO7Ots8pdojCwjSlb_5WOC6l04

!procedure EndUserComputing($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Category/EndUserComputing', $name, $tech, $desc)
!endprocedure

!procedure EndUserComputingCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$EndUserComputingLg>', '', $funcName, $content)
!endprocedure

!procedure EndUserComputingGroup($id, $name='End User Computing', $tech='')
  IconGroupElement($id, 'EndUserComputing', '<$EndUserComputingLg>', $name, $tech)
!endprocedure
