' definition of the Item aws-q2-2024/Architecture/ArtificialIntelligence/AmazonForecast

sprite $AmazonForecastXs [10x10/16z] uy0A6460Wm7AOuVIB1nC3CmW1Yi7ZCM1oM800sOaqm

sprite $AmazonForecastSm [12x12/16z] XSQ55S1020FGHo6o_y9rjqEIxzOKnuX9OkpcbBDPycAWlBcBTsSodRErZYyp

sprite $AmazonForecastMd [16x16/16z] bSY50S0m30D1ixJ_mcNcVl3C_zKKGqRFOusDjOgS7QhmPCrM5QxEf71ZzRsjdktESO_s9V2r5W

sprite $AmazonForecastLg [20x20/16z] hSYr0SG0300nis__XH_2K0LKYlTqCmXTq3AcCwagBNPNpMIwp5HpmJSNWB6vRiSYTvTP1FiJzTCPzyyzSQzmNqusd6U-

!procedure AmazonForecast($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Architecture/ArtificialIntelligence/AmazonForecast', $name, $tech, $desc)
!endprocedure

!procedure AmazonForecastCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonForecastLg>', 'ArtificialIntelligence', $funcName, $content)
!endprocedure

!procedure AmazonForecastGroup($id, $name='Amazon Forecast', $tech='')
  IconGroupElement($id, 'ArtificialIntelligenceFamily', '<$AmazonForecastLg>', $name, $tech)
!endprocedure
