' definition of the Item aws-q2-2022/Resource/GeneralIcons/SamlToken

sprite $SamlTokenXs [10x10/16z] Oq05t60C8NXPEI0C7WO6LeW843C36RmW3YD8WWae16G0cOoy80QO2MB0c2

sprite $SamlTokenSm [12x12/16z] PSo50S0m20J0kCB-wnQjnO-FXAFbb6j79SrLGHXfcGsCG1UsiY_AGEvIHEHjG9j2-Y3CE8LIIEg5yqal

sprite $SamlTokenMd [16x16/16z] TSq30W0X50JGoVXr_-CkilqcuLR2No9hp9CSo0L1Zxikm3GwalzOQPJ_tw9CfpEDo0Hee64H_cVwZQ0S8LQ2UNWNM68Dwk4MPBQ0_fV7qlW2

sprite $SamlTokenLg [20x20/16z] {
VSo5bG0n20JGWOq3_PUx6Z-91_uR_3-oIiafnQaaeTwJUajIK6XL1i-95eMG5P4cHMhFs_ESnUMv77V5vh_Cu_WKYSdnQTQgh6cGrgo8o92ku1I870n2LJt5
0cWEh4rLIMRIr92OLPLDpRAgLUwb9snwNm
}

!procedure SamlToken($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/GeneralIcons/SamlToken', $name, $tech)
!endprocedure

!procedure SamlTokenCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$SamlTokenLg>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure SamlTokenGroup($id, $name='Saml Token', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$SamlTokenLg>', $name, $tech)
!endprocedure
