' definition of the Item material-4/Maps/EvStation

sprite $EvStationXs [10x10/16z] Oy0A-860WH_2OkO74Z0M7vW5H7mC434sVWOWWkf0i8080G

sprite $EvStationSm [12x12/16z] TSP50G0n402nBNF7lzfZXhmYloA0jEKLEbgtxGsDIylLzDxh_2v2Dx8Saz7ivpoFHvHSZG

sprite $EvStationMd [16x16/16z] XSZ50GH14CD03wFR-KTxZ8lwbN1Uc2J7rteq2_zCD7uSxvRnRKZqX5uEe0ZJo_QO4tYxWx8qtjRq4ltyslxyQ6M8VDW_0ppMNG4

sprite $EvStationLg [20x20/16z] {
fSZ50GGn40InNZEDA_zeZvb1J-a_2tjLvNIH0nbNrm79xF8ye02SB-_Ewa8udNRNPo8UBsh9e6NCqqr90MQMJjUIP53nvmCbG9QkZlkh3uwdroYutOMvPrAp
fC-j0G
}

!procedure EvStation($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Maps/EvStation', $name, $tech, $desc)
!endprocedure
