' definition of the Item material-4/Maps/MenuBook

sprite $MenuBookXs [10x10/16z] Oy06MFdvEHbu-FaP6VX102Z23sOn0J6KnGjdiVFnG5bmTLnWTN

sprite $MenuBookSm [12x12/16z] TKe30W0X4AnLRlx_shEn7BdVyapJfVbWhePMWHNp7DWmeJVUSG4Ex5ZSZXDvlsFAnIOSHJkQIeAxr0W

sprite $MenuBookMd [16x16/16z] bOx50S0W54E3E-m_RN6zzQ7VWzzmuwm4g7PEKo1rGja-9ZTjIr08OTgK6k_LOKV5c3XiNIv_sBK1EVEVE7lw4sMTRdOCHKn9hqy0HuKOD2WUCW

sprite $MenuBookLg [20x20/16z] {
hSw53KHH449HUAup_LVxtIEhDqPE3FmzttKg4xRDenAOP6qQqfge1eZkUSmPZQSPWEJ3gixThNYIvcxhWRlrx9qBTqFi8krkqdDAvVbbxc4krvh3rSe-8dgs
1EYRLZSFrppUR0G
}

!procedure MenuBook($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Maps/MenuBook', $name, $tech, $desc)
!endprocedure
