' definition of the Item aws-20210131/Architecture/SecurityIdentityCompliance/AwsFirewallManager

sprite $AwsFirewallManagerXs [10x10/16z] 3SY53SD00CNGDl3fzjytjkZ9fOGyGBJbbL-XAeuHo_VBvp4UySvCSdkWx2BOR8WswWS

sprite $AwsFirewallManagerSm [12x12/16z] HSa55eLG24NH7t03vpzVqTUrpyBFqhjO3sTKMGaGm-WVyTYWiWEFa_Y765GLd8XuPbTH91Aqhmx0aDiTokRZ9zxr-CGD

sprite $AwsFirewallManagerMd [16x16/16z] {
LSY5RKKn40LHwNalhVllDuPy6k6Pt7oJVctrbkHNlOPH0Cdh3W5RLReMOsVTQvN2XskK_gqQZvQv7Qx56dBPdjsCB0mOIUPiYQ4DwNWD2Z6JupN2GUJwZBRJ
_VOQf-FVyGS
}

sprite $AwsFirewallManagerLg [20x20/16z] {
RSe9RWD0349HjGC6FFU_Rwt4wVxH-aGslvAKVx3_mNwWA7_L3mHdADJQe8YAJK8lC-nC0hncL08EkxW6Ck7R6IJmD48vEE_yPcO7A1pQHx5lTyOOpxCC9xw3
jAfBLHGptK6p52Og-Mc34Zt6aRN15awnihQOAdVtskAszWVlF_W1
}

!procedure AwsFirewallManager($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/SecurityIdentityCompliance/AwsFirewallManager', $name, $tech)
!endprocedure

!procedure AwsFirewallManagerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsFirewallManagerMd>', 'SecurityIdentityCompliance', $funcName, $content)
!endprocedure

!procedure AwsFirewallManagerGroup($id, $name='Aws Firewall Manager', $tech='')
  IconGroupElement($id, 'SecurityIdentityComplianceFamily', '<$AwsFirewallManagerMd>', $name, $tech)
!endprocedure
