' definition of the Item simpleicons-14/D/Debridlink

sprite $DebridlinkXs [10x10/16z] Oy0B-460WH_AWx3ucU0iPZWB29Z193PJ

sprite $DebridlinkSm [12x12/16z] Oo02y0C1Dv02iRbvUVdu-O5i682o-NbHsQmmDWXmGYakBav61WPcBcvkRbns0G

sprite $DebridlinkMd [16x16/16z] fSor0O1030NGZqDq_sbnl-RaDV6Wa6-iMfFsg0z7VMdShfhbs7hsiR9N7SvhSuBhx_zX8gAfneg8LqYq

sprite $DebridlinkLg [20x20/16z] lOx50GGW30HnX_HVBUuyJmQDB_e3q53rktoDpKSAr06GuZkmOFPQNDF1xJxIVFxnyJEFjaSTMW8KshS2bPez_zfaD4K5POmje2-J

!procedure Debridlink($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/D/Debridlink', $name, $tech, $desc)
!endprocedure
