@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-17/bootstrap')

' loads the Item which embeds the element ServiceAzureAdIdentityProtectionCard
include('azure-17/Item/Identity/ServiceAzureAdIdentityProtection')

' renders the element
ServiceAzureAdIdentityProtectionCard('ServiceAzureAdIdentityProtectionCard', 'Service Azure Ad Identity Protection Card', 'an optional description')
@enduml