' definition of the Item azure-17/Item/Identity/ServiceAdministrativeUnits

sprite $ServiceAdministrativeUnitsXs [10x10/16z] JSA74S9G30N1--64vj5_lMHixsnYoCmhVmjqyX9GR-6jgZf5m6NVGNHeXrZrsXcnthXw0W

sprite $ServiceAdministrativeUnitsSm [12x12/16z] ROo30GDH341ZxJzmFzBpYrbSMB15uQI68U-S04G7tTT1U8xvw9jPHEq-iaO535G5nrAkhmkVIsIRcFlV_

sprite $ServiceAdministrativeUnitsMd [16x16/16z] NOm50iGm20GXXuN-_x-tMsycEbXBbxObNcwJXLuy1PZxvUDGznXtlPFC6NB0R5GLSnD70q3xgXy_zQgjxd8TxaT1Yz5nsE7m07PCsDWT5rbwr9y8cVB55_y3

sprite $ServiceAdministrativeUnitsLg [20x20/16z] {
TP050i0m20C9DPhz_xzhvdfR3GU2B6DPf_iuI6-mDtoBy2LB9ih03w5hoqNKV8rNLbbhz3NUAOj6IhQ6go8agqSj4hM8877wUaA9w5F85siu89NIPAZtcY51
kxpx4gy8h9bZekAjITTzoGBbFEcXecLtyZyN-o3C7MCPtCQXFyq
}

!procedure ServiceAdministrativeUnits($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/Identity/ServiceAdministrativeUnits', $name, $tech, $desc)
!endprocedure

!procedure ServiceAdministrativeUnitsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAdministrativeUnitsLg>', 'Identity', $funcName, $content)
!endprocedure

!procedure ServiceAdministrativeUnitsGroup($id, $name='Service Administrative Units', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAdministrativeUnitsLg>', $name, $tech)
!endprocedure
