' definition of the Item simpleicons-14/D/Dungeonsanddragons

sprite $DungeonsanddragonsXs [10x10/16z] JSR50K81042XPxViFwtncnDjOCn97cFlzcFUNkf5--nSgWk_gyukTRHBF83YtPtT5m

sprite $DungeonsanddragonsSm [12x12/16z] LSR50GGn4C0mBuIJSV_L7gDUuizKttV7-lfUg-VhZaYlXis0c4ezSvsU4-XBp4S070eevUHKcAgRBDLZgW590Gok

sprite $DungeonsanddragonsMd [16x16/16z] {
POo5WGCm4828UzX_sdTjELUUcMhzBRitw6-jaUJygKVljPj_wcAvw_13LNslmvhZVJow2dUSkoAEN0sAuUFwUbc8Ym_qaDZkx--VsL8sabL0cugYUdMZleTy
FYD3J-ETLlb0uHK
}

sprite $DungeonsanddragonsLg [20x20/16z] {
TSk5OGKX403HMSwG3zD_j-4adZnqZNzajS5NBozyfTjzVTgA2_oOZf59kl95gekl95-ftHvtdSlGqNK0fJiTnE6Q7KquIj-M4b1JOdSDvP1BShKjSRIsRoOk
XnEfeglSGjsPYXP81EpgmRIlEaAIh4vSjVkxMz2fEU4jKxitk4kTwVeDeAAkmIM2Hou1Rm
}

!procedure Dungeonsanddragons($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/D/Dungeonsanddragons', $name, $tech, $desc)
!endprocedure
