@startuml
sprite $AzureRecentLg [20x20/16z] {
LP27SG0m20CH896w_xh1ZRky-xjZcqWr6JOuHMQo6xygn80v3A7AgnBTY5s1M_fMsntfNH4Mp_LOij0IppLHaSH_X-BhclGwfJHOW--lqnh7nU_l1_susPja
VGXhxzpH81A6udlB41Mstpp28CtVcldRn02O64oicebLuwmIgQxTXc0r3Dly0G
}

sprite $AzureRecentMd [14x14/16z] HOw55GD024C_4Qwl--zR5zm9CEc3CW2eqOEoVYM26Fn8fnfeOBoJ0FHZgt_cNGrm3Z0wAu3BTJFel2SPrtWJFZGqxm_m_l3-FWF-WAabzvN0PC_P3707

!procedure AzureRecent($id, $name="Recent", $tech="")
  CloudElement($id, 'azure/GeneralServiceIcons/AzureRecent', $name, $tech)
!endprocedure
!procedure AzureRecentCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureRecentMd>', 'Recent', $funcName, $content)
!endprocedure
@enduml
