@startuml
sprite $AzureMarketplaceLg [17x20/16z] {
ZSt50G9144JHxhBT_2E6CUp4FxuQgP6IMAmJtOnQE22Ku08FU44lw6wpdz1GTvUkpnpv2n9lkEyVI0vahEugBXXBtFFpUy6OPznmiLQTVKArmu3nE7i6dSzU
_GdVDlxiRe2IFMRK0m
}

sprite $AzureMarketplaceMd [12x14/16z] JOm50W11209j_V-B3xdQsJ11H2mhtOI4EkwJ2tBq4Q8YSSEz-gNooAjwsjMVF5UMqvlIotlp4fARTmP8zA4PmlpmD7TiS5Sl

!function AzureMarketplace($id, $name="Marketplace", $tech="")
  CloudElement($id, 'azure/GeneralServiceIcons/AzureMarketplace', $name, $tech)
!endfunction
!function AzureMarketplaceCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureMarketplaceMd>', 'Marketplace', $funcName, $content)
!endfunction
@enduml
