@startuml
sprite $AwsServerContentsLg [20x20/16z] uoG5SB130GT2Z8s55GnOs934s3Z0gjXGnDX0ojXGnI0qONKSOC16WHsq54E40TQm8WK

sprite $AwsServerContentsMd [14x14/16z] uyG07600ux2o0G4h1vJ71WPm7aWX6ouvTdOaENOs88BpG2HX7i9sL9TX

!procedure AwsServerContents($id, $name="Server Contents", $tech="")
  CloudElement($id, 'aws/GroupIcons/AwsServerContents', $name, $tech)
!endprocedure
!procedure AwsServerContentsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsServerContentsMd>', 'Server Contents', $funcName, $content)
!endprocedure
@enduml
