' definition of the Item aws-20210131/Resource/Blockchain/AmazonManagedBlockchainBlockchain

sprite $AmazonManagedBlockchainBlockchainXs [10x10/16z] uySBU7cWW9URamiCEBc1B4uW3MGXPF6R0W

sprite $AmazonManagedBlockchainBlockchainSm [12x12/16z] uoSHy71nSN5pWG4FDoSN9uW1fBYHsL0rt20rf9eF

sprite $AmazonManagedBlockchainBlockchainMd [16x16/16z] hKn50K1H33fEWVvflyiBC3T0myQkQXobpj94PEQPwUU0zZZMYgYZXVUrnxd7jV_uQy2bjnGDsmu

sprite $AmazonManagedBlockchainBlockchainLg [20x20/16z] nOwr0S0m30JRlvTX_sd37FSwWnXw5ctb4EVFYirDgtX1X1rerQbLCZYkJpfysDixV8FQQyRrq-vTxesoc04

!procedure AmazonManagedBlockchainBlockchain($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Blockchain/AmazonManagedBlockchainBlockchain', $name, $tech)
!endprocedure

!procedure AmazonManagedBlockchainBlockchainCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonManagedBlockchainBlockchainMd>', 'Blockchain', $funcName, $content)
!endprocedure

!procedure AmazonManagedBlockchainBlockchainGroup($id, $name='Amazon Managed Blockchain Blockchain', $tech='')
  IconGroupElement($id, 'BlockchainFamily', '<$AmazonManagedBlockchainBlockchainMd>', $name, $tech)
!endprocedure
