' definition of the Item eip-1/MessageRouting/RecipientList

sprite $RecipientListXs [15x10/16z] uq43J2W05vUBdu-F3yPbXylo0m4V481ec2mhkbuEi2n-Ym

sprite $RecipientListSm [18x12/16z] uy44JEW0hmWpCve85okg20SBGXS_2F2108Z135V3oeffCWSR2wRjH8i

sprite $RecipientListMd [25x16/16z] uy49c700oYKui4imy_2pim412ve4BpEcKGXXX0G_1F210OJDYLy7aXGBJkS2NGK2h9Z-OASuI301

sprite $RecipientListLg [31x20/16z] lT433WL1303Gf1xs_gVzNACRpei7PNq04HnzZHPUk_U_Ysig0dpxs-akD-dtvmVgxhhufF_vRFSR2RF1bzpcRXBtZSL0mxxxBlUPZjeOHlWD

!procedure RecipientList($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'eip-1/MessageRouting/RecipientList', $name, $tech)
!endprocedure

!procedure RecipientListGroup($id, $name='Recipient List', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$RecipientListMd>', $name, $tech)
!endprocedure
