' definition of the Item eip-1/MessageRouting/Splitter

sprite $SplitterXs [15x10/16z] uq43J2W03vUH6LEMaOM9cP-VdmSaIwfU5

sprite $SplitterSm [18x12/16z] uy44JEY0a0WR8njM4KvEX0Wh9mj83ICJ4pC_4B33rB2o8jGmip8JQJ9X5m8

sprite $SplitterMd [25x16/16z] uy49c700waWmChAHAC7AoWgIO6428WZWX4cnWIKO6K4I_630WsGKCniRCrGXErGz6pjsEzZPsIXoBkLX1G

sprite $SplitterLg [31x20/16z] nP434iG034Kdpcvr_zFMjlk6CNwu0Qv1duG9G2w4HMpNR0NmrX5RrtmOJcfq63RchZgKkffPBznDfDVUyhXYj8Pa

!procedure Splitter($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'eip-1/MessageRouting/Splitter', $name, $tech)
!endprocedure

!procedure SplitterGroup($id, $name='Splitter', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$SplitterMd>', $name, $tech)
!endprocedure
