@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2022/bootstrap')

' loads the Item which embeds the element AwsIoTThingTemperatureVibrationSensorCard
include('aws-q2-2022/Resource/LoT/AwsIoTThingTemperatureVibrationSensor')

' renders the element
AwsIoTThingTemperatureVibrationSensorCard('AwsIoTThingTemperatureVibrationSensorCard', 'Aws Io T Thing Temperature Vibration Sensor Card', 'an optional description')
@enduml