' definition of the Item simpleicons-14/H/H3

sprite $H3Xs [10x10/16z] JOY50O103CI2Ezb_MkIzFQUzosit94LD3Y6PnjlKCHmJf48uzIJ52NW1

sprite $H3Sm [12x12/16z] LOY50G0n38IkxcN_QT-L63dfJyMgXKCj662pHBKcRNjp61DcW2YQ0C-6CWZfy2kqgQfVFze07mw_-BhQiLS

sprite $H3Md [16x16/16z] RSx5OKKX50N0yzo0wR_QvBlF2gxdfsbFqkKETSUMYnvn_rTxqYyT-wrMXvR-i2KOAWHacPE2Ee04AKSIdbKRUsZJ0Ei2zNBPiqZEQEFpVtD0onFq-U4V

sprite $H3Lg [20x20/16z] {
VSm5LaGn40NHwdpNslzkEGyObnjF2r-qWaU7Uh2gH9JgE1j4gA91hBhIw2SsNUl_IpdL4-ZT04tKw7jZU6YrQK2ZgZIrQi2fKix0el5_GhUvCwYkQA010x0P
6sf06CmFVwiUFQSQt6aQE_Tce-V1hWEV_G
}

!procedure H3($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/H/H3', $name, $tech, $desc)
!endprocedure
