' definition of the Item simpleicons-14/H/Hootsuite

sprite $HootsuiteXs [10x10/16z] DSQ50S0m4CD0bRdQVzf24j-3pGqnkQHQJ63fDyo4RKMWly1RMJrK34Xv0G

sprite $HootsuiteSm [12x12/16z] HSl5WKG134CnpMT-_LUx34hicqty6phzgxhgGNrv8Snjuygmy8A146KNED7rDTzaQEoBhzhxDQE-y0u

sprite $HootsuiteMd [16x16/16z] LS654SD040GmcV5---ys4xObLkwImSsPLDlyvQT3dw_9KnQqf6g7sZpDc20OJooTnb5eGM8anLCydKFYgHoOqfA6IZTdNf8X7_OysNBLCULlzBJdxS03

sprite $HootsuiteLg [20x20/16z] {
PSm5Oe0m50JHYU4mzpzjPUlfG_DbuQdyTxeNPaDTcLIDqRRZkk_Kkh-Cb5OZ3g9w9pGUmejux71sW4L-ow1RtYTGda5PeLgIAR0f27TgjC8EUm4hkXArtf2K
NIMb7PAfZsf9r7rgDBzLZ8VTMRR-6YHrcefwQbmTu1K
}

!procedure Hootsuite($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/H/Hootsuite', $name, $tech, $desc)
!endprocedure
