' definition of the Item simpleicons-7/V/Vimeolivestream

sprite $VimeolivestreamXs [10x10/16z] Oo0Pi71nSp8mih4nSHAh0m

sprite $VimeolivestreamSm [12x12/16z] Ow0IOE7auM9bPcHZPMDcfiGS

sprite $VimeolivestreamMd [16x16/16z] OnXWmCB7pSF5pSp8oCp2pCR6na5l-m4

sprite $VimeolivestreamLg [20x20/16z] rOJ70O1G58F8xw_ilwxzv0IQ0Fnoa_VQyWot1MfZZb5a0ufAaK1wojUt0m

!procedure Vimeolivestream($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/V/Vimeolivestream', $name, $tech, $desc)
!endprocedure
