' definition of the Item simpleicons-7/V/Vite

sprite $ViteXs [10x10/16z] DOQ50O0048ImM_QVrho_X5y7j82w_AVkYb5F8J0LWFOX72IaH1_S

sprite $ViteSm [12x12/16z] FSp50KCn30MmznaJxJzjsTN5xFpibK2I0JCQWXLtToLii4dIx1sMkhJxlhCk3FLosELhrAHOU_w-xIS

sprite $ViteMd [16x16/16z] JSw53S0W54NHLyFXxhzjWtCYo5SjLzGIgEej4nw9AkfBYCK0A02PoXUF923IHBAa3poDGnLuUmEHq0S3zMrHbsil4bO3y64urtiIjnR8jcZxYEW4HQSBTJy

sprite $ViteLg [20x20/16z] {
NSs5aKGX50J0-QxG-KTxmXgrNVfqqbjAUjDL8V_6wT7I7FcpRd1jYsQu8PfTSyF-k79epZgG19mUAdCUJRU7LSs_4yN3RKY3zP4ygddOO4SXJVTnTUPbH6Pk
-O31Q4y7Io6zaxAQavxxyQstE-KRLxvDyl8B
}

!procedure Vite($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/V/Vite', $name, $tech, $desc)
!endprocedure
