@startuml
sprite $MaterialsSignalWifi3BarLg [20x20/16z] {
bSr50WKX30FG57VkVzelKpAsuwsW5kmIUNtDmWOBBBFqAkh3kX-hRnn5dqeVevVajGHnUSnbPASfOTw45PokKX8eKrWg1cIRbfh5nOqZmU4kyFwD9Dw_CONt
xqMBNLy
}

sprite $MaterialsSignalWifi3BarMd [14x14/16z] VSw35KKn303GiCR-qvQVJ_UW2E4P8Ws8wquVk1yimgydgq-b9AyySxM-w2hq--4H9ehp4UarWdEjcU5DNqKlrlwl0nSw

!procedure MaterialsSignalWifi3Bar($id, $name="Signal Wifi3 Bar", $tech="")
  CloudElement($id, 'materials/Device/MaterialsSignalWifi3Bar', $name, $tech)
!endprocedure
!procedure MaterialsSignalWifi3BarCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSignalWifi3BarMd>', 'Signal Wifi3 Bar', $funcName, $content)
!endprocedure
@enduml
