@startuml
sprite $MaterialsBatteryCharging30Lg [20x20/16z] bT350GGW34JHJ73llzfrnVduEqA7WHcLW6_XJ_dLZg4rK6lK6Xfxlb3RUty7won8thUlXH81Nq9jgjGMP6Wi-LAPoocdb1t-V-_Ubvgk

sprite $MaterialsBatteryCharging30Md [14x14/16z] ROo35G1144C7oHdzLtl6OlvZA06ggJ3JL1moKPegpPH8eZHz1LM8LtMh-zhz2bsgXlbNQ0yW5Ji

!procedure MaterialsBatteryCharging30($id, $name="Battery Charging30", $tech="")
  CloudElement($id, 'materials/Device/MaterialsBatteryCharging30', $name, $tech)
!endprocedure
!procedure MaterialsBatteryCharging30Card($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsBatteryCharging30Md>', 'Battery Charging30', $funcName, $content)
!endprocedure
@enduml
