@startuml
sprite $MaterialsSignalWifi4BarLockLg [20x20/16z] {
bP1L0iGW30LV85xX_gVTkd_jL1aaWh-WKfbheKkmvT1cXZIcpMIxaRCjtbvuAVbsML3xk-Z3Am0UBsK56tef790V6mkAQbtb4IS09L9QvHx7GG98MTqUnr53
DUGUHs3BPxp5STfSmo4p2I-7KjOZXc7etdrS0BvC
}

sprite $MaterialsSignalWifi4BarLockMd [14x14/16z] PSo53G0n40F1THYL_hjznepmm6OcOyJ1-5HRgyaRK6ZZr8BiEbownOzJyXQ8nn1r5EOzPEISrj7KTIgoCfQLxMDaXH0YhDOchx9-i8kHroH1Y37miG

!procedure MaterialsSignalWifi4BarLock($id, $name="Signal Wifi4 Bar Lock", $tech="")
  CloudElement($id, 'materials/Device/MaterialsSignalWifi4BarLock', $name, $tech)
!endprocedure
!procedure MaterialsSignalWifi4BarLockCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSignalWifi4BarLockMd>', 'Signal Wifi4 Bar Lock', $funcName, $content)
!endprocedure
@enduml
