@startuml
sprite $MaterialsSignalCellular4BarLg [20x20/16z] dSYd0G0X44N1Ey2H-kyMldiR52FdUzLAh55YhH9gwrpfNEbSuL0w5Ww5G-bGE1HEXKFXRgr9kk9ygGC

sprite $MaterialsSignalCellular4BarMd [14x14/16z] TSU33G0m002msVZ_sjbeMF25rX2-nl8bnlCrUIDv8taZPJrrBNF4-Zd41mfs4G

!function MaterialsSignalCellular4Bar($id, $name="Signal Cellular4 Bar", $tech="")
  CloudElement($id, 'materials/Device/MaterialsSignalCellular4Bar', $name, $tech)
!endfunction
!function MaterialsSignalCellular4BarCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSignalCellular4BarMd>', 'Signal Cellular4 Bar', $funcName, $content)
!endfunction
@enduml
