@startuml
sprite $MaterialsBrightnessMediumLg [20x20/16z] {
RT050iKW30DGwltQ-vzsxYJpDuEqFKJj6OgWZggkA6wMDINDN5RpclDxV-U3hsQBlPbzKhlPTARVpIWFQrv9snyFusy5hNGOlMj2PE1Ty0ym5ZHcD3VK0UmA
Tugw7m4
}

sprite $MaterialsBrightnessMediumMd [14x14/16z] LKu54iH030ftBRFE_rzRDp8QF8u3uZtaVBz_CakP_EyV9TKv3V7-SiHyVCZd5wdWUCvlKeP_hlGKR_1sN-QhLm

!procedure MaterialsBrightnessMedium($id, $name="Brightness Medium", $tech="")
  CloudElement($id, 'materials/Device/MaterialsBrightnessMedium', $name, $tech)
!endprocedure
!procedure MaterialsBrightnessMediumCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsBrightnessMediumMd>', 'Brightness Medium', $funcName, $content)
!endprocedure
@enduml
