@startuml
sprite $MaterialsBatteryCharging50Lg [20x20/16z] bT3L0O0m303HN70gsNzQt9shly_Apr3b86WNEzMfByRPaBF9sJZRy69h5Dcm5spCkHB9pEtCFDHdo-neBdKd2xKTh8eXXX0hThytXDpM0W

!function MaterialsBatteryCharging50($id, $name="Battery Charging50", $tech="")
  CloudElement($id, 'materials/Device/MaterialsBatteryCharging50', $name, $tech)
!endfunction
!function MaterialsBatteryCharging50Card($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsBatteryCharging50Lg>', 'Battery Charging50', $funcName, $content)
!endfunction
@enduml
