@startuml
sprite $MaterialsSignalCellularNullLg [20x20/16z] dSY53O0m04N1ybEt_RV5uM4nBdxcBwjtLRshwrMbwLdUxaS5e_seWQFEepYAepYAepXR_HQShSNguDQpjRVQi9mUpAS9

sprite $MaterialsSignalCellularNullMd [14x14/16z] TST50S0m402mClktErwFyuip1PnKSHPQQXcMUWWLnTtRkRTpRsSljIVlqihXaQ-5kcL7dG

!procedure MaterialsSignalCellularNull($id, $name="Signal Cellular Null", $tech="")
  CloudElement($id, 'materials/Device/MaterialsSignalCellularNull', $name, $tech)
!endprocedure
!procedure MaterialsSignalCellularNullCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSignalCellularNullMd>', 'Signal Cellular Null', $funcName, $content)
!endprocedure
@enduml
