@startuml
sprite $MaterialsSdStorageLg [20x20/16z] rT2r0S0m30H0cVb__sd3J7skjCNoGIzaPqkR5BC_LMUYySuKjpz1YnUh9VdjYTStKqcikSkRum0W1dJhs-ulRwQWBR3TIX_8Ynu

sprite $MaterialsSdStorageMd [14x14/16z] hSUr0O1G50F0_pHuzfyMTrgkk_9bMEWMhpmzChRq45FrN68TQmltN1Sa1mu3uzZYpobsMbuc

!procedure MaterialsSdStorage($id, $name="Sd Storage", $tech="")
  CloudElement($id, 'materials/Device/MaterialsSdStorage', $name, $tech)
!endprocedure
!procedure MaterialsSdStorageCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSdStorageMd>', 'Sd Storage', $funcName, $content)
!endprocedure
@enduml
