' definition of the Item azure-6/Item/Networking/ServiceOnPremisesDataGateways

sprite $ServiceOnPremisesDataGatewaysXs [10x10/16z] JSR50G0X0C2mdYBx3qnnyWgdxnUwlo3pglLjebgu76r9C4QJqLu1

sprite $ServiceOnPremisesDataGatewaysSm [12x12/16z] NSRN0O0m2431XwO0-m-iwUM-Zaigg49z12I44FCF24Kk95Il5grGJYYm0fb_g9mfU61o0VW

sprite $ServiceOnPremisesDataGatewaysMd [16x16/16z] RSZ50G0m2CNGNvVzzwqhaDiBn7oFy0xdmsWEsvjZymmBlUpYoDiLmXoRM0Dxs3GY3e2UTfqEkspnHPnoLlzOh

sprite $ServiceOnPremisesDataGatewaysLg [20x20/16z] TSg5aSL03C1GhV7M_VTxdnnEth16F9FuK7Oysk5gjYRpoCQNsjVQrhH50snh3TlyjLYB8ajS6p2wZKuY3C_vnJRA_4cuD00vD6UdaejhYrbLunohk8ZrUW4

!procedure ServiceOnPremisesDataGateways($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-6/Item/Networking/ServiceOnPremisesDataGateways', $name, $tech, $desc)
!endprocedure

!procedure ServiceOnPremisesDataGatewaysCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceOnPremisesDataGatewaysLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServiceOnPremisesDataGatewaysGroup($id, $name='Service On Premises Data Gateways', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceOnPremisesDataGatewaysLg>', $name, $tech)
!endprocedure
