' definition of the Item simpleicons-14/N/Nationalgrid

sprite $NationalgridXs [10x10/16z] Oo0PSB8oSx82QMP-g00J8Hq

sprite $NationalgridSm [12x12/16z] Ow0CCC8Od8oiJ0mi36pSR8mSC34ECWm4

sprite $NationalgridMd [16x16/16z] nS470O10302nwsxz2sPB03vXcH14PAfH2QYM903XOGx2ntO

sprite $NationalgridLg [20x20/16z] rSUt0SD040InERFlJV_TIYax8961hsdWOL6Si2IXHP7rxXhX7K6bKw9Vaobmou34wxzMUN3UvWS

!procedure Nationalgrid($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Nationalgrid', $name, $tech, $desc)
!endprocedure
