' definition of the Item simpleicons-14/N/Nextbike

sprite $NextbikeXs [10x10/16z] Oy09EFWP67Zv-O4a3uZB3mHWWfqFp0AAy8A46O6o82uta61c1Qbc0mfpSo6P1

sprite $NextbikeSm [12x12/16z] ZOl50SD04CIKc57zLtlyD6aPXW-OW5uxc4pyu3UcP2RbqtDgFU2vvlmlFKL9xLSLkfJ_t101

sprite $NextbikeMd [16x16/16z] dStL5KGX303HUOvF_ztk2VolNLoIyBUx7O3XW7CjL4E5mUAqGrltBWmpnVwuu0LabRsquI71CjScxaGL771Pq8rTOsW3303R1dFTDpvw0G

sprite $NextbikeLg [20x20/16z] {
jOw54SD030JFpxpzTnjhh4a1WNqKd_v8WsWl64rI0lTj7YoyP7WKEBh9cvqiweJtLy9PMknBrs5K3Xu66N3GDSnDOBfl8_zTBFybdyZqsWk4EITS6X2LeKcu
58iONJTnxQA7UOQ-umK
}

!procedure Nextbike($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Nextbike', $name, $tech, $desc)
!endprocedure
