' definition of the Item simpleicons-7/S/Selenium

sprite $SeleniumXs [10x10/16z] POc50O0m40CFTxB_j53NboWAGwyuSNGnYbGX24waJ03SGXnSo-EoC3y

sprite $SeleniumSm [12x12/16z] JOg50O0m30GFTzX_Mzgul_55aNX9_39H4ef7Ui3qeN_QOrN1Kl1sFCCrNXyTtrtTpxDZuEoduwmV

sprite $SeleniumMd [16x16/16z] LSp50GH130F17cOh_sYFOQrV6OHSmDCxU0_Gpri6zZCO7FqiOEbYqVGsrrQKaR9aTRpTeJv8ZRoi2HoebLyV6UQSBmT2u1WrfvUrIp79IhMtNUu

sprite $SeleniumLg [20x20/16z] {
RSv50WGX30NH6i4X__wd7MbDI-ruMD0vk5ZXQW1NAYUBK0stbZe4EOCcUCfRXJyvSrFCLglDgDKoVgRPm2m4IQCv6_ht0B9cUmEFhiHGORPV0J00wBFrdsOg
r5ys6wG2rWWQsSzIvnVUirswjIy
}

!procedure Selenium($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Selenium', $name, $tech, $desc)
!endprocedure
