' definition of the Item simpleicons-7/S/Sonarlint

sprite $SonarlintXs [10x10/16z] 1S450S10000XvlxNl-q0hZPGixsBRj0cGDSycQ4uNDxjtdT00kGAXAtkuWS

sprite $SonarlintSm [12x12/16z] DSR70SCm4C0mskhbnFsdJGzUu6tP-TBPGW7Cl6tv5oAGFzUyBmP1HTlHFDXJUm3SN23o9-v_AnZV7e3mhS8J

sprite $SonarlintMd [16x16/16z] {
JSU55GCn4CHG-SLCwh_QyC5V7BxYSWGEov_2bsO-fkiNuUVXX2MdQC3CPPla9hh4YXq7UwB6wCYxzNTF74ROHmU3t1HnSd5HV70O0ijunWGmtH4e_Y84lpR0
2m
}

sprite $SonarlintLg [20x20/16z] {
NT25WOL0303HMPnSmlHVxTd7txeBktKpHsv6TzNOgTK1axeUNSckqm3OYvsEC9hSAIWFimiMJxhQqO3krhV9w1VXHDcZf8euYsjXnXXXoahdm6WZX2md9vuK
vQ5Pb1rtQKTJRYO5LdrtGUYyxvNQtRuqerGvBUhni_03
}

!procedure Sonarlint($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Sonarlint', $name, $tech, $desc)
!endprocedure
