' definition of the Item simpleicons-14/R/Redash

sprite $RedashXs [10x10/16z] Om02Tdvc1Z3W1m480yfaXj105XU8omjYWJ4tX0K12BqG06SmW1a

sprite $RedashSm [12x12/16z] JSl50S1G309Gwbxsd_PRz9qYWExc3l6os_fuKKnjbWcapCXp8pCUdt-A5Lx-CAnj_6MKi9En0W

sprite $RedashMd [16x16/16z] LOs50G0X4CFwWaltdnRNe2boQBoU5ekNdLjNm4MiQeTeaFFOErAYPjs1wAkxvhBLgcu01EAPVly_t2rzSGK2WyTNbJWWBIvtk0XZpG

sprite $RedashLg [20x20/16z] {
PT250O0m44FHuDNB_jjIruy_l2XzGdjXp37tTMBBTUhPJ9PZnt8PKEw-PYD2cY6DSpGJJU40VBENF8vajXdYffia4uhGCymIrdUoWsF8VJi1pquX9Vt7UcUW
6vizsEp5PdsCVm
}

!procedure Redash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Redash', $name, $tech, $desc)
!endprocedure
