' definition of the Item simpleicons-14/R/Rossmann

sprite $RossmannXs [10x10/16z] 5Sc54OG040J1ViMP_BEbpbPXws-cUBNH3_jGU9Us5vGxxsR-___tdKcIWcmJ47urdGS

sprite $RossmannSm [12x12/16z] FS65OGCm0C0mXpd-_zgjBF6qxBnforC1Z02b2VuSv4d1DSfwKD3gM-FsupGQBqKadLiP0N4X0bRm8E85E3ur-0S

sprite $RossmannMd [16x16/16z] {
JS65eOLG5C2m0jVbTFzflpmbuI5lvy7RKaEjFEW5G7C363m8BjZU7LXuK66RXOTBuN2BRu3AK1zgmYaZD8nmYuTql4AErLeM9qtamQ1uuTa4w0BRX6SLXXbW
6TcZgfc7muS0-0K
}

sprite $RossmannLg [20x20/16z] {
NT17UaKX3CLWSJi4hFslDWMSzluHw3iZashOB_uuJQEGr0PGGYlJBDD6hBUUB2toT_eAb6KRAcm-s4dxR6YrG5ej37bQQ08UbRhvuxwuxDb-RDNBeswdCeGQ
coWAnOOTEdV3mN3ZJPIbkL4KxFGL3mNgZ86kb6kVjInDjxydZQxAZyTfhD47
}

!procedure Rossmann($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Rossmann', $name, $tech, $desc)
!endprocedure
