' definition of the Item simpleicons-14/R/Rubysinatra

sprite $RubysinatraXs [10x10/16z] Oy0EUFdvkI4iVX3WWhFuWJHG5WWO-VduUS1AUFY1SX00KSQDQXW

sprite $RubysinatraSm [12x12/16z] VS750O1G5C2muaxtd_RhkqB2ZtaV28FLJNNQK1bcTBHQzLOwlQnUrPFRxk1J1W

sprite $RubysinatraMd [16x16/16z] dSgr0SCm54NHBsRT_QSDYhh4Fjq3kID32piglkh8da5zCvF_nCWM9PDr7tC63rQcmaSQCGAMKnC9EusVIIbw9Vzv0W

sprite $RubysinatraLg [20x20/16z] hS-r0GGX54NHDuxV_gjTnMDE1j-rmAPPvCiFIHH1nK7bb0KghunErDVbQH8ONQ0zajqRS03gxFzSWfgG_o3Quyj6W4FCyhvLijjmXJ-rm1i

!procedure Rubysinatra($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Rubysinatra', $name, $tech, $desc)
!endprocedure
