@startuml


include('simpleicons-7/bootstrap')
include('simpleicons-7/_/_1001Tracklists')
include('simpleicons-7/_/_1Password')
include('simpleicons-7/_/_3M')
include('simpleicons-7/_/_42')
include('simpleicons-7/_/_4Chan')
include('simpleicons-7/_/_4D')
include('simpleicons-7/_/_500Px')
include('simpleicons-7/A/Abbott')
include('simpleicons-7/A/Abbrobotstudio')
include('simpleicons-7/A/Abbvie')
include('simpleicons-7/A/Abletonlive')
include('simpleicons-7/A/Aboutdotme')
include('simpleicons-7/A/Abstract')
include('simpleicons-7/A/Academia')
include('simpleicons-7/A/Accenture')
include('simpleicons-7/A/Acclaim')
include('simpleicons-7/A/Accusoft')
include('simpleicons-7/A/Acer')
include('simpleicons-7/A/Acm')
include('simpleicons-7/A/Actigraph')
include('simpleicons-7/A/Activision')
include('simpleicons-7/A/Adafruit')
include('simpleicons-7/A/Adblock')
include('simpleicons-7/A/Adblockplus')
include('simpleicons-7/A/Addthis')
include('simpleicons-7/A/Adguard')
include('simpleicons-7/A/Adidas')
include('simpleicons-7/A/Adobe')
include('simpleicons-7/A/Adobeacrobatreader')
include('simpleicons-7/A/Adobeaftereffects')
include('simpleicons-7/A/Adobeaudition')
include('simpleicons-7/A/Adobecreativecloud')
include('simpleicons-7/A/Adobedreamweaver')
include('simpleicons-7/A/Adobefonts')
include('simpleicons-7/A/Adobeillustrator')
include('simpleicons-7/A/Adobeindesign')
include('simpleicons-7/A/Adobelightroom')
include('simpleicons-7/A/Adobelightroomclassic')
include('simpleicons-7/A/Adobephotoshop')
include('simpleicons-7/A/Adobepremierepro')
include('simpleicons-7/A/Adobexd')
include('simpleicons-7/A/Adonisjs')
include('simpleicons-7/A/Adyen')
include('simpleicons-7/A/Aerlingus')
include('simpleicons-7/A/Aeroflot')
include('simpleicons-7/A/Aeromexico')
include('simpleicons-7/A/Aerospike')
include('simpleicons-7/A/Aew')
include('simpleicons-7/A/Affinity')
include('simpleicons-7/A/Affinitydesigner')
include('simpleicons-7/A/Affinityphoto')
include('simpleicons-7/A/Affinitypublisher')
include('simpleicons-7/A/Aframe')
include('simpleicons-7/A/Aib')
include('simpleicons-7/A/Aidungeon')
include('simpleicons-7/A/Aiohttp')
include('simpleicons-7/A/Aiqfome')
include('simpleicons-7/A/Airasia')
include('simpleicons-7/A/Airbnb')
include('simpleicons-7/A/Airbus')
include('simpleicons-7/A/Aircall')
include('simpleicons-7/A/Aircanada')
include('simpleicons-7/A/Airchina')
include('simpleicons-7/A/Airfrance')
include('simpleicons-7/A/Airplayaudio')
include('simpleicons-7/A/Airplayvideo')
include('simpleicons-7/A/Airtable')
include('simpleicons-7/A/Ajv')
include('simpleicons-7/A/Alacritty')
include('simpleicons-7/A/Albertheijn')
include('simpleicons-7/A/Aldinord')
include('simpleicons-7/A/Aldisud')
include('simpleicons-7/A/Alfaromeo')
include('simpleicons-7/A/Alfred')
include('simpleicons-7/A/Algolia')
include('simpleicons-7/A/Alibabacloud')
include('simpleicons-7/A/Alibabadotcom')
include('simpleicons-7/A/Aliexpress')
include('simpleicons-7/A/Alipay')
include('simpleicons-7/A/Alitalia')
include('simpleicons-7/A/Allegro')
include('simpleicons-7/A/Alliedmodders')
include('simpleicons-7/A/Allocine')
include('simpleicons-7/A/Alltrails')
include('simpleicons-7/A/Alpinedotjs')
include('simpleicons-7/A/Alpinelinux')
include('simpleicons-7/A/Altiumdesigner')
include('simpleicons-7/A/Amazon')
include('simpleicons-7/A/Amazonalexa')
include('simpleicons-7/A/Amazonapigateway')
include('simpleicons-7/A/Amazonaws')
include('simpleicons-7/A/Amazoncloudwatch')
include('simpleicons-7/A/Amazondynamodb')
include('simpleicons-7/A/Amazonec2')
include('simpleicons-7/A/Amazonecs')
include('simpleicons-7/A/Amazoneks')
include('simpleicons-7/A/Amazonfiretv')
include('simpleicons-7/A/Amazonlumberyard')
include('simpleicons-7/A/Amazonpay')
include('simpleicons-7/A/Amazonprime')
include('simpleicons-7/A/Amazonrds')
include('simpleicons-7/A/Amazons3')
include('simpleicons-7/A/Amazonsqs')
include('simpleicons-7/A/Amd')
include('simpleicons-7/A/Americanairlines')
include('simpleicons-7/A/Americanexpress')
include('simpleicons-7/A/Amg')
include('simpleicons-7/A/Amp')
include('simpleicons-7/A/Amul')
include('simpleicons-7/A/Ana')
include('simpleicons-7/A/Anaconda')
include('simpleicons-7/A/Analogue')
include('simpleicons-7/A/Anchor')
include('simpleicons-7/A/Andela')
include('simpleicons-7/A/Android')
include('simpleicons-7/A/Androidauto')
include('simpleicons-7/A/Androidstudio')
include('simpleicons-7/A/Angellist')
include('simpleicons-7/A/Angular')
include('simpleicons-7/A/Angularjs')
include('simpleicons-7/A/Angularuniversal')
include('simpleicons-7/A/Anilist')
include('simpleicons-7/A/Ansible')
include('simpleicons-7/A/Ansys')
include('simpleicons-7/A/Anta')
include('simpleicons-7/A/Antdesign')
include('simpleicons-7/A/Antena3')
include('simpleicons-7/A/Anydesk')
include('simpleicons-7/A/Aol')
include('simpleicons-7/A/Apache')
include('simpleicons-7/A/Apacheairflow')
include('simpleicons-7/A/Apacheant')
include('simpleicons-7/A/Apachecassandra')
include('simpleicons-7/A/Apachecloudstack')
include('simpleicons-7/A/Apachecordova')
include('simpleicons-7/A/Apachecouchdb')
include('simpleicons-7/A/Apachedruid')
include('simpleicons-7/A/Apacheecharts')
include('simpleicons-7/A/Apacheflink')
include('simpleicons-7/A/Apachegroovy')
include('simpleicons-7/A/Apachehadoop')
include('simpleicons-7/A/Apachehive')
include('simpleicons-7/A/Apachejmeter')
include('simpleicons-7/A/Apachekafka')
include('simpleicons-7/A/Apachekylin')
include('simpleicons-7/A/Apachemaven')
include('simpleicons-7/A/Apachenetbeanside')
include('simpleicons-7/A/Apacheopenoffice')
include('simpleicons-7/A/Apachepulsar')
include('simpleicons-7/A/Apacherocketmq')
include('simpleicons-7/A/Apachesolr')
include('simpleicons-7/A/Apachespark')
include('simpleicons-7/A/Apachetomcat')
include('simpleicons-7/A/Aparat')
include('simpleicons-7/A/Apollographql')
include('simpleicons-7/A/Apostrophe')
include('simpleicons-7/A/Appannie')
include('simpleicons-7/A/Appian')
include('simpleicons-7/A/Apple')
include('simpleicons-7/A/Applearcade')
include('simpleicons-7/A/Applemusic')
include('simpleicons-7/A/Applepay')
include('simpleicons-7/A/Applepodcasts')
include('simpleicons-7/A/Appletv')
include('simpleicons-7/A/Appsignal')
include('simpleicons-7/A/Appstore')
include('simpleicons-7/A/Appveyor')
include('simpleicons-7/A/Appwrite')
include('simpleicons-7/A/Aqua')
include('simpleicons-7/A/Aral')
include('simpleicons-7/A/Arangodb')
include('simpleicons-7/A/Archicad')
include('simpleicons-7/A/Archiveofourown')
include('simpleicons-7/A/Archlinux')
include('simpleicons-7/A/Ardour')
include('simpleicons-7/A/Arduino')
include('simpleicons-7/A/Argo')
include('simpleicons-7/A/Argos')
include('simpleicons-7/A/Arkecosystem')
include('simpleicons-7/A/Arlo')
include('simpleicons-7/A/Arm')
include('simpleicons-7/A/Artifacthub')
include('simpleicons-7/A/Artixlinux')
include('simpleicons-7/A/Artstation')
include('simpleicons-7/A/Arxiv')
include('simpleicons-7/A/Asana')
include('simpleicons-7/A/Asciidoctor')
include('simpleicons-7/A/Asciinema')
include('simpleicons-7/A/Asda')
include('simpleicons-7/A/Aseprite')
include('simpleicons-7/A/Askfm')
include('simpleicons-7/A/Askubuntu')
include('simpleicons-7/A/Assemblyscript')
include('simpleicons-7/A/Astonmartin')
include('simpleicons-7/A/Astro')
include('simpleicons-7/A/Asus')
include('simpleicons-7/A/Atandt')
include('simpleicons-7/A/Atari')
include('simpleicons-7/A/Atlassian')
include('simpleicons-7/A/Atom')
include('simpleicons-7/A/Auchan')
include('simpleicons-7/A/Audacity')
include('simpleicons-7/A/Audi')
include('simpleicons-7/A/Audible')
include('simpleicons-7/A/Audioboom')
include('simpleicons-7/A/Audiomack')
include('simpleicons-7/A/Audiotechnica')
include('simpleicons-7/A/Aurelia')
include('simpleicons-7/A/Auth0')
include('simpleicons-7/A/Authy')
include('simpleicons-7/A/Autodesk')
include('simpleicons-7/A/Autohotkey')
include('simpleicons-7/A/Automattic')
include('simpleicons-7/A/Autoprefixer')
include('simpleicons-7/A/Avast')
include('simpleicons-7/A/Awesomelists')
include('simpleicons-7/A/Awesomewm')
include('simpleicons-7/A/Awsamplify')
include('simpleicons-7/A/Awsfargate')
include('simpleicons-7/A/Awslambda')
include('simpleicons-7/A/Azureartifacts')
include('simpleicons-7/A/Azuredataexplorer')
include('simpleicons-7/A/Azuredevops')
include('simpleicons-7/A/Azurefunctions')
include('simpleicons-7/A/Azurepipelines')
include('simpleicons-7/B/Babel')
include('simpleicons-7/B/Backbonedotjs')
include('simpleicons-7/B/Badgr')
include('simpleicons-7/B/Badoo')
include('simpleicons-7/B/Baidu')
include('simpleicons-7/B/Bamboo')
include('simpleicons-7/B/Bandcamp')
include('simpleicons-7/B/Bandlab')
include('simpleicons-7/B/Bandrautomation')
include('simpleicons-7/B/Bandsintown')
include('simpleicons-7/B/Bankofamerica')
include('simpleicons-7/B/Barclays')
include('simpleicons-7/B/Baremetrics')
include('simpleicons-7/B/Basecamp')
include('simpleicons-7/B/Bata')
include('simpleicons-7/B/Bathasu')
include('simpleicons-7/B/Battledotnet')
include('simpleicons-7/B/Bbc')
include('simpleicons-7/B/Bbciplayer')
include('simpleicons-7/B/Beatport')
include('simpleicons-7/B/Beats')
include('simpleicons-7/B/Beatsbydre')
include('simpleicons-7/B/Behance')
include('simpleicons-7/B/Beijingsubway')
include('simpleicons-7/B/Bem')
include('simpleicons-7/B/Bentley')
include('simpleicons-7/B/Betfair')
include('simpleicons-7/B/Bigbasket')
include('simpleicons-7/B/Bigbluebutton')
include('simpleicons-7/B/Bigcartel')
include('simpleicons-7/B/Bigcommerce')
include('simpleicons-7/B/Bilibili')
include('simpleicons-7/B/Binance')
include('simpleicons-7/B/Biolink')
include('simpleicons-7/B/Bit')
include('simpleicons-7/B/Bitbucket')
include('simpleicons-7/B/Bitcoin')
include('simpleicons-7/B/Bitcoincash')
include('simpleicons-7/B/Bitcoinsv')
include('simpleicons-7/B/Bitdefender')
include('simpleicons-7/B/Bitly')
include('simpleicons-7/B/Bitrise')
include('simpleicons-7/B/Bitwarden')
include('simpleicons-7/B/Bitwig')
include('simpleicons-7/B/Blackberry')
include('simpleicons-7/B/Blazemeter')
include('simpleicons-7/B/Blazor')
include('simpleicons-7/B/Blender')
include('simpleicons-7/B/Blockchaindotcom')
include('simpleicons-7/B/Blogger')
include('simpleicons-7/B/Bloglovin')
include('simpleicons-7/B/Blueprint')
include('simpleicons-7/B/Bluetooth')
include('simpleicons-7/B/Bmcsoftware')
include('simpleicons-7/B/Bmw')
include('simpleicons-7/B/Boehringeringelheim')
include('simpleicons-7/B/Boeing')
include('simpleicons-7/B/Bookbub')
include('simpleicons-7/B/Bookmeter')
include('simpleicons-7/B/Bookstack')
include('simpleicons-7/B/Boost')
include('simpleicons-7/B/Boots')
include('simpleicons-7/B/Bootstrap')
include('simpleicons-7/B/Borgbackup')
include('simpleicons-7/B/Bosch')
include('simpleicons-7/B/Bose')
include('simpleicons-7/B/Boulanger')
include('simpleicons-7/B/Bower')
include('simpleicons-7/B/Box')
include('simpleicons-7/B/Boxysvg')
include('simpleicons-7/B/Brandfolder')
include('simpleicons-7/B/Brave')
include('simpleicons-7/B/Breaker')
include('simpleicons-7/B/Britishairways')
include('simpleicons-7/B/Broadcom')
include('simpleicons-7/B/Bt')
include('simpleicons-7/B/Buddy')
include('simpleicons-7/B/Budibase')
include('simpleicons-7/B/Buefy')
include('simpleicons-7/B/Buffer')
include('simpleicons-7/B/Bugatti')
include('simpleicons-7/B/Bugcrowd')
include('simpleicons-7/B/Bugsnag')
include('simpleicons-7/B/Buildkite')
include('simpleicons-7/B/Bukalapak')
include('simpleicons-7/B/Bulma')
include('simpleicons-7/B/Bunq')
include('simpleicons-7/B/Burgerking')
include('simpleicons-7/B/Buymeacoffee')
include('simpleicons-7/B/Buzzfeed')
include('simpleicons-7/B/Byjus')
include('simpleicons-7/B/Byte')
include('simpleicons-7/B/Bytedance')
include('simpleicons-7/C/C')
include('simpleicons-7/C/Cachet')
include('simpleicons-7/C/Caffeine')
include('simpleicons-7/C/Cairometro')
include('simpleicons-7/C/Cakephp')
include('simpleicons-7/C/Campaignmonitor')
include('simpleicons-7/C/Canonical')
include('simpleicons-7/C/Canva')
include('simpleicons-7/C/Capacitor')
include('simpleicons-7/C/Carrefour')
include('simpleicons-7/C/Carthrottle')
include('simpleicons-7/C/Carto')
include('simpleicons-7/C/Cashapp')
include('simpleicons-7/C/Castbox')
include('simpleicons-7/C/Castorama')
include('simpleicons-7/C/Castro')
include('simpleicons-7/C/Caterpillar')
include('simpleicons-7/C/Cbs')
include('simpleicons-7/C/Cdprojekt')
include('simpleicons-7/C/Celery')
include('simpleicons-7/C/Centos')
include('simpleicons-7/C/Ceph')
include('simpleicons-7/C/Cesium')
include('simpleicons-7/C/Chai')
include('simpleicons-7/C/Chainlink')
include('simpleicons-7/C/Chakraui')
include('simpleicons-7/C/Chartdotjs')
include('simpleicons-7/C/Chartmogul')
include('simpleicons-7/C/Chase')
include('simpleicons-7/C/Chatbot')
include('simpleicons-7/C/Checkio')
include('simpleicons-7/C/Checkmarx')
include('simpleicons-7/C/Chef')
include('simpleicons-7/C/Chemex')
include('simpleicons-7/C/Chevrolet')
include('simpleicons-7/C/Chinaeasternairlines')
include('simpleicons-7/C/Chinasouthernairlines')
include('simpleicons-7/C/Chocolatey')
include('simpleicons-7/C/Chromecast')
include('simpleicons-7/C/Chrysler')
include('simpleicons-7/C/Chupachups')
include('simpleicons-7/C/Cilium')
include('simpleicons-7/C/Cinema4D')
include('simpleicons-7/C/Circle')
include('simpleicons-7/C/Circleci')
include('simpleicons-7/C/Cirrusci')
include('simpleicons-7/C/Cisco')
include('simpleicons-7/C/Citrix')
include('simpleicons-7/C/Citroen')
include('simpleicons-7/C/Civicrm')
include('simpleicons-7/C/Civo')
include('simpleicons-7/C/Ckeditor4')
include('simpleicons-7/C/Claris')
include('simpleicons-7/C/Clickhouse')
include('simpleicons-7/C/Clickup')
include('simpleicons-7/C/Clion')
include('simpleicons-7/C/Cliqz')
include('simpleicons-7/C/Clockify')
include('simpleicons-7/C/Clojure')
include('simpleicons-7/C/Cloud66')
include('simpleicons-7/C/Cloudbees')
include('simpleicons-7/C/Cloudcannon')
include('simpleicons-7/C/Cloudera')
include('simpleicons-7/C/Cloudflare')
include('simpleicons-7/C/Cloudflarepages')
include('simpleicons-7/C/Cloudfoundry')
include('simpleicons-7/C/Cloudsmith')
include('simpleicons-7/C/Cloudways')
include('simpleicons-7/C/Clubhouse')
include('simpleicons-7/C/Clyp')
include('simpleicons-7/C/Cmake')
include('simpleicons-7/C/Cncf')
include('simpleicons-7/C/Cnn')
include('simpleicons-7/C/Cockpit')
include('simpleicons-7/C/Cockroachlabs')
include('simpleicons-7/C/Cocoapods')
include('simpleicons-7/C/Cocos')
include('simpleicons-7/C/Coda')
include('simpleicons-7/C/Codacy')
include('simpleicons-7/C/Codeberg')
include('simpleicons-7/C/Codecademy')
include('simpleicons-7/C/Codeceptjs')
include('simpleicons-7/C/Codechef')
include('simpleicons-7/C/Codeclimate')
include('simpleicons-7/C/Codecov')
include('simpleicons-7/C/Codefactor')
include('simpleicons-7/C/Codeforces')
include('simpleicons-7/C/Codeigniter')
include('simpleicons-7/C/Codemagic')
include('simpleicons-7/C/Codemirror')
include('simpleicons-7/C/Codenewbie')
include('simpleicons-7/C/Codepen')
include('simpleicons-7/C/Codeproject')
include('simpleicons-7/C/Codereview')
include('simpleicons-7/C/Codersrank')
include('simpleicons-7/C/Coderwall')
include('simpleicons-7/C/Codesandbox')
include('simpleicons-7/C/Codeship')
include('simpleicons-7/C/Codewars')
include('simpleicons-7/C/Codingame')
include('simpleicons-7/C/Codingninjas')
include('simpleicons-7/C/Codio')
include('simpleicons-7/C/Coffeescript')
include('simpleicons-7/C/Cognizant')
include('simpleicons-7/C/Coil')
include('simpleicons-7/C/Coinbase')
include('simpleicons-7/C/Coinmarketcap')
include('simpleicons-7/C/Commerzbank')
include('simpleicons-7/C/Commitlint')
include('simpleicons-7/C/Commonworkflowlanguage')
include('simpleicons-7/C/Composer')
include('simpleicons-7/C/Comsol')
include('simpleicons-7/C/Conan')
include('simpleicons-7/C/Concourse')
include('simpleicons-7/C/Condaforge')
include('simpleicons-7/C/Conekta')
include('simpleicons-7/C/Confluence')
include('simpleicons-7/C/Construct3')
include('simpleicons-7/C/Consul')
include('simpleicons-7/C/Contactlesspayment')
include('simpleicons-7/C/Containerd')
include('simpleicons-7/C/Contentful')
include('simpleicons-7/C/Conventionalcommits')
include('simpleicons-7/C/Convertio')
include('simpleicons-7/C/Cookiecutter')
include('simpleicons-7/C/Coop')
include('simpleicons-7/C/Cora')
include('simpleicons-7/C/Coronaengine')
include('simpleicons-7/C/Coronarenderer')
include('simpleicons-7/C/Corsair')
include('simpleicons-7/C/Couchbase')
include('simpleicons-7/C/Counterstrike')
include('simpleicons-7/C/Countingworkspro')
include('simpleicons-7/C/Coursera')
include('simpleicons-7/C/Coveralls')
include('simpleicons-7/C/Cpanel')
include('simpleicons-7/C/Cplusplus')
include('simpleicons-7/C/Craftcms')
include('simpleicons-7/C/Cratedb')
include('simpleicons-7/C/Createreactapp')
include('simpleicons-7/C/Creativecommons')
include('simpleicons-7/C/Credly')
include('simpleicons-7/C/Crehana')
include('simpleicons-7/C/Crowdin')
include('simpleicons-7/C/Crowdsource')
include('simpleicons-7/C/Crunchbase')
include('simpleicons-7/C/Crunchyroll')
include('simpleicons-7/C/Cryengine')
include('simpleicons-7/C/Crystal')
include('simpleicons-7/C/Csharp')
include('simpleicons-7/C/Css3')
include('simpleicons-7/C/Cssmodules')
include('simpleicons-7/C/Csswizardry')
include('simpleicons-7/C/Cucumber')
include('simpleicons-7/C/Curl')
include('simpleicons-7/C/Curseforge')
include('simpleicons-7/C/Cycling74')
include('simpleicons-7/C/Cypress')
include('simpleicons-7/C/Cytoscapedotjs')
include('simpleicons-7/D/D3Dotjs')
include('simpleicons-7/D/Dacia')
include('simpleicons-7/D/Daf')
include('simpleicons-7/D/Dailymotion')
include('simpleicons-7/D/Daimler')
include('simpleicons-7/D/Darkreader')
include('simpleicons-7/D/Dart')
include('simpleicons-7/D/Darty')
include('simpleicons-7/D/Daserste')
include('simpleicons-7/D/Dash')
include('simpleicons-7/D/Dashlane')
include('simpleicons-7/D/Dask')
include('simpleicons-7/D/Dassaultsystemes')
include('simpleicons-7/D/Databricks')
include('simpleicons-7/D/Datacamp')
include('simpleicons-7/D/Datadog')
include('simpleicons-7/D/Datadotai')
include('simpleicons-7/D/Datagrip')
include('simpleicons-7/D/Dataiku')
include('simpleicons-7/D/Datastax')
include('simpleicons-7/D/Dataversioncontrol')
include('simpleicons-7/D/Datocms')
include('simpleicons-7/D/Datto')
include('simpleicons-7/D/Dazn')
include('simpleicons-7/D/Dblp')
include('simpleicons-7/D/Dbt')
include('simpleicons-7/D/Dcentertainment')
include('simpleicons-7/D/Debian')
include('simpleicons-7/D/Dedge')
include('simpleicons-7/D/Deepin')
include('simpleicons-7/D/Deepnote')
include('simpleicons-7/D/Deezer')
include('simpleicons-7/D/Delicious')
include('simpleicons-7/D/Deliveroo')
include('simpleicons-7/D/Dell')
include('simpleicons-7/D/Delonghi')
include('simpleicons-7/D/Delphi')
include('simpleicons-7/D/Delta')
include('simpleicons-7/D/Deno')
include('simpleicons-7/D/Dependabot')
include('simpleicons-7/D/Derspiegel')
include('simpleicons-7/D/Designernews')
include('simpleicons-7/D/Deutschebahn')
include('simpleicons-7/D/Deutschebank')
include('simpleicons-7/D/Devdotto')
include('simpleicons-7/D/Devexpress')
include('simpleicons-7/D/Deviantart')
include('simpleicons-7/D/Devpost')
include('simpleicons-7/D/Devrant')
include('simpleicons-7/D/Dgraph')
include('simpleicons-7/D/Dhl')
include('simpleicons-7/D/Diagramsdotnet')
include('simpleicons-7/D/Dialogflow')
include('simpleicons-7/D/Diaspora')
include('simpleicons-7/D/Digg')
include('simpleicons-7/D/Digikeyelectronics')
include('simpleicons-7/D/Digitalocean')
include('simpleicons-7/D/Dior')
include('simpleicons-7/D/Directus')
include('simpleicons-7/D/Discogs')
include('simpleicons-7/D/Discord')
include('simpleicons-7/D/Discourse')
include('simpleicons-7/D/Discover')
include('simpleicons-7/D/Disqus')
include('simpleicons-7/D/Disroot')
include('simpleicons-7/D/Django')
include('simpleicons-7/D/Dlib')
include('simpleicons-7/D/Dlna')
include('simpleicons-7/D/Dm')
include('simpleicons-7/D/Docker')
include('simpleicons-7/D/Docsdotrs')
include('simpleicons-7/D/Docusign')
include('simpleicons-7/D/Dogecoin')
include('simpleicons-7/D/Dolby')
include('simpleicons-7/D/Doordash')
include('simpleicons-7/D/Dotnet')
include('simpleicons-7/D/Douban')
include('simpleicons-7/D/Doubanread')
include('simpleicons-7/D/Dpd')
include('simpleicons-7/D/Dragonframe')
include('simpleicons-7/D/Draugiemdotlv')
include('simpleicons-7/D/Dribbble')
include('simpleicons-7/D/Drone')
include('simpleicons-7/D/Drooble')
include('simpleicons-7/D/Dropbox')
include('simpleicons-7/D/Drupal')
include('simpleicons-7/D/Dsautomobiles')
include('simpleicons-7/D/Dtube')
include('simpleicons-7/D/Duckdb')
include('simpleicons-7/D/Duckduckgo')
include('simpleicons-7/D/Dungeonsanddragons')
include('simpleicons-7/D/Dunked')
include('simpleicons-7/D/Duolingo')
include('simpleicons-7/D/Dvc')
include('simpleicons-7/D/Dwavesystems')
include('simpleicons-7/D/Dwm')
include('simpleicons-7/D/Dynamics365')
include('simpleicons-7/D/Dynatrace')
include('simpleicons-7/E/E')
include('simpleicons-7/E/Ea')
include('simpleicons-7/E/Eagle')
include('simpleicons-7/E/Easyjet')
include('simpleicons-7/E/Ebay')
include('simpleicons-7/E/Eclipseche')
include('simpleicons-7/E/Eclipseide')
include('simpleicons-7/E/Eclipsejetty')
include('simpleicons-7/E/Eclipsemosquitto')
include('simpleicons-7/E/Eclipsevertdotx')
include('simpleicons-7/E/Edeka')
include('simpleicons-7/E/Editorconfig')
include('simpleicons-7/E/Edotleclerc')
include('simpleicons-7/E/Edx')
include('simpleicons-7/E/Egghead')
include('simpleicons-7/E/Egnyte')
include('simpleicons-7/E/Eightsleep')
include('simpleicons-7/E/Elastic')
include('simpleicons-7/E/Elasticcloud')
include('simpleicons-7/E/Elasticsearch')
include('simpleicons-7/E/Elasticstack')
include('simpleicons-7/E/Electron')
include('simpleicons-7/E/Element')
include('simpleicons-7/E/Elementary')
include('simpleicons-7/E/Eleventy')
include('simpleicons-7/E/Elixir')
include('simpleicons-7/E/Eljueves')
include('simpleicons-7/E/Ello')
include('simpleicons-7/E/Elm')
include('simpleicons-7/E/Elsevier')
include('simpleicons-7/E/Embarcadero')
include('simpleicons-7/E/Emberdotjs')
include('simpleicons-7/E/Emby')
include('simpleicons-7/E/Emirates')
include('simpleicons-7/E/Emlakjet')
include('simpleicons-7/E/Empirekred')
include('simpleicons-7/E/Enpass')
include('simpleicons-7/E/Enterprisedb')
include('simpleicons-7/E/Envato')
include('simpleicons-7/E/Epel')
include('simpleicons-7/E/Epicgames')
include('simpleicons-7/E/Epson')
include('simpleicons-7/E/Equinixmetal')
include('simpleicons-7/E/Erlang')
include('simpleicons-7/E/Esbuild')
include('simpleicons-7/E/Esea')
include('simpleicons-7/E/Eslgaming')
include('simpleicons-7/E/Eslint')
include('simpleicons-7/E/Esphome')
include('simpleicons-7/E/Espressif')
include('simpleicons-7/E/Etcd')
include('simpleicons-7/E/Ethereum')
include('simpleicons-7/E/Ethiopianairlines')
include('simpleicons-7/E/Etihadairways')
include('simpleicons-7/E/Etsy')
include('simpleicons-7/E/Eventbrite')
include('simpleicons-7/E/Eventstore')
include('simpleicons-7/E/Evernote')
include('simpleicons-7/E/Exercism')
include('simpleicons-7/E/Exordo')
include('simpleicons-7/E/Exoscale')
include('simpleicons-7/E/Expensify')
include('simpleicons-7/E/Expertsexchange')
include('simpleicons-7/E/Expo')
include('simpleicons-7/E/Express')
include('simpleicons-7/E/Expressvpn')
include('simpleicons-7/E/Eyeem')
include('simpleicons-7/F/Facebook')
include('simpleicons-7/F/Facebookgaming')
include('simpleicons-7/F/Facebooklive')
include('simpleicons-7/F/Faceit')
include('simpleicons-7/F/Facepunch')
include('simpleicons-7/F/Falcon')
include('simpleicons-7/F/Fampay')
include('simpleicons-7/F/Fandango')
include('simpleicons-7/F/Fandom')
include('simpleicons-7/F/Farfetch')
include('simpleicons-7/F/Fastapi')
include('simpleicons-7/F/Fastify')
include('simpleicons-7/F/Fastlane')
include('simpleicons-7/F/Fastly')
include('simpleicons-7/F/Fathom')
include('simpleicons-7/F/Fauna')
include('simpleicons-7/F/Favro')
include('simpleicons-7/F/Fdroid')
include('simpleicons-7/F/Feathub')
include('simpleicons-7/F/Fedex')
include('simpleicons-7/F/Fedora')
include('simpleicons-7/F/Feedly')
include('simpleicons-7/F/Ferrari')
include('simpleicons-7/F/Ferrarinv')
include('simpleicons-7/F/Ffmpeg')
include('simpleicons-7/F/Fiat')
include('simpleicons-7/F/Fidoalliance')
include('simpleicons-7/F/Fifa')
include('simpleicons-7/F/Figma')
include('simpleicons-7/F/Figshare')
include('simpleicons-7/F/Fila')
include('simpleicons-7/F/Files')
include('simpleicons-7/F/Filezilla')
include('simpleicons-7/F/Fing')
include('simpleicons-7/F/Firebase')
include('simpleicons-7/F/Firefox')
include('simpleicons-7/F/Firefoxbrowser')
include('simpleicons-7/F/First')
include('simpleicons-7/F/Fitbit')
include('simpleicons-7/F/Fite')
include('simpleicons-7/F/Fivem')
include('simpleicons-7/F/Fiverr')
include('simpleicons-7/F/Flask')
include('simpleicons-7/F/Flat')
include('simpleicons-7/F/Flathub')
include('simpleicons-7/F/Flatpak')
include('simpleicons-7/F/Flattr')
include('simpleicons-7/F/Flickr')
include('simpleicons-7/F/Flipboard')
include('simpleicons-7/F/Flipkart')
include('simpleicons-7/F/Floatplane')
include('simpleicons-7/F/Flood')
include('simpleicons-7/F/Fluentbit')
include('simpleicons-7/F/Fluentd')
include('simpleicons-7/F/Flutter')
include('simpleicons-7/F/Flyway')
include('simpleicons-7/F/Fmod')
include('simpleicons-7/F/Fnac')
include('simpleicons-7/F/Folium')
include('simpleicons-7/F/Fonoma')
include('simpleicons-7/F/Fontawesome')
include('simpleicons-7/F/Fontbase')
include('simpleicons-7/F/Foodpanda')
include('simpleicons-7/F/Ford')
include('simpleicons-7/F/Forestry')
include('simpleicons-7/F/Formstack')
include('simpleicons-7/F/Fortinet')
include('simpleicons-7/F/Fortran')
include('simpleicons-7/F/Fossa')
include('simpleicons-7/F/Fossilscm')
include('simpleicons-7/F/Foursquare')
include('simpleicons-7/F/Foursquarecityguide')
include('simpleicons-7/F/Foxtel')
include('simpleicons-7/F/Fozzy')
include('simpleicons-7/F/Framer')
include('simpleicons-7/F/Framework7')
include('simpleicons-7/F/Franprix')
include('simpleicons-7/F/Fraunhofergesellschaft')
include('simpleicons-7/F/Freebsd')
include('simpleicons-7/F/Freecodecamp')
include('simpleicons-7/F/Freedesktopdotorg')
include('simpleicons-7/F/Freelancer')
include('simpleicons-7/F/Freenas')
include('simpleicons-7/F/Frontendmentor')
include('simpleicons-7/F/Fsecure')
include('simpleicons-7/F/Fujifilm')
include('simpleicons-7/F/Fujitsu')
include('simpleicons-7/F/Funimation')
include('simpleicons-7/F/Furaffinity')
include('simpleicons-7/F/Furrynetwork')
include('simpleicons-7/F/Futurelearn')
include('simpleicons-7/G/G2')
include('simpleicons-7/G/G2A')
include('simpleicons-7/G/Gameandwatch')
include('simpleicons-7/G/Gamejolt')
include('simpleicons-7/G/Garmin')
include('simpleicons-7/G/Gatling')
include('simpleicons-7/G/Gatsby')
include('simpleicons-7/G/Geant')
include('simpleicons-7/G/Geeksforgeeks')
include('simpleicons-7/G/Generalelectric')
include('simpleicons-7/G/Generalmotors')
include('simpleicons-7/G/Genius')
include('simpleicons-7/G/Gentoo')
include('simpleicons-7/G/Geocaching')
include('simpleicons-7/G/Gerrit')
include('simpleicons-7/G/Ghost')
include('simpleicons-7/G/Ghostery')
include('simpleicons-7/G/Gimp')
include('simpleicons-7/G/Giphy')
include('simpleicons-7/G/Git')
include('simpleicons-7/G/Gitbook')
include('simpleicons-7/G/Gitea')
include('simpleicons-7/G/Gitee')
include('simpleicons-7/G/Gitextensions')
include('simpleicons-7/G/Github')
include('simpleicons-7/G/Githubactions')
include('simpleicons-7/G/Githubpages')
include('simpleicons-7/G/Githubsponsors')
include('simpleicons-7/G/Gitignoredotio')
include('simpleicons-7/G/Gitkraken')
include('simpleicons-7/G/Gitlab')
include('simpleicons-7/G/Gitlfs')
include('simpleicons-7/G/Gitpod')
include('simpleicons-7/G/Gitter')
include('simpleicons-7/G/Glassdoor')
include('simpleicons-7/G/Glitch')
include('simpleicons-7/G/Globus')
include('simpleicons-7/G/Gmail')
include('simpleicons-7/G/Gnome')
include('simpleicons-7/G/Gnometerminal')
include('simpleicons-7/G/Gnu')
include('simpleicons-7/G/Gnubash')
include('simpleicons-7/G/Gnuemacs')
include('simpleicons-7/G/Gnuicecat')
include('simpleicons-7/G/Gnuprivacyguard')
include('simpleicons-7/G/Gnusocial')
include('simpleicons-7/G/Go')
include('simpleicons-7/G/Gocd')
include('simpleicons-7/G/Godaddy')
include('simpleicons-7/G/Godotengine')
include('simpleicons-7/G/Gofundme')
include('simpleicons-7/G/Gogdotcom')
include('simpleicons-7/G/Goland')
include('simpleicons-7/G/Goldenline')
include('simpleicons-7/G/Goodreads')
include('simpleicons-7/G/Google')
include('simpleicons-7/G/Googleadmob')
include('simpleicons-7/G/Googleads')
include('simpleicons-7/G/Googleadsense')
include('simpleicons-7/G/Googleanalytics')
include('simpleicons-7/G/Googleassistant')
include('simpleicons-7/G/Googlecalendar')
include('simpleicons-7/G/Googlecardboard')
include('simpleicons-7/G/Googlechat')
include('simpleicons-7/G/Googlechrome')
include('simpleicons-7/G/Googleclassroom')
include('simpleicons-7/G/Googlecloud')
include('simpleicons-7/G/Googlecolab')
include('simpleicons-7/G/Googledomains')
include('simpleicons-7/G/Googledrive')
include('simpleicons-7/G/Googleearth')
include('simpleicons-7/G/Googlefit')
include('simpleicons-7/G/Googlefonts')
include('simpleicons-7/G/Googlehangouts')
include('simpleicons-7/G/Googlekeep')
include('simpleicons-7/G/Googlelens')
include('simpleicons-7/G/Googlemaps')
include('simpleicons-7/G/Googlemarketingplatform')
include('simpleicons-7/G/Googlemeet')
include('simpleicons-7/G/Googlemessages')
include('simpleicons-7/G/Googlemybusiness')
include('simpleicons-7/G/Googlenearby')
include('simpleicons-7/G/Googlenews')
include('simpleicons-7/G/Googleoptimize')
include('simpleicons-7/G/Googlepay')
include('simpleicons-7/G/Googlephotos')
include('simpleicons-7/G/Googleplay')
include('simpleicons-7/G/Googlepodcasts')
include('simpleicons-7/G/Googlescholar')
include('simpleicons-7/G/Googlesearchconsole')
include('simpleicons-7/G/Googlesheets')
include('simpleicons-7/G/Googlestreetview')
include('simpleicons-7/G/Googletagmanager')
include('simpleicons-7/G/Googletranslate')
include('simpleicons-7/G/Gotomeeting')
include('simpleicons-7/G/Grab')
include('simpleicons-7/G/Gradle')
include('simpleicons-7/G/Grafana')
include('simpleicons-7/G/Grammarly')
include('simpleicons-7/G/Grandfrais')
include('simpleicons-7/G/Graphql')
include('simpleicons-7/G/Grav')
include('simpleicons-7/G/Gravatar')
include('simpleicons-7/G/Graylog')
include('simpleicons-7/G/Greensock')
include('simpleicons-7/G/Griddotai')
include('simpleicons-7/G/Gridsome')
include('simpleicons-7/G/Groupme')
include('simpleicons-7/G/Groupon')
include('simpleicons-7/G/Grubhub')
include('simpleicons-7/G/Grunt')
include('simpleicons-7/G/Gtk')
include('simpleicons-7/G/Guangzhoumetro')
include('simpleicons-7/G/Guilded')
include('simpleicons-7/G/Gulp')
include('simpleicons-7/G/Gumroad')
include('simpleicons-7/G/Gumtree')
include('simpleicons-7/G/Gunicorn')
include('simpleicons-7/G/Gurobi')
include('simpleicons-7/G/Gutenberg')
include('simpleicons-7/H/Habr')
include('simpleicons-7/H/Hackaday')
include('simpleicons-7/H/Hackclub')
include('simpleicons-7/H/Hackerearth')
include('simpleicons-7/H/Hackernoon')
include('simpleicons-7/H/Hackerone')
include('simpleicons-7/H/Hackerrank')
include('simpleicons-7/H/Hackster')
include('simpleicons-7/H/Hackthebox')
include('simpleicons-7/H/Handlebarsdotjs')
include('simpleicons-7/H/HandshakeProtocol')
include('simpleicons-7/H/Handshake')
include('simpleicons-7/H/Happycow')
include('simpleicons-7/H/Harbor')
include('simpleicons-7/H/Hashnode')
include('simpleicons-7/H/Haskell')
include('simpleicons-7/H/Hasura')
include('simpleicons-7/H/Hatenabookmark')
include('simpleicons-7/H/Haveibeenpwned')
include('simpleicons-7/H/Haxe')
include('simpleicons-7/H/Hbo')
include('simpleicons-7/H/Hcl')
include('simpleicons-7/H/Headlessui')
include('simpleicons-7/H/Headspace')
include('simpleicons-7/H/Hellofresh')
include('simpleicons-7/H/Hellyhansen')
include('simpleicons-7/H/Helm')
include('simpleicons-7/H/Helpdesk')
include('simpleicons-7/H/Helpscout')
include('simpleicons-7/H/Here')
include('simpleicons-7/H/Heroku')
include('simpleicons-7/H/Hetzner')
include('simpleicons-7/H/Hexo')
include('simpleicons-7/H/Hey')
include('simpleicons-7/H/Hibernate')
include('simpleicons-7/H/Hibob')
include('simpleicons-7/H/Hilton')
include('simpleicons-7/H/Hitachi')
include('simpleicons-7/H/HiveBlockchain')
include('simpleicons-7/H/Hive')
include('simpleicons-7/H/Homeadvisor')
include('simpleicons-7/H/Homeassistant')
include('simpleicons-7/H/Homeassistantcommunitystore')
include('simpleicons-7/H/Homebrew')
include('simpleicons-7/H/Homebridge')
include('simpleicons-7/H/Homify')
include('simpleicons-7/H/Honda')
include('simpleicons-7/H/Hootsuite')
include('simpleicons-7/H/Hoppscotch')
include('simpleicons-7/H/Hotelsdotcom')
include('simpleicons-7/H/Hotjar')
include('simpleicons-7/H/Houdini')
include('simpleicons-7/H/Houzz')
include('simpleicons-7/H/Hp')
include('simpleicons-7/H/Html5')
include('simpleicons-7/H/Htmlacademy')
include('simpleicons-7/H/Httpie')
include('simpleicons-7/H/Huawei')
include('simpleicons-7/H/Hubspot')
include('simpleicons-7/H/Hugo')
include('simpleicons-7/H/Hulu')
include('simpleicons-7/H/Humblebundle')
include('simpleicons-7/H/Hungryjacks')
include('simpleicons-7/H/Hurriyetemlak')
include('simpleicons-7/H/Husqvarna')
include('simpleicons-7/H/Hyper')
include('simpleicons-7/H/Hyperledger')
include('simpleicons-7/H/Hypothesis')
include('simpleicons-7/H/Hyundai')
include('simpleicons-7/I/I18Next')
include('simpleicons-7/I/Iata')
include('simpleicons-7/I/Ibeacon')
include('simpleicons-7/I/Ibm')
include('simpleicons-7/I/Ibmcloud')
include('simpleicons-7/I/Ibmwatson')
include('simpleicons-7/I/Iceland')
include('simpleicons-7/I/Icinga')
include('simpleicons-7/I/Icloud')
include('simpleicons-7/I/Icomoon')
include('simpleicons-7/I/Icon')
include('simpleicons-7/I/Iconfinder')
include('simpleicons-7/I/Iconify')
include('simpleicons-7/I/Iconjar')
include('simpleicons-7/I/Icons8')
include('simpleicons-7/I/Icq')
include('simpleicons-7/I/Ieee')
include('simpleicons-7/I/Ifixit')
include('simpleicons-7/I/Ifood')
include('simpleicons-7/I/Ifttt')
include('simpleicons-7/I/Iheartradio')
include('simpleicons-7/I/Ikea')
include('simpleicons-7/I/Imagej')
include('simpleicons-7/I/Imdb')
include('simpleicons-7/I/Imgur')
include('simpleicons-7/I/Immer')
include('simpleicons-7/I/Imou')
include('simpleicons-7/I/Indeed')
include('simpleicons-7/I/Infiniti')
include('simpleicons-7/I/Influxdb')
include('simpleicons-7/I/Informatica')
include('simpleicons-7/I/Infosys')
include('simpleicons-7/I/Ingress')
include('simpleicons-7/I/Inkscape')
include('simpleicons-7/I/Insomnia')
include('simpleicons-7/I/Instacart')
include('simpleicons-7/I/Instagram')
include('simpleicons-7/I/Instapaper')
include('simpleicons-7/I/Instatus')
include('simpleicons-7/I/Instructables')
include('simpleicons-7/I/Integromat')
include('simpleicons-7/I/Intel')
include('simpleicons-7/I/Intellijidea')
include('simpleicons-7/I/Interactjs')
include('simpleicons-7/I/Intercom')
include('simpleicons-7/I/Intermarche')
include('simpleicons-7/I/Internetarchive')
include('simpleicons-7/I/Internetexplorer')
include('simpleicons-7/I/Intigriti')
include('simpleicons-7/I/Invision')
include('simpleicons-7/I/Invoiceninja')
include('simpleicons-7/I/Iobroker')
include('simpleicons-7/I/Ionic')
include('simpleicons-7/I/Ionos')
include('simpleicons-7/I/Ios')
include('simpleicons-7/I/Iota')
include('simpleicons-7/I/Ipfs')
include('simpleicons-7/I/Issuu')
include('simpleicons-7/I/Istio')
include('simpleicons-7/I/Itchdotio')
include('simpleicons-7/I/Iterm2')
include('simpleicons-7/I/Itunes')
include('simpleicons-7/I/Iveco')
include('simpleicons-7/J/Jabber')
include('simpleicons-7/J/Jaguar')
include('simpleicons-7/J/Jamboard')
include('simpleicons-7/J/Jameson')
include('simpleicons-7/J/Jamstack')
include('simpleicons-7/J/Jasmine')
include('simpleicons-7/J/Javascript')
include('simpleicons-7/J/Jbl')
include('simpleicons-7/J/Jcb')
include('simpleicons-7/J/Jeep')
include('simpleicons-7/J/Jekyll')
include('simpleicons-7/J/Jellyfin')
include('simpleicons-7/J/Jenkins')
include('simpleicons-7/J/Jenkinsx')
include('simpleicons-7/J/Jest')
include('simpleicons-7/J/Jet')
include('simpleicons-7/J/Jetbrains')
include('simpleicons-7/J/Jetpackcompose')
include('simpleicons-7/J/Jfrog')
include('simpleicons-7/J/Jfrogbintray')
include('simpleicons-7/J/Jinja')
include('simpleicons-7/J/Jira')
include('simpleicons-7/J/Jirasoftware')
include('simpleicons-7/J/Jitsi')
include('simpleicons-7/J/Johndeere')
include('simpleicons-7/J/Joomla')
include('simpleicons-7/J/Joplin')
include('simpleicons-7/J/Jordan')
include('simpleicons-7/J/Jpeg')
include('simpleicons-7/J/Jquery')
include('simpleicons-7/J/Jrgroup')
include('simpleicons-7/J/Jsdelivr')
include('simpleicons-7/J/Jsfiddle')
include('simpleicons-7/J/Json')
include('simpleicons-7/J/Jsonwebtokens')
include('simpleicons-7/J/Jss')
include('simpleicons-7/J/Julia')
include('simpleicons-7/J/Junipernetworks')
include('simpleicons-7/J/Junit5')
include('simpleicons-7/J/Jupyter')
include('simpleicons-7/J/Justeat')
include('simpleicons-7/J/Justgiving')
include('simpleicons-7/K/K3S')
include('simpleicons-7/K/K6')
include('simpleicons-7/K/Kaggle')
include('simpleicons-7/K/Kahoot')
include('simpleicons-7/K/Kaios')
include('simpleicons-7/K/Kakao')
include('simpleicons-7/K/Kakaotalk')
include('simpleicons-7/K/Kalilinux')
include('simpleicons-7/K/Kaniko')
include('simpleicons-7/K/Karlsruherverkehrsverbund')
include('simpleicons-7/K/Kasasmart')
include('simpleicons-7/K/Kashflow')
include('simpleicons-7/K/Kaspersky')
include('simpleicons-7/K/Katacoda')
include('simpleicons-7/K/Katana')
include('simpleicons-7/K/Kaufland')
include('simpleicons-7/K/Kde')
include('simpleicons-7/K/Kdenlive')
include('simpleicons-7/K/Keepachangelog')
include('simpleicons-7/K/Keepassxc')
include('simpleicons-7/K/Kentico')
include('simpleicons-7/K/Keras')
include('simpleicons-7/K/Keybase')
include('simpleicons-7/K/Keycdn')
include('simpleicons-7/K/Kfc')
include('simpleicons-7/K/Khanacademy')
include('simpleicons-7/K/Khronosgroup')
include('simpleicons-7/K/Kia')
include('simpleicons-7/K/Kibana')
include('simpleicons-7/K/Kicad')
include('simpleicons-7/K/Kickstarter')
include('simpleicons-7/K/Kik')
include('simpleicons-7/K/Kingstontechnology')
include('simpleicons-7/K/Kinopoisk')
include('simpleicons-7/K/Kirby')
include('simpleicons-7/K/Kitsu')
include('simpleicons-7/K/Klarna')
include('simpleicons-7/K/Klm')
include('simpleicons-7/K/Klook')
include('simpleicons-7/K/Knative')
include('simpleicons-7/K/Knowledgebase')
include('simpleicons-7/K/Known')
include('simpleicons-7/K/Koa')
include('simpleicons-7/K/Koc')
include('simpleicons-7/K/Kodi')
include('simpleicons-7/K/Kofax')
include('simpleicons-7/K/Kofi')
include('simpleicons-7/K/Komoot')
include('simpleicons-7/K/Konami')
include('simpleicons-7/K/Kong')
include('simpleicons-7/K/Kongregate')
include('simpleicons-7/K/Konva')
include('simpleicons-7/K/Kotlin')
include('simpleicons-7/K/Koyeb')
include('simpleicons-7/K/Krita')
include('simpleicons-7/K/Ktm')
include('simpleicons-7/K/Kuaishou')
include('simpleicons-7/K/Kubernetes')
include('simpleicons-7/K/Kubuntu')
include('simpleicons-7/K/Kuma')
include('simpleicons-7/K/Kyocera')
include('simpleicons-7/L/Labview')
include('simpleicons-7/L/Lada')
include('simpleicons-7/L/Lamborghini')
include('simpleicons-7/L/Landrover')
include('simpleicons-7/L/Lapce')
include('simpleicons-7/L/Laragon')
include('simpleicons-7/L/Laravel')
include('simpleicons-7/L/Laravelhorizon')
include('simpleicons-7/L/Laravelnova')
include('simpleicons-7/L/Lastdotfm')
include('simpleicons-7/L/Lastpass')
include('simpleicons-7/L/Latex')
include('simpleicons-7/L/Launchpad')
include('simpleicons-7/L/Lazarus')
include('simpleicons-7/L/Lbry')
include('simpleicons-7/L/Leaderprice')
include('simpleicons-7/L/Leaflet')
include('simpleicons-7/L/Leanpub')
include('simpleicons-7/L/Leetcode')
include('simpleicons-7/L/Lemmy')
include('simpleicons-7/L/Lenovo')
include('simpleicons-7/L/Lens')
include('simpleicons-7/L/Lerna')
include('simpleicons-7/L/Leroymerlin')
include('simpleicons-7/L/Less')
include('simpleicons-7/L/Letsencrypt')
include('simpleicons-7/L/Letterboxd')
include('simpleicons-7/L/Levelsdotfyi')
include('simpleicons-7/L/Lg')
include('simpleicons-7/L/Lgtm')
include('simpleicons-7/L/Liberapay')
include('simpleicons-7/L/Librariesdotio')
include('simpleicons-7/L/Librarything')
include('simpleicons-7/L/Libreoffice')
include('simpleicons-7/L/Libuv')
include('simpleicons-7/L/Lichess')
include('simpleicons-7/L/Lidl')
include('simpleicons-7/L/Lifx')
include('simpleicons-7/L/Lighthouse')
include('simpleicons-7/L/Line')
include('simpleicons-7/L/Lineageos')
include('simpleicons-7/L/Linear')
include('simpleicons-7/L/Linkedin')
include('simpleicons-7/L/Linkerd')
include('simpleicons-7/L/Linkfire')
include('simpleicons-7/L/Linktree')
include('simpleicons-7/L/Linode')
include('simpleicons-7/L/Linux')
include('simpleicons-7/L/Linuxcontainers')
include('simpleicons-7/L/Linuxfoundation')
include('simpleicons-7/L/Linuxmint')
include('simpleicons-7/L/Lionair')
include('simpleicons-7/L/Liquibase')
include('simpleicons-7/L/Lit')
include('simpleicons-7/L/Litecoin')
include('simpleicons-7/L/Livechat')
include('simpleicons-7/L/Livejournal')
include('simpleicons-7/L/Livewire')
include('simpleicons-7/L/Llvm')
include('simpleicons-7/L/Lmms')
include('simpleicons-7/L/Lodash')
include('simpleicons-7/L/Logitech')
include('simpleicons-7/L/Logmein')
include('simpleicons-7/L/Logstash')
include('simpleicons-7/L/Looker')
include('simpleicons-7/L/Loom')
include('simpleicons-7/L/Loop')
include('simpleicons-7/L/Loopback')
include('simpleicons-7/L/Lospec')
include('simpleicons-7/L/Lotpolishairlines')
include('simpleicons-7/L/Lua')
include('simpleicons-7/L/Lubuntu')
include('simpleicons-7/L/Ludwig')
include('simpleicons-7/L/Lufthansa')
include('simpleicons-7/L/Lumen')
include('simpleicons-7/L/Lunacy')
include('simpleicons-7/L/Lydia')
include('simpleicons-7/L/Lyft')
include('simpleicons-7/M/Maas')
include('simpleicons-7/M/Macos')
include('simpleicons-7/M/Macys')
include('simpleicons-7/M/Magasinsu')
include('simpleicons-7/M/Magento')
include('simpleicons-7/M/Magisk')
include('simpleicons-7/M/Mailchimp')
include('simpleicons-7/M/Maildotru')
include('simpleicons-7/M/Mailgun')
include('simpleicons-7/M/Majorleaguehacking')
include('simpleicons-7/M/Makerbot')
include('simpleicons-7/M/Mamp')
include('simpleicons-7/M/Man')
include('simpleicons-7/M/Manageiq')
include('simpleicons-7/M/Manjaro')
include('simpleicons-7/M/Mapbox')
include('simpleicons-7/M/Mariadb')
include('simpleicons-7/M/Mariadbfoundation')
include('simpleicons-7/M/Markdown')
include('simpleicons-7/M/Marketo')
include('simpleicons-7/M/Marko')
include('simpleicons-7/M/Marriott')
include('simpleicons-7/M/Maserati')
include('simpleicons-7/M/Mastercard')
include('simpleicons-7/M/Mastercomfig')
include('simpleicons-7/M/Mastodon')
include('simpleicons-7/M/Materialdesign')
include('simpleicons-7/M/Materialdesignicons')
include('simpleicons-7/M/Matomo')
include('simpleicons-7/M/Matrix')
include('simpleicons-7/M/Matterdotjs')
include('simpleicons-7/M/Mattermost')
include('simpleicons-7/M/Matternet')
include('simpleicons-7/M/Max')
include('simpleicons-7/M/Maxplanckgesellschaft')
include('simpleicons-7/M/Maytag')
include('simpleicons-7/M/Mazda')
include('simpleicons-7/M/Mcafee')
include('simpleicons-7/M/Mcdonalds')
include('simpleicons-7/M/Mclaren')
include('simpleicons-7/M/Mdbook')
include('simpleicons-7/M/Mdnwebdocs')
include('simpleicons-7/M/Mdx')
include('simpleicons-7/M/Mediafire')
include('simpleicons-7/M/Mediamarkt')
include('simpleicons-7/M/Mediatek')
include('simpleicons-7/M/Mediatemple')
include('simpleicons-7/M/Medium')
include('simpleicons-7/M/Meetup')
include('simpleicons-7/M/Mega')
include('simpleicons-7/M/Mendeley')
include('simpleicons-7/M/Mercedes')
include('simpleicons-7/M/Merck')
include('simpleicons-7/M/Mercurial')
include('simpleicons-7/M/Messenger')
include('simpleicons-7/M/Meta')
include('simpleicons-7/M/Metabase')
include('simpleicons-7/M/Metafilter')
include('simpleicons-7/M/Meteor')
include('simpleicons-7/M/Metro')
include('simpleicons-7/M/Metrodelaciudaddemexico')
include('simpleicons-7/M/Metrodemadrid')
include('simpleicons-7/M/Metrodeparis')
include('simpleicons-7/M/Mewe')
include('simpleicons-7/M/Microbit')
include('simpleicons-7/M/Microdotblog')
include('simpleicons-7/M/Microgenetics')
include('simpleicons-7/M/Micropython')
include('simpleicons-7/M/Microsoft')
include('simpleicons-7/M/Microsoftacademic')
include('simpleicons-7/M/Microsoftaccess')
include('simpleicons-7/M/Microsoftazure')
include('simpleicons-7/M/Microsoftbing')
include('simpleicons-7/M/Microsoftedge')
include('simpleicons-7/M/Microsoftexcel')
include('simpleicons-7/M/Microsoftexchange')
include('simpleicons-7/M/Microsoftoffice')
include('simpleicons-7/M/Microsoftonedrive')
include('simpleicons-7/M/Microsoftonenote')
include('simpleicons-7/M/Microsoftoutlook')
include('simpleicons-7/M/Microsoftpowerpoint')
include('simpleicons-7/M/Microsoftsharepoint')
include('simpleicons-7/M/Microsoftsqlserver')
include('simpleicons-7/M/Microsoftteams')
include('simpleicons-7/M/Microsofttranslator')
include('simpleicons-7/M/Microsoftvisio')
include('simpleicons-7/M/Microsoftword')
include('simpleicons-7/M/Microstrategy')
include('simpleicons-7/M/Midi')
include('simpleicons-7/M/Minds')
include('simpleicons-7/M/Minecraft')
include('simpleicons-7/M/Minetest')
include('simpleicons-7/M/Mini')
include('simpleicons-7/M/Minutemailer')
include('simpleicons-7/M/Miro')
include('simpleicons-7/M/Mitsubishi')
include('simpleicons-7/M/Mix')
include('simpleicons-7/M/Mixcloud')
include('simpleicons-7/M/Mlb')
include('simpleicons-7/M/Mlflow')
include('simpleicons-7/M/Mobx')
include('simpleicons-7/M/Mobxstatetree')
include('simpleicons-7/M/Mocha')
include('simpleicons-7/M/Modx')
include('simpleicons-7/M/Mojangstudios')
include('simpleicons-7/M/Moleculer')
include('simpleicons-7/M/Momenteo')
include('simpleicons-7/M/Monero')
include('simpleicons-7/M/Moneygram')
include('simpleicons-7/M/Mongodb')
include('simpleicons-7/M/Monkeytie')
include('simpleicons-7/M/Monoprix')
include('simpleicons-7/M/Monster')
include('simpleicons-7/M/Monzo')
include('simpleicons-7/M/Moo')
include('simpleicons-7/M/Morrisons')
include('simpleicons-7/M/Moscowmetro')
include('simpleicons-7/M/Motorola')
include('simpleicons-7/M/Mozilla')
include('simpleicons-7/M/Msi')
include('simpleicons-7/M/Mta')
include('simpleicons-7/M/Mtr')
include('simpleicons-7/M/Mui')
include('simpleicons-7/M/Mulesoft')
include('simpleicons-7/M/Muller')
include('simpleicons-7/M/Mumble')
include('simpleicons-7/M/Musescore')
include('simpleicons-7/M/Musicbrainz')
include('simpleicons-7/M/Mxlinux')
include('simpleicons-7/M/Myanimelist')
include('simpleicons-7/M/Myob')
include('simpleicons-7/M/Myspace')
include('simpleicons-7/M/Mysql')
include('simpleicons-7/N/N26')
include('simpleicons-7/N/Namebase')
include('simpleicons-7/N/Namecheap')
include('simpleicons-7/N/Nano')
include('simpleicons-7/N/Nasa')
include('simpleicons-7/N/Nationalgrid')
include('simpleicons-7/N/Nativescript')
include('simpleicons-7/N/Naver')
include('simpleicons-7/N/Nba')
include('simpleicons-7/N/Nbb')
include('simpleicons-7/N/Ndr')
include('simpleicons-7/N/Nec')
include('simpleicons-7/N/Neo4J')
include('simpleicons-7/N/Neovim')
include('simpleicons-7/N/Nestjs')
include('simpleicons-7/N/Netapp')
include('simpleicons-7/N/Netbsd')
include('simpleicons-7/N/Netflix')
include('simpleicons-7/N/Netlify')
include('simpleicons-7/N/Nette')
include('simpleicons-7/N/Netto')
include('simpleicons-7/N/Newbalance')
include('simpleicons-7/N/Newjapanprowrestling')
include('simpleicons-7/N/Newrelic')
include('simpleicons-7/N/Newyorktimes')
include('simpleicons-7/N/Nextcloud')
include('simpleicons-7/N/Nextdoor')
include('simpleicons-7/N/Nextdotjs')
include('simpleicons-7/N/Nfc')
include('simpleicons-7/N/Nginx')
include('simpleicons-7/N/Ngrok')
include('simpleicons-7/N/Niconico')
include('simpleicons-7/N/Nike')
include('simpleicons-7/N/Nim')
include('simpleicons-7/N/Nintendo')
include('simpleicons-7/N/Nintendo3Ds')
include('simpleicons-7/N/Nintendogamecube')
include('simpleicons-7/N/Nintendonetwork')
include('simpleicons-7/N/Nintendoswitch')
include('simpleicons-7/N/Nissan')
include('simpleicons-7/N/Nixos')
include('simpleicons-7/N/Nodedotjs')
include('simpleicons-7/N/Nodemon')
include('simpleicons-7/N/Nodered')
include('simpleicons-7/N/Nokia')
include('simpleicons-7/N/Norco')
include('simpleicons-7/N/Nordvpn')
include('simpleicons-7/N/Norwegian')
include('simpleicons-7/N/Notepadplusplus')
include('simpleicons-7/N/Notion')
include('simpleicons-7/N/Notist')
include('simpleicons-7/N/Nounproject')
include('simpleicons-7/N/Now')
include('simpleicons-7/N/Npm')
include('simpleicons-7/N/Nrwl')
include('simpleicons-7/N/Nubank')
include('simpleicons-7/N/Nucleo')
include('simpleicons-7/N/Nuget')
include('simpleicons-7/N/Nuke')
include('simpleicons-7/N/Numba')
include('simpleicons-7/N/Numpy')
include('simpleicons-7/N/Nutanix')
include('simpleicons-7/N/Nuxtdotjs')
include('simpleicons-7/N/Nvidia')
include('simpleicons-7/N/Nx')
include('simpleicons-7/N/Nzxt')
include('simpleicons-7/O/Observable')
include('simpleicons-7/O/Obsidian')
include('simpleicons-7/O/Obsstudio')
include('simpleicons-7/O/Ocaml')
include('simpleicons-7/O/Octanerender')
include('simpleicons-7/O/Octave')
include('simpleicons-7/O/Octopusdeploy')
include('simpleicons-7/O/Oculus')
include('simpleicons-7/O/Odnoklassniki')
include('simpleicons-7/O/Odysee')
include('simpleicons-7/O/Ohdear')
include('simpleicons-7/O/Okcupid')
include('simpleicons-7/O/Okta')
include('simpleicons-7/O/Oneplus')
include('simpleicons-7/O/Onlyfans')
include('simpleicons-7/O/Onlyoffice')
include('simpleicons-7/O/Onnx')
include('simpleicons-7/O/Onstar')
include('simpleicons-7/O/Opel')
include('simpleicons-7/O/Openaccess')
include('simpleicons-7/O/Openai')
include('simpleicons-7/O/Openaigym')
include('simpleicons-7/O/Openapiinitiative')
include('simpleicons-7/O/Openbadges')
include('simpleicons-7/O/Openbsd')
include('simpleicons-7/O/Openbugbounty')
include('simpleicons-7/O/Opencollective')
include('simpleicons-7/O/Opencontainersinitiative')
include('simpleicons-7/O/Opencv')
include('simpleicons-7/O/Openfaas')
include('simpleicons-7/O/Opengl')
include('simpleicons-7/O/Openid')
include('simpleicons-7/O/Openjdk')
include('simpleicons-7/O/Openlayers')
include('simpleicons-7/O/Openmined')
include('simpleicons-7/O/Opennebula')
include('simpleicons-7/O/Opensea')
include('simpleicons-7/O/Opensearch')
include('simpleicons-7/O/Opensourceinitiative')
include('simpleicons-7/O/Openssl')
include('simpleicons-7/O/Openstack')
include('simpleicons-7/O/Openstreetmap')
include('simpleicons-7/O/Opensuse')
include('simpleicons-7/O/Opentelemetry')
include('simpleicons-7/O/Openvpn')
include('simpleicons-7/O/Openwrt')
include('simpleicons-7/O/Openzeppelin')
include('simpleicons-7/O/Openzfs')
include('simpleicons-7/O/Opera')
include('simpleicons-7/O/Opnsense')
include('simpleicons-7/O/Opsgenie')
include('simpleicons-7/O/Opslevel')
include('simpleicons-7/O/Oracle')
include('simpleicons-7/O/Orcid')
include('simpleicons-7/O/Oreilly')
include('simpleicons-7/O/Org')
include('simpleicons-7/O/Origin')
include('simpleicons-7/O/Osano')
include('simpleicons-7/O/Oshkosh')
include('simpleicons-7/O/Osmc')
include('simpleicons-7/O/Osu')
include('simpleicons-7/O/Otto')
include('simpleicons-7/O/Overcast')
include('simpleicons-7/O/Overleaf')
include('simpleicons-7/O/Ovh')
include('simpleicons-7/O/Owasp')
include('simpleicons-7/O/Oxygen')
include('simpleicons-7/O/Oyo')
include('simpleicons-7/P/P5Dotjs')
include('simpleicons-7/P/Packagist')
include('simpleicons-7/P/Packer')
include('simpleicons-7/P/Paddypower')
include('simpleicons-7/P/Pagekit')
include('simpleicons-7/P/Pagerduty')
include('simpleicons-7/P/Pagespeedinsights')
include('simpleicons-7/P/Pagseguro')
include('simpleicons-7/P/Palantir')
include('simpleicons-7/P/Paloaltosoftware')
include('simpleicons-7/P/Pandas')
include('simpleicons-7/P/Pandora')
include('simpleicons-7/P/Pantheon')
include('simpleicons-7/P/Paperspace')
include('simpleicons-7/P/Paritysubstrate')
include('simpleicons-7/P/Parsedotly')
include('simpleicons-7/P/Passport')
include('simpleicons-7/P/Pastebin')
include('simpleicons-7/P/Patreon')
include('simpleicons-7/P/Payoneer')
include('simpleicons-7/P/Paypal')
include('simpleicons-7/P/Paytm')
include('simpleicons-7/P/Pcgamingwiki')
include('simpleicons-7/P/Peakdesign')
include('simpleicons-7/P/Peertube')
include('simpleicons-7/P/Pegasusairlines')
include('simpleicons-7/P/Pelican')
include('simpleicons-7/P/Peloton')
include('simpleicons-7/P/Penny')
include('simpleicons-7/P/Pepsi')
include('simpleicons-7/P/Percy')
include('simpleicons-7/P/Perforce')
include('simpleicons-7/P/Perl')
include('simpleicons-7/P/Personio')
include('simpleicons-7/P/Petsathome')
include('simpleicons-7/P/Peugeot')
include('simpleicons-7/P/Pexels')
include('simpleicons-7/P/Pfsense')
include('simpleicons-7/P/Phabricator')
include('simpleicons-7/P/Philipshue')
include('simpleicons-7/P/Phonepe')
include('simpleicons-7/P/Photobucket')
include('simpleicons-7/P/Photocrowd')
include('simpleicons-7/P/Photopea')
include('simpleicons-7/P/Php')
include('simpleicons-7/P/Phpmyadmin')
include('simpleicons-7/P/Phpstorm')
include('simpleicons-7/P/Picardsurgeles')
include('simpleicons-7/P/Picartodottv')
include('simpleicons-7/P/Picnic')
include('simpleicons-7/P/Picpay')
include('simpleicons-7/P/Pihole')
include('simpleicons-7/P/Pimcore')
include('simpleicons-7/P/Pinboard')
include('simpleicons-7/P/Pingdom')
include('simpleicons-7/P/Pinterest')
include('simpleicons-7/P/Pioneerdj')
include('simpleicons-7/P/Pivotaltracker')
include('simpleicons-7/P/Piwigo')
include('simpleicons-7/P/Pix')
include('simpleicons-7/P/Pixabay')
include('simpleicons-7/P/Pixiv')
include('simpleicons-7/P/Pkgsrc')
include('simpleicons-7/P/Planet')
include('simpleicons-7/P/Planetscale')
include('simpleicons-7/P/Plangrid')
include('simpleicons-7/P/Platformdotsh')
include('simpleicons-7/P/Platzi')
include('simpleicons-7/P/Plausibleanalytics')
include('simpleicons-7/P/Playcanvas')
include('simpleicons-7/P/Playerdotme')
include('simpleicons-7/P/Playerfm')
include('simpleicons-7/P/Playstation')
include('simpleicons-7/P/Playstation2')
include('simpleicons-7/P/Playstation3')
include('simpleicons-7/P/Playstation4')
include('simpleicons-7/P/Playstation5')
include('simpleicons-7/P/Playstationvita')
include('simpleicons-7/P/Playwright')
include('simpleicons-7/P/Pleroma')
include('simpleicons-7/P/Plesk')
include('simpleicons-7/P/Plex')
include('simpleicons-7/P/Plotly')
include('simpleicons-7/P/Pluralsight')
include('simpleicons-7/P/Plurk')
include('simpleicons-7/P/Pluscodes')
include('simpleicons-7/P/Pm2')
include('simpleicons-7/P/Pnpm')
include('simpleicons-7/P/Pocket')
include('simpleicons-7/P/Pocketcasts')
include('simpleicons-7/P/Podcastaddict')
include('simpleicons-7/P/Podman')
include('simpleicons-7/P/Poetry')
include('simpleicons-7/P/Pointy')
include('simpleicons-7/P/Pokemon')
include('simpleicons-7/P/Polkadot')
include('simpleicons-7/P/Poly')
include('simpleicons-7/P/Polymerproject')
include('simpleicons-7/P/Polywork')
include('simpleicons-7/P/Popos')
include('simpleicons-7/P/Porsche')
include('simpleicons-7/P/Portainer')
include('simpleicons-7/P/Postcss')
include('simpleicons-7/P/Postgresql')
include('simpleicons-7/P/Postman')
include('simpleicons-7/P/Postmates')
include('simpleicons-7/P/Powerapps')
include('simpleicons-7/P/Powerautomate')
include('simpleicons-7/P/Powerbi')
include('simpleicons-7/P/Powers')
include('simpleicons-7/P/Powershell')
include('simpleicons-7/P/Powervirtualagents')
include('simpleicons-7/P/Prdotco')
include('simpleicons-7/P/Preact')
include('simpleicons-7/P/Precommit')
include('simpleicons-7/P/Premierleague')
include('simpleicons-7/P/Prestashop')
include('simpleicons-7/P/Presto')
include('simpleicons-7/P/Prettier')
include('simpleicons-7/P/Prezi')
include('simpleicons-7/P/Prime')
include('simpleicons-7/P/Primevideo')
include('simpleicons-7/P/Prisma')
include('simpleicons-7/P/Prismic')
include('simpleicons-7/P/Privateinternetaccess')
include('simpleicons-7/P/Probot')
include('simpleicons-7/P/Processingfoundation')
include('simpleicons-7/P/Processwire')
include('simpleicons-7/P/Producthunt')
include('simpleicons-7/P/Progate')
include('simpleicons-7/P/Progress')
include('simpleicons-7/P/Prometheus')
include('simpleicons-7/P/Prosieben')
include('simpleicons-7/P/Protocolsdotio')
include('simpleicons-7/P/Protodotio')
include('simpleicons-7/P/Protondb')
include('simpleicons-7/P/Protonmail')
include('simpleicons-7/P/Protonvpn')
include('simpleicons-7/P/Protools')
include('simpleicons-7/P/Protractor')
include('simpleicons-7/P/Proxmox')
include('simpleicons-7/P/Pubg')
include('simpleicons-7/P/Publons')
include('simpleicons-7/P/Pubmed')
include('simpleicons-7/P/Pug')
include('simpleicons-7/P/Pulumi')
include('simpleicons-7/P/Puma')
include('simpleicons-7/P/Puppet')
include('simpleicons-7/P/Puppeteer')
include('simpleicons-7/P/Purescript')
include('simpleicons-7/P/Purgecss')
include('simpleicons-7/P/Purism')
include('simpleicons-7/P/Pusher')
include('simpleicons-7/P/Pwa')
include('simpleicons-7/P/Pycharm')
include('simpleicons-7/P/Pyg')
include('simpleicons-7/P/Pypi')
include('simpleicons-7/P/Pypy')
include('simpleicons-7/P/Pyscaffold')
include('simpleicons-7/P/Pytest')
include('simpleicons-7/P/Python')
include('simpleicons-7/P/Pytorch')
include('simpleicons-7/P/Pytorchlightning')
include('simpleicons-7/P/Pyup')
include('simpleicons-7/Q/Qantas')
include('simpleicons-7/Q/Qatarairways')
include('simpleicons-7/Q/Qemu')
include('simpleicons-7/Q/Qgis')
include('simpleicons-7/Q/Qi')
include('simpleicons-7/Q/Qiita')
include('simpleicons-7/Q/Qiskit')
include('simpleicons-7/Q/Qiwi')
include('simpleicons-7/Q/Qt')
include('simpleicons-7/Q/Qualcomm')
include('simpleicons-7/Q/Qualtrics')
include('simpleicons-7/Q/Qualys')
include('simpleicons-7/Q/Quantcast')
include('simpleicons-7/Q/Quantconnect')
include('simpleicons-7/Q/Quarkus')
include('simpleicons-7/Q/Quasar')
include('simpleicons-7/Q/Qubesos')
include('simpleicons-7/Q/Quest')
include('simpleicons-7/Q/Quickbooks')
include('simpleicons-7/Q/Quicklook')
include('simpleicons-7/Q/Quicktime')
include('simpleicons-7/Q/Quip')
include('simpleicons-7/Q/Quora')
include('simpleicons-7/Q/Qwiklabs')
include('simpleicons-7/Q/Qzone')
include('simpleicons-7/R/R')
include('simpleicons-7/R/R3')
include('simpleicons-7/R/Rabbitmq')
include('simpleicons-7/R/Racket')
include('simpleicons-7/R/Radar')
include('simpleicons-7/R/Radiopublic')
include('simpleicons-7/R/Railway')
include('simpleicons-7/R/Rainmeter')
include('simpleicons-7/R/Rakuten')
include('simpleicons-7/R/Ram')
include('simpleicons-7/R/Rancher')
include('simpleicons-7/R/Rarible')
include('simpleicons-7/R/Rasa')
include('simpleicons-7/R/Raspberrypi')
include('simpleicons-7/R/Ray')
include('simpleicons-7/R/Razer')
include('simpleicons-7/R/Razorpay')
include('simpleicons-7/R/React')
include('simpleicons-7/R/Reactivex')
include('simpleicons-7/R/Reactos')
include('simpleicons-7/R/Reactquery')
include('simpleicons-7/R/Reactrouter')
include('simpleicons-7/R/Reacttable')
include('simpleicons-7/R/Readthedocs')
include('simpleicons-7/R/Realm')
include('simpleicons-7/R/Reason')
include('simpleicons-7/R/Reasonstudios')
include('simpleicons-7/R/Redbubble')
include('simpleicons-7/R/Reddit')
include('simpleicons-7/R/Redhat')
include('simpleicons-7/R/Redhatopenshift')
include('simpleicons-7/R/Redis')
include('simpleicons-7/R/Redmine')
include('simpleicons-7/R/Redux')
include('simpleicons-7/R/Reduxsaga')
include('simpleicons-7/R/Redwoodjs')
include('simpleicons-7/R/Reebok')
include('simpleicons-7/R/Relianceindustrieslimited')
include('simpleicons-7/R/Remix')
include('simpleicons-7/R/Renault')
include('simpleicons-7/R/Render')
include('simpleicons-7/R/Renovatebot')
include('simpleicons-7/R/Renpy')
include('simpleicons-7/R/Renren')
include('simpleicons-7/R/Replit')
include('simpleicons-7/R/Republicofgamers')
include('simpleicons-7/R/Rescript')
include('simpleicons-7/R/Rescuetime')
include('simpleicons-7/R/Researchgate')
include('simpleicons-7/R/Resurrectionremixos')
include('simpleicons-7/R/Retroarch')
include('simpleicons-7/R/Retropie')
include('simpleicons-7/R/Revealdotjs')
include('simpleicons-7/R/Reverbnation')
include('simpleicons-7/R/Revolut')
include('simpleicons-7/R/Revue')
include('simpleicons-7/R/Rewe')
include('simpleicons-7/R/Rezgo')
include('simpleicons-7/R/Rhinoceros')
include('simpleicons-7/R/Rider')
include('simpleicons-7/R/Rimacautomobili')
include('simpleicons-7/R/Ring')
include('simpleicons-7/R/Riotgames')
include('simpleicons-7/R/Ripple')
include('simpleicons-7/R/Riseup')
include('simpleicons-7/R/Roamresearch')
include('simpleicons-7/R/Roblox')
include('simpleicons-7/R/Robotframework')
include('simpleicons-7/R/Rocketdotchat')
include('simpleicons-7/R/Rocksdb')
include('simpleicons-7/R/Rockylinux')
include('simpleicons-7/R/Roku')
include('simpleicons-7/R/Rollsroyce')
include('simpleicons-7/R/Rollupdotjs')
include('simpleicons-7/R/Rome')
include('simpleicons-7/R/Roots')
include('simpleicons-7/R/Rootsbedrock')
include('simpleicons-7/R/Rootssage')
include('simpleicons-7/R/Ros')
include('simpleicons-7/R/Rossmann')
include('simpleicons-7/R/Rotaryinternational')
include('simpleicons-7/R/Rottentomatoes')
include('simpleicons-7/R/Roundcube')
include('simpleicons-7/R/Rss')
include('simpleicons-7/R/Rstudio')
include('simpleicons-7/R/Rte')
include('simpleicons-7/R/Rtl')
include('simpleicons-7/R/Rtlzwei')
include('simpleicons-7/R/Rubocop')
include('simpleicons-7/R/Ruby')
include('simpleicons-7/R/Rubygems')
include('simpleicons-7/R/Rubyonrails')
include('simpleicons-7/R/Rubysinatra')
include('simpleicons-7/R/Runkeeper')
include('simpleicons-7/R/Runkit')
include('simpleicons-7/R/Rust')
include('simpleicons-7/R/Rxdb')
include('simpleicons-7/R/Ryanair')
include('simpleicons-7/S/S7Airlines')
include('simpleicons-7/S/Sabanci')
include('simpleicons-7/S/Safari')
include('simpleicons-7/S/Sahibinden')
include('simpleicons-7/S/Sailfishos')
include('simpleicons-7/S/Salesforce')
include('simpleicons-7/S/Saltproject')
include('simpleicons-7/S/Samsung')
include('simpleicons-7/S/Samsungpay')
include('simpleicons-7/S/Sandisk')
include('simpleicons-7/S/Sanfranciscomunicipalrailway')
include('simpleicons-7/S/Saopaulometro')
include('simpleicons-7/S/Sap')
include('simpleicons-7/S/Sass')
include('simpleicons-7/S/Sat1')
include('simpleicons-7/S/Saturn')
include('simpleicons-7/S/Saucelabs')
include('simpleicons-7/S/Scala')
include('simpleicons-7/S/Scaleway')
include('simpleicons-7/S/Scania')
include('simpleicons-7/S/Schneiderelectric')
include('simpleicons-7/S/Scikitlearn')
include('simpleicons-7/S/Scipy')
include('simpleicons-7/S/Scopus')
include('simpleicons-7/S/Scpfoundation')
include('simpleicons-7/S/Scratch')
include('simpleicons-7/S/Screencastify')
include('simpleicons-7/S/Scribd')
include('simpleicons-7/S/Scrimba')
include('simpleicons-7/S/Scrollreveal')
include('simpleicons-7/S/Scrumalliance')
include('simpleicons-7/S/Scrutinizerci')
include('simpleicons-7/S/Seagate')
include('simpleicons-7/S/Seat')
include('simpleicons-7/S/Sefaria')
include('simpleicons-7/S/Sega')
include('simpleicons-7/S/Selenium')
include('simpleicons-7/S/Sellfy')
include('simpleicons-7/S/Semanticrelease')
include('simpleicons-7/S/Semanticuireact')
include('simpleicons-7/S/Semanticweb')
include('simpleicons-7/S/Semaphoreci')
include('simpleicons-7/S/Semver')
include('simpleicons-7/S/Sencha')
include('simpleicons-7/S/Sennheiser')
include('simpleicons-7/S/Sensu')
include('simpleicons-7/S/Sentry')
include('simpleicons-7/S/Sepa')
include('simpleicons-7/S/Sequelize')
include('simpleicons-7/S/Serverfault')
include('simpleicons-7/S/Serverless')
include('simpleicons-7/S/Sfml')
include('simpleicons-7/S/Shadow')
include('simpleicons-7/S/Shanghaimetro')
include('simpleicons-7/S/Sharp')
include('simpleicons-7/S/Shazam')
include('simpleicons-7/S/Shell')
include('simpleicons-7/S/Shelly')
include('simpleicons-7/S/Shenzhenmetro')
include('simpleicons-7/S/Shieldsdotio')
include('simpleicons-7/S/Shikimori')
include('simpleicons-7/S/Shopify')
include('simpleicons-7/S/Shopware')
include('simpleicons-7/S/Shotcut')
include('simpleicons-7/S/Showpad')
include('simpleicons-7/S/Showtime')
include('simpleicons-7/S/Shutterstock')
include('simpleicons-7/S/Siemens')
include('simpleicons-7/S/Signal')
include('simpleicons-7/S/Simkl')
include('simpleicons-7/S/Simpleanalytics')
include('simpleicons-7/S/Simpleicons')
include('simpleicons-7/S/Simplenote')
include('simpleicons-7/S/Sinaweibo')
include('simpleicons-7/S/Singlestore')
include('simpleicons-7/S/Sitepoint')
include('simpleicons-7/S/Sketch')
include('simpleicons-7/S/Sketchfab')
include('simpleicons-7/S/Sketchup')
include('simpleicons-7/S/Skillshare')
include('simpleicons-7/S/Skoda')
include('simpleicons-7/S/Sky')
include('simpleicons-7/S/Skynet')
include('simpleicons-7/S/Skypack')
include('simpleicons-7/S/Skype')
include('simpleicons-7/S/Skypeforbusiness')
include('simpleicons-7/S/Slack')
include('simpleicons-7/S/Slackware')
include('simpleicons-7/S/Slashdot')
include('simpleicons-7/S/Slickpic')
include('simpleicons-7/S/Slides')
include('simpleicons-7/S/Slideshare')
include('simpleicons-7/S/Smart')
include('simpleicons-7/S/Smartthings')
include('simpleicons-7/S/Smashdotgg')
include('simpleicons-7/S/Smashingmagazine')
include('simpleicons-7/S/Smrt')
include('simpleicons-7/S/Smugmug')
include('simpleicons-7/S/Snapchat')
include('simpleicons-7/S/Snapcraft')
include('simpleicons-7/S/Snowflake')
include('simpleicons-7/S/Snowpack')
include('simpleicons-7/S/Snyk')
include('simpleicons-7/S/Socialblade')
include('simpleicons-7/S/Society6')
include('simpleicons-7/S/Socketdotio')
include('simpleicons-7/S/Sogou')
include('simpleicons-7/S/Solid')
include('simpleicons-7/S/Solidity')
include('simpleicons-7/S/Sololearn')
include('simpleicons-7/S/Solus')
include('simpleicons-7/S/Sonarcloud')
include('simpleicons-7/S/Sonarlint')
include('simpleicons-7/S/Sonarqube')
include('simpleicons-7/S/Sonarsource')
include('simpleicons-7/S/Songkick')
include('simpleicons-7/S/Songoda')
include('simpleicons-7/S/Sonicwall')
include('simpleicons-7/S/Sonos')
include('simpleicons-7/S/Sony')
include('simpleicons-7/S/Soundcharts')
include('simpleicons-7/S/Soundcloud')
include('simpleicons-7/S/Sourceengine')
include('simpleicons-7/S/Sourceforge')
include('simpleicons-7/S/Sourcegraph')
include('simpleicons-7/S/Sourcetree')
include('simpleicons-7/S/Southwestairlines')
include('simpleicons-7/S/Spacemacs')
include('simpleicons-7/S/Spacex')
include('simpleicons-7/S/Spacy')
include('simpleicons-7/S/Sparkar')
include('simpleicons-7/S/Sparkasse')
include('simpleicons-7/S/Sparkfun')
include('simpleicons-7/S/Sparkpost')
include('simpleicons-7/S/Spdx')
include('simpleicons-7/S/Speakerdeck')
include('simpleicons-7/S/Spectrum')
include('simpleicons-7/S/Speedtest')
include('simpleicons-7/S/Spinnaker')
include('simpleicons-7/S/Spinrilla')
include('simpleicons-7/S/Splunk')
include('simpleicons-7/S/Spond')
include('simpleicons-7/S/Spotify')
include('simpleicons-7/S/Spotlight')
include('simpleicons-7/S/Spreadshirt')
include('simpleicons-7/S/Spreaker')
include('simpleicons-7/S/SpringCreators')
include('simpleicons-7/S/Spring')
include('simpleicons-7/S/Springboot')
include('simpleicons-7/S/Springsecurity')
include('simpleicons-7/S/Spyderide')
include('simpleicons-7/S/Sqlite')
include('simpleicons-7/S/Square')
include('simpleicons-7/S/Squareenix')
include('simpleicons-7/S/Squarespace')
include('simpleicons-7/S/Ssrn')
include('simpleicons-7/S/Stackbit')
include('simpleicons-7/S/Stackedit')
include('simpleicons-7/S/Stackexchange')
include('simpleicons-7/S/Stackoverflow')
include('simpleicons-7/S/Stackpath')
include('simpleicons-7/S/Stackshare')
include('simpleicons-7/S/Stadia')
include('simpleicons-7/S/Staffbase')
include('simpleicons-7/S/Starbucks')
include('simpleicons-7/S/Stardock')
include('simpleicons-7/S/Starlingbank')
include('simpleicons-7/S/Starship')
include('simpleicons-7/S/Startrek')
include('simpleicons-7/S/Starz')
include('simpleicons-7/S/Statamic')
include('simpleicons-7/S/Statuspage')
include('simpleicons-7/S/Statuspal')
include('simpleicons-7/S/Steam')
include('simpleicons-7/S/Steamdb')
include('simpleicons-7/S/Steamdeck')
include('simpleicons-7/S/Steamworks')
include('simpleicons-7/S/Steelseries')
include('simpleicons-7/S/Steem')
include('simpleicons-7/S/Steemit')
include('simpleicons-7/S/Steinberg')
include('simpleicons-7/S/Stellar')
include('simpleicons-7/S/Stencyl')
include('simpleicons-7/S/Stimulus')
include('simpleicons-7/S/Stitcher')
include('simpleicons-7/S/Stmicroelectronics')
include('simpleicons-7/S/Stopstalk')
include('simpleicons-7/S/Storyblok')
include('simpleicons-7/S/Storybook')
include('simpleicons-7/S/Strapi')
include('simpleicons-7/S/Strava')
include('simpleicons-7/S/Streamlit')
include('simpleicons-7/S/Stripe')
include('simpleicons-7/S/Strongswan')
include('simpleicons-7/S/Stubhub')
include('simpleicons-7/S/Styledcomponents')
include('simpleicons-7/S/Stylelint')
include('simpleicons-7/S/Styleshare')
include('simpleicons-7/S/Stylus')
include('simpleicons-7/S/Subaru')
include('simpleicons-7/S/Sublimetext')
include('simpleicons-7/S/Substack')
include('simpleicons-7/S/Subversion')
include('simpleicons-7/S/Suckless')
include('simpleicons-7/S/Sumologic')
include('simpleicons-7/S/Supabase')
include('simpleicons-7/S/Supermicro')
include('simpleicons-7/S/Superuser')
include('simpleicons-7/S/Surveymonkey')
include('simpleicons-7/S/Suse')
include('simpleicons-7/S/Suzuki')
include('simpleicons-7/S/Svelte')
include('simpleicons-7/S/Svg')
include('simpleicons-7/S/Svgo')
include('simpleicons-7/S/Swagger')
include('simpleicons-7/S/Swarm')
include('simpleicons-7/S/Swc')
include('simpleicons-7/S/Swift')
include('simpleicons-7/S/Swiggy')
include('simpleicons-7/S/Swiper')
include('simpleicons-7/S/Symantec')
include('simpleicons-7/S/Symfony')
include('simpleicons-7/S/Symphony')
include('simpleicons-7/S/Sympy')
include('simpleicons-7/S/Synology')
include('simpleicons-7/T/Tableau')
include('simpleicons-7/T/Tado')
include('simpleicons-7/T/Tails')
include('simpleicons-7/T/Tailwindcss')
include('simpleicons-7/T/Talend')
include('simpleicons-7/T/Talenthouse')
include('simpleicons-7/T/Tampermonkey')
include('simpleicons-7/T/Taobao')
include('simpleicons-7/T/Tapas')
include('simpleicons-7/T/Target')
include('simpleicons-7/T/Task')
include('simpleicons-7/T/Tasmota')
include('simpleicons-7/T/Tata')
include('simpleicons-7/T/Tauri')
include('simpleicons-7/T/Taxbuzz')
include('simpleicons-7/T/Teamcity')
include('simpleicons-7/T/Teamspeak')
include('simpleicons-7/T/Teamviewer')
include('simpleicons-7/T/Ted')
include('simpleicons-7/T/Teespring')
include('simpleicons-7/T/Tekton')
include('simpleicons-7/T/Tele5')
include('simpleicons-7/T/Telegram')
include('simpleicons-7/T/Telegraph')
include('simpleicons-7/T/Temporal')
include('simpleicons-7/T/Tencentqq')
include('simpleicons-7/T/Tensorflow')
include('simpleicons-7/T/Teradata')
include('simpleicons-7/T/Teratail')
include('simpleicons-7/T/Terraform')
include('simpleicons-7/T/Tesco')
include('simpleicons-7/T/Tesla')
include('simpleicons-7/T/Testcafe')
include('simpleicons-7/T/Testin')
include('simpleicons-7/T/Testinglibrary')
include('simpleicons-7/T/Tether')
include('simpleicons-7/T/Textpattern')
include('simpleicons-7/T/Thealgorithms')
include('simpleicons-7/T/Theconversation')
include('simpleicons-7/T/Theirishtimes')
include('simpleicons-7/T/Themighty')
include('simpleicons-7/T/Themodelsresource')
include('simpleicons-7/T/Themoviedatabase')
include('simpleicons-7/T/Thenorthface')
include('simpleicons-7/T/Theregister')
include('simpleicons-7/T/Thesoundsresource')
include('simpleicons-7/T/Thespritersresource')
include('simpleicons-7/T/Thewashingtonpost')
include('simpleicons-7/T/Thingiverse')
include('simpleicons-7/T/Thinkpad')
include('simpleicons-7/T/Threadless')
include('simpleicons-7/T/Threedotjs')
include('simpleicons-7/T/Threema')
include('simpleicons-7/T/Thumbtack')
include('simpleicons-7/T/Thunderbird')
include('simpleicons-7/T/Thymeleaf')
include('simpleicons-7/T/Ticketmaster')
include('simpleicons-7/T/Tidal')
include('simpleicons-7/T/Tide')
include('simpleicons-7/T/Tietoevry')
include('simpleicons-7/T/Tiktok')
include('simpleicons-7/T/Tile')
include('simpleicons-7/T/Timescale')
include('simpleicons-7/T/Tinder')
include('simpleicons-7/T/Tinyletter')
include('simpleicons-7/T/Tmobile')
include('simpleicons-7/T/Tmux')
include('simpleicons-7/T/Todoist')
include('simpleicons-7/T/Toggl')
include('simpleicons-7/T/Tokyometro')
include('simpleicons-7/T/Tomorrowland')
include('simpleicons-7/T/Topcoder')
include('simpleicons-7/T/Toptal')
include('simpleicons-7/T/Torbrowser')
include('simpleicons-7/T/Torproject')
include('simpleicons-7/T/Toshiba')
include('simpleicons-7/T/Toyota')
include('simpleicons-7/T/Tplink')
include('simpleicons-7/T/Tqdm')
include('simpleicons-7/T/Traefikmesh')
include('simpleicons-7/T/Trainerroad')
include('simpleicons-7/T/Trakt')
include('simpleicons-7/T/Transportforireland')
include('simpleicons-7/T/Transportforlondon')
include('simpleicons-7/T/Travisci')
include('simpleicons-7/T/Treehouse')
include('simpleicons-7/T/Trello')
include('simpleicons-7/T/Trendmicro')
include('simpleicons-7/T/Treyarch')
include('simpleicons-7/T/Triller')
include('simpleicons-7/T/Trino')
include('simpleicons-7/T/Tripadvisor')
include('simpleicons-7/T/Tripdotcom')
include('simpleicons-7/T/Trove')
include('simpleicons-7/T/Trpc')
include('simpleicons-7/T/Truenas')
include('simpleicons-7/T/Trulia')
include('simpleicons-7/T/Trustedshops')
include('simpleicons-7/T/Trustpilot')
include('simpleicons-7/T/Tryhackme')
include('simpleicons-7/T/Tryitonline')
include('simpleicons-7/T/Tsnode')
include('simpleicons-7/T/Tubi')
include('simpleicons-7/T/Tui')
include('simpleicons-7/T/Tumblr')
include('simpleicons-7/T/Tunein')
include('simpleicons-7/T/Turborepo')
include('simpleicons-7/T/Turbosquid')
include('simpleicons-7/T/Turkishairlines')
include('simpleicons-7/T/Tutanota')
include('simpleicons-7/T/Tvtime')
include('simpleicons-7/T/Twilio')
include('simpleicons-7/T/Twitch')
include('simpleicons-7/T/Twitter')
include('simpleicons-7/T/Twoo')
include('simpleicons-7/T/Typeform')
include('simpleicons-7/T/Typescript')
include('simpleicons-7/T/Typo3')
include('simpleicons-7/U/Uber')
include('simpleicons-7/U/Ubereats')
include('simpleicons-7/U/Ubiquiti')
include('simpleicons-7/U/Ubisoft')
include('simpleicons-7/U/Ublockorigin')
include('simpleicons-7/U/Ubuntu')
include('simpleicons-7/U/Udacity')
include('simpleicons-7/U/Udemy')
include('simpleicons-7/U/Ufc')
include('simpleicons-7/U/Uikit')
include('simpleicons-7/U/Ulule')
include('simpleicons-7/U/Umbraco')
include('simpleicons-7/U/Unacademy')
include('simpleicons-7/U/Underarmour')
include('simpleicons-7/U/Underscoredotjs')
include('simpleicons-7/U/Undertale')
include('simpleicons-7/U/Unicode')
include('simpleicons-7/U/Unilever')
include('simpleicons-7/U/Unitedairlines')
include('simpleicons-7/U/Unity')
include('simpleicons-7/U/Unocss')
include('simpleicons-7/U/Unraid')
include('simpleicons-7/U/Unrealengine')
include('simpleicons-7/U/Unsplash')
include('simpleicons-7/U/Untangle')
include('simpleicons-7/U/Untappd')
include('simpleicons-7/U/Upcloud')
include('simpleicons-7/U/Uplabs')
include('simpleicons-7/U/Uploaded')
include('simpleicons-7/U/Ups')
include('simpleicons-7/U/Upstash')
include('simpleicons-7/U/Uptobox')
include('simpleicons-7/U/Upwork')
include('simpleicons-7/U/Usps')
include('simpleicons-7/V/V')
include('simpleicons-7/V/V8')
include('simpleicons-7/V/Vaadin')
include('simpleicons-7/V/Vagrant')
include('simpleicons-7/V/Valorant')
include('simpleicons-7/V/Valve')
include('simpleicons-7/V/Vapor')
include('simpleicons-7/V/Vault')
include('simpleicons-7/V/Vauxhall')
include('simpleicons-7/V/Vbulletin')
include('simpleicons-7/V/Vectorlogozone')
include('simpleicons-7/V/Vectorworks')
include('simpleicons-7/V/Veeam')
include('simpleicons-7/V/Veepee')
include('simpleicons-7/V/Velog')
include('simpleicons-7/V/Venmo')
include('simpleicons-7/V/Vercel')
include('simpleicons-7/V/Verdaccio')
include('simpleicons-7/V/Veritas')
include('simpleicons-7/V/Verizon')
include('simpleicons-7/V/Vexxhost')
include('simpleicons-7/V/Vfairs')
include('simpleicons-7/V/Viadeo')
include('simpleicons-7/V/Viber')
include('simpleicons-7/V/Vim')
include('simpleicons-7/V/Vimeo')
include('simpleicons-7/V/Vimeolivestream')
include('simpleicons-7/V/Virgin')
include('simpleicons-7/V/Virtualbox')
include('simpleicons-7/V/Virustotal')
include('simpleicons-7/V/Visa')
include('simpleicons-7/V/Visualstudio')
include('simpleicons-7/V/Visualstudiocode')
include('simpleicons-7/V/Vite')
include('simpleicons-7/V/Vitess')
include('simpleicons-7/V/Vivaldi')
include('simpleicons-7/V/Vivino')
include('simpleicons-7/V/Vk')
include('simpleicons-7/V/Vlcmediaplayer')
include('simpleicons-7/V/Vmware')
include('simpleicons-7/V/Vodafone')
include('simpleicons-7/V/Volkswagen')
include('simpleicons-7/V/Volvo')
include('simpleicons-7/V/Vonage')
include('simpleicons-7/V/Vowpalwabbit')
include('simpleicons-7/V/Vox')
include('simpleicons-7/V/Vsco')
include('simpleicons-7/V/Vtex')
include('simpleicons-7/V/Vuedotjs')
include('simpleicons-7/V/Vuetify')
include('simpleicons-7/V/Vulkan')
include('simpleicons-7/V/Vultr')
include('simpleicons-7/W/W3C')
include('simpleicons-7/W/Wagtail')
include('simpleicons-7/W/Wakatime')
include('simpleicons-7/W/Walkman')
include('simpleicons-7/W/Wallabag')
include('simpleicons-7/W/Walmart')
include('simpleicons-7/W/Wappalyzer')
include('simpleicons-7/W/Warnerbros')
include('simpleicons-7/W/Wattpad')
include('simpleicons-7/W/Waze')
include('simpleicons-7/W/Wearos')
include('simpleicons-7/W/Weasyl')
include('simpleicons-7/W/Web3Dotjs')
include('simpleicons-7/W/Webassembly')
include('simpleicons-7/W/Webauthn')
include('simpleicons-7/W/Webcomponentsdotorg')
include('simpleicons-7/W/Webdriverio')
include('simpleicons-7/W/Webflow')
include('simpleicons-7/W/Webgl')
include('simpleicons-7/W/Webhint')
include('simpleicons-7/W/Weblate')
include('simpleicons-7/W/Webmin')
include('simpleicons-7/W/Webmoney')
include('simpleicons-7/W/Webpack')
include('simpleicons-7/W/Webrtc')
include('simpleicons-7/W/Webstorm')
include('simpleicons-7/W/Webtoon')
include('simpleicons-7/W/Wechat')
include('simpleicons-7/W/Wegame')
include('simpleicons-7/W/Weightsandbiases')
include('simpleicons-7/W/Welcometothejungle')
include('simpleicons-7/W/Wemo')
include('simpleicons-7/W/Westerndigital')
include('simpleicons-7/W/Wetransfer')
include('simpleicons-7/W/Whatsapp')
include('simpleicons-7/W/Wheniwork')
include('simpleicons-7/W/Whitesource')
include('simpleicons-7/W/Wii')
include('simpleicons-7/W/Wiiu')
include('simpleicons-7/W/Wikidata')
include('simpleicons-7/W/Wikidotjs')
include('simpleicons-7/W/Wikimediacommons')
include('simpleicons-7/W/Wikipedia')
include('simpleicons-7/W/Wikiquote')
include('simpleicons-7/W/Wikivoyage')
include('simpleicons-7/W/Winamp')
include('simpleicons-7/W/Windicss')
include('simpleicons-7/W/Windows')
include('simpleicons-7/W/Windows95')
include('simpleicons-7/W/Windowsterminal')
include('simpleicons-7/W/Windowsxp')
include('simpleicons-7/W/Winmate')
include('simpleicons-7/W/Wipro')
include('simpleicons-7/W/Wire')
include('simpleicons-7/W/Wireguard')
include('simpleicons-7/W/Wireshark')
include('simpleicons-7/W/Wise')
include('simpleicons-7/W/Wish')
include('simpleicons-7/W/Wistia')
include('simpleicons-7/W/Wix')
include('simpleicons-7/W/Wizzair')
include('simpleicons-7/W/Wolfram')
include('simpleicons-7/W/Wolframlanguage')
include('simpleicons-7/W/Wolframmathematica')
include('simpleicons-7/W/Woo')
include('simpleicons-7/W/Woocommerce')
include('simpleicons-7/W/Wordpress')
include('simpleicons-7/W/Workplace')
include('simpleicons-7/W/Worldhealthorganization')
include('simpleicons-7/W/Wpengine')
include('simpleicons-7/W/Wprocket')
include('simpleicons-7/W/Writedotas')
include('simpleicons-7/W/Wwe')
include('simpleicons-7/W/Wwise')
include('simpleicons-7/X/Xamarin')
include('simpleicons-7/X/Xaml')
include('simpleicons-7/X/Xampp')
include('simpleicons-7/X/Xbox')
include('simpleicons-7/X/Xcode')
include('simpleicons-7/X/Xdadevelopers')
include('simpleicons-7/X/Xdotorg')
include('simpleicons-7/X/Xero')
include('simpleicons-7/X/Xfce')
include('simpleicons-7/X/Xiaomi')
include('simpleicons-7/X/Xilinx')
include('simpleicons-7/X/Xing')
include('simpleicons-7/X/Xmpp')
include('simpleicons-7/X/Xrp')
include('simpleicons-7/X/Xsplit')
include('simpleicons-7/X/Xstate')
include('simpleicons-7/Y/Yahoo')
include('simpleicons-7/Y/Yale')
include('simpleicons-7/Y/Yamahacorporation')
include('simpleicons-7/Y/Yamahamotorcorporation')
include('simpleicons-7/Y/Yammer')
include('simpleicons-7/Y/Yarn')
include('simpleicons-7/Y/Ycombinator')
include('simpleicons-7/Y/Yelp')
include('simpleicons-7/Y/Yoast')
include('simpleicons-7/Y/Yolo')
include('simpleicons-7/Y/Yourtraveldottv')
include('simpleicons-7/Y/Youtube')
include('simpleicons-7/Y/Youtubegaming')
include('simpleicons-7/Y/Youtubemusic')
include('simpleicons-7/Y/Youtubestudio')
include('simpleicons-7/Y/Youtubetv')
include('simpleicons-7/Y/Yubico')
include('simpleicons-7/Z/Zabka')
include('simpleicons-7/Z/Zalando')
include('simpleicons-7/Z/Zalo')
include('simpleicons-7/Z/Zapier')
include('simpleicons-7/Z/Zara')
include('simpleicons-7/Z/Zazzle')
include('simpleicons-7/Z/Zcash')
include('simpleicons-7/Z/Zdf')
include('simpleicons-7/Z/Zelle')
include('simpleicons-7/Z/Zend')
include('simpleicons-7/Z/Zendesk')
include('simpleicons-7/Z/Zendframework')
include('simpleicons-7/Z/Zenn')
include('simpleicons-7/Z/Zenodo')
include('simpleicons-7/Z/Zerodha')
include('simpleicons-7/Z/Zeromq')
include('simpleicons-7/Z/Zerply')
include('simpleicons-7/Z/Zhihu')
include('simpleicons-7/Z/Zig')
include('simpleicons-7/Z/Zigbee')
include('simpleicons-7/Z/Zillow')
include('simpleicons-7/Z/Zingat')
include('simpleicons-7/Z/Zoho')
include('simpleicons-7/Z/Zoiper')
include('simpleicons-7/Z/Zomato')
include('simpleicons-7/Z/Zoom')
include('simpleicons-7/Z/Zorin')
include('simpleicons-7/Z/Zotero')
include('simpleicons-7/Z/Zulip')
include('simpleicons-7/Z/Zwave')
include('simpleicons-7/Z/Zyte')



@enduml