' definition of the Item simpleicons-14/R/Renovate

sprite $RenovateXs [10x10/16z] Os1Wu6U00rOG0H7YWh3OWHom0cuGWnyap0zYC8B4e0m8an7P97va9W

sprite $RenovateSm [12x12/16z] FSot0GCn5CKmN8xIstzQPtzKh0Y7SZgLqmwu38OCVeOa8wxzUETfOFFEom7dE-r0SYe3jYXNQajoFG4

sprite $RenovateMd [16x16/16z] LOn50G0n0CCovjM_scFChmZ0v4UbySFIUN7E6iQh3MbW5Eob6snIylLvswKQ6MZaVaX10V3y98HBPaxAAHDSp5tINiC2P2V75qdNu_lBbogn0W

sprite $RenovateLg [20x20/16z] {
RSo54KCn3C1GXJdUVzf-9b_ViGpinA5Ll4Sf40nAHqVfMwoyPEZMOcHWEPa4MrhHx-XXJn9eUscDT2Ovlrf8uKmE9Xk1Cnaei6lFLZ6SrDQkRSa2XaVVjw08
3ykkHSaeKKG6YgpcluZYHJeB
}

!procedure Renovate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Renovate', $name, $tech, $desc)
!endprocedure
