' definition of the Item simpleicons-14/R/Roboflow

sprite $RoboflowXs [10x10/16z] 1S470SD0002Xwsv-uTzjeEhohGguYa_ryaaN9ov613DwyDNHaEILwF9HL1zGDm

sprite $RoboflowSm [12x12/16z] 9Oc50SHG5C9I_vxzfpqfUGhmfri8Xhm360gwyHGudNYT6hERosQiZCMEUSL14jCx6zqdQJzr0Kp_FF05

sprite $RoboflowMd [16x16/16z] {
HK-50S0m36BkvVzl5qY5AiHXR1-V2GqV4qTI_qlHLUbbVITVEq-OhZF2Ltt9EIDMkswXfVoQA_SDXEO4pAodgCCUnGzAErRdVIRZlo6rCqwHZeSG8ZQxB-sp
ItxPOEhYRDFy
}

sprite $RoboflowLg [20x20/16z] {
JOw5eSKm30CLvcZ_QJ_SmojRKEl9kDvLNnG_EK5F_CNu6eqOOx-svsjK94YyqnMaD7gGb6rBt0RvApwxxALbxuD84mwAFxDhsrdIuZ7yPA4xIO7l_Owm2bI-
BgDfNzJdGbqY4koZOsQ9FBT8hGhx1caXyFj2MB8PKGtxc2GKVz2RRZYOz0i
}

!procedure Roboflow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Roboflow', $name, $tech, $desc)
!endprocedure
