' definition of the Item simpleicons-14/R/Root

sprite $RootXs [10x10/16z] DOk50G0n20FphctsdnRdS0cCXoSS1ays-pzvH1VfoQuPdWws1hqYxde3i3CR1G

sprite $RootSm [12x12/16z] JOo30S1G34IlTc__QR_25nETXoS42fO-wxPTsXt-IpcVuMS6t_0dVwpsQI6nQnwd1s3vZyPhtGe

sprite $RootMd [16x16/16z] NSx50O1034JH2Uw__sg1TNctUEJDDwSfkGdM49BT9PpDXc5QSdDCcsXYvYw-stnofVm9Z68YChO1FKgn5k2n53y-HYcEtzznVj7l0guS_YpD_Zu

sprite $RootLg [20x20/16z] {
POw53KH150BvlWRqN-tPQd8J8_CKZIYN6mkN6zowyaB4gbH8IN7jEaEXR5_BBgY7kMoaiBfExA5CfnxYxJzsZbZge_RcmMKB9w8n7NH-DB4ueXu6v-oEcZEE
EGg46kAYWFIxpp7vu_G4Wr05QzCR
}

!procedure Root($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Root', $name, $tech, $desc)
!endprocedure
