' definition of the Item simpleicons-14/M/Mambaui

sprite $MambauiXs [10x10/16z] HS750OK0040XVjg-_RVrOe37gx36kykcAkcYgh52VGiAhH020t

sprite $MambauiSm [12x12/16z] LSlL0OH054FH2unR-kzs9-kSdwVXfWbJWQLjIYghpbClQAZBV49ctzwf1awlei5M3WxWmkIs2ilkEo_HU-01

sprite $MambauiMd [16x16/16z] RSZ50SCm00D0XT6-_QSjStCVGVvrSbV7NE5Q6YGHRocBxE_PgQPuM2Owt-BBdW8BTiX58OmDQ-ucQvGcTqhxUFjSjRPSaRkovqgV1_Sx1yu

sprite $MambauiLg [20x20/16z] {
TSy5eiGW303H8THjxd_QBs5zsuSxuK9Pk5kYpHmgpQOLwFfLTU-ZBggnWr5zXSjiu8k1F0LwDx7gx3VyidBuAHYotVCoKqQX5dHcpOURKJswTkwcG5cX1b1f
L5BHZMPvcUDEIU7CNVZItesaogLV
}

!procedure Mambaui($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Mambaui', $name, $tech, $desc)
!endprocedure
