' definition of the Item simpleicons-14/M/Metager

sprite $MetagerXs [10x10/16z] O-070nu61Y0B0ZWO-9c0N9000moWiFYW2Xd011-SnGbdSSDOO1u

sprite $MetagerSm [12x12/16z] RSQ50S0m30F1BxEq_xHb2dnY-_2LMZXzTPYpUeV5rUutnVRJgOxsPx8M_RvdMZ-n0G

sprite $MetagerMd [16x16/16z] ZSx50O003C30u4xstnPtlL-zr2wQ51ZYJJp4JJOPAaDSij2yZrCMbR8NtyP1lMY7cD0TT03fAUPNt9xYUFXfqAxvnWrq

sprite $MetagerLg [20x20/16z] {
TS-54SGW54NHXplqN-qAhdSiStumi3Jb9NvbcpFPjdGsYXRnFzmC-1dz6wPeNhnLJjdDlYoakM9nDyvr_kBSTclJzlzcvctcOc8sbtAa3PEaOapJ5evdU09y
0G
}

!procedure Metager($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Metager', $name, $tech, $desc)
!endprocedure
