@startuml
sprite $AwsFsxForLustreLg [20x20/16z] pOq50S0m40E7Twb_msEeWsTEMYs9xjRFCEIKtuou3o6Qxwvb7wmiovnxjey2kAmptXoxcJsAUrDBDW

sprite $AwsFsxForLustreMd [14x14/16z] hST70S104CImT7lu0qwxWc3rKue0E7S1NkW_35pdUV3D279YYZm

!procedure AwsFsxForLustre($id, $name="Fsx For Lustre", $tech="")
  CloudElement($id, 'aws/Storage/AwsFsxForLustre', $name, $tech)
!endprocedure
!procedure AwsFsxForLustreCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsFsxForLustreMd>', 'Fsx For Lustre', $funcName, $content)
!endprocedure
@enduml
