@startuml
sprite $AwsFsxForWindowsFileServerLg [20x20/16z] RSY54KHH5CBGjGVazj_lkdyo6JlSodSs1Ib8GGfIy2tmRPPkyzO11PaeDWyR94V6Qqdoqnomk5gikuqOaYLfMKyB4oacfzD9tEmMdsvMS0fEmIau1QVW1G

sprite $AwsFsxForWindowsFileServerMd [14x14/16z] LSnH0W0G30BG7r3tFx20hO07Wp9UEemmmhXsqFBKL-uTqHPwrRBKzQmjDOd2kgrrINbL8Is-q4WZZHC

!function AwsFsxForWindowsFileServer($id, $name="Fsx For Windows File Server", $tech="")
  CloudElement($id, 'aws/Storage/AwsFsxForWindowsFileServer', $name, $tech)
!endfunction
!function AwsFsxForWindowsFileServerCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsFsxForWindowsFileServerMd>', 'Fsx For Windows File Server', $funcName, $content)
!endfunction
@enduml
