@startuml
sprite $AwsVpcAccessPointsDarkBgLg [20x20/16z] {
VP250OH040CtcMp_9V_Z3eD7EAaLgIuu0puA18-FNLRFRnharXhRBNpIIAwQckQWqK60ZvgLQOP7BQIKPDCKBRKeMhLbAUnQJRENZ9nQc5nONXOS1EAq2y9W
L2T6hIwaErTDtQeF_W
}

sprite $AwsVpcAccessPointsDarkBgMd [14x14/16z] LSw50KGn20HHTeRqN_B9dlxuYy6qm7nA53G5dHEfdd0dVDvabxTq4_ALYRm5Z4WLUu5t21aOB7g0bsmoFvrJVVZ67G

!procedure AwsVpcAccessPointsDarkBg($id, $name="Vpc Access Points Dark Bg", $tech="")
  CloudElement($id, 'aws/Storage/AwsVpcAccessPointsDarkBg', $name, $tech)
!endprocedure
!procedure AwsVpcAccessPointsDarkBgCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsVpcAccessPointsDarkBgMd>', 'Vpc Access Points Dark Bg', $funcName, $content)
!endprocedure
@enduml
