' definition of the Item simpleicons-8/H/Htmlacademy

sprite $HtmlacademyXs [10x10/16z] BScr0O0040J1mPthlrhqinMOCy46YfQcQCAXRgDxAVR4IwqKEJyWqEt5mGq

sprite $HtmlacademySm [12x12/16z] DOg70S0W20JVtZ2__xPHWLFwuH07Uy0bGPbMlnFrTNAq-lgYqXXsBoSHXz0Xc-QlLUcz559UBySYpD_bUXqAqrl-

sprite $HtmlacademyMd [16x16/16z] {
HSU50S0m20NHYrU0l_-qTRa8FAxQggLnfrXw1igmiDFyVRQbyRlFWAN7oRbATZkVy0Jqot4wSERRf02h9hYT-pAGVYT7lo5Pbfp77HXA9nU0himz4tUhGrBd
J-5SxG
}

sprite $HtmlacademyLg [20x20/16z] {
PP07WaGX2CM2_Yxmxd_QBOFJOuyTYdwunjwP34bn7RtrSuIac-kyagzk-t9dcDvT2mFsyU9ofuXZkXZySm1Og1o53EZbDbzlxReDYtO_psJWo0LtrzhcaDAB
eoKXlRjev_clhXV7bjJtonrg5PxbzaTnGycaovaiEkiJQKpcpg6LDonqCVa5
}

!procedure Htmlacademy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/H/Htmlacademy', $name, $tech, $desc)
!endprocedure
