@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsInternetAlt2 element
include('elements/aws/General/AwsInternetAlt2')
AwsInternetAlt2('element', 'Internet Alt2', 'an optional tech field')
@enduml
