' definition of the Item homecloud-1/Container/Service

sprite $ServiceXs [10x10/16z] uwS3

sprite $ServiceSm [12x12/16z] unza

sprite $ServiceMd [16x16/16z] un_X

sprite $ServiceLg [20x20/16z] unzKO1G

!procedure Service($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'homecloud-1/Container/Service', $name, $tech)
!endprocedure

!procedure ServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceMd>', '', $funcName, $content)
!endprocedure

!procedure ServiceGroup($id, $name='Service', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceMd>', $name, $tech)
!endprocedure
