' definition of the Item simpleicons-6/V/Vaadin

sprite $VaadinXs [10x10/16z] Ou03VZY3Yny8M84OBCG4bs3WG5BA3s5nCW1LGPN1548q8Wm5

sprite $VaadinSm [12x12/16z] HSk54S0m3C10bRdQVzjSq1yqGV2XypSZxfuXap35JBukibiuxGLphJfzfTEFRf4i0G

sprite $VaadinMd [16x16/16z] TSU50OH04CNGu4xwh_O4P-MDVW8QHClY1_YVpjbTwGvtwtuMTeiLJvNaAK3hm6vr1BHcLoWChfnc5xJaehChjqdbIHUU1jbz0G

sprite $VaadinLg [20x20/16z] {
RSw55OGm54JHmOc-_gjTZVx3XRYD7YHaH406Ny5_k5Md_uhWgGugPOfCuLIi41y2xBAMMvFjB1TSQk0ghLDLaj_VjUe4LvVcZOxfwHMy89jqH4p2ZI_DCY0B
WgmxBohU
}

!procedure Vaadin($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/V/Vaadin', $name, $tech)
!endprocedure
