' definition of the Item simpleicons-6/V/Vagrant

sprite $VagrantXs [10x10/16z] Ou039dv-VY058b5OR402o691aU26ii20YG76P41bGTK3

sprite $VagrantSm [12x12/16z] POa50e0m30CJtE__hvtXS5lRYDHePr85P5K3PZVbFFKCD4Nwt-QoJxfYHvbTRaKFHLjteHqVCW8

sprite $VagrantMd [16x16/16z] NOp50KCn3CNqCPpiFst1LD15pmYPuDXXhTMiN2_szMO3aYIYpbzr1WqtXnWsC-A3-LO7ojyVJStNaKtbalg86iNBQdMsUkDdOU9qgK-2BQPF

sprite $VagrantLg [20x20/16z] {
PO-54SGm4CGKvcp_rJviRXo3XcmT0pk9-1sIfjT8cdkPpcQM2NVOwO7MxUmo05EK4iLpLfgz1faH6EF9APDrFf7PxBOOdM_QAOS7PVJX-ZOjJzoIMvFhQ1Dv
kTE4Z2iTdT7VsWc-
}

!procedure Vagrant($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/V/Vagrant', $name, $tech)
!endprocedure
