' definition of the Item simpleicons-6/V/Veeam

sprite $VeeamXs [10x10/16z] Oo0IC3CmC89e9Y3DpyVFnyV7m4siNW

sprite $VeeamSm [12x12/16z] Ow00y31myp7oS32mCuDuZ7my_7pyRAoyl0pC32mCZEIP2G

sprite $VeeamMd [16x16/16z] lS470O104C2m_fvN_Bj51IJyR9DRZL8UB6qJJ9TUBTtMISoC1s-GE_Ar5m

sprite $VeeamLg [20x20/16z] pOS50S0m40ElJ0_-rOxdeU6mEH94Ie3s7r99g8QI7M4DYe0WeRZPxM3P2drbgbE7HEas0hCoHsPpd

!procedure Veeam($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/V/Veeam', $name, $tech)
!endprocedure
