@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../"

' loads the library
!include ../../library.puml

' loads the style
include('styles/gcp')

' loads the GcpGroupOnPremise group
include('groups/gcp/GcpGroupOnPremise')
GcpGroupOnPremise('element', 'On premise', 'an optional tech field')
@enduml
