@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../"

' loads the library
!include ../../library.puml

' loads the AWS style
include('styles/aws')

' loads the GcpGroupInfrastructureSystem group
include('groups/gcp/GcpGroupInfrastructureSystem')
GcpGroupInfrastructureSystem('element', 'Infrastructure System', 'an optional tech field')
@enduml
