' definition of the Item simpleicons-5/M/Manageiq

sprite $ManageiqXs [10x10/16z] 9SC50SC00C2md3-iVxN30dpc5vYhUlClr3rAY6VY5P9UMFEe5QNMXYgjtUm

sprite $ManageiqSm [12x12/16z] FShL0SDG5CDGvJ5h_sdBpVcvOFDML-RBZ_DRQsWg7FSlRUXTnGNPtpvXs-28PkzELe6gfE_QzNgltI-KeqwiJm

sprite $ManageiqMd [16x16/16z] {
FOq55WKX30E3hRTp_zD-oJuOj9R8bFCvj3Z0T9baSi-mIHh0ANK8lG3lDO4GMFa_eG11TILjj69FxOvtKOgjRiS5ACjWBu1d5CwlCAS_BGbCLg0c9W1Lgie5
xDA1lW
}

sprite $ManageiqLg [20x20/16z] {
VOy75iCW34F5tkZ-j-qpZhlRdm1wtiP5whC5F14sbU7CDFaWgcbGw4tV8gOgIdEYI02Ev8AXndPkmv-I93CUR7A8xUfKBD1imNn_RIEXxzVSGORd7erXF9Ro
gjmnxUUPSKm3GX9PBzFsd6rHoLNkuVaCfjIY8Se3Ksgvt7fBPnYF6m
}

!procedure Manageiq($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Manageiq', $name, $tech)
!endprocedure
