' definition of the Item simpleicons-5/M/Mdnwebdocs

sprite $MdnwebdocsXs [10x10/16z] uyS1EFcW30OWu0Kp8038OeUp-FaW54GUhfaLrIm

sprite $MdnwebdocsSm [12x12/16z] uoSIC001AvG91XmW9Wi3503PFEm8DZyNaERavuDhG1Z4n83N7W

sprite $MdnwebdocsMd [16x16/16z] uoSFyA3mc1X0W1V6PO009WGNHOGFp4PeOMU7yv6Du-9WH3QV6ya-a0PKvy3v20SI1m

sprite $MdnwebdocsLg [20x20/16z] jSwr0S0m40D0cTc__xHXLDhuoaV98CbtgZXirAEaS6XNIUEYyruoUB9xiJvhUg-5yAXvUkiqefpwbOJ210gzrf8G3nJvS5L-C0C

!procedure Mdnwebdocs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Mdnwebdocs', $name, $tech)
!endprocedure
