' definition of the Item simpleicons-5/M/Microsoftoffice

sprite $MicrosoftofficeXs [10x10/16z] Om01VY06q_pyG0nXy815UFdPWII4nOYN1I8Hfa008py_5v03

sprite $MicrosoftofficeSm [12x12/16z] dOm50G0X4C3sxh_-QN4Ai7Eb89rV_zy3E4syyC6a_qJDPuN1V7BkUOxrlsGMQnK1

sprite $MicrosoftofficeMd [16x16/16z] jSX50S0m0C30ZClrhxQC0fRVXThXRvPyoHnLkWY4_u2do2LpEo0XVLOVxEPNkvFLe7mEU6pnMPtsIUtsANK04G

sprite $MicrosoftofficeLg [20x20/16z] pSs50O0m34JHrBst_xJ81P-0ZpygSXQGv9q3Q-4cC8a0gh0AJIUGe7Nzuhrp8S-lqmR0BRzcVcJoiOfXtyOIsClgPR6V9eR6NuR08e1P7DzN

!procedure Microsoftoffice($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Microsoftoffice', $name, $tech)
!endprocedure
