' definition of the Item simpleicons-5/M/Microsoftteams

sprite $MicrosoftteamsXs [10x10/16z] uwS3

sprite $MicrosoftteamsSm [12x12/16z] unza

sprite $MicrosoftteamsMd [16x16/16z] un_X

sprite $MicrosoftteamsLg [20x20/16z] unzKO1G

!procedure Microsoftteams($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Microsoftteams', $name, $tech)
!endprocedure
