' definition of the Item simpleicons-5/M/Midi

sprite $MidiXs [10x10/16z] uwS3

sprite $MidiSm [12x12/16z] unza

sprite $MidiMd [16x16/16z] un_X

sprite $MidiLg [20x20/16z] unzKO1G

!procedure Midi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Midi', $name, $tech)
!endprocedure
