' definition of the Item simpleicons-5/M/Minds

sprite $MindsXs [10x10/16z] uwS3

sprite $MindsSm [12x12/16z] unza

sprite $MindsMd [16x16/16z] un_X

sprite $MindsLg [20x20/16z] unzKO1G

!procedure Minds($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Minds', $name, $tech)
!endprocedure
