' definition of the Item simpleicons-5/M/Mojangstudios

sprite $MojangstudiosXs [10x10/16z] HSP50GH10C2mxZ3NlzfZo2lyR0KZkkcAmAPgiFNCdoMOPrrvOnB53SyXWPxeC0X4QD2v0m

sprite $MojangstudiosSm [12x12/16z] JSR70O0m34FHJn8xeXZjFotjn7EH-9bImhxGf0ehtBtGg_2OPkhWwJpTnWv8bamW4iSnAlna5AU7y7BCi-3hMCNFXWWIRRjuBC-yRW

sprite $MojangstudiosMd [16x16/16z] {
TOVNOSGm34CVrMnB9B7_jd7xINA73hx0tWv93cSEsfaH8zgPvm5uVswWtUzlhMbeAKq-nt50NRJOmQQV9nCoyvc9zkvez7cKStOFCvcWw73C8gJtTnKf0jxF
4k8Fzc71N2mAmrdxuinWbSeHJFxW1m
}

sprite $MojangstudiosLg [20x20/16z] {
ZOk3WKHH5CNox9_-grsRasiSRkIeBk3I15drE7KNT5vcufpJ8uviDOCRWFTTUXhso-wqRD2uRDqHotK4iY6h2wRAZnGLba-5yLIrr1sNfRILchkKiWJCpwLw
08xenzsbHrfxssNF69vFMge1-O7OQ8CSO40ZJ9XbGAKdGbfi5eKL2oGOqA4I1Wn-u1u
}

!procedure Mojangstudios($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Mojangstudios', $name, $tech)
!endprocedure
