' definition of the Item simpleicons-5/M/Moleculer

sprite $MoleculerXs [10x10/16z] Oq03_Fnm5X-c73UO0YAmCZuWoGB4R4013Y0VAep10W

sprite $MoleculerSm [12x12/16z] Oy04_Fp8R4OucnVEOk62YpBnGvNpi39mGDay_Fpi350sArIQ3yI7wkA7o27O20ut

sprite $MoleculerMd [16x16/16z] VKor0G0n42Bkn_xJlhk42iSVXBnfagQNM_NONqKYvN56jr8lcmwhdAcktDzbbe2o4DlOWFE9Cm2zIRFf7VgXyTGGDem

sprite $MoleculerLg [20x20/16z] {
ZO-53S103CHIvjx-qpupMnGvJ6rMu4uT1FE0su2V4gPdefGd5KVUk4EG57wGa65HX_wXMo3udYFiLGMpUkp0BWQB-0xdVA-k07061-cIuCNVEcgxAt4AfRRq
xUUQYGC
}

!procedure Moleculer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Moleculer', $name, $tech)
!endprocedure
