' definition of the Item simpleicons-5/M/Mongodb

sprite $MongodbXs [10x10/16z] uwS3

sprite $MongodbSm [12x12/16z] unza

sprite $MongodbMd [16x16/16z] un_X

sprite $MongodbLg [20x20/16z] unzKO1G

!procedure Mongodb($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Mongodb', $name, $tech)
!endprocedure
