' definition of the Item simpleicons-5/M/Monster

sprite $MonsterXs [10x10/16z] uwS3

sprite $MonsterSm [12x12/16z] unza

sprite $MonsterMd [16x16/16z] un_X

sprite $MonsterLg [20x20/16z] unzKO1G

!procedure Monster($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Monster', $name, $tech)
!endprocedure
