' definition of the Item simpleicons-5/M/Moo

sprite $MooXs [10x10/16z] LOQ50O1008ImM_QVrloyX5SxGOEHn0YiRIGapfG8Qsg0unrqLBW1

sprite $MooSm [12x12/16z] JKs30G1H5EhiQ_zflvxDmf0NBZUZ9hpvL_o7b1C1Mt3gBvVK4SyZjkyg54iB-vilvnOk0-BFNbO

sprite $MooMd [16x16/16z] LOw50S0W30HJt7__QN48FJJ-j4dq8qEyveU2rqOcU3OjY1JOXXbNEgQV8O7lXDLyIbwcmNh5UhapDASFScBtQoSUEr1RUpYA4jp8Xc91Wocd0G

sprite $MooLg [20x20/16z] {
PP054iKm24IXxk_-f_sAb8QnpEfa9UwGvax69pG2Jmm6zWfj37BILTafefpL-HFVXGEBKt6NlMScXvJPCwwIPiB0jYop7_QCJVB8a4CODZ1LNORKEj0OJ9Fj
RObqzC0o7NL2tG6ywmq
}

!procedure Moo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/M/Moo', $name, $tech)
!endprocedure
