@startuml

' icons

!function getIcon($name) return $IMAGE_BASE_PATH + "icons" + "/" + $name + "." + $ICON_FORMAT

' library

!function include($resource)
  !if (%get_variable_value("$INCLUSION_MODE") == "remote")
    !includeurl $LIB_BASE_LOCATION/$resource.puml
  !else
    !include $LIB_BASE_LOCATION/$resource.puml
  !endif
!endfunction

' Formatting

!function fmtTech($value)
  <size:$FONT_SIZE_SM>[$value]</size>
!endfunction

!function fmtLabel($value, $tech="")
  !if ($tech != '')
    $value\n<size:$FONT_SIZE_SM>[$tech]</size>
  !else
    $value
  !endif
!endfunction

' Element

!function CloudElement($id, $icon, $name="", $tech="")
card $id <<CloudElement>> [
  <img:getIcon($icon)>
  !if ($name)
    $name
  !endif
  !if ($tech)
    <size:$FONT_SIZE_SM>[$tech]</size>
  !endif
]
!endfunction

' Card

!function CloudCard($id, $sprite="", $techName="", $funcName="", $content="")
  !local $V=""
  !local $H=""
  !local $F=""
  !if ($sprite)
    !$H="<color:" + $SPRITE_COLOR + ">" + $sprite + " </color>"
  !endif
  Rectangle $id <<CloudCard>> [
    !if ($techName) && ($funcName)
      !$T="<color:" + $FONT_COLOR + ">" + $funcName + "</color>"
      !$ST="\l" + $techName
      !$H=$H + $T + $ST
      !$V=$V + $H
    !elseif ($techName)
      !$H=$H + $techName
      !$V=$V + $H
    !elseif ($funcName)
      !$T="<color:" + $FONT_COLOR + ">" + $funcName + "</color>"
      !$H=$H + $T
      !$V=$V + $H
    !endif
    !if ($H) && ($content)
      !$F="\l----\l<size:" + $FONT_SIZE_SM + ">" + $content + "</size>"
      !$V=$V + $F
    !elseif ($content)
      !$F="\l<size:" + $FONT_SIZE_SM + " + $content + "</size>"
      !$V=$V + $F
    !endif
    $V
  ]
!endfunction

' Group

!function CloudGroup($id, $stereotype, $sprite, $name, $tech="")
  !local $value=""
  !if ($sprite)
    !$value=$sprite + " "
  !endif

  !if ($name) && ($tech)
    !$value=$value + $name + "\n<color:" + $FONT_COLOR + "><size:" + $FONT_SIZE_SM + ">[" + $tech + "]</size></color>"
  !elseif ($name)
    !$value=$value + $name
  !elseif ($tech)
    !$value=$value + "<color:" + $FONT_COLOR + "><size:" + $FONT_SIZE_SM>[" + $tech + "]</size></color>"
  !endif

  !if ($value)
    Rectangle $id <<$stereotype>> as "$value"
  !else
    Rectangle $id <<$stereotype>>
  !endif
!endfunction

@enduml