@startuml

' by default the inclusion mode is remote
!if (%not(%variable_exists("$INCLUSION_MODE")))
    !global $INCLUSION_MODE="remote"
!endif

' by default the branch is master
!if (%not(%variable_exists("$LIB_BRANCH")))
    !global $LIB_BRANCH="v1.x"
!endif

!if ($INCLUSION_MODE == "remote")
    !if (%not(%variable_exists("$LIB_BASE_LOCATION")))
        !global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/" + $LIB_BRANCH + "/cloud"
    !endif
    !includeurl $LIB_BASE_LOCATION/constants.puml
    !includeurl $LIB_BASE_LOCATION/styles/common.puml
    !includeurl $LIB_BASE_LOCATION/functions.puml
!else
    !if (%not(%variable_exists("$LIB_BASE_LOCATION")))
        !global $LIB_BASE_LOCATION="."
    !endif
    !include constants.puml
    !include styles/common.puml
    !include functions.puml
!endif

@enduml