' definition of the Item material-4/Places/Countertops

sprite $CountertopsXs [10x10/16z] RORL0ODG0CJITpz5i_-qkCDf-9IssEo4G2gJc49Hv_v0NVeWLKwD

sprite $CountertopsSm [12x12/16z] TKg30G113CkPRVQVzcsK4Nwhz6vHue8xQLkbtV5q_GIha2925GipwRJJXZL3JEi-SD-mTMlXLYC

sprite $CountertopsMd [16x16/16z] bOl50O1040E3MvRflrhSNi3DwKQK3WlIIFUS1ohonxn0kSy6ttFEarE8upxxiTtMtndViozwVJ83

sprite $CountertopsLg [20x20/16z] hOtL0S0W44CFXrhsdnRtN_hGiuJEO2eYuqVodbE8F4JnlhVS3NM3hxdyapKdKiukEI5SR1C90or46iT6Kk4Q2Si_93Zh7Z1KSaJ_vDu7Msv0PmG

!procedure Countertops($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Places/Countertops', $name, $tech, $desc)
!endprocedure
