' definition of the Item aws-q1-2024/Architecture/ManagementGovernance/AwsFaultInjectionSimulator

sprite $AwsFaultInjectionSimulatorXs [10x10/16z] uy8E6BcOOKnMBWu64Cq2ve6P71nSd105RCoihAnSO1OJL3r8EIe

sprite $AwsFaultInjectionSimulatorSm [12x12/16z] VSQt0G11202Woohx3_pz9ohys6C37CVQGBUGC9oo2NIPYWDpzzRQ07Q7vwCyN

sprite $AwsFaultInjectionSimulatorMd [16x16/16z] ZOo53SG030CLZc__VP-nefxGo3dqfwB6VfoM1ijvQySBKU_se0MK-z15cOW4U-dTPUQZnzaxhi_XyelRGVElsyH9hW

sprite $AwsFaultInjectionSimulatorLg [20x20/16z] {
fSgr0G9044JHlLkTtt-_k9F1oqRuNqUATwl1YrVLzE3fuc6Zt6Wmxch13e2uFoUu471_vhasQ1Ea7jq98y35cKpPUtHMpasNVF9CF9ICJsNxkvFpQSBu8dvm
1
}

!procedure AwsFaultInjectionSimulator($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Architecture/ManagementGovernance/AwsFaultInjectionSimulator', $name, $tech, $desc)
!endprocedure

!procedure AwsFaultInjectionSimulatorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsFaultInjectionSimulatorLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsFaultInjectionSimulatorGroup($id, $name='Aws Fault Injection Simulator', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsFaultInjectionSimulatorLg>', $name, $tech)
!endprocedure
