' definition of the Item material-4/Alert/AutoDelete

sprite $AutoDeleteXs [10x10/16z] uwS3

sprite $AutoDeleteSm [12x12/16z] unza

sprite $AutoDeleteMd [16x16/16z] un_X

sprite $AutoDeleteLg [20x20/16z] unzKO1G

!procedure AutoDelete($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Alert/AutoDelete', $name, $tech)
!endprocedure
