' definition of the Item material-4/Alert/ErrorOutline

sprite $ErrorOutlineXs [10x10/16z] uwS3

sprite $ErrorOutlineSm [12x12/16z] unza

sprite $ErrorOutlineMd [16x16/16z] un_X

sprite $ErrorOutlineLg [20x20/16z] unzKO1G

!procedure ErrorOutline($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Alert/ErrorOutline', $name, $tech)
!endprocedure
