' definition of the Item simpleicons-7/L/Laravelnova

sprite $LaravelnovaXs [10x10/16z] 9Kg50S0m39glpl_V5ebY1wlYErI0RYVuYCt0Pe5oYyO-boKtyXsRHj8UWvyx23O

sprite $LaravelnovaSm [12x12/16z] BSs50G0X241HujBw-qzhOZu3aDKodvm6EjUwQN93sdIXcIQkwVsG9dHP8A7Azcf73gIZkFwdrtLgws7NqrVdmtwlhzrjtGu

sprite $LaravelnovaMd [16x16/16z] {
9Se95iGW20JH4YTxfEv_stcGxmeqRLi-Wr9Idz_Sra7JuBDtcN1QPfLBq2T6B1VWWTAY6ZAib5vCnrTFW-DBLckdt7AABu_hL4Bssi6k2r9UwvcKrrbXUFIz
KoUNj5jpXykZArfOPHbcgWdm1m
}

sprite $LaravelnovaLg [20x20/16z] {
JSu5Rc0n303HoUUGv_wdtMq3Kf_GR9OSjeS_RZLgARqd5dMtd7Md2d1y-Jk00s0qVKvjxIeGcezqF6e256BLH__C9JlSeH-y1bWfWXDqqyxr1XGhXtdE1fE2
mUnlnz5y245vBMjRxBxrS_gU1BUTP07sztI5wW6WHgsX0QSot0uNN3epi1Kz6TwrhwcmPOT-0F0V
}

!procedure Laravelnova($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Laravelnova', $name, $tech)
!endprocedure
