' definition of the Item simpleicons-7/L/Livejournal

sprite $LivejournalXs [10x10/16z] Os1WOe02VWW0Yl13UK0I9W5aGPb036D1b41OK0fk31lCH7O6

sprite $LivejournalSm [12x12/16z] FSV50S0m0810wbxsdpQUyEA0ZTwYg_e0ADogCvlGCB6IkpBm7i2Aito1EPwCqsLMi3JZ3uijWCdS3n4

sprite $LivejournalMd [16x16/16z] LOq10a0W5CKU0Bvs_zE2Xsh0LfKk1fMiC6YAhVyrNQ-Rk1qsrnjf84bLa5aUdw-HAcYY2Wg-mESEs0SS8ARRtTT4g7bynqoDeFN2ZrqtjNudU_89

sprite $LivejournalLg [20x20/16z] {
PT150WKn20FG05_6S__R3dNBgdrLW4U_c7EHZgegbHXoCANkeW45zt1NMcnu0T-mQy0z831Y66921ou8vO8mDbGsoxYpdGsOwOa6PXGNM6yyuqHoUInvJCAa
Njtoowtf4avEE_ze1VIRNW
}

!procedure Livejournal($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Livejournal', $name, $tech, $desc)
!endprocedure
