' definition of the Item simpleicons-7/L/Lodash

sprite $LodashXs [10x10/16z] Ou03VcmiACd83s6nCp3mW5biGCmAbGKYC61W0c8ay-

sprite $LodashSm [12x12/16z] VSgr0G0X4031Lnos_sfnYnZazDeWppamSifh-UFp5rekJC_NZhVPvT2OkxggVyCc0G

sprite $LodashMd [16x16/16z] dOs50S0W30G_TR_zfwsxmq7ST09yumeejxWP7Eer7gsnnF5arpWvnUT-CJYi30UWbite0Kva9pe

sprite $LodashLg [20x20/16z] dOs50GCn54A9UzX_slRS_KM_0Gv8QPyZF-N4DcVP8a4kKu1eakHMXdMPSzsJEUViy3CtET1tJ-6nX-mHKAGIjabmn0Dz08WHN5CFu07YW3y

!procedure Lodash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Lodash', $name, $tech)
!endprocedure
