' definition of the Item simpleicons-7/L/Logmein

sprite $LogmeinXs [10x10/16z] Om02Jdus1X3W1mDE88CLp0PHZ31H88i7eWRCuWSosI0iPY07mUBaXm2WMbOe0m

sprite $LogmeinSm [12x12/16z] RSY54O1040J1BSDXyyyMXdUPb-iwqUbD8OSo2UeAlfDv9nQPi2rxgwovLqReqTUDsBu

sprite $LogmeinMd [16x16/16z] NOy30W0n3C1onj3_ltPsndGiYSk8sgWOoJnPfM6Jskkl0Hqt_-nIsP39vSeE9obiglE2baZsE8RDghkAlYtEx9PxylpxnWsWPuLjoCO3

sprite $LogmeinLg [20x20/16z] {
RSw50O0W04JHenlsdzQWwzjF1L0pCNc9AP5gWQ2Mfaob9Lj8B2xoM6Jz5aY7wMx69arP-D5KyzCQuZ0QBC1-7FOFdyz-CPRFyc8uBI0SHa4E0s3I6lxiGXGv
iNvLqmL2-UW5
}

!procedure Logmein($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Logmein', $name, $tech)
!endprocedure
