' definition of the Item simpleicons-14/K/Kdenlive

sprite $KdenliveXs [10x10/16z] Oq01_FniS2QOPENdP-S7CvdOs9Zu-VbvW6f0OY00Pq7KGXbWCGvaKm

sprite $KdenliveSm [12x12/16z] NOh50S100CAWxjb_slffNaXK0yJSXcXRP09Jb9xC8FZtZvY3yqL_-wQG-rQ1TzG5

sprite $KdenliveMd [16x16/16z] RSt50S0m4CH0XJdglzemsfxVuPBKZ-DOyA7orRvbjaEoTrKHsw1svYMg6PwksYweRKvtNVpldu2Z7ldL9H-IjW8

sprite $KdenliveLg [20x20/16z] VSo50O0m40J1nPthlriqBWEnDohQ1o7THfBWGMnHWzCyG3Y37XD2oiNKmwCT7-qNquvFw77od7xleqzYZpIs9_CqaiJuUBqxIMp6M6yzOcg9Y9eB

!procedure Kdenlive($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/K/Kdenlive', $name, $tech, $desc)
!endprocedure
