' definition of the Item simpleicons-14/K/Knexdotjs

sprite $KnexdotjsXs [10x10/16z] BSQr0SG0000XtYLo-qyRfm8-W3p-lCai-L6_wkdDdhnyAjKDxRZIXu-dJ6xylT-m0W

sprite $KnexdotjsSm [12x12/16z] LOo50S0m40A9Usx_QUlwBe1sQuewpMXwTsseirV9GWCw-x9VDtTIcnKnjjow0Qe0LA95WC6q2szsl29ue4p--iTcmjvM

sprite $KnexdotjsMd [16x16/16z] {
JSp50SH03CLGXGUj_gjT2B-JyNEOQBo9N581JPoZ6GV2YIG9wDfKGyrxLfWHhHmiQj_xOTKcDioZAeGgDDLCM1S9iyjgwG8OLbVTs2LrS5NtLgrDtGpRCO5m
PPG182Um9v3BuDLy0G
}

sprite $KnexdotjsLg [20x20/16z] {
NSg5RS104031jPzn--ysEYay3uTyQZ3unudmmmJ9AN0h4DQ5LmM4OC4BryhZOGzWg1x3YkmXg8vNL3EVZZxJTtsswWKSpO12yTbwZ2sMiQaTcWP86Xv63AGu
tYlRfPS4w38a3z09IydIzE6JORbL6-5wjQYU76a66aJK2aVoGpW7qFZbqtoWMWKw_B3W2uGF
}

!procedure Knexdotjs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/K/Knexdotjs', $name, $tech, $desc)
!endprocedure
