@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2024/bootstrap')

' loads the Item which embeds the element AmazonElasticContainerServiceContainer3Card
include('aws-q1-2024/Resource/Containers/AmazonElasticContainerServiceContainer3')

' renders the element
AmazonElasticContainerServiceContainer3Card('AmazonElasticContainerServiceContainer3Card', 'Amazon Elastic Container Service Container3 Card', 'an optional description')
@enduml