' definition of the Item material-4/Social/Coronavirus

sprite $CoronavirusXs [10x10/16z] uwS3

sprite $CoronavirusSm [12x12/16z] unza

sprite $CoronavirusMd [16x16/16z] un_X

sprite $CoronavirusLg [20x20/16z] unzKO1G

!procedure Coronavirus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Social/Coronavirus', $name, $tech)
!endprocedure
