' definition of the Item material-4/Social/PersonOutline

sprite $PersonOutlineXs [10x10/16z] uwS3

sprite $PersonOutlineSm [12x12/16z] unza

sprite $PersonOutlineMd [16x16/16z] un_X

sprite $PersonOutlineLg [20x20/16z] unzKO1G

!procedure PersonOutline($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Social/PersonOutline', $name, $tech)
!endprocedure
