' definition of the Item material-4/Social/SportsCricket

sprite $SportsCricketXs [10x10/16z] Oq07VFn0Wfy5HF1p0J4_CuW5ve956T2P732Tx8m8K_YHZGG

sprite $SportsCricketSm [12x12/16z] Oy06k9b090U8uEVd1vDS43OZ0oS_cCF6pmDI2EHmGpLXSXWG70P6XEcC_1WS1

sprite $SportsCricketMd [16x16/16z] XSY50O0m4CNGuCxVVrfSwdtL2ma55aaDGBTo6dKun_Fvvq8dxayBJ6-WBC0Aa0Yz7MOmmqnRO5cK3IMU7G

sprite $SportsCricketLg [20x20/16z] dOu30aKX54JdsSt-L_kPNITS0rq8Sf7gAEN33mE-a3Eayk6K1LoCRrSA9tou-K4fAdD_hX6MSuRD9JCzPpeJ3hVSmdTky3at3081Cpd0Po4HSJwHSYHu0m

!procedure SportsCricket($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Social/SportsCricket', $name, $tech, $desc)
!endprocedure
