' definition of the Item c4k8s/Element/ReplicationController

!procedure ReplicationController($id, $name, $desc="", $tech="")
  C4Element('rectangle', 'Node', 'K8s/ReplicationController', $id, $name, $desc, $tech)
!endprocedure
