' definition of the Item c4k8s/Element/ServiceAccount

!procedure ServiceAccount($id, $name, $desc="", $tech="")
  C4Element('rectangle', 'Node', 'K8s/ServiceAccount', $id, $name, $desc, $tech)
!endprocedure
