@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-14/bootstrap')

' loads the Item which embeds the element Qlik
include('simpleicons-14/Q/Qlik')

' renders the element
Qlik('Qlik', 'Qlik', 'an optional tech label', 'an optional description')
@enduml