' definition of the Item simpleicons-14/Q/Quad9

sprite $Quad9Xs [10x10/16z] Om023dvM1X1WvWS140j4ieEPs0b-7hX220F2veGmcE1240O

sprite $Quad9Sm [12x12/16z] HOe74e0W40FjNVV_ltKkoS0ga3OKDyTW46V91zuLc1GVBdLNUqHVoRMdpbZrXnZCyZHPwxt97b-HFm

sprite $Quad9Md [16x16/16z] NOm50a0X34AnM-v_sf_sCxS1-D252GF7drPwTiHNaoo0wWhVbUqjP5ZhJAQrrksrYu_C_69Reu56-KlNojvQIhsNEDHr7_jPtW

sprite $Quad9Lg [20x20/16z] {
XOy50iGW30Hnb_-_jaYEpNcdmXAFU11QBrOy8Lid4aowCoUARet-P2l7xvTGsxQKt2gjah1nbNPheu9vgzMmOW2pROg6A2y3vivuB0jJ4umjjM5EPfdYgoaX
4wWVcU7LL3uptKlc
}

!procedure Quad9($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/Q/Quad9', $name, $tech, $desc)
!endprocedure
