' definition of the Item simpleicons-14/Q/Qwik

sprite $QwikXs [10x10/16z] 9Ok55S0m50AlxcN_RSE3Ytm109cFDkPFn-yMydt-3pVcbRhBhxH9fwqGPefR1W

sprite $QwikSm [12x12/16z] FOo50S0W4CHIzsR_QN67FmKsyoAlIGRGgO0V3hqeeBmV5Ln5h23V1JZRx0QV7XHmSfNI9uDxTwwft2vZwKu4

sprite $QwikMd [16x16/16z] FOo54S0m08IeUt__QIlX4iuU8W1J2ZUWpX4zsT5FWBqS63fSr01tTCTK-a8B_-i3-PqOKEEjgtgF-TO3h2c02X7gFtta3j9jstRyPQRXH_02

sprite $QwikLg [20x20/16z] {
LO-53KLH2CNESxd2_jD-mMcC5CUVWvG1uwOvp9hxX-QcgCRfhd9Xfoqp5NgsYJo0auFjdnss9azvENwkSa4NMKvTs6blLfDdsAcRpKvFhJReYWSM7qCcsTqs
HLWHPv5n_BqooBbGE6n_PMrq0by
}

!procedure Qwik($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/Q/Qwik', $name, $tech, $desc)
!endprocedure
