@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceOpenSupplyChainPlatform
include('azure-20/Item/Other/ServiceOpenSupplyChainPlatform')

' renders the element
ServiceOpenSupplyChainPlatform('ServiceOpenSupplyChainPlatform', 'Service Open Supply Chain Platform', 'an optional tech label', 'an optional description')
@enduml