@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceDataCollectionRulesCard
include('azure-20/Item/Other/ServiceDataCollectionRules')

' renders the element
ServiceDataCollectionRulesCard('ServiceDataCollectionRulesCard', 'Service Data Collection Rules Card', 'an optional description')
@enduml