' definition of the Item azure-20/Item/Other/ServiceDefenderRelay

sprite $ServiceDefenderRelayXs [10x10/16z] Oo08sDZOm3Gx0pixEuXYu63WuE00KK30oSb9q0G

sprite $ServiceDefenderRelaySm [12x12/16z] dOO50S0m40ElxKFYN_1Gm21ul5Lct53CxeOWi_hYp8PaIWAEBgPjVcW7

sprite $ServiceDefenderRelayMd [16x16/16z] jSk90O0W28NXXnUm_yBz52FaLogdVh7stjQn4JWEyHISln0UYwA0lp55JdJeB0nEelAZZvCltV

sprite $ServiceDefenderRelayLg [20x20/16z] nSZ70O0m3C10fTlxBqnSQ0l0_II-KyRMxwx0c2RBUi1SfcHjgz_FIXnBJCc28f0l2xJ2KbEYqbJ3MocryBC3

!procedure ServiceDefenderRelay($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-20/Item/Other/ServiceDefenderRelay', $name, $tech, $desc)
!endprocedure

!procedure ServiceDefenderRelayCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDefenderRelayLg>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceDefenderRelayGroup($id, $name='Service Defender Relay', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDefenderRelayLg>', $name, $tech)
!endprocedure
