' definition of the Item aws-q2-2023/Resource/ManagementGovernance/AwsOpsWorksResources

sprite $AwsOpsWorksResourcesXs [10x10/16z] TSor0SD00C30UuRzzmt7R5LNoQvfW08nqYF8KJVGlSNaHlHb8y-09m

sprite $AwsOpsWorksResourcesSm [12x12/16z] TKk30G0n38or_xvlrasEq9vWkn3jmF4GBoctht90erj1VyfrWmaEF33vrQtjNmVFp0e

sprite $AwsOpsWorksResourcesMd [16x16/16z] ZKu30W0n3CkyzF__dNhcN0LuNfxsa1dgNTRIytbyAMwD57etRpa98FVoqXsvCdW2MmuZm377V6vebjmIcp7PRAf7KHFRul9N

sprite $AwsOpsWorksResourcesLg [20x20/16z] {
dOy50WGW409HD_d_Vo-uxh2TJV1kp9xtY87g6vAfg_nClCy9E7MFjgi8BmNmEhdfLoDg0AUOAGQW5Q7hp31x8VGwidEYUmRY3xPkc2ljiJsUwkFSbrZdaHmr
yzZWjKvou7xCysiB
}

!procedure AwsOpsWorksResources($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/ManagementGovernance/AwsOpsWorksResources', $name, $tech, $desc)
!endprocedure

!procedure AwsOpsWorksResourcesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsOpsWorksResourcesLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsOpsWorksResourcesGroup($id, $name='Aws Ops Works Resources', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsOpsWorksResourcesLg>', $name, $tech)
!endprocedure
