' definition of the Item aws-q2-2023/Resource/ManagementGovernance/AwsSystemsManagerDistributor

sprite $AwsSystemsManagerDistributorXs [10x10/16z] LKo30G0n38or_xwFsiqHxbLpo9A3oFzK6n3qfpj9XWN9A_jFyK_qcVwvjRm

sprite $AwsSystemsManagerDistributorSm [12x12/16z] POs50S1030BlBSB--zQzSGL-ehiiQaVL2gBKO-zkj0I7X980SVqcPD2r9N1gLqB0vZeorH5HJWPjrGm

sprite $AwsSystemsManagerDistributorMd [16x16/16z] VKw35G0n36sC_VUjyNHNvYCe7oj_CLBQG-I5kkuu4SHu0Beh1Ww89OY3T3Ci2m_HkhnAvFgyty5uFX8mG3FOo-evAgzv5kOxdwzvWYRc1HUJzj2ohjK

sprite $AwsSystemsManagerDistributorLg [20x20/16z] {
ZOy73iH020CfMy3_V_1PMf2k9quV8cpBN-KNXbii1s8y0-Uk1UF4cc1AQvTJfFD6ATcEok0ODUKEJcoVZIOhjVopbYtK_kJJ3et3DhTIOLYY2roMwNesYsX2
uC7LpPwxDTCdjhH3DxEdIYkKR6IJ_XTLvbaghGS
}

!procedure AwsSystemsManagerDistributor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/ManagementGovernance/AwsSystemsManagerDistributor', $name, $tech, $desc)
!endprocedure

!procedure AwsSystemsManagerDistributorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsSystemsManagerDistributorLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsSystemsManagerDistributorGroup($id, $name='Aws Systems Manager Distributor', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsSystemsManagerDistributorLg>', $name, $tech)
!endprocedure
