' definition of the Item aws-q1-2025/Resource/Database/AmazonAuroraSqlServerInstanceAlternate

sprite $AmazonAuroraSqlServerInstanceAlternateXs [10x10/16z] Oq009YZDoS3A2QHO6TYOu7Bai3YP880J

sprite $AmazonAuroraSqlServerInstanceAlternateSm [12x12/16z] Oq06d8mmmCR0oCZA317bO61aOs9bO6PYO6K3ik6ggSTcuu01HW

sprite $AmazonAuroraSqlServerInstanceAlternateMd [16x16/16z] nSSt0S1040InsR_C7x13uqJ0wiIN-c6WUKewPKQp152qR1cOMSKwpzF_7nvaa7KpTW

sprite $AmazonAuroraSqlServerInstanceAlternateLg [20x20/16z] tSX70SC0302nyxRv0-vkDeBeAIvbprOBfB8tq0W223ygJ30291s9PwioL2cAM0GL7fy3O-DttE2QWn1aT2S6GFRW2G

!procedure AmazonAuroraSqlServerInstanceAlternate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Resource/Database/AmazonAuroraSqlServerInstanceAlternate', $name, $tech, $desc)
!endprocedure

!procedure AmazonAuroraSqlServerInstanceAlternateCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonAuroraSqlServerInstanceAlternateLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonAuroraSqlServerInstanceAlternateGroup($id, $name='Amazon Aurora Sql Server Instance Alternate', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonAuroraSqlServerInstanceAlternateLg>', $name, $tech)
!endprocedure
