' definition of the Item material-4/Content/AddCircle

sprite $AddCircleXs [10x10/16z] LOo54S0m4CDSRb3xRvkp3wDdr0OCcOOvqy6M9Dajy4gXQQQNHQ2GoOLHUBf_B

sprite $AddCircleSm [12x12/16z] NSg30S0m54NHMxjl_sbZd-2JqVdiH9-y8wRH1iY97sV99rwNUTBCtkpGvgUY2MUlgJFDU1O

sprite $AddCircleMd [16x16/16z] ROo55O0m44ClkAMt_xIruF2HDl9Y_m1tjNbXDD7u3gNzX6UPSbl5qYgW75oD3FccDUsqzOQhh-Ikbwp7SWbjrR1CsH6JXdX9qPRA2liX0G

sprite $AddCircleLg [20x20/16z] {
bOu50iDG34AfVK-u_sad6ND_xRSOu3yA3zY2Avd2PuZEAmfctZ95Z466nzar_ZR6QzarjYgMSrwGSXuags8GLGF3btk2kP-607uxJmxN5xgwZwfSn1RUO822
jo4nTOKoRjdQA3FUimS
}

!procedure AddCircle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Content/AddCircle', $name, $tech, $desc)
!endprocedure
