@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element Waves
include('material-4/Content/Waves')

' renders the element
Waves('Waves', 'Waves', 'an optional tech label', 'an optional description')
@enduml