' definition of the Item simpleicons-8/A/Affine

sprite $AffineXs [10x10/16z] LSA54SC000GWAd7v_QUDAuUttY5YKnhjXgW3oRzlFrzy_w4BwxICw_wRMb7aD0C

sprite $AffineSm [12x12/16z] NSd50GCn0CH0cTdRVxN9COsUuik8YvWSqY1mqDPcp6fqdDHBbxOXqsIxHWDZPaznrYWGPKg18bL0wWRmwFO7

sprite $AffineMd [16x16/16z] {
RKt50KDH3EAv987zfwrxFpSSnoZwvW8_gMKmVN09q9lIBcps9yskZ7W7j6SBMDvtEaQ8hhpq_6eafPYyKiypBs8JqlMJKAw9iGpbVhigXZRI4aSn3BJbc-iQ
LhGcbyrsHw1y0MS
}

sprite $AffineLg [20x20/16z] {
VSp7aKCn3C1GY3zB8j5_jPlpsdupk897sia_piaVTMBmI_ZMBzKJQkE7NOu2-K4RvqMVVEcfW-l4nYTNbytMrptvu66jpjv7CtYpI6MDeLM7l35YdJO6DVG4
E9B9CEb6pn90A8PXTe4iw8Euw7av6t6LDeHgz9dnCTkgDf33l88FRlx73Sy
}

!procedure Affine($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/A/Affine', $name, $tech, $desc)
!endprocedure
