@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-8/bootstrap')

' loads the Item which embeds the element Algorand
include('simpleicons-8/A/Algorand')

' renders the element
Algorand('Algorand', 'Algorand', 'an optional tech label', 'an optional description')
@enduml