' definition of the Item simpleicons-8/A/Altiumdesigner

sprite $AltiumdesignerXs [10x10/16z] 9SR10K1040Im003RVxLmarTW5TNhPLOgempPhitbp4fFTZ1cYXD62bu

sprite $AltiumdesignerSm [12x12/16z] HSY54G0W0810x7R_RUtWwWy08xbLADSu0VbOJUdj8H3RcFoS-GRpNC5UAmAaxG9ARQOxEm

sprite $AltiumdesignerMd [16x16/16z] JSTN0i8W502miBeUwFrFwvOsVm5khdfMZhDh2aIP9rRqyqbFrFypTEdt0VR_aQDVV-VoN17dLxRACPyZiPTvKjiHymDj0omzaOOf3NDF

sprite $AltiumdesignerLg [20x20/16z] {
NSz50iCW5431mQB8_M_RJTj0tdBG3xWFhqgbHdEZHyI-c5ZXE6TJZnj6cOsQaSDYmY2adwKMm35PndujXj12VLdRMArSl6tyfbYjHiGosNbNj6pTvpZXDjc0
lVfRg0c_QK3klsdcpkCy_Vi
}

!procedure Altiumdesigner($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/A/Altiumdesigner', $name, $tech, $desc)
!endprocedure
