' definition of the Item simpleicons-8/A/Apacheant

sprite $ApacheantXs [10x10/16z] Oy09M60CFdueWv-VdnT4CpE3A5Qm40idFoCZ0nC_673pOpK9

sprite $ApacheantSm [12x12/16z] Oo0Uy2Cn-NaGJ7we10ix5v3aP0OIZ0oy34nCZ9mWUJv-4E3W1miJ1

sprite $ApacheantMd [16x16/16z] hOp50SDG34FbpsZjFsqRfblWcH5VqVLKahoKh7kPAkk-uAABOypMBcC159AdWWZCFR6molIfSYIowBHWC2DumXy

sprite $ApacheantLg [20x20/16z] jOx50K0X3CMAEzb_s-_AcQ3r9nEneojX_guERNJ1nwDO-IMst4WvFud6cj3ACSVPit3TGSIjAvsIrfTiTHAIIafMD5WsIYH2F5oLWxxwAtkYamijSrW

!procedure Apacheant($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/A/Apacheant', $name, $tech, $desc)
!endprocedure
