' definition of the Item aws-20210131/Resource/LoT/IoTAlexaSkill

sprite $IoTAlexaSkillXs [10x10/16z] HOor0G113CFwiwpiF-qpf8bPdXF7rX76a3XWqWQXwGpfWnelLyFTM2iE_yg_l0C

sprite $IoTAlexaSkillSm [12x12/16z] JKx30G1G23td_QVzo7OzuwONQXA_qDIBtwcIayTCdikFNydisHLppfYnp_WkO-m-G-Gtzw-DuG8

sprite $IoTAlexaSkillMd [16x16/16z] NO_L0SGm34E_Qmlst_OY7LU5v9bjyKUoPl7HZhYEf1vBui16E8p3mSRYnN4I-PKrcnezohijbkh_lB_ntXV7iJ9cMAvdSLtmY-EBDtoVzxxFVTy7

sprite $IoTAlexaSkillLg [20x20/16z] {
TT3L0S0m40BGxt0SxBzjgJlrLqkmzOXjuX5QQDz2I5XFkrlhsMOgeBBrnGfaTvI74GGYMRMPaCjSA5YRTMpzpo1q6BTV4hqRDgkB4Gi9nFKVJeYgsrXa3a3N
CQCung0FSsCa9IT_7V3LrLUdNzrF
}

!procedure IoTAlexaSkill($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/LoT/IoTAlexaSkill', $name, $tech)
!endprocedure

!procedure IoTAlexaSkillCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IoTAlexaSkillMd>', 'LoT', $funcName, $content)
!endprocedure

!procedure IoTAlexaSkillGroup($id, $name='Io T Alexa Skill', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$IoTAlexaSkillMd>', $name, $tech)
!endprocedure
