@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-20210131/bootstrap')

' loads the Item which embeds the element IoTHttp2ProtocolGroup
include('aws-20210131/Resource/LoT/IoTHttp2Protocol')

' renders the element
IoTHttp2ProtocolGroup('IoTHttp2ProtocolGroup', 'Io T Http2 Protocol Group', 'an optional tech label') {
    note as note
        the content of the group
    end note
}
@enduml