@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-20210131/bootstrap')

' loads the Item which embeds the element IoTOverAirUpdateCard
include('aws-20210131/Resource/LoT/IoTOverAirUpdate')

' renders the element
IoTOverAirUpdateCard('IoTOverAirUpdateCard', 'Io T Over Air Update Card', 'an optional description')
@enduml