' definition of the Item aws-20210131/Resource/LoT/IoTPolicy

sprite $IoTPolicyXs [10x10/16z] VS6n0G0G00In0_Zz1mP09U5A7N-MomD2Nic3G5OXCXXU5G

sprite $IoTPolicySm [12x12/16z] JSp70S0m3090m4tilt3YxbDzWPU6-PF4nfplBztVqK_qJRjlGEmRi2qPhEt_XTQCKhiULZ15AGsl3m

sprite $IoTPolicyMd [16x16/16z] XOk50G0n20CJYku_yBlhLOdWZuePNUQasFZwEgFqD5Fyx4CkUPi-bHLJtch90RMymu_L0CeukunfqSmCf4QRslHXT9IRZz26b1ChOzqLE-96tEW1

sprite $IoTPolicyLg [20x20/16z] {
ZOo50O0m40Fxdko_CEvwKFj8-ulLWgupoWAsMKE_1lOpeO-tBr_Fcq_FVSACOEnzyvw-wuD4p1B7r70lLwBSlP_vv2NwQsGn-dVETL1XHAGrP4RszFUrRuDo
6RM-f01jl-a
}

!procedure IoTPolicy($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/LoT/IoTPolicy', $name, $tech)
!endprocedure

!procedure IoTPolicyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IoTPolicyMd>', 'LoT', $funcName, $content)
!endprocedure

!procedure IoTPolicyGroup($id, $name='Io T Policy', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$IoTPolicyMd>', $name, $tech)
!endprocedure
