' definition of the Item aws-20210131/Resource/LoT/IoTRule

sprite $IoTRuleXs [10x10/16z] Oq03d12AbPE1anCk16F0c1mCB50c2n2pusHnCZ4m0zK1

sprite $IoTRuleSm [12x12/16z] XSQr0SD0400mFV_jFt1YXiggv6qKKXbWTdAPTcKafzooqpJjQbBbl9_4TLyNSu4_

sprite $IoTRuleMd [16x16/16z] dSv50e1034FHTAH9xdzWt6757tsxuYFBqosrpOItUqroe9eTHvqDjtmNAPsa5LJkR3tG45bsHvVKw-7ryzjr7JG3UsbxvGW

sprite $IoTRuleLg [20x20/16z] lSh50KCn30DGcQtz5-vdphKlOCH8avXLAtQ5m8G2ddkMhrv4JhMHL5nL9Lw81ykPuigfqtDSL4mtBUgorJ9zW53FNYGddNNfELP_xe5BOKrSQ7X421O_

!procedure IoTRule($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/LoT/IoTRule', $name, $tech)
!endprocedure

!procedure IoTRuleCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IoTRuleMd>', 'LoT', $funcName, $content)
!endprocedure

!procedure IoTRuleGroup($id, $name='Io T Rule', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$IoTRuleMd>', $name, $tech)
!endprocedure
