' definition of the Item aws-20210131/Resource/LoT/IoTThingMedicalEmergency

sprite $IoTThingMedicalEmergencyXs [10x10/16z] Oq01h9oSd0oeW1C4G58Cd0oCG0oYEHaPs80a6B91QAWwJcpc0G

sprite $IoTThingMedicalEmergencySm [12x12/16z] LSsd0G0W4C30yFtt7vYgY3eN_fpH_fZ-QWZdLG77Yb4mZiVne1qTo7RZ3WZR3exjWkBuTTprok-x

sprite $IoTThingMedicalEmergencyMd [16x16/16z] {
PS_50S0m40D1AOVgl-0mUtzZDZ0MQ8Xk5oiKoghmdRXp0balP-xp5LlQvrk0emfOtRtFUucLnxoqcM2lNi7OrtDVFn5UcxDtXoDMQs_ty1xuKsq6WqrDuIJs
70tX-Dy2
}

sprite $IoTThingMedicalEmergencyLg [20x20/16z] {
TP255O0m44Dpv7J_XNard8z7gE0F1GtLZmDxQNb3qGYSZ2_tkvREuTHYvCYc0HRipw10RMWfDfwskbObLTliLZKjH23EQjy-SxIICDnoRGu6t7B0Hk2UMvov
a_MLDytHqCY8ZEg7o-_-0OGGte_63W
}

!procedure IoTThingMedicalEmergency($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/LoT/IoTThingMedicalEmergency', $name, $tech)
!endprocedure

!procedure IoTThingMedicalEmergencyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IoTThingMedicalEmergencyLg>', 'LoT', $funcName, $content)
!endprocedure

!procedure IoTThingMedicalEmergencyGroup($id, $name='Io T Thing Medical Emergency', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$IoTThingMedicalEmergencyLg>', $name, $tech)
!endprocedure
