' definition of the Item aws-20210131/Resource/LoT/IoTThingLightbulb

sprite $IoTThingLightbulbXs [10x10/16z] Oq01h9oSd0mOW1qinS360A61AY0OHBB3MOnW5ZRp

sprite $IoTThingLightbulbSm [12x12/16z] LOt50S1G24FVDo3xBrpaL5mJ_l9OiYdzZYYd5-GvZmSNzM70kfd9AXQwcKL6ONMlka_F-inLrZsQMZ5YFzuF

sprite $IoTThingLightbulbMd [16x16/16z] {
ROn15a912CF2dpBG-r_O1wehiw9j7lmXQHpIDrOwVQjI6-5Bngo0kZmvjViHqEpUtXEUGtRjlZcqkmtvuFNTn0NkiMFwG0NG_lxVZ7qdwq1klZqv0EMFPeYC
3ZzIm2AAZdC0NW
}

sprite $IoTThingLightbulbLg [20x20/16z] {
TP35eK0X30G7ulqN_2NFRVV44ETBYYZLtcM8NLd6IQdDWhCSC6iM6TKXQNEDg-Qwnea4J8Fr9sIW_xa-zrfxhWdYa2kl2lfLQ-MojOVcA2qkSSGiXqiSukxS
uaPLtUD6UkrnaEpQcNfwf5VRn-VzG1WJQ__h5m
}

!procedure IoTThingLightbulb($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/LoT/IoTThingLightbulb', $name, $tech)
!endprocedure

!procedure IoTThingLightbulbCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IoTThingLightbulbLg>', 'LoT', $funcName, $content)
!endprocedure

!procedure IoTThingLightbulbGroup($id, $name='Io T Thing Lightbulb', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$IoTThingLightbulbLg>', $name, $tech)
!endprocedure
