@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-6/bootstrap')

' loads the Item which embeds the element ServiceWebSlotsCard
include('azure-6/Item/General/ServiceWebSlots')

' renders the element
ServiceWebSlotsCard('ServiceWebSlotsCard', 'Service Web Slots Card', 'an optional description')
@enduml