' definition of the Item azure-19/Item/Devops/ServiceDevTestLabs

sprite $ServiceDevTestLabsXs [10x10/16z] LSQ54S0m54Cn5_t-UVzvov3eIEhO_dBLjqK2l2p0EVwbpadhcgoZJadg2XVj

sprite $ServiceDevTestLabsSm [12x12/16z] NSQ75KGX24JHCGuS--ztIVlJLU3Xev7irNGDPZDPyWA8sMjjEz6obbnzJZIeQaqL16j5uZ6CR186VW

sprite $ServiceDevTestLabsMd [16x16/16z] ROu55a0X20JjnRVtFw_A_eunnm32Bnb0lhJ1QOScwV4YukIb-c52kjRJQwtQB1Tl9vlUhGzzuUxhLfnP8mseoqJbeeM3Q7mSWAAdmw_w9W

sprite $ServiceDevTestLabsLg [20x20/16z] {
VT050iD024HH8ZD0kVzz2x6Loel_-CeV2uXjJ7gQqXptf-4gq4wxhq6xgfDljvEYM7cQCPDQmPT6uNspkvvjRm-CyBD9CY-ibbjRv02IULsGMALXf1TbIidH
qkvnidQlDMsKcpnw0m
}

!procedure ServiceDevTestLabs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Devops/ServiceDevTestLabs', $name, $tech, $desc)
!endprocedure

!procedure ServiceDevTestLabsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDevTestLabsLg>', 'Devops', $funcName, $content)
!endprocedure

!procedure ServiceDevTestLabsGroup($id, $name='Service Dev Test Labs', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDevTestLabsLg>', $name, $tech)
!endprocedure
