' definition of the Item aws-20210131/Architecture/InternetOfThings/AwsIoTDeviceManagement

sprite $AwsIoTDeviceManagementXs [10x10/16z] 7SR70SGm40En2oPdG__zcX9UwAu3w1IV9fPac3PtDOt-_-VEVlxM6PRiB0NJjJDJrR5fP2y

sprite $AwsIoTDeviceManagementSm [12x12/16z] 9SUt0G0m2CJ00lY0zv_N2LKdsthnvZ_yyuWgKC_4zJsn3LqbI-e6Co8m1YAgnaGcy2sG12YjRd_PNdVQq_epUm

sprite $AwsIoTDeviceManagementMd [16x16/16z] {
NSZ70SCW40LHXvyMzT-l1QoJvlQcphBpxCTPtaFo7eicYNcMGudh91vLT21HXfCnYgNd6S9sW6czRKsRsuEH0KbV4q_IxKYfiYPpZ7aeqpKxrYXFBS-nQb_6
2m
}

sprite $AwsIoTDeviceManagementLg [20x20/16z] {
RSm7ieKm34FH6InPijd_UY4P__8AbvgJKYl_fgaUi1wm9Wl8mLyJaJcgCOzmLEfbI0iIwOoDtMKi9i2GbzlTRLOUF087p1mh6eWTyiMeJHHV34OWb2zMJ4Ma
Niv3EWc24ZJMbLIjXFsrpzwPjBbavtEmHwRp5xlwnJPEl_Q0Dm
}

!procedure AwsIoTDeviceManagement($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/InternetOfThings/AwsIoTDeviceManagement', $name, $tech)
!endprocedure

!procedure AwsIoTDeviceManagementCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTDeviceManagementMd>', 'InternetOfThings', $funcName, $content)
!endprocedure

!procedure AwsIoTDeviceManagementGroup($id, $name='Aws Io T Device Management', $tech='')
  IconGroupElement($id, 'InternetOfThingsFamily', '<$AwsIoTDeviceManagementMd>', $name, $tech)
!endprocedure
