@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsPortableWifiOff element
include('elements/materials/Communication/MaterialsPortableWifiOff')
MaterialsPortableWifiOff('element', 'Portable Wifi Off', 'an optional tech field')
@enduml
