' definition of the Item fontawesome-6/Brands/Angrycreative

sprite $AngrycreativeXs [12x10/16z] ZSP70S1030InzVK-_Dd60DBqalw9BDps7c_RIyqVYjbW4Wb2M6-vmRG3kt2af0SN

sprite $AngrycreativeSm [15x12/16z] bS470SD04C0m_zvd_cnBeP7uBC6k4KS04Hag0ECURQuL0D9J1Sz4UVh4QwLb9Rb5FLWawYWvyPSV

sprite $AngrycreativeMd [20x16/16z] {
jOs5eGCm20KVn0Lk_sc_P8Rs4jpqBTnl3U8SFR8j56b_EecNiatkWmFewX60672WeaUeLwlQ1K2P2229QWXnBM5N6IUub86ofQ7e1ipPkUz2wcp5rN1tqsVu
1G
}

sprite $AngrycreativeLg [25x20/16z] {
pSY5OGGn34JHaRr6mU-_sd0BIUw9fLTWKjUAPm4-ukSR8ROWDuoLe1-5e85ka5ZTdtzE7WuWGRdIz0s84hjWej2HMPDqZ_hizdnqXt1q4pHW0PLNqEWv48FT
K0D1t1u8LQl3vjIM19VJwx8GSippUbaMJ71MW51tZMxosbhMcvd-t3i
}

!procedure Angrycreative($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Angrycreative', $name, $tech, $desc)
!endprocedure
