' definition of the Item fontawesome-6/Brands/Dochub

sprite $DochubXs [8x10/16z] umS2NWO61duGu0FHG0uVFuJcuEG4qq0UNfeV3XW

sprite $DochubSm [9x12/16z] umS11Y20CBX037P69WP-DY235IpE0c60sQmGYY237MmS7ny_I3i4S34

sprite $DochubMd [13x16/16z] bSUr0S0m54D1_J0fR_zfms2NlkwuwV9cIMFkL3eOil0bJdTEjly0fOaqAup0qBRj321-VPAGTW

sprite $DochubLg [16x20/16z] jSUr0S0m00CmbyF-_zemxzKcLXO56uZjJhMhICDHrYDpfDfEELt8w2ulZkF0V9BwvylfZkJP_p815yzwYVdw01

!procedure Dochub($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Dochub', $name, $tech, $desc)
!endprocedure
