' definition of the Item fontawesome-6/Brands/Ember

sprite $EmberXs [12x10/16z] ZSQr0SGm04MnRsQ__QSz25O1LTAjMizlRRaMJt4GwXJ8W0KrBmrCw45lV04

sprite $EmberSm [15x12/16z] fOb50e1030EtBGv9_lzQN4_ON2AJ7i7hzCkgjPQojQX8HGUhKoCsq2XpeJ6aLaWXgkHOVZ4

sprite $EmberMd [20x16/16z] lS6r0GCm00D1cL7-_RTD5Iu3T_gATlI6gJS3tUIi75N2xbBh2bKAqwcnNBnQpOIDfdUTiCO8gU0u3Qe-T7H8S0nHBuB-vG8

sprite $EmberLg [25x20/16z] {
rS59OiD024N1Bz04QdZtlssMIUnUUgpIarXeZjRKkQ4fl3NLvVeZQE7jBK0gXdgO98GtJObbXFLIAvWoGKaIOQNOeb1Ye0qFEDYkaGiqTb4oISaHxYciEAH1
XBxF3m
}

!procedure Ember($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Ember', $name, $tech, $desc)
!endprocedure
