' definition of the Item fontawesome-6/Brands/Figma

sprite $FigmaXs [7x10/16z] JS770O0W00ImsBkt_xGAl4X8mGQlPf9bMzQuEKKp2cbxh-07

sprite $FigmaSm [9x12/16z] LOg30G0n54FVcMtsdxRcPmI_GjqWk8ZloC1Ygx8h5Kbvfem2K5GU-rk-8FxPIlTBGFiX00y

sprite $FigmaMd [12x16/16z] TOs54GGX40Jxt8QT_BFzmik-OTrW3MS4FB60OJVP31NJd_bJB9PaAGnlRhBPlCoUvS_iaLYS93liV7TTLxCmMpDpjfdderB7CZy

sprite $FigmaLg [15x20/16z] {
RSw53GGn44DHBqzeVl_TteQEBSNI2qioUdoxiL3CZ6GMo9BVu-wzDflGYo5zqB8ylCYX1J-FmyDn64WgU2c0EvUKQ9jPf8LbNXLgvpHvrBwos1jBRKmdPoMv
NgfQDLUcpiYOtsXX_QJ-a6KmL3kQYK2PU
}

!procedure Figma($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Figma', $name, $tech, $desc)
!endprocedure
