' definition of the Item fontawesome-6/Brands/Foursquare

sprite $FoursquareXs [7x10/16z] 9Og50G0X30DVSRZzfwrUlSar0rW6rClmSI2l9yVl0tYe1_Tiqdev2W

sprite $FoursquareSm [8x12/16z] O-060ov-6E1b004K6Y7EnmUX-Tc1D2DGb058y_FmS0DfY0n8348pW04

sprite $FoursquareMd [11x16/16z] JKt50G102DBhPlzfhukNakJZXaluG0lkdV6Tsp2DPPwv5C0SWmITC-vJQurrpfaqJetCpDHFFlPlUbxdrETi

sprite $FoursquareLg [14x20/16z] VSUr0S1040InFJDF_zMQwL6Pr8oVgiCptUOZhHwPrKpN5axTDIx5iKi1-cREwczcDjFTurHSkpBht08wd1kkN9l1la6jR_HwpKpwR

!procedure Foursquare($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Foursquare', $name, $tech, $desc)
!endprocedure
