' definition of the Item fontawesome-6/Brands/Maxcdn

sprite $MaxcdnXs [10x10/16z] Oy06-660WHtE0Y8GveAne8WJcGF4RFoC41OdmZW

sprite $MaxcdnSm [12x12/16z] Oy05-E60WO4RcOE4sH1i8EA2yO68aO6FduU12Snc0F51PY1fPU7XvuDhHGO

sprite $MaxcdnMd [16x16/16z] XOp50SKW5C1ITxB_j5-AtiXpfSVQ011i0RG5r6rTrNNBDOpwm5tgKvUOpdh6BFgW8x4Ur6R2hdlC5htXYU_YuoakxRgrxtfy0G

sprite $MaxcdnLg [20x20/16z] {
fOx50G9154FVZllqNoqMt65p-HfX3SQyHGRil0Vmi6iGdpnclVjTCVe0NQWgvRGRwAIYNRdPZKCM2ykk1FHn45ZEJleOLpgokDL17nAuTGe7EUbebqcb522e
s5rP-1PR
}

!procedure Maxcdn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Maxcdn', $name, $tech, $desc)
!endprocedure
