' definition of the Item fontawesome-6/Brands/Opencart

sprite $OpencartXs [12x10/16z] Oy05cFcPaRcy_1209CIFbSa3fL4b-T7P

sprite $OpencartSm [15x12/16z] Oy0FkDXH-OpyOC37nyVBpGmN108kVdvKZHmeN5O6me0HGa01Bp-GYJ2K2SHYXt01

sprite $OpencartMd [20x16/16z] ZOy30a0n241dnFkVzjlS6tEP1yAJKXwLx1_2TK46cAgTrTOLG29Y7Rb5kGUTrwO-wbsLxYfx-yxF3CxbLG_3ywhBPcV-kxL03m

sprite $OpencartLg [25x20/16z] bP250S0W30HnXzz_sheNFPnuI0bMbDYYIU852GMYp8iCJj9AZC7fKoOSFcITkrMG1Q25V6Z1WEI9W_-Iz40_bnCBYFKKmBlP2OZh6O6KjP2hHIl63

!procedure Opencart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Opencart', $name, $tech, $desc)
!endprocedure
