' definition of the Item fontawesome-6/Brands/PhoenixFramework

sprite $PhoenixFrameworkXs [12x10/16z] NSR50O100C2mud3M_QV5FQ_mPf5Ben8uk0gGpbC2L8030MGdjM8ba4FcCJBmim

sprite $PhoenixFrameworkSm [15x12/16z] ROh50SGm0CCSvcZ_QG_BhJv6NV1GpX6qmnVBALBx_9_-Pvh-V7zyw_3FiqXK7udzltiZh_Xr-WB5wOG9Uk0D

sprite $PhoenixFrameworkMd [20x16/16z] {
TSq5aeH044JHtmNjalS_xUuO3YyievHxipyLJ2D8EbNrGJKsjXGRvq45xwoEigkPQVOrWsqrmBCPYfY-YOKw1FabVlK8KHgeGIlVchawSrAacXmdRlbxqdZs
3m
}

sprite $PhoenixFrameworkLg [25x20/16z] {
XS_5OGGW54NHYpkl_seZI3mpPuD-un5Z-4EIkYH-CawRWv_koz2Fb5ERYSfyrNJO293xpLgrZ26_jhrxbg85l9Hu5rYSf35NMmQmbakQK7N2sxSPWQw0omw6
B4TMkcrF9EpK7R_arMYrTkJrjTwGTXFyu2JruWr_oCbYBNzpW_yqdda5
}

!procedure PhoenixFramework($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/PhoenixFramework', $name, $tech, $desc)
!endprocedure
