' definition of the Item fontawesome-6/Brands/PiedPiperHat

sprite $PiedPiperHatXs [12x10/16z] Oy0EU11CFWIJcGd1veVH_8niS2O_GXJ4OmKncRZvGG2cW8s1cH781

sprite $PiedPiperHatSm [15x12/16z] VOo35S0034JZrBV_jBNr7u_qHtbHpKLr5oMuIEHU0oWEV-AiX9XNLS4neRDYh6mlZT76

sprite $PiedPiperHatMd [20x16/16z] ZSl50GCX04HHtE7tNssoxlQE8-8RUuxIEMeNaJn53d72-LfsimPqsIQHzFP7UYKSeYXTQIshEKeKpMYTDIPUz4AbTvZvwCJU7m

sprite $PiedPiperHatLg [25x20/16z] {
bO-50GGX3C2AEzb_slTJU0iUh9L_qMzyU-FB6yyRtyFSvtSNu4r0pB_MW-z0lGtgg3qFcZdvm8jwzEeXWvf424eg3muf4QQFqJeiB5Bf-B0BQTbOH8ktIBNF
ig6Kaf4h
}

!procedure PiedPiperHat($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/PiedPiperHat', $name, $tech, $desc)
!endprocedure
