' definition of the Item fontawesome-6/Brands/Pushed

sprite $PushedXs [8x10/16z] 1S470S0m00CWzcyJ_suB0FZxhE9C--ys10SWyS7E1Vp0K-034m

sprite $PushedSm [10x12/16z] 1S670S0W00CWkjoQ_xyj003tJ6Z9A9V51xWVWN3iZjjXN4m1iGuOsW6E02u0Dl03

sprite $PushedMd [13x16/16z] RSQv0SCW50Km-RQ1pzj_stHKKIL_REy0JwNkJM6URw_C_cRZUe7Bjhy21949JYRVVc8Gs2UwWA7S0fHF0jXPvrEM69Qd-US7

sprite $PushedLg [16x20/16z] {
TS65WO0m50Mm06tn__QVzjmbyQzvyQvVIVPzndGdjJSeAEPnL9vTMzDlW7sQvkMI1L0G5M1P4Ov-W1l1lDyJd1GeXNCIu3O64K1RnBJ6kzjqLcRlmXMVZics
-68NNzKoV7N6lnu1
}

!procedure Pushed($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Pushed', $name, $tech, $desc)
!endprocedure
