' definition of the Item fontawesome-6/Brands/Themeco

sprite $ThemecoXs [8x10/16z] Om023WOGOE7dvmTI_EY0bOUTdmD8StCnCO45-4081XWWJ7QWJh1-

sprite $ThemecoSm [10x12/16z] RSq50S0m0C2mdldrh_QCss8Wx5fEdPe1cISwKp8op6QrBCXpKMipnO_C6ypkpaO5LW

sprite $ThemecoMd [14x16/16z] ZSV50GCn00InDREd_sh3d2FzfBkijma4tMNkZ2JBorJXk5dhIALfcDjo7jQEZhsjGOqeMpQPhqcL9wShReeUB4nTdG4

sprite $ThemecoLg [17x20/16z] {
dSE53SGm44N17pJj-lLVRHX51oED3h7Hqm2ORkoATeNB82dmeiG_nY4o38PrnaPu5fttIrOgWwbNS3ooabTaNUsyhQniwn3vIiERIyP3hqLJEIGTHbPL3nbQ
RMO
}

!procedure Themeco($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Themeco', $name, $tech, $desc)
!endprocedure
