' definition of the Item fontawesome-6/Brands/Vnv

sprite $VnvXs [12x10/16z] bS610S0G0C2mRW3G_x_r0WcFnWAtKH3PIJGZK-qOb1i7

sprite $VnvSm [15x12/16z] hOC55O100CM6st-iVrk8S3PX79kmUol2loTkpe_AAwiQGLJW2PdWofQDAZu

sprite $VnvMd [20x16/16z] nOo50O10203FBl3stzPd1klev2UEB1z1v4fEm9GOq9cgem9AnLCCT79cSG9pDfIgj5TgIJ417Ue3ZRvlHb59n-DS

sprite $VnvLg [25x20/16z] rOo50GD120JXzNpwxnQ9jP2V4tHN7eR-Wch6H3j4xAmTHo1NCjizWusWTeQNm__6YcIT87ikvfx6TsWAhiZBOCfafhqpGo0f8P1WHX82Pt7Vk4x-50C

!procedure Vnv($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Vnv', $name, $tech, $desc)
!endprocedure
