' definition of the Item aws-q1-2022/Resource/NetworkingAndContentDelivery/ElasticLoadBalancingApplicationLoadBalancer

sprite $ElasticLoadBalancingApplicationLoadBalancerXs [10x10/16z] JOgr0G0n08I82_lF-ouvgO0rFYUWCa7kZ8zttaGWI1En6MDFPF1J6JsQOGS

sprite $ElasticLoadBalancingApplicationLoadBalancerSm [12x12/16z] LSh55GKW302mb28Fkl-ytpNd-1SrsYem8ZBJ329if4MnyuPbGC7Hl8vZcQP2AMDbwxKbSxPfZdaG2nnWrQd45G

sprite $ElasticLoadBalancingApplicationLoadBalancerMd [16x16/16z] {
RSg5OKKn20NGGtWIOFzvwzwFNlEeSgQd0n2pm5KWMjHBRT4mh8KYRd9zSyKWzfwz8JLKJHMKvZkl3TVkrrEujUYxw-t845VcLAteNHeLrt5TNi-Pq04uB-0k
o4u0MNq7U0O
}

sprite $ElasticLoadBalancingApplicationLoadBalancerLg [20x20/16z] {
TOm5WWKW24I759dxttSNVzUpdXH-4zNiPSyHEePDmPLEtDXn3Gd0mmBQJsDE74FTZ7Y9sGR2JwA6TQqfNE7rBRjsDOSSjG3nEW-QvvVT18npmnrhOeA9BKoC
0jjOnIhgxgh69OxbBALcbMsa0v2jcPQ1p7-Hnk347Rcvjrqj6tSsozH9npCMwNBrFm
}

!procedure ElasticLoadBalancingApplicationLoadBalancer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/NetworkingAndContentDelivery/ElasticLoadBalancingApplicationLoadBalancer', $name, $tech)
!endprocedure

!procedure ElasticLoadBalancingApplicationLoadBalancerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ElasticLoadBalancingApplicationLoadBalancerLg>', 'NetworkingAndContentDelivery', $funcName, $content)
!endprocedure

!procedure ElasticLoadBalancingApplicationLoadBalancerGroup($id, $name='Elastic Load Balancing Application Load Balancer', $tech='')
  IconGroupElement($id, 'NetworkingAndContentDeliveryFamily', '<$ElasticLoadBalancingApplicationLoadBalancerLg>', $name, $tech)
!endprocedure
