' definition of the Item simpleicons-14/B/Backblaze

sprite $BackblazeXs [10x10/16z] Om02PWOOO86p-FcX34P-Hdwu49p5nCy75-C7Cy0SHeGOXCNFniF

sprite $BackblazeSm [12x12/16z] Oq07V4XiVdvKDeB93sEYifbWghX1ulnGinZ1SZ0rA6ns7eHcFbuW3G

sprite $BackblazeMd [16x16/16z] NSh50S0W40LHt67whpOUxD_Ux8fdIcnZTrmeOJ6NpM2v66MdupAkcySiLXaMEqWZj2U-ylvftHBWTpzbK9yrKCKqHVy-0G

sprite $BackblazeLg [20x20/16z] {
PSx50SGm34HHcTc__seNmh7c-8Hon8bEzjeysZ8QqHQq6S08Ao7zPMCpC0zZiyPSpLgOYpa3XCiYW5Y0awROMepCfp6k3TVf1X1tUzreMobTrlSfwsHzSCJS
drWszRBb2m
}

!procedure Backblaze($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Backblaze', $name, $tech, $desc)
!endprocedure
