' definition of the Item simpleicons-14/B/Bitwarden

sprite $BitwardenXs [10x10/16z] O-3bXm0c1X39oihApGjcCJ0mS1B9ucS3OZ0BXDc0B1OGWm4c2W

sprite $BitwardenSm [12x12/16z] Os3XXm461ZuGnGS4C3O34931va9YCq3P72226yncuMTYW720kfWPm809gWC

sprite $BitwardenMd [16x16/16z] lSn50SC004FHDrun_jMMMK1p2troKEFiitdGtEpRYqzGRxx94rRVf68DI6eidDH9OTDx9Ue1

sprite $BitwardenLg [20x20/16z] pKo50S0m36Bku_zhwveyKAh1W8yzPW0K-1fk2tWw3W7NuDpDLt7axjqjjwItvSWxQPcRIWNsnAsLYWFnjbJfVD3X8Byf_Iq

!procedure Bitwarden($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Bitwarden', $name, $tech, $desc)
!endprocedure
