@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2025/bootstrap')

' loads the Item which embeds the element AmazonRdsBlueGreenDeployments
include('aws-q1-2025/Resource/Database/AmazonRdsBlueGreenDeployments')

' renders the element
AmazonRdsBlueGreenDeployments('AmazonRdsBlueGreenDeployments', 'Amazon Rds Blue Green Deployments', 'an optional tech label', 'an optional description')
@enduml