' definition of the Item fontawesome/Regular/CalendarMinus

sprite $CalendarMinusXs [8x10/16z] LOU53S0m0CEiYSR-_zeoXWC25xNbzizG2ewbrUrlZHKH

sprite $CalendarMinusSm [10x12/16z] Os1WO09YRWOWOEK54lmW30Si3130XuC5KSE7NnqFBoi4y3Dmyq40Em

sprite $CalendarMinusMd [14x16/16z] dSp50S0W40NHYNkc_shZ0aTufzKFL3sdbSii9mkWcNK-kSmqnlWbTeEdjokc4v2TYI4YEm

sprite $CalendarMinusLg [17x20/16z] hS_L0O0m34NHXpjt_sbnwfyvTMzqMLezjaOl-DgbEB4JwMVO0rmK6kmcTXwrcvXusBuIJWnfSDg8T4gT

!procedure CalendarMinus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Regular/CalendarMinus', $name, $tech, $desc)
!endprocedure
