' definition of the Item fontawesome/Regular/Message

sprite $MessageXs [10x10/16z] Oq00VXZWOOABmEIuyRFuO2nUa2aCd21JmFh1IW

sprite $MessageSm [12x12/16z] Oq06NFmmmCpC3nVbvsUd3XjX9YC_0oT82cmN8r20Xu-V1Im3

sprite $MessageMd [16x16/16z] lSor0S0m30313tD-_sd3QFU-HYmYxVoO2l1dwkIZLlbANXTMl2OPtUpPuHYEPbho63zVLW

sprite $MessageLg [20x20/16z] pSh50GCn4CLGBUDO_LSR9aC1URSFjFN3hnwOBO7EsUyqJdjogf0x_hvBGYuSJ6H69Rm3DbycMCvG28sxe-FXT579dEh4nnK

!procedure Message($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Regular/Message', $name, $tech, $desc)
!endprocedure
