@startuml
sprite $AwsApplicationDiscoveryServiceLg [20x20/16z] {
bP350SLG3CC-rF9pzj-tp3rLHuLJByb36E5Sb9XGkoXXX8vCi-R1xa18SsgktKpZA1QRFPpdMYEupRNeL3jDJ7I6ezX8GkIGk19I4Box9DDbqDZxJMJ-nNvp
Hkez0m
}

sprite $AwsApplicationDiscoveryServiceMd [14x14/16z] VOod0G0n30DHJfRttpVTwCinrVp70ha4coj5Mqf70MrfbmALqX7KIzjT7oK1n976baseRd1QSPVELmO

!procedure AwsApplicationDiscoveryService($id, $name="Application Discovery Service", $tech="")
  CloudElement($id, 'aws/MigrationTransfer/AwsApplicationDiscoveryService', $name, $tech)
!endprocedure
!procedure AwsApplicationDiscoveryServiceCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsApplicationDiscoveryServiceMd>', 'Application Discovery Service', $funcName, $content)
!endprocedure
@enduml
