@startuml
sprite $AwsTransferForSftpResourceIconLg [20x20/16z] {
XSW7OaHH249HGD6__nM79DFhVTM3hpMVo3kFQACVS5RWR50xIG0z0wzZPPArBa2nFB7EnMgLU35x9vMBKxlrRmL2DU9MjVzDUVeOmeVhnc3d3Eui47umj75h
1CXqOxBSDMtprgQOQqusssmF4PCc5dIh9K0KPE5bFm
}

sprite $AwsTransferForSftpResourceIconMd [14x14/16z] RSc55SC020JGKxh_nFLuyF_0VQJS8VfGjW4zp2bGoHKK1K1ans7IjrhBAPlg8m8JTBo8TRaA3F6NvNVyVqhYr1zbd4Ws-nO8uXEVzG8

!procedure AwsTransferForSftpResourceIcon($id, $name="Transfer For Sftp Resource Icon", $tech="")
  CloudElement($id, 'aws/MigrationTransfer/AwsTransferForSftpResourceIcon', $name, $tech)
!endprocedure
!procedure AwsTransferForSftpResourceIconCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsTransferForSftpResourceIconMd>', 'Transfer For Sftp Resource Icon', $funcName, $content)
!endprocedure
@enduml
