' definition of the Item aws-20210730/Resource/NetworkingAndContentDelivery/AmazonVpcNatGateway

sprite $AmazonVpcNatGatewayXs [10x10/16z] JKo50G0W349i-VzUkzO1u3VjX9bh6LlKk6GSIpszkWL-F25mx6u9x9eJrIyD

sprite $AmazonVpcNatGatewaySm [12x12/16z] LOp50SD04CHq3DD_lOcjdxMCV2aPTSLq5CCiK4g6nOAGXYm6jhc4IkJcihZsWzAH1ZDzJd1S5fZAolNl7m

sprite $AmazonVpcNatGatewayMd [16x16/16z] {
RScteGD120N0uVRMGV_rVYDIJVICRqPLLeOMzO1rksPN8g7KrM8p7bKnvu5BiU208SdeNk5AwgxwboaLDVK_RSdM_J52B5KHSI1neqwizM0EoA7D1UmBetSm
Rku0lm
}

sprite $AmazonVpcNatGatewayLg [20x20/16z] {
TP25SGD030JtINJzrnluKT3s3eYHrvmebIz-EDe0f0PD6JHvsZKEtzI-XOOqVfm00dbAkXOhuMoGTKRdn9-g0x6k9gTz2jP1W4vAbpAVnergG6liZGERxrhG
OEN_kHsod7DU7xQ1aKZ3x1gC-lbACzJAhjMQ5T-aOisjBg1Pn_Pe_Hq
}

!procedure AmazonVpcNatGateway($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/NetworkingAndContentDelivery/AmazonVpcNatGateway', $name, $tech)
!endprocedure

!procedure AmazonVpcNatGatewayCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonVpcNatGatewayLg>', 'NetworkingAndContentDelivery', $funcName, $content)
!endprocedure

!procedure AmazonVpcNatGatewayGroup($id, $name='Amazon Vpc Nat Gateway', $tech='')
  IconGroupElement($id, 'NetworkingAndContentDeliveryFamily', '<$AmazonVpcNatGatewayLg>', $name, $tech)
!endprocedure
