' definition of the Item simpleicons-7/M/Makerbot

sprite $MakerbotXs [10x10/16z] DKe50G0W31lkqByjrzaLXF4g66zn338U8nOiFAPlYIJlgdU9x1mHZ4ikz9F87m

sprite $MakerbotSm [12x12/16z] HOg50S0m3CCqBCV_VxkL5OvD9SdJKVoRgQtu4CABwgg6FmgnUeGoIgmzQE-Fttl6jh-6goqu1pgeEAkzA3nP3Zu

sprite $MakerbotMd [16x16/16z] LSVL0SKm3C10bI6njV-q3ygzlsFJXwNX5EOqBZhkjR3Bs3hWfX8Lek1XnWP1IS5Avv3FOqplExwUPNdTnlTvVKx6H9a55mGYE3a2LBjjyrverDG4-08

sprite $MakerbotLg [20x20/16z] {
PSg5hSL05CHGtuq2Y-w_seylRD7eQFYKXstXqgosshN7JbgFbVSHn7_CbdyYt2CvmspWqKOMhA09tMWsS4CULimlmz7UPdrRwszRVDeaBnkTxiDCX3CQT1FP
J1V89iw601GpUtq_p5e0fg4SRVxL_q_V
}

!procedure Makerbot($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Makerbot', $name, $tech, $desc)
!endprocedure
