' definition of the Item simpleicons-7/M/Microbit

sprite $MicrobitXs [10x10/16z] Oy0EM400IFF303C_I1WimiF03wA142u6LyUApJ

sprite $MicrobitSm [12x12/16z] ZS750O100C2muaxtdnRdTvPGnCy6Md6hTP2VYZtWZBLyAj5bkcskCFbgY3a1

sprite $MicrobitMd [16x16/16z] fSgr0SGm04MnRsQ__QSz39K1rT9ZcPsLEhJwDy0Aj37GC8fEN-MNqLgeYYI2TXE1rQg0B4VwwAoABdi3

sprite $MicrobitLg [20x20/16z] jS7LOSDG0C10sNvCsd_QDapVoHs_i8SxRgQlAh3v2NHjF6KjX_Acw7117rmSwm3L0Sf5iu4sXNtdwe1DqSIhvQ9hsxUxeExWXmWGfazzu-l-0G

!procedure Microbit($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Microbit', $name, $tech, $desc)
!endprocedure
