' definition of the Item simpleicons-7/M/Myanimelist

sprite $MyanimelistXs [10x10/16z] Oy0B-A28du4V25Xuk9ZvWMm6VZv-VYYBWPsBXPyVloa

sprite $MyanimelistSm [12x12/16z] bOO50G0X00FtWilrJuiMWEdfKY2Sc3SNLtynRMfmm6O5bzz9QEdLgJe

sprite $MyanimelistMd [16x16/16z] hOc50O104CE2UxF_j3XCy2TL2ez2X2dE29fLYKp3utKHmUN6C4oY_fxfxxic6umX8JD9UAQYq1m

sprite $MyanimelistLg [20x20/16z] nSY50SCm44DHcTdQVzkguMG1V-CzB6fENNr2bKc0NOT48GqQEKOvRCju3PNki4HMca7d-cLeA3IJwZP0blNMZu59va5bhSpeccrxhCAYVW

!procedure Myanimelist($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Myanimelist', $name, $tech, $desc)
!endprocedure
