@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsOutposts element
include('elements/aws/Compute/AwsOutposts')
AwsOutposts('element', 'Outposts', 'an optional tech field')
@enduml
