' definition of the Item azure-4/Item/Blockchain/ServiceAzureTokenService

sprite $ServiceAzureTokenServiceXs [10x10/16z] NSV70S1G20BGhm8f-mySsodMnydoiqLoVnLIKk9zMxhUdw848DBv22Ybo2-aEeG-

sprite $ServiceAzureTokenServiceSm [12x12/16z] PKs30G1H2CtQVz_pVRDwWdcnghuLwRFahksjywdjwgBggorhh_MfK-HLoxleRgvVJOr-gwldF_lgyGG

sprite $ServiceAzureTokenServiceMd [16x16/16z] XOu54aGn34Bpjq3b_lUjwzY-qGGPhFEp1vBkN8wTwVcu6QhcfJHljGzYEhSOKhflfV-t1_2rRIqFj1Em1Wvs7XAbSVT98Bi-Iztm7_ekAm

sprite $ServiceAzureTokenServiceLg [20x20/16z] {
fSzH0aD040HHqjC5zxzlaZIC_Ku17jYTpbvJTufjZUHK3obVgL_hwZIQrlqoJbtslItALqPZsV-qnL8cgTigPU2peHvDQQxaxBccd023JyEgKXd8kya0_RqE
IuB11FdS1m
}

!procedure ServiceAzureTokenService($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Blockchain/ServiceAzureTokenService', $name, $tech)
!endprocedure

!procedure ServiceAzureTokenServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureTokenServiceLg>', 'Blockchain', $funcName, $content)
!endprocedure

!procedure ServiceAzureTokenServiceGroup($id, $name='Service Azure Token Service', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureTokenServiceLg>', $name, $tech)
!endprocedure
