@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-11/bootstrap')

' loads the Item which embeds the element ServiceIntuneTrendsCard
include('azure-11/Item/NewIcons/ServiceIntuneTrends')

' renders the element
ServiceIntuneTrendsCard('ServiceIntuneTrendsCard', 'Service Intune Trends Card', 'an optional description')
@enduml