' definition of the Item material-4/Places/AcUnit

sprite $AcUnitXs [10x10/16z] uwS3

sprite $AcUnitSm [12x12/16z] unza

sprite $AcUnitMd [16x16/16z] un_X

sprite $AcUnitLg [20x20/16z] unzKO1G

!procedure AcUnit($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Places/AcUnit', $name, $tech)
!endprocedure
