' definition of the Item material-4/Places/House

sprite $HouseXs [10x10/16z] TSQt0O0m4C10yJHaxJyjETk-wYZehDmpgljqhBM3wDm4q3gWPFTO

sprite $HouseSm [12x12/16z] VSY50O103C30u4xsdnPt-QkNa4IgTbqpjPDPgQawhwrsdPf25BkAcMWQTyfiVdtjIGBntAv6

sprite $HouseMd [16x16/16z] ZOu30W0X54JNhER-fytsYz-pJ7Ad9l39uwmL4kBjJLeKSFQkVvUpJmHqTd1icykdb6NrsxIz4KAa9dqF4G

sprite $HouseLg [20x20/16z] jSZL0O0m303H26wt_xIuf7mYLysJBoenqJoFr02QmusWZjPpb91B5Km1UdS7Q5OoajhLh0ba9cjrC97BkldznLus0G

!procedure House($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Places/House', $name, $tech)
!endprocedure
