' definition of the Item material-4/Places/SportsBar

sprite $SportsBarXs [10x10/16z] uwS3

sprite $SportsBarSm [12x12/16z] unza

sprite $SportsBarMd [16x16/16z] un_X

sprite $SportsBarLg [20x20/16z] unzKO1G

!procedure SportsBar($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Places/SportsBar', $name, $tech)
!endprocedure
