' definition of the Item aws-20210131/Resource/ManagementGovernance/AwsOrganizationsManagementAccount

sprite $AwsOrganizationsManagementAccountXs [10x10/16z] HSQt0O1000GWFeVRVr-jb0f-bId1egdfXDWzI70eOA4ZEDOhue3xZV

sprite $AwsOrganizationsManagementAccountSm [12x12/16z] LSd50GGW302mu9JkF--vvXl_ikv23tI4qrGMQcbxvZDIj3EGaPCA4sGY8Ggpw90rKjNkZaO5wch2svbS0G

sprite $AwsOrganizationsManagementAccountMd [16x16/16z] {
PSo5aGGm243HJuWW_VTx0xdrDu83lrP6KEIM2YGIQKcbtKIExqvxTv1YCHomksIXswKNpagX7b3SH6RoyCYETpQK8bNOUOupz3v8BIIQXeCsWYgS1vzL94yZ
t0xlDi0V
}

sprite $AwsOrganizationsManagementAccountLg [20x20/16z] {
PSl5OG1134FHFs1K__K6rk6yYr6C_tQgpfzL0-c0Kk8nHGijkqS09tYAuLlo-sEttMDbxRHVsKgxCTDD80BCpTruXAG2eAPmT87J1ovZDJ0KOXeOMOjL2TXb
gASK50pj3g9FGST0S7HO1ViC6X3Fxajl49pYXqYqClbD4lzS05u1
}

!procedure AwsOrganizationsManagementAccount($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/ManagementGovernance/AwsOrganizationsManagementAccount', $name, $tech)
!endprocedure

!procedure AwsOrganizationsManagementAccountCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsOrganizationsManagementAccountLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsOrganizationsManagementAccountGroup($id, $name='Aws Organizations Management Account', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsOrganizationsManagementAccountLg>', $name, $tech)
!endprocedure
