' definition of the Item aws-20210131/Resource/ManagementGovernance/AwsTrustedAdvisorChecklist

sprite $AwsTrustedAdvisorChecklistXs [10x10/16z] Oy0AM3cmYJ93QIPk1cPcPdHPDXY3cu6Rcnki3W8O

sprite $AwsTrustedAdvisorChecklistSm [12x12/16z] POo50G0W3CEwulp_B-vahhZGxEYIKqBhiPe5N86ZNds8h3nwgCAti_B_9mirZnDa

sprite $AwsTrustedAdvisorChecklistMd [16x16/16z] XOw30G0n302l3lQVzsrU4OCRQZiAZC_NsFX2aN2qgGNQo6BllDbsj8Cvf94b7i9VVJtP8UUJRVgrJxMTIWy

sprite $AwsTrustedAdvisorChecklistLg [20x20/16z] dOq30iHG44CprltFkpRRlizHWi_CCwTSu96utKqlESkqjpulWEB4BVV0dnpBUsvU-xX703bnwzC0o4ziy5L_pH7whM-6m7FYbcDzrKj-94yvVmRO0m

!procedure AwsTrustedAdvisorChecklist($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/ManagementGovernance/AwsTrustedAdvisorChecklist', $name, $tech)
!endprocedure

!procedure AwsTrustedAdvisorChecklistCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsTrustedAdvisorChecklistLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsTrustedAdvisorChecklistGroup($id, $name='Aws Trusted Advisor Checklist', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsTrustedAdvisorChecklistLg>', $name, $tech)
!endprocedure
