' definition of the Item material-4/Notification/AirlineSeatReclineNormal

sprite $AirlineSeatReclineNormalXs [10x10/16z] uwS3

sprite $AirlineSeatReclineNormalSm [12x12/16z] unza

sprite $AirlineSeatReclineNormalMd [16x16/16z] un_X

sprite $AirlineSeatReclineNormalLg [20x20/16z] unzKO1G

!procedure AirlineSeatReclineNormal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Notification/AirlineSeatReclineNormal', $name, $tech)
!endprocedure
