' definition of the Item material-4/Notification/DoNotDisturbOff

sprite $DoNotDisturbOffXs [10x10/16z] uwS3

sprite $DoNotDisturbOffSm [12x12/16z] unza

sprite $DoNotDisturbOffMd [16x16/16z] un_X

sprite $DoNotDisturbOffLg [20x20/16z] unzKO1G

!procedure DoNotDisturbOff($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Notification/DoNotDisturbOff', $name, $tech)
!endprocedure
