' definition of the Item material-4/Notification/DoNotDisturbAlt

sprite $DoNotDisturbAltXs [10x10/16z] uwS3

sprite $DoNotDisturbAltSm [12x12/16z] unza

sprite $DoNotDisturbAltMd [16x16/16z] un_X

sprite $DoNotDisturbAltLg [20x20/16z] unzKO1G

!procedure DoNotDisturbAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Notification/DoNotDisturbAlt', $name, $tech)
!endprocedure
