' definition of the Item material-4/Notification/SyncDisabled

sprite $SyncDisabledXs [10x10/16z] uwS3

sprite $SyncDisabledSm [12x12/16z] unza

sprite $SyncDisabledMd [16x16/16z] un_X

sprite $SyncDisabledLg [20x20/16z] unzKO1G

!procedure SyncDisabled($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Notification/SyncDisabled', $name, $tech)
!endprocedure
