' definition of the Item material-4/Notification/SyncProblem

sprite $SyncProblemXs [10x10/16z] Oy0Ek86Odnz4C3FmC_1pWbWmnC06PO4nbEJX1mhpCqEqeG4

sprite $SyncProblemSm [12x12/16z] VKn50i0m3Afxc___Tf1TfeqBO3RcaMCqZckXY70S5HCEWPSpBVizhGgGLPRm9hmuqM_Gf_VcRGS

sprite $SyncProblemMd [16x16/16z] dKpL0K9134i5xpNxRmifzeUyqqQnPHtyzYooxx3vm0_OW1EhUH0Csk0B3XG-BmXhb8AgDrRFiV5OHfit3cuANOWf8DqAE3467pYvOWxCgX8M-hwk

sprite $SyncProblemLg [20x20/16z] {
hSrL0eGm54FHrBtP_sh7yWRuXuiVAdYgz2d06WlV-0dARmwPIAy1g7HVQwB61Dd6fBDXC0CygwoU1avPljgIQLDt_TW46bHYjcSVMtCT2JN9ZP21G8QhVIFZ
IMOLjti3
}

!procedure SyncProblem($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Notification/SyncProblem', $name, $tech)
!endprocedure
