' definition of the Item aws-q1-2023/Resource/Compute/AmazonEc2M6IdnInstance

sprite $AmazonEc2M6IdnInstanceXs [10x10/16z] Oq0576n876RiB0u63dPc1cPc3WPsg1WxiZfcC615CWy

sprite $AmazonEc2M6IdnInstanceSm [12x12/16z] LOs50G0120BFGlTV-3lj1FuYOq1xENsAGEAK4NRNRI3CRA_tLLQ5KNC3dFEt_kFGquVbZtS5

sprite $AmazonEc2M6IdnInstanceMd [16x16/16z] RG-30G11ADV-2_-VdGruW8539BRcU_EzkemTSi0SPwDfaekVczUyvmWoWX18pKUWi2Yxg5fuwtSYONxtB_vplrk7UF-ZOCNBnJy

sprite $AmazonEc2M6IdnInstanceLg [20x20/16z] {
bP05eWLH24B10FQ_uf-l-ypSiXMF41O81EY9R1t7XutumJYZVsHIBcGMxzhjNjffxzlzo0Ph4YJG1I099clrWBsT77n7svmVsOz4lgh5jpdgipxwZ2L-84sn
GZVDPpCbUDo--G8
}

!procedure AmazonEc2M6IdnInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/Compute/AmazonEc2M6IdnInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonEc2M6IdnInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2M6IdnInstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2M6IdnInstanceGroup($id, $name='Amazon Ec2 M6 Idn Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2M6IdnInstanceLg>', $name, $tech)
!endprocedure
