@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2023/bootstrap')

' loads the Item which embeds the element AmazonEc2M6IInstanceCard
include('aws-q1-2023/Resource/Compute/AmazonEc2M6IInstance')

' renders the element
AmazonEc2M6IInstanceCard('AmazonEc2M6iInstanceCard', 'Amazon Ec2 M6i Instance Card', 'an optional description')
@enduml