' definition of the Item aws-q3-2022/Resource/GeneralIcons/Folders

sprite $FoldersXs [10x10/16z] Oq00NbvUC8qGGB0uu2mcubWCG1ON5

sprite $FoldersSm [12x12/16z] Oq06N5nSZ30s8n01-M0HBaueO6HaG2ZW9fcDC8SRoLPaDWC

sprite $FoldersMd [16x16/16z] Oo04U9YOc3WO4Nnk4C440LmWUKu4u684oIC05mCFhVaezWFvG54anuBvN4Y01zrx

sprite $FoldersLg [20x20/16z] pSe34W0X043HHSRzZvljSJ-_wJbDIDjRczjvAbbEEgDLyda7_yZVstUPqIfdNTvaPRypLlS-WpG

!procedure Folders($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Resource/GeneralIcons/Folders', $name, $tech, $desc)
!endprocedure

!procedure FoldersCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$FoldersLg>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure FoldersGroup($id, $name='Folders', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$FoldersLg>', $name, $tech)
!endprocedure
