' definition of the Item homecloud-1/Network/LocalNetwork

sprite $LocalNetworkXs [12x10/16z] Om02Fdv-VWu62E070IWRI3Fneuh3U10I0g1IZ5nmAOW04vZYXvd3p8yi3W

sprite $LocalNetworkSm [15x12/16z] JOs50G0X30Fpxi_-qqAzFRIMWFaRSS9fGeOpy9NmVPvQ5P3yMnOAd9aWtBUNAV7o-w9zwwf6zFvaahuS4XeI_m

sprite $LocalNetworkMd [20x16/16z] {
PP250SGW3029lKRsdxQ6mrKWBYaJ3vu6F38mwOI8RD7XzLzr-l__vrYBJ1f1V0KY5eaBd-1Ax3mPufSAvGgguVgVhgKafk5gyMRseXDcUtGqpQ6FpinARBrg
tqYzdW
}

sprite $LocalNetworkLg [25x20/16z] {
bT054eGm50FGu4xkVzkjP4YxpaCpzGzPA0rglA3IV6be4Hnt6lOj8FbzSLkF8qmJNZrUyOIDgv5b-0Hj4FPg0xSsq9PW7LTzosqkJXD59oyR-huVt13IeeQN
Merg27let13Iz7MDljhLUgK7
}

!procedure LocalNetwork($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'homecloud-1/Network/LocalNetwork', $name, $tech)
!endprocedure

!procedure LocalNetworkCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$LocalNetworkLg>', '', $funcName, $content)
!endprocedure

!procedure LocalNetworkGroup($id, $name='Local Network', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$LocalNetworkLg>', $name, $tech)
!endprocedure
