' definition of the Item simpleicons-14/B/Bandrautomation

sprite $BandrautomationXs [10x10/16z] Oy0B-1auc44K4pyGC80G9v1W07CuEFdu-1ZuE404FnnWCmK

sprite $BandrautomationSm [12x12/16z] ZSY50SC03C0mRsNq_zUMcHKE7wZbD7C3111KQ_f7hVtuPwOYQeLrBVZRA3UuqG8

sprite $BandrautomationMd [16x16/16z] fSenca416C30x0B0tF-qy7-gLy6qIJ-2SmF-N4j3xR4-QCqgTS1cfrJG_F_-I1U1d4XJnrylbuNpGX-w0m

sprite $BandrautomationLg [20x20/16z] {
lSX5WWCn4C103OzH___jjZV9pRT06LlyW4FbeHWw2hVRgwthQLRON4af7T40gqC1DKTBgNdhigmUv3ZHcYOKq4WQZTlHScuUsVNHucnzsA1xrvuxq3iJJjG9
FkmF
}

!procedure Bandrautomation($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Bandrautomation', $name, $tech, $desc)
!endprocedure
