' definition of the Item simpleicons-14/B/Baserow

sprite $BaserowXs [10x10/16z] FSQt4G0W00Cn7nNvzv-MZ5L9BIkr3H17ysGLi-39k0Hu4m

sprite $BaserowSm [12x12/16z] TSd50S0m34FHRrtArVxJbZ7m4ZFJ1EDqi1tuyVH843hmuOh-q_CHuw55u_ZS-wCy_Ge

sprite $BaserowMd [16x16/16z] bSp50S0m30J1FVsCwh_QC7F6R06bPA3Cl2EopzxUc0cmYJXGtlEVqCvz_mJMxRuGiTlVtYq

sprite $BaserowLg [20x20/16z] hSwr0KGX50NHUJV2wR_QrUzk1vy8Siu1yBaJwfT17JdMydTZt91aWAbZ79JgipHFXOCizGJw7A4EGVWUHriQVy9_ppS

!procedure Baserow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Baserow', $name, $tech, $desc)
!endprocedure
