@startuml
sprite $AwsCertificateManagerLg [20x20/16z] {
XSZL0GCW303HdzY5_VSj3lL3ypZ5YgjtEvmGlZFpPecghLHrcEYL35EFcezRfv602BKObirCp4IxCIrTG7mOqr0pfHbVpKWWmYDkCmzLDOTZ7c5DjgcvzIAn
PgKaCNBQjrd5EuQLVzRm0G
}

sprite $AwsCertificateManagerMd [14x14/16z] HSpL0G0n30BGBuZS_liUf4RrLL8xETdOxigOa661Au3bCrAtLbDVWAYYfHMwiChgVLVMb7sA99XBz0spK_ewqvHI-lh66cxz

!function AwsCertificateManager($id, $name="Certificate Manager", $tech="")
  CloudElement($id, 'aws/SecurityIdentityCompliance/AwsCertificateManager', $name, $tech)
!endfunction
!function AwsCertificateManagerCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsCertificateManagerMd>', 'Certificate Manager', $funcName, $content)
!endfunction
@enduml
