@startuml
sprite $AwsGuarddutyLg [20x20/16z] {
hP150WCn30ClraZr_n_SPSojdON43Fq7BBcl15TI9gTAa0dGeOIs9ZpVDan45GhUL4ik9kPpKoeztITgkkYYmsRJxR4II6TicnPLKkDBBz74PxgDUXxCDjZ1
xtm1
}

sprite $AwsGuarddutyMd [14x14/16z] XOt50S0m30DVbdJTVzyoKounKzS095Y3I9bagIYM7B54hX4laPAoAz4pGgcHVGvBHZmk7DSR3

!procedure AwsGuardduty($id, $name="Guardduty", $tech="")
  CloudElement($id, 'aws/SecurityIdentityCompliance/AwsGuardduty', $name, $tech)
!endprocedure
!procedure AwsGuarddutyCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsGuarddutyMd>', 'Guardduty', $funcName, $content)
!endprocedure
@enduml
