@startuml
sprite $AwsMacieLg [20x20/16z] {
RSy70iCW30F03ij6yF__LgWxiJA0O_ERyGuRP8EpmTdWR50c7MymcX0q0HjjbPba9lHIw64aXZfkHPJGmu02Y4GMR8oehBkRGDIsYY67rwVwFDSVVQLTs3wX
8sjmhJEk1bU3jWC-
}

sprite $AwsMacieMd [14x14/16z] LOp50GG120FlLWWJ-gzttPWNnBZ80zhhzhgztjuyRuvFytxC0TkNoiYO984T6xDY8p7JbjfZceJDPyStx5HxgxtLtXK

!procedure AwsMacie($id, $name="Macie", $tech="")
  CloudElement($id, 'aws/SecurityIdentityCompliance/AwsMacie', $name, $tech)
!endprocedure
!procedure AwsMacieCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsMacieMd>', 'Macie', $funcName, $content)
!endprocedure
@enduml
