@startuml
sprite $AwsSecretsManagerLg [20x20/16z] {
RSwrWGH130LHHn-gD_zyRtYEodmD4c-zun_a7rpG0hLRBbkhQgKPAV5fExgqn9F7h5eoTJWDjHMeHEKoLYUP7Cvk4MXh16FWDZIUrz3-tDvDFMsvInjfgBYC
q6pLxcFAlUTZAJfg3_nyrX79Vg6dxVZ6RY_-Ooz-0G
}

!function AwsSecretsManager($id, $name="Secrets Manager", $tech="")
  CloudElement($id, 'aws/SecurityIdentityCompliance/AwsSecretsManager', $name, $tech)
!endfunction
!function AwsSecretsManagerCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsSecretsManagerLg>', 'Secrets Manager', $funcName, $content)
!endfunction
@enduml
