' definition of the Item simpleicons-7/B/Bandrautomation

sprite $BandrautomationXs [10x10/16z] RSQt0O0m4C10aS59-qzBTlTN7P6fIpe2xZMvyWoIfdA09XVoFotBCm8N

sprite $BandrautomationSm [12x12/16z] ZOY54S1G5CAWxjb_shgSz4kUa4CP3FtEdGDesdsF-V3vSqElgOMZ7nbgwV85xK1J7TIsgqe1DW

sprite $BandrautomationMd [16x16/16z] fOhL0K8n00DJzsR_RIdmtEM-BeANnF3bQ_OhBf8Lvfih2R3b337BH1Xo-MPHm22gScJ_9r85DdB_xxFLNuGnIWdH33Vv

sprite $BandrautomationLg [20x20/16z] {
hSe53WGm20NHgNku_ssNicxHJWnUFgVpuJDwRRl8hjiTkcZuQQPdPTLj6Hu6n7ycljUxDRUycUjrIai8HR-ohS2SGgNQj6vBQaFQVDXprvwc3L5BZrsELeWf
HUUTqpjnk0i
}

!procedure Bandrautomation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/B/Bandrautomation', $name, $tech)
!endprocedure
