' definition of the Item simpleicons-7/B/Beats

sprite $BeatsXs [10x10/16z] O-3Wv-VdPW0280i442n-l2m6RY0B8W94Z4nCJAn03bmTFv8E

sprite $BeatsSm [12x12/16z] Os3W1m9k1WZW1mDM93O_Cfi3YSs9NGqV0pECpSh02vQ1oSBLeB8v4MnU1WO

sprite $BeatsMd [16x16/16z] VOt50O0m40G7TxR_Qd7YoVpkra0F2p_ws89RQt0hlCVWdeAxBUTx5lTk6Hv7_G3NgG53_o_8eGrk_Bltxxlq1

sprite $BeatsLg [20x20/16z] ZSr50e0m30NHZpjp_zFYJYMpV6qIgMQlItHs6OmE0vVXiiHXjSDQux_KTbVglfOgfNbPBWdGkvB3adIl6DZwtNLRup3zJJ_hDva1

!procedure Beats($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/B/Beats', $name, $tech)
!endprocedure
