' definition of the Item simpleicons-7/B/Bitcoincash

sprite $BitcoincashXs [10x10/16z] DKh50S103A8zVx7_j74F1gl73Iz6lGRaSfJ6SyHsSAR1dTflrz6QVbz7W5L00G

sprite $BitcoincashSm [12x12/16z] JOo50G0X30Fpxi_-qqAzFQIQW7dQ2QKfcHAIBktxANoKhy0cquSUPMNpkBau9My_v_nUSqFQ7Ud_W_Wuu-u

sprite $BitcoincashMd [16x16/16z] LO-50GGn20JdF9x-gtrXz-KcYWF1qMTTmFGfBedpo_YAXnHDpcFTke8Mtk89i7mTpusml94RgI1PmDMbgDyqA_5pdGjIUDeVtD7f35Ut8LuJZRIxwCuypHC

sprite $BitcoincashLg [20x20/16z] {
JT053W0X30J0nPt-_xUNakt1H70geBPbPZoIq78WURIxTVL_Qmc4alq5mPhSj9SEQekgi9snlSLlztx5a6FRs-BjiQb0MP6_Jrw7kn7pam3WcTYne3Bdo_9B
8ShXzPzZO78Ae0aHL9UNjvPU-5L6zr0V
}

!procedure Bitcoincash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/B/Bitcoincash', $name, $tech)
!endprocedure
