' definition of the Item simpleicons-7/B/Blackberry

sprite $BlackberryXs [10x10/16z] Oy06-FdvWHZ2Ok3Xvs3WusFWP6NWv0G9C8Cb-H6gUI0Sk30Ba4G1

sprite $BlackberrySm [12x12/16z] TKo50S0m329pv_zhL_SsBW16HXAppZ2_v9J_BnBV9pelyzVGs_HAOpLjtWJXzvacxdtV6sfJ

sprite $BlackberryMd [16x16/16z] bOpL0SD034ELOxJttxOw5J-RPqRS9RjxW1C8OtRzrAKa-G0qzmtnNGMjePxif1Rf9hQU7fPPuwPP0cgb-rAuL21u21rTAXEpWKk5dh36Vpm

sprite $BlackberryLg [20x20/16z] {
fOo54GCn40FtpUp-kytVA3mKMCEXn5-CCPf2Fn37Di3-YOXMDBo2w6UUO9oXG5vhHLxfjawjDOA51CZSlduhc7DsxzLpwXdo7b0KE8w3DuQsdv7hyLGKr7jU
MAzsmNgP5mxd75zp0G
}

!procedure Blackberry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/B/Blackberry', $name, $tech)
!endprocedure
