@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2024/bootstrap')

' loads the Item which embeds the element AmazonWorkSpacesFamilyAmazonWorkSpacesCard
include('aws-q2-2024/Resource/EndUserComputing/AmazonWorkSpacesFamilyAmazonWorkSpaces')

' renders the element
AmazonWorkSpacesFamilyAmazonWorkSpacesCard('AmazonWorkSpacesFamilyAmazonWorkSpacesCard', 'Amazon Work Spaces Family Amazon Work Spaces Card', 'an optional description')
@enduml