' definition of the Item azure-19/Item/Analytics/ServiceDataLakeStoreGen1

sprite $ServiceDataLakeStoreGen1Xs [10x10/16z] HSI50G0m20F1hzl-yzQ1Ys1223nZImT9a3ViE5SskuigK0i

sprite $ServiceDataLakeStoreGen1Sm [12x12/16z] TSQ50G0W4090xDf_NhlrxmD0yNc3G1Kogohe1VVdg06JoVfD-w9rknnzam

sprite $ServiceDataLakeStoreGen1Md [16x16/16z] XSV50G114091riR8Fzvpr_f0umyZWYnxMwrAQfw14saBo63OlMTvMJmlW3eV7MKWoTApougiRHEnnTmxj3DSz

sprite $ServiceDataLakeStoreGen1Lg [20x20/16z] ZSY54O104C30UxV-wyLpEFoEPIAzt4gEMWdU-zRoyI4eNjrN5Ehu8eAZU8zb7vvCoEEY4yHf4O4wF9kKv4tCq7Vq-3gD

!procedure ServiceDataLakeStoreGen1($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Analytics/ServiceDataLakeStoreGen1', $name, $tech, $desc)
!endprocedure

!procedure ServiceDataLakeStoreGen1Card($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDataLakeStoreGen1Lg>', 'Analytics', $funcName, $content)
!endprocedure

!procedure ServiceDataLakeStoreGen1Group($id, $name='Service Data Lake Store Gen1', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDataLakeStoreGen1Lg>', $name, $tech)
!endprocedure
