@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2024/bootstrap')

' loads the Item which embeds the element AmazonElasticFileSystemEfsOneZoneCard
include('aws-q2-2024/Resource/Storage/AmazonElasticFileSystemEfsOneZone')

' renders the element
AmazonElasticFileSystemEfsOneZoneCard('AmazonElasticFileSystemEfsOneZoneCard', 'Amazon Elastic File System Efs One Zone Card', 'an optional description')
@enduml