' definition of the Item aws-q2-2024/Resource/Storage/AwsBackupDatabase

sprite $AwsBackupDatabaseXs [10x10/16z] TSIv0O005CBGvx_OVsDBAo69dwK2rOo2ybWfW4BuUW4E2uBm0W

sprite $AwsBackupDatabaseSm [12x12/16z] NKs50G0m2BB0_pzUfvqWluIUclHLedgs8baTALwBcX16ROMmtsZD5MJMNHGJO47KTHCb0EDXRQ4

sprite $AwsBackupDatabaseMd [16x16/16z] RKq54W0W26DI_t-ntJe35dUZFynnS2VRgOWQTZS3BG4LoRjfbaFvA7ze8Il7aMrtjz62QfS2RTs3zquTV3G6SeOOUQDZGZfNHOPW-5ADncya

sprite $AwsBackupDatabaseLg [20x20/16z] {
VSe54WH120J1Qgp__-CBpcqtGsQ0uanRV2lC5utyNPa8ysw2DGMi80ra1OGHq3crXQIj7GCczokW6qm8sMmtqsh03M1WM0sHh8YtdO7byrt1NL7ssA_ixQTN
vocMszoLyAncNft56ZS7BW
}

!procedure AwsBackupDatabase($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/Storage/AwsBackupDatabase', $name, $tech, $desc)
!endprocedure

!procedure AwsBackupDatabaseCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsBackupDatabaseLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AwsBackupDatabaseGroup($id, $name='Aws Backup Database', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AwsBackupDatabaseLg>', $name, $tech)
!endprocedure
