@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsSagemakerModel element
include('elements/aws/MachineLearning/AwsSagemakerModel')
AwsSagemakerModel('element', 'Sagemaker Model', 'an optional tech field')
@enduml
