' definition of the Item azure-20/Item/Networking/ServiceDnsSecurityPolicy

sprite $ServiceDnsSecurityPolicyXs [10x10/16z] BOQ50O0m0CE2LVu_69XK0xXCFMqwkP5KWMhhIY2n3by6wbz8q2RnXU69QmupbP6DuGC

sprite $ServiceDnsSecurityPolicySm [12x12/16z] BOk50G0m3C8oXVv_yBIPL02WX4d2SUvl9VkyRz31jtVCtcPp553CsehgxVaUnfod3zjl4bYldqKSRgoVnwU-KD8iDW

sprite $ServiceDnsSecurityPolicyMd [16x16/16z] {
HSx50S0W44JHDKRwRpZ4_uc7novbn9yfatwfRSdsisgUGUB9fCKpMQTfg6UofClUNZt5bd9x6JE3g1BZx3sV0M0YDhK3o5haEs5miKu7DccoEi6uoeXh-FfC
tKt-RbrV_gkJ1m
}

sprite $ServiceDnsSecurityPolicyLg [20x20/16z] {
PStNOKKn20HHwH9sjl-6_S3PdZ-E0cUwiklyx342eMygZ07BNxSGOlj2swYxrLYzT35e0tkjSUZHxGXXrWoXwgoe1DqnnhBhXXGVbZYovcO6nDh1I5kSw5Sl
apwiymLLgyPYIYdYjBHhiD7OKUVQAIFPCzrxnxPxptbs6liHQ_HFUvXqVXN_wVFBDm
}

!procedure ServiceDnsSecurityPolicy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-20/Item/Networking/ServiceDnsSecurityPolicy', $name, $tech, $desc)
!endprocedure

!procedure ServiceDnsSecurityPolicyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDnsSecurityPolicyLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServiceDnsSecurityPolicyGroup($id, $name='Service Dns Security Policy', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDnsSecurityPolicyLg>', $name, $tech)
!endprocedure
