@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceDnsMultistackCard
include('azure-20/Item/Networking/ServiceDnsMultistack')

' renders the element
ServiceDnsMultistackCard('ServiceDnsMultistackCard', 'Service Dns Multistack Card', 'an optional description')
@enduml