' definition of the Item material-4/Maps/AddLocation

sprite $AddLocationXs [10x10/16z] uwS3

sprite $AddLocationSm [12x12/16z] unza

sprite $AddLocationMd [16x16/16z] un_X

sprite $AddLocationLg [20x20/16z] unzKO1G

!procedure AddLocation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/AddLocation', $name, $tech)
!endprocedure
