' definition of the Item material-4/Maps/BusAlert

sprite $BusAlertXs [10x10/16z] LSUv0O0m0CF0u-_m_jD2uYwgTDOouacokqMjHzZqgl7jhPDplv46AV43

sprite $BusAlertSm [12x12/16z] POhL0SDG3CGKU0pQVzg2sx_8x3iUTFK2xZRMOkA1Nq0EyRek8L9YMQGL-ordY7ysO59NbV1kBKViso01Z9zw0cy

sprite $BusAlertMd [16x16/16z] {
TSS53WGX4031PWN8CaF__xUNSwzeyKUPceMxtTptT0FQL6raq8NmWlEnOaQ4UNqEN84nOLbWzkiN8OB5SZtfKifgW2yENX-SsPbgv_vsUSF1sU7TmjbYBcVA
LUwSnU3i1
}

sprite $BusAlertLg [20x20/16z] {
VSv50e0m30NHNyF9tF-qM8Aic5rVBVglMsmPz2tXrLYMMYjqQhb2bjJZPUbWmKkBt0QoLhm-hD1a-0-dMVkQhhib-TsmcNhTJPWK9Wx8Af1EiokEB6OsFbal
NROk3lDvFKm-OrN-cldGZUOsyaaHc0UJelVbrrelh_P9Lpi
}

!procedure BusAlert($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Maps/BusAlert', $name, $tech, $desc)
!endprocedure
