' definition of the Item material-4/Maps/Celebration

sprite $CelebrationXs [10x10/16z] uwS3

sprite $CelebrationSm [12x12/16z] unza

sprite $CelebrationMd [16x16/16z] un_X

sprite $CelebrationLg [20x20/16z] unzKO1G

!procedure Celebration($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/Celebration', $name, $tech)
!endprocedure
