' definition of the Item material-4/Maps/DirectionsWalk

sprite $DirectionsWalkXs [10x10/16z] Oq05_Fmm5WSNX6Q22_7pmfZyG0O_kWQu42CdZCNB06O1

sprite $DirectionsWalkSm [12x12/16z] POkr0G0W0CDmX_p_BGjEfrh4fyBsRA_pT1ueywo1iFscGKx0jSZqrOhb4R_l

sprite $DirectionsWalkMd [16x16/16z] TOe30aGn30NpQy_zJxj6EKNo80Tq7ZMKGHTCBrrVlnBG-gu5t5yN0v6YVpg1A90l3QI7F1ge2_sN1f5UfqdNCcdpU4gUt04

sprite $DirectionsWalkLg [20x20/16z] {
VS_LOSKm3010GnXq-q_RFgQ0_tpYTFfobpU6FTia3gOVoSDSlgMiY2-QWV7J5cc5xjimX1W_BAEcaPVbN76T-xbXRtl6hCOlXfH-JLpzYx9nOxsoiLNQvbsl
wlh7xny
}

!procedure DirectionsWalk($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/DirectionsWalk', $name, $tech)
!endprocedure
