' definition of the Item material-4/Maps/LocalPostOffice

sprite $LocalPostOfficeXs [10x10/16z] uwS3

sprite $LocalPostOfficeSm [12x12/16z] unza

sprite $LocalPostOfficeMd [16x16/16z] un_X

sprite $LocalPostOfficeLg [20x20/16z] unzKO1G

!procedure LocalPostOffice($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/LocalPostOffice', $name, $tech)
!endprocedure
