' definition of the Item material-4/Maps/LocalCarWash

sprite $LocalCarWashXs [10x10/16z] Oq06_6080gmCR40818py802H104k8EQ1A0PXVfWq9uYD9iOFLGS

sprite $LocalCarWashSm [12x12/16z] NOo30S105CLUxMR_QS_EDzNpB4Bl6lB_4DwDy7hmwJw7pXtQ2ao-81Fw7x0gv6_e_emxwG-o

sprite $LocalCarWashMd [16x16/16z] RSpL0GCm24NH6_Um_xILGBtd2ttyKJ88R6Uz25ESbsvzhVW9m_EN4xEqRmLbWUAihmt0xzSZG9SN3on9wpIrQh-8fmVjPSgnj_NV_zchUVgqEBIw0W

sprite $LocalCarWashLg [20x20/16z] {
VSxL0GGn24NHEsw4rt-rQmdC-ld3uPTnXVu02idLOHhPj12a4TU2QIVq4tGpCFDFftJGc4r17PL6WhKZaqYpOfJKQMZV-Qbzg1TUSmTzZGjTvBReDOYSJ8rv
v5v4pjEP6mY7Ilrz8VNB05S
}

!procedure LocalCarWash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/LocalCarWash', $name, $tech)
!endprocedure
