' definition of the Item material-4/Maps/LocalBar

sprite $LocalBarXs [10x10/16z] Oy0A-Db0W1_8OkC70R0WDv3129NdPuChPK1dGNKW

sprite $LocalBarSm [12x12/16z] Oy09-640oERYXGWnWqXUi2WRH1KVaCc9qCABf9-109i7R0uBggq

sprite $LocalBarMd [16x16/16z] ZSZ50SC00810shYo_xHnz_i1h_9gzGTAoqbjtrWn-9lJ-pafOJigPe4zLj6KYzGVMt_vtgMZSEh_1CvQ

sprite $LocalBarLg [20x20/16z] hSwr0GCm00D1cTdQVzgmkGbT-TNZDrpKLtEsISouqonuqQnuiXpGU3OINUAJ0FQepo6BJQN7pbFyhMKs6asiZS87hW

!procedure LocalBar($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Maps/LocalBar', $name, $tech, $desc)
!endprocedure
