' definition of the Item material-4/Maps/MapsUgc

sprite $MapsUgcXs [10x10/16z] Oq01_FoyO9gR7mIOG28G066021OG0PRWPk03CS4AML7KGLMmCx3oWCm

sprite $MapsUgcSm [12x12/16z] NOg50G0W20JVRjr_Mxiu0pv0iK6lBPMEMUj0jRrFqR_M7QD_h5S4W5WAXpd-wiUvox9WmBCY2u1nT2e

sprite $MapsUgcMd [16x16/16z] ROw50S1020D9tMZsd_PTgDmh7la7iDR5o5giWGNDDXlQa_Czrh3MHv3UKrGPoDqkYMGRDf-l-YFODpl8ySeMpD6QMSurnveJ4jdoK_4

sprite $MapsUgcLg [20x20/16z] {
bSu53WGX30NGZtjx_zlk5WbfYCsB85Lya_blE5o9DxBO6bzMPoq6WfMssui4MfULfl_y-Kl98QOgrtB-C8NJa0LHnA3T123LRsterxK6NbOJ9SdVK5y3uls2
Umg1mYItq7gss3mUFm
}

!procedure MapsUgc($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/MapsUgc', $name, $tech)
!endprocedure
