@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element MyLocation
include('material-4/Maps/MyLocation')

' renders the element
MyLocation('MyLocation', 'My Location', 'an optional tech label')
@enduml