' definition of the Item material-4/Maps/NoTransfer

sprite $NoTransferXs [10x10/16z] Oq06VFpy_Dn0cf-TaHy4m4oG19W5PC9OO0LW7eW9Pd62HO4iJeGs1eXU

sprite $NoTransferSm [12x12/16z] NOk10G0G20G10FQVLWNWmPsAVR4n1KrGBQizKnGcI-I4GazdrMLmhNscStPTEblUAyGCgKjdWLT4EJ4C

sprite $NoTransferMd [16x16/16z] ROy54e0m40DJzzx_VyiSf7YWibl7Ruo6_OGgHvfYa4ka9PpNZ0uDFT39XM9no2gi9NEh9h9uKf0znYugkNik2T04ONYiazSzB9iezlLCO0C

sprite $NoTransferLg [20x20/16z] {
bSq56eL024LXT3hP_sej-2wluzY_4_HFVhBK5Zfpd8uB-GlvmCMGhiQ1gvU6Mk03jGupDFD0irekp3bFs15sXoawDYkKTAHP88UHOYjpOQn9KXCGr0fMCVIZ
wIfZ0idYI2_R0G
}

!procedure NoTransfer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/NoTransfer', $name, $tech)
!endprocedure
