' definition of the Item material-4/Maps/Place

sprite $PlaceXs [10x10/16z] Oq01VFnS40O_280OBFmy310M6pypK1ukYs1nmxL0JM7dXnl82Y8

sprite $PlaceSm [12x12/16z] NOl50K0X04BvQSl-qzhzJYHEVlDqoSoGbjHD0n_Pz0KrT4OMVIzV-17N5JeFSH81

sprite $PlaceMd [16x16/16z] RSg50G0X30F0u0xxR_j8tZcqRR0d11vqw-gpd42jo_r4JB9_UK-gjGBWgaN_2RYhHYFFsh86CH2lMd5yIRrKU63wLh5t

sprite $PlaceLg [20x20/16z] bSx50GGn30J1MMPt_j6QuHZg9vR-qnjWrwsDP52rKdGgyCp9xVW8d5A7TpiQXgwRt9otcvjSZpTsAs1KKArFxq6dYknGiv3ebY6OTQl7kvJTJElHmQ0dapvn

!procedure Place($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Maps/Place', $name, $tech, $desc)
!endprocedure
