' definition of the Item material-4/Maps/Traffic

sprite $TrafficXs [10x10/16z] ROgr0G0X0CJU5SZ-q-8EQKwNAIyyYDSwWLnWisu7oRDRfn2sEzmHonMCw-xILHW

sprite $TrafficSm [12x12/16z] VOor0K0X34I_ul3sdnQtYckIq-i02kgdG1Hw5-An-LVbDHvUy4_-RtYon-ZwrVrdrs56TzlVa

sprite $TrafficMd [16x16/16z] ZSpL0SCm54DHXSrt_saBnd9p_Xv8EiF5kwrEom94YCkSPm1f1qoUbpnla5IL_p0c5dd0vTa09JKfsy3DaEeOxjaL23RFiVzlzQ7s6LLaGSsSwPCh

sprite $TrafficLg [20x20/16z] {
fOw55GCX44G7T-Y_smpxuidvHzO5bnbt7EwOb6ZMEB-K8EX1-aiAbNe3r20QTm8Dhmjh7ovbp22DBnfpdp4cWBrBeS-9zuqixcGQ1ebJtU_E7dZlf-3V-ust
Vk6nJ7tcnPL-97UXQHpX1W
}

!procedure Traffic($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Maps/Traffic', $name, $tech)
!endprocedure
