' definition of the Item material-4/Hardware/DeviceUnknown

sprite $DeviceUnknownXs [10x10/16z] JSQr0S0m00Cmjs7q_zU6IPFmiEpwd6xY60pXvWYkmQazYxsqngvFhbK

sprite $DeviceUnknownSm [12x12/16z] Oq05_120mKOb-NduOMn6PY0BBil9Ws3p8UdYHpC1XrtS30m

sprite $DeviceUnknownMd [16x16/16z] ROg50O1030E3Ezb_MkIzSYzj10vC754Ep6Hz1gwixHp9kzKSSUsojnz2RuJGXDIzr1sbbZFZQsnNP0Jm0W

sprite $DeviceUnknownLg [20x20/16z] VSnL0aGX28LXk_NiVxKpjqlWVuBFK5nrd8MJ4kvEowI5etORCqLWVCoX-86thOk3ddv9c7xEy5-p26gof2RpVROmspnTYUOcMp6UwNNz0m

!procedure DeviceUnknown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Hardware/DeviceUnknown', $name, $tech, $desc)
!endprocedure
