' definition of the Item material-4/Hardware/LaptopMac

sprite $LaptopMacXs [10x10/16z] Oy06-DaWW9k17of2YCN7py_F2SJCJFmmW30E

sprite $LaptopMacSm [12x12/16z] Oy05EFXXW961bnagoCD4Cfk7bmS2-9cuUK36CO087WPc142s5W

sprite $LaptopMacMd [16x16/16z] lSUr0S0024N15pVWxpzjN2kwN7UaUhzP1ONive9ItAeVNcZdsZ5PQ1NiDSC-1X8B

sprite $LaptopMacLg [20x20/16z] pSY53OHG04J1Tu9l_lPVBUv4yOaFXyXBNy2Avrm0pfbxtocQQo-u5J9tVXIIMobk1Udh3N501G

!procedure LaptopMac($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Hardware/LaptopMac', $name, $tech, $desc)
!endprocedure
