@startuml


include('homecloud-2/bootstrap')
include('homecloud-2/Brand/Backup')
include('homecloud-2/Brand/Calibreweb')
include('homecloud-2/Brand/Ceph')
include('homecloud-2/Brand/Debian')
include('homecloud-2/Brand/Dnas')
include('homecloud-2/Brand/Docker')
include('homecloud-2/Brand/Influxdata')
include('homecloud-2/Brand/Keepalived')
include('homecloud-2/Brand/Kubernetes')
include('homecloud-2/Brand/Longhorn')
include('homecloud-2/Brand/Nextcloud')
include('homecloud-2/Brand/Nfs')
include('homecloud-2/Brand/Portainer')
include('homecloud-2/Brand/Samba')
include('homecloud-2/Brand/Syncthing')
include('homecloud-2/Brand/Traefik')
include('homecloud-2/Brand/Ubuntu')
include('homecloud-2/Container/Container')
include('homecloud-2/Container/Pod')
include('homecloud-2/Container/Registry')
include('homecloud-2/Container/VolumeDisk')
include('homecloud-2/Container/VolumeK8S')
include('homecloud-2/Container/VolumeLonghorn')
include('homecloud-2/Hardware/Board')
include('homecloud-2/Hardware/Hdd')
include('homecloud-2/Hardware/Laptop')
include('homecloud-2/Hardware/SdCard')
include('homecloud-2/Hardware/Smartphone')
include('homecloud-2/Hardware/Usb')
include('homecloud-2/Network/Dns')
include('homecloud-2/Network/Internet')
include('homecloud-2/Network/LocalNetwork')
include('homecloud-2/Network/Router')



@enduml