' definition of the Item aws-q1-2022/Resource/Compute/AmazonEc2Trn1Instance

sprite $AmazonEc2Trn1InstanceXs [10x10/16z] Oq0576n876RiB0u69Wuc88k3WGqgneQiZXaCM97C0m

sprite $AmazonEc2Trn1InstanceSm [12x12/16z] LOs50G0n4C9IIzb_uNSzL-0lLb8H85u2UgqZzQvd1Pj0nsFLQYsIt3VbkBdl_pWmCm_hFzuL

sprite $AmazonEc2Trn1InstanceMd [16x16/16z] RK-50SH03CfBWVqdBkSQTuaB81WoexXV6fLbTl_V1hGBVaSZuFpacpddcVDba0Mi9EjlV1dMKkv_cd_jd_phVgA1hlzOmpwo_m8

sprite $AmazonEc2Trn1InstanceLg [20x20/16z] {
bP250GGn20G7t_uRVdSvIN07_hscGBJH2xOQdVwTnCKslBn8e5jljkdy6LVr7jSLl-8kDWiFjw1lDadW22yIGYfWdhQ5MSm-UjYkFUBbLTx29pjJ9tQ2fPic
0KKQbx0Z
}

!procedure AmazonEc2Trn1Instance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/Compute/AmazonEc2Trn1Instance', $name, $tech)
!endprocedure

!procedure AmazonEc2Trn1InstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2Trn1InstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2Trn1InstanceGroup($id, $name='Amazon Ec2 Trn1 Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2Trn1InstanceLg>', $name, $tech)
!endprocedure
