@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AzureTimeSeriesInsightsEnvironments element
include('elements/azure/InternetOfThingsServiceColor/AzureTimeSeriesInsightsEnvironments')
AzureTimeSeriesInsightsEnvironments('element', 'Time Series Insights Environments', 'an optional tech field')
@enduml
