' definition of the Item material-4/Editor/FormatLineSpacing

sprite $FormatLineSpacingXs [10x10/16z] Oy0A-1cOE8607SI205GMCpyGy229SV9p8dIW0m

sprite $FormatLineSpacingSm [12x12/16z] Oy09s9aGJ7v-9bv-402AyR30X37OXDGmylCZr00H5W

sprite $FormatLineSpacingMd [16x16/16z] bSsr0O1G30JG-z4ARlzfSNTU5Gz-Aqn09ttAhi09EZGixdAPJFcF_Q8CtVn7JSfkln9yrm8

sprite $FormatLineSpacingLg [20x20/16z] fSy35W1H20NG-lRR_sh7DkvnZduA-r168X9-PBiGcg34A553Gz7IwnYxaHbZnpjuydo7y17Hy_eF0q1lTvWcj2Ffcne

!procedure FormatLineSpacing($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Editor/FormatLineSpacing', $name, $tech, $desc)
!endprocedure
