' definition of the Item simpleicons-6/L/Lbry

sprite $LbryXs [10x10/16z] Oy01-1WuaNYi30myC3O_bEO1ia28Wu611SnWX4f1AGG

sprite $LbrySm [12x12/16z] VS750SDG500Wulc-_xJLTwc2V-Rj40gc1CS4JCL1Q4DO9eC2cMJPoOaCbeDb4URitHK

sprite $LbryMd [16x16/16z] ZSt55OGm00N0GUB9e_zgLx4ZS_xYeTNTrCJiL6O81LZIMQheRaAQtVHf4zajaOsOi1V7N14oQQ5CMCh-jMPxhq9rcLjPFF86

sprite $LbryLg [20x20/16z] {
hSs54SH0243HZqJN-k_sXdWoTlRM1U0VB8qyL8LfugBV_WpdRU7GPSBOSzNFMEQXPEDkwcWWd28gxZmPAqaAafl4FkQjsEnWoOZPRGOyfkENn1IxZKK030DN
qfJ2apgVUW4
}

!procedure Lbry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/L/Lbry', $name, $tech)
!endprocedure
