' definition of the Item simpleicons-6/L/Lgtm

sprite $LgtmXs [10x10/16z] TS410KG0002n_GF0zM-h09iFspLZ5FnpKmfDoqx_QCOlw6_DgmS

sprite $LgtmSm [12x12/16z] ZS6r0GD10C0m_p5x_sb3TKZY7yvkRyEiatPTF9GG9ZZ4VOYuHCQb2um7oc7mO02Il6GzWS_k

sprite $LgtmMd [16x16/16z] dS47OGGn0C0mP--OFzhs5uAJU2JcaW8VceUxzt4jozKwThxEHI5sBoIDiEicQBnOjo3BOaHak8oGrbReMWJ010HW3ZxkIK1nyXENsddY7m

sprite $LgtmLg [20x20/16z] {
jSh5eSKm50FHiMEcwR_Q3myhoDbSaBX7x7EFmijMkcUqrgVceYN9yF0IDU9kSAWD8BKS5dWQe0fD7O3HHDOu6yepecYsCXg2HWKm73LGrRuRy2oNvnQ2F9qL
800a2ozB8z0qyLMFkXAt-0K
}

!procedure Lgtm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/L/Lgtm', $name, $tech)
!endprocedure
