@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-6/bootstrap')

' loads the Item which embeds the element Libreoffice
include('simpleicons-6/L/Libreoffice')

' renders the element
Libreoffice('Libreoffice', 'Libreoffice', 'an optional tech label')
@enduml