' definition of the Item simpleicons-6/L/Liquibase

sprite $LiquibaseXs [10x10/16z] JSkr0O1000F0mntsdnPxJHE7_Lh05Q1MQ9db0SPSnd4-7q6SNDWi__01

sprite $LiquibaseSm [12x12/16z] FSp50GGW34JHZplJVxKhsBl40-27ck5lQak0Be1wseyROXblHui_QGMx-WM_tev_hfKP1-pTkdOyMN-6Bm

sprite $LiquibaseMd [16x16/16z] LSk54G0X34JHZplqt-rDSWPl9Be8K-OQYKTRh_2EBmkuzKFLPqhy312cu-MwV3npFFBsdJnA-oPv_Q-h6t3jpLUizA8ZvZDLWmMwNWBOhlz93bJzGfdvnoy

sprite $LiquibaseLg [20x20/16z] {
LT053W0n24JHN_To_zjkrWXzqIemlFBSibf0LL4xyjXYLMvosDoQM9w7wtgfO3d_rUCGsrqErFz-_UzC6SSZYueSMxj5y5sqvyPjo5z3ceFqr-ZczLasYcgE
mit6b4Hhp0o4kaLp6JOSnyjhXVi-5m
}

!procedure Liquibase($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/L/Liquibase', $name, $tech)
!endprocedure
