' definition of the Item simpleicons-6/L/Livechat

sprite $LivechatXs [10x10/16z] FKc50G0W3C9k-VzQsnK9XDhPYm7u9n1ts4HHL1TLHDsU3-qMjyWR9m

sprite $LivechatSm [12x12/16z] JOp50SLG3CCSAZpI_jD-XkeIC4ZUvcADGn8_faEvcqT18_LciF3FtW7xxUko3-BdTpWEoOu31A01S4gM2Ik_rP_y7G

sprite $LivechatMd [16x16/16z] PSx50GGn34DH3GVr-wzs6GBlPhQa8nM3dSCYQQCbqJjWrrU61FhPeRRn2hJnCiSUuZBCnpOE89xMtv-AxxZmAnJx0cn7VTHdfL6pFku

sprite $LivechatLg [20x20/16z] {
ZSu50eCm44JHRLntxd_RJgZWyl47914MIrC5eBqcAwE6TM6cEITWhUIfKiSN6dd8Cc81wjOwUMjwO2m_CPtjSevwi1O_3cDUCZB6L3xJHvrYyQcA_rd3Ds6J
kP_CCne-gPLLPlvWDZNpmni
}

!procedure Livechat($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/L/Livechat', $name, $tech)
!endprocedure
