' definition of the Item azure-4/Item/Identity/ServiceAzureAdDomainServices

sprite $ServiceAzureAdDomainServicesXs [10x10/16z] LOh50K0n38Leuzb_t-_AwGdyyJkeNr6tT4JTKiI4kR5j0N8aws0eqyrw729RQdO2QrO

sprite $ServiceAzureAdDomainServicesSm [12x12/16z] PSo53S103C10XwFVVzyorw8JcLzvqpCkUgRljDMbAzKNLvM0cAhcKe7gxjR4dDNH8q1SBMDn7QFLOpLII0ip

sprite $ServiceAzureAdDomainServicesMd [16x16/16z] TSu50iGW30J0U0B_V_1jhcxR8eFJH_nA2prJBK8EYi4X9xRZ89p8ugR6Fc0gI7JIYPXbSmMfcD9ghz4xp5JRxZK78Vyb83o543OJNZot9sIsQt-ZeIZA3m

sprite $ServiceAzureAdDomainServicesLg [20x20/16z] {
VS_5WSKm34LHmHEC-ozuz0tXvEvypFGLoztKzKPmvpCnolniw6O74NGxhSIq29m89PNiErMbhvieAZtlHVRtoy7IGKnGsisoIGGfe3pDolx2-XUKIej-rdZ-
5KBY6DRs5nBPj9YeW2_RFuXmGfdIeJxel_W7
}

!procedure ServiceAzureAdDomainServices($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Identity/ServiceAzureAdDomainServices', $name, $tech)
!endprocedure

!procedure ServiceAzureAdDomainServicesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureAdDomainServicesLg>', 'Identity', $funcName, $content)
!endprocedure

!procedure ServiceAzureAdDomainServicesGroup($id, $name='Service Azure Ad Domain Services', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureAdDomainServicesLg>', $name, $tech)
!endprocedure
