@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-7/bootstrap')

' loads the Item which embeds the element Hibob
include('simpleicons-7/H/Hibob')

' renders the element
Hibob('Hibob', 'Hibob', 'an optional tech label')
@enduml