' definition of the Item simpleicons-7/H/Hive

sprite $HiveXs [10x10/16z] Oq02ZDmWm80CcBduGO2JaOa5AiB6mC0A5WCAy464cFY1Ui5YO1vK6H10nG

sprite $HiveSm [12x12/16z] NOs50S0W30GVX-Z-qzQLWxZXZv_CsOV-JRD93PkDJGq8uZkq9t1JK6nBxYLDs4dZghhkJZP_JkXcLm

sprite $HiveMd [16x16/16z] ZOk50G0n2CJg3km_RVrTKmLox0gd1VO3HtjwdXiNOt2AywkEpS9eZGES0PbcE0XsPUkRr7rkSVgW5ubRBvU_ZyjNGNzYLPE5Ujj5RuNltm8

sprite $HiveLg [20x20/16z] {
bSw54KGn409GVboN_gizZvw_aUWou0t7JjhTaRk4VnpS0T0-LJObkWElg62s2nTZArPodG9X2vkqJ1rJDiKlSOaPYLSrQcMptBQtyIEp2MkdQAV4f30uXoiX
9Lx_w6j6QZ_PkBbT4jPMwWm
}

!procedure Hive($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/H/Hive', $name, $tech)
!endprocedure
