' definition of the Item simpleicons-7/H/Hypothesis

sprite $HypothesisXs [10x10/16z] RSR50O0m0C30u4xsdnRNjlSwMa_W3GTIWtj-HosEfQMpuesT02i

sprite $HypothesisSm [12x12/16z] TSor0G0X44JHVtvu_zNYJCRgYuOZhG8n_TNi77XbRkIOv3Lo65O-Tuonebv6fNuB

sprite $HypothesisMd [16x16/16z] XOor0S1030Cl_Apzfms3NUKw8JHzH5XaWI2LvdHZ-jDvSRe3hAO5Wj6ZnEB_3XsyXdJhHI8eTrTkWSxh6wbXwPva0m

sprite $HypothesisLg [20x20/16z] hP2r0G0X5CM2E-m_xRbBHwhlyi2t6nKGxSblB47lc0IUiHdrYEMc4QzvuJTMtZ6mxnXoYsMjfuIUIghxrO2lc50pi-CNYvDvrHFL3dC4

!procedure Hypothesis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/H/Hypothesis', $name, $tech, $desc)
!endprocedure
