@startuml
sprite $MaterialsBusinessCenterLg [20x20/16z] {
bO-50GGX30G_ONdRSFHVBNBkClXWoUiX3d0hvOqqlr1g487fA4G40NqdhVcGj6Xznq-n6kA2eCKrIzTCZhyV9yTsvag8xIwrHkihvMLf9staWefCam9YvUFz
fvrWSYsdJcsk-fmLCrframm
}

sprite $MaterialsBusinessCenterMd [14x14/16z] ROw5TGGn34HZCRxqt-qjypUAv-y3WFC_n4p6Rg6DORXzBSgimcQ7_X_eQdL4hnPdbewXbSbJGoB2gNnwfhQGLI4ILGcJrNkJdgpXlU5ZLW8Rat7d1m

!procedure MaterialsBusinessCenter($id, $name="Business Center", $tech="")
  CloudElement($id, 'materials/Places/MaterialsBusinessCenter', $name, $tech)
!endprocedure
!procedure MaterialsBusinessCenterCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsBusinessCenterMd>', 'Business Center', $funcName, $content)
!endprocedure
@enduml
