@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-8/bootstrap')

' loads the Item which embeds the element Bentley
include('simpleicons-8/B/Bentley')

' renders the element
Bentley('Bentley', 'Bentley', 'an optional tech label', 'an optional description')
@enduml