@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-8/bootstrap')

' loads the Item which embeds the element Bit
include('simpleicons-8/B/Bit')

' renders the element
Bit('Bit', 'Bit', 'an optional tech label', 'an optional description')
@enduml