' definition of the Item simpleicons-8/B/Britishairways

sprite $BritishairwaysXs [10x10/16z] Oo0ICF7305o87y703m

sprite $BritishairwaysSm [12x12/16z] Ow04iFF30P8edCtCnyz4gf4

sprite $BritishairwaysMd [16x16/16z] Ow0vO6HYPc5bO-VauU7bOGK9iFFo8m2gMbvaFZjGcXtLAEgx3W

sprite $BritishairwaysLg [20x20/16z] OnYyW154CF7nemE893C79oSN571oyM3ePe4eH00cRg1UJZHLxFmyWylJ

!procedure Britishairways($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/B/Britishairways', $name, $tech, $desc)
!endprocedure
