' definition of the Item simpleicons-6/R/Renovatebot

sprite $RenovatebotXs [10x10/16z] BSQ74S0W4C0mfuVg_RVbWDSr0IHV9krgcld-JttedhydcaolP9mYh_OiLT698acd13nEC

sprite $RenovatebotSm [12x12/16z] FSV50S0m0810wbxsdpQUt0l87ayggvA7jD5ByDIFxTlNQS5T7_-VXUkqOEM-SkJdSiw3nSywseVt09iVu3Cx808

sprite $RenovatebotMd [16x16/16z] {
HS_50KCX50NHYplJVxS9xzlP3OvCMWodn-9Ih1mm9yS-3TfBry2qnOqG_sDdo8kCYuEfrWQGY21DgUq2B52yCd8xsGaSmmRKI1Z7qMmGG3pY6TZAV0CUU_sZ
alKtUMGPp_UR7m
}

sprite $RenovatebotLg [20x20/16z] {
JSm54WGX30NHtd6qxt_RBJBwSF8hN5AtRdpiNjhCHRLhI0HjzYURhnIxn_Ev4jTaOwLvE81TcJnYH_L0TYiJ5IWkgYdMXa2MhZesVXGWENSVRofKXqZbec5p
w6GLheIlcIWrcY-WwCha1t0r_o39aFsQ2Qil7eUXhGn_
}

!procedure Renovatebot($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Renovatebot', $name, $tech)
!endprocedure
