' definition of the Item simpleicons-6/R/Rescript

sprite $RescriptXs [10x10/16z] Os3cumS1NWPcVXW0YY000mCGOR8W09F5Yz08Pm4

sprite $RescriptSm [12x12/16z] TSR50O0m0C30u4xsdnPtsdiT3EvQy3RuCeBc-oiGk9wGND_5Fv3jwRpXRGO

sprite $RescriptMd [16x16/16z] bSUt0O100810p5dstzRcyrTISR2_nku9hDiRl_Qz0-YsH6-0Er1wQYpibMF__S2PthgvCJNN3m

sprite $RescriptLg [20x20/16z] hSW54WD120NHNX-3V__JnXKgfUbH7YpTzSuAC1JR5-MwSguV-GoRPDl-jeEhEK2mIhQHxVQCOE_-ONim0-nZLAueHoPZY-IS0G

!procedure Rescript($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Rescript', $name, $tech)
!endprocedure
