' definition of the Item simpleicons-6/R/Researchgate

sprite $ResearchgateXs [10x10/16z] Ou02VWI32SO2iVaPUFZ1B2ZYOe2me4hu-E6A4ImEc2mGSG1f

sprite $ResearchgateSm [12x12/16z] HSU50S0W40J1nHtwhpQ2lSznAhPBfyd71QrfhVSCtumvQg2BxTDp5TUpXZOZ7DCAntEktH3JPtW1

sprite $ResearchgateMd [16x16/16z] LOi50aGX20NdTmbp_zDk1ohrYl9svmglWwY4z4-Mwo8YCcD_uLU7C2Zan7x0Be0dQF33oUlzy5BnA__3gIi5CxXrcCiUK_Adm61yuARN1BCv0jm1

sprite $ResearchgateLg [20x20/16z] {
PSu50aGX20HGx7RkVzjrtFhOyGmGNJAQ76MEKA39S6-rUPhS1cGPgymvUrpcU6-PM73LEPfjWGFUMLIUb07vcTcJgq6-zf_aiV6efnd0ACC43vI5IDB69C9b
1hXCCd2P39JJEEMlDARIcE7429jU
}

!procedure Researchgate($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Researchgate', $name, $tech)
!endprocedure
