' definition of the Item simpleicons-6/R/Rollsroyce

sprite $RollsroyceXs [10x10/16z] NOl50O100CE2Ezb_Mfoplce1TUQHmxxRF8uLiNJEZrDz3AApFr6os-MsHau

sprite $RollsroyceSm [12x12/16z] JKor0G0n42Ak1_jF-owXmW4TwBWXUE_rSZfeQE5i7tTc3rU7uibFG7pwD7BvWVtShvyZ7DoVtFini0C

sprite $RollsroyceMd [16x16/16z] JSo50S0W40J1mvtjlzguu0mlKWMWwXsMymputvavEpEyZaWUHrYSi9F5eBuuayNdCWuwocsWOWppxsyyeDyrOeV_BRLXMUqGTh51evpsjoUXedka-p6HTW

sprite $RollsroyceLg [20x20/16z] {
NSzH0a0m30JH1T0scVkV5e3eV3xeLX9ddXGo-hqXaw9fyhtCr0KJjh-9uz6Ar83WRnt8QNysOogCFuDUpX0Dqk7DQod191ccsuucPkMmfLKfwZaexZjA7Qes
BuXKMK_NKPbOn5YRoz6PX_lcsyo6qyoiItHwUfR196q
}

!procedure Rollsroyce($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Rollsroyce', $name, $tech)
!endprocedure
