' definition of the Item simpleicons-6/R/Rotaryinternational

sprite $RotaryinternationalXs [10x10/16z] 5S450SG0000Xvhxhd_O5_Bq3V_Sr5JI_RU953ekpsall-DWzbiRkbfwETExIzD8wR8TWgk8B

sprite $RotaryinternationalSm [12x12/16z] BS450GH140InMeQ1zg_syH9-aeTcXie1aAs-zpI1hXs4DNC60Z4ldIX5-qYDbL4XEO1GRFb9hIDg3n2C0zk6LSrnUeUmSG-xEu2D8T7X3G

sprite $RotaryinternationalMd [16x16/16z] {
HSV5WI1G3CDGEPyfxh_QXS6da_WWaby7XrkgyP_YlTwAXbjylElgQm-H1kwDSoNJTZafk3oeXb8vX2dsdbRQN1DibZEM9JNI_vvJi22gwV_Utlyw9QPu4pyr
qvpaGpcM2CEeCw7Mq-R2vRPr1b2ywwcxrtxDXznlzVtS-IICzVZlBm
}

sprite $RotaryinternationalLg [20x20/16z] {
HSp5OGGm0CH0cTdglzlaUBuBV5q2_1JsgM8cyk6-gwLcjtz6VO-IIo-phBeQ3zsKqrLRvXY0ucQjmX3cIdK9tCG4fi08d0Bx4ZoPPMHuo7Do9bQrzwCMi8MM
k71wOzi86VCrSY1q60SeA5Iak_UOtXWVZQXtgsMRZZhqaZh52jD0c8EH8i4ns-DDm9cy45hjfUpSZUFVpGDWMseDfTMHk2OUAkkqr4UEtLGYBwRbGxJpiseM
8ppy0G
}

!procedure Rotaryinternational($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Rotaryinternational', $name, $tech)
!endprocedure
