' definition of the Item simpleicons-6/R/Roundcube

sprite $RoundcubeXs [10x10/16z] Om02Pbu616024QnW9h8m6p-4PkJdvsS4ivZvGG38099y82OxX0zXGPG3MK0I

sprite $RoundcubeSm [12x12/16z] HSY50SCm300mbIdm_xM3XcGsEEAiM65YcE5IBAod8adXKUGjvqkHyj-C8pVJszt__dvtb3ruJRyTlW

sprite $RoundcubeMd [16x16/16z] LSs54GKn20JGZNks_sg_70pClRW04FCqkAcpgheENqJosLyAJ0_09VpCpN7zm-c7PFHu2irEiu30bwehTDDa2G2cdRLIkCzvm4IsAxil

sprite $RoundcubeLg [20x20/16z] {
NSg53KGn30JH-HIEtN-rXmu-qMgqc2lNoC8xFevmq2NCUM4SNPyFGrtISWpC3k0IOQO9LrINc-gjuYgJ4eD-oC5mgOcOi-hmy5Lq8HU-xrvxKYxPMkBZMHec
zlOmoAy55hVuZ7a3
}

!procedure Roundcube($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Roundcube', $name, $tech)
!endprocedure
