' definition of the Item simpleicons-6/R/Rxdb

sprite $RxdbXs [10x10/16z] Os1Wu6E00dv-5dOe2m88ifWW09iimb06

sprite $RxdbSm [12x12/16z] Os1WO6Q00mvsVZuc69iV0XZHsAnS481F3Jil130IKiC7OaC1CpyZ8mC

sprite $RxdbMd [16x16/16z] Om02PbO6PC3Fmi_8Zypd1ufmCWC18uGF1nn4yHdXW852_QJR3mCy37pi83u2SBBoCm3z3G

sprite $RxdbLg [20x20/16z] hSs54GDH24NHYyJbzTzjXf6i-vxl0b3YIu-zG_UuqUQIddc_tNft-jOepLrZsntHDlRl-1tU1iLURIVKk1PLgxkMG4WfEf8K2Vm

!procedure Rxdb($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/R/Rxdb', $name, $tech)
!endprocedure
