@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('eip-1/bootstrap')

' loads the Item which embeds the element CorrelationIdentifier
include('eip-1/MessageConstruction/CorrelationIdentifier')

' renders the element
CorrelationIdentifier('CorrelationIdentifier', 'Correlation Identifier', 'an optional tech label', 'an optional description')
@enduml