' definition of the Item aws-q1-2022/Category/FrontEndWebMobile

sprite $FrontEndWebMobileXs [10x10/16z] HSX15a0030FH0D7q_lVLDZ2h_uP_KLqLgGt0rXHgmb9KvqXMbbGAIwDCYOnHphq1

sprite $FrontEndWebMobileSm [12x12/16z] JOk53O1034KJwkt--rA3knVxAZTMQ27YAPRIHCIhEKT4EDhxijfBcqgKzj8cuGBW04_fGCGSTfvuiNhD2m

sprite $FrontEndWebMobileMd [16x16/16z] NSs54O1034HHV8N--sKdmV_eoqdmJnKxJF1d49jBTNlXceZRs_NYiaC06oxxkd7Pj_UsouhtjLo3jhBEjLDpx2LP0DkfhwUuSXVFdyO3

sprite $FrontEndWebMobileLg [20x20/16z] {
RSr50W0X241Ha_B-znsfwRzy2k1VVJuQOpG4zYZ3ooxS9joBro-JGbEZShV9sdmOc3KDJnErgOVWClap-JDXC6Er5IPXt13NAe0880EqDB7iUXeEJIO34ORj
P4UuuyiKhR0dghLl1m
}

!procedure FrontEndWebMobile($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Category/FrontEndWebMobile', $name, $tech, $desc)
!endprocedure

!procedure FrontEndWebMobileCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$FrontEndWebMobileLg>', '', $funcName, $content)
!endprocedure

!procedure FrontEndWebMobileGroup($id, $name='Front End Web Mobile', $tech='')
  IconGroupElement($id, 'FrontEndWebMobile', '<$FrontEndWebMobileLg>', $name, $tech)
!endprocedure
