' definition of the Item aws-q1-2022/Category/Serverless

sprite $ServerlessXs [10x10/16z] HSQr0G1130In8yEi-w_t6HGfVa0UxZqLZ7PLIY3EcHhEkIOvh8pIWOIekzUUxW

sprite $ServerlessSm [12x12/16z] JSc53G1144BHt8t2zj_lkX1xFyGxj6NVyWu-GI8oPPdU3fjEVlYXpQKTBTgQYwXHJ83cyG3TAvPtL

sprite $ServerlessMd [16x16/16z] NSbP0W9G24BHd59u-zzlqbptxq3_1pMFkbt-36l-3ElFyB26gCoFMVgjtxz1-TCpRCC5IFcmTg9Zkye7Gpf3X7mGHJ9z86-amXRoUtZuCyZnazq

sprite $ServerlessLg [20x20/16z] {
RSZ50O1040ImqnsX_tfnXpo3FxNVj4L6QCKTW7BSbTTTkPpVkToQ9QMud-UQ6mstCwb5ntMzA89YIpYkqqvDDQHsNBATqQbPlPqZOhccvOR1bQnmDBBClTrE
fDR3C3jIt_Drj_qxhrU-9W
}

!procedure Serverless($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Category/Serverless', $name, $tech, $desc)
!endprocedure

!procedure ServerlessCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServerlessLg>', '', $funcName, $content)
!endprocedure

!procedure ServerlessGroup($id, $name='Serverless', $tech='')
  IconGroupElement($id, 'Serverless', '<$ServerlessLg>', $name, $tech)
!endprocedure
