' definition of the Item aws-q1-2024/Resource/QuantumTechnologies/AmazonBraketNoiseSimulator

sprite $AmazonBraketNoiseSimulatorXs [10x10/16z] Oq02h0mCx0WU4vH64MI7qUn01EOoWLaWm0ncCO8COcS2ijWWeWmC

sprite $AmazonBraketNoiseSimulatorSm [12x12/16z] TSZ50K0n3CDGjKdi_IV-pF1k4ZUAfix5DOeVoSwcBF0INVZuY8saFJ8esCiDHW

sprite $AmazonBraketNoiseSimulatorMd [16x16/16z] NO-50GCn3CGKi6x_YSlmCJD11sUqBlv7dZvfFhFvrNpgzCF57ubKCZw-e4A1AuO4YB_-Elq2ovSEm3IYSyBwxHDWdu_S0G

sprite $AmazonBraketNoiseSimulatorLg [20x20/16z] {
ZOs54GCm4CFygFqtxeNA58xEeFSZhRhhaJ7_nODkNTQlJE6lJFp9uWqJs8lEzSYIeIfW_EeK01toeGKVEdU6MYolPvhetZMtZYW6SswiXwOw5IPPB5PDEmWR
WZFAzYTkJCJAiGDkdmi
}

!procedure AmazonBraketNoiseSimulator($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/QuantumTechnologies/AmazonBraketNoiseSimulator', $name, $tech, $desc)
!endprocedure

!procedure AmazonBraketNoiseSimulatorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonBraketNoiseSimulatorLg>', 'QuantumTechnologies', $funcName, $content)
!endprocedure

!procedure AmazonBraketNoiseSimulatorGroup($id, $name='Amazon Braket Noise Simulator', $tech='')
  IconGroupElement($id, 'QuantumTechnologiesFamily', '<$AmazonBraketNoiseSimulatorLg>', $name, $tech)
!endprocedure
