' definition of the Item fontawesome/Regular/BarChart

sprite $BarChartXs [10x10/16z] Ou03VcGMFmXW4SEgZXz9Z9S98Gq3

sprite $BarChartSm [12x12/16z] NSh50G0W509GxDRzfxNxNNu0BbvWImegDMC7RUP-TToi_7-eZhUT-yuz7P741X6t0W

sprite $BarChartMd [16x16/16z] Oq03J1oeV7v-J3utFmGmmkIP802NUXPU8E11y3d0kX5ymlR10Cm-6C1KpmNb8mn01UZ-1G

sprite $BarChartLg [20x20/16z] ZT350S0W30LGlDw__xJruf2y8yH5ZIgVWCQRd7xXRS5FXbpraVrwGZx2MrGlVjFBmuOt_imEmVYzJGWMVhqDrMFjcKqO54J52G

!procedure BarChart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Regular/BarChart', $name, $tech, $desc)
!endprocedure
