' definition of the Item fontawesome/Regular/Dizzy

sprite $DizzyXs [10x10/16z] 1S470SD0000XkfjVvzzj0Aw-e5v-NRH07ns9hfUGCcmnlpzsI5JaYelmgLdS

sprite $DizzySm [12x12/16z] FSQvOOC0540nsUQ6pzj_stHH9N1t06hsAMW5J_zbHdfNNUaUnQT3xKu_htGCxhv8g90UwgQT1lJ2LBNp1m

sprite $DizzyMd [16x16/16z] {
DOw55GKX4CHoRa3wh_RBxBkWwqFOki_4IxSu2E-dsSk4Oh51ZrbiJdWSOn9o3pT1B-fUxR4bTrthXJ3V23u2iFUIusJCAk4KMwJe13ZONM1Iuuxw3PXYxkGP
QshBXCam0Bu
}

sprite $DizzyLg [20x20/16z] {
JT25WSKW403HYGTPflzgJyX-URWBgGpxoPV350j97HjmgIMxxAHLwrTNqWCEiolfJADJ1LoGsni7bs41L46B6pGZrosWGwXM-tjUg50BLm3EsEpoMBUi34yl
85TCYcOjEnU3SFtkc-t5h6h-0r2UphtmxeAgDzCIkdvzQRIXojlj5C-aNm
}

!procedure Dizzy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Regular/Dizzy', $name, $tech, $desc)
!endprocedure
