' definition of the Item fontawesome/Regular/Star

sprite $StarXs [11x10/16z] Om01VauG2M7omraCx9nW6WYW93ypH8eN9C04Ol60bKC9D2OFI0-OoGuJ1G

sprite $StarSm [13x12/16z] HOh50GGn08HObmZzLtiIvJDAmGoTHMTmYH4AMnGC6w3v1BXL7kSPWjD3lehVc5Ki5R8ekvIWoscM-Nw4Bm

sprite $StarMd [17x16/16z] LOw54G0X0CFwxcJ_RVzm6bnJ5K362vDjS0Ixyg2fNvdMXrE2UubxHBvu48ZuzpkN2MSUYp0HbB0nmbl6hQNo0p7hWaKlTUE4Ay13bUMxD5tJniaF

sprite $StarLg [22x20/16z] {
PO-73SH020G1PvlxwR_R5q82Xt4yuguKSCY75VX6OSM_fOTyYoEoFIRhT0xEIE77f5cKnFz2SaJqdBNwRB_W4eNfiM54tpjyCN8PM0Mzv5dzoS6lk_Z-nOAs
s3joGihVAXfhT_YP2DvHtqcijscw57LeELjuJ3AQx5BO6ky_
}

!procedure Star($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Regular/Star', $name, $tech, $desc)
!endprocedure
