' definition of the Item fontawesome-6/Solid/_4

sprite $_4Xs [7x10/16z] Ou03VWZ90w70Y9iVoW9XLdumOE060dvkg2ee1G

sprite $_4Sm [9x12/16z] NKc30G0n4CkpRlQVjlOXn3AIJT1NVWbS8WT9sFGFKGM7q59AJwdP1dboTGW8H

sprite $_4Md [12x16/16z] ROh50O104CHmX_HVBRPocjT8ceps21d2JCWNmpjiGJbe_tcIBBFbYyMop98F0jqbm7KsWlYLlFyvy

sprite $_4Lg [15x20/16z] ZS-50SCW04HHtE7lFsqRTxi8F1nn5RrJeMq9SQCC-yxI_MLMWzBOMQXpvuO1n8RGDlGWDnmxPrfsQNkAF0V8NeoPvtwb6s-vony

!procedure _4($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/_4', $name, $tech, $desc)
!endprocedure
