' definition of the Item fontawesome-6/Solid/_5

sprite $_5Xs [6x10/16z] Ou00VX1Wu0Sn8IG7FoSd8mCBH1m4e2GxFniRK8G790m

sprite $_5Sm [7x12/16z] DOk50S1020FlNI7xJrlluH8-T3EHxRqJukOhK-xUoNhW9lmFTZT9hzm8vXOv0G

sprite $_5Md [9x16/16z] FS654O0m0C30u53B_jjorN-MerGPx2xqg43f_A0wtQ7AMdsSTY-TqdsoKTrcgVJGb98cabK1sBOD-04

sprite $_5Lg [12x20/16z] LSp50SGm34JHIMActt-rYyPt4Ki7rzsIPv0oNPCQIGFOBR_LNQ0XGFpmbwJ6yCZ0SAapKBKLsX-wbTUnLi13TSvv8AhHbT_mn-dm1W

!procedure _5($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/_5', $name, $tech)
!endprocedure
