' definition of the Item fontawesome-6/Solid/_7

sprite $_7Xs [6x10/16z] Om03NduG0B4OmIG_2v1WXp31yWWcFn-S2G

sprite $_7Sm [7x12/16z] Ou00TdumOE010Y050lmy898Jok40aRnG3WkOX78OaJYSO18

sprite $_7Md [9x16/16z] LSX50G012011x8Ti_xJdEZZoc5CF5x5TW1mQFnUufzxBVohpVpZzVmHrBeFyhG

sprite $_7Lg [12x20/16z] RSsr0S0W443HuCxVVziqEBm6ph-L6cHXiaozLK3e_pBJ4dJ_G-rV1tAcI_yc-6OwlVVP_gyphTzdr796aB-77m

!procedure _7($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/_7', $name, $tech, $desc)
!endprocedure
