' definition of the Item fontawesome-6/Solid/_9

sprite $_9Xs [6x10/16z] BKc53G0W32iXWgx_NpktAdf8Ebpdmx1V0dqnYEtj39zXz0Wm

sprite $_9Sm [7x12/16z] HSQ50S800CJ0mvtiFotK-nghddMYllKKRWD2xo2T-UPLZUZT1sfVT_W3

sprite $_9Md [9x16/16z] JOl50G0n3CESOwpsdxPC-YGcJMp_co-9Frstxd09YltbgmVAitDXwN6KZa5A4wRoVMsIhzKhMAjnQoO

sprite $_9Lg [12x20/16z] PSp50O0030ImuaxsdnPtygfUVALPUbIZLRMM3ct4G1UH80lgM36sn0x6gnxSTU6ugOZZAA6B4atMsVQDNRQjUsXYbzt92UBWBZkoE1Ig-9a1

!procedure _9($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/_9', $name, $tech, $desc)
!endprocedure
