' definition of the Item fontawesome-6/Solid/AnglesLeft

sprite $AnglesLeftXs [8x10/16z] Oy04_404mfmCV22AZu4NI86OG0IMOeGnsFYXwdduOPe1

sprite $AnglesLeftSm [10x12/16z] Oy01-46O5qJmWp0cWv61WG_Cus20Yd7pio6Oh30c3pypp3nUJeJv

sprite $AnglesLeftMd [14x16/16z] Oo046BaH90CJFp-4P8HGN50IJ742bO4uS0f2Cg1m-C0cy898Y1m_dCJayk7bGcYGMo1kWvAe

sprite $AnglesLeftLg [17x20/16z] {
dOu53aCn34C_bCdtl-rSELeqmQZq0hQQuzzLqJS2eBm1WpXXXG8iucP-ALU3E3UpyekuFVT-y3ni7Wk8Cap2MeaOGFVAJKnfR9oeIdlLhAVhyafrZNrfXMjg
Y475n_K
}

!procedure AnglesLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/AnglesLeft', $name, $tech)
!endprocedure
