' definition of the Item fontawesome-6/Solid/AngleLeft

sprite $AngleLeftXs [5x10/16z] Oq06_Fm8pCSF5i4W6G

sprite $AngleLeftSm [6x12/16z] Oq03_3mWWX-5uEDd14jXfTWX-W

sprite $AngleLeftMd [8x16/16z] Oy066BaX53y_bEB2e1YW51z83PXF50F3AW

sprite $AngleLeftLg [10x20/16z] Oo02iF7pmndyH3DOO0m6Fdv-3WOC9Zy-KKmcp34yd5ZT2

!procedure AngleLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/AngleLeft', $name, $tech, $desc)
!endprocedure
