' definition of the Item fontawesome-6/Solid/Archway

sprite $ArchwayXs [10x10/16z] Ou03NduOO400X1Y2XK90r00n5pgB3Su2

sprite $ArchwaySm [12x12/16z] PSQr0S104C0mXzct_xHXVbM2HnCFnWV3hITk9X-uNmAU1yX-Rvu7wdvr0G

sprite $ArchwayMd [16x16/16z] ZSV50O0m002nmntsdnQhU_CBljEn7vUBrj6mRZOuBrljHpRxl5hpWOzvyt-F_dA-7-ulF0y

sprite $ArchwayLg [20x20/16z] hSZ50G0X40ImmPtjlzfpTo7Fu8ZOuOdsDEtX20zRWA2jCYTXD-VGogj3XoqlehSyVtzkTppIxaWV70xK

!procedure Archway($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Archway', $name, $tech, $desc)
!endprocedure
