' definition of the Item fontawesome-6/Solid/ArrowTrendUp

sprite $ArrowTrendUpXs [11x10/16z] VS750OK0040XVgU-_QSrpmhELDdTFuNtYA5urU2VFAFYVmjoQ0O

sprite $ArrowTrendUpSm [13x12/16z] XSVH0K0m0CJG0m2o_xPIyCcZRIx_6ZszehnwXrYyEbPAuseW3k-HcTqgdKosDbjDlXq

sprite $ArrowTrendUpMd [17x16/16z] fOtL0SKm549fuyh-qyRbzyc9NWFyXO-DW0i7kBn2x8InjwU_cXmPCjkUa6oOKOVbYD-NxEasJ8Zs1yGUVnvIzO_QXebccHvtV4i5

sprite $ArrowTrendUpLg [22x20/16z] lKu54WGX32lh0kt_NukaHKRFBtXieBz03C-motaU0-kQ43fx27So65jI0JSlSZjbTn6ZVJaA2vBfpk-oUL9sqtP6W57389rMmWdC_NVzHW5ESr33GJz10W

!procedure ArrowTrendUp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowTrendUp', $name, $tech)
!endprocedure
