' definition of the Item fontawesome-6/Solid/ArrowsRotate

sprite $ArrowsRotateXs [10x10/16z] JS710KC0002nj01m-s_hIUBhg0PHFtFb2EOIgBmgQ5SWgkQQ-LFX0G

sprite $ArrowsRotateSm [12x12/16z] NSm50e0m509Gx9RxtrR07gkt-YWoago1HfHMZOuc76eT7Wf3lExxZ6zo6TXRRqunwt2MmKHCfYt53W

sprite $ArrowsRotateMd [16x16/16z] XSvL0aKX201Hl6dF_bThmEkSlsCY7rjJ3NUTM4vWC4DUbnrOfy-vCTjX-agNCMVH4kO_nLfhldvyY3pU0dLqnafG4unwJgUYsEVJGNVir7iT

sprite $ArrowsRotateLg [20x20/16z] {
ZP350GCm30CLvcZ_QKlXyZtFR7n1A2LFazXGWA5uv72IKPcwglUWlTlcICgjnzsbfM1hSsGTYkHmE9t5lmXr1nCrU-JLCWxdHnPfcalxv56RPnPRF_NGmQQv
72aHEUWBoFL0WuzS0G
}

!procedure ArrowsRotate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowsRotate', $name, $tech, $desc)
!endprocedure
