' definition of the Item fontawesome-6/Solid/ArrowUpRightDots

sprite $ArrowUpRightDotsXs [11x10/16z] FOkr0G0X5CM2qsN_QK-Gd-efeB9OSW829MIM9Hl916YHfHOf0oP502HaPTrG75fy0G

sprite $ArrowUpRightDotsSm [13x12/16z] FOo50SGm4CDKRb3xJ_iGEWRRmA4ohQW5U0Iu-wB0PMeB6vncl0-vPBS2P2z5MVQskzlkK2EOEgpPDWDFfAjnM8AvmRu

sprite $ArrowUpRightDotsMd [17x16/16z] {
JKu50W0X20FEpl__zd3c37gC5BOhFhhe0DmKOAIiX5dvi3ju6gz6xu7hdKV2PkM8c9F5xGU7x9Z6QWmRUj6wm-AgN1awU6lR77i-wnE-snbl8Gj9fgLZpxyS
3K5UEdu
}

sprite $ArrowUpRightDotsLg [22x20/16z] {
POz75aKX24DZ-xtiVxTF0YUsEw34e08Z_OqVLhv_SeTJ8hdw0EaLd4fL5fbFBu-b8Z5cdb9j08Cx4z2-78wGAEhAQYQEPmG_z_uWvynFpf8iW265o9dfDKYz
wxLPdO98Ko1LeJ7e7yThbbxdQvzkiu6nsmK
}

!procedure ArrowUpRightDots($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowUpRightDots', $name, $tech, $desc)
!endprocedure
