' definition of the Item fontawesome-6/Solid/ArrowUp19

sprite $ArrowUp19Xs [10x10/16z] Oq02_2mWWX-4-S4i48C9oEG3Snd0Oknm5eW0CxZu8InUVZu82ra77nC3

sprite $ArrowUp19Sm [12x12/16z] LOk55SD03CNKXb7xRvjtpFP7XhCQvXdcJyFAGv-mOVDm5f9xXC7plXLltXMxksIyY4_6GnVFC8ymkE43

sprite $ArrowUp19Md [16x16/16z] VOo50KKn30AfUs__QR_Bywic0RGdvFThnhk4ydo1-km294brlcfUXEVaMGyoE93yO7wCUZ_0h_xnhoVeGazNMjLJVLdNRNvSvwaHjUCE

sprite $ArrowUp19Lg [20x20/16z] {
ZSw55KCX44JH-KgKst-rKU8woBwpdW_gkoiEpSwCPu8JZ72A5ytNSGrl6cWwzTnoTXLwriS9bIdfjdr7ncsVJA2sZhdDLMw-cvhlHgOd7vWVVCYA9z-GFFcs
z9K_TgdKFFbSyUQh-hpN7W
}

!procedure ArrowUp19($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowUp19', $name, $tech, $desc)
!endprocedure
