' definition of the Item fontawesome-6/Solid/ArrowUpAZ

sprite $ArrowUpAZXs [11x10/16z] LOlL0G0G54Nr7sV_QJMlwuOpWGnO8yxHrary781Vfx55KERwJYZtz4im

sprite $ArrowUpAZSm [13x12/16z] PSg50OKm5CNGu52vsN_RxygfFELFEbUEN1swmw30vDM8Ea1jfbKyb2i3choBktVXrRjesjx5Q3-lJUFrIt9m0G

sprite $ArrowUpAZMd [17x16/16z] ROo50SCm3C3AOUl_RnV3k0hAjDnn97zx-0uMIM2-CjddXmYew_T441r0XOkwW6x5tnsblGETDNxn11-19YBZCu2oVmJM7UHLeQX_1WHwlvdnnmC

sprite $ArrowUpAZLg [22x20/16z] {
VOrL0WKX3CIGTQ2v_scVpBgHhsbgha9SWm-x1DP4iqe3ab8FjiW2mBGi4IKJY5QZW2oOaG35k0nFoHd9vTwrWEsN3JrZmLziK15sUsMtKLniH9IpzOXfjslQ
HtUR8RkhBK3NrRzDDFitadlX2m
}

!procedure ArrowUpAZ($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowUpAZ', $name, $tech, $desc)
!endprocedure
