' definition of the Item fontawesome-6/Solid/ArrowLeftLong

sprite $ArrowLeftLongXs [10x10/16z] Oy0E-E4CVdG67pyC8CGOa9cSw8O1

sprite $ArrowLeftLongSm [12x12/16z] Oo0EyFDZPpB201y_0e34uMhGEGGi0W

sprite $ArrowLeftLongMd [16x16/16z] Oo03C7AXSldvqRXSkBaC_FpyV0Z0oyUF2a3oZ0W0qO2a7Ri0kWE9zmi

sprite $ArrowLeftLongLg [20x20/16z] jSYt0G0X00CnVuvm-szB3Qv8AgKPJYulVY-QQiV4Y1F0azabu5OfWYTmUVBBF1eb0G

!procedure ArrowLeftLong($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowLeftLong', $name, $tech, $desc)
!endprocedure
