@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element ArrowRotateRight
include('fontawesome-6/Solid/ArrowRotateRight')

' renders the element
ArrowRotateRight('ArrowRotateRight', 'Arrow Rotate Right', 'an optional tech label')
@enduml