' definition of the Item fontawesome-6/Solid/ArrowsSplitUpAndLeft

sprite $ArrowsSplitUpAndLeftXs [10x10/16z] DOh50O0m0CI2Ezb_MgJjvNDAuQAXniGEo0ROWPaMWKxpwWGasCTrwWi

sprite $ArrowsSplitUpAndLeftSm [12x12/16z] HOh70O1048IuZrdflrhrqYwl2K1Z9TYrZBXf50yl1Og05orcLdLjURFHCeTxEEncRZoIg7u

sprite $ArrowsSplitUpAndLeftMd [16x16/16z] PS-50S0W40F0rFK_-q-BEwd0uQ14qONaG79WRVZvAhVavNCVbAlxUvA-z4vyKLnMkfAL9QL_TP7aSh1YnFMb69uuADE5HFxnIXO

sprite $ArrowsSplitUpAndLeftLg [20x20/16z] {
PSw53S0m30NHxpBV_jjMOJgHzOAgUZVrVN1q1FJuCI2flRPh1i4JOPRcLSvq1fdY0MSfm5gRW4Mj4VlsR1zrmQmtrmpCRh1epNo2KlFmFzUU3apg0rOpQym8
DJXzk7u
}

!procedure ArrowsSplitUpAndLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowsSplitUpAndLeft', $name, $tech, $desc)
!endprocedure
