' definition of the Item fontawesome-6/Solid/ArrowDownLong

sprite $ArrowDownLongXs [6x10/16z] Os1Wu6K00Nv293S_0nW20Hi3aE9W

sprite $ArrowDownLongSm [7x12/16z] Os1WO6Da005-Rb8eNduG1IJu-Rdv-O5YG02I0v4

sprite $ArrowDownLongMd [9x16/16z] Om02BYO62E3deoA3aGl2uERbvm4n-Fc1Y8kVZm_81RA002W9OO4rCO5f

sprite $ArrowDownLongLg [12x20/16z] nSpL0SDG34MnsuPH-qyRXX5o7bXVpbunvOdcjVPBTuRJFmQ6myX4JpTJ9yvs9ZEUJG_twFQn0W

!procedure ArrowDownLong($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowDownLong', $name, $tech)
!endprocedure
