' definition of the Item fontawesome-6/Solid/ArrowsSplitUpAndLeft

sprite $ArrowsSplitUpAndLeftXs [10x10/16z] DOh50O0m0CI2Ezb_MgJjvNDAuQAXniGEo0ROWPaMWKxpwWGasCTrwWi

sprite $ArrowsSplitUpAndLeftSm [12x12/16z] HOg50S0m20I_xhtzfuq35u4NTOv9nWLph2wuUQ4iS_ruLPY8dShHzfD6stLpUKSNiJT-501a

sprite $ArrowsSplitUpAndLeftMd [16x16/16z] LOtL0K0X08JkTIhxJsidVt266bOZ2p3h65QOmizhsM1DuoTj2gwiEKSlBpqQdCnLtD9e-nOmrLM-RQxylc5N8QeEZ2O0O_uvW0S

sprite $ArrowsSplitUpAndLeftLg [20x20/16z] {
POy53iKm3CNUcEVxd_RZKWKiYbnovRXcPMvOamAol2aIOv7HmRw0u7pC80sJlaxRt_JmZVWv0-YYwu59tla7cxlnM4Hr6e3HXfPhy-PQXkT3itFIOckzCi3I
zywx1dc6V-qR
}

!procedure ArrowsSplitUpAndLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowsSplitUpAndLeft', $name, $tech)
!endprocedure
