' definition of the Item fontawesome-6/Solid/ArrowDownZA

sprite $ArrowDownZAXs [10x10/16z] JKg50G0X2BplLFVVLhhX2gN6HKj5zoNQ1WGHE0qLTmSCYJJ-WO-G7Czjj3GJ

sprite $ArrowDownZASm [12x12/16z] LOkr0SH00CEK7AFsd_OPtPZvXu1gWI1GfvulZGPU-dTJzjx7IyE2jrv63gDPK45riYq6q0sg0lFr75S

sprite $ArrowDownZAMd [16x16/16z] VOn5bWKm40A9UxZ_RIVqVBTQr6i5xxXftWUh9eDPk5kFaCcEU-_Ltdj7SeuV_qxWtiCj-TwJzNYuqwS2198MEzbKaLi7Yo9gNJJ6FctMMZG0LtiVx03kGNy

sprite $ArrowDownZALg [20x20/16z] {
VSu55i0W30DGt27tF-qavRtvCkKZhVg8zlBrOO_XFn19a4mh-yS8ZSEOJhfO8Hqcgn32OVyr3hldCDUV1lIxPG2Qe3UBN80jTNxHs6pbpsO94itfA2TM4a-J
w8bMJkczpu92Qa1pTL0lMG4
}

!procedure ArrowDownZA($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowDownZA', $name, $tech)
!endprocedure
