' definition of the Item fontawesome-6/Solid/ArrowsUpDown

sprite $ArrowsUpDownXs [5x10/16z] HOc50O0m4CI2Ezb_MgZtvHGcO54cLV2S8j1XsZsbjF83

sprite $ArrowsUpDownSm [6x12/16z] TOJ50S0m08IeDyh-qyR-kGE00g2kQFKOX-ckrTjVL0FCT

sprite $ArrowsUpDownMd [8x16/16z] XSK50S0m4CNGZ7dnhxRm3JG7ZzP7KaElatwlrqcPQBPFPEWJdrzVLyLqWQ4LAW

sprite $ArrowsUpDownLg [10x20/16z] dOs53SHG5CDoK0RlF-qdgmlKeWU1D7vNv0-COQBZnV77mms1VOQiwLD-K-8aRwSVwvX6nzmcgsIFenw7WKC5

!procedure ArrowsUpDown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowsUpDown', $name, $tech, $desc)
!endprocedure
