' definition of the Item fontawesome-6/Solid/Asterisk

sprite $AsteriskXs [8x10/16z] Oq02_CWqFnUGvkS7Ce008iBF1oJPmNn6e2GGCVEZwmC

sprite $AsteriskSm [10x12/16z] LSO50e0m3C30u4x-_rfqcgtjKMT4yslzrOte_aWFc7nhUNiGxzF-eczaKLfuz5U8WwSR

sprite $AsteriskMd [14x16/16z] ROw30GH14C1oM2FzL_lsNnPZS4JdW-boP8Noj9O6QhfPJGCCTLfkNc3nnk21QkDEyyuEx6gThbC57VS9cqPONzEtmys6VBBSnHa

sprite $AsteriskLg [17x20/16z] {
XS_50GHH2C3G0EEM_gjTTtsdBoZVjCcJL9xKZuUSw_umJB3eUdb8jIWFXj9Or8M3sPlY95PFHcvUxgCNBKUD1vSws-LxYL9Q3u99yphOg075VTA8lylTkVB5
7W
}

!procedure Asterisk($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Asterisk', $name, $tech)
!endprocedure
