' definition of the Item fontawesome-6/Solid/AudioDescription

sprite $AudioDescriptionXs [11x10/16z] Oq02_BW1BoU41YfYu6BWWpA1EbY1B0BQaIG

sprite $AudioDescriptionSm [13x12/16z] ZSV50S0W0C30rBtPVzgw02_kbH0n6mgipo3Bmjq3ilhCgIllcRHkgzh470xJ-kbs

sprite $AudioDescriptionMd [17x16/16z] dSk50SCm34JHhvhnzf-sp9myeuWNSTuRcwXrQjqVvsxZ83dsBWsGvP3evmRdE2MI3ZfxrQ72kS5wDnpWTJFLk_vZUWBsW1q

sprite $AudioDescriptionLg [22x20/16z] hSm53e103031nPtz_sz9WyF5RoBriljfVshGlsKsatZaCWolXnErIXYz02gC7Qow6oceb2BIJdS5A-nTQTpDK1OqHhTcSiTE2BgBdmvxjpQFpXGM_ngIDW

!procedure AudioDescription($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/AudioDescription', $name, $tech)
!endprocedure
