' definition of the Item fontawesome-6/Solid/B

sprite $BXs [6x10/16z] Om03NduWOE3dPM3Wvm6HJFnWDbYO7yncW95yR6ny_6nWzG

sprite $BSm [7x12/16z] FSg50S0W4C30rBtPVreS3dcbEan0trTHmBU6JwVfThAujAsJZ53n9oiH

sprite $BMd [9x16/16z] FSk50O0m3011tE7ttvPF9GTjeqFwTFbIpGRJDArWC6XdhC74L8CtMcw1GQZ1gBF4uUt1sWFqA7RxLle1

sprite $BLg [12x20/16z] TOo50S0W30H3tM__ROixXqJ_9MUsA9E-U7HEnEIltOGdvB93pAUGbtrbOk6JCFbfUE4AMj5Pp6MGdoR_DiC7T-wvXUoMWXy

!procedure B($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/B', $name, $tech, $desc)
!endprocedure
