' definition of the Item fontawesome-6/Solid/Baseball

sprite $BaseballXs [10x10/16z] HOcr0G0W40CFXohxJul3MnIWAhD6UzeJKbhgkFg43VdogrZVNWlfT0m

sprite $BaseballSm [12x12/16z] NOo30G0n302JDtlxJrlxOafWuv8463mnBQGqrNy8-XFP3F8py-fL3izoHlU2CrXw6gwDU7oYiUi

sprite $BaseballMd [16x16/16z] RScr0SC040J15UDx--_MRxXC4ntmDUCr4ANOLhviWxPAZHlATcKTqCPBVsRrv39WoFk0yT9WiEx1OBTXwcOhrdHjGAcnq6uRbGg3EbuMxGq

sprite $BaseballLg [20x20/16z] {
VSy52WGn44JHcdWoykz_swMXWCRsZSPQP4iyGqa71F1UCi1piDCK1tyzHTQb3Y6-vcrC0RRagPSq2I1FcQJDuB-k-f1T5wEMGP9RCZN2gnViydhH1QPSYfd2
SNlR9uFRL_KkMq0jl4NX1m
}

!procedure Baseball($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Baseball', $name, $tech, $desc)
!endprocedure
