' definition of the Item fontawesome-6/Solid/Basketball

sprite $BasketballXs [10x10/16z] 1S4t0G0n002X-v8suTzje2gZAZwSaj2847r90C54QeieEc6h6g0k

sprite $BasketballSm [12x12/16z] LOg30S0030IlPdBxJripV76KFMSfgXyS9ufE4mCD3gX0A-9J9-mz0YHbyylV3pj0jLG0GctiO0K

sprite $BasketballMd [16x16/16z] DSV50GGn0CGmB-F4_LTx4D1FL0i-4qCKrQErsEzMIpnNrPqNOWYjEg66jLSNFLaflGAh5dg7KPzHYZCmzLhWKkbLY8QZTxv21BPQqR02lEFMmjGUW2y

sprite $BasketballLg [20x20/16z] {
LSy7ZWCX5C1G3wE_8QJu_hTTqOdL7_KpU_WEZa9JKlrSarJlPleSLbJ2rjN4Kf7t80F2Yi4a1Qrua1dLWB98kUzvvoGVASLRBIpQNHH7xqqLCy3V92raoEhl
9_hGV1P9egY9Qr6UOy9pa6GhqdAOwY3YC5QvsoTH-mS
}

!procedure Basketball($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Basketball', $name, $tech, $desc)
!endprocedure
