' definition of the Item fontawesome-6/Solid/BatteryThreeQuarters

sprite $BatteryThreeQuartersXs [11x10/16z] Oy0E-660WOUV4mA073w840CB3YO7Fq8V2rGRExAn

sprite $BatteryThreeQuartersSm [13x12/16z] Oy03c640oEP706P-VhWIVZv-VZQmA2D83KuEK1tSD7vUPDFms0y

sprite $BatteryThreeQuartersMd [17x16/16z] dSYr0SCm04N1BsQz_QSDnr0PhZpTO5jVLKdiQHBTgkF0zF4bAJB0yFC9JeNx-KIepBu2AtQ69BTXTS8J

sprite $BatteryThreeQuartersLg [22x20/16z] jSZ50O1G3C3Gu4xsdnPtEF9VlOGI-rG1ljMqKwjkLBGdtaLCqkthhj--1lhsAdUPKle1UbyI8Atk2lum0W

!procedure BatteryThreeQuarters($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BatteryThreeQuarters', $name, $tech)
!endprocedure
