' definition of the Item fontawesome-6/Solid/Bicycle

sprite $BicycleXs [12x10/16z] POp50O0030Dn9zb_Mwxou-ew_F3HqJYiAtY9i7Ybx2Rhfs7Lo9WIrJhA6gb6uQvyD4tkdna-

sprite $BicycleSm [15x12/16z] ROd50GGn58KOYoVqN-tw_jDmUGAtQDHj0rfiFG49_11hoA5XiFifQHCJk7OzJjT2LQQ8IK3WLtGfy2aBqjm1tcNZ2G

sprite $BicycleMd [20x16/16z] {
VSc55GGn203HMJV2zD_jFSxz9pZ_37dmRjQHkpwY0sXojwWK5vvunHCzOAnyjMKQKWUtd85PTKPNcIoWX806QkrtmOo8b4rix2fecMWooEZi1AG0rLCNtSTc
e-XMFQXLoht_T08
}

sprite $BicycleLg [25x20/16z] {
ZSu3WaH1303H-cPIzp_jeh76l3OJ7Z5D0pzPr5zUxDvyf4gXV1JQhau6dwNTo2UNPaIaoYTgri69xb3TRWyM0zLOWC42T2h3-ph7sxNUE50TTpqMxUcVog97
-TFmPBUP20_QFnwGcMfU4EviWguACDM13qjDcFMYACj5JoQBf1e_B5FTATwNlti6
}

!procedure Bicycle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Bicycle', $name, $tech, $desc)
!endprocedure
