@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element BookTanakh
include('fontawesome-6/Solid/BookTanakh')

' renders the element
BookTanakh('BookTanakh', 'Book Tanakh', 'an optional tech label', 'an optional description')
@enduml