' definition of the Item fontawesome-6/Solid/BookJournalWhills

sprite $BookJournalWhillsXs [8x10/16z] Os3b1mCcVZXWWz8CV52Q0Kgp0naOW8i11FXXKW

sprite $BookJournalWhillsSm [10x12/16z] RSd50S104CD0Xz6h_giDSswUaiGkH98D-yha6FPMgIdshQOMkzQyvJkCTeZJ3

sprite $BookJournalWhillsMd [14x16/16z] XSc50GGX40J1mPtEFzftFIrObmeVIVmgh0nWygPF0ggRWz1UrwZfGz1hgXdvD7cH4WgyUQboQjgt0JYzTHoCDz3WnnK

sprite $BookJournalWhillsLg [17x20/16z] dSn50aCX54FH81-7k__Lrbjas3DxaaXkiF2gx2o7paTZLU7QLWBB45z30qEQVRBciPDpSzEJIfgH57DIisNMIbrLXibAylpFsnz7Ww45hO0r4qqSvDZT0G

!procedure BookJournalWhills($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BookJournalWhills', $name, $tech, $desc)
!endprocedure
