' definition of the Item fontawesome-6/Solid/Brain

sprite $BrainXs [10x10/16z] TSP10a1030F00IxG_xyMSeDjssGmJrOmLAc2YYg8zkWL6Ote6AFE2G

sprite $BrainSm [12x12/16z] PSQ50OC040F0gnVD_jFYpajoqF8jWJgHVA39vBoHnHLPdUhWxy7BkETdCu-3AIO_w04

sprite $BrainMd [16x16/16z] NSe52WD10C30gNlp_zVMvVQmC11mFACLmA5IBO1Z7t-EVWvs4o_PDd5S1Yyi1zFWhZEVHizxPh3HLwm-_X2REghW3W

sprite $BrainLg [20x20/16z] {
PSk53S105CDGbxdUVzeote_uoU5ORGMC4_jkqffPVQXG7L2T7dhiARkVPJjbuy-QtVHdpb2d9fH6AunVKtCQewdHIgCn12iWjPne6P3_RU9OEQZzOLLso9Nc
j7Uq0W
}

!procedure Brain($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Brain', $name, $tech)
!endprocedure
