' definition of the Item fontawesome-6/Solid/BridgeCircleXmark

sprite $BridgeCircleXmarkXs [12x10/16z] JOs50O104CE2Ezb_MkJzN5jQiGhSlqatm7pFdpcl-qpPOwh_j40OUahO6TnIRsc-99eN

sprite $BridgeCircleXmarkSm [15x12/16z] RKx50G0W23m-Tkm_hTtI3OU7uaaIoaMtX6f_oJiSTef27YiR9LUSxKkXRtVR5Ov9zp251GyP

sprite $BridgeCircleXmarkMd [20x16/16z] {
ROe5WaD12CKolji2x_wdhNsNZ03XSKkSC32T0N9N_htnULKv0MH1cLyImCDSTdZWsZ78JnrSf_apiNU3gK9wpA6C9Xn8qv8g4Hq98AGEFAK0JSua9ZV03ovB
o5a308H-DFRufDu
}

sprite $BridgeCircleXmarkLg [25x20/16z] {
VOy53iGm30J7QQ2KxFz_UsUfJ2F9ZBmJkWSCEZq2fYSgpYnWSZ7A5kiZOJbNPHSbvzb5S_6qlBcu9IQST4iOfKcZSKaOYv4WJ5geGq4h7R1u0IXI62Manfef
Yp4oO99mwch8CvXMVpucC8PROlIuHcu9jjypJldRB2ylS2Kq3sVu0G
}

!procedure BridgeCircleXmark($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BridgeCircleXmark', $name, $tech, $desc)
!endprocedure
