' definition of the Item fontawesome-6/Solid/BriefcaseMedical

sprite $BriefcaseMedicalXs [10x10/16z] Os1WOEFdvsS00tuOnW5W4WWrl30MGXQJ2m

sprite $BriefcaseMedicalSm [12x12/16z] VSh50S1G309Gg7qF-qzRTtkN261aaY9cgJZdH8oO0qarHASV1cqmSgUTZyuaQP9rGBHDDm

sprite $BriefcaseMedicalMd [16x16/16z] ZSk53S1034DHbydAtt_Rgipm3aCQj0mopHeccXaDI8Uxj0CFiBkav9TA74Xng0vO9HgObQNEJ_E3wBWdZdJI0m

sprite $BriefcaseMedicalLg [20x20/16z] bSt50O1044FHuCxllrhSMNt7aKIRaisWMy7fddLeqv3gr7zcBLz9IQHnu4VA0cRQyT0QPiCz2--u3Hqk5N_g-SfbC0C

!procedure BriefcaseMedical($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BriefcaseMedical', $name, $tech, $desc)
!endprocedure
