' definition of the Item fontawesome-6/Solid/BugSlash

sprite $BugSlashXs [12x10/16z] DOg35K0n54FpZUBklstFiw9TLiYBJO8YpV5r6vdSzxMdSr0XUoG3cigvt9aPGkZ5eA5cO04

sprite $BugSlashSm [15x12/16z] HSo54SD030NHDVjm--ysyqD-0sAj4AFmOH9LFlGfeykwhWiAiVknycLin53Gk03LIZK8zM1n_5zx24xYDgKm1HOhx1NWyWK

sprite $BugSlashMd [20x16/16z] {
JSc50OHG3C3G5FViFotMdZpubZOpQRQbJ1uylEsKHj_HWozjEAh5IjfSQMv1Q906tMvhemjVbbzglv6IzyrqS5lDs9juDCskTl3iJP36cX_EKE9jmkn1CPj1
er5fwT-MZmvONVYpUm4
}

sprite $BugSlashLg [25x20/16z] {
TO-3eKKn50Jt8iRqN-rZ-35n3lVCwjYQ3mqoj5S5yDEIu6xd6qqin1u0HWl0QiWSMw7ppI55SEe4SCQ-k9IXQd8ngThuv_-KqYz3QCeSWsD9agI3JkdDVbWA
dREfPl70xvvqIJVatmR_phqrJ3E0fDgx-bnJCvHl8T_zevJUXbjlpjOm1FsWyWG
}

!procedure BugSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BugSlash', $name, $tech, $desc)
!endprocedure
