' definition of the Item fontawesome-6/Solid/Burger

sprite $BurgerXs [10x10/16z] Oq06_4301MKm0p6G0GLyK1P8a0_Au48IGm2463kC0G

sprite $BurgerSm [12x12/16z] LSE54O100C2muaxtdnPzpLsWjgaZhr7b3OsDhqOmMPZE25QZ3ZFMFUhPaWcJ5Oxpjt83

sprite $BurgerMd [16x16/16z] RSs53SKm5CLGXpbt_sa_G_lK8xJ8N8fZTSVNqbjvfvxGmtgdqvjJXwGZcAQje8CDEZEzm1yuAEC8blsPDku

sprite $BurgerLg [20x20/16z] bSx50S0W50FGu4xsdxRktdU2xtWWf9BOuIHY5eU_OqzYK8PFLLo3WHIS2H8T7bH0yGWGFCArohq8yCHVn2BCnnqY7VsusNrQqG8

!procedure Burger($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Burger', $name, $tech, $desc)
!endprocedure
