' definition of the Item fontawesome-6/Solid/Burger

sprite $BurgerXs [10x10/16z] Oq06_4300sKm0p6G0GNSK1P8a0_Au48IGm2463kC0G

sprite $BurgerSm [12x12/16z] NS650O0m0C2muax_lnPdbb3Or95Rhw82YBTAC1WOzr_DxA_1Y7dzjIp1WC4Cs_wQEG4

sprite $BurgerMd [16x16/16z] NSt50S1030F13NFKVxN1GytBR7vctC-j9JhrM_vKB_Gu_XJz6itGgWIxvQwplcgM7z0M6fYs4Xp-pt9p0m

sprite $BurgerLg [20x20/16z] ZSx50G0X40F0u4xwh_RSbNck1X-aKbAS2bnah187rKrLYKdcL5FSYvO4LuB4W1S9aBm2n4FjKULP17ZZ7seHfl67I5U0Qiticbxq

!procedure Burger($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Burger', $name, $tech, $desc)
!endprocedure
