' definition of the Item fontawesome-6/Solid/Burst

sprite $BurstXs [10x10/16z] NScr0GH100GWNfELwR_QSoVb3Hsa4T0oUTKFie0icfuThyTsv5-Z1mYC

sprite $BurstSm [12x12/16z] 9Sg50G0X40F1VLUI_gl5CiZfkj29OR5WDPFiHJwPxCZM962LGoGBE1qhdIDft81NId-tYSG6

sprite $BurstMd [16x16/16z] LSg53SH04CLGXpdklzg3qU8JVXWFmWlXK81J4dK3FPlYHMMu-Diq8xnc44pYVzfQNtlzOUFFZ72RZNb-ciFb4nsZakbAQytJ5m

sprite $BurstLg [20x20/16z] {
PStLeS0W50JHYHim_LSRHPwSpokxVU3J9OgW0uzeJw56RdfG3DvwHfKgUZkyTGI7-jsCkL4RiiEizOpQHA2B_hKd_wC__6th_XH7iis6J9l4QpUBthfoDXDK
I1fuX3LlW2vCDBhnrsv7TW4
}

!procedure Burst($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Burst', $name, $tech, $desc)
!endprocedure
