' definition of the Item fontawesome-6/Solid/CakeCandles

sprite $CakeCandlesXs [8x10/16z] Om02LX31mSy0X8mC3CmCF0pSG44m7qwpyQC21aO6JWOU365-

sprite $CakeCandlesSm [10x12/16z] ROh50S103CDKvch_QGj7hoWS6rQOI4WdisaRP9DAKvUaThtT-biZ-FFk7JhxmMwwCE05

sprite $CakeCandlesMd [14x16/16z] ZOU50SGm00Al4azW_sdVNOi3n8F3nGH3l1ZiSd0xDKHD99tx5TqBmnFjqESdJuUU8TdInLFqLXIj52rSE_dg5V-0djuU

sprite $CakeCandlesLg [17x20/16z] {
dO_50KCn34CLvcZ_RUj0cVyxc14REuJ7f3SHB4F4cICLqX2Td7MaGHq1hW3IA2nEH3LuXHg5PeZ4FWBwSs38Ewpd4N8H4Pk8G19L0wQE5ug8c0rCavZjMS4n
AHnPyHWu0G
}

!procedure CakeCandles($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CakeCandles', $name, $tech)
!endprocedure
