' definition of the Item fontawesome-6/Solid/CandyCane

sprite $CandyCaneXs [10x10/16z] Om03TZu62E1duEVd1p70D8W5vS0P712QcHiiniuF1CmGvHmW0HweDh0G8uG1

sprite $CandyCaneSm [12x12/16z] BSh50GH14CD0BGyh_sWFNPy6cx_3GhYhsLrraUDE48j9g6QRw0rG_Tg1JGjs0FjfgbEd6t_QY3S

sprite $CandyCaneMd [16x16/16z] LSh50SH04CJ0CRCh_sWFlQHNWo9pMAF0IbbMWlcUop_RWjHdPmzHSQvDtorH-a3j4rEf1_INf9vnOqagH-TCwZ12zwytfiKS2IGr2L7n1W

sprite $CandyCaneLg [20x20/16z] {
LSx50S0m34DH5SFv-qzR1lkT0WR92Br7EPaEKFIheCp9bZ6DC0ZJpod85QwmZ9pa5G0v0vC6P5M0Y7uBjyMqCVbnzoqfK_K8qBbCkeqTLerNuQDnwX7--5tp
tUOYIQPDYbogB4w3d0cYl1q
}

!procedure CandyCane($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CandyCane', $name, $tech, $desc)
!endprocedure
