' definition of the Item fontawesome-6/Solid/Certificate

sprite $CertificateXs [10x10/16z] HOZL5G0m4CAey7lPVzgwv8GyDB12YmeiOREQRUQYAuxVwSctwPxP0G

sprite $CertificateSm [12x12/16z] NSp50O1G081Gx9RzfxNznUcT06XWv4jxvqzVH6yqnZ167paQOmxiY-SM3RlO0oS

sprite $CertificateMd [16x16/16z] LShL0SDG04BHsyQ5n_xJnetpXt0eW7WqDZQdTaBUrNy1J7wnozpea-UgE96nXyZW92UeF-aF_6C5PTxDp_bKkSTcjm8

sprite $CertificateLg [20x20/16z] {
PS-54GKn203HFLUo_LVxNPZZZIOuRyS4j8vC9y8W6NrBET5ysxNn_iiEdiAi1nYRsGw7rMH5_GIyc20idysggta7i9jrrDjcwb_mr8v-zwsRO-FhSn6PmkJE
onq
}

!procedure Certificate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Certificate', $name, $tech, $desc)
!endprocedure
