' definition of the Item fontawesome-6/Solid/Chalkboard

sprite $ChalkboardXs [11x10/16z] Oq02_730m0yLOY6T2TJEoCBFoCR6nWvaihEnyIC

sprite $ChalkboardSm [13x12/16z] fSUr0G0X00F0lE9a_sbnhRdkiF4SFj3RXXvKQ4xoFC-Tyzw0PeBtyLm8luW

sprite $ChalkboardMd [17x16/16z] lSYr0S0m40D0cU5f_sd3dDxN2F0d-a20sajOZXWkrU9ou9O77yIBl1qXOc4hWekkycOxz6fFS1yp

sprite $ChalkboardLg [22x20/16z] tSYr5S0m50D0AUz3gVsd3JExzPM71nPdG-eAoAV5WTMtcd3Qncn8haipC2QfISP01N2h0m

!procedure Chalkboard($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Chalkboard', $name, $tech)
!endprocedure
