' definition of the Item fontawesome-6/Solid/ChessQueen

sprite $ChessQueenXs [10x10/16z] Om01VY26CFZPOKm-k108CN3omm03WiKDeK7Q4InEC6104WC

sprite $ChessQueenSm [12x12/16z] LOh50O1G08MmM_QVrlp9wGLyI4BFb7Ux63VejpUSh3fgoz6PeSnzZb3cCSTCvTm

sprite $ChessQueenMd [16x16/16z] NOk50SGW54E3Ezb_shjw6nxw8pW9n1T3Yk2M6PNkCxMsN_MC0fxq62HWCCd1crsZiCuUAa1d3nMWSyA1kJd7FcxYCKh_3m

sprite $ChessQueenLg [20x20/16z] ZSx50S0m40F13NFKVxLXD8_XTI1kdGeCeoGCsZG9TRHpniymvCV_wSwEnlnkhwKictNhiafJ9nkozDY5O1LEm62LMOKZkrvV6LRXpAdxu9QzECtwojbPyLO

!procedure ChessQueen($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ChessQueen', $name, $tech, $desc)
!endprocedure
