' definition of the Item fontawesome-6/Solid/Children

sprite $ChildrenXs [12x10/16z] LKg30S1044ljPlzftwT73E17FMp0l-5Jy6Z9rX1RmwFyXQnHGzRJyVigpZtPPDDmQxX4dG4

sprite $ChildrenSm [15x12/16z] PKk54GCW40lkPFzjUozrU8i1g1lwRf0PoIMR96pNJuXWAy7DNVPMDP0I5YIO-eBjTldnhik0xkZPAR0Bn12FmF8F7m

sprite $ChildrenMd [20x16/16z] {
VSu54iKW40FGnPtS_xHjMV9TqW9lCXQv4gSm4MOZ0M1rLxzhNd8gT-yCfQrygFP4jPxrzLXHteMTkygzGfLCISCjvYu_FL-PPQ6EieTogdR4Wsb15T0fzxVp
TxarxmG
}

sprite $ChildrenLg [25x20/16z] {
dT15WiKW40RXFmakNVS_xHWsjdhVgZeAw5CWQclzMbc0kWQ0qsVm0EcV6m-0qt01ZoO3q_RekE_Jbx-qXR3AyScV5TBElzSVq-ZosIoNT76wiqbsEi2O38fd
Yntgk67qV9ugycBuA7dPRjqCGH_MZK-HeSmRtM2Vc_R16Qs_VkC2mRtEgcHCqZi
}

!procedure Children($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Children', $name, $tech)
!endprocedure
