' definition of the Item fontawesome-6/Solid/ChildReaching

sprite $ChildReachingXs [7x10/16z] Os1Wu6HY005-VX01f20458D5UO0a9iMBe

sprite $ChildReachingSm [9x12/16z] VOQ30S100CHIkzb_sjhuOm3Qd4MDHe0KIjHZJmnAh7MZGAJBGmYg7OeRZ

sprite $ChildReachingMd [12x16/16z] dSR50OG00C2mdk9q_sbnTyWhrFxI2zJ-gVe6CEUjWg8XV20tuQNfYwyAV6pHQFlqtydPVGwK

sprite $ChildReachingLg [15x20/16z] jOdL0SKm58MeUy_-qpPkVq-9Si7JtmU5KPQYfzC-b1NsK3lxbVobtTq7bpJ0qC4XJRxCW9lVsA28D-YYdL0xVz7fQBJRtb0cNLWC

!procedure ChildReaching($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ChildReaching', $name, $tech)
!endprocedure
