' definition of the Item fontawesome-6/Solid/Circle

sprite $CircleXs [10x10/16z] Om02Jdus1X3W1mDE80CAM44ig2W_9c23inWGB9X2e7ciK0O

sprite $CircleSm [12x12/16z] Om01RduE1WZWXm084yxXXmDU93O_Dpzsm874Pi3EPaSOoWUoZ1Sc2W

sprite $CircleMd [16x16/16z] VS-r0S105CDGXpdQVzem7FxNgRDrQHQcGg-5MtSddzLFcAK5Lo5y3Ru5suIlm2SygrglvGzgTPZzb0hdpGu

sprite $CircleLg [20x20/16z] ZSl50GHH309GvhlJVxNhIbRctH80DtLn9Bo8l9aRRlYYwkkiwUii0f4Ae550gz9Qt6VGIhH0Os9IEMnK0Ag-pfeiBwAsBWelfiFP4G

!procedure Circle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Circle', $name, $tech, $desc)
!endprocedure
