' definition of the Item fontawesome-6/Solid/CircleDot

sprite $CircleDotXs [10x10/16z] Om02Jdus1X3W1mDE80CAMC4iBh0e4CELS45OR70ng3Y8nGaY8HAiK0O

sprite $CircleDotSm [12x12/16z] JOo50S1020D3tRl_je_3lQ09XFi_OFn6fa9B_rTpmYhXrXGucueu7lnMpZ_foU0aIIKFzZBzHFP6Tm

sprite $CircleDotMd [16x16/16z] NK-30G0W4Cp6_jEcorTlam4PiwTa8MP0mymR2UP1GF819P2AMYXoy5v7XpRIrTSNeqDNVMVsnEbEGCDL5TP6Aj-ujj-3mcjYatLD1G

sprite $CircleDotLg [20x20/16z] {
NSq53iK0309Gvjfn_zD-8IHaVV4Am8w7zmh4Ggi1HiQHKPmPnPAio5cTj1sUu6VmyF2zh9GdPwtlVCrkoclcY46ZomVqBgD2iHini0DmzD7VsJvbwLUoKqf7
-08
}

!procedure CircleDot($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CircleDot', $name, $tech, $desc)
!endprocedure
