' definition of the Item fontawesome-6/Solid/CircleChevronDown

sprite $CircleChevronDownXs [10x10/16z] FOdN0S1G20993r-t_xIlgcS5D32l9YoS3pprOH1hvjPitlMMVQx8J5RmnDC1

sprite $CircleChevronDownSm [12x12/16z] HSp50O1G3C3Gu4xsdnRvrdUfbz_XIcOMwITIlJ0SIXyBE-HqLJTo5rDXpfibdjvyhjfz0G

sprite $CircleChevronDownMd [16x16/16z] LS-54S0W44JH7yUt_supw1mFTuxcoOe7KrRtKHrQ2e2CL3TR9zezjGHfDdKxrDu9wW947NqOQ-LX37LeJA1cD7wqXLSM-uTUWBGFuJJH_

sprite $CircleChevronDownLg [20x20/16z] {
PP053i0m4CCyvkN_hnsUee95gPiYmN9g7qcO51mTWHAMMabhhQJ1UoM0AkRSdVyvV_iVJBIUuPMl-ftFFr-5NdRB2HfzZD5CRuz2kgM38zBcxGSS3R3K2bQb
n0yEQSlCSUB0omq
}

!procedure CircleChevronDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CircleChevronDown', $name, $tech)
!endprocedure
