' definition of the Item fontawesome-6/Solid/CircleStop

sprite $CircleStopXs [10x10/16z] FOg50G0n309vgGlxJrkd5mzW46WnuI9e8StSGWYpar4MRVPke43G0fYpT

sprite $CircleStopSm [12x12/16z] JSd50S0m40D1XJdRVxK1ot3p4kXtiCemnypHBkLt0ewS1ondrf05JCCmx3bdYqHswtEHrnS

sprite $CircleStopMd [16x16/16z] NSy54i0W44FHKFVS_xQTNytmS6TrwNUlHS3ksoWKVmx63XkRKoFgjONHKxN2HdVFCQhnMerBDPQnuVxHu1I_nt2VYo6QYEO4

sprite $CircleStopLg [20x20/16z] RSm52i1G30FGpBNB_MyxAa09_stVQYZNntT7Sx3OWiBcqf2xDUGsdwM0whYSqPse8NtqDOXz6YiQUmUnVH3BmthCO5GRPYe0buRSpMv1sBGgd0osmVq

!procedure CircleStop($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CircleStop', $name, $tech)
!endprocedure
