' definition of the Item fontawesome-6/Solid/ClipboardCheck

sprite $ClipboardCheckXs [7x10/16z] Os1Wu6PZ009-Vdus4C70pOy5i361f82G7qoZ0m

sprite $ClipboardCheckSm [9x12/16z] Om02Nau6CE070WO6TX39o4yOy88ry37mCq3uZ0mSK1aUL7Km1W

sprite $ClipboardCheckMd [12x16/16z] ZSkr0SGm04MnRsQ__QSz25O1zT9VmMl3JzTFwvFfeFSu-37Yr7d3iZbtInGL5bb6XasHE4nk9KvV

sprite $ClipboardCheckLg [15x20/16z] fSx50K0X30FGVCN9_jFYUkRXsgBuQIyCdidVLve5aglC7517RilEyOI3uGAmh6oQt7ZcWVm0TXR9_j2TP_LiAny1

!procedure ClipboardCheck($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ClipboardCheck', $name, $tech, $desc)
!endprocedure
