' definition of the Item fontawesome-6/Solid/CloudSunRain

sprite $CloudSunRainXs [12x10/16z] BSU53S10581Gwbxst_RovSM0yD0cjJF2xbcTb0buVMFrWCN7yX3N00uxmmem4Qx7IMG

sprite $CloudSunRainSm [15x12/16z] JSh50GGn0810rZMX_sfFulC5u8A5JfLgkNmE0yNX7cHwjlgYanfTI-Kr0NYThQPo5m4u6MeoBmc5nEbu9abYN4NS-G8

sprite $CloudSunRainMd [20x16/16z] {
PSY50S0m3C0mZw7W_xyTOnKEgmbe-ChssO4FDv77eFOGyy13-_KFO-YuzABYAeQPNH9jHq-i6erKU0ci-cp05pOssPUALMfZyLkRZy2bRauyufM1Iv1PujOh
JauuhdrB5W
}

sprite $CloudSunRainLg [25x20/16z] {
NT47Wk0G043HBzAm_FkVTcScdPVe7G1I0E82esgYM62a1mPXKQiwyxMgJaScq57NIHlCEIzz2shbdqUoS6kYnkWjSoWQ5pF5Hm28QcCY-x41J4cbsKaSh3ZW
q4fmmA4ax3LkmGuVKtm4lfOhHEXQaYlLW1AjVDTWFIuiqJt0veA24Yp03m
}

!procedure CloudSunRain($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CloudSunRain', $name, $tech)
!endprocedure
