' definition of the Item fontawesome-6/Solid/ColonSign

sprite $ColonSignXs [6x10/16z] 3SO50S0m00F1Z7ddtst3dsIQpgv31x5Px5RVwtERPYAXa9PuBHa

sprite $ColonSignSm [7x12/16z] 3SQ50S1058DGwbxst_PuNnBoyn8H3iEhmSNJvnAdQW_P_Rq4VVrdDWsJMRXSXG4

sprite $ColonSignMd [9x16/16z] HOQ30GH10CHoQwV_QjyOXgVMnNc1i_dyxbB8laHIBOe6JxPUZcXVyaWN_MTuQN20kfgy82hpHQfVgE2kPk2oBO4x

sprite $ColonSignLg [12x20/16z] {
DOw52G1140FpVZxzT_iXS0Fhgd2iGwKhJFe12l1TnFy8oowRxRw01ZpGBXj1EU1eeDToMoR3ijGiS5kcfHrmg2Vt591EU25b2OZ_vG4OhkQtpYOJX2fL-61-
CZ0ibsHMdfBv0G
}

!procedure ColonSign($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ColonSign', $name, $tech)
!endprocedure
