' definition of the Item fontawesome-6/Solid/Comment

sprite $CommentXs [10x10/16z] Oq06_200f5du8G0e0WFSS1OldCM0OF516KmCSAtSG0m1

sprite $CommentSm [12x12/16z] TSR50O0m0C30u4xsdnPtsdiT7uFQR1lTrU2bmjiGEU7Nf6SRqA7VHrTpcG4

sprite $CommentMd [16x16/16z] VSV50OK0500WVjg-_QUrkxZXqh-iyy-SLqmgaCNgHHfRn5voU7ruTVZxSFiMNhjZinhvsWz4b1wq

sprite $CommentLg [20x20/16z] ZT150eHG081Gx9RxdtOwzTTRieI4kcdgYX-zRxpK_bYuQ_q7r1w19qFbsMAPpRFECpoPwJq2Tl_LvzO0bUS5czhHBTksJZKFYuuKk08

!procedure Comment($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Comment', $name, $tech, $desc)
!endprocedure
