' definition of the Item fontawesome-6/Solid/Comments

sprite $CommentsXs [12x10/16z] Os1WuEHdOW02C0i486mW0yRXWx4PGKeW02ZF25F31-B3XH46mDbCI6m67Z0R

sprite $CommentsSm [15x12/16z] LOs50O0m40E3ExV_j4WzrxwRFavc5GZi5i4IeecC5K4SLWMQsHiWXqSNpQR-E5TjpJxr9FpwAOzV

sprite $CommentsMd [20x16/16z] VS_L0S0W34NH97Lz-q_RuWxtZuEJxi2xKXh3zaGIX88XzZfQaEJipUmwHTcTcJiWDrrccnlG4UXs10OUc6PF42RLfAxRghSBXlyvg4QcsEFn1m

sprite $CommentsLg [25x20/16z] {
TSw5ZSG044DHXtb-_zKUX2olj2-SGPtcWsFKfwxWTBJnVy86sGXOvm19Zm6BaY8jwhy5pfkqaCRk6KNInaddYqrwMxPWk_DY-koHBDJKB0NK77rbJiz0Iv1L
hcTH8ij8grEEhndu1G
}

!procedure Comments($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Comments', $name, $tech)
!endprocedure
