' definition of the Item fontawesome-6/Solid/CookieBite

sprite $CookieBiteXs [10x10/16z] Oq06_FnyK0OGm1WW365n0p4Ra0K3G1OpY08ZJY0BMHfc33i30m

sprite $CookieBiteSm [12x12/16z] Oq05ZFpyN50c7pyGm4I102e3f3b011k83GECG3O2WDM0DKFOK3bM94KWGn5Cg57iG1e

sprite $CookieBiteMd [16x16/16z] ROw50O0m40E3ExV_j7Xuf5TzZrBKK8MLioDJST3RnjGHFhtv7LPzFhQDxS2scoZQgOJgwAJgto0aX3dhOEQaacacQBIp0W

sprite $CookieBiteLg [20x20/16z] {
TP050eGm30H3tVl_rvviRJaPgCKJ-K_gNTybiRzeB55ze4ZM5nngKpIRAGauBuZMtU3C72tFqoqPawybOv9KjX4D6KhHmzoBu657jGN2s4RfkAEIazdtEwjg
ma96bZIS7SqBesnAQofF
}

!procedure CookieBite($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CookieBite', $name, $tech, $desc)
!endprocedure
