' definition of the Item fontawesome-6/Solid/Cookie

sprite $CookieXs [10x10/16z] Oq06_200Pa00c074K98RpkA7iPX151XnWeNOaFH2cEmC3

sprite $CookieSm [12x12/16z] Oq05ZFmW06RoyKC08rGKAWCaE1Z0R3uW1GVeR0weOWQ472i3GX74AhXb41bs80q

sprite $CookieMd [16x16/16z] NO-r0O1054E3DoVxJuj6WDTybo24jLziZCPE6YwM7gwuls6PMJjO6I_e7ofZmzYpo1RCr_orAJ_yxgzvA0-Z-RZOgkGT

sprite $CookieLg [20x20/16z] {
TP253KCn34JlX_dsdxRWnb90VG8puZ-5vAXXyMGgwZLSY12uaRJLYjCqWqG5Kt_W5jzKAgayu8K7BmhwObLOySag5hgm6Futgeap3p4WkkDsSkGElgHZ4s7D
D9YuvLCBnfTYf_u6
}

!procedure Cookie($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Cookie', $name, $tech, $desc)
!endprocedure
