' definition of the Item fontawesome-6/Solid/CropSimple

sprite $CropSimpleXs [10x10/16z] Os3WPe01VYZDpS_FnWy2S36IM200916c0W

sprite $CropSimpleSm [12x12/16z] dSgr5S1G5CDGXSd_QFzfmz3dDWziA7nikHLjFStGsfwANoU_zYoxAIumUqYKHsG3

sprite $CropSimpleMd [16x16/16z] lSw53S1030D01ygElF-qPLoW9tW80bRuA0KUHYa77doBIacT06Gf8tSbt-iJ1_xofZZjVBi1hbFms11-0DKuNYOv5W

sprite $CropSimpleLg [20x20/16z] rSp50GDG309GwX9X_stxtHVeEoO0W8zWGzuEjpic7mRt9viB8EjD0DpkuNQv5qRRzfJ-9pUL8jmedtZhmYq8jujO5MycQDhUwaC1VW

!procedure CropSimple($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CropSimple', $name, $tech)
!endprocedure
