' definition of the Item fontawesome-6/Solid/Cross

sprite $CrossXs [7x10/16z] Os1WuES74YWKFmg02kAZ

sprite $CrossSm [9x12/16z] Om02Vdu6CE3XvsT4Pd1py_Fpym19301HmmIaI64

sprite $CrossMd [12x16/16z] Om01Vdu-1YZWuUVdPyJ7vkRcvWS27X2D0_0XiM5wcO0qDTdSKFS

sprite $CrossLg [15x20/16z] Om03Vdv-RWOuuE470aRIkTn0m0y2F4069pyfW0kLYp2P2SGQK2uNt44

!procedure Cross($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Cross', $name, $tech, $desc)
!endprocedure
