' definition of the Item fontawesome-6/Solid/Crosshairs

sprite $CrosshairsXs [10x10/16z] BS653GC1300nboFAxRzjzM0xh5lbK5kz4KEq3itMIAKSUXEPyEx0ONhZ3m

sprite $CrosshairsSm [12x12/16z] FSm53W0X34JHeH6SV__RRgPDzk5Kb9v-Xwb2sdKDeS7mFMGRvoeruW6I9sYYWjUig--BtH3LOc2X4iW-

sprite $CrosshairsMd [16x16/16z] LSg50GD12031VNUs_seZ796V4vGIt8GzFwQ3fbSrL99kd48eLKANsP0_fRDjdS15fbUeTeHmgD8RjtsKCkReQFzledPXD-f1iXoKGJKwVYvfdW

sprite $CrosshairsLg [20x20/16z] {
PSy55i0W30JHhNlc_hVjIohOh-2mw3EQ6h2gTE8M9JkV8Iq3WmjW_6TT4imQW4ukkgGu0kBu2_IR80tbaKPSxDgz0SnmwvkPe1MkMLAtnWziZ37zEYBX4kdJ
7UL8PwomoNdwIR1sPzfd94ax6o4M9c-8al5ttG
}

!procedure Crosshairs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Crosshairs', $name, $tech, $desc)
!endprocedure
