' definition of the Item fontawesome-6/Solid/Crutch

sprite $CrutchXs [10x10/16z] DSor0S0m44DHALt8V_zf3SVmAYbgg0iQBiBP0B93Uk1IwCC7Fw101tmDBG

sprite $CrutchSm [12x12/16z] POt50O1G3CM2Ezb_Mbo-zDJdtDSNVAVb-pQiLlVRkbpWUWLMRxCJCbqqemgtM5xlRVdVkSvNrlzb1m

sprite $CrutchMd [16x16/16z] TOt50SCm40HNp9h-gmt7xFdTBMa1xUYW7UmUSsXk7WFqVcpFzJ40ArNzRYXWEqFcVKQgAi0oxNPpaDcSbZTpSyvizST0bUvEnVsf9m

sprite $CrutchLg [20x20/16z] {
PSu53iKm3C1GZtc-_sa_3AF6ugSs2Q5zeApNAQ4PM_OIjIfVgWF7ouA8BrKvslMX0oihBgjrcDHM3TV2h6fzsw8SQ1kMBZIhMX7iABnYysZdRL7dleBuwdWH
cpEjcQWpyGK
}

!procedure Crutch($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Crutch', $name, $tech)
!endprocedure
