' definition of the Item fontawesome-6/Solid/DiagramNext

sprite $DiagramNextXs [10x10/16z] Oq00Vdm08GjH2zN119K2ylducS5ciB6nCB2niI7f

sprite $DiagramNextSm [12x12/16z] Oq06_8G13nARWOiF2FX111lK09Wvp21vBZwm3cu6a5eUa4wu6eWvl8mmSs203G

sprite $DiagramNextMd [16x16/16z] fSs54S0W00F07ExilsrnF-tZ6fnuM7Y8-0_ETSNJPCNYaYz8235b-vRFH7qQoi09WIm_4UBJI938-ZwllKlIZtbuv1y-

sprite $DiagramNextLg [20x20/16z] hS-30GKn00FGr6xst_RZRBv3ZM2Lcf405tBcknoNi3n4enCfC5Zs_NA8xw_G_ie-XvHieFGvKdkIxfFYfv9KlueO-f2fCVJPdr-7_N6Z72KUv5Zw

!procedure DiagramNext($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DiagramNext', $name, $tech, $desc)
!endprocedure
