' definition of the Item fontawesome-6/Solid/DiagramProject

sprite $DiagramProjectXs [11x10/16z] Oq00Ddv-VX3DZm4uWG0a2SGS40L0af4VePKRgXKa36GoeZ7XUW

sprite $DiagramProjectSm [13x12/16z] XOm30e004C2os_x_scpkpE24ceonTI4Uy0cMTGF0U2XYQERcvQFPMbGE_1T12-4GUW

sprite $DiagramProjectMd [17x16/16z] bSXL0e10409GnixX_hTrSUts_H0uwTmzYRKCjUef4EEg6_51AZcbf6GG2imi9I7giTHwTaXtxtQFrCUZ_NyKsB00CW

sprite $DiagramProjectLg [22x20/16z] hT230GGn40NGFuSO_LSRhuqN6rZtOyaN7POHyqNNxITqrtkRarNNRCLqtwuKA9ZF38gqWh10UTNIForZ2QQqhnPx5FHoBzPxTVUZso8

!procedure DiagramProject($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DiagramProject', $name, $tech)
!endprocedure
