@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element DiagramPredecessor
include('fontawesome-6/Solid/DiagramPredecessor')

' renders the element
DiagramPredecessor('DiagramPredecessor', 'Diagram Predecessor', 'an optional tech label', 'an optional description')
@enduml