' definition of the Item fontawesome-6/Solid/DiceOne

sprite $DiceOneXs [8x10/16z] Ou01ViA0WGWv

sprite $DiceOneSm [10x12/16z] Oq00Vh804Tfu48gv-I207G

sprite $DiceOneMd [14x16/16z] Oq05h7nmmCl8naz5m8J2OQ2cqOmeF0O6HWHW

sprite $DiceOneLg [17x20/16z] Oy04RCY0bO617nNmyl3J4p2me5cFuI0EcZg87SD1lAXyLem01

!procedure DiceOne($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DiceOne', $name, $tech)
!endprocedure
