' definition of the Item fontawesome-6/Solid/Dice

sprite $DiceXs [12x10/16z] HSR50SDG5C0mjs5wtd_Qm4UT110qQYzQctmzdCG8Gz7ahqBgP3hY6fAE-w4gIReF

sprite $DiceSm [15x12/16z] NOs50S1020DJzzx-qxwx0p7vzQjTGDUfwOchTat_8-gXelFdszmlLr84od96SkXPhyQFPOZBhGK

sprite $DiceMd [20x16/16z] RSu52WHH40FHx8vhtV-qOu7lmHzDqVhsErNk3zIqGqc7W9pm6XJmzxNOSFDuDfxiSc_JQm0YsIad4ZmKihZrHNPixeMkpPSwyvTUsWWMjZTi2dO3

sprite $DiceLg [25x20/16z] {
RP454iGm30ELs4Eb_Vzh3tNWYRVSbOCo-w6M4ourN01euO2CfWPW2639crf3eSsxPZoGTiW1p064uDGxiCCKC6HhWIugIZ-hGGCiYf4miid0-HnlOJFalDU0
ieZ13zau_wDir2fCB-h0hpi
}

!procedure Dice($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Dice', $name, $tech, $desc)
!endprocedure
