' definition of the Item fontawesome-6/Solid/DownLeftAndUpRightToCenter

sprite $DownLeftAndUpRightToCenterXs [10x10/16z] Ou01RWZ5nS3F3sO0QNvUE8i1pc9cG00k51ae0yRY1cg7A0O

sprite $DownLeftAndUpRightToCenterSm [12x12/16z] Oq00PYZDmi38pmzbytFn8zWW9eBDoO0f3ZC1MGZ914QmEC84A9iPIJy

sprite $DownLeftAndUpRightToCenterMd [16x16/16z] NSr75W0X309GihFd_gUTFlA0bTyqI9OoC_ckIF6JK0V43UgivadROhgQOLxg6-qsgu7AGpV1d

sprite $DownLeftAndUpRightToCenterLg [20x20/16z] RT1L0i0m20DGvglc_gUTImhahwy6YCwS32q0OuqN0MH0k2YntIbYB8arSImuXe5jJMSY4wSwxqIlXk3OmiQ4P8bjljU1BJsJEAidDCFU0G

!procedure DownLeftAndUpRightToCenter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DownLeftAndUpRightToCenter', $name, $tech, $desc)
!endprocedure
