' definition of the Item fontawesome-6/Solid/Dumbbell

sprite $DumbbellXs [12x10/16z] Oq05FFmC34pyJ40MFpylcCtCpu-BpGTY0m4-DGoSR50s9nlGL6v-8072

sprite $DumbbellSm [15x12/16z] VOhL0K0n20DJuAjs-s_xtEKg4D4J6Bz2rOZvA4rgDBa4libAVvMHqYBxB6T6oQty8mjD8vlKGkdZvpt6Vm

sprite $DumbbellMd [20x16/16z] ZKt50GH134ekzng1_gjTOzQL3n74xX20gAwtIlv48Kt9szkmQjZSoZ1-lb4t3A1k5Re9kj7QxU_kYnSNUNZlpQIRHTZcDguJIhk96jotr0C

sprite $DumbbellLg [25x20/16z] hT250OGm40J0ZVjT_zN-u-wmQ39ndCHQsto5jHgJ66QMg5AgdpDGrQ-OWs_KLMyrX_mnQEwWImz4Ey18FSHGXNgmNoxNhY4rW10yvY12C6V7BhjoDyfX_W

!procedure Dumbbell($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Dumbbell', $name, $tech)
!endprocedure
