' definition of the Item fontawesome-6/Solid/Dumbbell

sprite $DumbbellXs [12x10/16z] Oy09cFd153y8ymD928tCvWEneHYN6YHpK

sprite $DumbbellSm [15x12/16z] Oo04-FcXD1-GOEU6S_cv6O44WWkK1tCPWG3CvGDp4GIcOWINbu612S5bGh6N1yD9

sprite $DumbbellMd [20x16/16z] bOz50W0X30D3ze8s_t_jkZk33TwYWf1MpSqiqh9aiwPqM4i9AD9XJRfVqpWK6vZMYarhcWRR3N0ZquItx-MRDP27DRfJ7ddIdtG

sprite $DumbbellLg [25x20/16z] hP035W0n44DJktF_qwvjz3yKmmI58VBBHrpSyp90_SM7k0s4O03HNBQ1XWy1IKE0UinmoVaaG0X3mBeECGJaXwtuMG2Cyss0yrEl1a8ISy0dXK_K

!procedure Dumbbell($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Dumbbell', $name, $tech, $desc)
!endprocedure
