' definition of the Item fontawesome-6/Solid/EarListen

sprite $EarListenXs [10x10/16z] DSU50G0X4CJ0l2ka_sfnvdJfDgRB0x20slyJTzltX4tB3miytWos4PIvW2Uu72rb

sprite $EarListenSm [12x12/16z] FSU50S0m30D1DSpQVzig-06VSUjuVUGUwWEvwBqM9ulhGjRym40qg09KHxp6Tj4mZ1A9_T_XwAHED0mEg1y

sprite $EarListenMd [16x16/16z] {
LSk5eSCm303HCuPStVxJVcZu6KNSqeUNJJExFhRoJV1lzYkp6dkurXQQK43pedKp2A6xBWv56S9cSO2h5XB_flHt20jFoYvj04s_mSfgXkpUFWmI42vyQJod
1veP-k5Vc4XxqzSl
}

sprite $EarListenLg [20x20/16z] {
PP3LWKKX30NFnIrC_zMkG5RV_CHLVuYc5u2gVrGWkrusm90Uu3ckZIC9XhjsYNcTd0cI2YnrjjAdak6axLiT9oXuXzenHGYGvBuRCmHDSfvFDVRZ-qU0e7yC
-DRRtJF2lAqmzQC_W0uPJC4Va7G1x2W6kZnQKAGmlnVfcE1H1lWURzwM8UST
}

!procedure EarListen($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EarListen', $name, $tech)
!endprocedure
