' definition of the Item fontawesome-6/Solid/EarthAfrica

sprite $EarthAfricaXs [10x10/16z] BKg30S1044lTP_QVzkm8LeqllCWBFvi31dyS1M5BxGxUC_scjkncoey7a-4fe

sprite $EarthAfricaSm [12x12/16z] FOk50S0W4CHIzsR_QN78knoPnvEAVkUlfQtbjRHo2_zN-lTt0Hzr0kxR0arsgblhQPTvz1Fg0JP-W4_hDW8

sprite $EarthAfricaMd [16x16/16z] JSt50SGm44FH7p23-gzsGS5tiOUnCDGMBaEoX4awq-CCXUtgPpEfrWf12xejC1NyZLYgSdjmzEwy4-qvxDMB6sO7kYz9ThPFecmXd-aXw_VTBdDeYsm2V04

sprite $EarthAfricaLg [20x20/16z] {
JT053WKX303HMVUT-v_sIsb8Num0LTBnUgyKY-aPIEex0Rjwz2jFmfWd_rwIBh3atNMkaK312ZZSiJc6xJw65dqO9i9C98ghcyRYf5xUhN_IexeQrd8bjGyo
w2btOnn61jC0fV6qzIiuhSQoqaIt6vxswGi
}

!procedure EarthAfrica($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EarthAfrica', $name, $tech, $desc)
!endprocedure
