' definition of the Item fontawesome-6/Solid/EarthAsia

sprite $EarthAsiaXs [10x10/16z] BOlL0K0n20F3S-tjlssn-u6Od9j30IowkFrvKx4BVxPuRyj6a8lW23yg2EoBW8vIx5sV

sprite $EarthAsiaSm [12x12/16z] BSY54SCm00J1Crju_NUR_5Wxy40qNpuwojHKRs1JLosUEf2OggqJ6c_ULMtk0pj5rCso0UcnWm-uJFv6MjuV

sprite $EarthAsiaMd [16x16/16z] DSw53KLH2C3GFbTkzv_s2uGJnI5juJFHmdBmD-a9y6W0A4drXP2_IqATiQSc_pOfbf1qslYpFKwh6w8FCPmik06tg4BzX8FT4i0h49PtX3kPRJjfDWs0Bm

sprite $EarthAsiaLg [20x20/16z] {
JT3LeKGX34NHSmKdi_klzacmMLzeJ5FvqAE-92PxD05sIyf0aOCkTmFKSTGqu8AKrgj27wSIQ7YPkR8mJSPKk3InVFRNph4o71tf8Uic0kqs8EAkqbQX801I
fJuZsut9_9dwV2KZw6QR8vePfz3phAFoxP4B7DeopeBlVW4
}

!procedure EarthAsia($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EarthAsia', $name, $tech)
!endprocedure
