' definition of the Item fontawesome-6/Solid/EnvelopesBulk

sprite $EnvelopesBulkXs [12x10/16z] PSQt0S0m3C0mflVm_sjTfD6O08U1phICPmzv4x_gVxaiOfXLULVTxho2JjTrpHZeAW

sprite $EnvelopesBulkSm [15x12/16z] TSc53SL00CDGVyR6-qzRYEx4jIXF0HpHRfFB2PVxqMqIHw-T2Sc165wsYouOOdil_RazUpu7_Q7uB_-eS0oQRN83

sprite $EnvelopesBulkMd [20x16/16z] {
XO-50SD030EbC7l_RTitbdl9ara0ACa5vv2Y-s3h_zYMmK3PLXx9xZPUKh3DGhQbze57wrspQOzcEwld_NfTEkFcfi7TBOw3tZ3sPPCH8Xjs2HjRmevUwniT
hCWPkbxLTc6w0G
}

sprite $EnvelopesBulkLg [25x20/16z] {
jOz55e1004APjEN-fxMcQ-dVKWyyAEPOH5Zodp3fG2a0DYSJJXO4uHmCUSJkMp_XOCGW4ompFjTarrV8LssA0m8JFHAvC9t-uG71Gk0fiPCJ9fR2rstT5kR5
8Pp0JUhcrZJwgmV23G
}

!procedure EnvelopesBulk($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EnvelopesBulk', $name, $tech)
!endprocedure
