' definition of the Item fontawesome-6/Solid/Expand

sprite $ExpandXs [8x10/16z] Ou02Ndv-1WOcVdv-BZ0NJZFW071rF6n0YesVZPyVp0K

sprite $ExpandSm [10x12/16z] VOor0K0X50DJVONS_jFYqd7FLOiRA85AU4iM0g0EjsUc8ruNx6nzblsLBDeP

sprite $ExpandMd [14x16/16z] dSw52G1140F09F38Ql_LlZj-WvoiugkgOh_aUkdDzl3UJI8sKguluH9TpTSBe_ovqhyJ_g-CFPcnFkgp9puM

sprite $ExpandLg [17x20/16z] jS-r0K1120FGSp-o_xJVtVKrGAh0LcH5JDQCMfCaZ5ZDTaTc4rS2dkKqy97zmSFVBGQGCLqtOomwlBvZivhnVJUkKoK

!procedure Expand($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Expand', $name, $tech, $desc)
!endprocedure
