' definition of the Item fontawesome-6/Solid/Expand

sprite $ExpandXs [8x10/16z] Ou02Ndv-1WOMVdv-BZ0NJZFW071rF6n0YesV3QIVaPyV

sprite $ExpandSm [10x12/16z] Ou03Tdv-VY353m8yN40M3mz810BusVbWB0QyW0-kWn_1WflCoCS7CfcNZmy

sprite $ExpandMd [14x16/16z] ZSut0e0m34DHERtd_hT5CPs9D-bFDjx660qadMCkXbMd2fP1rdQMnQdDCULHCBXm_oRrkTyNljLRNLCQOxp-X118nmO

sprite $ExpandLg [17x20/16z] jS-r0K1120DGplso_xJVtVKrG2f2AxgYnbKcr6HzHunO7PZkI3HYLmAU14suG7zmy3HnxTEijUZh6tIQ9A2cn_eMDLeg0G

!procedure Expand($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Expand', $name, $tech)
!endprocedure
