' definition of the Item fontawesome-6/Solid/EyeLowVision

sprite $EyeLowVisionXs [12x10/16z] JOU50O0m0CE2E_d_McHURqy3EovrZYSXd5i6mXbby1OTwH0KbUN07HS5DEeYdZKe89Ol

sprite $EyeLowVisionSm [15x12/16z] LSZ5WOHG042nZE0VNl_LhckEkVklZNjryQ4Flp4AKmMdPmzH9uhEKh4RKQc6U-xjzbIueikjcg3kFYuVHiFwTH-c0PPU0G

sprite $EyeLowVisionMd [20x16/16z] {
POo7YKH13CNqSvnH_zqUvjrc0SxMUF33RgUOxtO-XvD2CsmGV0V2RUhbVRWgd1Dez3fN66uRfxfaU8459Dxbiy9hXaF9gV2SNQvFQK6XDxIITlKWGuMzmb4X
T1qPTKW8a-vW9-OVcdy
}

sprite $EyeLowVisionLg [25x20/16z] {
RP070eCm30ETlQF__xQnKJVN0agyxQVSCm57wKCmIGOGpwU0l6qPw1vlFdBZXwz2T4m_bWPaBSzmMj158Z3qqai0L1ySWCipcFheRGDU-rOIloB1MV7AKVAf
nofwbosjrtIom289-oh1zxkjPRMMhQP2KQLSgWDD-sOYMdWtcUu5tYMiU_Uv4yuIh50LObEKy_QgFR3adeq7
}

!procedure EyeLowVision($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EyeLowVision', $name, $tech, $desc)
!endprocedure
