' definition of the Item fontawesome-6/Solid/FaceGrin

sprite $FaceGrinXs [10x10/16z] HS650O0m0C2muax_lnRcIm0ELoAD3h1Oi3gKImRjLbypb4Wv551WCO8V

sprite $FaceGrinSm [12x12/16z] LOb50a0X24JP_8wv_sbL6fu24yGyE4c1ej8e4X_hSyszvk4IUDSqJXU_zAI8_aqUlF3kdqNhGj89

sprite $FaceGrinMd [16x16/16z] RSy30W0X50JGMIFC_K-RNI-xZ-1I51ionUX1m4B7OINZvce3UvUl05zjT5GOtxwwk23OsqY1KoWbtnqaGqaE_wFRLrwuF_t-TYCPMaSok_F66eq5

sprite $FaceGrinLg [20x20/16z] {
TP055iCm242XRkJV_xGJP9QttyPma6HlN8jyC9EObeWFzbu4Ho-2kM9z8aB75h95FPHQv4dpqtTNqK8p0TZ0Novw5g2bei9BzQEgsO69US9Y0mPFtqgq41OU
OdMHKKu7JiCPVaRQXGOiZEu
}

!procedure FaceGrin($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceGrin', $name, $tech, $desc)
!endprocedure
