' definition of the Item fontawesome-6/Solid/FaceGrinTears

sprite $FaceGrinTearsXs [12x10/16z] FSY54S0m0810wbxsdpQU_746sUb6zPejTLO0UfeJ9hqcB_p0sUhn5wjPK39FO5B6cSo02

sprite $FaceGrinTearsSm [15x12/16z] BSq75KGn3C0m_zbTyqTx8oyY8CBZEY0DmqLOfXVWKXE02igX7JXrRn-R_GAzJ3XrTjEXJAm4zpc079lozwgzgmVXC01y0G

sprite $FaceGrinTearsMd [20x16/16z] {
JT25aG0X00J1FTmd_sXViA9n5ss-Kp-z1alGyN4DRJoQfiRBtMcoW0p0F76sb3561T1Ko91NPjPkrS8by1r2Xai38cWqXTfxArR40FfaGSkipXqZeCa0dwOE
PCdKzyMTm-iol3_m2m
}

sprite $FaceGrinTearsLg [25x20/16z] {
NT230SH000J0ZNcP_gjzVpHd8xjkjKrLRkhLpvYptaaEeuiwFxMR_BYRyZ70zYsgvhIa_AepLT90dpSRGssgY1AKEL-3WXKKzgjsZOkWdd5_HmesP3NvAwks
GUX3Nkgwhf9qbXHBNZRcxD3agvm_TJiDv7XjntbvxMp9oMOtvg9Tzu_zUW8
}

!procedure FaceGrinTears($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceGrinTears', $name, $tech)
!endprocedure
