' definition of the Item fontawesome-6/Solid/FaceSadTear

sprite $FaceSadTearXs [10x10/16z] JSd50O100C2muaxtdnOvppS0cpC_WmrC9imsvPJUngmO4BRVbStP7p3vWnS

sprite $FaceSadTearSm [12x12/16z] LOo30S1G30LVxTx-qtuh5rEHXrCPCZqD32bVpCzWTx0d3aCGbZDPHkb-qTDosE3eJty5lfZ5hWS

sprite $FaceSadTearMd [16x16/16z] ROy50a8n34Cpz-N-juLqEFzDwosCj3WSdYmUYacEBxPaVZ2FyniFVfDqMGvuVPV9HLVc1SCAlsL5PYo6UcJe01m9pJhAaltRf8Oc7sJSCUajolizpGq

sprite $FaceSadTearLg [20x20/16z] {
TSy53eH040J01jQj___RoqWkQA5h8t1rSIISPBfvmF6a-jH5iwchQB6k03uKcuk7nj-dvV7jGzyxnRBjITuZyjFm26Ts28qdaDS6S02UTaA-iBoxRO_ORSvx
fOsgH5sdQABnx80wbug_GZKZn0y
}

!procedure FaceSadTear($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceSadTear', $name, $tech)
!endprocedure
