' definition of the Item fontawesome-6/Solid/FaceGrinSquintTears

sprite $FaceGrinSquintTearsXs [10x10/16z] BKg55G0X5CBhaCV-q_exANYzkW3vT2Mu9PQKzmr4QOG5fdfbT3Zg74AWjW8-9Hi

sprite $FaceGrinSquintTearsSm [12x12/16z] DOm50W0W30AnM_x_MdCxOmcuD6R0z9FnSS9Fvyq7j6bDaHps_8q2vjrzadxD_lPfp1jf-QtFvuYN9aEUs-PTwno5bmHi

sprite $FaceGrinSquintTearsMd [16x16/16z] {
DOi92iH02C3IkynQy__VBWfcpa2akJv_6v1NsQSDeO03wkWA9TV4ykhElZ4jdAhN-9D6QkK3HpyBKDtPzAVnygWlxBfrcAs4TdbMt5DPps7GgjKavh7jeTwa
hjsYbLlPR7hs3m
}

sprite $FaceGrinSquintTearsLg [20x20/16z] {
LOq92WGn40BDdS3s-F_VBawSIwwcb6euw-2lwnXCK1gTG2Kfn2Vd_K9X5WyQMIpwsmMnZ3GyioLHcJTRG5e--Nx1hEdngOxRDG24dM8_Cd9odJVhLFR7XCts
84slv0YBT2d97L1yR0LGDJ6BZOR-g7PKdirua0q1JF_PrZy
}

!procedure FaceGrinSquintTears($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceGrinSquintTears', $name, $tech, $desc)
!endprocedure
