' definition of the Item fontawesome-6/Solid/Faucet

sprite $FaucetXs [10x10/16z] Oy0A-7dvEVZvGIns86PYXOf2AGW0Ck206yu2AOV88Km3

sprite $FaucetSm [12x12/16z] VSY54K0X3C3GV1Ti_scnoZaFQQwi5DWan8QuS9ijYtebbRHYtwy-qZvwk3Tuj5K3

sprite $FaucetMd [16x16/16z] ZSvL0e10409Gm4xkVrfpyqlVTixW5ox8be6RgN4EIqSCbv77O3EovydUXxcpCIop0QvrkskGr3qpwLdVk7i9cU732G

sprite $FaucetLg [20x20/16z] hS65OSD04031_HF3QVklDZ4pspFyW79gqHoqJvKTJnIsgYxOYAxXL2QNYd8XNLdOyqpFYfT6y1fUQoQlKIAYSQEBoZKsmfK6c5tXN6Jcn8l-0G

!procedure Faucet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Faucet', $name, $tech, $desc)
!endprocedure
