' definition of the Item fontawesome-6/Solid/FileExcel

sprite $FileExcelXs [7x10/16z] JOM50S0m0CBOwih_rzODIK1I0xcBuD2CrjoHIGu3ZxHg2Xof

sprite $FileExcelSm [9x12/16z] ROh50O0030CFTsx_QR7qIJN6hfu3t_VS9mnm2cZQrh_2BT4PJD7azt1Kva17gsu

sprite $FileExcelMd [12x16/16z] VSor0GGn44DHcTc__seF3Tc-Q52AV9aWhHBJayIkIRerQTNEM6jP-WSFLBc1gceiak7MaSKhQAnQuVv-PnCGrni

sprite $FileExcelLg [15x20/16z] XSsr0GD130NHEMPD_ztwS5UPNoRyjE6DWLFhYtq2efREO2hFEfTdNSkcFLcC5__RrIYHGQivaxLXAcLmifeWKWaijUffuKYdRkcusRNhFMsQ4RbQVW

!procedure FileExcel($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileExcel', $name, $tech, $desc)
!endprocedure
