' definition of the Item fontawesome-6/Solid/FileCircleMinus

sprite $FileCircleMinusXs [11x10/16z] FSd50O1G0CFGVjpV_jFYq5EJP6ChkRPXSt_tzLrTrtsN_3VeGErV_Bq2CoXm

sprite $FileCircleMinusSm [13x12/16z] JOo50S0W30I_xhtzfwq04JIlEe5UTPtyW0geW01Zt_SLj9M14f0_C92MkC_p370S1lhwpRdW1G

sprite $FileCircleMinusMd [17x16/16z] PSd50G0X4CNGMS7bzryjxkJuGW8v6d6KQ10wu0BiyBxliuAtrkeLSYVGO-ot07da1dmAfSpxMU1DkHLC2YligGSbCGvzI4cA

sprite $FileCircleMinusLg [22x20/16z] {
RSy53WGX44JH6iEXxd_QzPsMz8-HX-DOVBUmGTh9drBn4bLCKM6hz4hixxoEz4vK5-b2e2UkIVRDQ88CrFR1NuVe0GQXXNe_pEWWHtyrjUuxWphaZLqOc_nx
ASRdo0my0G
}

!procedure FileCircleMinus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileCircleMinus', $name, $tech, $desc)
!endprocedure
