' definition of the Item fontawesome-6/Solid/FileCsv

sprite $FileCsvXs [7x10/16z] DOQ50G0X08JuJcN_QMqlGJqXrXFRTPqJ13mHuxBi0ilgqDSl0m

sprite $FileCsvSm [9x12/16z] HOQ30G1H5CFwxPVzfpsZZ2PWITTZiuWRA3U46FbbLq1a8Hi8lDTOQEQf8M0SnlYKNzW1

sprite $FileCsvMd [12x16/16z] TSR50GGm30In3TkXwR_QOmQzfCfPBDAjnDaaxgUzd7PxIZbdRkO9RrA4u944AraL2C7C47N_6dZ89jWALcBS6i2Qp0cBlyJJ4G

sprite $FileCsvLg [15x20/16z] {
XSV70SGW30NH8ODjzFllTWMRJnw2z8Yc7GKlwXLNSzgNwg0Vkd_f_Z9bJv_gIZSLC0jCR4Gd5clCQtOMTLqbJ6SBcrxYOiIscQkKqm0jmXdX4achQyfEaqnt
dV_4VZKU
}

!procedure FileCsv($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileCsv', $name, $tech)
!endprocedure
