' definition of the Item fontawesome-6/Solid/FileArrowDown

sprite $FileArrowDownXs [7x10/16z] O-3dvsTZ0990YXzAGG0Ra043x7mWae6T3wm2g1mD

sprite $FileArrowDownSm [9x12/16z] JOU50G0n48DugTl-qzQDan1I9Gf8NRnQajIGx__JpMwFxQ75O-a6FAapSX6M5

sprite $FileArrowDownMd [12x16/16z] RSV50SGm0CJ0DRFLVxM7uKIlaGRVR90MOdkIM4qwcBJOEUyzI_qJrvgUdCR7SVnib1HKM4PAi4vcgtCj7Vm6

sprite $FileArrowDownLg [15x20/16z] ZSx50G0X44FHu4xwhtRTbNzxw21o3WR09YAxWTn9VoRzcVGxbHxYbXtZOxuULI5V6IQcCgi00yCsai5Kvf8ULRXbfhszKDcGEgds

!procedure FileArrowDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileArrowDown', $name, $tech)
!endprocedure
