' definition of the Item fontawesome-6/Solid/FilePrescription

sprite $FilePrescriptionXs [7x10/16z] 9SMr0S000C2WB7NX_skhB8InOFI7xv7Q8K6Pa8Bj3su

sprite $FilePrescriptionSm [9x12/16z] HOh50G0n408vbmZzLnjRcmyA3ke5S9dycE4ZvZXF1W0sCPcmvj7c4bjcAVVtkj-PXGu

sprite $FilePrescriptionMd [12x16/16z] JSg54KGn30FHdU3dxR_Qmz0RiYLn-nKojDDmLR3VrkMsjZl6b9BDzQ664B8D7w7Vbx3aUxztU6gO6x9VfnQuRSXWS-kZrUaD

sprite $FilePrescriptionLg [15x20/16z] PS_50S0W5C3GrEr3zj-sxhaz74RtQ81B4jr2Rzg_kVZ9nJUhUichTisbb5Bsgc6fUB2gI_gROQQ-kHOlTjfVYmC6Y9CkldPFcf-VKwWXBlQjKVdhFPHd

!procedure FilePrescription($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FilePrescription', $name, $tech)
!endprocedure
