' definition of the Item fontawesome-6/Solid/Film

sprite $FilmXs [10x10/16z] FOc50O0m4CI2rTliFoqEBwVy4_o7fG3I3ILTwkxofUxMcvgQ_knML4CnX60Glpa

sprite $FilmSm [12x12/16z] NSp50S0024DHg4kQl_-qTNyNd7X9NYmcIKRG1CSys3oxfiZC5kyxXz-ETUI_Fs_XsxW

sprite $FilmMd [16x16/16z] TSs55O1030FG5DTc_srv2MuVEQdXQSghPkPJKR4fXDH7W06PjIMdQJzhQ_lP46IAjwwtVPl9DaJRPxtdx-VV-Jc9jotlyB

sprite $FilmLg [20x20/16z] ZO-54G0n20HltZNqNstSVQCueCQovk2WMO2L7XYKz6lTGbUcEuudwAH4bg0Bt9aEsCWHQgo9xfFtkZuoMFCeYLLhr7N0clJyLkPuxHnqQ2up1wCIbAeN5GG

!procedure Film($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Film', $name, $tech, $desc)
!endprocedure
