' definition of the Item fontawesome-6/Solid/FilterCircleDollar

sprite $FilterCircleDollarXs [11x10/16z] DOh50S1048I8U-Y_slFbDG8EVYu3Y3GH-OAHwSmbgJk0ktBQ8YN-BRBwWA6_cW4

sprite $FilterCircleDollarSm [13x12/16z] HOpL0S1G20Elxit-qpu7xWU986VdKm2nJyHr02nz_scytJ-e-mZ1f6BTaVfHbtzuc-lu1ADncw95XJa3

sprite $FilterCircleDollarMd [17x16/16z] LSp50SCm50JHCLiu_LSRZk3TFkpYg8ApayK9S3jO0OfDu6Eid3Q9lrrLbbmslh9ALRM5Zg3nQ3sAncNBEYmoPyiKKRsNLdAX0MxbRzDywSMuqPid

sprite $FilterCircleDollarLg [22x20/16z] {
ROy50e0W40HNfVF_lvMZQqm6hk3ZHW2677X0dzPT3uFOvGFYNIL7GSnIes7c-eCmMfqfKa2aZkpRx5jaRBiLIU4kcPUAi6fPFGf0fS-mi3Hiy76rTHc6JQhq
5pWcYy3IUGjWiVXewH-QNpNNkdQjsE3niPpy0G
}

!procedure FilterCircleDollar($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FilterCircleDollar', $name, $tech)
!endprocedure
