@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element FireBurner
include('fontawesome-6/Solid/FireBurner')

' renders the element
FireBurner('FireBurner', 'Fire Burner', 'an optional tech label', 'an optional description')
@enduml