' definition of the Item fontawesome-6/Solid/ForwardFast

sprite $ForwardFastXs [10x10/16z] Oy02-Fb112yG0m6O1BFucVZH05I66wQE1OX1UY4O3W

sprite $ForwardFastSm [12x12/16z] TSQ52S1G0CJGkxfd_srBlTy2FA926uVK1u1bwAwdCZ1TJtUmakI3XYCTNubZvGFH7-hXQmS

sprite $ForwardFastMd [16x16/16z] ZSwv5GD1409HTdUSEHhoZrP7Lm1IEV_XeHzT6mwi9FfaEFbsIOPATyjGeSVDgFoPeK8oi2svOH_-r8UAquSBJdIh0o1w0m

sprite $ForwardFastLg [20x20/16z] fOy55iGm24GfRLpc_gTTGnvFrwQI7npwGmrBOA4Au2L5yJ94XxfdiC5JWWsdsdQmWGFyhEcqIM6mEssMIcnEc-_o-PgjUVaUnVPzdGV0Az5BUR50x_IXxW

!procedure ForwardFast($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ForwardFast', $name, $tech)
!endprocedure
