' definition of the Item fontawesome-6/Solid/Genderless

sprite $GenderlessXs [7x10/16z] NS750G0X0C2mdYjq_stvu0aJTG5_DZa57lq0N0GKNHLGAH8

sprite $GenderlessSm [9x12/16z] RKa30a0X5Ditmkv_sknw6B4QIUdfe9yJe0eXFeQQBvDGLn8NGfI0gT-U3SrO

sprite $GenderlessMd [12x16/16z] ZSg53O1G5CNGYplTVrjIB8gSBq_ppmJGH1mMK_mBwCqZu-ocLW9befaCZFUEJmqueqf6tBLG7HKp37cn0G

sprite $GenderlessLg [15x20/16z] bOvL6W0X20PnsvpxttO_m7XsJFgNROuldjFuC9fRXO5QiR_5NwXYl73Bup6bWTHbVY0iKnFpClKRj843pHe4DRoBXgddaO1aWZ7SMZA3xF83

!procedure Genderless($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Genderless', $name, $tech, $desc)
!endprocedure
