' definition of the Item fontawesome-6/Solid/Globe

sprite $GlobeXs [10x10/16z] DOc30S1054DJks__RUyReNn-nM1pShbmlR7fkkpyJrZ8t1jNJfEhlg0hr8saZH-P6

sprite $GlobeSm [12x12/16z] JOo50S0W4CIkZcV_ROj3tbMLf0w2OAbfpgkLDBgMHsruECc4G6RbfkS-Wev3sOvgm9TDyAt_IPbu9vwKkpy

sprite $GlobeMd [16x16/16z] {
NSy5WiKm24NH1_KMSlU_sodCznFte8UXjno2kwngO07OHVOGgf068IMaA5MRp4ooqlMScRvdqLKru1V50fh7kxb-rkNkCY_gAY9sZrBTKolmVhyYUOoF2HRT
WgKt3LOrGx0hg_y7
}

sprite $GlobeLg [20x20/16z] {
RP3NbSKW50D5j8dglzkz2FRb-P1yncJy4oVUI7I1dAZ3uK0ID6xByb3Ea-TFFOfeSYvP963L0CMj1egHKSIbZd06BCNkcuOFt62id7BfttNL3wVmySrfH73_
RYf_e9qQAAhQmptdCE9CBQkA7EfMM1_PRQUP8ft9yAzxtb7FsVQWFm
}

!procedure Globe($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Globe', $name, $tech, $desc)
!endprocedure
