' definition of the Item fontawesome-6/Solid/GolfBallTee

sprite $GolfBallTeeXs [7x10/16z] DOU50S0W0CCoLyZ_r-BK2uGFU2rOiQ4TZIfDEYioeVwjJyW

sprite $GolfBallTeeSm [9x12/16z] DSQ50G0n2C30lFjd_sdhN0i4cF-NoYQk_sHKhA_6-YCEBIwzuQtAPQv1jUjAumza

sprite $GolfBallTeeMd [12x16/16z] HSY50S1020J1YnjX-w_sNGP7oMgyAXOAhsiZCNmBaxKVqu8xBvbZ0j4E-cuBS4WqfcIhb3sMrNqZSJNEeUvdpIC2

sprite $GolfBallTeeLg [15x20/16z] RSt50O1034JHmPtVVxN8khrJFFhr1_SYPyGwzPi9GY_afDQEp4xR30VS68js6635kwOBb1svTVffW35xV4cAdm-rdDOYo_qUf5YO5KsWLle2

!procedure GolfBallTee($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/GolfBallTee', $name, $tech)
!endprocedure
