' definition of the Item fontawesome-6/Solid/GreaterThan

sprite $GreaterThanXs [7x10/16z] Oq01tFpy40O_FpUCmGQc-K0Id21f5Y014cT2qWS

sprite $GreaterThanSm [9x12/16z] POY30G0n34NFgDx-qzPkyhqjf_boKjIeuS_HW4ZfW6p1psGxi8VvJTQT0m

sprite $GreaterThanMd [12x16/16z] VSs53G0X5C3GSmMw_xO4Ttxi5Lq6i_vhj0GPwm64GImvAHLY0vBOZNQZm-WmEetM8FElsOqFBDtH

sprite $GreaterThanLg [15x20/16z] dSl50S0W44JHk8VflrlSdNzxArDF5x0xVC5QhGzkubni6BomNhZDDU4w9MOusFxSPhO_F0UyvUTeZ08

!procedure GreaterThan($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/GreaterThan', $name, $tech)
!endprocedure
