' definition of the Item fontawesome-6/Solid/Hammer

sprite $HammerXs [11x10/16z] Om01JZu6AE070cuecn78PaCIXx9WR6P-VYu63X2J0o80n7nGPL0nE1DcF

sprite $HammerSm [13x12/16z] Om03RZu6663X1m4u5uN73E8m8alnyOAPVFm8XI1H4Ca1LGAYE65i441Zyo5RnyJFpmhd

sprite $HammerMd [17x16/16z] NOu54W0X24NjLkv_sargU1C_3738WkeK1rwI51EmiNTKqRxYg0O-FCLUiG7-D3bLR7IK3sQFVyZD63WdCwwRfJS66Q2n-GO

sprite $HammerLg [22x20/16z] {
RP054i0W30I3E_p_jLNic5oBxSHfAhJgw51kdv3NrfK0Yz9n9EGTMvOsD6QfNYdzPYcdTTk3IhBfW-M7QXRbbwbP5cLQ-ZtOE6E7t0W4mDw_1kYv2HBC3sqh
dIeSl04
}

!procedure Hammer($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Hammer', $name, $tech, $desc)
!endprocedure
