' definition of the Item fontawesome-6/Solid/HandHoldingDollar

sprite $HandHoldingDollarXs [11x10/16z] Om01HWOuuEU7iHY1B8GmiW8yW1yCe1G_9niRFpy7b0FI2

sprite $HandHoldingDollarSm [13x12/16z] Om035WOamC-Fn6PZn273mytFZ2J3nK0Gy8C10mCNFmCtYCN4n0WMGm0-93uR0mC

sprite $HandHoldingDollarMd [17x16/16z] bSp50S0W50FGu4xstxPkkVNXVC6fG738cwpVZoOLcV8LKAazj6l1BxLlpDQyR4yUEj18jCcDjHRWorQp7U1702PVi5e

sprite $HandHoldingDollarLg [22x20/16z] hSsr0O104031nPtjlrhS_qCcEZykoKX4PqR0HSD7OfUrX5L7GfNQ4g6n2yhNe19gv6-jX_78M7WxChhENPwcAUGkUYzDkUXSr1ZAmA_ZuLl5QWO

!procedure HandHoldingDollar($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandHoldingDollar', $name, $tech, $desc)
!endprocedure
