' definition of the Item fontawesome-6/Solid/HandshakeSimpleSlash

sprite $HandshakeSimpleSlashXs [12x10/16z] JSV50G810C2muaxsdnOvxolTjyds49xrrdiwRpheFbdHP8-8wicawewkMjlv0W

sprite $HandshakeSimpleSlashSm [15x12/16z] NOc54S1G38MeMtxOVzjUNOXohwxuuFHpEuTEhO5g86n7Dqf4ccmHwSQsmL9DjsxkmAtEBBev4U5s6wqYs71pJ4xCKY3bm-0A

sprite $HandshakeSimpleSlashMd [20x16/16z] {
PSz70eKW4C3G3DWToFrF-tlLjymkPULaiNDIDM3Og6sllEccZDwDt4H2AejFBNFl6ipUnUPJLqUAIl6dkOEs4hzD8NNchncCsaZLz6KYL3QLSjDL4xgTMWiF
pJjOVqztRVewVOiWkDE9a-OL
}

sprite $HandshakeSimpleSlashLg [25x20/16z] {
RSa5WWCX5C3G81tZCxd_QLUWtZwSvE2xqCnNJIjVBNfGcfsgUYHkaggTnMcPlv4XDDYywH6ndxh0hgVgeuvtWphk55-20dD_3rPeusXlmHrMTML_2mOKjL7V
WYPGdRlLXmiSQggZ3nU70wfsXfVI8Ua93ya9E3Npa5lK4Yl0fXjVPUrybKv_0G
}

!procedure HandshakeSimpleSlash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandshakeSimpleSlash', $name, $tech)
!endprocedure
