' definition of the Item fontawesome-6/Solid/HandSparkles

sprite $HandSparklesXs [12x10/16z] LOg50G0X30Fphd3xJulh8Mr42QCAwGIEj2_iSI7jc5-HQK_4dNtO8Nr3HTWcTCa3

sprite $HandSparklesSm [15x12/16z] LOtL0S1G20DJzzx-qrQU0VU5H9HPv42S2ta-9NhEAwqz77KbAyCwk3L38SzXlQ1SZjnKrgEO3oYAl8zfdOLU

sprite $HandSparklesMd [20x16/16z] {
TSy50i8m04FHhEwv_sr91OS_VxCMZpe-QcYyj3yvROD6riMxOL-jICmWwzEqdyX-FUsytWo-JFsnHyiYnvTbdSZQCQpMLOLP5EqBche8_M3boTbEjetvMDbJ
E6thGBrm0m
}

sprite $HandSparklesLg [25x20/16z] {
XSo53S103C10bxdUVzeoumaUh8I39kKk28aL8YwKHAcLZNC8nz0SGdWDjG4GrceL78CM09NZvI4G28-1ry1Fs6oXiNWEQlqoePNQXCwQy_vakyMKp6f7EOxQ
Y48MZQEvGwbjoAnqGw5QiyYsa4CZcsse0g8QUW
}

!procedure HandSparkles($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandSparkles', $name, $tech, $desc)
!endprocedure
