' definition of the Item fontawesome-6/Solid/HandHoldingHeart

sprite $HandHoldingHeartXs [11x10/16z] VSYr0S0m0CH0XJdQVzg0iVCr3m3IdmJ-zbgtUfCe3GOORVEiincy

sprite $HandHoldingHeartSm [13x12/16z] Om02HZu61du6AE070vmSNYHrG6q87WC1W32CYv-D2yHYOsK6Yo407nAVZO41

sprite $HandHoldingHeartMd [17x16/16z] bSp50SGm0C0mbp7n_jCU1f_L0E8d7X1E2ZMgWMGq8HbC88d-R1H-NT2tT9GdXltw6e3b07R_0bowdhTVoxA0ZVj3lR0pWwq1U0C

sprite $HandHoldingHeartLg [22x20/16z] hSwr0GH1049HJiQ5_gjT6vTmNyQFG29eWM_qw1bUD2-VhhAosngtrNHLregUwUAIlvZuxbR7yO-N6MOU5viEiibBMfk34a80WXV7oiZBioMu-cAj4LYhmkq4

!procedure HandHoldingHeart($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandHoldingHeart', $name, $tech)
!endprocedure
