' definition of the Item fontawesome-6/Solid/HeadSideCoughSlash

sprite $HeadSideCoughSlashXs [12x10/16z] JOd50O1G08MmM_QVrlZDvGKzdEv438pj03ZaKhs0MncoKA5sJvGPUgEvcMAVPrQ9NQ7p1G

sprite $HeadSideCoughSlashSm [15x12/16z] RKs50SD04EBTOVzfsxYVArW3CzInYpRvx4r2lxJKG3ZxlkHphQCFUwk69XLWR3tXb5p5vK-4hhpKlYKDWAG_

sprite $HeadSideCoughSlashMd [20x16/16z] {
JOu7ZWCn30FfRkEqdl-_zbeK8eCkiTKZbO2eCfjBqdnic2c3oKDvf21vNhU0eaLY8qCrRw_o0_3r3hsV3HcQvfnNDDBSyPIb0aCDoKjkaIv7MzstyMgywlX6
H4WDYhrkXUbRBqN_FFm
}

sprite $HeadSideCoughSlashLg [25x20/16z] {
NP450eGm40DJz-R_hxt36mZEhA_j04mbsJrKdGoyLPGqgfH41LE9KPBNNxidMf8K4IWBs0lixnNm3-WNcBV_DrRY8R_g3XTPlQLthBPYknMBbE3cAIK11a8Y
KFTxsD--zVWpIKm26dRPOs3l3cgCqG3pRfyg1o2J-GloFUyX8Cac9ly
}

!procedure HeadSideCoughSlash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HeadSideCoughSlash', $name, $tech)
!endprocedure
