' definition of the Item fontawesome-6/Solid/Headphones

sprite $HeadphonesXs [10x10/16z] Oq06_4300MOm0GbkVY038i743sQ1fNWvcS0CBf1gY10IYnV60khWWx8

sprite $HeadphonesSm [12x12/16z] NOh50GCn0CCKvdZ_QTjZqiiWFbH9SKj1tM2d02isd40S99ahep776LVC5jkMxPRxEuU7G-Zi3Fu

sprite $HeadphonesMd [16x16/16z] XOx50S1G5CAeAp_xJrjtpUafe4VIrdMqTIqp-TokHOldLWi9hMGECaIQZbS26ISVJ2YsrZKZg_FSGRpb-E_hIo_O70kmBlG

sprite $HeadphonesLg [20x20/16z] {
fS-50SCW54NHXpjt_sdhxaqExdnzO9opvcw6awop0jJWSWTEUmTO7JK8ntRgmXrsMj3LSJYvVwuH1Bh7J0JTWq71wgfEZdJtrQFhnhvsRhoO4u2vHW5CUPYw
0lJA5W
}

!procedure Headphones($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Headphones', $name, $tech, $desc)
!endprocedure
