' definition of the Item fontawesome-6/Solid/HillRockslide

sprite $HillRockslideXs [11x10/16z] Oq01_0nC_An0ceyVnE57a9nWMI20AOImeGgWAc40meIBCoFO

sprite $HillRockslideSm [13x12/16z] NOo50O0m30GVTsx_QN4QgUPLQMsh6jPxQb3J2BZ1-qq5K09un8Ss2hYd5YXeCB1BsrBGzZPOx0G

sprite $HillRockslideMd [17x16/16z] RSu50e0m241HiFlV_xJgkdjl0T8hqoQYpvq0J6UncuFR8qzOMBb10t2PXQf4uB3B3DZigmnOpVB8W2a_jcKm6P8NJP1aep2VUYqrV

sprite $HillRockslideLg [22x20/16z] {
VSo50SCm30NH7pRV_jCMmbBXWdu6_MbONyDWi1Ab7fYqbryG62K0TcnGrX-Z07dz6u7bfZl767LNacmOThgVsAfLrZF1AREagPSIJ80z9EAQlYhpLsMKDDDw
FAyrnyEg0owj9OjrnIS
}

!procedure HillRockslide($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HillRockslide', $name, $tech, $desc)
!endprocedure
