' definition of the Item fontawesome-6/Solid/Hourglass

sprite $HourglassXs [7x10/16z] O-070qO8nS3FmC30pC_03U8mCu0aUO0YG1f2WcWmPeFguuHG

sprite $HourglassSm [9x12/16z] HOo50O103CGETxB_jF1IILs5iME8HmLktLm5Hiac1OyQB8uvSIj7DxD_VXwC7m

sprite $HourglassMd [12x16/16z] HSm55e0W54JHiPLw-z-jPyXByqDCfR2eS1-ME1HuP8LD6qG3Vz3SZe85oLXNbx2kux4xeJzyzHwbi_LF3YI6JKofiFm

sprite $HourglassLg [15x20/16z] LSx50SKW44NH5mzw-w_so-1d1UDYvZEBZLdI3IeUa4xOP98b80S3GT9BLRiYrIMJCOUgM7FL1kJb1t7wdQddIr-4K7zdFMehfU4l0jB5H7gMhsFXMNm1

!procedure Hourglass($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Hourglass', $name, $tech)
!endprocedure
