' definition of the Item fontawesome-6/Solid/Hourglass

sprite $HourglassXs [7x10/16z] 9OY50S0W30IlYiF-qyRppecxqZZ0SnYnWUa4zrJtuC-9QsaA

sprite $HourglassSm [9x12/16z] HOo30S0m50MlRlZsdpR6VHCD_fcWG44UBrVG0MDIc156FFPaMZdokkVd43J8

sprite $HourglassMd [12x16/16z] HSp50S0m30J12yUu_LThXlc89POOsHHvpifpodAhYaW7k0fQetjLq5WrE-s5keDgfdPE-YuuwUx_FKYUIMBnaIq3

sprite $HourglassLg [15x20/16z] LOxL0GKW30DnX-m_xPC6lQzUNU6c33penxgoW2BX7vbV1xLB0HXL0EfF4nQSQiiSXmRDqbXdZVniRE4hxQgvpZhDotnTjVcKfifJJVwmM8ZwHpCUogjV

!procedure Hourglass($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Hourglass', $name, $tech, $desc)
!endprocedure
