' definition of the Item fontawesome-6/Solid/HouseFire

sprite $HouseFireXs [12x10/16z] Om013WOuuEVdHp3X77umG6Q2C1-42I7153C_8upDm0rI3sKp8h71sjW1

sprite $HouseFireSm [15x12/16z] JSV50OH000ImmPtqN-q9klabfoc5bltT3EvjG7qEaBqgLc-iijy5Um8g9ZYxXcHRdStHpEuksbJSpGxv0W

sprite $HouseFireMd [20x16/16z] NSZLOGD10CHG7SE2-gysiRrmyBvcH9DvczHNslmQk0aMCrsoscbi5lPtsj63T4-vpaIs8LgCj9bGo-vjtdL4Sszv92Ymq1kmAr_tXavyxxtjcbFPHslCblaF

sprite $HouseFireLg [25x20/16z] {
PSy53e0m44JHZpjp_zkIhMI0laXr3LEFsIXfeJKhxFnjoWw-BbLtUv-T7IOx6AawsScc2_hIfh55cLa7J99rVTtDt9y2tiEwgcA9CggZueTQ9k27BNOzNEBz
CEOTGFTvm0yq3rSEf9UkpqDijwwBFhllmw1YeZxSP366hWuU
}

!procedure HouseFire($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HouseFire', $name, $tech, $desc)
!endprocedure
