' definition of the Item fontawesome-6/Solid/HouseFloodWater

sprite $HouseFloodWaterXs [11x10/16z] NSP50S1000InANFNlzfZpYjuAvca9y-B6q_iySR-S4qWVXKm4QpSAYm

sprite $HouseFloodWaterSm [13x12/16z] HOo50GCn3CGkpD7-qxRFbXbrKMG0tVAJAqrWrUOXsHRvFKaThe_drEjo0Oour5WkR893ZY0nf8us67y

sprite $HouseFloodWaterMd [17x16/16z] NSw50G0X30F0u4xsd_OLFrnRD4bXGp9Z4loCjMSZyAaSV7i_OT-9E3R2ig7Ss1X46xw_7Qc0mep4WwP692D4PjK815J48seyKikp53vARTrJMyT4tW

sprite $HouseFloodWaterLg [22x20/16z] {
ZS-5eKCn241HY2jt_sc_KFUUfp54pfB9em5akOERDtEH8vEBnTab2ZU6kCajzLdTNB5pHkCYoHUpDQpRMGdT2z9MBplDFnrF7gZ7_jdToxCn_9EDPn9JfHis
LFA25INP5X5LSUdgenDMq320ebg0wiaU3UWD_mlcvSGDlm
}

!procedure HouseFloodWater($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HouseFloodWater', $name, $tech, $desc)
!endprocedure
