' definition of the Item fontawesome-6/Solid/HouseSignal

sprite $HouseSignalXs [11x10/16z] DKm50G0n4E9TD_gdFNS547QXxIDh6cJDJAifwlfvo_IIW8TuVpJM_7cUqqxtMg8A

sprite $HouseSignalSm [13x12/16z] FOc55S1038L-tSl-qvv5E0cyo5Wc9JkiuIUDtVo2h0VdQj6d_VFNqqAwtKP8AxejJff-YisDaF5rZQW

sprite $HouseSignalMd [17x16/16z] NOf50S100CEoOwv_jMFEfyZ5rFamIOCNHleqLWTFllXdZIT3k3_vDDem8m9tuVQrWpI6zcB5I_jw5BOOK2TVHTAQx7sP0AEC6jC6AvKYchWOOXBnAHO

sprite $HouseSignalLg [22x20/16z] {
PS-50O0W54NHJpTl_ssLhciV2sZBH7fpG7eme7HX15vE6DruCrQBCsefzHEnFNcT4ekNSeJolDWqzs6w_t702w6x_ldw7CSehycMcqiT88j4eaqjK2IZRAtG
v-288n1tDJtdMxTL_Q85VpIGWA1uw0S
}

!procedure HouseSignal($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HouseSignal', $name, $tech, $desc)
!endprocedure
