' definition of the Item fontawesome-6/Solid/IdCard

sprite $IdCardXs [11x10/16z] Oq02_720BeYGO0PYi20NY8JAC_0YQMI7Cjc002A6q0u

sprite $IdCardSm [13x12/16z] NSt50S0m30D0kToGzfyspFSo6mjEj9de6JV0IpuYKXB4fDuwOTd5C-HLngPlPZcbNVS6

sprite $IdCardMd [17x16/16z] RSx50K0X30FGVDUI_QV57Tu5gM9mgfhWP6VjVJtE2Fm_h9_nHajPJ1zVp91v1YLlu6-Rkv7yBLeBF6RoUup03de6

sprite $IdCardLg [22x20/16z] ZS_50S0W50FGrBtPVzeAxl1ky1qPGwG7c72TJ47IaSG6z_MXCWA3-8H0uSBdOc37PpCRZSvwijNmsVGGso35cRP2MD97qpChj1Qc98TFI7e1

!procedure IdCard($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/IdCard', $name, $tech, $desc)
!endprocedure
