@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element IndianRupeeSign
include('fontawesome-6/Solid/IndianRupeeSign')

' renders the element
IndianRupeeSign('IndianRupeeSign', 'Indian Rupee Sign', 'an optional tech label')
@enduml