' definition of the Item fontawesome-6/Solid/Info

sprite $InfoXs [3x10/16z] Om02Vcu6VauWpSdFoC3334TS_Fm

sprite $InfoSm [4x12/16z] Om01Hdu61Xv-HWO6PZ2NbvyVI69YFdv-VW

sprite $InfoMd [6x16/16z] Ou02PbuGoS_F3oPvm48CCC3B2nJW0qg2X7W8aeoy_FoyF4022

sprite $InfoLg [7x20/16z] bOl50S0m3CJAt6Z_RMF-HsQugJXMpHziKe1BoWEBRlMKp8kkRW1zq29iWsKvO56v4gK3

!procedure Info($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Info', $name, $tech)
!endprocedure
