' definition of the Item fontawesome-6/Solid/JarWheat

sprite $JarWheatXs [6x10/16z] 9SQr0S000C2WB7NX_skhJ7HY2hRyLWigplHzVB-7jTF6mGq

sprite $JarWheatSm [7x12/16z] BOk30G1H3CLonjV-qzQfyVYMiRESd_qmk5V1Zb_QjiNKBfysug6lsNq9SVmjIgS

sprite $JarWheatMd [9x16/16z] NSo50GCX44JHmPtVVxN9kJsS5JasqcGJ9BUoKkghvY8Nvtfo6KXQi9fpdXsomYj4xzlXVI-Vgc4Rkx0LS_W3

sprite $JarWheatLg [12x20/16z] RSk53S0m44FHN-Pu_sshC3x1eS78E-1G1CJseV8eMdPLhblwhYlcPrXatLXg6RYqCCd2sHG7zj4_B-5_mhhat3kxKOIiHzONDz7z0m

!procedure JarWheat($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/JarWheat', $name, $tech)
!endprocedure
