' definition of the Item fontawesome-6/Solid/L

sprite $LXs [6x10/16z] Ou00Vk99DY1Wu0S1

sprite $LSm [7x12/16z] Ou02VYO8nKOc1GOCd7mW

sprite $LMd [9x16/16z] Ou03PaueWv-V3WmU4E1cuEC70P0u8mG

sprite $LLg [12x20/16z] Oq01R8nm9Zi_FvpDCRZPR13016J30GCJ4Xi9

!procedure L($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/L', $name, $tech)
!endprocedure
