@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element LandMineOn
include('fontawesome-6/Solid/LandMineOn')

' renders the element
LandMineOn('LandMineOn', 'Land Mine On', 'an optional tech label', 'an optional description')
@enduml