' definition of the Item fontawesome-6/Solid/Lightbulb

sprite $LightbulbXs [7x10/16z] JSM50SC040B0Q-FA_jF6xHyuJ0EgR4SSfZt9bqC7BSgwXb_22W

sprite $LightbulbSm [9x12/16z] LSY54O104C30e2D8-gyMtcLVBdC4xqrazCIP-iJZCK8iuHmdfO2bp501KTkyUi0F

sprite $LightbulbMd [12x16/16z] HSt50K0n20FGV5UQ_QUjOU-4W-7d0yNfj_3ODFafE8NT0XB2gOnOmnb8nk754J40cZD_5GpdZA6MmU9_i9YTM7pRU0C

sprite $LightbulbLg [15x20/16z] LSc53GH1581GrltJVxKdOvbzKGB9QMmKGvYSkQm2G5tWB7_NYSSCmgUL2xfXTQB7rlB2tivbPm0xmF4gY5eRYLcGNIPKGqAr9bGcxxoe9lNXxmi

!procedure Lightbulb($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Lightbulb', $name, $tech, $desc)
!endprocedure
