' definition of the Item fontawesome-6/Solid/ListCheck

sprite $ListCheckXs [10x10/16z] Oq02l9mGcfEVdu617mGOs12oh1mGcWyX2sIW0w0eApz4bXac1W

sprite $ListCheckSm [12x12/16z] RS650O0m0C2muax_lnRNRGb_Sfa61_204r0U-Cc4x31h0HwO6r8AAvhXOi_iYOyL

sprite $ListCheckMd [16x16/16z] VSm50GC134MnLnYl_VxLZk4u0iA2AmDEox3hswLqLKBfWz8U8Dy2VFlZzT5lrIh5yEltPs-0iIKayCjFIyv5FwW0_s7Y3W

sprite $ListCheckLg [20x20/16z] dS650SCm0C0m5yFn_z-EcIVnoig3Pk9Qw2Gxq3nBRh7LFIFf05lpoG3hm3C33nOZrwR4h0CaJtftQmAyeEd2rfXELZ3mfqaBaCj5SWiMhotQWDek2iF4DpO

!procedure ListCheck($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ListCheck', $name, $tech)
!endprocedure
