' definition of the Item fontawesome-6/Solid/Marker

sprite $MarkerXs [10x10/16z] Ou02JZ393mOW1Wy3bCN601D3OZ0ZH9XHfHZW34v-Vaw8sG

sprite $MarkerSm [12x12/16z] JKk50G0X2BplVlUVLcamu19-vbrtqyFmRt3y_4WTlyB4raH20l_4S2jPWLDYHNXR-mnY

sprite $MarkerMd [16x16/16z] NSt50S1020NH7_TC_zL6rc5kRmNKrA_A0Jl0aja5Gk1D9wgFIXJol1nrkyVoVyEEq4b8YHs44kKenobGfJjSrbu

sprite $MarkerLg [20x20/16z] RT350G0X44FHh2jC_zNY4EmV7mxQrcS3Ko8_n5T8c4gavQNdMNyasiTPN7kIfcTWDCeEDIxSC924cIJj9CvSCZsIsiSJEGllI9ZG4aLJyWaF8Nwllj1c0G

!procedure Marker($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Marker', $name, $tech, $desc)
!endprocedure
