' definition of the Item fontawesome-6/Solid/MarsDouble

sprite $MarsDoubleXs [12x10/16z] POd50K0X5CE-Av3zjoNOYQTjiqm5dD3qfO2Q1LPYjOQtaTHj-AvlUL3_xiXN5vIurbVbfye

sprite $MarsDoubleSm [15x12/16z] ROw30KGn5C1oh9lzfpryAyKpkAIf_D_8eDR1V9T0cgCt1nBzBXbz4nIo1Tv681X0X_V7Cgh1rpQAliPQBJ1rlWzx38GUe5R-V04

sprite $MarsDoubleMd [20x16/16z] {
VO_55KGX5CNkTvp-gqLoaDLC5a6VwI-fCJmvSkCukxLu-ntcvDqv_c79ve6ziYBULsfaXudlkN4IcTNvMB4Ivlyn7VRTU275gKRa3bFZuRiVPgQ14XPm4-Jn
Boe
}

sprite $MarsDoubleLg [25x20/16z] {
ZP054WGX30I7i2x9_tzxWyDvb_HklC0_Y2S2-00wB09DwjXov2LH8ajDBEUvEPGPI-auhNBkZD2EWhRu3eX3hFQfVbsqp1N-bOLRiEV7Gb-vW9iKaJL7A4VT
PdCx5kcMDVt9c3WuE-bCSMcZV7PjEAYv1DJY5j4KsAsCS5RPa0oCcHLNa3uzzvKVRSOF7W
}

!procedure MarsDouble($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MarsDouble', $name, $tech, $desc)
!endprocedure
