' definition of the Item fontawesome-6/Solid/MasksTheater

sprite $MasksTheaterXs [12x10/16z] FOs50S0W3C0oz-N_R_46wWRCtxzJCRCE5_WiJ9lJYWriHS_mCq_sfmdlrhDuPPyPesF9FuvaDm4

sprite $MasksTheaterSm [15x12/16z] DSR70OGm0C0mNm7IlV-sfEebkgkQsIu7jiVs0Up6YdJHxIEA1z8fU7qL0myUsFZYmMK2fMXI2FhH2EX5byM5mox02m

sprite $MasksTheaterMd [20x16/16z] {
NO-70GCX30E5dGyTxRzj8lWk-k4AoSfW_-BIXrCZ-edqRj53YBNLQ4ADOvw1kxhzsOgJUQex6t8ry2Pm87Q8XN0o7gb6rFraVFdIGTyUR2DNMZjGdW5SvKLu
gMaZLM-V8TPTgO-Eapn7rNV2BiFASg03YmpTVW
}

sprite $MasksTheaterLg [25x20/16z] {
NT350SGW503HYHim_NUxo4RV9G9VQPQWSUjucQ9DF4Pket-Hby5i7SXMcp2JgGDLxor1K9hDfssg1rq2tz01tTl1TZmFPYfrXA3J_Z_Ohzh9S9JJf19CGEmM
NoARmXuvVDcPT626gC7RV1Oj1v7T8gazT6fg2o4R-llLxA2TdskbEjHkhEV3bCmupSV1xcNYwJxXQpAB4yKF
}

!procedure MasksTheater($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MasksTheater', $name, $tech)
!endprocedure
