' definition of the Item fontawesome-6/Solid/MasksTheater

sprite $MasksTheaterXs [12x10/16z] HOg50S1020DJzzx-qxxZ49Eq_fzw0Rm1kTfTLtungeAdlgtXLw7VuknOiDGdExHuhviACm

sprite $MasksTheaterSm [15x12/16z] HOq50eKW5C1cAxNxd_Q7rE1r0Lobd3Gk_-mjYc-4BokXMXkOYSOPgeykU5333IirF9ZXMdDiEIqActfQW7O-YI-PnXiVy0K

sprite $MasksTheaterMd [20x16/16z] {
LSy5SeKX4C3W84-mpVrFMmMc_Nu1mjZohOw8nXzlVxNCiSkJCcAr0X2xuL7e_XZPQsLzFh4slT18IzJ4RNUPBOJJ9dZjHlxVohdARQS9iTk2N40hCDJorFSU
YszP9TIvr2TS_ifSU_G0-0G
}

sprite $MasksTheaterLg [25x20/16z] {
POu7ZaGn24ETtkFxttQ56Bw8zgdGiG4XziEx4bugZHrSkz3mNTz7E9hS8Iiq6kY8cD-ZIC_890yJYSu7g2g9JN8DDt39Wjo5v0T7apjP0vOCBWNdpnRdhn_u
C15bd5WaJdvaUz4b8cp9nLgqvrT20V3xAb7rKVM1zg-koE-byrPrpQZxUCCHBrGk_h6bhUj_
}

!procedure MasksTheater($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MasksTheater', $name, $tech, $desc)
!endprocedure
