' definition of the Item fontawesome-6/Solid/MaskFace

sprite $MaskFaceXs [12x10/16z] Oy03UFdv-Pc1D1i_4c008X3Wvs53i3dPc7YOu0eO4AevmT90m8DcDW

sprite $MaskFaceSm [15x12/16z] ZSs30GG144MnVyRWzL_jsau3qGL0gc5cISFDVXa_1X_utE3M0C57e0Q8Jug140JSAl0dfNlGiTlukZQK

sprite $MaskFaceMd [20x16/16z] bShL0O0m34NHXqlaxhyjnUMFKudghybxlSsikdDkPix9IzNChBxaC6W7LEid0t9tzQRNdeIXwhLNIk42fdgr9WAriF8Lh5HqmSrgdPBLf5yM

sprite $MaskFaceLg [25x20/16z] {
jSw50OH030J0vTnost-t7_BkFZXH_4EdohWKk8EzsDNWqUoh9V6k1POdErGLmvgUjOO5sY5m9ky2vykG31eGmi9-hrhMfBlHQwv_81GlnrwPP2nwQV2M3BKK
uPdkSNI8HLmANKPp-Dm6
}

!procedure MaskFace($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MaskFace', $name, $tech, $desc)
!endprocedure
