' definition of the Item fontawesome-6/Solid/MaskVentilator

sprite $MaskVentilatorXs [12x10/16z] NKc30G0W4Cokst_QxCUH_0FWo64Khcbnh9zgt3Jfe5XeX0MBRArfLVNNW3Oi

sprite $MaskVentilatorSm [15x12/16z] RSTL0WGX081GDcsv_sb7tOvvNy2UY_9MdOwtB9CtCr9l8VYmAe1sK65jKgRRXavL3EWHqTjMDDdXs6uRj1ouyMXjycRbPW

sprite $MaskVentilatorMd [20x16/16z] {
VSi5ZWGm34DHbxc-_stNpGxJamhvKl1BNH7F0e_dHZx6DeGNQqZe_EIosR1rJm3MdEuCMBosPhTSsj0zoQhRcjCME37ET-gGTY7oQDScaBH8dbP83eyBqgij
RZnOrZAUgU7Y3m
}

sprite $MaskVentilatorLg [25x20/16z] {
ZP050WGX3CHmX_p_jxUbvvvL9cZD7rZltkO8-KCExKCEwPB4Baokz8rDVCGUmmR2OkCqG5VGdxBdEdwQjfrsl0ozYGeCixcAAP-X0zontDHL5mukImLvPHLW
9jFhZF4YN84eSXDKB6urisNAluWzWEuVIkL4JAZcWNaHBuMtLaGnRn1numG
}

!procedure MaskVentilator($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MaskVentilator', $name, $tech, $desc)
!endprocedure
