' definition of the Item fontawesome-6/Solid/Maximize

sprite $MaximizeXs [8x10/16z] Ou02VY004Y00vi7uF0my81OhM90FIB3oWqHvWGGlN3qRFpytL3q

sprite $MaximizeSm [10x12/16z] FOk30S1054DVxMR_QK_V3CXu9Rt80-QyfWIbJmj3zB73EBltn0H_wC8RvypTvlB__yRRPWK

sprite $MaximizeMd [14x16/16z] TOs50S0m3CCqvlZ_RrVkKCMGpOtM70Tqvb40PXKQO2dHx29J3KlGJExo0OjmkD11nj8itHo261xI4YhkJAOVzwb4ozqTzlZUE04

sprite $MaximizeLg [17x20/16z] {
PSo50OKm54FHYplPVzelALHFNLve30RqWodOGRaRc9I1wcO3k1Mq6RD-rblIlKYdO4nHMn57uhmPwu5BDW63jFbi8rxylrlZre1DcPxgPiRHcG5EsI5RG06r
Bm
}

!procedure Maximize($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Maximize', $name, $tech, $desc)
!endprocedure
