' definition of the Item fontawesome-6/Solid/MoneyCheck

sprite $MoneyCheckXs [11x10/16z] Oy0AkFZH0JSddCd0mC9F430Zc4Zc0W

sprite $MoneyCheckSm [13x12/16z] Oy096Fa90HO61Z3D1mJyZ40ENi3B30LeuYZQK5m

sprite $MoneyCheckMd [17x16/16z] bSYr0O0040F0l3P8zfyMT-VAmxiiTpJvWvdLkm2Gx9bqR8almXObUrMvu0NX0Q0xE6a1

sprite $MoneyCheckLg [22x20/16z] hSY35S1000FGr6xsdxRcMVyXGBoPihPdgA7hEefcR2hbM_A4qzKgfeAVcduAgg2U94C63oi

!procedure MoneyCheck($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MoneyCheck', $name, $tech)
!endprocedure
