' definition of the Item fontawesome-6/Solid/MugSaucer

sprite $MugSaucerXs [12x10/16z] Oq01_33036SpC_8Zs0peR1XWXRCX1Y7OR7004ONA

sprite $MugSaucerSm [15x12/16z] Oq07JFnmm0VaCiDvlFpyI5nU1WPyN2Q8OWH0Dfa7OXEC2xUP1GYOmKm-VcG0v2C19WO

sprite $MugSaucerMd [20x16/16z] ZOu30W0X54Gdk-v_sZNpYz-3EYn-2EBm-VGdzqaUKify3AZv_4nUZDifvXukk7_jWSYqPQ8bNlZ1NQXz3e5AEG181e0L

sprite $MugSaucerLg [25x20/16z] bSl55KGX0CNGu33s-gzst3zwjpcXnyK_ZWTjcLQGgmHmqgaQY58zM6dnK2qy-4PmL4B90Mg1DwzlYO-iZy8FvnySRx76maar1q0rbhOB

!procedure MugSaucer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MugSaucer', $name, $tech)
!endprocedure
