' definition of the Item fontawesome-6/Solid/Newspaper

sprite $NewspaperXs [10x10/16z] Oq02BFmGmCpEpyV0mCJF0E9m0IKWmhmC38mGCGJW1Mj45W1YDX10KWa

sprite $NewspaperSm [12x12/16z] PSfL0e0020DGsW9t_zFQxViXDdh3YOXHcOLC08mj71xxXc7C2fPjFssTtU-lie4_lkJZAMO

sprite $NewspaperMd [16x16/16z] TSg50KKn24FHF7Vk_jD-hSkf0b73OjwZZvM4BjrSumUCem7ZpQ2FX-iYgo6l9PV7FhuthlPSlGsEpzzE9x-FZd5YO34lSYgy0G

sprite $NewspaperLg [20x20/16z] bSp50S0W44JHk8VflrhSdNzyArEfUVLQ96q8-eGXQiN9ZSZz1U1_97Dxr5_WVKbYlCJ8R-sND0V_aafssxxmdsmP_KSMsmxymCNziBs5mosXRSh4

!procedure Newspaper($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Newspaper', $name, $tech, $desc)
!endprocedure
