' definition of the Item fontawesome-6/Solid/NotEqual

sprite $NotEqualXs [8x10/16z] Oq01_12A0qZpGm03AoihFnyh2r2K4IYA4EVZv-S30hWUHZum1G

sprite $NotEqualSm [10x12/16z] Oq07JFmm5ZyVbC733-B104GEfeeBmc1ZP-VdPsTdPq5MnyRF23EA5sOeZ04

sprite $NotEqualMd [14x16/16z] Oy0167cGUVpyJ0WEDpyVWiF4pmzMW0nGU1nmTIZciI4uF60fJ5Fua3YSsEr5E8aDnV489W

sprite $NotEqualLg [17x20/16z] VSxL0SKm3CLGbTdQVzh7K4XoJ9_N57KL1ul1NgCBUofxatOyX0SZ7itGlQmwFKxBHwLHJEXr_BztqE3HGX-X6XyydHDMhTcfTEP0ARa3

!procedure NotEqual($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/NotEqual', $name, $tech)
!endprocedure
