' definition of the Item fontawesome-6/Solid/Om

sprite $OmXs [10x10/16z] DKc50G112FguBlRVziIMV6msGGSAu2ikWPQZ0YQ1GwkIgBN-K4I1TfzWlG

sprite $OmSm [12x12/16z] NSQ5WG810CJ00Suj_LVxhgm6dZNDuCxQyEYYEctLmDsONyLM1xS-j6_X0sUwmncqmJqRQQHKUNmi--uL

sprite $OmMd [16x16/16z] {
LSU5GKH140JHMhdlivL_jZGERxJvjV6VYrzx9mvYtbUZwrFQu34sfWQnvgv07uql9N7Nv9D2DnxWyClT5PX-Eg4anYZjH7a1eNpb3M993IXn8vJRzIYPAbrW
lE0q5j4Ql04
}

sprite $OmLg [20x20/16z] {
PP074WCX30D5x-Z_lytu74pAJXChEhvO-ADm_qkwdtNC0Foa31n9sOXlODd3RGfTNEUOMhlQ4emYJl3N-RlDEAuzJZTisXf3FAmMckrY4ptC2PDqvpIJP3wk
3tC5MntOZqiWPoQ9oLs2VoBimVTGpKN_G8WmNW
}

!procedure Om($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Om', $name, $tech)
!endprocedure
