' definition of the Item fontawesome-6/Solid/Otter

sprite $OtterXs [12x10/16z] JSY54G8034MnuCxRVrlkdv9w_RjMc6_eWFZe5ZpIkqzTTKYepcs_iz4rbsfNHJFiDoz-

sprite $OtterSm [15x12/16z] NSY50GCm30D1XJdQVziQoXyyupzANnf0P91VbJih9pVWKs8Gl5HJViy4KRbjp96T52Rz6ENOvD0_bDPQfW2t5s6DAnt50m

sprite $OtterMd [20x16/16z] {
RSt50GDH203HMNUc_shNFl6y4mx_JH5RnmSBRZF0a9aRbzg0rdQw-Y5P5AnPf0g7XOkkA4rGvSc5LTbCrq6jIwqkPtGYQvCjS8zZrj1jNHUegz42lENiPQAy
ZELa0T3uWI9yclZl
}

sprite $OtterLg [25x20/16z] {
VT07RaKX34JHWNcTmDt_RYFibD-FX1hk-gJQhdgoa0xTCvos3x32II-I1XG5w4fmHI5li-0ss9Hg_42fZL7SaOl2W2gGZ2KcXHsw3cZaouz6sG0PO11AJbz_
FpGrfbFZzwE20a3NnU_7__mNL0Di5_cHD7r1Qf9lFpga_wZU9kukofEcT75lrv_6lqCVVGC
}

!procedure Otter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Otter', $name, $tech, $desc)
!endprocedure
