' definition of the Item fontawesome-6/Solid/Pallet

sprite $PalletXs [12x10/16z] Ow01uEP700O6889YBYHn

sprite $PalletSm [15x12/16z] OnWWmCkF0XYO-5cOc9ZuUO44BpyJ0mC_8mEGu04IFFpeYW4

sprite $PalletMd [20x16/16z] OnWkW0S3SFFoOm869bv-5YOWG52CGCtyG0AL0chc1G44nSE7nJm

sprite $PalletLg [25x20/16z] xScr0S0m34JHEuNnxp-jgLULDiyMwxlVGU8Y8GVCqUqGmyCRQi3g5j1my_HYcDnjuE7cjKuIwQ42

!procedure Pallet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Pallet', $name, $tech, $desc)
!endprocedure
