' definition of the Item fontawesome-6/Solid/Panorama

sprite $PanoramaXs [12x10/16z] Oy01-C60bny2-FWHW0528FWCS1OlN2F446O81w6J3Mew5py

sprite $PanoramaSm [15x12/16z] VOg50G0X30CFTzX_sdSNhjw4BgwrOkIyATS-gDnlDJUjxfQBXmRdBLZOxQ7ClVZsWY8vC6a4

sprite $PanoramaMd [20x16/16z] ZSl50GCn44FHRsQh_sh3dALt6HH7jMpvv5eSkXebXX1IdTemlFu4XgxoP_BHWtu1KHzcLGBu_XdmlRGy9JsLDdKrQjEAw_DCpd1bNTK5XX-6Cm

sprite $PanoramaLg [25x20/16z] {
hS630GDG54Mnss--i_-qjQr4_-E0dfpEX39XScOQxnhS9nNkMcYoeyfTJZBkQ98SN6fWsgXSc78uRN51Kj2EuupJcSv9RuCT6zLuojYPlPQrEemT0LcNt82X
HrO
}

!procedure Panorama($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Panorama', $name, $tech)
!endprocedure
