' definition of the Item fontawesome-6/Solid/PenClip

sprite $PenClipXs [10x10/16z] POR50G0W08Huskm_hUtBIxXg3zIrpKCMb4KPLPPyz0C-Y1fXQG

sprite $PenClipSm [12x12/16z] NSs55S0W40FGrBtPVrlUAIwVO8Xo7qcIdym_AQPG1FN_MyWPU8Moa6AS1sxEZ2Uuaw_yvwK

sprite $PenClipMd [16x16/16z] ROm54W0X4CEMdcl__rhS8MCap5OgxbTgQ8dFXvlJ57v-l4882c4CMKE0krKsXO2ox52jOgflgsXLsgdaIBfvbSmVFnC6

sprite $PenClipLg [20x20/16z] {
ZOu53W1120FBkSB_NxlkfnCZ4w15pSOT6iGmNrGXsSn4ueaBV9evoB2r0NdJRnrEXSsks1A_IMvjZyfGb_1qlnH5nTUjzQheUeZjgd1LyPIpYGahIawpCwD6
0m
}

!procedure PenClip($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PenClip', $name, $tech)
!endprocedure
