' definition of the Item fontawesome-6/Solid/PenToSquare

sprite $PenToSquareXs [10x10/16z] FSY54S0m0810wbxsdpQUSFO7hML0CSLlef1GLaFMdb5KOD53KqcmHGG

sprite $PenToSquareSm [12x12/16z] HSP50GH10C2m7Yn3_QiTXhp2iCsggDxmVFJm__k1Ffz38LStyaiFyajFwajtym_TuIxFofz-1Ri_4G

sprite $PenToSquareMd [16x16/16z] LSlLeKCn3C1GXHxMqVxJ5W8Nz7SCN6lfHlKNVdhlZ-6kuYY1GUYlKKh9e0QHjUnV3LXsbBStbn-3YUt5jFxB90_pyB_-mMaIdAx0wQAnKo0yQ_02

sprite $PenToSquareLg [20x20/16z] {
PT250OGm00J1Uzot_su_Ua4M7pnwrKzwjmE_rrN4oWOKMZKI4iskVCcvmjo7ohDEZGXGxlBrjfsFNIQRhsescPercd_D2cqSnMP2bq87Lx4TTkbfwgMtXMnd
V2XZvuRy45vr7aOt1le3
}

!procedure PenToSquare($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PenToSquare', $name, $tech)
!endprocedure
