@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element PersonFalling
include('fontawesome-6/Solid/PersonFalling')

' renders the element
PersonFalling('PersonFalling', 'Person Falling', 'an optional tech label', 'an optional description')
@enduml