' definition of the Item fontawesome-6/Solid/PersonCircleQuestion

sprite $PersonCircleQuestionXs [11x10/16z] ROO50e0W0CHcj_l_Q-q4BWV8hK8IKb_IBwfrbXzKjGZkbkx1qGip9rq1

sprite $PersonCircleQuestionSm [13x12/16z] JOh50S0038IeUzb_shfSNZa0w3l-qnXfcAQizFzZkUhYxVjrrhbK68Hpe5OvHl-ny0rKsG4

sprite $PersonCircleQuestionMd [17x16/16z] NOo50SD030ELFFF-srPsKRtaoGAGDg2S4_y7DvGBmZscHFeXMngCMz-4JME6ty5-7vUVePqE99PTy07trs_NvGEgIGUp71sC_3jWTx7bWsdpS4Z50m

sprite $PersonCircleQuestionLg [22x20/16z] {
ZSt5WKGn30MmznaJzL_juZ3hP7P-ZThSQP0x7NAlsFAXRjktktSLxBao-zTTLHtbmkPeIVh2rYIX-3V6CQZq83KxRTFCT8ss1KaOCa_vJuxLbMMrdgiX0Sbo
NTsXtLnNMzYvhWOIZ9VL1WNocnohIO4f-GO
}

!procedure PersonCircleQuestion($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PersonCircleQuestion', $name, $tech, $desc)
!endprocedure
