' definition of the Item fontawesome-6/Solid/PumpSoap

sprite $PumpSoapXs [8x10/16z] BKY50G112EBxBzb_Mbjf0Do8ersw0y_x7jPcpUGgDrxbtRqpSXmK

sprite $PumpSoapSm [10x12/16z] JOc50S0m409fuyh-qyRj5JW0WXcpsCii5HDrK___0quksDd7BGsfflBC-8PA_GpLu5QpNbK1

sprite $PumpSoapMd [14x16/16z] HSk50O0W0011fVltdvQED-28RmJbkoKwIxfQwIijD4pzGeW-gAcGHcRTOZVubAu4K8xwNM1hd7dw-xyiIGXlpm8biULPtNjF3G

sprite $PumpSoapLg [17x20/16z] {
PO-54G0X30IJTpJzT_jpSpYBRx08K3DxPC30UPwZ8Dygx1q4Hue3O9AZWEi1ztxboRMt1aLUXG5Tn2Kw2rxLXNBiOWf8oU0eWhUb9s9uX94vUnq4qmbjdR7y
0G
}

!procedure PumpSoap($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PumpSoap', $name, $tech, $desc)
!endprocedure
