' definition of the Item fontawesome-6/Solid/PumpMedical

sprite $PumpMedicalXs [8x10/16z] BKg30S1044lTP_QVzkm803UYQ9NV1y_x7iPcoUIeVtoyuYzs_pi2Z882

sprite $PumpMedicalSm [10x12/16z] NOct0S0m08D8x-7_QrDiJTOa01YygLDroJilPw3lUzZ6H83EN1OTwjkzkSkx14u15SspUIy

sprite $PumpMedicalMd [14x16/16z] LSs50G0G50HGtTp-q-elJZx9He32JX8wIpfQqKTQQ62A2o7weAP26Z5i1ZlcKpeIumzIc4jRyzqZoHdtI-exQSSaapmevmTI0m

sprite $PumpMedicalLg [17x20/16z] {
PSs54O0m40J0Ztkk_swP6o2wQ5w5500l2v0nPWzGF0C8I-3zlW5D_EbLo7fozyXlIyRm1leP0Ac-1uhuBH2SwB04yhjy1j2pkCv9numte401v1dGcE9RCJcX
Wb_dyG4
}

!procedure PumpMedical($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PumpMedical', $name, $tech, $desc)
!endprocedure
