' definition of the Item fontawesome-6/Solid/PuzzlePiece

sprite $PuzzlePieceXs [10x10/16z] Om027aO6263XvsU00dv6C0a5o2o4C8A5a8MGg2m

sprite $PuzzlePieceSm [12x12/16z] LOj50i0m20IdkLG2xFzVMuiFBij7R3GaqT5HQixP9RDoBwIrdq-0gvDK2hdKtBL0xyNvzmy

sprite $PuzzlePieceMd [16x16/16z] RO-55G0W24Jjrjj_Mv-TtwI1L7IYPCC1s6LroIHY-li2W11y4R71lZ8pImxgZYbos6IkbpteSgSj7-qsmVnUZvVF9jibj-ZsbXao

sprite $PuzzlePieceLg [20x20/16z] {
VSw54O1G30FGu1R8_jFYt-MTzUhuaGqYkdK8zBhD26tIZaWZDR3MxQ4RoGKFXPfChYtb3WsOPNLOxyH38JoOoIb4DHXbzTYqL7vXssvn3hSrp16tCSXziPrT
RUDkNxi
}

!procedure PuzzlePiece($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PuzzlePiece', $name, $tech, $desc)
!endprocedure
