' definition of the Item fontawesome-6/Solid/RectangleAd

sprite $RectangleAdXs [11x10/16z] Oq02_BW03vp52rJ4nGXcCl0mSp63zV01zVBXreua0G

sprite $RectangleAdSm [13x12/16z] ZSUr0O0m0031nvtVVrgSI9VhZep5bawLDw1jzMQZxdQcDm0xpPj6EwUsDRUcOTc3uGG

sprite $RectangleAdMd [17x16/16z] dOd50S0W5CM2E-m_RTqlRGbyouCdjbufqhPEz3aMF7uUYLq0Kmoxc192mwbTCDF8ZbqefIWITb7MgbFxWdWA43SO0G

sprite $RectangleAdLg [22x20/16z] hSrL0iGm203HgRUnkVzfrttvp8iB0B7rpmm6Qh6NuaFrRU1n6l6b0gff6V1bPA3e0E1JWy9aOghm-NK4Tmu7tb_lxkkxLb77mGJ3O1UR4Qh_5a9d

!procedure RectangleAd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/RectangleAd', $name, $tech)
!endprocedure
