' definition of the Item fontawesome-6/Solid/Reply

sprite $ReplyXs [10x10/16z] Oq06VFnG1Zy_FvG11K069XEc3anmGGWqeq2o3

sprite $ReplySm [12x12/16z] POl50O100CE2Ezr_MZZNlAeqQCjIRvRITLsZbGakPRWBpUQ_JZCxZTMMJcUvm0y

sprite $ReplyMd [16x16/16z] RSV50S1G0C9Gg7lsdxPkNtA1froU0XRmPqFW7c0Qnt4e3exySaXGIPYAoD8nfLqCjtMF_9nxj3p7rqotdo8EM74R

sprite $ReplyLg [20x20/16z] ZT053WCm241HcA_sxt_Q-UhsOysB591n1sqeG4sUndZN8UmxS_Y8KdPg2Qv2ctRGIGT_qy7zbOcMp-VYqqQJQ6AYcMWIptA5-yQ5Zg2r6QJV4m

!procedure Reply($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Reply', $name, $tech, $desc)
!endprocedure
