' definition of the Item fontawesome-6/Solid/RoadSpikes

sprite $RoadSpikesXs [12x10/16z] TOY50O0m30GFTsx_QN6dJTw9NG8zpUQa8ls0Mywr5uSrd_VCyZWDxpC

sprite $RoadSpikesSm [15x12/16z] Oo0DyCCHXCl3mCyBHZnWBZyZ684OO2u2e791odcG03CZ3mfWvqS1Q8u

sprite $RoadSpikesMd [20x16/16z] fOZ50S0m4CDSPcl_QSkS_A83Wv8eVhSnMZAd-koePPfBpmuPBhqw3Bxqx3vKaOvOLqhv7sLZm30HeZn44HO

sprite $RoadSpikesLg [25x20/16z] lOdL0S1G3099lK_2_jlMtVK-4k3m3roULbX0QAfZgsfwmR3S63IdghqWf3zrxOMhDbCTY-hqWb5rukg4zMd5aarXjWHbIs0JSUiORX4uluh1PGe

!procedure RoadSpikes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/RoadSpikes', $name, $tech)
!endprocedure
