' definition of the Item fontawesome-6/Solid/RotateLeft

sprite $RotateLeftXs [10x10/16z] FSQ50OC00CJ0gtkp_xGulCQXErNsMnjSyjamkxeUX2_yGtrU1UxrnWW

sprite $RotateLeftSm [12x12/16z] NSQ50S0m20LHf2x_zf-shda9S5OGi5_eO9wtipUZRGPYRsotdPHqj6ElJ-UduLpFTWvkXvYcsEyA

sprite $RotateLeftMd [16x16/16z] VSx50GDH24NHD_xzzbzj18ZBsU7egzJR9ZEGSFKQO_AyL1WHLnbe7YC74HDRANe1V-FfBQxibevmZZ9OPeKrNeRMWIotOoPzSGO

sprite $RotateLeftLg [20x20/16z] {
VP253G0X4C3ktUd-stvmfx6cE39WNfR9-uw8h5Xksm3v2CokQNQzN4jeZpQtXs-8Ou7Bjn1VhK_UPgqbiDIDjKmJJ6Kxe5wAilFVa1JCGSBjth07FCS5UcMu
gEUIo1w-hySF
}

!procedure RotateLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/RotateLeft', $name, $tech, $desc)
!endprocedure
