' definition of the Item fontawesome-6/Solid/SackXmark

sprite $SackXmarkXs [10x10/16z] Os1Wu0S2JY0DOJ8W0wWi5vW10M064p-Gv8OePmUI760M4rG91qWMY64

sprite $SackXmarkSm [12x12/16z] HOY54S1040B9kzD_jnbUzsmF0A2GR6_Oj7RLr5gtTeeWvQO0ZVmQlqwk61zqh9P1qUdwGVJb5_3n0m

sprite $SackXmarkMd [16x16/16z] FSw53SHG30JHERxWzDzjh9MoxpFQC8o3w7gXiePw3g2syUlghG6nUikRHOkHoBhZQAYTX-E7qQH-wLUQT3eUWj5R7nqleyY3Uby

sprite $SackXmarkLg [20x20/16z] {
XSy53iD030J03UTm___RrfL9Aatmo80Nge90TUDjSY8h50l-EPjOa51Lc9LkwDJ136AXIlLGO9NHoQS6t7fYerK9f32NDKsL0j_wpJKDcphuLjMjBr7v3dpJ
iRrFFG
}

!procedure SackXmark($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SackXmark', $name, $tech, $desc)
!endprocedure
