' definition of the Item fontawesome-6/Solid/ScrollTorah

sprite $ScrollTorahXs [12x10/16z] O-1bW05-VduW1WDcB6nEE9k1aP-10ShcuGSYc3W36oDC72B6ZDDC

sprite $ScrollTorahSm [15x12/16z] TKq30a1H3EgPM_S_xRSniq2SueJidPiuyhjr_TB6Q17pqGAaiqSx6IqlMzM22vJ73RdyybRTP6f7

sprite $ScrollTorahMd [20x16/16z] XO-50G0n20DJfPxzftrtlIeEg14d1WL9azgEAHmPdfrVNS5TX-BFEcrXhR8u-K6DhXVT-DNrgAi67A-ZpcBcKbT9llNItCySTrqZjJg0JFO

sprite $ScrollTorahLg [25x20/16z] {
fP150iKW30K7XqhU_K_xNGkiEZZni9gdeogP95B-moKzOTCV8PyMaCU2K1W8d7C0pjM30BllOIdb85XSa6IWW-0LoAUZ86OahGux2CWkvaoA_XYZDQfFhLbV
Ht5CAa_RH72okqqoZdX9Lm
}

!procedure ScrollTorah($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ScrollTorah', $name, $tech)
!endprocedure
