' definition of the Item fontawesome-6/Solid/SdCard

sprite $SdCardXs [7x10/16z] Os1Wu-Vdvs7Wu0S1HdvcVWO6C9EBZvy8m0sX

sprite $SdCardSm [9x12/16z] Os1WuEC70ZO61du8O00YCEI3CIW4R306

sprite $SdCardMd [12x16/16z] lSR50SDG50Cmju7B1-q_RHWsY1xOsNGW6xU4GPst9qXBfEhU3fMk-LIyLW

sprite $SdCardLg [15x20/16z] rSS50G0n3C30F7FZN-qpJS9kq8PT4LwcenfV0RK_HmNTCIcqyCX6Ia4ZpLEdlGwBUPXC4FuC6m

!procedure SdCard($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SdCard', $name, $tech, $desc)
!endprocedure
