' definition of the Item fontawesome-6/Solid/Shapes

sprite $ShapesXs [10x10/16z] Om03HWOeuEU7ClZuOKn-51P89Gyd0q80JF30MPnm5e8

sprite $ShapesSm [12x12/16z] Ou003WOuuEU7Cxdv4Hn-8625C-4IxBn0m0rYiV4p8glbXv1iI6n-93OZX8qWsI1i

sprite $ShapesMd [16x16/16z] NSY50SCm50DHjM6y_QSDoNp6znKxLGLRoGNu5GOuCm_UXiWE5xtXkZZuEMDbL6xaBRu8fzFlsfZ6OsFvEP9bwcVV

sprite $ShapesLg [20x20/16z] PSx50SG03CH0XJdglzh3yCxFR4vhmPFAGwSEqHQDgv6i_6iukSisxRBFWaqgvtXizQk7mhzrIsbBwwPqH-TcDdEQkS7CuMRXpFN-GUC6sdyNq4y_xHi

!procedure Shapes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Shapes', $name, $tech)
!endprocedure
