' definition of the Item fontawesome-6/Solid/ShieldVirus

sprite $ShieldVirusXs [10x10/16z] DOk30S1040GdThx_Qi_60ez1n3Oy05yzfWN-V2z8x22nTzn0MwBZh8D25

sprite $ShieldVirusSm [12x12/16z] FSY55S0W4C3GrBtPVreSFd9vHo7DOJO3lybhSb4AJnMLvBBqnmryOx-WDsjfpZBq4-_Ii_fR4YwpYM9lsmW

sprite $ShieldVirusMd [16x16/16z] JOs50OKm5CI2Ezb_sYySqAOkUKVefMBppvX3uyiE6Dei2zUiw6LnFPOgn7lC4nNUoXEhsW07IvwIaurPc1gcjjSfrbFNadEMN4x30g4-Hda_Vm4

sprite $ShieldVirusLg [20x20/16z] {
LSw55S0W34NHL_Vy_RSj2NQuLI16TMfcC3ro9yscnWYN1hQ3YXSL1tAtTE4Vzo0tiU0i0b0WpANx9yTrayWjqPPEKea_IApKg_4aIpv_WJTQPKhgp_nemxH-
7kRwf6uYA9ZSHQ7cerfK67HZLF58sib-
}

!procedure ShieldVirus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ShieldVirus', $name, $tech, $desc)
!endprocedure
