' definition of the Item fontawesome-6/Solid/ShieldDog

sprite $ShieldDogXs [10x10/16z] BSk50S0m20H0gFlllsrVSb6igBUo6y8Om_S19nUjBAZc1rVnrmh88yc_2gtao-S7

sprite $ShieldDogSm [12x12/16z] HSR50SC05CKmjs7wtd_RlB1EWkXxRfkn4Rwex-kgVmfZQSwliDfW42NvJBJcVmkC1l06yJLAYzW1

sprite $ShieldDogMd [16x16/16z] NO-50S0m2C0oh_F_jwjRgZXGS2-3GnAEmYkT0v05mYRxUBs7FmzVP1Ml4u-3v0jLJhWY9s2oXzx60wV8bNnTSokjIK8LjmwPQuYBWi4OxmS

sprite $ShieldDogLg [20x20/16z] {
PSv50aGX3C3GV7To_zEEGJlsTWGhJNVDV5kAwjwH3bFVBlbbWivVXUAVsigskstPZlfo9t1TrwjDqNe1JXLKHmQXjGEizjgATctWjQ-fKu5UNQXMNrSXBbfr
STuhsiNBNXUrqMZg2EK_PUJBeAuqTm
}

!procedure ShieldDog($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ShieldDog', $name, $tech, $desc)
!endprocedure
