' definition of the Item fontawesome-6/Solid/ShieldHeart

sprite $ShieldHeartXs [10x10/16z] FOkr4G0n4CJq45lzT-ivLBH88CbZ47v0F-Ia8bZrMpdlN3v3XGoHbBW

sprite $ShieldHeartSm [12x12/16z] HSc75O0m30FHetUq_xOyMK1-uauHn2JhW5EV1JL89uoGliVEweNvFcVuyutI3mfib_LONG0U

sprite $ShieldHeartMd [16x16/16z] NOw50O1G44AnM_RVrYkiz_CQ92tnOgRJbtLGB6Rnm_Qp6RON0Qti3ibPTliqNh2vCyaVvU1Zd_KkBZKTT7xwQf3C5SKfzM8oiu5p0G

sprite $ShieldHeartLg [20x20/16z] {
PS-54S0m34FHN-Pe_srx3iCxCgb0ielEBREHJSfUCASQtmmQN6ZmXDa2Xm1NPXT9w6mraxmMucw-ooucPZidMcCZKusSdUVXd2iKjqiip1FgCD84flq9-g4Z
MSPHldnfd9AR2Nu
}

!procedure ShieldHeart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ShieldHeart', $name, $tech, $desc)
!endprocedure
