' definition of the Item fontawesome-6/Solid/Shuffle

sprite $ShuffleXs [10x10/16z] POl50G0X4CHohf3-gyL_P5s62TaKiC3pIF0P2q0ORKCSYfQQ0hYhOY0P

sprite $ShuffleSm [12x12/16z] RSor0S0m34JHRsRV_jE6rULLmkFFtE0SDxUqbwG0kW5RH36L0Pv9os2DoGgC9qT2SlFDmNBCdMDQuGG

sprite $ShuffleMd [16x16/16z] VSt5OGC130NHMQQ_clwhJSnilvDO_B0MJs91aksSHTrtrG2UqJIDziIzYOu0ZOAGSmgBdkez5wKyEMqknSaiZTx_w-b4IklqlmVg_h_Xg3d_Vn0d7ZK3_0C

sprite $ShuffleLg [20x20/16z] {
XO-53GGn4CJc6BFklzjNQAHdYv9bwp_pfJTkuaECq4H61IgHS31eQ3-E0vAKu3foV5NcX5tYbkuSygH1-NEngUCzeynOWyzSTT1yEqAvvCaZobfuyiZR9fuz
KhdooMDN9Z-Zz3npluNiOUpn
}

!procedure Shuffle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Shuffle', $name, $tech, $desc)
!endprocedure
