' definition of the Item fontawesome-6/Solid/Sink

sprite $SinkXs [10x10/16z] HSQr0S0m44MnVqrYVljFQmPLqeHf1yv4E1j2cFE_P46CS-dXkFiR

sprite $SinkSm [12x12/16z] JOlL0G0X04AvFfFzfxL5tnU9JhIOi22DQ-gZY4jwJcFJR7SMtVRS-Fq2JbXGE5pIo

sprite $SinkMd [16x16/16z] LSpL0SLG3CDGbV5Q-q_x69hp5x3vsfsuK6tyR6RGZg_OSJgKcO4oVzKvQl-QDp-D3fy-O4bYuaiIhHWgzkEgetdLCPGPoiF87G

sprite $SinkLg [20x20/16z] {
ROw50G0X30FpbkBPVzftXyCFQ8i7K-xmHHlkexnsViyIEic-pczJg5m_e78FbUj22FvsmNi3k9TrkgUSJk5qXnX8cX8f9JE9AsfGL8CMK_m3iF5rR3ZybM4b
VvG75W
}

!procedure Sink($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Sink', $name, $tech)
!endprocedure
