' definition of the Item fontawesome-6/Solid/Smoking

sprite $SmokingXs [12x10/16z] HKg30S1037p5sd_Q6k6fFSNjgrwM7wbMyyC7-GtwiTcD_-1T2-Bw8bhXPQz-u1q

sprite $SmokingSm [15x12/16z] NSx50O0m5C3Gu4xsdnQdzaxjTuAHZMWJYNfn9tAhNGa6nrcYMOGeVgFgyyqF45__6HRP4m

sprite $SmokingMd [20x16/16z] ZSu53iGm5CHG1yfDVF_JBaE-i4yZicWOTMX4pNIQ20xhwavGxEXAe3LhObGrLoLO5INIr2GwJATSDPz_1-nmp8xI-Tn7JG_Tr8RMdlmq7Bs_t04

sprite $SmokingLg [25x20/16z] {
bSd50KDH3C0mV-Rd_QSjOrBKLGIbejd8DaN7Tx6IZCgg3L6bBMf5f5AhH9LAenFHe1khaenQrKgcO_Kc1fIiwg5k-T_iivxL2ksDq0dlffEIephPlCPYS0sA
prQA7Re7
}

!procedure Smoking($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Smoking', $name, $tech, $desc)
!endprocedure
