' definition of the Item fontawesome-6/Solid/SquareCheck

sprite $SquareCheckXs [8x10/16z] Ou01VZo0WGDCC322ULZLmiG

sprite $SquareCheckSm [10x12/16z] Oq00VY800vp10EN3zB4W3617qyI3qCxD1m7i

sprite $SquareCheckMd [14x16/16z] bSYr0G0n581GpYMs_xHnBJ_TWxNBzWota_VCWEd2Lt2oDQGsAXf_9unLIm4

sprite $SquareCheckLg [17x20/16z] hSUr0O000C2muax_lnPt9YHRk8kEGl2igVrLI7vw08spD50Zg5m0fzimAZsutfhSzp8lQ3n9kEe1

!procedure SquareCheck($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareCheck', $name, $tech, $desc)
!endprocedure
