' definition of the Item fontawesome-6/Solid/SquareArrowUpRight

sprite $SquareArrowUpRightXs [8x10/16z] Ou01VWo046I0KbnG7fZcGrKCfG4

sprite $SquareArrowUpRightSm [10x12/16z] Oq00VWA03KaHAup5mS0FON41AH0BGZ8ZQ-I1inYu-I207G

sprite $SquareArrowUpRightMd [14x16/16z] bSUt0O0W5431Psf-t7zQim8TN7UqjlWvMuvGRb_TlUm44rLofaePH3tF3hHh7

sprite $SquareArrowUpRightLg [17x20/16z] dSor0O1040NHmPtflrhSYUvUjFhvovvIy6teZTEmkvEI1U1J2dpwX7VlSv219hpwvw035pbtWY4gFnXyAVYQ0G

!procedure SquareArrowUpRight($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareArrowUpRight', $name, $tech, $desc)
!endprocedure
