' definition of the Item fontawesome-6/Solid/SquareNfi

sprite $SquareNfiXs [8x10/16z] Ou01VWp0myy99BbO8N9SZ52Q7qXZ0fWO

sprite $SquareNfiSm [10x12/16z] Oq00Vlo0XP-9aO43f8g1duc1Zn_4OcTa0b9W5XkCnStFpWvIZG0yS1O3Dny4i0C

sprite $SquareNfiMd [14x16/16z] ZSU50KKn24FHK5Uo_xHVd_kjmC4whrDT0f-Nb97HMlqif1KQHUsqxIkKZqG6LNoa7DG2bk92dtJwBvAL09d36m

sprite $SquareNfiLg [17x20/16z] dSe52aGn00FHrBrp_zEkxrUqWuL7T2yU2nBdHcUb3XDgAPy9GmCVaBMZcI-O3m1_K7k3rFzGTNaWNO0JJ86F7-Y6bHAND3WLTEq9

!procedure SquareNfi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareNfi', $name, $tech)
!endprocedure
