' definition of the Item fontawesome-6/Solid/SquarePollHorizontal

sprite $SquarePollHorizontalXs [8x10/16z] Ou01VdI0BeQk2bKQnW4

sprite $SquarePollHorizontalSm [10x12/16z] Oq00Vgo0XOK5mk13AE430H234uj6BWOc69CRGl70vHYu-I207G

sprite $SquarePollHorizontalMd [14x16/16z] VSUr0G0n40CmX_cy_xJF354dt3avDENPrUpacCE4XpOv8cgXkR1OLIvamIt6ykG0uQbKVbAt0Ug44G

sprite $SquarePollHorizontalLg [17x20/16z] ZSZ50SCm04MntmRCVljF6sRMKJghjog9lHJvmfKTnqe3LkRVCJmeDGcCDAiOnNfak2F97SEm4oBt30TAx5GwQW4

!procedure SquarePollHorizontal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquarePollHorizontal', $name, $tech)
!endprocedure
