' definition of the Item fontawesome-6/Solid/StarHalfStroke

sprite $StarHalfStrokeXs [11x10/16z] NKg30G113AlUoFxJdbr65Cke5L3HNY5_WE19PgZ4CoRIb4ameGMYmRmU

sprite $StarHalfStrokeSm [13x12/16z] JOp50O1G08MmM_QVrlZDxIM1XGQbi6lN16UC3dzGxmcZW54X2uMeok4P1UHanhK8lOt22Gw55m

sprite $StarHalfStrokeMd [17x16/16z] NOw50S0W30JhnM__QN5tIDwEElHzh0FsFyzMM246FgxwkQN9VS2yiKWTXyoNhZSCBpKAS1R5Mg3fkbAuQMaxufaB8jvwBi0DS-u7fa8cgrm8

sprite $StarHalfStrokeLg [22x20/16z] {
RSy50eKW50NHQzEp_zN-V8Gnzh50hHKz1E6E1_3qwCF3EmWU7bN13JBj6K0p43Tx5KlgPsbGJKS6cAMklnORIbF3A0tSdhIwGXgdq5IjDEZKjF1h-PvjJS6I
9rxK0uKyAeUa321h0czdcV8zlW4
}

!procedure StarHalfStroke($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/StarHalfStroke', $name, $tech, $desc)
!endprocedure
