' definition of the Item fontawesome-6/Solid/SterlingSign

sprite $SterlingSignXs [6x10/16z] DSYn0G0G0C2m0ZRz_rg0ZE7fsYXInRh3UbVva-vlRXC

sprite $SterlingSignSm [7x12/16z] FSZ70S0W3C10-PCUjF-qT3Xti-dR-w-S0i7J1dL4GB9XFTyn_5k_x4XT0G

sprite $SterlingSignMd [9x16/16z] JSk54G0W30F0u4xstvR3-sWDKceM4wSstwmh2Sm0K53qcFwdaxtt-IuHC4nAATbZQB6GTvfrAfq7hW4

sprite $SterlingSignLg [12x20/16z] RSp50G0X40F0u4xwh_PSi7cj1YEXr5jMdjnRNW131i1UDLcUhxEsUArhpOTl0Yi0JvPm4FElQMhrbe5injNUPE7FDZKQEm

!procedure SterlingSign($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SterlingSign', $name, $tech, $desc)
!endprocedure
