' definition of the Item fontawesome-6/Solid/SunPlantWilt

sprite $SunPlantWiltXs [12x10/16z] HOd50S1048I8U-Y_siZPyXa1EAc8qrNw99Rp_gjTyemtmcdw1hShEO4RblIIw4ih2Bl12m

sprite $SunPlantWiltSm [15x12/16z] LOw50K8n50FpwtxxRqjmkCfpaGdwKg-9riUyOBC_fcEj8xEWHKuZqcpol2tHBNYO-q17VGk1JFS3cykcUPlV3Vgm-GT-cpzk

sprite $SunPlantWiltMd [20x16/16z] {
PSk50O0m4C30u53B_jlYVjKtLecVKJvKYtvoGvsTs4rX7NGWelKrHDGwYbe1bR2Eb0mu06qAWX7KeXb6LJ23GViZw2KeYrfM9XePb4lGDOU1It_aNWnhxkV8
vHUNauf_Cm
}

sprite $SunPlantWiltLg [25x20/16z] {
TT25THmn0431ltYuclwxpLCuiJrYXff6dzlT-eXri0pzPs3wiDrAnVbdOzSiXgNN6djDcwc1NaQucbXwMpfekxQurqJThBLGSLJXvy2_j-92NLx5YPtALRIZ
wVYv_-9LjA8cDM6D6jxz3MTKruVVMQ8FLi-Ypr5Dot-OUKzV-7BW6m
}

!procedure SunPlantWilt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SunPlantWilt', $name, $tech, $desc)
!endprocedure
