' definition of the Item fontawesome-6/Solid/TemperatureHalf

sprite $TemperatureHalfXs [6x10/16z] HOcr0S103CGKvcZ_QGtL6mu1wsSLl71lz2XquEnjLT9xplAeKm8

sprite $TemperatureHalfSm [7x12/16z] JSMn0KG0002n-mU0xB-jaZIfpgqAQb5gL_vluoUct8bHOX3bBkW1

sprite $TemperatureHalfMd [9x16/16z] PSt50GGn30J1CRCx_sWFba5OUac_64t_YFpY3uZrBqEL_h2KD-AEVaTPOV_7Y9OXPlXvARV3M2MgF8m9-tUZBm

sprite $TemperatureHalfLg [12x20/16z] XOw54K8n50JlnttxxnPkq37Oo7EHcJGzQ9XWDV30-k58wH60xf_ofTS_Eh_rwwLlxq8G6bZGBvYFL681j5c27At3q0Q5fW3P6vuKwcFfoODBTugr7QGR

!procedure TemperatureHalf($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TemperatureHalf', $name, $tech)
!endprocedure
