' definition of the Item fontawesome-6/Solid/TemperatureFull

sprite $TemperatureFullXs [6x10/16z] LON50G0W08JERjb_Mkld1KZYtC8H1U9Z-ccfY7X-cYrgWDa

sprite $TemperatureFullSm [7x12/16z] RSMr0OG0002nUyN9_jCYFMbIhLCLrA3Kx9VtS-xsn5VY8yfUq0a

sprite $TemperatureFullMd [9x16/16z] ZSsr0G0n241HBkv__sdZwGzzLCYCccM5OyO2kBJqaPmiA6BvZNYWrb6TeWhDJk_I3vyIJn83jS7x_ia

sprite $TemperatureFullLg [12x20/16z] fOhL0SDG3CIKF4RjFssP_YkpxxWph3oftZdlw-cJ-xxT49-2DaJpprx-su_tlc3eYNJlmtReU5eDMMKvqHHKjBEKit9g8kgEPr61uPC38Akk4wu

!procedure TemperatureFull($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TemperatureFull', $name, $tech)
!endprocedure
