' definition of the Item fontawesome-6/Solid/ToggleOn

sprite $ToggleOnXs [11x10/16z] Oy01-A40nk81OdQe20CVN9A1XPy9nWGI_720R082

sprite $ToggleOnSm [13x12/16z] Oy03MFcX0CZcveS39WQuC1y_FnTS2KGOmM53vi0acPb1GamW9eP67ZJx0G

sprite $ToggleOnMd [17x16/16z] ZOor0G0W4CGETzX_MbmxWkODNt3dEvQWmT95TNfxYwI58xBUdYoNgBJ82g3Hx0cebEmJQEyAXEhi2gnn2YjowX2EAtnG

sprite $ToggleOnLg [22x20/16z] {
hP055eOW40RNLlB-fwLZuyKVZWBV6nfuXSiZp5gbPoWagTPakYdDWeS-a7XIi7WdABYifzohFJq1AdkAQBExMfNYAWQNXAnR0CeeXHV7avIG2teSDB9o6jjH
Atn91
}

!procedure ToggleOn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ToggleOn', $name, $tech, $desc)
!endprocedure
