' definition of the Item fontawesome-6/Solid/ToriiGate

sprite $ToriiGateXs [10x10/16z] usM00NuuO8ApWA9GX01ygB8C818_2m

sprite $ToriiGateSm [12x12/16z] bSQX0SGW50N1_G0AOFklzYvHJsVK74BZ63HdcxPsBB1HmXOghW4sNbk-_Wy

sprite $ToriiGateMd [16x16/16z] hSp50GCX54NHYpkl_shZ6L_EmVaosB5wcNywIzh330LhvtiRyi2GXIa3NPpDdJ6l-fclllJxwkA6TvFXgmcU

sprite $ToriiGateLg [20x20/16z] nSsr0SCm54NH9sRT_RSDSmoTJo7uE8o-1Q2vDtcmc-MNP25OUpxh-HnCgpEmrxESpyxKnHZcUgRpMKVNNvuVS_9BkK0j3nEAV-uzU-mzDAQdGfDE

!procedure ToriiGate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ToriiGate', $name, $tech, $desc)
!endprocedure
