' definition of the Item fontawesome-6/Solid/ToriiGate

sprite $ToriiGateXs [10x10/16z] usA00NuuO8ApWA9GX01ygB8C818_2m

sprite $ToriiGateSm [12x12/16z] bSQt0S0W4C10lNFM_jCw0pLNtKBMQB5RqDWtlKsp6s1329iGnM41DZmsgVq5

sprite $ToriiGateMd [16x16/16z] hSp50GCX54NHYpkl_shZ6L_EmVbIBLj5B_DFPqbxcA5WxNnlGnuOiZ1be8kpkJFcLJ_prPT-NrtSy6uoV3N14m

sprite $ToriiGateLg [20x20/16z] nSsr0S0m40D0cTdQVzemSvSh38_HuYYJp5wjGkLdacU098sKtHcxix1AT4Wvd67OMT4hHGodwyvOCYvfdjJAC_ZGRGopIWOzx-tDUt-DOH6OW1O

!procedure ToriiGate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ToriiGate', $name, $tech, $desc)
!endprocedure
