' definition of the Item fontawesome-6/Solid/Trophy

sprite $TrophyXs [11x10/16z] FSh50S0m5CDGbTdQVzfoyYuVRC370MKLJ7p5hNw3fIkcVv-siFbgU7HAuLGtt_S5

sprite $TrophySm [13x12/16z] JSp50O1G081Gx9RzfpL-lpi0lG61qGA7hGcZddkwM78ZveXELl5t8x1wj-yZZZ8lAYNpTm0l

sprite $TrophyMd [17x16/16z] VOw50O1030EBEzb_MrBUzLxh4JB38XOu3hNk-uRZfV4YvurA5luFi2fg2YwPWeDnVO83grhEiVrH6VYpCfoq1px5ST1w9udHx9xZrf8hs77F3m

sprite $TrophyLg [22x20/16z] {
RS-50OGm5C3Gu4xsd_OKgBwwz_FL-3Xu70OzjpEVdQqxppCRgmAxGGEhcy1a09oshj2ciyhLHlyTN1ZTuw-rtFjEUc-WxHN3u6LPTE1dCzPmQS9yJwnJNIde
GaadSisgjgIyx4HcR_oy0G
}

!procedure Trophy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Trophy', $name, $tech, $desc)
!endprocedure
