' definition of the Item fontawesome-6/Solid/TrowelBricks

sprite $TrowelBricksXs [10x10/16z] Om02BY06q_pyO9g57mXuUO440n03nS040v200x04AWlEu-I70Iu81G

sprite $TrowelBricksSm [12x12/16z] PSg50S0W30J0Rt7VVrhSEIIAmcDm8Qoiv7_-VLX0Mnz2iFoJadyPchRpvj9cdp4QsbHr5eQL9m

sprite $TrowelBricksMd [16x16/16z] TSc50S0W00F1r1Mo_xIuow4FS5Q9maeorqOMlT0xZiETaZNSuGHUS_o0Vq7fjYqjWKZIcVRVD3PhNRxlUx5-4QtjPsKJZ6Jphm4

sprite $TrowelBricksLg [20x20/16z] dSg54O1G0CFGuaxtdnRdkx_pNF2P5nWcaj3Cl1cFQCDqgLl-jctR-TXfmyOFBky6L8jig2vuRA99pukAhntIm4z1gsMpLSjb1gP5cFYOAbhcEjPctZfGSG8

!procedure TrowelBricks($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TrowelBricks', $name, $tech)
!endprocedure
