' definition of the Item fontawesome-6/Solid/TruckMoving

sprite $TruckMovingXs [12x10/16z] Oq06_520nEHd0h8H05cSdnZ0oyZDpm0s40JvEK5C1Y09

sprite $TruckMovingSm [15x12/16z] bSc50O0m40J1mvtjlrhSYKxohWykxud1DQxUrvuuhUX4ka3jaDD1YnOq52hwzM_wGZC

sprite $TruckMovingMd [20x16/16z] jSkr0S104CH0cTdglrepG_YJ72vVilxKHUlA6sRUnV-xfmZlKlGZQm2WO1PFUi6ubap9PLQjdTgg7PDruii8

sprite $TruckMovingLg [25x20/16z] nSd50SCm5C1GXJdQVzf2c7mfFlipOSbUnCIZaa7h2GFVFmpooqFNQOHd4ElrWTBU_u9COtAhUA2WTCOKcbAQCz0vPemwrGPIbKIDcFJFVTWT

!procedure TruckMoving($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TruckMoving', $name, $tech, $desc)
!endprocedure
