' definition of the Item fontawesome-6/Solid/UserLock

sprite $UserLockXs [12x10/16z] RSR50OK000MWzpiCzf_MRkL4ahXbSaCn7LmyU2MLB4HomtiyK67tsleM

sprite $UserLockSm [15x12/16z] LSc55S0m30DHkSpQVzk6J1VypoW9DtWlIyugdqlZdQUJSI_wolkG217NWzAsxzAuVkNkOTo9IoOpVm

sprite $UserLockMd [20x16/16z] XSm50W0H40NGsTJS_xIwy-k70H-cVcY3b4jhJZea4sFHhihUQ9Dwt6qlJYeKUGTjX8NUP3AgGZxtbNDNMEL0ivwDJKpM9i9g

sprite $UserLockLg [25x20/16z] {
fSbL0WCX30RXVrsJkVzfA-awyDGFP_JJcVTALOH6JspqCBDPTSVXxz2o6VHW15U8ssO2c1KSSqmfY9N29D_2GbYhUrWvc2es4bVgs6Wf1GfXA0KlXPMRkcBp
1W
}

!procedure UserLock($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/UserLock', $name, $tech, $desc)
!endprocedure
