' definition of the Item fontawesome-6/Solid/UsersRectangle

sprite $UsersRectangleXs [12x10/16z] LOo30G0n5CNUcMtsdxPclgcDYbO6Z2envxDiaFBetw_an8MKHn_jIxS4Bcdw8peU

sprite $UsersRectangleSm [15x12/16z] LSV50K81042XPxViFwtvanjbzYZMMlZrLjT3c-k_Twx4zjSU7MXxxzSRLHp2XY12_UPG_Tlseyf32xBo1W

sprite $UsersRectangleMd [20x16/16z] {
PSi53i0m049HwbxkVzkjFlanyXA0m7SAuAyQMEKhrLZYNHuMFQ2Jk8TRbaWOaYYacER9llgOrclMEj-ot0mBP4AejPg6mmm9ze9ODb-jDhS9sS8oXNU5YYpl
o9k_wGi
}

sprite $UsersRectangleLg [25x20/16z] {
TP350SH030Db-sXH_NTxKHZdOPfa2V362nb0uItXVA2Hk18Kk64HgHZW9G7ubDX4LdGgci8gYcAbebQtLHYPaAQQx5Z5H9SMnwNIQlcUnTnu301w89k4OfOL
NtM_MLW4NfpHd_lDVwiGEm6ViBsuOcGcNtQXaE0z5V4m_mC
}

!procedure UsersRectangle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/UsersRectangle', $name, $tech, $desc)
!endprocedure
