' definition of the Item fontawesome-6/Solid/UserGroup

sprite $UserGroupXs [12x10/16z] NSct0S0020CmIE_w_zfKfcW1st6JKH8hdX-qZFNhM6le4J-9uNi1GLU_3OUoSm4

sprite $UserGroupSm [15x12/16z] RShL0SDG30D0X_Fmzf-spCrzsPBYOh36MuFe-lq5QyTz2gNXtOwUxuOUcEF8kct3wt4tJvJNHw3FNXPV0cS

sprite $UserGroupMd [20x16/16z] bOz50WKn24CpNi_zJ_ibL9VpgZX0HDvOUVW7s5FiEXfwJmZVT4MtY3Ish5kwS_4p7IYIlNEHZ4EgTmGQ5tnAZrJiPFqVgJeEviyPaoB5qdPPTHhl2m

sprite $UserGroupLg [25x20/16z] {
dS_L0KCX50FGu4xsdxP2K_TtVj1hE0bZHZmpN1m0wmokAFe1IALqh6L0U86n5lFk8Jq_pBi7JqdGkoW19ufwk5WN5N1QjskQp-1EvyK0ZakxJ76birMQgw4B
0pw0MKjFV52XQVb83vqFXXxs
}

!procedure UserGroup($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/UserGroup', $name, $tech, $desc)
!endprocedure
