' definition of the Item fontawesome-6/Solid/VirusSlash

sprite $VirusSlashXs [12x10/16z] 9S653SH0400nFqDW-kysMfrzDmv6DsIfes6S3SiZzOEY0LkROhmhPMJlvPibw08

sprite $VirusSlashSm [15x12/16z] LOw50O0m30GVTsx_QP7aaLubBhM2NeR9lm6aU0fMabr92pFWDhL4PFnh-JbcpL_j1gXYKE8yXzijvsgdt6tW1

sprite $VirusSlashMd [20x16/16z] {
LSo54KCX403H_Jhuzbzj_1ZoS4xsp4yd94TSc0xT4j3SWSINEhQaxfloqvnkmcrWeTkv_kLHGPDlBG5KrU-nbE_gngKw2ATwWihVdms6cJ0xvLcSlK7xj_N6
L8oQav3ag_i4
}

sprite $VirusSlashLg [25x20/16z] {
JT055iCW403HGTg627F_s_OH8lkVuApadSVnuRLhOifAi6dbL9JegxjjFYv0bvj3SpWsDGQA4g_cQoSgQghlGQ1oE6IOjguPDkrElJ8uBF3pSJ2aqjGDigV-
AJ6s0Wv43XMQxaIU6bID9p6eTcwhPghEhHwwietPJpajkX1aPKfwy4hAhVi7
}

!procedure VirusSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/VirusSlash', $name, $tech, $desc)
!endprocedure
