' definition of the Item fontawesome-6/Solid/Volleyball

sprite $VolleyballXs [10x10/16z] DSY54OG00C2mlYja_sbnSZrhYuysne7hf_Z6moEnJkyxEjDVRWm_VlTl1FH9DsujGCq

sprite $VolleyballSm [12x12/16z] DS67WG8W00Im-rVfaFsdjPlaPSgN8FB42Qj8-B_-8NPaKoZ7R0FX38AMHb4dbyv_dXW54983IhA6MtusgCa3

sprite $VolleyballMd [16x16/16z] {
HOi5WWCn3CHaBqEY_x_shgqN5FG0FwOcBoTDvLXgr8ugjXezI7KBJsYQt043PTGyr5nqD4UrePwXhQ9oNzH8rFyeOtQZc5HsRpXr7BtfBFeB5K2RPaV8TGcA
Nt2TvtsiEUuky0y
}

sprite $VolleyballLg [20x20/16z] {
LSu53aGX303HmRuXS__RRfgmzd1jsUubVofDbJGJcowcAjdxlQK7gfFkyzvwu51jHAEfcNjYO2duxgPgpdgX2TLSL6_KouhXsb6YMmp3Wm7LZ0PWx20ZEdse
LY2HeBoJDVIZjaUokhZycXJVsRnbaYwW-zQ1Mx8Lob17WN0pr3iJCfjVlBt3panu0G
}

!procedure Volleyball($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Volleyball', $name, $tech, $desc)
!endprocedure
