' definition of the Item fontawesome-6/Solid/Water

sprite $WaterXs [11x10/16z] RS750O1G00KWxFRjlwqd-uEY9XTq0sEbemCcQowUmjeHkN4v

sprite $WaterSm [13x12/16z] TSE53K9H44N1-zptzDyj6mM-J39wDx3G80KeXmMOnz0_yxjAoRJveIHLNuhN7s1xExuXWp9W9lJh0m

sprite $WaterMd [17x16/16z] ZSu52aGn0CJGVAktkVzjrrq3F0OV_cWk1_Dyi07k6_rWyq2_30yLPGAc0vnvJHCaNQ3RQ3wrk56qCGr7eCXhIpwObuCL66e_7Hltnxg7ilAp7G

sprite $WaterLg [22x20/16z] {
hSn5WaKX34JH2cwXzh_RVg6_kzt98HX-K2BBXfli0iZW57ZUIicfNBKZiDU8DHkk5B4fudR7etg2iv-J2uDaTQxPpp9ugq86hxPAqerkuBt8nM0q4jiQh37_
qKNbpKGB4BkE3TTKgq1wnnlz0G
}

!procedure Water($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Water', $name, $tech, $desc)
!endprocedure
