' definition of the Item fontawesome-6/Solid/WineBottle

sprite $WineBottleXs [10x10/16z] Ou02LWOOuEU7C_WX58p12sDmCR03MI06M1wg55KvmW06

sprite $WineBottleSm [12x12/16z] JSo50S0W40F0rBtPVrhi5RqW3szVSE5ld4ZATOEIcKVZBGHQU9J0tzTlb7fvZB8jF8FZAGSrA2i

sprite $WineBottleMd [16x16/16z] RSw50O0m00F1uCxlForIDwXTgag_8vC6o0oGChh7VhtbtEOOE2o_JqipyGT7f0bwSxAbuBOTTq8DVn1f3xhjms9W6OF85m

sprite $WineBottleLg [20x20/16z] PSu52i1034JHkhV__hSjQyEG7JIFs12oxaFC11qUT7YIqdN1rSeB-98ywa095BlUOgVHEQnuNpsr9xkjAoLrhjRLJ7yvwOj6Ox4vsUTTxHpgCXG9ZHoTVW

!procedure WineBottle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/WineBottle', $name, $tech, $desc)
!endprocedure
