' definition of the Item fontawesome-6/Solid/X

sprite $XXs [7x10/16z] 9SI50SC008J0gpVA_jD6_m70ia1wiaGUOIfGTnlvnOrNtn-iEm

sprite $XSm [9x12/16z] DOk50O003CE2E_d_MgpCjmeLazdYzcsPxE4Gs6Mn2nmQjBPcqxZzXibnYc6NESBz1W

sprite $XMd [12x16/16z] JSor0SL0081GuiaP-q_xzOoAwZ6NncLpNKL3tGIw0za2hBeGb6-Nxje0TQMcPQp6_sQj68zMZ4Ch1bOYQl6kGf6fDm

sprite $XLg [15x20/16z] LOw55SKm30DLXi3jF-t7Mdwve5dIoA9adXlOMc676YQW0iNM97LOlrQ3FRqLxgmve4L_VYZO1ql2XKzJsCAgS06JAvicm7tzsFrCpg8ATtqKXsgA36Za3G

!procedure X($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/X', $name, $tech, $desc)
!endprocedure
