' definition of the Item fontawesome-6/Solid/XRay

sprite $XRayXs [10x10/16z] Ou03VZXWG2ROs1ZOs40iY2es80l2H5F708RyZ40U6r03CW

sprite $XRaySm [12x12/16z] POg50G1H24BvNIhxJtlTzsm13_YWRbss3hB4Y1YLXlF3TLVd79RQ_WahFmyL3XxxpcKFRjcDDyLkPW

sprite $XRayMd [16x16/16z] NSk50KCX30JGm-7RxRzjYTKU6iEVyVpY7tYcKZM9HwqL-znaalY-hWlxqEAUDyXrQ_m8oENz3IRcwNL6N4j1AJFY6mFeGCJC2TkIU59SGZ_yW_Jh1G

sprite $XRayLg [20x20/16z] {
ZOq50iKW34E3Ezp_jX-7FtyRrZO9Bc3oJBeWNjIW-iLXbcfDSSuPU2RCcit6738JHoqK3EenQjYGlNQP8J1O6IQxYv7ne8r3IlOQoJUPrwhb45QcqBJ4rbFB
GgXtcJw22tu
}

!procedure XRay($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/XRay', $name, $tech)
!endprocedure
