' definition of the Item simpleicons-14/C/Coggle

sprite $CoggleXs [10x10/16z] O-3Y1mD6A8ELWO41p6000IW39iRFpi30315XP-3ZPs40ir3K81GZT04

sprite $CoggleSm [12x12/16z] HOh50O1G5CEAEzb_MkG_owaIJHYNCkh3qgdCkp9lCZ3k5atuSXii0v9bAbEPp0l62m

sprite $CoggleMd [16x16/16z] PSc55O0m4C3Gu0xxRmkrOAd-Tx0VfGr0xK4u7ICfh7cv0Ytrs5v5DeS5RkK3uGdQq86WZxT3VykNg-FbHUud

sprite $CoggleLg [20x20/16z] XSu53aGX303H-IxO_K-xWZR19lwG5budCWk058rFtZe82Lge32gZDcgZjj3bPNELXUKi8M_Mquqm_PSTXDLhNRestzHSRRQoFKEonKZQlW

!procedure Coggle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/C/Coggle', $name, $tech, $desc)
!endprocedure
