' definition of the Item aws-q1-2022/Resource/Database/AmazonAuroraPostgreSqlInstance

sprite $AmazonAuroraPostgreSqlInstanceXs [10x10/16z] HKU30G1H5Ee_Q_zrpyZX1pyzoDJ8fKlEUyQvBh0yQu3y5ZsBvLqpZf43MZax

sprite $AmazonAuroraPostgreSqlInstanceSm [12x12/16z] JOY55KGn3CCKBBZxhtiCNm7hcIl7FlWa30UYKmJLdj5MmlZoywcT7z_0kVZ-kfQklV2Fs-EcdY0TxW

sprite $AmazonAuroraPostgreSqlInstanceMd [16x16/16z] TStL0GKW34FHMqYniF-wprtENpLyAdwnmRpgE29AaTG3CJ6P6Lr2KIyrWBXur7pNzbYEPps0yBEkROtNEW5UQeqrw_yvEJnbzZCQrA7F2r6Ru0W

sprite $AmazonAuroraPostgreSqlInstanceLg [20x20/16z] {
RStN0KGX20NHuPgL_jlTVJdFvm65p-hmQzqc2jnp63BsX22AqLABgTNSieM4sMBaL5FBSJ8Pcesbc5Wo5dlqj93YmrgJL9oh-JhHpSfmRrdlFTrj_Uzkorrz
l2rt6purMN_k1M4UjqBoNfel4sqPO0Ry0G
}

!procedure AmazonAuroraPostgreSqlInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/Database/AmazonAuroraPostgreSqlInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonAuroraPostgreSqlInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonAuroraPostgreSqlInstanceLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonAuroraPostgreSqlInstanceGroup($id, $name='Amazon Aurora Postgre Sql Instance', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonAuroraPostgreSqlInstanceLg>', $name, $tech)
!endprocedure
