' definition of the Item aws-q2-2023/Architecture/MediaServices/AwsElementalMediaConvert

sprite $AwsElementalMediaConvertXs [10x10/16z] TOU30G1140FNqt_5RnxYC85URI1K0HBfjNy8BaYWODT1kDSFAm

sprite $AwsElementalMediaConvertSm [12x12/16z] VSp50SG024HHPE3tN_5kt9F72Hk-j7DNWKyrKPglLtAMSP7RIHSXaLjcin5NVm

sprite $AwsElementalMediaConvertMd [16x16/16z] dOl50SC030EDklqdRiFq2PmPn3UyWYjQQjPoztdZyXxNJgzgMHlDYXFiL-6KiNyZ9-NhPkpADDOTRuwqYKVy0G

sprite $AwsElementalMediaConvertLg [20x20/16z] hSZLeSDG340nKwtz9tvORZwZYpxEiErTZdHetLGYOzYurSYfPd-VkZMp5ssRSZCxjQ7XqLpaHykgvnQcIO9oQpP7DNjh4Xk8uM7bUXTHJl0D

!procedure AwsElementalMediaConvert($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Architecture/MediaServices/AwsElementalMediaConvert', $name, $tech, $desc)
!endprocedure

!procedure AwsElementalMediaConvertCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsElementalMediaConvertLg>', 'MediaServices', $funcName, $content)
!endprocedure

!procedure AwsElementalMediaConvertGroup($id, $name='Aws Elemental Media Convert', $tech='')
  IconGroupElement($id, 'MediaServicesFamily', '<$AwsElementalMediaConvertLg>', $name, $tech)
!endprocedure
