' definition of the Item simpleicons-14/J/Jovian

sprite $JovianXs [10x10/16z] Os3WvGS1TWO61du8m60n8CHmitWPSAe3

sprite $JovianSm [12x12/16z] Os1WueS01Y3WXm9sR6msNWIRWHLP3G4sq0e6HYYRZu1w

sprite $JovianMd [16x16/16z] Os1WuEI70IO64E1701BulCmmFimiNbJrl41Cflbyp22Cu3CnyF4p8vlF0y9acGy

sprite $JovianLg [20x20/16z] Om02Ndu4O6S00mv-P00HuwI661CdXXW70mE661yZApRpQ2d61t863wfRU45SRZJtWOEBXuygzhAWYm4

!procedure Jovian($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/J/Jovian', $name, $tech, $desc)
!endprocedure
