' definition of the Item aws-20210730/Architecture/Database/AmazonRdsOnVMware

sprite $AmazonRdsOnVMwareXs [10x10/16z] FSZ50S1030F1eu1azrzlrg7v26pXXFzgjwgT1Xtr1jzecbB4DFPglCrhrKSzjIi33Swx6XS

sprite $AmazonRdsOnVMwareSm [12x12/16z] JOh50O1G5CEGfodxpyl7oQaIw8Cwu5SWxSXh7DaMHfxNoocpgg69XP6iXoaP1jP-P2dDill8jegQ8xoFLLe0xqq7VS1s5Gvs

sprite $AmazonRdsOnVMwareMd [16x16/16z] {
NOlL0GKX30GXmNP2_-q-uVpcQnMqCJRWcV0AWEGhwEQRTrkBKLpxdcOsjaj0TtAhILa_8cZW6acovID3XwnHDn-DBkKXRLu8QPXPMjuym9Hhi-LBYS3uOMZ6
HldX1UOHi35VmHS
}

sprite $AmazonRdsOnVMwareLg [20x20/16z] {
RSm75iH0209GfwgO-vztySNPJlf_401-OXNyGNnZcLcHwZ4JGzNQE6QzvcCFJwluLlRen4XOwCgspniZu0AqBj9pd1WH4xGnP-DdB_D1eq_uNcM9VSyrCTJB
69Y8J4ocjguBJEFIjjN_DfiG6ATbdEIz8xEvlU94xZZyUY5EhYyi-y47
}

!procedure AmazonRdsOnVMware($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Architecture/Database/AmazonRdsOnVMware', $name, $tech)
!endprocedure

!procedure AmazonRdsOnVMwareCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonRdsOnVMwareLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonRdsOnVMwareGroup($id, $name='Amazon Rds On V Mware', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonRdsOnVMwareLg>', $name, $tech)
!endprocedure
