' definition of the Item fontawesome/Solid/BookReader

sprite $BookReaderXs [10x10/16z] Om02Vdv-88d9GWQCG0561dP-EE02YK1LOM6ny3F0bG8

sprite $BookReaderSm [12x12/16z] TSn50e100810x9R_lzPkT-V42LOgXrvDZ-xKX8DsV5Ig3ODFEQwEoz74EXzKXj7TsCy

sprite $BookReaderMd [16x16/16z] bOwr0S1030FzZBBsdpRCgVuwWq0sGDB93LVkqLtpuwwFsL_d7nszxDQXTKHmGoD_mCj-lTmViupFlZKo7ND__8Lzs6hD

sprite $BookReaderLg [20x20/16z] jS-r0SKm54DHXHEJzf_sWvcxdCg-bHwSXNye6DkEej5IdIQA9crRK50aJymiI_aDmwWN01SjmqYnJ-pBKeG7VqK3NcZhVkK3SOSts52mriSUU2pu-m8

!procedure BookReader($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/BookReader', $name, $tech, $desc)
!endprocedure
