' definition of the Item fontawesome/Solid/CalendarDays

sprite $CalendarDaysXs [8x10/16z] Os3WOM1WO0PYVWO69du6BduSW8k17mJXW1l6v-1d0qAO3

sprite $CalendarDaysSm [10x12/16z] VOh50O100CE2Uxl_jBZ3NUML01qWWCB0-dXqp5YuVlhziPFs9wFJbce2

sprite $CalendarDaysMd [14x16/16z] dOsr0G0n548vjm_iF-svfyl3cWXMYASHFhfOkmcR4NkZSIuzv0x7skN-XVPTqPFaNgar-oRt54_WD_Ym

sprite $CalendarDaysLg [17x20/16z] jOr50aD124CPLoRtlst9hjv-UmkSH8oiGXmO2U2P5FrvC9WM7iWTbx3eEncgE1ZAkZDa2oH62o416je6KMKe3Ez4Ss6e30qeU48K3oHvvWO

!procedure CalendarDays($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/CalendarDays', $name, $tech, $desc)
!endprocedure
