' definition of the Item fontawesome/Solid/Comments

sprite $CommentsXs [11x10/16z] Os3W1m86802nO6nEVZYR3yf4A63bveSnGHGxFmkG0JU62Q6S0yf4Q0K

sprite $CommentsSm [13x12/16z] JOs54S0m58MeUzb_srmydF7rWP6PIFJ857ss40l7ucx5sqSlsWg--4L_FJXKbta8w1gBuUK7aITN0G

sprite $CommentsMd [17x16/16z] NS_50GGX5C3GZ3lflzfL_DtWEsp-R4IhjZzcNOAkNO8FNu_PpGWCPZFQDfrK24OnXdyXjGlUC0paLFw6quX-U7_0nTzkD15DHcy

sprite $CommentsLg [22x20/16z] {
RP250O10482mM_QVrcwFRxuF63tWWJV99NiVH4krEcIZmM93EuQsUicHpEPtH46d0ktxWAEfNh9sfU5s0sJkh4lpjMgvfQqL77I_dwTr50-Dx6jfJRGO8fro
Krrsd04
}

!procedure Comments($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Comments', $name, $tech, $desc)
!endprocedure
