' definition of the Item fontawesome/Solid/CompassDrafting

sprite $CompassDraftingXs [10x10/16z] BSR50GD100IWYUUK_gjTvqKwMLXzozh96W-za2tqllEZvy8tzvjqhEId0W

sprite $CompassDraftingSm [12x12/16z] FSR50SCm002nAtEr_xI59BPUwk-euOvQaMUhjwTJAt-piLldsAjeX-f1NQqU5U_QLIylwcyFvrOlNm

sprite $CompassDraftingMd [16x16/16z] JSw54S0m3C10bJdQVzjUE7zeDjdboa3rw-5bMBJ7ZnCwKQtwAer6Tmtt6AX4sutwOOo_sWlB37g1wb6ssfPzzQN5AipbLe1fck8XtrEbE3LwgCfRNV07

sprite $CompassDraftingLg [20x20/16z] {
NT3LeOKm40N0WmI7wR_QvxAvynTPpQ_JcjuCqW7E51D33bv2aurKkBXJN81oDU3ryeO1nf_qRO8f5sjowLBjIJ0cDT7mSEK3F7EIbP-hMxNyzk4kDq_ou4ao
34C-ZBGPXhB57tLCFrAiO4zdkBq3
}

!procedure CompassDrafting($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/CompassDrafting', $name, $tech, $desc)
!endprocedure
