' definition of the Item fontawesome/Solid/Ellipsis

sprite $EllipsisXs [8x10/16z] Oo04-268dv-1cvyHIB8nG10E

sprite $EllipsisSm [10x12/16z] Oo0Ty7CnSF03AH00aZn0pC37oC30ny30paki8G

sprite $EllipsisMd [14x16/16z] jOU50O104CE2Ezb_MdWTuUeb0iC8CDLOz0GLh63g3rr0RxYL0Fm

sprite $EllipsisLg [17x20/16z] pOg74G0X3CFqlOBstvRpCGGeFJQpyFi2kmBeyQXRDYiKEoTh1gHdNSZwm1CV9-5OqzU3GJG

!procedure Ellipsis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Ellipsis', $name, $tech, $desc)
!endprocedure
