' definition of the Item fontawesome/Solid/HeadSideCoughSlash

sprite $HeadSideCoughSlashXs [11x10/16z] DSQt0SD0000XRELu-s-hwgdmt81KGJzL5_sfjpIXL3DKjHZTZEviJEeGFtJfWVC3

sprite $HeadSideCoughSlashSm [13x12/16z] HOc53GH13CJcbddwx_P3qdiXjeBvCWA2mkUUB6XUv4MnmW9w6poIl0uBO-4VMwrQk1CMHoGjh2pny1WRymnXbHy

sprite $HeadSideCoughSlashMd [17x16/16z] FSk54SGm4CLGXJdglze3Us5GR_Op-epKlVAgJj6FOmVNrfSp0G8SpGDUsDq865GsTm8UTZqyIR3DRXBwFQs63jMOy6OczFUp9Y0ur0IKclI-00ucw2tzv0i

sprite $HeadSideCoughSlashLg [22x20/16z] {
PSo53GGn44FHlynn_zsUHh5yvCMy0NXqptncaPXLERvmj4gsEWz45PpuqAjmh75hcgVgZBOcwM0mMg7UepJpfqPhiX3zm-5BL_T97xfrsvZI6rm4HFVUk39m
JAN61gY_h0T8L8PiA7oiS_I29ZquEg7LwocCNhm
}

!procedure HeadSideCoughSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/HeadSideCoughSlash', $name, $tech, $desc)
!endprocedure
