' definition of the Item fontawesome/Solid/Jedi

sprite $JediXs [11x10/16z] JOk54O0030CVTtx_RSdbZ7eZ_CFEAKjx3axemK2MxO55vvuZNRgGzVfctMWjPE-iIi86V

sprite $JediSm [13x12/16z] LKs50GGn2AFkpVxJLiBB7SIgoBiyr6dG1HrNB1TP5qwat10el67q98cq6xXG3eOCXEjt4VFqChdmPpLi_uy3c3S

sprite $JediMd [17x16/16z] {
HOs50GKX5CDohf3zf_rIJe8-QxdeU9cz4oOUBC2KXBcJc9_lQl9BIvZB3bPWLxTq21kChLPRukXOL2kgAvmT-KekhEV6O6nKXbCt-iHKXIN2BQ6Ud2wHsu3s
kiIFu4tbOZFq05y
}

sprite $JediLg [22x20/16z] {
JOy75iCm348LxytzRzkd8ZsRDY5yBonNdUOA-DlHLpa68qZXWScffKLxwGSWqXvQ6OTQ_y_obVXaqaav1y56GPgXIWudgITplqjqQgUXe4oRtEXP97750N2i
Tv4DLLMwlU5YVKtMFh7lwiYRVKKr-TKWKZZZuZwG5YzcghWozF9j4ty
}

!procedure Jedi($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Jedi', $name, $tech, $desc)
!endprocedure
