' definition of the Item fontawesome/Solid/ListAlt

sprite $ListAltXs [10x10/16z] Oy02kFYn0GO-Vg0ScXWxI8m3IOGP8GS7

sprite $ListAltSm [12x12/16z] Oy05-741Fg0KN04JFpyN5nStNZMC_FoSG82g0jbyP6i1

sprite $ListAltMd [16x16/16z] Oo04M7cG0GCRFq70omWak400mcTcuE5d0fl52n7Wmw-VZmb8S0C13q8_8x9-NZoQ6T3v1

sprite $ListAltLg [20x20/16z] fS750GCm40InDREd_sf3zmgJf7yiRgNE5oPtf0eo3IDjoBhWIxjnHoeWKp5E2vAxs7mkS4zntHZwr14

!procedure ListAlt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/ListAlt', $name, $tech, $desc)
!endprocedure
