' definition of the Item fontawesome/Solid/LongArrowUp

sprite $LongArrowUpXs [6x10/16z] Os3Wv6TWO63dv-TdOEPdu6S6yVWPcC0a0tuI

sprite $LongArrowUpSm [7x12/16z] Os1WuETd095002Qv-Vdv-1dukHc0N135G385

sprite $LongArrowUpMd [9x16/16z] hSP50S0m0C30Z7dnhxPS1xtN0PUIRLesQvrE_gV-plZp2kGmzJ0y4G

sprite $LongArrowUpLg [12x20/16z] pOY50O0m4CI2Ezb_MwYlqBpbdfz39R4PQ9h2egzU8KnXwHxkgmGFJtQICowGFT2PVm

!procedure LongArrowUp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/LongArrowUp', $name, $tech, $desc)
!endprocedure
