' definition of the Item fontawesome/Solid/MagnifyingGlassArrowRight

sprite $MagnifyingGlassArrowRightXs [10x10/16z] JOgr0S1008I8volsd_RTg4u0NXyg5cOeyLLFIj8B20OUMz-y6GyA0OuUAJ41

sprite $MagnifyingGlassArrowRightSm [12x12/16z] HSq30W0m2030sVZ_QuTuCohpz1qDsi31bl0Ufl_tQGRszEh-4hTUmTS2_-0LL2dGAXn8XL-axGi

sprite $MagnifyingGlassArrowRightMd [16x16/16z] TSw50SGm2010QEEw_xGnvBKNLu0jz6P1jNu485qKEHMt7byqdAzuncjzjsT8puqn24XhsxTCz_K_Xxjlb9k28tzlt9qkdms2o5-1UjYO

sprite $MagnifyingGlassArrowRightLg [20x20/16z] {
RO-55SGW50GNT-Y_sWYsd4oKUL_HiQLbWvFK1e6g4L0H9X8FXbM0WNO6I62xqXwirdgckFbL68GvJtvbV01aJm5WE0I7MKuskj1Ex9yz5Fv8CQLVYOgH3ovO
F0X64aQI7ea_aJS
}

!procedure MagnifyingGlassArrowRight($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/MagnifyingGlassArrowRight', $name, $tech, $desc)
!endprocedure
