' definition of the Item fontawesome/Solid/MarsStrokeUp

sprite $MarsStrokeUpXs [7x10/16z] NOd50S0W54FJulhsdnQzyIKgHT0QI9V3TRH50JwfOIDEjtvfCNa2

sprite $MarsStrokeUpSm [9x12/16z] HKk30G0n4CiRHVQVjZex042oGZPvOuO00gtZKMQVYEpzcfTP8Re_Zg0EyfZY3W

sprite $MarsStrokeUpMd [12x16/16z] NOs50S1030AfE-o_RMFLUua763BeZhjFmFLGonc9-UKjSfhmk_2HjDAAzvwzt06hT02RVPdAvmmwRj-Sdvygg-qTif264krfn0a

sprite $MarsStrokeUpLg [15x20/16z] {
RSw53SDG34LHvuVnx3zjoQg2LsXu41ygi4LII79i6LY8f4HBb2h-TEo3f3sFzVDp0MiaC_Rl1KDLhyY6-LOGiRTfAS6uvuz1sSSv6FPnYerzhAEbpoaFc3Cm
zq1ktm
}

!procedure MarsStrokeUp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/MarsStrokeUp', $name, $tech, $desc)
!endprocedure
