' definition of the Item fontawesome/Solid/MosquitoNet

sprite $MosquitoNetXs [12x10/16z] NOo30S105CLUxMR_QS_EDpM0Vb5oslnC-OddT1c5l-Hwf1MOUEMAyiVXy-Im

sprite $MosquitoNetSm [15x12/16z] PSsr0SDG0CHGsVvCsd_QCETLf-hurmJmrPBPFdC6FbAdcPiqlLjpX-M70r-AhLDkmo4F6suETlTLk9AwCLK1vdg-7sS

sprite $MosquitoNetMd [20x16/16z] {
NSo50SGm3C101SgW_QTzSBaNZe6Gs6HEsUsno6KL9DbocOHjNfGYs7FfNMQBSjVvbs7J-WHats3n3Nh_jds5ZMfodSqBZ34X9J3D9kZCdOLGfRzw4vHG_C-G
PTDQU-iN
}

sprite $MosquitoNetLg [25x20/16z] {
RSm5Ok0W503HmQAGkVzfTzl6vU5yOHNWl5svi8fMhge3j0GQuKh1_2e0sry0XQli2DPt8EfO59Mxe8jgvIhrrSFSnQFBImFmomB9JsUWkgem3PojniMgpSeX
gfR1MfG9ck34hn1WD1HTy-BlOjCCMQ6uOPLS88M_cpbhOgNizFfqP3FfDEdu7m
}

!procedure MosquitoNet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/MosquitoNet', $name, $tech, $desc)
!endprocedure
