' definition of the Item fontawesome/Solid/SquareRootAlt

sprite $SquareRootAltXs [11x10/16z] NSh55O104C3Gu4xwxvQNAtzbb3z31adUXqJoAdJfkpTXiYMTmTVIles9SiW7

sprite $SquareRootAltSm [13x12/16z] NS650G81000XxFRsdzRs2s2f3rzTttpSCkhcOmNvkDVM9ceVjnJgYYuTs5Gu5Re9oiJUrnC

sprite $SquareRootAltMd [17x16/16z] TSx50KKX30NHUMwGwR_QhtVBmJLXQAgV1c4GXyVyDH5A33SUece5kXEqxwJKEIyKPPer6xVQW7BTF9CBNrh-n-my6IswV6LZIeFJbQ4t

sprite $SquareRootAltLg [22x20/16z] {
XOy50e0m2031BhZ_lzR0xjDjTCWlcYua1sF1ni7AarL1vKO5SiSnkGFvtPWU2sH0DGbTMDlfCdU0CWfqSICEKjK6eMlKcMXa2IjXBO-5r81w58ZoSDWrcoG3
Nyq58It5icDm25fEjPTr4cZbZY7_3
}

!procedure SquareRootAlt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/SquareRootAlt', $name, $tech, $desc)
!endprocedure
