' definition of the Item fontawesome/Solid/Stethoscope

sprite $StethoscopeXs [11x10/16z] DOo50S0m40AfI-JsdpREkm2waGZg1YF7k0gdHm8UXxSvqs9mm9mlo-Dc4KidLG

sprite $StethoscopeSm [13x12/16z] LSw50G8130J1mPtjlrhqDUuvc-xq02g76f8Bj5abnsfAUcZOJHro3aM3APo2NHTJeWFSXYIMA7RxuWq

sprite $StethoscopeMd [17x16/16z] RSd5eLi10C0m9NbCtd_QzZFxA7EriNLvwwoeUeEhEzo_052C-_0DZkhy2dMhRx1Ri_Q0eKDTHK4nLHDRLHqO6dYJrITG_0bp3-3eyMsu5QpbhRskgy9_

sprite $StethoscopeLg [22x20/16z] {
VSy5TiGm40JHDhF__KyRq9jmTiiMbLgKp5n9DevyqiEGy5sFaEJ4_TrMxvd5-DjsOFvbSU2tjIHa-6MFbkiOorgoevsgmZUjHf8EnxXXJPAZGXFWRAFjyoqx
pZw_x8FkGehJbQAZgov7Kg2EgFdFUzIbQuFA5EsiLm
}

!procedure Stethoscope($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Stethoscope', $name, $tech, $desc)
!endprocedure
