' definition of the Item fontawesome/Solid/Synagogue

sprite $SynagogueXs [11x10/16z] NOQ30S1000DJkxV_j6-7fqPG_lyrk_E_xx1_lFikd3I7fMX4AUDVaVlsQm4

sprite $SynagogueSm [13x12/16z] Oq01_FpCC0O_20CPV10E4B3m0m4ZM1O4e1IKP85n402JmuUiXuc1WGyR1m4

sprite $SynagogueMd [17x16/16z] bOm34iG00CHog97_lxQscz7EYXsvJlgdVzG4-BI6AceAXKQ3qVAnfHm-6bI-QgknXqdO4sORG--CNxGsW61hyDAOY6e

sprite $SynagogueLg [22x20/16z] fSZ50KGn481Glcj2_ztkpBhTycx0VxsMhpx1iFDYM34HTiV7FQW9UaC5QZYuMRqPkPcJOQQeP-Q83z1vTxpV_i-jXpytDTuT-Bs4uVjMKijr3uSt6wE_k

!procedure Synagogue($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Synagogue', $name, $tech, $desc)
!endprocedure
