' definition of the Item fontawesome/Solid/Temperature3

sprite $Temperature3Xs [6x10/16z] Os1Wu6S04Vpy2981JZA1INuW2UVoWDZSG9MC

sprite $Temperature3Sm [7x12/16z] PSkd0S0m4C10FKfSjV-qhj3eq07r1r3xnKsvH7tGA8eLDkLYRdPkdm

sprite $Temperature3Md [9x16/16z] VOp50K0X34F3LxpxJri_yv1g0cKDEAHOt9OysQ3koRyomNjA9j0zeQADQjqDTxtrz-JpPAEOzKL6jYqA

sprite $Temperature3Lg [12x20/16z] bKx50O0m40jGj-m_RTs-LCyYQCjJOQoF9DE8sPUxudJ5d74K9_xm8twlc3EEpGlvmFQtFu0ZtOKAArQj7bjXChpaCUTd-CpHpeu2

!procedure Temperature3($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Temperature3', $name, $tech, $desc)
!endprocedure
