' definition of the Item aws-q2-2022/Architecture/SecurityIdentityCompliance/AwsCloudHsm

sprite $AwsCloudHsmXs [10x10/16z] FSQ50S0m449Hwlra_tdZf_3eyu_vdFIYbgwFfLVljTIFaxzup2qeaw9haQjhqJG

sprite $AwsCloudHsmSm [12x12/16z] JOS14W0G3CCEw5h_Voy0mhQ40vj0NqXqtdMcPn3zJtVmPc6va90TEDmZY0ca5GcISY9PYhpt0grxZq4q6xu2orU83G

sprite $AwsCloudHsmMd [16x16/16z] {
NSW75WGX20DGXISftl-ysnYtnG8_wh03-A-m6oUsjG1KrRnSa9ulsWAKOXoRIDMaGcqZg2H3UXbGMKCfYTiEsBaYdzRUDYovvcflau0diDhRdS5idoB6vLFu
-5FS0G
}

sprite $AwsCloudHsmLg [20x20/16z] {
RSm7aWKX24LHoJnw__iTiOPsmhzbfIE0xtAA27p0-e3LA9CThCQOoJMMjYqzW6kAW0c2WDUC0neidjSAuRdWMnVQ3aK6EsLY0U-zeWAuN-DpxXM4sOaJZS_6
Ykf8VQ5x6aLtnQnZZITV11eRhEIaiHUn9CSk9iOkrjWV_08
}

!procedure AwsCloudHsm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Architecture/SecurityIdentityCompliance/AwsCloudHsm', $name, $tech)
!endprocedure

!procedure AwsCloudHsmCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsCloudHsmLg>', 'SecurityIdentityCompliance', $funcName, $content)
!endprocedure

!procedure AwsCloudHsmGroup($id, $name='Aws Cloud Hsm', $tech='')
  IconGroupElement($id, 'SecurityIdentityComplianceFamily', '<$AwsCloudHsmLg>', $name, $tech)
!endprocedure
