@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-7/bootstrap')

' loads the Item which embeds the element Manjaro
include('simpleicons-7/M/Manjaro')

' renders the element
Manjaro('Manjaro', 'Manjaro', 'an optional tech label')
@enduml