' definition of the Item simpleicons-7/M/Mediafire

sprite $MediafireXs [10x10/16z] XS710K1G00MW1m2q_xHmXbyfQp0a6-nadkYJIB9W9BSDJLwS

sprite $MediafireSm [12x12/16z] ZSYr0S0m0CH0XJdQVrfZ6_0r3pJhrO5a6i7aWi5QRhbcTIQHv5Bx_6UhsKdLxnkl8W

sprite $MediafireMd [16x16/16z] hSd50S10449HufxVVxNhSetikym0QgI_WLNLWUUN3USaSfdo2iIwuipoRkGDE5tSdNwdKDINM6p7rkar2m

sprite $MediafireLg [20x20/16z] lSwt0G9150DHhVUh_hj57sz2u5uuqU1GVb8wdWKrKo1kx3sRH-H5X2pUx4e1mYC504DjzzneCc0ywM0SPJX89m4pU54pvMNk8k1kVIO9VMZpzqu

!procedure Mediafire($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Mediafire', $name, $tech, $desc)
!endprocedure
