' definition of the Item simpleicons-7/M/Microsoftonenote

sprite $MicrosoftonenoteXs [10x10/16z] Oq06_100P751161SDZP-FWOEY0G_7n-G1PRZusS0Yy7L8VHo8Pa7

sprite $MicrosoftonenoteSm [12x12/16z] LKo30G0m39kD_w-TLxj91BVKdwsvl9kqERUSxzoxwl9y3wgACw_xxdXFU6-zdbaQeLHLQi_AFls3MLMtPnC

sprite $MicrosoftonenoteMd [16x16/16z] RSu50iCW38NXOBE4lFlVTelDsh_wLG0wgUidiwnUXHjLkfXPXRaCg481mrq4TeTsTSiWDT_BpVsWCYpYGUdPr0npVH-5HK2zzprxZ-z_rcTND-y8hvt-UW8

sprite $MicrosoftonenoteLg [20x20/16z] {
TS-55O0m303HKFVilorrxs5v7uTdT2cJnQLipi3KrRYDXH1tmxQdC254d0CeLD2UZDvdWyaCG35-Me1X4RBX1zsyriK2xFTIH4aNs_uoJoJcBI5ViJXj_vkd
PbyjJSKCBi6b7m
}

!procedure Microsoftonenote($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Microsoftonenote', $name, $tech)
!endprocedure
