' definition of the Item simpleicons-7/M/Microsoftacademic

sprite $MicrosoftacademicXs [10x10/16z] Oq05_0py_106680OC1Q80BDO-LaWJ3O8PWJpME4wk41ik87yd0m

sprite $MicrosoftacademicSm [12x12/16z] DOg53SH040Fz7qwidVwh3LYt8p2gsTgiEXZ1p41iyGCIY8q7-BSNiCL3FalwlqUm3DxPA1HEruRLBCka1m

sprite $MicrosoftacademicMd [16x16/16z] {
LOl50K0n2CMe6oNxJ_jTStiI-L3anw3AZKSBuAuOmG5mndp7qnXFX2rEe8qtAy2iTmRfXtfc01F0nf7J14WAtQ28qE84RU1tVHYG5MkO8WV1oBiVizmaAsfH
lkIovHK
}

sprite $MicrosoftacademicLg [20x20/16z] {
PSg5ZTXG00N1vqynJ__L9Zaow4QyshpzoI-xDKzg5ZpFqp50BfXunl98fiyqdicU93EEwf9a0sUURPg1wMwTD110EcnPxtCVWD6kM9FK3VRWM904hSE4WcGz
OEad4-UivylArYb4BjDitbHjorFLpKl9szJdESa_
}

!procedure Microsoftacademic($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/M/Microsoftacademic', $name, $tech)
!endprocedure
