@startuml
sprite $MaterialsFormatSizeLg [20x20/16z] hOpL0G0n24Enkh3_jEUrx-kh0adWFsHD0rjFj56fzTWv5xJuwtbxhQ-frIWF35GJhb5nxd6CHLFqRw-1GGLWVq-d7bZ7Ty_PrjlB2G

sprite $MaterialsFormatSizeMd [14x14/16z] XOZL0S1G20EJvmRiFsrTVYg7Nl27Jod5bC9kgNVLtjDk94jT5i2q49dBbhiwh9VJW20UABUvL_DjiPHnm7M87sO

!procedure MaterialsFormatSize($id, $name="Format Size", $tech="")
  CloudElement($id, 'materials/Editor/MaterialsFormatSize', $name, $tech)
!endprocedure
!procedure MaterialsFormatSizeCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsFormatSizeMd>', 'Format Size', $funcName, $content)
!endprocedure
@enduml
