@startuml
sprite $MaterialsMonetizationOnLg [20x20/16z] {
VP1LWiKm202nf3IXE_U_xPPrVVoWWya3KJFz7eZSLJlZCsm9o_s4jFVG0WwH2Inx1HEgAHqNv0iUm12Rq-G0ecC9UBjf0yX6DvtqBEe2zWrR6yjlO_GiBdkB
KTErftNiZQs27U9lRCzuYjxn52l8RxjucyItdSLNx_pdRRz_yFjNlt_wG9u1
}

!function MaterialsMonetizationOn($id, $name="Monetization On", $tech="")
  CloudElement($id, 'materials/Editor/MaterialsMonetizationOn', $name, $tech)
!endfunction
!function MaterialsMonetizationOnCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsMonetizationOnLg>', 'Monetization On', $funcName, $content)
!endfunction
@enduml
