@startuml
sprite $MaterialsFormatAlignJustifyLg [20x20/16z] Oo0QCBAW04QG60iFDnBWOO4eH04CsCKmzMAr0mTWva01pDZ4Xe8_C04

sprite $MaterialsFormatAlignJustifyMd [14x14/16z] Oq03J700v32oSq01EoE82mTeSXZwM5YXW8KHbKST6z

!procedure MaterialsFormatAlignJustify($id, $name="Format Align Justify", $tech="")
  CloudElement($id, 'materials/Editor/MaterialsFormatAlignJustify', $name, $tech)
!endprocedure
!procedure MaterialsFormatAlignJustifyCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsFormatAlignJustifyMd>', 'Format Align Justify', $funcName, $content)
!endprocedure
@enduml
