' definition of the Item simpleicons-8/S/Sepa

sprite $SepaXs [10x10/16z] Oo0IyF3piJ1py0C18n2pCV02ILP-7WP-e1mh8twz

sprite $SepaSm [12x12/16z] fS450G0X0C30lUAiVrig87SSw8yqxbflswLF-D5oMHH_4dwTHGC

sprite $SepaMd [16x16/16z] jOS50GD10CFoUDpuLpkqi9NBdx4d3H8qHAoqq_j6l5p7fXxZ_UF8QVeX0XvRZDnbX-kYyDMFyGG

sprite $SepaLg [20x20/16z] pOI90O0028HG-pFPVziQepk0Foqp-LP1rPUiejLXiSv3DLHcOitJxaPmTpD2jTosmaTlyUYBq_HCyBhsHvrLRL0HS2NaHti1

!procedure Sepa($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/Sepa', $name, $tech, $desc)
!endprocedure
