' definition of the Item simpleicons-8/S/Sonar

sprite $SonarXs [10x10/16z] JSR50G0X00InmPtjlzfp8Q-mqkaEY0Jn7CPcT4u6a4xptL0bwbIc1bDILFC0JhLbs04

sprite $SonarSm [12x12/16z] LSc50S0W40J1nPthlzgu3hp3dtRfQlU8-MWTJ4AAM0aWI1r90-GrB3gXoTtdAf_jjTuFsWNrQIqqLJJ3zEniOnHW1G

sprite $SonarMd [16x16/16z] {
ROz9aWCW30F5Je5n__-rCmakRkcJTqlwYGFOopPOEXZZfWP5Seek3LmId-XKIH1pLJx4pKrIGfIEEa1L0P6tQ_9erEEgaHplRdkv5FaTfx1Vcfo4J6zvKTnc
oEF861Cb1GjAvsOF3pF_
}

sprite $SonarLg [20x20/16z] {
TSi5aWKn30DHsHa8z_rF-zcPnLVS9Ub_LdcehWjB50UQPE3CzFwzanfJElKI5ufyxngIZcXLpRgNV4f4Kvv2QEfgEyDuLUF5hK8zebtI_D7wXZvliGmdLuHf
4ZGHm_l1ueNff64QaVRjlUnIV7M0DRQi9yiboGROJjMIWAf6rWyvwUqE
}

!procedure Sonar($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/Sonar', $name, $tech, $desc)
!endprocedure
