' definition of the Item simpleicons-8/S/Ssrn

sprite $SsrnXs [10x10/16z] Oy0FU9av6Tc0D1C7XCyFnEoyZFmyB8py3DmCh20nHg0eNW

sprite $SsrnSm [12x12/16z] bSG70GCn0CF0--mT_cWx6BIs97-lD3UEHIrig0lFDUVQMJCWKhyTjTOqj4Vomzu

sprite $SsrnMd [16x16/16z] hSC50SCm443H5suREFzg1ngs3_xD6BEqMU_Pa9-1xbi4PjgS8d6Uu6OVBSeAZt0d4WxxuTo3_ftwEOMSAKec9ueVUGC

sprite $SsrnLg [20x20/16z] nS470GD1202mm8_RnR_RolZ4L_AiozXnlQ-4Z0nEvvciEM3rm437h8QXPbWx3UuhzasdrH6_6ljt2nKwB9XK1AKlF31n0ZLovVsSpBuRVI2cZ_m1

!procedure Ssrn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/Ssrn', $name, $tech, $desc)
!endprocedure
