@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureCitrixVirtualDesktopsEssentials element
include('elements/azure/ComputeServiceColor/AzureCitrixVirtualDesktopsEssentials')
AzureCitrixVirtualDesktopsEssentials('element', 'Citrix Virtual Desktops Essentials', 'an optional tech field')
@enduml
