@startuml
sprite $MaterialsTextsmsLg [20x20/16z] fSY54KD120L0O3Y_H_glDlRTRSUNLh5CyA-YOSJYDmMl2SZtR7fsyP86E8UWQRX0MfchKXYkn6mnMevbkC6pGtD88uv-LvL7w7TLQKwKxle

sprite $MaterialsTextsmsMd [14x14/16z] TOk30G1H34FpZMh_QS_6gn7S2UKW0CKEoiSaAfDl4uMQKWsqJfnQAItnf-vxojCaAMwuQOguuF7B2

!procedure MaterialsTextsms($id, $name="Textsms", $tech="")
  CloudElement($id, 'materials/Communication/MaterialsTextsms', $name, $tech)
!endprocedure
!procedure MaterialsTextsmsCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsTextsmsMd>', 'Textsms', $funcName, $content)
!endprocedure
@enduml
