@startuml
sprite $MaterialsNoSimLg [20x20/16z] bSZ50K8150EmFiVPVrgiVFSSWuFClmoa2Y0Upv_WnTMWjoSLA3_fz-79-QfDDeTwCeV771rpTCpHCOV771vJXySS7DEQ2yOmpVyiBue95ynw0m

sprite $MaterialsNoSimMd [14x14/16z] RSV50S0m30D0oodZ_jjM3OFlTs9GWX1KiDwq-MqE-qi7_khXTC_3SR9bhs-URvxlMiRw-FcAjztU4GeD5lWM7m

!function MaterialsNoSim($id, $name="No Sim", $tech="")
  CloudElement($id, 'materials/Communication/MaterialsNoSim', $name, $tech)
!endfunction
!function MaterialsNoSimCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsNoSimMd>', 'No Sim', $funcName, $content)
!endfunction
@enduml
