@startuml
sprite $MaterialsCallMissedLg [20x20/16z] lSY50K0X24LHiDlzfxNUpmMu9eTaujEFTDubeFRdDRq7Omme1rZBMTEFo6GTW20OyqRGOxGHX5ZlAvG2Uje8-YD8gWa

sprite $MaterialsCallMissedMd [14x14/16z] fST50W0X241Hkxt_TOTcFtu3NlXR7532fS2NxYc4KL6pzIW0ZLX758G8emw0Lm4lVG

!function MaterialsCallMissed($id, $name="Call Missed", $tech="")
  CloudElement($id, 'materials/Communication/MaterialsCallMissed', $name, $tech)
!endfunction
!function MaterialsCallMissedCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCallMissedMd>', 'Call Missed', $funcName, $content)
!endfunction
@enduml
