' definition of the Item material-4/Navigation/ArrowForwardIos

sprite $ArrowForwardIosXs [10x10/16z] Oq06d70MFpz19c460oE40W

sprite $ArrowForwardIosSm [12x12/16z] Oq03h0Wc9pyxWiEDpE7Xvy31uUTd9CHaWZ4v44m4

sprite $ArrowForwardIosMd [16x16/16z] Oo02CFApe_1P-8aGuC0lm8mkmCFFpuZ4vURdPqBcufNbGkLoGhW8m0VZOW8

sprite $ArrowForwardIosLg [20x20/16z] Oo09SB9Z277mysC8Cl9Z4-IZaqfse4f6L24sAWin4LJ5m0mImd0l8w4G1W

!procedure ArrowForwardIos($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Navigation/ArrowForwardIos', $name, $tech)
!endprocedure
