' definition of the Item material-4/Navigation/ArrowForward

sprite $ArrowForwardXs [10x10/16z] Oy05-E4i9WIJ4Spa1mDUg1WN7pg3WHVLA

sprite $ArrowForwardSm [12x12/16z] Oy0Bs97O_BWv722IXny2617YJ0IO38mODW8

sprite $ArrowForwardMd [16x16/16z] Oo0FCFAX2V3p4Yt0107CC05-E617Li_2pu67ouefYm8WNC8

sprite $ArrowForwardLg [20x20/16z] Ow0AOCGKukHdmX1ZviSYoCHFh4f6X20J1mnmmmLP-P40BqmF373nyw2RnyNFX-5gSbKnCF5I9IG1

!procedure ArrowForward($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Navigation/ArrowForward', $name, $tech)
!endprocedure
