' definition of the Item material-4/Navigation/FirstPage

sprite $FirstPageXs [10x10/16z] uwS3

sprite $FirstPageSm [12x12/16z] unza

sprite $FirstPageMd [16x16/16z] un_X

sprite $FirstPageLg [20x20/16z] unzKO1G

!procedure FirstPage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Navigation/FirstPage', $name, $tech)
!endprocedure
