' definition of the Item material-4/Navigation/MoreVert

sprite $MoreVertXs [10x10/16z] Oy05-B6mc60CPdx2EX

sprite $MoreVertSm [12x12/16z] Oy0Bk15C7duc18UP0Ka2mUH5LiD4WZa8

sprite $MoreVertMd [16x16/16z] Oo0FSFEpeF3v-NbG-Amy-FNp4DBFIrFx4G

sprite $MoreVertLg [20x20/16z] Ow06O6J15EFdvq4NOkBdvyTGnylFHfmbJDZiu4ONOiPc1my_6ttyGJa

!procedure MoreVert($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Navigation/MoreVert', $name, $tech, $desc)
!endprocedure
