' definition of the Item material-4/Navigation/MoreVert

sprite $MoreVertXs [10x10/16z] uwS3

sprite $MoreVertSm [12x12/16z] unza

sprite $MoreVertMd [16x16/16z] un_X

sprite $MoreVertLg [20x20/16z] unzKO1G

!procedure MoreVert($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Navigation/MoreVert', $name, $tech)
!endprocedure
