' definition of the Item azure-19/Item/Intune/ServiceSecurityBaselines

sprite $ServiceSecurityBaselinesXs [10x10/16z] HSQ73G0W2011EedxxskZlG874wg8ujEzglQa3oapywTxrm_Gd7u0LBgD-Ei

sprite $ServiceSecurityBaselinesSm [12x12/16z] LST50G0m4CJ0BHpwzrl6l2Ru2harsK2jSKF4mqEypIsPPZQV0Imfpe0eYRJNZ93OUjs8QJIzgW

sprite $ServiceSecurityBaselinesMd [16x16/16z] TSg53S1034DH7yF-0xVXuXVboS57hTOMQFKa9JQrBdQgJMPJ7-OkDDEzFO36wW6fZrQog6G0cLmaCb8RPN6JJ2-U-7y_

sprite $ServiceSecurityBaselinesLg [20x20/16z] {
TSy53WD128NXibYwzpzm1ykZziU_ZC3ZNwAYl86Ed5I5XYJJQWnYOoew11k9nY0mY8z1tBMD4-wLduDXZk8qXLohMESAk_dPXGL-dOlhN-VYA88vMmVZ7-TM
z08
}

!procedure ServiceSecurityBaselines($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Intune/ServiceSecurityBaselines', $name, $tech, $desc)
!endprocedure

!procedure ServiceSecurityBaselinesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceSecurityBaselinesLg>', 'Intune', $funcName, $content)
!endprocedure

!procedure ServiceSecurityBaselinesGroup($id, $name='Service Security Baselines', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceSecurityBaselinesLg>', $name, $tech)
!endprocedure
