@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceImageTemplates
include('azure-20/Item/Compute/ServiceImageTemplates')

' renders the element
ServiceImageTemplates('ServiceImageTemplates', 'Service Image Templates', 'an optional tech label', 'an optional description')
@enduml