@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element Menu
include('material-4/Navigation/Menu')

' renders the element
Menu('Menu', 'Menu', 'an optional tech label', 'an optional description')
@enduml