' definition of the Item aws-q2-2022/Resource/ApplicationIntegration/AmazonEventBridgeSchemaRegistry

sprite $AmazonEventBridgeSchemaRegistryXs [10x10/16z] LKg50O0m30l3oV__ijMzCVJYt37V1ZxWHDSaxqJ5fTSanEhfdfbpRSpYtEC7

sprite $AmazonEventBridgeSchemaRegistrySm [12x12/16z] NOi10W0G3083eF__rm3iW5NXnHc1_QemO0HHA-HV-WYW_trWrql_Tsdfl8YUk-wyxcQahblLhHsEgm4

sprite $AmazonEventBridgeSchemaRegistryMd [16x16/16z] ZOs30G0n54DVZUm_xzdiDnEkeZh9cgZBU4sL4ef7Infxg6CFPUg57GlXyjIJ30YYXJkUplBELz_vtCI7NVYYRUPBFG

sprite $AmazonEventBridgeSchemaRegistryLg [20x20/16z] {
ZOw50GGX30GdE6p_zRu0UPSRDBvyOkYLWDZu9onVhyjdIjjdSoDQ9slvGeOAeWFkAz2cpt0VPIY2eFLXXFUvNtt7DGV9fgzekEO6VMf9s0_Drc60Q9MmVQ1v
GLJxhYzi_9C2uGtE
}

!procedure AmazonEventBridgeSchemaRegistry($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/ApplicationIntegration/AmazonEventBridgeSchemaRegistry', $name, $tech, $desc)
!endprocedure

!procedure AmazonEventBridgeSchemaRegistryCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEventBridgeSchemaRegistryLg>', 'ApplicationIntegration', $funcName, $content)
!endprocedure

!procedure AmazonEventBridgeSchemaRegistryGroup($id, $name='Amazon Event Bridge Schema Registry', $tech='')
  IconGroupElement($id, 'ApplicationIntegrationFamily', '<$AmazonEventBridgeSchemaRegistryLg>', $name, $tech)
!endprocedure
