' definition of the Item aws-q1-2024/Resource/IoT/AwsIoTThingMedicalEmergency

sprite $AwsIoTThingMedicalEmergencyXs [10x10/16z] Oq01BEpix0oeW1q4G58Cx0oCG0oYsHaPM84a6B92QAWwTcpc0G

sprite $AwsIoTThingMedicalEmergencySm [12x12/16z] LOt70S0W3CJall_42N0l2zmRcu19kULYm1pH1jUtwxFySSnmw24TrJfbhrQ_kFwqg7Nt1m

sprite $AwsIoTThingMedicalEmergencyMd [16x16/16z] ROy55aHH24B1tF-E1vtwnSjxR3p8KMYOVp0gMYipV14_SKuTsBXsuwZNNZr-KO2uQktCPiRRtcClweW5QqVAzBPR3dijku7YNed9MpzmurSVK-myxfVv3D8B

sprite $AwsIoTThingMedicalEmergencyLg [20x20/16z] {
VP254S0m30Cba_QVkCnDyZxyCwE7Wm5jCN3rmdQ79mc0VBlYaQUJHvw0I0BQypns9nukUDI6H0b7hRIw9C7acgypZnI3xxmj5NZbOUETTt3c_M_hEClAgjGM
EVef0HwnCWC
}

!procedure AwsIoTThingMedicalEmergency($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/IoT/AwsIoTThingMedicalEmergency', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTThingMedicalEmergencyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTThingMedicalEmergencyLg>', 'IoT', $funcName, $content)
!endprocedure

!procedure AwsIoTThingMedicalEmergencyGroup($id, $name='Aws Io T Thing Medical Emergency', $tech='')
  IconGroupElement($id, 'IoTFamily', '<$AwsIoTThingMedicalEmergencyLg>', $name, $tech)
!endprocedure
