' definition of the Item simpleicons-6/S/Sabanci

sprite $SabanciXs [10x10/16z] VS450OG0002nUyLP_xO4GBQUGLZUdxBgpLA3HPhBBshWqqvN3W

sprite $SabanciSm [12x12/16z] ZSd50G0X3031nJtqNotsFc4WpfKaSUNSFFJjPF5Lfzqf9Ii3il9wkks-868g-zJeImJbMRJZrGG

sprite $SabanciMd [16x16/16z] fSM7OGCm20NHhuQwRlzj0nl4zgESVfRtMybRpvsUGQWwX2HQpdbIeUG76y4nuAebd4BKqCNVN2OuIYa9yTRSe7s0VPK8KerSkM9PeRQaZ_q1

sprite $SabanciLg [20x20/16z] {
lSk7SGCn30NHlHm8OlllrWEo14jw4n0_lt56na6vUt-tQfnWSsYGPaIaWHgXdgiRHKC3LgjZQIsUL5suwJDVhj4fcpwkMyzUhGmflXGzhf63pkDqqfrMk2pR
I1M6_ToPZcFby_u
}

!procedure Sabanci($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Sabanci', $name, $tech)
!endprocedure
