' definition of the Item simpleicons-6/S/Sass

sprite $SassXs [10x10/16z] DSY53S0m4CNGN-Pw_scJ75dqP8qkTbbubsDCZcsexi33kPa_eXsuJvD02vVfUbanI1k13W

sprite $SassSm [12x12/16z] FSp50GGW34JHmPtVVxKhsBl4exz6riPsqYBdnKerWCGGY3y3ZLQ8rGOMSUGrdgzfH3ovC3GWwVo5AMbzNzql

sprite $SassMd [16x16/16z] {
HSg70GGX24JHCMuIVl_Ttg4RdX4OJSsuaXx6iYaamgYfkaKDSAXS3FbOuLHMVf05w60IqA1NWi-eGTvXJzfvYCy58EUH22dd-cKzSH0RN1t4QU00aWprnDBr
Dyo-CcGcZ_yF
}

sprite $SassLg [20x20/16z] {
JSo54S0W44JHnPtVVxSPRc8FvqItjfbPFuNR2hhnq_vVpPrxf3zVvzO0V27TlRmQfcIGmFQRW7gsA6uX0JH05OOb98uDMC-USkEp17yJO6Zmap6kjxgv2HCq
LyrFgsMrX0KDa-G1sQHW93McmqSUEZhUDnv19l7Hgs9Mqd41
}

!procedure Sass($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Sass', $name, $tech)
!endprocedure
