' definition of the Item simpleicons-6/S/Scala

sprite $ScalaXs [10x10/16z] Ou02LX31pCFFpyyEP00f91ONJ14dDbb-5hWqDbb-1WO

sprite $ScalaSm [12x12/16z] Oq03Z4oS_Fpy81OJFn2WihaXR1vsPWO6DeXoDXu-tEfPmKgus1Y18hnWDYSFiXe46suy

sprite $ScalaMd [16x16/16z] ZKp50S102CkvX_sdhGjzzVA1A3Ii_fl8oQjS-ECDBs_H0aRjcS8hNyYvFQezDeSFJEXNFfJ6gJs1uiCVP0K

sprite $ScalaLg [20x20/16z] fP034i0m403ZvFp_rzRkeDZ1cUv2ljYnYjNLyB6opQo-oNZd8tVneT_dGIivJ5gHUbe4_iwrUFLfSYk3mL2dZ5pS2G-7VW0aR-UMko-TVg1Krzrw

!procedure Scala($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Scala', $name, $tech)
!endprocedure
