' definition of the Item simpleicons-6/S/Showpad

sprite $ShowpadXs [10x10/16z] XSQn0KHG042nt07LV_jlImzInOT2_JL9j0y4pYPY3oDt3W

sprite $ShowpadSm [12x12/16z] ZSV50OG00C2md0lI_QV55e2-6jUQRt0_TkZcqT2uBGbzWs2ouP5kP4Ee7lWuQGK

sprite $ShowpadMd [16x16/16z] hOk50SGm24MHkthxzfys2J111UUBV13NNDkqNWXW1QvynGTmO7d3m9nbJoqBbbQM-YM1dG8K6O3lXEAmYN0jeC5TKAPvl4-Z0m

sprite $ShowpadLg [20x20/16z] lOo53GHH509Pbo_JVxUNPoNS4YE3w2lDNcvTqW011y3gBOxR8JpxETdDRP91s6DbBSdXwaWxDrDAMFVbEGes96lwrytmQO-L8JCC8A-8-sN2fT2rwv_w0G

!procedure Showpad($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Showpad', $name, $tech)
!endprocedure
