' definition of the Item simpleicons-6/S/Simpleanalytics

sprite $SimpleanalyticsXs [10x10/16z] Ou02VdvSB6P-d2n-9g9O

sprite $SimpleanalyticsSm [12x12/16z] Ou03VdwyR5Os19kF7oyRYCXc0m

sprite $SimpleanalyticsMd [16x16/16z] Oq06_FnyPFBPs5WGV32BYpm-Y4LFFW

sprite $SimpleanalyticsLg [20x20/16z] Oq03_FpyxBGIOsHZOqKNO-RdvwEP61y_FnEw6F_W5WC

!procedure Simpleanalytics($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Simpleanalytics', $name, $tech)
!endprocedure
