' definition of the Item simpleicons-6/S/Spdx

sprite $SpdxXs [10x10/16z] uySEU400nE1b008-C0lC0BCW30OGYuyNee4Fo87hPeSn-1X09

sprite $SpdxSm [12x12/16z] uoSEC8013uBDWn3d1TBC43OVa69Y0BDv8G381ghbXPa3rCQBR2o2oGXX0m

sprite $SpdxMd [16x16/16z] dSVL0K0X34FHFDUG_QV5zPUBj4SJcL8cSl_emEB2hvgH27-WIImcbrGonKyr_1hi6JoqZZum-46n0m

sprite $SpdxLg [20x20/16z] jSgr4S1050DHcUb3_zMQGMF5j-6RpHBPrqEEDpL4al4LZz45ikMwy1XTP1Rj4SWYlKig04knpB-biN63sWonW9Y3R0C

!procedure Spdx($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Spdx', $name, $tech)
!endprocedure
