' definition of the Item simpleicons-6/S/Speakerdeck

sprite $SpeakerdeckXs [10x10/16z] Oy06EFZv-K6OZuaVH888Rdwe73y3FmY0M10-6n3pGCH0c1C8G0IISG

sprite $SpeakerdeckSm [12x12/16z] TOh50G1120DFru7-gyM_34vobJpl-qQxoBcjJPgzz-ll7NM7SxPvEwKdTeVGzfkStQsbnrk1

sprite $SpeakerdeckMd [16x16/16z] bSi34W0n40J0YPtv_siFMq7nqE4Al_bIBmRtdG0Eu-D664RSsB6HTjJZYC6XZ1YsjjP8pbW4-IaoS1YJPOLIgJ12GpuARqu

sprite $SpeakerdeckLg [20x20/16z] hSwt4SD050FHfIVFeVzgvRwHSl4bcDa8tEwKER4Tq1GejdtED92hqZLzm6UyyQjBaqBBHiquih5tkIcRAz8UxRoCf1dRfY-s-9SMR0-EowpmsPE_F04

!procedure Speakerdeck($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Speakerdeck', $name, $tech)
!endprocedure
