' definition of the Item simpleicons-6/S/Spond

sprite $SpondXs [10x10/16z] BSkr0SG0000XtYLo-qyRfmT-lK7TUlMZY5wAL-dtl0TLJ4NlWcv9L_nTrn4hLW

sprite $SpondSm [12x12/16z] 9Ok50S102CHILyZ-qxxYd03mUJD3VqC1_BcpSw3ZNud0Du5BNxyWfrDrhXMyTPaeuga9U8WVtFQ-m01Xa8HgHoi

sprite $SpondMd [16x16/16z] {
BSg5aG1H2C3GV5s5z5_j2RCPGnxL2fy6Nw7L0K3J2uN70AXx2WpVma2lwxJZzW9wgZjTSlW0q4CDOMbsWARQWAqc_5CT09nwCco6dgKlroa-xR4GhoRR0Iq4
JWN22NY2Rehb78xhMw5R9S0l
}

sprite $SpondLg [20x20/16z] {
JKy70eGm28Fkri7_VtkauTIu8Ki9pDlE9Xzq2rnP0lXGirJzPJuZzVljhzbinQZiHn0glS9pSOThsWw4czs-6sAdGWpawTCJf289Uq8t6PxfHWjs0pVoBhnr
9fzFpR9ycZ5hpvuwzHcwm7RgJlQXNMwKKIqi5a9HX8rHG0Op9uTg9tzUoBVEMMOoTI_amU3WgWBy
}

!procedure Spond($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Spond', $name, $tech)
!endprocedure
