' definition of the Item simpleicons-6/S/Square

sprite $SquareXs [10x10/16z] Os3dXm1680CE6C207SvY1BE014uMGXqx8mW03OIR1W

sprite $SquareSm [12x12/16z] Os3YXm484m6u8G3CP80033QO8iZ6r8i2aBa

sprite $SquareMd [16x16/16z] bSsr0G0X44JH8G7M-w_stFqU-gC5D5OLY3sD4yBCXqwOyLrRzvHDHuT_T26YDFVRFETP5pNsi4zk0G

sprite $SquareLg [20x20/16z] jSYr0S100090Y55zs7_QkBjUUO0y4mZaNf9y7IQqSJm-PhNvPQxzUOFh5xabZbm9NgFN82z59G

!procedure Square($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Square', $name, $tech)
!endprocedure
