' definition of the Item simpleicons-6/S/Styleshare

sprite $StyleshareXs [10x10/16z] BSQ50G0n349HJkhozv-scXS1BGclZID962VmbGuagF9179ND0y4XzgBx4vSaPsK2

sprite $StyleshareSm [12x12/16z] JOo30G0m3C1cu_zhnoerrQNEf3xpyrD0fBFVl8yQsudrv-xc5sUcIoTUYocQSO-FjJP7X1o8_7IeGyVk1W

sprite $StyleshareMd [16x16/16z] {
JO-54GHH24FNi2-a_svlo1bl19SSH3RcUNpP03569tvanMWiDZSkbWsAbLgkr1Wo7mslUBD-FO39V-yUa8LYSksPAn_MJzO35i9vxjTGY2z-fEZm-pzI3wyM
agkfUG4
}

sprite $StyleshareLg [20x20/16z] {
NSrN4WGX20JGdY2i2lJzRxl5u8VbcoWHIm-QOADS_CR2JJz3QPoXr6hM4lLPPMAclEDb-bNCsZFKPLwrfs8FXhWER3DQY59LWflNWeCrZyRqz24n4JL9M1-T
RL9hNhtR7EAkyLKudEa2EI1LW9id0FqCfS7TWqyxgigl0jwG_W
}

!procedure Styleshare($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/S/Styleshare', $name, $tech)
!endprocedure
