' definition of the Item aws-q2-2022/Category/SecurityIdentityCompliance

sprite $SecurityIdentityComplianceXs [10x10/16z] HSP50S0m00ImyP5_loiths1JmG9mNwbztYVEjaUtnbmc8ZxANWc9drDgYuksqHy

sprite $SecurityIdentityComplianceSm [12x12/16z] JSQ53G1130CmgPYa-y_x36UHUyKJJjdYwRa8AtkkW5S_TpgBp-Liidga-3vAUDZzaPVf-UXq7EXRnGu

sprite $SecurityIdentityComplianceMd [16x16/16z] NSY53O105C1GybtsdnSubqPVzOwangr7nMlM-Xst_q4e8CqQ4O8CI32jxkYCjtqvghquk-ct5sSG1mPCfwW0gaydiw35SaQjs78Rlv-p3m

sprite $SecurityIdentityComplianceLg [20x20/16z] {
RSpL0KGn24JH46NO_ljTvbdqVXwadGgo5fhWJfzQwzRHpRhTqOWjvffoDqT1ukygtIn7847pP8c6is4qUmoN_MupMeGZpJ7SLWiyccEfQibYnMl4b9C4f6uU
OgavMJTcTzr6xDQH5hRa3m
}

!procedure SecurityIdentityCompliance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Category/SecurityIdentityCompliance', $name, $tech)
!endprocedure

!procedure SecurityIdentityComplianceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$SecurityIdentityComplianceLg>', '', $funcName, $content)
!endprocedure

!procedure SecurityIdentityComplianceGroup($id, $name='Security Identity Compliance', $tech='')
  IconGroupElement($id, 'SecurityIdentityCompliance', '<$SecurityIdentityComplianceLg>', $name, $tech)
!endprocedure
