@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-19/bootstrap')

' loads the Item which embeds the element ServiceDnsSecurityPolicy
include('azure-19/Item/Networking/ServiceDnsSecurityPolicy')

' renders the element
ServiceDnsSecurityPolicy('ServiceDnsSecurityPolicy', 'Service Dns Security Policy', 'an optional tech label', 'an optional description')
@enduml