' definition of the Item azure-19/Item/Networking/ServiceVirtualWaNs

sprite $ServiceVirtualWaNsXs [10x10/16z] JSL10W0X24BHNwNAtF_04wrw2l0Q4J6miBk40p73Hf0prJfDLOQKLS1ds9XTukhEqpy

sprite $ServiceVirtualWaNsSm [12x12/16z] NOa70i0W20E32adw_mVNxd4APE17pynnoCYDs6IsiScjsCwc8xSuBr2zQBco2cHHdfe4KWsAxiAaOce4TaZRczXO3ha2

sprite $ServiceVirtualWaNsMd [16x16/16z] {
ROg5OGL024FH1Bh_m3tz_auW8Z-9p8odpCsLVhGVPRganfGsUrF6M7MkbWUF4G66YmD3Az1TVusCgPb1Qdd0I8YGG4b9WwGCj8BHuz1bWN56GrKEQ8vJSe5h
XQiywPl-0m
}

sprite $ServiceVirtualWaNsLg [20x20/16z] {
VSlNOKH124DH4IGOzz_loz7sxlcP01TV1Cd4at5dkF64I_AKruyVhLjUtRbf2FhUUSHHXctvcl2IjbPIfXPLfOL92OakzQWUexOxaPApVA1jR6joO8kA71nI
BR1G5mKqbEekxEhdH9o4RI_S3IUpT6yl7xXrZEXe9Hvw_H7nObJWC0C
}

!procedure ServiceVirtualWaNs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Networking/ServiceVirtualWaNs', $name, $tech, $desc)
!endprocedure

!procedure ServiceVirtualWaNsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceVirtualWaNsLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServiceVirtualWaNsGroup($id, $name='Service Virtual Wa Ns', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceVirtualWaNsLg>', $name, $tech)
!endprocedure
