' definition of the Item material-4/Editor/FormatAlignLeft

sprite $FormatAlignLeftXs [10x10/16z] Oy0As200oE870JHPVWZ0r8535W

sprite $FormatAlignLeftSm [12x12/16z] Oy09-640gpYjr0C

sprite $FormatAlignLeftMd [16x16/16z] Oo08k7WHW0d4vq409YpgUVaXW1dAPu82c3mZ4m90r2C04nxxcM1yF7PZCm_9EYnQ

sprite $FormatAlignLeftLg [20x20/16z] Ow0CyAC0Fh0O6mfW9K8lGemF3l3Rou42s76wXH4LaEGMX1z83mC-5C13V802

!procedure FormatAlignLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Editor/FormatAlignLeft', $name, $tech)
!endprocedure
