' definition of the Item material-4/Editor/Height

sprite $HeightXs [10x10/16z] Oy01sFZXJ29P7FmS234K

sprite $HeightSm [12x12/16z] Oy076FdXJ2P-VWI70SWabytFpuVWy65O2G

sprite $HeightMd [16x16/16z] Oo0IiA5o-VZPaRcy_Foe0apyG89sV6PMVcPc93u7q7uc1XG19bG3677u2m

sprite $HeightLg [20x20/16z] Ow06OEDdn1JYvyCG0W8CbHmWaK4hnix1my_9mOmYnWZo1XUwNgWGgafEaeCI

!procedure Height($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Editor/Height', $name, $tech)
!endprocedure
