' definition of the Item material-4/Editor/InsertDriveFile

sprite $InsertDriveFileXs [10x10/16z] uwS3

sprite $InsertDriveFileSm [12x12/16z] unza

sprite $InsertDriveFileMd [16x16/16z] un_X

sprite $InsertDriveFileLg [20x20/16z] unzKO1G

!procedure InsertDriveFile($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Editor/InsertDriveFile', $name, $tech)
!endprocedure
