' definition of the Item material-4/Editor/Padding

sprite $PaddingXs [10x10/16z] uwS3

sprite $PaddingSm [12x12/16z] unza

sprite $PaddingMd [16x16/16z] un_X

sprite $PaddingLg [20x20/16z] unzKO1G

!procedure Padding($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Editor/Padding', $name, $tech)
!endprocedure
