@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element StrikethroughS
include('material-4/Editor/StrikethroughS')

' renders the element
StrikethroughS('StrikethroughS', 'Strikethrough S', 'an optional tech label')
@enduml