@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q3-2021/bootstrap')

' loads the Item which embeds the element AmazonBraketSimulator
include('aws-q3-2021/Resource/QuantumTechnologies/AmazonBraketSimulator')

' renders the element
AmazonBraketSimulator('AmazonBraketSimulator', 'Amazon Braket Simulator', 'an optional tech label')
@enduml