' definition of the Item aws-q1-2022/Architecture/SecurityIdentityCompliance/AwsSecretsManager

sprite $AwsSecretsManagerXs [10x10/16z] FSR70O0m54Cn0sb-V_zzITT9xjfGkGLPUiPc_OsfDxdEeSzgmGFlQpk216WiQ1gDqS4_

sprite $AwsSecretsManagerSm [12x12/16z] JKi50W0X25Dwu__llGuBbZXFNIUv458FE1zCSIHSB-mwqp5FVBp4m9MPnny9zMgUHyPHGJU34I5-uZQ1fSk5ZrYGlF7T8NO

sprite $AwsSecretsManagerMd [16x16/16z] {
NSYv0S0W3CNGOF2Xp_xpvdGLTKzyrLUcVaDgTv86X1qpAp_B0fBCsOw1sIBzSwA0WBP9Ay8BulLHcZemvg2sRhGhOMzHiemq9e-tG4-3pwm8BIRs-awgKP9c
Uwkx_HiN
}

sprite $AwsSecretsManagerLg [20x20/16z] {
RSvP4i0W20DGn0KIxt_VmY1_JLVVA80NxvWPVf0_ICBBbdSOA83941dkvncXCEIzpYnxErKEa5Hc1X-ExO2sIUt40ioUZTWgSyuHhcLRd2iK4vWITklivXbf
-VWD76bKAB0HkO6vIpC6BGkqnPwpBKYTApRtlWpfAgjttaQYZgSrTj9-y0C
}

!procedure AwsSecretsManager($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Architecture/SecurityIdentityCompliance/AwsSecretsManager', $name, $tech)
!endprocedure

!procedure AwsSecretsManagerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsSecretsManagerLg>', 'SecurityIdentityCompliance', $funcName, $content)
!endprocedure

!procedure AwsSecretsManagerGroup($id, $name='Aws Secrets Manager', $tech='')
  IconGroupElement($id, 'SecurityIdentityComplianceFamily', '<$AwsSecretsManagerLg>', $name, $tech)
!endprocedure
