' definition of the Item aws-q1-2025/Resource/IoT/AwsIoTThingHouse

sprite $AwsIoTThingHouseXs [10x10/16z] Oq01BEpix0neW9s16Im5P00v89e5B0o2G8gT5S9YP0Ipi9a7

sprite $AwsIoTThingHouseSm [12x12/16z] LStN0GKm20B0IwAo_yIlr_jLmByY3VH-2hKHJB5jci4kE8RiW4pqhaam_Vo9rx-rbcMGUUg_tIi

sprite $AwsIoTThingHouseMd [16x16/16z] {
ROy73i0m2CISO_t_nmsWLglEjAm5FpX98NirlUwASDlweQbShCRTjhk8ipqBaijjokXU38hkLQzRgRAxowqyZUuA_AIATWcx3goRQ3iNxXONqqVypeDTJuwu
F
}

sprite $AwsIoTThingHouseLg [20x20/16z] {
TP25TSKm40JdSFllE15-7bkqxvXV11PeVfV4ybNh5tnfF5D0vD9AjYposidfE7PcGzDy3fEsxIiceUlhpSPx-agTOYCXsR0ZvwE5s7P7en1FTd2qQsV_YF8d
Esm0OzMFVi6hgxiql_evluFDR_07
}

!procedure AwsIoTThingHouse($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Resource/IoT/AwsIoTThingHouse', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTThingHouseCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTThingHouseLg>', 'IoT', $funcName, $content)
!endprocedure

!procedure AwsIoTThingHouseGroup($id, $name='Aws Io T Thing House', $tech='')
  IconGroupElement($id, 'IoTFamily', '<$AwsIoTThingHouseLg>', $name, $tech)
!endprocedure
