' definition of the Item aws-q1-2022/Architecture/NetworkingContentDelivery/AwsAppMesh

sprite $AwsAppMeshXs [10x10/16z] FSR10K1G30L109lqtwzzyESqm1NdoMYbKrfrBN3vibWdfhJJ7TjTKrqSqDRZKi4D

sprite $AwsAppMeshSm [12x12/16z] JOfP5W0X2CFS9UN-zntiroXBmYlrmkzUVY9BiqXrFYopr1thviCXOfktQBnK5bV19ZBL9N4xP8d6N51ikPBPeYSV

sprite $AwsAppMeshMd [16x16/16z] {
NOm75e0m349jCy7xtrTvRkdyIG1Idweg7BeB_1Lu57mv2rIXq8YRUpJai74mR8fh-i44QzPGvi51rgBGarirA1QzafWx9z2AMVU2XJ8mNAm2qsqG41y535tY
et18_2ji
}

sprite $AwsAppMeshLg [20x20/16z] {
RSe55aGX241HuYFX_jThu-Ipxz5NTjFHedVziiH8rETY90AKn3WexkyM1hJS2b2QOF6DW6aXjksnvvg52p4FrMiIuGpxPvhF9TDiJAlJv9ei6qWOeqc8SwyJ
3GPPE1LRjZ02XSbFDP5XR6aBixGVh7-m0m
}

!procedure AwsAppMesh($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Architecture/NetworkingContentDelivery/AwsAppMesh', $name, $tech, $desc)
!endprocedure

!procedure AwsAppMeshCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsAppMeshLg>', 'NetworkingContentDelivery', $funcName, $content)
!endprocedure

!procedure AwsAppMeshGroup($id, $name='Aws App Mesh', $tech='')
  IconGroupElement($id, 'NetworkingContentDeliveryFamily', '<$AwsAppMeshLg>', $name, $tech)
!endprocedure
