@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsSlowMotionVideo element
include('elements/materials/Av/MaterialsSlowMotionVideo')
MaterialsSlowMotionVideo('element', 'Slow Motion Video', 'an optional tech field')
@enduml
