@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsHearing element
include('elements/materials/Av/MaterialsHearing')
MaterialsHearing('element', 'Hearing', 'an optional tech field')
@enduml
