@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsForward10 element
include('elements/materials/Av/MaterialsForward10')
MaterialsForward10('element', 'Forward10', 'an optional tech field')
@enduml
