@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsVolumeDown element
include('elements/materials/Av/MaterialsVolumeDown')
MaterialsVolumeDown('element', 'Volume Down', 'an optional tech field')
@enduml
