' definition of the Item aws-q3-2021/Resource/Storage/AmazonSimpleStorageServiceS3Standard

sprite $AmazonSimpleStorageServiceS3StandardXs [10x10/16z] PKg30S1038on_y356-49bih_Q0348cccTpEBLYYc-GpTIFvW8EedlG

sprite $AmazonSimpleStorageServiceS3StandardSm [12x12/16z] LSgr0GH040GWpcVxB_XTYV5dPVK-4vINHTNgj9KGBs50eMX0jNIyhFPAQDX0Xm0JdDmrhW

sprite $AmazonSimpleStorageServiceS3StandardMd [16x16/16z] PKo50GCX38JuxRzm8tr7Sxg-QpiY5tmt0Xq28v-uEsqjiT1sa8PnSdjjbbmv4oMM5llLQlJ6KL_6hqB33kIFgnxObtv4zS9JVK8QpAUy-uFy8OvUSS2vrHy

sprite $AmazonSimpleStorageServiceS3StandardLg [20x20/16z] {
TKw54S0W4EFzi__0LQG2mMD7MK4j4iWmQGpGhuOy3qvwHkGazTmUmEKxUoulgsMW2cG90A77ColtH3murDCUd2ZE9rzSSAaWW3pZCemoCWHgGyLeyWcN4muF
YkFlKwrzKebdTo2L2h41pt-fkLlpxm
}

!procedure AmazonSimpleStorageServiceS3Standard($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q3-2021/Resource/Storage/AmazonSimpleStorageServiceS3Standard', $name, $tech)
!endprocedure

!procedure AmazonSimpleStorageServiceS3StandardCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceS3StandardLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceS3StandardGroup($id, $name='Amazon Simple Storage Service S3 Standard', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceS3StandardLg>', $name, $tech)
!endprocedure
