@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q3-2021/bootstrap')

' loads the Item which embeds the element AwsStorageGatewayAmazonS3FileGatewayCard
include('aws-q3-2021/Resource/Storage/AwsStorageGatewayAmazonS3FileGateway')

' renders the element
AwsStorageGatewayAmazonS3FileGatewayCard('AwsStorageGatewayAmazonS3FileGatewayCard', 'Aws Storage Gateway Amazon S3 File Gateway Card', 'an optional description')
@enduml