@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element DataLabCard
include('gcp/Item/BigData/DataLab')

' renders the element
DataLabCard('DataLabCard', 'Data Lab Card', 'an optional description')
@enduml