' definition of the Item aws-q2-2022/Resource/MigrationAndTransfer/AwsMigrationHubRefactorSpacesServices

sprite $AwsMigrationHubRefactorSpacesServicesXs [10x10/16z] LOl50S1G24C3tzb_uEPnAqv4loZjtZ6PpprLvwcWoCMf4znXyKk_YUajCul3EtcUJKrz

sprite $AwsMigrationHubRefactorSpacesServicesSm [12x12/16z] NSV50GCm50BG5mz__tthf-Bunsu1LgjcPq3x-Q8SHZFO3R7DQ6yMHBPndQWGTmiT3d1nzbYgtzzD0ay

sprite $AwsMigrationHubRefactorSpacesServicesMd [16x16/16z] RSUtWGH030GWj7xKVxzlqoF3HoDf0DfYgm3FAymjqA2W5ZoowXo2iKfOQhcJOCau6X6gwFB-lpcYHUrWkeL3e7RTtIy8lBe0SwAkN2gP-x_BP3DXWYJ0Dm

sprite $AwsMigrationHubRefactorSpacesServicesLg [20x20/16z] {
VKy5eWKm21AMSly3VyT_NPk97J_UbiH7e1n5O1PVePnhPMbrhNw141UhbMEJq_wrJ9Od7yebr-CVAsWxiy0DBv4kw8T7cS9_VKPV9Uo0_se5ckAEmNRRbNS8
ZS6fii7BD6wlrbiCzGEDwtgbHXRgzM8iRqNhwtFaPCaxKyErpXOW7xEkMLOY-upd1v9N-my
}

!procedure AwsMigrationHubRefactorSpacesServices($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/MigrationAndTransfer/AwsMigrationHubRefactorSpacesServices', $name, $tech, $desc)
!endprocedure

!procedure AwsMigrationHubRefactorSpacesServicesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsMigrationHubRefactorSpacesServicesLg>', 'MigrationAndTransfer', $funcName, $content)
!endprocedure

!procedure AwsMigrationHubRefactorSpacesServicesGroup($id, $name='Aws Migration Hub Refactor Spaces Services', $tech='')
  IconGroupElement($id, 'MigrationAndTransferFamily', '<$AwsMigrationHubRefactorSpacesServicesLg>', $name, $tech)
!endprocedure
