' definition of the Item simpleicons-6/I/Ibeacon

sprite $IbeaconXs [10x10/16z] 7Sh50SGm000W6lViF-r9tm1r9Z03GMMKvP564bQlIQ7_cyZwKN9LfRmVdLW0Om0ebeul

sprite $IbeaconSm [12x12/16z] 9S670S1020EnCmycFVjFcohncbVpYvXhLlCQcNHqG0oN679FH5P0y5Zc54IcAxO2uaJLDSyzOZ3RAIGni7YuJMAK1ZNvDey9FGqt

sprite $IbeaconMd [16x16/16z] {
FSx1GHr130KmsHw_sKq0-k-MsrS50kR__zV7gsPR7M3ww2wF2xC2PxekRqk5YencKvMfhTMvfqYadxAtVKqpwHzpqtnjK_tpEyyk_dUfVGmtX-Aau9W4prYi
j7b5ntuwt9g-J5mBZpGo5fW3NlW3
}

sprite $IbeaconLg [20x20/16z] {
HSy7SfqX30R0bO3lhpFl_gTD8R6zz8wm7UzpJtwiK5qwZUtH5_JDOLiEdR_q4hZ5YwAdsxHtHGOonMnMUrsESpw49Lmj3dELfK-zBc8S7emXwlsJX7DwFdEQ
CKzlIvdBvtDnB2kU4fuoBvUASOkEq4oxTmrrwsaDfE8k4Jt45ckNiTiE7Qj67RZTdEpkqB1ZiDLHFMmf_J8l3jWg2tet_0O
}

!procedure Ibeacon($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/I/Ibeacon', $name, $tech)
!endprocedure
