' definition of the Item simpleicons-6/I/Icomoon

sprite $IcomoonXs [10x10/16z] HSgt0O000C2WsBly_wsZp5GTrghCuInxXILLSEZL0gAmghKT_-jKCwh5Xle

sprite $IcomoonSm [12x12/16z] DOo50S1020FJTsV_ROlU2vf0s3HWK3h4QFh9G0kQsc0kT8PAp2PyEbQm8XyStxRSzwVbDtmwXsRf0tEtTty

sprite $IcomoonMd [16x16/16z] {
JOy53W0n2C3WtFl_truwITOf3b5ON-wCpik9x279woMVShqdvDMv1dx8rCmzWfKZOZwCGtHVWIxxkmRvPZBqxN9oXNGve8fJwsXd7Sqsac5EsUeusSKnj3Rw
0m
}

sprite $IcomoonLg [20x20/16z] {
LSu5ee0W0CRWsUtkVzeNy5kpFnMWrYod-yYhoTtIqPAq1slhYxweCxnmW4dlKMkWztInkVdtT0INOgSsCCHEhIETW7Umbijjkq9NrzN4nZh7DW9p36r9eOF3
DTJ41bgDxJ5W3VOt5TnUr54Qb2d4tPmP1_xx1G
}

!procedure Icomoon($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/I/Icomoon', $name, $tech)
!endprocedure
