' definition of the Item simpleicons-6/I/Ifttt

sprite $IftttXs [10x10/16z] Oo0Iy3FmS_5300C8Cd0m05dCK1P-lG

sprite $IftttSm [12x12/16z] Ow00y3FnytFp0m4F43Fnyp7mCm0H4uZD06EJQYO

sprite $IftttMd [16x16/16z] jOV70G9040BdScRxxrQU5g1a-3Fq95LxIySLvYuxzb1Cbt-8570VHF8_VFtHHmC6j8xhr_W

sprite $IftttLg [20x20/16z] pSY50GCn30D0FNDk_sdBt0LYYrFH3SC5GpTShda6WXL6x43COzVJDxsrwpSzeIGaCIUB4ElqltNvtcgwCm

!procedure Ifttt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/I/Ifttt', $name, $tech)
!endprocedure
