' definition of the Item simpleicons-6/I/Influxdb

sprite $InfluxdbXs [10x10/16z] 1S670OC0400XKkpwj_-s0Wn0wrCGbr-4GT_8a1eM4jSFAN3a62pFm5GdBm

sprite $InfluxdbSm [12x12/16z] DSR50G0X00InmPtjlzeJ9A_mSPKhwJCCdoB8-2beayzq39DMtO1O-M-9W13N_rJolU4J59FmOga2f0osJvOiwUyB

sprite $InfluxdbMd [16x16/16z] {
JSl5SG0m0C0mXpdUVzjUolgBJxVmdqy7FWKtXw5EWEG2Bh2za1qyja2LQEFPdrsg0M0I08nOW0uau6oCZVevW2ukxasV1P1nGuHqQY4D9TZub1FToWkV9jCC
w0m0OvbugdfIk0P-95MU3m
}

sprite $InfluxdbLg [20x20/16z] {
NP253GCn4C3y7FR-srQNg2fOS8miqjZvewds6puCy_rqrVHnFP1sZXpP13gBwWP7Ls3JYuab53FemMIia99M8LIOpYgxRg4QcQ4yxbZAoe8EiFkWk39MBTQe
nt9-dChj4NeT1-JbY_gfigKwIatL0JPXKI4he2SiReejbEpxTnVTyNbUkm6RXJVxK2rEruSZVpxw0W
}

!procedure Influxdb($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/I/Influxdb', $name, $tech)
!endprocedure
