' definition of the Item simpleicons-6/I/Infosys

sprite $InfosysXs [10x10/16z] Oo0Iy7FmSl4pSZ2my_CpyJ21AIOGYu-HcvMV3RzU

sprite $InfosysSm [12x12/16z] bSQt0O0m402n-qnc_sd9zBOgqMa7ylzkeJhBWig-OWkrMMtSHsO95UTZj3a1

sprite $InfosysMd [16x16/16z] hSa50SGm343H7yxX_AiTWu6-DinW3L3AIISLhOm0Pukf2IEOd2BOPhU0gjztZMFUxeWcjy1a2tW80om

sprite $InfosysLg [20x20/16z] pOg50GH120E7PTtIVxNlMi7Tu2IS1nDtilCboUjSlNTjQrLGcf0xqyE4FKc607cu_ngK95S92lVVsmUpb_jy_MmlqyW9zSm_YoEv0W

!procedure Infosys($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/I/Infosys', $name, $tech)
!endprocedure
