' definition of the Item simpleicons-5/X/Xdadevelopers

sprite $XdadevelopersXs [10x10/16z] uwS3

sprite $XdadevelopersSm [12x12/16z] unza

sprite $XdadevelopersMd [16x16/16z] un_X

sprite $XdadevelopersLg [20x20/16z] unzKO1G

!procedure Xdadevelopers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/X/Xdadevelopers', $name, $tech)
!endprocedure
