' definition of the Item simpleicons-5/X/Xrp

sprite $XrpXs [10x10/16z] Oy06-A4q4v35ni00nBmWCNummGMIOGPYRX2N2qJmGdM0MEmG1YEISG

sprite $XrpSm [12x12/16z] TSg54O10302mu4xttvR3FIzLltfcMJ3OfNC-8kOyvYIT_wvjpCiGyqBIYcq_gT3FUMkN4CoApjK4

sprite $XrpMd [16x16/16z] XSt50KKX302mb3utzf_sksikKFVVN3WPUwXkSYKwTzifZWLYTefRol6jMAaSW-tqjjDqUaadLIQ69MhWidySiELjVu9BFBaxtHXTbAKzFIx2kpq

sprite $XrpLg [20x20/16z] {
fOq55W8m241P9t3_s_e8ktKZFmN_FS9uYZiFSPolEdOKTZsLjx5O9JEVqFiQQOk4meBE5WQe6aM6IdOq4oy_ikRfH7A_69B1lGSN2NINCfmIDRYuIrsRiL-m
Y_U8jI46Br6mbde1omhmyJi
}

!procedure Xrp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/X/Xrp', $name, $tech)
!endprocedure
