' definition of the Item aws-20210131/Resource/Compute/AmazonEc2R5AdInstance

sprite $AmazonEc2R5AdInstanceXs [10x10/16z] Oq0576n876PC5YEGnS70piZ0oiZCmS06bML3LiSC1gn8vW4

sprite $AmazonEc2R5AdInstanceSm [12x12/16z] NOs50G0X4CE2jTr_uNSbS6xyKIKL0KGN874IKM_V5TI7WIA8HYk8aamzd4nxS7py_hkx0W

sprite $AmazonEc2R5AdInstanceMd [16x16/16z] TOy50W0X40BN0lx_uiEzBim1Cpw4OCWDArQwAFl4NdVH2Bkx03Y_i1klEJCVDQPNYYcaEcZktIpDl4TZeE1d_uK_xoTswUC_oJ0ZUG4

sprite $AmazonEc2R5AdInstanceLg [20x20/16z] {
bP255GGm24EJrnzW_uNFtQ_57VJkbIADogeFjlJi_fciWwrrynQIgkREriNBkEG-hhBkuto8EzYYZ8GNFjXcHcav8jXh9eSu1349VZkBtNSs_DSUw-Q5KtXJ
C3GqdswAbXHX7SAs
}

!procedure AmazonEc2R5AdInstance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Compute/AmazonEc2R5AdInstance', $name, $tech)
!endprocedure

!procedure AmazonEc2R5AdInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2R5AdInstanceMd>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2R5AdInstanceGroup($id, $name='Amazon Ec2 R5 Ad Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2R5AdInstanceMd>', $name, $tech)
!endprocedure
