' definition of the Item aws-20210131/Resource/Compute/AmazonEc2T4GInstance

sprite $AmazonEc2T4GInstanceXs [10x10/16z] HKor0G0m39eZmF_NrfimuH8Ej8WVO15gWOx5kFbcY8Z4yP3kkTbkFMzJElgbdoS

sprite $AmazonEc2T4GInstanceSm [12x12/16z] JOx50G0W24NFycl_QLKuyGmw4biVEn-WvYO6D00sb46mYfBrzTBNIVJNkaoSmkYQvDPtxUwvP-qT7W

sprite $AmazonEc2T4GInstanceMd [16x16/16z] PO_50GHH24FF4PB-grqPb_SLXxOvw88jIvQzYY28vN8RmzbOlcQw4JeHJXbAp15bdlQ9XZ0rqEfl0p0NsKpToEHSyqKJw5NlsS-pt-Syptc_

sprite $AmazonEc2T4GInstanceLg [20x20/16z] {
RP1N0iCm24E_zG1n_ziMTxT1YTVpajKZk_skdeem1kE89pAaIlCd-87q8my9fddB8dnOV-cmTlwo78JagdBNWuc1fK94oADM3G9rHvMKW0L-CIIH3zQkmpnD
07xirR3Zi1mAI_nuoNnusJnlRrioMBBQCzsolm4
}

!procedure AmazonEc2T4GInstance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Compute/AmazonEc2T4GInstance', $name, $tech)
!endprocedure

!procedure AmazonEc2T4GInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2T4GInstanceMd>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2T4GInstanceGroup($id, $name='Amazon Ec2 T4g Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2T4GInstanceMd>', $name, $tech)
!endprocedure
