@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-20210131/bootstrap')

' loads the Item which embeds the element AmazonEc2M5DnInstance
include('aws-20210131/Resource/Compute/AmazonEc2M5DnInstance')

' renders the element
AmazonEc2M5DnInstance('AmazonEc2M5DnInstance', 'Amazon Ec2 M5 Dn Instance', 'an optional tech label')
@enduml