' definition of the Item simpleicons-6/B/Bem

sprite $BemXs [10x10/16z] Ou03Vdv-A8k5XOK17N2003zO7GWWis205Q4QIPoJanC

sprite $BemSm [12x12/16z] RSgr0G0X002nUrTW_sbnXzIXyhulCqefaiTRSHPls-9nS7RdE0-ipLdPkvCScqMqM0O

sprite $BemMd [16x16/16z] bSa33a0n0C3GRuptF-tCXdjXqmtsO6mRh7oorO7nuoly7V_5LlWR2Htrjhd10m

sprite $BemLg [20x20/16z] ZSl50SGm40Im2PXX-w_sC6RKNzX4NoZnBvJkh-vTey0h13BGvF6uW-iuinjuj2uyA8E73fGuq63KkHSww86COTSFSaBzeECD

!procedure Bem($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/B/Bem', $name, $tech)
!endprocedure
