' definition of the Item simpleicons-6/B/Blogger

sprite $BloggerXs [10x10/16z] O-372XY00Cf0i7XuW4mm2oQAH801CqoQ6Tam

sprite $BloggerSm [12x12/16z] TOp50S0m202lRiZ-qzO2_7AuudtcSP98-TXRbrM4TZV2-5dB6_BdiwgsV8NnMxBwmz2UgeXytS-I1m

sprite $BloggerMd [16x16/16z] VSU50KCX34NHXpliFstx3PUB90SnjTdCKmPtiUDLDW1AAI2AwVTdv_XWcatkgiatsJTpvd7C9EbBqYjcqY8x-0y

sprite $BloggerLg [20x20/16z] bSg53GCm34JH2vDX_sdB3OhoHFRNWNGNIMz8VH6TENoT2R0z2RhUwk-9G9bR8I83W7gRNRP-bNur0Ac-kTuK4wV_OMVqZwVLXQ2d9m

!procedure Blogger($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/B/Blogger', $name, $tech)
!endprocedure
