' definition of the Item simpleicons-6/B/Buffer

sprite $BufferXs [10x10/16z] JOk30K0n50Fl6qNsdxRMFIDa31KbFi2hyi1L6Wgl-bV9Pb4WkA4UV8hrDG8

sprite $BufferSm [12x12/16z] DOs54S0m30DLvlx-sqPddJynauf7pG-SvRs4GvffP9Ro9Xch9PuU-6s0rUQ6yj9pnTCFUug7yy2L8UM4p

sprite $BufferMd [16x16/16z] POy50aGX24Jjrhd_RPUH_VrC6ioVRkui0FMK9fIidhZ87vcCkqGiyvLJi78nUvvoUNfQIlmO8V1Jv2nAfsOUKgDcC9G54W1gZ5iQR-TkNk-Dm-OseZkJ_m

sprite $BufferLg [20x20/16z] {
TP073iGm20Hnxzx___O4w89IFEakC1lwumSz20j0kmr1iL4_OLGPshXJY2ZZnlJ491lPrgD0ME7MkGAugKcpg0giurJC5CQL0LKVxPZ3ibJxxX3DpBS6rl4Y
varpyTk41eXW4Wbktdx0lN6d6t7Ro0y
}

!procedure Buffer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/B/Buffer', $name, $tech)
!endprocedure
