' definition of the Item simpleicons-6/B/Buildkite

sprite $BuildkiteXs [10x10/16z] RSQn0K0040ImV0dS_jF2Dq2g-36Fa3h6b8GwffSHQOn2hoKBRN6p0m

sprite $BuildkiteSm [12x12/16z] TSR50O10000WxDRzfpKkN_B2ZqtGpDYDxwwhDRrdkxuBNyFFQmsFMDwlufae5zx9uge7

sprite $BuildkiteMd [16x16/16z] bSV50GCX04N1juR3xx_Q27vCvZRyALceRfdhUx1r4fZhUx1IFJprZ1ljVoI5zGhyKN-T_U0ENT3VzRlz--2m_E0D

sprite $BuildkiteLg [20x20/16z] fSYr0S0m4C10cTc__xPXJcTrEWPoFrDLFaMIIgk12Sm54Pd5-jL05J_BREkarK1kLjv64tcQAZANrMwt89ZTggw7GLQpTU2mjL0KBrixhF6sh7XPOxG9

!procedure Buildkite($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/B/Buildkite', $name, $tech)
!endprocedure
