@startuml
sprite $AzureReservedIpAddressesClassicLg [24x20/16z] tSYd5SGm40N0UxVIJ_qNRAh8Z3nm53ixHO2oCwgwMiqOur-DzPiXOM-qDNDioGVu11cW2LZBS_htz4i_

sprite $AzureReservedIpAddressesClassicMd [17x14/16z] jSVL0OC030JG5aXEzjyNzn_yHK-YryIeW9YbMPKPnQoIa5epzl8hOD_ASsAV6m

!procedure AzureReservedIpAddressesClassic($id, $name="Reserved Ip Addresses Classic", $tech="")
  CloudElement($id, 'azure/NetworkingServiceColor/AzureReservedIpAddressesClassic', $name, $tech)
!endprocedure
!procedure AzureReservedIpAddressesClassicCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureReservedIpAddressesClassicMd>', 'Reserved Ip Addresses Classic', $funcName, $content)
!endprocedure
@enduml
