' definition of the Item aws-20210131/Architecture/Database/AmazonElastiCache

sprite $AmazonElastiCacheXs [10x10/16z] BSR50K0n240nlc2FxhzkFQT0JZ5nkoR7cfbBM1IWI6ZMQh2dgAJDJPyuP9jxH86sMam3

sprite $AmazonElastiCacheSm [12x12/16z] FSU73S9G40HHVhmDxhzUs4FoABsHc93qJWnK5uzJ4tFMYUSXQzu3Q_uii0xjYItexp7sM4EVsDxWbTW-LkAJ4PMU7hU_

sprite $AmazonElastiCacheMd [16x16/16z] {
LOa7WWCX3CJMfdd4_l-zHxqaeae6RM83luMViDm_BC_5iyTOpUvyVDHgpOeEuHGp7yMbtfU3dhWUX0A_ypp_YaV5Xay8m4735vwo6t3zp47lSfLSMRmZBBZ-
6_u
}

sprite $AmazonElastiCacheLg [20x20/16z] {
RSy74iGW30H145wq6lp_xrxEvoagDHcePtx40NA0722mjS_oRgbmN8SYux6tnSmvCjkmPjaBjWfNPThJELnUYurWgCXcfrorrhfQK-OCRMypGHdabtNJ2vYo
7cQ9K6-ZDAMwsgqEO46zBSRr2m8-R04rkU5-DtfhJTog_OeFVxOVu7w0Pm
}

!procedure AmazonElastiCache($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/Database/AmazonElastiCache', $name, $tech)
!endprocedure

!procedure AmazonElastiCacheCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonElastiCacheMd>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonElastiCacheGroup($id, $name='Amazon Elasti Cache', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonElastiCacheMd>', $name, $tech)
!endprocedure
