' definition of the Item aws-20210131/Architecture/Database/AwsDatabaseMigrationService

sprite $AwsDatabaseMigrationServiceXs [10x10/16z] FOh50S1G5CBg0c__UHlw9ISaqWiFQ4R1Vgz4mhKi6wj9JR19n2GdYGJdUXChKQ5c_

sprite $AwsDatabaseMigrationServiceSm [12x12/16z] DSV70G0W3CD0MeeTzb-NZbud4ZlVySqp8KtnN04KN0jy6HxBIRqk8zR8-ki8iURVrLoLrofa8T7tyDRtl9i

sprite $AwsDatabaseMigrationServiceMd [16x16/16z] NOm54WD13CEk2m7x_l_URg3eGKcJ05wp6l1hy2kQnzbCaJoYgeOerZMtQPmmELy4EnayhySbpSmET0ynnkdxpUoE5sEECNQuxjnOq10tSuADtDs2QFuJJm

sprite $AwsDatabaseMigrationServiceLg [20x20/16z] {
RSp50GCn34JHNR76xh_TmDZX_ECJ0EX7jSCVn1_40olhWLWT6Xcd4hT5y5IQ-B3ZbcWJnxBcJstY88RYZaUpGOnoLGlRHep6FTr6355tatCRstk6DskxKmb0
My7bb0I8YnAZOB25aqOMh7eI6HxDFpZ_u1K
}

!procedure AwsDatabaseMigrationService($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/Database/AwsDatabaseMigrationService', $name, $tech)
!endprocedure

!procedure AwsDatabaseMigrationServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsDatabaseMigrationServiceMd>', 'Database', $funcName, $content)
!endprocedure

!procedure AwsDatabaseMigrationServiceGroup($id, $name='Aws Database Migration Service', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AwsDatabaseMigrationServiceMd>', $name, $tech)
!endprocedure
