' definition of the Item fontawesome-6/Regular/AddressBook

sprite $AddressBookXs [10x10/16z] Os3W1mDc88C13FXHM21v10jT5gmPmKAJvG83VWO

sprite $AddressBookSm [12x12/16z] NOg50S0m3CESCUl_RrSc5HA3H49klVR0XTkLmC9-d6LVO75xk0OM_A6F8tLE75Vo9yVGTxUW7m

sprite $AddressBookMd [16x16/16z] PO_L0S1G20EXhjp-qrQUo_sXIKGM4l8nGzKm986SJMsXFlUg1YvNQwefxmtcwhxvTvdj-LvnfFiJXwRzmT7zS_TtLN_K-Lu

sprite $AddressBookLg [20x20/16z] {
ZS_50SCm40NHBufnC_rNQsQUunEkf9fDGNtiYnq5Sct21Wix-uid2rLnj0omoOh9ZAx9t6JrnfZC0Ud3kpw4u2VBHsDiD0sM9hFDsOgfZScFkTjtYvEP90_b
cb5f6cjJ9oq
}

!procedure AddressBook($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/AddressBook', $name, $tech, $desc)
!endprocedure
