' definition of the Item fontawesome-6/Regular/Comments

sprite $CommentsXs [12x10/16z] JOo50O104CE2Ezb_MkJzNDe2cptHTdiEusojTxvuimtvlXY_yrzlxDLmMFI6LcKDxSYttru

sprite $CommentsSm [15x12/16z] JOk50O0m30GVjv3RVrgej_6yA8IngmNSftFNBpCSQMrKM5T2sskuDc-lv8Xvy1BsV1_mPF047jkQOqhhJPzHOMnxv9Tgd7u1Fm

sprite $CommentsMd [20x16/16z] {
POw55S0W4CL-tO3ilsqVRccnau0y3-vK1n5R8mkiVZr16ToqEshsH5_GEge6hpQIRMDPov93Xgo5ehlo3MkCRTvKjOR0Ljy4l5gzj6hZgMhNeCt1Rv4MFQXo
4tYn6l3-7m
}

sprite $CommentsLg [25x20/16z] {
RSr5eaCX40NHY_EagVslzai84ZaZh1ezLCEoteL6Pqwx2YH91GXQ4lYHmjQ09WzRS6enV3Zxl8OsaIp0-gID8yjNG3g86kRkWhS4neDB5vS6AEhOamotdWnL
BXbTrN3X65hLGkVrnj7atFRp04uBS-ivjJE01bdmDjeOchwe3VW5
}

!procedure Comments($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Comments', $name, $tech, $desc)
!endprocedure
