' definition of the Item fontawesome-6/Regular/FaceGrinStars

sprite $FaceGrinStarsXs [10x10/16z] BSA5aSG0000XufxjlzhNOu2Z5THaww0RjCZ5ICUaFfdWMZVlOBubQqMEG5ZgAhu1

sprite $FaceGrinStarsSm [12x12/16z] DSQ50GC140B1ZTkHxR_RvsrE0Ehd6pQQLvJo0JLkzGFSI91nICzVk7b7wRsuRWE-mqa4hQqFZ1_mrGkKVofQBrW

sprite $FaceGrinStarsMd [16x16/16z] {
JSw5WGCn3031FJwJjlzg_nChD6QKc8vXMtWRfelfFUcEN4BQx3245MPtkE35QbrOBGlX8OJUg8NT8MmAXmBwynomoI-Nl6-eS8iTufsUmUa6HzWNw0B3WzGz
SuWTkCqbB4u1y0y
}

sprite $FaceGrinStarsLg [20x20/16z] {
NT25OKGX50NH-Muyflzg8zpe7jm5ukgsdJysZPeWrBu0XtenQ8EOzVxR5Rh1DhhM70He4ezP2PoUs5bL6secNIuv42OLq2wmZM9Aep8qmmB4OvCNtTq3wES4
h4y3bEmUgHVb3Bi1epqfCDrQH_u1k9JuwO9RJuQfTFxpfVLqLNwS3fL9xm
}

!procedure FaceGrinStars($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceGrinStars', $name, $tech, $desc)
!endprocedure
