' definition of the Item fontawesome-6/Regular/FaceKissWinkHeart

sprite $FaceKissWinkHeartXs [10x10/16z] DSI50OC000Inr1Lk_sbnyWAVdbPry-f3VwiUikjpqrqfXz_pXT3vtNmYh-9Hlunc

sprite $FaceKissWinkHeartSm [12x12/16z] FSQ5RGG1400n_p6jflzk8un51cyNeEQSWdRmzLzcn8w5tY7wFdK2w1e84lRee0zHqLXHOQgkapy

sprite $FaceKissWinkHeartMd [16x16/16z] {
JSt50KCX403H-OR3z5zjR6Fl0klmT4txniSqv0W_d-6C4CBXW2byN6wO-LbU0Wf3JqwdW1Naog3opnvnaOYtpoV3s0vnG5pj2YGFOcLMXUa5gm4HCrmdK30-
RFgq0zm1
}

sprite $FaceKissWinkHeartLg [20x20/16z] {
JP050i0W30E1kVN-_zjLi4mWzIPLNCAxfmaR5Lzk9YMow7a0LpEzpLlW7gQHircjC0rZV3DEpeJO9A_Jv_30YyNFrTlps26Ukji8Qqv5v_jevGOUtcQJjeEm
SxGXf0y3BMMr7wbiwQEuxQkjYywHOUJYq7d323cKSNh3ESd6soNz7b6cGex5SNkm7m
}

!procedure FaceKissWinkHeart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceKissWinkHeart', $name, $tech, $desc)
!endprocedure
