' definition of the Item fontawesome-6/Regular/FilePdf

sprite $FilePdfXs [8x10/16z] NSQr0G0m30F1BytUVzfm5ODEz1gWW5sQRRD5d_ooxRrBQulm8B2m2G

sprite $FilePdfSm [10x12/16z] VOo50S103099tTb_st8Pu3se7cSfw_dsVU_H2mzZJnyZ4siygQVALZ4jH6Ucu_ChRpwYqVm3

sprite $FilePdfMd [14x16/16z] ZSd54KCn54DHVJEh_supCcvpZMSU0cS6QeDC4Wcr-IHk3V4At_SzgV_rFQcjMX2gGMrJZ1oUe5dwE0p1FIEcz3Dwnf1-

sprite $FilePdfLg [17x20/16z] hSg54SKW50NH6m_sjlzgqUyociNFeCNe9Orc7iqT38s0s_a4fa_W2z8BBCuvhCEpAy2TDtZs5y09aYBSO6PYPJ8ttq1MdnNyVWDG1qk1v2KM3TWb0udRhme5

!procedure FilePdf($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FilePdf', $name, $tech, $desc)
!endprocedure
