@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2023/bootstrap')

' loads the Item which embeds the element Open3DEngineGroup
include('aws-q2-2023/Architecture/Games/Open3DEngine')

' renders the element
Open3DEngineGroup('Open3DEngineGroup', 'Open3 D Engine Group', 'an optional tech label') {
    note as note
        the content of the group
    end note
}
@enduml