' definition of the Item azure-17/Item/Compute/ServiceVmImagesClassic

sprite $ServiceVmImagesClassicXs [10x10/16z] FOY70G0W2CCg6_x_rwrXXU9ZxM4qNrcPJnDP6dCiQnajusa9mueDwkuHFbb15GwIcVCC

sprite $ServiceVmImagesClassicSm [12x12/16z] JSR50GGn54Enzyc9qt-_op0wYGlDZyGC3p6AnKDtm_kQDaHiGFBv7dc1maWyX9I-uEcSuijUl9KVDd07

sprite $ServiceVmImagesClassicMd [16x16/16z] NSm50W8n30NHISd6xdzWVeipgw_6N_4VPiRk_CXnlBQTI4AwkRlfi-twNdA34GLoH8qCMLp7tVBQ3i1bD4uriTRx_EsVgletJcjc-CfdVZQsihUo7g7k

sprite $ServiceVmImagesClassicLg [20x20/16z] {
VOu70iCW24NP8_S_S56Xkts9-dbE-8Be9qRuZjbg1ar5Xd94ksGvMi3yE9A2ZlDsAfjnVP1ANcUxnpZBgrr4xMsNUVQEm-KOZaka7O5itfA9yFfcAcVoXgRw
8OgE1irLJFxdik0N8xdH9sK-xF86
}

!procedure ServiceVmImagesClassic($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/Compute/ServiceVmImagesClassic', $name, $tech, $desc)
!endprocedure

!procedure ServiceVmImagesClassicCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceVmImagesClassicLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure ServiceVmImagesClassicGroup($id, $name='Service Vm Images Classic', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceVmImagesClassicLg>', $name, $tech)
!endprocedure
