' definition of the Item azure-4/Item/Storage/ServiceAzureNetAppFiles

sprite $ServiceAzureNetAppFilesXs [10x10/16z] FSQ50OC040F05Y8loFxJud0loVhfUdJbeyo7DGu-3ACCf2C16qmfUJQOF7_68zVF3W

sprite $ServiceAzureNetAppFilesSm [12x12/16z] JSO73W0X24JH66ReYVS_xVRYK-3FHIyoFXd-2QFW8ZJ3e1yuSBHOkgV9tK76rNoRHmFFjyfFpSKE

sprite $ServiceAzureNetAppFilesMd [16x16/16z] NSc53KDH34DHDPoKzf_sFyOZyfN_jz_X__R3EywEi4EO24yYPWmlm2eFhirUSMiY2JVp4ABI2Bc9SWEsNyEPFRJzXEBbTy7Un8p8TPYhRDH_b_yb0G

sprite $ServiceAzureNetAppFilesLg [20x20/16z] {
ZOi54WGn3CFQ9kx5MVh_Rw_B31hoQApk8qrregbuelhg-3j10sG7O0OD8M8YXg23Yr7f0-ntxw2QwJIZCwkERKgWcwevaTBu4-cTI77zthJ0qXAGqhB_iRG2
i7Tze28wJJ9dxCYPjP-eku_y0G
}

!procedure ServiceAzureNetAppFiles($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Storage/ServiceAzureNetAppFiles', $name, $tech)
!endprocedure

!procedure ServiceAzureNetAppFilesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureNetAppFilesMd>', 'Storage', $funcName, $content)
!endprocedure

!procedure ServiceAzureNetAppFilesGroup($id, $name='Service Azure Net App Files', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureNetAppFilesMd>', $name, $tech)
!endprocedure
