' definition of the Item azure-4/Item/Storage/ServiceStorSimpleDeviceManagers

sprite $ServiceStorSimpleDeviceManagersXs [10x10/16z] LSQ50S0020F1ns7_WUjwIC9FPYgxskrvChHlrJVcnbxRVOITH71nXnK

sprite $ServiceStorSimpleDeviceManagersSm [12x12/16z] NSl50KC1309Guh3_mErtUwS8u2EwE_SnPnNhsBDRnhaWINOFLyCRT4DBcREEQziZ8ZDmi2exPoST-0C

sprite $ServiceStorSimpleDeviceManagersMd [16x16/16z] TSg50G1H209G4t7_WQyxtayL-HG0yYonsiki5TPi7TRXAQUQDuxfAbLDheftsjsSvkYLp9UxrruBrqzLpUNCV18Hhd9G02R_bEGS7m4

sprite $ServiceStorSimpleDeviceManagersLg [20x20/16z] VSk50S0m20J0ns7_XKlgVb4CFyJSbN3c2yQEOyFOUEomi3Z1G74XQ76du7pGo1Pecfl89yu1pNA3UWBtbTIiLW9W_QQsh29WO1cq2UECh16kfE566_2SnJ01

!procedure ServiceStorSimpleDeviceManagers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Storage/ServiceStorSimpleDeviceManagers', $name, $tech)
!endprocedure

!procedure ServiceStorSimpleDeviceManagersCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceStorSimpleDeviceManagersMd>', 'Storage', $funcName, $content)
!endprocedure

!procedure ServiceStorSimpleDeviceManagersGroup($id, $name='Service Stor Simple Device Managers', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceStorSimpleDeviceManagersMd>', $name, $tech)
!endprocedure
