' definition of the Item simpleicons-14/N/Notist

sprite $NotistXs [10x10/16z] Oy06-Fdv6NZu-Nd0B7uk49S1Wm2huu3mMC528C07aG2I2

sprite $NotistSm [12x12/16z] TOR50O1G08MmM_QVrhhuyoLKjIXihi2fZgeTREg1sl2kt_Bj5F0t4MyU7u-gJJSsl9ew8jq

sprite $NotistMd [16x16/16z] bOk53O0040EBEzr_Mrx3nv2BLV6RW-I2Xa8ZriHyK3aXkBAOObDGR-BdoFFFulC-0dlrzunT-k08Fr8vzNVE40OH7Lwv

sprite $NotistLg [20x20/16z] fOy53i0W34N_7E_zJpjfg8J5UVWhLaooXRZp6ECAXXYWy5Yyeuuu9lrS0-Be06HrAy-Y10_0dx2ZLQRZTS7V6-M4kB1MEim9LrLtTXNGBCaWuHaU

!procedure Notist($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Notist', $name, $tech, $desc)
!endprocedure
