' definition of the Item simpleicons-14/N/Ntfy

sprite $NtfyXs [10x10/16z] Oq00VXXWv82AS36oCqDOd8piG7aC5ZDO6rWCgeu5RWedt6

sprite $NtfySm [12x12/16z] JSO50W0X20NHptOwzp-jNK-1qMpzcbNi3URKkDYSe_NJ--Rj_SSBv6vYsrrnmLEP9W4

sprite $NtfyMd [16x16/16z] XSsr0G0X343HSy7-_jkI1hVNG7nReRHHLlTEp5d61hUN_P37Fnp5_2E_J-Jx4VrxnnzfRWgFiUSsum4

sprite $NtfyLg [20x20/16z] ZSw54O0m44JHnPtVVxSC7a_U-EcgL8Mh4kmsg1XbcwaOdDh4MMlmQpKiRaq26hUcrQjDWFTZhy_qfw_MwiJfhJtQarLpxqqcQF6CCsn3PP8cbJa

!procedure Ntfy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Ntfy', $name, $tech, $desc)
!endprocedure
