' definition of the Item simpleicons-14/N/Nushell

sprite $NushellXs [10x10/16z] Oo0Iy4CX0m-SnS8F5yKF

sprite $NushellSm [12x12/16z] Oo0HC38mWoWc1bu61duGbnL4CV4Ys0myO3ORaCt8ny0DOdDoSHDhFW

sprite $NushellMd [16x16/16z] jSUr0O0m002mu0x_NujRzpPR9DHW6Vg5YVv8PK-RFLSk-vllmdUpwtrLJeovHoQI3G

sprite $NushellLg [20x20/16z] pOk50O1030FJnpNxRylXDW3K6z4_8kRHHjFNtEtQxGXgq_nqedbwER7YWgdo6ylVs73pjdJ3lMCQHfTWND_51

!procedure Nushell($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Nushell', $name, $tech, $desc)
!endprocedure
