' definition of the Item simpleicons-14/B/Black

sprite $BlackXs [10x10/16z] XS750O0m0C30u4xsdnPfdxKx6gv3dLVGiVDptkfrCo6hqGISypRVPBq

sprite $BlackSm [12x12/16z] ZOh50G11309PjmJwh_QqWSm7HP3SHqclILkc1mv0dEIRjb422_la4SxIwdMDtfxJ-k-x8S8D

sprite $BlackMd [16x16/16z] hSt50K8n303Gjd7VVreS5k2_Kpph2XjOu7mJpPwdSdsaNbx6ynR0KoEExzJ7dwDhpcufQ9HPqLxQiRSqO_4wEZ-jpmSWaLMPhdlzxGu

sprite $BlackLg [20x20/16z] {
lSp50GKm20DGgZZPVzhlka3V4PBGENriNgD_3xaT3xL57XUnYk32wwnCf0ZOHCDRg1RSc3VuVO4zEeIHKfDo5J5ys80O-aZYQCKHK1B1lzM8kjhta2Rq9B6t
A6--RHvo1G
}

!procedure Black($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Black', $name, $tech, $desc)
!endprocedure
