' definition of the Item simpleicons-14/B/Bmw

sprite $BmwXs [10x10/16z] FSd50O1G0CMmuCxRVrgStsC3KteG9YPILzLgQpk6v8Cg0R6IX1vITjAhJKeTr9m

sprite $BmwSm [12x12/16z] 7St50KKn202mFAsN_QVzWeSJO4G5TC_DXhjuK1fzzXdgszh2ZC3f64Hw4I3ohbbfU4ZUDjVwKw415gn3VlG5

sprite $BmwMd [16x16/16z] {
DSdNeO0m3C30CnsIsFjF-mhbyoHW7TK2m5YarRK13IDtvd6pDPQOnAupZ6khCkTyTc7XZuKUv8gwJMSPnEU68g3Us33ZSo1VxnmkzDk9OOFHxdjZ010RT83j
9f4BZW6_
}

sprite $BmwLg [20x20/16z] {
JSd5eUqm5C30CIN6dFwh_VWkQ3a264_iorVjL4rE_QGNHS8P2sC0ksNKyi_oX6ZvITBSDsVLrcYfdvaZGbuhZrKEXxl4NoD5HLVn_9ZQS0PIl4oWFvWVcoY1
3U9ryiQTVLkv4fQN7KmTAxqiOJiGzRzTo5aQq6D6d0I1aNstmMpVb85sNfA3L_tqailS6Vm6
}

!procedure Bmw($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Bmw', $name, $tech, $desc)
!endprocedure
