' definition of the Item simpleicons-14/B/Burpsuite

sprite $BurpsuiteXs [10x10/16z] uyS5630Od0mCcBByp70ccYm2

sprite $BurpsuiteSm [12x12/16z] uySB611CRYGsCfE10KqzGeQHW6O46m4

sprite $BurpsuiteMd [16x16/16z] uoSISABn6L2vZAXyDbGkDmCB6ufc8C1b7a89Ave02fU9WO1-8lq5

sprite $BurpsuiteLg [20x20/16z] hOwr0G0W30GFTzX_M_eqw7MHb_63oDuETbQ6B5S9GEoijPhTBe0NbaQZBXj6obPkjUEK2G

!procedure Burpsuite($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/B/Burpsuite', $name, $tech, $desc)
!endprocedure
