' definition of the Item simpleicons-8/J/Javascript

sprite $JavascriptXs [10x10/16z] uoSFCF0pCC1PS35kC9EDdu6Bduy9B0JaiV43

sprite $JavascriptSm [12x12/16z] uwSgOE1dO610i974cHcOO6mGvWKIF42rl0oC45LyF402A0e

sprite $JavascriptMd [16x16/16z] nOm50SC04CIobJ7-rPRX73JFw8SCFdGu0aFK40ijrXHcRGLDrlh7dPdfX_ntVm3q3i__P0K

sprite $JavascriptLg [20x20/16z] rSk55SGm30JHDREd_sgFKIyDv1j5d5c9zyiNVdXjT6TpZZ9jJe391SblasD8iZbe2ZpbWHDTiELvsBfZwcv_9-EZtsUENG4

!procedure Javascript($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/J/Javascript', $name, $tech, $desc)
!endprocedure
