' definition of the Item simpleicons-8/L/Letterboxd

sprite $LetterboxdXs [10x10/16z] Om02Jdus1X3W1mDE40F2OmKH311HE8iVpc83iM08QWBGC100yrcX3

sprite $LetterboxdSm [12x12/16z] BOa70i0m20BjdeJ__xPIk4Hbb7Xubg6n39980EqptMCTf7EZjq4gEgelVeqIwAWOXfD6wGS

sprite $LetterboxdMd [16x16/16z] NO-50SKm24IXZHlxJ_lbYB_gIOo0hPAP1bKKhr8cJMLpFs0KbEjgiNuXWRrqlRHSEY_TCE7KB_Q5m19Pot_To8dKjM-y5uv-b4q2taxp1G

sprite $LetterboxdLg [20x20/16z] RT3N0GKH04JHMJbF_zM-A7CtuF05DL-O3AOqQ_bfn2dVQ2vKolEU1lHkRBC7aYrtCVgBbOlnOkbYPZOWypkSbkl_tzy4diC0UAxXMrX8J5TQGy_z8VyFlG4

!procedure Letterboxd($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/L/Letterboxd', $name, $tech, $desc)
!endprocedure
