' definition of the Item simpleicons-14/G/Gitconnected

sprite $GitconnectedXs [10x10/16z] Oy0F-8602KA0U60HE0j4yl0pWbXy866GCco6

sprite $GitconnectedSm [12x12/16z] ZOQ50SCm0CCSvkZ_QyUyab4wf05E1Qe49YTm3XAww3vyiBtUkCw5e8EOWoRvNYNJkz6QpW

sprite $GitconnectedMd [16x16/16z] fOo52GDH40NFlilqtstM83YHGLQU77zp0yl7bhF3t9pD1kS1yhnYmE3MKENHiO13sJucXQBB-msNbkuaEIdL3kM8eLrpt3QcZYzv0G

sprite $GitconnectedLg [20x20/16z] {
lSo5SGCm44JH5RD-_zrcDkG236_W-FGP4s18uJWfRl4ZH7v9bnkaV0H7KeSUtRS1Vv-sKxiCMS0aW_INp4SlolmCcbF_23y_hXQi63VKmeZvGl00Qy9-NuIv
TtSIrzbDh_S5
}

!procedure Gitconnected($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Gitconnected', $name, $tech, $desc)
!endprocedure
