' definition of the Item simpleicons-14/G/Gltf

sprite $GltfXs [10x10/16z] XOR50S0m08IeUzb_siWxTWe3AMnh1YvHVvqnEzyhDnEWroTrHG

sprite $GltfSm [12x12/16z] ZSQr0S1040InUURR_girnWP5ufzgMe7JKE7am0kZqkkiI0GgaIcGhtP-04wgGERcg-VD3W

sprite $GltfMd [16x16/16z] hObL0iGW5CG6T-R-jrsSxsqRD7du05_8uhSrKMY8MPh9t88RAC-8r1PGaSTOGi5C9o5PmFRVynOBu73H9AqKDfcJXFCIp_W1

sprite $GltfLg [20x20/16z] {
lSY5SSLG3031UvBCSFrtcp5NaB_3ou-qSLMtERvI7G2whU1GkW8aXyP19xPfDr5TTSz5OG8J3DQkWKhaTnhq2XlvN02ei9O1SsDi77OTMoqSugX3gVsqRJe2
dnoxQFoJFm
}

!procedure Gltf($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Gltf', $name, $tech, $desc)
!endprocedure
