' definition of the Item simpleicons-14/M/Marvelapp

sprite $MarvelappXs [10x10/16z] Ou02VZW3pEBb1m4m7mYu-24IG8XWCO9rSO3OO1O_XCNApy0ECOm3PYO

sprite $MarvelappSm [12x12/16z] FSQ70O0m30D1qJk__xIGkDlIAUUOYu3r3KDu0bZT3ZRp8zQPpWUjw3LZ84tvx1XsyoGD7TrZG3y

sprite $MarvelappMd [16x16/16z] LSk50OH044FHuCxhlzeJdBywaJmOvZn1avrECc7Onnbn-HMi6guYckAO2ugEZAPjNibY3SKsquKsTtq_nzo-vwrQF6R6VMxwOsuIIqweyeJoCNq1

sprite $MarvelappLg [20x20/16z] {
NOw54S0W5CLU7S_-s_QmGr8bNxLYqGwGDfM0aUZ1wsDs4K3CxYBZ22MzGaCEpf5sn9m2Z3IRPsfrzNM07QNPXVntzDruSyeZjvQQF36iBezONAo1KNk2QqxM
LFU0aJxGu8DB6sQu0Hoh-04
}

!procedure Marvelapp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Marvelapp', $name, $tech, $desc)
!endprocedure
