@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-14/bootstrap')

' loads the Item which embeds the element Matterdotjs
include('simpleicons-14/M/Matterdotjs')

' renders the element
Matterdotjs('Matterdotjs', 'Matterdotjs', 'an optional tech label', 'an optional description')
@enduml