' definition of the Item simpleicons-14/M/Mojeek

sprite $MojeekXs [10x10/16z] Oy06-FaO-Db190CFFmHm00M1Y9M1dmT8GH0ZdCK0Pm4n530XZ0C

sprite $MojeekSm [12x12/16z] ZOg53OG040Jt7zVflri6YsANt7e-N0SpqFawAFoqk_OdF_xir_blUl1_s-RCUdtyHls3tDm2

sprite $MojeekMd [16x16/16z] bOYr0G0X0CI2ExV_jizxJOgSi8l92K8nu8g58cbg4KvbQ4vIcezONFxrLtCrftbAOA-Tr9VEqsi0JGMwAjIp8JcOYkUMpcqUcNDlSW

sprite $MojeekLg [20x20/16z] {
hOzL0e8n3CRokstxxdzQ93Yla6czvT-CIOCzMM3opvOaBLSsdm0f-MG5NIkikWp-uT2_JoOWAG1LtUJTMGiinlxmxdYw5tM3DoGxq9IsXyxo5cH_wWRlup62
mtNgDkkg-sBg-OKp
}

!procedure Mojeek($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Mojeek', $name, $tech, $desc)
!endprocedure
