' definition of the Item simpleicons-14/M/Mongoosedotws

sprite $MongoosedotwsXs [10x10/16z] Om01VWO8uERdvuSoG036u08nWPYLdm74XP0i32112624iA2w8GmmW3

sprite $MongoosedotwsSm [12x12/16z] FSa73e004091xDtz_syz4axIPeEy6VLUOF_f21FcT39C5JDS0-GrlHU5lYHwalPmK2Ai23y

sprite $MongoosedotwsMd [16x16/16z] JOc50G112CFwxdJ_RR-SGKuJKBcu8a5XmoPoX50FeH7qtjxc6hnFDxdPxU5orNY6NegcUX-kr9vBDhzm4j802s39JmZBsa9eX0i36zCV

sprite $MongoosedotwsLg [20x20/16z] {
POq73e1G2CMUUzlxtzQ0p_cR1Kq3abaPz6KYgDzguQIeilnKfgXSkae_hrcwwdV1DWq4bNobYraaPrv1rmZMEbCh6XfeYNImOci0HjKWAnF5h9zYLy27BLtz
LQPKBgqUIkNdivS3
}

!procedure Mongoosedotws($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Mongoosedotws', $name, $tech, $desc)
!endprocedure
