' definition of the Item simpleicons-14/M/Moodle

sprite $MoodleXs [10x10/16z] FOg50S1020Elxit-qxuXXvFGkBJJqU1gYxEXnw-hRUxv7jH3-nKRoksI0Mo-L

sprite $MoodleSm [12x12/16z] JOd50S0m3CHKvjx-quOJMvy3aNbqKb75rJHoVPSrzu_gpYUDvqtZO6PAOnUVq8gIj8vy7noCyPFu-Xi1

sprite $MoodleMd [16x16/16z] NO-50S0m20IlxltzfutxHN4Wi7rw9ZAV8aSKLVYZM7cZyt_Egm8JqWgSIcp_vcNcbDSVM6TNCgRwzRDeHGhoCyYJUfbU_jdL4giKTXnlByBKJ6C1

sprite $MoodleLg [20x20/16z] {
PP054i0W40E3Jj7y_xST9DN55pziKcUDU12uQKQA3zAjRlAjReBEoivwoRciZEK7nG6Twfg5IHmahSiOsE7wADO40ev9DxQnZWGIstALwUSY_mxarpMqdxCm
_08W_HMG-SGgf3SG2a1RYqu
}

!procedure Moodle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Moodle', $name, $tech, $desc)
!endprocedure
