@startuml
sprite $AwsCloudformationStackLg [20x20/16z] {
ZP050eGm30JfIlB_5v_iASuWRLm6k013xGKjQLgWwxhYWXAy0gmtKhsXD0AhECAl1cmiwYvqwzYj6d3Aom_q4IfjjaZrMqWDsTC3Ey9rNTlk_Drl8Rj7_iHR
k0C
}

sprite $AwsCloudformationStackMd [14x14/16z] NOk50GGW30CRst_a5nokBf4F576X6BM0GomOvy29xPNJT4dJFTFzwRIO3Q4OS0J6A4PL2gkj59EzaMrv97q1

!procedure AwsCloudformationStack($id, $name="Cloudformation Stack", $tech="")
  CloudElement($id, 'aws/ManagementGovernance/AwsCloudformationStack', $name, $tech)
!endprocedure
!procedure AwsCloudformationStackCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsCloudformationStackMd>', 'Cloudformation Stack', $funcName, $content)
!endprocedure
@enduml
