@startuml
sprite $AwsPersonalHealthDashboardLg [20x20/16z] {
hOx5OK9H54GJOBJ_Vh_x5ixJwzDlCUNMedTFI0aa93AhJvnlV6QJMdtmV4jpVNZrDM-UFir_rS1P6pfycuAzpx006eW0g2i9qmyQ9kcEM6TjTaBjEay26-dJ
URXExFw24G
}

sprite $AwsPersonalHealthDashboardMd [14x14/16z] XSYr0S0m40J1o4Vzzok6p5hXVFuJQPDQi01v4kuJnUoYu_3pb6YG43K50cex8wh5h0otdSk6cvHd5G

!procedure AwsPersonalHealthDashboard($id, $name="Personal Health Dashboard", $tech="")
  CloudElement($id, 'aws/ManagementGovernance/AwsPersonalHealthDashboard', $name, $tech)
!endprocedure
!procedure AwsPersonalHealthDashboardCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsPersonalHealthDashboardMd>', 'Personal Health Dashboard', $funcName, $content)
!endprocedure
@enduml
