@startuml
sprite $AwsSystemsManagerInventoryLg [20x20/16z] {
POi74W0X20Eb9Fp_nuTdrnrfwwGCLCk5W8GSnccb67tPUgolYcuX0NNqXHBY4FCD4sJNS7Y-HcZj2aG-Rrbqns2-qnait-aG_JtPV4ystv5Txydcwuujs1v_
9y6Da5HqnqOLwW_w0G
}

sprite $AwsSystemsManagerInventoryMd [14x14/16z] JSo70G0n2090HVZzHtvCl_HOOgYA0wmYOaWot_t-iXua98emeL-VXR5VZdY7NolMRgnbhjYA2gkdUGDLEahqM2Z-

!procedure AwsSystemsManagerInventory($id, $name="Systems Manager Inventory", $tech="")
  CloudElement($id, 'aws/ManagementGovernance/AwsSystemsManagerInventory', $name, $tech)
!endprocedure
!procedure AwsSystemsManagerInventoryCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsSystemsManagerInventoryMd>', 'Systems Manager Inventory', $funcName, $content)
!endprocedure
@enduml
