@startuml
sprite $AwsSystemsManagerOpscenterLg [20x20/16z] {
NOu5WaGn24C94lhlV-45oexL-v14QY2OJz8XyFuFSYYXxXBBN9kpdn6BxetQHbnca1rLZtYXmM0r2QjNGlR5FYoQAJh5hYIijHvo86CwPaxjUiJgT1ULzzX-
xbziKl2LQ6T-QrvlD-Oyl3F12GUT6mspLEE90afTDIPTxNYdv9Vgv63P6ngSyWipy0S
}

!function AwsSystemsManagerOpscenter($id, $name="Systems Manager Opscenter", $tech="")
  CloudElement($id, 'aws/ManagementGovernance/AwsSystemsManagerOpscenter', $name, $tech)
!endfunction
!function AwsSystemsManagerOpscenterCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsSystemsManagerOpscenterLg>', 'Systems Manager Opscenter', $funcName, $content)
!endfunction
@enduml
