@startuml
sprite $AwsTrustedAdvisorChecklistPerformanceLg [20x20/16z] {
XOo7aGCn4CEq99Rw_Xj-1vt6sSPa1XGtD1Q4JVVE6ECOw9P1XW7xbf5woSP6ltso_UBhRjxuIguhDr_DB2RBvqPPlncMJ_RE_YQmTUTCLH4m-mfATP8sb0yK
Ow4qOrEnMgx73A4ku9PD5hbbWqsT
}

sprite $AwsTrustedAdvisorChecklistPerformanceMd [14x14/16z] ROm70W8m20EXkTF__zWEjruda2Ioa5euHdhYhc3M44urKZqvbTrPBt-LNLDwedRch0Iy2FOuGgwwbDNKQ6Da4a2WDcr8V5KJh8C2vWO

!procedure AwsTrustedAdvisorChecklistPerformance($id, $name="Trusted Advisor Checklist Performance", $tech="")
  CloudElement($id, 'aws/ManagementGovernance/AwsTrustedAdvisorChecklistPerformance', $name, $tech)
!endprocedure
!procedure AwsTrustedAdvisorChecklistPerformanceCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsTrustedAdvisorChecklistPerformanceMd>', 'Trusted Advisor Checklist Performance', $funcName, $content)
!endprocedure
@enduml
