' definition of the Item simpleicons-6/Q/Qgis

sprite $QgisXs [10x10/16z] LOg30G0n54DpPllsdxRcPwHGBvTYaIk1H8qYIF3ZBCYow0J1chBlAtAEUfcX1m

sprite $QgisSm [12x12/16z] BOo50G0W40AnM_RVLZ_E-0G8YmDAfE7fB4iBwsWCdgAGH_ArTN0bru-i4X8Hy1EATqgIOPCB26Pt-CdPYg158Hy

sprite $QgisMd [16x16/16z] NOo54G0n3CFo30NjFssPTP0OpfAu3MgN2WMLr44do8t04vu_6yKknIVgJJ8Vy88TXotywJEBZWRmrQJqXV9AB4PT1ud69pk1FUayzP0uct6CXaHsaoF00m

sprite $QgisLg [20x20/16z] {
JP1N0aGn14N9wwJiVxSpQjmVSgA3gT5Suu4YMg4hObQLeiFymTEiCFLk47M7B1R1zCYZQTZfo2BuyBgr7rknbB2eTl_juMmcCoX6Lf2TBg-gZQC7BI0Y50Yv
9QcBRP7jNteYe7lFFW_MaSu2suQypqKLvghdIqmFshb-
}

!procedure Qgis($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/Q/Qgis', $name, $tech)
!endprocedure
