' definition of the Item simpleicons-6/Q/Quantcast

sprite $QuantcastXs [10x10/16z] Om02Jdus1X3W1mDM1WPsVdum5uB1J08iJeXYVhWft60PNduke1W

sprite $QuantcastSm [12x12/16z] POtL0S0W30LVtNlxJuj4lZY8cpeFbnoSS8_vjk3rp0IpuCnEmMJ-DVXNzbXi7fEPvm0-DNwCMSQyzMEg

sprite $QuantcastMd [16x16/16z] HSs55SH0203HYMTr-g_sZF3khml0pp5i2saOJduqDO2fxa1H3rZK2BrKcDe8wegw4PfML1wtJZ8yCdQoRbGwdgmisxR5Jgsnw01srN9DC_DfElw50o4ClNa3

sprite $QuantcastLg [20x20/16z] {
NSw50G0X20NGRoUo_xQ7mTMp4x2PCfWYNX8VP77mIy3IrwAM_cokX_uvXTXRsv1v0u8C1BKlLkbt4dhHddxJ6_ksoh9Awvw1AkjUUn8L92k7A7t_nGMV87Q8
Sw7e9l42w9noQinFhlpIdWmUk7cIPSspmy--U04
}

!procedure Quantcast($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/Q/Quantcast', $name, $tech)
!endprocedure
