' definition of the Item simpleicons-6/Q/Quora

sprite $QuoraXs [10x10/16z] FKg54S0W36nnP_zfetz4tpwfTjAdTQsgWQadoe7JRtkP3oZV0uJSaDSbW506P

sprite $QuoraSm [12x12/16z] JSR50O100C2muaxtdnOvpoi0xFT2P4Hi5De1cnx4mgc74gdDr-Re71lk7Zk1sG1S6hq

sprite $QuoraMd [16x16/16z] JOw50S0W40Dnb_stRPh73dsF8gwDeWvz2bxCUMZ7hANpaUJ0l86VLiUKJ8-Z5XP_f7FIqpczTiL-RVtKn_zF6KJp6t0FpIWuwX_1xPYhjtaS7m

sprite $QuoraLg [20x20/16z] {
RSo50SGm3C10bxct_xGFPOY2bY4sscaUohXGsnZpNRdGnCBiIdjM3Va-eOXee8-54aISQczgCeY35dE7DavWHZoSX1kHFro5-LGvX5lXX66vxQg7OgrMBusZ
RLBdpjdmb5LAHklA5m
}

!procedure Quora($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/Q/Quora', $name, $tech)
!endprocedure
