' definition of the Item aws-q1-2023/Resource/Analytics/AmazonRedshiftDataSharingGovernance

sprite $AmazonRedshiftDataSharingGovernanceXs [10x10/16z] LOg30G0n54DpAD_-yzRyZ7GLru6blolmwb6TYaQY8YUwDkiLFg3Vy6O

sprite $AmazonRedshiftDataSharingGovernanceSm [12x12/16z] NKk50G0W20FRxVz_xGvOod-GZJfqg5FfM85SRyVrIfI9nOCLppXHCHYPJxUUYPa80XNNj1KpzKp7L44T1G

sprite $AmazonRedshiftDataSharingGovernanceMd [16x16/16z] {
ROw50GCX54CV3id-yrQGwg7V8bolOajstAdt7yjd7blKobMaCHJJoUVR6YTFoXDryXwigfs7JJhpwk3Wnfiex86JanXGwTk8kehTL7R-kKGGPeIP1K6XqodG
UmNk
}

sprite $AmazonRedshiftDataSharingGovernanceLg [20x20/16z] {
VSi53WG120J1XXLa_l_Ui_MppiGgmByiIbA57QHaARLHi3VwPjgk9kt6tAggflsmxMuycOK11ISJ0bsjvfRenMmRJ5fDZd2z45ucMgZHoJvQB6PSi6onERDx
baR9_lpMkgqoGfMgKi8uJY4v6BOCpDq0xW
}

!procedure AmazonRedshiftDataSharingGovernance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/Analytics/AmazonRedshiftDataSharingGovernance', $name, $tech, $desc)
!endprocedure

!procedure AmazonRedshiftDataSharingGovernanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonRedshiftDataSharingGovernanceLg>', 'Analytics', $funcName, $content)
!endprocedure

!procedure AmazonRedshiftDataSharingGovernanceGroup($id, $name='Amazon Redshift Data Sharing Governance', $tech='')
  IconGroupElement($id, 'AnalyticsFamily', '<$AmazonRedshiftDataSharingGovernanceLg>', $name, $tech)
!endprocedure
