@startuml
sprite $AzureCitrixVirtualDesktopsEssentialsLg [20x20/16z] {
TL070i8m20mnX3CS__-kDBYrksNSQe88phOFOmIaoU9K2nmbq7Ho2TZpRmHw1o_vsOcejU6aZmA8q88ILQal3Th-w22HA8KQuoYvgxeNz6o8aQKbkRwoEBO4
kEIrCVqgn8QYKWi-FzZFQk-x4DzmlnppLuiHtvgD_xo5FJFW8uFth0gQa4LJLAO8g759PMy5DIlx6m
}

sprite $AzureCitrixVirtualDesktopsEssentialsMd [14x14/16z] LKu50iG0208s-__llOxPhJ1dYW1h9fafHaaLLEO8W7VxmsbUcI9URYg0eoFw0A9OhZw1i-L5wD70WnvjOMTxSb-vVk3ixtzaKkP6VGS

!procedure AzureCitrixVirtualDesktopsEssentials($id, $name="Citrix Virtual Desktops Essentials", $tech="")
  CloudElement($id, 'azure/ComputeServiceColor/AzureCitrixVirtualDesktopsEssentials', $name, $tech)
!endprocedure
!procedure AzureCitrixVirtualDesktopsEssentialsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureCitrixVirtualDesktopsEssentialsMd>', 'Citrix Virtual Desktops Essentials', $funcName, $content)
!endprocedure
@enduml
