@startuml
sprite $AzureBatchAccountsLg [21x20/16z] {
LSz10eGW34DHaYQT-zzu0CJQl-jJ07uLnks3V36hGbS07fI2gx3fr65DdKaJ6TRzSoVd_8k95oKTHFAYBaBfM6Xzba_4njiPzt9KQo0nUgpNLh0aanr5XXdi
Q6Sor72P3rQCMM7fQlIecVy
}

!function AzureBatchAccounts($id, $name="Batch Accounts", $tech="")
  CloudElement($id, 'azure/ComputeServiceColor/AzureBatchAccounts', $name, $tech)
!endfunction
!function AzureBatchAccountsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureBatchAccountsLg>', 'Batch Accounts', $funcName, $content)
!endfunction
@enduml
