@startuml
sprite $AzureDistributionPointLg [18x20/16z] hSx50G0X34HHB1FhlzurdFF-uqEIIAqKMcJcJsQOelAs2jCJ3EShN-Nj9t7_9BsRLc52Ve2VnSehpeL7ZwWgmKSWGoa9Rhr7J0sxd7VQFwleAI6-RV9LCCet

sprite $AzureDistributionPointMd [12x14/16z] XSp70OG020J0Ks4J_TThzdtp8cxnilukZEtKKmk0ttfoUklygRTQEHDWMufg9cHkf52QcsYsxjmXBNnr0VtT_4wjMny

!procedure AzureDistributionPoint($id, $name="Distribution Point", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneSystemCenter/AzureDistributionPoint', $name, $tech)
!endprocedure
!procedure AzureDistributionPointCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureDistributionPointMd>', 'Distribution Point', $funcName, $content)
!endprocedure
@enduml
