' definition of the Item aws-q2-2023/Resource/Analytics/AmazonOpenSearchServiceTraces

sprite $AmazonOpenSearchServiceTracesXs [10x10/16z] Oq0676220qGmCpCpCZ03EK0U9W2ACpCmmJXip9WAM3aGIW4

sprite $AmazonOpenSearchServiceTracesSm [12x12/16z] TOo30G01200lj__2R-CokQ8YB2J876OeX8roFgajTdUknLR_xESMj_-S_qS

sprite $AmazonOpenSearchServiceTracesMd [16x16/16z] VKk50S0m2Aj1yl_5Mzq5Yvdr4O0E67yNx49m6GjLLNuQHKVEyh__5mfkxuB9Xacg_dlKlVTkpJ-nICLYhJK_ai6puEp_

sprite $AmazonOpenSearchServiceTracesLg [20x20/16z] dSxL0KCn34DHcRN_mkrZvlkN4pAEAhQjhLlEHd8owK808QCPhKaQiz6cwwm2sDNPfhScvLnOcoMWiZddXjmQalRrNtZArZoM5wIQvbaM2VNWOG7-

!procedure AmazonOpenSearchServiceTraces($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/Analytics/AmazonOpenSearchServiceTraces', $name, $tech, $desc)
!endprocedure

!procedure AmazonOpenSearchServiceTracesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonOpenSearchServiceTracesLg>', 'Analytics', $funcName, $content)
!endprocedure

!procedure AmazonOpenSearchServiceTracesGroup($id, $name='Amazon Open Search Service Traces', $tech='')
  IconGroupElement($id, 'AnalyticsFamily', '<$AmazonOpenSearchServiceTracesLg>', $name, $tech)
!endprocedure
