@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsFormatColorText element
include('elements/materials/Editor/MaterialsFormatColorText')
MaterialsFormatColorText('element', 'Format Color Text', 'an optional tech field')
@enduml
