@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsFormatUnderlined element
include('elements/materials/Editor/MaterialsFormatUnderlined')
MaterialsFormatUnderlined('element', 'Format Underlined', 'an optional tech field')
@enduml
