@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsBorderColor element
include('elements/materials/Editor/MaterialsBorderColor')
MaterialsBorderColor('element', 'Border Color', 'an optional tech field')
@enduml
