@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsMultilineChart element
include('elements/materials/Editor/MaterialsMultilineChart')
MaterialsMultilineChart('element', 'Multiline Chart', 'an optional tech field')
@enduml
