@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsBorderStyle element
include('elements/materials/Editor/MaterialsBorderStyle')
MaterialsBorderStyle('element', 'Border Style', 'an optional tech field')
@enduml
