@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureNetworkSecurityGroupsClassic element
include('elements/azure/NetworkingServiceColor/AzureNetworkSecurityGroupsClassic')
AzureNetworkSecurityGroupsClassic('element', 'Network Security Groups Classic', 'an optional tech field')
@enduml
