' definition of the Item simpleicons-8/O/Openbugbounty

sprite $OpenbugbountyXs [10x10/16z] Ou00TZ39oS30pmzcyVE0I0WJ211CA0rZSNCZP1aGwe0Gmc01aG

sprite $OpenbugbountySm [12x12/16z] Ou01FWIBdn_2u0SYE9kV4GWOO1ouE0ChY0tJXy660IGsaZWVa04ran4g1W

sprite $OpenbugbountyMd [16x16/16z] NS-54O1040J1Ezmt_sXncAsVCfhte7eBJzB_sT_4YcpFFgzQyihNCfyVUFiCi30BC9CAohduUoOfF7W

sprite $OpenbugbountyLg [20x20/16z] ZSyt5W9H34DHpSzP-ryj6NJiYbjPhpECUk0KabgzlP9fhvk-BNYDBDSBPFC3aA4c_xJ33xL8qHlpGKsAcgZPH9zmsRR90AkG2KxZrBW3

!procedure Openbugbounty($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/O/Openbugbounty', $name, $tech, $desc)
!endprocedure
