' definition of the Item simpleicons-8/O/Overleaf

sprite $OverleafXs [10x10/16z] Om03RZukCCtFpy_63sAmymFP425EPWO8WuSV8WGXG2H41IgB4yo5ge7e

sprite $OverleafSm [12x12/16z] JOc53G0X40JV7v_-kuMpX9F9oc6J6RyfW8xBTY9IzC4kxv3jXIBo6y878Q-rIV2RpWiLqwSIXnbCJW

sprite $OverleafMd [16x16/16z] JOw50GCW30I3ExV_jDM7zj3uso6llPkJuVZIP0Fanf8vmMV01Ds0TSsG6NQX5e0kS-EIMRZDYNhvFE5qhOJtq_wdl2X8f5U3CtShe4aDVkBda5fbSiqd

sprite $OverleafLg [20x20/16z] {
LP254SH0200XdXEs_shV61wo8xXAidKpQtiw5WDd2TVfzc6S4W2qfSEGajQb0JEx6UgfwGAvnoeLJ0R0MGlT1Vs_ActzxJGo4yf2wGlY22qx6RSVYaamQPxt
gBrSoUqLrBKRzeYIdMdgxogtvJkJwtdP6m
}

!procedure Overleaf($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/O/Overleaf', $name, $tech, $desc)
!endprocedure
