' definition of the Item aws-20210131/Resource/SecurityIdentityAndCompliance/AwsDirectoryServiceAwsManagedMicrosoftAd

sprite $AwsDirectoryServiceAwsManagedMicrosoftAdXs [10x10/16z] LSj50G0m30J1BPD_lMNAV8A7KFHjxLb1HahCNS816D1OCypytKsnbDW

sprite $AwsDirectoryServiceAwsManagedMicrosoftAdSm [12x12/16z] NKm50W0X349Til-_zpfT1u3PwXrRUnS2UesofH_JrOEnrvkzvRWeuAL72oVqC7ORV6Mtl2mgi08

sprite $AwsDirectoryServiceAwsManagedMicrosoftAdMd [16x16/16z] ROo50S0W30JpVPpzzotkXrvCtiHT3VpcGTogVk-0IHTv30jTgQh7n99ckhvKPD3AZJEIt4lrTWTK0bdokf7SVAnLitwwzWIzbWa0aHy

sprite $AwsDirectoryServiceAwsManagedMicrosoftAdLg [20x20/16z] {
VOx50G0n2C0eBllFU-xIl20ez8Ytgi2dee1wkacmNiMMvxDjWcxIrlrvFNCsj6CIrxn2LQDcpzkxihQ7hWTM9vQP9Zg7koEOGLtRDiV099DpfWqX1wqsEPO3
Kb6ooPsS-ovEj_DmmMl6uOiH
}

!procedure AwsDirectoryServiceAwsManagedMicrosoftAd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/SecurityIdentityAndCompliance/AwsDirectoryServiceAwsManagedMicrosoftAd', $name, $tech)
!endprocedure

!procedure AwsDirectoryServiceAwsManagedMicrosoftAdCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsDirectoryServiceAwsManagedMicrosoftAdMd>', 'SecurityIdentityAndCompliance', $funcName, $content)
!endprocedure

!procedure AwsDirectoryServiceAwsManagedMicrosoftAdGroup($id, $name='Aws Directory Service Aws Managed Microsoft Ad', $tech='')
  IconGroupElement($id, 'SecurityIdentityAndComplianceFamily', '<$AwsDirectoryServiceAwsManagedMicrosoftAdMd>', $name, $tech)
!endprocedure
