' definition of the Item aws-20210131/Resource/SecurityIdentityAndCompliance/AwsIdentityAccessManagementTemporarySecurityCredential

sprite $AwsIdentityAccessManagementTemporarySecurityCredentialXs [10x10/16z] HOm50S104CCCB8b_jQEdOsZRR-Ae81HeNgGeZW9OZ3Ccu-fVGiBVK8_o0m

sprite $AwsIdentityAccessManagementTemporarySecurityCredentialSm [12x12/16z] BSi50G1034BH0l3fttRwJcTvDlFG31k85ibRRd7_wSus8TftcotzS8AwzS3M-P4Nd6Fc--PR

sprite $AwsIdentityAccessManagementTemporarySecurityCredentialMd [16x16/16z] JOo50SD04CC6U4lUVzg22ucEiHTgRmJ2Cc2vnBP6jviSDn-MRAuYHabBO6zSD6mnmNLFqggoXWdxk1tRe57ZaerifLWq3DV6gYEqfdyCnDxGjay

sprite $AwsIdentityAccessManagementTemporarySecurityCredentialLg [20x20/16z] {
PP370KDH2CC6Y6JsdpO57cbV9qo7-Y59_H80LwLvwQnJ6iVAk587rbUWYklRxYAszTA26vaqiIUQuVJAPBGr-JVO1VtqM9zx1tvgey6TqT6KLgZItQN5AnIo
473IEKo3hltGpf3hJzVreJqF
}

!procedure AwsIdentityAccessManagementTemporarySecurityCredential($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/SecurityIdentityAndCompliance/AwsIdentityAccessManagementTemporarySecurityCredential', $name, $tech)
!endprocedure

!procedure AwsIdentityAccessManagementTemporarySecurityCredentialCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIdentityAccessManagementTemporarySecurityCredentialMd>', 'SecurityIdentityAndCompliance', $funcName, $content)
!endprocedure

!procedure AwsIdentityAccessManagementTemporarySecurityCredentialGroup($id, $name='Aws Identity Access Management Temporary Security Credential', $tech='')
  IconGroupElement($id, 'SecurityIdentityAndComplianceFamily', '<$AwsIdentityAccessManagementTemporarySecurityCredentialMd>', $name, $tech)
!endprocedure
