' definition of the Item aws-q2-2022/Resource/Compute/AmazonEc2HabanaGaudiInstance

sprite $AmazonEc2HabanaGaudiInstanceXs [10x10/16z] Oq0576n876PK5WSBCpE8nG4Lus1WOs1bO6LYP6P3LiSC1gn8vW4

sprite $AmazonEc2HabanaGaudiInstanceSm [12x12/16z] LSs53GH030F1ENBIVyFFkBBGv9yCJQ3pWWJGCSA06cIilSy-eJ-P9fozfaACCV2_GtKzjFz-hm

sprite $AmazonEc2HabanaGaudiInstanceMd [16x16/16z] RK-50G1123B1_HV-Zkko0Lai2AMEYyVdu_DsNTzr1a3z6t6sDFxPJ5KFYBiwUENLCoqjylIgclgggp-laBtz4f7fcW8EyvVunBjghGU2myVbxm

sprite $AmazonEc2HabanaGaudiInstanceLg [20x20/16z] {
bL250GCm20kU_ozUVMujxe1tBn406qD-i4Mn_Kras0etpxejatUsIdaP5y5605csZ1bNX8kr3xVJ8zmCfitK243Uzo1rngbDm-qiaV1mTRcPnTmjpAtPzByz
xER5d4-a94KfPKtwT5Df7zh92Bi
}

!procedure AmazonEc2HabanaGaudiInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/Compute/AmazonEc2HabanaGaudiInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonEc2HabanaGaudiInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2HabanaGaudiInstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2HabanaGaudiInstanceGroup($id, $name='Amazon Ec2 Habana Gaudi Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2HabanaGaudiInstanceLg>', $name, $tech)
!endprocedure
