' definition of the Item aws-q2-2022/Resource/Compute/AmazonEc2M6AInstance

sprite $AmazonEc2M6AInstanceXs [10x10/16z] Oq0576n876Oq5WSp8uZ5mS36mix2o0oaeR9ioEgOmO0LoJm

sprite $AmazonEc2M6AInstanceSm [12x12/16z] NOs50G0X4CE2jTr_uNSbS6xyKI4WWEW293Y8ABVl0Wfn0q7aOOUH70DISpSWE9ZsuFZu_NTt1G

sprite $AmazonEc2M6AInstanceMd [16x16/16z] RKy50W114B65_t_u-hPx6jWiGl1r-VdwVBrk2l_IvL6XDP80El-wwlDwyaA91kAJjuCKeuXGQBzvHETu-Tl-pj_YY__oNW_1o-VZdm

sprite $AmazonEc2M6AInstanceLg [20x20/16z] {
bT3LOGKm20NGSoF0_XFtf-ulmHtyzCfb5FMBxVRqz0i9QE_U3ghcWwqhtyRT-p6kRj26iISlSRI-IdEklJ0pkkgapv6xPnPQSxHgztMMWFNZBEknFVQxTmEI
JcLDUgVpsqqZB27m1
}

!procedure AmazonEc2M6AInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/Compute/AmazonEc2M6AInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonEc2M6AInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2M6AInstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2M6AInstanceGroup($id, $name='Amazon Ec2 M6a Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2M6AInstanceLg>', $name, $tech)
!endprocedure
