' definition of the Item azure-4/Item/Other/ServiceResourceMover

sprite $ServiceResourceMoverXs [10x10/16z] 7Ko14G0n1Bi3RO7zjtrv09BCJ1g_tjwFYKXZ1WF6cYixiXecOJ7x9oOMt9uocyXEvU--Umeo6HxGWoM63m

sprite $ServiceResourceMoverSm [12x12/16z] BOs53G0W30IJokEm_xRKBbPvUSO6z_kSEvY8TDfub09kzstX62LcOIPMv2mi2fzNd2NkKqslziHzPtHeRuBbJTCOeygEhJOMEyOF

sprite $ServiceResourceMoverMd [16x16/16z] {
LSy53i0W58FXv1aEzx_jraxver-dB3P2OgodcLL4hCwBpUNA6uYBTrfE9zM7JfifPH6tpqNDOpC8pmI9cZdT4n_7JGwFmY422vvljUI8NCASVpXRPIK_9nZN
GjxDHdxrcmS
}

sprite $ServiceResourceMoverLg [20x20/16z] {
PT073aGX24NH11xOTV-x7Rja_aq_TjkkA24tM_4W8lRrKHHQ8MpDZkacQL01sP2cCLzXQ9u678JejJMLkrnRYY5_9i_obB4zpjeIpsx0q64rED18PAACjIbu
7MlLJzJIhSOOWdVgOqVP3oxnvDtzhfeE3hgQSpfaox6qZzrPFm
}

!procedure ServiceResourceMover($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Other/ServiceResourceMover', $name, $tech)
!endprocedure

!procedure ServiceResourceMoverCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceResourceMoverMd>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceResourceMoverGroup($id, $name='Service Resource Mover', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceResourceMoverMd>', $name, $tech)
!endprocedure
