' definition of the Item azure-4/Item/Other/ServiceLocalNetworkGateways

sprite $ServiceLocalNetworkGatewaysXs [10x10/16z] LOU50S0W40El1Lxs7nZNU7WGqnbf316gsa0-INKgfEhMAefgEvWrTTJ5XBSe

sprite $ServiceLocalNetworkGatewaysSm [12x12/16z] NSU50S1024FHZuNh_WFN_Q7XB-hzbfsl3DSUKXBhsFw6IcoX0NM1DzOhw-o6FR3DneUHWuCDRUyP9ZOB

sprite $ServiceLocalNetworkGatewaysMd [16x16/16z] ROY50S1038GYh_iltADk5mNxJzONrkftB7OJsVHxQxieJJ6MxrXXjeE0ai5dNQDz7AQ3lKS7pJj1WuYXc0Oa8PG5Bw6-udE2Tx4_2m

sprite $ServiceLocalNetworkGatewaysLg [20x20/16z] {
VOg73GH12CI6DFprt_03qkNWZLZ65nPoLHuHjofgowK2z5GQgO0ukPNEmi1cKmT7MHL85p9Yob9kXXAbe6PTPauTcGdC9o1Pj2gKTH55lvdUxwgWsJWsDVmA
dtjJq5P0_X87fjlKLbvLiImt1ILM_W
}

!procedure ServiceLocalNetworkGateways($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Other/ServiceLocalNetworkGateways', $name, $tech)
!endprocedure

!procedure ServiceLocalNetworkGatewaysCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceLocalNetworkGatewaysMd>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceLocalNetworkGatewaysGroup($id, $name='Service Local Network Gateways', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceLocalNetworkGatewaysMd>', $name, $tech)
!endprocedure
