' definition of the Item simpleicons-6/G/Gnu

sprite $GnuXs [10x10/16z] FS650OH0000WrElSVzhl5qX-Dc2bwDoj5sTkKSl1jObmj1CNLq_8qUcM5j3SziOJ

sprite $GnuSm [12x12/16z] BS65WG9G500W_alR_QUz58Zcew86rLtp9E_TnMiUwltSU8_NUUyvTKx6_MQ64suwMCawYmif9D2Q0kKuxUFAyH7FT-4R

sprite $GnuMd [16x16/16z] {
JSh50SGm34JHFyAm-gzsmQSyWn28vALwDql0B4uNRIj71gHg768cZcc8_LV_okTkxLE_Ei-gZPHRUM-7etc0hNKqSnHqWH04PYmjQ5AjjUf2t20M8o1WFK18
u9uEIz209x08JZ1UwkxYBMS4y0K
}

sprite $GnuLg [20x20/16z] {
NSR5WIWX502mm1F6TkY_sk-wEGMw_6_aUHuP2PdhM4diygzwirOFH5LaHJ3kwASmzzvNtlkOpEwhoBsVPucFtQnSVQtwuB96bZjoJx7VJURCCDdxIUagXWFl
SEN4B3IO_Nj5JAnmZsuGNHEZ8Wp0M8eneVsoB2pCwQyBPr_ly5lAnipcj-0wKVmrZITq-b_jU_jiliyDV0K
}

!procedure Gnu($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/G/Gnu', $name, $tech)
!endprocedure
