' definition of the Item simpleicons-6/G/Godotengine

sprite $GodotengineXs [10x10/16z] JSQ54O005CFGu4xstvRBAUzBov-si6AuBXCqRstiIUznS5Ssd2STTgomA6WkFW

sprite $GodotengineSm [12x12/16z] LSYr0KCn50D0VIRRj_-qeLVb6a7-RUvGVKLrNHdgB666PoLsks3y_YxsYHmFCEuzD9V9PcH3IJ81J_86

sprite $GodotengineMd [16x16/16z] {
RSk50SGm30J1CwEq_NVxZCaOHJgHGChmYZCuVEB9GrQGm7anRF9Bl-4Iz12u2VBhWG2Ew52vnNKN4BwhtU8VGIb4OAq5CqJ9sPi90me4HTXh0dCPI2e_upTn
SpDkqGK
}

sprite $GodotengineLg [20x20/16z] {
TT15WiGm40D01Us94zV_Nxiu37NhbaxA9yD9IwAljz-2fEBscu3RRqrmjYKjwJetdTAyYXTx2hgp3aaXTMrqvjDS_d_7oAg5Ifnx-gQ5HPlFF-MW3wWDoTez
EfAvJC4yJHFAiDHafUo4ex8W6L3cOKB6vRnDyIY_1cxQRTJQsjwsCkNNDm
}

!procedure Godotengine($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/G/Godotengine', $name, $tech)
!endprocedure
