' definition of the Item simpleicons-6/G/Googlekeep

sprite $GooglekeepXs [10x10/16z] Os3W1m8M1Y00irZv4In-A8iVpC9EyB12P44adCMFoW8

sprite $GooglekeepSm [12x12/16z] VSR50G0X44FHh2ly_gl5xSH8ygG7u54QaXbDytlVL_45a3oc6SoYlVawQ8QfFG

sprite $GooglekeepMd [16x16/16z] ZOh50O100CE2E-m_BUVMr-NN9i3xUKO2wnUPP7-Jx6-kzsuH_wLz0_K6c6LFrLwa3rGR9lMzUsws0G

sprite $GooglekeepLg [20x20/16z] fSe53i0m049HvaRB_Kyxt-gn_XXv0K2djnv_-XgOCIbdp9WKstpM_-PQd9ckcIAp_t8s5iq6ninF78P1aObaOjzmvget4zW87

!procedure Googlekeep($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/G/Googlekeep', $name, $tech)
!endprocedure
