' definition of the Item simpleicons-6/G/Grandfrais

sprite $GrandfraisXs [10x10/16z] BOk50S0m3CEybL7_NrjM6An5mcl3JY6zPk4acW7HaqhxF8eYsy2tSlR86O5Z9nKGIbos_3KJ

sprite $GrandfraisSm [12x12/16z] FSY50GD124JHlwum_LURd3ySJakTcoBGnS7Vrval8_biqSsisy9NPvds29gXXXtKnfnTUDce10cXQccNr8G-ZUzm3lP-_m

sprite $GrandfraisMd [16x16/16z] {
LSh50SLG24JHuHaHuFRVxNV9sOteQIQdwIDnoKxycOoXboDrn-_e8UNGJpQXS4hOsYl5T7ExvzroZtjEcP-KO_sHa-COQouijjpzg1CcRQ48hC2WLnCsWkeW
MBJ9OO4P9UUVfEHdwIulyQxnLBgx0G
}

sprite $GrandfraisLg [20x20/16z] {
PSl5eMWn30FH2L-7flzgFpo6ixCbyIh5TNU-6DuO_TcUp1lz3EFj5Nn8pfylm0P3lYc2DEknPB6Zt4YNIJ_fzeqFEpB6PAvrJD6pif-2Tn1fdJhEqzsSbT4z
M-q3JM6UKUTqwz2saIwcH-qws2qLAM9lAg-z61V4MQw7y_8xpDN4Z3QoFm7n-mNJhmelsiyMVEvF0-0l
}

!procedure Grandfrais($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/G/Grandfrais', $name, $tech)
!endprocedure
