' definition of the Item simpleicons-6/G/Gumtree

sprite $GumtreeXs [10x10/16z] Om02Pdu62E3dv-JdWR1062849LZvOHBy70WbS1OtFmCVI1bC09a5

sprite $GumtreeSm [12x12/16z] HOm55e0m3CLmXzp_jhnCsZz99krWTYPXu8EghsHLA_ZK-ZnokwcLasvawtVfDrXKhyPzuDk77XhJVm

sprite $GumtreeMd [16x16/16z] ROw54S0m4CDSvcZ_RNjXLF3PyZmSojnOvcXkuA-0_wsSsRPWekbx6JxxVApol2n5MlpoPPjuAK_OWv8fAdXWjbviEyjqIN1joXnCAZdHsFu1

sprite $GumtreeLg [20x20/16z] {
ZP250O10201Hl-lsdzRkFlsYGMQQX9S3LM4Wx6L0za3QH166mq2zCzFZcRUO5KmNHvb5DOjChJV8CgF1p-SisHxbKDOa0tUHXRrl3R8P7lC5m0oL-CJQIHmR
BGniOt7DK4LqIWv4l9p9s5-oX5ck7G
}

!procedure Gumtree($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/G/Gumtree', $name, $tech)
!endprocedure
