' definition of the Item aws-20210131/Category/Robotics

sprite $RoboticsXs [10x10/16z] HSh50S1G309GgiZVVzzIVwS4uC-b8jC3rvbOi-yhuEJhGcnQ7EbZz1cu1dkl8PPxLSe7

sprite $RoboticsSm [12x12/16z] JOn90e102CFSI-l__ojnpocP0VJ7K23bTY8TchRR2VjsbLS2T-obGtl6RObhjjldyFSuLmUy2U1V7

sprite $RoboticsMd [16x16/16z] {
NSq75WGX30BGDK4DyVxtNHwpTPZwiUrxwDIL7Rl_2jd5mlfO1MOilEqPKVow6GFanpuboBUX6Ixa8rQYH-GYvRDIdmxWSNacswkoc7B9L3HkdpOTsvKZvr_6
4m
}

sprite $RoboticsLg [20x20/16z] {
RSX90e0W30F0MWf9ol_Vwxxh70T_Ids824VJXWSSTy_vSXkpuNPBieL7t6vDEdMxDODLkb_I6ieWtKwXXKlNsTmpGZeEjJaLBgEqNCyiADdI1ND93lHk1ObC
GURjTYjPEIxcqygC-tMIs537pN9tktiw_6i2
}

!procedure Robotics($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Category/Robotics', $name, $tech)
!endprocedure

!procedure RoboticsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$RoboticsLg>', '', $funcName, $content)
!endprocedure

!procedure RoboticsGroup($id, $name='Robotics', $tech='')
  IconGroupElement($id, 'Robotics', '<$RoboticsLg>', $name, $tech)
!endprocedure
