' definition of the Item aws-q2-2024/Resource/ArtificialIntelligence/AmazonDevOpsGuruInsights

sprite $AmazonDevOpsGuruInsightsXs [10x10/16z] LS650SD000GWtc__XIlnWBVyqCUeneIcHp8WQKf88ikW51B5gQ2AK-0B

sprite $AmazonDevOpsGuruInsightsSm [12x12/16z] NS670GHG24AnXr-5_IU-NXFurocUGXl1ICf28UGHcPIDW0GAKE8muKhsif7Ao5TmPR8BirVcIXq-0bSN

sprite $AmazonDevOpsGuruInsightsMd [16x16/16z] TSS74WGn30B1OMiD_F_5L_Bbr0xIy8zQdXoZHDo4E2U5QjZ0eKAM5rc5als0gXJiMzDJu8caBKOj5E8akrPA2JS9J6jZxBPzmFA868SfR_hHt9eB

sprite $AmazonDevOpsGuruInsightsLg [20x20/16z] {
XSY5OI002C30uDb_uPUwzt3uXSexvObhyA8sY7-u07h-8HSdzn2uU32v0UHMWLGbqoqWCeb414CPA-5c8W0jKa24WJpQF40Uk_-41Nem0nB_m6aptX0lFy0J
Y4Jk4OyUVnz4KhUx0ym-aaSfo4U6V7BoMGEF_W8
}

!procedure AmazonDevOpsGuruInsights($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/ArtificialIntelligence/AmazonDevOpsGuruInsights', $name, $tech, $desc)
!endprocedure

!procedure AmazonDevOpsGuruInsightsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonDevOpsGuruInsightsLg>', 'ArtificialIntelligence', $funcName, $content)
!endprocedure

!procedure AmazonDevOpsGuruInsightsGroup($id, $name='Amazon Dev Ops Guru Insights', $tech='')
  IconGroupElement($id, 'ArtificialIntelligenceFamily', '<$AmazonDevOpsGuruInsightsLg>', $name, $tech)
!endprocedure
