' definition of the Item simpleicons-14/L/Libreofficedraw

sprite $LibreofficedrawXs [10x10/16z] Os3W1m8WmGl4O2Q81MN2MVmWPH2bl50M6vZ5pSy8PV5pSlB3JK5XSG

sprite $LibreofficedrawSm [12x12/16z] NSR50K81042XPxViFwtjBqxK5KATWQWR8ECrdlTlDNnTRgwVot6uSlKxBByR_mG

sprite $LibreofficedrawMd [16x16/16z] dSxL0S0W34NHMtVU_jFY-bly10kWM3Z2M1a2epKTepNjWyE9qPgIJqmE087GUuPTw7spFp2z9GFVF3M_Ky2Otny_E

sprite $LibreofficedrawLg [20x20/16z] {
fSxL5GGn34FHDynH_zKkosVrFU7SW0qi-fQHptG1frHeinZB2cs1ja1ReAq5VepAic9C09g6ORZAUk0KqdoMxT0TIjE1wFOqQOMpx_lhtxPjsoEkosrRWJ6f
mHC
}

!procedure Libreofficedraw($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Libreofficedraw', $name, $tech, $desc)
!endprocedure
