' definition of the Item simpleicons-14/L/Line

sprite $LineXs [10x10/16z] JOU50S1048EeUzb_siex9o4q69Ypw8sxUcp__npONENhls46idmCMJuSWHS

sprite $LineSm [12x12/16z] LSV50G0X0CJ0FLT8_zNYEgz4CvA_Pp0ad5mOdkkJIMSuKj-Szm_wRX2Trfx1aC42LXMh0Wy

sprite $LineMd [16x16/16z] RShLOSDG0CLGFJHR-q_R9Z73-Rl0Y-eYBD7TlCIJMxIFcZJscdAeEYbAORykUGv0qbPf9uePsb5HPnUpIkyPC7Y80EaK5w7rYnFjE8co-0S

sprite $LineLg [20x20/16z] {
TSo35S1044NH7wpn-gysDkx1UFIdYIoAquuBkovnavzRioeLdde14IeP4Y7CUG04RLI3YhgEsTvJK94FG3rwQD_pW7oOUsdV4z1rBbK7ViuWA_7KI3muwTaC
MlZ7rgghvwyB0sJTTT3hmGVjHW
}

!procedure Line($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Line', $name, $tech, $desc)
!endprocedure
