' definition of the Item simpleicons-14/L/Lintcode

sprite $LintcodeXs [10x10/16z] Oq01_7nm5fp116V1HVaP6PXWJ6Ibp70M2WC

sprite $LintcodeSm [12x12/16z] Oq07VFm8DZAJ2yvavKV8yBC2CIU4pSGF4c24SBX1YdWOe38CZCX6iS6Pd31Xk4u

sprite $LintcodeMd [16x16/16z] VK_50KKn24lTc_sd_VgioWs8uZy2xR0qgwDktspMtAw26P3tNjagyhi7-dENhB_h5IBGjYRL095Y5x7s6U8kCSv2Rm

sprite $LintcodeLg [20x20/16z] ZL030a0X3FrczUv_scpNx6rnxrpAXwSqWUMc5IZ3ojIh6hRbfXTK1wTXgwP_OZjDxplODXreMIW8nyAZEetXJTf8FAjJxlKfyx0rDp6GcMijt-Ka0G

!procedure Lintcode($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Lintcode', $name, $tech, $desc)
!endprocedure
