@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-14/bootstrap')

' loads the Item which embeds the element Listmonk
include('simpleicons-14/L/Listmonk')

' renders the element
Listmonk('Listmonk', 'Listmonk', 'an optional tech label', 'an optional description')
@enduml