' definition of the Item eip-1/MessagingEndpoints/MessageDispatcher

sprite $MessageDispatcherXs [15x10/16z] uqC3p2W09nUe4i9b1V4u869iOC37nyN52vI6A-PbGJCAf1U_HG

sprite $MessageDispatcherSm [18x12/16z] uyC4pEY0W0WR7we82oypN8GDYBcvGInUe0WB6nZmyd5pSV5nyR51rB22r458L7Fuq4s6yeXn8G

sprite $MessageDispatcherMd [25x16/16z] dL2r0KHH22km9v3zjxtxxfuIYU4KT88t2pbP2E9e4Nwyg7b3fSf4oFtOq2rqH0LAAG46wlp1BG_vGBZNOF2mtIp8IWLE0i9EA_cs-0C

sprite $MessageDispatcherLg [31x20/16z] {
jP750G0X30GV4GwR_hizT_knEF4i_4F-e6t4-LTSILzYJGZm9GwO678LwxoR2CjD_29s7qLEZTCzJD5z5li11KfAgP03SB6sQIScMm9rlAUc9K-xV1P6aeH_
jqN3JzqJ8ZQBsnAgV_01
}

!procedure MessageDispatcher($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'eip-1/MessagingEndpoints/MessageDispatcher', $name, $tech, $desc)
!endprocedure

!procedure MessageDispatcherGroup($id, $name='Message Dispatcher', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$MessageDispatcherLg>', $name, $tech)
!endprocedure
