@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureMobileInventory element
include('elements/azure/FlatSymbols/CneIntune/AzureMobileInventory')
AzureMobileInventory('element', 'Mobile Inventory', 'an optional tech field')
@enduml
