@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureDeviceOs element
include('elements/azure/FlatSymbols/CneIntune/AzureDeviceOs')
AzureDeviceOs('element', 'Device Os', 'an optional tech field')
@enduml
