' definition of the Item azure-6/Item/Iot/ServiceDeviceProvisioningServices

sprite $ServiceDeviceProvisioningServicesXs [10x10/16z] 7Sgr0G0n40F1CVlwB_X1YN111-nXRLI9xHWasPiTP2-oVPvDl0zMmyWmr6Yy

sprite $ServiceDeviceProvisioningServicesSm [12x12/16z] JSQ54GCm30Gm9RQ_b_q7BjEH16o099qKdAMn3uuLJmKsH2oIz_ll59vV35bTpy1wEksYdsNtiN03

sprite $ServiceDeviceProvisioningServicesMd [16x16/16z] {
BKnH5aHH2575lFQ_uJbT-Ia0HgIlYOoZIRwhhZqp0Niz0-0R7CVyDhNVpH5GkCp71O6ifhHZjRmRNZ1tFi3BSvbkB07QHYhoPOX3CFTmJmB5ibxiR-ZSuPlq
ymS
}

sprite $ServiceDeviceProvisioningServicesLg [20x20/16z] {
NKs5OGKn5E89wR7_metnZLCim8Z4DteSn5kQh83W_DwIdWoSH4solf827Br5IYjQ4j1NWxIaUmIzFpclPZ7d-B3cqT4Od8na_sXzShJcRXJwQEMD_U7UZVda
QUwNJSAOMhBmBI8kIJAkLEJRR3nYhI-CQaXFTU0BVqh__WC
}

!procedure ServiceDeviceProvisioningServices($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-6/Item/Iot/ServiceDeviceProvisioningServices', $name, $tech, $desc)
!endprocedure

!procedure ServiceDeviceProvisioningServicesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDeviceProvisioningServicesLg>', 'Iot', $funcName, $content)
!endprocedure

!procedure ServiceDeviceProvisioningServicesGroup($id, $name='Service Device Provisioning Services', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDeviceProvisioningServicesLg>', $name, $tech)
!endprocedure
