@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element _19Mp
include('material-4/Image/_19Mp')

' renders the element
_19Mp('19mp', '19mp', 'an optional tech label')
@enduml