' definition of the Item material-4/Image/Animation

sprite $AnimationXs [10x10/16z] uwS3

sprite $AnimationSm [12x12/16z] unza

sprite $AnimationMd [16x16/16z] un_X

sprite $AnimationLg [20x20/16z] unzKO1G

!procedure Animation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Animation', $name, $tech)
!endprocedure
