@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element AutoFixHigh
include('material-4/Image/AutoFixHigh')

' renders the element
AutoFixHigh('AutoFixHigh', 'Auto Fix High', 'an optional tech label')
@enduml