' definition of the Item material-4/Image/Brightness2

sprite $Brightness2Xs [10x10/16z] uwS3

sprite $Brightness2Sm [12x12/16z] unza

sprite $Brightness2Md [16x16/16z] un_X

sprite $Brightness2Lg [20x20/16z] unzKO1G

!procedure Brightness2($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Brightness2', $name, $tech)
!endprocedure
