' definition of the Item material-4/Image/Brightness1

sprite $Brightness1Xs [10x10/16z] uwS3

sprite $Brightness1Sm [12x12/16z] unza

sprite $Brightness1Md [16x16/16z] un_X

sprite $Brightness1Lg [20x20/16z] unzKO1G

!procedure Brightness1($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Brightness1', $name, $tech)
!endprocedure
