' definition of the Item material-4/Image/CropOriginal

sprite $CropOriginalXs [10x10/16z] uwS3

sprite $CropOriginalSm [12x12/16z] unza

sprite $CropOriginalMd [16x16/16z] un_X

sprite $CropOriginalLg [20x20/16z] unzKO1G

!procedure CropOriginal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/CropOriginal', $name, $tech)
!endprocedure
