' definition of the Item material-4/Image/ExposureZero

sprite $ExposureZeroXs [10x10/16z] uwS3

sprite $ExposureZeroSm [12x12/16z] unza

sprite $ExposureZeroMd [16x16/16z] un_X

sprite $ExposureZeroLg [20x20/16z] unzKO1G

!procedure ExposureZero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/ExposureZero', $name, $tech)
!endprocedure
