' definition of the Item material-4/Image/FilterVintage

sprite $FilterVintageXs [10x10/16z] uwS3

sprite $FilterVintageSm [12x12/16z] unza

sprite $FilterVintageMd [16x16/16z] un_X

sprite $FilterVintageLg [20x20/16z] unzKO1G

!procedure FilterVintage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/FilterVintage', $name, $tech)
!endprocedure
