' definition of the Item material-4/Image/FilterTiltShift

sprite $FilterTiltShiftXs [10x10/16z] uwS3

sprite $FilterTiltShiftSm [12x12/16z] unza

sprite $FilterTiltShiftMd [16x16/16z] un_X

sprite $FilterTiltShiftLg [20x20/16z] unzKO1G

!procedure FilterTiltShift($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/FilterTiltShift', $name, $tech)
!endprocedure
