' definition of the Item material-4/Image/Filter9

sprite $Filter9Xs [10x10/16z] Oq027FmGmC39oS300iJy3FnWaWt6ueUn69348EeW0CY26mSpZG4

sprite $Filter9Sm [12x12/16z] Oq05_300OiF4G10anOTW0o527C5cG17dWRCHva013v2DrLO

sprite $Filter9Md [16x16/16z] POtL0O1G30CFTxB_jF1Sxw-DGOyo4p1fYZmFaxc1OHe1SsjojwIZk4VntDNzgBmvcflMN_SnbNjJnDqeCzkxGa_6tdDz_m

sprite $Filter9Lg [20x20/16z] {
TSrL0W0X24LHxFRjVxNJOti_ZmAqA-Icy915bxxDWMeSXgpxJ3edFijuJU6AzsR127eqmQlLsT586ZFQtMWcvmmvtW02jLQgvch-DOOkTjjK1czxBAABdhHf
k-K4
}

!procedure Filter9($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Filter9', $name, $tech)
!endprocedure
