@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element Gradient
include('material-4/Image/Gradient')

' renders the element
Gradient('Gradient', 'Gradient', 'an optional tech label')
@enduml