' definition of the Item material-4/Image/Grain

sprite $GrainXs [10x10/16z] uwS3

sprite $GrainSm [12x12/16z] unza

sprite $GrainMd [16x16/16z] un_X

sprite $GrainLg [20x20/16z] unzKO1G

!procedure Grain($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Grain', $name, $tech)
!endprocedure
