' definition of the Item material-4/Image/LeakRemove

sprite $LeakRemoveXs [10x10/16z] Oy0A-1cO-I4i5du6A8iPp604oOB4-DaWmZnm1N068ok8YG

sprite $LeakRemoveSm [12x12/16z] TSQt0SGm00EnKyxY_jD-C6kZ0g_433VuGI3iI4miq0IK3LnTnDe9Y40HB4o8xDOT9Mp7dLcOVG4

sprite $LeakRemoveMd [16x16/16z] XOq54WCX303t27BA_l-rzMOwseMuyPzAN1nxXbOcPaopWl4DowOLitpPgy4lkmQqQG4EDQg1P-KP7m4q0nOIfnLBtfHX9PaddjQChOiqSq7X-JCakGC

sprite $LeakRemoveLg [20x20/16z] {
fOwr0SD054FbOtxxJnkcxoQaKgp_C8j4q-A5gnG5BwPsf1pbbGkSdRWN2cWKURsWUwdTazlTxJgSIJzWNPW5zCjGPAIhZrdTVNs7mNc8PGwro_bgR9l0nXcg
D4DkHB7ia5kRLfNgfezn1
}

!procedure LeakRemove($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/LeakRemove', $name, $tech)
!endprocedure
