' definition of the Item material-4/Image/PhotoLibrary

sprite $PhotoLibraryXs [10x10/16z] Oq06_620OF4myEDYyN62MH3525bc80i667d0W841

sprite $PhotoLibrarySm [12x12/16z] VSQr0O00000WxDR_hxMxc71JDvDgRhS85U7n9lgzxGAY-LLJJ-QBuab4tTIp2C851W

sprite $PhotoLibraryMd [16x16/16z] dSj50e1034FHF-xJ-vyMTrZnTcqIlYYzMSyaX-MkrrlL-wtbpvr5Z3tlJaYGZfjLM-_qs6FiXlasEnPoiBoD

sprite $PhotoLibraryLg [20x20/16z] hSZ50GCn00InEJPl_zM6J67MKtnYqXaoVtu-NpY_S0npUt9_kN1rJafOdP_59o2SNGH6W7PUwr9izJQTcV8npir8lXiwD-SRmfc91_O

!procedure PhotoLibrary($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/PhotoLibrary', $name, $tech)
!endprocedure
