' definition of the Item material-4/Image/Photo

sprite $PhotoXs [10x10/16z] uwS3

sprite $PhotoSm [12x12/16z] unza

sprite $PhotoMd [16x16/16z] un_X

sprite $PhotoLg [20x20/16z] unzKO1G

!procedure Photo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Photo', $name, $tech)
!endprocedure
