' definition of the Item material-4/Image/Straighten

sprite $StraightenXs [10x10/16z] Oy0F-660WP-J0KOmCZ0nC362M31LIEgm

sprite $StraightenSm [12x12/16z] Oo06SF3000i3FpCSCg129WW4iw40n8Rh1QfWWG6SLW4

sprite $StraightenMd [16x16/16z] fSU30G1H30FGVBlTVzgpZLS6V-cKPmdWKZXpqztDOAKOfLnSI0ZHhARxF3lAAm7G2mflrG

sprite $StraightenLg [20x20/16z] lSW30W0X40NGdrttF-tQPcyyo85OF-Cq4DAIG4mm2JIfPnkX04Krgkn_C_i_CIEhdqrB561yZk1h9G

!procedure Straighten($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Image/Straighten', $name, $tech)
!endprocedure
