' definition of the Item fontawesome-6/Brands/_42Group

sprite $_42GroupXs [12x10/16z] TSg30SG050FGdDc-_QUjZSyevrKa_tV_AV8d1Bv_xhn10VB1vS-LvESovfDhyigsQW

sprite $_42GroupSm [15x12/16z] ZSS55eH030JHxEAMtF-sTE4E8_zrsQVpNvQ7YFW1XS2dnbdhbx4xLg2Ro4arWZEiT16i1XvE3m

sprite $_42GroupMd [20x16/16z] fSi53e1G089Xx9RxtzO1njhwJRxjuM-jNdsNKGrwhzISoHx0GfgqP6mzGa8PIygurzj6__9euH4wffprmew8mQyWOa3ljxv5J9ysbihhvs4R

sprite $_42GroupLg [25x20/16z] {
lSfP4iCm309Gic-skVzjEofOu_ykj4cGdl2t4969dA3Mj6caWINAGoqOCR1fJzr73DncZ-mnrAgfCgDJvnnw7G57rclIjmbI7WYUss2vO9WWi3mmRC3I0MVS
2zOeIpFWFM8waJdmlRm
}

!procedure _42Group($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/_42Group', $name, $tech)
!endprocedure
