@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element _500Px
include('fontawesome-6/Brands/_500Px')

' renders the element
_500Px('500px', '500px', 'an optional tech label')
@enduml