' definition of the Item fontawesome-6/Brands/Audible

sprite $AudibleXs [12x10/16z] NSYr0GDH040Xufwt_xJdrQU4qTNXVwCUntrxwYERNxxEeJudjoYyzODJ9yySwcCm0m

sprite $AudibleSm [15x12/16z] XOk30KKn5CNoLBVPVzflCzSu_6Ln39KpbHFTTBf1KfrMDmHEssmABBCTQBfCeD2TWQaHp-99R_b4CZPNxjZun1u

sprite $AudibleMd [20x16/16z] {
bSe5aeKm6C3WL71exd_RdN-wp_s3UlXDsTKrSp6wZkDog9b_MwARTOPGWHpH1Zf1ZuynfzBYGi7ZlmmwGZBh0B2fXGQx_az1eVmdIHSwtVatQm6cM2uEz_oV
NrGrSQ_opXy
}

sprite $AudibleLg [25x20/16z] {
fSvL0W8n30JGgNjp_zkIJd3usmVhaS4LBeO_BxkOdV6kIONoGvJ3qtZDo28ieeAZda4UMCylpeRDiKH5Z7E2W1R8Sz1gGBI-OAyTeEa2u9QS6X0J1Sp4TUjC
bywcHtdONAAuaefdvtZcrLO7IipyiaGQb4uf-12rCkZIYH_TKltXTyCLDm
}

!procedure Audible($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Audible', $name, $tech)
!endprocedure
