' definition of the Item fontawesome-6/Brands/Bilibili

sprite $BilibiliXs [10x10/16z] JSR50SC000GWshZU_jF6ZHUCe462TEGsXqCI8xfZGOuTlfCRrSaA

sprite $BilibiliSm [12x12/16z] JSU54S0m0810wbxstpON3sSFJ2Un5s3p0NI2qzgs-7-vkDIYrpyY-p5w9veTk22wvjCyYps60W

sprite $BilibiliMd [16x16/16z] PSk30GGn54NHDqPm-wzs4UE4NvAkMv7TmWCclIwyAzXbMO3btqJhsi0L7c1NvS9GPKFyi4bws5DiE4BjJF4HPWwM55TpR7YR64HFAmshqHS

sprite $BilibiliLg [20x20/16z] {
ZSY53S1008NGNpzd_sdhxYz6K2yOBKAZKGv-Ni1MOGchGUKy4Btt0DxcKkIiAO2u1oJGGSb0HyiBkGQLtPu33Q1QdrzVlRw6EBzYVGV_duVii0o8ApMSvPAA
QY_JhGu
}

!procedure Bilibili($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Bilibili', $name, $tech)
!endprocedure
