' definition of the Item fontawesome-6/Brands/Debian

sprite $DebianXs [8x10/16z] 1S450S10000Xvhxht_O1WBB7CaFYdMGo8S1fuPi-0fW0m

sprite $DebianSm [10x12/16z] NSQt0O1000GWpF7-zj_MNYe0G9lqGNVewPw0Gm73mmEnSG5XZdbXm0nk-Cq1V

sprite $DebianMd [14x16/16z] LOo54G0X40E3E-c_sXUSHIDpQ6XiF1kgYShyFuaHGAH0ets82GsoMsFAY9g3RBgINOqiDyMXr1_MVsvhkLpCo4-glYHnfxSi2fqN

sprite $DebianLg [17x20/16z] {
NSg54S0m34FH7pTCsd_RNXdUWK7YO9utqwuQXo5DXsjIPzEtSpTL0LIuI0wKuPA74SMcBNX0q0g0vo3e2y1uFTp_SIsRhTuym981V0DoOUEdUIK09yV6l75G
vSl4poZyJED7aHy_kAm
}

!procedure Debian($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Debian', $name, $tech, $desc)
!endprocedure
