' definition of the Item fontawesome-6/Brands/Drupal

sprite $DrupalXs [8x10/16z] FOM50G0X08JuxcV_QMsz082P6gdIgZmk1IUaRjIPGtcTs5p1728

sprite $DrupalSm [10x12/16z] DSQt0SD0000XRELu-s-hwga0VqD6QaGlrEBNoPoOezS_ElINlEdgRwtNKwYP-faBgk83

sprite $DrupalMd [14x16/16z] JOw55GCn34CLvlpzjstzZi8cWQxbTIxE1DQPm7YIpHJq9y7wL4iQLm1632eKAO2KhR59zbotq_zfnGkKoHe4omOJquADamE2f09SSktwykMB4IQFjmbW6le1

sprite $DrupalLg [17x20/16z] {
NOq55WCX44Dnc1N-_M_RvirKineZAP3J7wxsonlyy0hiRm5-b0Ba3lUN_tnFE9rlG1iBXdY70iKT2Kg60akBUCnByMe0EMNzc_OXDn4NI50LtHdK1Ypc9II0
Bi60AxvBmWtaYEgCuOQ0Gpmm4Uwg_mS
}

!procedure Drupal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Drupal', $name, $tech)
!endprocedure
