' definition of the Item fontawesome-6/Brands/Firstdraft

sprite $FirstdraftXs [7x10/16z] uyS961YW59W0Krn05eXY18jmCJA00P02

sprite $FirstdraftSm [9x12/16z] XOkr0S0m30GlXawm_xOHzJunlB-uQtMprAPn8dz0Dn7J4AorS49bWHCgYkNy

sprite $FirstdraftMd [12x16/16z] dOn50e0m30GtYiF_NrjlSsTEoTht4sFcUJEfhbi4SLFB40f2tcusitFSpWMC6oZFqHLOtTVA2Qlxw5ZT1zGBHzb71W

sprite $FirstdraftLg [15x20/16z] jSU50O0m50FHu0xxJ_lby05wq3RlA55NHozhHLyU-_xb9lqviIhHflLYbRta-L3qScFLcP8TAuFC_Ifvn7ELt1Wh7T01

!procedure Firstdraft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Firstdraft', $name, $tech, $desc)
!endprocedure
