' definition of the Item fontawesome-6/Brands/Fonticons

sprite $FonticonsXs [8x10/16z] Ou02Vap0mC343A9uO5m-9aO8dnkPPcS78HW

sprite $FonticonsSm [10x12/16z] NKo50G0W3C9k_VzQkzS1O5lwBOxc4eLj0opSG6qi0OdgtBw9WoK6TqjkAm

sprite $FonticonsMd [14x16/16z] ZSl50S1030F13PFFwh_QCFDyZEB03_J0rgQHGJeDz0IQaCZKX6d8YBBSisnzZ3nidqC--J4baAY1N0FhoSs2JZZe

sprite $FonticonsLg [17x20/16z] fSw34G11343Hl_Qa_shF7fpUcWbNvahUQEumBqqig7NDm0vzMTO59MXHUdtZXzLH19GIfTJo9CmR2VBvYVgnKHIOALEzR8H1bJZqyWHNFG

!procedure Fonticons($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Fonticons', $name, $tech, $desc)
!endprocedure
