' definition of the Item fontawesome-6/Brands/Hashnode

sprite $HashnodeXs [10x10/16z] Om02Hdu62E070bO80ye4aX0c8v20Ii1POCm0bc55IB126L0ca08

sprite $HashnodeSm [12x12/16z] BObL0a0X20JN5_vOzp-jr8m26mhwQOBZB6GoXSJa-N9twWEVw-stXI7NZ1tf-PK66GQP1ca

sprite $HashnodeMd [16x16/16z] JOk50S0W40FhBljFsm8vFbm5OfquthapqvjffB04fB5ygb6EDGLoZXZsdZr9qfmZ7tHJeKTUrE2E7Md14bm6fpy

sprite $HashnodeLg [20x20/16z] {
JSx70KGX30FH-Jc2-gzsWz51xsW6C3QzEZ5xzRSJP1jWJILBcSkeifH5-QfSi7GF9u_oOMUKKucog_XeuUzneD819Z-7UvsxAm6RpFnocYXPOYwZofAqZYM6
Bm
}

!procedure Hashnode($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Hashnode', $name, $tech)
!endprocedure
