' definition of the Item fontawesome-6/Brands/KickstarterK

sprite $KickstarterKXs [7x10/16z] Ou02VduW1W48oSyD9X42V51n9gW8Bv3Y136vGVe

sprite $KickstarterKSm [9x12/16z] LOg50G0X30Fphd3xJulhrPke0Qaj7w2VpCA0o9nraIR90BPTPpNe-XGmgmS

sprite $KickstarterKMd [12x16/16z] JOo30G0n5CLoHl7sdxPMlidAxXw0mnviaWmyaYwl16XGqxzuCpkLVUOVCp-MN6ik5czhli_NyFJn1TZIsYXi6n4

sprite $KickstarterKLg [15x20/16z] TOu50e0W40JtRCd_lvRkM8MveJ7cVYYGdjFrskLol7o1LmU00X-TDF9F-aNU4HIXqg8KT7froj7fYztY_gWhUm9Bf-LL8XOoQLfs-4uufVfu-FW9GXyB

!procedure KickstarterK($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/KickstarterK', $name, $tech)
!endprocedure
