' definition of the Item fontawesome-6/Brands/Line

sprite $LineXs [10x10/16z] FOo30G0n303lZMh_QOleOd8qHPBW0BAqXLEobk_2ofx6_KWc_6to0P__2YSC

sprite $LineSm [12x12/16z] JOs30K0X500lk_QVzYDVFGlQf7JtfaZqTEcetnKCykSJYQqQwBwBr8ZuVCkW_UZLVfyfFV1TttTV

sprite $LineMd [16x16/16z] LSx50GCn3031DRFLVxN9aMb-Oa6MnO4S-gWU0e2g8-HZHZZuEsn4j5RHLyKTUpB6I8w99wxau0mI0upvOs5b64-DS2cZUQ39myc9VeJk3m

sprite $LineLg [20x20/16z] {
PSt50GGn30J1DhCd_sWFbrrwYS5DNJMWwyavhVR5NdAz7t7ydOScX-CK5_vVybpzZq85bMwZXg5SQwr6JOFRQocee3WJsrp0s4y0riBwbwgb67Ge_1NTP63e
hfzxJPivjKEBWLjBRm
}

!procedure Line($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Line', $name, $tech, $desc)
!endprocedure
