' definition of the Item fontawesome-6/Brands/Linode

sprite $LinodeXs [8x10/16z] LSN10K0m00Im002t_xJGlffFc80aTPhD6xaTcIITBWHIawra1Iy

sprite $LinodeSm [10x12/16z] BSR50G81402nuCxqNosSR5x1nwvgzZNA-6ISqjMphqDH8VGDhvEUe4_sFMFC_W

sprite $LinodeMd [14x16/16z] JSxL0SCm50F02tEq_xPjs6S_-XDiNdiEN8wzzrqjnRNu3DaLnj32UlHaI1hov-ZBjO_OKd5SExGPaDNci2_cb6bsnJNwr57wGly

sprite $LinodeLg [17x20/16z] {
LS450SH00C2mRiTO_sgVCG4uDp_IL9q7Rtet-53NoO-b_6bwy2jevC-mydPmjoUd6JXq0UhM0gWcgEg4x5O13Zs0eUx9dG9qZQbmbuqGzO38tRInLDwgQaZo
Tgf0uaFvTmZ_ui775G
}

!procedure Linode($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Linode', $name, $tech, $desc)
!endprocedure
