' definition of the Item fontawesome-6/Brands/Mailchimp

sprite $MailchimpXs [8x10/16z] HSQ30S0000F1gztiFssDyFsQkoaW2QFrUjSm9AfnL5H1evl3fOIueBS3

sprite $MailchimpSm [10x12/16z] LS770SCm00GWNDLr-syRVmF-xAqTE0_vuB3RpCEGp_FYJZWNHnADPHYvEAPknts0n75QU9Fw1cZxuGS

sprite $MailchimpMd [14x16/16z] {
PSr50WCn243HZpGkzxzjeRAQjqbmdcGr4Bw6mGsa1UN-em6pzhbkV32XtxGgi97uckGldUz8dK39uDBG77BTBOO8BXIAHwsKDZYmRMTd4RCDQCvX2fqm8en_
kP1Ut_FyYGZX3G
}

sprite $MailchimpLg [17x20/16z] {
TSj5GWD044JHF-xJzxyjrJWaUSiINiYLFonoeva5SBL3l2O7LweoiwrW8B73t6Kk9RWBtKGsud-JEGS3MM2IW52GGZGXP0KTcDLSOaBYG9gzN2NWbe8OHZTR
IBWbU5YdBgMr6c13liCKv01fA10FXf-X5vn9Hlf5v9giROSlnLpYYJS
}

!procedure Mailchimp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Mailchimp', $name, $tech)
!endprocedure
