' definition of the Item fontawesome-6/Brands/Mandalorian

sprite $MandalorianXs [8x10/16z] LS770O1040GWp5xQwRzRtmAEDa3IuAM3z3Uqj4WJsqaCMoDcjitVWGy

sprite $MandalorianSm [10x12/16z] DSQr0GCm0C0mXpd-_zfoDOctCVZeJVaOVPDu4_ni9LqAsQ044yBCa4LO4v0RcOMyUUia_k8_6U09

sprite $MandalorianMd [14x16/16z] {
JSU50SH030F1TNnCwh_QX_0O1O1RpOLJc5aQdBQrr0EdmNAMSL29h1cFa8BAb6a2PCcbWbG12KAVnzC4XE20DbJWM2WmCp2oWGbGZIHVMEJaDDuo3xF08vpX
2m
}

sprite $MandalorianLg [17x20/16z] {
NOq50iCm3CIk0NT1_V-typokmef1GPQLc-c3RGFwLoGoKBwYP-Xgtu2kj2JInz24CRuvcmKSeA3J36W5jXm_n_48q8te1ASqPqbI1wbYRjVeSXwY4RSQH-LG
so5o24FABlrcqwzd56tuiLixzSjim_w4jLxrHnlv8fR-gMzn1m
}

!procedure Mandalorian($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Mandalorian', $name, $tech)
!endprocedure
