@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element Microblog
include('fontawesome-6/Brands/Microblog')

' renders the element
Microblog('Microblog', 'Microblog', 'an optional tech label')
@enduml