' definition of the Item fontawesome-6/Brands/Mixcloud

sprite $MixcloudXs [12x10/16z] Oo0HyFCpS48OG2O7M82V5SHXO6A0YhCHOmu

sprite $MixcloudSm [15x12/16z] fS450SGm0C30bBdnh_R1mdR72meD_YfW8sNuopSeSIVyAKIHPOA_sx1IS-2PBm

sprite $MixcloudMd [20x16/16z] lOY50S0m48IeUzb_shea2pol1m4qJN6kpDbCCFl5SwoahkMJevnkHho0qXAho_0mYRDLLITkk2Q07G

sprite $MixcloudLg [25x20/16z] rSc50SCm44DHcVcq_xPLER10yir-k5UirCxUySqyL6UZWxVnXqBTIJQBA4FWtudCMC6M1sOKy9t0Sq80QWX-DUP5VmQZjafhM6LkeUAPmoLx

!procedure Mixcloud($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Mixcloud', $name, $tech, $desc)
!endprocedure
