' definition of the Item fontawesome-6/Brands/Ns8

sprite $Ns8Xs [12x10/16z] ZS6t0G0X00GWFaUz_RUribOm8w9RTkIEZLg4wjYiSeNTxPKQ0mq

sprite $Ns8Sm [15x12/16z] bS6r0SD0400m6PxXzjysxPUnv9i-7SAzIPBkBbRgI2c23RSGFPXBjkeJbft2s8BjSDt-zGC

sprite $Ns8Md [20x16/16z] hSYt5OH044J1p-gtz4pd7-r92spAB1vtICUz0g9mOMmC4XvnBYrZs1ZOrJCgcWbP2XXXGvVP9_wFE3oSIp991Cb5TMjkt9J2Szu

sprite $Ns8Lg [25x20/16z] {
nSav0iGW34FHpmu6M_S_xQnbqkSrjYGUrlqqRkY0Z8lc72F-7u79mRNOsUQfrg1feYJoi4fW1LQT0_ZLEfEYBOXyCdoMDdC8iEE3yBecHDhbCs3AAliZApkI
0a4kq4chGJFmHKwSnKNeOt4dPvxn1W
}

!procedure Ns8($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Ns8', $name, $tech, $desc)
!endprocedure
