' definition of the Item fontawesome-6/Brands/Replyd

sprite $ReplydXs [8x10/16z] Ou01NduGO6NW9mGO-1cu-RdvG3IOnytFpy7Foy08aGG

sprite $ReplydSm [10x12/16z] ZSQr0S0m0C0mbxd-_zfYQ8mcKV2NeglLcDY7PLSRwGOTlutxj65mmdI-Ecu

sprite $ReplydMd [14x16/16z] hScr0S104CH0cVdKVxLcZd-Y1Vwws4qLKFi0ttfJWI0Z1joWZ5MZJnj3hSzM5ew86kfsJHDucm2o4x

sprite $ReplydLg [17x20/16z] lSZ50G915C3GZAxEJ__LuWvdtYtXbzPlAcURFkLRFnLy5wl_iaBT0QNUHfYgfJYFsr185DNmDcQl-cqqMWcfeiQcxdtNBJQghmB0fvLlHm

!procedure Replyd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Replyd', $name, $tech)
!endprocedure
