' definition of the Item fontawesome-6/Brands/Rocketchat

sprite $RocketchatXs [11x10/16z] DOh50O004CE2Ezb_MhINJvLper2NOszYtGuzmRNMLe97WusZ6o91xEDsR52r1QtB3G

sprite $RocketchatSm [13x12/16z] FSq50SGm0C30Z5UCVxKFfJDmv0gBwhRlDCaX0QTk0BU2DuFUibWIbvXlmKqMCJ1OEQHvhM36vcYDXU4B

sprite $RocketchatMd [17x16/16z] {
JSw54SCm5C1GnSpQVzjUEU_8_antSfTyucRxa-19dyvHpG1w8Zmr7R3VuRTdZOqRxG8RraKjKDr2UnQAGh88L2WG0dHnSADKq_r_WPstQsg4O63ujdZVSjpp
d15vcggLlmS
}

sprite $RocketchatLg [22x20/16z] {
RT75WGH130J1QcQb_zOUQ1dYDo1MDLRGcu5BUdLmOnxR_HuKUB6lKU1iJG_3xYcQhl8696MOUXBzDJIz230Yw4s1HP5aHreMrBrnE0JF7GHLiFnjfqgQG-fB
AZluMu7UD4oRgHS9iWJvhOFjixMdQ0EFXI0PT_4QeSJDodBWljsYwzKl
}

!procedure Rocketchat($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Rocketchat', $name, $tech)
!endprocedure
