' definition of the Item fontawesome-6/Brands/RProject

sprite $RProjectXs [11x10/16z] LSQ54O0040EmuaxstvR38IzjVbOOajGmJYIqWT9gJUoAthpN3Cez0ayMPDTHxtMt9ni

sprite $RProjectSm [13x12/16z] NSV50S103CH0XTdglzhZLyQu_5qMEzNdS8B5H35vJ_g0rMq1wATkvmXrDlG2gqyc3VHLAMwxeDCw4rGHy4Pa

sprite $RProjectMd [18x16/16z] {
TSm54iCm44DHAOpxxt_QWknfXleIqvB-y7RLkLYTR-Zs13QYxYG6QGSuhHWA2y0oKVF1qIfDDsLNYzWttBKz4Mc1gmJCYJG3cXFgaTibARDMOCpCs7YeI--e
WaETWRRx5xBRxZS
}

sprite $RProjectLg [22x20/16z] {
VOy5aaKX30I3EtF_ssvbgfBztazfYCbFGgwrfcTtOGnJyS1ndssvvrXGNDxYaLCrPHMP0BanOMPGgZNcmDLjeNK2b6KsY6m04LsBFzX1osfcp-4uwN0Jj8Pe
33ilRbUwMMCxZ130G1867cdYjAlHsOeJxupfvfiLyFkHFm
}

!procedure RProject($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/RProject', $name, $tech)
!endprocedure
