' definition of the Item fontawesome-6/Brands/Sith

sprite $SithXs [8x10/16z] FS710K00002X083RVri_vHUcGJNMer1crGKLpgdk9aU3lLF7fQl9YCa7

sprite $SithSm [10x12/16z] DS450GCm0C2mZddrh_Ry1FuYFm6dWUpT1DtjAcYe9tGx65K4xbJ30KH5q4RXUib-WL70Qk7l2G

sprite $SithMd [14x16/16z] LSS55iGW4C3Gu3N8_M-xR-iDClFvLBuqqm62p9taq13AVm2gSrlL1bqtGW4rWxB-j-W2X3du3_chbPVooX_Za9B_g0eEZV17Ny6x3HQR2s3V37H2vjz2a4y_

sprite $SithLg [17x20/16z] {
NSs5bGGm24NH5_Vy_hlT0pj-umBmA_BhGWDN0kamrBCAm5JOYY0pOv1PGF5DwyTM0jjNasoNFOHufKcM1X3K7dcu5xF9Sio8ENGvUiBSHqcnAa3JOdi1f80N
IzGrer-3B47pKEck2LiV8aHfIPvBrpPdXx8nIMJL527n463mwmy
}

!procedure Sith($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Sith', $name, $tech)
!endprocedure
