' definition of the Item fontawesome-6/Brands/SpeakerDeck

sprite $SpeakerDeckXs [10x10/16z] Oy06EFdv-Jc0c8-57qI225v-g1m_0py8W5WGFXiGyq34G9WJ2404ad4

sprite $SpeakerDeckSm [12x12/16z] TOh50K0n24E_rjliFor-vU4aLyhplg-t2yQjRQ7NMg-_reE9lTPKRqLuV3TmTBzXpAejFDOI6

sprite $SpeakerDeckMd [16x16/16z] bOt50K0X34E3E-m_BGwzVNbeBS5lJ8WTWN4xe6psn-pGt486KOhUMRlZsnPs31LJIZsnuuMUFtRrhs6uuQn4Y0d7_32yqG

sprite $SpeakerDeckLg [20x20/16z] hSY54G9150JHFlVh_AF5fluI0BoI4VvkCrQIDrmMzkGrMcvQqwtxW4-ebsv4N3fOplPnMkxsiLmQNNrbrxc-TGkr9tdwnPGyR0QI2yiM8tnovITF

!procedure SpeakerDeck($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/SpeakerDeck', $name, $tech)
!endprocedure
