' definition of the Item fontawesome-6/Brands/SquareJs

sprite $SquareJsXs [8x10/16z] Ou02Ldx2W86BWHDCCtD2-Fny320A3A1g

sprite $SquareJsSm [10x12/16z] Oq00Vh800pzC9mCl0roCbO4FI7Fp0obU9Y2BdO47g0x8XG8U

sprite $SquareJsMd [14x16/16z] jOc55O0m4CM2Ezb_MfpA0CrftYTdtIF3PYashA6Anfnc3NLYhl3--uATij_MG2s0mwtx_YqoJW

sprite $SquareJsLg [17x20/16z] nSY50SCm4C101SoW_QSjSmV86L_yMRSl10zLskN4uGl11HYVWMZsAp3y2XsOdq4BUDEdH7TTyOQB8HUBqukvhqt7jcR5RuDVPm

!procedure SquareJs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/SquareJs', $name, $tech, $desc)
!endprocedure
