' definition of the Item fontawesome-6/Brands/SquareFontAwesome

sprite $SquareFontAwesomeXs [8x10/16z] Ou01VdJ0oCOAfg4o29eRefWJmaMJ1G

sprite $SquareFontAwesomeSm [10x12/16z] Oq00VXZWuySAW4gO88gOW1Y3nGGpWWbT8pV221YJ0m

sprite $SquareFontAwesomeMd [14x16/16z] bOc55S1G20FpNO7zfwsxzz1xmHvB2rLP-GCCT8ngjYeS0cQRzwK1EMypvsH2oJMyC-mDQWKj

sprite $SquareFontAwesomeLg [17x20/16z] dSp50G0n4090uXxwh_RSxxMPtmhWppzPW6-jS4X6WQgalnVAUmNWNd0ZMrYRUtikdCE_zDOS9G8_qFZYyJK3

!procedure SquareFontAwesome($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/SquareFontAwesome', $name, $tech)
!endprocedure
