' definition of the Item fontawesome-6/Brands/SquareGit

sprite $SquareGitXs [8x10/16z] Ou01Vap0mCy5985oJ21PLWOs49y7oETa0DBCA5fW7

sprite $SquareGitSm [10x12/16z] Oq00VXo07SxYumShOc1bO-9bu0QpkDZue69yJEnWCrZvOIRnSaDe7hW13Dny4C0E

sprite $SquareGitMd [14x16/16z] XOg35G0n0CLIkzr_shEPXq_EcBfHCEqNvu_9-iRYq041KtIYCJHbtXBka8h8uxkIvWsISos6CIcJA6qZf_OCvtIY1m

sprite $SquareGitLg [17x20/16z] ZSx50SL0203HYSkoJF_LVdVDk-7mhdlKWizgk5cJFacgt7AfcQwirQEEWuwL0uy8ILdZEa8pucDYRBiu9-AKIGwY0MyxrXcUFcXQPXz5yOV95rIV3BpQ0m

!procedure SquareGit($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/SquareGit', $name, $tech, $desc)
!endprocedure
