' definition of the Item fontawesome-6/Brands/SquareInstagram

sprite $SquareInstagramXs [8x10/16z] Ou01VXXW1N9u-U60Yv-1dn54WrX0cfkVWPaJ9iaE9jY054m_

sprite $SquareInstagramSm [10x12/16z] HSp50GGm2011uixsN-r9T3uuyi2Zeu-PI5FL78601kPM9YByizAXideoLi_nDpFZd9D1PzhVflG5

sprite $SquareInstagramMd [14x16/16z] NOe55i0m24E3pKVkVzlHD--lG0H_8Xzs17i6KrLRJe5vRxMG9iRvB3YoXYLd24ZTIsaIP8AwdKfhl0fLzhDfzG7EKvLx0ZP4rCmKusdcLknt_88V1m

sprite $SquareInstagramLg [17x20/16z] {
RS-r0SGm0CNGRsPh_saFmyahrKbtxiXAd8tEWwh5v2UgZlanqbB4N_RHyJ451AdMrBK6OnYgp2q8w3e4mySnQ49qXr3a90w1cGlGn9Sg2oM-XepzdneMBSKO
K-OhSQ71IT3L6m
}

!procedure SquareInstagram($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/SquareInstagram', $name, $tech, $desc)
!endprocedure
