@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element SquareFontAwesomeStroke
include('fontawesome-6/Brands/SquareFontAwesomeStroke')

' renders the element
SquareFontAwesomeStroke('SquareFontAwesomeStroke', 'Square Font Awesome Stroke', 'an optional tech label')
@enduml