' definition of the Item fontawesome-6/Brands/Untappd

sprite $UntappdXs [12x10/16z] DSl50SC034DHjM5y-qyRzh_OejpqMLFefVZxr_kZ_9M_Bq4bs0B9ZjTfywL_XBbM9m

sprite $UntappdSm [15x12/16z] JSd70S0m3CD0flTW_sdTROc_0rNsIgTi73-EIPFZ1wi9cFXCTLK_S6SUMLiz-WqmIRVLj-TNDNRhxz82UmG

sprite $UntappdMd [20x16/16z] NSw55SD030JHCREd_sxpDgpxnoZnTW8hnUgEKZdTxZHkfN7fEhPREfJ7W-gIZY-ZJtVnTXkTiK0inl8-8dB-UgH1cGt63eVH4-Tx_ZvxqS0eMPrGCftruW4

sprite $UntappdLg [25x20/16z] {
RSs5eO1G3CNGu4xsd_PBYyDvhfV339GzBwi3QCTJeQYyBSMg5HzMNVcmg5NzUT-rVeNt_YkZuwBstvB7d0f3j-JvzVzGpeOZPp2ibAQ2K9tBtaGmTPTFnvnV
8qqbj2PIOxfUIOjXmZ1ms0-w63cL_YD3k1fqWLy
}

!procedure Untappd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Untappd', $name, $tech)
!endprocedure
