' definition of the Item fontawesome-6/Brands/Usps

sprite $UspsXs [11x10/16z] Oy05kFaX0Cfb1ZF112Cx2nE4pyF40184CTcWyWnmNPmGm85iA

sprite $UspsSm [13x12/16z] VSl50S0W5C3GrBtPVzeATeE7VgEbAmWMVmUSmJvSTg1k_FpFXsrX5gOGS8VxluOyRtyOzTIz

sprite $UspsMd [17x16/16z] dSt50S0W40J0nHtwhnQtNsIYdE8NefpVn0hgc3fKj2E07G6-4j2UjH-_0vIe020r1Z82edvxe4Vw23836cGlaRq-TJqG7F5fYQZ81MyK

sprite $UspsLg [22x20/16z] {
jO-r0S0W54GFTzX_sWWkRVAQxtBu4-hI0Zf4Z19MMEpPaBsOiKoQPDxiD4MqaZpHFQiqCzbb9Mi17vykLHhQwQ00yWP-B4WSa2aZUfRbjam-Hd9LRCf4uiGU
UYdCYiONt
}

!procedure Usps($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Usps', $name, $tech, $desc)
!endprocedure
