' definition of the Item fontawesome-6/Brands/Viacoin

sprite $ViacoinXs [7x10/16z] Ou02VZ01fVZvkK0a48F5G034OmGI802bU1aPO

sprite $ViacoinSm [9x12/16z] JSa50e0W44JH6Rl__K-hqZpOLZ6JAc8AzK4NSM48pGPsZDqKuNvmAvX0IMrkg_C1

sprite $ViacoinMd [12x16/16z] JOk50SD03CJKXidQVzhWaynmDApHfMuFDFLAf7wnu-TEMgi2T2gCJe3-Y0XDoOOYu-Dmja_zJuM4BgKVf5BwmWK

sprite $ViacoinLg [15x20/16z] VOs50S0W4CIkxit-qzQBGz1mmCkdRXehrnwCJQ2T-LVer9YuUtRG_-4YRXwh0BPjW_hMzPPdtMvzJYdoLwX1Fz32OdG4a0NO7TsWaXVBPUyzxPJa1

!procedure Viacoin($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Viacoin', $name, $tech, $desc)
!endprocedure
