' definition of the Item fontawesome-6/Brands/Viber

sprite $ViberXs [10x10/16z] HOk30S1054DVxMR_RK_V383fqqFRQXErEbWh9dPqi_uDR5sntpHjt6rAj2JDN0tCA

sprite $ViberSm [12x12/16z] 9SR5WGH1000XTboxye_sb1UmZPuPD2QilVGtd9lSsRQBl9uczqeUmh7yVxz01ewA14QcuTC4jk0rgXrSD-0R

sprite $ViberMd [16x16/16z] {
DSd5eO1G00EmuF2i-q_x1Scf0fOwqa-lPDJpk7fI8DLd35fdeLwGIQZPxDUoK9kGXEiwM2AisM6UkRjnWUthChbzVKfFTjPyLqz2gyxXDhN5b8cCcTkU0cVe
VIJPt8g-hCliSnK-lm
}

sprite $ViberLg [20x20/16z] {
NSq5aWKX303HXb6qxt_RhL3xRHukILZIFNIqWvVKrD7xKBq9IIzUkXF0mPTiWrlW0lRMYAqm9pGdd3LN0C_eg1Nola_0WWcAyP9AtG4xVkgqYntcm5VY9N_k
6F8IiPamFK_xkglHbsu0lAYlg6tgWCDCil1o0BfgjipBgOHzhRKq0_ygJ7MsA_6vwpoLkl7b3m
}

!procedure Viber($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/Viber', $name, $tech)
!endprocedure
