' definition of the Item fontawesome-6/Brands/VimeoV

sprite $VimeoVXs [8x10/16z] Oq07ZFpy36py_8pyG9eNY1bGC1y30pi_I0e8G1I4Pa5e1m

sprite $VimeoVSm [10x12/16z] RSR14K100CNG3m2a_sx9k60tXpT9jPKc0NB8SZDAiieXkqHWY9v0F8kDpXFaqmK

sprite $VimeoVMd [14x16/16z] XOpL0GGm349JzxB_jjV8kRsFA41_IDhwECK3EAs0U-OQYC1KgOEIXsgiJMtxThp7PAbwhLo2RHOb332R50U6hcpx684-SG4

sprite $VimeoVLg [17x20/16z] dSx55SGm54FH5-Qe_seDEjeFt83n0_-vT6MKTa3D3Bpg63syCCi6oU3DZGkFpf79d96xZJV9EcOSIFeJzZOyT9iQyDyylTEEAIv20J6bMpDrMBnQ-LO5

!procedure VimeoV($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Brands/VimeoV', $name, $tech, $desc)
!endprocedure
