' definition of the Item simpleicons-6/X/Xero

sprite $XeroXs [10x10/16z] DSZL0O1G3CNGu3nfi_-qEEVd2a1nvUQZ_4KN_9LTQ3mFRjkchjrIJRlue_m5bg-S

sprite $XeroSm [12x12/16z] JSp50S1020314wB8zbzjN9WFJZafSxbnIoca54yvYgvghPYriz8wJRMBCGT4jKvLqdxEf_zfb8E_tHq

sprite $XeroMd [16x16/16z] LS-r0KGn30HHcK4m_LTx3DylcsnNNfgZIRwSj_6gn4_80nScubnbuTGmC1PiLe1ZMaB9GSOT8EiQOmIpCb4ogibIqBH0uYGSGZfNSWxgyc17FkJBcpi

sprite $XeroLg [20x20/16z] {
PSZ5OKKn0C0mzuNH-qzR_XWTnR-sdPadnNyhyCydxIpjPsc2uZlmKF7Kh4EPC2GdsBgrZ63KOfvZ6_p5C9HIBCreqgd1FCBQ7nQlFPDcfzhiJRUsgU9XiNoN
k7m7jBEW-opmA_d0NVNNIlpu0W
}

!procedure Xero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/X/Xero', $name, $tech)
!endprocedure
