' definition of the Item simpleicons-6/Z/Zazzle

sprite $ZazzleXs [10x10/16z] Om02Jdus1X3W1mDE80CAM84ig0mdaCNF1fE1A663CC280wgEWHEkX84LoW

sprite $ZazzleSm [12x12/16z] HOl50S0m4CCkpF7-sxOgwcKq6AfsevjF0fAavAnrwcWZcYLfI2s8-x-4AYqaXI5XewbA65AXlzcq2qLw

sprite $ZazzleMd [16x16/16z] {
JO-54S0m30CTvlp-s_PK_WCpo4xIOZXxM5oKA-Hb_qCnhsQl5SrdUTUSUoOJIcumSm1gfsimyP7D9eW1u3JQDOMxhlf1i0uODBj1jGnLDqDI--zxaTGs_w7m
FpK7
}

sprite $ZazzleLg [20x20/16z] {
LSu53WGn3C10BsFh___scgNeHbY85HvRzPmXBJvApqFJbbTfpwiqFQs9PbnNPXM-o1TQiHdezHY0msQp6Pbr_jhLK7I0td_0xEFybjfr6WpnUAKY4WyDQizb
6k6CE4LNFZOJlRh6wp8Cgm7O_4U8RXgUk8dFwgLCX1y
}

!procedure Zazzle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/Z/Zazzle', $name, $tech)
!endprocedure
