' definition of the Item simpleicons-6/Z/Zotero

sprite $ZoteroXs [10x10/16z] Os3WXm0610i2cFYPGHHO72U35SZ0gGWAM

sprite $ZoteroSm [12x12/16z] Os3WXm46P3OOW4MOO4nUVYuOanL91NOc7pydZCcE46R4hfWDOIy

sprite $ZoteroMd [16x16/16z] POl50O004CEAEzb_MbnEygj4MlXfbNFz0iWmGcNYCOyomEeZDYvGcjXwkGZl46SeJEoWy_8IvENZp1Rj

sprite $ZoteroLg [20x20/16z] ZT053e0m50JHnHtkVricscngV-AlNacVXyJCEw31QOGcfm4wvRtvPbTE2pJBWuwSdjXcoY-xPvjbqvwSDcZCDpkdLFPzD1Vj1m

!procedure Zotero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/Z/Zotero', $name, $tech)
!endprocedure
