@startuml
sprite $AwsGeneralLg [20x20/16z] {
RT150iGm34FHiYrBcViVTvoKuU_w6ku-wnyb3OWQzfO-BIHkHMQRgNrVZChePXwy664WaNgQBspJPoCFSs_ZxB0YvxfUfFbXTQnuiL8DaC9F0vhHBwRm0CB0
pLGoOLb0POTbJ3djLxPEm_5InrlrmwEqZ_u
}

sprite $AwsGeneralMd [14x14/16z] LSx70GK1209HVrH6jlzoDySvyMx4iszc_hS-4Mdt4l1RDBEAFYH1QHT9j_xgMJK0AkbGMpAx6eF5fW4jzQx1yxOFpLxwhS_-rxEzrrp41

!procedure AwsGeneral($id, $name="General", $tech="")
  CloudElement($id, 'aws/General/AwsGeneral', $name, $tech)
!endprocedure
!procedure AwsGeneralCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsGeneralMd>', 'General', $funcName, $content)
!endprocedure
@enduml
