@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureDataBox element
include('elements/azure/StorageServiceColor/AzureDataBox')
AzureDataBox('element', 'Data Box', 'an optional tech field')
@enduml
