@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureArchiveStorage element
include('elements/azure/StorageServiceColor/AzureArchiveStorage')
AzureArchiveStorage('element', 'Archive Storage', 'an optional tech field')
@enduml
