' definition of the Item azure-19/Item/Networking/ServicePrivateLinkService

sprite $ServicePrivateLinkServiceXs [10x10/16z] Oo00E4048nk8mGfX0jbix0mCB0oC34nWUNOW3K8C418J

sprite $ServicePrivateLinkServiceSm [12x12/16z] ZSZ73S1024JHJwR_YgtHNfqU6VvPfCuQwL25rlEjxi0OSg1nXrHgKSsO6u0ZngCB

sprite $ServicePrivateLinkServiceMd [16x16/16z] hKp55S1G32BysFuBLtZflHON03zOG-Ongrttc3L9TnsqEc1UwpnadWkDQAIaw81xj6ITq045h81BMGVIjEempV3STW

sprite $ServicePrivateLinkServiceLg [20x20/16z] jSjN4iD020DGqSdzBvmLZ5E_BNlR6u4x8lzahTXqlCXV0vqliZmHuZJraCn8NaqIE1lfOjlCv9aeeE4-2EMPslLGCk2AmNr1Qkc59oG1NiXShS4N2Mx84m

!procedure ServicePrivateLinkService($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Networking/ServicePrivateLinkService', $name, $tech, $desc)
!endprocedure

!procedure ServicePrivateLinkServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServicePrivateLinkServiceLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServicePrivateLinkServiceGroup($id, $name='Service Private Link Service', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServicePrivateLinkServiceLg>', $name, $tech)
!endprocedure
