@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-23/bootstrap')

' loads the Item which embeds the element ServiceMicrosoftDiscoveryCard
include('azure-23/Item/NewIcons/ServiceMicrosoftDiscovery')

' renders the element
ServiceMicrosoftDiscoveryCard('ServiceMicrosoftDiscoveryCard', 'Service Microsoft Discovery Card', 'an optional description')
@enduml