' definition of the Item aws-q2-2023/Resource/Database/AmazonDynamoDbAttributes

sprite $AmazonDynamoDbAttributesXs [10x10/16z] PKc30G0m34ip_t_mx2h4DRHW9G5IcYhLOOFMxpQgLkgmVMt3tnO

sprite $AmazonDynamoDbAttributesSm [12x12/16z] JOo30G0m3C1IJFyVF2ir-L5n4PLEHeo0qkavaPiFZYU_lk4dZmCTBfC7EZs2o_lvyZBGwHi

sprite $AmazonDynamoDbAttributesMd [16x16/16z] NSw50GGW20NGJyF-0r_O-km4l2h_YhD3mYBWZ2PxkTPmEjRKhR7YBpcQzjRk_mhr_8TZpTqQo_-IlMd_wPFV-vyIOgqVNm

sprite $AmazonDynamoDbAttributesLg [20x20/16z] ZOw54KHH4C82J-c_u7E_RnbZrh8iCVF0hq30gJ1jRkXM2tEXbh-Qkg-rmgksuEXFz0e4QFmxb4E_b5bVjLMld_0AH98bJLVTyDrHbxpZhzOpzhqBd04

!procedure AmazonDynamoDbAttributes($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/Database/AmazonDynamoDbAttributes', $name, $tech, $desc)
!endprocedure

!procedure AmazonDynamoDbAttributesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonDynamoDbAttributesLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonDynamoDbAttributesGroup($id, $name='Amazon Dynamo Db Attributes', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonDynamoDbAttributesLg>', $name, $tech)
!endprocedure
