' definition of the Item simpleicons-8/Y/Yolo

sprite $YoloXs [10x10/16z] VS470SCm0C0mv_-OFzi1M5k9Rwr9Deo4VMJFk1ASshk2h3p6ZipTm5bvyWC

sprite $YoloSm [12x12/16z] ZKZ70SD029DzHuTe_sdJtYa6TLmx5Ltk0aI6PeUOZ42hYrmhIO3PvA5yPGlXc1aLy1k0UAt0-PRZmDTx

sprite $YoloMd [16x16/16z] fOt50SLG3CFy85JI_jEM9lYWe4xM_pItgP6PTelFOK4hSyp29MD6ve7GKhXq13qXg1sGaYLudTTrb04hli2yVKtv2CSPRmAhtsTox5Cti-kXzzRqFHS

sprite $YoloLg [20x20/16z] {
lStNOKKX30DGSN6dQFzjOuR8Et-kme-OgGYcHuJYSGyFNgGOEIHp8XRfpbaymPFXt0eZ8_C8MMTdNJ80eN2mdKZh5XSmYbLiEohOwiKovoAPiMIJT032X2sA
vChQ_0O0vLAC3vFDFhIEcuvcF9M6H-V0qwlV6FW7Vm
}

!procedure Yolo($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/Y/Yolo', $name, $tech, $desc)
!endprocedure
