' definition of the Item gcp/Item/Networking/CloudLoadBalancing

sprite $CloudLoadBalancingXs [10x10/16z] 7Kg55GHG2BgmdyZ-q_uoAHBTmF1KY9ZLHQbY_X2dwfceYgW2sN5HD2UZ_KnEd_ZVN0mNtN6mWJVS

sprite $CloudLoadBalancingSm [12x12/16z] 9SQ10SGW24FHkrP8L0dxRrkLhy3BJ4L8obDOCm2wRk_hNbQdOmnbDKPTzTw1lRGD7XFR2oj8BKJA3DwSPbIqxTUnZsHE6BYFKhlGAJy

sprite $CloudLoadBalancingMd [16x16/16z] XOx50KGn24GFP4SYq7-rwsx_HV6fJv97P3ilzceHWIFhXqrW1qdvQ74l_hGdxyoJFK0IvskSRQwJX3psFTbJwBC3One-5Z2Eiqxp6GtUjasvyt9vr3i7

sprite $CloudLoadBalancingLg [20x20/16z] {
fP0r5WKn30EBn5hbhU7-fmr-PfZ2bgO9n1Dy7-ZWv3Id3WRshJCHoHbRv-J2tPMqlk8I9o-5MqT97TkNAxYWBCTBnwDJCyMQ9sVzFfXpEOK82oMZJ_If4NjA
0cAyOqFAm9_ErtUEiQR78ne
}

!procedure CloudLoadBalancing($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'gcp/Item/Networking/CloudLoadBalancing', $name, $tech)
!endprocedure

!procedure CloudLoadBalancingCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudLoadBalancingMd>', 'Networking', $funcName, $content)
!endprocedure

!procedure CloudLoadBalancingGroup($id, $name='Cloud Load Balancing', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudLoadBalancingMd>', $name, $tech)
!endprocedure
