' definition of the Item fontawesome-6/Solid/_3

sprite $_3Xs [6x10/16z] Om03NduG0B7usK44AmC38pylCmC39qoS0KgoyxEn0KLuGS8

sprite $_3Sm [7x12/16z] DOc50G0X30Fl5OVzfqKgLqs24eP0hRMF3jos6t3j9CZP8FWfGt8aQj1wkra

sprite $_3Md [9x16/16z] FSQ75S0W201HqXlFst_RIFqAdBGHpa6ITNhdDKVU7PQ-1dDRT1d8kCcu-29X0rK55SKCQJy

sprite $_3Lg [12x20/16z] LSy30W0X50JGMMJC_K-R-RBxE7qB0XSdkOYnitJLxihPNHkUknlCrpSCR-aR3W-mTWPCFucbzCNkkxdDaueCKihIq21oyC2CGEAI0G

!procedure _3($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/_3', $name, $tech, $desc)
!endprocedure
