' definition of the Item fontawesome-6/Solid/ArrowDownUpLock

sprite $ArrowDownUpLockXs [12x10/16z] DSR50OK0042XzpkL_QUrvKIRePt2UN3ydQwTrAZHBYbjvFQK1C7vwFWC

sprite $ArrowDownUpLockSm [15x12/16z] HSx50O0030ImmvtiFoqk-TMRMvUFfEUD2XdW3mrclZ0nvrPUB6KMidf5nlbglacp_hDWqUfzOM3ymp1SJu8T

sprite $ArrowDownUpLockMd [20x16/16z] {
LSi53iKm3C1GHrymQdp_qtugUoizAOmAjUMbCdkifBjPM-tnV8pT2Bv6iFSpYES4igMPDwgaIr44wzIBLau3k3D0CtsuV_RR3QmL_SxgQksyDgCIzsheIQrK
-m
}

sprite $ArrowDownUpLockLg [25x20/16z] {
POw50GKX5CDwhe_iF-sNdWB12LAzY445dVi4apBm1b0QM7pUfXHSZ9LO1X1GY6xGNsZEOePVjgXv192yoWWb8dd8sGHo6-SPOhxeH4Y9EzL3BVnvmqd7R04M
JvY06TPK2N6obk8qYofXipf49lAuJwel
}

!procedure ArrowDownUpLock($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowDownUpLock', $name, $tech, $desc)
!endprocedure
