' definition of the Item fontawesome-6/Solid/ArrowDown91

sprite $ArrowDown91Xs [11x10/16z] Oq01_43CmSyFPe8nWWaHXH0yS2OtN1ilH1L87IUG2TN1oC-6R08

sprite $ArrowDown91Sm [13x12/16z] NOs50O1030E3ExV_jCXxtPl8oNN-4RgGxb3lr6PHRNgeZMvKcrvD0o5mWuxqGiXdQBf0jq7eXk4VtVUc5m

sprite $ArrowDown91Md [17x16/16z] RO-50SGW40Gtdc3JVxMlE9oxQ0Rx_TV6nG141NLWPnEs2XmimlKjUnrGDoFgshYMFl3yb1N8bX4RWCT8uHVuQQ0P7dqBRlXbqm1l

sprite $ArrowDown91Lg [22x20/16z] {
ZT253S0m44DHbxb__sdB63wHzK9M59ZYJVaJ9xepj02tpWndW1acGvjT84a5O6iDK9gg4aPPEZ7BLZtXfqLcw_GqW6pJuhYGZmBNfcwyDUUSkva-rJbUoLge
zVvV-RdjBacbHv-Mrgm
}

!procedure ArrowDown91($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ArrowDown91', $name, $tech, $desc)
!endprocedure
