' definition of the Item fontawesome-6/Solid/Backward

sprite $BackwardXs [10x10/16z] Oy0EMFcX13y_bE274NpyS2uVd61WXX5002NW

sprite $BackwardSm [12x12/16z] Oy03cFdX91S_dEJZXvD032E1V8G8BnB9m8P4CZ31IH20amW

sprite $BackwardMd [16x16/16z] ZSU55S0m409GwbxsdxOIz-I4_q3JT8VdIBhkzBpeINfIUKjlstql9Ov0ZCf9YTxp7y_Yl

sprite $BackwardLg [20x20/16z] fSW53e1G081Gx9RxtzQ5tVfPlK5uYUwLUL3jGNfGVr2aUsLEaKpgJnxzoQC_4UM9I4v4V28u4tKzgMbusG

!procedure Backward($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Backward', $name, $tech, $desc)
!endprocedure
