' definition of the Item fontawesome-6/Solid/Bacteria

sprite $BacteriaXs [12x10/16z] LOk53S0m0CCoJL3s_zUMCQAGzUe3feqS3w7vdsgLUjr6M1PxRAh7RhNu2aSqDOu5

sprite $BacteriaSm [15x12/16z] Ou007WOamC_FZyG10oGUEvJB1UB2P244BvY6YaCauKRmmNXyC2ry809kF2D49ICGSq8jumRByM0u3

sprite $BacteriaMd [20x16/16z] {
NSo50GCX50FGu4xstxODd3-SBpXrVCn9UZnnKYfkXjl0XNzPcuEiR1NEetRKrJTph5I8rQs3j1Wqxkwi74cGGOcL0d696zpnL-pW1Y1D7tVTN76B2qcZhHIS
ClywsV1WAQRWASz00_a1
}

sprite $BacteriaLg [25x20/16z] {
RT25bG0X30JGmJLC_zMU9Aky_RWBRYNX0-lWnAvZyT_0XfTj0Ky13y9__hcWn7kZmdyE03tPRGNjQCdTd_E6bdgAq47HeDc0mFXAbJ1fO3ADIrJBzWc-qDH6
bRSNoR267h5a-m56g42oezq33cRQ2qdEYOTm_O3WfKmQMTWClJW-CBimO7u1
}

!procedure Bacteria($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Bacteria', $name, $tech, $desc)
!endprocedure
