' definition of the Item fontawesome-6/Solid/Bahai

sprite $BahaiXs [11x10/16z] FSQ50O0m00F1mvtiForEemzgm6wF2UGHc3xqtBTLmfO1NL9BTkGJA408d

sprite $BahaiSm [13x12/16z] JSV50O1G081Gx9RzfpL-S-BnDz6apUcOF1aAFynUfpeFSAaptEe0Q0-xGe2W0QQ2-c33_BG_97T102y

sprite $BahaiMd [17x16/16z] {
LSs5OO0m04JHmvst_xILIEL3_2GL-S_aJ3gZDJUPx2aCF3YPKz7v3M2XnHpzxOKdMM18kxcJvAhYcRVNMbAaUs_biiBQIb_QN1HZ0lQoBSoaD7HMQmRoovIa
opy1
}

sprite $BahaiLg [22x20/16z] {
VSw55GCn3C1G7OUr_xPzBlCFeytDcFbqE7Wnnteea0itNJVKPHhAJLB7hN7dmyfTLiq6hceRwf5O5zLUzyVhdSSSc8Pg8io6Wp2f4lfjB-pQ9u13ErUROGPz
9BngQFRhX53rjc5xfBnCp_dD4tVgf6QUpPgOhty-A53C_7K2
}

!procedure Bahai($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Bahai', $name, $tech, $desc)
!endprocedure
