' definition of the Item fontawesome-6/Solid/BanSmoking

sprite $BanSmokingXs [10x10/16z] 7SQ50G0n2C30lFjd_scBf0MEx7AdihiA4o-uuPGynKkAO5MytMswYMIJbrpDtfiL1

sprite $BanSmokingSm [12x12/16z] 9SU50S0m3CH0bHlK_jC6p_XCoP_D3M3lMq4Du8i52KRuZcWInZwE0_NmIYOo_XxEe8WtG3GKKQQW7sW4YfLvd3xe

sprite $BanSmokingMd [16x16/16z] {
DOw74O1020GFp0fi_zKQdd4_aa-39RbCFqcpjGd4x4j1jecatMKGKj8EBXEOGErmDC52TCa0adcz1DJBAFOWEYCikLY2TXJsRahkBW7UpKq3uAIqWXg0LZyF
-uHLBm5a5cs-68FIomC
}

sprite $BanSmokingLg [20x20/16z] {
HOy74eGm3CHI3aZN_tzxs0j4bDWQbqbug8jnAXG7Y1bV1PkwrS-Z0hHNMSleIevtLh9yLfV-YwYoA2_1PYKWXvjxxuGATwnA9yE2mB9ASKQC0BoLeqKOSgey
ycm9JZbLcYxWkuMsmxJTKjfU8NaGTgMokkME6p1pZAdevix1HiOe4bD5Vm
}

!procedure BanSmoking($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BanSmoking', $name, $tech, $desc)
!endprocedure
