' definition of the Item fontawesome-6/Solid/Baseball

sprite $BaseballXs [10x10/16z] HOcr0G0W40CFXohxJul3MnIWAR56UzeJKbgAapvXGxxyAjQtrq8w7GC

sprite $BaseballSm [12x12/16z] 9SY55SLG34CnVonN-qzRiXxadkJsCwROeQcQSTk2ryRjjqkpQiseCX1DQ1lkby2AFPUDkBSd

sprite $BaseballMd [16x16/16z] TSU7RSD0002nSxSblRZ_j2aFfCT4PTCbww4FW-3Q10SmFlfXgm5hJ8T0EwOBrbOVwY3FT5pvKCPsyA4RzBDxru-3Qk33jMg3naVhWCDchte5

sprite $BaseballLg [20x20/16z] {
VSy52WGn40NH6lUf-zzsIVWmZUsBUveuy5ue5XNLPo1ii3lAb9TsvpVrMM2nQss0tOOQEvcw_HogP2g0oyN_LgRRQiHj6bUB6b8mspmyzM3QGGFJmc44pMct
RZdPBJPCsHMxEeq-8yqF
}

!procedure Baseball($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Baseball', $name, $tech, $desc)
!endprocedure
