' definition of the Item fontawesome-6/Solid/BowlingBall

sprite $BowlingBallXs [10x10/16z] Om02Jdus1X3W1mDEC8CDHB022PWeX8i2sE0i1WIB4yPWO625CW

sprite $BowlingBallSm [12x12/16z] Om01RduE1WZWXm0eauKDmW6HpAmWafS1o6VZumEhueRAeWCE93O3TZOxGXiVo39Uc2W

sprite $BowlingBallMd [16x16/16z] RO-50SDG20MlZUlRVzeO4hslE71GJHf-19ECnaGbSuh-ZE5CfOCVPamgCwRASrFgc-4X_nuoTt6clidMVL83Z7SHVfTfLW

sprite $BowlingBallLg [20x20/16z] {
VOo50S0m3CCynjJ_NpieiufH09P3yLuHiT0YWrECE6ArtEOzWrfz-U9dIHWAk3kmEwU6pSj3D-eftYbQnfCzRfQiB46f15Au4KFP2Xob0iwiKxCm0CzkX9YY
5m
}

!procedure BowlingBall($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BowlingBall', $name, $tech, $desc)
!endprocedure
