' definition of the Item fontawesome-6/Solid/BoxArchive

sprite $BoxArchiveXs [10x10/16z] Ou03NdvCmC060mnmCP9Px

sprite $BoxArchiveSm [12x12/16z] Oq02xFpO0GCJ0Z0WXFaOG0GGGDWGG0QRbu613mfu6G

sprite $BoxArchiveMd [16x16/16z] Oq07V2Y0Xvy0O6121GpSFCW0Q1wASWYV3M8Jb0y7DE6peVBH0G

sprite $BoxArchiveLg [20x20/16z] Oy06c3404oy_-O212HCmCBAX0w2z65hnY7537OjDtI0KOq0NOiSQz

!procedure BoxArchive($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BoxArchive', $name, $tech, $desc)
!endprocedure
