' definition of the Item fontawesome-6/Solid/BreadSlice

sprite $BreadSliceXs [10x10/16z] Oq02JFmW06Jmmm0Fd8KGWqip4Ci2

sprite $BreadSliceSm [12x12/16z] Oq05BFn0mCS8P37omm030pzsmC0BPt8XAM8WdSt31m7i3

sprite $BreadSliceMd [16x16/16z] jSUr0G0X002nUy5j_srfS6X95quU7QANTI5L1X1f16aMbwlb48OzpEV2tVHL1W

sprite $BreadSliceLg [20x20/16z] pSgr0O1004FHZplPVrhSm_NtkWXXIPfbMSejrQK_BgEUEg3G5yWClTmeXqm7dtQ4gBi1xnf-pG

!procedure BreadSlice($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BreadSlice', $name, $tech, $desc)
!endprocedure
