@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element BreadSlice
include('fontawesome-6/Solid/BreadSlice')

' renders the element
BreadSlice('BreadSlice', 'Bread Slice', 'an optional tech label', 'an optional description')
@enduml