' definition of the Item fontawesome-6/Solid/BuildingFlag

sprite $BuildingFlagXs [12x10/16z] ROf50G0W40G7T-YV5d-Uhp5k4U73qTx5AEh38zGQniS_es5dWFhmAmc3W1S

sprite $BuildingFlagSm [15x12/16z] TOg30S0040ElPZxxJriRpmYl9Me0xyNsUoj21wM7b8C-mZ7rD5Z07ZxeMlyqQsyK3gex7G4

sprite $BuildingFlagMd [20x16/16z] ZSo55OH040JHkiDjElziUOqx5Bf_XKvp1GJED8SKJdkRAlzH_ltUs9yM_DvOjDDjEsPB0QIIAF3RzhSTpfjCCTrRc_fWzVzim9iL5zO3

sprite $BuildingFlagLg [25x20/16z] {
fOq53W9100Dd_Rp_VorknU4cQQp6e1iYp9K3WmoIb0x8eUY1HmEc2PJWqUX1yS6eTQUcgGuVFkO3JmmE73xc4PG9PjYv6oLfILbZwirmrXjBpCyDeBmouhT6
CcEv6bi
}

!procedure BuildingFlag($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/BuildingFlag', $name, $tech, $desc)
!endprocedure
