' definition of the Item fontawesome-6/Solid/CakeCandles

sprite $CakeCandlesXs [8x10/16z] Om02LX31mSy0X406CmCF0pS30nEO3wVP-540I24d0m-6C3y

sprite $CakeCandlesSm [10x12/16z] ROd50S0m4CDKvch_QOFFd0vjmmaR3Mjljc-MIpf3EirEX-n6KFkVdN6QPFum80C

sprite $CakeCandlesMd [14x16/16z] ZOc53S1000Alxh3_jdMt9y61V62saCp3i13iQkNu2GfDVaFhY6vWuxLfO3kst9OMHaC9HAMOSk3ggMFoWTb0Vq2drWC

sprite $CakeCandlesLg [17x20/16z] {
dSq54eH044FHCEwv_sqtlUxsgtZ0A8uv8nd0ceBTo0A1t519O0cLI8zXtnHMBQ97CHoUHWBUg5pV3CYRVE8_jIxA544FnWRu0I1rKPh3DZNcLjjqTm7-kO9t
xG
}

!procedure CakeCandles($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CakeCandles', $name, $tech, $desc)
!endprocedure
