' definition of the Item fontawesome-6/Solid/CalendarMinus

sprite $CalendarMinusXs [8x10/16z] Os3WOM1WO0PYVWO69du6VYZWX09-d80Lf0S3

sprite $CalendarMinusSm [10x12/16z] Os1Wu0PYFWOWOEK74a3Cpey96E20dn30eueNpW8

sprite $CalendarMinusMd [14x16/16z] bSI50S1030B0f2vGzf-sxlw7M8-slK7JU_yr90BZPzGpF-21Wg0SD9hOH25oxNK

sprite $CalendarMinusLg [17x20/16z] Om02Dbu6463aPu02Vduc4CNBpuKkm0rMXmhu-0a2JdJ0Y0xuQGN0VaDsDG_SbrG2pEZX0G

!procedure CalendarMinus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CalendarMinus', $name, $tech, $desc)
!endprocedure
