' definition of the Item fontawesome-6/Solid/CandyCane

sprite $CandyCaneXs [10x10/16z] FOk30S1054DJks__QK_V33HYHXO8xEuRUK0UXstz_6tl04PmTM1AsmERcIe

sprite $CandyCaneSm [12x12/16z] FSY54GKX5CNGYplflzelkmyoTYQozZYY0i6ysn9cCg0JMgR0_JH1_AjoBnHH_vehd3bXu_IKOSdw0W

sprite $CandyCaneMd [16x16/16z] JSp5OSGm54NHRxRmz5zjCYpTtSFuSIinI3BgLru4PqiVtLZa83vWXPXejrbtLmnzWPycxY4hhFfRhMh0zhb5NgJlpx5DHoVEqpb-qMA0PPB_

sprite $CandyCaneLg [20x20/16z] {
LT350SGm34JH2SUatt-ropjHtj4MAvaxJJSpl0rT3b050Xcmp329cjy8cW2_hK2RUTDbbzJzPWUJ9fJnTkItmjVcbmMa0C9F_HinA6u90Rdd531h0NRzLDwY
4AdsjF2sE0--3QiiyDMiUSmaeEdk2G
}

!procedure CandyCane($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CandyCane', $name, $tech, $desc)
!endprocedure
