' definition of the Item fontawesome-6/Solid/CaretUp

sprite $CaretUpXs [6x10/16z] Oy02MFY111C_Fv3Y1m56C8cf3W

sprite $CaretUpSm [7x12/16z] Oy01sC4a6py_a6JcvmVH_6300Q4Oy

sprite $CaretUpMd [9x16/16z] Oo0IS391Q2v-VZ2BdHy8W3GBa0Ap-A603yPWO880HWPI

sprite $CaretUpLg [12x20/16z] jSQr0O1000J1mvtjlrgSl_nbeb6gRWvj0HVsfpMFtOLD8jXsh79t5N02

!procedure CaretUp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CaretUp', $name, $tech, $desc)
!endprocedure
