' definition of the Item fontawesome-6/Solid/CartPlus

sprite $CartPlusXs [11x10/16z] O-BdO803VXY0C9dWJA0S3uZaWeho8HI3zK7reueoCS19i0PUVWO

sprite $CartPlusSm [13x12/16z] JSc50G8n40J0ZNks_suv0VudEOya7eqFu5AihTbFf_PhGv2SGaZa1K3HfwJWWuCWNkxxWkW2HF4LjsL6B_W

sprite $CartPlusMd [17x16/16z] LOs54OHG4CM2Ezj_jIU4Rnd9czK-OgTcZOYxueGkv5Q0uQ8jN3jNAjpQvHdOwnM0mPkbO9BJmjmbiB3Ju1iPhFGPvEZqkkdqhNC52uQEBm

sprite $CartPlusLg [22x20/16z] {
RSw53GKW34NHuixRVzel3GudTeDM0l1qolXH1yaRbz-gGnFLiZfQKeloMsrTYwHIEErSNNuNSpKdGIdD0_5uj_AgRgj1WcbYrxHjDInaMwsWXumO9jrMBLQL
6hcYxfaUY7SMeDvf0Rlb5m
}

!procedure CartPlus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CartPlus', $name, $tech, $desc)
!endprocedure
