' definition of the Item fontawesome-6/Solid/CashRegister

sprite $CashRegisterXs [10x10/16z] HSG50S0m00F1Z5Ty_shBS045YaC5-nfLB-Oj92PnbxmuJb0BaSrqEAOC

sprite $CashRegisterSm [12x12/16z] NSR50SDG04Cnjm5_VljF6sQT9BCAMf5i9_RljFd_-V_t9au_qIgc9y3oHZXFCq900Xg9p9TEZDnc

sprite $CashRegisterMd [16x16/16z] XSVL0O1G34FHu5PwzvyMU_x5gKOYS0LErAUiJyf6r2de-nxwFaNjPc31AD4O15hHylMA2pPdXTNVHW3drmOm0OUmhm7Zpz8L3lXPW6ZT

sprite $CashRegisterLg [20x20/16z] {
ZSZ5WGH030InzZ2wye_sS9drbBJXm7GGEJjVqx_By_vdd2zmfYCB8K0DmNIMIu5U3e8auuPBYrj1i9LfcfX0WYmWEIHO1Tg48Uxi033LYN8aVZK0jyqCK0A_
d8-DVcdpowuacDoJSwj_0m
}

!procedure CashRegister($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CashRegister', $name, $tech, $desc)
!endprocedure
