@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element Cheese
include('fontawesome-6/Solid/Cheese')

' renders the element
Cheese('Cheese', 'Cheese', 'an optional tech label', 'an optional description')
@enduml