' definition of the Item fontawesome-6/Solid/ChessPawn

sprite $ChessPawnXs [6x10/16z] Ou02VdvU1WOMVdv-1WOsCCc0IlB2sPoSd0oC_2

sprite $ChessPawnSm [7x12/16z] Ou019dv-4CNF3w8P8HG3bEBWvsT2ua5Kyi8rS8CD0Ck00G

sprite $ChessPawnMd [9x16/16z] NOl50S0W40JZ7kY_MyvjNgjJv7icPEq0YewyAhgA1kBKpOTYrUgHspzLqPEO4Np_nFLtOG

sprite $ChessPawnLg [12x20/16z] NSu52i0m40NHkilzJvkLsSAdWxrukd_3s9Vwrxlncvt1wQNmBbx47UJmnBJCFvZIMqulRE8eoTb1lAkpATX_yVdg4Hi

!procedure ChessPawn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ChessPawn', $name, $tech, $desc)
!endprocedure
