' definition of the Item fontawesome-6/Solid/CommentSlash

sprite $CommentSlashXs [12x10/16z] HOo50O1058MmM_QVrlOUlxE6O8KNsrjyFCMUGfhaGd9dldnyekOFutlxuGa

sprite $CommentSlashSm [15x12/16z] LSs50S0W40J1ZNlelrgSbqC7dV495smXPrZI_3f_h8DtFGp3XSE3vTJTXkwVQJmzpeM__xCt_sNxcnWvGW8

sprite $CommentSlashMd [20x16/16z] PO-50G0X30FxBaZsdnOFUlXXxVx9mWihaLkR_w0y0DbHiBJesOlKlUJ9ktCsYrDaEgW0HTbSckZU7MLsDSThV5Gbju4BosDqSVan4mkooHwx5B2HHdnvmS03

sprite $CommentSlashLg [25x20/16z] {
RP453i0m30EpCll_lvtAUEBTajWg2_Gc01yLFiOveua71155DFGm2d0E2tCC1sOvj2E6iOUXGd94V1UodpWF-N6RvToJE4HEegS8K-HfDeIUaVP3Hq7HVt9D
i6uiaG2GHhqjpIAEpgc_XClJ7xCXHg_p9vFJrrb66wnNl4du0G
}

!procedure CommentSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/CommentSlash', $name, $tech, $desc)
!endprocedure
