' definition of the Item fontawesome-6/Solid/Cow

sprite $CowXs [12x10/16z] Oy05UFcX0CZcvsS1aipy_7pCG3O_1mCRM0P8mW4F0vJ12z81man0NL0sY00X9

sprite $CowSm [15x12/16z] XOt50S0W40Hnb_wx3NFn5uEUxQeDysP8LASr2nA4UgQxAKp2EKmW8a7ueJsXugWLcZODOPMGY_3Ivf8RZny7

sprite $CowMd [20x16/16z] ZSrL0e0W44NH0Tk9j__LAXr_NFj8q7gUfSHR8SDOeXkCrwSQGXatfPAz-qrW0PvfaMGX6vOzivNkydI3EItR1DF1zcA4NNrukWkmQh5eLEPojl84Tbhi1m

sprite $CowLg [25x20/16z] {
hT250OH040J1mUrsE_zeN-RTjN0QFVrLpuL5Uy6rIbir2THxcCD21KLxwH1gf430A9l1HfPz84_Nsw9qkB7qF0ZS164bTJz83Za0D8TGbMCGTPToA7xICLHI
9GUl-sCm7Ah3U0qHZQoFgBqPzBar
}

!procedure Cow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Cow', $name, $tech, $desc)
!endprocedure
