' definition of the Item fontawesome-6/Solid/DeleteLeft

sprite $DeleteLeftXs [11x10/16z] Oy05-A40mU87itWO61Zv-Vd00emCC55s1au65BN89Y

sprite $DeleteLeftSm [13x12/16z] Oy0B-640cSqFORFpyJC1AOWu7mCJ0uY2A601ic4ox0my80PSFo-wQUZs8

sprite $DeleteLeftMd [17x16/16z] ZKm30a0X5Ditg_kVDjkBRy8SrjzZKVF98iZvO2cnwvV8ysbYTG8xGDKdobxgfOvuOJJd-B0PnlAgYveEnpWWPv0p648

sprite $DeleteLeftLg [22x20/16z] hSg53SHG0CDGb_lH-qzxp0nzmbXX8RDNPhQ2DuxFkpfvvnn7aZQuTOfcAD2urNkIE4QhPmqS9bSHohwUyWI6m-IKSwk6_bZn3bkFAuyhgLn8V6CD

!procedure DeleteLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DeleteLeft', $name, $tech, $desc)
!endprocedure
