' definition of the Item fontawesome-6/Solid/DiagramPredecessor

sprite $DiagramPredecessorXs [10x10/16z] Oq00VYXWW58CS1PCa8k1aPyPMGS284JO880V8Gi

sprite $DiagramPredecessorSm [12x12/16z] LSQ53S1000En2CfHRlzfoqyMMJsAKcmern4E_m-WFJT9GGDwBW0Lc4PxYla2

sprite $DiagramPredecessorMd [16x16/16z] NSq54i0W44FHu0xtFsszOMTV1VvOe8L9vSgu983NOEsKRKoRgpSsmdkmaUw_b9XgduRSv_0shhROxXvzupv1EG4

sprite $DiagramPredecessorLg [20x20/16z] TSg35KGn00NH-KOm_LUxPd0F7sYQVetSMG2YXVtlTW3HL7Hdo1hElywdpO-HqRkPwCi93Ef4ONIcOogCO2L6c_WpTBlrpwQRDQAbcOOh

!procedure DiagramPredecessor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DiagramPredecessor', $name, $tech, $desc)
!endprocedure
