' definition of the Item fontawesome-6/Solid/Dna

sprite $DnaXs [8x10/16z] 9SY50S0m2031htj__scJ08Tpx8H_iI117iC4Yd_-N6km2wOJZ-1XwG

sprite $DnaSm [10x12/16z] DSR70O0m3C10qJlQVrj8RD_hjfVWQi7dRfJNs0owRRloqwibUjEC2hOPMeR62ylf6_m

sprite $DnaMd [14x16/16z] JSs50SKm203Hgtjk_sc_bDYB2x19jNkQAiKUkexXyMJKEoZmM4m0wi2X1r1VDmYg515obaEgCrOddAOXAEXJgwVHtkD2aVm2

sprite $DnaLg [17x20/16z] {
NSVH0K0m5C30041VzfyMW79_rpcIqLchLwELF_WrCIctNWlGc2yQG6U6NT84r6hD8THoK5ikauU6HwZoADGeeSm-0idWeAPXeqx7SnNKsXMNK0ZjReFM-1MT
Fs6GqHK
}

!procedure Dna($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Dna', $name, $tech, $desc)
!endprocedure
