' definition of the Item fontawesome-6/Solid/DollarSign

sprite $DollarSignXs [6x10/16z] BSf50G0n0C2m7iEW_jMEymvmqMm2DgHCSxhJF2fTbWT-iLc_0W

sprite $DollarSignSm [7x12/16z] BOo50S0m409futhxJnj_5q1Irp5sIG3wAN-gwhmFPhV__BPvydiKg61bsFMfJ

sprite $DollarSignMd [9x16/16z] LOs50G0X2001Es__QR_pb2xPc7AYsEbKocuwErKCekMXCf5VmmOmzVRWTFtaxWnuyQTZ3UWJxir7tk7kw_lm2W

sprite $DollarSignLg [12x20/16z] RS-50O0m3031nps__xIumzMzOJ4K71BzwMVXRDtMkuDKeqopPYXXC3Z4hP-hARl1MP-ngbmrh98wri4Xtl-mOj4gdRE-Nohmm2BhjSj-OmaM4m

!procedure DollarSign($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DollarSign', $name, $tech, $desc)
!endprocedure
