' definition of the Item fontawesome-6/Solid/DropletSlash

sprite $DropletSlashXs [12x10/16z] FSV50S0m0810wbxsdpQUyE9cSZyb9z2ZuK6bzka0otY40RqPZzB_HpaRSc04

sprite $DropletSlashSm [15x12/16z] JOs50O0m4CI2Ezb_MgIUwjjTJs0buHPkIooe9JuDbFxH08KGNZb8SOmEtTdLBeIxUDFb4571ktNkkOrnzbry0G

sprite $DropletSlashMd [20x16/16z] {
NSzLeWGn449HshtF_bVxD5CZzoif0_ejZJiFLktDLSM1_n9p2lei82bE1v_56RJj0Y35NiMjQYGdK6D89gZQOMLCeAyimywHt6ek19BDNV7jwMwwz7Grw88f
OQnujD_b6m
}

sprite $DropletSlashLg [25x20/16z] {
RSy5ZaGX403H-gvGzp_j6caaEo-6jCulX7pGl3fH95rfdhWUgdHslO59rKnF1OkBtgkt5Wmk6mQBXfNHvvGym_CfHKyunfJOxO7vtySJTrMT-WzAyMlys9HK
rbvL6brGVG7D4BB2djHocGZgEIsg2vnw4WmlC6iQTj4qH-rl
}

!procedure DropletSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/DropletSlash', $name, $tech, $desc)
!endprocedure
