' definition of the Item fontawesome-6/Solid/EllipsisVertical

sprite $EllipsisVerticalXs [2x10/16z] Os1WuEVb1v7y_0mi35n0aWy

sprite $EllipsisVerticalSm [3x12/16z] Om02VaO-Vdu6VXumcvSVoEPZ1Z9P-FcvWMn61W

sprite $EllipsisVerticalMd [4x16/16z] Om03HWOMVdvkFdv-VWP-VYQ841DOZ1yYnW8HWwb3Y04

sprite $EllipsisVerticalLg [5x20/16z] HKc30S1044ljPlzj_ymGFIJn2joVm6EsHveNfsGxjPq5Pc3FTdqNh9Bfyza5DXoCUW

!procedure EllipsisVertical($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/EllipsisVertical', $name, $tech, $desc)
!endprocedure
