' definition of the Item fontawesome-6/Solid/FaceFrown

sprite $FaceFrownXs [10x10/16z] JSQ50O105CFGu4xsdnOvVrzQWCsPdy6MYqwORSekdOrP1LGqnsO4JAcy

sprite $FaceFrownSm [12x12/16z] LOm30G01303VHl-qCs_cmDp_CIY_8gbJql_b_20xoMuUKY1h7FP2GhT5dhp_da-_WNWvuou2

sprite $FaceFrownMd [16x16/16z] PO_J0K0n34NlGutiFstjde-OA317va77KKLKbmQ-kXDRYoSFQ8Tb0NH1hlYiYmjJ5_slhFwJ1OEqFsfhsLgFAO8J_JbJ5VQ3E19sTu5d-IO2

sprite $FaceFrownLg [20x20/16z] {
TSq55iCm30DGjGsJxd_RFJiQRxyD6o1rSIIyY9HvGFYYml5DqzMRg5fl5FQcWEOylDGnQQh2cyy7pThXmUPnBlupAAqEIgAxO3eTr6DQF-_4gGEDrjFRXyBD
8m1KleDfV7N2nVSeKRsvWsu
}

!procedure FaceFrown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceFrown', $name, $tech, $desc)
!endprocedure
