' definition of the Item fontawesome-6/Solid/FaceLaugh

sprite $FaceLaughXs [10x10/16z] JSR70S0W3CNGdzwZ_QUbwCG3sqfpiQT3bw7DqWM1xMQm4nq4BCXbkZQwf08

sprite $FaceLaughSm [12x12/16z] LOm30G01303VHl-qCs_cmDp_CIY_8gbJql_bVB1uaqraozyvQAp8Riq_ItTv-coljIZ-qaK

sprite $FaceLaughMd [16x16/16z] PSk54SGm34JHLTZu-w_sG9uToZEAbCv12zbWkPN0faFhRhOGm5w1utzn0aY-oFRfwwr12mC2Bja40GutcBh-LufL6kH8D5YZ7RlSc7Bi2m

sprite $FaceLaughLg [20x20/16z] {
XT054WCn30D07uVr_zzs5987k-rnOh8fDfJNd0TJFMo24_LAabx9erYobXLG1WMRdse_Nw3ebZ-MG0t_A7YEmdSlepaVdtjiOTEpY8NRJZkOt0-8AqPOeugr
AS5NUguTej01NHsBVW
}

!procedure FaceLaugh($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceLaugh', $name, $tech, $desc)
!endprocedure
