' definition of the Item fontawesome-6/Solid/FaceSadCry

sprite $FaceSadCryXs [10x10/16z] HS650G81000XxFRsdrQ_7-3H5JHvqEAYrQCZyMrtgUjNIbqlKXvTkoQShnN-

sprite $FaceSadCrySm [12x12/16z] LSP50G0n00InBNF7lzfZp2lQDR9Ed3w5JncVqnYA3XNnay5IHU-W_L9yRZIs9sdxflUfZJdkfHK

sprite $FaceSadCryMd [16x16/16z] NOu50WGW20JNRlV_lptYUimn01ZbS0MyE7IQAzzSrm_R7ty8u2z51f3UipnFa_4oBGQHVvQCkBcZBMHm1-2ENx-eJm_cMhrjjXrN25kTwgB6qo4y

sprite $FaceSadCryLg [20x20/16z] {
RSw50O0W00NHRzEt_xG6OP_zL40rcmYpRatKOjU8M_PBuBu4qpNMbSGdaysFdYDhKhu0VHas7PS3qs69r4ESOGxybxrV85X0-N7ADkV1cgdQT5bK_5YlhbYu
J9BDbbUIJKSk6nJhbHilypeRo4NbDW
}

!procedure FaceSadCry($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaceSadCry', $name, $tech, $desc)
!endprocedure
