' definition of the Item fontawesome-6/Solid/Fan

sprite $FanXs [10x10/16z] Om01FWOeuEU7CH0iC42m-3d1V0Y19ecf6ym

sprite $FanSm [12x12/16z] Om03FWOOuEJdXxFv4Mmk89k3XmFCvk6704OWcuMVdm_CuGIJ34WaL3SZN3MOnuXiAXeRH08

sprite $FanMd [16x16/16z] LOw50GCn200Xxkm_RVk6NVGY07mSi12HrUCToVkuFSxLFb_4TBvdIfqr9g83_E9T0ZklagAh8zmauo-80AOaVdICDtyDc_KF

sprite $FanLg [20x20/16z] {
ROy54WGn20I9U_h_hpr9BUjTDZWZYfjMhbWWo1K0-qnX7fCW5-hA-TfRDfhh7FGjrpWnPP4vapkZbGfu6PeiAaGEgMBa5HhhydM__ZWveU-bIqunnaX-zVVC
zMTgdOfo1OOU-08
}

!procedure Fan($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Fan', $name, $tech, $desc)
!endprocedure
