' definition of the Item fontawesome-6/Solid/FaucetDrip

sprite $FaucetDripXs [10x10/16z] NSh50O100C2muaxtdnRdBEzmcNdve63_75yx1fK_BbiB2gNA4m

sprite $FaucetDripSm [12x12/16z] HSh50O0m0C30u4xsdnRglVSHlHJwUYlHjOyCoqqXZRe3l5OtskrsvS6jDED8CzFv_

sprite $FaucetDripMd [16x16/16z] LSx50SGm44DHcL5M_zNkXfDvndyRd1PUB9v2RFFCePl3mS6yEmfVNPeP9v9BEyu2G4Q1hBHamNkVjVFXw9sdnZKPlhntC9hD8Dj3-0C

sprite $FaucetDripLg [20x20/16z] ZT2r0KD10CDG-SB_GFjF6sP-bLkBisdYNaf03wDmvfrmChHDgyNKL7w8ycoboy9Lahb7wt0q-MW0lYZu2b-r-EfwHSTbS3BhVGwmyUNWfSsJyChrNp6AiWC

!procedure FaucetDrip($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FaucetDrip', $name, $tech, $desc)
!endprocedure
