' definition of the Item fontawesome-6/Solid/Ferry

sprite $FerryXs [11x10/16z] NSR50O1G500WxFRjFwsTdnCmHfGWBl2A2m98Uy5m3LbUqIfryLW1

sprite $FerrySm [13x12/16z] PSV50O100C2muaxtdnQNa_p2ILsur3uupG-0wJK0VW2vTNa-GEk3areDEW1OWJECiXhO0G

sprite $FerryMd [17x16/16z] RSw50GD020F0l3lPVzisrENU5U0wh_0mpUZC8iJuLE7Y4oIjD-ylNFODFDJlZVn_uz2Uc1IKRo2RJm5EqrX9BaYS204p8m3hdjSvLA-fEYFLoIGl

sprite $FerryLg [22x20/16z] {
dO-50SGW40HFSDl-kttitJC9DYn6cuA1eIkYwh5GLThWdctZdMJwGCptwAjjqRPjzShLtkrto5gzKYxsdZIjldvnVY4x3HqhSzPlnqmIBP4X2g4tq_L44PRK
SuxPpNZ4AteaXjMJkNtL2fm
}

!procedure Ferry($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Ferry', $name, $tech, $desc)
!endprocedure
