' definition of the Item fontawesome-6/Solid/FileAudio

sprite $FileAudioXs [7x10/16z] O-3dvsTZOE03KVn03eY203OO0oR5pG1MnmEaU462t411ReWy

sprite $FileAudioSm [9x12/16z] ROR50O004CE2UxF_jDZnf1fsDGFlctt20gU2fctzrI5HOK8AjWFLTafQI-Zefmi

sprite $FileAudioMd [12x16/16z] PSR50KCX00Mmzzs0x3zjtPjJCeDkIXxLbINXSSl7BUw6hkzx3-N2lpPx6CWCxKZq0dqIgLrvNIheexIugrgAbuRmSWO

sprite $FileAudioLg [15x20/16z] ZSa53iH0581GQYELp_rlktM9xeiIQCCT0wlM4tC6uaaB-CgrtxdsaqsxyfOs_YSttbeLF3M4arGth6B6ldbIviBdTes7bZ22oLDHQNofdQl93yAN-WC

!procedure FileAudio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileAudio', $name, $tech, $desc)
!endprocedure
