' definition of the Item fontawesome-6/Solid/FileVideo

sprite $FileVideoXs [7x10/16z] O-3dvsTZOE03KVn03eY203OW0meOm1BS30ni350A9iyDKG

sprite $FileVideoSm [9x12/16z] RSQr0S0m4C10XJdQVrhZbxxgUDL_WzUQzy0UZvvfdXsOeOTY9p979cl2RiW

sprite $FileVideoMd [12x16/16z] TSor0G0n581Gufw__xJdBbIl0Yzpoi7CnJM0x9PmiOJDHccjPQjEoMyTK9irKwrJ3-kNpUmkflskkNW4

sprite $FileVideoLg [15x20/16z] bSV50G0X00Emuaxtt_RSbVm2MJc2GKzoXkpwrgtq07UbFxJ_LY5xNDa16rdqmbgCI8Lz9HfAByScsokyauv5tIzq

!procedure FileVideo($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileVideo', $name, $tech, $desc)
!endprocedure
