' definition of the Item fontawesome-6/Solid/FileArrowDown

sprite $FileArrowDownXs [7x10/16z] FOM50G0X08JkqvRzfxNr0WJyKkv23CtyFoTV1j2NDInsmbG5

sprite $FileArrowDownSm [9x12/16z] JOY50O103CI2Ezb_MkIzFUTKxudWtkU2CRZ4qFMzxOqviAU1dJW0fcHpSmul

sprite $FileArrowDownMd [12x16/16z] POp50GKX44E3E-c_sY-xEEyq4uFb7s60Tb9a1x3VTCjDrsubf9Hiv1yyIPXtd7VztQLjm46XFGA08_lZERYdiTnV

sprite $FileArrowDownLg [15x20/16z] ZSc54OL05CNGVCNVxRzRrXU7Z9u9RrE87wwtKeoDerMg1ItelAHpvUljKkdlqs6jBMNmbE3OqoR-24rAVHTAVzIYpdJKi2QsL3S3

!procedure FileArrowDown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FileArrowDown', $name, $tech, $desc)
!endprocedure
