' definition of the Item fontawesome-6/Solid/FilePrescription

sprite $FilePrescriptionXs [7x10/16z] 7Sc30SG050FG76gy_QSjyX46OtA-94gKHreGAKL9Fh1_OjEv0G

sprite $FilePrescriptionSm [9x12/16z] HKg30G0n44ljPlzf7yNv8dIICs1zpfx03PWsCDPIom1kWqbSPHmb0M77WFrZxv6Hfru

sprite $FilePrescriptionMd [12x16/16z] JOkr0GGn0CDqOVR-qpw6L1a9-l9uc59FYw2b5I-jEBLzZ36Qj0-IelT54u2mz93ZollEGPsf1JXD2eobgUkzuD9l

sprite $FilePrescriptionLg [15x20/16z] PSo50O0m00F1nptPVrky-kZLQEKd1gvQVx5FW28zWnDUJdaviccl71hlNBLorGSkT5tB5YcRAP8hHJPmVVLJ1wXd_qwM3KoE0Nkg7HJORtPtVQzF6agrd

!procedure FilePrescription($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/FilePrescription', $name, $tech, $desc)
!endprocedure
