' definition of the Item fontawesome-6/Solid/Filter

sprite $FilterXs [10x10/16z] Ou03BduOO42mc64C1gWW4mEKoGVH1PB3pMBWvW8I

sprite $FilterSm [12x12/16z] TSY54O100C2mu0xxJuixVCzoTIiPhegRzTVcO0kxWHlb5mcvkLbKmWG

sprite $FilterMd [16x16/16z] bSur0e0m00J1mHt-_rhSaYxRpLKdRfh_zVCI9dOTak773EQN3V1m91Wy5I6PTkO9BYDpVn6t0G

sprite $FilterLg [20x20/16z] fSsr0O0040F0mntsdnPtgRZo9V4cZEw2idkgNsQUer9u7xM8RZEJuZ8ApCwZqAhTHxdTaNy8dYEolV8G_9XvcsbUPggkz6q

!procedure Filter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Filter', $name, $tech, $desc)
!endprocedure
