' definition of the Item fontawesome-6/Solid/G

sprite $GXs [8x10/16z] FOU50S0W0CCoz-N_Qt6ebu551HuNBa4ApjRUyAkhzL9wbrbtor4X0W

sprite $GSm [10x12/16z] JSg30S0030J0fFRjFssjy1N_Qd02J2m7E6Xne2Sqd2WpBtE1zd65-WIBc4uuAYDck9r-QVQx0G

sprite $GMd [14x16/16z] PSfL0a9H549HNlVTyv-jSh1TVuJ-zKVREiL2L3xX7Fe9o9BJv4H235nwknXbpHReAr1sPbbt1mAPLPeKZLqTR0drwe7h10ThsAPVDm

sprite $GLg [17x20/16z] {
TP030W0X402ps_d_Qy_676eDzOEnLbz4LkecHWuMhmJawTG2Cfq6P4z4clu2z_nWRt9wEiYUeREGZvHij5rXyqG1TyiH9mdAjMHJ5SmkDz1BjdWKAdl-5X8S
5OMDVApdjeu78m
}

!procedure G($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/G', $name, $tech, $desc)
!endprocedure
