' definition of the Item fontawesome-6/Solid/GaugeSimpleHigh

sprite $GaugeSimpleHighXs [10x10/16z] DOp50S0020DJRrxPVrgSmnK1zI9HmKsaPx88t2JOx0qxiLK_06SGvTERS

sprite $GaugeSimpleHighSm [12x12/16z] HOY75K0X2CJkzwgt_xPAZm9vWV3nXa4ZLKYzo1OkzpDT5mgPUSlQi6O0m7BfbnIZOz98gmC

sprite $GaugeSimpleHighMd [16x16/16z] JOy54W0n20DpLfV_lxQM8NDRnG67h_PymQYTU8fTD1EDGcTohtD1Oa1RzoSPrxxbxkafG3bJ2fReegYwVDHbWpjPpQxkoxaT5lnA1AxVD1C

sprite $GaugeSimpleHighLg [20x20/16z] {
JP255SKm30DLvcZ_QJ-UytHjo6mBZkPxLR0Oda7Wu2XHSfOeMOW5p-WFc87qsDvJTcDn6CAfPSR1aD68qODjtMpb7AFIkaH73p5IDbQGGGer5LvhHZcTZ35I
K6Sduz_e3G
}

!procedure GaugeSimpleHigh($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/GaugeSimpleHigh', $name, $tech, $desc)
!endprocedure
