' definition of the Item fontawesome-6/Solid/GreaterThanEqual

sprite $GreaterThanEqualXs [8x10/16z] Ou01VduO0vd5X11YukVd0xFP69016nJmGm

sprite $GreaterThanEqualSm [10x12/16z] NOk30S1G50DJkxV_jD--PqGLVYKkO4hz35nAVBdVqmU0OhsJTjR8GKP_nW8

sprite $GreaterThanEqualMd [14x16/16z] TSsr0KDH3C10Xyalj_-qdnckKwNOo5NWEUS3yZBr9U4HaoVat0NHkp55mZSwyB_EltVCBd4g5tx5KgpK

sprite $GreaterThanEqualLg [17x20/16z] bSwr0SHG30DG9PzH-qzx38OghpCRNZXCJ392EFZK86I-dB9hyAb2g7pQ4Cx51n7pHK_CynDkTJg-mdNY6xzwrQSxuPgKbNFIo3HWtG4

!procedure GreaterThanEqual($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/GreaterThanEqual', $name, $tech, $desc)
!endprocedure
