' definition of the Item fontawesome-6/Solid/HandScissors

sprite $HandScissorsXs [10x10/16z] RSR50O0m0C30u4xsdnRNjlSwKjI1N8NI4_rcS3DwOzCzux-Hnme

sprite $HandScissorsSm [12x12/16z] Oy05-FdvcS0aFmC39py8C3E0EL0kYCsF03n8RB1-FYGs9nAR0Sg6A-95iHO

sprite $HandScissorsMd [16x16/16z] XSk50O0W443HRzV5_jFQhS0ZhqYIWbKlKW7gimRozGEPRrgORsFM-8LDUSIDFyah9bkzvzznzuhnZJvZ8MK2

sprite $HandScissorsLg [20x20/16z] fSZ50SCm04MnPsR__QSjCpVHKQnXf9aDUzehWDD10-pK7Z1qKYre9xFZTOyZssulrvFhDZthUaOeHxTtykh2YoEzEAEpy7oTgpJsgk5dMm

!procedure HandScissors($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandScissors', $name, $tech, $desc)
!endprocedure
