' definition of the Item fontawesome-6/Solid/HandHoldingHeart

sprite $HandHoldingHeartXs [11x10/16z] VSQr0G0X04MnTox8ttzQN3fIXSHp6Wfbx-n9lwD9Mr21gk--fLSTH

sprite $HandHoldingHeartSm [13x12/16z] XSUr0O000C2muax_lnPtpHP64hOid3obSP2nQ3LdOyal9r1AvI0C0pnfSPD23m

sprite $HandHoldingHeartMd [17x16/16z] bSs35S1G343HLolOVzhQ_lSe3YCHi8ALJvfpmPyBrPH7hEeXJzYHCT_JZ22r38OdMJM-c0WqxZGsPd4SW-z8RvpoW_wtxNDw7G

sprite $HandHoldingHeartLg [22x20/16z] hSsr0SDG54FHQsPh_stZprZcT0-5CxutpBh8hVfS-f1Hj7UxPxSxqsbVqBOVIaDg5hfDXfD_E-MzlkAZn5TSbs_CupZ2hC-jw5W_bpuxQasqNHzOsZ1-

!procedure HandHoldingHeart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandHoldingHeart', $name, $tech, $desc)
!endprocedure
