' definition of the Item fontawesome-6/Solid/HandPeace

sprite $HandPeaceXs [10x10/16z] Om02BWOmu0SYA8iVnc80iPWXB3uW6raSh114GZ4Jb0S441OZb04

sprite $HandPeaceSm [12x12/16z] HSc53S1034DHbodDtt_QOmW-oShbgiKjqUnCYsqQalqgNhAnTuPcsK1-LxMPuDwAFwE55R0awo-yfGW

sprite $HandPeaceMd [16x16/16z] NSk50S0W00F1L76o_xIuVmKEGSrZPDFdECb_CyZJp-QRB3PeLNlUiCM2hjeGCylBLZE7bAd_wdG9Lpt8-wwdNBOYZN7CBVSNYydQlJ02

sprite $HandPeaceLg [20x20/16z] {
PSy55eD040JH6HnMwlwdZVH6-ZqgmJuwyUcwmfholGOd7QMPZZOt1TniXbdcGHis_sq3sGH-ON_R375o3RjAoL9abHwUsmpmtj-dA3GPeqXDi9YrA43Q81fS
jQ_LKZgZIzRmKfPEJUJeqnL6XuwU
}

!procedure HandPeace($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandPeace', $name, $tech, $desc)
!endprocedure
