' definition of the Item fontawesome-6/Solid/HandPeace

sprite $HandPeaceXs [10x10/16z] Om02BWOmu0SYA8iVnc90Ol70s0XnVh1AVXY31Im30K0MZ04

sprite $HandPeaceSm [12x12/16z] HSR50O0m0C30u4xsdnRglTSHlMJkOFbhFuxzsZ_4Uv6SWFSjCAZbYtgk-y0AAAUFtl45KUu0Fm

sprite $HandPeaceMd [16x16/16z] NSk50S0W0CJ0htkp_xIufmA7AFQhzBhlevAzis3qt7dcxom8VhDF7kVVNrFebZRlb-W5LFtZklGoFS6UZz0a_mPh_k5rh_TEwP6lMh6aSDe2

sprite $HandPeaceLg [20x20/16z] {
PS-54S0W44JHY-E__supXmso4U3XKkES3BaE_SD0PsuTesdhNKs0pMuuLnC8cndOJ0UgdQCdKBlozxHBw9SjaFfTWfN939fpj9GfdplAZL7BOaNGyql9amTz
G4WG2ZD5Sln8xNW3cGpZo7ZavWy
}

!procedure HandPeace($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandPeace', $name, $tech, $desc)
!endprocedure
