' definition of the Item fontawesome-6/Solid/HandBackFist

sprite $HandBackFistXs [8x10/16z] Os1Wu6400tv-VYOm3GP02ZyDPK0rCC1e

sprite $HandBackFistSm [10x12/16z] PSR50O1000InnPtflreurxmYQLyK04SQF6aWykZtfYbFAVr-

sprite $HandBackFistMd [14x16/16z] VSt50S1030D1XJdRVxLXEBH-OzIHUfKJOEvSGJaNZe3n62W_WKfSBIoELd1xdbfFykNCNl_d1wLSoTGE

sprite $HandBackFistLg [17x20/16z] dSg53O005CJGmvtkFoskzsFG-4krLfBeMG8asGDIjWBqy8IZpW49WvogCO2Fa3eeGCApKdeze_GM6Oo_O0O

!procedure HandBackFist($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandBackFist', $name, $tech, $desc)
!endprocedure
