' definition of the Item fontawesome-6/Solid/HandsPraying

sprite $HandsPrayingXs [12x10/16z] HOg54O1040E3Ezj_jqp2oxxSHMJGhSA1K851DsN5t-DrS8C3xrFsBVkU_SQk4OstxsEQy04

sprite $HandsPrayingSm [15x12/16z] JOs50S0W3C0wnSd_r-8Mg9iqdDoFB6vkpmwXoI1MJw5cAxDbMDw89gpm0mLdg5kegNoS1b4SU14cyw03CW

sprite $HandsPrayingMd [20x16/16z] bSj50e0W503HiTkv_sdj0bO-yXUN8MSe2DIA4j2SKSFKlDysuUIcKHuwFksNMHbAkYBN-ccJU_ilLwkpudwR0Lvcl8pUMan0RcXYvsbs7tkDwWe

sprite $HandsPrayingLg [25x20/16z] {
dSo5ZGKn40JHMZPN_j4UMikY_mI6cMvsEK2RUDYKJNbGGUlB_m1PDovYt_LMDjW_jbkP6lRRocux6gRzkgyfYwAMys0PbQ0qzVF1eAQj3zm7OxOZs8M1oGEh
hnhu2YY-M7YTR7JPVrbR6BYOileD
}

!procedure HandsPraying($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HandsPraying', $name, $tech, $desc)
!endprocedure
