' definition of the Item fontawesome-6/Solid/HatCowboy

sprite $HatCowboyXs [12x10/16z] Oq03_Fpi_4mmDWXWidd1R4O61cP-Y30_3mEOnGMHv8EeXklWWAf70G

sprite $HatCowboySm [15x12/16z] POk35S100CLIkzb_sXg7F7r2JYkbV7Zo-JgswsthQEi2L7vMQayzVPyH_5a1bjSDt0odQSdP0G

sprite $HatCowboyMd [20x16/16z] bO-50S0W30HnXzz_sYfQxw7nXDmZ_NB5KOUTNfMoZf_Ta9gAeT1qRjIfd2uZ5abpX9OEkq1gPhfU0e2iJYdc376rOo0F4z6m94DJrVnX1W

sprite $HatCowboyLg [25x20/16z] {
dSw5OKKn34DHnNeOkljFstvcFc6qzLQ4DgnR0p1dG3SuMdN5dEXAvIHqYRFyxA3hmiW5xPIyw-yEki4IbqBAe0QCKWfFos8dAMLWEDvkKz96BESCWdjDUdoY
WyQLLIU---RCkRPMbj3F_W4
}

!procedure HatCowboy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HatCowboy', $name, $tech, $desc)
!endprocedure
