' definition of the Item fontawesome-6/Solid/HeadSideCoughSlash

sprite $HeadSideCoughSlashXs [12x10/16z] Os9WuE9dPO00VZ30u73mC_31s22A6Oa39c3AkO0a0nk2myV033M73MW8ifdy

sprite $HeadSideCoughSlashSm [15x12/16z] NOn50eL004BV3rlX_gUrfeSL_GLsBoGuOEtqFwYHFUXN7Jxu5wcN5EsiD_WIVrVx2o9eyV7usO3yQ-4WWo6JoWAOV04

sprite $HeadSideCoughSlashMd [20x16/16z] {
JS_50KCX54JH-t6V_gkD4MIM1vwP31GfSv8qD3CEMkrmigqkwT3kZxCzX6MdqC4zPjRLXUMUi9e2F6YX_viLpxJPrFBeNY_3K2RpdEqCa3KmEgRMm4WFo_RK
N-UwIjUnUWC
}

sprite $HeadSideCoughSlashLg [25x20/16z] {
POzL0aCX40E3Exd_QIlF26t-O5PcRGU0FCY2BPsqWsUcKT8eiKgY4WED4larnw8_aCa8b0U46qoI5V0t6FjyMHGlK2_FvUrsfGoaVV-ydWsm2v2mQdfDJJ1M
Z_27Tu2X_paSXtU7GKmAvbKtZnq2s68yTOoCaYloOR-32k3m7W82LYRV
}

!procedure HeadSideCoughSlash($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HeadSideCoughSlash', $name, $tech, $desc)
!endprocedure
