' definition of the Item fontawesome-6/Solid/HeadSideMask

sprite $HeadSideMaskXs [10x10/16z] JKl50G10249_Lx3_jDTbIm0moZ12C-PnJf-x21Gc8YO9NFGSdvNaRvuhHcy

sprite $HeadSideMaskSm [12x12/16z] DSc50G0X30J1UyNP_gl5Cn3NuE3J4bakQwVHOuhSEQWYS1V33Ia1Oh2gHmkJOvA02XgiTywzrW_g

sprite $HeadSideMaskMd [16x16/16z] JSp50OLG34JH2potwR_QBmbsLj7XxnXIvPBb5cReTcql3PXwWOCaDtS9XZPa3eOMzZKyNrBjzhRhWj-oziqWq-d3i5c_JJcutY9kUkzUVS1rxqtc2m

sprite $HeadSideMaskLg [20x20/16z] {
VOm54iCm40CLDfx-_zlMg68sCMbMXyhYZOmBnCd1WKwYy1-Hp8tlbCn_P7i9Lxqjan7m6J3rSjcis7vcHQvEn4AACtR1ABfnu63m7MY-E4P1Cp74UbeX0eio
jPLfyhqNmvFrkvk01m
}

!procedure HeadSideMask($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HeadSideMask', $name, $tech, $desc)
!endprocedure
