' definition of the Item fontawesome-6/Solid/HeartCirclePlus

sprite $HeartCirclePlusXs [11x10/16z] JOU50O0m0CE2E_d_McHUBosqu_O8Au6ZpYlr3yDIPqPr20TwHGZ6y2JiJlK5

sprite $HeartCirclePlusSm [13x12/16z] LOo50S0W30Ilxf_zjoqEkRZYcRK3tnbpYoYwL5I4hCDJaqJ9asEBOGbsrWhJkxznTqt5iwM2gQ_5wieFVW

sprite $HeartCirclePlusMd [17x16/16z] ZOp50O1G3CM2I-NjFotk9_ArgV23r0B5UXk0dlXN2E8jgcU1GL_JtzM5UVMOGHv3cgDvaDAM0-qcraghjnAwGvG5PGZMcarONvasGVrksSnGQAFZebhZdXa

sprite $HeartCirclePlusLg [22x20/16z] {
bO_L0OH030K7rht_QWz8SBvkO2t--8yqLYQWhsT16KgqSgYVDjv8w0SFvMjjtz3UHt-LxMpCuCQ5nQr1PGBkNQvszaglwoxTpMKs4gfAEStaXvLPhTiIzjE8
TIrR2w4qjUeay_oieEQ2zAmoscLc6Ziy4Vq15W
}

!procedure HeartCirclePlus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HeartCirclePlus', $name, $tech, $desc)
!endprocedure
