' definition of the Item fontawesome-6/Solid/HillRockslide

sprite $HillRockslideXs [11x10/16z] Oq01_0nC_An0ceyVnE57a9nWMI20AOImeGgWAc40meIBCoFO

sprite $HillRockslideSm [13x12/16z] NOo50O0m30GVTsx_QN4QgUPLQMshQjPxQb3J2BZ1-qq5K09un8Ss2hYd5YXeCB1BsrBGzZPOx0G

sprite $HillRockslideMd [17x16/16z] RSu50e0m241HiFlV_xJgkdjl0T8hyoQYpvC0J6UncuFR8qzOMBb10t2PXQf4uBJB3DZjgm11E39Woezj6VxzH5uqGPADmdpgjTJm0G

sprite $HillRockslideLg [22x20/16z] {
VSq5WeD000J1mTVx_w-zI_295Twiw8TXlGs3nKgIUc3IBaSfC4ayQTEWwCagGDRJ2Cn7lNACKVTAaiEpL-AsT_MwZGQls_xJ92MOk0GzHN3JnyhyiJ9Accaz
RjAguOQr3k2qIfYwndy
}

!procedure HillRockslide($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HillRockslide', $name, $tech, $desc)
!endprocedure
