' definition of the Item fontawesome-6/Solid/Hippo

sprite $HippoXs [12x10/16z] Oy00tBnWYfKV2ZZu6Q0iTY3cuySF61WO4MmW098id0myO3OtcEG4am

sprite $HippoSm [15x12/16z] Oy0E-64CJduWO0PYNh0m2c22i_ZuIG0WSn0Q83PXS7cWD9XYvcC6qxnyO0e

sprite $HippoMd [20x16/16z] hSZ50SGm4CLGcTc__sgNCNJACuuuP0S_NEi5kahtF2KzZVlLySrGjOBMKzD9h36co-eNG1Mh1lSsds7-DWl6G5-qkoQnxme

sprite $HippoLg [25x20/16z] jSw30GKm34NHMxjl_sc_RPwQ2I-nZjiapXIj3STchEmuNHWqoU1r6xf0qKRK7LD_CyfAawwIJQn4YPi7E7VdOEKqvNbv03QNPE7wOEFye5qS19vP0W

!procedure Hippo($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Hippo', $name, $tech, $desc)
!endprocedure
