' definition of the Item fontawesome-6/Solid/HorseHead

sprite $HorseHeadXs [12x10/16z] Oy00_Fpy40OZFmZ0c70EX05bGm4Nc0tbGiGPOIP1nJZWwhb1B

sprite $HorseHeadSm [15x12/16z] ROjL0a0X0C9UfxhxdzPkvG_Obcbs81SO6gYwFR2w9aBTuar9h6dQuhlSNhb3zLg2YpTK0m

sprite $HorseHeadMd [20x16/16z] VSk54S0m34DHkyn__sdBLIc9ZkntagKpmXiwu6qJUxe7eLH_qdhK3pIVsgHYoIk-MG-GoVhDXdrH26Mu-N5DXsaqdJKPnVgulGrJgfyj

sprite $HorseHeadLg [25x20/16z] {
ZP150iKW4CMGEioy-v_sA-vPjGakrhY0fxO7ld1X5U67AJp3Gvb7Ygoz8tWAYgK1e9sN2D3tmB0k69IuW8eZ2MphAUvYdG0bxl8gxkV-VhjOR4vAYES_-qUn
zdKs7iHqNp0Br0nl
}

!procedure HorseHead($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HorseHead', $name, $tech, $desc)
!endprocedure
