' definition of the Item fontawesome-6/Solid/HouseUser

sprite $HouseUserXs [11x10/16z] Om01LWOOuEBdPuQm-4607ShY0s9UY1Y4v8Cm4II4nG0c6A1CDY00CH4A

sprite $HouseUserSm [13x12/16z] LOg50O1030E3Ezb_MkJhzz96q5WH7EHW-ysFHNOAX-tjlsGVj7fJaZnqX_mmqV_YKc5KyG8

sprite $HouseUserMd [17x16/16z] NSm53WDH409Gzhjp_zDMg96-s039u6qcm96iC8SFtNUPdcLPlZ8VzZS3K7FUcLhaK2vWVwP3Km4L9uQW7-bTG7x5-2-un8eF5P46k0C

sprite $HouseUserLg [22x20/16z] {
PP053WL124DXtORU_xHVbgGTUV67OsGD6za1U2yl_9bR-I1PQmcoImR4qMP6jaPvdQjZKAz8gWHGefdAGLCzrOuJoJKN9CV2CX5gvdm6hHxGMhwpiSUMX6p7
QFM84orkzWK
}

!procedure HouseUser($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/HouseUser', $name, $tech, $desc)
!endprocedure
