' definition of the Item fontawesome-6/Solid/K

sprite $KXs [6x10/16z] 7Og53G1020DVYJQt_xH8qTfoINsWBtDX8J3pdR5xvsuY9by

sprite $KSm [7x12/16z] HKe30W0W45js-_zhCuuJThaoBybznwl4U9cJHuejBvOmw8yCAQ-d28DHgGC

sprite $KMd [9x16/16z] FSY73O1030H1apFRVxVy_acSqyZrvygveLy8Nl9nYnrAp6t4q5hq1DlDBYvNfYO8waKRU8FTatm

sprite $KLg [12x20/16z] DSq53iH00CF0t9Nv_x-jAoiMJM4tCHkAt_zwBlb_24VMu8VBO3b4mp4Qpj4NzhpTzR5nL7iO-vcP4xlr_LNdvY_jNtLM1faq1ziB

!procedure K($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/K', $name, $tech, $desc)
!endprocedure
