' definition of the Item fontawesome-6/Solid/Magnet

sprite $MagnetXs [8x10/16z] Ou02Ndv-8CaF112QZOqDIBEnyQE9iq1f8888Ci7a6C0K

sprite $MagnetSm [10x12/16z] POW54i003C8eSyt_VxlEBHLowAA1DOALrIgmhHNxxdvMGmDzsbgG6lDg8pk5DB5IQwMRrrm

sprite $MagnetMd [14x16/16z] TSk54S0W40J0UyPm-k-M6rmt0LwnYz6Z2j4dafAKSCiKeH16dchFCBhslfdbCILBXDuqDIlgaeMa2O2QIH5BR73A

sprite $MagnetLg [17x20/16z] bSk50GCn4CH0FREt_suJXHd6UCIJfccgct-zPO-Z8H97qyj4BOug_xquQlm_ZVoNcFslNWqeQYDKHKHR1LsqikHE1RarmrscW4fE9axgQE6b7G

!procedure Magnet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Magnet', $name, $tech, $desc)
!endprocedure
