' definition of the Item fontawesome-6/Solid/MoneyCheckDollar

sprite $MoneyCheckDollarXs [11x10/16z] Oy0AkFYH0IkSnS3B3vO7CbaO4A8Cl31HVfXEPeHs97C1

sprite $MoneyCheckDollarSm [13x12/16z] Oy0D-5417nARcu4HmM40IZ4nWW185R8-1Yu6VeHP3Bpys0032WSP

sprite $MoneyCheckDollarMd [17x16/16z] XSl50SCm5C1GjM7K_jCQJ-5d_CItVZtuzTxOFTgOZtL0gLPrBVTUcVMm7sVyj_wghOp0vhOM5lW6FU9J1

sprite $MoneyCheckDollarLg [22x20/16z] fS_50GGn30D0XJdglzg3PSPvcettAjTyvAxABJ1SoVZvDPGE6m8icSI0VmeoSKqt-RM8o1WwgPlxKyQvWdz50fvhYBn2xJnRLXBk-08

!procedure MoneyCheckDollar($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MoneyCheckDollar', $name, $tech, $desc)
!endprocedure
