' definition of the Item fontawesome-6/Solid/MoneyBill

sprite $MoneyBillXs [11x10/16z] Oy0AkFWHW8y1Y84q0vW7bEI0Ie0KGfdC30oy4BLGANvcX058vW8

sprite $MoneyBillSm [13x12/16z] Oy0D-5404vJc0Z60SZnW1L15oChve1nq6H35o0PbSCCKSuEv2EN8

sprite $MoneyBillMd [17x16/16z] XSsr0GH140Cm7_Eg_sgV6PKDEl_rwvEgzwQfNQtrZ0HRrK96R5Xo0CLPZbftENbjJCxQQmVBBSNcbh8khifIn8lyjGS

sprite $MoneyBillLg [22x20/16z] fSy30aKX50JGoMxslzgFP_DaT_5UuPgFt25bvSXBzMygmAPjZvLkABi1qFIYv00DpvcA5cVovYpH49nJYv0gmhzn0FA_8p3zRoTsmvGuKL8c5RV0b9M4Exu

!procedure MoneyBill($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MoneyBill', $name, $tech, $desc)
!endprocedure
