' definition of the Item fontawesome-6/Solid/MoneyBillWave

sprite $MoneyBillWaveXs [11x10/16z] NOo50O10482mM_QVrlQBwwHaCmNTR_DdWJ-jOF5b1rtYNgNsoGzN7au

sprite $MoneyBillWaveSm [13x12/16z] ROo50OGm5CLUtPlzfpt58TzLJmoWEMgPV9cT0rfDR4XonqAi6Ab2MogROImFLiOIgv4fCdqaBRm1

sprite $MoneyBillWaveMd [17x16/16z] VOw30K0n34IlLh3_jDz6NnaVEhZA57R3isuqlK2swXta-SByDM7noEoWnGkZ5oechexqTF3JCVV8-nI_U1PXT1bxWUZurQgwXpF-604

sprite $MoneyBillWaveLg [22x20/16z] {
ZO-50S0m20JleQxxJrjtpKLn80IPkquQhzk5YY8poPAo_II6zau3ozDCxveacxK-FWRSafV0FQDDskgY5N1F4KtQvjuGQAvmAZShwwNVS-LKjWzp8qcQgoe_
_0jdGf3CcihvfGS
}

!procedure MoneyBillWave($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MoneyBillWave', $name, $tech, $desc)
!endprocedure
