' definition of the Item fontawesome-6/Solid/MosquitoNet

sprite $MosquitoNetXs [12x10/16z] HOo50O10482mM_QVLh-VwmHsw0mWXMdkkJuZaTC274R6GtXp_X8z-u8EE0pzllyT3Fm

sprite $MosquitoNetSm [15x12/16z] DSxL0SK02CNGFAa3sN_QEkSJlG05CDDM0A45CDB-M_WJsb-3H_eg2nOlwVQHO0grPitmWgwOWaXnIGOsBvsgkssqB0y

sprite $MosquitoNetMd [20x16/16z] {
PSg50GCn30J1DQDy_LSRpkCOXBnLZk4hw1F4aM3G-hqNBpq_vReuqSjavuijlQsPFMywy6Mw1aqVPl9o1IOLVPGgYQorz3fEBw78b0gAGTu2SIt7mkH03Z4T
7u86Gr-yEV7ntUDZy55bfjVXIFwpzmG
}

sprite $MosquitoNetLg [25x20/16z] {
NS-55GCX403HmSxPwR_RFEB7nvs58UsyR8KxF-syS7LeiCaa2nriJ8w0WACpkUIoqsNM3JMOvUgmvCJNxcndy2wn9zR__KitYea3BWXygwjwa0xBQccMzmas
G-NqW_SlpTrWeqaM1BROW5U0i9ZAoBnLuKZyN_KoJWt_Lmr5tbPJDMKJBv-s-y6aIHBa0G
}

!procedure MosquitoNet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/MosquitoNet', $name, $tech, $desc)
!endprocedure
