' definition of the Item fontawesome-6/Solid/N

sprite $NXs [7x10/16z] 7SM50G0n349HJkhozv-sGW8yoJV6NU0r7TCQHc14DGBp4UD1SmC

sprite $NSm [9x12/16z] DSQ50O004CF0u4xsdnRjMtlKJFwjRWNxO3T00pH0WyRj1vC1kypykW4

sprite $NMd [12x16/16z] JSQ50S0m449Hwjw__xJLX5DuohE7u0Z2canlJz1KjnFORzg2qnPijg2tMpYhDO6j3KwQtpfHcXi

sprite $NLg [15x20/16z] LS-t0O0030D1aJEt_xQKs5_fIYMzgUnnVFW9xavNfxdJK1XKZYZCobEOcxCm3qjXC1GE67zcH66spjoTULYTzMzw7m

!procedure N($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/N', $name, $tech, $desc)
!endprocedure
