' definition of the Item fontawesome-6/Solid/PaintRoller

sprite $PaintRollerXs [10x10/16z] O-3Z1m4-1Y030ZWO-A60YvyPocBWPu0240kc5iA50ZOW7mSB

sprite $PaintRollerSm [12x12/16z] O-3XXm061X0Jpk57i7cGsFnm2IuW6m8O6Havm6oe71-43IPXmaIp0G

sprite $PaintRollerMd [16x16/16z] fSsr5S003CJGSvYr_xHXkESswdubDRnfpmYxyQ9CdkTavDPkpxoSyPYxwk945tkw2nXbJK3yyCWxtW

sprite $PaintRollerLg [20x20/16z] jSv55WGX30HG8C6bxd_QcNQfnxR_Cbh63To6MJcycSMWMbfg8CMMIGqL95j0-CTICzeVccmr5Xwr_0vEESq9Q7aZPsLw6GlbPulyRSsz_lu1

!procedure PaintRoller($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PaintRoller', $name, $tech, $desc)
!endprocedure
