' definition of the Item fontawesome-6/Solid/Peace

sprite $PeaceXs [10x10/16z] HSQ50S800CJ0mvtiFotK-nfuT0Krwa4HNOJGOwEYddHDesJVH-GUBetY3m

sprite $PeaceSm [12x12/16z] HSY50S8034JHZpjl_scXtkIyyLxkpMU-ENRGcQ8nbqzgpa-lBOTTxmgKF3c8ZtXtKDoAvq4VtweFZEiV

sprite $PeaceMd [16x16/16z] {
JSo55OD054N1XplJVxSvdurTTDRoD5sEBfykhQKH9-lDLLIVMvUEinPVQKxeGhuUcPm_XyluvmjzaWNDXoavLSEpp1tLmHuQQgA7EpDdoWdQcUFZdJdvd7PJ
h3ggk_vV
}

sprite $PeaceLg [20x20/16z] {
NP05jeKm4CM2Kyt-L_lrdcU1McQgX3Bj9oySXh4GVA4yrDpHGb5hL05CxG57yX-De9Euj3UwlRcXHNbpcyvFjwWQfJMkwoDe1rOz5IuDS2jwDtNLadOm4jUI
_9L5xMJV9NiMbRZR7AEgOzDMLDV7apxWmPrd_a_w1W
}

!procedure Peace($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Peace', $name, $tech, $desc)
!endprocedure
