' definition of the Item fontawesome-6/Solid/PeopleRoof

sprite $PeopleRoofXs [12x10/16z] DSc50OC040J1YIji_zNYl9m2etF6wWbkXGEktFdMSu1EUBh67twfT45LZngfsgkNgflXKiq

sprite $PeopleRoofSm [15x12/16z] HS65SS00002XZtlOVzjU7VgsZ_qReLzeG9zUXgg9gusnSbK7xNtozkckdifTozedWkZJa1ThVOA9e7ngMnTOSx2_9KOV

sprite $PeopleRoofMd [20x16/16z] {
NKy50WGW2BDR-Fzl3xPhkgVXHL72FwdH_gbSgopJzguCouRvOpwZKhwsnEA8GzVJZ7hoLBn1a0dVLB-E_g8wt26CXxp1zob3eXsMj0On92BkhCC1jUuDn8EH
RChfP7ytn_o6PqY_0IeCUr1_-XIn6iEZ3m
}

sprite $PeopleRoofLg [25x20/16z] {
ROy50iGW30GNT_B_tzvjGxtJ0d71XP7mHP4_3a-YB0okE9ewl3udGa0IfGQbKmbOP6eHGAEWutYjFsdnGqGA24FKO-YACd6MjESmk50p7eossMK6lZDUTdPh
vhwz83gyuIp4OrpgMmih2y0QA6R5ykfIUL_jtV66AeCEKJg5kMiUy6Tn7NdNH085jwSNQbKoPWD537K4hnNp3m
}

!procedure PeopleRoof($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PeopleRoof', $name, $tech, $desc)
!endprocedure
