' definition of the Item fontawesome-6/Solid/Percent

sprite $PercentXs [7x10/16z] Oq01NFpyG9AVcPyNI78mWDWyO98FJFB3I7uWW30X

sprite $PercentSm [9x12/16z] Oy04_FmWaf6VZv-V4KJp0qKWD1YWqOm86g6OWPkVdvqVfWm6

sprite $PercentMd [12x16/16z] TSsr0S0m0CJ0_p1h_sd3R5lLTLAgSl01zoLm4ARLFjXfzS5MPz15EPpoXzt-kLa1EgX-zNXGNgr42m

sprite $PercentLg [15x20/16z] bSn50a8n34NHVBUsP_-hnGaZx4uYJ-8lAijZxTZXSQ91zz2CGweO8iPwf1P9NhzeqpUjCR-q5I9p1-GL8tGrEwTwn6VE

!procedure Percent($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Percent', $name, $tech, $desc)
!endprocedure
