' definition of the Item fontawesome-6/Solid/PersonBiking

sprite $PersonBikingXs [12x10/16z] JKo30G1047eR-s_xE1kL0IlMiEtDuzBNdGADoG9eflY6rkwnt-dwMdlakpw_hGwURxa6Kli

sprite $PersonBikingSm [15x12/16z] JOc50G0n2CJoxcJ_QTyhQO4J4aT3HQFKR2q5NOlfV2dTGHF1mnZDe8-m0Gt5_HKn2Zps4yQp6_V3Jq0hJgtGIQWZDpxY0W

sprite $PersonBikingMd [20x16/16z] {
POm75e0W34FP6tB_szh6hL7WlzzX7fd5VDE1doj_5wpzAW3jRHmqQ_Ht5tZPfvklkROIMyX8SYTeTA4zsUW9SWrOSWGQHpfT9LUsQgCLDmzEYF8kIAlTMIeo
7XQMTXmy5N0eigWD
}

sprite $PersonBikingLg [25x20/16z] {
ROu7aWKX20MPP9X5-_wttIByR5Uo1Luz-MIeB07M4u3beC0clrHEMJ60MtxOS6Ofds4xXc9yJ8X2zq-lkIYww-nnKaBfkMjKwS1Jcp-q0PTSDY2rx56YWWyE
lx9hHSN8WVAN2YrVcmq6DRN3-qLxgisyon3HPZyrjH58K5zQ0DjFhjH_
}

!procedure PersonBiking($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PersonBiking', $name, $tech, $desc)
!endprocedure
