' definition of the Item fontawesome-6/Solid/PersonWalkingArrowLoopLeft

sprite $PersonWalkingArrowLoopLeftXs [12x10/16z] JS750OG0402ndEio_NVB2qbWxFuv-rOzN2iWtUe9ylwaY-yYBk6TOdvHnIGqVA81LW

sprite $PersonWalkingArrowLoopLeftSm [15x12/16z] JOg54GGn3CHqZ8dwx_Pd_NGAs0k4nXCTddAum7157Vc7SHnFEuV-ohDuHaCX5qhqQIIrZvoUjMtr3mR06sVGbK_L_bde3hLzU04

sprite $PersonWalkingArrowLoopLeftMd [20x16/16z] {
NSu5ZaGn081GvhkM-zzsGsJjrOaLyXxyzoZ_7RNFavta0znggdpEkvCfbwxm6f996Pg7P8XYI1uvFcW-W0EKRfwSmaSlBltvSibNxJuOThdDACq-w0Ae7_BH
YSMtkmwYLxl4itrOgltu0W
}

sprite $PersonWalkingArrowLoopLeftLg [25x20/16z] {
RSy5Oi0W40NHYJjp_zDMs5_lYmVMAAiJ_nbK_ZEh0_zvl03ZuXSrHjwDntNchJkJ-9zmlHcCbI-xykZIVFUpVNJ1Ri_FBCm7axgg3u2Ui5NygZBKA4qto2PK
YdgofrsOpDlpeyLDfiGOTCsRLUUit0FbrgLcpSf2Tse3ddvFk-yEwy-Yb2a1NplvuHK
}

!procedure PersonWalkingArrowLoopLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PersonWalkingArrowLoopLeft', $name, $tech, $desc)
!endprocedure
