' definition of the Item fontawesome-6/Solid/PersonRunning

sprite $PersonRunningXs [8x10/16z] Om01VY16qFpi89AHdviVmcVcXp209121Q4OmoSu8ud5oekW7

sprite $PersonRunningSm [10x12/16z] BSZ50O1G0CFGu4xsdnQ-z5qgDDT0A76D09lcyXnCHNL88s-UONZH1_h_IdWG0Zy

sprite $PersonRunningMd [14x16/16z] POw50O0m40C3TRtzfyMTgxv71wRh0VINLO_VMDAWuJ0gAsat2emT29irD8aL7LYWqRlPhDNG5UxRE-njdQwUgLQyChIZXYoDXx9Xow-ubqxzh1a

sprite $PersonRunningLg [17x20/16z] {
NO-50SKW30LVlUZjF-qN70wD9sgOg8aBc1JlgX0ygWJmcneRcRVx4YA0QOfT3kQaFQWtGV8wbOZ0eQJj4TBscXhq046Te0FWgbr2b7mjIqtbYc8pngIf86e2
Zac-GOl2f_SB
}

!procedure PersonRunning($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/PersonRunning', $name, $tech, $desc)
!endprocedure
