' definition of the Item fontawesome-6/Solid/Pills

sprite $PillsXs [11x10/16z] JSY50SC020J0hpV6xJzjtE0zjyEUFgBRnqfJotH6T50_3q1XpzNXANW7agysYLad

sprite $PillsSm [13x12/16z] LSU30SK050F0VDIu_QUj-PZBgtxSCDuQBVuUSA3dUm4Qy1q4TY0tTlNmANO54XYJT4sM-WpBcm4

sprite $PillsMd [17x16/16z] POg50S102CHIzsR_QUloaXSW73drqXEoUi1FgUNa6WOA22FAAzfvZ8GdGo0gJrflJjSOmFcwHCYG29bqzcllSgzwy3RGgWiyXfmT

sprite $PillsLg [22x20/16z] {
TT1L0e0W403HjOEO-v_Mf6E-rcS1qckOnXfv6ohyod61HGPGcThlCONDbE_wy3eljHhUbaBvKwag6HnFkAni43YgmN6cuBXMPCnL9QoT6l-kVLY9qrd49WUb
t1DFxhtpdTTl-9eSThe1
}

!procedure Pills($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Pills', $name, $tech, $desc)
!endprocedure
