' definition of the Item fontawesome-6/Solid/Play

sprite $PlayXs [7x10/16z] Ou00LdumnGy4K8eVH642JeGSEqW7H1y

sprite $PlaySm [9x12/16z] Ou03VbOe3GHm1ZyFY041p406Bi05fQ6AcI2wk24cya9j

sprite $PlayMd [12x16/16z] Oq06tEnm9Yy_FpyZbCqF0ZnGDWIm8TWGXM0Qgf2VCE13C9dWwZdWPl8Xx6A2sClEpy_5W0K

sprite $PlayLg [15x20/16z] XS-r0S1G201HufxRVzguy9NhNeE8LrbfDK3v4u3P9GmkeNJ9uX8Qb-3GQd7KYiBaB2f4iTD7hlAq0AYNOPHaEm

!procedure Play($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Play', $name, $tech, $desc)
!endprocedure
