' definition of the Item fontawesome-6/Solid/Poo

sprite $PooXs [10x10/16z] NSW53W0X30NHlwumzxyjcJJAgpSY4apRZ-gXmnSFgqzlx7afkMtnvrO6

sprite $PooSm [12x12/16z] NSc50OGm50MmTugJ_QV5FUttBEJ4w-orQ_DhqQy7gqV_fkpdBq7-Kj2biti7xyaNFIGVU3kD

sprite $PooMd [16x16/16z] LSk50GCn2010tZst_xHLg5mKYsIAFrp_CR_XWAw2wGH7bw7oZWyb6vIAMeyEPyIEFfe-BkHqooEdItk7K__KS1ooBKPmPME-mhyx

sprite $PooLg [20x20/16z] {
RO-54G0W3CHmXzz_MmxNuC5QCe4X3m1-BZpkFHWl9qD4nTEX0XR3OSDyd6oAwisnzHgpeoilqlfVUS2MhahUHbawrHt5HRdi7jLoYgo1WZHx-1O7Zb6HHYvu
8U5H8WC
}

!procedure Poo($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Poo', $name, $tech, $desc)
!endprocedure
