' definition of the Item fontawesome-6/Solid/Q

sprite $QXs [8x10/16z] FS650OG0002X--vd_sbjXGuNL1-NNavfvgaPxsQkwYIf_dJcphT2HW

sprite $QSm [10x12/16z] JSot5O0008HGp5dstzPxLqdrA_YtgeLwwnj86ZsGTdX6JQirsWns8rp2rrVkKYTuR6yFpmf-

sprite $QMd [14x16/16z] POw55K9130JppttwxvQNnM5Eusl_X7cwFQWWBZSMh1Wo41IHqpAOoH2T4zds13RfPMtLEaVz1aK6no-3HytmB-I7wOuBf2gXh03iTN3BqOy-tNnpk04

sprite $QLg [17x20/16z] {
TS-5iSKm300mbzdQVzeFvJxGKIxc-AAigY8kDcDiEgSrgyVm_qZyLvD78wp_SQYfWofEANlYKf4oRd1y3EFsCHyVssngZdwgw8XpOnJCCL6UF-lowDQFzhWF
vhQ_7PnsINDUnRGcnnE_
}

!procedure Q($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Q', $name, $tech, $desc)
!endprocedure
