' definition of the Item fontawesome-6/Solid/QuoteRight

sprite $QuoteRightXs [8x10/16z] Oq07_FoC31pyO01aGsa41ge0OH2R3QIOWGF80n8m

sprite $QuoteRightSm [10x12/16z] ROV50S0W00Elxhtzfwq07oGUckX2TCpgYWbtiGZh_1Tu0GYp0tINw0dutnel

sprite $QuoteRightMd [14x16/16z] ZOd50O100CE2Ezr_MbpFywc4TEfn7B8xQ-r0fHUOVcjsEAvrPvQDWZsd8mztvIZDkzfIzs2uJdRs3BC2

sprite $QuoteRightLg [17x20/16z] hSwr0GGX0031lSEz_shnr-HreiNX7tpfB5qUTUWoYJs-yb3UdKZF4rmdx9uuh7DpWjEDOjWVwTP4dp-OyfWeNQRJeonoFCKGUpd0M3Qd-Ke3

!procedure QuoteRight($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/QuoteRight', $name, $tech, $desc)
!endprocedure
