' definition of the Item fontawesome-6/Solid/Registered

sprite $RegisteredXs [10x10/16z] FOg30G1024NFnlxRvjwXFW8oVml4PoOkIiLjIJ1nsryJzPfx-FQHRNu1ArKN

sprite $RegisteredSm [12x12/16z] NOo50S0W40DJzxB_jEZx8Qy96aywCKY3aH8zNUVvgk5hERODPurFo-je2gfpz7iEobVAlzGvrFz7vUDk0G

sprite $RegisteredMd [16x16/16z] LO-55S0W44E3E-m_RUNoi5-DO11S6qLXqWO9b6FHfvnKbelMseYXmFSgkkbsJjkcpdEYsTVoMwXxHsGq-s0VztmTNZRsxqLYRcZYyL4FAQZZD2y

sprite $RegisteredLg [20x20/16z] {
JP3L0GKX30GNT-Y_sYUNpP7vOuY3j7rcXY4TiXp8CJHLbgxAahIM_pD50anuwC-ZgcjxTwtJwCPDEfkkZf7e2EijUKqw7y8Rbcyz1ntckW4dIqkDyOGmsSEP
ifjxe1r2k975cvCIl5IUMOA-
}

!procedure Registered($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Registered', $name, $tech, $desc)
!endprocedure
