' definition of the Item fontawesome-6/Solid/RightLeft

sprite $RightLeftXs [10x10/16z] JSl50O100CJ0u4xwhnOvd-SAqKYc36PiWLfR6CWlTtxjGwzuWjo-

sprite $RightLeftSm [12x12/16z] ROo35S1G3023X_hsdxRwniMKn2KPXTS573WfL3jhoV_qB1-WIj78HK60sVu3

sprite $RightLeftMd [16x16/16z] NSk50O1034FH5FU__xGuXV1EQ_fOP2Run-ntuZ3Z56a6UfktKECJpZ8G5dhCRahZWXExAbBElopU

sprite $RightLeftLg [20x20/16z] RSwr0S105CDGXpdQVzf0S-J_IbLIPRnbWAWHDJJWBfpMhS1lLoL82f9o6YwrHjWyiRV9se2xSU9tROKfl_kynqcb5m

!procedure RightLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/RightLeft', $name, $tech, $desc)
!endprocedure
