' definition of the Item fontawesome-6/Solid/Rotate

sprite $RotateXs [10x10/16z] Oq06_400944CA8UV3oGEPi4Ke2i7QO0o-C0iVYvEg2es81j80G

sprite $RotateSm [12x12/16z] NOk30S1G34I36lVsdxRcZtEm8WISLmVp33qoPzoHWUs-QFPxk3nIsYSceDwFmE0sl3VixHpXfoUcAVQz0W

sprite $RotateMd [16x16/16z] XS_L0SKW5C3GYplPVzedTM_-3evS5bjrgnWhOlX90ScOmg-__nD3enDjf1aDsrFaBTr_XGbrsjL65fnig62QLtzQi7-t3jG6fE4d8fvrrR4l

sprite $RotateLg [20x20/16z] {
ZT054aCX48FXfpZyzpzj9TFKBMFmeRlJbophEZ_01aevZJEY1ivIa0qWd8zBPHNgxGxP3CFtbejbC6MV3HGRjd-pAhVf_79715kswMEFD62HSHwuy3x91a09
6SudPTd5toxHiU3sVSmH
}

!procedure Rotate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Rotate', $name, $tech, $desc)
!endprocedure
