' definition of the Item fontawesome-6/Solid/Shapes

sprite $ShapesXs [10x10/16z] Om03HWOeuEU7ClZuOKn-51P89Gyd0q80JF30MPnm5e8

sprite $ShapesSm [12x12/16z] JOh50O104CHmX_HVBIUhUOra48x10OyNKQWi4K7o_bMUbZR6x7wYRU8YH1vJ7hucIYu

sprite $ShapesMd [16x16/16z] ROi34i1000DJk_l_rnPdxI0JoNCh0uxKha1UG_Au-1czxR5uVpZVgSNEdBZPFfqYdDvMzy9J-Bdmxdy5BskjmWi

sprite $ShapesLg [20x20/16z] RO_50G0W3CHmX-u_BUwGPwg75W6Z6m2ubSnEFsrFOu17OcYmQ_9gfDF9Jz_yyOMuzjZpXLeBGbODiGuH62pdFWu-Jd_S_DPlJisWP6KMhIkZR8Kd

!procedure Shapes($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Shapes', $name, $tech, $desc)
!endprocedure
