' definition of the Item fontawesome-6/Solid/ShieldHeart

sprite $ShieldHeartXs [10x10/16z] Om02HZO6CE3c1m4WdnyA-FZuOO0LA04487aOYn7COq3MmWjH0X820Ju80m

sprite $ShieldHeartSm [12x12/16z] HOo50O10482mM_RVLZ-FwoInhbGUVvwKsU6D_BxLEhuc7LC-w4JqitlXpVcOYfHEn5CIFKsy-gRu0G

sprite $ShieldHeartMd [16x16/16z] NO-30G0n00Fph9lzfwrzpw12nVwONCpOfduEBW3SW3-qosznKLssQ4bIef1rUTzLkwvvvFHTVi3T3FOY9pBhQseKdYat0vDvl0W

sprite $ShieldHeartLg [20x20/16z] {
PSy50e0W00J1izlx_sybreAn5mkXEKRzJQU3jT5ZywFb8VyC8RbqwdH5j2riAos__v3KIHfIouTMo4rLsnWYpGuQVlWaCTwQIDeKc1WIZvOpEPIitoOuuqcS
TNgYVhfGPk42
}

!procedure ShieldHeart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ShieldHeart', $name, $tech, $desc)
!endprocedure
