' definition of the Item fontawesome-6/Solid/ShoePrints

sprite $ShoePrintsXs [12x10/16z] Ou00RZvcCCqF1Nn8R7uWcv6J1yw6AMJ00305_32zG2QS3HQ7Cm4

sprite $ShoePrintsSm [15x12/16z] ROp50S0m30ETXb7xJriAmxri4HMkc5GvWOZCz_dobf-DRo7Lj-AYeJCIWAsFwJiA8Q30YCBm_eE-lF7x7W

sprite $ShoePrintsMd [20x16/16z] bSx50G0X34JH1FVflzerdDl-6myBpNH6ajGpXJ9wbJGm3R2lnM7p99_snSIcJ9jnbKI_CpcxNI9gikudzfXz18Y46JzMfitPTfl35jHqNTy

sprite $ShoePrintsLg [25x20/16z] {
fP2r0KCn30K5dunl_sb3PkXovOb50tT0CD8RLReZ2fwB1q017I5vkmJWVW6t1l0By2wGU0oPk0OAqc928qVI1_s9gF9g6HaTapqgjhw3_EQs2sk0yr_t5VSI
A4VxES3KeGu99qMz0G
}

!procedure ShoePrints($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/ShoePrints', $name, $tech, $desc)
!endprocedure
