' definition of the Item fontawesome-6/Solid/SquareXmark

sprite $SquareXmarkXs [8x10/16z] Ou01Vfo0WGyg2QSm5SE5

sprite $SquareXmarkSm [10x12/16z] Oq00VWA0cuUV1SfaO86fPeSnk1du4IRmeMZaWRCOkFaWW1q

sprite $SquareXmarkMd [14x16/16z] bOk35G0n40NdZAZ_QcC-xwpnMRbint0x4If57xWSzDiDMDU1SncuXiww2oU2TLe8

sprite $SquareXmarkLg [17x20/16z] hS770O9000319MUs_sxbS_cbCaDhoFLWwJfzoSQk7IPmTdGc9mzpFLnc1XwdqGeUO7JtwZ7weyKAbuM9sWS

!procedure SquareXmark($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareXmark', $name, $tech, $desc)
!endprocedure
