' definition of the Item fontawesome-6/Solid/SquareCaretDown

sprite $SquareCaretDownXs [8x10/16z] Ou01Vbm0BWjJn8rDBKmC

sprite $SquareCaretDownSm [10x12/16z] Oq00Vc819q8vYC713sKomXGmeghdWRCOkFaWW1q

sprite $SquareCaretDownMd [14x16/16z] dSUr0S0m00Cmbxd-_zemBY5jGcxxWmyRXpsmx0wtttOrUUbCAZS3u6JYOnNoPIG

sprite $SquareCaretDownLg [17x20/16z] hSgr0O0m04JHmvs__xHeF1NokXFbgb0f4LjcVh8O6B8gKrGovkGoOfYcmJ1DJKGbhtKaj11fbDe1

!procedure SquareCaretDown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareCaretDown', $name, $tech, $desc)
!endprocedure
