' definition of the Item fontawesome-6/Solid/SquareParking

sprite $SquareParkingXs [8x10/16z] Ou01VWm04sG0GXG-0ozK70uG7

sprite $SquareParkingSm [10x12/16z] Oq00Vgo0buc94y82gM66ilYP8SeH6X4cO9Z40sSnSFD103i

sprite $SquareParkingMd [14x16/16z] XST50G1140EmBlFKlzfZnlo2CoUR1iyVMckpHM4asqepKDk41BQDz6dSLYet1iA3naSuxwG7

sprite $SquareParkingLg [17x20/16z] ZSp50SHG54BHEnDN-gysRlpesJq1pgAZFyWrjJvf_uDCEsQs-Da68YaD5vajPe-b44dMOI2JgsLCfW2DJ4Ae1m

!procedure SquareParking($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/SquareParking', $name, $tech, $desc)
!endprocedure
