' definition of the Item fontawesome-6/Solid/StarAndCrescent

sprite $StarAndCrescentXs [10x10/16z] DOo50S0m2C3clkR_Qt62wsJSx9C3V9rCIIOslYCxOISoZ2EontraPaSi5dizL

sprite $StarAndCrescentSm [12x12/16z] FOl50G0n3CFSOwpsdxQOH2-ZEY-N9ZJkmwKc8RUXdw7fDvhOC_03_lykI75htHYbeLlX0BkS_YStKG4

sprite $StarAndCrescentMd [16x16/16z] HOq50a8n34FpTRxS_xPGWRn9KuVpB8u3FnQTcgxfQKBkANV9lJEzu5oqoKhRH2ytfr7062uFCzfJS92y__uAu_u-y1BVHtO8tp00CMEIEEWqqny

sprite $StarAndCrescentLg [20x20/16z] {
PSu55WGX30FGu0xtF-rOOCjZEyf7KinAVLI7hToO9SHnLJWe0oTv_9sLriZACbdmCxUCEz9hJDIXF__5eNFhtkHBD45KCGGI_FlHj4nZRbcfFNs1JJOFyoxs
W98KgVJb7yYZdS3UM2sxHcBZw0O
}

!procedure StarAndCrescent($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/StarAndCrescent', $name, $tech, $desc)
!endprocedure
