' definition of the Item fontawesome-6/Solid/Tags

sprite $TagsXs [10x10/16z] FSQ50S1034BHN_Uo_xHdyS0ZPrCRj467KSAuzZBEmOV3W32Ybqw3pGSL

sprite $TagsSm [12x12/16z] JOd50S1008EeUzb_sievhmHeyOVnobFn_3Vae_ULoc41-x8xcQid7xo1ASpxdw64cJc15m

sprite $TagsMd [16x16/16z] NSY54K9H4CNG_ET--wyMPsSXeoVyjywZ7M41iFMk8W58RhmDDjxEie7UsVWfHmNv4DMnNe9YN4X0ziJ6ukZ2XYCaDQRHTmS

sprite $TagsLg [20x20/16z] {
TT253SGm0CLGbxb__saFmlY4iSAqZ9C532F68W-anJH532wg4IMjaCJPZ0u6PL51YACAZ7hVAhOcNcAfvy6M9zEocIFcXh1bi-xy8qPUdJXRFYlC3BDoUkZv
0W
}

!procedure Tags($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Tags', $name, $tech, $desc)
!endprocedure
