' definition of the Item fontawesome-6/Solid/TeethOpen

sprite $TeethOpenXs [11x10/16z] Oq02_7300yGC_9nW4Q0u0oE8uEC6aMmWWXUxDeHQ3dP-JduEa45i_0W57

sprite $TeethOpenSm [13x12/16z] LSj50G0n00InANFNlzfZp3_yD3syqwPBGmShIu4nd1J04A73ZCEqPcOoSaRywFK_QgH8jqmG-e0nBvqL

sprite $TeethOpenMd [17x16/16z] PSs50GD12031pTahRF_LnltdN02Eblo83lxAnPlMjAm-BCKLuWHc2HNw0jlj0j24yds1cRv6Pih1o6_1i9J8KjnAjPUk2VnK4PO0f-T5rT18tRqFmX-3VnS

sprite $TeethOpenLg [22x20/16z] {
TO_5TKD140JxytBbdwrVMopDrc4ODMFxOfLqyOj4m6XWcWJvlMRRmECjJjgQ0DkhnMAnMmomqcSqKP-rfyLbqN7v3sN-Ml0S0Rqzrs_FbNLo6MpImMBRPHQ3
2t86KWMk1fmTH41M44wA-GC
}

!procedure TeethOpen($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TeethOpen', $name, $tech, $desc)
!endprocedure
