' definition of the Item fontawesome-6/Solid/TentArrowLeftRight

sprite $TentArrowLeftRightXs [11x10/16z] Os3WPG03FWO6VYO8auUVYnyE6DZv8Q8GYfCVfWeiomTcGG4can71P01X

sprite $TentArrowLeftRightSm [13x12/16z] JOo30S104C1Ikzb_sl9nEHDM4YqSviBXC80x2GyGE5VeKrSrVz5IpLehCsCk3dNFnUTBCQhS

sprite $TentArrowLeftRightMd [17x16/16z] RSp50KCn3C1GVUPe_sbB0PVUnMmWqPm0IjLvWNPXDbr-uRAdsLtWz9KEmE18eHuGL4rKemNPOPF_Q_ZRw7Ewj4REf3NEqkZhrwiqK1su0m

sprite $TentArrowLeftRightLg [22x20/16z] {
RS-55KCX44JH-Uwy_hlDsObX5tTMqlWebnGMK6OZkMPKxeQOx3ZfqG63SZkClbWsAwoWiDokmJySRvaTX5651soJsS1FoiB93RAHacpkpfvWArZvlX8sAV2X
0LlAMTs4I-Mi24yzwmTlwGK
}

!procedure TentArrowLeftRight($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TentArrowLeftRight', $name, $tech, $desc)
!endprocedure
