' definition of the Item fontawesome-6/Solid/Ticket

sprite $TicketXs [11x10/16z] Oy0AkFYH00CR6B3mC_8pG4IOWGmOavq7pWHYg7us80UX7m4

sprite $TicketSm [13x12/16z] TSd50O1000F1uCxsNorwBlEAg8vOQ_1O-8qWLoPEBRwe3Px7ikwVbjVssq445Be1

sprite $TicketMd [17x16/16z] XOg50O0W0C1cj_v_hKetZ1wZpNm6TFEJilSM9JXCF_pzzGlN_e8b540ixb3C_n480LslOLKVX-5KVGXDFW

sprite $TicketLg [22x20/16z] fSYr0GGn00CmXpdUVzg7OqQLmdk5QpvoZvTJbIr8EuBkjtAa5KcnjHbORyRMEa2jbyXSRmk58pNiZ6KdJMJ-A6w1AIi9Ttm1

!procedure Ticket($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Ticket', $name, $tech, $desc)
!endprocedure
