' definition of the Item fontawesome-6/Solid/Timeline

sprite $TimelineXs [12x10/16z] JKY50S0m36Bku_zhQ_7WoBUJmxjnvfY-TvS1QXBnlVWP9wEOH5wHmRG_tIe

sprite $TimelineSm [15x12/16z] NOc54S0m3CG-U53G_jCMmh6CkfS5M9w4gkRwxAaygZZ-5N6Ly3qt6wfmQeLxDwvLyysYWMOl

sprite $TimelineMd [20x16/16z] ROy55iGm20LPhG5p_zDMURywRH9Sx94FOCMxP71o4KgEvHrCWVWc0tIAWtOHKgPTTam4hyMJa6AH8n72NeNpBSc48-MqmGKOYAkjjX7Qu48YqmG

sprite $TimelineLg [25x20/16z] {
VP250O103CIAUxF_jFYx14tlNIeCe8tJoMZ7WwttLc6vdyu4-chx1jFzz2uO_tQZDrIegwrRlIStipYSveEUFAeKa7anxB1O-l1e9CjK26R89x0fXoIq80ra
UooAPeArD8Uqw-BP1G
}

!procedure Timeline($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/Timeline', $name, $tech, $desc)
!endprocedure
