@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-6/bootstrap')

' loads the Item which embeds the element TrainTram
include('fontawesome-6/Solid/TrainTram')

' renders the element
TrainTram('TrainTram', 'Train Tram', 'an optional tech label', 'an optional description')
@enduml