' definition of the Item fontawesome-6/Solid/TruckRampBox

sprite $TruckRampBoxXs [12x10/16z] Ou02VY20Cp7PlFmmDZyJ0u8D12n8R3wOUY2BWHl40h8PGKAi87KW5inK

sprite $TruckRampBoxSm [15x12/16z] LSwr0S004810ulhF_jF6bUuwk6lTU-YFvSjsUXc1lbHwgvTx-R1nxo5gb5Hgx2oXSYz1ob3jGQajDTwlN04

sprite $TruckRampBoxMd [20x16/16z] XSZ50GGn08NG7_VGVxNhEigDfvyYptueiBP-QhR5FpFLtE_FeCYj31c8lnPvD7zDF3kr0LGZcGdWqjra9LDuvgHnjpYuDvmQIPg8HqcFO4pkrlN90-WA

sprite $TruckRampBoxLg [25x20/16z] {
fT454WGn24HHUbppxt_Q5MhSfKlXnMFpPFIPzmjsWFUWij4QSZzCkuJA4LX22vbtj80CWiL0kG3H9InWB2v32fvg2LxbawTjp8A3P6PHDHshxabAkjJI06dJ
DvFk7LifWA3ReqkD9pCee_KlPlO5
}

!procedure TruckRampBox($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/TruckRampBox', $name, $tech, $desc)
!endprocedure
