' definition of the Item fontawesome-6/Solid/UsersBetweenLines

sprite $UsersBetweenLinesXs [12x10/16z] LS650G81002XirlsdzRyXArPAsTjb4D5s5BTX9mhZjMTuWeNz07wktprSPsz0G

sprite $UsersBetweenLinesSm [15x12/16z] PSc50KCX54FHV4TUc_sdnPsB7ZWvXMyAQuh4Ztn1Ne4sa4oRGlI3V_pzJ1JZDIIa93qtGz46IYG-9Sk1q5sufpZb0G

sprite $UsersBetweenLinesMd [20x16/16z] TS-50S0W30J0fsxm-s_Ru7wuauMzYprCFBTKnxl4hg20bkgmNPtdc6fO7tc7EMsxoK6o7XdVtIbo-nbZNgWma7hPwU7s6vTb0ICPANZ3i9I7ASFU3m

sprite $UsersBetweenLinesLg [25x20/16z] {
dS_50O0m50FGKFViFotk3kzI_IPuhYHUm2-AD00IQG44iaAlOaiWisMWbmAIBGVsXdUnHCYAFTWbejjxW9tKbv9O384PQucjE3qNjYnQ7EzbHomf9Jim75LW
Pvf2S8QuBXOvayS61WeRVcBn99ppcHSQ
}

!procedure UsersBetweenLines($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/UsersBetweenLines', $name, $tech, $desc)
!endprocedure
