' definition of the Item fontawesome-6/Solid/UserGear

sprite $UserGearXs [12x10/16z] RSR50OC00CNGrBrl_sbnRdnDbLERJlXi30uut4gxyFlN2Ur1tddk37-Wane1

sprite $UserGearSm [15x12/16z] LSsr0GH130ImEOO5zL_jCoeoEpU3DLyDyW7V_W3AVtVCsuQU36g-m9IRTTk6pe84Y2FvP4SdXHdmUkTbpQ0bLm

sprite $UserGearMd [20x16/16z] {
ROu54W0X30DxYjF_lnR9u90JCaig11d-QPRWh9a1pL0Tc2di6jXRsA6VJUv-9-XWqZ7fOPVZV5W9KLr6f1G6wdxz98TqHvpTZMK7velvJME6535xChWiKdVP
Bm8
}

sprite $UserGearLg [25x20/16z] {
fT170eL020FGsCi0kVzfVm7ikl8jXnP5wDHwN5Lq3SwOS38poNKWlIwqJ0DEbCuoIS5gui-yD2akPXPleJt6gF5Nw316CcNSaIrKHrO-E1t6vt_msDZ7ceIU
7gbu4pTjjJi-S6Ce4RTGOTmPTXyet2iJflm5Nm
}

!procedure UserGear($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/UserGear', $name, $tech, $desc)
!endprocedure
