' definition of the Item fontawesome-6/Solid/VanShuttle

sprite $VanShuttleXs [12x10/16z] ZOR70O0W0CIY7xlPVrgbmvEhOPHLuCCZzuDsnYcjNgY-A8ZKtINjmWy

sprite $VanShuttleSm [15x12/16z] bSU54OG050FHFS79RF_LuZxA-neUF06nxvqdqu5ZcEyjuZlHFoxef_aA_h_VDE1dchGoiRHbKlSiyeSH

sprite $VanShuttleMd [20x16/16z] hOx50GH148HgNUl8Fzfr6taUeyqBvIZz-p0SYX1l3jgoDFLrmRYxKZAIPhG1NU9AAC3sSstmVpf0gZcuVYgEXhstzFaxYkghhQQwVjl3fdSCcywo0W

sprite $VanShuttleLg [25x20/16z] {
nSz50W8n4031ZgFf_xyMX_MzKf6nqx0jffd0YqkLXwCh0g02vVNp_LqV9Esh0wgA6aAehpzg34yNFVbtbtJsfpQVeYhG_OWGL27QWPCvFbpbmHvuqF7IHsYU
U2hQzSYBBxnbjV7HjRFd3W
}

!procedure VanShuttle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/VanShuttle', $name, $tech, $desc)
!endprocedure
