' definition of the Item fontawesome-6/Solid/VanShuttle

sprite $VanShuttleXs [12x10/16z] Oq06_300PF8oyF8pyF02nH1i88SOmCJF0r7903O9264a9v00aOmC

sprite $VanShuttleSm [15x12/16z] bSU54OG050FHFS79RF_LuZxA-neUF06nxvqdqu5ZcEyjuZlH0XVqqtm5_zzl6l0pJLgPMDeogNiM-SC8

sprite $VanShuttleMd [20x16/16z] hOv50W913C2ohYN__osCuSTDlQVmZpvkRspvvIS1wDptuLYRxkdNGmYSgQ7Zpw_NJYEYjOJNiwWmrGl6rBlia7pxA5isciWNetErV8madmXru2zt

sprite $VanShuttleLg [25x20/16z] {
nSdL0SCm303Hanocst_QG9b_-smntsLv4Ppuhc7N-q40Ab2VCjVivqFHvUE1LaMDYEQKKpCEimx-tLGcRzhMGwe2NXK8LKWNOB3AtImxbpWLp-dGE4BdmA7M
HNjEF87hnPQBHHT-sG
}

!procedure VanShuttle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/VanShuttle', $name, $tech, $desc)
!endprocedure
