' definition of the Item fontawesome-6/Solid/VialVirus

sprite $VialVirusXs [10x10/16z] NSR50OK000MWzzEM_QUrcnCvTB1M_fw3nBg0TU4LMY2e8Gdnaky8

sprite $VialVirusSm [12x12/16z] ROg50S0m3CCqvkd_QyVOLk7OV6ZSuKJ7TnznJkrg0TuxxkIeCr8hdEzgEgVb-O3-yGFb13a2Am

sprite $VialVirusMd [16x16/16z] VOw5OGGW0CIkk6V_RVl8kmJDeNfbB9eEdSrz7Mywvi6D6lhXlREy7f_8AYAPuyMoEJx4C3FVdXKnwojk-Ly5EhDVwP20gelACH6BBgdDOuOo5TrnI_u1

sprite $VialVirusLg [20x20/16z] {
dP054W8m30GlWjNk_xzbgi76sFhMWr_OGaDLRi9TVpWOEMRmdnEvVRguel7DGHE4DDmrNEBck1l8LATQJY1CmEnELz5w9UoqwGeuyLxjlRDrzBBMCu6BY1Rk
szKk4qc34j8tLaSGVti2
}

!procedure VialVirus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/VialVirus', $name, $tech, $desc)
!endprocedure
