' definition of the Item fontawesome-6/Solid/WalkieTalkie

sprite $WalkieTalkieXs [7x10/16z] Ou029cOGoSmF1PoSd5pyg82F7wI2dm7CGQC

sprite $WalkieTalkieSm [9x12/16z] Os3WOu02VYZDoC_8pySB91201omF0dn00AGmf1WWF0I35uF13G

sprite $WalkieTalkieMd [12x16/16z] TSk55O0m40JHnPtflriUSVtHCsdQ5Tna__N-z__5xOlSClmUVk_pmvZqUoYjld-5z_u1Ul66P4RT_nh_7m

sprite $WalkieTalkieLg [15x20/16z] fSx50SCm5C1GbHlK_jE6cU6TxCz0ycJ8TEVxLc8JUBadgANM7hM_YwXzDqSbQZek9dKW79_5hI_sOd8

!procedure WalkieTalkie($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/WalkieTalkie', $name, $tech, $desc)
!endprocedure
