' definition of the Item fontawesome-6/Solid/XRay

sprite $XRayXs [10x10/16z] Ou03NduOO40cG5ACC2wcB0y36ok41O8G2JOsDX09Dmy

sprite $XRaySm [12x12/16z] NOs30S1054DVxNJ_QS_-Pa8Znr-54BzOroWVjurjYxKa99V7czFLPwndOEADyr2xUSUbAXO

sprite $XRayMd [16x16/16z] TOw30S0m402lThF_jB5nmHlK_0Nl9qhudLoSc8ED5zR64UmwZcUkumFxW9KfzLlOCVShvyrMisMlncxUxb-X

sprite $XRayLg [20x20/16z] ZT230G0X00NGVsQr_xJPVjb0pLPO2IkTbJvijlB3T_c-B--3jKHzbD8NCXkiHL3E6v_xoxuJH-XRuH3VTm6w1j1uxGAL7jqm1RjFXUZw-i_-LOK

!procedure XRay($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Solid/XRay', $name, $tech, $desc)
!endprocedure
