' definition of the Item eip-1/MessagingSystems/MessageEndpoint/Sink

sprite $SinkXs [15x10/16z] Oo00s9aG02UNav4H3vSBXruk142t5G

sprite $SinkSm [18x12/16z] Oo0EyA80a0WJCk33ByB8o4YI266JML005WS3

sprite $SinkMd [25x16/16z] Ow0ku6971zmG2JOcTC19l0Gto1ni4foCZ8nKak010awW1BdEvUD51tpa12

sprite $SinkLg [31x20/16z] Ow0rO6J73fWWqaoiJ5W16_MbcJb00ASq2oCGi0wGD5W6JD0ZM7Yui0AWD4q1

!procedure Sink($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'eip-1/MessagingSystems/MessageEndpoint/Sink', $name, $tech)
!endprocedure

!procedure SinkGroup($id, $name='Sink', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$SinkMd>', $name, $tech)
!endprocedure
