@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceMultifactorAuthentication
include('azure-20/Item/Security/ServiceMultifactorAuthentication')

' renders the element
ServiceMultifactorAuthentication('ServiceMultifactorAuthentication', 'Service Multifactor Authentication', 'an optional tech label', 'an optional description')
@enduml