' definition of the Item azure/Item/AiMachineLearning/ServiceAiStudio

sprite $ServiceAiStudioXs [10x10/16z] POgr0S103CJ-pVR--mPK1LGTQDr4o8BA749MLPEwwuP49i0luRyIuGG

sprite $ServiceAiStudioSm [12x12/16z] HSY74O000C90h0JttzUEvjfVTBUkcvv6x1fm_3X0SdD9mjMrh-ec-NCthAgbilvv

sprite $ServiceAiStudioMd [16x16/16z] PSg50S0W44FHuWdx3zpWzgkFkwzbOqpncoN5F6a0o7QEeKWCa-sWqr6XLSUrn_KjUiwgTs8vzt7eTjOQSQvNREvCbw_r7m

sprite $ServiceAiStudioLg [20x20/16z] ZSy50eGW54LH6jwV_QztLBhXsiS2bfB661AiYjitywFQd7Cl4l7QF19C8Ujy08e1Wt6ykPJoPe5AjJV4AXFP_DuRgZQcE_DpG8hmnjjNMKfF35kpTw_oH0y

!procedure ServiceAiStudio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure/Item/AiMachineLearning/ServiceAiStudio', $name, $tech, $desc)
!endprocedure

!procedure ServiceAiStudioCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAiStudioLg>', 'AiMachineLearning', $funcName, $content)
!endprocedure

!procedure ServiceAiStudioGroup($id, $name='Service Ai Studio', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAiStudioLg>', $name, $tech)
!endprocedure
