' definition of the Item simpleicons-6/A/Abstract

sprite $AbstractXs [10x10/16z] FSR50S0W0C30rBtPVreSxdN0yVkjWCq-vg5a-flwcfOZUL_UUQUjQM0QTkmz4G

sprite $AbstractSm [12x12/16z] HSR70SGW0C0mNqa7lF-seQENoEvaEak-3k22Gh7fhR7OyfCA7_VDWassygJeyoa_TUCYbADUl-1rbKy9Lby

sprite $AbstractMd [16x16/16z] LSx50G0X4CNGlwwG_gl5DRU7ZcAt0ViTIbtqrfaWCMMZLJg06pXpoORO_mF9AOK69oZRHZ_m5N_HAop59_2ccRC5OFRjX-D9ddgrJbR83hlo

sprite $AbstractLg [20x20/16z] {
PSo53SHG0CDGb_lH-qzxK8OdTgImc59LI-ZP12_gadqO8VZKu4jS6eT1TVBTaXTvQTRzbxotVVyRRmsImgEfWR2rShIPkBMWsZARmAtrgfM_UM-u6Di-Qnc2
MgW-JVG-0UCxGHCzb0du0W
}

!procedure Abstract($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Abstract', $name, $tech)
!endprocedure
