' definition of the Item simpleicons-6/A/Affinityphoto

sprite $AffinityphotoXs [10x10/16z] HOc50G0n309VwxB_jYL-KU0YDbZqDFeQdd-_6wqPeEUdJLFKerdtMkkYFxXYBym1

sprite $AffinityphotoSm [12x12/16z] 7SQ53GCn00Imu7FY_RUjhXQvn2bw-HCh-snKEOqbxsECKy-xpNFBAJZpq-NJv5m6iNLCnC97557X1m

sprite $AffinityphotoMd [16x16/16z] FSnL0a8n34N1vrAR_QyMky3vcpR9b4XVpZqyn39WYoykMCLOqE-uZbShiu-NrjRQ3gN5s34lFjvOEpOn_VxCn3UpFltpkJEJ1WkPJWUvbdu_ipH9jOCd

sprite $AffinityphotoLg [20x20/16z] {
PSu5Wi0W3031K3So_t_jQJZT-hG5OcIKstyB9VDr51tNiDJAchALPmRpCmocZZufEy7qUPIrrjwEU3pxCDmhGYXRqE2Uxc4uPj2KROWrCVTXM8dCi-LdSM7X
MCwl0g5ELNBjQZNVHLsIqNxvRFxt6LkgblzlNm4
}

!procedure Affinityphoto($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Affinityphoto', $name, $tech)
!endprocedure
