' definition of the Item simpleicons-6/A/Aiohttp

sprite $AiohttpXs [10x10/16z] 1S450S10000Xvhxht_O1hZOGk0ZODwYP-O8WS6EtXnsGs-TQ0MmpRWO

sprite $AiohttpSm [12x12/16z] 9Oe50G0W40CFT-YV5jlhZ5TjPLJpt_LE9agIsfSBbI5_lH_RZqL9_39Voh4dm4bpnEXMSes5me44qykTxuvdj0G7

sprite $AiohttpMd [16x16/16z] {
9SU5SGCm40315IQsuFklrlGxS7D0Fx4AqbbGxWIk3hIJom2rRmw8s6qypMhBZsmd_u2LmHzeaI6LLOkneS4eXNKhHE6wT4hCUieOrsocD2oSyY_jlv6HrW1g
h5R6lV06
}

sprite $AiohttpLg [20x20/16z] {
FSq50iGW44FHp-2q9VU_xIxwgbZ2LhlU25nPDJWilP-ngNBqkh-6CxRQ06I0EobffER2uALEZ0q4OjAVCLXXXpwIRcLW-MxxszqE1plLOee0ZQcy7h3aWBEp
fOHBacU82Q3p0g5OjDcJ7Nny9qq1ru0lOXqIHyG4r1fU3Y66rWA7xJQYZAM9g-YjfVKlClm
}

!procedure Aiohttp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Aiohttp', $name, $tech)
!endprocedure
