' definition of the Item simpleicons-6/A/Aiqfome

sprite $AiqfomeXs [10x10/16z] FSQt0O000C0WxDty_wsRJC3v0X482YDGkn2UVmi05u2qQ1EF8SVzV

sprite $AiqfomeSm [12x12/16z] DSD50S0m00J1AOVFlzk-iW360jmv1BWwv8O0p-oNpoRDDv2FCeqWdQDmsW-R9ZRBbPNv99Tm78vEuWS

sprite $AiqfomeMd [16x16/16z] {
LSsr0GHG08DGldko_xJd-ZegU6WI7z6gmOMNwW2CyyfW7kJ3dHClvumLCH-jBPT3ZjmD0A-A3T0De9DVFHq0pSuPtu-Y-2NCB-Fvty6rsI0Bwe9YfsRFA6FU
0h2ykG8
}

sprite $AiqfomeLg [20x20/16z] {
NSx7WSKW4C1GEHkOGVrNk_4xlekkujzOU-Tk27ijLYwh0M23m-82mEJ6mPL_kygVAXm6Syzvm94RJTiWB-7UuNDnr6ZC2i1Hix8e04TjmN3SVkeYRo9lOkD5
YWCF9S04NM3H3N23MJMDCBexam1ZhZ3e1CKmULaLlW4
}

!procedure Aiqfome($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Aiqfome', $name, $tech)
!endprocedure
