' definition of the Item simpleicons-6/A/Allegro

sprite $AllegroXs [10x10/16z] Oo0MiFCpS35mCh1nSRFmCt1oCB0n40q

sprite $AllegroSm [12x12/16z] bS750O10402nERUL_gl5-KF2Rx7niZIAuMYsbTFmqP7YK4CYKrOWSqjyj0C

sprite $AllegroMd [16x16/16z] jKl50O103CjvDUo_BNomFzGRmVVHwliFVNwLeMqH6eYczB65ggcWZI6bDJ8499YZ7-FoIUAFs04

sprite $AllegroLg [20x20/16z] pSY53SKm5CNG6yxZ_QSDY3uiq5fa7Roie3yOurhcX4f0w-bSwVsOmGibB_ESoQpZ6j6iyDx086AwfYnmYMFAYkyS_rMkUBGD

!procedure Allegro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Allegro', $name, $tech)
!endprocedure
