' definition of the Item simpleicons-6/A/Amazondynamodb

sprite $AmazondynamodbXs [10x10/16z] 1S670S0W00CWkjoQ_xyjOAM31KaeB-7Y_O3NsmETExTcOr-S7Bp64y6zil850Iy_

sprite $AmazondynamodbSm [12x12/16z] 7SN7WG8W002mq3liF-sTcazGxnl017llo8D3-DLt2EoUpUytSRZoWetpEjs4U_5QWhjcKLLu1SA5KqFEKOJO86py0m

sprite $AmazondynamodbMd [16x16/16z] {
BSw5eKCX30NGWpQK5zX_sg-DUoxCl6S1k1MKMah1fw5YOMM5Y_xVh_5aBNWY62rmvu0tRURhh_dHLIWe9Ansen0Si6Q7wnOW2wpJDmXzdoo7__mVJn2VVIsU
p3symIWlG0Bp3DITu1i
}

sprite $AmazondynamodbLg [20x20/16z] {
DKy74WGX20jMFCNy_xSti99jcBO37EDSsX8WKKshVwNlfEJan81FxVUe6MuBRh1zjcYMu0gQ7bEDqr5LeBRRuuGFwYakYLblj4wu3ukSppbMz57onq0B2gri
Ql6me1eUDo6j3o5ABY8cN_WAvJwIjghxcs7hopRVp-gYwuyxdxY1QiaL7DBE9JkIgrQHO7u5YL_BQTwjeyzbko3m1m
}

!procedure Amazondynamodb($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Amazondynamodb', $name, $tech)
!endprocedure
