' definition of the Item simpleicons-6/A/Americanairlines

sprite $AmericanairlinesXs [10x10/16z] OsDdW05-VYnCVWIJaOaH8Sh90cKnOb7AZye4

sprite $AmericanairlinesSm [12x12/16z] ROl50O1040DNS9l-gyNXD9zurxlyWENN3crK87KZtR9uA6RNHnkoTD-c1_I_H__nCr_10G

sprite $AmericanairlinesMd [16x16/16z] NSx70GGW449HivjV_ztk5VsdYS3QknnWPZ_HSW3PL_noyC8x1s-CadpXbH_CNiEZb3HzrKlp1v6yWtwcfDw3-yCV

sprite $AmericanairlinesLg [20x20/16z] RT350G0X44DHt27zLxkkG_xnuOGOlP9XomYBExA9Ws4HLdRqP2BqtnpOETeOeoKs7DLfo-oS_fjL8W-ZftD698UJGrG-CP69S5-p5sfoRymV1FGL

!procedure Americanairlines($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Americanairlines', $name, $tech)
!endprocedure
