' definition of the Item simpleicons-6/A/Apacheopenoffice

sprite $ApacheopenofficeXs [10x10/16z] Om02Jdus1X3W1mDE80CAMC4i1WPce2W_9W1gOMS4gmPYg2u6JeGaAvG1

sprite $ApacheopenofficeSm [12x12/16z] RSgr0S1G30FH2yE7st_Qa5tcDGQ9Lt4d669DiMw7PIsD_5Mr-6zRfk86urdad85eeguzAc3g02s_t

sprite $ApacheopenofficeMd [16x16/16z] VS-35KGn54NH6pkd_sh7-DvBmQDUmg0PVGruINeo_4mziD0_mJKLAB5WnSlCKkOXi3QurfWJ67em1lILU14q-nzgAWBzUsKn_LFKGrzUd-nYcpi

sprite $ApacheopenofficeLg [20x20/16z] {
ZO-50S0m20I_hl3xJrkDL68NnG66IRdsU33G83KCV31PrPFPgfvqDfUCmwJ7tOz2u9MeKPBZ8tI16ZF_ACjOQT2-ma5tAEnmby8ue6jmqzhK0hbRn_mOfEP9
_UW9W94Ugf_IfE--NazNwN2o0m
}

!procedure Apacheopenoffice($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Apacheopenoffice', $name, $tech)
!endprocedure
