' definition of the Item simpleicons-6/A/Apachetomcat

sprite $ApachetomcatXs [10x10/16z] TS470S0W000W_5_xjrs2WJzzi3bF3om75LaHX4G65F0Obbc11O0F

sprite $ApachetomcatSm [12x12/16z] VS750KCn500Wukzhzf-sRgU2ltAX960TfVHACLDJvInZJse5WxJNjk6mO7JqEFTe31JMWrgpMhpayECA

sprite $ApachetomcatMd [16x16/16z] dS6tOSGm400maBoWhFstTUdEuG4VgXVh072ix9KmAjzJMrD0WXfP7GcusXnzs53QD4hc2gmTs5cmRJC7P4EaxQLhK1Y8Tw93E3VVCfPVV04

sprite $ApachetomcatLg [20x20/16z] {
hS75GKH1502ml77PuVVVBJVSsSHzD926P-DCk6wUhUZvv98tn3dNOOWE6v6feqX54jd10NRhYaB1WNbAh5pRq0igFRA8aaCr2xH9XXfCOA62N1SmOfypUmrO
e2ZorT4diQ7UuE62r8l6YkQbdKplrEg77W4
}

!procedure Apachetomcat($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Apachetomcat', $name, $tech)
!endprocedure
