' definition of the Item simpleicons-6/A/Astro

sprite $AstroXs [10x10/16z] LOR50S0m3CJiJnlM_jE6yL1I1L66W0NAFwdcfROERUJg9EGLiB5D0G

sprite $AstroSm [12x12/16z] FKo50S0m29jBBVzVYqELwAOBm1PhoVp63AmKTXboxZQVOJaaic8sduwVKGkxHgFji7TYLlzXaLm-CW

sprite $AstroMd [16x16/16z] LSs55SKm2010wjxRVzelULHoSG6Ys374hGFFUGFTVSR45gb18DB276ZoNBOBotFEe69apziYInsCvNps6JUVkMcZDd0GZsFXY3TZLEJw1G

sprite $AstroLg [20x20/16z] {
RP255S0W44DJmMt_QN67tsBdBoXyBcAmu3BYOdEpILviwVt4nOOfFINMG1PV16QnfLVnqALSgQ2RwI_LbuBbNYPwDXj6SaoLJxdPbanV3CY3XYY6NGCJ_uik
TB5ze8i2hVk30uT6
}

!procedure Astro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Astro', $name, $tech)
!endprocedure
