' definition of the Item simpleicons-6/A/Azureartifacts

sprite $AzureartifactsXs [10x10/16z] Os3W1mDs1X0Bp06p-76ocFaH02ZAn83WOYY6C

sprite $AzureartifactsSm [12x12/16z] ZSQr0OG0402m-ySr-q-BGuEcIiJVAYQbjeRVShu_GMbNHU4Vh4fSFikourK5HW

sprite $AzureartifactsMd [16x16/16z] hOh50S0m30CLPcl_QSjChrx05W38ND4OuKPST37cg5V-q6QQF5Ao8rkkgsxLawoowhN_fG7eezRwfTy3

sprite $AzureartifactsLg [20x20/16z] jOx50S0m30DLPcN_QGjXyATqGRDmeY86Q6eL4tn0K_Z88a_pfwzAVLxM5dcf7IVwITDFizQt9gbzviF5clgcQLeMfhuuYqA_0m

!procedure Azureartifacts($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/A/Azureartifacts', $name, $tech)
!endprocedure
