' definition of the Item aws-20210730/Resource/GeneralIcons/Firewall

sprite $FirewallXs [10x10/16z] LSk30S0030J0g_dxZrippiCdXkTgvJn2slEg9O7v-FeU6gRJkgyeIQdmYnK

sprite $FirewallSm [12x12/16z] TS630SH0002mj6VjF-xRIForcswYfW7QQFe40kBAO98jjLPs9ZkTIfPIIMcAKTLQRst2i6tRyEO8

sprite $FirewallMd [16x16/16z] XSU5WKCn30Km_R03-uzxpD3A-Dnt8lcgv7HykeJOdp7QbA_mRhIcNETyP4md1j0W7EC9DZfCIc9XgRtltcDK2zl2n6PVbXKH-saMUXhXmlB5UkAtHm

sprite $FirewallLg [20x20/16z] {
bSZ5OGLG202mF5Vs7xVkf_xW-B-qghzov3BzqPiLVgeiulWXhatq_lENxoH4Ipw5MWXnuiSFPOdTV2WN3f7hVD6m-EodlDYuq1gSXFrHTXRxnMixNLiuIK0W
TzPa5h5UlBRTKQFaGNefnxUUfJtdl1xm3
}

!procedure Firewall($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/GeneralIcons/Firewall', $name, $tech)
!endprocedure

!procedure FirewallCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$FirewallMd>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure FirewallGroup($id, $name='Firewall', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$FirewallMd>', $name, $tech)
!endprocedure
