' definition of the Item azure-20/Item/Monitor/ServiceAutoScale

sprite $ServiceAutoScaleXs [10x10/16z] HSp50G0m2C30uFjlN2-fS2_eFDCXC_6PR9d310LJLSocT4AsEBzUEMuxoRjlZW4

sprite $ServiceAutoScaleSm [12x12/16z] ROs55S10349_0e_RV-EwDwx0NI8Kw2JNRAbRKf5ua6QPZgBnKe-vNAIFAMW91QRt-wKMj3U1FzuOJG

sprite $ServiceAutoScaleMd [16x16/16z] NSa95eCW50F0OR__ZVkRhfeeC2_k6LBiIlCfugK_WnOpHwKfhjDiawndqH6tKqJsS9F4OV_jTeO5yVUn_ZrpVHFnow1_g-a_jtBr0G

sprite $ServiceAutoScaleLg [20x20/16z] {
XP050i0m20DJai7_VxmQSxdwrS4VnWP0mMiIKV46BWn7GProMYSsgbkgMG8WeTF6wipIUKGW6IvsHK7xgjCw6yhASPtrLH8yroKQyxmuLMTtLz6HUGSF53YU
sECt6hsiMm4
}

!procedure ServiceAutoScale($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-20/Item/Monitor/ServiceAutoScale', $name, $tech, $desc)
!endprocedure

!procedure ServiceAutoScaleCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAutoScaleLg>', 'Monitor', $funcName, $content)
!endprocedure

!procedure ServiceAutoScaleGroup($id, $name='Service Auto Scale', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAutoScaleLg>', $name, $tech)
!endprocedure
