' definition of the Item simpleicons-8/D/Dragonframe

sprite $DragonframeXs [10x10/16z] DKk34G1037iR-qzRDuUu_dz329-HlglUN76ayh38dlsgbyQbXSzKzUX7KGW

sprite $DragonframeSm [12x12/16z] JOrL0i0m5CBUtCVzJri9a-OBI6MI58LBvYfPj_DMyjOJep8uZnJ1Oa6-Inf3SCOIqqxqRGVovS25fTdvDGC

sprite $DragonframeMd [16x16/16z] XSvL0e0W54JHePlP_sxrsUtzuj2EOm4IbnefTAlJxC0ykzOWrbISmvpJPwFDB7LnkQodnHrPxWFNWWFgJigoEfXUldlinpRUrlqy6

sprite $DragonframeLg [20x20/16z] {
PSs74SGm20NH1Jcdtt-rpeORtPky4j3gidBh51R9xgRaKddR-ZNJvdVRr7wjdpgxcol7wNYOPmjpt1sYATh2gxGH2Kkq3GSGhTACm0UJajD10Vrgyse2sAhM
0Agq_st6eAkY3PWg6nIz3W
}

!procedure Dragonframe($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/D/Dragonframe', $name, $tech, $desc)
!endprocedure
