' definition of the Item simpleicons-8/D/Duolingo

sprite $DuolingoXs [10x10/16z] RSRL0O1G5CFGu4xstvRN7_nSQVdbQDaqirL5hsAWy-GoAqm6eTaYkIEN0m

sprite $DuolingoSm [12x12/16z] TOgt0SD04CCeVOxOVriVArT2mwXlk3H0vkmDXp2tp9HHFftNLITpGE0qmYuf0KO6xe5fctpZwWdVubSaxF_y

sprite $DuolingoMd [16x16/16z] {
ZSU50GH120J1EPTbwFoZFNlthnLe_M7EIb97Sye61p0dfnxi32AE7gPgA6fXd1IgIm7AGBf51WG4sAU92X1Xp0nKKiDLwW1kQG2T68viJzaesKtRjjkMrXI9
r8DQhrO
}

sprite $DuolingoLg [20x20/16z] {
fSZLOKK12C3GN3SW-szRdd_M3Wx_DAZdm9nQFEaUjlrIdap3Cenme8rWCA05G_HlBYrFSj1pApBKrLPAkgjfmnRgLVdSJXRRwH7crRC1Gtdt71TtXn-ygCVf
eYOlf_t4Dl0mZ8GF2nDtqUjiAqX7xdBdfLP-xWi
}

!procedure Duolingo($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/D/Duolingo', $name, $tech, $desc)
!endprocedure
