' definition of the Item simpleicons-7/A/Abstract

sprite $AbstractXs [10x10/16z] FSR50S0W0C30rBtPVreSxdN0yVkjWCq-vg5a-flwcfOZUL_UUQUjQM0QTkmz4G

sprite $AbstractSm [12x12/16z] HSR50S0W0C30r9tilsrnxdL4Tp2S93RWW48owwrViiG75N2DJrraIm-AFgIVkh3pfgDUq-jvf7S1Hdy

sprite $AbstractMd [16x16/16z] NSx50SCm40NHRmR1zDzjj13otDuAPPqDUjda7Nnxq0RyrStAPk04biZTi6e5t9v6FtOetCqRb7GnJp2bT-3sFuS5qEQfmdou_xhrFz2e_ww-

sprite $AbstractLg [20x20/16z] {
RSY5ZGCn04N1RsQ__gkzIwn5AoCUBQbDO1IlG-5Xkc-nYL9XPmIxkauN2v1-NEEXhsEoIEh77Rg-_Eka1j9sG54vRboNLOyh04QP9d6S1vZwoXmdbc1iXs4J
C3JP9Jbsak9UNwPo6KdIFm
}

!procedure Abstract($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Abstract', $name, $tech, $desc)
!endprocedure
