' definition of the Item simpleicons-7/A/Adobefonts

sprite $AdobefontsXs [10x10/16z] Os1WXW061dvKmCWCPN32HBWGQf0KOmXneoi1

sprite $AdobefontsSm [12x12/16z] Os1WOeO0HWO6VWJWWzAy22569ZWJIIKt0nS_Dd4sFcp2lAmi40OFFrPT_

sprite $AdobefontsMd [16x16/16z] VOl50G0X40E3E_HVxRcWEwye0F713rSQd2ahj6uiIdELl6ajJEpc3QRpy8MQvyOdyFmrL_1tlBJ0jdO7

sprite $AdobefontsLg [20x20/16z] ZO-r0S0m30GlpFdzjtLfjdIbu06ObnI0JIMWcbTZ9fPon7DJZ2vKmLnERgWpdBHCwnb7OrQFTi_hnurAdYTh99VT3MzLA

!procedure Adobefonts($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Adobefonts', $name, $tech, $desc)
!endprocedure
