@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsEventbridge element
include('elements/aws/ApplicationIntegration/AwsEventbridge')
AwsEventbridge('element', 'Eventbridge', 'an optional tech field')
@enduml
