@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the GCP style
include('styles/gcp')

' loads the AwsSaasEventBusResourceIcon64Squid card
include('elements/aws/ApplicationIntegration/AwsSaasEventBusResourceIcon64Squid')
AwsSaasEventBusResourceIcon64SquidCard('card', 'an optional functional name', 'Molestiae praesentium aut natus dolorem. Aut consequatur fugiat a consequatur ut.')
@enduml
