' definition of the Item aws-q2-2022/Architecture/MachineLearning/AmazonComprehend

sprite $AmazonComprehendXs [10x10/16z] BSRR5OCm50Emsm9-PVzzSKxGbrGimFvwXbtRq3nTx6lcLXUNW6vtT2kdFsdbsj2jbEi5

sprite $AmazonComprehendSm [12x12/16z] HSe74W0X349HAqAy_tsNk8rfxq_2tF80I7z8fTPomcvY6oViQPrBgC6lXRIZoMDjJ8SzoScqWvYBstRCMicz8or0zXFU1G

sprite $AmazonComprehendMd [16x16/16z] {
LSq70iCm30B06ciWvV__BP4xoJoyECb9A5K_pRXkVMQ8hlgH9xTJCs1n2irFmFO6noq7tJt8SLVEdZA_LcEEbzTQM3HoaTsT03J18u_rbBBTaxnkJv5Q8r_D
StB1IbOngOdyNpm1
}

sprite $AmazonComprehendLg [20x20/16z] {
PSvP0e0W28HXHCJ1xd_VMDhx7xzI1qUpqiZiZ_R7CEsHtkZM4RKRm_Bu43anJNM0YCQ1AmoL06NBnAYJ5uQo9LPJtNJYj0eWPKNPOkR9R2qc0MNBCdAJ2QGD
pusL93pDiwWrXhTjOOangHqs-nbqbhbMESVijiGghVJ67G
}

!procedure AmazonComprehend($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Architecture/MachineLearning/AmazonComprehend', $name, $tech, $desc)
!endprocedure

!procedure AmazonComprehendCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonComprehendLg>', 'MachineLearning', $funcName, $content)
!endprocedure

!procedure AmazonComprehendGroup($id, $name='Amazon Comprehend', $tech='')
  IconGroupElement($id, 'MachineLearningFamily', '<$AmazonComprehendLg>', $name, $tech)
!endprocedure
