' definition of the Item simpleicons-8/E/Esri

sprite $EsriXs [10x10/16z] BOo50G0W20JVRd__QGtWwCIZJWZyhl_ayRr3uv8o52Rmq_UVbPVLKjPu1MtdkuxvV9lqykeDlSC5

sprite $EsriSm [12x12/16z] BOO70e103CAYtkxW_wzrfmN2Wpa_4uErFxeT9lag2IcDjxiXUS5rKwTsikbXf1yL-kDCMRtL7mUzisiR22c2gQs2eSDX1a2Me1U32m

sprite $EsriMd [16x16/16z] {
HSZ5eKKn481GhiHdGl_LVdbwTi33dS5N7CJLTkDfF1umAi0yrHnnwnWGQ08zTVU3eYwu_7TvfLAPFirr1LZmwTp7NeMW-S12O7A6QZyl3ZK5jfOWy1-WSIu6
jthaemkmGSbrZ7rK7cCwILYTX-9A3Zs0Nm
}

sprite $EsriLg [20x20/16z] {
JSm5WWKW24NHQnVozh_R6NuVMuANwPRurNPgOwpJu4q94C1sdWnANbdjVq-t00Y5ZjFZag3sBQa0QSLN5bZSBe0ht3A9_5O1lQ2nf0P7Ho_R346LWzwcewh6
XF7-AiOIm8PS5DOSO_ZLoOgsiUiQ6prq8AwiWzwDtdyxKGudljA5Q8W3zkp3abKf6y4w9bc-qCSg4BQp18YinDlMyZBT1-4F
}

!procedure Esri($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/E/Esri', $name, $tech, $desc)
!endprocedure
