' definition of the Item aws-q1-2022/Resource/Database/AmazonAuroraMySqlInstance

sprite $AmazonAuroraMySqlInstanceXs [10x10/16z] HOg30G114CHoLlflzutbYB_IymKDTCXG76sHyvjvaJ0-51-KyekqOJwgpE4E

sprite $AmazonAuroraMySqlInstanceSm [12x12/16z] JSY54SD04CLGBHp-wx_Tn6nhw8tujkpAE-P0Cm-4vOYcEUfkWAJPRUYQUNa2w-DvMqFVB_ooCUdQGrhy0G

sprite $AmazonAuroraMySqlInstanceMd [16x16/16z] TSc53GGm4CH0Xuus_RVxp63Xo7pMzT86yPeZDeisyMQGYCeraH4t9wjQaLIx69ZSkXb0Yb9xEe2cfxjLl7e1l7X6vlZ_MQ6SOdChWUdWUMaoRC8H

sprite $AmazonAuroraMySqlInstanceLg [20x20/16z] {
ROs50O1030FJl9Pc_tbn_yDZO4WFFPbiaHBU20WSsF7CN3MPpFfIQQYdLbqzB4ZUMe7CKxDmU3wqXMHOgFVUJIhvexcJRC9Jq-xmfRMGlFAVurlRzzxQzbyE
kksjXHOMRVhc4c7A1wbeQgxDuO41iFKs0m
}

!procedure AmazonAuroraMySqlInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/Database/AmazonAuroraMySqlInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonAuroraMySqlInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonAuroraMySqlInstanceLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonAuroraMySqlInstanceGroup($id, $name='Amazon Aurora My Sql Instance', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonAuroraMySqlInstanceLg>', $name, $tech)
!endprocedure
