' definition of the Item simpleicons-5/Z/Zelle

sprite $ZelleXs [10x10/16z] uwS3

sprite $ZelleSm [12x12/16z] unza

sprite $ZelleMd [16x16/16z] un_X

sprite $ZelleLg [20x20/16z] unzKO1G

!procedure Zelle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/Z/Zelle', $name, $tech)
!endprocedure
