' definition of the Item simpleicons-5/Z/Zoho

sprite $ZohoXs [10x10/16z] Oo0ISF0py_0oy75nStFnSJ3nC_Fp0GLP-LaP6VZv2Ua5

sprite $ZohoSm [12x12/16z] dS770O0m30D0ARtPtdzQEdo1t652mgbRfYQl6JatirA67w4C1ued4PY5U3Y73rO

sprite $ZohoMd [16x16/16z] jS470G8m40ImQ_jx-dSB8Y31dntlX0u1O7mPQr0ULRRageezRTZpJhTHp8rTFNE0T8qDlEk02xX5vIr-x0C

sprite $ZohoLg [20x20/16z] pS7N0G9H20J09SCxZ-s_MiEN9UWC_eiP-X9yDKd3e-v5Bm-kjqaxdgLIaLTCxkmvtEdMfPlHja4S9xWfl0FfoZP6emD4Y1I6pKBZ81KV3bGeV6eIF_82

!procedure Zoho($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/Z/Zoho', $name, $tech)
!endprocedure
