' definition of the Item simpleicons-8/D/Datadotai

sprite $DatadotaiXs [10x10/16z] 5SI50KGn0CBGzxLUzf_s1980W3N6Fc0wRZ0uGKl2yMzWKOXO6kIY0na3OC8N

sprite $DatadotaiSm [12x12/16z] NOi54i0W40DJz_B_tx9pEqfQ89e13TpIFurpIKauf_Il-zmRY9iGBJNRxMqCD6xODSzHR9cnnTEA2ca7

sprite $DatadotaiMd [16x16/16z] RSi56iCW04FXXyr9xd_QQMPjW_xXWwsK_IDVJWFoXs04-f1YI94j1IwbL04gfRHNtm7o3G6AdOS9z91weSDyCSL4BwOGuqjeLfXKivqR

sprite $DatadotaiLg [20x20/16z] {
VOw5OGD130Jt-L3RVxSHnMpFuuqGtrc2HpNP5U63R7KZi0ku_gjHjPYg02AerTubZf7PcxrNGKhBShM9wl_CIaTy8GQOUrGONZAFx3hyv7yN5D7VjMNoEE5m
yVCoOzL05hlRWXugCxS2vghtJ55JyGIbIySBPCCR0x_u0m
}

!procedure Datadotai($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/D/Datadotai', $name, $tech, $desc)
!endprocedure
