' definition of the Item simpleicons-8/D/Dazn

sprite $DaznXs [10x10/16z] uqS01XW0ie0yVWYBXn_8WOb11K40mcU2o48GCqmTb0K3

sprite $DaznSm [12x12/16z] JKs30G0m3ClivVzlPwDjn7_XBj5h6tlXLvr05BwQQTG2YH4M6H5Fp5xwGX0IijUzG0roQat_2rVziiHTgW4

sprite $DaznMd [16x16/16z] PSwr0GH1581GriRdqt-rvtvaByFVjkMpSE6pcxi2ffUN8rX6lBt9N7oxTWmJH1DgT1WmMCJCEviTkWwahQ0BW61S7JT70kTu-d1T49_EhLKQPO7___ZACm

sprite $DaznLg [20x20/16z] {
TSpLeSKm3C1G9Iw3jV-q3ouMzNaCNhMEntJasDDAAG2KZSqge5jRCC1fELgrUhJPrNBu9pW1DWvG8me4b02JHTWMDW-QChEo3cI5uVcFsbj8iG8lmnuonwsv
0XbkhBMf_xRTczNuCpQswSwk-WK
}

!procedure Dazn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/D/Dazn', $name, $tech, $desc)
!endprocedure
