' definition of the Item simpleicons-8/B/Bastyon

sprite $BastyonXs [10x10/16z] JOg30G0n54FV6KNsdxRMPuG5ZhJxgrua24YE30eaWmAFZePsQirbU4hldd6f2

sprite $BastyonSm [12x12/16z] HSQ50OH000F1u70s_LVxBj7DakGzcNrqaevjBgWPIfvY3NcBs3uyBEOFDr4-JFXpvuk1qM34EOE9Em

sprite $BastyonMd [16x16/16z] LSlL0GDG3090djMRst_QkjvV0YGjITh8tJQX3q_PglYNe7gIzJmdXpmzRYflx4F_t2SQ-HYCtxkJttiIrkSkWf_vJCFdb1pWDFego9wp7wbAzg2dcLS

sprite $BastyonLg [20x20/16z] {
POo5ZSLG0CFSFaRlF-t1Px0e2i7amXcu2HWEw5xO6RQX-Wtj9aQVDnNWqkH2Lbs0shcZUhtdmQ4Ul5cmj7rww3vrV7W6xPyUEZ-zpx-eawtvlPR8RyMg0gh7
YrLkdklsfLRGJzgfihopr4tmXADjTKPWR7u1
}

!procedure Bastyon($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/B/Bastyon', $name, $tech, $desc)
!endprocedure
