' definition of the Item simpleicons-8/B/Bmcsoftware

sprite $BmcsoftwareXs [10x10/16z] LOo50O104CE2Ezb_MlJrNDe24y7KE46OTw7vnycnCq5pT-Olfp-tSQhqRW

sprite $BmcsoftwareSm [12x12/16z] HOh50S1048I8U-Y_siZPyXe1k6bqQcHkvvP1krIICajYzLuyAUZUqeIccEuxvKvOYzFPAPJiGE85

sprite $BmcsoftwareMd [16x16/16z] JOxL0KD120Gvzvl-gqsUm_pWxCh13cAPWAqN6OQjHJeatR-UW7iQx3FptnSFyzpGhmEMxXyai2Li3-ZswN0-6u4cLxdLZrI8wizRmui5edJ8N_47

sprite $BmcsoftwareLg [20x20/16z] {
RP254KKn3CFy65ljF-s7Ckae5xRrnnvg0PW7EMoRqmfSJKwwWBN9II-OAURUa9m0HGpSBYYN7i2k1L313SJkAbd_wFwhVmICUu0pfwnxRCwv65buQXsdwovp
4t3K7hpmzlvDgZ2mg-0B
}

!procedure Bmcsoftware($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/B/Bmcsoftware', $name, $tech, $desc)
!endprocedure
