@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsPictureInPictureAlt element
include('elements/materials/Action/MaterialsPictureInPictureAlt')
MaterialsPictureInPictureAlt('element', 'Picture In Picture Alt', 'an optional tech field')
@enduml
