@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsShoppingCart element
include('elements/materials/Action/MaterialsShoppingCart')
MaterialsShoppingCart('element', 'Shopping Cart', 'an optional tech field')
@enduml
