@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsAspectRatio element
include('elements/materials/Action/MaterialsAspectRatio')
MaterialsAspectRatio('element', 'Aspect Ratio', 'an optional tech field')
@enduml
