@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsSettingsInputSvideo element
include('elements/materials/Action/MaterialsSettingsInputSvideo')
MaterialsSettingsInputSvideo('element', 'Settings Input Svideo', 'an optional tech field')
@enduml
