@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsAccountCircle element
include('elements/materials/Action/MaterialsAccountCircle')
MaterialsAccountCircle('element', 'Account Circle', 'an optional tech field')
@enduml
