@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsFingerprint element
include('elements/materials/Action/MaterialsFingerprint')
MaterialsFingerprint('element', 'Fingerprint', 'an optional tech field')
@enduml
