@startuml
sprite $MaterialsTimer3Lg [20x20/16z] {
jKv50e0026CqwF-_Q_VTNSW5_GBWk-6eilSM7Qo3lNVhJ-HAKC5ZNqva7PMu1PSU2n_EvvTw2r6MCZtWkPwo0plJiMeHbbSUTTyDpj9EQ6STPUT9xfavClME
GdzY1W
}

!function MaterialsTimer3($id, $name="Timer3", $tech="")
  CloudElement($id, 'materials/Image/MaterialsTimer3', $name, $tech)
!endfunction
!function MaterialsTimer3Card($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsTimer3Lg>', 'Timer3', $funcName, $content)
!endfunction
@enduml
