@startuml
sprite $MaterialsLooksTwoLg [20x20/16z] ZP053a0X34Cd9JZS_xJVNNcnPTvIEu83CgTIFP2c9Ee9RBbWhVMNt1YnFUSie8HphfPihxcWp6JEEKFC6gutR2wtkmhOFRT7zv_jPTyEdZsuUzLE3m

sprite $MaterialsLooksTwoMd [14x14/16z] NOw50G0n20C_fDu2-q_xxbV5C_s0d60pgfxKrHHrxwsljyfkAO5uMrOIr-Uql12FfG8MVoocOkykVEfwQ_t8_4p_Alko

!function MaterialsLooksTwo($id, $name="Looks Two", $tech="")
  CloudElement($id, 'materials/Image/MaterialsLooksTwo', $name, $tech)
!endfunction
!function MaterialsLooksTwoCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsLooksTwoMd>', 'Looks Two', $funcName, $content)
!endfunction
@enduml
