@startuml
sprite $MaterialsFilterFramesLg [20x20/16z] {
lSYr5SDG5C3G3uyXtd_RcBcsAfrRjW2sEoW27eJW1tOa8iVHVHpi8pLtDOCo1chgtaRBNaxrdAsLjZNkPZhyvWOzszh7nhh6XnrjXkqKJbObBqaj8xPB8xtr
1m
}

sprite $MaterialsFilterFramesMd [14x14/16z] bSSv0WCX30D0oTXMgl3_r-RWfjpf1eq7Dd_9qLXaYbHc6A1q9q3tr6z6QsXjNjy_rUUQnwCtR0iRuhUYfU3s1G

!procedure MaterialsFilterFrames($id, $name="Filter Frames", $tech="")
  CloudElement($id, 'materials/Image/MaterialsFilterFrames', $name, $tech)
!endprocedure
!procedure MaterialsFilterFramesCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsFilterFramesMd>', 'Filter Frames', $funcName, $content)
!endprocedure
@enduml
