@startuml
sprite $MaterialsCropSquareLg [20x20/16z] Ow0GiB310GjCY8yB3lYWWcnSJ8nGmCJ51XNZP8IPmiWv6CMu469SR72_SK81s6-OOK0X

sprite $MaterialsCropSquareMd [14x14/16z] Oy0B65dPm82L4SHZPMS10tPM48-D1QA6XOrwF8GDQBRZ1G

!procedure MaterialsCropSquare($id, $name="Crop Square", $tech="")
  CloudElement($id, 'materials/Image/MaterialsCropSquare', $name, $tech)
!endprocedure
!procedure MaterialsCropSquareCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCropSquareMd>', 'Crop Square', $funcName, $content)
!endprocedure
@enduml
