@startuml
sprite $MaterialsBrightness7Lg [20x20/16z] {
RL250S0m34ge-__NpdtK6mNa7Aho7Hg2_anZF8t6EnV7Cg9ptkmsl_vhpdMz_MvpYyL35NwnkjDMhGWWOkjXqxWa8BOM8Nv4tJjMoDv3KDVkAuYiQAkjGVCA
YTb8Bkb1i33CZ1lJW6h5DMNQpm
}

sprite $MaterialsBrightness7Md [14x14/16z] NOx50GCm30CZKpZQVzeokVSp2Ce3e7n1x-zH8phP8_G-1KypQuVnd0mYiCU4qU1xEzf0GQV98fSOE_AKFhykpiW9EVs_MMvz1G

!procedure MaterialsBrightness7($id, $name="Brightness7", $tech="")
  CloudElement($id, 'materials/Image/MaterialsBrightness7', $name, $tech)
!endprocedure
!procedure MaterialsBrightness7Card($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsBrightness7Md>', 'Brightness7', $funcName, $content)
!endprocedure
@enduml
