@startuml
sprite $MaterialsCrop32Lg [20x20/16z] Ow0CCBCX0MQ842yN9nS401cyO44M7YO6HYXWOE9X0OjnCoBCOUGUL68mDyC0oCqmly40n6-OOK0P

sprite $MaterialsCrop32Md [14x14/16z] Oy0BMDYWW0N8OU9aPG43Lauc88y3feY3UZnE5YZWP4Ar7Iy

!procedure MaterialsCrop32($id, $name="Crop32", $tech="")
  CloudElement($id, 'materials/Image/MaterialsCrop32', $name, $tech)
!endprocedure
!procedure MaterialsCrop32Card($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCrop32Md>', 'Crop32', $funcName, $content)
!endprocedure
@enduml
