@startuml
sprite $MaterialsMovieCreationLg [20x20/16z] nOXL0aGX3CH2v-5Gxd_QTVrTJNN2MoW6GZJO14enWFML81M8BI1t0_Cr3EiYj0XbdTtAfbfafScINznoz-jSt1D_TVtPTGCKdn1liGS

sprite $MaterialsMovieCreationMd [14x14/16z] fSVL0O0m34NHM_Tc_sbn-CDFz755EvHTsba8Ol66e8bXJicuQ7pKVadI-zAofDsVfDr1SsK4

!procedure MaterialsMovieCreation($id, $name="Movie Creation", $tech="")
  CloudElement($id, 'materials/Image/MaterialsMovieCreation', $name, $tech)
!endprocedure
!procedure MaterialsMovieCreationCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsMovieCreationMd>', 'Movie Creation', $funcName, $content)
!endprocedure
@enduml
