@startuml
sprite $MaterialsCompareLg [20x20/16z] {
jT0t5e0m30JHNMTRUjRzJqlEq3BbBmTR95x5YcikJ9K6XYctajfSWnCHrGM3RGQINiFTfYZ_MSuDvCqgOuFBl9WufCbwEaqzLkl1xPO8BcQQTBDMQzN5h5ku
FvZCr7s_-dxwVZy2
}

sprite $MaterialsCompareMd [14x14/16z] ZKw35SH041rpqN-rP-Ofoz47F1R3Uo4H9zvUl2SvvqpKYBobDFVUUIy7_MHm8XiMIEzi2GKwlp83l6NDZwnLDD5t5JtLrosxMpWu-tTz1G

!procedure MaterialsCompare($id, $name="Compare", $tech="")
  CloudElement($id, 'materials/Image/MaterialsCompare', $name, $tech)
!endprocedure
!procedure MaterialsCompareCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCompareMd>', 'Compare', $funcName, $content)
!endprocedure
@enduml
