@startuml
sprite $MaterialsFilterLg [20x20/16z] {
hT2r5SD0301GqHCdj_-q0JEq_js14FwGTWWJpZxGwSvITbOutHdif16DxtSjpzpXvUvtPiVJ7GTH3ZtU_SuHOxpbU2SptkxyNbVRRPCvtP7Q0SF_xWhBv82d
IwtUlMpvITVDVm4
}

sprite $MaterialsFilterMd [14x14/16z] XSwt0SD03CNGpqmwxJ-kfSkTNeSE05W7mIN3cwWhAGcTgzXPwiz5kefIuYUpn2z6lPYwk0fUEV1Le06G2kyC5pcV_m

!function MaterialsFilter($id, $name="Filter", $tech="")
  CloudElement($id, 'materials/Image/MaterialsFilter', $name, $tech)
!endfunction
!function MaterialsFilterCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsFilterMd>', 'Filter', $funcName, $content)
!endfunction
@enduml
