' definition of the Item simpleicons-7/E/Expertsexchange

sprite $ExpertsexchangeXs [10x10/16z] Oq00Vdv-20abm5nkVdus1dOaUGGJay4FLCZ2py_Bm0Wp14m2

sprite $ExpertsexchangeSm [12x12/16z] JOp50S0W54EXbpfl_scnxov9IZRWaaQfm9ftVNUxEJPgBuzJT5f_I58rnc_Me3Pk1IjEmGym

sprite $ExpertsexchangeMd [16x16/16z] NOs50G0X30FpkBF_jez3UsWj0QSsmlbLs7v_BKmZ1F9wOtlaxUjlHEVhSUe93AQ4mk9ANFR43M_zEdypD4jErciNvzGPlffbXT3z8ss_nPNz0G

sprite $ExpertsexchangeLg [20x20/16z] {
VP030iD0402FCVx_scBEd3R9MgA3UV_SNdj177nMJ0-oZBuV6zAI4e9qaQ7V82jySCQS5HFS6DK_Hq1PCg7JbBF0r2LXCPs3pAirXSNz5OnVM9NNaaXHU4GI
oybsvCtkVwpmHlW2
}

!procedure Expertsexchange($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/E/Expertsexchange', $name, $tech, $desc)
!endprocedure
