@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2023/bootstrap')

' loads the Item which embeds the element AmazonRoute53RouteTable
include('aws-q1-2023/Resource/NetworkingAndContentDelivery/AmazonRoute53RouteTable')

' renders the element
AmazonRoute53RouteTable('AmazonRoute53RouteTable', 'Amazon Route53 Route Table', 'an optional tech label', 'an optional description')
@enduml