@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../"

' loads the library
!include ../../library.puml

' loads the style
include('styles/aws')

' loads the AwsGroupEc2InstanceContents group
include('groups/aws/AwsGroupEc2InstanceContents')
AwsGroupEc2InstanceContents('element', 'EC2 Instance Contents', 'an optional tech field')
@enduml
