@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../"

' loads the library
!include ../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsGroupEcsContainer group
include('groups/aws/AwsGroupEcsContainer')
AwsGroupEcsContainer('element', 'ECS Container', 'an optional tech field')
@enduml
