' definition of the Item aws-20210730/Resource/Database/AmazonAuroraInstance

sprite $AmazonAuroraInstanceXs [10x10/16z] HKg30G113Ckvsd_TPuq8LSE_FNCO1-YkV4YsEFBGT5JQt87C6DQVMdlQ3G

sprite $AmazonAuroraInstanceSm [12x12/16z] LSh50KC1309Guhh_klL-UPS8u6hvhq0LuS86D8XOXC6VlSmZ1D-_Ya4uJK5uIm1px2xztpTdRnt-xgJIg7x3pl0J

sprite $AmazonAuroraInstanceMd [16x16/16z] VOc5SGD04CJqTBJVVxk9cMqTQfPNkXxO82Pt0k5kexLm0A7MUX_7lZWEGEEQbvibSNKkB6qLDsy6K7TtIQa71zg3MrRQprornEP20ICWTCAmoiu_

sprite $AmazonAuroraInstanceLg [20x20/16z] {
ROs55GGn20LnWlJVxjswJtpWvSCde_fAogGOxZH2WOemAfEop8vjSgFTDGJKVNOqEsOY4YOXEXp1mU4it4Qe-SLvXcagnCKTICKO5N1rlLRivYeZEkxkuxyE
PR5-z8aRFlfmtksHqHDXaCyCDf1csj0sbfmhQ1iA8AO4y0S
}

!procedure AmazonAuroraInstance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/Database/AmazonAuroraInstance', $name, $tech)
!endprocedure

!procedure AmazonAuroraInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonAuroraInstanceMd>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonAuroraInstanceGroup($id, $name='Amazon Aurora Instance', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonAuroraInstanceMd>', $name, $tech)
!endprocedure
