@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-20210730/bootstrap')

' loads the Item which embeds the element AmazonAuroraAmazonAuroraInstanceAlternate
include('aws-20210730/Resource/Database/AmazonAuroraAmazonAuroraInstanceAlternate')

' renders the element
AmazonAuroraAmazonAuroraInstanceAlternate('AmazonAuroraAmazonAuroraInstanceAlternate', 'Amazon Aurora Amazon Aurora Instance Alternate', 'an optional tech label')
@enduml