' definition of the Item simpleicons-5/L/Latex

sprite $LatexXs [10x10/16z] uwS3

sprite $LatexSm [12x12/16z] unza

sprite $LatexMd [16x16/16z] un_X

sprite $LatexLg [20x20/16z] unzKO1G

!procedure Latex($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/L/Latex', $name, $tech)
!endprocedure
