' definition of the Item simpleicons-5/L/Leanpub

sprite $LeanpubXs [10x10/16z] uwS3

sprite $LeanpubSm [12x12/16z] unza

sprite $LeanpubMd [16x16/16z] un_X

sprite $LeanpubLg [20x20/16z] unzKO1G

!procedure Leanpub($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/L/Leanpub', $name, $tech)
!endprocedure
