' definition of the Item simpleicons-5/L/Less

sprite $LessXs [10x10/16z] uwS3

sprite $LessSm [12x12/16z] unza

sprite $LessMd [16x16/16z] un_X

sprite $LessLg [20x20/16z] unzKO1G

!procedure Less($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/L/Less', $name, $tech)
!endprocedure
