' definition of the Item simpleicons-5/L/Lineageos

sprite $LineageosXs [10x10/16z] Oo086FcHs222Zu4V37dumIBS3AWAC04

sprite $LineageosSm [12x12/16z] dSQd0O1000Imq3kt_xOux9Uew94hVsrkU9tN7bc6C-B5xYOpTtREgF01

sprite $LineageosMd [16x16/16z] jSFL3SKm04Mn4-RS_QTzKFmlM3AlS5ETazNoC4Z29_vQeGgf6WMwwpOCcg6HdHEzkfX0pgGEqtPA0eZL0HJFJLy

sprite $LineageosLg [20x20/16z] nSUr0G9044N1Twwxl_zgSIU7oOO_2wR9kw5MXXAl1134YzLmTPohwf6fZEGi5UeEVHTv6uFX2UMXqvNPW0Am9gYmefO3KROqWNJ-by0l704

!procedure Lineageos($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/L/Lineageos', $name, $tech)
!endprocedure
