@startuml
sprite $GcpApiMonetizationLg [20x20/16z] {
TP054WGX40En9Fp_m-XKRizwbIROf4CEaYaq9LHcDunewm_QZUdfT89m6zollO0SQTjfBSENEQupDOKIrdN-h2fhvBfk5uLpHR_E1f1HrXLRt5zkbyFnxaLj
NI2uNV6U3VwTxRi6hfLZpvfguPf-rNu2
}

sprite $GcpApiMonetizationMd [14x14/16z] JSx50GGW44FH897-6yPN_ksX0w2qKm4sv9CEUrvzeJexEwu0BwY4QBxOyeMujUYpyRGtNTkAImtSBwoSwFl3hlx_pkza2tw3_gQU

!procedure GcpApiMonetization($id, $name="Api Monetization", $tech="")
  CloudElement($id, 'gcp/ApiManagement/GcpApiMonetization', $name, $tech)
!endprocedure
!procedure GcpApiMonetizationCard($id, $funcName="", $content="")
  CloudCard($id, '<$GcpApiMonetizationMd>', 'Api Monetization', $funcName, $content)
!endprocedure
@enduml
