' definition of the Item aws-q3-2022/Resource/ManagementGovernance/AwsSystemsManagerStateManager

sprite $AwsSystemsManagerStateManagerXs [10x10/16z] HOY30G0m30I_nkq_RutahN_nE4iTLKxtLYgHaw96yW9k2Yu2UIIvkxbzT

sprite $AwsSystemsManagerStateManagerSm [12x12/16z] JSR50SD000Cm7nlsdxSD9te9NocNEb3YpT2oKTOE7MqxRlVvFVStSjmVRHcYEBSlUrwVYN8mXc_u0m

sprite $AwsSystemsManagerStateManagerMd [16x16/16z] PSS50W0X24JHKQI6-vztk_SRyF2hU5SBSJGQ50PQNpEC2aY2pRTW3OR5U7GwIVRRswSHuGyRWFgR8PARssvZ1L4m1pSNOrdKF6frYf0YmrHaSU6HTi3ohcC6

sprite $AwsSystemsManagerStateManagerLg [20x20/16z] {
TSo7aGGm24DHONo0KV_z7h0v_KcQvu2lMVAvqsHuZK0YhabGDMCli7JIHSa0jSslYHZWClRMmwHxDJbcnZSp04nMRzRRzW-RuismHCjw9kbZwo_BZ3M9Y379
Dfue2uuHWBx-TymhzMvc2C2jpmLHhPS4-0S
}

!procedure AwsSystemsManagerStateManager($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Resource/ManagementGovernance/AwsSystemsManagerStateManager', $name, $tech, $desc)
!endprocedure

!procedure AwsSystemsManagerStateManagerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsSystemsManagerStateManagerLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsSystemsManagerStateManagerGroup($id, $name='Aws Systems Manager State Manager', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsSystemsManagerStateManagerLg>', $name, $tech)
!endprocedure
