@startuml
sprite $AzureEbooksLg [24x20/16z] {
fOe5SWGm4CDgBmJ-_-1kulQOJqCQMm3e6vuQUayZzjkQoonxdybbHiAzR2cOSmQui7M9ibZxgZIMokBGd-Q77XIoRthRFMJFUplj2LpqjOZB_cmNlDn_S7Ya
sjCy8ZASXPT4kEMSem_HMplec5sKRKRl0X2CKMiG4By
}

sprite $AzureEbooksMd [17x14/16z] bSp75SH020FGXoGczL_mhepppVz2Xcyp4G3O68uv9uoeG5Q3HEt1ZS2c0fyd-71Y4UvUFyBSgEpMa9Gfaif_r3oC8w6fpJMRQ3y

!procedure AzureEbooks($id, $name="Ebooks", $tech="")
  CloudElement($id, 'azure/IntuneServiceColor/AzureEbooks', $name, $tech)
!endprocedure
!procedure AzureEbooksCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureEbooksMd>', 'Ebooks', $funcName, $content)
!endprocedure
@enduml
