@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsKeyManagementService element
include('elements/aws/SecurityIdentityCompliance/AwsKeyManagementService')
AwsKeyManagementService('element', 'Key Management Service', 'an optional tech field')
@enduml
