' definition of the Item simpleicons-14/D/Delonghi

sprite $DelonghiXs [10x10/16z] Oo0MyF5302iNFmCpM8IVWO4J0WXe1G

sprite $DelonghiSm [12x12/16z] bS450G0n30F0P0m5_seVPw1tY68-2cZ3fp_6BiihM94QgwFO9vaXwWO

sprite $DelonghiMd [16x16/16z] jSG50S0m34JHN-R4lzen2LZV0RDv5rucvG6vTDqP7QQgWHmXHcDypzRhfPdj8F1X-TiA

sprite $DelonghiLg [20x20/16z] pS654G9H34315_ysfFzk6S4Ru7Qv4Wdz5i2jlqNEsIAnwBNdcfDfBMktWe4yjuQrdzpkkTCLTs-bc5-A0Ft1tzm1

!procedure Delonghi($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/D/Delonghi', $name, $tech, $desc)
!endprocedure
