' definition of the Item simpleicons-8/A/Aeromexico

sprite $AeromexicoXs [10x10/16z] LSh50S0m30J13NEk_sejUcaCGfhfF4bowxN3BtUTgXvvNOOr8G6tOzkWzXe3

sprite $AeromexicoSm [12x12/16z] VSe30e10443HdrttFsrhuos6T7pIVVbKWtcHuPqP1wxhbhcgtOBAZzTGER0gDX_6UPvnfec2

sprite $AeromexicoMd [16x16/16z] ZSVL0GCX50J0tJESrt-tmI5-ypUuuuYIwNuf3fpi7LAtNJ93yamtnjHBY0SEwRmaa9U7gXq9hs8SB2AST_NRaH3Jbc3XBF750m

sprite $AeromexicoLg [20x20/16z] {
bSe54e0m3031grje_lzQt1bZeNOJVZ8nb-ouqqFw94-HoCBeWm2-wwwNc0TLI2Ao9QfOKzZjRTjnPJEShMt7ZlrmksiE_6LlBFfcd-iiwauXXC3A6EiNbWTT
y2GYcTyc
}

!procedure Aeromexico($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/A/Aeromexico', $name, $tech, $desc)
!endprocedure
