' definition of the Item simpleicons-8/A/Applepay

sprite $ApplepayXs [10x10/16z] RS6t0O0000CWxDty_wrJDi6FRQYeu0f4zYoNHmmO4If5VG

sprite $ApplepaySm [12x12/16z] Oy0561607qaObSt52oGP6HYOW6n-86BbvELY1B9PkO3IlDpigEhv60W3

sprite $ApplepayMd [16x16/16z] bSp50S0m509GuXxsdxRktdVw2dwISO_Ok-epOZ5hJzgCQgeKhkyDAJADAYgMQMyoK9sAOf-NB_8h3kGUNhG

sprite $ApplepayLg [20x20/16z] hSwr0SGm0CLGcTb__scFCL0bhrGbJfQiMSfYRRSvC6RH0ZIdtpQbIaK-Zs2C1u6aZ1HeeWv0K2HHeT5fhuRXoKBQU0bxVvEjgANA0LS

!procedure Applepay($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/A/Applepay', $name, $tech, $desc)
!endprocedure
