@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-6/bootstrap')

' loads the Item which embeds the element ServiceAzureDatabaseMySqlServerCard
include('azure-6/Item/Databases/ServiceAzureDatabaseMySqlServer')

' renders the element
ServiceAzureDatabaseMySqlServerCard('ServiceAzureDatabaseMySqlServerCard', 'Service Azure Database My Sql Server Card', 'an optional description')
@enduml