' definition of the Item material-4/Hardware/CastForEducation

sprite $CastForEducationXs [10x10/16z] uwS3

sprite $CastForEducationSm [12x12/16z] unza

sprite $CastForEducationMd [16x16/16z] un_X

sprite $CastForEducationLg [20x20/16z] unzKO1G

!procedure CastForEducation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Hardware/CastForEducation', $name, $tech)
!endprocedure
