' definition of the Item material-4/Hardware/DesktopWindows

sprite $DesktopWindowsXs [10x10/16z] uwS3

sprite $DesktopWindowsSm [12x12/16z] unza

sprite $DesktopWindowsMd [16x16/16z] un_X

sprite $DesktopWindowsLg [20x20/16z] unzKO1G

!procedure DesktopWindows($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Hardware/DesktopWindows', $name, $tech)
!endprocedure
