' definition of the Item material-4/Hardware/Laptop

sprite $LaptopXs [10x10/16z] Oy06-A60XO4VAi93WCK7rS7C3mS8um

sprite $LaptopSm [12x12/16z] Oy09UA20cu61busPcGK8c7cP67YPOVB4iNbueURmCm4n3F0m8m5aMm4

sprite $LaptopMd [16x16/16z] Oo0Py2C1RWO69duMPXO8O6RZ1_4HIfbfm6VaHmOCF3nyI5mU3438Dm

sprite $LaptopLg [20x20/16z] Ow0CiB0Y0sQG43yQO069SRCmWo4G04b-7f0O5uf90ol6W-8Fi1WVcZ-O6NXuU525-402c82I00K

!procedure Laptop($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Hardware/Laptop', $name, $tech, $desc)
!endprocedure
