' definition of the Item material-4/Hardware/PowerInput

sprite $PowerInputXs [10x10/16z] uwS3

sprite $PowerInputSm [12x12/16z] unza

sprite $PowerInputMd [16x16/16z] un_X

sprite $PowerInputLg [20x20/16z] unzKO1G

!procedure PowerInput($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Hardware/PowerInput', $name, $tech)
!endprocedure
