' definition of the Item material-4/Hardware/Scanner

sprite $ScannerXs [10x10/16z] Oy0A6E4iJdv-X30lFpUOuWC1a3W_681OFFoSG80iXW

sprite $ScannerSm [12x12/16z] Oo0AyFCn8pXCVFmyI78i_FnS89gJ3mpu-K7g8G321a8GG1TdOeO0L9i

sprite $ScannerMd [16x16/16z] bSl50S0m509GuXxsdxRktdVv2luJXv7LOaj6icXigKAcVKwJ34ENwuIK_SZ5C9UYQDJWE5_-8oy2NhK

sprite $ScannerLg [20x20/16z] hOo53S0m40F3oVF-qvOPHEs9B9Fx7-_l7fYsS3S7yjMDEBYKRhQCzksw3BR6IIRH3JEPF3kXxrvnWrfOFGOpM7ZSokJHoOlk4pq

!procedure Scanner($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Hardware/Scanner', $name, $tech)
!endprocedure
