' definition of the Item material-4/Hardware/VideogameAsset

sprite $VideogameAssetXs [10x10/16z] uwS3

sprite $VideogameAssetSm [12x12/16z] unza

sprite $VideogameAssetMd [16x16/16z] un_X

sprite $VideogameAssetLg [20x20/16z] unzKO1G

!procedure VideogameAsset($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Hardware/VideogameAsset', $name, $tech)
!endprocedure
