@startuml
sprite $AwsFargateLg [20x20/16z] {
PS-7ZSGW04HH7PFel-9Zi5TEd_mKoSwFSk7RBhtC1FWq5TZjCXmsxaOBa76Pn6unnDCe_yp4ON18xHcTvlq4mBLhsKnLu4vEhMWC91hTKvkP0Y0HW8kp6MFy
hJ6OjktuB-HSDZCNAhcis2wxyB8l_WC
}

sprite $AwsFargateMd [14x14/16z] FSp13KGX30DH2O_Dxx_YTT0gS-81oMtPHi-h6Bn2YLWP_5VCjOCz8fu8em89SFAzBGxAhKeTq76_VQKvHypwgcREgscr_04

!procedure AwsFargate($id, $name="Fargate", $tech="")
  CloudElement($id, 'aws/Compute/AwsFargate', $name, $tech)
!endprocedure
!procedure AwsFargateCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsFargateMd>', 'Fargate', $funcName, $content)
!endprocedure
@enduml
