@startuml
sprite $AwsLambdaLambdaFunctionLg [20x20/16z] {
RL050WCn22Es_pzv7AnpJXeYjTe29QBUYhObstnIZWYiTYWnTgQL7rJXGi6JPFyGysdXVaK6OnmFLeLKqXf13tLJ2bcEAphsCKep8l3JA4rsF6QFauLhT0Dk
uDcdsPxPPIC45w8Hzjiew7VswwjsnO7dmC_IysBCvpr-tscEzkVkxm
}

sprite $AwsLambdaLambdaFunctionMd [14x14/16z] LOxN0G9G20EJEzn_PONt9RsJ_AYgpID7Mdq9eoIuIJEDkRIk0wxXEL_pRlcPRhClOuoN4TWY1hjLkmuRPpJHSnbwy9WiQLkkyu_w2m

!procedure AwsLambdaLambdaFunction($id, $name="Lambda Lambda Function", $tech="")
  CloudElement($id, 'aws/Compute/AwsLambdaLambdaFunction', $name, $tech)
!endprocedure
!procedure AwsLambdaLambdaFunctionCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsLambdaLambdaFunctionMd>', 'Lambda Lambda Function', $funcName, $content)
!endprocedure
@enduml
