' definition of the Item simpleicons-8/S/Snowflake

sprite $SnowflakeXs [10x10/16z] JS710K00002X083RVrjVvMzFZ8xkL53QE7juA4DlkrvlG76Kmj6P2iw43m

sprite $SnowflakeSm [12x12/16z] NSQtSGD1000nlBTpst-r4faI4Vpe42PQlf-QLzw-Rp3VD8dZcclpPAgJqhdMx2wcar5cUviU9gfT1SFt7g1Dy0y

sprite $SnowflakeMd [16x16/16z] {
ROxLOKKn3CKKk1Imzf-sVSpwCnpW5qDmFETvdHCSeFCopr0o95LG0w10lSu52g4PI0aekXCQP4se7UYQBNliUbpTLb3OL8OTyW4zmt0520KDuAg_pde0QBds
BSxt_W-QO0NW7m
}

sprite $SnowflakeLg [20x20/16z] {
TO-5OSH03C0KE0RjFsqfL7eTccrUiZj1V-Yother09PRjun9353KVkYcUWTww7Ikd8nBbm2eZWMM7g1M82fL7G3dhSAkkcEpqTG6iAXpaopg1EXgXw8Bcshc
RYa0aDHb6H7e3j08r0v0UNhUET17vxYyMZrqoptl1gSErdlUM_U34Q5L3ju1
}

!procedure Snowflake($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/Snowflake', $name, $tech, $desc)
!endprocedure
