' definition of the Item simpleicons-8/S/Snowpack

sprite $SnowpackXs [10x10/16z] Oq05V306Bp-CnG-4K0O39vZ90HJY1xFu8G3EuETZueS1XA4

sprite $SnowpackSm [12x12/16z] VSR50S0m5CDGbRdQVzf2y9RtmQPbitONIpt-3MO12RmxrL2J1JepiBgje7e1

sprite $SnowpackMd [16x16/16z] ZOhL0S0W34IBExV_jBX_zI79oVSFWLi3yPG12c9B3lq1Pxj-OKfVf10Uj4i25AiosnDNfSM6p7ZoI1YD6_xexo43

sprite $SnowpackLg [20x20/16z] bSx5OSKm403HCVDE_zKcdytqJj8oToN1YhOi32fpcLRBe9Q43HEjGgACFhzc6WnBwBfE2pvghGbVnivHZAUDIXvAvtXm8Q1tAKjT6rpZedy

!procedure Snowpack($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/Snowpack', $name, $tech, $desc)
!endprocedure
