' definition of the Item simpleicons-8/S/System76

sprite $System76Xs [10x10/16z] DOlL0K0X30FlkKBstnPgzzF6c3mwC6JiZpq6PPk-LpCkVPz5rslvOPPXYsO6ugurbkjzOG

sprite $System76Sm [12x12/16z] HSQrWGG1002XkNMd_shVXOW-7RQ-0VyrKe2uQnY6vFKudfKCp1VCpm5jo0t5W1ZlUC4wMYjOF_JX1akz0m

sprite $System76Md [16x16/16z] {
HSg5WSCm50MmbnWA1kq_xK5HXezvgDCuyhOyvSbBgUjR8iplilE68qSUx1XeEn1PMcwMSt7S1R8znBt1g7V8TE-mIZ23G5OUFouPuoWxtJZ0BcLAihAzzVmf
85-7Xvq_lm
}

sprite $System76Lg [20x20/16z] {
NSc5TK0X5C3GO5-mxBzj2uVgXUSSxx0N-54y1Xn-oxp_LvDk1V17H2rG_84Bl1nAT7derEN1XaBJnxYlN8PRRJIdebOKtKiFRcjmetMNYhvdnrjELN5Ze5fG
3LarCUZxv08bWv6WEUXMKweAF9EkFrW2RW5-5BTMF_7jSHkHvGC
}

!procedure System76($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/S/System76', $name, $tech, $desc)
!endprocedure
