' definition of the Item gcp/Item/IdentitySecurity/Iam

sprite $IamXs [10x10/16z] LOk50G0X30Fpmf7z5yPTsgZkuxu2sFuB0gd0Xjw521FLJbI5g_rHGJ_DoW

sprite $IamSm [12x12/16z] PKk50O0m39k6_7ynTMJMHjjna6009ATfmEf638jNUBIhCBPaXk09cM9qA-i45OhHMZVPYANZEBe1

sprite $IamMd [16x16/16z] VSxL0S0W00DHzCZ-4rTnkGgylvXDjfD7yXak0hh3lkOkM7IN7U_ZP899lQDQlmiaNdl2UvO9sQciS_S_gMmEH7IpP15csGK

sprite $IamLg [20x20/16z] {
bSy53W0X34HHz7VkV-4rPDqcrhn0nVrD5dk8W2JI-eGvMfBMHn1yKR_QN5mP1miNxqZ9j5ekbekjS-DIMJS7b299rdTUpRkQPa6ivv8BpSzM9CuJLfcVW6H-
XQAhN6K4
}

!procedure Iam($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'gcp/Item/IdentitySecurity/Iam', $name, $tech)
!endprocedure

!procedure IamCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$IamLg>', 'IdentitySecurity', $funcName, $content)
!endprocedure

!procedure IamGroup($id, $name='Iam', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$IamLg>', $name, $tech)
!endprocedure
