' definition of the Item aws-q2-2022/Resource/MachineLearning/AmazonSageMakerCanvas

sprite $AmazonSageMakerCanvasXs [10x10/16z] PSd50S0040B1FI3QVxznpxmG_ehsq44g8HI7BOrho95whobBKkwtBtJm3

sprite $AmazonSageMakerCanvasSm [12x12/16z] JOk50G0n20Clhy3--zRjgaGukJHn9DHLvpxra9cLKtH1b-lVw5ZLZt_KoM--gOktTwqWojyNaG4

sprite $AmazonSageMakerCanvasMd [16x16/16z] RSx50S0m30D0XUNkls_3dFkPZTCd6mYeY2x7JO_LglPxaW5qjL-XyNrUkbOdAjRw5lUwVBx5L2Ns1chfLp0EFLOPj7dzkmaH

sprite $AmazonSageMakerCanvasLg [20x20/16z] {
RSk53S103CLGvnzd_ttBcDRY9vc_XiU44xBLQgFPssgeBMQXl1ZAM5uZPUqlNQ0rJFsmq6OP_CxsTp7EycxbnpZCUa-dTTjDNZXD-J3r3DplNYjVetPEwsEh
ShmA9Q5Fp
}

!procedure AmazonSageMakerCanvas($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/MachineLearning/AmazonSageMakerCanvas', $name, $tech)
!endprocedure

!procedure AmazonSageMakerCanvasCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSageMakerCanvasLg>', 'MachineLearning', $funcName, $content)
!endprocedure

!procedure AmazonSageMakerCanvasGroup($id, $name='Amazon Sage Maker Canvas', $tech='')
  IconGroupElement($id, 'MachineLearningFamily', '<$AmazonSageMakerCanvasLg>', $name, $tech)
!endprocedure
