' definition of the Item material-4/Av/_5KPlus

sprite $_5KPlusXs [10x10/16z] Oy0A-240XSN6mC_806QnC_83sOm8CQmw4

sprite $_5KPlusSm [12x12/16z] Oy09-6407vk1YP-HWPyLp6O4SdbP67X0R0YNbvy8StXGR0K

sprite $_5KPlusMd [16x16/16z] ZStL0SG020DG87VrDFjFMtT_VsZiNSbPrfULLj7LVAiPyQz_n5nN8EacOQhT_pJ8xJVl1zrA_QT_f4JnOrwkbLid5cudBG

sprite $_5KPlusLg [20x20/16z] fOw50KGn34B9TsbW_schvowl6WV_uRfagZvTuGzyVEvZHcqVVRMjPjj0-SdNavg1NSo_vflDa7sctM07txwk9T0DKd_JZzXUQFdL5wflTfxn3X-J

!procedure _5KPlus($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Av/_5KPlus', $name, $tech, $desc)
!endprocedure
