' definition of the Item material-4/Av/_8K

sprite $_8KXs [10x10/16z] Oy0A-240bGL4F8mm5WD234XYqu4

sprite $_8KSm [12x12/16z] Oy09-6407vk7Yu6VYG7APcJWP-25i7cPeEA4pU51iHK

sprite $_8KMd [16x16/16z] ZSrL0iHG24DH83FrDFjVRTtzFZrVs7ibvxAUbTQYCz-DA1H2FRa2GnQPPfjtDYsEidE6sM9_n6_pyetTkcB9xLGB

sprite $_8KLg [20x20/16z] fSW50eH034FHxEBG9lS_BUukVxGFttBDYrlJ8jyndXb9gTcJ6G9a-bdmcnkHwXT1S_irXdXXQYo7JTQyffzbu63pFfcrbZYd_8_RLG

!procedure _8K($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Av/_8K', $name, $tech)
!endprocedure
