' definition of the Item material-4/Av/FastRewind

sprite $FastRewindXs [10x10/16z] Oo08-A6OaP-VWHE86LZu-VbvWHWioG_68C0DLOS9

sprite $FastRewindSm [12x12/16z] ZOYt0S0m48HmQgp0_jCg3_3N741q3y2zC0kNAwWa5wiMDrELvp2Vipn4rW4

sprite $FastRewindMd [16x16/16z] hSb53i1034FHJ9cStF-sRN1Tyk99NwP_DfKsnaNZ8quHcDuGRVN859ZMD6ghsZOMgDMqmAocbZxT2G

sprite $FastRewindLg [20x20/16z] lSZ50SGm00CmXpdUVze31pPezHJUv241bsF2N-EjGfqZpnbILtWlKMS6xtbIzwzpi4E7T4wo3j0TTkfGT4VJmUaEWyTy0G

!procedure FastRewind($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Av/FastRewind', $name, $tech)
!endprocedure
