' definition of the Item material-4/Av/Note

sprite $NoteXs [10x10/16z] Oy06-C607SxYOeUn681CVYZWmShYWBAGZ0C

sprite $NoteSm [12x12/16z] Oy09UC207SJavGS3FdO4cm78WRCP-9Y0R1Z0pUP1OZCmmm2AhG

sprite $NoteMd [16x16/16z] Oo0PyCC0EvZB1EEoWWKGV6Oci0223sIo8_5Pc9XO-C5y1223puZ6P-3aGG0MWhu1

sprite $NoteLg [20x20/16z] Ow0CiB3200jCY1y9i6EASG85qSKOk822w68CG9KOOY2Lg68SGC370nT307g8SG75ED34A0jG

!procedure Note($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Av/Note', $name, $tech)
!endprocedure
