' definition of the Item material-4/Av/Radio

sprite $RadioXs [10x10/16z] uwS3

sprite $RadioSm [12x12/16z] unza

sprite $RadioMd [16x16/16z] un_X

sprite $RadioLg [20x20/16z] unzKO1G

!procedure Radio($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Av/Radio', $name, $tech)
!endprocedure
