' definition of the Item material-4/Av/RepeatOn

sprite $RepeatOnXs [10x10/16z] uwS3

sprite $RepeatOnSm [12x12/16z] unza

sprite $RepeatOnMd [16x16/16z] un_X

sprite $RepeatOnLg [20x20/16z] unzKO1G

!procedure RepeatOn($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Av/RepeatOn', $name, $tech)
!endprocedure
