' definition of the Item simpleicons-14/F/Foobar2000

sprite $Foobar2000Xs [10x10/16z] Oq06p1mC_10MFpyxFp-KnGzXyJBomuJ0Y172v8TguG8n882F7yQ2204

sprite $Foobar2000Sm [12x12/16z] HOk52S1G5CHIzsR_QIiFZX_ib8-EXZ3EqJTAiQdH5ZT5_yTRoPLHiBJT9_OpXoDVrlkMe5TaZYy

sprite $Foobar2000Md [16x16/16z] LSV50SGm0C0mbpdUVzg3XlKJnKGnNe0KGPXSoFGOrDp3AD_aYXtCuZSurO4zVOVW318vC0bd_kwZjvAfW-uKpY58jJ-UjFIW8z4N

sprite $Foobar2000Lg [20x20/16z] {
LSxL5SDG40FHCREd_sh3Eczp5tublWRUEYe1ferYS0MKGeLH1nfrMsuLOZCWD3P-UXj-hgdpu-2ivMvrXYt9lt87OCVNR0V7zn4wSzfpkHATGRFhYKfrEzoh
CrLtdqxoRrE9C9b59_44
}

!procedure Foobar2000($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Foobar2000', $name, $tech, $desc)
!endprocedure
