' definition of the Item simpleicons-14/F/Fossa

sprite $FossaXs [10x10/16z] Oo0IyFCpyJE083S_Fpy3cCN2mi30mi3AmC9CG2y

sprite $FossaSm [12x12/16z] fS470G0X00En-y66rhzRB30IBhWpz3LwvBC30LDoaK3n4teQkoO

sprite $FossaMd [16x16/16z] jS875GCn00KWRcT__svR4-5Xi_Cy_3kv8BJZ4vR3b0YVF5PHLhXdhFRDNhjXiny

sprite $FossaLg [20x20/16z] pS6B0KDG50Mmu7sBU_RVjcj8V5mIPt9uirK6jo14uK6B94AvScjPgisW-doii_Jpzbnfq1f7vsmkJX_o1m

!procedure Fossa($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Fossa', $name, $tech, $desc)
!endprocedure
