' definition of the Item simpleicons-5/S/Sap

sprite $SapXs [10x10/16z] Oy0B-160YO6HWO6PWHy8mO09A0iKO0MIC7MuJ04

sprite $SapSm [12x12/16z] ZSQr0O0040F0mvtiForMqI3talXXkiauPigHIJcNIvHMAOMXWu9SHGhaSbNLfV1c1m

sprite $SapMd [16x16/16z] fSE53SDG40KmtxyolVsdBRCuiMGpxV_armZIWcKox9qITleevNvh3GevnLsdu5Hwd3B6ia1Uobq_bMak

sprite $SapLg [20x20/16z] lSX5Wi9G00MmVAktx_wd7LTOGvRn1FkzBVTArbgdN7r9xtt-A56754BZlPpQdcWEqgGW0wlJW5eWoOG6y_PH0bePb1GViYzhZYJ7SHG-vDTtQJ-AHta5

!procedure Sap($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sap', $name, $tech)
!endprocedure
