' definition of the Item simpleicons-5/S/Saucelabs

sprite $SaucelabsXs [10x10/16z] 5S650S90002nmsbVil-qI59rUFR7FHrbRTuyiZd2SUSmvoJzcO-Z4i8HwN29LFTCwWi

sprite $SaucelabsSm [12x12/16z] 9Oi50WGn309PjvBv_sylzAOI0HG-Rlq1lopVRAy35a7QwhOABB95jlcSDjpGCGNCNM_33YUQShTezkkHZqi2bKzH2WLa-mC

sprite $SaucelabsMd [16x16/16z] {
JOu5WaKX3CIcx3Cqzx_jqlPRq32OWdFIJMycWPLKg2f_c9YfgfxU3mnfekKwnAQ86kci3UT4eSYvcPJGnBE2AN7ls4zc66LZTsXjYCoKmzBbwpMq3FBtqeAg
mQdDUBIwh9CgJvsbpJy
}

sprite $SaucelabsLg [20x20/16z] {
PT05RgKn0CHWX_P_sO3lVzisKFx4reY6gqxxFxvvlFYapWpTWFKcHuXrJ4F8-lycfcfueLhW-KhbSG4D9rLnU-6CPsK9PT5ghcTbtu9EwHgUUPcdoZ30fQNR
fNarrAJ5olQS98gETvsRUd8mN4ezIOQ5wC9DyQL0LKD1jNFIYWES9P669hQSqDbT_Xmz2iiR
}

!procedure Saucelabs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Saucelabs', $name, $tech)
!endprocedure
