' definition of the Item simpleicons-5/S/Sentry

sprite $SentryXs [10x10/16z] uwS3

sprite $SentrySm [12x12/16z] unza

sprite $SentryMd [16x16/16z] un_X

sprite $SentryLg [20x20/16z] unzKO1G

!procedure Sentry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sentry', $name, $tech)
!endprocedure
