' definition of the Item simpleicons-5/S/Sharp

sprite $SharpXs [10x10/16z] Om037XumnS_6mC-Fn69dOEBXP-C70NOWPWCIwEeWW1LCmiIu651P

sprite $SharpSm [12x12/16z] POg50S1030AXxkm_RT_zuW44jYVCNQ76dTiho-tQBCUpsdQ1oRE9AFjoxSvqocFtzu9jchDd5SVT

sprite $SharpMd [16x16/16z] XSp50GGn40D1cTcTVxJ7k5YlGUcZTxqaa0JdlV6ltiNAWozj0fEN2hnxPoG7rHltbnTXrHlb0I0RAdUEXmIy-vgi17E0-VqFeFE-jNjz1G

sprite $SharpLg [20x20/16z] {
fOu30aKn30IVaXJRplrF-srZodY72oIT3PEMpGESVG7-hMyAdNoBPm2E0S0v8u2pholx74TVY-auOze69ajt-XpyYMzPeWWu-e2J5XT7ZhvcNFd6OGlG6zJR
6GRbJv-PxSmr
}

!procedure Sharp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sharp', $name, $tech)
!endprocedure
