' definition of the Item simpleicons-5/S/Shikimori

sprite $ShikimoriXs [10x10/16z] Oq02pFnWmC303nU2Y73oGhbCd5pS435k80Qh0v8mjKpyO0ei0vQ286u

sprite $ShikimoriSm [12x12/16z] BOk5OSD05CNaOzR-qxP9pleCZyjpI_7IuV0bv26ePwJmUyfgpKz8ligwzIpyCLLnBf3M2O3WVD-Dk6zVH3DwN-YG3Fy

sprite $ShikimoriMd [16x16/16z] {
FSs5WS0m30GmbI5m-q_xK58OR3F0jp3cKs4RXhCd5-o7JnceryTZ7WUNwOtTpjA6wsOQkGm1sxo_2OklLia_IGzoogOj30hIfN494ZrSCfDecS2PfITH4XYo
qpAI13bWWCGl
}

sprite $ShikimoriLg [20x20/16z] {
RSo5OHmn503HsHNZz5zjOliOdbWVU3XuQCusbXU3Y-2J1B3J0KVAfVOnBud9phC6P7-jMUDv7j-QjRqEW3XrjS15zUJPkLllSq22SuondnhWtRu5y5T912VP
T4v_xva1H0K7Dmj82igDGD6JvxyQg1hGneNQLK4DSEb-q7J3RuXVbwDu04i7iEL9DVCV
}

!procedure Shikimori($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Shikimori', $name, $tech)
!endprocedure
