' definition of the Item simpleicons-5/S/Sinaweibo

sprite $SinaweiboXs [10x10/16z] uwS3

sprite $SinaweiboSm [12x12/16z] unza

sprite $SinaweiboMd [16x16/16z] un_X

sprite $SinaweiboLg [20x20/16z] unzKO1G

!procedure Sinaweibo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sinaweibo', $name, $tech)
!endprocedure
