' definition of the Item simpleicons-5/S/Singlestore

sprite $SinglestoreXs [10x10/16z] uwS3

sprite $SinglestoreSm [12x12/16z] unza

sprite $SinglestoreMd [16x16/16z] un_X

sprite $SinglestoreLg [20x20/16z] unzKO1G

!procedure Singlestore($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Singlestore', $name, $tech)
!endprocedure
