' definition of the Item simpleicons-5/S/Smugmug

sprite $SmugmugXs [10x10/16z] uwS3

sprite $SmugmugSm [12x12/16z] unza

sprite $SmugmugMd [16x16/16z] un_X

sprite $SmugmugLg [20x20/16z] unzKO1G

!procedure Smugmug($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Smugmug', $name, $tech)
!endprocedure
