' definition of the Item simpleicons-5/S/Sonarcloud

sprite $SonarcloudXs [10x10/16z] uwS3

sprite $SonarcloudSm [12x12/16z] unza

sprite $SonarcloudMd [16x16/16z] un_X

sprite $SonarcloudLg [20x20/16z] unzKO1G

!procedure Sonarcloud($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sonarcloud', $name, $tech)
!endprocedure
