' definition of the Item simpleicons-5/S/Sonarqube

sprite $SonarqubeXs [10x10/16z] HSX50S0m00J1RSFiNsqOvdC0X_v0PJw6OaXi1KaujRpNSkHt7fQd0G

sprite $SonarqubeSm [12x12/16z] JSd50G0X00InmPtjlzfp8T-mC82LmsJmiIk0eDmdHmV79LOwcPihY5V665vQ8fZ2f_CJlyaE

sprite $SonarqubeMd [16x16/16z] PS750SCm00GmXT6-_RVjfs49lZAXGbAdXgQER2qOzemCbRK1pEa8nI4BONVODqqnSTWdSySbX4iJKyDbRrKkRV4KJtlZOUayZ8CV

sprite $SonarqubeLg [20x20/16z] {
TSh5bKCn50KmVKQ_st-rmnYVQ2tFtSU0ymJhF80bXQ7WkYkv5YpP6UFBbcne3UNRL3MnXVdoOydEN5oJ7qETx3VbZnnaiVeh2_7V6FRTV-VTHw5c_-rbtFlO
owApdpf3qujUU0K
}

!procedure Sonarqube($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sonarqube', $name, $tech)
!endprocedure
