' definition of the Item simpleicons-5/S/Sparkfun

sprite $SparkfunXs [10x10/16z] Om01FYO62E3dPu2pU7Z036OW4opCpmjdWG4ddCK0Ow6R0QK1

sprite $SparkfunSm [12x12/16z] JKor0S104EA9A_jF6psZml7XdE2GK3X1uvjaqTdZvUsXixgFqmhMSRuvVwbnjZWqyl9WDm

sprite $SparkfunMd [16x16/16z] NSg53G0n049Hwbxsd_Qq_gEFW5RDM39aM5r9h2MIK1uZVZMur0RNph8vzQyhdqDpJnt6Rcmkc0v20DCUQqpOAYjk

sprite $SparkfunLg [20x20/16z] PSk53SLG5CFGF2vx_sa_GzDhyP6iR-NOixmLZfQC2b3bLM2MYY70fcs_pi_oNwJsmO_CR9BSOBzQ1OwDOB_cQ2XQZpOKBCcifYUOwPcRekLeLTuT

!procedure Sparkfun($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Sparkfun', $name, $tech)
!endprocedure
