' definition of the Item simpleicons-5/S/Spdx

sprite $SpdxXs [10x10/16z] uwS3

sprite $SpdxSm [12x12/16z] unza

sprite $SpdxMd [16x16/16z] un_X

sprite $SpdxLg [20x20/16z] unzKO1G

!procedure Spdx($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Spdx', $name, $tech)
!endprocedure
