' definition of the Item simpleicons-5/S/Spotify

sprite $SpotifyXs [10x10/16z] BSR50S103C0mbxdUVzgZH2_HNEvq3XUODgGxzNAuKM45TDDptcrmG3dDmvgf

sprite $SpotifySm [12x12/16z] 9SZ50SDG50Cmb_5zxJzjcyIw6BBxUAPKgqemdu69r9aFzGmckIR14siMPyBrizxd853tX5hP37t_

sprite $SpotifyMd [16x16/16z] JS-50S0W3031hrl2xpzjtGvtmgbDbuf7w6dWvAlyXuU0L3CYFTKejsfMMnsYg3a1cchsTTs5EdZeeMcUcnTV7MgbXTFY0RLuL2rgqli7fFyhWFWF3_KlcWq

sprite $SpotifyLg [20x20/16z] {
NS-50SGW04FHu4xst_Okr7drNmESocIFU8ay3NSblfGzITsJ123fE7lhWoSzrd7BQXdQZ4yvHQ_g9bds7qJodzcZXcL3rJaF2ju-u-fyp7J4GCdUkZYKrtjh
FZP4_TQlD33uSCUhiDnfx7kImZU7nVEnpPqS0V83
}

!procedure Spotify($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Spotify', $name, $tech)
!endprocedure
