' definition of the Item simpleicons-5/S/SpringCreators

sprite $SpringCreatorsXs [10x10/16z] FOk50O1030DnXzj_Mtf1NjfeupacPn3q0Hxya2axQwv1GaH-kP2_k-CyLTe2Dm

sprite $SpringCreatorsSm [12x12/16z] FSY50S0W3031hnlm-szR_EAX2WzJqCHqjUD-IZy5p4AP3xZo-49vb1a5TmXku9SaK_TI5AVPMfRIbShnvGS

sprite $SpringCreatorsMd [16x16/16z] {
JO-50KCX50FxSR_zjorFAdYImrvUrWo-SWtaFntRWUx2BOYwQCF80dTy04zKBrO2qbrk7Z7lJLMZ8xepD3hEFmBekeCU3rMEsV285f-p_nuO3bBi1wV9kC6o
uh2d_ZvuJBq1
}

sprite $SpringCreatorsLg [20x20/16z] {
PP350O104CI0Sqt_rQA3vxEkmqLjVlXIWJRzVM0-cMC2xF05K3pcg4OUd2JGNec8FRNAj_LjIaY7E1O8q9zvUHDjprTwLQjjZjFSKPj6kFUpG3Mxk8-R4Azx
C_3yIpzo2rHvHY1Rumem3gAn8vSmbOrokHO
}

!procedure SpringCreators($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/SpringCreators', $name, $tech)
!endprocedure
