' definition of the Item simpleicons-5/S/Statamic

sprite $StatamicXs [10x10/16z] uwS3

sprite $StatamicSm [12x12/16z] unza

sprite $StatamicMd [16x16/16z] un_X

sprite $StatamicLg [20x20/16z] unzKO1G

!procedure Statamic($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Statamic', $name, $tech)
!endprocedure
