' definition of the Item simpleicons-5/S/Swift

sprite $SwiftXs [10x10/16z] Oy06MC0aFuHWGp3vWGGRcCdFpymFv46OG1O_Z0aa8G0c0ZGB

sprite $SwiftSm [12x12/16z] PSY55GGX40FGu4xwx_PUuDR_-01VSO-WvgjwnHfqwXD3Eo6qr6uW90DPi50g_7auMCxQkUYtJK8oXmNm0m

sprite $SwiftMd [16x16/16z] TOe50iCW0CHILxZ_ltQM-TQqm1c7Z7mHduP1iKJViIlYEonEILgkh9LqDr-vKT9VjqcGcYID7WDfMgJeeVRlYvkeswOpM5K2q1Jr01lID8tY3

sprite $SwiftLg [20x20/16z] {
dSq54iCm40J1DOld_wyDteQBqkQnIgT_L3tDyPnOTRDAYmB4IvQo_-F8ehPxONPCeaJ3CnY2QBky3ncsMqDXvwejReucsOPfsXmNt7ImHcnkryYefO9bIIl1
T5N0yb4z-E3cjlMk7yu
}

!procedure Swift($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Swift', $name, $tech)
!endprocedure
