' definition of the Item simpleicons-5/S/Synology

sprite $SynologyXs [10x10/16z] Oo0ICFF3M1pShApy_DniZ8n0KP009ni1lG

sprite $SynologySm [12x12/16z] Ow00SB0oC332s4pSh8pi_5mip0mS30nS44569fBD1

sprite $SynologyMd [16x16/16z] jOS50SC030GldB5_jIk3WFRvkHkrjYtLxhnV_XKlpOndZo_qnozu6M-XU8CbdcGgPnZNOm

sprite $SynologyLg [20x20/16z] pSZL0SCm30JGios6QlzfozaXx-S0zxIkSXvpLRykAYvKjeUwopwM44CAC_jWF25dhOMLZbb7ABSfBJC4tlBWuYgDMta1

!procedure Synology($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/S/Synology', $name, $tech)
!endprocedure
