' definition of the Item aws-q1-2022/Resource/ManagementGovernance/AwsOpsWorksLayers

sprite $AwsOpsWorksLayersXs [10x10/16z] Oy04p5XPR320f98R1h3gO8O2LW

sprite $AwsOpsWorksLayersSm [12x12/16z] Oq06p4mmmCN021V5mqO057FO4O0eSxZWW1i

sprite $AwsOpsWorksLayersMd [16x16/16z] Oq07t5meW84BHPPaFffvd0o402CA0Bg71HbGxXvE5C06

sprite $AwsOpsWorksLayersLg [20x20/16z] Oy06kBZH0Gi3DxeYPbRgYp6Z0LPM1XOsTC38G0dWnW2i0-StLdJ02

!procedure AwsOpsWorksLayers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/ManagementGovernance/AwsOpsWorksLayers', $name, $tech)
!endprocedure

!procedure AwsOpsWorksLayersCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsOpsWorksLayersLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsOpsWorksLayersGroup($id, $name='Aws Ops Works Layers', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsOpsWorksLayersLg>', $name, $tech)
!endprocedure
