' definition of the Item aws-q1-2022/Resource/ManagementGovernance/AwsTrustedAdvisorChecklistCost

sprite $AwsTrustedAdvisorChecklistCostXs [10x10/16z] NKW50W0X389TAlz_hzqRZUEKnKH9-qQ_RaQVpU4ZaAAboqjcjGyjVeW

sprite $AwsTrustedAdvisorChecklistCostSm [12x12/16z] JSj50G0m30F0ZCc_tb7nFiN0I_7fluyXNUtteU3Y7jtwXLfhudrveVcp7Qk4Zl7trzs-eJv_ky36ltr_Um

sprite $AwsTrustedAdvisorChecklistCostMd [16x16/16z] NSV5WGH1400WsgNoZ_TaPOmVdc9_L60p8NqVMvjp7fV1UUFslPJMsd75uNKDkQHuVurKkxA8rrE31F7wIu2Wlmd8qo58YrFaMvdu1G

sprite $AwsTrustedAdvisorChecklistCostLg [20x20/16z] {
RSm52aGn38JXYLMI-zztjmAlzc5X-0bUF3wOsa7pNBQKpeqZGF5dIwVVkHnoRzdEZSBlVuo6qz_opm0aPZAV6r5LY2HnWvNPHGLoJjJgKGO8JJ8qlGoUV8uE
M9fGnkYAHIzpnggLEU7Wdd7fltu
}

!procedure AwsTrustedAdvisorChecklistCost($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/ManagementGovernance/AwsTrustedAdvisorChecklistCost', $name, $tech)
!endprocedure

!procedure AwsTrustedAdvisorChecklistCostCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsTrustedAdvisorChecklistCostLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsTrustedAdvisorChecklistCostGroup($id, $name='Aws Trusted Advisor Checklist Cost', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsTrustedAdvisorChecklistCostLg>', $name, $tech)
!endprocedure
