' definition of the Item gcp/Item/AgentAssist

sprite $AgentAssistXs [10x10/16z] Oq05730Q2DWX30OWP8KASK1PZ70MEn2omdImmJIZ6We

sprite $AgentAssistSm [12x12/16z] PSQr0S10402WUsV_XUCUAkAdtKFPbkWDwuiszFC9xNmevtkMzyS0FJO5SKXAVCq

sprite $AgentAssistMd [16x16/16z] TSZ50GLG2C0mU0BPV-7lBhsbyQTyqw2V9nli6oVsBkJ5HRQQp9khC9xUrNfvkalifskKoAVH4OoujC65js35CofUa_6d8m

sprite $AgentAssistLg [20x20/16z] bP250S0m3CF2zlyFZvcdiigHlnJzO98Ti8rHJc2phICosQ6J8ra2Hj_9rVM55JldxB6TimGhzouKpEEwtXtM4IImSSM1Y2Bjz8_QHw03Tef1Pmukv8Z92oq

!procedure AgentAssist($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/AgentAssist', $name, $tech, $desc)
!endprocedure

!procedure AgentAssistCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AgentAssistLg>', '', $funcName, $content)
!endprocedure

!procedure AgentAssistGroup($id, $name='Agent Assist', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$AgentAssistLg>', $name, $tech)
!endprocedure
