@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element ArtifactRegistry
include('gcp/Item/ArtifactRegistry')

' renders the element
ArtifactRegistry('ArtifactRegistry', 'Artifact Registry', 'an optional tech label')
@enduml