' definition of the Item gcp/Item/CloudFirewallRules

sprite $CloudFirewallRulesXs [10x10/16z] Oq003Y004MmeOanWKJOorB410OXW1G

sprite $CloudFirewallRulesSm [12x12/16z] PSt50G0n2031nUc_uTZd91CNWBUiXJq9iPrPCCCMnQ2QNf8MtgeNzlIxl_xVjKGNpZG1

sprite $CloudFirewallRulesMd [16x16/16z] XSo53S1030D0XxF_n9KjLL2yvm_WnkGyO4k55Tn5m8DuLJvwoV2OxsHm-UtFV9YJhl_zYm8bl_qF

sprite $CloudFirewallRulesLg [20x20/16z] fT350KCX403HWHNel-7OtEB9VoTqZQzj1Sj50qj1koYUYmX622AcyPXROBpCPAIkk-2vqYHTv8lwXbouUlIibgTdnsRL2if5ySmP

!procedure CloudFirewallRules($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudFirewallRules', $name, $tech)
!endprocedure

!procedure CloudFirewallRulesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudFirewallRulesLg>', '', $funcName, $content)
!endprocedure

!procedure CloudFirewallRulesGroup($id, $name='Cloud Firewall Rules', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudFirewallRulesLg>', $name, $tech)
!endprocedure
