' definition of the Item gcp/Item/CloudComposer

sprite $CloudComposerXs [10x10/16z] LSOr0G1030ImAzU_uMVC53na-6S6WL5RPblo7DQQkMPDP8yP3YTK

sprite $CloudComposerSm [12x12/16z] RSY53S100CD09odjlt2P7YmwcR9S0UXdx4JI-PSbOLawXjTxZ-VvDVRq_kGrbemD6m

sprite $CloudComposerMd [16x16/16z] TSgr0G1120H07Ffl-ELS9rk10wnAv0hFcOZ-KF_i3lnnpuL4f1nnpvyX__oQIKJ6Z4GmPUPhthm

sprite $CloudComposerLg [20x20/16z] bO-50G0X2031azX_ukzEpwH16e2DLbtfKK1x5fsP8Rrk-2pApBHHrt_AbwxFUT7r77GpZRgDHRVDmLa7r0_T5klkmr6vfmC

!procedure CloudComposer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudComposer', $name, $tech)
!endprocedure

!procedure CloudComposerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudComposerLg>', '', $funcName, $content)
!endprocedure

!procedure CloudComposerGroup($id, $name='Cloud Composer', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudComposerLg>', $name, $tech)
!endprocedure
