' definition of the Item gcp/Item/CloudDataFusion

sprite $CloudDataFusionXs [10x10/16z] Oq03pCpCB2222KYmiO9PG54m2opF2f95A0QH71meB3Om0B9OeO01

sprite $CloudDataFusionSm [12x12/16z] PSY54S1024JHnNRIVyKvD_u9Rq1EIu2KNs1ceR2IbhspkB9KFGWHJDUcWxhCpwgzrirHiSo07m

sprite $CloudDataFusionMd [16x16/16z] TSt50G0n20117Ffl-2Ik6vqNS0t_1lANbfVpgzODH6B5HF1NdRKvTtSUtnrXPqlEYwtcoTPJs7e1

sprite $CloudDataFusionLg [20x20/16z] dSY53K0n30FHaAtil_1dnhOdEZrfoATYE9lELWFMsumycvd5rOPMM-7D78ZTzjeiChFMOWcxSMyryD1iE2VFzG

!procedure CloudDataFusion($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudDataFusion', $name, $tech, $desc)
!endprocedure

!procedure CloudDataFusionCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudDataFusionLg>', '', $funcName, $content)
!endprocedure

!procedure CloudDataFusionGroup($id, $name='Cloud Data Fusion', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudDataFusionLg>', $name, $tech)
!endprocedure
