' definition of the Item gcp/Item/CloudScheduler

sprite $CloudSchedulerXs [10x10/16z] JOc50O0020Hfs7zYFKpYKtvZW09UnPsgH6PnrQnob5_PaA68qr4CxJi7

sprite $CloudSchedulerSm [12x12/16z] LSU70O1024FHqFwn_yHYL-gB_kNl3MSgOmzEp4rsx-nMnMxjNk9nNxPXsUvChIxXkod9M3P60RYXRsq

sprite $CloudSchedulerMd [16x16/16z] XOo50GGX30Gtjj1_nK_atUOEc2Z-emRrC56p3eMCEESO3aBlXnMYmhr6e4J6UyFAF2OEr41SOu8AL9ViWtTTA1MkcKSmJvo2LRnOObnU-odEn8vX44qzvvKB

sprite $CloudSchedulerLg [20x20/16z] {
bOy74iCm20IH3jRy_yK90tBAj6HjDVhP7spPiCvDaZc5BscDRGDI04zZfsuOBrZV36hFQww5TrHcLjrzmiQMPgXjkctBY6-RnjQ7SdBzhaSMb-tfuSZK9Wki
WICrq0XFy1fHmSK9smnYUiIkp0YlyYxxcGS
}

!procedure CloudScheduler($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudScheduler', $name, $tech, $desc)
!endprocedure

!procedure CloudSchedulerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudSchedulerLg>', '', $funcName, $content)
!endprocedure

!procedure CloudSchedulerGroup($id, $name='Cloud Scheduler', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudSchedulerLg>', $name, $tech)
!endprocedure
