' definition of the Item gcp/Item/CloudDomains

sprite $CloudDomainsXs [10x10/16z] Oo0CcDaOs80Ka61c0RAX0imW8KOWcvaPn61XO0PAOpS

sprite $CloudDomainsSm [12x12/16z] Oo0Ui36ni46Pp6mCR20sY6HcPMI3oBCm0Nb8IfYPOGn689Cu

sprite $CloudDomainsMd [16x16/16z] hOh50K0n34A9yFRV-BkUsoYcMGLg_D32Clfm9JpHR5JaGOCTb-eVh_ABZxreUyTPVML30xK2

sprite $CloudDomainsLg [20x20/16z] lOl90G9048F8Cfl-E_Q-VMkU0VZlsisqhvTjs5yVgrsFgiJEvNzyWtFvzqk5tMXvcJReNKkyVAXvAYmLdRlc32fvVX1-koC

!procedure CloudDomains($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudDomains', $name, $tech, $desc)
!endprocedure

!procedure CloudDomainsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudDomainsLg>', '', $funcName, $content)
!endprocedure

!procedure CloudDomainsGroup($id, $name='Cloud Domains', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudDomainsLg>', $name, $tech)
!endprocedure
