' definition of the Item gcp/Item/CloudCdn

sprite $CloudCdnXs [10x10/16z] LOer0G1030FBZN_3ptXBa7vY6ptsDgeW7HzDa4kt4TdDmFVJc1PZgW

sprite $CloudCdnSm [12x12/16z] POg50S0m20GFP_-5wvgWRqobBxHuYH1CPO9PxGzDi6f83f9P97FPHvKvi08

sprite $CloudCdnMd [16x16/16z] ZOs55S0m44AH5zBz5wwx_-WPu1_CCRGE2VTRZxE6t4Cl8VgeCQP4nhZsCP8vuQGQPVOGr4Dk3fpFWeboy7S93WJtT

sprite $CloudCdnLg [20x20/16z] bO-50S0m20G_o3NxJrntloWE-WrdbPCdbGkEEgcW_xZtnxtspwhgTKsTXQbSh-frYQb_A7rxz7xHgsPFw9IJrnjvdYCuzHWK7R2hzCyLMm

!procedure CloudCdn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudCdn', $name, $tech, $desc)
!endprocedure

!procedure CloudCdnCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudCdnLg>', '', $funcName, $content)
!endprocedure

!procedure CloudCdnGroup($id, $name='Cloud Cdn', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudCdnLg>', $name, $tech)
!endprocedure
