' definition of the Item gcp/Item/FreeTrial

sprite $FreeTrialXs [10x10/16z] ROY50G0G44MVPl-1TNFtc--vUXgKCSPbWkb9GWZ1PG9z-wPr2G

sprite $FreeTrialSm [12x12/16z] VOY55S105CAeGlSVkESk-K8UM4FIdqCIxLaxdkTvAVk1it9y5jfpdlfhutTqD1W

sprite $FreeTrialMd [16x16/16z] bShL0K0X20LGE_OVM6duUd5CuAOFUizmrzwad4hcQwqv5v0qc7FJ-w5E6wovKK83m1mVgaF-T_tg0W

sprite $FreeTrialLg [20x20/16z] jSr50e0W40NGJqnu_mjBryRacKpY8n8HDh0Ie921Bp6dWOX69K99Y562W9QOVH037L68fIyIhtrlNppsxed1fnWB1HxtdG

!procedure FreeTrial($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/FreeTrial', $name, $tech, $desc)
!endprocedure

!procedure FreeTrialCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$FreeTrialLg>', '', $funcName, $content)
!endprocedure

!procedure FreeTrialGroup($id, $name='Free Trial', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$FreeTrialLg>', $name, $tech)
!endprocedure
