@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element ManagedServiceForMicrosoftActiveDirectoryCard
include('gcp/Item/ManagedServiceForMicrosoftActiveDirectory')

' renders the element
ManagedServiceForMicrosoftActiveDirectoryCard('ManagedServiceForMicrosoftActiveDirectoryCard', 'Managed Service For Microsoft Active Directory Card', 'an optional description')
@enduml