' definition of the Item gcp/Item/PartnerInterconnect

sprite $PartnerInterconnectXs [10x10/16z] Oo0Cs20K1mS36pC76v0FOR6p8iI0W96HZP4Hkm4

sprite $PartnerInterconnectSm [12x12/16z] Oo0Ii840d0TdSN0mi04988kL3SfcGnA7gqSp1pS

sprite $PartnerInterconnectMd [16x16/16z] Ow06O8C0524a9ZixCv3FpiuEuRDpSB00-HmS711f19-D3Oiy0nCpCoEGpypCZ6e-flra

sprite $PartnerInterconnectLg [20x20/16z] Ow0RO8C1L656DbGk4035e0m8u002a1Wpa6Q3ga8H0wjaOqCMOsTZnQONKmpTBUYkOMQ3kWJJ7xG

!procedure PartnerInterconnect($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/PartnerInterconnect', $name, $tech, $desc)
!endprocedure

!procedure PartnerInterconnectCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$PartnerInterconnectLg>', '', $funcName, $content)
!endprocedure

!procedure PartnerInterconnectGroup($id, $name='Partner Interconnect', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$PartnerInterconnectLg>', $name, $tech)
!endprocedure
