' definition of the Item gcp/Item/Profiler

sprite $ProfilerXs [10x10/16z] NSct0K0n20FH8zt-6__Wphm6975HMKeTWHY2CujLkBwgZ3npq7B40Bm

sprite $ProfilerSm [12x12/16z] NOg54S0m00BXaEu_STsIFq4nuIHu8FbwcOZEjeAxd6r10JqFOgNBcwd4d7T3T_yyBuysBKOs

sprite $ProfilerMd [16x16/16z] ZOw50KKn3099ARV_nb-V-rNZw15yqGMzMmfpUe3P_3_zRne9M-9lOu5juR-jmKx-TWd_x7-3eEP5_RzkCRv8LLiA3c0TyGO

sprite $ProfilerLg [20x20/16z] {
bO-34KL154DpbVux_dXSuumomG9xyC0ppmyCK-Hi1H_7U19yF6TSIJoxGmg0ftOeqamXrDip-D-pjoWKyF0KaNdnUC_MBTiUmYo_GnYtoBuXnzE95-L184Cy
30E-
}

!procedure Profiler($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/Profiler', $name, $tech, $desc)
!endprocedure

!procedure ProfilerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ProfilerLg>', '', $funcName, $content)
!endprocedure

!procedure ProfilerGroup($id, $name='Profiler', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ProfilerLg>', $name, $tech)
!endprocedure
