' definition of the Item gcp/Item/WebRisk

sprite $WebRiskXs [10x10/16z] Oy06E8203GXO6JY0F6OW1h7O61au624i88QmW4oWD4GT8qWTN2ypmZW

sprite $WebRiskSm [12x12/16z] TSRN0G0m14NHfzj_ubJ-t0G7K-mxEm71H8JTyOQBb7rlQIVA9X3wXcvU-qvtZga5

sprite $WebRiskMd [16x16/16z] bSV95O1G349HCgV_YZt4SQN-ju6BvNhAFLeOc8xvt9HpEDDXePSvPKzBu-7W6WvpqqmVXbA7apaBEgUO75zj

sprite $WebRiskLg [20x20/16z] fSv55i0W34NH5_lj_ZTS5s3A7UN4cMA3CxS-zAWpfwT-ktF5ASFwd9KK4Txc93kZi3PN6ABFYLpfSoa0Z-wkv0mte7Ic-XnO-_EYIzxkt4EFOCOE

!procedure WebRisk($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/WebRisk', $name, $tech, $desc)
!endprocedure

!procedure WebRiskCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$WebRiskLg>', '', $funcName, $content)
!endprocedure

!procedure WebRiskGroup($id, $name='Web Risk', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$WebRiskLg>', $name, $tech)
!endprocedure
