@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2023/bootstrap')

' loads the Item which embeds the element AmazonSimpleStorageServiceS3StorageLens
include('aws-q1-2023/Resource/Storage/AmazonSimpleStorageServiceS3StorageLens')

' renders the element
AmazonSimpleStorageServiceS3StorageLens('AmazonSimpleStorageServiceS3StorageLens', 'Amazon Simple Storage Service S3 Storage Lens', 'an optional tech label', 'an optional description')
@enduml