' definition of the Item aws-q1-2023/Resource/Storage/AwsBackupAuditManager

sprite $AwsBackupAuditManagerXs [10x10/16z] TSYt0G0X00GWpDx-0t-ifSJ1Qe4wQ0hyaGQ9m8Xg1x44b8r0WbxT

sprite $AwsBackupAuditManagerSm [12x12/16z] NSZN0KCX30F0KtY0lV_0wVr-LFoRyTQrFMIY7XzLswctrHfzAnRLWqP9fk6XiU9c63lAJMQINcugsCq5

sprite $AwsBackupAuditManagerMd [16x16/16z] PSI7OGGW30F0CpnOtd_Wz9vJ0VybvQSHFsJrVVXK-NxLzt1waTr4cyOGaPGqj4wnqJKZBhXcJrR7W165zW37kXWRi3cz2L1fC0DSdLUh02bm3fu1

sprite $AwsBackupAuditManagerLg [20x20/16z] {
TS65OG1030GWajVRV-2w2-1_E-sd9NuOj-AxSmmPFbKQx0Deww86AXfddcMFZDf1nYtN7790YD4gbsvgwqqE128XBB19UgSY3b1Bk8qhWDWDBWSGxg4oB6zw
KFiiN6yg5v1u4_lLrHEG4M3FqzwqDrNm2
}

!procedure AwsBackupAuditManager($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/Storage/AwsBackupAuditManager', $name, $tech, $desc)
!endprocedure

!procedure AwsBackupAuditManagerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsBackupAuditManagerLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AwsBackupAuditManagerGroup($id, $name='Aws Backup Audit Manager', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AwsBackupAuditManagerLg>', $name, $tech)
!endprocedure
