@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2023/bootstrap')

' loads the Item which embeds the element AwsStorageGatewayAmazonFSxFileGatewayGroup
include('aws-q1-2023/Resource/Storage/AwsStorageGatewayAmazonFSxFileGateway')

' renders the element
AwsStorageGatewayAmazonFSxFileGatewayGroup('AwsStorageGatewayAmazonFSxFileGatewayGroup', 'Aws Storage Gateway Amazon F Sx File Gateway Group', 'an optional tech label') {
    note as note
        the content of the group
    end note
}
@enduml