@startuml
sprite $AwsSimpleNotificationServiceSnsEmailNotificationLg [20x20/16z] {
ROs7bIL02CD0Ccp_7T_DpqcUu4UiCjG7CzcFe5F5liUIgbxt1LbwfcC88ZrfTwSg7Q_nIc8TWXZL4_kRm-xEEV_vIyUR7gOTZgunvaYe3q0_OmhLL_NDWF4w
90yZyNs7GPi-5sv6fJxWTopOji3DH2GTWXAEv1y
}

!function AwsSimpleNotificationServiceSnsEmailNotification($id, $name="Simple Notification Service Sns Email Notification", $tech="")
  CloudElement($id, 'aws/ApplicationIntegration/AwsSimpleNotificationServiceSnsEmailNotification', $name, $tech)
!endfunction
!function AwsSimpleNotificationServiceSnsEmailNotificationCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsSimpleNotificationServiceSnsEmailNotificationLg>', 'Simple Notification Service Sns Email Notification', $funcName, $content)
!endfunction
@enduml
