' definition of the Item simpleicons-8/R/Rottentomatoes

sprite $RottentomatoesXs [10x10/16z] HSR50O0000GWxFRsdzOENl0hac60EJTI5ENTw0f5KMIAsxbE5ebe6_TEnxWRTW

sprite $RottentomatoesSm [12x12/16z] 9ShL0SC034F1AqFWxJzj8RuVWuIp4qPbl6f0DMZ1DaUBmBcbnJYrjhWerNawgJJKuZhxKZ37dIy

sprite $RottentomatoesMd [16x16/16z] HOw50G0X4CFwxcJ_RPyh5ZH5bPbTEnip35r9c6yAFJwhUHqmID9CR9l0R29x962cy1V9m1FUWQywH8FJ-wMdkkn96bwnZvUP9ZZz_yukyp1-_mC

sprite $RottentomatoesLg [20x20/16z] {
LS_55G0X40JHnftEFzlTmHxKyHz686a02a-Tg6olgKOofPBCbiIhEaQO6dddrhWd2u1KVxeT7ECmyjiYA1Qe03NAf1dccQupoh3HiNPil4Afp7aAu34tvtL0
RUkO9kVNPH6LfsK0NXi4noS3ITs4dMqS5Gtf0m
}

!procedure Rottentomatoes($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/R/Rottentomatoes', $name, $tech, $desc)
!endprocedure
