' definition of the Item simpleicons-6/D/Dashlane

sprite $DashlaneXs [10x10/16z] Oq02_428OF4ZM2mWDWWZM0nm5YkG1LU7ePSNI0C

sprite $DashlaneSm [12x12/16z] LOp50K0X04BVxrJsdzPEJZIi62eagudh6lYzPSuJk9GvV0E7pfVAxPlw_MSrdVV_PGKy

sprite $DashlaneMd [16x16/16z] VSwr0S100CD0XJdQVzemmxkxoe8OifnpjHRwSf_ShIydkwDsTgJHQc1rV9hYOSAsNtt-FKtSHA--jrFD3p02

sprite $DashlaneLg [20x20/16z] ZT250GCX00F0u4xsdxRULzmF1u01K70EP7vbNeoVB1j6XeRLfgcxQT9j1fYVvOEXQO1i69QCvcp5tixuvhP1nd2pbJyGfMnc2v6E__m4

!procedure Dashlane($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/D/Dashlane', $name, $tech)
!endprocedure
