' definition of the Item simpleicons-6/D/Deliveroo

sprite $DeliverooXs [10x10/16z] LOg30G0n54DpPllsdxRcPwHSzahlHq14i3V4Y4m0Uq974ZOBDJGZwSh00m

sprite $DeliverooSm [12x12/16z] DSs50SD030D0j-4ytFxJXiqiHKePt_nlySDT5khurGDMIjo2ofGrVdUvl_KxAxEIDM_TP1Vnp_gZBUWH9m

sprite $DeliverooMd [16x16/16z] NSu50e0W50FGMJJi_hVrXycKU3JU73Ki3vQ0HB8QWlG6gjG15agiMYTV1mpf1hNJjhQFDrfk1xxkrkPnszkz4DcUa_d93YnVG_9XLAzXtCQJ9GkBT4u

sprite $DeliverooLg [20x20/16z] {
LOu53W0n20IfU_l_rvwG9SrEZC65sAC4IdYHyvFWSNw273fLBETiqIyH9T1_MPvoMIrIpgbboedQr0sSKvgzjrJjvTJMdSDx0w64imKd2dBxsnwG2uTPUf69
dBiVDqebCSgsd12nVY_MFte1
}

!procedure Deliveroo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/D/Deliveroo', $name, $tech)
!endprocedure
