' definition of the Item simpleicons-6/D/Devrant

sprite $DevrantXs [10x10/16z] DOm50S103CHkp8j_jrzC6MKyN788Rcd1EOZMYvM_PoVkXRDLDhkR-fP-yoiW_

sprite $DevrantSm [12x12/16z] HOo50S102CIkxit-qxu3mLM5wUDHXqwaFqZRwDOSk6Vs3JPvczFpsZ_WNlG3_gVdawUL1vv50th8

sprite $DevrantMd [16x16/16z] LOw50G0X30FpWalsdnRNGmzfYuQE33yc7DYXYr0r38c6_8_hzoaJyDRzNxUkkQgEI0Csr-CvH7SndTsVjlY-SiL7c1LztA2YbZveFBwPnY8IDyip

sprite $DevrantLg [20x20/16z] {
PStL0O1G34FHuF3ixZyj7lHyrQj34w5CUfYmpYKUWdQPftu_1LOFm6TJBT2uHjepW2BLR2e1P-npUOH9uLdpx5chC7MkYKqj6dzpBTIezebxUSfiYZQ1frgx
oAtLgN6bw271q3Tw8-cd7-zu0G
}

!procedure Devrant($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/D/Devrant', $name, $tech)
!endprocedure
