' definition of the Item simpleicons-6/D/Django

sprite $DjangoXs [10x10/16z] FOgr0G0W40FJu7BxJulprqIr0NLzXxbDXzUHt-gn7z7S-ptuhe4c

sprite $DjangoSm [12x12/16z] XKg35G0W5Bpisd_QhCVl4sQLWfnnSP-BfHn0fjnn21t6Ccfbng5m_l9GgIGxy2dpS1gm0G

sprite $DjangoMd [16x16/16z] ZOnL0WKn20EfU-V-ftsooi_AL84aiW5UvioYQxYlTtnd_ElMuh_i0AVUmxJkh87__RfECBHVvfcVv4_ear6jXI2A2bQL2H35Mdu1

sprite $DjangoLg [20x20/16z] {
ZOy50e1020Ina-N_hxMBK6_rQcWwLOi84G0YmzOjXGt3uDYjSe10-q5MgNpz-cJ5rhCtTVFjrAmEME7PThQMyLONUZRPf1bLwnpSDtR0Cu8rsTmQZVRvj0hU
8sS
}

!procedure Django($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/D/Django', $name, $tech)
!endprocedure
