blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/tmorin/plantuml-libs/discussions
    about: Ask usage questions or discuss ideas before filing an issue
