' definition of the Item aws-q1-2023/Resource/EndUserComputing/AmazonWorkSpacesFamilyAmazonWorkSpaces

sprite $AmazonWorkSpacesFamilyAmazonWorkSpacesXs [10x10/16z] JKo50S0m3ABUvl-3jxWhW6BzsN11x3nEgJpFJJmqd7daq03iVngD9_BW8y6b-F01

sprite $AmazonWorkSpacesFamilyAmazonWorkSpacesSm [12x12/16z] LKs50G0W21ks_lylOTEzmKkvLSge6lgSfWOhegwfKSMKOVMSTzD6kXqHDgaqfsixw-MsiQn_KteFZt722W

sprite $AmazonWorkSpacesFamilyAmazonWorkSpacesMd [16x16/16z] XSh7GGH130J0qimQjVBF5myVuAv-RJoNCvkzWFkYjrcLWinkzy1kH1j-pj5r9A3FVEGopTN4wBen0-7ish3EpqmL5FsLrrVM0Qi_ysvVifIK7oiv_U4L

sprite $AmazonWorkSpacesFamilyAmazonWorkSpacesLg [20x20/16z] {
bSk7aGCW30NHbG21Vl_ztjc0Srxocu4VSkMTMBQv62CsvG0KXC3Lfcdq6BW4G943mYhgiEjQPjc9RP6-BDX_czpEbY77LS2SqG_M3HWAc4PLjGH0thO15iie
s8D1uDjqDj0ooBhDvcqLEIsJwxAefd5RgFAoVm
}

!procedure AmazonWorkSpacesFamilyAmazonWorkSpaces($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/EndUserComputing/AmazonWorkSpacesFamilyAmazonWorkSpaces', $name, $tech, $desc)
!endprocedure

!procedure AmazonWorkSpacesFamilyAmazonWorkSpacesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonWorkSpacesFamilyAmazonWorkSpacesLg>', 'EndUserComputing', $funcName, $content)
!endprocedure

!procedure AmazonWorkSpacesFamilyAmazonWorkSpacesGroup($id, $name='Amazon Work Spaces Family Amazon Work Spaces', $tech='')
  IconGroupElement($id, 'EndUserComputingFamily', '<$AmazonWorkSpacesFamilyAmazonWorkSpacesLg>', $name, $tech)
!endprocedure
