' definition of the Item aws-q1-2024/Architecture/InternetOfThings/AwsIoTDeviceManagement

sprite $AwsIoTDeviceManagementXs [10x10/16z] TSYr0S0m00Cm1_N_nSMbgCNWHz7jfggPnnDHzvRCv6W3ezehubJTh

sprite $AwsIoTDeviceManagementSm [12x12/16z] VKg30K1H43hM_XD_upaSumgGRrJcuGTv4FTe0EoDEmpF73ZyZDHK-hFagHV15Zi

sprite $AwsIoTDeviceManagementMd [16x16/16z] dOZ50KKn3CD2ZlQV-77RqqS5PVx3Arc443cIJYIgoRvSO1bfeCVJPRAS7jK7onqh8wRhZAJ7yUOiEG_jvpGBBNlF3W

sprite $AwsIoTDeviceManagementLg [20x20/16z] hS_70G1120904ON-AxwSxxjiT7vuHCGVWOvw2TDg2RSgx2oJTkWmBBoGkK3UnWWZ-BIca6ZMmy9HwkL-6P6ebtKRstERp5p3HnjYVzzLaiVrIcHwG6O

!procedure AwsIoTDeviceManagement($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Architecture/InternetOfThings/AwsIoTDeviceManagement', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTDeviceManagementCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTDeviceManagementLg>', 'InternetOfThings', $funcName, $content)
!endprocedure

!procedure AwsIoTDeviceManagementGroup($id, $name='Aws Io T Device Management', $tech='')
  IconGroupElement($id, 'InternetOfThingsFamily', '<$AwsIoTDeviceManagementLg>', $name, $tech)
!endprocedure
