' definition of the Item simpleicons-14/S/Semanticui

sprite $SemanticuiXs [10x10/16z] uyS161WO-A0CVWwO42kIB2U23QKOGIo4GWG

sprite $SemanticuiSm [12x12/16z] uyS761aOOKm6480m-HXOW2H278c3nkE1C80q4mClcCaBL04n5CB5i18

sprite $SemanticuiMd [16x16/16z] uoSIyA7m64205y6503WVBCU1h9m9KpkoYImW0MPa9Lp8AdWWchXXRc5WOE5YHDZ72x4UoK8U5cPMFgBy1G

sprite $SemanticuiLg [20x20/16z] hOv50W0X24MnM-z_skaYTkDRmgynWUgqAVW49nsV3YowxP88drF_s93N3Ko27TNGiS516lYgz-CGKZ-pexbkzJdLem5x6roWueeM_c05

!procedure Semanticui($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Semanticui', $name, $tech, $desc)
!endprocedure
