' definition of the Item simpleicons-14/S/Skaffold

sprite $SkaffoldXs [10x10/16z] uuK21WP-A6200v0OJ1Y51GR8CdnGm02LGrK1

sprite $SkaffoldSm [12x12/16z] uuK11WO6VXXWm0s0aemmPMXiA6172A6oCOpbXW8W4suE

sprite $SkaffoldMd [16x16/16z] uqK23430ZmGm-OG1I1aZaXviV0Pc640t5bKXOJvHRaAn7vqF

sprite $SkaffoldLg [20x20/16z] bSZ50S0m30D0fSpQVzeoXUrxtcp3WRRezJPeaAnWQ57TN_ocxdETBNgBxJne65gajm4

!procedure Skaffold($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Skaffold', $name, $tech, $desc)
!endprocedure
