' definition of the Item simpleicons-14/S/Strava

sprite $StravaXs [10x10/16z] Oq01_0WMFuo1O351cI2A7w65dHz99Oo9R28

sprite $StravaSm [12x12/16z] HOlL0O1G08ImM_QVrlOTVnTmqnAaq6bgJRsvbvf_w5sW33I24ozkGz4hxpf-kEiJ

sprite $StravaMd [16x16/16z] LO-30KGn341Jks__QG-ViIadUB60TJT1kmwmQOWs3IRj8Qbq5bLmck-4rgB4E5gFxqpFba9J1_8ZUzAPrbCDgBHwyGi

sprite $StravaLg [20x20/16z] VO-r0GD14CJqpAl-gpL5FbGyI8Vhf439EVKkPONmKhrAcUPfFlfaid5CXRS6g5Sg0_w5HqG0F17Pnl26BIsV53IzhMOo65GFyaGbOonbe9Ji_7W3

!procedure Strava($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Strava', $name, $tech, $desc)
!endprocedure
