' definition of the Item simpleicons-14/S/Symfony

sprite $SymfonyXs [10x10/16z] JOg30G0n54FV6KNsdxRMPmJmwIQNIdqT65qLvVlbXwSc_l9lyHPpFP-e02vL404

sprite $SymfonySm [12x12/16z] NSY55S0m3CJGAwEZ_RTjmw20_xDy3wTYn2gTaRaYp7lo0XwODwPfnsS8cTV9xUqv_e-j-0w9TtEUJd-Mjny

sprite $SymfonyMd [16x16/16z] {
JS_50KGX4C3GuDyW_LUxDciFpN5uQTCpyJ4D8zAlzPzhL2-OXfbbcL0zch9KRUh8pWFBfKuriuHw6dP1Y3WL3sH49xLc5uPuhV6ww7esCG3JrlCLsG7Y_qr8
VzFS0G
}

sprite $SymfonyLg [20x20/16z] {
NT05ZWGX503HQc-qxd_Q5SBya7cu2rFgrfl5vTGs9XSfkXRvgsilwBNifNIf2eOTXtUKZL9kkTswQeePqCL_O-1YLqZPa8IyR5sre3oDpUbMwIyc7gVOTQVf
qA86JllOfMns_02IxaXTkY3hc_pOuqi3uNLeE_z-0G
}

!procedure Symfony($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Symfony', $name, $tech, $desc)
!endprocedure
