@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureSliderBarHorizontal element
include('elements/azure/FlatSymbols/CneGeneralsymbols/AzureSliderBarHorizontal')
AzureSliderBarHorizontal('element', 'Slider Bar Horizontal', 'an optional tech field')
@enduml
