' definition of the Item simpleicons-14/I/Indiansuperleague

sprite $IndiansuperleagueXs [10x10/16z] DSYt0O000C0WxDty_wsJZC2v02f5LUzV3UgaU2jCk2r3XfgEbrJ9Xhh1mnWV

sprite $IndiansuperleagueSm [12x12/16z] DS650OC04C3058UNxBzjqJjEGyoyIYNaugdf4VhdPIC663nDb0QWR8idFisA8xicxA1uofJu7RJAz8E0EEet5ATOM7i7_W

sprite $IndiansuperleagueMd [16x16/16z] {
HSq5WWCm24JH7xSbS__JRbkelBW0k7aQFrDF6OaWnvK1M96Rj0mCJ6v15u3St-98ghrKV-tnO0LeAkp4rHC01tSB6nFu4mm0IJx5GiqIAKeKYSRSt_S3xEmL
f4Cuzqn8fB88DsCo01u
}

sprite $IndiansuperleagueLg [20x20/16z] {
LSs50KCX34NHYzk7j_-sBLOvk2HXyxK5_dXD0JCgbpRCd9Rej5NAkHCwHcOp5LqPx2ZhLeTfL4aTqYTTWN4tHBq1PLtr4PbwWmIqcLM6nO45U1eyXj41bwha
eG818xLRt54O0sjN_gObCKzb7a5RPqOPHwbGjK29G6BQmGz7bCC4JB5WksTJ1-WsoF3XsWfcUm4
}

!procedure Indiansuperleague($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/I/Indiansuperleague', $name, $tech, $desc)
!endprocedure
