' definition of the Item simpleicons-14/I/Isc2

sprite $Isc2Xs [10x10/16z] Oy0Bc82G0OGP-U5Y_0oiN9mW1WS_YCFEmCZ7W1y

sprite $Isc2Sm [12x12/16z] bS410KG0002n_GF0zM-h0fkFSiNPghAm0v4Rt64V8RDfvtzWzi83

sprite $Isc2Md [16x16/16z] hS450GCn402mF9NRywzsF0UVk5cZDkozSFGzj4rIAbKoGau8NpdOuxHyHK08i2rXbZo8rBfXyxUvnHC

sprite $Isc2Lg [20x20/16z] nOg54S0m3CGKvlp-szQb6IAppXp2t-MuSVUESyYnMziGr9iIgcsPczo8dtd_LI0rVhOvaZej_Ahssu6SdxoqWRboExQDOAF1WYuLkCU0ZCGXBW

!procedure Isc2($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/I/Isc2', $name, $tech, $desc)
!endprocedure
