' definition of the Item material-4/Action/Android

sprite $AndroidXs [10x10/16z] Oo00M4044vZ93m8G1fG9nFmWp0Uau8AO

sprite $AndroidSm [12x12/16z] ZSRL0S10309GpZLX_sdhybEv5m4CiMwBjdqrfMMKhNCZToKLw3I590ejU8Ftpdc_VRoO0G

sprite $AndroidMd [16x16/16z] fShL0S0m20JGG-h2_jDMulnLNXGu_3SBeeKHx00pWJT4usu18PWi2_cXb35ntHIAEmZCPkiQwZ44p1aXggAHg0XUEW4

sprite $AndroidLg [20x20/16z] lSlL0SKW50FGu4xsd_PfqT_AGQ_X8LHeaiMVBZX8eYakL9BPLeCcix5zO1BnmqKu1XLQd4W926wv2dZk139t6afhhNvB7p-1Yxq1

!procedure Android($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/Android', $name, $tech, $desc)
!endprocedure
