' definition of the Item material-4/Action/ArrowCircleUp

sprite $ArrowCircleUpXs [10x10/16z] Oq01_FoyO9gR7yHX0X4GSJ1Y0c4MC0ianyt01v5YPK9Iny0Cb6C5Su4oF20p

sprite $ArrowCircleUpSm [12x12/16z] NKc50S0W30lkvFzhWSv79OfzOl6NQemsCnoo70cTmFfmSbpS6HSeL0EbgO6guVFHlsy09Hmx8589UVRAGnwXFcW2

sprite $ArrowCircleUpMd [16x16/16z] ROk70GCX30Ff7RJ_jh5Yf_wBUYTmz_7-cnQOQXHmaXmDMndJ_gXOHv4YijR7djMcb4i5A8hS0paa1E44xSswoXtrpMUej6JufptUiAdVM3dMGzJ40s1wTvC7

sprite $ArrowCircleUpLg [20x20/16z] {
bOvN6iGW28GZ97QT-zzs-K2olSs3mizGjl-K8HfyGn8mUnloagC6aBl9NSsh10GDWEqKMpsRduV23hNDrQMGiCkhRWOMH947LPv01Kp1BUXsXszCyapSiaCt
xaYQrDl3ffHS1MdTETcHxZQ8JZfBa2iqcDA9R4NFjBtN1G
}

!procedure ArrowCircleUp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/ArrowCircleUp', $name, $tech, $desc)
!endprocedure
