' definition of the Item material-4/Action/CheckCircle

sprite $CheckCircleXs [10x10/16z] LOp50G0X4CJcX0-M_gl5DUkg2mWjEYfloNh2J0o_yAe9Jh6OwOlWAKZww4d5-FeZ0m

sprite $CheckCircleSm [12x12/16z] NOe54i1020C3TTt__xQPosZt12Bwir-hmWDconeMxzccnjsi1QKRNRHNMYjehAJlDVjEA9cLhA5wZ0y

sprite $CheckCircleMd [16x16/16z] ROm54eL034FJxHUic_lVbgdWlD4etX4vguNE7qbZOQcvOrakj55FiSAy8EIqITBVEfHiw7JjkK4r9NFVKN82y2Tfna20Z981WPsberwP1I-i

sprite $CheckCircleLg [20x20/16z] {
bSxL0GCW30JGmvtRVzeA97LzNn37Vp9FXiDLefWMel7AQjKjisAtLO5DnYk7IDwNMGIIViS2kJwH9sN5Eg1L9stNLHYj8XE0ARbmSw7dgemKW1IoKwGLSxmn
iBdRa3BjsdWZr9ujtZi2
}

!procedure CheckCircle($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/CheckCircle', $name, $tech, $desc)
!endprocedure
