' definition of the Item material-4/Action/ExploreOff

sprite $ExploreOffXs [10x10/16z] HOgr0S1G58I8onVstpRlgb2TmCy5EfBQTLYi5QtOLYje1FUaTg6DQOiRqIN22MoQI3ZwHbi-

sprite $ExploreOffSm [12x12/16z] JKq50i102C9rulz_EpXNTWB-qicNVMervqZBx2QhuUXQ3KC9M6k_PmOEhTLeqc7oeFsqUn_CdUk57wQkBAm6ONBY0W

sprite $ExploreOffMd [16x16/16z] {
RKm50W8n36jmgFt_jpGPpkLaYzesWESjpsRHn5byDsUsa1BsJo5BGZ1P7K3tVlYh6chWjSMJUmEEtiJbkr4eSiLWvX9y-BaJlZOIDgWYax2G_IFicN1mz0ix
s1q
}

sprite $ExploreOffLg [20x20/16z] {
ZSv75WGW20DGUrVkVzj10flfMV6-9RX_uwlZDEBigDQfka2Q4u2JCPD5SJ4Mo3panOZqvhoVJ7meM1hVs3pY6f0ZNGbcEE_GpTgyY1upxuQrDxOZPxOdDapI
5GRQxomNfzyim2eMwP1514YlwAV9029vh1wbtRkNyC43
}

!procedure ExploreOff($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/ExploreOff', $name, $tech, $desc)
!endprocedure
