' definition of the Item material-4/Action/IntegrationInstructions

sprite $IntegrationInstructionsXs [10x10/16z] Oq01_Bpi41e2q5WCG0XaWIbU1bGnJ1q8

sprite $IntegrationInstructionsSm [12x12/16z] POl50O100CEAEzb_MZZNlAfgWJCAE022fjHlrEE4Dgzt0NgncateeV_s-bR93m

sprite $IntegrationInstructionsMd [16x16/16z] ZSt50GD130D0BQEi_giDSuxcPJQMcJgU1cbo8bbnCVNcBpaFv9vAvPrxI1tbcLUCMy-U_OAX0BxtYpJjuB-cDuSB_t99Vvq1

sprite $IntegrationInstructionsLg [20x20/16z] bSs50GGX40F0vHLF_zMUunvyCEg4ASjp0mp-OMbmnhnnvVSSYMCgPlicZiPJOwJm9Xxi977rF1Wdzdnfmxa_lG1rKh03xTM2dTEh1GjPC7tPtzWGywBfx

!procedure IntegrationInstructions($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/IntegrationInstructions', $name, $tech, $desc)
!endprocedure
