' definition of the Item material-4/Action/List

sprite $ListXs [10x10/16z] Oo00sFZ1WA0O4niOO3K3

sprite $ListSm [12x12/16z] Oo0Py3FmGm0PueG1

sprite $ListMd [16x16/16z] hSgf0O0m00Imz1G_-s-BEbL9esEv-_9Ma4Z165Bpdns7ku9ZTrNyzG4

sprite $ListLg [20x20/16z] OnWumC_6m8y0V60nFbO6FWJWmQcNWvc10m7OSPh724H8W2Iti34ni240Atq21G

!procedure List($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/List', $name, $tech, $desc)
!endprocedure
