' definition of the Item material-4/Action/Outbox

sprite $OutboxXs [10x10/16z] RSR50O0m0C30u4xsdnRNjlSwalfw9r310ETql5R8DJYdDNhin6i5

sprite $OutboxSm [12x12/16z] Oy09-640n8Q9GJ0ZFvpD25O0vVFoCy7PJ4nGDI05O6LGCtdu4Mmm7yLM

sprite $OutboxMd [16x16/16z] XSa53i0W40NHfP7gP-v_MbnZ7VHbxRzNlQkGhyUHhDTwqyvlTk1N2tWN6yXMIzymKdvVgHdA48Rn7zqtCsUfOrIu5m4

sprite $OutboxLg [20x20/16z] fSy33aL104FHZZtT_se_diqRDISitbKupJR6QCTOMZCOOvsOI2iJbN5XWh_ot6pucPCpW_ePS6Pze_rgbXmMXajS64lcmiPoOwxKiI9nkIy

!procedure Outbox($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/Outbox', $name, $tech, $desc)
!endprocedure
