' definition of the Item material-4/Action/Receipt

sprite $ReceiptXs [10x10/16z] Oq02J0pCVBnC81O_181O360-OJ5E440M0mDMPY01

sprite $ReceiptSm [12x12/16z] Oq05h8mCR8n04iZaXm5qDWjO9G-buWWs1322IG

sprite $ReceiptMd [16x16/16z] Oo08U3ZuGP0TH381-Rpy282TpmBJ2UNpGW5CdW_Anr2FmpmsPWZWmU0Junvk9ZucFaOW1D9C6Bu3

sprite $ReceiptLg [20x20/16z] bS-50S0m20J0Zokm_xHrzrxS0xwpcb2COL3VI-Z93l-SivZLPSxfMNqycyAC7kyJdlt_Iqap_XaRaoJfgjnNYJ1oi7rbfkfA2m

!procedure Receipt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/Receipt', $name, $tech, $desc)
!endprocedure
