' definition of the Item material-4/Action/Segment

sprite $SegmentXs [10x10/16z] Oo00-240GvIm608

sprite $SegmentSm [12x12/16z] Oo0AyC00aCqC0vZA-C40btO8cmK8u7en0G

sprite $SegmentMd [16x16/16z] Ow0OSF8W01EGpuN2nmuOcI00nkVbXm0c0dRXKi_C0WBCBAIx7W

sprite $SegmentLg [20x20/16z] Ow0Fu441N60nVXJ0HxAPZ1mmm0uNOy9c7YCSu3UG5GPOy9l7mim2142IcVe11G

!procedure Segment($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/Segment', $name, $tech, $desc)
!endprocedure
