' definition of the Item material-4/Action/Toll

sprite $TollXs [10x10/16z] RSQt0OD000GmsUHu-s_BDsHKoQUM93_cGL0Q4uZ8iUuFKKTA0mnPNMm

sprite $TollSm [12x12/16z] TOQ55G1H3CBuhYtxJtlkaeS4_xWfjPXPgLD2P0DwcJD11sBE3B_TAf8Yw-mqGEMKBlJOi1PtHW

sprite $TollMd [16x16/16z] bOnL3aD130FdyM9y_zjs7VMxC58uDl-pTOUa1tCg7FTP5PvLsLGm4J1Mz1M9TdI3hlSS3Hra97DWgPsDXoAe8ZcqWI8ZnvOcSimH7itXQADiVES5

sprite $TollLg [20x20/16z] {
hO_74GCm20HNEUlwxzQ3XfU_zYgIWVyGSmhWL05Dnd7jrdrNpsLAXQSQCEq2WXGWQTbtWoilJ3CiWJCKEGBCw6GLxfSkgh85p-0KPReID4MSBI-4572t2MGf
Kkm2kcUk4gQyU_jmndYNf9lvaGy
}

!procedure Toll($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/Toll', $name, $tech, $desc)
!endprocedure
