' definition of the Item simpleicons-14/P/Phoenixframework

sprite $PhoenixframeworkXs [10x10/16z] RS650O0m0C2muax_lnRNRGa9bSgfL2SEcbbr0288G8VA18psF6Q-LW

sprite $PhoenixframeworkSm [12x12/16z] VSQr0S0m0C0mbxd-_zfYO4eqYPB5ZMXI-vQVZxbX2CS5Ui29PpQyfD5M1APZ9siPgRW1

sprite $PhoenixframeworkMd [16x16/16z] bScr0SCm04JH4xF-_jl635tygWDzHOFy6XQjsbUdX7OkWrNj4-RQAz3bXj61fFNm74jV6ZDuWwjQ-IIbgBKahI0PFHcpFczD__W1

sprite $PhoenixframeworkLg [20x20/16z] {
fSgr0SG034FHRmh7sd_QOxuohp587E8nELzAcYKPNtJZY_EMkc7V_uezbiVIoyVFKbNh3F7-0U5WtEqQATstvy-qmQGnC-azd9kUOPQ4LjWthjQ8rG7ZmoRr
ulmmevn_pN5d
}

!procedure Phoenixframework($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Phoenixframework', $name, $tech, $desc)
!endprocedure
