' definition of the Item simpleicons-14/P/Piapro

sprite $PiaproXs [10x10/16z] Om02Tdvc1Z3W1m4eWnVCP0RpGGGtTXOdK1c2nG2HXG1k60C

sprite $PiaproSm [12x12/16z] HOgr0GH108HuEHVwhtPTY4OWSxfIkSqiEHvMFe0A7nMeozLoDMUsvrVrF_DDpy-7bWSpHW

sprite $PiaproMd [16x16/16z] LSo54G0n4090tltJVxMHysE4MIAWp6-vO9aB9p0EHXwktaVlJzphrtkdbFhXEjINcV-1-k-ABfGfUu7PFWt_cpyapr4D

sprite $PiaproLg [20x20/16z] {
VOq53i0W5CK-xd3_souFbsITq1IZZiab2Dg9fM5MAfEqqYAq5FgIDh2vB4CqBCB4cdLGY6y2sD3mtzJPrcsh6Sbj0N8rLphqDdeRxGs7HKv76wmMtiReRluk
7m
}

!procedure Piapro($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Piapro', $name, $tech, $desc)
!endprocedure
