' definition of the Item simpleicons-14/P/Protonvpn

sprite $ProtonvpnXs [10x10/16z] FSot0O100CGmaJEt_xHaNfKhAyRSrWOrGsxoysQNdhnuKhpLP-3Db2US

sprite $ProtonvpnSm [12x12/16z] JOo50S0W40ElkBF_jiNXaDU41r4RsTBvLCnrGNibo8_SSdkRCDEIMygtseP6JviTh2AlbD8sB8icOUDc-WC

sprite $ProtonvpnMd [16x16/16z] NOg54G0X0CFwkBF_jd_58QTjWfTQQtPopL8FekNrIPVMZKgIbmB8t99xEs3lZnCufk7EVSP8lGFCYJ2cmQ3N1HDpreJJuY1J7qYFpWy

sprite $ProtonvpnLg [20x20/16z] {
NOq73i0W4CDoN0UR_x-sWnM1krrP0I4sUgjcLOL4gzMvaCl6YQjsUaTAfFf8mQaHIAfEbWx_Vo3j3X-5dAwKgqvFbV1VbQsiN5rTNt6Zmp9ZeBCKJ6ffQqcu
IG8tYNoRTdEMcqJCV7q1
}

!procedure Protonvpn($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Protonvpn', $name, $tech, $desc)
!endprocedure
