' definition of the Item simpleicons-7/S/Screencastify

sprite $ScreencastifyXs [10x10/16z] Oq06F70MFpy_c6PbvUBYucU72N0pyCEaW3IO1HA1SM5wcHbG

sprite $ScreencastifySm [12x12/16z] PKo30S0m46nZt_xJndR--5thtsPWdn7Axr1P2L6uCbUIR3FwpFBy4Mlj__yE_-mHizDzpqe

sprite $ScreencastifyMd [16x16/16z] ZSx50S1G309GwaPX_sdhhl_Tua48ynBRvIaUnHZ574I3pDfA60da7eze5vVOvrZOOnVDU28Qj0EvEDrlpl_WI17Uz

sprite $ScreencastifyLg [20x20/16z] bSy53e0m30NGuh1LxdzRCfSVsulNIqlunPYPdH0B81Ouogx01MpsT1Mb-l7x5FD4R3h40WvZ8HP0JBPXnqKSRdV3NhtdcqtW3ztWjmF-VMdT3m

!procedure Screencastify($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Screencastify', $name, $tech)
!endprocedure
