' definition of the Item simpleicons-7/S/Shikimori

sprite $ShikimoriXs [10x10/16z] Oq02pFnWmC303nU2Y73oGhbCd5pS435k80Qh0v8mjKpyO0ei0vQ286u

sprite $ShikimoriSm [12x12/16z] FOg50SGm3CHK3cl_QHyQaDbtTBO-BZiHMlyVGL1REhTbURQDGpftrLRm9QjYBY0XiWE2SUjsTwnzlqHFj5k8SBf_0G

sprite $ShikimoriMd [16x16/16z] {
LOs50SGW4C1IBvhzfts1Qk3SO02u38nUP82D8LGxm1wuI41kZM4-vwTpTekf3E_LWysiytOkJ5otKZDe5J3WHbdECrOiT0IKwXdFBIwE04Idgf8K07TwJVjc
JfGl
}

sprite $ShikimoriLg [20x20/16z] {
JSu5OkCm443HBqXiuR__QNVRJa3F81pWA_7Ld6qimo0K3nbWLo3bKku-PbpCTaxj4xZcNLE2a3oqlG38KrTBXDlCAU_M-nnG8OqnjXyDF_Rx8FQkJ7PIhMbQ
AJw9FWK7R-kp9sz6xvbpxqxSMj16KBj6h0aY2ffkw4OqCLm2B1t0biFja_y
}

!procedure Shikimori($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Shikimori', $name, $tech)
!endprocedure
