' definition of the Item simpleicons-7/S/Springsecurity

sprite $SpringsecurityXs [10x10/16z] Om01FWOmu8S051Q8u0Ap-FWOk844H9O3GnqOSCADWPi8904

sprite $SpringsecuritySm [12x12/16z] HSst0S0W50FHiniox3yjyOUhdYfn-Zgl8JNS_RdzRZBkuXvnYAK2935-qF6195m

sprite $SpringsecurityMd [16x16/16z] TSt50G0n2031ZNlelzfpbtdXi79Ti_EowPQPd7xpfDir3rYE70nKCfjvdCJzNdpT_ytxaLfk0tr_TqvV2ro8D1OZ

sprite $SpringsecurityLg [20x20/16z] {
dSw52G0n30NGN_Ts_sqlK1Vi7XRYw4nMM32RIXKLgwco4JzoYeSp1-9dpf84de14KJsS2IK2K2XQPXaaudaZslLkVlmIjboz8RSSgZNbK8cPokZSFbdvzK1d
QjUEvU9x_04
}

!procedure Springsecurity($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Springsecurity', $name, $tech, $desc)
!endprocedure
