' definition of the Item simpleicons-7/S/Stylelint

sprite $StylelintXs [10x10/16z] JSV50G810C2muaxsdnOvpwjjXLst9y7LMETq8jJmaQXITrMzq4ZQ-W8

sprite $StylelintSm [12x12/16z] NSZ50OLG0C2m0i-j-q_xNSan_D9j0NRRfjtg0pegCBMYGYMee16UnL9y3GguU12QFBMHtNYHoSaL

sprite $StylelintMd [16x16/16z] PSk55SCm303H2xDl_sqhlORpZI8-b8cqZKgjnZkElSL0t6liA6OyCMP0g3C6GmN2RA1N5v9XVuwusr-GGGkfYVoU_blskPgTCk32eOfuaSiuiOSx6Nbez_S7

sprite $StylelintLg [20x20/16z] {
RSo53GD13031VJo-xR_Ro0edFmApkLILzCZJeGjqTJKoYdseUrAjXgRTmEazpJazUh0PwKweZvxgE6C674P5CG0BO5Z0G8W_Ul8OheIkTa9IA-lZDtTJXHNK
dOV7k6eZF7uVZz7Rq5MKJqfQpNnQN6ZohMJaL-Vapm4FDm
}

!procedure Stylelint($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/S/Stylelint', $name, $tech)
!endprocedure
