' definition of the Item simpleicons-14/L/Lazyvim

sprite $LazyvimXs [10x10/16z] O-3Zv-TY00D-862002G64qG2J41a-800HGaBCmCda0jLWf20iG

sprite $LazyvimSm [12x12/16z] HOs50G0X30ChxvBiFoqEFQYRV2HTEgp8XBHmBn5_tzUB-yzEdVrrmmVWQvqnXB4qDbUbLcZkv8wp6G

sprite $LazyvimMd [16x16/16z] LOs50S0W40DJmH-o_xGjBeU-9L3C94p8C_6Av5XZuKd1GlTk7qBmm4LowR2yKKG1pkMlcVaw67Cw5HHmb-p622-brDIJzebBlpfU-RaBRV31HcAuJjtTw0S

sprite $LazyvimLg [20x20/16z] {
RO-50S0W3C3AtFd_spMuPKgW9kQpS4a12kR2NRs36ISr0qN6YP_pXeDJKHqfCpLE0HFSAZRm5AbjfAYsV1wZ_wyglatxQwrsLVUoCD1AaYya2_zdhF0cfomQ
mtVo2FJZZXMCt5QO7m
}

!procedure Lazyvim($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Lazyvim', $name, $tech, $desc)
!endprocedure
