' definition of the Item simpleicons-14/L/Litiengine

sprite $LitiengineXs [10x10/16z] DSY34G1030J0jz5_jR6pSu5h1Azl_9-fO39qnb1Soec4J9SfK3ACL0W

sprite $LitiengineSm [12x12/16z] FOh50S0W0CHIzsR_QN78vvJ2oU1rx_Rdw-5pxilll5j2jG_gSVfIB9ySAMGhYVB8gOQtsXu6HsqZ

sprite $LitiengineMd [16x16/16z] LOk54GD108I8U-Y_svyzFqPPeV5aGn-RN_JEu2Vd14Eb1aFlZk1lr3EQmAed38zdcgh_N7WaE1DzSO7sZIgCeEe8XeuWkWKh3waS

sprite $LitiengineLg [20x20/16z] {
PSm53WKW38FXFjVH-vyMcQ2DaJyVGzyRnnAVHoEvIT7utD0kXVnYbMpfkKYnHC4b93rLbsWoLDBqQ_Aj89Jeqt-9ATng1A3IrOs4BkvNHMyX9T8i8oqoqY9Z
Yzps7Aa
}

!procedure Litiengine($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Litiengine', $name, $tech, $desc)
!endprocedure
