' definition of the Item simpleicons-14/L/Lucid

sprite $LucidXs [10x10/16z] Oq067FnG1Zy_MImmZny482mE1Z0B

sprite $LucidSm [12x12/16z] Oq037Fmm5YC_FvpDJpcRdmF6vkM7iTc06CBc0s8m6m

sprite $LucidMd [16x16/16z] nSUt0O0030InDpdV_jjIujIZJcgT-8tW3p_T2B_mty3z17_9t_Jz1G

sprite $LucidLg [20x20/16z] rSYd0S0m44Mndzxpzj_MsDUu1QN2ZPqJpCrWxsQaczmzsBl0t0hcVh0tozufcNkaxXe

!procedure Lucid($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Lucid', $name, $tech, $desc)
!endprocedure
