' definition of the Item simpleicons-14/S/Sequelize

sprite $SequelizeXs [10x10/16z] 9SQ74O0m30J19sUs_swP7zQMTAahlmqfOcdRKH6ttTwwiRUYMcOC9DmFKlH-

sprite $SequelizeSm [12x12/16z] DSt50O1G30MmuaxsdnQ-LdDxKUgANZl6ef5xHoAsrxDoXWSBhwiO5AzWoNxpdoZUm9fyCZskKubucJYZ5lBx0G

sprite $SequelizeMd [16x16/16z] {
FOo73GGn2C3IU_3-stv0zpZLaaNus7ev2yXk5H0WcaNWDXfmlhHLxJlm1j4kx75XYdc6inW2z-yJQEvDp6yrfw297lSf3UybNkjFuNa2LWIIW8J706hSG7gc
N9GHdAYfyGC
}

sprite $SequelizeLg [20x20/16z] {
NSzLeeKW0411J9hP_sfVNlDywT3Xh8Pt1V4X4N3937KVQ1yQ46WRb6FIlXRaDSEVfOB5Ylcm07kDa2uh3MayB8DkdBQtZwNjDBQ15bzhLulkiY5JwTfXbZM3
FXNyFUtuIIlayDCABVG9X4y96YpXgeCO7arTERw_0G
}

!procedure Sequelize($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Sequelize', $name, $tech, $desc)
!endprocedure
