' definition of the Item simpleicons-14/S/Socialblade

sprite $SocialbladeXs [10x10/16z] Oo0Ey29OC8eVoE9dOk3d0xBu6VZv8InicW4

sprite $SocialbladeSm [12x12/16z] Oo0Dy6DbStB0sNnSN40sFoD8cX_AveUoUTbv6NaPW92JWnUN1G

sprite $SocialbladeMd [16x16/16z] Ow0ku2U5pyMFpETZXVAv6I5AONn-Hdu-LdueduC3bS_Boy3BoCl30gHOEO44gGu6

sprite $SocialbladeLg [20x20/16z] nSZ50O1034JHp9wmsTz_jRXpnE9vyKkO1wr2HtDUBQNPCglLgET-7Wts1bUpexBwMLhDE6l7mz41

!procedure Socialblade($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Socialblade', $name, $tech, $desc)
!endprocedure
