' definition of the Item simpleicons-14/Y/Youtubeshorts

sprite $YoutubeshortsXs [10x10/16z] Ou00VXWD110QokA7iK04N19CGFIXg-C3qunGGzX0D

sprite $YoutubeshortsSm [12x12/16z] Ou027YuOYuyV2C0iBY03mcO1KZ0s4fC9HB51bSDb8OOmm1JnOkhbPO2p8NOYM

sprite $YoutubeshortsMd [16x16/16z] HSrL0a0X24HHV67hx7-rjipzEmQ8zjGep62cn2vjLTocCZGtMCYYNnD6ZwZtZ3ATjYK0-6KKft_EDz3ou0-cyxYEDaBlvJnuBpe

sprite $YoutubeshortsLg [20x20/16z] dT155i0W40DGtEN-fws6JjWsgxoFepXv5ZIHEvOaJUGJ3n1p8Z3D0jl9ot7zbQvf6dPewabTkrYwtp9kzcswRVUBL-j_xfTOSBz1fENR40EH_OAYc5iImGa

!procedure Youtubeshorts($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/Y/Youtubeshorts', $name, $tech, $desc)
!endprocedure
