@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceToolchainOrchestratorGroup
include('azure-20/Item/NewIcons/ServiceToolchainOrchestrator')

' renders the element
ServiceToolchainOrchestratorGroup('ServiceToolchainOrchestratorGroup', 'Service Toolchain Orchestrator Group', 'an optional tech label') {
    note as note
        the content of the group
    end note
}
@enduml