@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsPhoneIphone element
include('elements/materials/Hardware/MaterialsPhoneIphone')
MaterialsPhoneIphone('element', 'Phone Iphone', 'an optional tech field')
@enduml
