@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsCastConnected element
include('elements/materials/Hardware/MaterialsCastConnected')
MaterialsCastConnected('element', 'Cast Connected', 'an optional tech field')
@enduml
