@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsHeadsetMic element
include('elements/materials/Hardware/MaterialsHeadsetMic')
MaterialsHeadsetMic('element', 'Headset Mic', 'an optional tech field')
@enduml
