' definition of the Item material-4/Content/Forward

sprite $ForwardXs [10x10/16z] Oy05UE4iFdumnGy621OlZCK7KmTZC72Z6WK

sprite $ForwardSm [12x12/16z] Oy0BM97OVEmGcfE7XuUV7y81Ca200udDpuXWCu74cPYPcVc0JBWv22O38uQD

sprite $ForwardMd [16x16/16z] Oo0JyA3n-NZXJ6OGuEE72_130I-CZoR03mVig7mEL7aE5FiWN0GVbSl0HgG_

sprite $ForwardLg [20x20/16z] hSur0e00581GxDRxdzPkri_u9WWfmGsfRPnIR2yifhjKTkDjDye6Muziv2nhzrRg_JSYwr4T4Iq

!procedure Forward($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Content/Forward', $name, $tech)
!endprocedure
