' definition of the Item material-4/Content/OutlinedFlag

sprite $OutlinedFlagXs [10x10/16z] uwS3

sprite $OutlinedFlagSm [12x12/16z] unza

sprite $OutlinedFlagMd [16x16/16z] un_X

sprite $OutlinedFlagLg [20x20/16z] unzKO1G

!procedure OutlinedFlag($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Content/OutlinedFlag', $name, $tech)
!endprocedure
