' definition of the Item material-4/Content/Reply

sprite $ReplyXs [10x10/16z] Oy01c60CLXuOWv-V7yBY1m5MA1CkoWFYOZKB

sprite $ReplySm [12x12/16z] Oo0IC38XcFnC22OGi47O_120pE65S43gMVaP8HomNXwSzW

sprite $ReplyMd [16x16/16z] Ow0Au4NZygDn-JcPaBbWm0BbilD30HTKW0Ccm84GO6BXvEFdPuGBW4X6FXwOaL2LtAIx7

sprite $ReplyLg [20x20/16z] jSx50O1040F0u4xwhnO_s_o0c-Tga4cffNQMKaEfjPHQmqkTJ3tM2Ww3njKAKvH9XCdhRpcG4poNPMAe5QxVjr0DFja1

!procedure Reply($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Content/Reply', $name, $tech)
!endprocedure
