' definition of the Item material-4/Content/Weekend

sprite $WeekendXs [10x10/16z] Oy0Ac3X10CJYXm2W43kO0H9YWme2MM3L81OCO3CD

sprite $WeekendSm [12x12/16z] Oo0ASF1302EGpGDbCpCmSB90c3oSp0n04im62W7PJ63006B300gR1vTD

sprite $WeekendMd [16x16/16z] dSgr0G0X00F0l0kI_QV5lOFh8bXm97kCBDuXov1LoOzBacUv2nuWfKpP3ShdNqL7p5HPoWq5sUKJaom

sprite $WeekendLg [20x20/16z] jSZ50O0m4031o-6w_LUB4yyFvZdo0nsixYqywtqDlkAfT7xfKIEOrLOxWSeAxMol1hhh9dkLFN7UynMlIyx8ntO

!procedure Weekend($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Content/Weekend', $name, $tech)
!endprocedure
