' definition of the Item simpleicons-8/F/Fantom

sprite $FantomXs [10x10/16z] FSR50O1G00KWxFRjFwtjFm48nTH8XMb1h5FZsInzyupmJ1BFu5vRffuPQau

sprite $FantomSm [12x12/16z] DOo53O1040G7UDV-koMxoSsvOYx1WUV8ypo8_YXNvvtWd7uVp9C6b_Cwh_wpdJFIxIdsqKBa1DL-oKrwPcdh1m

sprite $FantomMd [16x16/16z] TSytWeD0400maM73pFzVUsUJEfSg1PWJ0CPa2GeOOWHRiqC_036CfzKTRJLmckWRNiUKUtqTCqbjjpUdzTjYbafrco6ouZNySdazd-xsXhS1fOa9_0C

sprite $FantomLg [20x20/16z] {
VT250S0W40F0u4xsdxRwTS4v7412fCOrE1gafgR68NQf2w7xIjm7KNmMen9AB11RjqBe6eS1jISQu6AvilkBPGA4fpciAvaT-su1OcYxMTh5SZMx0NxopDkv
S5dXOX9-pRwODx5haTYaCSbo9CBjgtEDtKXx1
}

!procedure Fantom($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/F/Fantom', $name, $tech, $desc)
!endprocedure
