' definition of the Item simpleicons-8/F/Fedex

sprite $FedexXs [10x10/16z] Oo0IyFE3232BXvcFWP-J7SW2GNvMLcu2UW4

sprite $FedexSm [12x12/16z] Ow00yBE0INP64Cd3pydFoC_9nC31mC_0pyV3ny_0oif8ifa

sprite $FedexMd [16x16/16z] jKe50S0m34jnlFXNUxJm5qFukSXzFz-GboVKuCbmkn7t6cttHUzFW67TUflKSdCpWJb2xAex_tMT

sprite $FedexLg [20x20/16z] pOZN0SL03C9mjrEE_QTzDKCSFqZ2HZEpFwYfoXz9wWzE0l6qs-KSn7aHKM6H07dHPX4afWlujXFCBEAcX8j08JmH_9R5Y8uw2u6DzWO

!procedure Fedex($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/F/Fedex', $name, $tech, $desc)
!endprocedure
