' definition of the Item simpleicons-8/F/Freebsd

sprite $FreebsdXs [10x10/16z] Ou03FdvkVY1WvkTZu04ncFZv6HZueG31OeApUB28CS0KCeACX8e

sprite $FreebsdSm [12x12/16z] ZSQr0S0m0C0mbxd-_zfYQ8mcKT2LJNSMMnnLUnLwWmFYZWrCwjx4Ti3eP-6pwG5m0m

sprite $FreebsdMd [16x16/16z] bSUr0SH00C0mF-RO-qyRvYxgn4qn0DyKtq2LfA4woLK5VywQQeBewgy2mKsmUu67yA_WnSCt27fu0nug4tSmgyuIkrzARsO3

sprite $FreebsdLg [20x20/16z] {
ZT255G8m40JHYNks_svvXplyk0kyohDYdFSOtpDRqa0dDKZQAKgjwuHbUGHDgybu6I0sNKpRA07efbW2ckxqY00zyw1d3VHi_ZdFGzCJNW_ky38HpD8Tnqb_
EE129vK7ziyN1m
}

!procedure Freebsd($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/F/Freebsd', $name, $tech, $desc)
!endprocedure
