@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2022/bootstrap')

' loads the Item which embeds the element AmazonEc2X2GdInstance
include('aws-q2-2022/Resource/Compute/AmazonEc2X2GdInstance')

' renders the element
AmazonEc2X2GdInstance('AmazonEc2X2GdInstance', 'Amazon Ec2 X2 Gd Instance', 'an optional tech label')
@enduml