' definition of the Item aws-q2-2022/Resource/Compute/AmazonEc2C5Instance

sprite $AmazonEc2C5InstanceXs [10x10/16z] Oq0576n876Oq5WSGCeCe861ZOEO04X1PDcHrp630YcGU

sprite $AmazonEc2C5InstanceSm [12x12/16z] NKs50G0m2C8b_p-y3hiLOAK8EE8iMOwCVWtM37BhAkim8QxCCefft01rw3JSUuU3ohei6TuE

sprite $AmazonEc2C5InstanceMd [16x16/16z] RO_50GD154BV6D1_mycwS_k2yG5XWj4sUvkzZgtic1ToEOaIS9a1knmxURiBwdPFoZ9KWvBrxaxLbS-5Vva__QqT-UuZHD0o_m4

sprite $AmazonEc2C5InstanceLg [20x20/16z] {
bL254GD022Dezf-u5-hU_kCEzkwrbHcj9RstrN0uPuArpMsPaAsRTxPfl8ohke_hkiIHWbFSsdQ6sZZV09xihkf1-acla8wdMV1s5lzlZxXv1TC31Wqd9Z3u
T5De3XVPi0C
}

!procedure AmazonEc2C5Instance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/Compute/AmazonEc2C5Instance', $name, $tech)
!endprocedure

!procedure AmazonEc2C5InstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2C5InstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2C5InstanceGroup($id, $name='Amazon Ec2 C5 Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2C5InstanceLg>', $name, $tech)
!endprocedure
