' definition of the Item material-4/Action/BookmarkBorder

sprite $BookmarkBorderXs [10x10/16z] Oy0AEDc0W0VC8fhWu-U4iFWP61Y1604

sprite $BookmarkBorderSm [12x12/16z] Oy0D-240pAQCPEA1i_dvsFZv86mU4C74Xsef

sprite $BookmarkBorderMd [16x16/16z] Oo02SF220GypXClCpmC6lFnGFlrfPbv-BaO4dv-VXusFdm_EvmHHJ43t4GO

sprite $BookmarkBorderLg [20x20/16z] Ow0GCFB30GzCZ9EV3Gfu-E5YGu75n8OkniG7z1WdYXXGX8kDbnz88yJuES1X0HI5YR6pmaE8avJm1

!procedure BookmarkBorder($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/BookmarkBorder', $name, $tech, $desc)
!endprocedure
