' definition of the Item material-4/Action/BugReport

sprite $BugReportXs [10x10/16z] uwS3

sprite $BugReportSm [12x12/16z] unza

sprite $BugReportMd [16x16/16z] un_X

sprite $BugReportLg [20x20/16z] unzKO1G

!procedure BugReport($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/BugReport', $name, $tech)
!endprocedure
