' definition of the Item material-4/Action/ChromeReaderMode

sprite $ChromeReaderModeXs [10x10/16z] uwS3

sprite $ChromeReaderModeSm [12x12/16z] unza

sprite $ChromeReaderModeMd [16x16/16z] un_X

sprite $ChromeReaderModeLg [20x20/16z] unzKO1G

!procedure ChromeReaderMode($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/ChromeReaderMode', $name, $tech)
!endprocedure
