' definition of the Item material-4/Action/CloseFullscreen

sprite $CloseFullscreenXs [10x10/16z] TSQd0O00302mjDYE_x_5CgFYJxF0xBgjPuxCWDt4RKkuEG4

sprite $CloseFullscreenSm [12x12/16z] RKZ50S103E8ayeBzfwrxBy4nFBlTTMJ65K6jySgvkfDijTPjJAdYEB-p2tba4qOt0m

sprite $CloseFullscreenMd [16x16/16z] bOt50S1G348Zrm3xJrjtx_iQ0_i3k7ohF_8b9dQXKUh3RKpRny8anOwC3bzhOHiESOdRkFVb6cFmNRtxy9uM

sprite $CloseFullscreenLg [20x20/16z] dSw54S0W50FGdwJ7AMJ_RUlkfCKU6hKfiGdwYhOsbjbLThFRPBAdlRcdawKuctco5P5B7x4FOWnziOqVpKu76rwllOsl5tRlwkaGnOUq

!procedure CloseFullscreen($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/CloseFullscreen', $name, $tech)
!endprocedure
