' definition of the Item material-4/Action/CommentBank

sprite $CommentBankXs [10x10/16z] uwS3

sprite $CommentBankSm [12x12/16z] unza

sprite $CommentBankMd [16x16/16z] un_X

sprite $CommentBankLg [20x20/16z] unzKO1G

!procedure CommentBank($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/CommentBank', $name, $tech)
!endprocedure
