' definition of the Item material-4/Action/CommentBank

sprite $CommentBankXs [10x10/16z] Oq00Jdu8O600Ksni_3mCK05C5YCVY0K521Op0pyZ0pe

sprite $CommentBankSm [12x12/16z] Oq01FBmGmCt0mCiF0qn0DeHc8Cm6GOHU33OB1303pMTYm0O

sprite $CommentBankMd [16x16/16z] fSUr0O10002nmntsdnQtTqiN55d-ERhyGRxSnd7yVmAItYpvzO_donV7S_xo39iD

sprite $CommentBankLg [20x20/16z] jSYr0S0W00J0ZtlOVrhS6_pAGxQBXC2Ho1FSpX7o1WTkz4t_FuUdjDsYRlNCa3SXHcPKOW

!procedure CommentBank($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/CommentBank', $name, $tech)
!endprocedure
