' definition of the Item material-4/Action/ContactSupport

sprite $ContactSupportXs [10x10/16z] LOd50S0W5CNgnRF_j4XkV7bwR0E_75ZQ93SEFZl22ofyrGldeJHosXBEjs

sprite $ContactSupportSm [12x12/16z] NOg50G0n2CIWxjb_sdTjAd0Y4vgBkTP6yd2i2UkICFOT6WYSEwW7U-vZ_tJREx0_sTbM1qaEyb6x6UygUlmh

sprite $ContactSupportMd [16x16/16z] ROw53GH100AvMzVflziFxpPHB47_EOvtjG3MCuCY5RXtOAXM3RPCW9pW212iEnWrQDRp9ZCmhAjb5DppWoT1Zy5fbzUTQJDQcBITThsntwKtGN-v

sprite $ContactSupportLg [20x20/16z] {
bS-50SCm4CNG7pDh_stRApCe_4As_gi1v5l9G1-0lr3PYnrlq0DIAuRhPCCUMv1jbux6gMIsxgme0jnQKUBHDd5Z0sijh7QqW1KYrdOxCMq0G-Sgvvmk-G5M
r5qtaxYnvVLOqgTs
}

!procedure ContactSupport($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/ContactSupport', $name, $tech)
!endprocedure
