' definition of the Item material-4/Action/Dangerous

sprite $DangerousXs [10x10/16z] Oy0E-440pE23CO44489PG19330nuO7fva0q3

sprite $DangerousSm [12x12/16z] Oy03-440YSdF1s424JSZM0OapmqaeMmW4y86C-7YZ4062r04RWutmb1kD3i1

sprite $DangerousMd [16x16/16z] ZSk53S0m40J1DmbCst-toIdCMT6FvRC_XJPMLqQcJgHFdo4L81QG6nIhH0FyP8e5SV9qrBsZQJAvYfgKoRe1YjvCCILExJZbbTqr

sprite $DangerousLg [20x20/16z] fSn50i8030NHZsiozpyjCZXiQ3lB5ydajc2pRn9_YHQbtYZBvoQmpiQTXdgOE4i1hO4OwTr8rhoRl_pvPluINxPC-RDWhys1vbh1KH8V7OHtTEk9rTVs6TGP

!procedure Dangerous($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Dangerous', $name, $tech)
!endprocedure
