' definition of the Item material-4/Action/DisabledByDefault

sprite $DisabledByDefaultXs [10x10/16z] uwS3

sprite $DisabledByDefaultSm [12x12/16z] unza

sprite $DisabledByDefaultMd [16x16/16z] un_X

sprite $DisabledByDefaultLg [20x20/16z] unzKO1G

!procedure DisabledByDefault($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/DisabledByDefault', $name, $tech)
!endprocedure
