' definition of the Item material-4/Action/DoneOutline

sprite $DoneOutlineXs [10x10/16z] Oy00d3065oy_L8IN0SXY0eg06VpyJ1064FE36M0cb06IHpCH

sprite $DoneOutlineSm [12x12/16z] RSsr0S0m0CH0XJdQVzemslxgL3t9PIydyuS3Nfn7hC4F1vadR22Nrl7W4VL5A3nuHnq_hW

sprite $DoneOutlineMd [16x16/16z] bSZ50S0m0CD0XpdUVzkcpAJV2J-Ib7lMVgnCA5mec65fpopSiRAoiS3GDKPg538Fx0lzM3aEs9xh6BaEsbNzw7bT1m

sprite $DoneOutlineLg [20x20/16z] dSp70SD0449H96rEl_zkVR9nJdDy0-ZFgziZmJqs9kntgQu0jpIbHRwXSQ6wdxTCSDodcB3Vf0feXqQNvoT5EquPdJAQZ2OZ9kC3IL4VxWG

!procedure DoneOutline($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/DoneOutline', $name, $tech)
!endprocedure
