' definition of the Item material-4/Action/EventSeat

sprite $EventSeatXs [10x10/16z] Oy0E-8603ON5p0XcCJCnyBE1MVmyA1eW0CG2SJdvaUG

sprite $EventSeatSm [12x12/16z] VSQr0S0m00Cm5vOsuF-l3JDf4WxewEOS_wjqTKCndJSwaj4J_hnEEhpmoW8

sprite $EventSeatMd [16x16/16z] ZSwr0G0X04FHSmMo_xIu-w_okYmpxOHI-WT3zsScKzv0l87IPTJtQSD7h0_TvMrVMs-RiHzn0W

sprite $EventSeatLg [20x20/16z] hSY30G0n343HMj7-svvj_39FVIv9rzoaB_nWrkgPMMjggtyp4y43qxe-NTrF7UHbtgavMwywc9dgoyFNCG-Mwk_zAW

!procedure EventSeat($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Action/EventSeat', $name, $tech, $desc)
!endprocedure
