' definition of the Item material-4/Action/ExploreOff

sprite $ExploreOffXs [10x10/16z] uwS3

sprite $ExploreOffSm [12x12/16z] unza

sprite $ExploreOffMd [16x16/16z] un_X

sprite $ExploreOffLg [20x20/16z] unzKO1G

!procedure ExploreOff($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/ExploreOff', $name, $tech)
!endprocedure
