' definition of the Item material-4/Action/HighlightOff

sprite $HighlightOffXs [10x10/16z] LSZ50O0030F0mvtiFotM5stSxv83x45Qf7Q5Q7jHy-QiRMnhAEtI6geQzXOt

sprite $HighlightOffSm [12x12/16z] NKc54S102Ckxa_stxI5dHQBuppmzrEEicyFaWGwRWgfcF0SIEm59k0KOsjsClj48GazV9obFSPcLEkLIfVSkFW

sprite $HighlightOffMd [16x16/16z] {
RKs50GGn28Ewalst_V1-aagi8lTG_NSBZlfs4PP83VlbCL-ihs0PvJk8NYUA8flnsXuogp3mJA4ExiLGk2Uy-utgGNNj_vfAxQJX_qBUo50dCttRzietLexL
QD-81c2gtE01
}

sprite $HighlightOffLg [20x20/16z] {
bKv5WaKn37frB_U_xOJgPhwnY0TuVaE4e9dd8W2zbYPHxr45zBxM-whihGRKA83BOkO-yjvbEUgAFEEiIoZ8Sc_uRJaRrmM07IU98KzMxlO9wXIiSuaWeOD1
7WjRFnnQbihGmJNMPRMH49RFRiwe7VEeF7NO8weMJF3nmkKQvVOb_W
}

!procedure HighlightOff($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/HighlightOff', $name, $tech)
!endprocedure
