' definition of the Item material-4/Action/InvertColors

sprite $InvertColorsXs [10x10/16z] LKc30G0n4Cizw-m_RSr3Y7Fq4AJfuWcigNaHo1gXA1xAIr5NhNrWG1ifa

sprite $InvertColorsSm [12x12/16z] POl50S0m00AfDyh-qyOzlB33fhDRnQjQQItlOWdBl1n4z4prcttarTtzPVe7_A9NqUPMO9O7

sprite $InvertColorsMd [16x16/16z] ZSwr0G0W00D1t27xJujhntTN9UGlZeS2m4ERW9kaEatIocR4OP_8C7WtrB8T5ij-M2-RRejbsaqGX_qUHAWCry6G75juAW

sprite $InvertColorsLg [20x20/16z] {
bS_50GCm3CNGxp1h_sdBpDNn1Qs_gqzYYoS4Q8-xuk9kfq7GuWudKGSZdwaHTJBEnj39Bkzuqick6oFXoGBnoOn-jN7vYbtCNR_iJzPrpiECUrkwPfsxAIwk
Jsq1
}

!procedure InvertColors($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/InvertColors', $name, $tech)
!endprocedure
