' definition of the Item material-4/Action/NextPlan

sprite $NextPlanXs [10x10/16z] LOo30G0n54Dpg97zfwtvleaBChJeM7bRfz4IlCRmBvaj2Zf4TjvZ3zz8AiBN7na

sprite $NextPlanSm [12x12/16z] NOg50G0n2CIWxjb_sdTjAd0YCwc6Q-lin7S5l-tSR5smfUbeg3G2CBPfPD-WT_Zt9LshoaPurmqrnrW1

sprite $NextPlanMd [16x16/16z] ROo50SCm3C0C3TF_tyuqhe8omJs8dpQFKiBe1Clzl5XH_88ZFPY7fBK0HKbg9g7SDYqlhK5GrtnLPI9pE1zqyVBX2C9-QGLZVQh2MZ8GRdW

sprite $NextPlanLg [20x20/16z] {
bSp50S0m40D1cTdglzemS-Qv1_Z7irCKLewJAZ59NCdTraGCZJjfUj-hTOhBce6K20oPr5EJWHshqBKmDXlPY-XR6fiUKi3G783AFGb0SmyuBRgXgMqgm1HF
2H1fTpWpCNk9Uoq
}

!procedure NextPlan($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/NextPlan', $name, $tech)
!endprocedure
