' definition of the Item material-4/Action/NotStarted

sprite $NotStartedXs [10x10/16z] uwS3

sprite $NotStartedSm [12x12/16z] unza

sprite $NotStartedMd [16x16/16z] un_X

sprite $NotStartedLg [20x20/16z] unzKO1G

!procedure NotStarted($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/NotStarted', $name, $tech)
!endprocedure
