' definition of the Item material-4/Action/OnlinePrediction

sprite $OnlinePredictionXs [10x10/16z] RSQt0O0m40GmaJEt_xHWzwzAIWiOCMsuNZ98iflbwEFo6gTuZ9m3ngZy

sprite $OnlinePredictionSm [12x12/16z] ZOZ50S1G24FVToVxJrixro3EhrlkifA1tdqOD2ze24bOSIocExE2ft1iggm6hEIOrmJLSNhsFDqE

sprite $OnlinePredictionMd [16x16/16z] bS790OGW50MmV71NUFrtErxdQEAxyYy5s0SysxBJU8oEI6r975SVr6X3NhS8RVH7NfS8DIlM92g2c8idtRDlDuwx6frD2cRHWktmsGy

sprite $OnlinePredictionLg [20x20/16z] {
jS-tGG114CLGpSvwz_ll5iut02zIAlv1uXFWK6KyojroArm6Um2qnPgahKbGCW4ect0Tg8iT0NbPD1tCnEY0GfjK7GpH1w2ODgPVWo1c1NP30PSsh74qHD44
Guuh977O7UCIKE7WilScB_xU3m
}

!procedure OnlinePrediction($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/OnlinePrediction', $name, $tech)
!endprocedure
