' definition of the Item material-4/Action/PermMedia

sprite $PermMediaXs [10x10/16z] Oq02_FpyV50M3A2ok60ie0e6C8i5h1n57HpmG043

sprite $PermMediaSm [12x12/16z] NShL0K0n24FHMtVOVzhdslC5IVZhOwJxr4tVj6wt-pRVmxytzC1vSuZRtJvxd3yv7VrYmTvW1G

sprite $PermMediaMd [16x16/16z] ZSor0K1120FG8Cq9iF-qtrtlTKY21pp0BYPqcHSrd-UmfdbiSTzc1MJQpNF1J9VPLezz4DrmkEnugjXLtFG

sprite $PermMediaLg [20x20/16z] bOw30G0n54DJkzb_shDzh_mEVi21kdKPZcGp8XRVXfpEFlAdpyIJBmA5z7dnZU844x3nINIexiZ5fx7WRkUA2n-4qbj4vpkHpsL0o7jmJGi

!procedure PermMedia($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/PermMedia', $name, $tech)
!endprocedure
