' definition of the Item material-4/Action/PowerSettingsNew

sprite $PowerSettingsNewXs [10x10/16z] uwS3

sprite $PowerSettingsNewSm [12x12/16z] unza

sprite $PowerSettingsNewMd [16x16/16z] un_X

sprite $PowerSettingsNewLg [20x20/16z] unzKO1G

!procedure PowerSettingsNew($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/PowerSettingsNew', $name, $tech)
!endprocedure
