' definition of the Item material-4/Action/Print

sprite $PrintXs [10x10/16z] Oy0E-440LGG2-5ZWB1uG2op3my361cQniMBJ2m

sprite $PrintSm [12x12/16z] Oy0DUFX1W0MTpSK30Mn09Zy4SF4pCl3omm0JYCtAnCJ42sKpGmnW0b5WDeQP2

sprite $PrintMd [16x16/16z] ZSx50G0n24JHYIlGVxNhhddHVmCD4itCqbLczhcrMQanvI03QY_d1D1oi3QDzguOpQrgNPlg_5cUjtcW5tZG0m

sprite $PrintLg [20x20/16z] fS-34G113030iwB-gttRs74SzHVAoBsDxMcIfTp6P8N5RM9DGE2W3dSncMEguwzY8GIQOYa4F_unngv_ApooweKQ

!procedure Print($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Print', $name, $tech)
!endprocedure
