' definition of the Item material-4/Action/Room

sprite $RoomXs [10x10/16z] Oq01VFnS40O_280OBFmy310M6pyJK1ukYs1nmxL0JM7dXnl82Y8

sprite $RoomSm [12x12/16z] NOl50K0X04BvQSl-qzhzJYHEVlDqoSoGbjHD0n_Pz0KrT4OMVIzV-17N5JeFSH81

sprite $RoomMd [16x16/16z] RSg50G0X30F0u0xxR_j8tZcqRR0d11vqw-gpd42jo_r4JB9_UK-gjGBWgaN_2RYhHYFFsh86CH2lMd5yIRrKU63wLh5t

sprite $RoomLg [20x20/16z] bSx50SC030Im2tEq_xHbvkfdTlvJhXXpQt1KvQ9tLkGCrjdjU8qvAU1sT3-qtEHQb4dMcrm9TT5ZpPcB_kazYZmrJhdg7ENMQg_DhHAMd5sdysXIvKcJJxO

!procedure Room($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Room', $name, $tech)
!endprocedure
