' definition of the Item material-4/Action/SettingsOverscan

sprite $SettingsOverscanXs [10x10/16z] uwS3

sprite $SettingsOverscanSm [12x12/16z] unza

sprite $SettingsOverscanMd [16x16/16z] un_X

sprite $SettingsOverscanLg [20x20/16z] unzKO1G

!procedure SettingsOverscan($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/SettingsOverscan', $name, $tech)
!endprocedure
