' definition of the Item material-4/Action/SubtitlesOff

sprite $SubtitlesOffXs [10x10/16z] uwS3

sprite $SubtitlesOffSm [12x12/16z] unza

sprite $SubtitlesOffMd [16x16/16z] un_X

sprite $SubtitlesOffLg [20x20/16z] unzKO1G

!procedure SubtitlesOff($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/SubtitlesOff', $name, $tech)
!endprocedure
