' definition of the Item material-4/Action/Swipe

sprite $SwipeXs [10x10/16z] uwS3

sprite $SwipeSm [12x12/16z] unza

sprite $SwipeMd [16x16/16z] un_X

sprite $SwipeLg [20x20/16z] unzKO1G

!procedure Swipe($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Swipe', $name, $tech)
!endprocedure
