' definition of the Item material-4/Action/TableView

sprite $TableViewXs [10x10/16z] uwS3

sprite $TableViewSm [12x12/16z] unza

sprite $TableViewMd [16x16/16z] un_X

sprite $TableViewLg [20x20/16z] unzKO1G

!procedure TableView($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/TableView', $name, $tech)
!endprocedure
