' definition of the Item material-4/Action/Theaters

sprite $TheatersXs [10x10/16z] Oy0A-3dv-O4On680iXZ0B3309OQf0m4

sprite $TheatersSm [12x12/16z] Oy09U5Xu-FdvcNcOGMn-262caJW2

sprite $TheatersMd [16x16/16z] dOs50G0X30E3Uxl_jE_kpw6r1EyK9KiFGXnYjfPxLCvZl335MWqHvdefGrpcEj4Qd_lFUjRCVbN-ijizwFQ95W

sprite $TheatersLg [20x20/16z] hSz50eGm40J0YNlt_r-xYyC5fsx9kBpZQ8M3B9NpNqaSj8JbR-kercaEYgw7jIbmq48xx4Tm11xq-_eE2oCO9CcGw_u

!procedure Theaters($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Theaters', $name, $tech)
!endprocedure
