' definition of the Item material-4/Action/Theaters

sprite $TheatersXs [10x10/16z] uwS3

sprite $TheatersSm [12x12/16z] unza

sprite $TheatersMd [16x16/16z] un_X

sprite $TheatersLg [20x20/16z] unzKO1G

!procedure Theaters($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Theaters', $name, $tech)
!endprocedure
