' definition of the Item material-4/Action/ThumbDownOffAlt

sprite $ThumbDownOffAltXs [10x10/16z] RSQr0S0m0C0mbxd-_zfmjcWIGwy9lY39dhQjVTAtgjphyv9u_rH-D0TP1

sprite $ThumbDownOffAltSm [12x12/16z] TSQ50G0X34FHd0kI_RV57Hwq_LWJqjfXFnvnMWHj4uxlNPTMH-cJLcohXCMI6pVq3

sprite $ThumbDownOffAltMd [16x16/16z] bSUr0S0m00CmXpd-_zeoUQmsuJ_7amMvVpQ_c-syeS5kzFDzG4udjuJSSDUUmpZd8k4POHrEbO4Phpcbe1RfKxK2

sprite $ThumbDownOffAltLg [20x20/16z] {
fSg53GCn0CNGduRH-qzRPZfwOilQolaB8-syEwV6ZGHDHuRgpZp-rZ9M5uHRO-YzUTnxksplhNnfZADkdvlZh4i5ftfk5pHbcfuPSc7eXQE_NLA2hZVkVBs9
-ky
}

!procedure ThumbDownOffAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/ThumbDownOffAlt', $name, $tech)
!endprocedure
