' definition of the Item material-4/Action/Translate

sprite $TranslateXs [10x10/16z] Oq01F12A7mpO6A0yACt7oCN036PnyWD5MS5oFDmiZFmGHSpyd72bCACuGOO2

sprite $TranslateSm [12x12/16z] NSb50W0X243HRoTo_zkEmMgUqlnqRysSKsKdjdX8YdO1nKYII1nSkdQyqrWQq1w1AJjQvXo4JJVCWjou79l_

sprite $TranslateMd [16x16/16z] RSm50eKW403HiVcnpFrFQxS-cWrUbLnKidFtPr8l8kgAHJ5TF5eKu_qdXsGjO6OLDb1emQnMuHlnNP-9BDQrZ1eJq5LMumHIOf8T1JiBADoVdOnikHa

sprite $TranslateLg [20x20/16z] {
bT054iCm34JHbIith7__stRaS3BK5uv1eFymwy9hOgcfg0aklce-lbbmDzqnw6B0jji58MFCZOfsbO78Nt1TJSwOe6fJe4LWYj06V6QIOpsspt9f34M6wlTP
oW36CcIi5Awcfp5THBmwL6ZpHtGQPgKok_Js0m
}

!procedure Translate($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/Translate', $name, $tech)
!endprocedure
