' definition of the Item material-4/Action/TrendingUp

sprite $TrendingUpXs [10x10/16z] Oo06CFBpW2WWmSiDOl7pSFDoCO0OG45kY1GU

sprite $TrendingUpSm [12x12/16z] Oo01iF3mCC8vtFnC88gD6uZvEO1i8CNFpShF01O5KlmG9b245

sprite $TrendingUpMd [16x16/16z] hSZ50O0m0CNGuCxVVrgeoxdDxOL-7VTzK_P8-1PCWw9NNPOFR-1kXY616wCgmXY9OTL0Ipy

sprite $TrendingUpLg [20x20/16z] nOo54OG040FpZtEo_LUBUm6mOvcOtkPdxjuzJS3rm2zUlQh03g-6NfBHgV3TIiSKIt1OF_KatTLQx-tMMeKEFFK18m

!procedure TrendingUp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/TrendingUp', $name, $tech)
!endprocedure
