' definition of the Item material-4/Action/TurnedInNot

sprite $TurnedInNotXs [10x10/16z] Oy0AEDc0W0VC8fhWu-U4iFWP61Y1604

sprite $TurnedInNotSm [12x12/16z] Oy0D-240pAQCPEA1i_dvs61cye089ZvKIm4

sprite $TurnedInNotMd [16x16/16z] Oo02SF220GypXClCpmC6lFnGFlrfPbv-BaO4dv-VXusFdm_EvmHHJ43t4GO

sprite $TurnedInNotLg [20x20/16z] rP2r0S0m3C32dEZ_Qyiy5QRAhD7Y8vADihg8MoXixW-RSbUd6X1Fha5o5Th14SOfAvlpTljG40_e0G

!procedure TurnedInNot($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/TurnedInNot', $name, $tech)
!endprocedure
