' definition of the Item material-4/Action/ViewAgenda

sprite $ViewAgendaXs [10x10/16z] Oy06-A406uiCTG

sprite $ViewAgendaSm [12x12/16z] Oy05UFbX03UR6ywccbu

sprite $ViewAgendaMd [16x16/16z] Oo08U7ZXW0V8PU970aoaynbuaG0MwnXHrLDk7nCImBGE

sprite $ViewAgendaLg [20x20/16z] Ow08yAC27YnYV5GMumM9iRAZ06PSxkFbGm4Sj7KVGem7tLwY0G

!procedure ViewAgenda($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/ViewAgenda', $name, $tech)
!endprocedure
