@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element ViewModule
include('material-4/Action/ViewModule')

' renders the element
ViewModule('ViewModule', 'View Module', 'an optional tech label')
@enduml