' definition of the Item material-4/Action/WorkOff

sprite $WorkOffXs [10x10/16z] uwS3

sprite $WorkOffSm [12x12/16z] unza

sprite $WorkOffMd [16x16/16z] un_X

sprite $WorkOffLg [20x20/16z] unzKO1G

!procedure WorkOff($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Action/WorkOff', $name, $tech)
!endprocedure
