' definition of the Item simpleicons-5/F/Fedex

sprite $FedexXs [10x10/16z] uwS3

sprite $FedexSm [12x12/16z] unza

sprite $FedexMd [16x16/16z] un_X

sprite $FedexLg [20x20/16z] unzKO1G

!procedure Fedex($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fedex', $name, $tech)
!endprocedure
