' definition of the Item simpleicons-5/F/Fedora

sprite $FedoraXs [10x10/16z] uwS3

sprite $FedoraSm [12x12/16z] unza

sprite $FedoraMd [16x16/16z] un_X

sprite $FedoraLg [20x20/16z] unzKO1G

!procedure Fedora($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fedora', $name, $tech)
!endprocedure
