' definition of the Item simpleicons-5/F/Fidoalliance

sprite $FidoallianceXs [10x10/16z] Oy0FE7cP61WOGIn-98AVbOMVaHL8C_1o0ZaGOGPcY4fC

sprite $FidoallianceSm [12x12/16z] bSQt4S0W0C10-SuvQVzfoVJmrJDB4Uwrd6HDNylzLrSn_vMd_rayrykJ0H4

sprite $FidoallianceMd [16x16/16z] hSVN0S803CL0lJYzMFjFIsS2kB_ZtmQR0s1_toq8n5VRhkwaDndw0cSmZhCud7vFBAdtvxWVudGrMq6HepQoh_pg3W

sprite $FidoallianceLg [20x20/16z] nOk55SD034CL1iFVVzk-mn4QimNwB1v2QxsM0LtOAhoSMCUCVapi0Z1uPIIccs9nYk8zs5TiuLXu1rOMzfIP3OltgTXHfWzC0AOaMJLZgtDPzPVu0G

!procedure Fidoalliance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fidoalliance', $name, $tech)
!endprocedure
