' definition of the Item simpleicons-5/F/Fontawesome

sprite $FontawesomeXs [10x10/16z] uwS3

sprite $FontawesomeSm [12x12/16z] unza

sprite $FontawesomeMd [16x16/16z] un_X

sprite $FontawesomeLg [20x20/16z] unzKO1G

!procedure Fontawesome($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fontawesome', $name, $tech)
!endprocedure
