' definition of the Item simpleicons-5/F/Ford

sprite $FordXs [10x10/16z] XOU54O0030EhQAw__xJ80X2F_I8xtYeQDpW6qFbyJ33YLDidRW

sprite $FordSm [12x12/16z] bKn50S1033igG_oh7JZO-cbu_Bufwk6Y3pHKS2a0Ri3an9WE3Es5HQ0kUmigBF9n_GO

sprite $FordMd [16x16/16z] jSV70SDG20KmVgF3st_Qz6nWwoQwmH0H5ZtVQROgHmVAZ4O2oI5uSU0q04FjsBLU1p5gyVQiEGqTH5ky6kXALVgRQz8bdW

sprite $FordLg [20x20/16z] nSVL0S0m409GOYT4s7_QobT7w3i5FsjzzFf5SvBhdBt8j0R0kwGXUG7qs2p6ztPsryianT4ZrPVDXj7vfX9Ii6taSP-5qWfWcOwUNjAUMZxmwkR9LvfL_ES6

!procedure Ford($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Ford', $name, $tech)
!endprocedure
