' definition of the Item simpleicons-5/F/Fsecure

sprite $FsecureXs [10x10/16z] uwS3

sprite $FsecureSm [12x12/16z] unza

sprite $FsecureMd [16x16/16z] un_X

sprite $FsecureLg [20x20/16z] unzKO1G

!procedure Fsecure($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fsecure', $name, $tech)
!endprocedure
