' definition of the Item simpleicons-5/F/Fsecure

sprite $FsecureXs [10x10/16z] Oq00VXZWXRCO-Fb0Can05Yy_Bvf260kYXfMRcO4BBCtDpyyDLmaY0G

sprite $FsecureSm [12x12/16z] JSc50S0W40J1mvtjlzguCF2kLU9b9p_BJ_YkY_Vo99joq8N7N7fx7MPEZQbJ0FJgwp0nPza1

sprite $FsecureMd [16x16/16z] PSt50GD130J1MMPr_j6QVLWliNJZ1t_PAN1cd7dE13dfAmwIrWBpsf7zCB2LzU7PEUdqKMzsQh_GOd9Ag-Wh6U2r6xmqxUoxl1l_z0a

sprite $FsecureLg [20x20/16z] {
RSo50S0m30Cmbp7n_z-kOweE4EPCB5svafeS1k5NQlmJ_bd-L91KZuDTAuyUih829sC09-kQyCBiid2ZzLmQdmfMVB5O1JueTif1H3dWn62REW3Lu1GwXu2N
nbN3Yt1by7B-BoaR71O
}

!procedure Fsecure($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Fsecure', $name, $tech)
!endprocedure
