' definition of the Item simpleicons-5/F/Furaffinity

sprite $FuraffinityXs [10x10/16z] JOE50OH0083GwsJ_QRz3WYl2uir4WChCd2JeLGCgg0aFw8zZLhChfeJAwM4JW5HvSGS

sprite $FuraffinitySm [12x12/16z] NSQr0GD054EnztsCtd_QS1LLua-3cD_sI_NvjclY3Z3HxdbLMymusQNONZ1yNTgU4vHNG0nxweweyhKF34Ifnm4GfwLL-18_Jm

sprite $FuraffinityMd [16x16/16z] {
RSV5OKHH34MnOp-6xzj_jSamQoT-CTx9uP1pKqUjg9NRUlTcxFiBzEMejbWPHYLBqGETR7mKkRHhaPeP3EcGIdBDR42POS2kEW5BGu4jwz8ITIkbYVPAKWZw
nckqsYIZWAUvSJKDuwgpmFdj7m
}

sprite $FuraffinityLg [20x20/16z] {
bS750Tqm5031bKLFvEs_si37Ms26_s83EF9L5PeUlZ9v1rDvIJqY5w7joKiKsAt1lc1MW9GIjMelbckfDyGacaVpPlW0QoxBrhljMoiFpOUQ6CuK0Eq-pWmK
GdK1yqfIeSmsF2hqDQ8V2FVecaoqRJsfKAqT7w3ln7MN5ItKH4gGht2cfaCF7pEkYx8AVDKL_CrF
}

!procedure Furaffinity($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/F/Furaffinity', $name, $tech)
!endprocedure
