' definition of the Item simpleicons-8/M/Mastercard

sprite $MastercardXs [10x10/16z] RSY50O0m3031nvtVVrfSsruy9FLsp1QWJkugTuM7wyinERRB23H0pSSA

sprite $MastercardSm [12x12/16z] Oo0Ay0C1AuY0C3dvcK4K1pyOyF6Z0HO8nGlM017W0AbZOE23Yd3Xj0a

sprite $MastercardMd [16x16/16z] dSl50SCm50DGcTdQVzjMuLlW6J_XWrmSW5GZPF2l1qe29gNJKm8e2lQ2P9LuIYInLIHkkJEhSK6Yn6qSWDCxiTvN1W_y

sprite $MastercardLg [20x20/16z] {
jOzL0i8m50ItxfdxdnRPBFOBTDeapqKdi0ABf09qjWoOUIX-oyjqx4H2Yj014sQ9Su_T7Aa6iF51z_I_V4ik8qmvNZ9AGWjxn5vnCZ9WTjse9HSLluCgtPGr
nqO_SWK
}

!procedure Mastercard($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/M/Mastercard', $name, $tech, $desc)
!endprocedure
