' definition of the Item aws-q1-2023/Architecture/DeveloperTools/AwsXRay

sprite $AwsXRayXs [10x10/16z] FSY74O0m5CDGq_bb_tcHWKJNtYapwAQSHESbY7nNnLsvcg6e0d179VOTrYKTt7wPr6PP3m

sprite $AwsXRaySm [12x12/16z] HOe54i0m408d3bp-_zwMIsN7a9LeOFGNPw4XYoF9jPYvfWOY755zCQAuQNBUEJfPrGgT0wMWwkGfBKdSOIYpJyby0G

sprite $AwsXRayMd [16x16/16z] {
NSZ70S0m3CD0orM4il-wwPql7a37_1Xy2zzmkETSpW3W0ydw7W0o85VPGa3hmFQpIn6iz5HiBROvEaD0kTqoPAEMiJkYKbONT3eFIqaTJbC00z0K-tfrzard
24x_mW8
}

sprite $AwsXRayLg [20x20/16z] {
RSt90SGW30H1ReOM-SUxMldwqByf6m3Ma-uu80Vanga77njvZXJwcXe-YqRWPGKSLPG2xJ_pyr3fVpHZ5NWm_ZIp3YZtqQhlfjUkNulR2YEh0gFGryXXVqsW
Kf2q7ZEtwJONdqqbhnVWDQi2sYHmtpXJoa3W3enusWVS1_m1
}

!procedure AwsXRay($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Architecture/DeveloperTools/AwsXRay', $name, $tech, $desc)
!endprocedure

!procedure AwsXRayCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsXRayLg>', 'DeveloperTools', $funcName, $content)
!endprocedure

!procedure AwsXRayGroup($id, $name='Aws X Ray', $tech='')
  IconGroupElement($id, 'DeveloperToolsFamily', '<$AwsXRayLg>', $name, $tech)
!endprocedure
