@startuml
sprite $BrandTraefikLg [20x20/16z] {
TSpBaSL024DHa11CE_-01xj_gtTst59Xat_CBW1T0DuAqK42eHtzxnaHAUfvSi_6e1bWLa_jtHXzitkSdR48L88gNpFpR41cgSyPaU-fofJl8IHbauJLg5Ud
5zQkJalP0hO8Dkpcj_bfQ15ejvr_OOTguMt8cMINWo45t7xw1m
}

sprite $BrandTraefikMd [14x14/16z] FOw50S0m20JX9RB_mgMnY-8VHIvYGoO0OXcOdHBdM55EHYBQtBbDS6t7Ggr9lN4PMLPXxZhRPTZOCSckAnO0oBgsnHqx5lfFozXejOp7rVm1

!procedure BrandTraefik($id, $name="Traefik", $tech="")
  PersoElement($id, 'brand/BrandTraefik', $name, $tech)
!endprocedure
!procedure BrandTraefikCard($id, $funcName="", $content="")
  PersoCard($id, '<$BrandTraefikMd>', 'Traefik', $funcName, $content)
!endprocedure
@enduml
