' definition of the Item azure-4/Item/General/ServicePowerUp

sprite $ServicePowerUpXs [10x10/16z] LOc74G1120BNXFPVyS_dkpK2R2JYx7Cvd9mgSLAeX9sQxZvpEJDsvkTyc7CYN2Ja0G

sprite $ServicePowerUpSm [12x12/16z] JSh50SGm30J04SRzDtpWLuHBtjLKcc90Lg2v9vFHBe-mDxpx-uBs_2eD6-cSeuMIuL4qHDrVRYsKwTaGNHLV

sprite $ServicePowerUpMd [16x16/16z] NSX18W0m402nT3jT_lzXS9HZ_7UQ6hoj9T0Bh86p9x32X635N10oJbxUI8TM-uiMx-hZ5nrEyVaZT-Bn5y_978l8USY5k442zmt8GdiQ67QtWrEDRm

sprite $ServicePowerUpLg [20x20/16z] {
RSZ7eLi130CmIEAZlV_2wJqVH_ZGvPA3IPzqEJ1PBUWA8Cy2ue2kBF08w60FHA301Xitb6F7BaLqj7tQSxF5vNXzyv07XD-tWMxe-wintM5hZ--bXE2Mr_le
SAEG1GNh0NjC5vm7c6m1fy0-MM3E5jioEKomUH9Wzcxv3
}

!procedure ServicePowerUp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServicePowerUp', $name, $tech)
!endprocedure

!procedure ServicePowerUpCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServicePowerUpMd>', 'General', $funcName, $content)
!endprocedure

!procedure ServicePowerUpGroup($id, $name='Service Power Up', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServicePowerUpMd>', $name, $tech)
!endprocedure
