' definition of the Item azure-4/Item/General/ServiceServiceHealth

sprite $ServiceServiceHealthXs [10x10/16z] HOS50W0W4C9cWV__i1sxOF0fKa0Iw98y2FCDmqHIOfPCjaQjr06COCh4KmvBEW

sprite $ServiceServiceHealthSm [12x12/16z] LSR70K0n24Enbm0s-q_yUubEOY49KfhitPLs-pzXxv0ZOjWv3PaItgESs8D19Trk0-gcTx1JFztbrrt1RWC

sprite $ServiceServiceHealthMd [16x16/16z] ROU70K912CL2P_-9XVjspPMyy4kahonZfRd0aQxV-Mwnki2F_BHEKmu8crI2arMd4SVdtucOsAXxRYkWEfjUagLcn6PnaHklXDXCNcYtyPSR

sprite $ServiceServiceHealthLg [20x20/16z] {
VSi5OWKn24NHIx2t_nMtq7wNCvC4vGDpUmgoXe5lu6oqx1f0lNXRyxwmIqZqc1kwax7DeYOzZRaxx1hUX-1i1ZMtqqH3x19KSOGZ9P8Qu43BCMaTHcqtj1BM
n6WL5wL_oKrh1VTSlumd4j_y
}

!procedure ServiceServiceHealth($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceServiceHealth', $name, $tech, $desc)
!endprocedure

!procedure ServiceServiceHealthCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceServiceHealthLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceServiceHealthGroup($id, $name='Service Service Health', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceServiceHealthLg>', $name, $tech)
!endprocedure
