@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-4/bootstrap')

' loads the Item which embeds the element ServiceCommit
include('azure-4/Item/General/ServiceCommit')

' renders the element
ServiceCommit('ServiceCommit', 'Service Commit', 'an optional tech label')
@enduml