' definition of the Item azure-4/Item/General/ServiceMedia

sprite $ServiceMediaXs [10x10/16z] 5So53SG030D0DGnElV-q3y8J7VaUW2EvtGiCY0Ytc9shS7aUpTcidqIZgzf5rA9o9atD8khcPuz840Fy9vB_62_v1G

sprite $ServiceMediaSm [12x12/16z] BOu53WCm30FLCBNv_s_dJJj1EFRklZipTxzPLoFlVll2p3q7dMqpPIAjgeis7I1PvH54XrWYmpEOa4g4LwKmKd6BmP4XDJCymljqDmi8z4-ge0Nk_3ry

sprite $ServiceMediaMd [16x16/16z] {
BSu54iH024JHoWWEkVzjjo7xIn-ZBwgCYCnwlw39OXPLHCrXdu5ITyLX399Rwrb7OIi5zthG8iK69kOXTeYP4gkiXVtxmCgi9dij45OcRQFJPcBlCsTyYKZB
p5pldvnlmE52a-636Cnd-zy5O-0n9T3Lfrdy0G
}

sprite $ServiceMediaLg [20x20/16z] {
9S-7aKKX34FHsKzma87-krqz-Ku-H3zrJx5pNzVI0LHL2LINMQAqlSq3iaPijUREAX3lkowQlx-_OIWQUjkYiD-CP2TusIOr3gV1UB_JcYOjtBQd_zWdypCt
ysWZoKAKFaOJBNWPaZO7ana7Y4hcQxQjpV10Ar0bpEyxD5IbjMpx1jRW3E76aYH4AI3nkWjQTmNgd2hwUUeV
}

!procedure ServiceMedia($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceMedia', $name, $tech)
!endprocedure

!procedure ServiceMediaCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceMediaMd>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceMediaGroup($id, $name='Service Media', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceMediaMd>', $name, $tech)
!endprocedure
