@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-4/bootstrap')

' loads the Item which embeds the element ServiceDevConsole
include('azure-4/Item/General/ServiceDevConsole')

' renders the element
ServiceDevConsole('ServiceDevConsole', 'Service Dev Console', 'an optional tech label', 'an optional description')
@enduml