' definition of the Item azure-4/Item/General/ServiceInformation

sprite $ServiceInformationXs [10x10/16z] HSY50G0W30F1HvFz9wRurGjVwXDGvrohf3ORMI7DrkzFsNR7WRl1V4w4EJiC

sprite $ServiceInformationSm [12x12/16z] LSR50G0W34FHuEo_C5BlFoGFkJvVWpWbeUvwpV6tD5gitmnk-rNmTu4ikym07V7NliR31G

sprite $ServiceInformationMd [16x16/16z] PSc50G0X4CJ0uDT_mo-Bmw01kBcKFudcBmazkmW4tK27XoAuThRkIFkxotlxQ08cZhtlqw_jW6n3v1TxUfeqFry

sprite $ServiceInformationLg [20x20/16z] TSe72iL030FHiLd9U_yB_nA7z3oQ6CIh8TiQoIQysKu-Y7lgP_OSq4E0Qo6e1jGDMQk8hQcQO6k-jz1iXhaYxmrkhS3N1iIb6I3d2OjnIMqhXasgVa6qBm

!procedure ServiceInformation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceInformation', $name, $tech)
!endprocedure

!procedure ServiceInformationCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceInformationLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceInformationGroup($id, $name='Service Information', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceInformationLg>', $name, $tech)
!endprocedure
