' definition of the Item azure-4/Item/General/ServiceServiceBus

sprite $ServiceServiceBusXs [10x10/16z] LOo30G10200pzb_uZIuJ2cQs4dTpxv6yXvdvyH4X0j83P4edCtjcdPwD9sCqYTLe

sprite $ServiceServiceBusSm [12x12/16z] NSQ74G0n20F1SnJqt_2BCPD-7KxydNjejmniIA8UNFMU417Y9Mnlzd5dPcuxBdxNvCBfVIbfujastGy

sprite $ServiceServiceBusMd [16x16/16z] ROe95iCW44AP5NF_2rUSxkrFLFu3_CVStYnQn4ETx2OP3rNaHgRmxdnpDdo9Kg70evcEp6cEYrdYsYoAIo3trIAb2HZ7Q-ySXoNQ5CSrBPK_t

sprite $ServiceServiceBusLg [20x20/16z] {
VSW70WGX24FHg97W_I-ymavlpyh7fr8keLfeEEYsmAP9ca4IZqa5NHDIbQwDEZNh09GQWYc0_bSZULeUaWMDF4PECpLF686BaQ2ujSWa81vRPCD4FpJlM9Z_
uS17khQ4Lpy
}

!procedure ServiceServiceBus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceServiceBus', $name, $tech)
!endprocedure

!procedure ServiceServiceBusCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceServiceBusLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceServiceBusGroup($id, $name='Service Service Bus', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceServiceBusLg>', $name, $tech)
!endprocedure
