' definition of the Item azure-4/Item/General/ServiceJourneyHub

sprite $ServiceJourneyHubXs [10x10/16z] LSQ50G1H20BGQrHW_t6lwnlm754Hp3Jd6Vij2siSzufFyoKWbaRJT0ZGhlWKaGWvWbMgyWO

sprite $ServiceJourneyHubSm [12x12/16z] JSx50KC120FG2adm_RUjoqSVDpOYAw8gSnkW08diDiFNTRtQOpjnC3-MVlQ7HNNPnthQyF7qm-6Fa4_3-F3pdESFNTMFtZi

sprite $ServiceJourneyHubMd [16x16/16z] {
RO-50G8n34MHQ2NTVriYm6dqlthNwBrFByE6sp92HF549IAsZQKO0K1ya8edlDzlPfUnY0xi2yoAtMhzndhFkB6Nxtt9dbAiulB0RbVsKkzlmL7KyhysnvXP
rWS
}

sprite $ServiceJourneyHubLg [20x20/16z] fP350G91303H69B-koN6kTyy8hE--lqOtsvKfQT16HaDLaNlC2E1GJFkOK3VmTruPXSZMrn_BHfd79CxBWUSpgExXu5zX_iS6TFEaVfJaUXUvUg_FMh57m

!procedure ServiceJourneyHub($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceJourneyHub', $name, $tech)
!endprocedure

!procedure ServiceJourneyHubCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceJourneyHubMd>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceJourneyHubGroup($id, $name='Service Journey Hub', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceJourneyHubMd>', $name, $tech)
!endprocedure
