' definition of the Item azure-4/Item/General/ServiceLoadTest

sprite $ServiceLoadTestXs [10x10/16z] JOk50S0W40FVa_qNRd6uTucyH6RwR5id4vFTgTHiMd5VNGPwWoxmrZ8dfTpy

sprite $ServiceLoadTestSm [12x12/16z] LSk30G0m30J0ZxF_mZMlZF1Zwp3f_Vx_rlVy1OklqmIX3IWQSL4Q6I1jolRr9OBogW

sprite $ServiceLoadTestMd [16x16/16z] XSU50S0W3031XsZt7xZknYF9yPBO4bjbuL7Jm8-hIyKFkqoVRJGVdn6oK6Bw38t5eLC5mcU6RQM0f1ybvCcHINTj

sprite $ServiceLoadTestLg [20x20/16z] {
bSg55GGm20JH2R0B_JTyxduJ_o-yAtNk1al7afjkw7yBuD7MitblVZGbrXrvl-VjntH0AUnriJOW5UqBDIiM0Tbr97LfNq6wOqynrhNflStejZ5uV5TFh7cE
VifR
}

!procedure ServiceLoadTest($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceLoadTest', $name, $tech)
!endprocedure

!procedure ServiceLoadTestCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceLoadTestMd>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceLoadTestGroup($id, $name='Service Load Test', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceLoadTestMd>', $name, $tech)
!endprocedure
