' definition of the Item azure-4/Item/General/ServiceBacklog

sprite $ServiceBacklogXs [10x10/16z] FSor0G8130NGbk_xJmkSlYQUhTaffQm_4oe-VrZUQK3YZ_fFh-n_wckgGDU5u5rVrjr-

sprite $ServiceBacklogSm [12x12/16z] JSor0GH134FHQC0W_VwhFLnwYTc0kMYt_wAYjERNKXRqZx1B_BLoL-olg0Zvo6cRWz6kupRo-RF1Vpoy0G

sprite $ServiceBacklogMd [16x16/16z] TSwr0KKn34FHve59kljF-vdXL8cP7ofvaEczr3UJMT7KUhChi-6H5nviNYd2TtGhzkxz9YeYXkUVgG4UzM2cUR2PFP_xCZlIZtksoIpZlaDj-Ey8

sprite $ServiceBacklogLg [20x20/16z] {
VS-53GCn341HKMFstt_QyZ4yHHGpLyhxyAKZMCcWLBnTPsxVHyjZ9kLc0OHDl6XFpeGT_aD6TCtQhKB4MyPC_JiTLdz2_EQkQo4JceEGPANxyoMvtjaqGZJN
jutFN2jmNH3cnLxDNtTU
}

!procedure ServiceBacklog($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceBacklog', $name, $tech)
!endprocedure

!procedure ServiceBacklogCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceBacklogMd>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceBacklogGroup($id, $name='Service Backlog', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceBacklogMd>', $name, $tech)
!endprocedure
