' definition of the Item azure-4/Item/General/ServiceGlobe

sprite $ServiceGlobeXs [10x10/16z] JKo50S0m3AA2vF-3vzAu05YiJKhWCSMMD065zZm6k99xGdsZZcbU3E8jwEIdwBFk

sprite $ServiceGlobeSm [12x12/16z] LKs34G103Akn_y1lvb14y4F4p43xwYw-ZmXtD-MsKuOqgW40CoFwtZKvZw6dleiGjRrzH1579hQLbNSR6coeslXN

sprite $ServiceGlobeMd [16x16/16z] {
PO_50GGm3CC2Tfhkl_2vSAoVL8pPFm5MbHcFai1GyDmXkbdBo-XoTlSO2ao4V7QZv022onMq0yAtdr108kMuWJ26dGqAP_kcPs4qpdC6cZDfGPq-GPgalmU8
h6iN7vy6YlFO0m
}

sprite $ServiceGlobeLg [20x20/16z] {
TSq75iGW30DH0P9jxd_XzL9U-gJ_KF1LeSoC1MW7SQ1LI9DgM9eFB9eZFS8p-mTop4mRw2Or29abIPunczPxX2b7wZ1F_ETsMEqR3qC_aE0qBkJOjc5aq-mO
XeOM8ka7GIgFDr1guoHmL9LLt2kE9xbkmXb6Fm
}

!procedure ServiceGlobe($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/General/ServiceGlobe', $name, $tech)
!endprocedure

!procedure ServiceGlobeCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceGlobeLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceGlobeGroup($id, $name='Service Globe', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceGlobeLg>', $name, $tech)
!endprocedure
