' definition of the Item simpleicons-5/H/Hbo

sprite $HboXs [10x10/16z] uwS3

sprite $HboSm [12x12/16z] unza

sprite $HboMd [16x16/16z] un_X

sprite $HboLg [20x20/16z] unzKO1G

!procedure Hbo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/H/Hbo', $name, $tech)
!endprocedure
