' definition of the Item simpleicons-5/H/Hcl

sprite $HclXs [10x10/16z] Oo0Ty7FnyuCeeZK

sprite $HclSm [12x12/16z] Ow04i80GCpiZYC7F1OH0CLu-Yem4

sprite $HclMd [16x16/16z] lSM70G0m4050wPtzjuqbali7VYEHcIh56La1xIajmOuxPoSYjkerF7O1

sprite $HclLg [20x20/16z] rS475O105C2mik6FL_zg6IwuX16LEuUrj5SQgm8QeOloQNSuue08jgYAbVZmSmy

!procedure Hcl($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/H/Hcl', $name, $tech)
!endprocedure
