' definition of the Item simpleicons-5/H/Hellyhansen

sprite $HellyhansenXs [10x10/16z] uwS3

sprite $HellyhansenSm [12x12/16z] unza

sprite $HellyhansenMd [16x16/16z] un_X

sprite $HellyhansenLg [20x20/16z] unzKO1G

!procedure Hellyhansen($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/H/Hellyhansen', $name, $tech)
!endprocedure
