' definition of the Item simpleicons-5/H/Hitachi

sprite $HitachiXs [10x10/16z] Oo0PyBFpix3oSZ5myXEh0m

sprite $HitachiSm [12x12/16z] Ow00S3CmSN0piZ3oi32myhCpC_3oyV8piB6pKs8c

sprite $HitachiMd [16x16/16z] lS475O0034Inp-g-L_zkKG49FrlaZsBwIDaHn_ewpIZ1ee-XZ32moGVZQoy

sprite $HitachiLg [20x20/16z] rOC70GCn30ELwMtnPzl0wD_01o5WdAAhUZpl0fKYHknpRXq7hWcrWVS-FOQdnPremP_p0m

!procedure Hitachi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/H/Hitachi', $name, $tech)
!endprocedure
