' definition of the Item simpleicons-5/H/Hyper

sprite $HyperXs [10x10/16z] Oy0E-E4CDXW38OHWmbciS25kg19-X64

sprite $HyperSm [12x12/16z] Oy03k15CFYOuavyVYScEn4QIuEFdGqXmmPdiR22I5mGO80OoWG2odG

sprite $HyperMd [16x16/16z] dSsr0S0024HHYFlVVzguS4tiLJZsHwVfq4WA7ZA78QG98ECrGANxr25D8TTsQj7-hUbNrjYcR5RsO08

sprite $HyperLg [20x20/16z] fOsr0SKm30LbPj_-qtv6gKkkV2ZdALOY6ccZ5GTPIH5GKWQwbLZ1Lcrx0gH_hGDU_e4jYWIYORxVrWlnurju8LuESmK

!procedure Hyper($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/H/Hyper', $name, $tech)
!endprocedure
