' definition of the Item aws-q2-2024/Resource/ManagementGovernance/AmazonCloudWatchCrossAccountObservability

sprite $AmazonCloudWatchCrossAccountObservabilityXs [10x10/16z] NOg50O0m4CI2G_RV5wZBwnbJIQoxeEUHfHaQrXFF_x3iu1NGuy5_YU68Ozqty04

sprite $AmazonCloudWatchCrossAccountObservabilitySm [12x12/16z] NSk50SGW50MmuBpkl--vDkWtPxN6GrhPkeTcjFtEfte9vV5iZXk6up6VpL96CECH5BqIpTkZz9ODLm

sprite $AmazonCloudWatchCrossAccountObservabilityMd [16x16/16z] RSs7OSGm30GmgD3YUVzzqtiU2y1ZA_6fBiBXJH4n5cyESJeJRv9LADuqDM5seI7eGSZz2dlShJv3nj42Oq3jdczf9mVAQWIQzcPxSySlOmm_NPStpm

sprite $AmazonCloudWatchCrossAccountObservabilityLg [20x20/16z] {
VOw50GGm20E1MiB-0pzDtorL3hL_2kA35Sc7DO1btbuOj6dnmG2k1vi4bUUueSQeRI_Aax_L4yaTff2O-xilv_P9KnapwxXo_3nPgtk4qEhpiCLRt6YdXnlh
eX2H6FKfr2cqb3VhnctAhdJr7_OYpSbtvXYm3-YttmK
}

!procedure AmazonCloudWatchCrossAccountObservability($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/ManagementGovernance/AmazonCloudWatchCrossAccountObservability', $name, $tech, $desc)
!endprocedure

!procedure AmazonCloudWatchCrossAccountObservabilityCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonCloudWatchCrossAccountObservabilityLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AmazonCloudWatchCrossAccountObservabilityGroup($id, $name='Amazon Cloud Watch Cross Account Observability', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AmazonCloudWatchCrossAccountObservabilityLg>', $name, $tech)
!endprocedure
