@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2024/bootstrap')

' loads the Item which embeds the element AwsSystemsManagerDocumentsCard
include('aws-q2-2024/Resource/ManagementGovernance/AwsSystemsManagerDocuments')

' renders the element
AwsSystemsManagerDocumentsCard('AwsSystemsManagerDocumentsCard', 'Aws Systems Manager Documents Card', 'an optional description')
@enduml