@startuml
sprite $AzureContainerInstancesLg [20x20/16z] {
fS_7WSKW34NHaLu0-czua9pN_peV9_YxIahCwof09kITyYJvIT46TwGhjEby87GS7yFrWiwpvxaguRC8dwblZXrGUr-DDSzMeLWs4tlPwon3g0oBOt2XZ3qp
F-PholdOAJ_RX8tvDMIjRrjtRVy
}

sprite $AzureContainerInstancesMd [14x14/16z] XOjH0aHH1483sF-AfypzVmU009Z1gyiXeYghkyiuU9DCfj3frbRC0HLgADILMIMkQ9YTbuhopMFvObbJkh44IFsd0ZwdFDxKEsIRxGy

!function AzureContainerInstances($id, $name="Container Instances", $tech="")
  CloudElement($id, 'azure/ContainerServiceColor/AzureContainerInstances', $name, $tech)
!endfunction
!function AzureContainerInstancesCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureContainerInstancesMd>', 'Container Instances', $funcName, $content)
!endfunction
@enduml
