' definition of the Item azure-11/Item/Blockchain/ServiceAzureBlockchainService

sprite $ServiceAzureBlockchainServiceXs [10x10/16z] BKg54S0W44iBUTr_N-vTOgWws28vG4YDGSBq1X2EHE3MFQny7H56eAw8f46oQSKb_04

sprite $ServiceAzureBlockchainServiceSm [12x12/16z] HKm54W0X4CA0cyN___ViTadCLN0NIRoHtvubscSKc-QOa4GdZRcMVW6c5GJo-3Gw0kCBIMvz3jbZ3jKv8ybbDCZu0G

sprite $ServiceAzureBlockchainServiceMd [16x16/16z] {
JOw50SGm30CJW-pczz_tJGMLxghGcl3wPglgVbKxZoFDpkk0dlCubvizYtNlQ4Vy2gSbLAwvjoJaYxNt7i2zzG3oUyLM0uZKrd1BABz0qV-ggDvP6Pwm5g4E
El07
}

sprite $ServiceAzureBlockchainServiceLg [20x20/16z] {
NP074iGW30Df5cVn__yUbjCtJRDfCkMYbo_DpDfRMV9KiEJtT9AJVBbjdKzNvRZWhyVa7ErKEycH1PUBVZ0VkpZEkXfXP4-fOPkQuqLikWWzbC3q71YDqZWq
0XbEsKa4v99ZnDCj_FJSahDqZc2cqs2agcPqTSQy5yDtqpy
}

!procedure ServiceAzureBlockchainService($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-11/Item/Blockchain/ServiceAzureBlockchainService', $name, $tech, $desc)
!endprocedure

!procedure ServiceAzureBlockchainServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureBlockchainServiceLg>', 'Blockchain', $funcName, $content)
!endprocedure

!procedure ServiceAzureBlockchainServiceGroup($id, $name='Service Azure Blockchain Service', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureBlockchainServiceLg>', $name, $tech)
!endprocedure
