' definition of the Item azure-4/Item/Compute/ServiceDisksSnapshots

sprite $ServiceDisksSnapshotsXs [10x10/16z] JSY54S0m3C10XMd_VQjoFc2ToHav0fkcUiTQgpLhzjD4PSoHKAskQhNyrGcGt87rEW

sprite $ServiceDisksSnapshotsSm [12x12/16z] LOs55G0n24En1w7x3tmfvx-24ucGmI9K7iOt3wCDUdKYf00qdzFtxQ2N3DMhSxp8P7UcqQSPdBu2p0FqP0Is-UaU

sprite $ServiceDisksSnapshotsMd [16x16/16z] {
ROx50KCX3429I_VVjn2v_OV4vJ3p6V3gW6iL-cK3gvafF_i-iQLpdvQ_VABiy2NAfem8ZyY4xNhrzDr3TEb-Jxl5JvJjEan_ShVBJRdzQbzaLM7ut9y0pWAW
Vm
}

sprite $ServiceDisksSnapshotsLg [20x20/16z] {
VP05WeH030J78_V__rwCRLOBwnJZRHdjmR1gzFtakbMdNmB0zT4lrzmDAauwWsvKj-Nvp_6GRlETT5DXL5koH5L5_CqXgdjecZ07ZEhgcHqFS0KSmn0tB90S
-uuu7BUJWuDp0J_SVZlxymy
}

!procedure ServiceDisksSnapshots($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Compute/ServiceDisksSnapshots', $name, $tech)
!endprocedure

!procedure ServiceDisksSnapshotsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceDisksSnapshotsMd>', 'Compute', $funcName, $content)
!endprocedure

!procedure ServiceDisksSnapshotsGroup($id, $name='Service Disks Snapshots', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceDisksSnapshotsMd>', $name, $tech)
!endprocedure
