' definition of the Item azure-4/Item/Networking/ServiceCdnProfiles

sprite $ServiceCdnProfilesXs [10x10/16z] Oy09c60CDZOsHX3D3WOW6NO8O69Xvu001WuOm6OI

sprite $ServiceCdnProfilesSm [12x12/16z] ZSc30S0m4030D_OVk7QZIzumpCpuR7snL1JrpNRmawh62O0VFL7aHg1Y1W

sprite $ServiceCdnProfilesMd [16x16/16z] dSkt0G0n20F09yF-0xzpAkthGDBt2k2uDADrMuNzOhLAwy4sITtQHaJKDpd7ypOxRqJKwF9vAG4

sprite $ServiceCdnProfilesLg [20x20/16z] jSsr0G0n30D0C-m_y3E4okHAWmGBKJjWEt4rinl-4_JNDtAlPoBY9Rccv1MbyongezbLsisYPSSL4Md-36RR0G

!procedure ServiceCdnProfiles($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Networking/ServiceCdnProfiles', $name, $tech)
!endprocedure

!procedure ServiceCdnProfilesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceCdnProfilesLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServiceCdnProfilesGroup($id, $name='Service Cdn Profiles', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceCdnProfilesLg>', $name, $tech)
!endprocedure
