' definition of the Item azure-4/Item/Networking/ServiceExpressRouteCircuits

sprite $ServiceExpressRouteCircuitsXs [10x10/16z] Oq01h6niK1OREmUC1HDZOME0i40K8nkOmGeYm8gW-bdPsBb0W8sT0M82a08

sprite $ServiceExpressRouteCircuitsSm [12x12/16z] NOk54S103CC25pdj_lkMyNLaj962HuDUhKSdpXE7mVtSlHyQFu93SWyTrSacf6dUGJAr7RXw1G

sprite $ServiceExpressRouteCircuitsMd [16x16/16z] ROw55O0m44DF4nxxxujJ_zNpo9e4MZC0HXScix6TtAG124HRxj8slF-AhDtqSUfhAb2V9d1t4R7Q6V0xY_bp_q5k-mj0wcM6lUIjqcXL5_K4

sprite $ServiceExpressRouteCircuitsLg [20x20/16z] {
VP055aCn3CDIiDAt-nzuywWmqCVAASO_klgf961NLP2vks8rOiUg7NqnkuFcPrNTDGts6OgBwTC9pMYMhPa1lSDbWYU2PxQi0Lkhr0GovTUul70hkzN4QeHL
l6ct9X7g-q6sk08
}

!procedure ServiceExpressRouteCircuits($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Networking/ServiceExpressRouteCircuits', $name, $tech)
!endprocedure

!procedure ServiceExpressRouteCircuitsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceExpressRouteCircuitsLg>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServiceExpressRouteCircuitsGroup($id, $name='Service Express Route Circuits', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceExpressRouteCircuitsLg>', $name, $tech)
!endprocedure
