' definition of the Item azure-4/Item/Networking/ServicePublicIpAddresses

sprite $ServicePublicIpAddressesXs [10x10/16z] Oy06EE0q1mmmiC800n2180eB8Si60mZZ

sprite $ServicePublicIpAddressesSm [12x12/16z] TSg30G113031ZTD_mszZ3Y5_EZVLj6-oYTCZ5vz-qIL7dEbxxfp84vn6

sprite $ServicePublicIpAddressesMd [16x16/16z] XSk30G0n343HttZ_XS_cAoF-r4aECPjMDSIs6-8umy-UujRSXXUPOmDlD8KvTb7tDZpsE7z6dA5dSDO3

sprite $ServicePublicIpAddressesLg [20x20/16z] fOs50G0X30DJx_uJlxi2XzOIj90NlCy9ziIOSzqpzLrdxO8MvQY_6Me2NdA2_WzGVx3seU-XFizzliyr-Ve5kyafVj81

!procedure ServicePublicIpAddresses($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Networking/ServicePublicIpAddresses', $name, $tech)
!endprocedure

!procedure ServicePublicIpAddressesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServicePublicIpAddressesMd>', 'Networking', $funcName, $content)
!endprocedure

!procedure ServicePublicIpAddressesGroup($id, $name='Service Public Ip Addresses', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServicePublicIpAddressesMd>', $name, $tech)
!endprocedure
