' definition of the Item simpleicons-5/D/Databricks

sprite $DatabricksXs [10x10/16z] uwS3

sprite $DatabricksSm [12x12/16z] unza

sprite $DatabricksMd [16x16/16z] un_X

sprite $DatabricksLg [20x20/16z] unzKO1G

!procedure Databricks($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Databricks', $name, $tech)
!endprocedure
