' definition of the Item simpleicons-5/D/Datto

sprite $DattoXs [10x10/16z] uwS3

sprite $DattoSm [12x12/16z] unza

sprite $DattoMd [16x16/16z] un_X

sprite $DattoLg [20x20/16z] unzKO1G

!procedure Datto($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Datto', $name, $tech)
!endprocedure
