' definition of the Item simpleicons-5/D/Deno

sprite $DenoXs [10x10/16z] 3Oc50G0n4CBoLc-p_xPFJW52jq3m77M0rh8z_QFMfldi3k3awaDmpRAiew030snbg505aiE27m

sprite $DenoSm [12x12/16z] BSR50GG13CGm7qEISV_LBkibTkMNashhrNHPWd7Kw10F6Us_SuERPLHsfVKrB-xXheqxG8DZxuyVS3mUWEFzXHK

sprite $DenoMd [16x16/16z] {
DS-5ZKL120LGdXjm-kzsCvE_H86hCUTekSR_59-7QsuBtULvT8yTHRwLNrL4LKfuFsKBdHfwx8vwoxl4yXfuxRN75X6tiPFVpvOcVovhHC9AmIGWD7BiXu6z
mDYtDgYjp7rjvwpJDVTbhWE8_UhfymS
}

sprite $DenoLg [20x20/16z] {
JSu7aiGW30H0Dh8WfFx_RwySwyOcDR4TUGpos_wb8oJvkeXIqu9vaV2PkPHOEqfwV6Sc5SEdjRvYw6cYog0rFReVSTjuvDAfyPjiUylcfhQdY14KvT7wYJaZ
eEw7lbb2MZdQ5PY-Lj4_q_Usfe1ebsNB4skp97pQIoBPR9PbQydBUjdQ3REmFwQS3_jQvtbBkpCmGtxQbZy
}

!procedure Deno($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Deno', $name, $tech)
!endprocedure
