' definition of the Item simpleicons-5/D/Deutschebahn

sprite $DeutschebahnXs [10x10/16z] uwS3

sprite $DeutschebahnSm [12x12/16z] unza

sprite $DeutschebahnMd [16x16/16z] un_X

sprite $DeutschebahnLg [20x20/16z] unzKO1G

!procedure Deutschebahn($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Deutschebahn', $name, $tech)
!endprocedure
