' definition of the Item simpleicons-5/D/Devexpress

sprite $DevexpressXs [10x10/16z] O-372HWO6A0K0nUGvWBIS74u0yQ2Qu9hvuMp

sprite $DevexpressSm [12x12/16z] O-0d0BYOe4hO6O204SHY1ZAOmM8yG1OhH9e9o8Hg0Kj30KWUpcP668lBNW

sprite $DevexpressMd [16x16/16z] O-170Npy-04lab8E1Y20yTWPm809mcC6SpYWfh62E8nmhM0vk4Ky81udt5HkkA48nVoeV7vKFZyg7yq7hFpuFGW

sprite $DevexpressLg [20x20/16z] dSsr0SGm44JHDOFWzr_jeNWolsnn3E5vo9_RJ6kp7x9uMBAGM7AJn7HqKjpsuwWM-pfesDT48-eIAKnwdfwslhqRwUre3nLG7lK6

!procedure Devexpress($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Devexpress', $name, $tech)
!endprocedure
