' definition of the Item simpleicons-5/D/Discord

sprite $DiscordXs [10x10/16z] Oy0A-240o80118iP90wMuWCBiu1O27Ly_4nW0zWHfW4

sprite $DiscordSm [12x12/16z] TSQ50SCm44DHcTb__sdB3USTIBfLe8qANhByIIpwlq_0lLOTgS60h4bwtKu4tu5QG6heZQYj9m

sprite $DiscordMd [16x16/16z] ZSU55S9050J0ZVjD_ztoS8VCryqEpLeb6QVwdDmTCtThqdkKU385wXLT1yrn4hPamN7QX7BCphg2QV91ZtQ2Can8LfAZbY57TSwQl3i

sprite $DiscordLg [20x20/16z] {
fOw50GD120JXtEc_suGbxlcVKtnf7roMh11Jz28Zca_kgEhgSizp6fpboSSaJsJu9h4-XG8ihxUtjkU1JIztyS5SUWsu9E1vpP9d4egAXKQicaQqCCGmUKUu
3ZgpuFcH0m
}

!procedure Discord($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Discord', $name, $tech)
!endprocedure
