' definition of the Item simpleicons-5/D/Disqus

sprite $DisqusXs [10x10/16z] Om015WO8u0S15X030fX130WNWjc159G7Pu6aaTL10SWyA0C

sprite $DisqusSm [12x12/16z] JSd50O100CJ0u4xwhnOvdzSAmKYo-Rl-U9d0gEiyx-g9sWEeCIj3aodvPCuPEcFslbLdp4xIhGEy

sprite $DisqusMd [16x16/16z] LSY55S0m30DHXJdQVzi-rSKVFECI7HwE9bXctgOoyZK0Q9vphXGFlHsID02jPm7wfya6z-i9_3eWVje3sEfqjYoI2vIzDqzGlo9QY_x901CfJTy3

sprite $DisqusLg [20x20/16z] {
POy50iGW30Itxid_Nrk97pTL1c9mkh773mkni7UXE1dL35nPyrGolEhYb_bbFLK2lNq5YzxSIKcI1PbRc1TWaWM7azD_hcjTLiGPxWAq8cPpETA5hhXTHxR-
w8KL0hX5Cj1LLGzb2NCXMRwpjEcX1m
}

!procedure Disqus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Disqus', $name, $tech)
!endprocedure
