' definition of the Item simpleicons-5/D/Dsautomobiles

sprite $DsautomobilesXs [10x10/16z] 7SQr0S1000GWufxRVzetAgo0LMwmaz49QSuOMoxpDGR11_u0F01cW0SL

sprite $DsautomobilesSm [12x12/16z] HSp10G0G0830003xRmkWrxt2yFF-80mt9uRiu72BZgBPLYfgUwmXkUt4A0J0xOzeZbVurl9HP5wUKGS

sprite $DsautomobilesMd [16x16/16z] LSU54S0m3C10XVcy_xQzXj7oynmBLBEP_rLQNBJybjB-wk8P5YkA897b9AtM6hQjieGGjvq2YbykVr2IXaSWIlXZ9p55_D_joEEepKqVRv7gm-X6Fm

sprite $DsautomobilesLg [20x20/16z] {
NSi5YWKm00FHgNjp_zFkVgy46nu4FESyCFCkfW58TL68l4tv-w-Ph-dJCdPPKWUlKbcc8cN9SHZ1MtUOSmM2ZMLPJmuWbh2iVJAfV6nak7347p6d4e1TH2nZ
ECwrHBh811il8bbxKnstCDejzF2jVm
}

!procedure Dsautomobiles($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/D/Dsautomobiles', $name, $tech)
!endprocedure
