' definition of the Item simpleicons-14/Z/Zcool

sprite $ZcoolXs [10x10/16z] Oq03_12AdP-Vdm68W1W240mkVXZWWqX0bN626GnGAGOeamT80m

sprite $ZcoolSm [12x12/16z] PSq50O100C30uSxwfyNbvGeSkRxaKMZ189I-67oD-64qLNkWQnGy03uAeFMol95s77O

sprite $ZcoolMd [16x16/16z] TSs54S0W44JHnPtjlziC6l-Zxv33RtomMOwX26HpwSE67L2lL7SIkD7coE_cCvIsfBZnBWEAcKp2Jjx-4yrwCwDd9mjMfL6YTm

sprite $ZcoolLg [20x20/16z] {
NSwr0GG14810pdtflzh_Sza9YI39wfwiS6BZKqOTWKRPTUwghRW0J7xqW4b1OGPX0fZ4v6ZsIU61w3nqk0iOPWPjWD5D2U1k7jnDR2BzRafVWaFdRU5IUvfv
QMQDeU3q1m
}

!procedure Zcool($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/Z/Zcool', $name, $tech, $desc)
!endprocedure
