' definition of the Item azure-19/Item/AiMachineLearning/ServiceAiStudio

sprite $ServiceAiStudioXs [10x10/16z] POgr0S103CJ-pVR--mPK1LGTQDr4o8BA749MLPEwwuP49i0luRyIuGG

sprite $ServiceAiStudioSm [12x12/16z] HSY74O000C90h0JttzUEvjfVTBUkcvv6x1fm_3X0SdD9mjMrh-ec-NCthAgbilvv

sprite $ServiceAiStudioMd [16x16/16z] PSg50S0W44FHuWdx3zpWzgkFkwzbOqpncoN5F6a0o7QEeKWCa-sWqr6XLSUrn_KjUiwgTs8vzt7eTjOQSQvNREvCbw_r7m

sprite $ServiceAiStudioLg [20x20/16z] ZSi54e0m34JHDhxX_kV5tJ_KtapA4fjPKjbLlS-Qt5j4z9XPzpPYmZRo60DYCs0sh5JH5qiocWCxrT4mjpDQRTn7mzghwSbANs0fqLUFesL9Rmolvlz6wq8T

!procedure ServiceAiStudio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/AiMachineLearning/ServiceAiStudio', $name, $tech, $desc)
!endprocedure

!procedure ServiceAiStudioCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAiStudioLg>', 'AiMachineLearning', $funcName, $content)
!endprocedure

!procedure ServiceAiStudioGroup($id, $name='Service Ai Studio', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAiStudioLg>', $name, $tech)
!endprocedure
