@startuml
sprite $MaterialsCreateLg [20x20/16z] jSk52S1050JHBxjnwR_Q27AAHMxm1oElSgs8sr2YZljU8DJ6VVLYl90PhVUe9UqRAbhPYhmcGQHeDOa2Bgyw0G

sprite $MaterialsCreateMd [14x14/16z] Oy01694vh5nCI3Ai_5oCS1aE9bPME8UFduCHYSF7IYA7YGV4GV1uW1m4bmcNMm4

!procedure MaterialsCreate($id, $name="Create", $tech="")
  CloudElement($id, 'materials/Content/MaterialsCreate', $name, $tech)
!endprocedure
!procedure MaterialsCreateCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCreateMd>', 'Create', $funcName, $content)
!endprocedure
@enduml
