@startuml
sprite $MaterialsFlagLg [20x20/16z] jSX50W0X241Hk-F-frLWCztZDtdiOyfeoCYvsKevlhNi8RKqIe-oQ8pHRcaMRv5BAGj3nFZ25jqsATchEW

sprite $MaterialsFlagMd [14x14/16z] XSV50S0m30H1CmZxhpQSUmNM84tuhhPQQxmGoRTQAGdQg_yI4OLcYh6vNHfn-r9A4Rg2mF3I2W

!procedure MaterialsFlag($id, $name="Flag", $tech="")
  CloudElement($id, 'materials/Content/MaterialsFlag', $name, $tech)
!endprocedure
!procedure MaterialsFlagCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsFlagMd>', 'Flag', $funcName, $content)
!endprocedure
@enduml
