@startuml
sprite $AzureHdInsightLg [26x20/16z] {
PP05ikCm44J7dYPfQ-z_tL_ZSFBCRX3K6wUJkEi7HEY6KPySNEWByVXeYdLNcZheczhAbZm_Hy6Ae-bHP84zC6XkWpbznarTVz6jnLROM4xIC4OHfweROzbU
6_T8SvHXV1lBLpb6KJ_XgkjJxhio_Y4iwF6FuTnD05OLnmwJCRib_lyNiAkEv2gwxu2tr-eQBB5VU0DdtHLC7Sa9GUcwSrX1jxKq4GJrX6kyfqS8tvKZX5Wa
eaRN6qtdhCEBzSuV
}

sprite $AzureHdInsightMd [18x14/16z] {
HOy5beC034I1FnBkV-7TFDeITpa-G5kVnmkAGBu-xaag08Nm7t0d5fBef59YWqH2JUSE0VoqYSdmcSe3SmPYs4wnUYEs4abpspeq0cV5FRCdzbaao5oVOujI
h_WySHKlrlb4ZarUxU_BFm
}

!procedure AzureHdInsight($id, $name="Hd Insight", $tech="")
  CloudElement($id, 'azure/Companies/AzureHdInsight', $name, $tech)
!endprocedure
!procedure AzureHdInsightCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureHdInsightMd>', 'Hd Insight', $funcName, $content)
!endprocedure
@enduml
