' definition of the Item material-4/Social/NotificationsActive

sprite $NotificationsActiveXs [10x10/16z] NSP50S1000InANFNlzfZpYlqBWBnQ9y4nopd_438uu8qsbto9WOFW0K

sprite $NotificationsActiveSm [12x12/16z] PSR50O0040InES5b-wyMT_8AFyOkHGZJUZ58gbAGVMY5e8rkUtG6zDiJFX-trsixxO9DsniNPpK3

sprite $NotificationsActiveMd [16x16/16z] ZSV50SH040In6Z0kTFxH7ZDQFx51WrbWvLmrh6l6jG0iOjAHfGpGQ3hfz08cPftP9C0fbmVEKRqyOSjT5-rytHIk8fn7LSb7Um

sprite $NotificationsActiveLg [20x20/16z] {
fStL0SLG3CDGNKYvrVxJFcQ6yncm-KO6IW-GZgFH2jh1RDcFMiVjN1kIxcSkP7ScgiF-BED1n-pXB3oYM00d1eyoziVYeyBHv57zOnR7KUzPse-gbtWjwyAj
61Clh04
}

!procedure NotificationsActive($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Social/NotificationsActive', $name, $tech, $desc)
!endprocedure
