' definition of the Item material-4/Social/NotificationsOff

sprite $NotificationsOffXs [10x10/16z] Oq05d12Adu6Rdmt6vEVdWB10J0WBICDP40ONFvW91r0c3uW

sprite $NotificationsOffSm [12x12/16z] POg30S1034MZ6c__QMiSmY-fIfyV8SuhuXDqDtPiuN4cq1M_y0m8yM7qrbSkyiIlahk6MG_j8NRT7G

sprite $NotificationsOffMd [16x16/16z] ZOwr0GGm30CDptJxJnjErFurPals7m-K_rxcFnwdTbu6uBiHF7lZf-FUqC8RU3ZagZ_qHd1H3TnIyzauxnVNMOCQcymmkyhIX_xybA82

sprite $NotificationsOffLg [20x20/16z] {
bT235KGn00NHzn5Z-gzsZM0vnpUE_cqBQWkB9F0DhLGf0NP02v0xB7BGBRVSyMcHCtfWVLW6o0gmTNR6o3uOIMcSTyPbCc9xx8WxJK5JeNtA0lNsHyzCNlIX
8m
}

!procedure NotificationsOff($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Social/NotificationsOff', $name, $tech, $desc)
!endprocedure
