' definition of the Item material-4/Social/PersonRemove

sprite $PersonRemoveXs [10x10/16z] Oy0EEFbveIn-Vdua5XCpCuZ924HCJ10nHf007pyOW4HWB0G

sprite $PersonRemoveSm [12x12/16z] VSY50S0W30117EBxJrjtuR4ZhbCYlpERsMwQ73RxPIuYwsyw8OHPZOjRixMPl3bE3d7DtHi1

sprite $PersonRemoveMd [16x16/16z] dSnL0e0m30FGjBZc_hTbdZ_i8LiLVqpa11aOz8gt6E-AvnWla1W3NVWVICpYtzsjnR8mQWlO87B5NOnjRsByv08

sprite $PersonRemoveLg [20x20/16z] fSq30W1120NG6llV_xHh6s-CYlvZ9MZ30yYqej7oj1JHAhTtQemLii7zfGCGXrgmDE1-5WqwvT2AlAmwocDSmS9mXoLvSAVefne

!procedure PersonRemove($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Social/PersonRemove', $name, $tech, $desc)
!endprocedure
