' definition of the Item azure-19/Item/Other/ServiceBackupVault

sprite $ServiceBackupVaultXs [10x10/16z] NSQ50S0m30CmbPl_7nwZ0hQVtg-oWZO6wp67kQAk6oiD4WfNVRM-AbW

sprite $ServiceBackupVaultSm [12x12/16z] POs30G0n301Zx3_meyQriU16RRZsKJroTt0jlljVAXf493mY_fOlofylMKOGeOD_Xlk1eOR1Z-Ay

sprite $ServiceBackupVaultMd [16x16/16z] ZOw50GDH24DnwFuBbq1Txtt5GmUnQEuc1_2hcKrevjrKr6JQs5L6cLeDJ36ph0Mc8FUqzCzcGCBg0TSPhhWt-U6dJ5VyVWFHVSE74VlE6G

sprite $ServiceBackupVaultLg [20x20/16z] {
bSe50aCX30FGL7zt_miFAdDzU0Z-vuiyHOlYXdcvIOwDri5tqLnGrir0IdGiZXJxDq8ZOHCLqIC65cKi6gVYsSB6Nf41OeoYX6OOh8eaWYkZvsmU_jm3kt1J
mp1lWlVE
}

!procedure ServiceBackupVault($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Other/ServiceBackupVault', $name, $tech, $desc)
!endprocedure

!procedure ServiceBackupVaultCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceBackupVaultLg>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceBackupVaultGroup($id, $name='Service Backup Vault', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceBackupVaultLg>', $name, $tech)
!endprocedure
