@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-17/bootstrap')

' loads the Item which embeds the element ServiceMeshApplicationsCard
include('azure-17/Item/Compute/ServiceMeshApplications')

' renders the element
ServiceMeshApplicationsCard('ServiceMeshApplicationsCard', 'Service Mesh Applications Card', 'an optional description')
@enduml