' definition of the Item aws-q3-2021/Resource/Compute/AmazonEc2I2Instance

sprite $AmazonEc2I2InstanceXs [10x10/16z] Oq0576n876Oq5WS7cCK1Ga0M1mCRL9ODMHqp6B0YcGS

sprite $AmazonEc2I2InstanceSm [12x12/16z] NOq50W0X2C1c3Vx_uUjqIXT_h6H5WFG2b9EKUljHGR0Dy2XTStdqZF3fEPZs41d7xx-xAm

sprite $AmazonEc2I2InstanceMd [16x16/16z] RS-50S0m20J06F3xJzmlKetduhHDqcODh1eSnWnldMjKCb9jt0TLkVumgvcxkytNdPRhG7YU1cfTr_jyUvqlRzythOHDF6wbrNq

sprite $AmazonEc2I2InstanceLg [20x20/16z] {
bP254S0m30DbrluBbvaRpfzHk1k908WKv0EBOZVdmmPMs0np09dSiKg_j8lOssNOR4UGYzt240iZER4S61cBdPJAKoqYXrhaLn-s6U6JUNcwixkwzQIfmz1X
5mncBG
}

!procedure AmazonEc2I2Instance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q3-2021/Resource/Compute/AmazonEc2I2Instance', $name, $tech)
!endprocedure

!procedure AmazonEc2I2InstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2I2InstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2I2InstanceGroup($id, $name='Amazon Ec2 I2 Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2I2InstanceLg>', $name, $tech)
!endprocedure
