@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q3-2021/bootstrap')

' loads the Item which embeds the element AwsIoTThingTemperatureVibrationSensor
include('aws-q3-2021/Resource/LoT/AwsIoTThingTemperatureVibrationSensor')

' renders the element
AwsIoTThingTemperatureVibrationSensor('AwsIoTThingTemperatureVibrationSensor', 'Aws Io T Thing Temperature Vibration Sensor', 'an optional tech label')
@enduml