' definition of the Item simpleicons-7/N/Nintendogamecube

sprite $NintendogamecubeXs [10x10/16z] FOR50S0W5CNoUwcJ_QV5uMbeUg7hKZleHUV_vJP093GzsbXqqsV_0zgX2Hj0IFi2

sprite $NintendogamecubeSm [12x12/16z] JSR5WG81002nWNLD_zMU2tcbBqU_LZo_ziG3rODdIwlAseowxkXvsnQ-Jhm-NtzAdxyPguEjGjnz6QJg7G

sprite $NintendogamecubeMd [16x16/16z] {
NS-5WO0m50MmXplPVzeJ7Egf_nnfsjfBg2urRAdOL42L0VE_P_gaIvPjmphaJoYJB7_MfWAPs2s3gk4ouUir3g-RXyEIKfQa8lS_2lwTB1WoR-trux3aIeqS
qVm2
}

sprite $NintendogamecubeLg [20x20/16z] {
POu54iGm3CHKvkh_lxs9VMM5TkGG9mjlPhL_cD64azh2LAQ5P5ST0Oz0_oyFq6WDq6mKKqvM09LHAo5OOVLqySpEhATpezkpS3cTqRUJEFrrwyrLMxY9qzb1
BHkmXijVL1Iwo03BFpKMMfBrUCEHaohTneD1zeha1m
}

!procedure Nintendogamecube($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/N/Nintendogamecube', $name, $tech, $desc)
!endprocedure
