' definition of the Item simpleicons-14/_/_1Password

sprite $_1PasswordXs [10x10/16z] HKg30S1044lj_lxJdeq8KjVOe3MiBWFVB6TJjC9KFP58RI-4HbT406m16

sprite $_1PasswordSm [12x12/16z] JSY53S1G481G8dLX_saht-w8lS3VuKhDMgMrIfZLAzd3l-hAwhNwLYL-zW9Qk_cwjDuN

sprite $_1PasswordMd [16x16/16z] NOy54WKn24EpMzVS_xHVOAflDD8246nZUJ2eL89AJlgKEKkf0atqy1_mq7INrZhDqBpoCZILvyfnwWv_QEX20wVd33o4Pxlc2m

sprite $_1PasswordLg [20x20/16z] {
RP250SKW30KVxcJ_QRysKZdyyE2WRPe9XaG7ox4YGrEbT5NB-q0_afmLTGDthAiFZXftZDj7kyGfTkzK9yVaXtMukuLrSnvEVgJ_qADL0PqidaEgGAWSC7nv
0m
}

!procedure _1Password($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/_/_1Password', $name, $tech, $desc)
!endprocedure
