' definition of the Item simpleicons-14/_/_3M

sprite $_3MXs [10x10/16z] VS710K0000IW0m3QVrhW2PL_Q0aP0o6Xes4I54P1xYzs

sprite $_3MSm [12x12/16z] ZOQr0S0m0CCSvkZ_QyjZoIZzaO7iUvUsmgI3TI39xTpdpW7IPY832H0O150kLiwIbTsY1wq

sprite $_3MMd [16x16/16z] fOXL5WCn3CHcEU1OzxzjN_2xxSgeqMioP6Mp99cPM6W71DBmH1MPWrCuw0xLCuO3b9v4u84RzaZr0gfTSISUtRM7i6dVwzJ-aGy

sprite $_3MLg [20x20/16z] {
lOs54SCm40JFjfYk_sxpD9C20Yiz4_v2FUHEMC85CnWqYggAImr4xandmJoCaG46MAQ5c3qsjT-vQf6CTdAC0JnKzYGj9xO2djEZe_lTGy-fVsbEH47ae3aW
ztO3zttZ2laoBm
}

!procedure _3M($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/_/_3M', $name, $tech, $desc)
!endprocedure
