' definition of the Item simpleicons-14/_/_7Zip

sprite $_7ZipXs [10x10/16z] TSRN5O005CBGs3lPVriF_tfV0JxCHJcEevG97iUr7ueIixVrWiMV5m

sprite $_7ZipSm [12x12/16z] ZSgr0S1040InVUQR_girnWR5qWzSTC5B8bu0pMNcd1b4iOHp6AYpa7Ca4Dn7d9PUxG

sprite $_7ZipMd [16x16/16z] fSUr0SD00C106Pv1-syRvYw-xZZ8c_ZyvEpdFA-DAZhxelrypW4v7y_8dbCkD-bWdc_DvuFExFdxlctivzyi_Ea4

sprite $_7ZipLg [20x20/16z] jSYr0KDH5CKmd_UPhlUVDenzebByMF_4cq_vl7OrVnzNdUrDgmhABCkIBVEoe0gpvYXZgXpK0rImCBNEYpemg4noFMrgOrSnjzj03QfDpUEUU7lV_vm1

!procedure _7Zip($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/_/_7Zip', $name, $tech, $desc)
!endprocedure
