@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-19/bootstrap')

' loads the Item which embeds the element ServiceCustomerLockboxForMicrosoftAzure
include('azure-19/Item/ManagementGovernance/ServiceCustomerLockboxForMicrosoftAzure')

' renders the element
ServiceCustomerLockboxForMicrosoftAzure('ServiceCustomerLockboxForMicrosoftAzure', 'Service Customer Lockbox For Microsoft Azure', 'an optional tech label', 'an optional description')
@enduml