' definition of the Item simpleicons-14/W/Webrtc

sprite $WebrtcXs [10x10/16z] HSl50S0m40D1XMFS_girmxmE95MNkXDOGnlXA4u8tAhWNPFsz8K-IH-AguofKmO

sprite $WebrtcSm [12x12/16z] DSV50SC05CMmruPH-qyR_Zx9UMfIhQW3DqPLGfuczl98Jraexubo4f8PZyU5ppr-3qy

sprite $WebrtcMd [16x16/16z] NOx50G0n3CDyZBNtdxRCUYaSP3Rqo6DQI0NklXo8lgZZ3pKYOxm_qbVYMu4nFgSOOqo0NHoqFVRgJSz4ZyJumwV44n-ar7-ynm9Jw

sprite $WebrtcLg [20x20/16z] {
RSe54e1G30FHuDg_zpyj5XpUI6UsqQdGIyaYFLAEwGQikLOP1rdmL4a9o0xv5Wj_3YsB0CfNIp-j_cdwjbxwjFK-MrfFGrmjF1lmxJ7lrc7Ye1Mq0nn2gvfD
voFB0WQf2EYrc04
}

!procedure Webrtc($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/W/Webrtc', $name, $tech, $desc)
!endprocedure
