' definition of the Item aws-q2-2023/Resource/QuantumTechnologies/AmazonBraketSimulator4

sprite $AmazonBraketSimulator4Xs [10x10/16z] Oq05xAn872Oq5Zi38uZ5pi8E0api3435R21PLcHrp630WcGU

sprite $AmazonBraketSimulator4Sm [12x12/16z] NOs50G0n309v0VRVk2x9jN53X0zSDIhc1AWoC6Un8dJVuB1qfveUgxxPCyXxPFN_Xxi5

sprite $AmazonBraketSimulator4Md [16x16/16z] VOy75i0W34AnVS3zJzpfNZY_g4am4I7u6OoioFhn24dl0HNAGxvF2h-asbVo3KRVFXr5Mj4Nl7qVUHfVJF9GJsG-p8zl

sprite $AmazonBraketSimulator4Lg [20x20/16z] {
bP250S1020CJBFjFN7VllJyExaW4eEv0FlnbgHlpXe7-M33sMgdTNoKlzIBsUXcBdW3df3V_iJm7FUiLfD12chJOMg6EkTHJBlQl3jyGH0zPJ9fOnk9JJmak
MqSB
}

!procedure AmazonBraketSimulator4($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/QuantumTechnologies/AmazonBraketSimulator4', $name, $tech, $desc)
!endprocedure

!procedure AmazonBraketSimulator4Card($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonBraketSimulator4Lg>', 'QuantumTechnologies', $funcName, $content)
!endprocedure

!procedure AmazonBraketSimulator4Group($id, $name='Amazon Braket Simulator4', $tech='')
  IconGroupElement($id, 'QuantumTechnologiesFamily', '<$AmazonBraketSimulator4Lg>', $name, $tech)
!endprocedure
