' definition of the Item material-4/Communication/Call

sprite $CallXs [10x10/16z] uwS3

sprite $CallSm [12x12/16z] unza

sprite $CallMd [16x16/16z] un_X

sprite $CallLg [20x20/16z] unzKO1G

!procedure Call($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Communication/Call', $name, $tech)
!endprocedure
