' definition of the Item material-4/Communication/ChatBubble

sprite $ChatBubbleXs [10x10/16z] uwS3

sprite $ChatBubbleSm [12x12/16z] unza

sprite $ChatBubbleMd [16x16/16z] un_X

sprite $ChatBubbleLg [20x20/16z] unzKO1G

!procedure ChatBubble($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Communication/ChatBubble', $name, $tech)
!endprocedure
