' definition of the Item material-4/Communication/PhonelinkSetup

sprite $PhonelinkSetupXs [10x10/16z] Oq06_600Ph410PW58_WWCY3Cmm1bSI346DWGYa40mU9Z

sprite $PhonelinkSetupSm [12x12/16z] NOo30S1054DJks__QS_s3zMlYx0cFxznNlmS7htXuydpnGEPTqEUDwYyk6hsckCyzgznbYm

sprite $PhonelinkSetupMd [16x16/16z] RSw50O0W54LHmWR-tNzQc-OfSMWroCGV-zb7-sZ_9jh6TR-XD042XJ66mhienPwimJdGqUfOO3xAyztVHkzxzFYzBjgfBpwyUQOl

sprite $PhonelinkSetupLg [20x20/16z] {
ZP3L0S0W50EhE6J_QQkutryEURAqMBMnwCCvYO1pgkg8HNkt7_xKEuCjS-G4-774pk0dTloD4Yfv-qQ2_Esvc_GjmuVEUW7EeZz2ofwvAfsQt0iBoYoEarh8
csu
}

!procedure PhonelinkSetup($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Communication/PhonelinkSetup', $name, $tech)
!endprocedure
