' definition of the Item material-4/Communication/Voicemail

sprite $VoicemailXs [10x10/16z] VKV50G0X0EBEJlQVrluPD7Y39239P4KxZSWPQ-aMAO3wRqVf3eaJAW

sprite $VoicemailSm [12x12/16z] ZOR50S0W00CFTxB_jFNo9dfiALS3k1P1ESXIvRjQ1eG0JRzueciIobZXz6coenC

sprite $VoicemailMd [16x16/16z] fOm50G0X5CM6Ewz_sbD8mBuhnxXQ7I-nPGDDSwe2qf2SamNxk2wWFaCUPaE1XrMFf_PVxMJUVSTu1qNqzv_66Fy_yArlgk6K6m

sprite $VoicemailLg [20x20/16z] {
lSZ5bSH00CHGDTDpA_zirql3P_-JghX6cxFyLkXhPY3wRNFAVZj02xJlYkv4c8vkuZICJCDtRhTyIrR-idpugiNs7Sl0C7-diXs4mmL1At7RllUpnYcKUfUv
nXS
}

!procedure Voicemail($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Communication/Voicemail', $name, $tech, $desc)
!endprocedure
