' definition of the Item simpleicons-6/N/Newjapanprowrestling

sprite $NewjapanprowrestlingXs [10x10/16z] 5S650GGW40InmU5i-w_s9G5Of_DtxvfzBNZzMSvS0xt4IDUxctyTtnj4Dr-4Inhg354AMdBwKsWSODHU2lW2

sprite $NewjapanprowrestlingSm [12x12/16z] 9Ko50SGm429wHiB-qxwqvmBWRzicNZFrtjB-OrfHjE60anMqVq04G6XAUQfX_Zb7rRac11gN9GsI-eX4NQjQuNSdOgIdzjsn06yhJes_Fc1vbs80Nm

sprite $NewjapanprowrestlingMd [16x16/16z] {
FSpL0GGm20FGLB10o_xRdj_xGnAy3JN5dx9pNEh2cxd9TQRJyEIoajAiN6P0k9SpAdPMSQBgw0G8V-xQ9La7lcSwlQhOTwsfZkp2wKw42816RZkK69fxz-np
0sTnsBpRL_Uhwcn7A5Cj-puF8iGpmOlTd5Sb0BYlg3n5MR7nP2bSic6-y3Oy3eyhdXu
}

sprite $NewjapanprowrestlingLg [20x20/16z] {
HSy5SaKn20NG-o0uXFtljjFsonbDSBo8cXBmnLRtMglBWnSlTwdZP6A2FpP1TtvfSVzznX179kOvEoR1WDonzZPl5yqUKI1NuWw017Pk-UfJjNt0e8BkUVfM
nFgeG9HHkZZRbXanC8OmxguzEjD5-fl7U1POihIoP9x3NKfvB2ysE2GHhSNx2rnhb4YTUp3kwhZeQdOuvov-1smpvfave3oSI-GRY55j1s199tArQulP7B-q
L8zOnY5L8_nXkw4Yljg6Z-FnUv4GVlq
}

!procedure Newjapanprowrestling($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/N/Newjapanprowrestling', $name, $tech)
!endprocedure
