' definition of the Item simpleicons-6/N/Ngrok

sprite $NgrokXs [10x10/16z] Oo0ACCDP_438oy34mC_DpmlYCn6X6m

sprite $NgrokSm [12x12/16z] dS474S0m302nRpEzplpP1aA6n3D51PcjVu5gOZedYMSnfbY3O0WWnha5

sprite $NgrokMd [16x16/16z] jS6t0SCm0C0mgdVn_s-pnhiDyAN5a-0KzTwaqQhSDb5soLkH4xrUWaQJ077Bln02R_a1

sprite $NgrokLg [20x20/16z] pOpL0O0m30LJzzx-s-BEFznhuudy1FDImzuAQgdHwOQA1a_3Zmf4eMNf6l58gT24iMPfZ3KrEZSgom9wkNUG66lVCm

!procedure Ngrok($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/N/Ngrok', $name, $tech)
!endprocedure
