' definition of the Item azure-4/Item/Containers/ServiceAppServices

sprite $ServiceAppServicesXs [10x10/16z] JSod0SG05CDG_MxlF_2Le3ma9DxyzuJgHp1IvSacuJPlJ4JiReHnvksfchOQP8EjpExNxmi

sprite $ServiceAppServicesSm [12x12/16z] LOr10aHX188bZxh_XQT_ETyAgkgVeGCgsEAHx2fAwbxPEJSuCtgB8jlzY75z03OBu6YQjtSHbgaX4RqAPrrafrTb-sFsUZYywmy

sprite $ServiceAppServicesMd [16x16/16z] {
ROw54GGn30Dbbljl-EMR3Fy6DmhX7y4L-IoN8MKN3jUyiY8YwyLiyvmx132d59vhmQ0AvBJ7-M0XhBl30QvouV9niv2xwFDoJs8pAsF4dKzK32S3yFFl_Uy3
PZrikQsWpkeW3jl7u66KDOuV
}

sprite $ServiceAppServicesLg [20x20/16z] {
TT05aa0n20DG2ZGazx_m_h1kRuofOF6lQjcDJrB9Fa_JSP5pwn5h9B9UWV1HGoJhP8EKbC_HRHzLPW_tC69udBC7xuSPoh01a3MuhgrOi3hk0g6pOED84xff
UpIlaMT8r_JHi8jz0rF3smNKdUtbnEaIYIuNshEtdP3i9trXo31e3vtrKR4e8qQIZrRfNNpXcjCdrWi
}

!procedure ServiceAppServices($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'azure-4/Item/Containers/ServiceAppServices', $name, $tech)
!endprocedure

!procedure ServiceAppServicesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAppServicesMd>', 'Containers', $funcName, $content)
!endprocedure

!procedure ServiceAppServicesGroup($id, $name='Service App Services', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAppServicesMd>', $name, $tech)
!endprocedure
