' definition of the Item simpleicons-14/C/Curseforge

sprite $CurseforgeXs [10x10/16z] Oy06-C40oe9p684KAqG11r000k1YG8gVdmt8O6BW0G4aum

sprite $CurseforgeSm [12x12/16z] TSor0S0m34HHEMpy-qyRkclz6h5Y9jcN8oFd70ti7oKWXmrGedvNUa3hdWmzYwa7

sprite $CurseforgeMd [16x16/16z] bSs35S1G343HLtmZ-qzRsxr7SVX9vKL1pylCkmx8bWAbvn73h98E6rqQMOLztubi2r6oAirQoA0E3ueHhre

sprite $CurseforgeLg [20x20/16z] hS-r0S0W40NGZpliFsqKXovvvVdXRwcNOxoFcGUGPdAE1O6CnFJ8WIpS8OQ1lcExaypKEiyZgR0eubFXyt4vHW0plaS1-0BVd

!procedure Curseforge($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/C/Curseforge', $name, $tech, $desc)
!endprocedure
