@startuml
sprite $AwsQuantumLedgerDatabaseQldbLg [20x20/16z] {
ZSy53WCn34JHKWRi-z-tjYAh37_vBILH-Jv9yO9jBwejgcxO0f04T6TWT5ht1aeYxeqMIHbt1lTFBAYRTuNBXBBiTxtMEbzmETUnBGFEf-So0Oa4eShRvhzq
L6EPVO6PUbbmZzcnAslT8vroYl_i7gy
}

!function AwsQuantumLedgerDatabaseQldb($id, $name="Quantum Ledger Database Qldb", $tech="")
  CloudElement($id, 'aws/Database/AwsQuantumLedgerDatabaseQldb', $name, $tech)
!endfunction
!function AwsQuantumLedgerDatabaseQldbCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsQuantumLedgerDatabaseQldbLg>', 'Quantum Ledger Database Qldb', $funcName, $content)
!endfunction
@enduml
