@startuml
sprite $AwsRdsLg [20x20/16z] fP253G0n30C50Rk__xvVPc5FP8NZy8Qf7L85BGRHceInA4Ov-cbcpZ0WA0QOi8Uf7cEH65EsUH_50HT-i15JZsYBNNiZQ7K84_Hso-NcwszN3zxu0G

sprite $AwsRdsMd [14x14/16z] VOt50K0n349F0Lxtt_UxI-CAhIlIDKlCYMqAiGFhYLDsnMi3iWkyhfXtRCkibsbtb3l3Wxqh8m

!procedure AwsRds($id, $name="Rds", $tech="")
  CloudElement($id, 'aws/Database/AwsRds', $name, $tech)
!endprocedure
!procedure AwsRdsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsRdsMd>', 'Rds', $funcName, $content)
!endprocedure
@enduml
