@startuml
sprite $AwsRdsPostgresqlInstanceAltLg [20x20/16z] tP254GGn30EjbMUK_Yl-FyOARiCncpmWhXlEWEE9a2gZs_Qq9i2U_kW_dYQJh9MX0aHRawKDIIseTlQ_-k3VMq_90tu

!function AwsRdsPostgresqlInstanceAlt($id, $name="Rds Postgresql Instance Alt", $tech="")
  CloudElement($id, 'aws/Database/AwsRdsPostgresqlInstanceAlt', $name, $tech)
!endfunction
!function AwsRdsPostgresqlInstanceAltCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsRdsPostgresqlInstanceAltLg>', 'Rds Postgresql Instance Alt', $funcName, $content)
!endfunction
@enduml
