@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsElasticBlockStoreEbs element
include('elements/aws/Storage/AwsElasticBlockStoreEbs')
AwsElasticBlockStoreEbs('element', 'Elastic Block Store Ebs', 'an optional tech field')
@enduml
