@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsFsx element
include('elements/aws/Storage/AwsFsx')
AwsFsx('element', 'Fsx', 'an optional tech field')
@enduml
