@startuml
' configures the library
!global $LIB_BRANCH="master"
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/" + $LIB_BRANCH + "/cloud"

' loads the library
!includeurl $LIB_BASE_LOCATION/library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsSimpleStorageServiceS3Object element
include('elements/aws/Storage/AwsSimpleStorageServiceS3Object')
AwsSimpleStorageServiceS3Object('element', 'Simple Storage Service S3 Object', 'an optional tech field')
@enduml
