' definition of the Item simpleicons-8/K/Kalilinux

sprite $KalilinuxXs [10x10/16z] Oy0AcBcusQ1C5WO63fWmFmC38uJ5YwoQdn7EvC9c6W

sprite $KalilinuxSm [12x12/16z] Oy07M5aXD2CGSt121Lb012SdZCl03yGyK3OlicvcJZvsd2RZaW

sprite $KalilinuxMd [16x16/16z] XKk30G0n3ApRUFzftsQSW_kDa78w8zxxHDipQHeS37cSmZKSF3XAUVzjchJzuYx1rF8LYrV4tnIt_oTw

sprite $KalilinuxLg [20x20/16z] fSg35GH144NHLvWsyezsRUCUVl0tNQ9pnL9fDGVXI0H0OihNp-hxktFiZHqfO2rpQUwNUjyXWRCEzrfI4Uw5MOKxXdEdy27X3si

!procedure Kalilinux($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/K/Kalilinux', $name, $tech, $desc)
!endprocedure
