' definition of the Item simpleicons-8/K/Kotlin

sprite $KotlinXs [10x10/16z] uyS437060vp106N0M1nW5fp93sVomvdyS2O

sprite $KotlinSm [12x12/16z] RSQX0G0010J0Bz1-_sqrmANZ3wserb57tTjfxTHsQZkrdHO

sprite $KotlinMd [16x16/16z] VSUh0G0W34F16A3kxRyjElsTEtPALQgiVldbbp_IUUdST6uwDvsRpatdVG

sprite $KotlinLg [20x20/16z] ZSeX5e0m4CJGcBRhvlwd1LWRW4R-b-o52KmsRDYmOSE6hR1bolgqPShwj6NA-hHbjkcqPPu

!procedure Kotlin($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/K/Kotlin', $name, $tech, $desc)
!endprocedure
