' definition of the Item simpleicons-5/B/Baidu

sprite $BaiduXs [10x10/16z] HOc54O0030F_UeAJ_QT5wXBbcuCSwRzHpiPgkojMf_j4tRjquGRktxj2nwfj4oy

sprite $BaiduSm [12x12/16z] FOk55SCm30Ml3Hfl_stpp21z17XEzb6geSE_eW9HEcuvJRGJV3eE5LHk2Mh7DDP0QEK2fwV0JmJHZXE4Zj5QsvCF

sprite $BaiduMd [16x16/16z] {
LOs55KCn30FlSrZxRzjdA2bu9c7Q5d-IPDUPk1lBhj3soxicoqxMIwhimBKVgpiFJ9dowvAMi-3zctRtBBoixDJwioy4tcpGHLHxCbZdbvizpTZB9cH-qrVm
0W
}

sprite $BaiduLg [20x20/16z] {
NSo5TKGX503H-OBBzDzj3cJzuZo1hJT-gHMA7ZmTgjpguEbKfQdoeafNv_FTrZEHr9kbkDxN2UHvKYimrSxJKC77NypFnl5HUxeF7iUqWzk5Qc3hrg5ALb-T
YIuy75eoiNL7ys3JWvj8CA4dG5JqzJS1vlUV05bF0l7YEfv_g2tdPYkbw62vNNeRBWVy0G
}

!procedure Baidu($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Baidu', $name, $tech)
!endprocedure
