' definition of the Item simpleicons-5/B/Behance

sprite $BehanceXs [10x10/16z] uwS3

sprite $BehanceSm [12x12/16z] unza

sprite $BehanceMd [16x16/16z] un_X

sprite $BehanceLg [20x20/16z] unzKO1G

!procedure Behance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Behance', $name, $tech)
!endprocedure
