' definition of the Item simpleicons-5/B/Bigcommerce

sprite $BigcommerceXs [10x10/16z] Oy04_706Fvo18SRF0L772HFZvmJH_20UI8mBo8O1

sprite $BigcommerceSm [12x12/16z] Oy0E-96O_4XCVYGcYXe4Wm_2PWHY9eWuFoC3Foz43J-GpSiDL0Cs0QI65IZEZm

sprite $BigcommerceMd [16x16/16z] VSo30O1G50NGx3hxJvkjptSP_2ytw0gls1MxuYXktFBr2TC6sGbdsQb_-S8DCzqkA1Pi-jgsMFEE60lKZOi9kwu1

sprite $BigcommerceLg [20x20/16z] ZSs50S0W00F1rBs__xPrmGb-cFA2I-2IQxY6QxYshAwvxpLDBHMc0RrasZHDql1PCHpzHTp4RbtNIIDm4yFp9N3JOSiorxSTTDYHw-vDpCsHTWROoObBi04

!procedure Bigcommerce($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Bigcommerce', $name, $tech)
!endprocedure
