' definition of the Item simpleicons-5/B/Biolink

sprite $BiolinkXs [10x10/16z] FSR50S0W0C30rBtPVreSxdKCud8u2vvvv35cdfym2Fw7l9OvHfbFMmG

sprite $BiolinkSm [12x12/16z] JSR50G0X00InnPtflzfp8QzemIHY69pFuxokW_kUHxhV1CSC8BIYQ0Gi1d6Vu_5vFuwxh-CUuBdO0G

sprite $BiolinkMd [16x16/16z] PSk54S0m30J1DxEl_supOJ9g1Vei0DyGC7UBjDeqTZlYomDt-jjlLgUzlytrKMijApV5LgsIVWkaWP17-CZfkPdBh0xOqpqY1lSyhFqUZBaz0URcj3gm

sprite $BiolinkLg [20x20/16z] {
TSt70GGW24JHCIkAqt-t2svE_uJFX1_H2udjJFLcQ6nccJEITwl72ZiUrXVBfocPdlQy-zU6B_Osyx9PfANEA5P2A17H1uI8dwa2c8gb2DgWOaAQAR7PWl-o
8b-CLnEM5ql739wsvDl0lzRPQCshzME15AjrmH04gP0EaGi
}

!procedure Biolink($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Biolink', $name, $tech)
!endprocedure
