' definition of the Item simpleicons-5/B/Bitwig

sprite $BitwigXs [10x10/16z] uwS3

sprite $BitwigSm [12x12/16z] unza

sprite $BitwigMd [16x16/16z] un_X

sprite $BitwigLg [20x20/16z] unzKO1G

!procedure Bitwig($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Bitwig', $name, $tech)
!endprocedure
