' definition of the Item simpleicons-5/B/Blackberry

sprite $BlackberryXs [10x10/16z] Oy06-FdvWHZ2Ok3Xvs3WusFWP6NWv0G9C8Cb-H6gUI0Sk30Ba4G1

sprite $BlackberrySm [12x12/16z] TOo30K0n44ElTj_-qtuRPoIHFmF4Wjhd1kRwpo2zwodp_3TGvlxGS7EptehUVdrkMibifNXvsWW

sprite $BlackberryMd [16x16/16z] ZSwr0GD130NHEUO__LTxe6Wp-osZn4zzttrT3sLIHrGfKOTcFSzp__KJh7hHY8gwiQcWPb0FhlhaSoOR91dfbcMaCQipdqv3FUhuBFL99LfEbVyy

sprite $BlackberryLg [20x20/16z] {
fOr5WaCX40KBTxZ_RGVxkfeaXRJtuoTopd6P95ceDe3n5nPk116rp29rtqBkneEhjHgUfBaeXD0Bm_Hksc3-wGWefIIjLcwh3zRkBF33W51AyYAVtHTj86-1
txbxGmKfhtLwv1mFbDQQZ_a3
}

!procedure Blackberry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Blackberry', $name, $tech)
!endprocedure
