' definition of the Item simpleicons-5/B/Boulanger

sprite $BoulangerXs [10x10/16z] Oy0A-1duGG380686HY2J3SXYP6I0YeCm1pyJaEG5OX02AsG3Qm433YJJ

sprite $BoulangerSm [12x12/16z] TOW50W0X383irlt_jyTrOmocVj732rGqYCLdj19H2qJ6RUzz2TpnDTpZ335yN08gKnEjjctb2cIhRam

sprite $BoulangerMd [16x16/16z] ZSt50K9H34JH-S_zzbyjaY1BEBlew1-Nari8rvubn7VDUPR8N1CObzMk0ilgxowVcgWD_LjB1-GnAMUBuhb3yW2xiGPppWDKFQI3cvT-kWC

sprite $BoulangerLg [20x20/16z] {
fSfN4iCW48DXkTkq__wtJKGPNbC-6xGZLlywdoTMpwxceIWoRAwoStOStW8rIy0MWRkX0EditVBc0CYjYrZmeitEmmr4nZWVLtn9kQV35rd32TpQiLd1I7AC
CG4KLJ3T6jQjMVID5m
}

!procedure Boulanger($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/B/Boulanger', $name, $tech)
!endprocedure
