' definition of the Item simpleicons-7/X/Xdadevelopers

sprite $XdadevelopersXs [10x10/16z] O-070X31XC9Y004YMDpS35nSA7g102AFO04

sprite $XdadevelopersSm [12x12/16z] Os3bv-TdOU070WOqDWCOC570PaOr4mI0R3XWHM8pGDa

sprite $XdadevelopersMd [16x16/16z] Os3W1m461XO8ZOtFpCmCf9cPsQ1y1YXWeWEVaFl0W0zC8m0ZWWzLWCPdXBC

sprite $XdadevelopersLg [20x20/16z] Os3WXm0668k9WIGn1ZXW6Z9Yt400P75nSV6Guby8u0QAOG1iObnOn1YmYV4WiG4

!procedure Xdadevelopers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/X/Xdadevelopers', $name, $tech)
!endprocedure
