' definition of the Item simpleicons-7/X/Xero

sprite $XeroXs [10x10/16z] DSZL0O1G3CNGu3nfi_-qEEVd2a1nvUQZ_4KN_9LTQ3mFRjkchjrIJRlue_m5bg-S

sprite $XeroSm [12x12/16z] JSp50S0020J1Ymko_LSR5-Q3evCnwyQjf51IekGOjfgtSci1isQQcgvrveIKTyWe-pMV_gUfGxpT7G

sprite $XeroMd [16x16/16z] LSy50e0m241Hi9Nuzx-jhUEjUyXb34pb5TpcUyWdwn3ytlnJeHfnZhp2nfeGcFLfT8aImK5jdUSvMJecZfLZXvec_TQ3KWb5obINwuScENWP7hI9PWS

sprite $XeroLg [20x20/16z] {
PT2r0GGm4CJ0DVEf_sgVqPvGeVJIZ9dr8_6od5xuqSu4_KoGfCHEub35gL47Q4e3vIGP6AGH2538SnW1xZG8fHHAm-DXGY0DlynHS3OJP2RGw0qCsWJ4OMcn
ytBi9BKztNL--Mqfe8yATylhxWe
}

!procedure Xero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/X/Xero', $name, $tech)
!endprocedure
