@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AzureEbooks element
include('elements/azure/IntuneServiceColor/AzureEbooks')
AzureEbooks('element', 'Ebooks', 'an optional tech field')
@enduml
