@startuml
sprite $AwsCloudfrontEdgeLocationLg [20x20/16z] hL254S0W4EiJEVPVkDwYvpYy9aaSHg8xostOki45jk0zehRHJyVQzfwLBU0t6l7O8EkpoGB9RDIvK2RLzz0CotA-CqrdsXy

!function AwsCloudfrontEdgeLocation($id, $name="Cloudfront Edge Location", $tech="")
  CloudElement($id, 'aws/NetworkingContentDelivery/AwsCloudfrontEdgeLocation', $name, $tech)
!endfunction
!function AwsCloudfrontEdgeLocationCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsCloudfrontEdgeLocationLg>', 'Cloudfront Edge Location', $funcName, $content)
!endfunction
@enduml
