@startuml
sprite $AwsRoute53RouteTableLg [20x20/16z] {
RP250KKn30B3GThzD_xoNAwk2GZVG9bzOoP1W0fHeY37dfsoPNSI2La5WTzUaf4llNU_3Ve17W-SDhQHiLXZ775TyY_y5zQu3iKIjoK4qgz3qF5yng0Va94R
lmtBM6N-SI57N3kIw-A1P84WMJmTuzSjmyoRzny
}

sprite $AwsRoute53RouteTableMd [14x14/16z] JSt70GC024BHo8VzLmwc-YmSmGSne5tXHFKG6oJDtUMG0wVSjJUHD6AcBz5CbmsI-2Sc1w7KhTC-x_RrQ_V14m

!procedure AwsRoute53RouteTable($id, $name="Route53 Route Table", $tech="")
  CloudElement($id, 'aws/NetworkingContentDelivery/AwsRoute53RouteTable', $name, $tech)
!endprocedure
!procedure AwsRoute53RouteTableCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsRoute53RouteTableMd>', 'Route53 Route Table', $funcName, $content)
!endprocedure
@enduml
