@startuml
sprite $AwsVpcVpnConnectionLg [20x20/16z] {
POw50KCX50DvCThz1_xk71OERGSbeRrXhFYZQkdzai4-r7NJCjcZs5IhwW683HBfYyG_Vf0_rWDPsl4KMlQ8LjcTrR0d9Bziz1vUdri0rbu-t3fMmYDVJaA-
3Zr-k-DBNqUFhZ2wTsRNHGvNyWqMCGC
}

sprite $AwsVpcVpnConnectionMd [14x14/16z] JOg50G0n20EZxB_nk_Gg4C494-555UDNXSVNEmZD0oi2Pj9Sp00qWWFJlAfp9VLbcdH8vL82s-Dx5LekIi6Yo4-P5xgK-c1W1m

!procedure AwsVpcVpnConnection($id, $name="Vpc Vpn Connection", $tech="")
  CloudElement($id, 'aws/NetworkingContentDelivery/AwsVpcVpnConnection', $name, $tech)
!endprocedure
!procedure AwsVpcVpnConnectionCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsVpcVpnConnectionMd>', 'Vpc Vpn Connection', $funcName, $content)
!endprocedure
@enduml
