' definition of the Item fontawesome-5/Solid/AngleLeft

sprite $AngleLeftXs [5x10/16z] Oq06JCn0pCyFnWmWZ4J20G

sprite $AngleLeftSm [6x12/16z] Oq03J222XPyVJ30oC8C81dv-Tg0eEiM5h0y

sprite $AngleLeftMd [8x16/16z] Oy07MDWX53y_6uJYPuHJp12A0KW1LU5Yi40PZ1036J6i

sprite $AngleLeftLg [10x20/16z] Oo09CF4pGnWi_FpyJ10H8829y3F2H1YHHHYuWGnsY4QG60SX9ZES2REOWv3B

!procedure AngleLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/AngleLeft', $name, $tech)
!endprocedure
