' definition of the Item fontawesome-5/Solid/ArrowsAltH

sprite $ArrowsAltHXs [10x10/16z] Oo00-64aFvJ5pySF0t0nTWO6RZ2B5QiP

sprite $ArrowsAltHSm [12x12/16z] Oo0Py7D0A3uWvkVZ0G4WpSUF00nyC3Nyx0mCVEmGDeWY3

sprite $ArrowsAltHMd [16x16/16z] Ow0wOEHdXxBu-S0aFmUC3nBWHmLyQ7m6a1Wl102PGAFu4FeX9lEmGFbSx9Ix5W

sprite $ArrowsAltHLg [20x20/16z] nOn55e0050B7JZxtFwtTxdLMF8h_o5mUEhnPhW_FrcBTFNkoNYZy1hsi2kv_YmMwUOi57GT5mJUC

!procedure ArrowsAltH($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ArrowsAltH', $name, $tech)
!endprocedure
