' definition of the Item fontawesome-5/Solid/ArrowDown

sprite $ArrowDownXs [8x10/16z] Oq02_7XeDduW3IBvWOYHdnl80m6GD912g0C

sprite $ArrowDownSm [10x12/16z] Oq01RFmm5WTk5ZUKnSR6pmzcyVC34Iy7YEG4yi00g0Z2v07h0Ic06GDc

sprite $ArrowDownMd [14x16/16z] fSVL0O0m5CNGu4xsdnPt-jUdzn2ePamVqZvEOt_9ijJka8hQRb8h6BLUj0C6rHqx7u1nnyKd8DdV3

sprite $ArrowDownLg [17x20/16z] jSyr0WH124L1MFUw_sdNnrh2gUo_2A8Z3uTbU92BOELmjv_2pV60xH1kY0Sslt31AG8IUSRvVpOC-ytWChmwxG6unYI7FN6BZXS

!procedure ArrowDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ArrowDown', $name, $tech)
!endprocedure
