' definition of the Item fontawesome-5/Solid/BabyCarriage

sprite $BabyCarriageXs [10x10/16z] POl50O1G3CM2Ezb_Mbo-vD8-0tbGuszoyduTU9311yY-ahaUsxuHgUxbB3i

sprite $BabyCarriageSm [12x12/16z] FOY50S0m48IeUzb_sdZ26t-mxdHM7QxjcPSb-m7i-fi1NfawoIy7C7I1jUa7sBd93LZRx7VE8m

sprite $BabyCarriageMd [16x16/16z] JSl50S103CH0dHqczLzjcEPZN61i-5iq-7IgV3nqS6Z6AVN0eL5dlyLedN43c0pcvQD1xry1_u3HJm3XQmBm3nO9Cp8cAGQ3D1QWb_PexjpJR

sprite $BabyCarriageLg [20x20/16z] {
POy55WGX3CKoxfFxttRVNmU2rbi0PshKlbKf1PjXgzmAnqCTB9IpQlI6vUEsRTSNmkbDJNHOSy5cnKxhE2Q39GHRLMz1txhfa7GZk_EuhjFamUW9jp2wabbT
wRnWq5C9dVbcxbtpXbazW0S
}

!procedure BabyCarriage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/BabyCarriage', $name, $tech)
!endprocedure
