' definition of the Item fontawesome-5/Solid/Baby

sprite $BabyXs [7x9/16z] uwSC

sprite $BabySm [9x11/16z] uwSz

sprite $BabyMd [12x15/16z] un-2

sprite $BabyLg [15x19/16z] uySDHW4

!procedure Baby($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Baby', $name, $tech)
!endprocedure
