' definition of the Item fontawesome-5/Solid/BatteryThreeQuarters

sprite $BatteryThreeQuartersXs [12x10/16z] Oy05-E60ZP-F4mgu-Vbv8O8C3Cn8R0OKSMJ0m0a7ACO3

sprite $BatteryThreeQuartersSm [15x12/16z] VSV50O100C2muaxtdnPtkVn2M795vrMZd9mahe3-NkvrxaaBhmg2HW

sprite $BatteryThreeQuartersMd [20x16/16z] fSh50GCn40D0cMaTzLzjw9XfVW8yaMKce791aTvC28KqgNRm9VmomWw-b2mxh7IPNqQRJdUZJBte0XS0RMPmsWS

sprite $BatteryThreeQuartersLg [25x20/16z] Ow07uCSAM1Xu-R43a0PE3C03r0AIP482Z23ZsU2w480BhmG34waIJ1m4x401S0bS7cJ79S70mea5S50rEW

!procedure BatteryThreeQuarters($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/BatteryThreeQuarters', $name, $tech)
!endprocedure
