' definition of the Item fontawesome-5/Solid/Biking

sprite $BikingXs [12x10/16z] JKg30S1044lxPlQVzgrZX5a6jyWBNvLQRcY-6KfQTk3zy0cE5pCmC437YsTcHYi

sprite $BikingSm [15x12/16z] JOt50GGn30FbnV3qN-r1M1-3I0DPEmxOJul7Ta7Ohufr5LafTN-m2wmkNITINSg3TF_Fjour02FbljnA27UsfG3FA7k-

sprite $BikingMd [20x16/16z] {
POu75e0W34CBxb7-_Myh0JTnVPlaKNl99_jhWsOsjxDbYFzHWlKtGahxzao29kKLtqMN5SAzmwWXuZMpsOXa4RgB3TRUC-nq5szbWpgx6FfoHiWpBwVkZ7ZD
RNGpgJBWw2VQoIxGI19hT
}

sprite $BikingLg [25x20/16z] {
ROz50eH04CGAPxJ-_zjjMpod3c4CTrh19vsidu72PrZ84MyILtnHI6QyeT7NzRxPGALIkHKgGARmscZ0dR4nULbDgwgzLjcnapnL1sV1fe71EjhT1yaMPbU_
88Gvmgb2F6FGq5n7ClajKwp87dOIUkueGmDgmgaQZNZT5YhZIg75zrD_
}

!procedure Biking($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Biking', $name, $tech)
!endprocedure
