' definition of the Item fontawesome-5/Solid/Biohazard

sprite $BiohazardXs [11x10/16z] DSQt0SD0000XRELu-s-hwgd00N_mGA1_ZKQXOR5wezr3tlbUXAP_UMPeBG7TXGy

sprite $BiohazardSm [13x12/16z] FOk54S0m4CDKvcZ_RNk-W9x1TEvQFi9Q1oVrVKiTJ3O3S_QVvhius7b0QnWzCijt0QTykY71_TNbaufQDYh5-JAA7m

sprite $BiohazardMd [17x16/16z] {
LSw50SH02031ZITdst-rB_0wvmey7OG2wLe8TIAvShIwqYh9DgcY99tZvS-6PLcxvg_L7piCmt8QDeH93z01YoS8Lh1noPCRYqDX2EIWokH6iFAVs5QMtE13
kpRUbbX4MBW3
}

sprite $BiohazardLg [22x20/16z] {
PSy5aiKW0C3GL75o_zlkmA_DxAkd1ao9oxhoM1kNnRUsJzsuASbXNIrl7PS3pVgfCXr-QjVvlQA6gnqZliewelySKBni92yxdhyFHy3VeLaMGbc8vbaNpWBZ
mUWEtPtg0SgqsE1muAtendhLvdxLzPrnidCBBgS3MLuRJf65ZwuLzU0LTKucQvlz3m
}

!procedure Biohazard($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Biohazard', $name, $tech)
!endprocedure
