' definition of the Item fontawesome-5/Solid/BirthdayCake

sprite $BirthdayCakeXs [8x10/16z] NOM50O1008ImM_QVrlRh0W1MW5P4e7fA9sAqHTZ4XbvNHqDE

sprite $BirthdayCakeSm [10x12/16z] ROZ50S1G2CLIzsR_QRyVWUTmm0ixOCKaTQYu6SDXd1ptEswKLp-NPPzvuCRWCW

sprite $BirthdayCakeMd [14x16/16z] bOd50SGm40F7p5R_rHu6Ng458P20lZ161hGmJPOXg1y6lk0MfiinPRxyn0tjauPEPlWY5T-b6EHepc0RZfJfttf8whgODm

sprite $BirthdayCakeLg [17x20/16z] hSg54GCX54NHYpkl_supwup73l8Lm6sV0Jox9A0EOFHz986LjibaimVrhLlP67D_RFPjjtr5yq-DAgryrUSwH2d0b0p8aIh6K1CEr-msbNBU_jWbDNtk1G

!procedure BirthdayCake($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/BirthdayCake', $name, $tech)
!endprocedure
