' definition of the Item fontawesome-5/Solid/Boxes

sprite $BoxesXs [11x10/16z] Os1WOE5dOETd00DE49CHoWG2t4m4uEU7QcFXHs62UEnW2i44

sprite $BoxesSm [13x12/16z] Om02Vdu69dvU80FEuOTpkDaH7230pk430Hu6680huOIQ1gIGEM00uV3Zum

sprite $BoxesMd [17x16/16z] fSx50SKm0CDGVonR-qzRPWQ5tocgCaZmLnSD9Bi03-7LfDK2MxApQelqiu7HF_umWNS3W-8vS0OA

sprite $BoxesLg [22x20/16z] lS_50GCX00NH3ycwJF_LhhlxuE-6glw0v5LxNz2fEQGsz6TQzO4Ux-UwhlIlTjFj0EE__O4DjGDr_dHr2kcYyeZc

!procedure Boxes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Boxes', $name, $tech)
!endprocedure
