' definition of the Item fontawesome-5/Solid/Broom

sprite $BroomXs [12x10/16z] Oq00TWIJdn-JoOzW0bciK1ee1X7b1B5vOV90m0TdmlGnWPWy43O

sprite $BroomSm [15x12/16z] LSg54S1G3CDGfypQVzho1-SexopP7IQeq1Q5j55I3XZ_lvdxAOSZW3BXTVTfYPSXMrtJh-xLbiOB

sprite $BroomMd [20x16/16z] PS_50KKX302mFdUo_xJV1RkHUhHlQsIcffCghqEV_SU8YPId3FgZhhjW-7UvE4C-45Y2wqixe1_JzZNfWzbASJKMsuUMFqtQj2-DVrgXkl8E

sprite $BroomLg [25x20/16z] {
RT350SGm34JH2Pdjtt-rom5jzCx2aI-lSdMGOmQ6xYAG_J6iCfPzp2IBhW0q_GdGWQ0R0EmT0nXQWUluYQ-cOZlO9NN6h5tYCEkAtFWfCcPsYmmECi2Vr3du
2y16L_ZgITOJ
}

!procedure Broom($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Broom', $name, $tech)
!endprocedure
