' definition of the Item fontawesome-5/Solid/Brush

sprite $BrushXs [7x10/16z] O-0d21WW0CQ32q9bU84K

sprite $BrushSm [9x12/16z] O-0d1p3005o43Ix5oC8BvBA0P7dO-Pd1ojZvG5e

sprite $BrushMd [12x16/16z] O-270pv-6W069C2702XsCQAePs7X1T9iBCnWFJpytFn05eJDmy3F16KpGiq6

sprite $BrushLg [15x20/16z] pSV50O0m0C30u4xsdnQdia7lTvYQBGEvFcTkCOEf6PgstLJxjgruhAeDlrNQfBFrB94wSJi1

!procedure Brush($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Brush', $name, $tech)
!endprocedure
