' definition of the Item fontawesome-5/Solid/Calculator

sprite $CalculatorXs [8x10/16z] O-170rmC802duO2NaPy12FcvGIHC7AGEmeS1

sprite $CalculatorSm [10x12/16z] O-270bv-9C000LXPAEf0Y8S1pE9ZuEU0oK9OB234WIoBi0G

sprite $CalculatorMd [14x16/16z] XSi50e0W50FGsRtT_xIsql38NzXa35_m6PiFpwZ1Por4t3uA3A0wFEyrjwe2x_UqFkUAFbyqjjJGVf4xnysSGRO3

sprite $CalculatorLg [17x20/16z] bOw30G0n34LhXFjlUpRxolWRq0E-wZTYDkpWu7Q7k0q_E7wD7IwhYiRDJLLfkDBWdJDuSsmyEYI4-PeTrwREzTxXWbkbPvzq

!procedure Calculator($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Calculator', $name, $tech)
!endprocedure
