' definition of the Item fontawesome-5/Solid/CarBattery

sprite $CarBatteryXs [10x10/16z] Oy0A-FaX13yM09A34FW1mZG

sprite $CarBatterySm [12x12/16z] Oy09-FdveIGZDv3avWQJ_DW00vX0Q468umJioDgH

sprite $CarBatteryMd [16x16/16z] Oo08s7XuU1YHQ5v-VducECt8pGy4FDpSK9eV3s16upD0H45cmMbCUGG0oX84VEXsCA42TDy1

sprite $CarBatteryLg [20x20/16z] Ow0Cy0C1BnOM7pABaPkR7mIuWG3AukGd3FYmY06DX1l50sKnG5aW6vaGBAnwCSLe09XuCG0tiG4A

!procedure CarBattery($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/CarBattery', $name, $tech)
!endprocedure
