' definition of the Item fontawesome-5/Solid/CaretLeft

sprite $CaretLeftXs [3x10/16z] Oq00VWO-VWP-VWPMVWO6FeWG

sprite $CaretLeftSm [4x12/16z] Oq05V0mCFFmC7Fpy3Fn0p032B43Cm05J

sprite $CaretLeftMd [6x16/16z] RSIr0G0n4CH0FUJglzh3q5uOxdcRty51Fbj7LbPMv4W2

sprite $CaretLeftLg [7x20/16z] XSN70K0X309GVg_A_jEcdpK17gPtndxCTMuw9vs3GKzGe5WIeDY9mIa

!procedure CaretLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/CaretLeft', $name, $tech)
!endprocedure
