' definition of the Item fontawesome-5/Solid/CarSide

sprite $CarSideXs [12x10/16z] Oq01FFmW0643AJu63Z276Snc0Clmmm4lFqx00r46ri4FX50IQXmdFnC3

sprite $CarSideSm [15x12/16z] XSA54K8n00MmVBUsR_zfiHCSSl4ckU5cJIdNSPD6w5AXIqSmPqOUrVmpTxbH4cF8D8vr8oEfHz1bomvh0LqTEGC

sprite $CarSideMd [20x16/16z] {
fSu53iH0243Hty2mIl_zJxlk4kkBZA3yiPglDZniVU1ECyg8q2rNwGmXC6boeN7x8tMw3D0-iS_K_Q3yqYu4zNOZzmAEpEpBhHBIul9YMEpbREzz_rO7LvVb
dxSZ
}

sprite $CarSideLg [25x20/16z] {
hT35eSGW04NHXpkt_sf74yBNrHpSHVzoyUIrgrowDkoIbWoI6bOIuDR0PAu10wm126j0xXePO1ywtZvLQ4OF_6geyhl6X_NOMN9YsI_dtcz1tZCbLO9_63pV
mFHU4iy6w2dJdbdLKu89PVzflONzjoTC_USE
}

!procedure CarSide($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/CarSide', $name, $tech)
!endprocedure
