' definition of the Item fontawesome-5/Solid/ChartPie

sprite $ChartPieXs [10x10/16z] BSQ70S0m2CH0fVVy_jEQAXiuecCZq_rAmAnGKArxANKtqHsaLs_KV2XEO

sprite $ChartPieSm [12x12/16z] HSW75e0m2C3GkBUv_srzWDfq_KAsh5IzdBe5DHoVUCg2lvUv-JPTrGIZkW-QtGXtPYi2f1VW0G

sprite $ChartPieMd [16x16/16z] NOp50OH00CI2E-c_sXDOps-Km7AGwJTEjUDXL1zj3x2QjC1WeK-mrBQwtsez67JaZlgw7sQR8sk3AncTke2b0NHH7tGyd8_S0VW2

sprite $ChartPieLg [21x20/16z] {
NSu54eLG3CNGuCxT_sg_qib0ni-J5ZlNXbjDHvCaepGb-MEEYzgaKCqDisXYW5NqQiIAJXGtSQlm63l5PgpMg7Ek_Fw4fSvZfHkJU5pQGfvtLse1xsxmKApV
__C7_hq1
}

!procedure ChartPie($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ChartPie', $name, $tech)
!endprocedure
