' definition of the Item fontawesome-5/Solid/ChessPawn

sprite $ChessPawnXs [6x10/16z] Ou02VdvU1WOMVdv-1WOsCCa09fbWR5wO20Cd9oUG1G8

sprite $ChessPawnSm [7x12/16z] Ou019dv-4CNF3wAP8HG3bEBWvsT2yBWWAddX6dXWPl13

sprite $ChessPawnMd [9x16/16z] NOg50G0X30FpYfFzfyNza3Q2XSlgCXycyiACxGlxujCYUiVbvUkHGTqSpeNRSZy9GBe6En4

sprite $ChessPawnLg [12x20/16z] TSs34G0m4031sEY_sjYuqOOFpYX3JT2dRBKlwKpYQzco6IQpvlPqFcPjU-wxRBJS1w9iypdCWcbVYHUhnRB4aj08-ayH

!procedure ChessPawn($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ChessPawn', $name, $tech)
!endprocedure
