' definition of the Item fontawesome-5/Solid/ClipboardCheck

sprite $ClipboardCheckXs [7x10/16z] Os1Wu6G24a2Adu617nVW0qany3FmWIW6Rh0O9q8Q

sprite $ClipboardCheckSm [9x12/16z] Om027ZO6CE1cvsTaO63d9nOmC009HdO8pS_A0A8XB1Hbl306

sprite $ClipboardCheckMd [12x16/16z] dOS54e0040AnY_Z_Rnsx9jqB5YoqmK4NRMKYGqHag_nZcaubu2KBBzelsWFZeYiDJbtAa1FcGtVp6G

sprite $ClipboardCheckLg [15x20/16z] jSlL0KCX50FGu4xsdxQ2_rNVGQ-XaJLXqtpOOIOKPMjZOs9x2gzW9GyQq6pqimQ0ZG2eMzGOF8bZx86RQRNDyIsAfte7

!procedure ClipboardCheck($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ClipboardCheck', $name, $tech)
!endprocedure
