' definition of the Item fontawesome-5/Solid/ClipboardList

sprite $ClipboardListXs [7x10/16z] Os1Wu6G24a2Adu617ms0P10y5XGU9piR6umD

sprite $ClipboardListSm [9x12/16z] Om027ZO6CE1cvsTaO63dnmCO-1c105K4f1LLX0K8W0m-29yN9W4

sprite $ClipboardListMd [12x16/16z] ZSp50S1030D1Xqc-xR_QCFDy1JR8iKM1OuD6GePBkVE76rdS6zi5ON3JIQFUsCa8wjrqyhGt__YrKx3f

sprite $ClipboardListLg [15x20/16z] bSor5SGm44NH4RDU_ztkiIrAbcxwGMww5zaiW2mLCUYxnirbBeq_bGpjqhae8Sk-xOqFWgEdI-QYXRAtNnX5jHVFnIgwlyIlGqxz1G

!procedure ClipboardList($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ClipboardList', $name, $tech)
!endprocedure
