' definition of the Item fontawesome-5/Solid/Cogs

sprite $CogsXs [12x10/16z] HSh50G814CNGu3wl_sfns2yvfLykRzwSAwO9NTsoufsunhezxIf-wCo4ZVOjleefaxUshRW-

sprite $CogsSm [15x12/16z] HOs50SGW5CLUYslsd_O43NmtNOpgiD2duLrsQ4N49c4Q5Q01MC2fhyuiwP7Q2ht-lC2Z1v1Lbc4p3r56qEeuTEz6tZP2N-tAkYy

sprite $CogsMd [20x16/16z] {
LSy5WaCX34NHntS_-r_j631jBnfFyicPQQg_YRL_gBgx_qxdRKocBB1bB8yd8TwO6LVxx8shG7OuaWsUOjplfBJycDFekeibZGEb-jt9xoyFs5PWyP1uOsfp
h3RLrtMJa9wWpPZ2vxmZf59AVMkDRm
}

sprite $CogsLg [25x20/16z] {
PT25iGGX403HNaSEElzely3MdBqoT8nl7HwnETErCJamNQgl5vqfnSLQbKKhj9tciDFMGnDKfVfcoxhjcXVVjVczqXtgcPpGtfLvSqKv1sI8FV_AF0znaTIJ
iAek04rDSLxqlaaE95dSoNwWtoFnNOeXRlRar8kFNHjqPMYgO-w7bh7_d2whvg9hxEnCzwo-FRoIXLy
}

!procedure Cogs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Cogs', $name, $tech)
!endprocedure
