' definition of the Item fontawesome-5/Solid/CommentDollar

sprite $CommentDollarXs [10x10/16z] Oq06_200f5du8G0imiZ03YIvWHWYpmkN0MC6HX391oH032O6k5Pk88O

sprite $CommentDollarSm [12x12/16z] LOs50O1054AnsxV_j0RNlnFKIdS1cykR8AlahD2uL0TmkHx9DU4qX50tl-4qCC1rXah7gYml

sprite $CommentDollarMd [16x16/16z] ROo50GCm2C1Iz_R_QoV0VC6LVxWyTmyOuHXBodPU1AYI3BI1nWpMADgESsYznNk8zjC299re3RQ0-Edmck1i_xbtNcoWlyg8Z2VWlKTmZW-k

sprite $CommentDollarLg [20x20/16z] {
ZT230GGn50JGYPtflzh3_hLVRE26zTvfh7XE58JXIf5Lt5hDScXpvsgZ8DMenX9GyyGYHO3ZNiTFfcZhIr1CIrg82XHp-QEc5P72pDife4ijAmgDgMzcvqss
Nz181XLAQpKv30ePyS8N
}

!procedure CommentDollar($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/CommentDollar', $name, $tech)
!endprocedure
