' definition of the Item fontawesome-5/Solid/Comments

sprite $CommentsXs [11x10/16z] Oq06VFpy_6nW5Zy405aS22OlbCd8Zr00H50M28C15uYBR0WOW9K

sprite $CommentsSm [13x12/16z] LSa50G0W30J0nvtrJulhmHpuKSCmE1hItWyIGA9D0vwsG1oxPotse5q_MiWGDI8rQ7Jlze2mXyaap-0g

sprite $CommentsMd [17x16/16z] HSg54G1124FHmBd-_gizWTdbGJ8MbUB7VRYwcJGfRJIh0aM_Wr0JAFkCQQRC1xWeYhfeR8s6Yz-bYP_hOuF9Re9-VbwGBeMLPb1omW7gpA9V

sprite $CommentsLg [22x20/16z] {
VO_50S0W40GNT-Y_shWSEgzas3Ci45ehrhXSRZHnjdnariW7F9IAGADjk3GmPm6areOpBsgPSJqrBTJr7w6ez4z7P28DmlDQeXJ-_4e6YCqn9xuzqKUwecqE
Rnl4QchhBImDKtO
}

!procedure Comments($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Comments', $name, $tech)
!endprocedure
