' definition of the Item fontawesome-5/Solid/Cubes

sprite $CubesXs [10x10/16z] uwS3

sprite $CubesSm [12x12/16z] unza

sprite $CubesMd [16x16/16z] un_X

sprite $CubesLg [20x20/16z] unzKO1G

!procedure Cubes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Cubes', $name, $tech)
!endprocedure
