' definition of the Item fontawesome-5/Solid/Desktop

sprite $DesktopXs [11x10/16z] O-372lWOe80q9W8mS081Fp-81CfmSVFpSt4nC

sprite $DesktopSm [13x12/16z] O-1703v-LC001zJWCCC1Fpk6BOm8nJmGOIO61W

sprite $DesktopMd [17x16/16z] O-3ZHm4SlFmOW8KP2N011HWPa037m0dm80C-VdPqXpCmWPtC1_C2p02W52_298JVWHm

sprite $DesktopLg [22x20/16z] tSYr0O1004MnZyFPstzQt9sMb97XA35y4RGJ_NlF5PnHMWqyK8qqevLhBJ76qZ76QEPPf5qq

!procedure Desktop($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Desktop', $name, $tech)
!endprocedure
