' definition of the Item fontawesome-5/Solid/Divide

sprite $DivideXs [8x10/16z] Oq00Tdu8pS_F2M60AIu8u8S21YG0Ly-5u0C

sprite $DivideSm [10x12/16z] Oq01dFnCK1O_Fp-KnSVFYQA6cHyJC73004G90zmKNWpp6C52

sprite $DivideMd [14x16/16z] Oy02s7WP4HnsVdv-18y7o6E2yvZ0SWZ0ZCqqRdxSW1c5XzKjt4p4kOKHpG2e5m

sprite $DivideLg [17x20/16z] ZSwr0S0m34JH7-RS_jlQbPbU9nOr-qf4qaVWafKb9hmf7O5pe-Qw8_kldbC9Hbtnespfz2rhnjkp_M_O43C

!procedure Divide($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Divide', $name, $tech)
!endprocedure
