' definition of the Item fontawesome-5/Solid/Dumpster

sprite $DumpsterXs [11x10/16z] RSA54O0m0C30u4xsdnRNjd_FXnOEYkOwEMYXHTTsNNF45BmrJ5uoIY-GoK5M

sprite $DumpsterSm [13x12/16z] LSV50O100C2muaxtdnOzpIzKjDTPDnNbYwFkAIWLiyqIgqdBO09j6QgS_Dg36m

sprite $DumpsterMd [17x16/16z] VOY50GD13CESOxJttxRSvzT15E7094DzlawwGIP8UhqmfDoUOgimtLF6B_p4lFTuFdDVGPyRVD4MQW_2TZVODW2u3sCVsZDGxaTMVWOp_7dg0m

sprite $DumpsterLg [22x20/16z] {
ZSX50W8n50JHYYTZVV_RqhZ3lCMNuhDSQqru5AgT1xASF6Pafz5FCxPR3PF74cMijvgoR96qeLjjKPR669rXZVian7TGz8v5--MXDsi7lMbygWbOzIe0NQ-m
_B46QLllxZLmDxJnnG4
}

!procedure Dumpster($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Dumpster', $name, $tech)
!endprocedure
