' definition of the Item fontawesome-5/Solid/Envelope

sprite $EnvelopeXs [10x10/16z] Oy02-E40cOcWMTb1D1-42uJ8W0UX0Gu

sprite $EnvelopeSm [12x12/16z] TS650O0m00InnvtRVrgqBeag9hmJJojMpzpoqm48u12VPg4TCBQEL8Edm0q

sprite $EnvelopeMd [16x16/16z] XSkr0GGn00InDREd_sgVyL2vTARrNt7mR_9FdLznAF9bB5ZnCbG1ski4yI8FoF7XPLNvrTcM-2VxHqjN

sprite $EnvelopeLg [20x20/16z] fOw30KKn302lThF_jDzynXKnE86M4Kqcw1C-niveI0ENGSfW3Dn_JVru0k6fkBSYVDiNp5tK_pQAB8OmM01qattK2H-b3V5iv0e

!procedure Envelope($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Envelope', $name, $tech)
!endprocedure
