' definition of the Item fontawesome-5/Solid/ExclamationTriangle

sprite $ExclamationTriangleXs [11x10/16z] Om01TaO66E3dHx3uUI4i9duWG4X3sEn0YX721CaoWvM0539pWmWW4oo02W

sprite $ExclamationTriangleSm [13x12/16z] HOc54G0n383U_Sl-qrQYL1AEINZMALWX1VXzFm0odAVRDnQODOXeAYwd14Ts7y-iiidu8Ma

sprite $ExclamationTriangleMd [17x16/16z] LSt50SH030D0XpdJVxM7MTBB5iQ3Suu69rr3GFrVC9Q_exNSm9B-dZC2YS0TWVt_Zr0FASJz_TUAa0miExWYTh0deG_WJeJBmm0ij7W3

sprite $ExclamationTriangleLg [22x20/16z] {
VOy54iGW0CJQufh_l_OCXvbBYmNTgsEuhmCDd1OWxjBovJwN0ccLaOAOvKCbppP3lky7K4EgkWfWkwgsRgGgzcPUJ1qzJ552iw9qdg-yAJWNfoZq0654aHJ2
j63qucIjedTbv3y2Jl8R
}

!procedure ExclamationTriangle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ExclamationTriangle', $name, $tech)
!endprocedure
