@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-5/bootstrap')

' loads the Item which embeds the element ExternalLinkAlt
include('fontawesome-5/Solid/ExternalLinkAlt')

' renders the element
ExternalLinkAlt('ExternalLinkAlt', 'External Link Alt', 'an optional tech label')
@enduml