' definition of the Item fontawesome-5/Solid/Fan

sprite $FanXs [10x10/16z] uwS3

sprite $FanSm [12x12/16z] unza

sprite $FanMd [16x16/16z] un_X

sprite $FanLg [20x20/16z] unzKO1G

!procedure Fan($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Fan', $name, $tech)
!endprocedure
