' definition of the Item fontawesome-5/Solid/Fan

sprite $FanXs [10x10/16z] Om01NWOeuEU7CH0iC42m-3d1V0Y19ecf6ym

sprite $FanSm [12x12/16z] NOo50O103CIkk6V_QO5tILtbkPNO8UT0rMOxDv-V1EpF5oAxzwfylBQOZtBOM7_jSkS_

sprite $FanMd [16x16/16z] NOw50G0W20J1RlQVrkupwOT9X9j4T9kH7flJQzjcA-VDj3qjp8elf0b6j7gSZXb3c7Px5tynWuQY1OS1SiHFagnc-YJYPSTb5W

sprite $FanLg [20x20/16z] {
RT350GGW40J1nPt9FzeJtFfPEDGJIT8U1s1e3x_KJH0RoM9iCrTCkX0iwnOmYyqybZAL3DPiH0hE0T0KEpgqbjaqzYv4N6exprplc5VhRp6RzPZWP8lHbdzO
tBvX7gLf3qZzW2y
}

!procedure Fan($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Fan', $name, $tech)
!endprocedure
