' definition of the Item fontawesome-5/Solid/FighterJet

sprite $FighterJetXs [12x9/16z] uwSZ

sprite $FighterJetSm [15x11/16z] unyA

sprite $FighterJetMd [20x15/16z] uoSQZ08

sprite $FighterJetLg [25x19/16z] un-kO1G

!procedure FighterJet($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/FighterJet', $name, $tech)
!endprocedure
