' definition of the Item fontawesome-5/Solid/FireExtinguisher

sprite $FireExtinguisherXs [8x9/16z] uwSI

sprite $FireExtinguisherSm [10x11/16z] uwSh

sprite $FireExtinguisherMd [14x15/16z] unzs

sprite $FireExtinguisherLg [17x19/16z] uwSKZ08

!procedure FireExtinguisher($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/FireExtinguisher', $name, $tech)
!endprocedure
