' definition of the Item fontawesome-5/Solid/FolderPlus

sprite $FolderPlusXs [10x10/16z] Oy02-440mK80E9-7WGV2uELWu42HvK4eXWC

sprite $FolderPlusSm [12x12/16z] Oy01sFb10CBcXm1k8E3Ynm0CS1OF3mCFBvJDoCZ0o8Ia1W5O8VB89Y01

sprite $FolderPlusMd [16x16/16z] XSg35S1G50FGr7hOVzhwM_SmGCj13nYi7vFLE5wBvXq8ynvafXL4BkCrnVzA5dDUD8G-WDW5

sprite $FolderPlusLg [20x20/16z] fSs35KH150FGZ3tflzh5jtaF7uCN93jox76mrMFgQ1x9dYiQvK8lPuMOCoVGgHmLxoMSzxSoHicCWLn3AaiM5tq1

!procedure FolderPlus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/FolderPlus', $name, $tech)
!endprocedure
