' definition of the Item fontawesome-5/Solid/Glasses

sprite $GlassesXs [11x9/16z] uwSz

sprite $GlassesSm [13x11/16z] unzS

sprite $GlassesMd [17x15/16z] un_P

sprite $GlassesLg [22x19/16z] un_aO1G

!procedure Glasses($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Glasses', $name, $tech)
!endprocedure
