' definition of the Item fontawesome-5/Solid/Hammer

sprite $HammerXs [11x10/16z] HKp50S103ABkPVzjBnvUE1JR3uKo2b88VOF-PNDBJjugWOdKWqLPhPkznJ

sprite $HammerSm [13x12/16z] JKp50G0n3ABdMlQVjXhZaw0OEBb2mGvZgRFeMV8TrZ_-dnc_13EPUp99leyiG_UX-B_Xnnb-L

sprite $HammerMd [17x16/16z] NOxL0K0X202nM_UVzeL5t1T7moQD38GmVYB9n9a9j6bch4nqT6rc1ipTOLPcdADZA50t4NVKjuTJIRoEJyy5wE8XAr_-lG11pNy9Bm

sprite $HammerLg [22x20/16z] {
ROy55aGX30Fp7S_zJxk6Pby77wp5uCh5uu-RFwBQYmqeJxKP2Yj9hRFVA8OjLzNo2CcfvQiTsFdXNcKOTtviIwJaiyg2oj46AypDacULcrgHckK19Gqfj5IK
Dm
}

!procedure Hammer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Hammer', $name, $tech)
!endprocedure
