' definition of the Item fontawesome-5/Solid/HandPointRight

sprite $HandPointRightXs [10x10/16z] TSR50O0m0C30u4xsdnPtsdiTCSecL_k-Lpmbhk1O3R8j0HewbQSP

sprite $HandPointRightSm [12x12/16z] Oy0B-FdXJ3uecuEHWnyEUFZHs615A6nk93OdXCqEDP8998m6

sprite $HandPointRightMd [16x16/16z] ZSV50G0X00Emuaxtd_RSbVo2HZAVJzR35CcyJHGEwYXNKl9Clns3ZvVfEgzFqpFLSaoK0kpodP0IZte

sprite $HandPointRightLg [20x20/16z] hSYr0GH140CmB_Eu_sgVuPWL2fTe90OyIO-Up0UD3ikN-gAzI85m11nJ_967C3WyhL-SkFe-Zywfzqac-D7mbf83olioUc9jBMAVEm

!procedure HandPointRight($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/HandPointRight', $name, $tech)
!endprocedure
