@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-5/bootstrap')

' loads the Item which embeds the element HatWizard
include('fontawesome-5/Solid/HatWizard')

' renders the element
HatWizard('HatWizard', 'Hat Wizard', 'an optional tech label')
@enduml