' definition of the Item fontawesome-5/Solid/HatWizard

sprite $HatWizardXs [10x10/16z] DOg30G0n54CFjTx-qvRfP_IehFwF023muZSeL3vvSWqtjvm3OtpZhCLK0m

sprite $HatWizardSm [12x12/16z] RSk50OC034JHjBY-_QV57NvSBZxenKP9jhMmjQr8NDPRNshmtzQ786sdbAyzeaSJLrmO0G

sprite $HatWizardMd [16x16/16z] NStL0S0W00FHr0su_RSjRky_5_KMzJxKEU1LjU6jAcxmLE5qy7KbTikjWgHRsxu72C-KPxVeR8CKNY0LLtnThXRNpTCM-ROTCVa1

sprite $HatWizardLg [20x20/16z] {
ZS_50OG04CLGtE7rN-qAxf1ZHd-m8mts5FOcfjkQg4M-KNz3k5Rqh5L3cEr6gOAmthTfEwBZDjQlqc7TY2m5rQIIVcWxFFwGMeB4uvfmrTZeitTwqjwLVyAm
7FWFHmT2B_a2
}

!procedure HatWizard($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/HatWizard', $name, $tech)
!endprocedure
