@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-5/bootstrap')

' loads the Item which embeds the element Inbox
include('fontawesome-5/Solid/Inbox')

' renders the element
Inbox('Inbox', 'Inbox', 'an optional tech label')
@enduml