' definition of the Item fontawesome-5/Solid/Khanda

sprite $KhandaXs [10x10/16z] BSM50SG030EnUuQ2zf-shCHskryNvcC-8RySDzvDal7zzYTqpkoE7axLDyOEh-op0W

sprite $KhandaSm [12x12/16z] FSY5OGC1302nopDh_sdBZSpknzuRrz_IW0RbpcmJeoE_uN5d-FqVz48Z-Qq17LZTUDLjMhHP-dPVdFqQqglw1

sprite $KhandaMd [16x16/16z] {
LS650Hn1002X-NDT-gyshj0lP__XgL-kkb7JLcKqWV8MMmohizSUPLurHXStdsoRZ6vmzkAnXWi5LpE27dm-q83fjU-m5BY0kugZOUingleqlOEpJxyuFtBs
rwkVlW8
}

sprite $KhandaLg [20x20/16z] {
PT35eMin3431arp6wR_Q3uzXRE5IVTZwvRRNTt3tuL9FhxlHKkL_0SvYguEwBUmysXX2qM78sPDhGRdRFNFrm8MYotIQcxqQ6hqgsA5My6Y01nm5Lu5k7-Kv
WgKdC6sU1xYhmNVzjt8yucZ4ezTbFU2iyTlnHa_wOZgxJUcxsrol_W8
}

!procedure Khanda($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Khanda', $name, $tech)
!endprocedure
