' definition of the Item fontawesome-5/Solid/Leaf

sprite $LeafXs [11x9/16z] uwSz

sprite $LeafSm [13x11/16z] unzS

sprite $LeafMd [17x15/16z] un_P

sprite $LeafLg [22x19/16z] un_aO1G

!procedure Leaf($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Leaf', $name, $tech)
!endprocedure
