' definition of the Item fontawesome-5/Solid/LevelDownAlt

sprite $LevelDownAltXs [6x10/16z] u-Bdv-TYOE070WOWm4SoGXI1I8W8

sprite $LevelDownAltSm [7x12/16z] u-870WO61X35nW04ZCHIp2py7CmGZVn0CQX-5dvk1W

sprite $LevelDownAltMd [9x16/16z] hSt50S1030CmbRdPVzg2PpW5VzxhjwC2NHunD7dMywmwJ-uAv4xaEqZkpGi

sprite $LevelDownAltLg [12x20/16z] nS-r0G0X0C30lEAm_xIuRS1LQQD3eu4hT6Jtrjp__xTkJlGL1c3lk-T3zjNyg6HEHQVgOm8

!procedure LevelDownAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/LevelDownAlt', $name, $tech)
!endprocedure
