' definition of the Item fontawesome-5/Solid/ListUl

sprite $ListUlXs [10x10/16z] Oq00VXY3bv-1ZHyCa6GvuSgmoJ9WaMM6YG4

sprite $ListUlSm [12x12/16z] RSh50O1000InmPtjlrhatF8EgPdWreaS1CDeaH9qZjA_qZHeud1sxV4dNW

sprite $ListUlMd [16x16/16z] ZSwr0G0X04FHVwwG_RUbm-tr4GOs2QxVizBABm_ziEpULDzjFHLz1bYykN-VL_-tUcGS

sprite $ListUlLg [20x20/16z] fSt50SD00C0m9pacxxzjdsNM0k9JqvqRNONefQb2yXBJ28HBV2fMRcLTS7Zhzjsq0lL2uG-7TjZwfKTlr07xlCHsy8aJ

!procedure ListUl($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ListUl', $name, $tech)
!endprocedure
