' definition of the Item fontawesome-5/Solid/LuggageCart

sprite $LuggageCartXs [12x10/16z] dOO50O100CI6E-kV5ju3_Eas1PwqLrhP9c0KKIUxk6cq2RW5yEO7

sprite $LuggageCartSm [15x12/16z] fSV50S0m34DHsMNy-s_RS7BlCse3asI0Wd2cU8xzVXI5w65Dn-EM8qxmtFoF8-wh2t6a8EnwFW

sprite $LuggageCartMd [20x16/16z] jSd95G9G349HGfpbI__T6fnrxrrn7dlRXLYp3WYFpZWv2j7htcG0cQ4PfPAbcSVJirrCELhkFxNrqVXeQB03B3pQBrddRsc_W2ANtHmPMn9no1TxPrm1

sprite $LuggageCartLg [25x20/16z] {
nT750O103031u9fi_zNYTlfba9DzfcDJoA5XOt9YLntRYjCPfZTqrDlVa5i-GDbnafak5VG9nPz1aa6TKByXa0_p53f2p1PKrG2z0BOjx-pATtIzF81xg-Ue
Lm
}

!procedure LuggageCart($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/LuggageCart', $name, $tech)
!endprocedure
