' definition of the Item fontawesome-5/Solid/Magnet

sprite $MagnetXs [10x10/16z] Ou03VY20K0WMDba-X2oOnGfcmG2I0H0c5mC3

sprite $MagnetSm [12x12/16z] JKs30S104Alvs7_QiwraATBdd2VbQNAN-h9wFOw3RtVAzMQGFrRBmceAifNwacHRRpRX_WqB0G

sprite $MagnetMd [16x16/16z] ZSp50S1G20FGKFViFstzkxuB3ZmzR-kRqgYluIdj7xgMDvjqFNmPNuAMfZPwE8r3_z7bRV_B2SfmS6lVx08

sprite $MagnetLg [20x20/16z] fSq35WHH44FHjF6H_Qzsy6fitCDYz43hlNHPP8U6tcByqzC3Su8m97pwhnejlTLOZ8bUDUH0X44FovWT5es-nPDhlUwQix0Q67JG-63LfNwQnqvX2m

!procedure Magnet($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Magnet', $name, $tech)
!endprocedure
