' definition of the Item fontawesome-5/Solid/MapMarkedAlt

sprite $MapMarkedAltXs [11x10/16z] PSUr0G0n0810tltPVzfugb0TvDwBbgcgJPR6sVKjrCKKvdQKlp9FfmxyeV2E

sprite $MapMarkedAltSm [13x12/16z] POt50GGn4CCSvgZ_QW-MGODwMGkZQiS2x0AnqGzPPg4D02SD0GBGP44H95WmRkPw2CPp2l2M9Is2cFe2

sprite $MapMarkedAltMd [17x16/16z] VSg54SGm4CLGXSos-g_sc24QslzcuT8y6gyDrVZSmKjFk8pN5nsWwRxdegdg36GeYfSkTrAbgawhzq1jl411wI_WijBVm51y1zs3Idn0ryAbSeOCHm

sprite $MapMarkedAltLg [22x20/16z] {
ZT25WSKW00MmLwLAzf_szBlZ12V7q6pct8ODZDUu0zfBRB0lg9Sw8EbmgIEIt6YBFjjnX-uthr9nl4GXFNJDGPCPZlTSGNTSTD30ccljsvQQvKPbbCwjxadh
JgaUgG-rkzTw-BQZBc5fSWXbbxeFIRu1
}

!procedure MapMarkedAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/MapMarkedAlt', $name, $tech)
!endprocedure
