' definition of the Item fontawesome-5/Solid/Meh

sprite $MehXs [9x10/16z] HS650O0m0C2muax_lnRcImW64gCBp3Oi3aMnMopG8L0Ean4s0_W1

sprite $MehSm [11x12/16z] HSdN0OK03090NhLx-qzhrznF0cJtVkK4r4Tzfc2amy0l14fRR_XbWzIU0EPiHlWdAm

sprite $MehMd [15x16/16z] PS-35KGn54NH-utWz5_j8CPU2XuLhOiAGx0h87FT3QnaQMoYimEtVFvmW1VmY9cXiz1HA1K0JcVtAJcACsyG70fYkLS_Nm

sprite $MehLg [19x20/16z] {
TSw55S0m20JGYtjk_stxe6u_he2TDRZoWweUsvE7SDzHHNPuvu781u1FMRUcpJAuG57M0pdfsvD94PhqCVD7vqlW2wGRSQCB37bjDleEbdSJGE8Dn2qR2tM-
7JXezhDOY0K
}

!procedure Meh($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Meh', $name, $tech)
!endprocedure
