' definition of the Item fontawesome-5/Solid/MehBlank

sprite $MehBlankXs [9x10/16z] FOU50G0X00BlqvRzfxML1k1YG1rXjMJsa9COElZsu0mt-mOpFXK

sprite $MehBlankSm [11x12/16z] RSR50O0m0C30u4xsdnRNjlSwTdd6oSCxVUUqTzHE7RH2yQTzIwejzsSsuxuQLW

sprite $MehBlankMd [15x16/16z] PS-55S0W30JGg-Et_xIuvVNZJj2S1oRBwaR5mOiHwG37pGKATouAOIpuN4BfQV3FKZWeo1CUhrW4FATtHb0yg0uMfdGJ

sprite $MehBlankLg [19x20/16z] {
TSw55SCm40DGnSpQVzi-kM7uPhp3nYmuSvrJsRS7T_ws8raxl790u0t0kpItXaaQhAVa_u5E6a0P55_LXyGFZG-U3-1TH-UDX-7L011v0KayCPZCwUlTp7va
0_a1
}

!procedure MehBlank($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/MehBlank', $name, $tech)
!endprocedure
