' definition of the Item fontawesome-5/Solid/MinusCircle

sprite $MinusCircleXs [10x10/16z] uwS3

sprite $MinusCircleSm [12x12/16z] unza

sprite $MinusCircleMd [16x16/16z] un_X

sprite $MinusCircleLg [20x20/16z] unzKO1G

!procedure MinusCircle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/MinusCircle', $name, $tech)
!endprocedure
