' definition of the Item fontawesome-5/Solid/Monument

sprite $MonumentXs [7x10/16z] Ou03Vdum2GGO510ZA4Q881Cd433mGm

sprite $MonumentSm [9x12/16z] HSQ50S0m24JHkZUt_xIu_0HuaxHEtWPCsWouZiIZM0I_OXS0CbVYKrYD2Xa3

sprite $MonumentMd [12x16/16z] JSg50S1020F0r2qq-q_xBjmBYi8mI3RIX3MbidsqfSlbZylfyh_bm9g_7cg-IwJL_5HMywVbQzxVAk2sIKu4

sprite $MonumentLg [15x20/16z] VSx50KGX34LHtE7rN-r8WdszkuD6S5c9hGJefOnVQjlR3IuVsLWIu9ZcI7TaE381l2Y9XQZ7O9Le0KV4A1oPZYp4E0e_g3s9rxu

!procedure Monument($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Monument', $name, $tech)
!endprocedure
