' definition of the Item fontawesome-5/Solid/Monument

sprite $MonumentXs [7x9/16z] uwSC

sprite $MonumentSm [9x11/16z] uwSz

sprite $MonumentMd [12x15/16z] un-2

sprite $MonumentLg [15x19/16z] uySDHW4

!procedure Monument($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Monument', $name, $tech)
!endprocedure
