' definition of the Item fontawesome-5/Solid/NotesMedical

sprite $NotesMedicalXs [7x10/16z] HOU50S0m0C8oNvN_hwqB3c1Eg2NGnFk-dpOmBU7OJr_GH0O

sprite $NotesMedicalSm [9x12/16z] LSg30K0X543H-vbh_sapJtWaip-L4U424IRtPk7aHy9LWoMhomyyQxIuaIG

sprite $NotesMedicalMd [12x16/16z] RSpL0S0m409GhYvGzf-sxidxEWMRnhYqrj6Cf0cBREIFjjeSGt7ZZ2ecNmh8XoQ0YAEhiE6P4nYOtcyR_xL-B

sprite $NotesMedicalLg [15x20/16z] ZSi30W0X50JGoMxkVzgrsOjVcCYQiDCSx64c5ENKnec9qrDufsUHCplBR9C07iHZ6885V2YSOMRFeRlDFeVLMZPGFAez

!procedure NotesMedical($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/NotesMedical', $name, $tech)
!endprocedure
