' definition of the Item fontawesome-5/Solid/NotEqual

sprite $NotEqualXs [8x9/16z] uwSI

sprite $NotEqualSm [10x11/16z] uwSh

sprite $NotEqualMd [14x15/16z] unzs

sprite $NotEqualLg [17x19/16z] uwSKZ08

!procedure NotEqual($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/NotEqual', $name, $tech)
!endprocedure
