' definition of the Item fontawesome-5/Solid/ObjectGroup

sprite $ObjectGroupXs [10x10/16z] uwS3

sprite $ObjectGroupSm [12x12/16z] unza

sprite $ObjectGroupMd [16x16/16z] un_X

sprite $ObjectGroupLg [20x20/16z] unzKO1G

!procedure ObjectGroup($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ObjectGroup', $name, $tech)
!endprocedure
