' definition of the Item fontawesome-5/Solid/Pause

sprite $PauseXs [8x10/16z] Ou02Ddv-VWP-8227Xc0k40q

sprite $PauseSm [10x12/16z] Ou03Hdv-VXO67du8u6FWfm6BWPUNbu61YPUN6m

sprite $PauseMd [14x16/16z] Oq05lFpy_1mm6aW00IC33pyOG7byWux71YOP6A0q8n00lG2X0G

sprite $PauseLg [17x20/16z] Oy00h1n0m09YiG4Px8ni_630pC30nuyCk1aO-540px0Ku8LGN701A0qAAQXIT

!procedure Pause($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Pause', $name, $tech)
!endprocedure
