' definition of the Item fontawesome-5/Solid/PeopleCarry

sprite $PeopleCarryXs [12x10/16z] JOU50O0m0CE2E_d_McHUB-m432EWaAh5e1WCbhrWmX4-YmhET0g0ruAaZNkpNm

sprite $PeopleCarrySm [15x12/16z] FSU5OSC000F1Yvb__sdBZLXumF-e1QWLBdYFPUVy0kV0gz9ViF_VeNgffJSsLwEdwdGqy0IOsqa1tUEfwNstgoVN_vtq2G

sprite $PeopleCarryMd [20x16/16z] {
PSu53i0W5C3G_Z4NUl_JJabc3syC86MA-wvokU-wtCsPKqLntuS1kka0rTG2P1LFX7f4rQuq3n3UehHUsxjEQj0Ss-AbOr0WAv0E4Dh-_pm2quHIX0i6ojqQ
XzQSp6GfHbiqcvWCBhCLini
}

sprite $PeopleCarryLg [25x20/16z] {
VP054aGX34E3Exd_RHVQB-jl9FKCO96dmSsTHfAu2LTQI9gdXNjkieW-fVznRK_K9dWWh5oWU52fuZ6nQ5oCko4Y2yBLQ2916uFiaejElUL8niadhDxQOb5v
4IJHKnamvocjE7qf8vuOCWaOVFnLn-e4MaC6N903XMjngUoUw2E352VhSoFlhKhTUcu49BBkMc5xRXWOyW4
}

!procedure PeopleCarry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PeopleCarry', $name, $tech)
!endprocedure
