' definition of the Item fontawesome-5/Solid/PeopleArrows

sprite $PeopleArrowsXs [11x9/16z] uwSz

sprite $PeopleArrowsSm [13x11/16z] unzS

sprite $PeopleArrowsMd [17x15/16z] un_P

sprite $PeopleArrowsLg [22x19/16z] un_aO1G

!procedure PeopleArrows($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PeopleArrows', $name, $tech)
!endprocedure
