' definition of the Item fontawesome-5/Solid/PepperHot

sprite $PepperHotXs [10x10/16z] Oy04_12AavyBo88o8In-VWIBbHN2004U68CVHdCnCF1118

sprite $PepperHotSm [12x12/16z] ROh50O104CHMS4l_rU9mcjT8fCeyVybqdhu8w1D717Wo8O_GjgtTcPlcYjiTjpCvDwj8Hn2cExbS7

sprite $PepperHotMd [16x16/16z] LOo53KGn3CNAt7h_QGy-H8c5rWDdM5OBpe9NuUnLvvqVOk7427HPigCgHDXXZ8t4d9opsn9VIFpmnFlHSrdMgKUeUiaqpzazV04

sprite $PepperHotLg [20x20/16z] {
dT2r0SKW003H62wt_xHVSEbovSCvrfvZ3rwP0UnY8WB8aMAUoJaGNCbyeujgDFD_kvxdYTtIzaA8wsWMgDt3RZNV3wt5IlGodAfBICAOJUG62TUwUN_dISgD
l_45
}

!procedure PepperHot($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PepperHot', $name, $tech)
!endprocedure
