' definition of the Item fontawesome-5/Solid/PhoneVolume

sprite $PhoneVolumeXs [7x10/16z] BOK50G0n08HubmdzqyvFW940WYzgt42Fx-0MUAAPdY0ZkfIwBWKg

sprite $PhoneVolumeSm [9x12/16z] NOd50O1G08MmM_QVrlONbnVmKS6q04YjWYDgNzVMk0jiooWF-XMslzH28RVGj0Su0G

sprite $PhoneVolumeMd [12x16/16z] HOh50S0m08IeniF-qzQ5rmbyL80qSf8B1AqmYg1Anw7Jh-nOfyOPPnREhWp0MB5OkEcpHbwwwSlHoeSkuSz-MbBzZpyFEjvf1m

sprite $PhoneVolumeLg [15x20/16z] {
NSo50SCm0CH0cTc__xHjc1Gy4uzisJxne9C3ghQF5QE3rrB3e8H0Qzc8sX5veq4s3SIc0MAqZIrN2nWvfxWTkvLGwH9dKUX1-BAz6IJ_j3JcOsHgQJvENxEN
DzQBPcNXiNnUQ_y
}

!procedure PhoneVolume($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PhoneVolume', $name, $tech)
!endprocedure
