' definition of the Item fontawesome-5/Solid/Plus

sprite $PlusXs [8x9/16z] uwSI

sprite $PlusSm [10x11/16z] uwSh

sprite $PlusMd [14x15/16z] unzs

sprite $PlusLg [17x19/16z] uwSKZ08

!procedure Plus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Plus', $name, $tech)
!endprocedure
