' definition of the Item fontawesome-5/Solid/PooStorm

sprite $PooStormXs [8x10/16z] JSM50SC04090shZU_jF6xVw1REJ4Tq5IN4iXpFH2G6JJrpdOiW8

sprite $PooStormSm [10x12/16z] HOo50O003CEAE_d_MsY7PAuow0N-R7BeDs1tHb7PcGoEdOOmWpPGbD7ZtjdjWzyLs5q

sprite $PooStormMd [14x16/16z] LOc54G0X4CGMTz9_jp_laDFCwWQl1HYRyOi3tFscDW6QFINoSbhxx0m756CiK2K0GJ-L2Gn1yPpfEG4a0UV42c06NNBUDA3B6prqj43Ux3u7

sprite $PooStormLg [17x20/16z] {
NSo55OD040N0ZplJVxTvmM7ERoM7QSvRIPiNvAb7dLlX-J5Cgx_fwE8sxDctzVkn9AaMD4coO4py1LKDwxndecZzhT2NI0AL_zPW6FuvCY6zltHKIL7N6M1C
LUL6NafTNWPvMvhiVW
}

!procedure PooStorm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PooStorm', $name, $tech)
!endprocedure
