' definition of the Item fontawesome-5/Solid/PrayingHands

sprite $PrayingHandsXs [12x9/16z] uwSZ

sprite $PrayingHandsSm [15x11/16z] unyA

sprite $PrayingHandsMd [20x15/16z] uoSQZ08

sprite $PrayingHandsLg [25x19/16z] un-kO1G

!procedure PrayingHands($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PrayingHands', $name, $tech)
!endprocedure
