' definition of the Item fontawesome-5/Solid/PrescriptionBottleAlt

sprite $PrescriptionBottleAltXs [7x9/16z] uwSC

sprite $PrescriptionBottleAltSm [9x11/16z] uwSz

sprite $PrescriptionBottleAltMd [12x15/16z] un-2

sprite $PrescriptionBottleAltLg [15x19/16z] uySDHW4

!procedure PrescriptionBottleAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/PrescriptionBottleAlt', $name, $tech)
!endprocedure
