' definition of the Item fontawesome-5/Solid/Procedures

sprite $ProceduresXs [12x9/16z] uwSZ

sprite $ProceduresSm [15x11/16z] unyA

sprite $ProceduresMd [20x15/16z] uoSQZ08

sprite $ProceduresLg [25x19/16z] un-kO1G

!procedure Procedures($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Procedures', $name, $tech)
!endprocedure
