' definition of the Item fontawesome-5/Solid/QuoteLeft

sprite $QuoteLeftXs [10x10/16z] uwS3

sprite $QuoteLeftSm [12x12/16z] unza

sprite $QuoteLeftMd [16x16/16z] un_X

sprite $QuoteLeftLg [20x20/16z] unzKO1G

!procedure QuoteLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/QuoteLeft', $name, $tech)
!endprocedure
