' definition of the Item fontawesome-5/Solid/RadiationAlt

sprite $RadiationAltXs [9x10/16z] 9Sa50SC040J1AJUu_jK67mxX0NJEH44_FICDQz5wjv_putKAKLuPyds_UlAhOWS

sprite $RadiationAltSm [11x12/16z] BS65OSG0002XYtlOVzhgGrNZq3-WYg4MYgcQyoIAnUMY29Mxikj3nYRg5E4SxSKrZ8-tweQrlW4

sprite $RadiationAltMd [15x16/16z] {
FOw30S0m50LVOz_-qrR11T_Gn5mwL7xSj83H6j2drMS-DAdHJFnB15OWa1GO5Xob_kc0XVvzg3eFjG5czfiJArw7paNx-WnM3bnp4odH5U1x80T_0L7Mg4AO
_IQxwSL7qSi3
}

sprite $RadiationAltLg [19x20/16z] {
JOy50i0W30E3E_t_RvTsnY6rP88Nxt0IbnZzQs_vI7-dUhWuc3GGDO0yUGGo9sv0yLrxEjWy-TOCdieJfyrG61ppnahk5bDPYIuHpxGuCrb1e8GdEf7vf2Zn
7QMdbU2SJUpPvTRB0j6mJBQU7wnw--U3oOH-mlE50Q7HFsnCgf1UszJeONXvMVX8Qjdjbbm
}

!procedure RadiationAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/RadiationAlt', $name, $tech)
!endprocedure
