' definition of the Item fontawesome-5/Solid/Ribbon

sprite $RibbonXs [8x10/16z] 7SYr0OG00C30lEBS_jDYLQJwULNX4Uy6znKL2ptZNTLEbGyAOQFY1

sprite $RibbonSm [10x12/16z] FOs50G0n20F3k_RsdxQEEucgtEpgGfDMlF21zP5aq2k4Looyy-Czutbh-SBelojyQ_zeztKE1vqgGG4

sprite $RibbonMd [14x16/16z] DKw53S104ABlplxRDcUy7f80GRfS23mAkWsL1fl8Kqj_F38qiW6u9XwI6LlkYA55a3fE3XbYx3R4wEWwlb3g9-C9MyvoBo-f7SXnv4u0XhBFEa3Qp1y

sprite $RibbonLg [17x20/16z] {
HSy56eGm34JXmQLjtlrlkzzaWVneBQ8qDU9K6QHTZvs77hoQKeF3tmwJ3CY00Jqp0AmPcNWdOCxFa0MckH9ZeVtDuZNJfTUADPMzPco4BgYOtMiTMoJb8fS6
Dai7TaiaBHKEYu6fUj0s22NlRlCF
}

!procedure Ribbon($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Ribbon', $name, $tech)
!endprocedure
