' definition of the Item fontawesome-5/Solid/Road

sprite $RoadXs [11x10/16z] Oy05-C40n687Kfpy_8nWGPWm8vY443301sJ21H1C94C1

sprite $RoadSm [13x12/16z] VSd50OD040NGTOky_gkD1pWnyZMSJQFU-HgKoVsj8qB2ht27yJD_ND0xf61lPBZzp83vC-4uJm

sprite $RoadMd [17x16/16z] ZOk35S1044HprgB_Qizyp5zZldy0mES1qfgHcO5gKdF15UrQ7hCVxLbm0x7dDgk-48BN2_6HiDsALiSXy8ESXor5jHTnTBGNPdQoKnUdUoa

sprite $RoadLg [22x20/16z] {
hS_50GGX30NGZEE__sfnNvTtWpZznmBl8dYc_IeqQ_r5SEung2Yx411n14kVYdLDlonz7XYbNrqU6w8phPNKLgPRI-VVF0-TcioGoFCysppSAUDR_oinIqTc
gyx2xwOJHHzm
}

!procedure Road($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Road', $name, $tech)
!endprocedure
