' definition of the Item fontawesome-5/Solid/Rss

sprite $RssXs [8x10/16z] Ou02Vdv-CCtE3sCnC8COO1u8yu8Pp62b80JYiG0PC1u_H08

sprite $RssSm [10x12/16z] FOg50SCm4CGKCsl_QSlDun5twRd-I8rVV2tTG4pV2FYx7PeA2j2Lw230jABbvntN3sMP2ThXEay

sprite $RssMd [14x16/16z] LKm50WGX4C9k-VzlJyQhPJe03vHHt6-Yi3wBoJj_pxvhzlX2SxoyUKeurTbaipi5GBJPQeEmRDpaLwJfDoCFRsnBMOswX4hkCmLD4vvqdzjM0Xm4vnGl

sprite $RssLg [17x20/16z] {
NOq50i0W30EBE_p_jsio9nF2LIAxNFH_iA2-0TLqDqZhqf1NlXDP-MY2qDLH0yu8OkwbLOs5ULCqnEbHHCzsatGDNVEMtUqAUUSlODGcXaUf70nAkAN7jzlV
cGILcPYyWDTk0XbCX9-2Y-mw
}

!procedure Rss($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Rss', $name, $tech)
!endprocedure
