' definition of the Item fontawesome-5/Solid/RulerHorizontal

sprite $RulerHorizontalXs [11x10/16z] Oo04-FbP-7cvWGIGXM1Y1zm89dR3

sprite $RulerHorizontalSm [13x12/16z] ZS7N0K1054N1kp8ldFwxvKzcPrIdcBQ3BREr1g8maKu7D7GO12ELr1terGe

sprite $RulerHorizontalMd [17x16/16z] Ow02OEJcOkHcO-TcvkHcu0OXVdvUHdvEJduM7du6VX328i3F1oQWY0o0gOk11HKma-4N

sprite $RulerHorizontalLg [22x20/16z] Ow0hOEJcPcRcvcRWukPWW3Cv-VdvMLZu-Hbu-RaPu4n-4aJf3BYnYZ8mis02Hbg59

!procedure RulerHorizontal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/RulerHorizontal', $name, $tech)
!endprocedure
