' definition of the Item fontawesome-5/Solid/SearchMinus

sprite $SearchMinusXs [10x10/16z] FSZ50OK0342nzmKxPVzfSKYzrMZev535tKOT51zaQNX_ULik7PP2DpO

sprite $SearchMinusSm [12x12/16z] NSUr0OG00C30l0kI_RSb3NhTaS4NYPe7qG5kUWCS80g3FCCaAERt5rxU80eeUVi77Zh_3RcP9fjB5W

sprite $SearchMinusMd [16x16/16z] NOq75i0W34BfNYhtlsrVWlkthYG0Z9lfG2NHkI7i7e9jfRlP-P2kiQVpaMv5PFncCZgQJEMTGAx0KUSNtSYdo1Da-AdBfUGKJXY7_9PQmBAj04uL2YfWAlm

sprite $SearchMinusLg [20x20/16z] {
NO-54SGm40CLCjlglzkVUurnmvj3_76LvSDAfeXJSR8gV-CEKrhY_1lqqjLyTwGVBibLyaOM-2n0uHS57irJB2u8YtE0FS8w_DdtxkznI5Dkxf6-vylhojo0
21JEwZHqV7GZ1GTjHawMm3NI_m
}

!procedure SearchMinus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SearchMinus', $name, $tech)
!endprocedure
