' definition of the Item fontawesome-5/Solid/SearchLocation

sprite $SearchLocationXs [10x10/16z] 9S650SC00C0Wvglc_skhW6yVe1FqnXZVD2PAKnfy8a8Zrg0R6AW0QWS

sprite $SearchLocationSm [12x12/16z] NOU50OH00CC2d5lsd_PTgHUW6td21mw0Poqtm0DDA7H98b5GK3daySVBk61Zim67ncEe09jgK_dWTAu

sprite $SearchLocationMd [16x16/16z] {
NSw5TGLH203HMLUO_hlDWNo_AqyHocuklAHjXwQUyn9wFqwJCcZ7A8IkJDgfJcRN47G0dLaSBo6S82jAJKX7M0mUeGgFg7Fefg06fySuK2urqh9I5aiEZuqo
ZS2gRhpr1ZyRVm
}

sprite $SearchLocationLg [20x20/16z] {
PSj5Gc110CJGV6_F_Kyx0nJEMxMaU7DFnqL4DngV_0AXjWtOX_evF8ccXMGDgdh3J7ZhngvDuLGWNxU5xW7w02hisXNG2WnDRGFq1YxTa-S2W0xWT0TMtgZQ
Y9KfeCuJk9PQ2NyWYd5NTG7nrFjpmYyhvK-g_2tl_m
}

!procedure SearchLocation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SearchLocation', $name, $tech)
!endprocedure
