' definition of the Item fontawesome-5/Solid/Seedling

sprite $SeedlingXs [10x10/16z] Oq07_600PJ2227OG0UQo86IWge4YS9quMG

sprite $SeedlingSm [12x12/16z] Oy026Fdv-PcPcK1CRduWu09YNWPsVX1WG90C43OtBuW9vS2CO06p4GOIPZFmWKa

sprite $SeedlingMd [16x16/16z] hOh50G0X30GNT-Y_MfpaTwyR95d11ohLoigrHSefg2LpsyJzIxWhSQQMP-BgXd8an3DMUQ6kPYfhjiIl6ayE

sprite $SeedlingLg [20x20/16z] lSwr0S0m30J0DxD__sd3p5Mk4miVQ6ijjYG7s4ZSyEXbZaha802E4oquMNC09tcQhTYEoFLevGHaqS0kAR7XER3OqNNwSeyCF-Gy7hG

!procedure Seedling($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Seedling', $name, $tech)
!endprocedure
