' definition of the Item fontawesome-5/Solid/Seedling

sprite $SeedlingXs [10x10/16z] uwS3

sprite $SeedlingSm [12x12/16z] unza

sprite $SeedlingMd [16x16/16z] un_X

sprite $SeedlingLg [20x20/16z] unzKO1G

!procedure Seedling($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Seedling', $name, $tech)
!endprocedure
