' definition of the Item fontawesome-5/Solid/ShareAltSquare

sprite $ShareAltSquareXs [8x10/16z] Ou02Lduam06b6HY013CR0mkK0nTcXSl308m5

sprite $ShareAltSquareSm [10x12/16z] Oq00Vbm0A0LdyG59FWP69dvU49y98SN8nS35Y5370nDcG3693mfu

sprite $ShareAltSquareMd [14x16/16z] RSpL0O1G34FHYtkp_xGuFElvgeRKQi6moRN4yngMq06zRgi9u6aQmEAZJhy9gBLPcFHucU7Sb1aKeufm

sprite $ShareAltSquareLg [17x20/16z] bOlL0SCm30KlPlR-qvP1LZ7tzH0qBYniVkx0nTK3JleE8FomWBcP0ebjOCMRAjRj-HOBEsII-zpOeCcmw6FNmRHGvXk63b2-epa2

!procedure ShareAltSquare($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ShareAltSquare', $name, $tech)
!endprocedure
