' definition of the Item fontawesome-5/Solid/ShareSquare

sprite $ShareSquareXs [11x9/16z] uwSz

sprite $ShareSquareSm [13x11/16z] unzS

sprite $ShareSquareMd [17x15/16z] un_P

sprite $ShareSquareLg [22x19/16z] un_aO1G

!procedure ShareSquare($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ShareSquare', $name, $tech)
!endprocedure
