' definition of the Item fontawesome-5/Solid/ShippingFast

sprite $ShippingFastXs [12x10/16z] POk30S105CLIkzb_sXg7VEE19midfHS0lin0Uw8uSQ620x_4jydx7eTXF3Cu2rVU0G

sprite $ShippingFastSm [15x12/16z] TOnL0W0X44BPxlN-fpNUoAUOGqb70eS2gODXNZmkKnjN0766r-QMdnf-HgKj2kpuxHwEPhJJnzRxQUQb5Skg0W

sprite $ShippingFastMd [20x16/16z] {
XOs54GD040BttV_whpR2n7N7E060PHSANEXs0oxCjrtNwi8S2S372vVK2j2cq3jq5JaljdPeERVGoj3IWT3gWeUXj-UTql_jvda7sSH5mJ30OWXXIQK0qJAQ
I3Ubm2Xrhazm1
}

sprite $ShippingFastLg [25x20/16z] {
fSy50eCm00J1moMo_tzj9Jdgti5P997KSZRf0fV6Ps5z6x2xhxNzoOhDfJJZ9jPFDHxRa0ngS3bB3YwSETJoPD0rZ4VJWu3z4royEqzxt4AMjB8k1vb64YnB
ENXN-YWD15yG8Ac0dA1L4O2egWCO9Eq1
}

!procedure ShippingFast($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ShippingFast', $name, $tech)
!endprocedure
