' definition of the Item fontawesome-5/Solid/SignInAlt

sprite $SignInAltXs [10x10/16z] uwS3

sprite $SignInAltSm [12x12/16z] unza

sprite $SignInAltMd [16x16/16z] un_X

sprite $SignInAltLg [20x20/16z] unzKO1G

!procedure SignInAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SignInAlt', $name, $tech)
!endprocedure
