' definition of the Item fontawesome-5/Solid/Sink

sprite $SinkXs [10x10/16z] Om03FWOeuEVdXx4O-BbWB13WuWAo81GZ5qWMo8K31ZX02C9Px

sprite $SinkSm [12x12/16z] JShN0S0W409GqcDb_sdjek_h3a0N32OMkd7D-oZ7hNjEOxj9ryP7ttFp-mLEB2WEbsva

sprite $SinkMd [16x16/16z] NSm50W8W40NH8MpzS__Jsh7uQ3RuE3WeLC-KQAOsFcBZx5ZURRAyY_AEsf_lW--EZdS_O9V4nFUAVnWhZgUgSR5g32jO4YOt

sprite $SinkLg [20x20/16z] {
ROw50G0X30Fp5fpiF-sx8OSVq1OVp14LEh25SZgfdaKCaYcTEoRVk6b6upuQDtZltUly3i2phDjzvGpojxl4HD8eahecyfXRibhGOmar03jVvuv3hGnsKg4S
i04
}

!procedure Sink($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Sink', $name, $tech)
!endprocedure
