' definition of the Item fontawesome-5/Solid/Sitemap

sprite $SitemapXs [12x10/16z] Om01Vdv-48MNpSdFoO2GW8d102C39oD47CXWvkU7w6K1op61sRoeR

sprite $SitemapSm [15x12/16z] Om03Vdv-FZ03pkKdcil0nmfdCW817nk8177uaG28Yr0CP38pCm75c9aPG4ncY18moGGay7C1

sprite $SitemapMd [20x16/16z] dSo35KGn40NGzsEd_sfZhN4FneCX5W4tOlDVpu_U3IeZfRZ38ZOQkZZYU7_3r9wvkMqb9UF720INSyu2q2KouBAbZ1KPNm7NuctFl-g5srxxbG4

sprite $SitemapLg [25x20/16z] hP230G1130GtRq__rRvjpVdYQC2ZeT06Ek8ZGVAV8De8B8uXRlytR98z4XHiQ5C8OKiZY73Nhiu4nxYZop5gjip27QEo57YV1Kcx-vBHK8oTg

!procedure Sitemap($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Sitemap', $name, $tech)
!endprocedure
