' definition of the Item fontawesome-5/Solid/Slash

sprite $SlashXs [12x10/16z] Oq02pFoSI3n-Vg8uhFmSf6jYvmS

sprite $SlashSm [15x12/16z] POkv0G0W4CByVyt-szgAHmSahhatYoCzWNG7MVfXIIzMy5yVqWT83rOeqZSN

sprite $SlashMd [20x16/16z] ZS_L0O1G20LGk_Nilwq3l00-kJryGt4lO_7ys8hdoLCyPvIcM8hdpPNNZsNJMgc3SjIaCMgjZRgBvz8ezGC

sprite $SlashLg [25x20/16z] bT350S0m30F0C2VQVzkgVxdWxvdTSZeQK2L404UAlyLBMgGafLA6sGvItAP4APtIfIIASIm5NigW52dPR1ViDnnpxqRfThk_RvZcwpBs1G

!procedure Slash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Slash', $name, $tech)
!endprocedure
