' definition of the Item fontawesome-5/Solid/SortUp

sprite $SortUpXs [6x10/16z] Ou015X31pyy998207KpoC-05

sprite $SortUpSm [7x12/16z] Oq07_FmG4aJpWm0l0ny8y38G3G

sprite $SortUpMd [9x16/16z] Oy0A-DWXD3S_Fmk8vkG70YO61dP-C61au8S21aOeOA0I

sprite $SortUpLg [12x20/16z] Oy0BME0iHdv-BXYR7mWu8Km-VX3W08j20Ji30oy_3B11XQ5Q1Xu

!procedure SortUp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SortUp', $name, $tech)
!endprocedure
