' definition of the Item fontawesome-5/Solid/SortAmountUp

sprite $SortAmountUpXs [10x10/16z] Oq02_4040Y0I8iBCoS_9m0O425aG2qq70xeO6nD25aW3

sprite $SortAmountUpSm [12x12/16z] ROo30K0X503lczN-qsRNFPC61Olo8AtnUsvbAJjxt0avqY9Ytkri8VT_5gOx8PSB-2SO

sprite $SortAmountUpMd [16x16/16z] TOw55GCn3CLq7Cx-qnRy34K5pPzlAd0D1UPCCAP2UrmxR4eIxuAnR7sU6wa9Jtz_fclzQZQBWDg1s3fVRQ_VmfRvyA_-EH_UwpUNA9TAlWC

sprite $SortAmountUpLg [20x20/16z] XO-50G0X24Njrh__jDTX-qmQI1_6pbkgZqC2w7L_N4AgTE4nPHXSk5p7hGMybOIh6tQf0P7bYmlTnq8dtn6QVAAZuxryInr_HgZpvJgUw_hi

!procedure SortAmountUp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SortAmountUp', $name, $tech)
!endprocedure
