' definition of the Item fontawesome-5/Solid/SortAmountDown

sprite $SortAmountDownXs [10x10/16z] uwS3

sprite $SortAmountDownSm [12x12/16z] unza

sprite $SortAmountDownMd [16x16/16z] un_X

sprite $SortAmountDownLg [20x20/16z] unzKO1G

!procedure SortAmountDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SortAmountDown', $name, $tech)
!endprocedure
