' definition of the Item fontawesome-5/Solid/SortAlphaDown

sprite $SortAlphaDownXs [8x10/16z] DKd50K0X5EA7NWpsd_PrakWPDE0V_9B1RCPszkdyU0TUEFsSLaIk

sprite $SortAlphaDownSm [10x12/16z] LOk50G0X30Fphd3xJukxj54DXpX-Ae8ZeuM3Z0nKb1vJzmQMZMtHyGS4xB4IZKywKlUNj5jhFG

sprite $SortAlphaDownMd [14x16/16z] NOs50S0W40FhnM__QN4_z2qvDZvtvbUwAzw6EqV0Y5ui8uAJVqI95acKiZMAdFdaQ50Z5z6hoc_0c1ZT3vmdYLnCFMyD71YTdAxXdbtIdGW

sprite $SortAlphaDownLg [17x20/16z] {
TO-55GD120MHSvl-kytxctEPLHpiXQPPF_d_1QmAm0z5-T2V5GCTd1NWa8SY4EEXc2aSYl8ig-B2jw8HUIWgn7Glswx5XhNGRBvM5mkBKW6av0cQnirwQ8yS
atgUJEGwovqV
}

!procedure SortAlphaDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/SortAlphaDown', $name, $tech)
!endprocedure
