' definition of the Item fontawesome-5/Solid/StepForward

sprite $StepForwardXs [8x10/16z] Ou015duW0SIi_FmmcXz6ywFHt12Q3oBF0rRFo0VM3m

sprite $StepForwardSm [10x12/16z] Oq02_2225qJoypF2M40cdCNF165102OBBWlN0JS5PZ8lo0ukFWO

sprite $StepForwardMd [14x16/16z] ZSUr0S0m30NHCpJ1st_QC2cLXV_ngpIUVveJCEeXBQUCCWMPWwn1Dekl-6Zcev57WpslI0T82LO

sprite $StepForwardLg [17x20/16z] bS-30S0m443HeDRVVzfQiVN24vvKwNlGDFNHIQWlWENe5D3QG6_0BIOmsi1e0xCDb8EsG0iJf3112HF-mSbh_mVYM3V0J1i

!procedure StepForward($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/StepForward', $name, $tech)
!endprocedure
