' definition of the Item fontawesome-5/Solid/StreetView

sprite $StreetViewXs [10x10/16z] Om01VY26CFXXJ0vCCJOK5a8MGd7mWm0tFqoC1qXnCZ0mSVFp0G

sprite $StreetViewSm [12x12/16z] RSor0OG04031-yTr-gyMTzXeeeqbSOHFHt88welR3_Se5zK2VqNy9TipK_N7NoJqNTlr_4O

sprite $StreetViewMd [16x16/16z] ZOrL0i0m24EfJrXp_zikCEDpgJuiSgb3eWQ0o4hEWRFdeqg41jF7wbn-ymv4mom7iKeoIFmNuyAgLJ8s1frPE37n3FHgY1KnapClXVB6Aqro0W

sprite $StreetViewLg [20x20/16z] {
fP2r0O1040JltN_whnPto9ZeN5PsCaOUCE7aXcBcewu_OX6G9-fp1KIvOE6rnF-8ELO-zYRPKQ4QlPRbx8vFunPZeeXUvLXZSqcYmrENYg6RHTBMcfM9G1Up
B5nSxSgkc4cTdHgKo0W
}

!procedure StreetView($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/StreetView', $name, $tech)
!endprocedure
