' definition of the Item fontawesome-5/Solid/Strikethrough

sprite $StrikethroughXs [10x10/16z] Oq06_4301c9mylFpyVD3X62IBFpyZ60HE43HomAIuWIn47AC40O

sprite $StrikethroughSm [12x12/16z] ROs50S0W3C0wz-N_Qt67GDsa0SEPNNYjE_7Pn6hzsQG2qmHyauK26G39JC7_A8xDt_zEnce

sprite $StrikethroughMd [16x16/16z] RStL0S10309GKbVOVzeQLx_t5GzoOY3dvaexMJWDdPpt3XfLpaVdbrgQuhf5KZkQFX1lkBJJXAJ0JYgTIkthhP8P5aw9otrv1G

sprite $StrikethroughLg [20x20/16z] ZS_L0KCX5C3GF7Uo_xHLhDxp1zVvh1qlUcf68vdPHBHu4O9NH3bkwAk_XYp_hJpflJWQajt_zCkBcL-E-hguwgeBTws61kZKbiY2P3Rfo1fl0X-T0G

!procedure Strikethrough($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Strikethrough', $name, $tech)
!endprocedure
