' definition of the Item fontawesome-5/Solid/Synagogue

sprite $SynagogueXs [12x10/16z] NOh50S100CAWxjb_slefBo3HcqCnGAfnx5YclTle7QcXdIpOeOCMU3jPL-olN_KB

sprite $SynagogueSm [15x12/16z] RSc54O00581GxFoo_xHsAvVlOAjAkANM3wdtDsYSp24svg90RI1efeOQlRhH6p-tXJjJY3zE

sprite $SynagogueMd [20x16/16z] bSxL0G8n54JHk2Ut_svvWyCNp6xiHDqZ_hZlPC1_qaB9xyGzytFLySBmj0rgEiGR52_JBcJLReeWgpQQPWbkasQGK7UXF8pVhAVzRKFtVfaUk_-q2m

sprite $SynagogueLg [25x20/16z] {
fSsr0K0X54FHu4xsd_Qx0XsdlK_mKIn69Cc4dk41hSYBna_bm-D3SoSYT-q30K3OGGZOy1CCnH4aDkK8XTTviOUS8F8H_56vKOOxMxb39bduXCCJE1KCK4OX
OZCAQWzb4EHiM04
}

!procedure Synagogue($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Synagogue', $name, $tech)
!endprocedure
