' definition of the Item fontawesome-5/Solid/Sync

sprite $SyncXs [10x10/16z] uwS3

sprite $SyncSm [12x12/16z] unza

sprite $SyncMd [16x16/16z] un_X

sprite $SyncLg [20x20/16z] unzKO1G

!procedure Sync($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Sync', $name, $tech)
!endprocedure
