' definition of the Item fontawesome-5/Solid/Syringe

sprite $SyringeXs [10x10/16z] Ou02LYZD3q9WmCqFPV3pSCDO_3my_20Q1C02x406L0gc7C60cGq

sprite $SyringeSm [12x12/16z] FKp50S0m4AetdlsdFUTuuKUYWEpxQ11hlwk6BU8EkbDi5xznnUjCnOUoKd3GqxguJZ

sprite $SyringeMd [16x16/16z] JOm54e104CEAE_d_Q-7ykgDDCYk_I_tMMzhf6wwmEnZWVRKtlGnmMStgu8PK7CNgpQ3Ln5tMdS6QvmMtJO7Px7tgxA_Y7GpZDDYK_7u

sprite $SyringeLg [20x20/16z] {
NSs54SKm30JH3QDy_LVx8UZJ3hyHa1fQh01c6Ke2md2LH9HPyBRf67tdEgtdf5_RsGmdIMaoJjpPfUQGLWhYd5nE0jqDpyU9_QIHTsWQRUgmTyhC22CpeoXR
KVH68hSLo7q1
}

!procedure Syringe($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Syringe', $name, $tech)
!endprocedure
