' definition of the Item fontawesome-5/Solid/TabletAlt

sprite $TabletAltXs [8x9/16z] uwSI

sprite $TabletAltSm [10x11/16z] uwSh

sprite $TabletAltMd [14x15/16z] unzs

sprite $TabletAltLg [17x19/16z] uwSKZ08

!procedure TabletAlt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/TabletAlt', $name, $tech)
!endprocedure
