' definition of the Item fontawesome-5/Solid/Tenge

sprite $TengeXs [7x9/16z] uwSC

sprite $TengeSm [9x11/16z] uwSz

sprite $TengeMd [12x15/16z] un-2

sprite $TengeLg [15x19/16z] uySDHW4

!procedure Tenge($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Tenge', $name, $tech)
!endprocedure
