' definition of the Item fontawesome-5/Solid/ThermometerEmpty

sprite $ThermometerEmptyXs [5x10/16z] ROG70G0W08FmV-dVrW9k0Em6nYt2DmTr51NL1m

sprite $ThermometerEmptySm [6x12/16z] TSO50S0m00F1Z7ddNsr1G8EVB9BSRbCQNL_Vyn-i7JSNJ6wB_DWh

sprite $ThermometerEmptyMd [8x16/16z] bOt50S103CDyZ8dstxOyG8rFIHeadUAKIHsfdlMp8ln-LjaH9WL8P_VPI3qB3K6A3Vju1m

sprite $ThermometerEmptyLg [10x20/16z] hSwt0GCn5CMmTpb8NzX_MkSHp0ebywexycu7Rp6dlxavaxnrs5yQVzFuQP-D7Gibq21GtMM3Wx2qEawL4ns_PvKy0G

!procedure ThermometerEmpty($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ThermometerEmpty', $name, $tech)
!endprocedure
