' definition of the Item fontawesome-5/Solid/ThLarge

sprite $ThLargeXs [10x10/16z] Ou03VX00a_XPnEhWXhC

sprite $ThLargeSm [12x12/16z] Oq02FFmWmC0F0OJPV4XiP7FuIJI7cGy8U1duG

sprite $ThLargeMd [16x16/16z] Oq03J7nWmCx02s7mGm43bAQKpm6X-61yTFlvqFLJcS_020OCK9eH

sprite $ThLargeLg [20x20/16z] Oy06sA20aO45nkI70Mu6E7EWn9YveO2PWHFAuiBc3MwO1ew1TpFSBPm8CMnk1W

!procedure ThLarge($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/ThLarge', $name, $tech)
!endprocedure
