' definition of the Item fontawesome-5/Solid/Tint

sprite $TintXs [6x10/16z] 7SI30G0n04FH76hy_QSjeYTfwWP3iXY6PTZUha8Tdty3

sprite $TintSm [8x12/16z] 5SM50O004810x9RzjrNk0tulP1EYJrdKQk0r2sekazcCKlfGCNm

sprite $TintMd [10x16/16z] HOo30G0n303pg77xJrlZOaedooBmhWpYJ3vWjy3tnD3PBSWYYSalR2mNnIJnhEp5VpCJ-EG7KlSvpTSlq9CA

sprite $TintLg [13x20/16z] HSu54aGX3C3GV3SWzp_jQgTzeq7BJzz9YvA6JXdg85nQMtwrUCgVcO_Ly0qDDzoc2KlRj7H397NEKJ7hbFTGuOoFDdMVkogncdElG_K1tW

!procedure Tint($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Tint', $name, $tech)
!endprocedure
