' definition of the Item fontawesome-5/Solid/Transgender

sprite $TransgenderXs [7x9/16z] uwSC

sprite $TransgenderSm [9x11/16z] uwSz

sprite $TransgenderMd [12x15/16z] un-2

sprite $TransgenderLg [15x19/16z] uySDHW4

!procedure Transgender($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Transgender', $name, $tech)
!endprocedure
