' definition of the Item fontawesome-5/Solid/TruckLoading

sprite $TruckLoadingXs [12x10/16z] Ou00NduWWBBvCTWSG7aecusVYP6V7SB6Gx8mC720ML0psFdP6FXvOEO2QG

sprite $TruckLoadingSm [15x12/16z] TSUt0S8040ImSyxM_jEIlm6iJYb0hRlieMgsXwNQaOrguATDzS2IF7kGDCbmmfb8iyFQX0mMjCaJpZi

sprite $TruckLoadingMd [20x16/16z] dSZ50SC000IWYtlOVzkwUtcIYyBHrSr_tSZD3MkHXVRgPleqB5SNPC3TyUBwg-iST5TNOAgJL2iqFKcJfEXNzfKiiiqPh6qn6H96O2YpmuAQjSf93Ta

sprite $TruckLoadingLg [25x20/16z] {
jSd50OHG00FHuCxqN-q2t-swSqkUiaP2EV17s6weO45QWJ67os07d3dCm6IUEmTppGT0bmEXCOS3tvd3J2X0DevP3LZqDTnyNTBzmJ2OSxjnVGlqjU2wXp70
T83fN7f9dLDEJBjy1wQvXsDIscf-FG
}

!procedure TruckLoading($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/TruckLoading', $name, $tech)
!endprocedure
