' definition of the Item fontawesome-5/Solid/UserSecret

sprite $UserSecretXs [8x10/16z] 5Sl75OG0440XDfhz_NVh6-xWSiDQOMzyQI1PgN7OMdlrLjBGqfZP0m

sprite $UserSecretSm [10x12/16z] 9SE53S0m0C2mZ5VC_zSMBPdXfx0uCPnE1-YMu3dEwumCXvUd1mIt4_oqLa4helugudPxg7KjQWS

sprite $UserSecretMd [14x16/16z] JSk50O0m3031nw6IttzQtAuQun0m9hWK3mCNBno6wYLriFXfWBAaNF9Ihy6nWkU69iBmt07u0SAY6Zf1fw8pAdZTPzPPjUbbzZ5KMrz5guV5lmq

sprite $UserSecretLg [17x20/16z] {
NSx50O1G3C3GuF0j-q-B-xlLowvq44TknLtBgV74ANfgs8o-rD3v0UzKgTZPGGkKaKCG33JMR7mh_yHqx4nUAg3NMAiPzVgBsa9rjBY1Cj2xzOrkQam47tsj
-1AZLluCxbf_5W
}

!procedure UserSecret($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/UserSecret', $name, $tech)
!endprocedure
