' definition of the Item fontawesome-5/Solid/UserNinja

sprite $UserNinjaXs [8x10/16z] LSV50O100C2muaxtdnOzpIz08u236YVu0L395W5RLDJJsWq

sprite $UserNinjaSm [10x12/16z] LSZL0S0m24NHQ0sv-szRtcSEJYkRha6dc1xW7cW3CzF6G9eOCDk1NIsY5bZDW8VoSGX4VW

sprite $UserNinjaMd [14x16/16z] XOm50aCn24FPwfhxttOD-wwl2YGHfS1F7oCUH2k32gpbABmnfk332a0XCAE8o1lbbrDIPO95aokyqIVoCO2cCMkACACW4GgB5yAk-W4

sprite $UserNinjaLg [17x20/16z] {
bSo54SD034JHFJ33xx_RP4SNHhy1iHH6jgnGYbInJUOYqKZ6JRbsP0EJR04MMvbT9su6dVLp6cYI6iAeqFxGwwEgaBEi1wAEP0JOMWr9OBiIs3OILfgTmmgF
zXC
}

!procedure UserNinja($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/UserNinja', $name, $tech)
!endprocedure
