' definition of the Item fontawesome-5/Solid/UserTimes

sprite $UserTimesXs [12x10/16z] LSc50O0m4C30u4xsdnQjNliEO4FGgXi_NtKl_iFmPQ9JcVtmlT_sdGB0ehy1

sprite $UserTimesSm [15x12/16z] LOg50O0m30HnXzj_MohHgoGlGs5a6voNWaiAdizDtZbTodmtYjo1hyor3cS1MdT_OEnbbA5oa3HPlbd-

sprite $UserTimesMd [20x16/16z] TSk35SHG00NHYV4n_LUxY7cF7vW4Myuw_pWgz1OEEYdO1PrKxDhzMzgI170IWLgpieQ9lyOfEibg0tIfBIX2h21gfrJk84CRyOX9_v1vKhnctSFt2m

sprite $UserTimesLg [25x20/16z] {
dS-50GCX44JHEJVWzrzjX9suv-7EAWovZ7hKKVMwXpKoMx7qUC3-MvYEJx7MlsAJjxNuSAOgkcoRLIq0gy84B7hY4b8_rfYxQ805a4RCLnTc3Q0PC3yqIEeb
xZGACtSsXS8z1NvUwBWpAEm1
}

!procedure UserTimes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/UserTimes', $name, $tech)
!endprocedure
