' definition of the Item fontawesome-5/Solid/UserPlus

sprite $UserPlusXs [12x10/16z] NSor0SC030H09MQy_QSrVkLhnAgBNyKVItBmoQNeQfxD5L2ZBAc2VDf5zYG_0G

sprite $UserPlusSm [15x12/16z] ROm50a0X34BPxvJxdzPkVUOs01RXWS9FIobTLUQhBp_xUzSytTpdTELfAsMBIOH_pe-K86O2-5PSBBM5RVctfG4

sprite $UserPlusMd [20x16/16z] TSw50S0W30J017VsdxQ2wxVOeP1Yeu0vClwP21FDg8lXOBOOJGEJJ8nxImEPt6G9VMdN5_XcqWi4j8wslJJsLEkIa180DLjAd89NauUzBm

sprite $UserPlusLg [25x20/16z] {
bO-50SCm40CJCsl_QGjcB2XetUELn7qGrogAABO0PDsJRmfmXmJW2x1s3qXjneel9t3vv8VNxssC1QmnYUYt7__vEiTKDXv4t9d6J-iXq4areD2K6jsfpkYt
ITKCR0O1ipB0tu3EFi_W2G
}

!procedure UserPlus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/UserPlus', $name, $tech)
!endprocedure
