' definition of the Item fontawesome-5/Solid/Venus

sprite $VenusXs [5x10/16z] 7S650OG0000XFcrl_sajyFWN-RJDD4MgQ4C_Xa9V9m

sprite $VenusSm [6x12/16z] Ou02VdvU4C73py_23-Q2ILOm2UI1-Nn0DM0-N04xFpk8myV

sprite $VenusMd [8x16/16z] JOc54S0m08IeUzb_srmydBn0v_esO342UgsV_-e1w2_0vfVo50MC6RaWnbTaudAAeVgMl4TFr04

sprite $VenusLg [11x20/16z] LSx50O0m5C3Gu4xsdnQjlalbAxLk71fUZQy3w0r0xM3JjTUMnwg7ychrz8p5I_WT5TtVrdgm6hJ4U_zL73hpwvLWq7ATixg-zvIGox8R

!procedure Venus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Venus', $name, $tech)
!endprocedure
