' definition of the Item fontawesome-5/Solid/Wallet

sprite $WalletXs [10x10/16z] Oq00VWI02n4560Y80W

sprite $WalletSm [12x12/16z] Oq06_730oC_F0mFi_FpSCC35JmfWOS0fnOF4Pk3cWm5k

sprite $WalletMd [16x16/16z] hS6t0S0m30D1m3d__jkwbCZAGNVAngioQI8mh7r5SEsLcOOcNTGsyvg99DTq0m

sprite $WalletLg [20x20/16z] lS6r0O1G5C30u4xstvRsowkmEq9Z0R32RWMLahflkTx_BKoM1ZehYyzCrjWjRGGk

!procedure Wallet($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Solid/Wallet', $name, $tech)
!endprocedure
