@startuml
sprite $AzureBlobStorageLg [24x20/16z] fT3L0G8n54HHv8qa_VUB3nBvugwVzO1pihLcUyF662dUgg6SBYZnT4p5WXDFX_INQ-F-TRuIKUdhErkxBOd8SrhlTa-wUNZqyEZXqSDV_dWlc76ZqiqBowu

sprite $AzureBlobStorageMd [17x14/16z] ZSt50S0m20NGoZUo_xvrF_N51T2BuyyvuODi2zG6up0kG3WRT9l-puMy2llDG9pr3tj8jPQsAS7R-Rp8Sh6T7p-qt5HbcLSHI3rn1W

!function AzureBlobStorage($id, $name="Blob Storage", $tech="")
  CloudElement($id, 'azure/DatabasesServiceColor/AzureBlobStorage', $name, $tech)
!endfunction
!function AzureBlobStorageCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureBlobStorageMd>', 'Blob Storage', $funcName, $content)
!endfunction
@enduml
