' definition of the Item aws-q2-2022/Architecture/Containers/AmazonEcsAnywhere

sprite $AmazonEcsAnywhereXs [10x10/16z] FSO10W0H30F176Jp_nSVO6axW6UzypZrMOCW9hg3hCykJZJRGXzBAHX1HlDEpQP-

sprite $AmazonEcsAnywhereSm [12x12/16z] JSY70S0W20LHYdBiFt4-wMTx0jJLtlm-J56hbBG7SLhRt4grdEdkuoxSpUonvf5Z5cuYrKfl522gqUDcEW

sprite $AmazonEcsAnywhereMd [16x16/16z] LSa74e1034BHD23tFx7CsBzkULavtW7GRq3xFpZTmPp7A0M9vEcY464roBK5CBD8s6idbQC-lQN8z5-tptV6xLKn8pYdbL8Nb9HinvB6o-tPf7Jwxczt-W

sprite $AmazonEcsAnywhereLg [20x20/16z] {
PSZ90KH1209Hf1Lwyazu_FjMTNjUqbLrVgCEyyTMJ8r3TneH8kfcXJ8rD7WQqXOGab27sQI2R63RN4q9HobsQyHwAFEmkKXidpPXjeTgf2ypsx8PDnCo8ZWi
RpP9Dzi5TvjDCrkYlDQmAT1osAc-x8k_B_eF
}

!procedure AmazonEcsAnywhere($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Architecture/Containers/AmazonEcsAnywhere', $name, $tech, $desc)
!endprocedure

!procedure AmazonEcsAnywhereCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEcsAnywhereLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure AmazonEcsAnywhereGroup($id, $name='Amazon Ecs Anywhere', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$AmazonEcsAnywhereLg>', $name, $tech)
!endprocedure
