@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsUndo element
include('elements/materials/Content/MaterialsUndo')
MaterialsUndo('element', 'Undo', 'an optional tech field')
@enduml
