@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsAddBox element
include('elements/materials/Content/MaterialsAddBox')
MaterialsAddBox('element', 'Add Box', 'an optional tech field')
@enduml
