@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsSort element
include('elements/materials/Content/MaterialsSort')
MaterialsSort('element', 'Sort', 'an optional tech field')
@enduml
