' definition of the Item simpleicons-6/U/Unraid

sprite $UnraidXs [10x10/16z] Oy0Dc60CVbOW1ZD0913324O61cOmYm74mcaG

sprite $UnraidSm [12x12/16z] Oo0UC35mi009C9EDWO67WH_CvaUmuIGpK1q_L1ip6qGFL8e

sprite $UnraidMd [16x16/16z] fSUr0S0m0CH0VPYp_xHcgcsfEWOIROiEgV73F2_yIRypyx9Lpo0r3Zd_GTbFyaDeWJ_SzjEV1G

sprite $UnraidLg [20x20/16z] jSYr0G0X542nTwxmzvyMzvwKOQfr6-VWk3dwayMTmBkcM5vtW739ba_oVUtvOkalyNS2vzhTyWBFrjn2EfPy2_x4tq2OoW8

!procedure Unraid($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/U/Unraid', $name, $tech)
!endprocedure
