' definition of the Item simpleicons-6/U/Unsplash

sprite $UnsplashXs [10x10/16z] Os1WOEFdvmTIc2pi02Z31Q5GMOoCZFpO0G

sprite $UnsplashSm [12x12/16z] Om02VY3W0TA4sQY04GXW390yYCaCf76p2GC

sprite $UnsplashMd [16x16/16z] Om017duGO0OnAUCJ1dmW05791M92T29C8OhF0kDJ3W

sprite $UnsplashLg [20x20/16z] Om03Ddu8WF1eB4OnW9Z3XSAZaHWZ1F3J3G

!procedure Unsplash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/U/Unsplash', $name, $tech)
!endprocedure
