@startuml
sprite $AwsBusinessApplicationsLg [20x20/16z] {
VT253O1G54DHh7ss_xvynxbfxCGxlJRVoYIQanuIBcerhLNpGNSZApERUKPk6y-Ma210Eva9bDIDPoFp03Mx6VbhyMe4oZOC2sK9a6OU4PwprCaAroIRQEdy
rRpSIlRI3W
}

sprite $AwsBusinessApplicationsMd [14x14/16z] LSV50S0m5CDG5mp9tt_UCkgaXt-JU3MFWDfHjkPD_VfBlONqesZhaRp5MyucfUsglqAHchtBrRDbjrDLVU_GBDwD08OdO0K

!procedure AwsBusinessApplications($id, $name="Business Applications", $tech="")
  CloudElement($id, 'aws/BusinessApplications/AwsBusinessApplications', $name, $tech)
!endprocedure
!procedure AwsBusinessApplicationsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsBusinessApplicationsMd>', 'Business Applications', $funcName, $content)
!endprocedure
@enduml
