' definition of the Item material-4/Image/ExposureNeg2

sprite $ExposureNeg2Xs [10x10/16z] Oy0963cW36Pk1dwuA3yGyVFpCC2540nMe0HMam

sprite $ExposureNeg2Sm [12x12/16z] Oo0UyFFpCqAP7DmCxDm86LuM80PACp4miFF1HLduuKn6VZOsDXYRXOMP6QSb

sprite $ExposureNeg2Md [16x16/16z] dSur0eH00CNGF-wJ-vzs1QU4TA-BNcVSZGD89mDIvRHrKbfi_-aVvK_-_JcdhdLkh7Twc7FQyyPxxxmUzmK

sprite $ExposureNeg2Lg [20x20/16z] jSlL0KCX50FGu3mi-qzRmU6xFUWr_95mNk8K-16nKzyuKM7Z2m1BWrkWgFNAzlbKNrRrBrbGYQgE50fSIDmoTHtO65O56w4_b5RukJS

!procedure ExposureNeg2($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Image/ExposureNeg2', $name, $tech, $desc)
!endprocedure
