' definition of the Item material-4/Image/ViewComfy

sprite $ViewComfyXs [10x10/16z] Oy0AE1au6JcPETaP6FWP-9dusVXv61YOGP2HcGbP304GOfW

sprite $ViewComfySm [12x12/16z] Oo0AyFFpy3E12LGsBoyNBoE8G1Dd0W8mWLil3W

sprite $ViewComfyMd [16x16/16z] bOq33WLX48C7mQyllVzf7rR1UipMNajascJnhyoGKWff3EcWZmZxsoI_VanxbqO_lEyGuD0Q_FgszHLk-TxA5m

sprite $ViewComfyLg [20x20/16z] hKm35aD14EkicTp_jdtjjxaOH9_tJupnzoN4g7sC_eUH_7q5qXMoR640VbyAO1EGVvZMklkYj5PNybfCVbZ-OMldUjw0lNs-

!procedure ViewComfy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Image/ViewComfy', $name, $tech, $desc)
!endprocedure
