@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-19/bootstrap')

' loads the Item which embeds the element ServiceSsisLiftAndShiftIrCard
include('azure-19/Item/Databases/ServiceSsisLiftAndShiftIr')

' renders the element
ServiceSsisLiftAndShiftIrCard('ServiceSsisLiftAndShiftIrCard', 'Service Ssis Lift And Shift Ir Card', 'an optional description')
@enduml