@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-19/bootstrap')

' loads the Item which embeds the element ServiceAzureDataExplorerClusters
include('azure-19/Item/Databases/ServiceAzureDataExplorerClusters')

' renders the element
ServiceAzureDataExplorerClusters('ServiceAzureDataExplorerClusters', 'Service Azure Data Explorer Clusters', 'an optional tech label', 'an optional description')
@enduml