' definition of the Item simpleicons-7/A/Adyen

sprite $AdyenXs [10x10/16z] Oo0IiB8nS30nCh0niF7pSdEmiJ12nPau2Ui5

sprite $AdyenSm [12x12/16z] dOM50O0m40DVSPBzfuNQ0ctaJXPo3pzmyFK4Nb2IHEHBxX8QOMUKc4pc1m

sprite $AdyenMd [16x16/16z] lSV10K0008NG3m1g_sa1RC0xLVwmD6zEYuLBOutOgFtxbGsE46YG6Ug5N7J99pO

sprite $AdyenLg [20x20/16z] pSZL0SD04CJGEPhRqAh_QiDaDs0__Kcx4-ZFiAiSL1VB7h9TP-Q9m7GAHZIuNFwUdbqW0-ud4PdF-rRd0QtKYA6DtG

!procedure Adyen($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Adyen', $name, $tech)
!endprocedure
