' definition of the Item simpleicons-7/A/Airtable

sprite $AirtableXs [10x10/16z] Oq01dFpCO9eV0XWOMA4ie0WN4FF1P60q4rGjN1S3Z8LaAW

sprite $AirtableSm [12x12/16z] NOj50S0m0CGoNjc_sZBdTSZEQPgIBl42hgC_pg9i5bzSlPXMuneNJPzGDONoRlfb8G

sprite $AirtableMd [16x16/16z] PSUr0GGn00InEJDl_zK-Wq6PE9sC7jftILyMQ9e1vhzs8LKeUWhOeHU7oL3r5z3CCT_2_yF0T61-PRxbJnautG4

sprite $AirtableLg [20x20/16z] bSn5eWDH40B06lVX_gVz6dlnrB8RyA4fIUD2jURVvA3FfHfjhg5BOMTRQzMSeuunl-R3mawTawscPagfaYjxxVfMKzwsclAsu-g6wzla-bPJtaPNLazy0m

!procedure Airtable($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Airtable', $name, $tech)
!endprocedure
