' definition of the Item simpleicons-7/A/Apache

sprite $ApacheXs [10x10/16z] Oq03l5nG1Zy_bC62ASJ0peyXnC_BW0i

sprite $ApacheSm [12x12/16z] Ou02BWOuuETdWZ7v-FaO46ma5N0s8ny_8rm5YX9ck18kJhWm2v095sV0mWO

sprite $ApacheMd [16x16/16z] VSt50S1024HHDcx3xx_Rd29hl1EElPPaVpEUvN1bgVZF7uwojZFzqaiGj2VojauK_BQJzPzE-vYra-NoRku6

sprite $ApacheLg [20x20/16z] ZOz50aCX30Ln3tF_svPbIIf_bf4dxXrn1XXwj8KHxb43rCWZe3ytn7kK4EF0Gi_YcMsj1dJzMasGCp51c6OKcRFOzg97gJJl7X2TvS7Z2m

!procedure Apache($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Apache', $name, $tech)
!endprocedure
