' definition of the Item simpleicons-7/A/Artstation

sprite $ArtstationXs [10x10/16z] Oq05_FmGcXt8ue28G0H193y8WraGGIZWG30XIY3o33nW5Yy3Bm

sprite $ArtstationSm [12x12/16z] NOc55G0X3CN-kL_stvQ7qmPD8yyFNU3Bd-dGLKDyoRB17sL9unQsCnBbKkM5dKmC8dDgZrw30W

sprite $ArtstationMd [16x16/16z] RSm5OGC1002nApn3_AiTyne1wJ5S-k50Fs7jmqKjwCFfLZXwSqVTV9Qm55JDeC9O0Mf3Fs7hXn6ZJqCXFjMLyccjix-U0G

sprite $ArtstationLg [20x20/16z] {
VOw54S0W40JZ3jT_jUXb7jy8iBnD0zPjM-TImh4KxlKo5IS3Br6p3xZpG8MFWU-l5W2kvvO6WWU8tE7PAJS90z9vFhgNrtSn-CL0ePWd7Gi74fpKVadT5R9L
Y4u37yoSXIWd_LTZ0G
}

!procedure Artstation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Artstation', $name, $tech)
!endprocedure
