' definition of the Item simpleicons-7/A/Authy

sprite $AuthyXs [10x10/16z] BOU50S1020FJlll-q-87CGZZLIZF65A28asN_533LHVvLT65RtlLU0w04eK1

sprite $AuthySm [12x12/16z] DSZ50OK0042XzpkL_QUrvKXLF-zsTbLEXTzeY25ZbrByD5Bw8D_abxTRYfwYL14kmAlOZLN3kJC

sprite $AuthyMd [16x16/16z] {
LOy55W0X24Insxd_RNVCjtwJ1fcuXgBaqB08IyIbFoAfoxaMNk9uAPgRa8Wm5JmZn4kW8jD8CqYYGizVvKttP57uAy1qZIEMiWBYJ6QgbKJZr4VaMOCT-Q5m
sFow7tWXzH69-atp0G
}

sprite $AuthyLg [20x20/16z] {
PSs5WSL020N05pSsqt-r9zzbrWN8pNQgEIycDwtBZHVRznNxznNJBLVR2rqA4iW_98Krd4c_3Kcff65Zo8wMd2HuhYrffXmWSKdVmf6LOioXae8rEpDdSfaA
2OAwrVnNj3HKWZw9ozf1TPwIRDxbt-vLdul9KnvM5wtFlry
}

!procedure Authy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/A/Authy', $name, $tech, $desc)
!endprocedure
