' definition of the Item simpleicons-7/O/Onnx

sprite $OnnxXs [10x10/16z] 1S670S0W00CWkjoQ_xyj082G0kzXwV1SG75XI0M23vGSzuqxi1o-1ybwXHy

sprite $OnnxSm [12x12/16z] DSQr0GDH500Wdfn_sN_RLA426W1VpkTV-3OqTP456qXclZTmNxm2J4CXqho5W9MDn9stnED3l23ETprFy0C

sprite $OnnxMd [16x16/16z] 1S690GCX202mWFSfMFVVjWa80C2ktmk0qP3x0EuRTocWyRt8XbTNWX0OtGs2bkUoR4YCzs7Hc3WsBrwA7f2Gexvib03F4V04V9-bG8bAr0sStm3h0q2-wmJ-

sprite $OnnxLg [20x20/16z] {
PS7ROTWW400m7JPlpEs_RN-RH08y_fYvQlWfOUJNDe1zWReJu8qBwp0cO7d5wb0cSBGd0mWBHfJSW4f5j6l50XRIoCuI1oIUfnyiV92G9WOSRDxlfVA0HPCk
aW3wQDE04WLGCXbWTJ1sHFY0UN0xr7W0ENO1vWR8ctd6Ymm_HQaPy0y
}

!procedure Onnx($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/O/Onnx', $name, $tech)
!endprocedure
