' definition of the Item simpleicons-5/N/Nette

sprite $NetteXs [10x10/16z] uwS3

sprite $NetteSm [12x12/16z] unza

sprite $NetteMd [16x16/16z] un_X

sprite $NetteLg [20x20/16z] unzKO1G

!procedure Nette($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/N/Nette', $name, $tech)
!endprocedure
