' definition of the Item simpleicons-5/N/Newbalance

sprite $NewbalanceXs [10x10/16z] Oo046DaO-860WO63bvy9I0DP_600PZ03QKP-3h044B1ZDG8

sprite $NewbalanceSm [12x12/16z] ZOh50O104CI2E-c_MZZzhuyHgs7Vy-vBPMoNcj6uBBTaR2_O7-yCT8HnOC_fXqZz

sprite $NewbalanceMd [16x16/16z] fSk50O0m3031hrja_srn682hnk2_q7k7lclfpYH2cxu3ikql-ybXVs-n3DyR6dJ_D224LCOoN-npaFiKTFzsSLUeOoNyClbj0m

sprite $NewbalanceLg [20x20/16z] {
lSt50SDG30DGVRI2sd_QWkhI0dadit6LGh83mQSeMMmpK9HS6JEuOZkbRMQDwo6flaQaqtErFIQNTNlaql6yftz8jVN9LGtoghyrcHCYjSbDTW3-LX5AWMlS
0G
}

!procedure Newbalance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/N/Newbalance', $name, $tech)
!endprocedure
