@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-5/bootstrap')

' loads the Item which embeds the element Nintendo3Ds
include('simpleicons-5/N/Nintendo3Ds')

' renders the element
Nintendo3Ds('Nintendo3Ds', 'Nintendo3 Ds', 'an optional tech label')
@enduml