' definition of the Item simpleicons-5/N/Nucleo

sprite $NucleoXs [10x10/16z] uwS3

sprite $NucleoSm [12x12/16z] unza

sprite $NucleoMd [16x16/16z] un_X

sprite $NucleoLg [20x20/16z] unzKO1G

!procedure Nucleo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/N/Nucleo', $name, $tech)
!endprocedure
