' definition of the Item azure-17/Item/General/ServiceResourceLinked

sprite $ServiceResourceLinkedXs [10x10/16z] DSQ50G0W449HBBxxBsnUmjETeHZR2Ns2Mi4Ng7Um0Lu8EhL3qIDKwVBXSLvi

sprite $ServiceResourceLinkedSm [12x12/16z] FOS14W0n1CG0w_ylFknSqoAH8-LHnQ3-KPY52y3SPqzWa3jLMBZbZkyscGWBwaQQKIUwUvI0-W4

sprite $ServiceResourceLinkedMd [16x16/16z] NOq50iCm30EDKlx_uO5XQwlWNS0oIRa5m0EHDzIB0Atc4IGrNOtCGNgaW2GQQIPQ6u2TNUjQ4DveyXMWgbbX5ue0VR1kg9aNhfZBAyuvXHiklW4

sprite $ServiceResourceLinkedLg [20x20/16z] {
PSu7ZiKW301HLsRlV-4KUsE-nAWbJu0jKyhHMddIqqbpSYZBVuZwKPYJy5YwFyOQGXyBIVvFKec61FH9EdE9DdBnjR_g3I8puoCJAOCmQzNU3YVJgQEszui4
VAXEecOoj7TicjRVMzF4GNLow0O
}

!procedure ServiceResourceLinked($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/General/ServiceResourceLinked', $name, $tech, $desc)
!endprocedure

!procedure ServiceResourceLinkedCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceResourceLinkedLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceResourceLinkedGroup($id, $name='Service Resource Linked', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceResourceLinkedLg>', $name, $tech)
!endprocedure
