' definition of the Item azure-17/Item/General/ServiceResourceGroupList

sprite $ServiceResourceGroupListXs [10x10/16z] ROk50S1020CJdFq7hdl_S0aUn0eZnbskC1Cmi6fnhDZTDRkN8hOh6WSp

sprite $ServiceResourceGroupListSm [12x12/16z] NOi54aG1249H6S7x7tZtTxqf4c-wgpS-caoIHIvQegIMBgrL1r2sPGEvNWuTgvxn3B3TTntEme5nyGS

sprite $ServiceResourceGroupListMd [16x16/16z] ZOg54GH120G7X_mJ_brujxkkGaRmYRWxrkWQFw5PLR66PQqlkKO4rjYQQ6t-elTafiLQ066ZpCGBG4PdUdREewiygmfJuBZh21Lbt8Z42s_o0W

sprite $ServiceResourceGroupListLg [20x20/16z] {
fO-53GGn30JDq7_3xytJeUX6Yc72T4C0_eLuwWpG2Zf1V-jMPF-kIy0h1EB1vS-vcH-SpM2hWNC2d19Wf1-Vnh2kmCPrDzS4E3kudaO4IdFhsap4xFSF7LLq
14kFn5cz
}

!procedure ServiceResourceGroupList($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/General/ServiceResourceGroupList', $name, $tech, $desc)
!endprocedure

!procedure ServiceResourceGroupListCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceResourceGroupListLg>', 'General', $funcName, $content)
!endprocedure

!procedure ServiceResourceGroupListGroup($id, $name='Service Resource Group List', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceResourceGroupListLg>', $name, $tech)
!endprocedure
