' definition of the Item simpleicons-7/D/Delicious

sprite $DeliciousXs [10x10/16z] Om01VX0WXWK796a3

sprite $DeliciousSm [12x12/16z] Om03VZ0Wbuq0b9i6

sprite $DeliciousMd [16x16/16z] Ou02VYYWDnzTdDvy

sprite $DeliciousLg [20x20/16z] Ou03VZWOYc88CBHz1

!procedure Delicious($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/D/Delicious', $name, $tech)
!endprocedure
