' definition of the Item simpleicons-7/D/Dior

sprite $DiorXs [10x10/16z] Oo0Qi819PbuebvCDIF0mC700nTZnwmG

sprite $DiorSm [12x12/16z] Ow04C35myG0fNWu6VY2RduU3WO6FWniapiZ3mCZ00H8d4G

sprite $DiorMd [16x16/16z] jOS50S0m40FliTpwLplmi8N3trWKJAaqgYJiH_eclK9xrr4Ei6ewxszA1xmIIAXWXgdYIl8nRW

sprite $DiorLg [20x20/16z] pOlL0S0W34HVSMV_QP7xwmR4Sy93yPdlk_Fq7VgOuFoP6HWaI_-OmkVv8VW_rW6RKsWWh0c5ShrJMDDC42yM8m_51W

!procedure Dior($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/D/Dior', $name, $tech, $desc)
!endprocedure
