' definition of the Item simpleicons-7/D/Dsautomobiles

sprite $DsautomobilesXs [10x10/16z] 7SQr0S1000GWufxRVzetAgo0LMwmaz49QSuOMoxpDGR11_u0F01cW0SL

sprite $DsautomobilesSm [12x12/16z] HKr50W0W29lT-l_Nsi1Ei8I38CP_f7sFS2w_ptsF7D0itcrKrlxVcolXtUKcZpy4NDoAZsJvD4heAkSTNm

sprite $DsautomobilesMd [16x16/16z] LSw54S0m30D0bOsd_QSjX_53DeQo08YvqXupfIT8psUUVCDdhWGE2egL6H5hzOeLno7LxqFVY_rVw3V9HmYFaXE-WFoV_1OCbcdkkKilQ0oKFxiB

sprite $DsautomobilesLg [20x20/16z] {
NSW5ZWKW5CNGuixT_sf7oN-1nfe3aRi8x0gM6m1IDqgPVrFrXtg5OpelvyoA9WIrZfcQLAN0PSJemcN1DqW-DxDPF41koMoSBMh7LeK7L-RJtYe03YktjG9t
er1uIYxpLBpZgI_Urk1jHaxV
}

!procedure Dsautomobiles($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/D/Dsautomobiles', $name, $tech, $desc)
!endprocedure
