' definition of the Item aws-q3-2022/Architecture/Analytics/AwsGlueElasticViews

sprite $AwsGlueElasticViewsXs [10x10/16z] FSRB5KGX24H15JZsRVAFT-RzQrM0JdlprNT7oPu1zypCAHqxkbP8RGyFHgZxs57eetQTkslu0m

sprite $AwsGlueElasticViewsSm [12x12/16z] JSV70G915CDGc6ZvzzyltY7jEqc4ZhsvZR_pNBBfrooDj1cCr6cZDf1EcoOUKhcvjRasgAePkx6WQZG7KP6SFXs-m0i

sprite $AwsGlueElasticViewsMd [16x16/16z] {
NOi7bWKW30ADBK3kVzz5z_Un3Y_mW0UPoNzUWNu2wULz1o0f1sxGqQzlBfhT7iw1FZConxPVWftJbQTt-t3X-iACTBSnYPAWyEMHdMILVPpAfB5NxtcyFxrq
QA6dbnvS_mx-
}

sprite $AwsGlueElasticViewsLg [20x20/16z] {
NSW90iGW24DH3Q0atl--mtHllokFMtarA_AZ7pjHV6gO5qfFQnapKuLcSUXbwhJT_3OuF06tqRndsHQpq-iKNARWx1CaNqRKidROC4DsHWADnimbkTHClO4y
R6scoad39BdMEWrj5Ems0TzCSLgbBSIux49AbrrONVR17m
}

!procedure AwsGlueElasticViews($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Architecture/Analytics/AwsGlueElasticViews', $name, $tech, $desc)
!endprocedure

!procedure AwsGlueElasticViewsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsGlueElasticViewsLg>', 'Analytics', $funcName, $content)
!endprocedure

!procedure AwsGlueElasticViewsGroup($id, $name='Aws Glue Elastic Views', $tech='')
  IconGroupElement($id, 'AnalyticsFamily', '<$AwsGlueElasticViewsLg>', $name, $tech)
!endprocedure
