@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-11/bootstrap')

' loads the Item which embeds the element ServiceSpotVmssCard
include('azure-11/Item/Networking/ServiceSpotVmss')

' renders the element
ServiceSpotVmssCard('ServiceSpotVmssCard', 'Service Spot Vmss Card', 'an optional description')
@enduml