@startuml
sprite $MaterialsCloudLg [20x20/16z] {
fS_50SD030J05QmE5VTVRJWnFJsVGn6k4oDDiEKZUy_XM353HJII_pZ_xPdskM5VAhxgPnSPQt8c5V1qhAoFIRHwQ8hJRu63saR1GImnzFHFMZCvv8FMx6qr
9Z_ZnugAInu
}

sprite $MaterialsCloudMd [14x14/16z] XOd50S1020HnTdFzrnkNNsxG0PdXcVxisiX4worrZ3fxyhegRPTpFvyiNKmUj7fy9ZOwFtCgEcwIBXfP5sdonmO

!procedure MaterialsCloud($id, $name="Cloud", $tech="")
  PersoElement($id, 'materials/MaterialsCloud', $name, $tech)
!endprocedure
!procedure MaterialsCloudCard($id, $funcName="", $content="")
  PersoCard($id, '<$MaterialsCloudMd>', 'Cloud', $funcName, $content)
!endprocedure
@enduml
