@startuml
sprite $MaterialsRouterLg [20x20/16z] {
bOw50GCm20G3F55a_sdhxhqe_kL_I21qxwaLq8PRdmW3kqFtYH3LtuOy-x3eeuzEg9trKRSJdcRzu4LcH4RkzXuSVLDqx3RN6zyWwOJTll7vc3wMZNNniUKD
nkNWn0qxryzi0G
}

sprite $MaterialsRouterMd [14x14/16z] RSk30G0W4030h0_xJvjT5r_e2nEy_gnObHoGhJEl1JEq8Qg_jE2cpc487U1SSe8B9fWBZfH8YhnuYx1sdSPba7GvE2K

!procedure MaterialsRouter($id, $name="Router", $tech="")
  PersoElement($id, 'materials/MaterialsRouter', $name, $tech)
!endprocedure
!procedure MaterialsRouterCard($id, $funcName="", $content="")
  PersoCard($id, '<$MaterialsRouterMd>', 'Router', $funcName, $content)
!endprocedure
@enduml
