' definition of the Item aws-20210131/Architecture/DeveloperTools/AwsCloud9

sprite $AwsCloud9Xs [10x10/16z] FSQv0S1G34AnpZnmzfyt_rQbn0D3NiTWTKIKHZioKk76KHcvZIKqrXx0_dh8zBt-

sprite $AwsCloud9Sm [12x12/16z] JOen0W11306xWFl_Uo-sobG3jWgBJ_09rHaqr4TD6-BD63P4iD69YkkGi1u2CtYVueU-4xuJVW

sprite $AwsCloud9Md [16x16/16z] NOi53WH120HFTcXX_l_U3H2bejLYQ-3W5NW5Na4x8gW9Hia3Tf2sGXQV4nLa6h3gq44cKPD3AL0EsUQXnIXNIBKdfqy1Y08gRpn8TmLt1NS5Bm

sprite $AwsCloud9Lg [20x20/16z] {
POu55WCX30LhoHUu_tcBLJExsBoORRtWmOFgQgGNnPN8ev3WhrCayh6bZWlCq4ScbsjjXjaYCoCqcIxIHWIaHt2xXEqSMChOBdRd6JqYZzDqkGvkrnWOPCuj
i5qJ3cVmTl0RgRTYrNkDxBr4JbSYdm
}

!procedure AwsCloud9($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/DeveloperTools/AwsCloud9', $name, $tech)
!endprocedure

!procedure AwsCloud9Card($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsCloud9Md>', 'DeveloperTools', $funcName, $content)
!endprocedure

!procedure AwsCloud9Group($id, $name='Aws Cloud9', $tech='')
  IconGroupElement($id, 'DeveloperToolsFamily', '<$AwsCloud9Md>', $name, $tech)
!endprocedure
