@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('eip-1/bootstrap')

' loads the Item which embeds the element PipesAndFilters
include('eip-1/MessagingSystems/PipesAndFilters')

' renders the element
PipesAndFilters('PipesAndFilters', 'Pipes And Filters', 'an optional tech label', 'an optional description')
@enduml