' definition of the Item simpleicons-6/M/Medium

sprite $MediumXs [10x10/16z] Oy0F-840H38myqC13uG2Iy04k63g-B0Q0W

sprite $MediumSm [12x12/16z] ZSLH0a0m40FH0G3c_gS5u8UsRpS9ITGEEibmDw3jt7WeVRMgkJw3km8j9sYTCyXRVgq

sprite $MediumMd [16x16/16z] fOl50O0058MmM_QVrcul1h_ZyPjSDG9Q8QNMUL5fYxZ0dAhJ7BWHpYaxtszwucKaqG8XgCO6I7FUqmC

sprite $MediumLg [20x20/16z] jOYr0O100CG2xthxJujxJugJy0S3Nz6qK5TlfQKiemw0lOGkS6lQ87ExVQQgThkuPUtIJTgoIVbsVilInEseQyOiogaomrg35MYd0atgImAkBSQoaY8_C0C

!procedure Medium($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Medium', $name, $tech)
!endprocedure
