' definition of the Item simpleicons-6/M/Meetup

sprite $MeetupXs [10x10/16z] Oy0A-C40XSK8vJAmCl0pS89OOCp73oIXwhWHMZWXvh0mCF0oC

sprite $MeetupSm [12x12/16z] PSp50SDG081Gadmtzf-sxdrtuD_WPcVgoDmChoQ0fa9k1a21j2iHCukeGX7Yu1PingxW0l3k_Tm3Rn7E

sprite $MeetupMd [16x16/16z] TSc54SCm5C1GXStQVzlU3nxrcIt-4JxpmiPND3HkpKidJ6frT-WKFt4IaXNMRIWq5dg4RHyUq1aO0HJAj9BYlLrlPwbtRuwkzYKfOVQnGFXUjs5hheUyTcu_

sprite $MeetupLg [20x20/16z] {
TSi7RkGm40NHObmHd5RT_xHhcnWbXuVGyVENt00cFydJs6FaLZXKyS3fvI7Elni4G7r11PAM1AkHDxLJHw01JCfuHzf4_y7e19kh1pM1fFLc6XLKQ3jcFFv2
8GmRxTZXONOripGl6yk6Xy6fwzB6vD8h58YTky7f0m
}

!procedure Meetup($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Meetup', $name, $tech)
!endprocedure
