' definition of the Item simpleicons-6/M/Mercurial

sprite $MercurialXs [10x10/16z] LKk30S0m40nhxBzjtkQXfFWX3ZaWJhWkFki_hvkk1kYSe71JXm6-_IuVNB1Q-IjOT_ZEKHO

sprite $MercurialSm [12x12/16z] LSkr0G0n40F1DRFLVxNFECcXu2zeT_OwVVi8b77sqyt2F0FLbW8rx5FYbAJPm4XW9JT0weC2tKFAqTDSYG0zWLo25G

sprite $MercurialMd [16x16/16z] {
JSc50S0W0CJ0uCxlFsrTE3J0ox1eEkKrJzroqIkz_SeSIjFBCsL27M-7839bvFpysvGzK4ERHux4gxgZxUHW7OSezTo18LL0QcOaS3flc0mb0q73H4E6D0E7
b4e2SZ-FapNNQtR03W
}

sprite $MercurialLg [20x20/16z] {
VO-5WGKn20LV5CcnzD_jmUQxJNnYW1yiJwmzAB_2vQhCx_Bns1Nvu5P7mlee2OqhQDgZA-x7A4hhuPVfw8IY9g9RaTGkYc38O7Y2XJgnALoEK4QEHpnepNBQ
pUay6KgdvyLwJOaoNZrgJ2NK67cr06idpExK5j1gpcT9DvYZ0eL8R0wSg1FlTwLrF37-XCwB_m
}

!procedure Mercurial($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Mercurial', $name, $tech)
!endprocedure
