' definition of the Item simpleicons-6/M/Mercedes

sprite $MercedesXs [10x10/16z] 1S474S0m000Xhdlc_RiDmDq1UgIR4ClkGUY685GuA6NH0ixS2nZOOua9

sprite $MercedesSm [12x12/16z] FOg50SCm4CGKDcl_QGinF1u1a0tqCYDD0Fjkmk9x9VDgFGiarprLu0wGDUb9eVKODOaRlS83xXssrpNTnGU-

sprite $MercedesMd [16x16/16z] {
HOp5eKLH20FdkXsO_glz0a-oWIY5BNmctWZpzDQzsEG326G0j6m51yHJ0yLnff_HPtNBUjAjhd7sTVHzhQardiyDimt0IGwzQj89SOo9nfOZsPCF9e68Bwtn
uLhqQjhxgLNy1G
}

sprite $MercedesLg [20x20/16z] {
LSs54GCn0CH0FPlLVxSPGsZDU2onMMv-F6gnQjrPDC5cRqO6tO1JWDiqj-Y2TBiNF6vqsUDpPc9etWm6PFfy7utVlSfaAmotkZ5eNWdTJB7K6J0zO-yMKBt6
tGAxk5sQThghsBPMgRhpzUZ5xislAX3_xZNfae5bgnuCFGHWRyf7SAWNtGi
}

!procedure Mercedes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Mercedes', $name, $tech)
!endprocedure
