' definition of the Item simpleicons-6/M/Microdotblog

sprite $MicrodotblogXs [10x10/16z] DOc50G0W20JVRjr_MybJu0F4U1NC4wu8axnb7ReCAvRT2jWs6bo2IGFbuGC

sprite $MicrodotblogSm [12x12/16z] JOg70O0W4CHYxxh_j2e7NmBVG-5uDaJtL83-CK2bvY7rTpLrlwhP-PMp5ddYa5W1k6gxKEdWEVW

sprite $MicrodotblogMd [16x16/16z] JSy30W0X54NHEqPu-rzjridkKznEPgTJyvCTce1DA-WT5Lzhtpx_vydZWFsO5praFdVTc52nAzlO-9TxDycK5Skb5V1hEaemwt9HpjY_Z1Ul808

sprite $MicrodotblogLg [20x20/16z] {
JSu54e0m44FHZrlRtF-qQ6R8GwehVBgjgSw4JTP6Fhr2up58gNAJnSsYJq4s8fkGrTa13PRMlFd5OGezZpNktM9BawjcfCUPGxtd1xiUYsvxrQDpG5Y0JahL
JQM1pwmVls7TPfZSFMdK3XS
}

!procedure Microdotblog($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Microdotblog', $name, $tech)
!endprocedure
