' definition of the Item simpleicons-6/M/Microsoftaccess

sprite $MicrosoftaccessXs [10x10/16z] JOl50S0m4CFSJyFH_jE6ISTWlH1RChJawRYHvmbzenkBjJEOrMrSrsgJ8IIe

sprite $MicrosoftaccessSm [12x12/16z] LKo50GLH239VA_jF--Fwx03eROoCFWBupGlJLJtWS-QShFh_0xPzjxbnmaLg0A2KwywTpZdn2rCj0J8Birtdhq-xwRzqR6PV

sprite $MicrosoftaccessMd [16x16/16z] {
RSs5aKKn243HItHciVwxNVBTpjEW_3BonkKSDOMhcHIpapBFCbKrJ5LwRq1aEI_AxJpnnpaBgrTDkUqWUAqN17ivrpEvdQNEDtRTpnZ3znZt_HJhNDtEEtLG
P7boqIsFF-4V
}

sprite $MicrosoftaccessLg [20x20/16z] {
TSy50WCX30J0nJtx_zysqFRy1dU2Tx49br4Sba3sWCaa8J5rjc2mk2I_kJguAGnDYMXbd7CMYZlySJAGsnnWzhd8gI236ybK5e9wEGjbptC9gvpcOffLvp-E
mRj2U3MQzswFunSlVlQv9WwRI2n2rLiRL14_BfRQMit101y
}

!procedure Microsoftaccess($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Microsoftaccess', $name, $tech)
!endprocedure
