' definition of the Item simpleicons-6/M/Monoprix

sprite $MonoprixXs [10x10/16z] Om023duM1X1Wv0S148iV0WYo6E0i28S12b0P

sprite $MonoprixSm [12x12/16z] VSh75G0X30DHiJch_se1UzvU-HS7IU7oBdpkk6vZxhj_WtqpRdK7Ur4gAnNaYZqRuDi

sprite $MonoprixMd [16x16/16z] POp50K0X34F3ToNxJujh-svH9DQV3nexCqMUh9YasOdogg8KxA3NeDz1Bq6lOr__ZSQ7p67hlFEJFmRAUj1cb38zaF4

sprite $MonoprixLg [20x20/16z] ZSw53K0X54FHuaxtd_QxApT63lQmv2kpnY5PE1Ss4jogToBBR9d7vaTvAZrORRJyy4UupqA3ANKqh3qPf4zfeqDce7YnS3-61ogak91ZnfMAtDOz

!procedure Monoprix($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Monoprix', $name, $tech)
!endprocedure
