' definition of the Item simpleicons-6/M/Mxlinux

sprite $MxlinuxXs [10x10/16z] JSc50O0m4C30u4xsdnQfN_jEOMjDeP0x6J2wECrNKWFIwPnucxq

sprite $MxlinuxSm [12x12/16z] TOo30S105CLIks__QSipyaq2JbMPU5o__WLe6MI0ngQhQ4rwWfZj1XnWqvScVXxaDm

sprite $MxlinuxMd [16x16/16z] ZSpL0O0W543HQokv_xHqVtbeNh1ux0_2HiQKvyCT3uGjjdZTXbPWziCEWEafO8xAuMC7n0rlVbv4UWSLdn-T2MyriYlUcGS

sprite $MxlinuxLg [20x20/16z] bSm30WGn44JHFunJzp_j6j5YNemkw2sXutM8JOyrwic0hZn55lTBh0gmABEfb641rI9CgYrfXQZI3cprfGDG5PYu4KKcTqjnEV5ms-ot_8Q6ideidVaC

!procedure Mxlinux($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/M/Mxlinux', $name, $tech)
!endprocedure
