@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element ArrowDownAZ
include('fontawesome/Solid/ArrowDownAZ')

' renders the element
ArrowDownAZ('ArrowDownAz', 'Arrow Down Az', 'an optional tech label', 'an optional description')
@enduml