' definition of the Item fontawesome/Solid/Backward

sprite $BackwardXs [11x10/16z] LSQt0S0m0CCmnbCw_xysHPgC2SpSO37pO6ZcySsikZO_q_oWvIyj3a1U

sprite $BackwardSm [13x12/16z] PSU53S0044BHN_Uo_xODWMXFUVnAFk-Rh1qUALcxio7ZzKrkDHVH6qJxKc0m5nWi1RVFlF81

sprite $BackwardMd [17x16/16z] RSW50W9134FHZE7mxtzQ92th6MdpT9nszwYFVuVwwz3T1z2aWY4wpTtGCLGI6iwPXC8S0rlG3bBw325DCoX0CoX00IabHjKk7m

sprite $BackwardLg [22x20/16z] {
VSc54O1000F1uCxrNoqU_3zZDnj5bwIkxC82cls5tbW2tHefC1vOSMZAeKQw7QqrkwveDT8LNDfmcxNaJ_bL_Uh5_KFDdSQxogg7oghnhhBgeR9gEDISxZ5I
AR0P
}

!procedure Backward($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Backward', $name, $tech, $desc)
!endprocedure
