' definition of the Item fontawesome/Solid/BusAlt

sprite $BusAltXs [8x10/16z] Os3b1m469X09OO80FpyNAeq1U41Y3FpCC5rWZVnS

sprite $BusAltSm [10x12/16z] Os3W1mC-80C1U7b0W0_8Oe00h2pi02pE1I9v86O1HU1od63DhFmC

sprite $BusAltMd [14x16/16z] XStL0S0m203HQ_Yft_xJrbrVN00eN0Luq1QUjMaHuocngdzEmQhnMnjEcccDALhJ73STvXMFG6EjndZAfbEbz

sprite $BusAltLg [17x20/16z] dS-r0KKX50FGFDop_xHVSJfEWru3P64N0KGkfE0cyuH1__u0m-L5mV3m4j17UsfI_lcwouLL8Ycv-SsJ_sgNOrvF6W257CDBl04

!procedure BusAlt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/BusAlt', $name, $tech, $desc)
!endprocedure
