' definition of the Item fontawesome/Solid/CloudBolt

sprite $CloudBoltXs [10x10/16z] LSR50K81042XPxViFwtvanFLuzGVCEzIHa_OXnrATDHML5tOD62LDm

sprite $CloudBoltSm [12x12/16z] JOd50O1G08MmM_QVrlZDvGL0Rq_YL6_ZDj7sFTMMg8TO_Jk7qdkX0n-Jab7hkbeHwmi

sprite $CloudBoltMd [16x16/16z] LSp50G0W30F0u4xtdnRNUrM3XkU8Hw968ZeCZ8xHXzkpUNv40T0dkVEhl_aE5gFr08dnEk9qtusz1C0P1FM-5PDghS55GyPrsjEdjpNaCLK

sprite $CloudBoltLg [20x20/16z] {
ROy54e0m4CHIn_V_lsLkEBo1MherZBYgyMQL0J45d4a7DZMxqvFGSID6VBdLvAml8Ubckrid0n-N852EhYiiv44MLr6QQBv9bJPJ7bivoJBtOZGrXy03EJDy
zSABvk__n1e_LpZP0G
}

!procedure CloudBolt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/CloudBolt', $name, $tech, $desc)
!endprocedure
