' definition of the Item fontawesome/Solid/Computer

sprite $ComputerXs [11x10/16z] Oq02_600flYW8WnyK2QgA1TMKNwu2Kpy23E1JBYv

sprite $ComputerSm [13x12/16z] TSg50O0m4C30u4xsdnPtsgkyykAEOGlz1eTUPISy2drDniZ4rj8TjaYIRZYMYjLPZ2koSUnd

sprite $ComputerMd [17x16/16z] XS-30K0X543HcrtxJ_jjdkmUDxOk0cwelMqhM3fQpc3ecc62JHE8yyJWF65GvmdWvyYiv1cqGcoSFaPj81TmkM6VECV2LGy

sprite $ComputerLg [22x20/16z] XP030i0m34N_ZEh-fwtDjrLnWW57OlSlG6J45-r83HmPHWFUbR9Mse_06U_7_LlflkzY4NUL3QyGfExjCbixXvsQoxP7Obpa55BAFRaqXJvmk_6YYm8

!procedure Computer($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Computer', $name, $tech, $desc)
!endprocedure
