' definition of the Item fontawesome/Solid/Dragon

sprite $DragonXs [12x10/16z] BSg54S0m30GmbxdQVzh2NnGmLk2efeC_ET9dJQpYfa1F1GQqb3txZKnYF3ECU04

sprite $DragonSm [15x12/16z] NSU53S0m00D1bxc__xQH5Su9Jz4F_AgmRdiyNDACFHxW2YOHkT7i2bYyYLXJDJvtsT-VwASJ

sprite $DragonMd [20x16/16z] NOw50S0W40DJnSd-q-9-LUuL7S6CmGOhcrFPs26lhkZItQjk07PMtypOubvHtCj6SSX89dn-tNPExTMFBkzrMpgi2zuLbCIUsZ4pSxAxw_cqTSqvpvDYTX01

sprite $DragonLg [25x20/16z] {
TP255GGX44EpkAV_Qi-mUyXV9UE3YM35OOKThEHXEUdk8MENeWBmSA97rJogp6Is_ffcyDrGVsfGbKBE3n0vADLGIIHpy7-6T9Yv5PTTj-m6KxzfNKKOlmOB
pvnmvRf8SJG8upaCGaWVKk52u1aRBphU
}

!procedure Dragon($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Dragon', $name, $tech, $desc)
!endprocedure
