' definition of the Item fontawesome/Solid/Ethernet

sprite $EthernetXs [10x10/16z] Oy0E-440me0mkVZn0qP-1Z14i1260G

sprite $EthernetSm [12x12/16z] Oy0DkFb1W174vE83itdOWMn-66002H863FpiZ402Y93Px4XiP4i1

sprite $EthernetMd [16x16/16z] bOq30aGX502pQ-v_siMtCVKiyG1PEl8OPtfKNyrjY4lwnuMPNrXPK0kloHuq5FSp_LKG3VatTHUtJInk-08

sprite $EthernetLg [20x20/16z] lSZ50KCn3C1GVGn7-qzRnbEvpsm-5JtZedesSXHBzwoMuzSx3M3mJX_8_WMJ3cWcAuDw7A29zDflQ0sE5OY7fV2aBG

!procedure Ethernet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Ethernet', $name, $tech, $desc)
!endprocedure
