' definition of the Item fontawesome/Solid/FileInvoice

sprite $FileInvoiceXs [7x10/16z] 3S650S0m40IWgqk4_RVDGp2I2S8cy4dm0q1FeQNWBXgm

sprite $FileInvoiceSm [9x12/16z] O-3X1m861X0DOO4nY8JoeIGtAoi_Di001bWOSC06Om

sprite $FileInvoiceMd [12x16/16z] XSV50O000810x9RzfxKxxmMaZce6Oqw6rYeCjTMnKsXb76VZ3weW67kQ3FpJ1fF8GSYildJ4h75GJwRSuQu7

sprite $FileInvoiceLg [15x20/16z] ZOs50SKW50FJufhzfyNvBZtqu0dEp853v-GcTSsyqtJkXYhq_wxYE4Y5vcpQwGhV_jijkdRH0CAkeCdSc1ryu6MYMqp5vdXMlEbxSD0BlX6U5VdHN0K

!procedure FileInvoice($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/FileInvoice', $name, $tech, $desc)
!endprocedure
