' definition of the Item fontawesome/Solid/FileAudio

sprite $FileAudioXs [7x10/16z] 1S4t0G0n002X-pAbuTzj8Emw80We03W_yiPCFv09N

sprite $FileAudioSm [9x12/16z] NOg30S1054DJks__QS_-ZFG2IE4755-Ook7PDeOArY_UUuv9tp2BwG_U6p8xgIm

sprite $FileAudioMd [12x16/16z] XOlN0O0W5CJEtit-stgF-caKI2XQ2MwPq8Izs0lDvMWUqTpnmz4UFZ2cc6GNwUrO_B4VevVn5O45D56v1znqFW

sprite $FileAudioLg [15x20/16z] {
TSg55SD040FHCSE1-kyskmhJ6F_JCNQvWspKlPRiUXRKhUNq_Y0bzoV9_SuLlD_haVxNtWGF3wijjuyiEcfZCo6u88PVd8RWVlGyx8BIW5uQEU9T7kwAyFlU
SG4
}

!procedure FileAudio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/FileAudio', $name, $tech, $desc)
!endprocedure
