' definition of the Item fontawesome/Solid/FolderOpen

sprite $FolderOpenXs [11x10/16z] Oq02_200PS80YCa90GmCV0nSK82Y0i5aHZ1vO2n691i

sprite $FolderOpenSm [13x12/16z] Oq01pFn0m0FbyCC14pA77yZXGDB3ny07a-5ZO691KOUBmuJ3R5JN

sprite $FolderOpenMd [17x16/16z] XSp50S1044BH7tVelzgusxxJA3mL6dMdtekCbNps62GWDz41KCwLo7r6ZI_WCSXyre4lOW8H7M43

sprite $FolderOpenLg [22x20/16z] bSp50GD134FHRrWSKF_LXfdpRWQ9TpmEkAEpstteeYvx3f1wb2-t_RGjowtvi9rvbXsczHwaq_I813t1I3q1gXwjW9uOX9u0NO_Aore3AEtUo5-s

!procedure FolderOpen($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/FolderOpen', $name, $tech, $desc)
!endprocedure
