' definition of the Item fontawesome/Solid/GrinTears

sprite $GrinTearsXs [12x10/16z] 9SY74O003CD0qplQVrlG-TCJxIof6urzbhkTZammFS_WoWXw7Xx22vni92CHjW67JUYV7m

sprite $GrinTearsSm [15x12/16z] HSc54GCn50DH6O-z_NURaKBFkFCLOpr5NnTH5GyVtLM91JZXbgvQ1AVxQAmY6YL3yI5Cwv-wTPqAIhlyK5mdo0Om3rnHiDGB

sprite $GrinTearsMd [20x16/16z] {
PT250KCX303H--wv_QUj0Qazt8LgkZmwFeN5GZB5VvUUfUjKmvODRHgmsi5QweoXU11uaZjsTbgpklB2gjGZTCSKgBFs_KathTioWXnQNf4lTAOh5MjdbpKk
TONkL4Uoinb9_TSFt04
}

sprite $GrinTearsLg [25x20/16z] {
PT25SSGm503HDLku_NURCV_9FJ43hwNQqy0_G_Ms4wq6F_s_8wD17F7GFFIkck0mgntO5HY-9Ks5FE32lf3KYOioswcW36PUfgwxjMZg3GvgmcX5JLLTCCge
DXMSoZj_bwv7bbdbimb7vq4hhz1eyLDLXzZm-yxCowWGT5yxH6FLG-Bs1m
}

!procedure GrinTears($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/GrinTears', $name, $tech, $desc)
!endprocedure
