' definition of the Item fontawesome/Solid/LocationArrow

sprite $LocationArrowXs [10x10/16z] Oy00_FmG2WZO6HXOG3HGY0j2WoJve0ouChX6NZWBnJ

sprite $LocationArrowSm [12x12/16z] ROor0G0X00FV5RZzfyKTKiMN6LRko0ImEtBYOPaYG7cMxQ_YIQON1PJlmXTO2_Us0G

sprite $LocationArrowMd [16x16/16z] VSx50G0X34JHa7MT_gl5tVxjeQ5P_EPw0KJi6j7YW-iokX3J-f5LaVN-McpRLd_eIODO2ufPK-hJt3EBk1qlV9MPJ0e

sprite $LocationArrowLg [20x20/16z] PSx50SH03C10XJdglzh3BC_FR5gjlgDogUGMVx8P7mkFpOYVqSm9TBk57dOhm65f1-XkSppwGnyNxNS3cTCV2izecwEqjpawTQAYKZlYXJS

!procedure LocationArrow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/LocationArrow', $name, $tech, $desc)
!endprocedure
