@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element Navicon
include('fontawesome/Solid/Navicon')

' renders the element
Navicon('Navicon', 'Navicon', 'an optional tech label', 'an optional description')
@enduml