' definition of the Item fontawesome/Solid/RightFromBracket

sprite $RightFromBracketXs [10x10/16z] Oq00Vdv-28C7GlE3XA0oO1O_532mGMYu63jC7Ji3EpyR6v35ZcmU

sprite $RightFromBracketSm [12x12/16z] JOo30S0m401hDxV_jE7htfmY3o3folyTDLxLjCaVSbBF4vtKSepsgdFu_k6tUtFjW_AdKx82

sprite $RightFromBracketMd [16x16/16z] PSw50O0W00H0fVltdvPkNecZloSg1BSH9OiQWP2_hlDjclGP3tyPOTXvdra6gYrMYjrbDI7wUOGGNxYVNvXDftckAU2SBVxPMBQ__qu2

sprite $RightFromBracketLg [20x20/16z] XT250SGm30H1XStNVxLca1utF67Jv_RZEAJSA3bXg2agROqSmC-tZJJ_RZbcMwcOdmPMjukRRtQ3rsm7wsf6Uj7p_YqNlTb3RtQLpGEu-xwxFNqhnugXfZyb

!procedure RightFromBracket($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/RightFromBracket', $name, $tech, $desc)
!endprocedure
