' definition of the Item fontawesome/Solid/ShieldAlt

sprite $ShieldAltXs [10x10/16z] Om01FWOmOEG70I03Ge48g0035XOlFmCVX0N2K1qCO2Q40HDb

sprite $ShieldAltSm [12x12/16z] ROq30WGn4C1ojsR-_zfYhRHZiJ2pKPdv0NrsADGICqkVfz_vdNUWtln_Lfk_g6Bnv-mk5z3_ucyLY

sprite $ShieldAltMd [16x16/16z] TSw50SGW44JHZU0o_LUBh9pVZxu8GDBPwQM8tQrg6nwhj5J1xL_u6wXt6NWpVVZyS4AaycA-_7Vb1PpcKxzguWEuY6FVG2QjGrTlXSM3TXC

sprite $ShieldAltLg [20x20/16z] {
RT1L0e0W50NHiVlT_Q_MfXcbpX_W6esiLKy3laQ-dRT9N_JsB4S3cvm1UcfHR31BQsxKRS4AwrXJQwM6DhL30bAJ3i1Yc_urDibusf9xDBnvMwKD8dmNmzKz
DZfokTTBcYLh-Re
}

!procedure ShieldAlt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/ShieldAlt', $name, $tech, $desc)
!endprocedure
