@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element Signal5
include('fontawesome/Solid/Signal5')

' renders the element
Signal5('Signal5', 'Signal5', 'an optional tech label', 'an optional description')
@enduml