' definition of the Item fontawesome/Solid/SlidersH

sprite $SlidersHXs [10x10/16z] Oq06_FmS88gR7mR0OYWAk1duuB8mCKOmoG_XmG523

sprite $SlidersHSm [12x12/16z] LSp50S1030D1MM7S_giDvs0-PgksG3p9HYORc7pJfRrMkZk91-3OoVJwivNq_TvQ7aEz3uqU9m

sprite $SlidersHMd [16x16/16z] TSw53GGW44JHOICuqt-r9xY-6Fgpk12IQ488_0kPZrn1HFXZ9LFb3yqpcYh-fPYuWgfoL668D4kfyZw7V7NC1-GI9cdQVW4

sprite $SlidersHLg [20x20/16z] {
TS_L0O0m30JGAvv6RlzfSOU-ptXGvAJWYOi11-6NyWkfgYekfDfT0ms_ElSMJprd2g3XHmI_CCXXIuiqxtSITjMUgwhdkxXHDIvS3y8VoJsu23_ePzwXrG4t
4m
}

!procedure SlidersH($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/SlidersH', $name, $tech, $desc)
!endprocedure
