@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element SortNumericDownAlt
include('fontawesome/Solid/SortNumericDownAlt')

' renders the element
SortNumericDownAlt('SortNumericDownAlt', 'Sort Numeric Down Alt', 'an optional tech label', 'an optional description')
@enduml