' definition of the Item fontawesome/Solid/Tablet

sprite $TabletXs [8x10/16z] O-070ru-Vh810mCxFpytb0C

sprite $TabletSm [10x12/16z] O-3XXm1s88E6W8610KYomVa

sprite $TabletMd [14x16/16z] Os3ZHm0WPmW19WO61bu4bvSNmc50KGG

sprite $TabletLg [17x20/16z] Os3cuqS2F0nC_6W0A3_Y03i3420BS3C20PI9hfW1BOIu

!procedure Tablet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Tablet', $name, $tech, $desc)
!endprocedure
