' definition of the Item fontawesome/Solid/Trowel

sprite $TrowelXs [11x10/16z] Ou01Vdu4Yn_1ueKp-S0K4F71v80iE1EX0oOF1Z0c1qGQ

sprite $TrowelSm [13x12/16z] LOk30S0m44LhDs__QUES-J59193xGvyB_yWzZvixTsZW0fT8WhK2iCcZr0l08yGz70a

sprite $TrowelMd [17x16/16z] NOy50i0W3CJclkN_hvq3ryCJhAsqR83oJ1GZ9bvkJBJ21z3_Zp_3NgxtyBES_LbU5wvTh9ZvcSF543BOonFxGr8k

sprite $TrowelLg [22x20/16z] RS-54K0X30DGt6N_QR_Wv9hp1pM6AVKBOgw4bafewXXkxPWPeOaQLG3ZLvp2KJX-bklFpw6FWHdGaJV5CNueNabn9sYXEy5LTISIwlb6qSbj6LeKWxm

!procedure Trowel($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Trowel', $name, $tech, $desc)
!endprocedure
