' definition of the Item fontawesome/Solid/Truck

sprite $TruckXs [11x10/16z] Oq02_100PY6OSC244EL7Os82PduUi1G3M0qlYE3cPm

sprite $TruckSm [13x12/16z] Oq01_500PiC12eUR5SH1S96KiIE90xNW1Soy89A32wWIffW1nc9cO03ASZ4

sprite $TruckMd [17x16/16z] ZS-30S1044JH7tkc_sfZ-vrzoqMgHJgDlOa0l5ET9rILu9F3H4tZWmfqdiXz8Fcdi9ZQE9_VdN_JC0qg4vkn3TTmchaLT

sprite $TruckLg [22x20/16z] {
hSwr0GCm0CH0cK86xJzjc9ckUrNF0-bCPCyBZQtc9RPygxPQ0-YjU5D7LvDU0hm5nBiLRvIKYl-IatirLlU76-JBkvHkXvcZzxwl5M3eRbEqQePzDh6nK1V0
2W
}

!procedure Truck($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/Truck', $name, $tech, $desc)
!endprocedure
