' definition of the Item fontawesome/Solid/WaveSquare

sprite $WaveSquareXs [10x10/16z] Oy0A-840oW8YL1OVFuG5eZ0L8BGZ

sprite $WaveSquareSm [12x12/16z] Oy09-440ncPbOeMpcHWOeMn669kHaO-Vdn7Cve5eWh8PiB2vkVduqUn

sprite $WaveSquareMd [16x16/16z] XOor0G0n4CCKQWA-_QTzPbHdv9ywKdPf4sxLpPBtEceFxrgsQwbfkfhqz8npiEd8oAvvrxKKxRhP1B_q

sprite $WaveSquareLg [20x20/16z] fSYr0G113CJ0FMQx_sgVcK6P1l_Y8NrWOML6Ihar2U23QUQbgUQ8MXEJvNRXGr1OMj1eMne17unIIhInlh8mK_eK7bS3

!procedure WaveSquare($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Solid/WaveSquare', $name, $tech, $desc)
!endprocedure
