' definition of the Item aws-q2-2024/Resource/IoT/AwsIoTSiteWiseAsset

sprite $AwsIoTSiteWiseAssetXs [10x10/16z] JOY50S1020CFpVuJLzyWpdbklHBkCubl5k04f5eOG7whtg1Flz60WXR8pFm6

sprite $AwsIoTSiteWiseAssetSm [12x12/16z] NOg50G01209jzj_uLRvjuUGNWDvtbU2viysJwPsYqMTty-IySWmRP66CdOCfTg66DGiYYSwk4SVim04

sprite $AwsIoTSiteWiseAssetMd [16x16/16z] RSV5OGH040CmUM7SVyLXpkadZwpUNxyww_TfVlvkwTTJXZD05RCuU0_sdC2-RN5TSDYbtgkeYOEPkFUeCxoVwdO2YPMcIIQOWGAbXRwxpm

sprite $AwsIoTSiteWiseAssetLg [20x20/16z] {
TSk5WKKn24JHGnvX-gzuvRlUA2E-C_CchQhCkrQcttAih6TjxKsddhihcBZGoS8qBcA5m0f7WJau0Zqxe8za4jGspbeVJ13sHHjqE6zKhGMxCbqRgaEICew-
n2QqAgDrEtFH6lRvdfYPbRbGp0f8dLb5LO6wuXS
}

!procedure AwsIoTSiteWiseAsset($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/IoT/AwsIoTSiteWiseAsset', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTSiteWiseAssetCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTSiteWiseAssetLg>', 'IoT', $funcName, $content)
!endprocedure

!procedure AwsIoTSiteWiseAssetGroup($id, $name='Aws Io T Site Wise Asset', $tech='')
  IconGroupElement($id, 'IoTFamily', '<$AwsIoTSiteWiseAssetLg>', $name, $tech)
!endprocedure
