' definition of the Item material-4/Device/AccessTime

sprite $AccessTimeXs [10x10/16z] uwS3

sprite $AccessTimeSm [12x12/16z] unza

sprite $AccessTimeMd [16x16/16z] un_X

sprite $AccessTimeLg [20x20/16z] unzKO1G

!procedure AccessTime($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Device/AccessTime', $name, $tech)
!endprocedure
