' definition of the Item material-4/Device/AdUnits

sprite $AdUnitsXs [10x10/16z] Oq027FmW069niW413vZ501JY1B689k2ci41P

sprite $AdUnitsSm [12x12/16z] Oq05_120oURauU5XWhAPc9cP6S1iYaXCkxWP6

sprite $AdUnitsMd [16x16/16z] Oy02-A606y9bveS169y737ZXV2Omdna7d_uq5E3WCt3oGW0Ba0q

sprite $AdUnitsLg [20x20/16z] Oy05kFbWW0qcnC6F030nJgnYR530WoJ6m0C679p8OX2DN0Yn8SaYCbnOaCNWWkmmm0ZY0W

!procedure AdUnits($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Device/AdUnits', $name, $tech)
!endprocedure
