' definition of the Item material-4/Device/BluetoothSearching

sprite $BluetoothSearchingXs [10x10/16z] Oq01_0WMFqo4dmc88KByG08goitAYn23gEFYOs27oFB2JE46am

sprite $BluetoothSearchingSm [12x12/16z] NSV50O1G081Gx9RzfxNzzKv0gITo-AF2VoehUsd7TvGPkGtI-7Qlr-2JM5tJ03jepS-AuCiJ

sprite $BluetoothSearchingMd [16x16/16z] RKk50S0m36AkZF-_NTsf91Y6c1hEh-7Amgx9-69XJkIa1yiR1UFRWbB2qEM6vY18vZsHJp803cZobEHdzbc1WjnqseJ1J80oj01h2XewnWy

sprite $BluetoothSearchingLg [20x20/16z] {
bT253GD030J1VGgyuVglDioSjN1aqV5VLPLdkyToi7lCB3kRTpYKErjMgL1qGJKjNHEQ-WNtJGfeSi4zaPqCpha4fa7ix4BAmgoaNMX_OfUMPvfLoo4LkigP
sDbK0gUtETbPofyt29xCUQmOdzi2
}

!procedure BluetoothSearching($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/Device/BluetoothSearching', $name, $tech)
!endprocedure
