@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material-4/bootstrap')

' loads the Item which embeds the element BrightnessHigh
include('material-4/Device/BrightnessHigh')

' renders the element
BrightnessHigh('BrightnessHigh', 'Brightness High', 'an optional tech label', 'an optional description')
@enduml