' definition of the Item material-4/Device/GpsOff

sprite $GpsOffXs [10x10/16z] Oq05_32AZvqVp0QJpBn0WWyioGz4x10AYC4Y4989hfkFdv-VWn_9F

sprite $GpsOffSm [12x12/16z] POs30G0n54FFgDx-qzRkDvDj4Mh-WJ_MUnnA4w9vOgFlT4jUG_ub3tquGXOYDNjyLfkVPee7E3Svy3e

sprite $GpsOffMd [16x16/16z] {
ROs54GGn30CtTEoe_sgVDCxGRz0ayPyg5XtQfRrag8xYcNemkxf7fcE54-XoFrqDO0YeTv09jOBqa0afu9XaGWKeAcbhW_0pr35J7JYq4fU-R4C5JBSKIGdC
6m
}

sprite $GpsOffLg [20x20/16z] {
VT25eGCX54JHmVtT_glziXRFh79mz2t5t8jLxcrLgGDOlgnHbQoL0RUsYtgCYHtauCJ0qfQ1RoTs_FR5f1FzzYsLgXjYDSYWw8P0aNDqtP2vBSVGXPvoh2hV
C1wh1d_38yveJb9St536djguOMZ6B4vgxkFv7IsBplm2
}

!procedure GpsOff($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Device/GpsOff', $name, $tech, $desc)
!endprocedure
