' definition of the Item aws-q2-2022/Resource/Storage/AmazonSimpleStorageServiceBucket

sprite $AmazonSimpleStorageServiceBucketXs [10x10/16z] PKg30S1038on_y356-49bih_g0F48cccTpEBLYYc-GpTYFzW4DedlG

sprite $AmazonSimpleStorageServiceBucketSm [12x12/16z] LOp50G0m30AXIlOVkAxtIZ1yH0NIAxVJZjPky_sY10YBTdILTiFzeeX3QBV39Pth3Fbfc1hjg

sprite $AmazonSimpleStorageServiceBucketMd [16x16/16z] RKs50O00398b_7-mtRfE67wanLbKMoSSSzCSUB-SJwBewmMSvTiOY5XcwzoM46lqzMVjsNDS_0GiWLhuJdH8k17kztdriU6VWZFU2-qNVY9xa-rhEG4

sprite $AmazonSimpleStorageServiceBucketLg [20x20/16z] {
TKv50e0029FU_lzW6rjEm7Bu6ua2YGhf3scz1clbu2x1-pTm_Q5CsXV57PXtpbC-dzX_rydBZzoZBpzpBgUjlKgE7gGabeOTsgNP3iUmazu_F7wlWlNcYUr-
7NprBi9Ln9AqgqPr_kx71
}

!procedure AmazonSimpleStorageServiceBucket($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/Storage/AmazonSimpleStorageServiceBucket', $name, $tech, $desc)
!endprocedure

!procedure AmazonSimpleStorageServiceBucketCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceBucketLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceBucketGroup($id, $name='Amazon Simple Storage Service Bucket', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceBucketLg>', $name, $tech)
!endprocedure
