' definition of the Item aws-q2-2022/Resource/Storage/AwsBackupVirtualMachineMonitor

sprite $AwsBackupVirtualMachineMonitorXs [10x10/16z] FSgr0GCn00J14UlwBzX-3XS0WAL0COI0f0bq10aedskC-vieaLO3LYdu0m

sprite $AwsBackupVirtualMachineMonitorSm [12x12/16z] NKm50e102AEP__-mEsmlMSf_cU8O41mApZ5uK_aqRt6lOvnFRtDkF_FpddnCfiVFl5yzM0DIP0kEiu2PTW

sprite $AwsBackupVirtualMachineMonitorMd [16x16/16z] NSst0SCm34JHHn8I3lilxCRvbnU1VpePBwg5SGAkeocd11fcmJuuYrHd4nWxS5f3SW2JXJK0s-3w-3VSd_xhxxK_aC__sT0rjzgJKy0IXkt5cMdW0G

sprite $AwsBackupVirtualMachineMonitorLg [20x20/16z] {
VS-5OG0n243H5mNs7xXsLlzH7Fn3lU4RGMyq1wsovwBbh1YdYiKk9ZMWWDsMHondZN6h92jX1GaqDHrKro0-DnQLK3xf-b5fvYVTZWtMvtoZWpeg7dSvVf_x
s_ki_tEERAscAAEwSf1f17tAz8beRJLyfh_Xv1K
}

!procedure AwsBackupVirtualMachineMonitor($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/Storage/AwsBackupVirtualMachineMonitor', $name, $tech)
!endprocedure

!procedure AwsBackupVirtualMachineMonitorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsBackupVirtualMachineMonitorLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AwsBackupVirtualMachineMonitorGroup($id, $name='Aws Backup Virtual Machine Monitor', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AwsBackupVirtualMachineMonitorLg>', $name, $tech)
!endprocedure
