' definition of the Item simpleicons-14/C/Cbc

sprite $CbcXs [10x10/16z] Om01VWOOO6A02l3pytF1X574MFcPOIoW69p5nS35nSNEXQQNZOqDI08

sprite $CbcSm [12x12/16z] FSh50GD15CKm_w7mS__LXXPq5W1TJdrq_cwYOW4QTIeKuUxW1NteNKNZz6zf63fKJ8092pg0ljIkG8a6-QlyBny

sprite $CbcMd [16x16/16z] {
JSs50SH02031ZUTq--_s-VYS2y0fEV7HG-PMe9aOjlEe6DgWnwlE6ivpc65QY8dGKRgw3tPgwasdvxzsTRdFgrDFoljEfickChWomZ0CCSwPi7tpXRlUEfXu
h7nLTOJm0m
}

sprite $CbcLg [20x20/16z] {
RS-5SSKm50NHDUhx2hR_RZEomyaPb1xpeLhuQNFYjvNlkg0QOlduak5qHbSc5MyzslZV1aFeQY5Ux20gtMcDbcDKV_NpKBUll_7ybUzvYVP394fn8heSBu2p
mzeDf2xSaf17IQvVTzHec8foEIrH7ck3b_Q5AtmvpecVXbful04
}

!procedure Cbc($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/C/Cbc', $name, $tech, $desc)
!endprocedure
