' definition of the Item aws-q1-2024/Architecture/BusinessApplications/AmazonWorkDocs

sprite $AmazonWorkDocsXs [10x10/16z] uyG56E0i9dOuYnFCP8G0Y1WR9oShXCK1OR620JEIKG

sprite $AmazonWorkDocsSm [12x12/16z] uyG961WP6HcWR2OGPaHYSp8YiI4S1ZOETaOWO4M8S-9Ziq81Eugj

sprite $AmazonWorkDocsMd [16x16/16z] XSc30K0X543HP-m_y3VZZQToNknzhBu5httVYEFlvFXxV_Wv-JIQeECU_F-JNdjXAKolaUuWfwq

sprite $AmazonWorkDocsLg [20x20/16z] fSg54S0m30D0C-m_S9cvYOB-KzR5U8XkZSS7v6naShPqELkQd6rjhhOs6GqL1SV4QDkwximkZ2uiNdkw2O-MiKr-Jmi

!procedure AmazonWorkDocs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Architecture/BusinessApplications/AmazonWorkDocs', $name, $tech, $desc)
!endprocedure

!procedure AmazonWorkDocsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonWorkDocsLg>', 'BusinessApplications', $funcName, $content)
!endprocedure

!procedure AmazonWorkDocsGroup($id, $name='Amazon Work Docs', $tech='')
  IconGroupElement($id, 'BusinessApplicationsFamily', '<$AmazonWorkDocsLg>', $name, $tech)
!endprocedure
