' definition of the Item simpleicons-5/J/Jasmine

sprite $JasmineXs [10x10/16z] uwS3

sprite $JasmineSm [12x12/16z] unza

sprite $JasmineMd [16x16/16z] un_X

sprite $JasmineLg [20x20/16z] unzKO1G

!procedure Jasmine($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/J/Jasmine', $name, $tech)
!endprocedure
