' definition of the Item simpleicons-5/J/Jitsi

sprite $JitsiXs [10x10/16z] Oq07h1WYd0mSO1f8iSF4E13Ak1bOG0Bid301BWQe1YQe

sprite $JitsiSm [12x12/16z] JOk30G0n40GdPl_jFdFcWXC1Y-pEecTpS6MVBq4antFtJWf7GU4tpoU9dwJK_7k0dFEF_iY96m

sprite $JitsiMd [16x16/16z] TK-50GCm328-___RkisgSG1xCTvNlBkiRwxGcnzoVUjtyEiOS0qOOCEZ_gckObokWCZmQzpA9im0czeijsirTZaxgaNT7VEmFH28w8-k3

sprite $JitsiLg [20x20/16z] {
XSz70i903CLGsTzJuVxNfPEUp5jg9uOIEzgtKB1pPwDu9hFMe5Jj6pGcNY4AY9dp5InPRGa4it09pyHcwWOjvcAz2ioCdreB3S0GN-8_469gT00g4v48ASJC
dRt2sXC
}

!procedure Jitsi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/J/Jitsi', $name, $tech)
!endprocedure
