' definition of the Item simpleicons-5/J/Json

sprite $JsonXs [10x10/16z] 9Kg50G0X4Fgtc_st5UII-bWDF2oeJXOmZ4BZuwAXmf735Ph8Hhfu9_6qIcWZR8CB

sprite $JsonSm [12x12/16z] HSwr0SHG04CnXvDFsd_QOtYLt3dFgYbvvTNuK_7YMLVeeKeccgAgIQY6m_5oSzYDbucJP5U9ZlF4djU0_demO4lk

sprite $JsonMd [16x16/16z] {
LO-50SGm30FB3T_-sxwbFFKAYSnUpD6vV34DSnzJyY6tXsJGPd3E-I0eR7BVZ1cNO8SAQ-Wa1yt_9TXy6tgjLySNXFqp4x65xcHv5AA0osUFCn6a98dY1b-y
GKq_QTQ4QBg_
}

sprite $JsonLg [20x20/16z] {
JOu5Wi0m40At7f__l_O4KfbgM86Of46EBoUcb2KcF0mEIuENH7BNby4sTzLKZrtQ1cwxeCo90Yc0DXZnnuf9RZk_0RfkLcaLCRG2PorGqPE0JLgJBmTa84dJ
68Hd-PUoPrfqrr1wvTvZdOsab3gWg8cBB-4rcPSrn3eqvC67o-Djr-aN
}

!procedure Json($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/J/Json', $name, $tech)
!endprocedure
