' definition of the Item simpleicons-5/J/Junit5

sprite $Junit5Xs [10x10/16z] BOQ50S1038IeUzb_shU4KngN6nq7PpyNlTUMvRBJcdSt-LzQR-Clap8UFPSJtEt0PWSg

sprite $Junit5Sm [12x12/16z] JOo50O1024N1LkBllwr768zE2WG75IWoJNz5Y8weEg2Pev38cLSq1vGuOsA_tRDpfvb9W3sUsYM8ri16ajqR

sprite $Junit5Md [16x16/16z] {
NO-50SL024EJxmAN_RTj0_LtYWEAP-fFhAIQLqcKHY6bPKbtB9zevnjYHlNpJMZbwGkxd2MRfpOYdEdZxryhe6zUPAnYL8A1bo_UsJMw-m_1ppP1oBHOt5eQ
_ay
}

sprite $Junit5Lg [20x20/16z] {
JSu72W0n20J0JU_n_x-zKvRWqCGE6bTsWTE4JWI9qr_gPAFzmr8McAHnvgwAidz759Sb3B-I9MkXmTnkTGbTvimGhr_PxzFj2a0LLLmk8OY2omLOnt5F7Euh
Y7eSY2a0HHGV252JAOR-aF6tyNHUAL0V
}

!procedure Junit5($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/J/Junit5', $name, $tech)
!endprocedure
