' definition of the Item eip-1/MessagingEndpoints/MessagingGateway

sprite $MessagingGatewayXs [15x9/16z] NOq53W0W008tEVJ_BxQR9MqsR4mO4B6nIPk9w5ILIeCAaZNex_xTR_dxBG

sprite $MessagingGatewaySm [18x11/16z] POw53S1030Ebzrsw_yHbZiNcWWSgnRY16yFDHChmC9XuCo63t4p0gV8mtTDx-bR_qpyl

sprite $MessagingGatewayMd [25x15/16z] ZL033a0n54jMRFU_y4Smg_53bJH7KcW1_6C6TGj5cwIx1ItA0Bg51SmM48O5J0mBIdAC9Yy_rXe5AgxEESgg95zqjMpt1G

sprite $MessagingGatewayLg [31x19/16z] dP993WGn2CIa68pw_m-UVVgK12c-ibDrkUDoJE7D6Cx2MLbgCGj7MPc0ap0QBCDfm38SmZGCdt0kmbd6D8nlweMqrUtiaytl6G6SVkqpm4buhbYZT-EM9m

!procedure MessagingGateway($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'eip-1/MessagingEndpoints/MessagingGateway', $name, $tech)
!endprocedure

!procedure MessagingGatewayGroup($id, $name='Messaging Gateway', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$MessagingGatewayMd>', $name, $tech)
!endprocedure
