' definition of the Item eip-1/MessagingEndpoints/SelectiveConsumer

sprite $SelectiveConsumerXs [15x10/16z] uq43J2W0EvSDnWKpcJcOOLns863cPERXv-RdXofcusN6C8em5m

sprite $SelectiveConsumerSm [18x12/16z] uy44JEY0514sDcOa4NOc9bPsRh087qY47GIOcLcPkVbvUVdPmMfOWPgOcLd0cX7cS7AIOpi2

sprite $SelectiveConsumerMd [25x16/16z] jSy52a0n281Xy7UzuVrF-xg3taVRrb_oeqyYnlYP2BuH7maVl7WWWo2YjYGqB28Or6AjcDMZGyI1Hyynvuv4rDkEa-lx-Ti8

sprite $SelectiveConsumerLg [31x20/16z] {
pP354KKn201dMFGP_LVxtVMQZGTd-OFyWd74wZ_46g3vGOmTzs2f8YuYVn17E4UiA973bANzB8uhm0enpztpqjqFrew8Gi8imj5tlwPMCA5yBIp3qmRg-Myn
lx0z
}

!procedure SelectiveConsumer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'eip-1/MessagingEndpoints/SelectiveConsumer', $name, $tech)
!endprocedure

!procedure SelectiveConsumerGroup($id, $name='Selective Consumer', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$SelectiveConsumerLg>', $name, $tech)
!endprocedure
