@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('material/bootstrap')

' loads the Item which embeds the element PanoramaFishEye
include('material/Image/PanoramaFishEye')

' renders the element
PanoramaFishEye('PanoramaFishEye', 'Panorama Fish Eye', 'an optional tech label', 'an optional description')
@enduml