' definition of the Item aws-q2-2023/Architecture/MachineLearning/AmazonSageMakerStudioLab

sprite $AmazonSageMakerStudioLabXs [10x10/16z] RSQ53S10302ne7BxBro69ulCck9lJGw06mB9GTv5eVT0wd2FtWu

sprite $AmazonSageMakerStudioLabSm [12x12/16z] VSR50S1030InCyGx_JSSPj9B_2ZRQqbkTyn2Ii3Ai83begtFP3-1caLq07ASdNWO

sprite $AmazonSageMakerStudioLabMd [16x16/16z] dSc53SG03C30SBp_mW_520iMdioRFAm6bIRcXXPnTrdfeQW2jhWicSuoaDDECp-6C-rOszBgji2OHNApBm

sprite $AmazonSageMakerStudioLabLg [20x20/16z] hSgv5SG02CHGOB17_JVi-qvtVwWdVcVnbKdfaqXeNaGNiMFdX22tSJ2h5bMCyMnIe_7zQNduViRm_kZmYDyDqUldHPjTqO5t79o9YuyXn5_C

!procedure AmazonSageMakerStudioLab($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Architecture/MachineLearning/AmazonSageMakerStudioLab', $name, $tech, $desc)
!endprocedure

!procedure AmazonSageMakerStudioLabCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSageMakerStudioLabLg>', 'MachineLearning', $funcName, $content)
!endprocedure

!procedure AmazonSageMakerStudioLabGroup($id, $name='Amazon Sage Maker Studio Lab', $tech='')
  IconGroupElement($id, 'MachineLearningFamily', '<$AmazonSageMakerStudioLabLg>', $name, $tech)
!endprocedure
