@startuml
sprite $AzureGenomicsAccountsLg [10x20/16z] LOu50W913CGsqydz_yaKXwpKnJaFHfqbr1hWn44dHDSgLDbSHkUXrCAgQ3XpILT9CjQUPD7LU6hVA9f78_Q7Nltlx3fe7af0cMk0WzN9Skft-ni

sprite $AzureGenomicsAccountsMd [7x14/16z] BOo70G10306vnFuZVqrl23wMDBX2oWIPRgIwgwhlwpmDbMbprA-wU8kScbin6UaD

!procedure AzureGenomicsAccounts($id, $name="Genomics Accounts", $tech="")
  CloudElement($id, 'azure/AiAndMlServiceColor/AzureGenomicsAccounts', $name, $tech)
!endprocedure
!procedure AzureGenomicsAccountsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureGenomicsAccountsMd>', 'Genomics Accounts', $funcName, $content)
!endprocedure
@enduml
