' definition of the Item simpleicons-5/W/Wagtail

sprite $WagtailXs [10x10/16z] uwS3

sprite $WagtailSm [12x12/16z] unza

sprite $WagtailMd [16x16/16z] un_X

sprite $WagtailLg [20x20/16z] unzKO1G

!procedure Wagtail($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wagtail', $name, $tech)
!endprocedure
