' definition of the Item simpleicons-5/W/Walkman

sprite $WalkmanXs [10x10/16z] uwS3

sprite $WalkmanSm [12x12/16z] unza

sprite $WalkmanMd [16x16/16z] un_X

sprite $WalkmanLg [20x20/16z] unzKO1G

!procedure Walkman($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Walkman', $name, $tech)
!endprocedure
