' definition of the Item simpleicons-5/W/Webauthn

sprite $WebauthnXs [10x10/16z] uwS3

sprite $WebauthnSm [12x12/16z] unza

sprite $WebauthnMd [16x16/16z] un_X

sprite $WebauthnLg [20x20/16z] unzKO1G

!procedure Webauthn($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Webauthn', $name, $tech)
!endprocedure
