' definition of the Item simpleicons-5/W/Webflow

sprite $WebflowXs [10x10/16z] uwS3

sprite $WebflowSm [12x12/16z] unza

sprite $WebflowMd [16x16/16z] un_X

sprite $WebflowLg [20x20/16z] unzKO1G

!procedure Webflow($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Webflow', $name, $tech)
!endprocedure
