' definition of the Item simpleicons-5/W/Whatsapp

sprite $WhatsappXs [10x10/16z] uwS3

sprite $WhatsappSm [12x12/16z] unza

sprite $WhatsappMd [16x16/16z] un_X

sprite $WhatsappLg [20x20/16z] unzKO1G

!procedure Whatsapp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Whatsapp', $name, $tech)
!endprocedure
