' definition of the Item simpleicons-5/W/Wii

sprite $WiiXs [10x10/16z] uwS3

sprite $WiiSm [12x12/16z] unza

sprite $WiiMd [16x16/16z] un_X

sprite $WiiLg [20x20/16z] unzKO1G

!procedure Wii($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wii', $name, $tech)
!endprocedure
