' definition of the Item simpleicons-5/W/Wikiquote

sprite $WikiquoteXs [10x10/16z] uwS3

sprite $WikiquoteSm [12x12/16z] unza

sprite $WikiquoteMd [16x16/16z] un_X

sprite $WikiquoteLg [20x20/16z] unzKO1G

!procedure Wikiquote($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wikiquote', $name, $tech)
!endprocedure
