' definition of the Item simpleicons-5/W/Wire

sprite $WireXs [10x10/16z] Ou039X313oR0c1VEuiFBueLeXz3CK446i09s8EPWO

sprite $WireSm [12x12/16z] Oy00d62I7qBmKyfcXx3vG4om20SFH8IHdusLdukNbHEiZ84HYW4

sprite $WireMd [16x16/16z] jKw35K113ClPpVxJVXlFLxl13wdDStEDYzzSihZbMVVAsm8asYqNNHPqikK4rU9hMkOgm02WSiwBB619MWII3YyQ0G

sprite $WireLg [20x20/16z] pKl50GD02CkvSjb_sXhmgZwB4y6F4OCTv7I8pQ2PJd7MCQ3B2-py4IPspcb7mXfEKm-PVYL2NBZL6bW1hiUzMPKx-iaKIZhSc-pGo2q_TkiHR-8A

!procedure Wire($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wire', $name, $tech)
!endprocedure
