' definition of the Item simpleicons-5/W/Wolframlanguage

sprite $WolframlanguageXs [10x10/16z] 1S670OD000GW4lrURlzj1HWf82x_GV17GPINEK15x6qBXS0XyF-B0G5b87m

sprite $WolframlanguageSm [12x12/16z] 5SI50KGn3CFGzndQnFjFUs1B0YCt82PxODeNWn0Uer3OgS8O70Z4Wxd_Uoixc5pRSLrlPsW1mKLWYOOQoCKN

sprite $WolframlanguageMd [16x16/16z] {
FScvOSGm300mwDVP9hd_jkc25i2CUXk0o85J6xHgdXTEGD768p4_eX6y6vukSJW7r1m4Ue8CLeCMy2lIv0k5ynfN0Vjwsothd3KQGga2wZmlOGVmFKZ406fv
r_-mAnVGA-zwCk0F
}

sprite $WolframlanguageLg [20x20/16z] {
JSW75WGX20JHaZ6EOD__jllO_8qKR-l86t-6OjJQbi9uKy0n0DDwfmwzJYf0t9_4PjiXdGOZW6dqRGPG18BNrQoIxaa0wm9slo1fZMn0ndSx3SJBMAHGvN8S
S64YFzxmqbLvsGEYBGJY8tBMTCO9Z_1xzdeeGMZm8iCgg64oNeOAq0Givqq2HBgZG2gAfWjIquAq9VYOakzGDD83
}

!procedure Wolframlanguage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wolframlanguage', $name, $tech)
!endprocedure
