' definition of the Item simpleicons-5/W/Wordpress

sprite $WordpressXs [10x10/16z] BKm50S1046A-L_gdFNS3ODRumerUpbQ3jGTaREmjsccLCNbzlUL-WItVrWPwA3nUBHK

sprite $WordpressSm [12x12/16z] 5Sh5WKLH08FGy_N95VglTYI17M1q0e9tC81FDDPpZgcMTm_FFu_cqA1DKloxdVu3FJrvQqwjsvRHxMuwIEYnOOKEVW4

sprite $WordpressMd [16x16/16z] {
HSl5eM0n34FHynWIM_rNE_3nheJ0KHcBRwftt3c1V3TNGNpJcTGSfSQOcoIh94WUPZh7dfoS2JAw76by-kq9luUu1ft3Bg6CvROdMkBOHKWCCq_Hpjl8krYI
gL7xcY3PnW5pvC6LFe0r_LuZ3Ny1
}

sprite $WordpressLg [20x20/16z] {
NOk5WHX13CHqosZrNstoJ3B3yC4CJ-C7tJjgQTER-C3B1ya90FxGFAw_AzGAtNqku-pNWYeV6NG3wXhShGa81OhYxEW4kYP0CUh71nf0NAw5eS2Z0ZREQJow
OLIj84HRe8Be8GaY5CqijZ8Ap-Lcq3KpMLE0bIHi5T0uL84P5Dt0qee0h7WK0Arc0AX-x4BvOkWzuQq0_0S
}

!procedure Wordpress($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/W/Wordpress', $name, $tech)
!endprocedure
