' definition of the Item simpleicons-6/J/Jabber

sprite $JabberXs [10x10/16z] 1S470G0X00GWVhgz_cq5jFq1GIu0Fm0DG22zqC1DOAA3y0BnW0C

sprite $JabberSm [12x12/16z] JOs30G0W402piV-qyNNrbZgquTMdJg_zoC-FJpkhc2dy01EooKJkEMxvFVx8_1qwvQYG4ItUDHsJ6m

sprite $JabberMd [16x16/16z] LSg53GGn00F1lJ2x_seVey083NoLqJoBf366nieFNsdC_8_W4pTnIuwBg_oDL1x0bvb38mAoCoSAa3kBWzPPRq2HoQOUCYlYEk1PEaaoB8yA3zCR

sprite $JabberLg [20x20/16z] {
RO-50SKW34GJt6__QR-qE1p-YD8ZNqhKD4cWgeZEDC9pCi2DgJX-cGwPIATmOTwVJEDaSZ0OXdgIJ8m2s-VYvtHF5H5BW_P1t2jzRrpAi4buZXBc0XoiyPG6
QScKdfcsI26k39f84jcPSOGtKu8l
}

!procedure Jabber($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/J/Jabber', $name, $tech)
!endprocedure
