' definition of the Item simpleicons-6/J/Jenkinsx

sprite $JenkinsxXs [10x10/16z] Oy02UC68WGE4880RH32nieD88EPdO-1XXQc6gcBbPU3dXGhmeve7

sprite $JenkinsxSm [12x12/16z] TOg54G0X3C22Ezr_sp_yx0ErjFoW09T36RLaJ1ukqYnnhxCUhL7AM983h1Y2C2v733p3kn22Jij4BLpYiOyF

sprite $JenkinsxMd [16x16/16z] ZSp50OH0343HDvRWz5_jkbpvSNMDsYgGa0DpXtNNMe5kqgUOen5OM4gbOSfC5Cqob7LGjgJl7FgvqywLZa9KBnVuVC7ur6Q3sbhwKjQpfZzZNNDnXJi

sprite $JenkinsxLg [20x20/16z] {
fSm5SWGW38NX7taa-Frlsw5KTdpbmudmkTJ66Curxvuukj-Z2KiOX-E1NhrI0US89mV5-uxXju-mxqKiCZCCyEYCMaXzEs1Ru5s0aVSk4CRvMnmLf02eP127
UE1SdQ8hv0HNbIQapOpySzOs2e-SkKNYKH24mck-
}

!procedure Jenkinsx($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/J/Jenkinsx', $name, $tech)
!endprocedure
