@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceMultiFactorAuthenticationCard
include('azure-20/Item/Identity/ServiceMultiFactorAuthentication')

' renders the element
ServiceMultiFactorAuthenticationCard('ServiceMultiFactorAuthenticationCard', 'Service Multi Factor Authentication Card', 'an optional description')
@enduml