@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-20/bootstrap')

' loads the Item which embeds the element ServiceAzureAdB2CCard
include('azure-20/Item/Identity/ServiceAzureAdB2C')

' renders the element
ServiceAzureAdB2CCard('ServiceAzureAdB2cCard', 'Service Azure Ad B2c Card', 'an optional description')
@enduml