' definition of the Item aws-q1-2023/Resource/Compute/AmazonEc2R7IzInstance

sprite $AmazonEc2R7IzInstanceXs [10x10/16z] Oq0576n876RiB0uWP0AoE1ZOe69ioEgOmO0LoJm

sprite $AmazonEc2R7IzInstanceSm [12x12/16z] LSs50GHG20BGzmlTV-7hj1FyIuOcq7a92Q1Z1523g5MBq57cZcu-DxxrFmxLzR3znti5

sprite $AmazonEc2R7IzInstanceMd [16x16/16z] TO_50GH1409h3CW_uPDrvTU2yG1XWj4oUvazZwsiC22NdIW1XndmyUxvNeJNUr9mfGuAIcP-hxGntlZx_EXlhSXp7o62flaB

sprite $AmazonEc2R7IzInstanceLg [20x20/16z] {
bL250GCn489Jzf-uaRf_FAS0Fer20XeNweijMsDU3YvRusxuj5NfmTR5jt6PZt6Lx-EMJLoN4Mx38caSsn0ZJh8Trs20IFiVYntZuNSZDpwoMJIndSrlcd9C
s3nMs0a
}

!procedure AmazonEc2R7IzInstance($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/Compute/AmazonEc2R7IzInstance', $name, $tech, $desc)
!endprocedure

!procedure AmazonEc2R7IzInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2R7IzInstanceLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2R7IzInstanceGroup($id, $name='Amazon Ec2 R7 Iz Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2R7IzInstanceLg>', $name, $tech)
!endprocedure
