' definition of the Item simpleicons-14/E/Ejs

sprite $EjsXs [10x10/16z] Oo04-C60WO4JGh4py099FZ2R0KWm0oaWamsa54oni78oC38n8Hi1

sprite $EjsSm [12x12/16z] VSR50SH000GWuhxJVxNdBk657V4mJPEsRO4k6OUwi6Kr1kTIoGbridOmOMkji6AQf4sM0VeAFXq1

sprite $EjsMd [16x16/16z] ZSU53SH034JHRmWiJl_TtbaHHPXd7Bw8YvVHNh6rbboPoUEyLgZtFkG6DgLbuayrsiO-9u-b3iXLW2R94HuHkm4IXYWzQylmSVAthNRRp7D9QXTbxklWiny

sprite $EjsLg [20x20/16z] {
dSL7WW8m34FHdzwZ-zzsd4o75JnR4gy9F6cAF5ayQiPHe_5yaV7wvBXSw5b9AGTGm3IPh2QEWf4K86WilYq9qtRJXPaoDfNMUkzQ61tim5M5YMg0-3GcHnOW
nA7yDQ8AcTqALrHQ3N3Uy2lnZWy
}

!procedure Ejs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/E/Ejs', $name, $tech, $desc)
!endprocedure
