' definition of the Item aws-q1-2024/Resource/GeneralIcons/AuthenticatedUser

sprite $AuthenticatedUserXs [10x10/16z] NSj50S10000WvgVzuywTFzugnLSFZPzQxq08H0Zwe8LG1Ur621O

sprite $AuthenticatedUserSm [12x12/16z] NOk50O1G44B1Lhpzn_tTxph0mhyVNsrZEdE_rKNW7led18dCQOQ2Kb8iLvrLHBeF2dVvOmWb608U

sprite $AuthenticatedUserMd [16x16/16z] RKw50G0W2BCB-FzSkvLkndx44T2iLDGOMZ8ZoMU_EJToVULOhPhpt1KJs28YqYi3Kuzgq7EzkAdpYSgMym5AAPCjJX36P3lokOkTeDrF

sprite $AuthenticatedUserLg [20x20/16z] {
TSw5WGGn243HZuo4WVxBFOkTxOihy9f7Xl53dS2Li8K0u3TRetjOJEaEONAbk-Jlss1xzjvM1bZoGrHL0xOhNKIE6r6XAwVBs-xwcMaAG05DwUG6_Be5aa7D
y42LKzdtAk0MWgLcdxfG8wxQmiZl7G
}

!procedure AuthenticatedUser($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/GeneralIcons/AuthenticatedUser', $name, $tech, $desc)
!endprocedure

!procedure AuthenticatedUserCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AuthenticatedUserLg>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure AuthenticatedUserGroup($id, $name='Authenticated User', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$AuthenticatedUserLg>', $name, $tech)
!endprocedure
