' definition of the Item aws-q1-2024/Resource/GeneralIcons/TapeStorage

sprite $TapeStorageXs [10x10/16z] XS450S0m000Wvjw_xWFSm8-pAVCG5qI7TGHRSfOjiia5pQCB

sprite $TapeStorageSm [12x12/16z] ZSIt0S0m3CJ0Kmxa_lEwSwr_0DvM_jQj3h5ibcwWIjMa65V8Jkh98NRUU_CSB_i

sprite $TapeStorageMd [16x16/16z] hSMt0G9130NHTxTU4lsNYmc9uPiPVyZrvREk6QXsHMDTYL0Ecw98jvKSvPfJNZo2L3PA2Av6Tg8vWwjWvxa_YUX-pWi

sprite $TapeStorageLg [20x20/16z] {
lOw50KD134BXNCZ-wvRKHlYdBmwUMlp3ZnHRIkXnTioaw3jVeArZcCktu6PeGs3vHEsOTvSgk2g4sWjazt0iQ9zSNGjSlhBaUBFJu1lCVY9sIQ3UJs6vSSw9
JQxq8qNq3s1EFBHU
}

!procedure TapeStorage($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/GeneralIcons/TapeStorage', $name, $tech, $desc)
!endprocedure

!procedure TapeStorageCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$TapeStorageLg>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure TapeStorageGroup($id, $name='Tape Storage', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$TapeStorageLg>', $name, $tech)
!endprocedure
