' definition of the Item aws-q2-2022/Resource/NetworkingAndContentDelivery/AwsAppMeshVirtualNode

sprite $AwsAppMeshVirtualNodeXs [10x10/16z] Oq05J12Cu76340k8nGXaCK74K6KPcK0ws80iRcvalKnGm08

sprite $AwsAppMeshVirtualNodeSm [12x12/16z] JKg50G0W2AFC_V-lBSsAOYdFadKwyUHbgmSJvlI9ApPkc1XjOfEN-PTl7XDBo5UfkVIVr48RzryO

sprite $AwsAppMeshVirtualNodeMd [16x16/16z] VKw50SH02CifaEm_xt_TMzm9hYGUIU1KhLgwuADlcbR7FCcc1b3pc0SuvOcrJVDAG9VtTJykzsAzvp7Vwykzd8xtG7AUpvKqyozyQ2j-dSZ-

sprite $AwsAppMeshVirtualNodeLg [20x20/16z] {
RSy50iCm30D0DUHQ-lzx1nexKp7d8Fw5gcdGgzXUtuznShE0TbE_lPN3jjnoSJJGbj3BA7QRZgSrVURpBvCdYYr_Qh-ulVlwDh-FiwMDXrus9_ArbmLRAWJR
O6iCHQgLivLrdTJuM2iP3MqBhW
}

!procedure AwsAppMeshVirtualNode($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/NetworkingAndContentDelivery/AwsAppMeshVirtualNode', $name, $tech)
!endprocedure

!procedure AwsAppMeshVirtualNodeCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsAppMeshVirtualNodeLg>', 'NetworkingAndContentDelivery', $funcName, $content)
!endprocedure

!procedure AwsAppMeshVirtualNodeGroup($id, $name='Aws App Mesh Virtual Node', $tech='')
  IconGroupElement($id, 'NetworkingAndContentDeliveryFamily', '<$AwsAppMeshVirtualNodeLg>', $name, $tech)
!endprocedure
