@startuml
sprite $MaterialsPersonOutlineLg [20x20/16z] {
hKtL0ODG32Jk-uzRnN_RWsSvM_u05C7RY3kp-JA2L01Dk3WRFzj5r_psmyMihQ__LYBkijm0Y70Ti6TLEXzZgJ8cOglQ_DG2grwQrixOBH2wpYPyHSmw8ps1
bj_m1
}

!function MaterialsPersonOutline($id, $name="Person Outline", $tech="")
  CloudElement($id, 'materials/Social/MaterialsPersonOutline', $name, $tech)
!endfunction
!function MaterialsPersonOutlineCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPersonOutlineLg>', 'Person Outline', $funcName, $content)
!endfunction
@enduml
