' definition of the Item simpleicons-14/V/Vitess

sprite $VitessXs [10x10/16z] Oq00Vdue1MLnyBE1UN224KC90oS_a04121OJFy9C404

sprite $VitessSm [12x12/16z] JOs50O0m40DnXzj_Mg3lxabN1JJtqC5jizKNewHR8Wp-iTlR8Ly1zV1OlHBZBd0Li93l4Zy

sprite $VitessMd [16x16/16z] NSt5WOL050J0nftAFzhTxp1JjwUTIiUPBmHjtZRcDBYDavC-JoVTrRuMT-OaQAwxUz3A7kGB4tk-Pf0BBBaCo1rZxbefDNdx1m

sprite $VitessLg [20x20/16z] {
VOm74WCX30D5x_3_tqR3DKEIMvfjxO0VXDvx47qd60Gtdbs2c_V5OInYPEtv6hvjqKXZeMQLMUbPgKEKsb6gTNGqXrz1n3_jqAHeU0eUqZY0v1WvI8BKf6Yn
eiVesEb3OKSDlF41
}

!procedure Vitess($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/V/Vitess', $name, $tech, $desc)
!endprocedure
