' definition of the Item simpleicons-14/V/Vivint

sprite $VivintXs [10x10/16z] Oq01l306Fpy_ZC47PZA2I2uG0P71oO82JdvcRWXWu0O

sprite $VivintSm [12x12/16z] VSk35O0004NHxBhxJvkjT_GPt8WE6RF97C9PbgD8I1SvFHXFh9_uJrSJjRYr4nES6

sprite $VivintMd [16x16/16z] dSb50e0W00NHRxTp_zDQD1kL8H_eImjzp1MO0ZVkPiSTTW6h8HVDiTdVpRqtvf2fsBFfSajIiy4UkmPbdG

sprite $VivintLg [20x20/16z] jOk30K0n34IlThF_jDysNva3xa5fBH75bLGpLHYrv4NAvcbIK8K6V2EEHGLCnVh3qQ2hh-WqYuuVjUGx6gsQQOvmj4Bm-Wep016mHGa

!procedure Vivint($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/V/Vivint', $name, $tech, $desc)
!endprocedure
