' definition of the Item simpleicons-14/N/Nuxtdotjs

sprite $NuxtdotjsXs [10x10/16z] Oy0EcFXXB7v-88OmW8YV4SG2SS0a4vJ322BPW59WDKmWWXzX6

sprite $NuxtdotjsSm [12x12/16z] Oy03c97O_Fm89Xy_3oC_EuZ9o0-IuUO72tE0s625d201AEQ7QUO4wWC11YOmYGC

sprite $NuxtdotjsMd [16x16/16z] dSJ5OGC100GnsJwcwR_QC3-Z1Vynv9UARtjxewiRRphLlVAck5TZCumjg8V2vryVTtJ75UpHYRKTrDMRYzvONomtflNLx8-_dW4

sprite $NuxtdotjsLg [20x20/16z] {
jSu53iD034HHXpdl_hUjLgv2ui9VD4_yXPfuWkNX6g64n07DJ60zN2NE2bMw6gMaHJUIFiPy7FzthEAe2UhoR9OZUyrP7OU6AlyZ_Q5r9vbBUHBvx7MPacpn
1Iy
}

!procedure Nuxtdotjs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/N/Nuxtdotjs', $name, $tech, $desc)
!endprocedure
