' definition of the Item aws-20210131/Architecture/MediaServices/AmazonElasticTranscoder

sprite $AmazonElasticTranscoderXs [10x10/16z] FSZB5O0W3031gC2a_uhblwTvYpQgrILUCJZMkYaCVIqp8iGJNGsghlTzZPyZ2hd93m

sprite $AmazonElasticTranscoderSm [12x12/16z] HOo53G0m2C26y__3U39lCJFJNIBsPPX0HZfS1u-nNOgze9cQdTvxzd1P0BffsAn4IhnN3ohnayBZdPO

sprite $AmazonElasticTranscoderMd [16x16/16z] NSZ50G0n48NGqK_wRtXTm-q1eBlkvZVKJEDWLCN7Qf37upXczUu1pL65xnwtqoft3ziAp4rrE3ena8KkkmBQdTDIPsQOajrxG5WdZ6V8WyFtE1hJM04

sprite $AmazonElasticTranscoderLg [20x20/16z] {
RSs50GGX40F0jIHy_mt_BUSIV31rU0PBz4JkfYz3rAah1KIx6wCxSroig4RwQSVlo6eRacp_F5dPjk3-kI72fWrQ1t8hvsvaITujdBj19aZgxh2SvnXCQBNe
G6QmCgbjHf8S3fCqhjZ7ffsuPtpWxmF_
}

!procedure AmazonElasticTranscoder($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/MediaServices/AmazonElasticTranscoder', $name, $tech)
!endprocedure

!procedure AmazonElasticTranscoderCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonElasticTranscoderLg>', 'MediaServices', $funcName, $content)
!endprocedure

!procedure AmazonElasticTranscoderGroup($id, $name='Amazon Elastic Transcoder', $tech='')
  IconGroupElement($id, 'MediaServicesFamily', '<$AmazonElasticTranscoderLg>', $name, $tech)
!endprocedure
