' definition of the Item fontawesome-5/Brands/_500Px

sprite $_500PxXs [8x9/16z] uwSI

sprite $_500PxSm [10x11/16z] uwSh

sprite $_500PxMd [14x15/16z] unzs

sprite $_500PxLg [17x19/16z] uwSKZ08

!procedure _500Px($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/_500Px', $name, $tech)
!endprocedure
