' definition of the Item fontawesome-5/Brands/Adversal

sprite $AdversalXs [10x10/16z] Ou03Vap0ZCHYOc1bu0TYa1Wxa0KIOs3aXx6uMO0iFf0iBqWz3uY60G

sprite $AdversalSm [12x12/16z] ROkr0S103CJqpFR-suOvgWwvCVIFUDFCaspihAoRTKOIIgdhTTXPhvkCoQisGqbQZdo0PRRCEfrea8i9

sprite $AdversalMd [16x16/16z] VSo50SGW5C3Gr738_jEUk_JXVE73EjvqzmHyirtU8oNFKhkyPu1iuKm7cu9Cb-EiRo3zreyBKJDQQ3eX-Te_KqqWZCuzVqOvyqihBx9Cxuu

sprite $AdversalLg [20x20/16z] {
bOy55aCX4CJo5MVkVzk-eUvjy62xl63Qdz4lrFxiMFvn6y0cQVSut0ph1ad1Xk50KcOJT6cnCoqmtEMzYh6RBWwch7fthexjm7fqqQv3qUhlTkWHEqzX0_y9
TgPTqgwdONgWgEaPNd
}

!procedure Adversal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Adversal', $name, $tech)
!endprocedure
