' definition of the Item fontawesome-5/Brands/CcAmex

sprite $CcAmexXs [11x9/16z] uwSz

sprite $CcAmexSm [13x11/16z] unzS

sprite $CcAmexMd [17x15/16z] un_P

sprite $CcAmexLg [22x19/16z] un_aO1G

!procedure CcAmex($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/CcAmex', $name, $tech)
!endprocedure
