' definition of the Item fontawesome-5/Brands/Cloudflare

sprite $CloudflareXs [12x10/16z] Oy0B-FbXB2P-VYY7cnyCUC7o4C08b09IC4t809V9

sprite $CloudflareSm [15x12/16z] ZScr0O0m54NHkEVV_QV5hG5ogYTgY7qM5d8rOLMlQ-VMvZaKgElNMoqv6nKgZKi6xCqjrASP

sprite $CloudflareMd [20x16/16z] hShL5S0W343Hu4xsdnRtt_RYxm1_uDQ99s53djJ05D3EvaPokFdOQpmQgGiidgbze3Z46881uagCU0Ais8No2Zx8

sprite $CloudflareLg [25x20/16z] lSp55G0X40FGu4xwhtPTvt7ctqOIp1L8TWL9yvGXy9RmCi5aFhxbFq6qFFHJnv_kpZxT-TEKugPSxmf_PAHWqJWKhxsHO4-OO0K

!procedure Cloudflare($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Cloudflare', $name, $tech)
!endprocedure
