' definition of the Item fontawesome-5/Brands/CreativeCommonsPd

sprite $CreativeCommonsPdXs [9x10/16z] 1S650SD0000Xgf6Nst_R0Bo0Egu6_M0T-Xn5bzs1EvfTVh-FBbU98jU6tXnLF

sprite $CreativeCommonsPdSm [11x12/16z] 9Kk50S0m369rv_zl1sqy21pXmmlo7F9UoNDGLz2UwWroaluvcvxzB5bzNRiDD6sBeAqrqNLs8DZLrEkQZkUYeW0_

sprite $CreativeCommonsPdMd [15x16/16z] {
FOw54SGm40Db_2I6xR_R7urXZSVI8WPT6fYyBFWaXS5ObXQ9BdLRkRLYEmbcx82zWqm120fEPx0wLncOpXd0QxCXlM0VJGJif9Uk1iWQykxCK2Mvfwzl3Ij7
UbqFRowTumwOpzy_
}

sprite $CreativeCommonsPdLg [19x20/16z] {
JSs54KGX4C3GVCVJVxStB6Tl3DtmiM_yExkXV8_7t5ttFBy-9tqdN9e1jFAb9zphvAarhJDG7pO3S9jm6F8pc3GBJHs__138gls0zneeUgdEmyScaFJcx56g
Nfv440vMYHXSdH9RqKxtMDEqCEiNkp8T4RmTaN0Zn1fMByVXENGdx7vqlgwP77bdUW4
}

!procedure CreativeCommonsPd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/CreativeCommonsPd', $name, $tech)
!endprocedure
