' definition of the Item fontawesome-5/Brands/CreativeCommonsNcEu

sprite $CreativeCommonsNcEuXs [9x10/16z] 1S450S10000XvlxNl-q09g3MlPSMU2xDKz6bDbnHNPPj4dU98jS7pHnLany

sprite $CreativeCommonsNcEuSm [11x12/16z] 9Og50KGX3CNo7QXa_sbFgyy0s3V-fTKAu0um_ADoCHfTzd62yQ0rWFPWg4AEoVxzAeBUYoaE21zwWWbWmp_d3My

sprite $CreativeCommonsNcEuMd [15x16/16z] {
FOw50GGX3C1oBa2p_xGlM92wq5WN9jdAoPz5h-OCWFetVu4Yi8V2wewMvT9ipTyzLMTwW0wF5ZZzym2cWD28q8IBW8vj-2TTgcs5qnNMR8RRfGwZyhQjazxR
blGOq_-y05y
}

sprite $CreativeCommonsNcEuLg [19x20/16z] {
JS-5SLWn403H_IpU_gjDRD7u3HyVotdorrFjyi6a-bvtKZ-wPcQuDG5ePDCNlf48seiLr0UQQksz4PjQz89ppX5ghvYgJJWSUjMdzW731JoMNhLz11yFG0Dm
D5NfWxE-n_5m9AsKFdNc8VfmAi1RhQ4l0bvbUPJvNZm0hlv4TxeqjYUhBPu0_0S
}

!procedure CreativeCommonsNcEu($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/CreativeCommonsNcEu', $name, $tech)
!endprocedure
