' definition of the Item fontawesome-5/Brands/CreativeCommonsZero

sprite $CreativeCommonsZeroXs [9x9/16z] uwSs

sprite $CreativeCommonsZeroSm [11x11/16z] unye

sprite $CreativeCommonsZeroMd [15x15/16z] un_k

sprite $CreativeCommonsZeroLg [19x19/16z] uwSF60K

!procedure CreativeCommonsZero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/CreativeCommonsZero', $name, $tech)
!endprocedure
