' definition of the Item fontawesome-5/Brands/Cuttlefish

sprite $CuttlefishXs [8x9/16z] uwSI

sprite $CuttlefishSm [10x11/16z] uwSh

sprite $CuttlefishMd [13x15/16z] un_w

sprite $CuttlefishLg [17x19/16z] uwSKZ08

!procedure Cuttlefish($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Cuttlefish', $name, $tech)
!endprocedure
