' definition of the Item fontawesome-5/Brands/EdgeLegacy

sprite $EdgeLegacyXs [10x10/16z] 9Scr0G0W00F1u0xxJulzLH4zJbWF8TeVbngxv5PhZV4Z2IHmlkH81m

sprite $EdgeLegacySm [12x12/16z] DSl10S40542n001l_scXxSyzmC7cqTyLtgqUxBf0HKuttEg91fS6hux6lOnTTU0QF5fXzjaN

sprite $EdgeLegacyMd [16x16/16z] LOw50S0W30HJtBF_jWqyUjKZIXDD1yM0WEU56PdoqtBcpYVEx4TrH8cI1vNmAZzjUqyCVF0utmHuMJWuRU3s6FRBqbW5_f2mWTFhUuKg-WC

sprite $EdgeLegacyLg [20x20/16z] {
RP254GGX40GFTpR_RFy7jowZce6LhyF4j-EeOgQYIJE2LjXCQSuZWGpbyOqePGZWY9jWFw3RbpBzLVk5DMTAaL2eF_AZbVuXUpY53XP4g_OT8ATEIMkGJKSE
tmXBuTxBSFfmvxhyh6DY2McSVm
}

!procedure EdgeLegacy($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/EdgeLegacy', $name, $tech)
!endprocedure
