' definition of the Item fontawesome-5/Brands/Ember

sprite $EmberXs [12x9/16z] uwSZ

sprite $EmberSm [15x11/16z] unyA

sprite $EmberMd [20x15/16z] uoSQZ08

sprite $EmberLg [25x19/16z] un-kO1G

!procedure Ember($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Ember', $name, $tech)
!endprocedure
