' definition of the Item fontawesome-5/Brands/Firefox

sprite $FirefoxXs [10x10/16z] uwS3

sprite $FirefoxSm [12x12/16z] unza

sprite $FirefoxMd [16x16/16z] un_X

sprite $FirefoxLg [20x20/16z] unzKO1G

!procedure Firefox($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Firefox', $name, $tech)
!endprocedure
