' definition of the Item fontawesome-5/Brands/Freebsd

sprite $FreebsdXs [8x10/16z] TON50G0W08JusRB_jFRN2-15QJOagL7nf3_xDKzGhJ01

sprite $FreebsdSm [10x12/16z] XSt50G0X34JHl-ux_LUB3bnvqLD2z_wmN0lygtObhyGcm_E_K3FO5YyBFhC1_a44

sprite $FreebsdMd [14x16/16z] bSUt0OGm0C10VIIZ_QS5PxlbkeFH-q_q8leUkan6lqDnDdchScYogNycYradR7R4mPDDTZFOmL2IoMYcUP7S

sprite $FreebsdLg [17x20/16z] hSZ54GHH203H7lz6TVxHhXkrrtau_5b89hL1yQP0rwgz-50V4oFqOVCcwDMNwit2vCUYCT7yEYeTpKvvD9CE9XCK_QhS33-2XyENmjkHpkmA

!procedure Freebsd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Freebsd', $name, $tech)
!endprocedure
