' definition of the Item fontawesome-5/Brands/Fulcrum

sprite $FulcrumXs [6x10/16z] Oy04_13C1kQmCF02IKO6R

sprite $FulcrumSm [7x12/16z] FOg30S0m44LVhCF-qzRDyOjT9JvlPg2pEW4FIvi0wJuus1Dn09RmlFQyaPwN0vm

sprite $FulcrumMd [9x16/16z] JSR50SGm300m9N4PlF-qXoMzvAd4aJeUQIkKfcqMChLTZahLqWofh3046zZAzz3IaVtCTcOvKeSZ6ju

sprite $FulcrumLg [12x20/16z] NSs54GGX40NHnfsVVxHdQrFNsADi-2yQL-Dfl747rjUHcA1h8IgImoaW9cFnBM_4KTZ7-ROZiDBvyVJ6aHERAz7Dt68SZ9-wSJRsn_C6

!procedure Fulcrum($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Fulcrum', $name, $tech)
!endprocedure
