' definition of the Item fontawesome-5/Brands/ItchIo

sprite $ItchIoXs [10x10/16z] HSY50O0m3031nvtVVrgez-AXizWcAyGfn2uM2qhaWJ36Ef4i_awDJp3Z1m

sprite $ItchIoSm [12x12/16z] JSQ50KKn24FHMw0ksN_Qx_8Ead1b-WBzXVvOKPkjEhqqchJrkiGGRqhC1Q5FDs0-Bz5WI09Bs5nw6WUmDlVPenXt

sprite $ItchIoMd [16x16/16z] PSU5SKGn5C106IRV-DH_jJdc7Ln-_CsrTvpjDHDqt-Naf-edD6iDstGq9mndTpUZXGtGbRfQaWf9URZz0AgSnVMS3JlGdYTp8R00BxWzo5ujae1l3gxI3MSd

sprite $ItchIoLg [20x20/16z] {
RSq50e0W30NGJqoQV__JMiFscIpnJsGwYJYi-1A0oZTn_FBhqrynZCVfqoDP0F7TYJIdt-hzpru1eEjBhKs0HaQDuKAc_Msm4irqvZs6bUNuQgnWascnqTY4
kxxFixg8kZ9F8vQfjfY5dk-mgRoB-BK
}

!procedure ItchIo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/ItchIo', $name, $tech)
!endprocedure
