' definition of the Item fontawesome-5/Brands/Kaggle

sprite $KaggleXs [6x9/16z] uoSB

sprite $KaggleSm [7x11/16z] uwSc

sprite $KaggleMd [9x14/16z] unzG

sprite $KaggleLg [12x19/16z] uny1

!procedure Kaggle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Kaggle', $name, $tech)
!endprocedure
