' definition of the Item fontawesome-5/Brands/Mailchimp

sprite $MailchimpXs [8x9/16z] uwSI

sprite $MailchimpSm [10x11/16z] uwSh

sprite $MailchimpMd [14x15/16z] unzs

sprite $MailchimpLg [17x19/16z] uwSKZ08

!procedure Mailchimp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Mailchimp', $name, $tech)
!endprocedure
