' definition of the Item fontawesome-5/Brands/Mastodon

sprite $MastodonXs [8x10/16z] Ou03VX00KTpyd406FmCV4F8ZGoum2GPGcXUa7ggV4wYJWG4

sprite $MastodonSm [10x12/16z] JOk50S0m40A9Utx_RGlrYxm0-95D1C1k2ZjEKB6G-JbrlgjRLzUlhapvDxiRi4kuOAhbTlLnpi1o

sprite $MastodonMd [14x16/16z] NOs50S0m20G_xc7_ROlKBuBp-EDYNtjMhm7TL62mMUVpN1hIe4sR7rkFiT3OvHjfYYaMfL-q-piIKBNb0K-aIjMCeSN4niFOshTnuPo3SW

sprite $MastodonLg [17x20/16z] {
ROs54S0W40GFzx_-kmqoSHPVNh15M--zC-TJU17HuPC4f7x8sDhOE0CiW3gtaJIjQA14QB9q8V1TwXLUfuWap2tQKvHJvB94FbFEbW5yeo1yue7IZrDcT2n7
uXDsy3DIgpISkBFWbWC
}

!procedure Mastodon($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Mastodon', $name, $tech)
!endprocedure
