' definition of the Item fontawesome-5/Brands/Medapps

sprite $MedappsXs [6x10/16z] BSC50S0W0031colGFot-mfRGts1Dx2ma-tpbnYlXF4z00G

sprite $MedappsSm [7x12/16z] 9SN50OH0402m0Eis_LTxcazm9kRW91rYW_JlKTJ75cQtNPL0SF1m8I8EN1Tl

sprite $MedappsMd [9x16/16z] DSZ5WG90402mh9t0IF_LukGPh4hGkKuNFU5w6U7xGFG4Bh-_s9GsVeEMKrtrfaqQkOY9_Ky3J5Zn0EO3YAhD7G

sprite $MedappsLg [12x20/16z] {
NSo50KCX34NH-mMNj_-s9Q5-S28irr35NL8jNTsl2IE1CjiibtWwDIelsYcttrlpNByVik_dfdH4jHAPcIZ8Tzen5JX0qVkoP66c_OoCwHNGYJbisrUkQ71j
c0l-QR6S1m
}

!procedure Medapps($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Medapps', $name, $tech)
!endprocedure
