' definition of the Item fontawesome-5/Brands/Monero

sprite $MoneroXs [9x10/16z] 5Oc50S0W0CCo7zh_luK4gG4S8966AXzvL5B2lvNujHC7p7wsIadaX5U51G

sprite $MoneroSm [11x12/16z] 9Sl50S103CH0XVdKVxSnpCUuf7cYMRfhuDFT--5S_NBxEFFgogr6V1n4UphFBnWjC7ifuNvUm_EiO1k4skxm0m

sprite $MoneroMd [15x16/16z] HSx50SD034JH2ODW-kysmiq_wTbBwAuNd8JLlSNDHfi2Iby9Ro0n-jnYVx3zHT2IA0Kpf0L5IVQNvANe08lp4EMCDn5X5KFOU7eWah-gopmZ-W4

sprite $MoneroLg [19x20/16z] {
LSg54O003CNGu4xsdnPfqPorxpvtPS6tUZ4Q7rvzQluI3G3-gw5r-S2ie1EFB6WVLDuRK8UJAAvDq1f45PiaaoXTeGcQWuGA6eEQ987Q9Dgs1brF4Tgs8VAA
R3gwwJX7eFKNP_rNIgBYWPMdPZh_8ISx
}

!procedure Monero($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Monero', $name, $tech)
!endprocedure
