' definition of the Item fontawesome-5/Brands/Npm

sprite $NpmXs [11x10/16z] XSR10K00402W083RVre0Fj0hVyfRq511Y4PKndoljT14U3S3

sprite $NpmSm [13x12/16z] dSUr0O0m04N1Xpj__sbn8atikgE0FC1ELLTGLQA_eYkZll1clQZH-k3IjYqH9m

sprite $NpmMd [17x16/16z] jOo35S1044Jdx9t-gutz6FqryGVr2it0xaobGWC16PnDpfUXmR4nEfjzs1fgQxJ6DZJ6q4Ha_iJn-G96x02UqmC

sprite $NpmLg [22x20/16z] pSZ50S0m40D1XJdglzem6Z-cCTuY0RKIEM--z_5fiUa6R9ePfwCosokFEjVbRA-Tik9RJrlb1mxTyHNbvGR-hG

!procedure Npm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Npm', $name, $tech)
!endprocedure
