' definition of the Item fontawesome-5/Brands/PennyArcade

sprite $PennyArcadeXs [12x10/16z] VOe52i0030FJkT__Vxk4eRChq9X-AGxyPc15uNha_4gJVvkWwPKjODtcXqeYFJa1

sprite $PennyArcadeSm [15x12/16z] ZS75OSDG00KmcVtnxJzjczn3aj_iCy3PnkW55vAqLJsjmWm6bsuDYVssit777jPCiiw4aBIIfqPpPRrQxsM3TdZh7m

sprite $PennyArcadeMd [20x16/16z] {
dSx5WG0n30F0MOOuKV_L7kDtvsrByiWq-M_hgVYotzLxvS1-m9ftvtA7cM19xXba4QuY2KOOp4WcoKM-lXeIUmgMN8p3L9-F90bpvGDNHvAHJuLhiLNc_MfL
xLny3JmcJxm2
}

sprite $PennyArcadeLg [25x20/16z] {
jSrLWaGX30NHGWODkVlVxP1n-Uq-puKAprF6QVpJ9EqYGaXjsZd7t5wul4COUhUaHaWYkAGp2fSTg0ay5cwfyY7gQq6LWxy7JjoN3ObBKdu_OHQf2FRotgT9
DncMKfo0wXAW2MbBUfypf01CYxoab9hfGmSYHTDFJX3KwJEtiSnihnXFq3NXlrnvY5S
}

!procedure PennyArcade($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/PennyArcade', $name, $tech)
!endprocedure
