' definition of the Item fontawesome-5/Brands/Ravelry

sprite $RavelryXs [10x10/16z] Oq06_200Pa00Y05ZGcJWB7uC5ZStJ0kACJmC3

sprite $RavelrySm [12x12/16z] Oq03_23036Any4C0DmC38uY6oe19PcOG1MQ3z23O_7ZOl50ZeReuO4mmu0Eok80q

sprite $RavelryMd [16x16/16z] XOs50G0X54AnM_UVrhuEd_aBy0PF3Rs5QODjuGRRmWt0zDVxr3y28zpdzfY9QzoUTUpWsXCu7_7DtmAWH-ZHYJDKc12xHmK

sprite $RavelryLg [20x20/16z] {
TT254OKm44NHnI4hh_zgln2tEyOSuZJlCW3sB5aEn2IIGv4VogZwqrs2dxwWpI_cPvnXoad5Ai6ui5CK_xGm-8Oc0xk8Erjeyn_CN5n4KKV_QjheJMhohUtp
URqSkvDyNm
}

!procedure Ravelry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Ravelry', $name, $tech)
!endprocedure
