' definition of the Item fontawesome-5/Brands/RedRiver

sprite $RedRiverXs [8x9/16z] uwSI

sprite $RedRiverSm [10x11/16z] uwSh

sprite $RedRiverMd [14x15/16z] unzs

sprite $RedRiverLg [17x19/16z] uwSKZ08

!procedure RedRiver($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/RedRiver', $name, $tech)
!endprocedure
