' definition of the Item fontawesome-5/Brands/Schlix

sprite $SchlixXs [8x9/16z] uwSI

sprite $SchlixSm [10x11/16z] uwSh

sprite $SchlixMd [14x15/16z] unzs

sprite $SchlixLg [17x19/16z] uwSKZ08

!procedure Schlix($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Schlix', $name, $tech)
!endprocedure
