' definition of the Item fontawesome-5/Brands/Servicestack

sprite $ServicestackXs [9x10/16z] Oy06-BbW37v-L1OBFoClXCKF0YmC36pyO00LOEU76m8

sprite $ServicestackSm [11x12/16z] TOgr0G0X0CJkNP3iFoqk5QbEeXMVdHck6J4bt2LN2VJ3MIFkWnRnHTd9FA27ZYOH

sprite $ServicestackMd [15x16/16z] XOor0S0m30HbXSct_xHch7BTe_noc4aQx6G0vopvkho8575V8XzWMzVA1hnPMc1NO6sITwjp4jy7M_iDVI2hXcZ7gCgC1m

sprite $ServicestackLg [19x20/16z] fSw30GHH34NHPEpJVxLh6_SpVl4N_LpT-P0thWdzjQi2Lwu2jyNLZM-QcuZ-kXPT55U-6Qg4uK83VLwaBS1OdNpfm32Yl4X2ZV7K2ImBefulQJSdFc8D

!procedure Servicestack($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Servicestack', $name, $tech)
!endprocedure
