' definition of the Item fontawesome-5/Brands/Skype

sprite $SkypeXs [8x9/16z] uwSI

sprite $SkypeSm [10x11/16z] uwSh

sprite $SkypeMd [14x15/16z] unzs

sprite $SkypeLg [17x19/16z] uwSKZ08

!procedure Skype($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Skype', $name, $tech)
!endprocedure
