' definition of the Item fontawesome-5/Brands/Stackpath

sprite $StackpathXs [8x9/16z] uwSI

sprite $StackpathSm [10x11/16z] uwSh

sprite $StackpathMd [14x15/16z] unzs

sprite $StackpathLg [17x19/16z] uwSKZ08

!procedure Stackpath($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Stackpath', $name, $tech)
!endprocedure
