@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-5/bootstrap')

' loads the Item which embeds the element StumbleuponCircle
include('fontawesome-5/Brands/StumbleuponCircle')

' renders the element
StumbleuponCircle('StumbleuponCircle', 'Stumbleupon Circle', 'an optional tech label')
@enduml