' definition of the Item fontawesome-5/Brands/Unity

sprite $UnityXs [11x10/16z] NSZL0S0m203HIm8_jTj_she_7FxKOoaoMO4gOF7QZjn1FJvOaMkFYPrZR-6G2Wi

sprite $UnitySm [13x12/16z] RSYr0K9H0CNG_EUU_QV5eU8qL_WZw-4jQDVFUu75NmzYXlJi66W5VEFD1bXPatS1CVAq6-mb7tgKd-A6Em

sprite $UnityMd [17x16/16z] TOs50GCm20JZdjp-snQes-FwxZ_2vhnK69uD6E7Pg2pnYK2nkh0rYETOVGrTzXUsIL8mb4WtxtWXU8JoJ8t47LvtG8aCVk-idKfuUSJKnq-KToQ3dqFy1G

sprite $UnityLg [22x20/16z] {
ZOy55iCW40KtI7HXxd_RlW-HUZjHvgtQ7-IL-KcjYFBgAd0l1vZCPCEX4htSY2zduI0fG3btaQ8D08-HNJYXHx8sAaddJG6LYvOQRDSnY0M5JTYXZxgXlGvT
JMJACSDzDCIaY1qldllQJhOxW18sOBYtyNwyUxAasojXJlhS
}

!procedure Unity($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Unity', $name, $tech)
!endprocedure
