' definition of the Item fontawesome-5/Brands/Unsplash

sprite $UnsplashXs [8x10/16z] Oq00Vdv-59gLbHL54an2QPm

sprite $UnsplashSm [10x12/16z] Oq06hFpy_3XPc00emmsXK5cCZ8pys04V7

sprite $UnsplashMd [14x16/16z] Oy00Z7mW0EVnWm1U7fmB0fZciGC16vm5qW4n7CGYnEFd105-aW0Z2W

sprite $UnsplashLg [17x20/16z] Oy0EsC40mMVY1mEA11XOmO21EC030bn8RB1fl101C9j40Pe13AS3

!procedure Unsplash($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Brands/Unsplash', $name, $tech)
!endprocedure
