' definition of the Item simpleicons-5/C/Cairometro

sprite $CairometroXs [10x10/16z] DSR50O1G04EnntShtNzQd9p2hV7ntnWsekvuDmWy9eH9gyWEDe4gtm8WOwnxWY1pgm7W1

sprite $CairometroSm [12x12/16z] FOo50G0X30FpYgLa_sbnkBfYu778roeauNeazjm5GpIE_8vsHKijpv20Htgykrkkkna8zsYIBc0cyyySpvpaWqG631mlD2e

sprite $CairometroMd [16x16/16z] {
LSi75WGX20FGM7Q51qFkVzj1fyVwzGLd19_GduTQQpIOvBdegkrVYwXoMSU60fRXfoMWmj9jERgx5tZ6163xaGJQt4soEytAQH33qsUIW6otewHhEiiMgt0Q
Zjjv6d1xPZXOyCguldO
}

sprite $CairometroLg [20x20/16z] {
PSe7YWKn40FHSi8zeQtxttO5Pd-Q8WWUubNmQEc1ba-yCdD5fIXT1vUqHXsbKrlBiQtDQ0icPxzV9hKbYPDh6wl46OA8F5O6Jd5UruMhNcHSGSf1twEOOfkg
jbLXjBsYgs3yj2fm-M-Nf1mlMvZujNhpPGvNlThMnnWXhuOhl9ggujKBNuy_
}

!procedure Cairometro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Cairometro', $name, $tech)
!endprocedure
