' definition of the Item simpleicons-5/C/Chartmogul

sprite $ChartmogulXs [10x10/16z] uwS3

sprite $ChartmogulSm [12x12/16z] unza

sprite $ChartmogulMd [16x16/16z] un_X

sprite $ChartmogulLg [20x20/16z] unzKO1G

!procedure Chartmogul($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Chartmogul', $name, $tech)
!endprocedure
