' definition of the Item simpleicons-5/C/Chrysler

sprite $ChryslerXs [10x10/16z] uwS3

sprite $ChryslerSm [12x12/16z] unza

sprite $ChryslerMd [16x16/16z] un_X

sprite $ChryslerLg [20x20/16z] unzKO1G

!procedure Chrysler($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Chrysler', $name, $tech)
!endprocedure
