' definition of the Item simpleicons-5/C/Chrysler

sprite $ChryslerXs [10x10/16z] Oo0PiF5myt6nyF9mSHEh0m

sprite $ChryslerSm [12x12/16z] Ow08CBEmCO8eDWOs7cvkFdOMBZukRXvAJ0G

sprite $ChryslerMd [16x16/16z] lS450S1030ImUoY3VxS34qqmxcw6NfYSIm1dH7JHbIwFIFp8dL8F1hm

sprite $ChryslerLg [20x20/16z] rOf70S0m4CESvFRYpxQ3HMjBF-6VEpZh4RmMRzw0L6NcJ319JqLarjknHNReeojjV7ut

!procedure Chrysler($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Chrysler', $name, $tech)
!endprocedure
