' definition of the Item simpleicons-5/C/Civo

sprite $CivoXs [10x10/16z] uwS3

sprite $CivoSm [12x12/16z] unza

sprite $CivoMd [16x16/16z] un_X

sprite $CivoLg [20x20/16z] unzKO1G

!procedure Civo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Civo', $name, $tech)
!endprocedure
