' definition of the Item simpleicons-5/C/Cloudsmith

sprite $CloudsmithXs [10x10/16z] Om03DXu6263bv-U7iFXXB2ueWnzP2ggS3yX203W7ePIJdv-T0G

sprite $CloudsmithSm [12x12/16z] JOg35G114CNENFHVxLXv-iYYhDC2npbNovDuFFlUP9NuKshbNunTihEnk7lhvPl4vfRi2

sprite $CloudsmithMd [16x16/16z] TOt50O1G34E3E-m_BV2z-cvj39Np0kNv6TfvF04YM_U2IByTzDpYqN7hBABmRzmaJLq7EQyGcaJ90NSKUUG3

sprite $CloudsmithLg [20x20/16z] RSz50e0W443H6QNp_gUb6_vA7mrBp1iuiZv5DgA-j9chXglvUzvVoKr1TH1j__J3JlZOIMGuRYOV5oFThjjIs2DAvXEvv73qsC4Mi_1-xsttDOzJL2ALFo8

!procedure Cloudsmith($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Cloudsmith', $name, $tech)
!endprocedure
