' definition of the Item simpleicons-5/C/Cloud66

sprite $Cloud66Xs [10x10/16z] HSR50O0m0C30u4xsdnRglTSHZKHMADl5hAVLqUmw8IXAt-KqEe792J2em0y

sprite $Cloud66Sm [12x12/16z] JS65OGD10C0m_p5x_sdRS2Bn47ZOlWKC--IhZXODnZD36gKLv_uwFveA5gQYAI0iHJ5uYHNS8FG3uCFa8QeNy0y

sprite $Cloud66Md [16x16/16z] {
NSU5WGH13CH0sKl3oZ_Qn-CoDZV9dQzWkdvh-NSJ-_BokXnHF4r7MyVQTyjMUhNxZW_BTqKrGA6hg6Us9RrvoqH1haGheLb4x2XmEI4ye1e0ftV1d_3Fu25r
1R--0G
}

sprite $Cloud66Lg [20x20/16z] {
RSU50SCm4CLGnP2OjV-sPUux_3m5NgQprZRLNajR1WX-WsvF8shEHe-MYn4DYiVi0rDnjmKDOp56IOjUompQ_9N_g7zClLYrg-CIjNWHuL2WgswgbR4qCPSN
g0PWaxDTBPSjs93TW0ge4JiI3Lp2sN82sGPKArpeI-Ek-P1vslHYy24DAtSd
}

!procedure Cloud66($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Cloud66', $name, $tech)
!endprocedure
