' definition of the Item simpleicons-5/C/Codeigniter

sprite $CodeigniterXs [10x10/16z] uwS3

sprite $CodeigniterSm [12x12/16z] unza

sprite $CodeigniterMd [16x16/16z] un_X

sprite $CodeigniterLg [20x20/16z] unzKO1G

!procedure Codeigniter($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Codeigniter', $name, $tech)
!endprocedure
