' definition of the Item simpleicons-5/C/Codeproject

sprite $CodeprojectXs [10x10/16z] uwS3

sprite $CodeprojectSm [12x12/16z] unza

sprite $CodeprojectMd [16x16/16z] un_X

sprite $CodeprojectLg [20x20/16z] unzKO1G

!procedure Codeproject($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Codeproject', $name, $tech)
!endprocedure
