' definition of the Item simpleicons-5/C/Codingninjas

sprite $CodingninjasXs [10x10/16z] uwS3

sprite $CodingninjasSm [12x12/16z] unza

sprite $CodingninjasMd [16x16/16z] un_X

sprite $CodingninjasLg [20x20/16z] unzKO1G

!procedure Codingninjas($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Codingninjas', $name, $tech)
!endprocedure
