' definition of the Item simpleicons-5/C/Codingame

sprite $CodingameXs [10x10/16z] Oo0PyB6nyV4pShBnyX6h0m

sprite $CodingameSm [12x12/16z] Ow0Iu6FaukJcO6JdvkHbeiGS

sprite $CodingameMd [16x16/16z] lKW50G0m30Bksh_jhSEtuR2-VbXqx5sOcBsaCgZZzQmY1C9HlEdtRG

sprite $CodingameLg [20x20/16z] rOO70OD054EJst_xLzi2AY3puOEY3uArEUo2HoUnpfACAdQH9U699aqWyuhCFJc6uFNw0m

!procedure Codingame($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Codingame', $name, $tech)
!endprocedure
