' definition of the Item simpleicons-5/C/Commonworkflowlanguage

sprite $CommonworkflowlanguageXs [10x10/16z] Oq05_Amm1Zj23C5YXp7OiCdomHXmCLOm2m

sprite $CommonworkflowlanguageSm [12x12/16z] Ou00DWOuuEU7C_duCOGnEVpi22QICRmur3FpCyAOZ60cp0KG9G

sprite $CommonworkflowlanguageMd [16x16/16z] VSp50S104090uXxwh_RSRLwhm3kHEVdaxJjeiP78BENWvv6sRzdkIAtb-yP_cFVm7BJO-PLvi2G

sprite $CommonworkflowlanguageLg [20x20/16z] ZSZ50O1000InnPtflrfSp_ECNgKi1JYgigjnbMc2p9LAoHoQfAfboA2JnPMvAs4sQsOq2p2hWa99MPFhiW8

!procedure Commonworkflowlanguage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Commonworkflowlanguage', $name, $tech)
!endprocedure
