' definition of the Item simpleicons-5/C/Countingworkspro

sprite $CountingworksproXs [10x10/16z] Oq06_Fny_106DWAiW1_4W2hYP8BfuuEPm0kIWs9Me6f6a0u

sprite $CountingworksproSm [12x12/16z] LOh55O1G4CG6Tz9_jxpWFuVTiPHK0EsbgJsHVlDEYtUS8-qrDu0zeQUAx7Hx7c3wz9KFNc8nu1vduDbo

sprite $CountingworksproMd [16x16/16z] {
RO-54GGn2029Asp_rPxb_I_23WvoToP0Vwb65UdCXvhn9o9XwUY3uy6sEFJJtrMdkzJ48Z1F2FLLkJhSGNcSWIAV1txqzD0B3ucjIkSGxb0yZ6gOrwQmre4W
1Sw-Em
}

sprite $CountingworksproLg [20x20/16z] {
TOu54eKm30LV25xP-v_sIwQ3ivMuw1Kl0AiEJ42kW3OwyBzS3ivDJGoRhsm5QTEsvjIc6AafxjT-3e259ysjsD9QO98AMQ0DyB0DRJXreTCPgEX2Ul0L1kQc
JtKA2G8BTOIG2wl6sCWMy47gKeG626maq1-R2pboAtcKz0K
}

!procedure Countingworkspro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Countingworkspro', $name, $tech)
!endprocedure
