' definition of the Item simpleicons-5/C/Coveralls

sprite $CoverallsXs [10x10/16z] uqS5t70M0ngBXm4Cm1m80moG6FmCl10M12C

sprite $CoverallsSm [12x12/16z] uySB6B2pcHXueM9Gm0JYi86PF10PPZ0JfegHWH76vkFdXfh40IPvKMq4

sprite $CoverallsMd [16x16/16z] ZOo53S0m30IlN9Ey_xHbZ2WdVCnA-aBpbsEXuHceYWWW8gfdTd5tnajwNiGXtxUfq830-Ehzw2s8dRTPmGe

sprite $CoverallsLg [20x20/16z] bOw50S0m20G_hi3-qzRTUr7yvJVbmeUpArtuDDAv5EReoi2ck6BFu6IryNYPy8khdkhrOIfmc5mmSaWp_KKxNnv6gQtWyQMjxEN7yeCM

!procedure Coveralls($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Coveralls', $name, $tech)
!endprocedure
