' definition of the Item simpleicons-5/C/Crunchyroll

sprite $CrunchyrollXs [10x10/16z] uwS3

sprite $CrunchyrollSm [12x12/16z] unza

sprite $CrunchyrollMd [16x16/16z] un_X

sprite $CrunchyrollLg [20x20/16z] unzKO1G

!procedure Crunchyroll($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/C/Crunchyroll', $name, $tech)
!endprocedure
