' definition of the Item simpleicons-8/M/Metrodeparis

sprite $MetrodeparisXs [10x10/16z] 9KY30G113ClZZEm_RTqOTeF53JmkmuYuKd4YCrSw7aRgPiLIV0r5vWwxg1zVL0iA

sprite $MetrodeparisSm [12x12/16z] 9Kk70O0W0CAzvVzlWwHK9ep5ZWSU85p-z3c1fcN-JZmuQjkDuD9oRcqY9iLLlJkYzIXU2F43YcEQAqq9Wk8ACCEOn_VcReToFm

sprite $MetrodeparisMd [16x16/16z] {
DSk53S0m4CLGboaNxpzjuKkry1sGbl8Q-2lxiL-waMoamHwk_FM2tbWaQt10kFAf8ujB_op4MCVhSi4Mkt-UHUApFgED6ED5Ve-V8MxPJ6EyCmYq3kdb0d2v
XYtCF1N00m
}

sprite $MetrodeparisLg [20x20/16z] {
LSo7bKCX34JH8VueNl_TxX62jJta2qWhr-1j-ae3p7nAcy1YK-3QbBHpSWVzbka-9JNAX0VfHi9yppJ84fUGstmufhrSov0IvfOODgrIV7OJX8aXpXps4bOn
jAmj4vnX7T72AWhZrKkO5EOZSQiSYbmIIEgSsbaadJnR4kJO5J3VTY0adivOFFe3
}

!procedure Metrodeparis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/M/Metrodeparis', $name, $tech, $desc)
!endprocedure
