' definition of the Item material-4/Av/VolumeMute

sprite $VolumeMuteXs [10x10/16z] Oy09cE0CVWZD3mGuM50E3fC

sprite $VolumeMuteSm [12x12/16z] Oo00615CNcOuauyVnkO70jni6E00iX4SPZps0G

sprite $VolumeMuteMd [16x16/16z] Oo0RiADn-T6uI7nUNbv-P3wGGnAVcPaPmaS0HXWV8O3cFYQYV04

sprite $VolumeMuteLg [20x20/16z] jSYr0O1G50F0PxXa_scH1WlLbojFIb4k6waST8RtcLdWSpZKkzjo7YUVB3ydlMJR0G

!procedure VolumeMute($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Av/VolumeMute', $name, $tech, $desc)
!endprocedure
