' definition of the Item simpleicons-14/L/Libreofficemath

sprite $LibreofficemathXs [10x10/16z] HKk50G0X2BnFM_UVrY0Dk0J6Fdkq0mWI8cXeK0pFyv0R-uL2w1atAg6VhZSSnGK

sprite $LibreofficemathSm [12x12/16z] LOp50O100CE2Ezb_MlJqLI_iggYmQX1m64NcaddiTCTn_BmzROXRt2BtL4DdrytzjFuPChy1

sprite $LibreofficemathMd [16x16/16z] XSg53G0n509GE7VsdxPEayQEwli1W4gmAyNq8DlXFbhSxDuOBTh8UUJ-waBnz28tQQisrJsb3Kxs-qfFslRpI7VQd_lEhsz4

sprite $LibreofficemathLg [20x20/16z] {
ZSs50G8n44JHEOtlxxzRzXo7YR-OfC2MKUlGd2hSusfmXw_c-6gEh-RuQewdMLk3usaQrjIxFqoqJ8JJ-ZWRdQHo6TBQTTpP4A2NLEyCWpepSbcS8SyujzDg
WURDYfrsb_yjkesFPD8D
}

!procedure Libreofficemath($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Libreofficemath', $name, $tech, $desc)
!endprocedure
