' definition of the Item simpleicons-14/L/Luanti

sprite $LuantiXs [10x10/16z] 1S474S10300W-dlbujzj0G2B190K7Bg2JtI26d0oPInd8-hLOIPkdmZ0nWy

sprite $LuantiSm [12x12/16z] FSQt0S0m300Wt9lq_xlPmWGUWCdlO1l_SSh5iyHLdmTezPMqSMybijVQ1vIMHxim7iU1eHNSvR41Gy07

sprite $LuantiMd [16x16/16z] {
HSlNGKKX44NHDSmZW_rtQzQxlqw4ZOSHiZwsGPWLZtynm-CnTYo__oRxL0Ehb0cR4jDjee0tvSKr0rRsHSqh7TaEt1YthIKsADcSvfK9h2cKRXgO8HUCqioi
z00SoEQVs0xm0G
}

sprite $LuantiLg [20x20/16z] {
NSYtbIKn300maFgo8xxflzkBRXr2WCTVEysERx70--k0Tus-_XwSzFVYlB4IpWUhS_Cg3MQl_c3U85tYKZgeb5exjSFQ2SuZLcf50QU_Nhojq1PpduOudpmL
gpXt3w2YHGMjsO3KnTDL_xevNwwei3N8pLuJsgERKo4AOArau8Hl5tRtIvpS0Fy
}

!procedure Luanti($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/L/Luanti', $name, $tech, $desc)
!endprocedure
