@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsApiGateway element
include('elements/aws/NetworkingContentDelivery/AwsApiGateway')
AwsApiGateway('element', 'Api Gateway', 'an optional tech field')
@enduml
