@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsElasticLoadBalancingClassicLoadBalancer element
include('elements/aws/NetworkingContentDelivery/AwsElasticLoadBalancingClassicLoadBalancer')
AwsElasticLoadBalancingClassicLoadBalancer('element', 'Elastic Load Balancing Classic Load Balancer', 'an optional tech field')
@enduml
