@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsVpc element
include('elements/aws/NetworkingContentDelivery/AwsVpc')
AwsVpc('element', 'Vpc', 'an optional tech field')
@enduml
