@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsVpcFlowLogs element
include('elements/aws/NetworkingContentDelivery/AwsVpcFlowLogs')
AwsVpcFlowLogs('element', 'Vpc Flow Logs', 'an optional tech field')
@enduml
