@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureCostManagementBilling element
include('elements/azure/ManagementAndGovernanceServiceColor/AzureCostManagementBilling')
AzureCostManagementBilling('element', 'Cost Management Billing', 'an optional tech field')
@enduml
