' definition of the Item simpleicons-7/J/Jitsi

sprite $JitsiXs [10x10/16z] Oq07h1WYd0mSO1f8iSF4E13Ak1bOG0Bid301BWQe1YQe

sprite $JitsiSm [12x12/16z] HSYr0O0m443H5pb1zf-NZbHV001WEne0wcpfdS1W-htR098Gu7Op1iHQM62jPKnW0VW

sprite $JitsiMd [16x16/16z] PO-54GD020JtSMBzTnitvdS4b-F7Of8CberGaD4iDU9WNVAld1Wu0zEF0zMmFXyeuDXV9wxsQVSM0EGTBqNc_m48xEowRW

sprite $JitsiLg [20x20/16z] XSYt0G8m30J0axCD-yzB9p9Syy5VtPju_rfftbnvDcCOdctcgkyVMuf5cuIKlNcoTYUGMaGHGvCwNDZv5SuAI6jD6wY0K0tGGduEM5BeQaGBKXJlfcSt

!procedure Jitsi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/J/Jitsi', $name, $tech)
!endprocedure
