' definition of the Item simpleicons-7/J/Justgiving

sprite $JustgivingXs [10x10/16z] FOgr0G1120HVphN_Qd6OPFKX-iqFSuNgvcZr25rDpbagkHHsvt0H9Hy5Ffj1

sprite $JustgivingSm [12x12/16z] JOk54G0n40BttP_-kmsPs6ta123pwAIWGcYtrZvkIpzHUAhpDsxlvZpzQgjS5k0ilVbKl6fWlXA41

sprite $JustgivingMd [16x16/16z] NOw50G0X30FRT-jd_sbnWXnQZoHsmwjICMIER8BCPaksDvWjB6Hl9jDjwlCq4syuVpEXhNv9t-mDfYBP1n96IOR69O6FvXaiLgOnuW4

sprite $JustgivingLg [20x20/16z] {
POy53W1120FPSwFy_xLdq0Io4n-q4komQvR4R84sAakilJfxXRhhEi4kAJFP7KNjl-DF3lvThc29ewgBVQbhuJu54DhlQdu2eYa08pSBr09-IFZhKTGOxvSk
iiLARte
}

!procedure Justgiving($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/J/Justgiving', $name, $tech)
!endprocedure
