' definition of the Item simpleicons-14/C/Coronaengine

sprite $CoronaengineXs [10x10/16z] 7Sc50S8040J1mObk_zKYRwUmz0H3vqAqnCDJpIs0ctJ5cIbDTwhUJraukzdm2F45

sprite $CoronaengineSm [12x12/16z] 7Sg50SC040B0YtlOVzeAhnYuijCgU5B8CEYFCP7msFk7t7AXjLZZ2fhTpSLNx6uP39vN14bMoqQqvXUUhEEUZIy

sprite $CoronaengineMd [16x16/16z] {
9SU94GGX20NHTWUP4ph_RBSi7-U7PPRl0BQouiWsT_HYwmBmW3UU2dW_g8kVoXeSo7v3FuQp22TB3R224MmLj3zqn_IYtqGl5fquckd7pY12FUDvaoV9vYoW
LO4rzGBt4u09y3bOSaSOsgqDy0S
}

sprite $CoronaengineLg [20x20/16z] {
FP050iGW3C02KpJ_V-qfQpQith8eqtu2mQ6ZbgOZiT37ObgMQ11irX1DSz43-6w7aDM6ElzlJr13WpV2hHKW_LASbfKWae2pGgqyA6WXQuxw17iZgM4cU0eX
sxI02CSZknJwO4oeedfp9Z2Jt21bltIW2nHNng-I9b-g1m_T72CzbqI2sn_ZR_G6
}

!procedure Coronaengine($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/C/Coronaengine', $name, $tech, $desc)
!endprocedure
