' definition of the Item simpleicons-14/T/Tricentis

sprite $TricentisXs [10x10/16z] HSY53S105CDGgyAYzz-s1nyYUZ70HUprHITmx9r55fY5YSK6JXmJRau4dOSV

sprite $TricentisSm [12x12/16z] HOi74e104CAmT_F_tpeiwdL8PkNLI-eg2GPrK7c36OwYBexEQ4zCMH8zThLuYcIFGShk-1NTq8m_3Zq

sprite $TricentisMd [16x16/16z] LOs54S103CE-nqNjFsrPliIFScWKJVc0zok01rd_D3wjIHPD7c8CCKRqTjuxRY7dfaIC8K9hM3FWUEz5ux3m0W

sprite $TricentisLg [20x20/16z] {
ROy75e0W34CPRyh8_K_hIckg4YV_VMYRB1i_EIaDxKR0WmQ0SIF1Uz7u9g7133yB1cK1XB84QLbWqAnenkYiBsfBg-5djN1cSGi1LhSGJI51ekfzwip2YTHJ
HUL45pe
}

!procedure Tricentis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/T/Tricentis', $name, $tech, $desc)
!endprocedure
