' definition of the Item simpleicons-14/T/Tauri

sprite $TauriXs [10x10/16z] 9Oi50W0W30BjLlx_MmUxTH38Ua54l06myzJLNMX62M1XJx2q7Tgw9ri_dfVhYTKF

sprite $TauriSm [12x12/16z] BSY5SGCm44N1JSnqh_zg3Hhjm0VBlIExDGKE_Qt3zazNzAUEdj6JIymebkZVeuD3i_lHND1OJj03awKg-

sprite $TauriMd [16x16/16z] {
JK-54S0W44EBa_stBMy7gNsiW5DqJ7UnmJ0AhFEk9ZHK_WOJc9nd2b-RAg00gS1KxX5f8j7jCpREL6UWp8OEz8uo9c3GzBdNbmr7KXa-ymS8-hsxpscn_9vE
vXy
}

sprite $TauriLg [20x20/16z] {
LOu55eGm30LJj3xtl-rkBQ63Vtk84gbUlhXA9tyaeBuUG3KeqgdKAINhmBjjkl_jMMtVdcL4fWQCUr4DkCOZB2slXVDeDrY60h4PxOykKfTAJmJY6FCY1-1s
hNMQDBjll_j3LqKvxl6iAaQpWTPn6Mvji7Z5y3Ioay4F
}

!procedure Tauri($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/T/Tauri', $name, $tech, $desc)
!endprocedure
