' definition of the Item simpleicons-14/T/Trove

sprite $TroveXs [10x10/16z] Oo0QyFDpWoXs48iJI31mS8C00vZ02m

sprite $TroveSm [12x12/16z] fOO50G0W0CE6E_HFYoL0hkDIGY10RYI0R-JMK9C55OkS_j

sprite $TroveMd [16x16/16z] jSUd0S0m44MnvzxlxpzjAWkEnSHcKsEiXQbNLvmCCRhvW5ZYlIi8qJroVAnNPRtusGa

sprite $TroveLg [20x20/16z] pOY70G8n4CFaX7A5nFjFIsS6NbSj3aHKKNM5Iuj4CPwYmLZTcCrYNdcxlJ7adElfxBUJoHi63sQ82yIp488JAA9_3EhtwWVe1t_Y0G

!procedure Trove($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/T/Trove', $name, $tech, $desc)
!endprocedure
