' definition of the Item fontawesome-5/Regular/ArrowAltCircleDown

sprite $ArrowAltCircleDownXs [10x10/16z] LOcr0G0W40E3qzt-q-Bw4bKVfp4H4WoXFenRVvHB0iWZw_9h9os4KLS

sprite $ArrowAltCircleDownSm [12x12/16z] DOY50S0m0CAO-_Z_suPAAa1KMTJvRUwPwayZ_jGdOvM9gNyzmClF5uZuaphrpg3k9jN8_lXYTy5gY2W

sprite $ArrowAltCircleDownMd [16x16/16z] {
JOk74GGX4CDCl0Ie_sv_p7uIKTwnWbJqex1P2YQhIZgXXNO5WogLhTSJ8obgY-I7IzG_doJqvoV5pcP83R5ZawGBSJe8rSBRmTPCbTnJW6UT6PP1fi8ysxMi
mOMf_hu
}

sprite $ArrowAltCircleDownLg [20x20/16z] {
PO-50SGm30CLvcZ_QHySFVPAweLil711GRXEO-UtodpGok03gKOMpP-arooyAVRZfCP8Pz42kXQIJLyFJNkxp7Pnu7Rl-0d1jgEebi41eCevEU98AS-9RGb5
2eqP-U5jvb5dtRjRgVokGb2hF3Necwd38aMMiHcRv9Iv0m
}

!procedure ArrowAltCircleDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/ArrowAltCircleDown', $name, $tech)
!endprocedure
