' definition of the Item fontawesome-5/Regular/CalendarPlus

sprite $CalendarPlusXs [8x9/16z] uwSI

sprite $CalendarPlusSm [10x11/16z] uwSh

sprite $CalendarPlusMd [14x15/16z] unzs

sprite $CalendarPlusLg [17x19/16z] uwSKZ08

!procedure CalendarPlus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/CalendarPlus', $name, $tech)
!endprocedure
