' definition of the Item fontawesome-5/Regular/Calendar

sprite $CalendarXs [8x10/16z] Os3WPs1W1c8GpShFm0y3d6303HG50LQ2D1SOy08

sprite $CalendarSm [10x12/16z] Os1WvcTWO01X1dOm2qHZ0MmC4C172OiNRXm

sprite $CalendarMd [14x16/16z] Os1WuEHdX98WmCFF32UvUVZvUNbum2GRBpy-m8m0G1u30j2TnuxYBW

sprite $CalendarLg [17x20/16z] Om02Vdvc4CN5pm4a8GAi88gNdnkR01C_Ak3Z9m9m8WDUe003Ck0SKWBSN4Y0ZvyPFJm

!procedure Calendar($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Calendar', $name, $tech)
!endprocedure
