' definition of the Item fontawesome-5/Regular/CalendarMinus

sprite $CalendarMinusXs [8x9/16z] uwSI

sprite $CalendarMinusSm [10x11/16z] uwSh

sprite $CalendarMinusMd [14x15/16z] unzs

sprite $CalendarMinusLg [17x19/16z] uwSKZ08

!procedure CalendarMinus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/CalendarMinus', $name, $tech)
!endprocedure
