' definition of the Item fontawesome-5/Regular/CommentDots

sprite $CommentDotsXs [10x10/16z] HSct0S0m4CGmE6VV_jjANmaiYI45Qs0AGSapMLszV4JrZokhahd_5DwiA0q

sprite $CommentDotsSm [12x12/16z] LOt50K0n5CAeUxF_jDyrbwU0_fW1bAETLCbsiiJK2LdeXj4qZQPoENgCEFhlpqyxkYj6hbDaW7vbkMvrim8

sprite $CommentDotsMd [16x16/16z] RSw5OKGn3C1GVGh7sd_QzfXV66r-MTA8jd6pUJCvgyRrAEi6nS9T27QUDCkBmn0C-dN0ALZPhmEkygA9lkJbOB6_90QhspRsSyvX03gzsO5G3rZNzVu7R_u1

sprite $CommentDotsLg [20x20/16z] {
XP030W0X402pQ_x_shCvkVMA3unpLXq_72jIp6YWHUz21l9i1KKiI63MCc8dZP_prquXIAeu0taCvGPL6OTt71xCFcSVGOJnagdhNq89nQ3SiAIRlt6UyEHX
jLFT82y9Hb2plQv-k4aJcHKoeRAHzpPPdsijqQxbZUh_z
}

!procedure CommentDots($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/CommentDots', $name, $tech)
!endprocedure
