' definition of the Item fontawesome-5/Regular/Copy

sprite $CopyXs [8x10/16z] POV50S0W54DVY_l-s_BbI3p04KZHIHnvqby--cd3c_Gsu_k-8jtQ4NM1d0i

sprite $CopySm [10x12/16z] bSUt0O0m4CNGJyve_ssnB_MyIb93SrcS-mwFfecXdNZ0gbdLgdb_r8DRrHoxzDH_

sprite $CopyMd [14x16/16z] hSk50S0W40F0jBXc_sbnMO13tz0bTWb3u88kSbuaV8nSqSS-ig9XTK88SQFkOMHu0VY5aDH2WATBu7RDR0K

sprite $CopyLg [17x20/16z] lO-50GCm20H9gX_x_QUjeHFqeZZ8ZqNbAigXSrS5-RqtcsfI8PqKVd6F1kwgK2Aa0zYfKF1VHJEcAXOJzRu3c5m0IlXLHoVdKBOgBapaoni

!procedure Copy($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Copy', $name, $tech)
!endprocedure
