' definition of the Item fontawesome-5/Regular/DotCircle

sprite $DotCircleXs [10x10/16z] Om01PWOmOEFdP-Vd1pF0V7umWZ3177uGmSmEPi75EA0ik1OO0oG9LWW

sprite $DotCircleSm [12x12/16z] BOe74e0W40DZx-x_Vylb9gj0cff5uOVwJqi-ASzlQLY5NmycMaFVorzfT7AYmquDefcahowdkuELmi4

sprite $DotCircleMd [16x16/16z] FSc5TSGm5031CHxAst-ruMY4-xvVoyQqzUFoQtJjkDS1xqxy_dQscOpeOkgX7Ni5eoMe6hYtpGvdPZ_nI7SOtydLzvxMTdhFBXoD_sbWht4_7bVnwz6t7Ju1

sprite $DotCircleLg [20x20/16z] {
LOzP5WCX20J1cUUkVV_R1h4rIVrHx7BGH_xG2cV6goACaXeCgW8ardSWi4ekoGEbkar3fBBniBfP5leiN5Ze0kvIJ3LjT7VlRdxskEakRYTelD5GkZF5o7jo
jovr-KRbWL6Y-L-yZz-IkwXy5Rl2kIAKfSZ08T9unJJHQJu
}

!procedure DotCircle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/DotCircle', $name, $tech)
!endprocedure
