' definition of the Item fontawesome-5/Regular/FolderOpen

sprite $FolderOpenXs [11x10/16z] Oy0A-Fdv-FYXJ3011En09XHm0vdyS00N1x4XW9UL1o6D1

sprite $FolderOpenSm [13x12/16z] TSc54O0m40NH-oCuRF_LOd5xqPspePdNuOFvkyvztrSVDhzmeH_wWkGRUt34O27-nRiZMU41

sprite $FolderOpenMd [17x16/16z] XSYr0GH14C0m7o-E-w_scL6X-A-sWy9Dz-G-1WURhHwKMv0yMKznPpv7ZmkDRD1z4ZXnisg4t5bLxffeuywLpIV0-8WFzW

sprite $FolderOpenLg [22x20/16z] fSZ50SH04C0mXvE5SV_L7ZE3dk9lhNjnjMfigDVBJZRopdovX0VJvTBijERzNZjj4rvR57o0mSmLLPGharaNPwuegbof3gZTLNO65EyqGAutHhwp1W

!procedure FolderOpen($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/FolderOpen', $name, $tech)
!endprocedure
