@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome-5/bootstrap')

' loads the Item which embeds the element GrinTongueWink
include('fontawesome-5/Regular/GrinTongueWink')

' renders the element
GrinTongueWink('GrinTongueWink', 'Grin Tongue Wink', 'an optional tech label')
@enduml