' definition of the Item fontawesome-5/Regular/Handshake

sprite $HandshakeXs [12x10/16z] TSY50O0m3031nvtVVrhSQIyUuXnT4zHa785MjniJo5IsOzkLbPjCeBP8l7wypG

sprite $HandshakeSm [15x12/16z] XSZ50SCm40NHCTEFflzgZRg5tlBobuyNaCGD0rWIBICk561I3JWgftfY9kjP6cukazgVoQKppbr7uzHUt-l5HMF71mS

sprite $HandshakeMd [20x16/16z] {
bOk55KGX30GNakyo_NTx3pstGREYlzZsmjILGET8St8XoMaQEDESaD9PirWmoOgSs9icJi3ljGWwsRhcggnGj0LeeWFC06CN8uljO1OL84PyBmqpPSXicsw9
KJ7e0nS
}

sprite $HandshakeLg [25x20/16z] {
hSy5aiKm38DXEIc3__lVTaTJReVtVSKeQFrQvRAyyiIlJ4ZPOj2gXKwsabjcZITLRJX5ICu3mZtHit73xtFZZgkZ1vi-7Hfy0iXFnsQ5SdNGNpqJPfE0yUfP
7AQmwpXH0gG2r5gbW5M5HR3LNvpAakz-ctvTsd4Tz0z_
}

!procedure Handshake($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Handshake', $name, $tech)
!endprocedure
