' definition of the Item fontawesome-5/Regular/HandPointer

sprite $HandPointerXs [8x10/16z] DOM70O1038ImwtyIzj_MVWM0pXFRv-stnsjIPmN6fQqkxDVbTe0m7eBHMlC4

sprite $HandPointerSm [10x12/16z] JSc50S0W40J1nPthlzguCF0EzC2jJN4RSUdirnsYkw-oafUYmS8SDOI121F1cOBmUZjcvwGpBdq7

sprite $HandPointerMd [14x16/16z] VSU35KLH0C2mFboZ-s_xRUGm79N9GrCVi_5twyjqZiSMLITXUXnkoSrTZrjPE58vRj1O8wucLaHYGxeBr-s2tjQ4nSh62ei2sOqp8qVJAmu

sprite $HandPointerLg [17x20/16z] {
XSc5ZGKm0CDG5rNs_jCUuqSheXVUcoVmjwCcVWkkwEAtPCFz7C85wDdhBvpjEwxu3JbQcYfD_OGOPPhr7IAVwohLHkLptU5WLun1a2uQuGUMPFq3HnYEN_00
6cZGeSNtawXyLIq0JSTdtzVskyOh
}

!procedure HandPointer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/HandPointer', $name, $tech)
!endprocedure
