' definition of the Item fontawesome-5/Regular/Heart

sprite $HeartXs [10x10/16z] Oq02_FpyOCm0H8py804-c1GV5pDC4H32M60cb0IhHrS2OG

sprite $HeartSm [12x12/16z] LOo30S104C1Ikzb_slAPCwauj6FH2JnezGJFNXwU57GXudZc7FlqWrXiyc07h5zAO_UbeTY4M1nVk04

sprite $HeartMd [16x16/16z] POc50GCm48I8rVkt_xILk125voI-dXv8x_muPNo-3IJ0vozHhoWobk-xJCpelRbR_2aqXQW7KmWoo65Md4JMDupWyxG7btKAOi51vWi

sprite $HeartLg [20x20/16z] {
TOs54OH054C_hElhlzeJd9MCPQ8oWR9stOYsvf3Oi4e08FyzoDPbA12i1qHWoozGjrOXQD8nMg-fYZIeGAjb8ghHGDgWeaeXDJ4ZmbDS86mEyL1klXpaO8qB
iLtXVGUXaRPaAxN57by
}

!procedure Heart($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Heart', $name, $tech)
!endprocedure
