' definition of the Item fontawesome-5/Regular/Keyboard

sprite $KeyboardXs [11x10/16z] Oy0A-9bWW9cVWP-Pcnj8WI120GCZBpix7oC_YCaE4UD0PlBmmm6IkG

sprite $KeyboardSm [13x12/16z] Oy09sFcH0P849py343BoiNFoCV9peic0f9ZukDZuGHn6c0GZH0y8S36WwM54imO1

sprite $KeyboardMd [17x16/16z] XSm53eH044JHF-vJzp_j2aHmNZhILhnhVIUDMNUaoexq6pA5Aeh8I3LKKgO6ggMolAH_cOIBh0DvAxBeWflGgeLRGzCWbeLXNBma7M3t34TV

sprite $KeyboardLg [22x20/16z] fSw35KKn44NHEtXESlglzjl6NWY6-flpG0E_4u3k0G85YnRYU7t-U-VmMoPbISrbUpt-6bK3WngslHvpqsKfHMwlXzzXqAKnZZiuHySTdkJUe_28bdglrnVM

!procedure Keyboard($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Keyboard', $name, $tech)
!endprocedure
