' definition of the Item fontawesome-5/Regular/Star

sprite $StarXs [11x9/16z] uwSz

sprite $StarSm [13x11/16z] unzS

sprite $StarMd [17x15/16z] un_P

sprite $StarLg [22x19/16z] un_aO1G

!procedure Star($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Star', $name, $tech)
!endprocedure
