' definition of the Item fontawesome-5/Regular/Star

sprite $StarXs [11x10/16z] Om015WOuuEU7iTWueKn6NY23dmSaoGaHuGO9GDM35009c00IanTe68J9338LX04

sprite $StarSm [13x12/16z] JOo50O104CE2Ezb_MkJzNDeIRAKnhVD-sTS7VNoTwWr_tN39_rjmh7FUBkCf0EykQJ70SQH5lPEuFsbNU04

sprite $StarMd [17x16/16z] {
NOw50G0X24MnsxV_jDUXqisNXugHcM3DiNF1rccaSTQUnES6xjggoLwUwizER42NYXbNpMdqcrVSMxueusTGX1T4VRoNl-FquTjRCERyBOMtq44xw4z1Sxz9
r_4T
}

sprite $StarLg [22x20/16z] {
RP054iCm30GLCjlx_zzsL1LCbvXsnFBJtMGZI2kCmCxq8S_G4MKrLkA97JbyjLH0SQ9AcFJkCLq2nAjFaC7BgLklIhL4heCO7AqhvLi3t9EbrN7-JFi4XvWy
zz2Od46thZsgscijno-PNXEqg9pVx2_UTcPFHuFTpcBq1G
}

!procedure Star($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Star', $name, $tech)
!endprocedure
