' definition of the Item fontawesome-5/Regular/StopCircle

sprite $StopCircleXs [10x10/16z] BOa73W0W309nP_F_tveZdBPb29R2jPyT8N3-lPThQfBrgffL0QhIMI1z

sprite $StopCircleSm [12x12/16z] LSQ50O105CFGu4xsdnOzVLzQFXt1gS_EF3o8SRxrPO_WOwSnT-pEtB7k-sDcb5b-Dd2yZz6HH--hWHi

sprite $StopCircleMd [16x16/16z] {
LSo50OGm00J19Hxi-k_sSuyFkZ4EK-GHzRTpsBGde4dvoC9XLO9ufwV0s-fgquYErwoow0MJU7LJ_7GHd-wZswjt-MQA1i67Q-KYuJEsey98IzBMSj-TXovB
33y
}

sprite $StopCircleLg [20x20/16z] {
POi73iKW5CFoEq1Ct_-sNw1qksNv9PBvhNhmoqnwE5K0IB40M2M8pbTOdD99X36pCeacvLaCaqtIQCDG37nD7oVwZ_HshCIF4-NhuEaMgZe_QRjS8YXGTGVc
5Xygp8DqARSMF5pIKAQ12J8ZqO5gymS
}

!procedure StopCircle($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/StopCircle', $name, $tech)
!endprocedure
