' definition of the Item fontawesome-5/Regular/Surprise

sprite $SurpriseXs [9x10/16z] 7S650OG0000XFcrl_sajW9T7JMiB_M4VvD7q4bdYCVo-59ieCWMz6Qeu0G

sprite $SurpriseSm [11x12/16z] 9Km50G0m3DhTJ_-qSnU0p7AYCE03yAbPFT2fnEy-qasNJeIpQTlFABg7_NbSmugz9f1yt775r7ok_bqHSBO

sprite $SurpriseMd [15x16/16z] {
JSs54SCm4031itWYkFwh3HbtwFdPXOrBzo_jcNOWJEUUiKiE67BAHgnSbaceRljKTWgRG17GnODTWAXxkWdWFjN4lgS2Jee9ccxG1URvULW0klPIXsR-DdzU
01y
}

sprite $SurpriseLg [19x20/16z] {
LSp5OMK154Cn_STy-gzs81pjBjW-3Iy_JNTlZg_rKrtRNZL_RkxHcxLsgDkNcbYw-F8goazhcsvUzmhNWTeRM0jZePxWc61VSLP-ExhoPduhmjtS0cCLAEMZ
eHU6RdSJzggFdA7WgGrR3zPw-R0NsEeSONbgy6Req-tBV5RFFe2_
}

!procedure Surprise($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-5/Regular/Surprise', $name, $tech)
!endprocedure
