' definition of the Item simpleicons-6/K/Koa

sprite $KoaXs [10x10/16z] VSQr0O1000ImuCxjloqb_gcYA9VLsevMQXixIOHKLMA6Y0y7

sprite $KoaSm [12x12/16z] ZSP50GD100Im72-FVxSrKCeh_f2FtzWEzkqCAa4oE8djI4oLTP9gOx-ujyi7Bm

sprite $KoaMd [16x16/16z] fOo50G0X54AVtRh_j1UumCNl0FXfwzCUeQcRXTt7TEysh69WtgFVEsl_Wyb6kwdYBZhuK2GMR90QYPTs0W

sprite $KoaLg [20x20/16z] lKv55aD122EC-_rlMq9jN_cZ47l81Uk4xp2rFyR4LcCXvj2qEnugmmWj9kY-OtfovVzGFB1myCRGuPYOXRZ4uPnZkOiqXie3Q-e0Wd8MP01HVhnk

!procedure Koa($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/K/Koa', $name, $tech)
!endprocedure
