' definition of the Item simpleicons-6/K/Kofi

sprite $KofiXs [10x10/16z] Oy02UFcXW076u01nW0188hE019XavOCeumPAyF7nylBoe9W7

sprite $KofiSm [12x12/16z] TSR50S1G3CDGbRdQVzh2frjUm2RGJLN7RNFgFJWkogZoKr2tqZVL6VojxG63sKti1G

sprite $KofiMd [16x16/16z] bSp50S0W50FGfExPVrfSR-NXVC6WGusR-DHP_FQuY1okyX24o-ls3y4JtdsS2i8psiFEz7mdg0gDvlhUu4rhCk4F2m

sprite $KofiLg [20x20/16z] hSwr0S0W40NGZpliFsq4bp9vtVdXPo5jF13JWMmnqoczen4WdY2N0Pbh4eNCERBaLCwnd8ieycmxwjUlP4_sb43AGXlH0llF3Y-sv53G-0YPntSt

!procedure Kofi($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/K/Kofi', $name, $tech)
!endprocedure
