@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2023/bootstrap')

' loads the Item which embeds the element AmazonElasticFileSystemEfsOneZone
include('aws-q2-2023/Resource/Storage/AmazonElasticFileSystemEfsOneZone')

' renders the element
AmazonElasticFileSystemEfsOneZone('AmazonElasticFileSystemEfsOneZone', 'Amazon Elastic File System Efs One Zone', 'an optional tech label', 'an optional description')
@enduml