@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-7/bootstrap')

' loads the Item which embeds the element Underarmour
include('simpleicons-7/U/Underarmour')

' renders the element
Underarmour('Underarmour', 'Underarmour', 'an optional tech label', 'an optional description')
@enduml