' definition of the Item simpleicons-7/U/Unlicense

sprite $UnlicenseXs [10x10/16z] 5S650G91402nuBpiJV_L8WbiFVtLVbrj54mFgIPjcqofgoRqN2P7qbIHBN_XqHzV

sprite $UnlicenseSm [12x12/16z] 9Oa53WGn08HOgxVy_xUNoH4PWJ1j_D6prLG7GKbzDMnCxNhZF2XQ6Z5vBy0cfjeHCK8kKUzb1oiemEK1sAfvVm

sprite $UnlicenseMd [16x16/16z] {
BOw55S102CMWRf3zj-rBh_yqU7nQYpj3gM9e7mYFpzJKm3yoqL5Y0niq6Te0BhW2LlJM5xp6JQ5RlAq9o7f7oLk-n9qx5f8fje5a544R_8z7w-HQ6-Tld9uE
9Mu-3vnJBeMe4ZN2NW
}

sprite $UnlicenseLg [20x20/16z] {
FL010i0G409iW_F_tww2W6kdRkSsFfkzuBp8SsFuGp6gCMJ3-Lqg70LytDGL6GYoj9G0MCDYg8VR0PJhyqMeB0k-O_VEmuTE2AHbTE0HrtjgtSeavwMrkKvl
7gHYL4BXtPJ5vmyvJcarRBodEM3toL5mycCzhAlQ7EnLNxzr7JT5LDXwtH9BkoszS1VlRi9A-W4
}

!procedure Unlicense($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/U/Unlicense', $name, $tech, $desc)
!endprocedure
