@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2024/bootstrap')

' loads the Item which embeds the element AmazonAuroraMySqlInstanceAlternateCard
include('aws-q1-2024/Resource/Database/AmazonAuroraMySqlInstanceAlternate')

' renders the element
AmazonAuroraMySqlInstanceAlternateCard('AmazonAuroraMySqlInstanceAlternateCard', 'Amazon Aurora My Sql Instance Alternate Card', 'an optional description')
@enduml