' definition of the Item aws-20210730/Resource/LoT/AwsIoTGreengrassRecipe

sprite $AwsIoTGreengrassRecipeXs [10x10/16z] Oq02d43CXCw2avpC39oSB9m8CGXcP6I0Yw6p6460am4

sprite $AwsIoTGreengrassRecipeSm [12x12/16z] ZOo30S10301Zx3zmxRuk9hmWN4ZPyzK5ofMxEstv3czvG4Gi-MZVrpV_VkmGp

sprite $AwsIoTGreengrassRecipeMd [16x16/16z] ZOg50K0X44B10lSV-7UdpxWZSATuf7hLcdxJPmtggBEaikfJKo31WLTzxHV1ThdchpeFLIatzaDT2K0F

sprite $AwsIoTGreengrassRecipeLg [20x20/16z] dSo50O1020NGJyF-2zlTFhsYS25gH4kiq3EkanWL7MBpTRv8j6gEBUvZqbwhfVZUomPOYzTrrFuj_9aNGBJaUoyjffZuGjft0m

!procedure AwsIoTGreengrassRecipe($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/LoT/AwsIoTGreengrassRecipe', $name, $tech)
!endprocedure

!procedure AwsIoTGreengrassRecipeCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTGreengrassRecipeLg>', 'LoT', $funcName, $content)
!endprocedure

!procedure AwsIoTGreengrassRecipeGroup($id, $name='Aws Io T Greengrass Recipe', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$AwsIoTGreengrassRecipeLg>', $name, $tech)
!endprocedure
