' definition of the Item aws-20210730/Resource/LoT/AwsIoTDeviceDefenderIoTDeviceJobs

sprite $AwsIoTDeviceDefenderIoTDeviceJobsXs [10x10/16z] NKk30S1038on_y3jMt4Ey4RMmQeAMazYdY1qf4Tqh4vRLinn1DU5BH9-

sprite $AwsIoTDeviceDefenderIoTDeviceJobsSm [12x12/16z] LOo30G0m30J_Ys3_WMjUJ7n4TXoTCBqF7njerdDL7Rrbvcwh9dBcwdiFDdDfVUZQoMJY_ZzVmHOH5G

sprite $AwsIoTDeviceDefenderIoTDeviceJobsMd [16x16/16z] POi53WGW40ExMlh_1vy3czp4glY3wulyvtVU_lFn1epbqri4Fzv9shwUVx20woL8FaOcjzxU1A8WtpuH24-_Uv8eRDyLYEpZaKK6hh-oT2ZW2G

sprite $AwsIoTDeviceDefenderIoTDeviceJobsLg [20x20/16z] {
RSs5bSLG203HmQ7_WbU-S68Jltd2SxFLMXx-tYsjzYrU6Hqr7rDxfVpTJiQxDVyB404_xH4wZN6qp1J9ggCrT25pi1n6TPXWRI0WZMQjcuPXwhIUpeWCHui0
zpuQurtMd0pSzwDas_KY3mNm2m
}

!procedure AwsIoTDeviceDefenderIoTDeviceJobs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/LoT/AwsIoTDeviceDefenderIoTDeviceJobs', $name, $tech)
!endprocedure

!procedure AwsIoTDeviceDefenderIoTDeviceJobsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTDeviceDefenderIoTDeviceJobsMd>', 'LoT', $funcName, $content)
!endprocedure

!procedure AwsIoTDeviceDefenderIoTDeviceJobsGroup($id, $name='Aws Io T Device Defender Io T Device Jobs', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$AwsIoTDeviceDefenderIoTDeviceJobsMd>', $name, $tech)
!endprocedure
