' definition of the Item aws-20210730/Resource/LoT/AwsIoTThingUtility

sprite $AwsIoTThingUtilityXs [10x10/16z] Oq01h9oSd0neW9EJ0op5m0e4Z42Q4oW4KWU2O01ZiO1fJFC

sprite $AwsIoTThingUtilitySm [12x12/16z] LSt50GKW30MmuA_x3_nTSu6wVqkh1PprLApfx1soc6W8RUvs4sbgrXqfQqBVdtwE-FzNdixVtIi

sprite $AwsIoTThingUtilityMd [16x16/16z] {
ROy50eGm30GtZV__mnSvXu7gR0qtA099mg-XQsgQkyhQJv3Q0iVDhAIeh9UYN9T8nE0rZYZ_sY77PzRVC4DgGBQMilm1nB4Sw_q_utI8yES-4RDVXrvib9I2
ycZPHVfzsFSz
}

sprite $AwsIoTThingUtilityLg [20x20/16z] {
TT230G1H30FGrCt-0v-DzstWZyC2NC8XNdrzuvWLTdihOiwP4owhmhQHvgJtUMO5c-IKbZuJU1GgLfHpRM33TIrPu0QSst6z2_CoRwTupGFpDS-3htbQt5kD
groNLDSKkOIKz_yT36B89Sn6
}

!procedure AwsIoTThingUtility($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/LoT/AwsIoTThingUtility', $name, $tech)
!endprocedure

!procedure AwsIoTThingUtilityCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTThingUtilityMd>', 'LoT', $funcName, $content)
!endprocedure

!procedure AwsIoTThingUtilityGroup($id, $name='Aws Io T Thing Utility', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$AwsIoTThingUtilityMd>', $name, $tech)
!endprocedure
