' definition of the Item aws-q2-2023/Architecture/AppIntegration/AmazonManagedWorkflowsForApacheAirflow

sprite $AmazonManagedWorkflowsForApacheAirflowXs [10x10/16z] uy89610iTbOWoOmGOsPX0eh1P3b192UGP61Z0V4PG2ms99C

sprite $AmazonManagedWorkflowsForApacheAirflowSm [12x12/16z] TSn50aCn20L0e9-acVlVj-uosoV-YWf6rK19UkqM8fDk0p7H2afKvQQHq3OOFH_zlFxKWiQ-Utfr1

sprite $AmazonManagedWorkflowsForApacheAirflowMd [16x16/16z] XSp50GDG30BGnWFxxrkZUlfkB_3S06Y3zffyR3qpp_km7zjMF7OY-_c_JbUzrcsJRuEyomzjtNr37jQKlmm5_ZoL-yb7i-HTNWxcxZos6m

sprite $AmazonManagedWorkflowsForApacheAirflowLg [20x20/16z] {
fSz5WaGX34NH_0Zmxlxtsq9edPITOJoyPcJcv4D-qeubK7mmsj-OH_oFhKbrxwogjMEwrkdFe1bCMYfINMV3JWp2qzr_vf4PEhrM5zlYC5GSuT4nkQvkAQ7H
zmr-VkiU8ppPP6NTEpw89ZPjtEqT
}

!procedure AmazonManagedWorkflowsForApacheAirflow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Architecture/AppIntegration/AmazonManagedWorkflowsForApacheAirflow', $name, $tech, $desc)
!endprocedure

!procedure AmazonManagedWorkflowsForApacheAirflowCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonManagedWorkflowsForApacheAirflowLg>', 'AppIntegration', $funcName, $content)
!endprocedure

!procedure AmazonManagedWorkflowsForApacheAirflowGroup($id, $name='Amazon Managed Workflows For Apache Airflow', $tech='')
  IconGroupElement($id, 'AppIntegrationFamily', '<$AmazonManagedWorkflowsForApacheAirflowLg>', $name, $tech)
!endprocedure
