' definition of the Item aws-q3-2022/Resource/Database/AmazonElastiCacheElastiCacheForRedis

sprite $AmazonElastiCacheElastiCacheForRedisXs [10x10/16z] HS7B5O9G40Mm30VURsx_zRfHIRpo8tlSpvqqwtRRkLbmSe7RSabttReRLN60Oe5AWWy

sprite $AmazonElastiCacheElastiCacheForRedisSm [12x12/16z] JSY50GCm20J0YoVG_TUj6xpxl_YTDM95lRzqLZc6JbMMat6Pn3rlgEMHRRNpoDqUaQAqn1QA0e-Tyyx-Rvq9Dm

sprite $AmazonElastiCacheElastiCacheForRedisMd [16x16/16z] {
XSVLeSDG3C1GcHB3tN_T1sMkz7NuriXjGyjghucQhCmTjPPW2ph9WQ71iz8WcNz70D0dhnm5OjdH99WB8lox9OK8s5LggEvK5eDPzmwGi2fGuLWM2wSk1ld_
R6OpjMfUz0i
}

sprite $AmazonElastiCacheElastiCacheForRedisLg [20x20/16z] {
ZOo5WG0n2C02DQwm_xnVVRTK2S9_yVYCug2AhYFpIKeEUMhrxALbYn4vI8X9xVIYM30gm1akGyeA3y5ufwC_LLND6u5kPnowN1TswpmT1yQPPy9oPcr-HMPl
QdswS3SNiHoOfn4gx5wf-EezpAz49EZldCswXthSMs_xq5iR2mdU48-9yICl
}

!procedure AmazonElastiCacheElastiCacheForRedis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Resource/Database/AmazonElastiCacheElastiCacheForRedis', $name, $tech, $desc)
!endprocedure

!procedure AmazonElastiCacheElastiCacheForRedisCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonElastiCacheElastiCacheForRedisLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonElastiCacheElastiCacheForRedisGroup($id, $name='Amazon Elasti Cache Elasti Cache For Redis', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonElastiCacheElastiCacheForRedisLg>', $name, $tech)
!endprocedure
