' definition of the Item aws-q1-2025/Resource/Compute/AmazonEc2ElasticIpAddress

sprite $AmazonEc2ElasticIpAddressXs [10x10/16z] Oo00c60CLcHHTZOWO6TWPs04yLW8c04

sprite $AmazonEc2ElasticIpAddressSm [12x12/16z] Oo0PiBCnmfXi30mGDWkG0PO20NO6TWO6LfW21cPMKam7

sprite $AmazonEc2ElasticIpAddressMd [16x16/16z] Ow0-O6L5vZ6oC32mC4BOR43CpW0cu09iO1eAs5c1KX1nX0P69WINwW

sprite $AmazonEc2ElasticIpAddressLg [20x20/16z] pKm50S1043f1-YUUUu7zkG3nerL-Bs2MholNablrTZWdRLFsUKkVjx1ES-u2WRpa-n18NITiZJPY19i1

!procedure AmazonEc2ElasticIpAddress($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Resource/Compute/AmazonEc2ElasticIpAddress', $name, $tech, $desc)
!endprocedure

!procedure AmazonEc2ElasticIpAddressCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2ElasticIpAddressLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2ElasticIpAddressGroup($id, $name='Amazon Ec2 Elastic Ip Address', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2ElasticIpAddressLg>', $name, $tech)
!endprocedure
