' definition of the Item aws-q1-2024/Resource/ManagementGovernance/AwsCloudFormationTemplate

sprite $AwsCloudFormationTemplateXs [10x10/16z] Oy01kE0C3XYBdHKX2mHe6XWHEZYX32O8O

sprite $AwsCloudFormationTemplateSm [12x12/16z] POg50S0W30IJ_nRRVr_SEOYV750RpBqQ1ocrzWAVqJwllTVT2Pd7-K_7Pcx7kuQN1

sprite $AwsCloudFormationTemplateMd [16x16/16z] VSj50a0X24NH9mtxt-_l3iz8WOkNo5FCVvpMlr7S_t3aRFkZjTl-rSkxhzdsPzL-R_dgVRRtPfrUuwGO0G

sprite $AwsCloudFormationTemplateLg [20x20/16z] ZOs50S0W3C3mol__Jd27R5WjOWwr-9XhAbpS3O3hOl_9qnXvSimoOwbREpI07UP9ENUmfpWGuSOXbPBN3l2K63ET7Q1gmCTKYn0l

!procedure AwsCloudFormationTemplate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/ManagementGovernance/AwsCloudFormationTemplate', $name, $tech, $desc)
!endprocedure

!procedure AwsCloudFormationTemplateCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsCloudFormationTemplateLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsCloudFormationTemplateGroup($id, $name='Aws Cloud Formation Template', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsCloudFormationTemplateLg>', $name, $tech)
!endprocedure
