' definition of the Item aws-q3-2022/Architecture/MachineLearning/AwsDeepLearningAmIs

sprite $AwsDeepLearningAmIsXs [10x10/16z] DSY74S0m4091Nka1zz-l5M_Ipd6Mip6anoaWehMK56ITqvj0JLiHmInJas8bfv929p-xGSBKfAtP3m

sprite $AwsDeepLearningAmIsSm [12x12/16z] HKot0GD133ek893ttzUYUYgoWXgGj3_X4Q2Ag70Vg72gmgMbrDe6932yyG3SmpUyhwxvhjI3yc6kV-4WL_Y879WUdYJ2_WC

sprite $AwsDeepLearningAmIsMd [16x16/16z] {
LStPWOKm34FHU9So_VSxjjz-lpW24corPKT-BMj-N6j2F3hnh3Nx2N2nh5ghfIjgkis4IgQuZ2z5ZXD8YuSpf3jLUSON4ah6mGdWTYmpBsYXFOaQDP7jlx4o
CaDHxHbSvbeNj7lOkBL_Xty
}

sprite $AwsDeepLearningAmIsLg [20x20/16z] {
PSvPWaGX24DHa0Y9jV_zzWDxhljv782VrIqxwHsbTzJ5o454upMZUOV4Wve2LcIwHrRLDGUT7gpfD761uSLTETOO2YUtRKECdGfVEPFWEwz1sxkWLwvh2eyb
AGEvZApJfU0GwB7vT2Q3ohR4wLePNRJQqVPwjTdnV5gR-3R0PdbR76kTTFkqlzZsTlC3
}

!procedure AwsDeepLearningAmIs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Architecture/MachineLearning/AwsDeepLearningAmIs', $name, $tech, $desc)
!endprocedure

!procedure AwsDeepLearningAmIsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsDeepLearningAmIsLg>', 'MachineLearning', $funcName, $content)
!endprocedure

!procedure AwsDeepLearningAmIsGroup($id, $name='Aws Deep Learning Am Is', $tech='')
  IconGroupElement($id, 'MachineLearningFamily', '<$AwsDeepLearningAmIsLg>', $name, $tech)
!endprocedure
