' definition of the Item aws-q1-2025/Architecture/NetworkingContentDelivery/AwsVerifiedAccess

sprite $AwsVerifiedAccessXs [10x10/16z] uo04686O0S9aGf5WGLN70CBOfG

sprite $AwsVerifiedAccessSm [12x12/16z] VKg50G0X25JXOl-5lpiahzojUg3cAkmmgxqHbbQsRCtvOJNIHuK0cDvqY8S5Fsi4

sprite $AwsVerifiedAccessMd [16x16/16z] dSc53SG05CDG9P-y_yA79M7XYMsUSN5GRg5XKSCKv1eI6e7uSUCFuUQhn81DYSL4ObP1TRTOTzUILoCNug35DMy

sprite $AwsVerifiedAccessLg [20x20/16z] hSx50O1034HH9lhxRnXthhpTw2dyeO8F8tXejS_V7Yis0oT1UGXm3Wq6iNQRCaUvGcBb204YoM0JZP11aick48iaE0ZNeZg0vrszreErCYruKYG_c

!procedure AwsVerifiedAccess($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Architecture/NetworkingContentDelivery/AwsVerifiedAccess', $name, $tech, $desc)
!endprocedure

!procedure AwsVerifiedAccessCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsVerifiedAccessLg>', 'NetworkingContentDelivery', $funcName, $content)
!endprocedure

!procedure AwsVerifiedAccessGroup($id, $name='Aws Verified Access', $tech='')
  IconGroupElement($id, 'NetworkingContentDeliveryFamily', '<$AwsVerifiedAccessLg>', $name, $tech)
!endprocedure
