@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2024/bootstrap')

' loads the Item which embeds the element AwsKeyManagementServiceExternalKeyStore
include('aws-q1-2024/Resource/SecurityIdentityCompliance/AwsKeyManagementServiceExternalKeyStore')

' renders the element
AwsKeyManagementServiceExternalKeyStore('AwsKeyManagementServiceExternalKeyStore', 'Aws Key Management Service External Key Store', 'an optional tech label', 'an optional description')
@enduml