@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-14/bootstrap')

' loads the Item which embeds the element Vercel
include('simpleicons-14/V/Vercel')

' renders the element
Vercel('Vercel', 'Vercel', 'an optional tech label', 'an optional description')
@enduml