' definition of the Item simpleicons-14/R/Rapid

sprite $RapidXs [10x10/16z] Om027Zu6CE070o231KZnWbb06im5iTZ1V22648mm3Tm8lRmG5XiGGmJ1vW8

sprite $RapidSm [12x12/16z] POo50G0X30FJTm6o_xIuStM5PpC66KQwD1Ot-G4gvdbCIfVdzT8nNFz8_vDFAeBzo3yY3W

sprite $RapidMd [16x16/16z] LKs33G1037mR-q_xg99US2eCeEuLZ60ZlBOSh2yd1E19E1f8ZntbxT606iLuz3VpzyHze-1xOGkIVk-CzdlOxorRlj10W8smqQ48BHk2Vvvm0G

sprite $RapidLg [20x20/16z] {
NS-53S0m44DHb-bW_sshYyDFPFrYG8UudUYzJczBtfIaNHEctPE7bxedDm1B3ArDsnCnrXWxajAs6DVSGlq1AyzoIem5_5hdGpAdO2t9CXsNb4ryr6wqiq_y
j66H-fMGskpfsmy
}

!procedure Rapid($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/R/Rapid', $name, $tech, $desc)
!endprocedure
