' definition of the Item simpleicons-6/H/Habr

sprite $HabrXs [10x10/16z] 7Sd50G1124FHFovO_zMky2wGXDya2I5b02rCn3kmugSBPF_V7l-QQgMhHrW_q8x4AgJ2WbH9Bm

sprite $HabrSm [12x12/16z] NSYr0S0m34JHBvbv_sbZhFAQ0mxF9OYts5jxQxKeMybjZD7ENyVIKn1mUMmb0BNstIrxz3sgxn5Ku-WsS4ZmCSdhedZ-9W

sprite $HabrMd [16x16/16z] {
LS-50SGm30D0XS6q_xG5zV727EEbuq-vScxifjPbzx5x0hLk7iEYvloCvvQuk71OPsZSR4YxnjrRa3WFtAV9O-0I--hHGbq0t3WszJrc1uhv4EzM6wZMjMNm
BaeOewp5yQEjttZIA0Me-F6pzmG
}

sprite $HabrLg [20x20/16z] {
NOu50WGX201nKP3-_silrClPT4XuGmF-8RWUxxUtnrrbi-4dTOOo1L7WTGnoMQHrowIEHnggPprnEOfxKMt2dTSyr9vRUPE-EgBnh8FFjYOFypfarb8mqIkF
b89BdjL6kLrMpeuu7hANQyOQAttiRQY7XarNPs3OO1Eog8TfyAO1C_5SpJ_GCuE_3TAgec-dW9-o3mE-kGC
}

!procedure Habr($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/H/Habr', $name, $tech)
!endprocedure
