' definition of the Item simpleicons-6/H/Hackerrank

sprite $HackerrankXs [10x10/16z] uoSUC73mCp10M0mWX10Z

sprite $HackerrankSm [12x12/16z] uoSTiFAny3CpCuFPZBoC_0mC310sa0QoCSHv-NduUNXuY3CS

sprite $HackerrankMd [16x16/16z] uwS1uENbv-7d0G8edv6Ldu6V0GXWV1O-L3wGYU0Zr6FogGy

sprite $HackerrankLg [20x20/16z] unziW961duE1dm4428YnCMEA0G6661yxCUQniV9piVApWi10UXy

!procedure Hackerrank($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/H/Hackerrank', $name, $tech)
!endprocedure
