' definition of the Item simpleicons-6/H/Hetzner

sprite $HetznerXs [10x10/16z] uySA69X110Ck5WZWbcM1i1

sprite $HetznerSm [12x12/16z] uyS9s5b091yBBv1aO02nUHYuCTXSGC01OKC0iXgyR3uUVZ07rLO

sprite $HetznerMd [16x16/16z] uoSTC31mWsac1aOqFWEHV0P64620yQ40mUVa1G5q_SJoMPXvmJG7CnjXpm

sprite $HetznerLg [20x20/16z] uwSCy75pyq6PtDpS40O70mCpL8o1WO5MOd10I8oH3G9evXPE1WOM937A

!procedure Hetzner($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/H/Hetzner', $name, $tech)
!endprocedure
