' definition of the Item simpleicons-6/H/Homebrew

sprite $HomebrewXs [10x10/16z] Oq05Z0mOW9s72KopWGXEC9EBdv-VWGFEuiLaCVE1jVBpW_G2

sprite $HomebrewSm [12x12/16z] XOV50G0n3CDSRdZ_QO_XMGKiuu3nC_bldMa-EYgGnwNvE3h-HSNLBag98FmUSwozpDippNJg3W

sprite $HomebrewMd [16x16/16z] fOor0O0m50KlxldxJuixT5ptb9d8dO1gN8a9TIhBhD9P3u0vf35aNuWHFj_9oG35d0CH8O2-Q0awk5yQpARhhBrcmu62LOu

sprite $HomebrewLg [20x20/16z] {
hSm5hiGm303H2HgshUz_sWzb4kyeeXVRCDTuoOlSIR74jIxc8fS3yd9L90CPuQZJnGQo7LJcr-RHOspBE73wg6O6BSTWSOy80j2hJT6AZ5UBQ7pNA4oxVJwp
bIxi9ZFbnf7M1EHjwXS
}

!procedure Homebrew($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/H/Homebrew', $name, $tech)
!endprocedure
