' definition of the Item simpleicons-14/F/Filedotio

sprite $FiledotioXs [10x10/16z] Ou009bOmnS8F140QIC9Pp0Wn72oGJWYDocA0iW

sprite $FiledotioSm [12x12/16z] PSR50S0W00Im5lVRVrhSoIlV46O0_2KwfzyOCUy0aFdYlMtrttZ9TJ5V-Fu4

sprite $FiledotioMd [16x16/16z] ZSZ50K0n20FGkfViF-rt2RVY3qCXT3i1q1b7Z4k-0smqByg0nAfyV4GRvUX9paTtSZhQiASpx0SBjhSv-kST

sprite $FiledotioLg [20x20/16z] RSk53GG120LHz6xzzr_jkW8JVydG9vdy2pPWxGrOUvkEG31qYCReh0icM5FF1lYG3L8OrrQ_RJQbyCe9BtkaDYwC7aitnTgNBG

!procedure Filedotio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Filedotio', $name, $tech, $desc)
!endprocedure
