' definition of the Item simpleicons-7/P/Pagekit

sprite $PagekitXs [10x10/16z] O-270WOK5WC8aCZYvkQ6ic2cGEK1

sprite $PagekitSm [12x12/16z] Os3WXm46D3OZ0mXmKPiDDv-5YOa71A3sCe01

sprite $PagekitMd [16x16/16z] Os3WHmOCsFYyK03ZCp900DS0yXc1W0V6XxaQAn_AW00CFW

sprite $PagekitLg [20x20/16z] Os3WHmCC32I9CJF203TSZ9411hY6lXWt2F0Xn11XWLUCcmi8M9aW05KU0J35

!procedure Pagekit($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Pagekit', $name, $tech)
!endprocedure
