' definition of the Item simpleicons-7/P/Picpay

sprite $PicpayXs [10x10/16z] Oq07_7nyC1O_c01I_10E8pzS6ChYuUE7i400eGcD1G

sprite $PicpaySm [12x12/16z] RKg30G0W4Cp6_jDczpuXe72CSM5aoesbAWu8O-yhAS-tb8YqvXgc6xDwAcv51sxlmzPkd04

sprite $PicpayMd [16x16/16z] XSV50O000810x9RzfxKxUN6yLrH31pT0ThBDQ8VgoMsrMWT7KLHEHwG514EpQMsPUdQe-U8rJgxPpTg_x_K

sprite $PicpayLg [20x20/16z] dSg54KCn0CDGXpdUVzhsCxEEtmctoQwriJPnOn02UMjaPu5jiRTQ1-lhh2c748nIAlOdnnIQH3VsZOQ7viYwi9fpPPETRInXPn9BK-ZxQFVz0G

!procedure Picpay($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Picpay', $name, $tech)
!endprocedure
