' definition of the Item simpleicons-7/P/Plotly

sprite $PlotlyXs [10x10/16z] O-270Hua5Yi_0pyRcXW367A1nK2wk11YQBBS_7meUW4

sprite $PlotlySm [12x12/16z] O-270puUVWI0i_b0R1usVWOmH8ZpOug3Q0YR5ooAoUPZm6OEDn8R

sprite $PlotlyMd [16x16/16z] TOx50G0n20I9UwR_QizT-B4kdUkbmltg---TqgZWrbzxR40Aygrt0UNHTUThGpG9fEtwwUVuhSo_vFqtwv_-Vdly_TxVF_Q4npy2

sprite $PlotlyLg [20x20/16z] hT250SGW44JHIN3Rtt-rv-uId8UZncq8XVlGlx3GG4QDeACfOkhC0eqNQxj11XjGZYP7Ks4Ig1vii3FimZWO5pRjr_hfmgITIGiP1WriLttnL-w1hG4

!procedure Plotly($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Plotly', $name, $tech, $desc)
!endprocedure
