' definition of the Item simpleicons-7/P/Powerapps

sprite $PowerappsXs [10x10/16z] Oq01_FpyK0O8m1bS_5067nZ304WC8WoIHjM2R1u

sprite $PowerappsSm [12x12/16z] NSs50O0m40D0tE7sdnQ7ohicHIO3thAo_OqEnhjakkqkMLVOk2-WyClo7jci0MTxGIEoqdAN1m

sprite $PowerappsMd [16x16/16z] RSU5OKGn340nVmvh_sdROtu1M_4pclN9BcE-iph0T6NIWNpXWWqo9qvWfK84O1d003Y007G9MWGerzVZ51ACTc5CEZ3Ysc87SM-p8fvLyut_

sprite $PowerappsLg [20x20/16z] {
TS_L0KCn3CNG-nXZxJzjoL0-dmfQ__KSCyTxWmdOtzF8tVg-oysP6couJMwdscvqzxJwJUO99DLDO2TtwaYJxJYZB0Hbj8KHy9_NVV5Bao9EkT1Y_aom8ZVN
dp6bbHsdfuFDCfN60dHwZwDQfYi
}

!procedure Powerapps($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Powerapps', $name, $tech)
!endprocedure
