' definition of the Item simpleicons-7/P/Protractor

sprite $ProtractorXs [10x10/16z] DSR50OK0042XzpkL_QUrvKJLnxCLgq_nwXEFrCVr-VSHl4DMUMedfpvdwc5LCm

sprite $ProtractorSm [12x12/16z] JOk30S105CLIkzb_skASRpn-3bSYHc9xTTiG1XtuERrmOWhBsyCeY8KjzwjaH3Djlq1kRu0hRry

sprite $ProtractorMd [16x16/16z] JS-35KGn54NH-n7Zz5_j8DvBmQCQKqYNfaBdrB3KSOrIq5KWj-17NOPBl-ij3zpjmL1dGID1mUYYaofmAQnx9g53vY8SAe9JbUNKfrziAt9Sc-lOvWi

sprite $ProtractorLg [20x20/16z] {
PT3JeGH100NH6gDH-KVxi7i_1gTj44UthbmiHXi8BuvBLrdhqLJFTBa1H-hBTwy9eggWSi2XZgnKtVdku7VJR-rGmDZXqAumQi2GyhZqeLK7BePHLoL2yQNH
V1fppXKvz89_frVZvKi3Y3qdZlpx1G
}

!procedure Protractor($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Protractor', $name, $tech)
!endprocedure
