' definition of the Item simpleicons-7/P/Pycharm

sprite $PycharmXs [10x10/16z] uyS665WPU1WPc9Y0B7uUPWQ860CpFvG5uVBmOmMSG80c1

sprite $PycharmSm [12x12/16z] ZOgr0O105CNo6noo_xGu5MTfdfgZ1zo0xVGXwsdMkm_a-upAukpzEG5iOo3vFG

sprite $PycharmMd [16x16/16z] hSY30S1040NHlx6d_sfZM-yuooNVznCWTztc0TKSmkRnsoxgeFddz6qgn42rd5aNtHGidnhL2dvWhQdp5WSg

sprite $PycharmLg [20x20/16z] jSnL0eD034NHDrfBUlU_sYhE3tfWBCOk-gf0riUZYPKi6U6JYOfD350q1S3fOgQKT9_C4xDOWeV2C4PpnljLOHXhXXXVxZIUvfpZzlTW8FnbLdi3

!procedure Pycharm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/P/Pycharm', $name, $tech)
!endprocedure
