' definition of the Item fontawesome/Brands/_11Ty

sprite $_11TyXs [12x10/16z] JSY53S100810wbxsdxRoJkm2RVF9HMUmrorzDZ8qLiNoxQkNenhtwCu1uTuGBf4N

sprite $_11TySm [15x12/16z] NOf50eLG08HGNnVtF-tlT7O3S5u4TapFfsZ1_BnTZfzR1KjnrHcPhrkrkV1ndt7r-BtO-j-Lpwt_Lsa21u_jEqMk

sprite $_11TyMd [20x16/16z] VSW53WGn0810Ahlryl_VNkJSY97XV_r-IwbQ2PQRgMojn8Tb9RuP2jjAiISIaEuML8E3xTrejeIY3qiMKAnlDWtoPidsOUYhjGyBEc3PxbPWAHG3Rvr3k

sprite $_11TyLg [25x20/16z] {
ZSq50eGW00NHiPkv_satxDPFymZU9MQLB0XK5j1PC4ULKYtFeBQ7i8PC9SgFW0fn3rw0gcX5P7U4rexOPWtqNQwKPiS_8gKnEWBwjnC8bkTG6iu1jTn3DKAq
XKxJ_XFPGgwsK2czXvuJ8DCSYh-UfEd--WK
}

!procedure _11Ty($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/_11Ty', $name, $tech, $desc)
!endprocedure
