' definition of the Item fontawesome/Brands/CreativeCommonsNd

sprite $CreativeCommonsNdXs [10x10/16z] Om01PWOmOEVdOkBZ1pF0V7umWZAvWGG_I8IP2Ix63nD3KiS0rmkI14i3

sprite $CreativeCommonsNdSm [12x12/16z] HSY50SD0300nbVbl_sbB8PaD79YCngjkq6Fw3CQqqaaM6Joh1nrU5cdxYyakrqp2AzXtcSOFFW

sprite $CreativeCommonsNdMd [16x16/16z] LSc53SD040NHETYOFVrt6wtCJ_I1GsaykWSEcoj0tHsEMZaC1lIi76R1ZOSp0kMNWCKYK4q5caru5FdyNMn0IS0ckppiu0o7umkNfwQgQoknAHn6KmNu0m

sprite $CreativeCommonsNdLg [20x20/16z] {
NSx50KCX44NHXpkt_sfZ4-EV3JAg3nTqwhpieey2zEZp1dv9NgPYrs91u-m1-XFPpqglVnCdqC7Hn7ZUCA_hTiJdPHWB1xnE8FAr5i7rRsgZGo8fqA_j98Z7
ojKY-UzhwSd3yjQBvvTPV1HzkRQ1cUnr1m
}

!procedure CreativeCommonsNd($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/CreativeCommonsNd', $name, $tech, $desc)
!endprocedure
