' definition of the Item fontawesome/Brands/DartLang

sprite $DartLangXs [10x10/16z] Om017WO8uENdvuUm-4409CCFPG8fA9C3p8SGC9A12SPaW3CPu4m

sprite $DartLangSm [12x12/16z] BSd50S104CD0XJdklzg0RkTbGET8EP9ig5F5Q8MzIvMDFr7FdwlCvbOup1OWwinxX8xABm

sprite $DartLangMd [16x16/16z] JSZ50G0n4CD07sFY_giDBkatWlH_2FricTuyIkfVUeQURw6Kk_F7EDvcWXhOxUFk3kCNwu1O1w3cCesNOQ156zU5E4v8xWe

sprite $DartLangLg [20x20/16z] NSy74e0m44BHjNUv_sdj15ocl_cQ9ChMBT8MNAjTDhmpgijaq5YXCdpIjGPoYSjIEJtsB_6QboFDofrcPT2iZ8QcCgAcbL9FK_a-pag-kN7awcGiPIS

!procedure DartLang($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/DartLang', $name, $tech, $desc)
!endprocedure
