@startuml
sprite $AwsDeepLearningAmisLg [20x20/16z] fOz50iD024Kht-Zzxzku9wjvepZycWazF1wUcQB17fYrAeclOe3Q-I4axMnkDWS0Q5QMeA_Ba8HCEkaBEjIu7dJNs1djQZptClTSvvuDKiVPGk-U5Ze

!function AwsDeepLearningAmis($id, $name="Deep Learning Amis", $tech="")
  CloudElement($id, 'aws/MachineLearning/AwsDeepLearningAmis', $name, $tech)
!endfunction
!function AwsDeepLearningAmisCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsDeepLearningAmisLg>', 'Deep Learning Amis', $funcName, $content)
!endfunction
@enduml
