@startuml
sprite $AwsTranslateLg [20x20/16z] {
RSW73i9030H02M_p_V_1-EWa6VN9Xp_w8hklhWCIZC7l6GbhaihxmcxLJKOftxCj1UMV8s8E9-yBC2KL7jaxjSCT53AvvfoqzrdboRLMu44945_N4YcQLNxT
2D2oRyZt34QIfSzDggKCV6z6VCZdPj_sNUIwo3i
}

sprite $AwsTranslateMd [14x14/16z] LSUt0O0m40ImvfAz_y0yuAXE6Vnfzvf9MfnJ29DZZYN2-KUPSp6hGJMzbiWMLUkH2g1llK4sAF-hoFxsLnB_LNzZyta

!function AwsTranslate($id, $name="Translate", $tech="")
  CloudElement($id, 'aws/MachineLearning/AwsTranslate', $name, $tech)
!endfunction
!function AwsTranslateCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsTranslateMd>', 'Translate', $funcName, $content)
!endfunction
@enduml
