@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AzureEnterpriseApplications element
include('elements/azure/IdentityServiceColor/AzureEnterpriseApplications')
AzureEnterpriseApplications('element', 'Enterprise Applications', 'an optional tech field')
@enduml
