' definition of the Item aws-20210131/Architecture/ManagementGovernance/AwsAutoScaling

sprite $AwsAutoScalingXs [10x10/16z] 7Ol70S1G24BJ5F3lls_0Tw9AOW1aWCYnggAPIRPAtVLrhKBLAhC_7gjkcMCfJfHba7u

sprite $AwsAutoScalingSm [12x12/16z] JKo50O104BAkzzzNmFmyih2IAoBg1pJQ8T04xb8Q89-vmjmECoSVxfWqOz5Vs4DmLm-1sJqJLD-pR0Gd

sprite $AwsAutoScalingMd [16x16/16z] NOn50WGm20CFMA3__-_IP7sgW_K5efR-2xIeX093XLafC0mW4s8KgFeuqB60iTNqiWZRgwxtUcG6NVrJxjd0xZC4rGI7WSw40eU1Ddix0nnCPq3G_m8F

sprite $AwsAutoScalingLg [20x20/16z] {
RSy73WGX34DH2R2TSl_pRatOCdprHus_iaxF_81-m6rO6wECOx0n2WN8gjWe_x8ux0lHESb98yl4ASor9ZZ0jY4Gq9U5AMmzebF-jCgnh2VAHdjGOHOQgSOi
r1pSrWXujBsmApjW7l0E
}

!procedure AwsAutoScaling($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/ManagementGovernance/AwsAutoScaling', $name, $tech)
!endprocedure

!procedure AwsAutoScalingCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsAutoScalingMd>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsAutoScalingGroup($id, $name='Aws Auto Scaling', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsAutoScalingMd>', $name, $tech)
!endprocedure
