' definition of the Item aws-20210131/Architecture/ManagementGovernance/AwsDistroForOpenTelemetry

sprite $AwsDistroForOpenTelemetryXs [10x10/16z] 5SQ50S1030B0MeBy_liM8d2Is05K5d1pvrjwPx2x4RdxJMM711ZCrZnMPlBdE1D4PVq3

sprite $AwsDistroForOpenTelemetrySm [12x12/16z] JOa50W9H44AjeVxzxokwEGayjwGMIT_CBeaX8t0mdnaewbDJK36hFaNLYGL8dMeEHD9Q8I7NscibBShLkwcilimN

sprite $AwsDistroForOpenTelemetryMd [16x16/16z] {
NSct0GCm30F11b7QVryhE7_50xlBpQl-3Rsz_-DD2yoo7P44G2PZxDknLjTODgJuE6r4hEv_rLAggUlI2jiqcOi6N8fgCsUjiaD8LtFESGfx_1xwzXotwz_X
0G
}

sprite $AwsDistroForOpenTelemetryLg [20x20/16z] {
RSW73W9H30DHYJYndN__ymBRwwZEyvosEEKNz0lwYfpg4v4PGR7R9IlnBn05Id-BwIGH0bT3LQQLWkfiO7qgA2tMSfi598229fko1QRDpDsAVu5iQJC7aawA
bANn5rOYR2QoP6kC5cbcjmAU6tzSCsgt7UNLpjYhlU1umHy
}

!procedure AwsDistroForOpenTelemetry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/ManagementGovernance/AwsDistroForOpenTelemetry', $name, $tech)
!endprocedure

!procedure AwsDistroForOpenTelemetryCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsDistroForOpenTelemetryMd>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsDistroForOpenTelemetryGroup($id, $name='Aws Distro For Open Telemetry', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsDistroForOpenTelemetryMd>', $name, $tech)
!endprocedure
