' definition of the Item simpleicons-5/O/Opengl

sprite $OpenglXs [10x10/16z] uwS3

sprite $OpenglSm [12x12/16z] unza

sprite $OpenglMd [16x16/16z] un_X

sprite $OpenglLg [20x20/16z] unzKO1G

!procedure Opengl($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Opengl', $name, $tech)
!endprocedure
