' definition of the Item simpleicons-5/O/Openfaas

sprite $OpenfaasXs [10x10/16z] uwS3

sprite $OpenfaasSm [12x12/16z] unza

sprite $OpenfaasMd [16x16/16z] un_X

sprite $OpenfaasLg [20x20/16z] unzKO1G

!procedure Openfaas($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Openfaas', $name, $tech)
!endprocedure
