' definition of the Item simpleicons-5/O/Opennebula

sprite $OpennebulaXs [10x10/16z] NSUr0S0m0CJ03tDk_sc3hgpgbBf5tZZuuKLHwrTFzoAC9AEreJkJmPeJISRto0q

sprite $OpennebulaSm [12x12/16z] HSo50G0G441HtVpzjzNDuqAyeJvXtyPBZbd3JhP5m_jMN1j03Zfq7Lh_5kBuptfO-G6LrxzM2SZ634jfysehEW

sprite $OpennebulaMd [16x16/16z] {
LSq54WGn24JHZHlmxt_R9JNUfQyJuFV9_0fvKxXTGJ8m3Xf7f9vp9_ln_sHRl1s0UJltNQtDuYf79SwqmWID7IZkxYXPGL8NTutDOELYiCsgAKq0hS4TTzzI
IDEE-ycC8-u_
}

sprite $OpennebulaLg [20x20/16z] {
PP055iGm24JnQZBtl-q-oDQdcez3RqqVOi0RBNWo9dBSsPIdrkzinocvUmtHuNUIhdYpHV1YNLO0-vsPvLjZ80TwM3OoQn-nWKRb4tpsPvfvLerUPSej0N6h
R3nYtMJAEJQNvOZrz1FIZAoGbCPIWVlYOlFepq9pLRwXTFHt5z4F
}

!procedure Opennebula($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Opennebula', $name, $tech)
!endprocedure
