' definition of the Item simpleicons-5/O/Opera

sprite $OperaXs [10x10/16z] uwS3

sprite $OperaSm [12x12/16z] unza

sprite $OperaMd [16x16/16z] un_X

sprite $OperaLg [20x20/16z] unzKO1G

!procedure Opera($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Opera', $name, $tech)
!endprocedure
