' definition of the Item simpleicons-5/O/Overleaf

sprite $OverleafXs [10x10/16z] Om03RZukCCtFpy_63sAmymFP425EPWO8WuSV8WGXG2H41IgB4yo5ge7e

sprite $OverleafSm [12x12/16z] FSY50S0W3031KFVRVzeQpdCaybfTSnQS2e-Uo0w5IMAiqsDa_pXTNmTVBT4UM_RwPfVT_rMIFp8V

sprite $OverleafMd [16x16/16z] HOm30WGn4C2AhP7_l_Oqk9IZ1AEUUqVK82ACVqWV72rlU2fWiym0NasKoWeElG5C3I-fX91TJfLNTTciNGe3qugXaIJE8eWSysRrJ9cpGM1l80Rb0bPz0m

sprite $OverleafLg [20x20/16z] {
JOw72G1120JtStRwx_RnK7H8iWbLh8-PtLiJZ61DwM2m6uSI5-xvWLSjzkW6lbepbcb4Im9TxwB6XEa5E7fn6f9l1YltkdhyhIJKBAMLkCbPsa_65NEcv8i7
PthtZCFDjEFnAvS5r3BthEa0fff9LXKdpfEf7m
}

!procedure Overleaf($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Overleaf', $name, $tech)
!endprocedure
