' definition of the Item simpleicons-5/O/Oyo

sprite $OyoXs [10x10/16z] uwS3

sprite $OyoSm [12x12/16z] unza

sprite $OyoMd [16x16/16z] un_X

sprite $OyoLg [20x20/16z] unzKO1G

!procedure Oyo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/O/Oyo', $name, $tech)
!endprocedure
