' definition of the Item aws-20210131/Resource/Database/AmazonRdsProxyAlternate

sprite $AmazonRdsProxyAlternateXs [10x10/16z] Oy04t0mCpCmy81OJ47DoG5b04GWB9CZD2M9102uMDoC4y

sprite $AmazonRdsProxyAlternateSm [12x12/16z] TKe30G0139pPF-_R64zmhJvGJ8Ig5bpJaE6EZvfmJYfkEDYo-vA9H_uVH-s58m

sprite $AmazonRdsProxyAlternateMd [16x16/16z] dSUt0SCm54F1zm5cSlzrdQrKwhhZIdFi5apUWg_225lwlxtU5Cxx8KmwN03xGwaDjz7_3-EOph_pPSxdvjUn4fIs4qy

sprite $AmazonRdsProxyAlternateLg [20x20/16z] {
jSh73GCn44DHJf0qgVzsdMq5xDKVF3qGbrbkXJu8H_bSwpH4njTO7-QY4eNTaYNWctMeizbcisbU5zPrMFReJDCWSDSadpy1WKGOCMtsBulJca2JQQqL7kcM
07S
}

!procedure AmazonRdsProxyAlternate($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Database/AmazonRdsProxyAlternate', $name, $tech)
!endprocedure

!procedure AmazonRdsProxyAlternateCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonRdsProxyAlternateLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonRdsProxyAlternateGroup($id, $name='Amazon Rds Proxy Alternate', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonRdsProxyAlternateLg>', $name, $tech)
!endprocedure
