' definition of the Item aws-20210131/Resource/Database/AmazonRdsProxy

sprite $AmazonRdsProxyXs [10x10/16z] PSQr0S0m44MnP_R1_kk6VnLLuY-Wxu9554IhxLl2qYHBqp87KIvzpJm1

sprite $AmazonRdsProxySm [12x12/16z] ROl50G0n20Gd7jZ-wpttotnWZIUwlWwjLgoK7Fro8_VF_Piytpjq_NUdgxk6dHITxYj82ZC

sprite $AmazonRdsProxyMd [16x16/16z] VOk50SCm30HVJDv_tJ8toHdrW5zu-iq2XgCvg40N46X9roPpCp8K-gDAj_c3exdRS-WrKzp4zqnUIH-p0VYSEIhrq__fItHPO-51Neu447L3mQw4Cm

sprite $AmazonRdsProxyLg [20x20/16z] {
ZOtLOKKn3CNa66-S_TTj7pFfyo0lgRvZ6XGFjD3a5bkHCzJT3F6zPb4YkVEowQDsoz1d3NxIXZrsgqmjbjngYpqPTrhCxh9upd6lbU_txZN459wxsBtMQuS7
y-d3iPOpjjAZzuxu2GFH0Vm3
}

!procedure AmazonRdsProxy($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Database/AmazonRdsProxy', $name, $tech)
!endprocedure

!procedure AmazonRdsProxyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonRdsProxyLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonRdsProxyGroup($id, $name='Amazon Rds Proxy', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonRdsProxyLg>', $name, $tech)
!endprocedure
