' definition of the Item simpleicons-7/Q/Qgis

sprite $QgisXs [10x10/16z] LOg30G0n54DpPllsdxRcPwHGBvTYaIk1H8qYIF3ZBCYow0J1chBlAtAEUfcX1m

sprite $QgisSm [12x12/16z] HOs54G0X30HnX-k_sv_DsoBnd8EfxWolcySTSLh01rXSYDB6xyCA1zy-gM02VVIpEqGyjwHfcwbjIGhXLnDT5m

sprite $QgisMd [16x16/16z] NO-50SGm30DLvjx-qpv8nLpGRClq6qkj4muMInKtfxMJD4VXszJ088jX0aROdubtcFtR2fdDztHQ5EsP3y6ioFkPRDQKzYhBIJLWwajHFHKPQOi9-08

sprite $QgisLg [20x20/16z] {
JP274S0W30FfS7A2zvysHJH_ckwjDDmWeEjTdG6wIDDujLXrIn_Ntp4LZgyfXJTCgdvuri9oR4YSDVi-uSCEEl5VBhmErxTZeCDtrC_b-LI-Shq3wW1GSX0f
6Jy91oQY8_gPybcUDIR1o72ad2QCf2EXGH3zMAuN
}

!procedure Qgis($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/Q/Qgis', $name, $tech, $desc)
!endprocedure
