' definition of the Item simpleicons-7/Q/Qiita

sprite $QiitaXs [10x10/16z] Oo0MC78oyF8pCJ4my04vtFmC32343sBni_7Zrme

sprite $QiitaSm [12x12/16z] Oo0PCCDPJ0mC_0mCR9ny32pCV0mCl40kI0n8SO7OG04-Nb9D1m

sprite $QiitaMd [16x16/16z] jSa50O0030J0mttVFosM0IQl_fxQqzkLWAKX6et4agrml6rO3KfJho_YOEfs_RsczpwU2m

sprite $QiitaLg [20x20/16z] pSZ70SGm4CGmo3cjflzgBxe8uqTwadPS6nXO06dsCfGOpW5SCxgss6orEUfC7r26KpW8vr2qtEyab2KVzqk-sK7p26y

!procedure Qiita($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/Q/Qiita', $name, $tech, $desc)
!endprocedure
