' definition of the Item simpleicons-14/J/Jirasoftware

sprite $JirasoftwareXs [10x10/16z] BSU53G0m3CH0Lr26_RUjh73kiJfP-oLVUy5dIH-o22JT4r4AcP223m

sprite $JirasoftwareSm [12x12/16z] DOc35K0n54C_Qku_RN5pdiA7II3ppM1of6bcJ3UlGMg2P03ZUwFJGW5KWXcICWqf4n4oq0O

sprite $JirasoftwareMd [16x16/16z] LSg54O0040F1u4xwhnQz83-MlNbnlNxNkljoNUtsGzi4E16W1nFoh0JVP7H5gEPU7G5AxJMAC6612HLC6612pKnWx

sprite $JirasoftwareLg [20x20/16z] {
POo50GGn20JvFurk_zMUGv2DJmP8ibD8mkfH1U3ClbxCci06MBC3k9OstnUq-Hfjnp3nXcWNipCIkFxuKvTylPD2Kf4K8ZOtGRet8sKcHigiZ9HP62bp8vzb
M2S
}

!procedure Jirasoftware($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/J/Jirasoftware', $name, $tech, $desc)
!endprocedure
