' definition of the Item simpleicons-14/J/Jss

sprite $JssXs [10x10/16z] Ou037cu80BAW8hXP_ApyJFpyO1Od7mC_4vW5GY0MFoEGmSUFC1a

sprite $JssSm [12x12/16z] Oy01UCXXyxBoypFmyqFOlEmCJBnGSGPMVWOca3W_EoS_CpyN1nyF3di1

sprite $JssMd [16x16/16z] lSUr0SGm0C101StM_jC-CtQvxlYZRd9PDADURuHHk1uTqFLs5c7qU2SnHdERJX_B22b3A6DT7_1k3m

sprite $JssLg [20x20/16z] lSYr0SD04031lNinRV_LcZanQyBXHTDuxt0yMFaIeWHGydn5QZLHn-ivawG4r-jT0CsRezQMc9rk3aQ1z72MMPnoSR3gZpTeW0gBDXEVsm8

!procedure Jss($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/J/Jss', $name, $tech, $desc)
!endprocedure
