' definition of the Item aws-20210131/Architecture/Compute/AwsOutposts1UAnd2UServers

sprite $AwsOutposts1UAnd2UServersXs [10x10/16z] FSOt0S1040InpxFy4TiNLGbuvbwwT84ni0cChIlTSyxUyv-c6SXWrFq

sprite $AwsOutposts1UAnd2UServersSm [12x12/16z] JSV50G0n4CF0a2Ftt_11SFNI07qc4K000K2cQhn1G1dlp6XyLnhfUnSrMbFxtsRc00Uy

sprite $AwsOutposts1UAnd2UServersMd [16x16/16z] NOu54iH02C1ciV3_3vy1rvQC9Yi048Exqs4AAr1iv-vgfXCIC72pzkHGbyPxng4y3xDCUGeuNptjNjWXic38PdkEh_06

sprite $AwsOutposts1UAnd2UServersLg [20x20/16z] RSg53S0m4CNGuFTr_u7BuLZyP9xKodVCg6BCDgCexOp9iWjEZ1O07t8nUpz0U8ePYhp9LxD8AL4igrZv7WpfBTxvtooGl9U_YwbOz3K7iZ-wR8EsGTlWiS4B

!procedure AwsOutposts1UAnd2UServers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/Compute/AwsOutposts1UAnd2UServers', $name, $tech)
!endprocedure

!procedure AwsOutposts1UAnd2UServersCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsOutposts1UAnd2UServersMd>', 'Compute', $funcName, $content)
!endprocedure

!procedure AwsOutposts1UAnd2UServersGroup($id, $name='Aws Outposts1 U And2 U Servers', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AwsOutposts1UAnd2UServersMd>', $name, $tech)
!endprocedure
