' definition of the Item aws-q3-2022/Architecture/Containers/AmazonElasticKubernetesService

sprite $AmazonElasticKubernetesServiceXs [10x10/16z] FOg50G0X54AvmCV-2zlwamBAA9iB1vBL8RXFbqfuPk0jIKU2XSmdTnJ1Y7Gq0njbe0O

sprite $AmazonElasticKubernetesServiceSm [12x12/16z] HSU70S0W30F1191V-ozCBwud85P9l31DaKOOJ2Z-RNu6mvCnWptyRRiR_NcwSywmev00F4iyUxe1

sprite $AmazonElasticKubernetesServiceMd [16x16/16z] LSY70S0W00916xpxJnnCbnIz9_CpIMp1yHukg-RvN3rarTiQgpIxovvnYXdHyem7QlZsF5t-NazBUqmVULM9iuWEJH1dL51ADg-fmEUrpriu

sprite $AmazonElasticKubernetesServiceLg [20x20/16z] {
RSZ50GD1300nypZz5tou3kifJlMI1rQ-pF7lAA-SdH9DbuypnpBBV8vKGF8CoNKAOKLgLDbnVPzZABQkvwHUrtDWpBL2ODVuwv04NALodGUaXXO8tDSbN481
pZk5GMbowI7gC3VWTR_v-9Cx
}

!procedure AmazonElasticKubernetesService($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Architecture/Containers/AmazonElasticKubernetesService', $name, $tech, $desc)
!endprocedure

!procedure AmazonElasticKubernetesServiceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonElasticKubernetesServiceLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure AmazonElasticKubernetesServiceGroup($id, $name='Amazon Elastic Kubernetes Service', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$AmazonElasticKubernetesServiceLg>', $name, $tech)
!endprocedure
