' definition of the Item aws-20210131/Resource/Containers/AmazonEcsCopilotCli

sprite $AmazonEcsCopilotCliXs [10x10/16z] PKU50G0m067f_uVNFGqRiXAqBjUs134VYyDQROhuGSI93

sprite $AmazonEcsCopilotCliSm [12x12/16z] JSo50S0m2031ZyB-4vUlNpm8Vn7ERDuRykLTMPVqhZc9kWVQU2U_koUixdqCKD9wOvUlluB-QWS

sprite $AmazonEcsCopilotCliMd [16x16/16z] NSs50O0m40F0v7t_XT5we79VmncINtF-JY541Ed9pqzhOyHg0d0VXhspUZmg-HlL7Cr8hXw5OVDsm3-7eCSV9y5uqnvPKwXS4pXo0m

sprite $AmazonEcsCopilotCliLg [20x20/16z] {
VSZN0K8n3CLGnVNklp0jptJGdmx_MukZbXnT8jNin9JBEZyCbkhL0i3bOtiNi1A1CsMFwO4rHiMdKVbfP7rQ7MQoiGwcx6tYkOL02sgtLRor4gstBF5-Zs-T
0G
}

!procedure AmazonEcsCopilotCli($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Containers/AmazonEcsCopilotCli', $name, $tech)
!endprocedure

!procedure AmazonEcsCopilotCliCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEcsCopilotCliLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure AmazonEcsCopilotCliGroup($id, $name='Amazon Ecs Copilot Cli', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$AmazonEcsCopilotCliLg>', $name, $tech)
!endprocedure
