@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureSupport element
include('elements/azure/GeneralServiceIcons/AzureSupport')
AzureSupport('element', 'Support', 'an optional tech field')
@enduml
