@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the GcpCloudSpeechToText element
include('elements/gcp/AiAndMachineLearning/GcpCloudSpeechToText')
GcpCloudSpeechToText('element', 'Cloud Speech To Text', 'an optional tech field')
@enduml
