@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/gcp')

' loads the GcpCloudDataproc element
include('elements/gcp/DataAnalytics/GcpCloudDataproc')
GcpCloudDataproc('element', 'Cloud Dataproc', 'an optional tech field')
@enduml
