@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/gcp')

' loads the GcpCloudDataFusion element
include('elements/gcp/DataAnalytics/GcpCloudDataFusion')
GcpCloudDataFusion('element', 'Cloud Data Fusion', 'an optional tech field')
@enduml
