' definition of the Item simpleicons-8/F/Fujitsu

sprite $FujitsuXs [10x10/16z] Oy05-Fcv-5aHF900cCK9PeF5-A0oFFmiN0mCR0pS_4mWPK1nL

sprite $FujitsuSm [12x12/16z] VS650G81000XxFRsdzRkU31eKcq1OPkdg82zc0NQBZ4F-pPhJ2RLXiQckQczRqS

sprite $FujitsuMd [16x16/16z] ZOkr0GCn0CGKC8FsdpRuL5hL8SkKdYwkwz2osomVWlkaNEBx4m9_vAOgXtS2U_2m26VWt1ijeJj9Vn-eQe3_VmOEL0Uhl04

sprite $FujitsuLg [20x20/16z] {
hOzL0aGX203nfSdS_xGRjfyROz8W_y41H3Eh0E-1SwWIkxmmC3orlWRjEZjolAwm9d781YYahWi87FdJbN1nvryaIkR2AxqNBJPUtv47o8aFVDPS9cjroxro
vGRMEJCg2sTCOPClU08
}

!procedure Fujitsu($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/F/Fujitsu', $name, $tech, $desc)
!endprocedure
