' definition of the Item simpleicons-8/I/Internetarchive

sprite $InternetarchiveXs [10x10/16z] HOp50S0m3CJKXdd_QSEWbtt4834ect0lWvq61Y9Iz2j0Hgb-nT5JSbs1_--N0xCQYhVI

sprite $InternetarchiveSm [12x12/16z] ROs50S0W30GFTxB_j7KlSVrd5TFOnCif41yrWGHMhP66G35hfA-nsRlkRbnNkyRzD--_yS3CBwuP

sprite $InternetarchiveMd [16x16/16z] TOs53O105CMAm-d-sv9pRwJv-WWyUYFnsiG5R7SDO6k0R-DudU6v07iWh3DewNmYKwtQsXZd2xMkstqT_hV_sZnNNx6Mhdvgu6pgxGS

sprite $InternetarchiveLg [20x20/16z] {
VP053WGn4CFA3F__xINfCLcgDUlbcXjrUlE4gsiVHhGCQR_H4ViR4Ms_aT5yvHiCbNG4oeOs9pugQsgmsvPju5gr0OVjsIRUg3RXk0FRqXLWgSL_xVtUUTgn
lx-ZgNLzYtl-5jdUlw-ePPfBBMeoLeiwq_TzIVsDPYu
}

!procedure Internetarchive($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/I/Internetarchive', $name, $tech, $desc)
!endprocedure
