' definition of the Item aws-q2-2024/Architecture/SecurityIdentityCompliance/AwsWaf

sprite $AwsWafXs [10x10/16z] RSUt0G0X4CJ0nQF-2tx3cGX58wu9gGG7pT3wOXrHDZhQ34xjx6dfC7i1

sprite $AwsWafSm [12x12/16z] TSh50SC034FHcltt7xXXJjx58F79eALPI7GHFkzH_4016iALkINLY9Rb_9zVjVH9AObvTscl45PBzsm

sprite $AwsWafMd [16x16/16z] bSUt0GD1202m1-uUjF_0pcuTrCd_WZEF6kCfJbhFydI68vdzAb6Ll9xahWmQ72r5RXMWs4ZJO5grtihJZ5d4ksjlQqhmrj4eNrq1

sprite $AwsWafLg [20x20/16z] {
fSkt5GDG24DHChpz1tOsvvSEjmD9_6TuI4u29IgYKFlKAMY82iwc9E3xgMBA900xMkCItj3DamBHMb9R36a2jCPncTqQ1GG4-yj9o2PvImXDgyJsLxwBVSLO
4wIX7Dh4jxc6Rrq1
}

!procedure AwsWaf($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Architecture/SecurityIdentityCompliance/AwsWaf', $name, $tech, $desc)
!endprocedure

!procedure AwsWafCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsWafLg>', 'SecurityIdentityCompliance', $funcName, $content)
!endprocedure

!procedure AwsWafGroup($id, $name='Aws Waf', $tech='')
  IconGroupElement($id, 'SecurityIdentityComplianceFamily', '<$AwsWafLg>', $name, $tech)
!endprocedure
