' definition of the Item aws-q2-2022/Resource/MigrationAndTransfer/AwsMigrationHubRefactorSpacesApplications

sprite $AwsMigrationHubRefactorSpacesApplicationsXs [10x10/16z] Oy04Z10IpcA1i12o75nSN8mSN40MAv35pCe5bUM0gkDaOGAncA206G

sprite $AwsMigrationHubRefactorSpacesApplicationsSm [12x12/16z] JSQ70S0W20NHiolx3npWfvq2Zt-rF1qARC-FxE-pVIvU-fHcjds7cSkgRxS_IlKTZYOytgJFcrq

sprite $AwsMigrationHubRefactorSpacesApplicationsMd [16x16/16z] NSU50K0X203HiwZzz_qTw1dmM0kVmidTBhMquiaCmxBhui2o_IXUU_7I8yvvkMATA7hCo-xTY56EUHckpu3iaKoOaNtqUaft

sprite $AwsMigrationHubRefactorSpacesApplicationsLg [20x20/16z] {
RS-5aS0m30NHDOX-__qUX6c7D2ynyLNfMKSyQhjb_MStAsWG3yiSBnlJNrRnjiPjRRFjbjxcPfPDg2lQCYsMO1g845XRp0mXrCSoBOOvOnA8wPTp7I3lxnq6
w6vKJlM7qHeSrX-DJd_5Bm
}

!procedure AwsMigrationHubRefactorSpacesApplications($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2022/Resource/MigrationAndTransfer/AwsMigrationHubRefactorSpacesApplications', $name, $tech, $desc)
!endprocedure

!procedure AwsMigrationHubRefactorSpacesApplicationsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsMigrationHubRefactorSpacesApplicationsLg>', 'MigrationAndTransfer', $funcName, $content)
!endprocedure

!procedure AwsMigrationHubRefactorSpacesApplicationsGroup($id, $name='Aws Migration Hub Refactor Spaces Applications', $tech='')
  IconGroupElement($id, 'MigrationAndTransferFamily', '<$AwsMigrationHubRefactorSpacesApplicationsLg>', $name, $tech)
!endprocedure
