@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('domainstorytelling/bootstrap')

' loads the Item which embeds the element SolidAurora14Group
include('domainstorytelling/Group/SolidAurora14Group')

SolidAurora14Group('SolidAurora14Group', 'Solid Aurora14 Group', 'an optional tech label') {
  note as note
  the content of the boundary
  end note
}
@enduml