' definition of the Item simpleicons-5/P/Pagerduty

sprite $PagerdutyXs [10x10/16z] uwS3

sprite $PagerdutySm [12x12/16z] unza

sprite $PagerdutyMd [16x16/16z] un_X

sprite $PagerdutyLg [20x20/16z] unzKO1G

!procedure Pagerduty($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Pagerduty', $name, $tech)
!endprocedure
