' definition of the Item simpleicons-5/P/Pioneerdj

sprite $PioneerdjXs [10x10/16z] RS450e80002nsUtz_xLs0fj9LMiGww1OfRIdrB8ApJmLK5i_hW

sprite $PioneerdjSm [12x12/16z] TOdL0K0n30AfUs__QP_sDnS5P19IIk7y41Fa_z_l8kIiXPCwmu50Sl2EuwNgpmzmdWKuMTm

sprite $PioneerdjMd [16x16/16z] bSVL0SDG34Mn6qP7-qzRfi_cFB2Lyu6QtcoP-Wal7oJfM9vcVer21fxq_AWa6rqQshkdGfALB7LhdtEFBJyjD1_KWJ6VXd7eyaTN

sprite $PioneerdjLg [20x20/16z] {
hStL0SCm34NHPsRV_QSjX9FVzfX1alulieaw3AZUPw1h1-pVjIdGzZUJ-eS4U7q4G1MOSi3-hInpKeEgZmb8Pfa1RqDZ-QKCKvvDFUh8BemMM-YD1R8knWIe
ppyZwrTl
}

!procedure Pioneerdj($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Pioneerdj', $name, $tech)
!endprocedure
