' definition of the Item simpleicons-5/P/Planet

sprite $PlanetXs [10x10/16z] DKk30G0n4CkpRlUVzcm4a6ZxWyQnsV800fQtDkUrGkFqN2d-TMobChxg9WO

sprite $PlanetSm [12x12/16z] HOk50SCm40FD3FjlMv_S9FSCCj1MCPTDSihzMscsf4aQEyrpROtUwQmOzjQY7rSMpvvzG3mv5ciWwrFeQpRIsVu

sprite $PlanetMd [16x16/16z] {
LOm55e1G2C2c_Wwu_saDUDP-Zi88Gzh2pPGLY9fSzSwaQSh3Dc1wrk-w8bTyweaLX_LotQ1DG0Rczw2iVu_DFUEbTKdcG_LI17tgtLC2Rf_NsRXf4M3KkzWK
LfMIcWZ00G
}

sprite $PlanetLg [20x20/16z] {
JOw50GGn20GtRaZ_rRu09tEQIO15i4IeuSLG6hNKAPmHAE52LtpVDRH3lU46ZAimfIYpstxqHyMFEK7kT25jJJvdXBDUzXOfxhgLcJjQNhcMEshkh9LQE6hJ
7IcpNXaa-jLpHgG6XyE5D6IVVxkg01RXZVVS_9WQsT1qXhB9mLIXGyeUzWi
}

!procedure Planet($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Planet', $name, $tech)
!endprocedure
