' definition of the Item simpleicons-5/P/Polymerproject

sprite $PolymerprojectXs [10x10/16z] uwS3

sprite $PolymerprojectSm [12x12/16z] unza

sprite $PolymerprojectMd [16x16/16z] un_X

sprite $PolymerprojectLg [20x20/16z] unzKO1G

!procedure Polymerproject($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Polymerproject', $name, $tech)
!endprocedure
