' definition of the Item simpleicons-5/P/Poly

sprite $PolyXs [10x10/16z] Oq00VduuamlEvWS228ERWO6F7yo2YdE2TK3a-U7gm2Gg2m

sprite $PolySm [12x12/16z] NOo50S103099wdhxJrjzZmkWKTd0yd9ofjc0ESoSFeVbu2ap_td_QWyk-CJO_hOIfDXMJbEOlzREDm

sprite $PolyMd [16x16/16z] TOw30GGn44NNSLx_rHusrjZpjsThIIAQ_0REfcB0znF8d0fm5apA8Tf01p8x-uvVOSmO_aCoR4g0CmG_Y2UW0Zu2sOptq63tBUSXNEQ-IRy

sprite $PolyLg [20x20/16z] {
dS-53GGX443HTPpVVxSNN6CtCV8OFUvZZHkpCP0plW3Fh3heP0hc1euO_IoHKdJVj2JurlEiJmXBYB1VRm0gsXdf8OGzyntH8btrDlyz8eZexftt2_qqeCzA
tTm_pDyp_G
}

!procedure Poly($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Poly', $name, $tech)
!endprocedure
