' definition of the Item simpleicons-5/P/Privateinternetaccess

sprite $PrivateinternetaccessXs [10x10/16z] NOdL0O1G08ImM_QVrlOLNtS0q5dnuCqxDh2z5zGe-39Oh2QizLdJdq5jLKu

sprite $PrivateinternetaccessSm [12x12/16z] POg50O103CI2Ezb_MbnUKkyT9uCDDvKdz-vIm7qqCb2NtcRgfiBoTFYIxSloxnsvPnYyMO1MvIns

sprite $PrivateinternetaccessMd [16x16/16z] TS_50SKm3C1GbHkmjV-qdndUBJ5prIqyUT6UpvpPjNAnckoKGU_XyVockjxUK6jbiG2BsYz21QtUTPS_x-NZ3VaUd_Dd_SmGFjG0nkUxFAuRMDKDZW

sprite $PrivateinternetaccessLg [20x20/16z] {
VSx50SKW403HmPtjlzelSMLEcnUC9TUaA8u5cUe7pRAcLp8YRTh_mzN-Oql87-rc7cz9i2tKqw2rtit5qobUhS_O-dr2lfaUMahzPiR4cu6_MQtxtdIxGq4A
9qm1oFbaZQbfBdQzQxCAQhKl
}

!procedure Privateinternetaccess($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Privateinternetaccess', $name, $tech)
!endprocedure
