' definition of the Item simpleicons-5/P/Processingfoundation

sprite $ProcessingfoundationXs [10x10/16z] uwS3

sprite $ProcessingfoundationSm [12x12/16z] unza

sprite $ProcessingfoundationMd [16x16/16z] un_X

sprite $ProcessingfoundationLg [20x20/16z] unzKO1G

!procedure Processingfoundation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Processingfoundation', $name, $tech)
!endprocedure
