' definition of the Item simpleicons-5/P/Pubmed

sprite $PubmedXs [10x10/16z] LSQr0SG000GWNk9o-qyRLoee79gSgnEfeChclq-4yhL83P5VG5ke4wUO0G

sprite $PubmedSm [12x12/16z] LSl50G810CJ0uCxqNorwcjTgIpQizNRI1nWqJrm7dVlUf4k5_Rt3Jpz8UlxUxdZgY-f4Cte3

sprite $PubmedMd [16x16/16z] NSZ50O1G081GRFt5_jFQpUq1L7oozMjjVWvqK_-oIJMVVXeUet4mN4uejV5oJPFXCIE4jmM9c_jnT-wbsmoL9QcMV9WKW44ztPxxybKRMG

sprite $PubmedLg [20x20/16z] {
RS_50O0m5C3GuDOs-q-BE-JugX-WubrPL-5jdVgsLaq_9gZDqtBN-jqQrUXUUPccJWt1uJ8xL2e5g8z3dO7iOO05FAqcqh_Cd5pQrQgLQkmP1DdQ1oaqEotJ
45LDyJ1wgsFAq-ZEsI_Bhblu5c02
}

!procedure Pubmed($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Pubmed', $name, $tech)
!endprocedure
