' definition of the Item simpleicons-5/P/Pyscaffold

sprite $PyscaffoldXs [10x10/16z] uwS3

sprite $PyscaffoldSm [12x12/16z] unza

sprite $PyscaffoldMd [16x16/16z] un_X

sprite $PyscaffoldLg [20x20/16z] unzKO1G

!procedure Pyscaffold($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Pyscaffold', $name, $tech)
!endprocedure
