' definition of the Item simpleicons-5/P/Python

sprite $PythonXs [10x10/16z] Om027dvs1Z3Wv-NdvuUmG014mm0tb8P8iB2m02aEX02SXT0BOR43MG

sprite $PythonSm [12x12/16z] HSp50G113090u5pflzfrcKyyI9RF5wfhST9oPqmPpoJbkWatiZytcxCVwxhcjITt6jZNoA6KIvh__vV8s1OG0G

sprite $PythonMd [16x16/16z] NOw30G0W54Glk_QVDll5xqF7nkGf5Yh5r5YsKQJRPDdTMhRIZMPJQu1qOFN8owRfmQq-4OnNVFk7rlVheIyRzPXZIe3IPjCA7drnwzMpSjbOlIe5

sprite $PythonLg [20x20/16z] {
TP250KKX30E3Ezb_skVIVZdyyE8aTd8a23mlykiACKufNUI94OxQ-NnoE5jh03ebZcGqLDYzQlnQfndcFMd2-9t05qD5tgka7VQgADMGlnmsh3sStS6__qfd
hN3XT2a8XwJYl08
}

!procedure Python($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/P/Python', $name, $tech)
!endprocedure
