' definition of the Item simpleicons-5/G/Garmin

sprite $GarminXs [10x10/16z] Oo0Li3FmCp3m0Xay34oSF4069mCF3tuj

sprite $GarminSm [12x12/16z] Ow0Au6Pcu6FWOkDZOE1Yv-JcOcJYOEDauETYP-OdrIG

sprite $GarminMd [16x16/16z] lS6r0G91002m_BdV_jjIKoE9lvhUbCjPXdE5h1xzFBiKQvjT7RjhCObFW9WbN_O2

sprite $GarminLg [20x20/16z] pSYt0S0W402n8yF7_RUrUnP0fNXPuUQBozwGMH7SdKEohD63tNHZMv1b_vtQgvvXuefHZ_At3Hxo0G

!procedure Garmin($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Garmin', $name, $tech)
!endprocedure
