' definition of the Item simpleicons-5/G/Gitkraken

sprite $GitkrakenXs [10x10/16z] uwS3

sprite $GitkrakenSm [12x12/16z] unza

sprite $GitkrakenMd [16x16/16z] un_X

sprite $GitkrakenLg [20x20/16z] unzKO1G

!procedure Gitkraken($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Gitkraken', $name, $tech)
!endprocedure
