' definition of the Item simpleicons-5/G/Gmail

sprite $GmailXs [10x10/16z] Oy02-FZvmJG_482OpFmu0L0D9qWTN0U2XJ0F

sprite $GmailSm [12x12/16z] TOk30S1G50ElThF_jEKtxXcXGY-PJXyDCCWmSoXd-VB_zCbeJS-Ex_dwCUW9k04

sprite $GmailMd [16x16/16z] XOg30K1134DpThF_jD_cExG1_aXftrLnXQHQfEE2dsJXHWN04uxlf4i7Ulm5UjM0CEEeeN7MM7IxQ6YjLxti9te

sprite $GmailLg [20x20/16z] fSl50GGn509GuXxwhtOzUjcHT_e2k46G1HD3vieNZIQnYwsqm8lYnY3oYi36i87cHuPa0u0l0UiDWGhBhJbt4-LbkhssY8EU

!procedure Gmail($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Gmail', $name, $tech)
!endprocedure
