' definition of the Item simpleicons-5/G/Goldenline

sprite $GoldenlineXs [10x10/16z] BSP50G0n0C2m7iEW_jMEymh0boywXmzSBdG3ahvATrtE7NhEeMWQaTS9E5Sg

sprite $GoldenlineSm [12x12/16z] FOg54O1G3CLmX-m_BLzoRKwU3ethsmT1j4YtZyqxT6kuF4PCSuJV8GVqhECExAsGhwqFs1O

sprite $GoldenlineMd [16x16/16z] JOy50e0W34N7fFF-jtL5FEk750Y-p-PWqvSIrQx3K7lf08E_7-M91KeD0hBqrZADf-3QG69TxrYtnq_Mz2HGpFCgJ94THHdrkJ1jgh4kuHxdEH2gcwn_

sprite $GoldenlineLg [20x20/16z] {
RSs55SCm30HGcU55llstRKN5_A25v1QVgz673iSvGlYmB7JmQLlLjnQpfcGpGtXP8iEMjtUm9giEkJtnLomlWQzOWRXkObLUcSBM4dbnX9ATE88HGgCCDN8g
6x5nuXk9XK-5LFskCj7FZSG3
}

!procedure Goldenline($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Goldenline', $name, $tech)
!endprocedure
