' definition of the Item simpleicons-5/G/Googlemessages

sprite $GooglemessagesXs [10x10/16z] uwS3

sprite $GooglemessagesSm [12x12/16z] unza

sprite $GooglemessagesMd [16x16/16z] un_X

sprite $GooglemessagesLg [20x20/16z] unzKO1G

!procedure Googlemessages($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Googlemessages', $name, $tech)
!endprocedure
