' definition of the Item simpleicons-5/G/Googlechat

sprite $GooglechatXs [10x10/16z] Os1Wu8S091OB6302ML0H_2nkRXWBrJG6A

sprite $GooglechatSm [12x12/16z] ZSQr0G0X002nUnTi_sbnhqWLO3E914m1w2ZSP5VtT-cw7QOV4U5K3W

sprite $GooglechatMd [16x16/16z] Om02HduuO0Rn-P409f-HaGC2sFc0V6H9LZG-1xNvOCSGvlD003S3XC_2W0pGk

sprite $GooglechatLg [20x20/16z] lSYr0O1004MnXpliFotk_8Qpb64H3NVHUiD3BsxGbzv4xNh3GoQk37Jz-vgcuNs0wN5SnOieH4q

!procedure Googlechat($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Googlechat', $name, $tech)
!endprocedure
