' definition of the Item simpleicons-5/G/Googlepodcasts

sprite $GooglepodcastsXs [10x10/16z] uwS3

sprite $GooglepodcastsSm [12x12/16z] unza

sprite $GooglepodcastsMd [16x16/16z] un_X

sprite $GooglepodcastsLg [20x20/16z] unzKO1G

!procedure Googlepodcasts($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Googlepodcasts', $name, $tech)
!endprocedure
