' definition of the Item simpleicons-5/G/Googlesearchconsole

sprite $GooglesearchconsoleXs [10x10/16z] JKg50S0m36A-6ln_RTsY6FOIoJ__GwrmQHRnTi2LblHF9BoX8PIv9ae

sprite $GooglesearchconsoleSm [12x12/16z] NSR50GCn00InDREd_sgJOz9B-XZ0t6RjiDPYhSIbGDlr1lJ1OQ8JamR1IFCy4jTXktNE28mG3H18_04

sprite $GooglesearchconsoleMd [16x16/16z] RSc55GCW40JHnPtflziSSVlelDC_0RDVZOpd5cKCXZctanhlN8VvWkc-BUxcQLuc6xrffp7IbCfROurxwsMTtjhSvzD8G5LZedWeWAoLr0yvEuh-0W

sprite $GooglesearchconsoleLg [20x20/16z] {
TT250OD040NHmNNtzzzjSee_VF3Zsx878oSo3sm-jv5W5qcZ2mTwtT7fbMrMkFiQak_CewfTSj_zOlilSgwaV-iiW0deSajVmon0rwRO5kvjbDrQq5zQZ4Pg
d0Q3qBfodQ0qchRf8uWhMdu
}

!procedure Googlesearchconsole($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Googlesearchconsole', $name, $tech)
!endprocedure
