' definition of the Item simpleicons-5/G/Googlecolab

sprite $GooglecolabXs [10x10/16z] Oy0EE82O4uXP-I60avaVo0DZVY09vG59Hduc1ZOW2mZOGHYROG

sprite $GooglecolabSm [12x12/16z] ZOZL5SDG3CMKv35f_srx_5-oB_FNgOOSq7MQpZEjNj05XeRj47miK4p4iDGJueQfDQJmwLu

sprite $GooglecolabMd [16x16/16z] dOY50SGm30CLvjp-qpxO4xHd4EW5CPeabmamTG6oj1T0mkX9LfO3GMgmk9AiDO7jHYuDt4mNSMwCjz5wo83-3sR5a1GltAW6B3tc2m

sprite $GooglecolabLg [20x20/16z] {
jSo5RG0n44JHCRD__zr67kKwI9vWUVKVMe-ETHHPl3nLst59IWLB_1eIZ5FoF0kegJ4P2ROUu8i7_3z0rpDvd2QeJZfCACvXEHwG__dMJogWlGzxGMLormNo
ExBMlkITkPX1-G8dwS_z
}

!procedure Googlecolab($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Googlecolab', $name, $tech)
!endprocedure
