' definition of the Item simpleicons-5/G/Gravatar

sprite $GravatarXs [10x10/16z] BSU50G0m20F1kil-qwBv2aVGVhCHmvTca76_LaLwvSr_8FsZgGar6QugOtvFLu01

sprite $GravatarSm [12x12/16z] DOk75O0m44BFtcN_RUK-JpG9jO1s7cWZ95ocy6VpyJishrEwf8B_eqliTlE0tGPzuJf3DpRWBUCnmVq

sprite $GravatarMd [16x16/16z] HOy75e0W5CFgtkR-j_Mr7nzL866ZoimrI3quQt3WQixJXkRctD833FRGQDeKrmiieVB1My3rkqZEq5r-XPAur_oQlRn77twrkXuoMbCValw2cwx9MFQQFm

sprite $GravatarLg [20x20/16z] {
JOy54i0m40AfU_d_QokGCDaAautTeRBod568-hbw5BhlOs6p8jd5SI-A5nWcO57AOP3qiiC1nvg1OzOzttV6EU_l-ukwuungRDofMty6L3TheOZJRuWwrC3L
BfpSGC-VEQkqO6Em-jdPCkIKWB1QNAxq1G
}

!procedure Gravatar($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/G/Gravatar', $name, $tech)
!endprocedure
