' definition of the Item aws-q2-2023/Resource/Compute/AwsElasticBeanstalkApplication

sprite $AwsElasticBeanstalkApplicationXs [10x10/16z] Oq01BCmCh606EmC6G8Ypm1Mmi8Deg1XE5W

sprite $AwsElasticBeanstalkApplicationSm [12x12/16z] ZKkr0G0m2CFv_s9ywbIS2Bo1nkXxMhNlZTKwmC0oI0KLMdNE8IPSVS_pVjy9

sprite $AwsElasticBeanstalkApplicationMd [16x16/16z] dSk30KDH343H6-y_SVjjdyU84r6PnIYjIqqXWEaOYtGnIQ_B1oYzw4SSUjAdOehDWMHKYZLdOiAAy3tU-WC

sprite $AwsElasticBeanstalkApplicationLg [20x20/16z] lK-53O0m4EHz_udhRd6WUff-pmzOrNH4s2YiOWEa65SSCQjRnq0geztPn3nZ1g5ZA2sg8GuXgO9-a45HuO29nkxb3U4hZOCtVFzZA-G1

!procedure AwsElasticBeanstalkApplication($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/Compute/AwsElasticBeanstalkApplication', $name, $tech, $desc)
!endprocedure

!procedure AwsElasticBeanstalkApplicationCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsElasticBeanstalkApplicationLg>', 'Compute', $funcName, $content)
!endprocedure

!procedure AwsElasticBeanstalkApplicationGroup($id, $name='Aws Elastic Beanstalk Application', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AwsElasticBeanstalkApplicationLg>', $name, $tech)
!endprocedure
