@startuml


include('azure-4/bootstrap')
include('azure-4/Item/AiMachineLearning/ServiceMachineLearningStudioClassicWebServices')
include('azure-4/Item/AiMachineLearning/ServiceTranslatorText')
include('azure-4/Item/AiMachineLearning/ServiceCognitiveServices')
include('azure-4/Item/AiMachineLearning/ServiceBotServices')
include('azure-4/Item/AiMachineLearning/ServiceMachineLearningStudioWorkspaces')
include('azure-4/Item/AiMachineLearning/ServiceMachineLearningStudioWebServicePlans')
include('azure-4/Item/Analytics/ServiceLogAnalyticsWorkspaces')
include('azure-4/Item/Analytics/ServiceEventHubs')
include('azure-4/Item/Analytics/ServiceStreamAnalyticsJobs')
include('azure-4/Item/Analytics/ServiceAzureSynapseAnalytics')
include('azure-4/Item/Analytics/ServiceHdInsightClusters')
include('azure-4/Item/Analytics/ServiceAnalysisServices')
include('azure-4/Item/Analytics/ServiceEventHubClusters')
include('azure-4/Item/Analytics/ServiceDataLakeStoreGen1')
include('azure-4/Item/Analytics/ServiceAzureDatabricks')
include('azure-4/Item/AppServices/ServiceAppServicePlans')
include('azure-4/Item/AppServices/ServiceAppServiceCertificates')
include('azure-4/Item/AppServices/ServiceAppServiceDomains')
include('azure-4/Item/AppServices/ServiceCdnProfiles')
include('azure-4/Item/AppServices/ServiceAppServices')
include('azure-4/Item/AppServices/ServiceApiManagementServices')
include('azure-4/Item/AppServices/ServiceSearchServices')
include('azure-4/Item/AppServices/ServiceNotificationHubs')
include('azure-4/Item/AppServices/ServiceAppServiceEnvironments')
include('azure-4/Item/AzureStack/ServiceMultiTenancy')
include('azure-4/Item/AzureStack/ServiceInfrastructureBackup')
include('azure-4/Item/AzureStack/ServiceCapacity')
include('azure-4/Item/AzureStack/ServiceOffers')
include('azure-4/Item/AzureStack/ServiceUserSubscriptions')
include('azure-4/Item/AzureStack/ServicePlans')
include('azure-4/Item/AzureStack/ServiceAzureStack')
include('azure-4/Item/AzureStack/ServiceUpdates')
include('azure-4/Item/AzureVMwareSolution/ServiceAvs')
include('azure-4/Item/Blockchain/ServiceOutboundConnection')
include('azure-4/Item/Blockchain/ServiceAzureBlockchainService')
include('azure-4/Item/Blockchain/ServiceAzureTokenService')
include('azure-4/Item/Blockchain/ServiceAbsMember')
include('azure-4/Item/Blockchain/ServiceConsortium')
include('azure-4/Item/Compute/ServiceDiskEncryptionSets')
include('azure-4/Item/Compute/ServiceWorkspaces')
include('azure-4/Item/Compute/ServiceAutomanagedVm')
include('azure-4/Item/Compute/ServiceVirtualMachine')
include('azure-4/Item/Compute/ServiceKubernetesServices')
include('azure-4/Item/Compute/ServiceMeshApplications')
include('azure-4/Item/Compute/ServiceAvailabilitySets')
include('azure-4/Item/Compute/ServiceDisksSnapshots')
include('azure-4/Item/Compute/ServiceOsImagesClassic')
include('azure-4/Item/Compute/ServiceVirtualMachinesClassic')
include('azure-4/Item/Compute/ServiceFunctionApps')
include('azure-4/Item/Compute/ServiceCloudServicesClassic')
include('azure-4/Item/Compute/ServiceBatchAccounts')
include('azure-4/Item/Compute/ServiceDisks')
include('azure-4/Item/Compute/ServiceImages')
include('azure-4/Item/Compute/ServiceVmScaleSets')
include('azure-4/Item/Compute/ServiceAppServices')
include('azure-4/Item/Compute/ServiceServiceFabricClusters')
include('azure-4/Item/Compute/ServiceImageDefinitions')
include('azure-4/Item/Compute/ServiceImageVersions')
include('azure-4/Item/Compute/ServiceSharedImageGalleries')
include('azure-4/Item/Compute/ServiceVmImagesClassic')
include('azure-4/Item/Compute/ServiceDisksClassic')
include('azure-4/Item/Compute/ServiceContainerServicesDeprecated')
include('azure-4/Item/Compute/ServiceContainerInstances')
include('azure-4/Item/Compute/ServiceAzureSpringCloud')
include('azure-4/Item/Containers/ServiceKubernetesServices')
include('azure-4/Item/Containers/ServiceBatchAccounts')
include('azure-4/Item/Containers/ServiceAppServices')
include('azure-4/Item/Containers/ServiceServiceFabricClusters')
include('azure-4/Item/Containers/ServiceContainerInstances')
include('azure-4/Item/Containers/ServiceContainerRegistries')
include('azure-4/Item/Databases/ServiceSqlDataWarehouses')
include('azure-4/Item/Databases/ServiceAzureSynapseAnalytics')
include('azure-4/Item/Databases/ServiceAzureSql')
include('azure-4/Item/Databases/ServiceSsisLiftAndShiftIr')
include('azure-4/Item/Databases/ServiceAzureCosmosDb')
include('azure-4/Item/Databases/ServiceAzureDatabaseMySqlServer')
include('azure-4/Item/Databases/ServiceAzureDatabaseMariaDbServer')
include('azure-4/Item/Databases/ServiceAzureSqlVm')
include('azure-4/Item/Databases/ServiceDataFactory')
include('azure-4/Item/Databases/ServiceVirtualClusters')
include('azure-4/Item/Databases/ServiceElasticJobAgents')
include('azure-4/Item/Databases/ServiceSqlDatabase')
include('azure-4/Item/Databases/ServiceAzureDatabasePostgreSqlServer')
include('azure-4/Item/Databases/ServiceSqlServer')
include('azure-4/Item/Databases/ServiceAzureDatabaseMigrationServices')
include('azure-4/Item/Databases/ServiceSqlElasticPools')
include('azure-4/Item/Databases/ServiceManagedDatabase')
include('azure-4/Item/Databases/ServiceSqlManagedInstance')
include('azure-4/Item/Databases/ServiceAzureSqlServerStretchDatabases')
include('azure-4/Item/Databases/ServiceCacheRedis')
include('azure-4/Item/Databases/ServiceInstancePools')
include('azure-4/Item/Databases/ServiceAzureDataExplorerClusters')
include('azure-4/Item/DevOps/ServiceApplicationInsights')
include('azure-4/Item/DevOps/ServiceAzureDevOps')
include('azure-4/Item/DevOps/ServiceDevTestLabs')
include('azure-4/Item/DevOps/ServiceLabServices')
include('azure-4/Item/General/ServiceCostManagementAndBilling')
include('azure-4/Item/General/ServiceAllResources')
include('azure-4/Item/General/ServiceSubscriptions')
include('azure-4/Item/General/ServiceReservations')
include('azure-4/Item/General/ServiceServiceHealth')
include('azure-4/Item/General/ServiceInformation')
include('azure-4/Item/General/ServiceRecent')
include('azure-4/Item/General/ServiceResourceGroups')
include('azure-4/Item/General/ServiceMarketplace')
include('azure-4/Item/General/ServiceQuickstartCenter')
include('azure-4/Item/General/ServiceManagementGroups')
include('azure-4/Item/General/ServiceHelpAndSupport')
include('azure-4/Item/General/ServiceTag')
include('azure-4/Item/General/ServiceDashboard')
include('azure-4/Item/General/ServiceFreeServices')
include('azure-4/Item/General/ServiceCostManagement')
include('azure-4/Item/General/ServiceResourceExplorer')
include('azure-4/Item/General/ServiceBizTalk')
include('azure-4/Item/General/ServiceBlobBlock')
include('azure-4/Item/General/ServiceBlobPage')
include('azure-4/Item/General/ServiceBranch')
include('azure-4/Item/General/ServiceBrowser')
include('azure-4/Item/General/ServiceBug')
include('azure-4/Item/General/ServiceBuilds')
include('azure-4/Item/General/ServiceCache')
include('azure-4/Item/General/ServiceCode')
include('azure-4/Item/General/ServiceCommit')
include('azure-4/Item/General/ServiceControls')
include('azure-4/Item/General/ServiceControlsHorizontal')
include('azure-4/Item/General/ServiceCostAlerts')
include('azure-4/Item/General/ServiceCostAnalysis')
include('azure-4/Item/General/ServiceCostBudgets')
include('azure-4/Item/General/ServiceCounter')
include('azure-4/Item/General/ServiceCubes')
include('azure-4/Item/General/ServiceDevConsole')
include('azure-4/Item/General/ServiceDownload')
include('azure-4/Item/General/ServiceError')
include('azure-4/Item/General/ServiceExtensions')
include('azure-4/Item/General/ServiceFile')
include('azure-4/Item/General/ServiceFiles')
include('azure-4/Item/General/ServiceFolderBlank')
include('azure-4/Item/General/ServiceFolderWebsite')
include('azure-4/Item/General/ServiceFtp')
include('azure-4/Item/General/ServiceGear')
include('azure-4/Item/General/ServiceGlobe')
include('azure-4/Item/General/ServiceGlobeError')
include('azure-4/Item/General/ServiceGlobeSuccess')
include('azure-4/Item/General/ServiceGlobeWarning')
include('azure-4/Item/General/ServiceGuide')
include('azure-4/Item/General/ServiceHeart')
include('azure-4/Item/General/ServiceImage')
include('azure-4/Item/General/ServiceInputOutput')
include('azure-4/Item/General/ServiceJourneyHub')
include('azure-4/Item/General/ServiceLaunchPortal')
include('azure-4/Item/General/ServiceLearn')
include('azure-4/Item/General/ServiceLoadTest')
include('azure-4/Item/General/ServiceLocation')
include('azure-4/Item/General/ServiceLogStreaming')
include('azure-4/Item/General/ServiceManagementPortal')
include('azure-4/Item/General/ServiceMediaFile')
include('azure-4/Item/General/ServiceMobile')
include('azure-4/Item/General/ServiceMobileEngagement')
include('azure-4/Item/General/ServicePower')
include('azure-4/Item/General/ServicePowershell')
include('azure-4/Item/General/ServicePowerUp')
include('azure-4/Item/General/ServicePreview')
include('azure-4/Item/General/ServiceProcessExplorer')
include('azure-4/Item/General/ServiceProductionReadyDatabase')
include('azure-4/Item/General/ServiceResourceGroupList')
include('azure-4/Item/General/ServiceResourceLinked')
include('azure-4/Item/General/ServiceScale')
include('azure-4/Item/General/ServiceScheduler')
include('azure-4/Item/General/ServiceSearch')
include('azure-4/Item/General/ServiceServerFarm')
include('azure-4/Item/General/ServiceServiceBus')
include('azure-4/Item/General/ServiceSsd')
include('azure-4/Item/General/ServiceStorageAzureFiles')
include('azure-4/Item/General/ServiceStorageContainer')
include('azure-4/Item/General/ServiceStorageQueue')
include('azure-4/Item/General/ServiceTable')
include('azure-4/Item/General/ServiceTags')
include('azure-4/Item/General/ServiceTfsVcRepository')
include('azure-4/Item/General/ServiceToolbox')
include('azure-4/Item/General/ServiceVersions')
include('azure-4/Item/General/ServiceWebsitePower')
include('azure-4/Item/General/ServiceWebsiteStaging')
include('azure-4/Item/General/ServiceWebSlots')
include('azure-4/Item/General/ServiceWebTest')
include('azure-4/Item/General/ServiceWorkbooks')
include('azure-4/Item/General/ServiceWorkflow')
include('azure-4/Item/General/ServiceBacklog')
include('azure-4/Item/General/ServiceMedia')
include('azure-4/Item/General/ServiceModule')
include('azure-4/Item/General/ServiceSearchGrid')
include('azure-4/Item/Identity/ServiceAzureActiveDirectory')
include('azure-4/Item/Identity/ServiceAzureAdDomainServices')
include('azure-4/Item/Identity/ServiceGroups')
include('azure-4/Item/Identity/ServiceActiveDirectoryConnectHealth')
include('azure-4/Item/Identity/ServiceEnterpriseApplications')
include('azure-4/Item/Identity/ServiceManagedIdentities')
include('azure-4/Item/Identity/ServiceAzureAdB2C')
include('azure-4/Item/Identity/ServiceUsers')
include('azure-4/Item/Identity/ServiceAzureAdIdentityProtection')
include('azure-4/Item/Identity/ServiceAppRegistrations')
include('azure-4/Item/Identity/ServiceIdentityGovernance')
include('azure-4/Item/Integration/ServiceSqlDataWarehouses')
include('azure-4/Item/Integration/ServicePartnerTopic')
include('azure-4/Item/Integration/ServiceSystemTopic')
include('azure-4/Item/Integration/ServiceApiManagementServices')
include('azure-4/Item/Integration/ServiceLogicApps')
include('azure-4/Item/Integration/ServiceEventGridTopics')
include('azure-4/Item/Integration/ServiceRelays')
include('azure-4/Item/Integration/ServiceAzureApiForFhir')
include('azure-4/Item/Integration/ServiceSoftwareAsAService')
include('azure-4/Item/Integration/ServiceEventGridDomains')
include('azure-4/Item/Integration/ServiceAzureDataCatalog')
include('azure-4/Item/Integration/ServiceIntegrationAccounts')
include('azure-4/Item/Integration/ServiceEventGridSubscriptions')
include('azure-4/Item/InternetOfThings/ServiceDigitalTwins')
include('azure-4/Item/InternetOfThings/ServiceTimeSeriesInsightsAccessPolicies')
include('azure-4/Item/Intune/ServiceDeviceSecurityApple')
include('azure-4/Item/Intune/ServiceDeviceSecurityGoogle')
include('azure-4/Item/Intune/ServiceDeviceSecurityWindows')
include('azure-4/Item/Intune/ServiceIntune')
include('azure-4/Item/Intune/ServiceAzureAdRolesAndAdministrators')
include('azure-4/Item/Intune/ServiceIntuneForEducation')
include('azure-4/Item/IoT/ServiceEventHubs')
include('azure-4/Item/IoT/ServiceStreamAnalyticsJobs')
include('azure-4/Item/IoT/ServiceFunctionApps')
include('azure-4/Item/IoT/ServiceNotificationHubs')
include('azure-4/Item/IoT/ServiceTimeSeriesInsightsEnvironments')
include('azure-4/Item/IoT/ServiceIoTHub')
include('azure-4/Item/IoT/ServiceIoTCentralApplications')
include('azure-4/Item/IoT/ServiceAzureMapsAccounts')
include('azure-4/Item/IoT/ServiceTimeSeriesInsightsEventSources')
include('azure-4/Item/IoT/ServiceLogicApps')
include('azure-4/Item/IoT/ServiceDeviceProvisioningServices')
include('azure-4/Item/ManagementGovernance/ServiceMonitor')
include('azure-4/Item/ManagementGovernance/ServiceAlerts')
include('azure-4/Item/ManagementGovernance/ServiceAdvisor')
include('azure-4/Item/ManagementGovernance/ServiceCostManagementAndBilling')
include('azure-4/Item/ManagementGovernance/ServiceBlueprints')
include('azure-4/Item/ManagementGovernance/ServiceActivityLog')
include('azure-4/Item/ManagementGovernance/ServiceDiagnosticsSettings')
include('azure-4/Item/ManagementGovernance/ServiceLogAnalyticsWorkspaces')
include('azure-4/Item/ManagementGovernance/ServiceCompliance')
include('azure-4/Item/ManagementGovernance/ServiceApplicationInsights')
include('azure-4/Item/ManagementGovernance/ServiceMyCustomers')
include('azure-4/Item/ManagementGovernance/ServiceRecoveryServicesVaults')
include('azure-4/Item/ManagementGovernance/ServiceMetrics')
include('azure-4/Item/ManagementGovernance/ServiceSolutions')
include('azure-4/Item/ManagementGovernance/ServiceAutomationAccounts')
include('azure-4/Item/ManagementGovernance/ServiceOperationLogClassic')
include('azure-4/Item/ManagementGovernance/ServiceServiceProviders')
include('azure-4/Item/ManagementGovernance/ServiceEducation')
include('azure-4/Item/ManagementGovernance/ServiceAzureLighthouse')
include('azure-4/Item/ManagementGovernance/ServiceAzureArc')
include('azure-4/Item/ManagementGovernance/ServiceUserPrivacy')
include('azure-4/Item/ManagementGovernance/ServiceManagedApplicationsCenter')
include('azure-4/Item/ManagementGovernance/ServicePolicy')
include('azure-4/Item/ManagementGovernance/ServiceResourceGraphExplorer')
include('azure-4/Item/ManagementGovernance/ServiceMachinesAzureArc')
include('azure-4/Item/Migrate/ServiceCostManagementAndBilling')
include('azure-4/Item/Migrate/ServiceRecoveryServicesVaults')
include('azure-4/Item/Migrate/ServiceDataBox')
include('azure-4/Item/Migrate/ServiceDataBoxEdge')
include('azure-4/Item/Migrate/ServiceAzureMigrate')
include('azure-4/Item/MixedReality/ServiceRemoteRendering')
include('azure-4/Item/Monitor/ServiceSapAzureMonitor')
include('azure-4/Item/Networking/ServiceCdnProfiles')
include('azure-4/Item/Networking/ServiceAzureFirewallManager')
include('azure-4/Item/Networking/ServicePrivateLink')
include('azure-4/Item/Networking/ServiceIpGroups')
include('azure-4/Item/Networking/ServicePrivateLinkService')
include('azure-4/Item/Networking/ServiceVirtualNetworks')
include('azure-4/Item/Networking/ServiceLoadBalancers')
include('azure-4/Item/Networking/ServiceVirtualNetworkGateways')
include('azure-4/Item/Networking/ServiceDnsZones')
include('azure-4/Item/Networking/ServiceTrafficManagerProfiles')
include('azure-4/Item/Networking/ServiceNetworkWatcher')
include('azure-4/Item/Networking/ServiceNetworkSecurityGroups')
include('azure-4/Item/Networking/ServicePublicIpAddressesClassic')
include('azure-4/Item/Networking/ServicePublicIpAddresses')
include('azure-4/Item/Networking/ServiceRouteFilters')
include('azure-4/Item/Networking/ServiceDDoSProtectionPlans')
include('azure-4/Item/Networking/ServiceFrontDoors')
include('azure-4/Item/Networking/ServiceVirtualNetworksClassic')
include('azure-4/Item/Networking/ServiceApplicationGateways')
include('azure-4/Item/Networking/ServiceLocalNetworkGateways')
include('azure-4/Item/Networking/ServiceExpressRouteCircuits')
include('azure-4/Item/Networking/ServiceNetworkInterfaces')
include('azure-4/Item/Networking/ServiceConnections')
include('azure-4/Item/Networking/ServiceRouteTables')
include('azure-4/Item/Networking/ServiceFirewalls')
include('azure-4/Item/Networking/ServiceServiceEndpointPolicies')
include('azure-4/Item/Networking/ServiceNat')
include('azure-4/Item/Networking/ServiceVirtualWaNs')
include('azure-4/Item/Networking/ServiceWebApplicationFirewallPoliciesWaf')
include('azure-4/Item/Networking/ServiceProximityPlacementGroups')
include('azure-4/Item/Networking/ServiceReservedIpAddressesClassic')
include('azure-4/Item/Networking/ServicePublicIpPrefixes')
include('azure-4/Item/Other/ServiceWindowsVirtualDesktop')
include('azure-4/Item/Other/ServiceDetonation')
include('azure-4/Item/Other/ServiceSshKeys')
include('azure-4/Item/Other/ServiceInternetAnalyzerProfiles')
include('azure-4/Item/Other/ServiceUniversalPrint')
include('azure-4/Item/Other/ServiceExpressRouteDirect')
include('azure-4/Item/Other/ServicePeeringService')
include('azure-4/Item/Other/ServiceResourceMover')
include('azure-4/Item/Other/ServiceTemplateSpecs')
include('azure-4/Item/Other/ServiceAzureBackupCenter')
include('azure-4/Item/Other/ServiceLocalNetworkGateways')
include('azure-4/Item/Other/ServiceInstancePools')
include('azure-4/Item/Preview/ServiceAzureCloudShell')
include('azure-4/Item/Preview/ServiceStaticApps')
include('azure-4/Item/Preview/ServiceAzureWorkbooks')
include('azure-4/Item/Preview/ServicePrivateLinkHub')
include('azure-4/Item/Preview/ServiceIoTEdge')
include('azure-4/Item/Preview/ServiceAzureSphere')
include('azure-4/Item/Preview/ServiceTimeSeriesDataSets')
include('azure-4/Item/Preview/ServiceRtos')
include('azure-4/Item/Preview/ServiceWebEnvironment')
include('azure-4/Item/Security/ServiceAzureDefender')
include('azure-4/Item/Security/ServiceConditionalAccess')
include('azure-4/Item/Security/ServiceSecurityCenter')
include('azure-4/Item/Security/ServiceApplicationSecurityGroups')
include('azure-4/Item/Security/ServiceKeyVaults')
include('azure-4/Item/Security/ServiceAzureSentinel')
include('azure-4/Item/Security/ServiceExtendedSecurityUpdates')
include('azure-4/Item/Storage/ServiceRecoveryServicesVaults')
include('azure-4/Item/Storage/ServiceAzureStackEdge')
include('azure-4/Item/Storage/ServiceAzureHcpCache')
include('azure-4/Item/Storage/ServiceStorageAccounts')
include('azure-4/Item/Storage/ServiceStorageAccountsClassic')
include('azure-4/Item/Storage/ServiceStorSimpleDeviceManagers')
include('azure-4/Item/Storage/ServiceDataLakeStorageGen1')
include('azure-4/Item/Storage/ServiceStorSimpleDataManagers')
include('azure-4/Item/Storage/ServiceStorageSyncServices')
include('azure-4/Item/Storage/ServiceDataBox')
include('azure-4/Item/Storage/ServiceDataBoxEdge')
include('azure-4/Item/Storage/ServiceAzureNetAppFiles')
include('azure-4/Item/Storage/ServiceDataShareInvitations')
include('azure-4/Item/Storage/ServiceDataShares')
include('azure-4/Item/Storage/ServiceImportExportJobs')
include('azure-4/Item/Web/ServiceNotificationHubNamespaces')
include('azure-4/Item/Web/ServiceAzureMediaService')
include('azure-4/Group/GroupDotted')
include('azure-4/Group/GroupDashed')
include('azure-4/Group/GroupTransparent')
include('azure-4/Group/GroupPlain')
include('azure-4/Group/GroupPlainDotted')
include('azure-4/Group/GroupPlainDashed')
include('azure-4/Group/GroupNetwork')



@enduml