@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsMoodBad element
include('elements/materials/Social/MaterialsMoodBad')
MaterialsMoodBad('element', 'Mood Bad', 'an optional tech field')
@enduml
