@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsLocationCity element
include('elements/materials/Social/MaterialsLocationCity')
MaterialsLocationCity('element', 'Location City', 'an optional tech field')
@enduml
