' definition of the Item simpleicons-14/F/Fampay

sprite $FampayXs [10x10/16z] HKc30G0n4CkRRVQVjZWZH4wjWYIeps6vYHdg8n_Dl1ErGEUII2OLH7K

sprite $FampaySm [12x12/16z] LSc50OGm5C3GdE9a_ssfosk_qtrW9RaLzSNB0D3Du21u6zmX4tprChUi1cIBqfoULD_vGBUy21u

sprite $FampayMd [16x16/16z] LSw53G1120NHEVUT_hkz_2YyA0xTJJ7fODUBE5LXDLaUOu4qZCru87HH_RWbZbjr-LI8HMi_ft4HSQbx--DRRehtSL2fL8lIpCvqGlm

sprite $FampayLg [20x20/16z] {
PSi73iGm449H4lVA_M-x7h5MsbT_0dnhRqYJ1PYSs4skWCPLCF0cj1be9NXQ8g7haWPrBXgq9auE8MSo6IwGzBBcZ8hk-BTCJOzTfZfmLGtwbkjxYAxOJxQN
fKWIh_fbLx8F-Yzou5lnK3y
}

!procedure Fampay($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Fampay', $name, $tech, $desc)
!endprocedure
