' definition of the Item simpleicons-14/F/Franprix

sprite $FranprixXs [10x10/16z] RSQd5S1030KmcQN__QTDzGiw8M730H89aCwSLLAapVyoN7NeSW4

sprite $FranprixSm [12x12/16z] TSQr0S0m0C0mbxd-_zf2S8ec0TSCx3ry5aM9_5mGzMiNSwkzkeF5W5NpMosO77mE_Kpm0W

sprite $FranprixMd [16x16/16z] PSc50O0m4C30u4xsdnQNohNl79QHGx6Kt4PjKGiUQgVoQZmHgFgIrwGsp6VcO60who4mCc9apUwBeG8C0KDyXZ4UeT3Jmc47

sprite $FranprixLg [20x20/16z] {
NSk5OSGm40NHCREc_sxZd-DzmYNYEdjYQJqlfpOOr4ykKSCR7qtDcVXo6JC_kcaT-BAf1tJUEWWVTYD5iDXWieBBgaUhWMOrS5Xrz5Q0nGfq_cZ4M2UZgrt4
gd7sn1y
}

!procedure Franprix($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Franprix', $name, $tech, $desc)
!endprocedure
