@startuml
sprite $AzureQueuesStorageLg [23x20/16z] bT050i0W00B09Ghu_--kksTxjefLtGLE5H59ENtam1-iUCNo3uP_CA0BndVc7vQk63ViaJtpUE7GCQRPakoQmx_R7FfZICpGOJe4bYq

sprite $AzureQueuesStorageMd [16x14/16z] bSV50S1G30BGMWJu-y_RdEeQvT4cSvZLYGJRrjWxz-R1sZkUxNzCtrkhCpnI4NL0IYEerYJLhUyp

!procedure AzureQueuesStorage($id, $name="Queues Storage", $tech="")
  CloudElement($id, 'azure/StorageServiceColor/AzureQueuesStorage', $name, $tech)
!endprocedure
!procedure AzureQueuesStorageCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureQueuesStorageMd>', 'Queues Storage', $funcName, $content)
!endprocedure
@enduml
