@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsBattery50 element
include('elements/materials/Device/MaterialsBattery50')
MaterialsBattery50('element', 'Battery50', 'an optional tech field')
@enduml
