@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsSignalCellular3Bar element
include('elements/materials/Device/MaterialsSignalCellular3Bar')
MaterialsSignalCellular3Bar('element', 'Signal Cellular3 Bar', 'an optional tech field')
@enduml
