@startuml



!procedure EsEntity($shape, $stereotype, $id, $label="")
  !if ($label != "")
    $shape "$label" as $id <<$stereotype>>
  !else
    $shape $id <<$stereotype>>
  !endif
!endprocedure

show stereotype

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam maxMessageSize 150

skinparam Arrow {
    Color $FONT_COLOR
    FontColor $FONT_COLOR
    FontSize $FONT_SIZE_SM
}



@enduml