' definition of the Item material-4/Device/BrightnessLow

sprite $BrightnessLowXs [10x10/16z] Oq01pFmGcXyCG1me0PVYXmf1A32B4QQ44KWWwsM0AW

sprite $BrightnessLowSm [12x12/16z] NOm53i1G34BdIlRkVziLqjZtejEuDdgu9K1QQgxftbvOCrjTFMzSiOBlbba1R_CXt71rba-GULbNJnwpoFi3

sprite $BrightnessLowMd [16x16/16z] RSm50eD034JHkaxpxt_Q0Z5qLjzAJiUviI4qwAXiZzjxuPUl5hvXyUyCJXvPoC1_tz82nVS8A9RWDGk11L4QVeAov33fu-vIonG7

sprite $BrightnessLowLg [20x20/16z] {
VOy15WCH30MZNG3vzxzj0U1r1p0WeJTalDGNu6Kff9GQ2PQ9TWihY_FgqRoxJvcPuJGWgEA0_gEZ3i3jfXmk5id9FSE5jD8aajJ3fOMfuqXBD4Lo7kGrFbjE
yPu7Ok0o_iztN3DqmBSYeSVq1m
}

!procedure BrightnessLow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Device/BrightnessLow', $name, $tech, $desc)
!endprocedure
