' definition of the Item material-4/Device/MobileOff

sprite $MobileOffXs [10x10/16z] HSY34G0m40J0sEY_s-JjdNDMnL-ehxnyAML1EE1sKCzBvCeIVNgMomjreO09bVC3

sprite $MobileOffSm [12x12/16z] LOdN4S1G3CBqB-wo_xHfhxaR4BskKK1aQtJGSUNeU3J9qSIZYMoD3ZtAemqF

sprite $MobileOffMd [16x16/16z] ROc50SCm4CIk3UVXzfysRBQCqgC3F-IMGR27y4u5czuO4SB3mF0AIgUK3ahfe9OEIkbts9E_eN1GWWSaU1asUnanu0G

sprite $MobileOffLg [20x20/16z] {
TS-53GD144DHBzCexh_QOxRonMznyA_nEyixP3ZURHGu43w6H8FBUtOOCWUEscdeDB563hL44qFc44EcYQqxnRQTxcN7pd3RFT7JTA8xWzgvC_8kCHrOpXm2
C0C
}

!procedure MobileOff($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'material-4/Device/MobileOff', $name, $tech, $desc)
!endprocedure
