' definition of the Item aws-q1-2022/Resource/SecurityIdentityAndCompliance/AwsWafLabels

sprite $AwsWafLabelsXs [10x10/16z] Oq02t404PN1n0mcSW1i26F03HZ00CW

sprite $AwsWafLabelsSm [12x12/16z] NOo30G0m40CVgVUVj_OLpuGUL4JYI1aKbMpFNQtguzwVcrTE8zSq-VeIEkxi_pvnqF82

sprite $AwsWafLabelsMd [16x16/16z] RStL0O1G243HIxpUVruBMyyN3L_U5yP1Ao9KEVAEr0gTC41AZI3Q80Aq8m-Vd3EtSVdhemSYjqFaGJ__VlDnOZK3

sprite $AwsWafLabelsLg [20x20/16z] TOw10G0G2C0g0F_V2m1eWA421XaAk2iAK0XJj8Ds4j0VYdoPvNpf2G13FIizdnNQoHuEMAS_3ZOdmex-lMCT-OLatos8gPbrk1XERyYc4W

!procedure AwsWafLabels($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/SecurityIdentityAndCompliance/AwsWafLabels', $name, $tech)
!endprocedure

!procedure AwsWafLabelsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsWafLabelsLg>', 'SecurityIdentityAndCompliance', $funcName, $content)
!endprocedure

!procedure AwsWafLabelsGroup($id, $name='Aws Waf Labels', $tech='')
  IconGroupElement($id, 'SecurityIdentityAndComplianceFamily', '<$AwsWafLabelsLg>', $name, $tech)
!endprocedure
