' definition of the Item aws-q1-2022/Resource/Storage/AmazonSimpleStorageServiceObject

sprite $AmazonSimpleStorageServiceObjectXs [10x10/16z] Oq06d53Cm0ZZSa9bs84OdSM4f8yJBWPcGabsTYPEe0W

sprite $AmazonSimpleStorageServiceObjectSm [12x12/16z] LOg50S0W30GFuliFN2yIVMElLjgy7gZjUTQWlH0SQcGD7JXf2_Q1Qybti161vWC2bbaTE04

sprite $AmazonSimpleStorageServiceObjectMd [16x16/16z] RKw54G0n22iE-m_yKhTKOtUa6p3Smnk3WFoA5PwDyOlH0_cwa0Qis0EOEmEsST_oile4dpHeDWr66hC8ZNAQ1gV0COQvbDGB

sprite $AmazonSimpleStorageServiceObjectLg [20x20/16z] {
TSk5bSLG24NHWosu_HSyyosUxASOpx97Kyuc5G2qZ9yf5XE_rzZ80RBO6m1n40qP70cQatQ6aqZ4YHV3IGR5YS3xcaCSb0CsBBOej4ij_vnO1WSMhGvFoTdp
hEJd7m
}

!procedure AmazonSimpleStorageServiceObject($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/Storage/AmazonSimpleStorageServiceObject', $name, $tech)
!endprocedure

!procedure AmazonSimpleStorageServiceObjectCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceObjectLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceObjectGroup($id, $name='Amazon Simple Storage Service Object', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceObjectLg>', $name, $tech)
!endprocedure
