' definition of the Item aws-q1-2022/Resource/Storage/AmazonSimpleStorageServiceBucket

sprite $AmazonSimpleStorageServiceBucketXs [10x10/16z] PKg30S1038on_y356-49bih_g0F48cccTpEBLYYc-GpTYFzW4DedlG

sprite $AmazonSimpleStorageServiceBucketSm [12x12/16z] LSq50GH04CIm7C_w5_oC4T3wix9wdpaedZPLgzDMGdWA0wrGDA1Qce_P69xQimKT0gpdf7A3Am

sprite $AmazonSimpleStorageServiceBucketMd [16x16/16z] PKo50GCn4CevxBzm-Qktl2Je-OSD8R1j6Vrf1FN3PxBFoKPjmWiTqap154AdY-TbYWcxEDUjWEVrETWqK2VVywIz_LVrpNVQNzJZ_T-axS5yK3vtOu29TMy

sprite $AmazonSimpleStorageServiceBucketLg [20x20/16z] {
TKm7SW1128eT_l_Xn9qrrvc2qdw-u54WKM6ZaFzdi9eKSguOkeVh3bUkTsHLF53SXWH8ilplnTREo9F6pN7ItDclBQrqQa9AejhfvL63nLaOp5A-QBXfGmEj
Pyvjxos-RHVXAc99dconYF0HVW4
}

!procedure AmazonSimpleStorageServiceBucket($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Resource/Storage/AmazonSimpleStorageServiceBucket', $name, $tech)
!endprocedure

!procedure AmazonSimpleStorageServiceBucketCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceBucketLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceBucketGroup($id, $name='Amazon Simple Storage Service Bucket', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceBucketLg>', $name, $tech)
!endprocedure
