' definition of the Item azure-11/Item/Other/ServiceMobileNetworks

sprite $ServiceMobileNetworksXs [10x10/16z] TSd50G0X30J0ZLl__Px2Zu4u3hgRliRC-gwgk9jci9c8zks-wBsxGG7wElBRp32s2m

sprite $ServiceMobileNetworksSm [12x12/16z] VOhL0G0X34Ch2Rh_leV3rpsaZSWVkPIz5ZZC-cQ4EtDF00NQMj1SQXEbGtfhSEojhLYx1BOJQaT4GoEbPFBo0G

sprite $ServiceMobileNetworksMd [16x16/16z] dST70iD024DHeP688VU_RzpjLTgV0Wz_LJqN9xiq977d9C-fUfL43edLlL4WuAdd4hGTfDLhDGi6xDvA8y8y3IiuS7DcUdxFjGSGCmuBdte1

sprite $ServiceMobileNetworksLg [20x20/16z] {
hSdL0SCm34LHwK50tN_VXcD_5O_vElu0upIwJxNBBWsan0bNcWfUeUQZK0Incgls90dXXMg1DNbfcOd4M1i7l4WchJfeBKcav3ejZSRwTJSjBTAPJGkBeUWR
1W_3jXu7HEHmkDCYM_6-9m
}

!procedure ServiceMobileNetworks($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-11/Item/Other/ServiceMobileNetworks', $name, $tech, $desc)
!endprocedure

!procedure ServiceMobileNetworksCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceMobileNetworksLg>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceMobileNetworksGroup($id, $name='Service Mobile Networks', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceMobileNetworksLg>', $name, $tech)
!endprocedure
