' definition of the Item simpleicons-5/K/Kofax

sprite $KofaxXs [10x10/16z] Oo0Ii3CmS0C9TdO6Vdv-1bv-Tau6VcBr0W

sprite $KofaxSm [12x12/16z] Ow00y35oyV4nyt7nCV3nylCpiZ6nyREpSBBniZ6miR8nCe0ePbBD1

sprite $KofaxMd [16x16/16z] lS470O105CMmic_zL_zkKG49FnCFc-dzbjxKj1kZ7XttK2ssObiaM_ZO2m

sprite $KofaxLg [20x20/16z] pOC70S0W40F33Cyw_svR6TpGuxZ8wgl9jfhbAXFKi_8Pr2f8_mseTCK1l29q4Evq9Xc96CGPHu_p0G

!procedure Kofax($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/K/Kofax', $name, $tech)
!endprocedure
