' definition of the Item simpleicons-5/K/Kubernetes

sprite $KubernetesXs [10x10/16z] BOc50S104C9IzsR_QIlFvHJWPo2exdNxVt0n6XqdGAFcqvz3v5_k9C40ZFMy

sprite $KubernetesSm [12x12/16z] 5SQ55GD144EndsDM_ztchGRi6kQ6uSNHy26Sex9tOOejVJs-cFQvdej8VXOUlxurzvGmvnVQyMioVgy5bxMAuQa_

sprite $KubernetesMd [16x16/16z] {
JSY5TS0m303HCoHct_xRzgdynU9RuR-ZThwbkA86uHgIVdsowdbe1bZUNFDXqQicrCaG2sf3nGIqsLHKxCY-LUtUbrGXPUXwr3RaOhegggbCAQ-wGHL8vNkf
keuQDw7hjmpX-EK5FW
}

sprite $KubernetesLg [20x20/16z] {
LT25bSKW00NHIN2T_hlTmtw_KPm7Rm5-tKEjVBbywkz1o-FsQ1U0J_Vh-wvhaJmzDaGjIQWKWkZvLpl5YO8gB3L6KaUkKpAXYWiWchBQddMRBDaPrPrrT-0c
SiCzzOYUP83IHzEaEjbNbbtne3zpQeDNaArQmZjcVlrT7kLzDBSwFOPk7g8Vl3HVRe0_
}

!procedure Kubernetes($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/K/Kubernetes', $name, $tech)
!endprocedure
