' definition of the Item simpleicons-5/K/Kyocera

sprite $KyoceraXs [10x10/16z] DOp50K0X04BV3plOVrfRJZGBajvB1fEKm2z6AOCz28ggVy5C9W_83FRwEfXCUTV266DZBESlphyE

sprite $KyoceraSm [12x12/16z] HOs75O1024F3sUlVVrjVGBqEfAdM0VGowuZOxljsFSBaKTMJ_wed_yXOKzOkDLvzFd9sFfotglPgq7CZwmS

sprite $KyoceraMd [16x16/16z] NSq50e0W40NHjHlkVrl_q33cKy9oawU1nRClljHEPxJkh_6oPB_SWa_y6NOoD15xjq32wacloTVYetc8h1VCGopxyJYjUABFATnkW4l9Fm

sprite $KyoceraLg [20x20/16z] {
PT3L0O0m54FH87N9_jCYuU7tyzIBHrJZa_hVo9_rfr4LxCMd3Qry3MXiPiDXmsuiiXaoGCQ-sGZPS1fBdA4SBcF44VrbSoncT6OZ8hiPlMpMkSMCRhFn-mxV
PZpCAP_tckmg_VyAo3_JJBCL
}

!procedure Kyocera($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/K/Kyocera', $name, $tech)
!endprocedure
