' definition of the Item aws-q2-2024/Resource/BusinessApplications/AmazonPinpointJourney

sprite $AmazonPinpointJourneyXs [10x10/16z] FSQv0O0m000Xr7ot_y9seG9S9u3kt7bwYeV1P6T7V4lfPPiesC0F

sprite $AmazonPinpointJourneySm [12x12/16z] RS770KCn50CWVh7rjF_2kQM3RxEzr7-zlPaHXlE-ARLo59WuKXRgkbL02EB30m

sprite $AmazonPinpointJourneyMd [16x16/16z] TSct0GDH30KWVfJU_WkxTJfQ_DS-HBuwFYnVubEjHG9kJLEICN4EUZVwuaZ7XiBLgWHZe9GnXT4mnrcZXNAXeL0rmEsA9oy

sprite $AmazonPinpointJourneyLg [20x20/16z] {
XSq5WaKX34FHcnRB_XSyWdoNFEMq53v4UgQHVhG6JoRtQK-Tp_4h6nLGlQ4YB8LtVntkPCKHEPPPyrt6h2-2FgfrUrB7uFa-fb31shCZfwKQiCoEtJrIFJ6e
ddb9LEYpNfVHceYnDecJsWjVyWi
}

!procedure AmazonPinpointJourney($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/BusinessApplications/AmazonPinpointJourney', $name, $tech, $desc)
!endprocedure

!procedure AmazonPinpointJourneyCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonPinpointJourneyLg>', 'BusinessApplications', $funcName, $content)
!endprocedure

!procedure AmazonPinpointJourneyGroup($id, $name='Amazon Pinpoint Journey', $tech='')
  IconGroupElement($id, 'BusinessApplicationsFamily', '<$AmazonPinpointJourneyLg>', $name, $tech)
!endprocedure
