' definition of the Item aws-q2-2023/Architecture/InternetOfThings/AwsIoTEvents

sprite $AwsIoTEventsXs [10x10/16z] OoS4c5WPO4msHYOsPY3DoiZ8o0v4O34M5dOsi3es88qT

sprite $AwsIoTEventsSm [12x12/16z] ZSQr0S1054En-s2__ISEGnLG9NvAwFkEu62vGa1rHB0Vw36IetJ6yUBT3

sprite $AwsIoTEventsMd [16x16/16z] hOp50OH034Kd-TP_nIiuH-J5DM_GIfGTLLfmLknHQd6ks7C4Qhvc_KZ-RlymLC5wBx9u-X_qte1pboy

sprite $AwsIoTEventsLg [20x20/16z] lSxN0GDG24BHXo9t_udJYmiavzS2_4qNaB1LXXFOMgMHBRQCL8gQ9mcO3DJulMBTXKZYoGRIOiJXAyVbG7WhDRAdili529kR7xe2

!procedure AwsIoTEvents($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Architecture/InternetOfThings/AwsIoTEvents', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTEventsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTEventsLg>', 'InternetOfThings', $funcName, $content)
!endprocedure

!procedure AwsIoTEventsGroup($id, $name='Aws Io T Events', $tech='')
  IconGroupElement($id, 'InternetOfThingsFamily', '<$AwsIoTEventsLg>', $name, $tech)
!endprocedure
