@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsOrganizationsAccount element
include('elements/aws/ManagementGovernance/AwsOrganizationsAccount')
AwsOrganizationsAccount('element', 'Organizations Account', 'an optional tech field')
@enduml
