@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsPersonalHealthDashboard element
include('elements/aws/ManagementGovernance/AwsPersonalHealthDashboard')
AwsPersonalHealthDashboard('element', 'Personal Health Dashboard', 'an optional tech field')
@enduml
