@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AwsSystemsManagerInventory element
include('elements/aws/ManagementGovernance/AwsSystemsManagerInventory')
AwsSystemsManagerInventory('element', 'Systems Manager Inventory', 'an optional tech field')
@enduml
