@startuml
sprite $AzureKeyboardLg [33x20/16z] {
XP835a0X44LxORp_zNuRtPCnvlY7euEFJR_n696KWArZxcdhiZp8gWsYD7O6gu36tbJpzg14KFOGM2Wq31AUAQ8S4gn1ZI36O1EGAPeT4lesY5ImjB5J8c6q
iLUHmmRlsM1EKEUn2yGLF7PoEzk0rxuz036tLFcWfiPCEDamApuGM1msz1zarIKwAqlCz1oeDJehwsOpqkKRZoxUBRa1
}

sprite $AzureKeyboardMd [23x14/16z] {
TP07ZaCn24I_6Ko__tdNY4rFHa-5NgA-AGwVwi0YD1YeENw_D6493uGZ3AcNjtixn4cDJCa5BkF-Q39kBRutIUEwDJ6IWv8AsM6FcvWNU8J5V6-Iy1evyjP4
ipSS6R8Nd7DwbH4jp3dVZ__ngZy
}

!procedure AzureKeyboard($id, $name="Keyboard", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureKeyboard', $name, $tech)
!endprocedure
!procedure AzureKeyboardCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureKeyboardMd>', 'Keyboard', $funcName, $content)
!endprocedure
@enduml
