@startuml
sprite $AzureRouterLg [26x20/16z] {
RP5L0W11248dTL3kVztjTj-dBIWDBNt82gVwA2dIp5LKSqXKDFIMLBw9WffrdLfIrGTrZQIyDniVMBtNEL_uUMmU-72T6sux0tK4Zar2nxhOILzFWLFEZ2JG
SYDRDYB9dK4tkWnoYDCwpaptG3_521m7bdZrgexcYlAhADfXN731xKW4v-ZG_Els3
}

sprite $AzureRouterMd [18x14/16z] NS-50SGW3030kE-_xakz7Euaon1kakCky42UGaQ01m2Z_mQqsbqN-5nycq1zs3QnFV1sgAElxDjCIVzoI_toDgFveDlDzv-tlf31Wv6aqnB5fC0xqYy

!procedure AzureRouter($id, $name="Router", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureRouter', $name, $tech)
!endprocedure
!procedure AzureRouterCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureRouterMd>', 'Router', $funcName, $content)
!endprocedure
@enduml
