@startuml
sprite $AzureLaptopLg [32x20/16z] xOmr0eHG34JdM_p-rzt57KegNfMC0KdZ1a5FjLekgLPwlmckILeVVRpXVpvPky5QPnUFMooZsFew3wrTOFULtC6x1NwOxnV_

sprite $AzureLaptopMd [22x14/16z] rT350G1120F0i8Btt-wvNmKx7v8y0TaF0LNm8MLPUR1LoeTMa6Rit8-G0ibTj5hFdEBdkdpbpEap

!procedure AzureLaptop($id, $name="Laptop", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureLaptop', $name, $tech)
!endprocedure
!procedure AzureLaptopCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureLaptopMd>', 'Laptop', $funcName, $content)
!endprocedure
@enduml
