@startuml
sprite $AzureLockUnprotectedLg [15x20/16z] {
ROq54aGX34DRD26z_tbtlniFZSpK_XGgn68RLI8ejLLbQGaIbHVPe-usbeToM-5mCmTsYTNVnIBJyjnbxISZK6E6XkwgUBbfBbDlQRPyRyCGD-XF-KuvdSku
mny
}

sprite $AzureLockUnprotectedMd [10x14/16z] PSRN0G0n209GZ6aA-wzxpVpTim3WGOO3iDpkAmqOxqDCO2qyvWRCJcjbHMEHg4U4IffbDNgZofpwjRtre0xU

!function AzureLockUnprotected($id, $name="Lock Unprotected", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureLockUnprotected', $name, $tech)
!endfunction
!function AzureLockUnprotectedCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureLockUnprotectedMd>', 'Lock Unprotected', $funcName, $content)
!endfunction
@enduml
