@startuml
sprite $AzureStorageLg [24x20/16z] hSwr0S004CF01ple_TSDLs6wKfNKEhL2R_MYert1t2rMREbhIqUzWg7_-EcvukS_MQtalp_1bPXwkg_bqDNkqA4U

sprite $AzureStorageMd [17x14/16z] RSpL0S0m20JGkC7-wzORzFqXTrWhadkmYp99kHSXad0lyY3PxQX0daLC9DwBL4Wo7UuYLN97HkK66YS

!procedure AzureStorage($id, $name="Storage", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureStorage', $name, $tech)
!endprocedure
!procedure AzureStorageCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureStorageMd>', 'Storage', $funcName, $content)
!endprocedure
@enduml
