@startuml
sprite $AzureWorkstationClientLg [20x20/16z] {
fSwr0SD0341H-yIu_xWnKvjN_WCf-g3JfK_-Q4OhZcVJiV5dgrnKrRDjglhJaea8tat8ddHjhEMtgBt5VB_aiqqt-gzL9dsR0SwMVBFgT2V9rVfc5Ms808XZ
36uRc-DCvW7Q0MDTldQewQhgwKly0G
}

sprite $AzureWorkstationClientMd [14x14/16z] VSsr0O0m40NGoBdjloqEwNZTwSywMRkbgQgzLH00q5jL7ihVgagPiT-gakpbLK4snmNYgfwhxdzLAkEwIo6mGyJnqbEO6CPq7KTU7W95L9LRsm4

!function AzureWorkstationClient($id, $name="Workstation Client", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneEnterprise/AzureWorkstationClient', $name, $tech)
!endfunction
!function AzureWorkstationClientCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureWorkstationClientMd>', 'Workstation Client', $funcName, $content)
!endfunction
@enduml
