@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsRadioButtonChecked element
include('elements/materials/Toggle/MaterialsRadioButtonChecked')
MaterialsRadioButtonChecked('element', 'Radio Button Checked', 'an optional tech field')
@enduml
