' definition of the Item simpleicons-6/W/Wappalyzer

sprite $WappalyzerXs [10x10/16z] Oq05_52QZPyVmkI70323bnL4Ca2uO1OxM98HoEVX0h6O87eu-67cyO88

sprite $WappalyzerSm [12x12/16z] PSY54S0m3C10bT7H_jkMCH-mpcJYhahbCBlfjjnY34tqMpR7PllYo1uR3wqGurQH1bQDWwq51wVWLh9P

sprite $WappalyzerMd [16x16/16z] TOw50GCn30FrORxzfoquPRYWMVg3UpUXlrYHAyVT76ooMGwZ0VDYDhCAijUnSKw7VLJCb31S9TXdsTMGw8_-p3qkcPb8TpbbqSPJaDQADBrGSFh96G

sprite $WappalyzerLg [20x20/16z] {
bS-5OGGX54NHXpkt_sfZC5ctWpjVdsfuNR80LUSYYquwXwJ5iVJJrihIj5eliGm5l_jrxuhTMQkoN_ByAcSlcK4S_9ffjRcZn4YS632IdKIsMevWEhNnouFL
5fWHHcGOdKn27cHTo32jhfYXPxu1
}

!procedure Wappalyzer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/W/Wappalyzer', $name, $tech)
!endprocedure
