' definition of the Item simpleicons-6/W/Weightsandbiases

sprite $WeightsandbiasesXs [10x10/16z] O-1dW00-40k6OIG_Fmi3X4QIPOJgO0Jn6U4w-C0a3pzK6g632G

sprite $WeightsandbiasesSm [12x12/16z] JOs50O104CE2Ezb_MkJzN5jkYD9js04Zi1j7CVKUHD5BWHvGfdpJ3RHY3uF0QNwBUO8fZqAED_Q5wmK

sprite $WeightsandbiasesMd [16x16/16z] NOw50OL004B1xhV_j3_4FFIQqZZgncR1VQn1zdytvxOvN_gJLK6j4nD_p3e1EEyZSTcNsw-4fL3SdldfHwwNwdQ-Tabkez-U-HLR1yFVQGsvaNUB3OVo1G

sprite $WeightsandbiasesLg [20x20/16z] {
LOw55KKX3CNw19ViF-qNUf1UN1Dv4HFVHI2RFGWIUSOyS8snZ543IKpcFSqD1l921tWD0XBeerVn3P1AD8o6avciJXh5cNMVNlU4U6d4SJgTmCrpb6_-wgTx
GyKgSJ8gOCZW6g1Yp-PkNZ1E2Wbp-WK
}

!procedure Weightsandbiases($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/W/Weightsandbiases', $name, $tech)
!endprocedure
