' definition of the Item simpleicons-6/W/Wwise

sprite $WwiseXs [10x10/16z] Oy05-A4q4vp5pyV03sG3IGOe0X8W0DS10woeHW4

sprite $WwiseSm [12x12/16z] VSQt0S0W00In9sTk_scTJOagQSjegQnYScQzFf_2pOfAeqYoM2Pw3OFj-aIqSm8

sprite $WwiseMd [16x16/16z] dSI35GDH00NHMNnZ-gysvb5m7_ZFKdYZbQTUialFt6nwEyuginOnBmLcZMvvqLPe8cUAEBbP5S_7pRPCmywBQUBDodUE

sprite $WwiseLg [20x20/16z] jSYr0K9H0C30V7aksNzQt6dXokDVgXkVTF9cpMWXlvOELjItc_2uTQCCecZPP9yRSGvqew6JIRCWi0Q6QtMhHY8tcugeF6bCBjFA6nryqiwNm2yS0G

!procedure Wwise($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/W/Wwise', $name, $tech)
!endprocedure
