' definition of the Item simpleicons-8/Z/Zincsearch

sprite $ZincsearchXs [10x10/16z] Oq06B130mC0F1N0MM9gH0ShWu6U0C60o20sSC0OI

sprite $ZincsearchSm [12x12/16z] Oy0D-660WO4JpaR8yK1OV40s1qoGWPy9Bezi33SGC30m8fd216Eoe5eA

sprite $ZincsearchMd [16x16/16z] PSUr0GGn00InUJY6xRzQCrkPcCn-ge1L_TiUm1M4hXI-dvnZyoTxTDBqbLvgvL5RNV1HOuEjwGEm5IlCB

sprite $ZincsearchLg [20x20/16z] bS_50S0m34DH9MNK_jEMmL3ynnSqVfNAaeKwgcOYdGL3wMJHx98v2e2bb04TsGagoOYMZQ2QP8Awj9SV8APeujf2xqFCLbcQC_Id4G

!procedure Zincsearch($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/Z/Zincsearch', $name, $tech, $desc)
!endprocedure
