' definition of the Item simpleicons-6/C/Cakephp

sprite $CakephpXs [10x10/16z] Oq01hEmi88eV7s3W0n50mC49LiiDri03rGKamRAS_0XJ0G

sprite $CakephpSm [12x12/16z] VSJ50S1G508mU7Lb_sdhyZs784JYqkbLhoffhZ5S7repd6JN4yyFgmQTq5vpEe_i

sprite $CakephpMd [16x16/16z] bSp50S1020J0FLUW_shZxfaF3jwPB0EEkgkgR0MMVz8KeUiKfxgd2GENYiP8vYXI3FfjTgghJ_zicUBcdysg3zg4X1ij

sprite $CakephpLg [20x20/16z] hOq54aCX44E3Ezp_j9Nq3pfIUyZw1fyXZNDM2rper2Qg5q0xYBNz5zqzGFb2QQ3s70cUHhcOQqKdTA-r92-F3hqdDHX39slcEg5xb2KmFKV2or4-C_SnTm

!procedure Cakephp($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Cakephp', $name, $tech)
!endprocedure
