' definition of the Item simpleicons-6/C/Castro

sprite $CastroXs [10x10/16z] 9SZ50SC0002XgpVA_jD6UL8r-5O53CNTdzJasMhGQ5J8ad--Ug1a2j7WLdr0xG

sprite $CastroSm [12x12/16z] 9St50SD030NHISmWJV_Lclwxx8fv7Qw4aUy6b8B-U2qMxemcUQIaBCdyAHbS1MrFTh4WLT5LjTe5D9gSqJTx0m

sprite $CastroMd [16x16/16z] {
LO-50GCm2C2eU_F_jnimJHK7CSfX1NbpS9f90U3i2roLWMA62TkStv4DefXr0Cbi1LpKDyBXY6X8P-d7SgWjk65nxGdGpT7ZFBw2y1TtLTStIhbWtN-fycJ_
YvxkFSq3
}

sprite $CastroLg [20x20/16z] {
LOy5bW0n2CN-r3ttF-rA6KrTo0ETrCL8Uf4vcLudlAZFrOZky0MWdLVSLY2Qw_YOfVDN1voa1KKmRGjaKrL8KeFL07jTu4x10T4aSEWKGDaX0xm4E9NzF23j
nuFDaca0oyii0QOcTFtFLiAU7L0AnixJQloWVnfll3Rn--lazCseVtu1
}

!procedure Castro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Castro', $name, $tech)
!endprocedure
