' definition of the Item simpleicons-6/C/Celery

sprite $CeleryXs [10x10/16z] O-372XX00C82ObuuYnylYnckbmdPC

sprite $CelerySm [12x12/16z] O-270rv-DC0012mG9Wi39nSpL2qZc2QFpSR0oCG0upCpC33pebaC

sprite $CeleryMd [16x16/16z] jO-50S0W3C22E_n_xHmxO47hBQMjk2xkUEFob2eltLT3YXQwNP3wzoSvt4_eiWKbWSNXnYyTbze7R3id

sprite $CeleryLg [20x20/16z] nSwr0GCW40NGZpkt_xHnNDgy2ixXQ2QMq9N7sz0KK0Gg9A2YDnoWYfLFMcB5NsFbM2EeqW041uPo_73gM2cKYNGcQ96V

!procedure Celery($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Celery', $name, $tech)
!endprocedure
