' definition of the Item simpleicons-6/C/Chase

sprite $ChaseXs [10x10/16z] RSkr0O0030J0nvtRVreiBTT4Fm_aTKIrgu1s94LrBNzTsaAQIgeGRN83

sprite $ChaseSm [12x12/16z] ZScr0S0m0CH0XMFK_jE6eVLL3noIchbuAN_K-iGVfyOyX13U_7v1PwXFNZYKAmVO0G

sprite $ChaseMd [16x16/16z] fSUt0O0m00D1aJE__xPOpZtNdMp4PcNiO4lgMyxcFjIpkzqvRW8bUq1txETb_GyANzBMVL2mbhksv8-IFW

sprite $ChaseLg [20x20/16z] lSY54KCn04EnzvdZ_RVjEPm5gcEHAA5vosakzGaL9BUwqv9gECrmgZ_RTXa33JVB_d5NiF6O1ww7LHtV1qpzkMpfBq3I7SMi94pO3m

!procedure Chase($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Chase', $name, $tech)
!endprocedure
