' definition of the Item simpleicons-6/C/Cilium

sprite $CiliumXs [10x10/16z] FOc50O003CEAE_d_MyAGIJNEGVxPRc3QaxqmMSKgM8EOjjEAVc3PH7qFWnYmw0hBYXS

sprite $CiliumSm [12x12/16z] 5Sh70OGm300m0UanyVxJNj5R87C3F5HmHnpq28BHxamIJiGSBEakr4xbUGxQyv2KTkLBm5lANUcISjd1_l_4_7-u1Nm1

sprite $CiliumMd [16x16/16z] {
JOu54WGn2C12wJho_z_UKCuoXWPeCfC_0kJWovohrhZvF6lbDakelRGnzdd3sAcrJS_pYENj_gDwwBMa4kxpNalkrLJLNSkBwe2fZ3D1hWJhioOHqK_m0AT6
-2qbMRb5pGUS0cRMlitieLdt-6533g5u0G
}

sprite $CiliumLg [20x20/16z] {
NOu5WiKm24GdsaKQxd_R_K1zAdb11uTsCyDRTPLIFy7bFvaurCSOqCmuEzYsaUvEEe81Rb5WjJPBhjXpBQlgoOXbWsojDGx649yvsV_9_ltKew9JiDjjhM7b
fE3qygVKdMemm3LlH2B9bvVMUx-ztDD7yjlBV7ffKT4e6AbZakAfz5BmaX4n7_mF
}

!procedure Cilium($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Cilium', $name, $tech)
!endprocedure
