' definition of the Item simpleicons-6/C/Cinema4D

sprite $Cinema4DXs [10x10/16z] DSQr0S1040InCREt_sx_K94mbtQSt7r7Dl-A5gNhtrL0RjVc2ynTJfm5rYip

sprite $Cinema4DSm [12x12/16z] 9SY50SH03CH0XO_LVxKFsJ6RlsuXZAokrbJGRbnu6iM-CBfkg57WqQ30KAsAm3vj-i3YR_dEEQ_-Vhy

sprite $Cinema4DMd [16x16/16z] {
HSi53WH12031NbVe___svaZ8rYX6MSDdeeNbsIXQtjViy3rV_m92dtzG4dJJbYEu9jkj8LzyzSXNVsvuEWwT0lX2aS4UJ_QTOGlpK86OeQHMxRqO9dMZp9gE
m_03
}

sprite $Cinema4DLg [20x20/16z] {
LT254SCm44JHjSNu--ysSvCpFJ63NDlCh9U2EmyvRft-wLgzJs3SNJE1Y_-zHkCn923mKga7f9EN0OsjpDT62ZmcHXAFRFrRqlhs9Uix-H2V1tTWQPtM6Rsl
0Kad_ZSBPlP3wz3DkwGsvJOG91DfLWoVvIgObMH-
}

!procedure Cinema4D($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Cinema4D', $name, $tech)
!endprocedure
