' definition of the Item simpleicons-6/C/Coda

sprite $CodaXs [10x10/16z] O-270XuuYn-3nSG9PJ400NOM361Z0G

sprite $CodaSm [12x12/16z] O-3XXm5M1du48C3cOs1WWh4PG800cv-PaOkV6FC1

sprite $CodaMd [16x16/16z] Os3bHmOC3FoeW7m-5oC3AnAVdG42u0f9vFE1EAmiIFPnSV2HxJwugG

sprite $CodaLg [20x20/16z] fSwr0S0m50DHVOLv_sd3RBQlVDM1qwyUc9HgZRK9rdoifpG_8zQauyjAN3q6JnEDTOfTs4oL_bcfJR9UiM81

!procedure Coda($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Coda', $name, $tech)
!endprocedure
