' definition of the Item simpleicons-6/C/Codacy

sprite $CodacyXs [10x10/16z] FOg30S1054DJks__QK_VYDJgb1MjNng3hLDMiRcJ1GJQLaUFz4VkyfJViu4A

sprite $CodacySm [12x12/16z] PSp50SC03C30AtEr_xH5vnMP4LmjN6HJKDXKrEw_rqvtQowLuT3vQJZ7ZeNQJ3omqSMX7lE0Zhm1

sprite $CodacyMd [16x16/16z] LSg50OLG30F0mvtiF-qNd7lQDZRrxA7IXwIrILX9iknbQh0aytPNTcEssE1Keus7takIhAzwIbvruQMaN9ncD7Sc2PR2sA1Fqe0Y2LUftEi5lW

sprite $CodacyLg [20x20/16z] {
RP254O1030GFTxR_Riby4dpXxIQkODpqf9B03hPQ0PjhAp2618swJbemff3ev62qqb3CahaOXbL2cEjBeplJZyr69BgnWltzGzkXsvzcgXRq3_lDYgdiK5sI
KGgIvEeOKapFvtNhlSTmCoNvMhsk0m
}

!procedure Codacy($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Codacy', $name, $tech)
!endprocedure
