' definition of the Item simpleicons-6/C/Comsol

sprite $ComsolXs [10x10/16z] Oo0TyBC22GuM1WvYDG

sprite $ComsolSm [12x12/16z] Ow0Mu6HXO6DWO6HXOs2an1W

sprite $ComsolMd [16x16/16z] Ow0pO69aPc06OY00Ce0aBpyZa6HZO6TWOMDWPQ0t

sprite $ComsolLg [20x20/16z] rOK50S0m4CJoLsR_QWikjeE47oQN6l4t4Ybuypx0MktIt-Oi7x4Co30Xm9uVFfu3

!procedure Comsol($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Comsol', $name, $tech)
!endprocedure
