' definition of the Item simpleicons-6/C/Cora

sprite $CoraXs [10x10/16z] Oo0MyFFpy_A30P3Dm0z4d0pyl2pyR40M5twj

sprite $CoraSm [12x12/16z] dOG70G0X08JuFPN-QPq9z0vWPalFzeNLLSEpAsmtocL4qIZ_8uFB

sprite $CoraMd [16x16/16z] jOS50GD140EpS0pZNsr9GpySFOtBKOVCZS4PLoJwXjKKB2b-_wYng1X6jk-_rL7V8UqbxxATKt_66m

sprite $CoraLg [20x20/16z] pOY7RGGn0CFeRb_Z_jj6M-GfG8rVefuTdsV6oc6SNJ34NYtgyj5RsCr1ipkflTtwGNQbE6qiFH7Twc776z_B9UgRMsV9TpGVXH3_V_u

!procedure Cora($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Cora', $name, $tech)
!endprocedure
