' definition of the Item simpleicons-6/C/Cryengine

sprite $CryengineXs [10x10/16z] Oo0CUFaWD1ylCoubO0bULau65coo

sprite $CryengineSm [12x12/16z] Oo03iF1nC710sMnylEmiUDHoCh2nip2oCp2oiB0IOpO

sprite $CryengineMd [16x16/16z] jS6r5S10342nRtZ7iF-sgLo79VxGP2qweGY2I2EuhxqILrXgAgIMBLbIJTaoZkIMt3mZl7G

sprite $CryengineLg [20x20/16z] nSYt0SCm40J1VKV2e_zkzPaGoyv5j_nNPqqM1yyaMfZoRBgOQZURKsYTu-Pz5PmRezoELJVDvS_bdnBPK5T-u04

!procedure Cryengine($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Cryengine', $name, $tech)
!endprocedure
