' definition of the Item simpleicons-6/C/Csswizardry

sprite $CsswizardryXs [10x10/16z] O-Ad1c1WOE1dO0DZ48yBY7aP83903

sprite $CsswizardrySm [12x12/16z] jS470O000C2W-R_qRsiAOVIlinwLjw8tsz4hgCbLiUAOy04

sprite $CsswizardryMd [16x16/16z] pOc50G0W40Anszj_MciAxnEmVCxeRxS1pDPrI7XPMShPWYOqm78210SZLo38Pl7eLZhRlotC13LJOGC

sprite $CsswizardryLg [20x20/16z] vOo50GCn54A9UzX_sz9p6U5Uv2jOlfZy6i7Of50jJ5QCWCKVomweocfPnKvwC86azOJYrFjJWFgF3dPmw_rz_ktf_f47PIl2ty_XRxb4_ECF

!procedure Csswizardry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/C/Csswizardry', $name, $tech)
!endprocedure
