@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-7/bootstrap')

' loads the Item which embeds the element Bentley
include('simpleicons-7/B/Bentley')

' renders the element
Bentley('Bentley', 'Bentley', 'an optional tech label', 'an optional description')
@enduml