@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2022/bootstrap')

' loads the Item which embeds the element AmazonBraketTensorNetworkCard
include('aws-q1-2022/Resource/QuantumTechnologies/AmazonBraketTensorNetwork')

' renders the element
AmazonBraketTensorNetworkCard('AmazonBraketTensorNetworkCard', 'Amazon Braket Tensor Network Card', 'an optional description')
@enduml