' definition of the Item simpleicons-6/F/Facepunch

sprite $FacepunchXs [10x10/16z] DOU50K0X58JudSh-qzhouZY0nvEA-kbJfVS3wVY8OzzfXvpTa8uy3e732cG

sprite $FacepunchSm [12x12/16z] BSY50S102C30rBtPVzetE1ownvDWeF7FJwwT7v8M7_4NZNezqGrFyVXRFOYa_fNW3Ze3Xp_DPzE_5G

sprite $FacepunchMd [16x16/16z] {
LS-50KCX303H-ouGRlzfAqZbuKwejZ1D3Ddce59tuDPemvCcpE-g3glYZFAbgpldb67RheLYoA9AhMwrlWUNRXocl_NavCt21Z21_js_6Em6GrqBorXrw-74
TIJx46Qhkkq9
}

sprite $FacepunchLg [20x20/16z] {
JSY54SCm40NHDOgr_NURkP3r1ZxmLQRzPd7xDNQ-3BrDrGBXQSVK-hrsGYXwGOhhqHIqiDACmWOxS792qgAWtPrgiRFfj7Eg9eOwGBL2L-5KBz3kfAWs3A2N
GhzFOHTF3aLtLit1SB3IYrqB3nKesbYlKDMq0KUq0yBbWx-iOLo45m
}

!procedure Facepunch($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Facepunch', $name, $tech)
!endprocedure
