' definition of the Item simpleicons-6/F/Favro

sprite $FavroXs [10x10/16z] NOQ50O1008ImM_QVrlRh4Z9f2SC7dPMmgcYDxWgAS7VEI1NOeNNp1

sprite $FavroSm [12x12/16z] NSR50K81042XPxViFwtjBqwqiEBVdV7Zol6N2-j3tI6i0cfjcsiTL0xPLVyhlwz0TQZQ7pez0G

sprite $FavroMd [16x16/16z] RKw30K0X5Fp8klsdpNOz7PxhUZcTKmjWIZLWvPG3_ppzhyFyBVcdrFif1u2a76LbxhUdfQFJqvb8V1bSZ4QL0dEU8f6CzLmElYzZMS-N5G

sprite $FavroLg [20x20/16z] {
VO-50OKm30LJt6__QRz4yFP1xU9IKftkP0EkC05GtRteRv6moaqzr7SstVAtG1gCBG0Th033y6U4p5WvsenPkExRVnnZ0cYXABZNNPpr9nP-yudLQ9Sz9oQ4
b8tAP3qpOTEZ0TPutFG5
}

!procedure Favro($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Favro', $name, $tech)
!endprocedure
