' definition of the Item simpleicons-6/F/Fedex

sprite $FedexXs [10x10/16z] Oo0IyFE3232BXvcFWP-J7SW2GNvMLcu2UW4

sprite $FedexSm [12x12/16z] Ow00yBE0IKuc4Cd3pydFoC_9pC31mC_0pyV3ny_0oif4ifa

sprite $FedexMd [16x16/16z] jKg30S1030pUqVxJFbTemnFyN15-NdRYnmjib4lanBXHk4dtOP460HwV1u-kmUtm7OASeHBlGcRukXO

sprite $FedexLg [20x20/16z] pOZ70GGn4C9mW76c_selRX7cWoHSD4dv1rLa-JVR_C4qmAVjLcQ7vd9Yi5A0lLpwCUpKMm3VDc4fZEtCcXCAiYVeRpac6sC6Y8ls1W

!procedure Fedex($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Fedex', $name, $tech)
!endprocedure
