' definition of the Item simpleicons-6/F/Flask

sprite $FlaskXs [10x10/16z] JSZ50O0040F1uCxsNorwDf-8YbQ60IipCkSamzbPMrYMEEL0YzQlzXDmtW

sprite $FlaskSm [12x12/16z] JOt50K0n34AfKediF-rtwRj40Qo4fMVtjurUKSUpjegd1QGWlNqdFtanucFcyVkgZl4FpjBvPjS-d647

sprite $FlaskMd [16x16/16z] PKp70SGW39C1qstjl-rzBWb5BtLSq4FJzzYArqy6re1KqwDdwHR2DfVzRYgmM6QpoAA5KL2MGMUfww5udv8M8zgqs5U3T4W3wkEqIOxXvlxTn1G4-04

sprite $FlaskLg [20x20/16z] {
RSvL0aKX20HGi9MO_Q_sTLnZFWz9n-HmmBOZJDj27ICxyfM2ImqKgrmMeBI6J77g0neJvVc4KrrDyA0oMqNn6jDahDPeJGUyKvzHa8qvJ9O1hrJcnc93d0VF
260GFtUEFmx0UYbzzDhoLrEfUCVdNyDxvHq
}

!procedure Flask($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Flask', $name, $tech)
!endprocedure
