' definition of the Item simpleicons-6/F/Flipkart

sprite $FlipkartXs [10x10/16z] Os3W1mDU1XYB7yY00GmM0up5m074SDL0pC40130nDh0OZ

sprite $FlipkartSm [12x12/16z] ROgr0G0X0CJo_lZ-q-9SHQgJG4Y3WvedHdFb98bdapqeW_OQHpO7hDrz3xnoEDBA0TDo0G

sprite $FlipkartMd [16x16/16z] bOj50e0W00I7RlZ_QsqbRivf4sWVZXFHkQpk2D1jv8zFSVG9ADtVgdiDhVjQGTRF1ouUNvCt1emV_kLgkpUB5uZRxm

sprite $FlipkartLg [20x20/16z] hSw53SD03030Apo4zv-s31yNH3cHPKPU6fERb5jkfgMLe0yIkoNQBhSZv7eewnngcCtak0zZanjAIWafDNtLmoit3LrE1wH-lQ-Guyy7vfZ3l-WC

!procedure Flipkart($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Flipkart', $name, $tech)
!endprocedure
