' definition of the Item simpleicons-6/F/Fontbase

sprite $FontbaseXs [10x10/16z] Oy05-A4q6py_XCdE3m8G1eJ91APuW9WRo0DIZ211e0fcLAC

sprite $FontbaseSm [12x12/16z] Oy0B6E4i9dv-VWGJnc7aXm084yxXnmGi80c872S3a8FBHW

sprite $FontbaseMd [16x16/16z] dOY53S0m40DTvdh_QOl9WoXmaX5rz7DhvqboSLCEcN9GM6JgGSUoIXq-FrxhNklxr_4AxUSzUG0DWDVpk04

sprite $FontbaseLg [20x20/16z] jOm52i004CCwz-t_hvsT7pu9KWYX-8jrcvBfjel2gtOZSaMbAIChAaqPML5PRiRCk_gYffdeWwUWkLhWbYLmbGDG5hYfQ0gyuW

!procedure Fontbase($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Fontbase', $name, $tech)
!endprocedure
