' definition of the Item simpleicons-6/F/Freebsd

sprite $FreebsdXs [10x10/16z] Ou03FdvkVY1WvkTZu04ncFZv6HZueG31OeApUB28CS0KCeACX8e

sprite $FreebsdSm [12x12/16z] TSZ50O0m0CNGu4xsdnPtsdVvmeEsTDhJc6AfcgkGUnZWR4C7NfuzZVoGUYY0qat3fjC1O0O

sprite $FreebsdMd [16x16/16z] bSUr0SD00C10sNucxJzjcBjST_mO5Y2qkiCsfMcPNlMfWj6RfTgW-f1KeFXKp3luLlC4l_pv1KNVTi2t2R3v0ZVJcyPBREtWvWm

sprite $FreebsdLg [20x20/16z] {
ZSe5ZeHG0C3GViNf_KyxWhCwBscq_A2EBMyfvm1G-igi3i5LczIvPErwLqog6HmdDz4te7RknbcjGF3Kl0CwB_gAW5z5yAiE_6hyy8lG-GKGlEk1hoEyJLu4
Lhs7n2wuQhb99GSsJm
}

!procedure Freebsd($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/F/Freebsd', $name, $tech)
!endprocedure
