' definition of the Item simpleicons-7/G/Generalelectric

sprite $GeneralelectricXs [10x10/16z] HOY50O103CI2yzRiFoqkxJb0SkOybPK4FZU1dgDzIgAely-Qw0Q5R6tE24dFIy042Em

sprite $GeneralelectricSm [12x12/16z] 9St74G0X581GZ1lKJ__LRdmpdE4rtFcr9J1u97yTgaOoq04caAnfOD1Ckm--bbfstHTvcImS9eyP5k5q3Xs7U_zM3bs3nw2qIOSR

sprite $GeneralelectricMd [16x16/16z] {
DS670SCW30311yb0JFdzjqs_u-FQpiBVuc54pSP7dvfT9vENjlrh4rPL2meQ1OvrxEAzKvrNrGANBNnXLpKRCIbQmWjrOFM5dBvWfZoQD-LIl6U8E2gfPQES
FcJHmZLy6KiBCCE_Sl4oYNjmFFNYeqngbhfuUG8
}

sprite $GeneralelectricLg [20x20/16z] {
JS67eSKm24Mn2oGsk9tzj_tbLKbFTLXDN-wAoCiLm_I40AcbAqhwKnV0ua-fz0lZcztIhGsKNT2jmUvI2HeYG2C1J_aDDbAvLmH_ggmW9KGJ_F4J3Xnpjv9r
Y2kujG3K47-6OcK_u96ZvJGLA9e3NcZRY8b0eG2C8_9YOA3I6A2b3MfBYocNsM7b1gWyO5jIYI_LzQTq7y07S7UN_jnTVnPBMszP7h_AzUS7
}

!procedure Generalelectric($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/G/Generalelectric', $name, $tech)
!endprocedure
