' definition of the Item simpleicons-7/G/Gnometerminal

sprite $GnometerminalXs [10x10/16z] O-371X2YZ2YYf01cE0i

sprite $GnometerminalSm [12x12/16z] O-372bZu-TcHsFmC23OdiZW_5oUK3GOai3dWW8cN1G4

sprite $GnometerminalMd [16x16/16z] lSct0G0W4090p5dstzOlnG6yYW2AIOGR6EMtleDs4lh7z-VCMRhvrNCHSmwn3W

sprite $GnometerminalLg [20x20/16z] pSmr0i1030F13RFt_wyDbE4hRqfR4ejNtL9oDOfNbHWFjuxxpU1sQukqlGDmk-tol4LnCrJXrT0PLsu

!procedure Gnometerminal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/G/Gnometerminal', $name, $tech)
!endprocedure
