' definition of the Item simpleicons-7/G/Gnusocial

sprite $GnusocialXs [10x10/16z] Os3YXm061Y01PO8G7vW5bW2J40uNZCN02fLb1fC8lM00endOG0m

sprite $GnusocialSm [12x12/16z] HSpL0K0X34FHvBd2_jCYrOlqV1MeLX5wqujCUoEwxxAAxPKqO2R-ZURwyfQTPwwtKYZ23W

sprite $GnusocialMd [16x16/16z] LSc54SGm4C10XJdglze7isNSEJYjJM3N5BohRgftC3xwpEf3SEWidXZdWRUO8LpLaw5s3XGllCfMx01WjRw6Dh3fflGgRRht7CBx1G

sprite $GnusocialLg [20x20/16z] {
PSv50iCm34JH7uvnxd_QWfI5gavYUaPOfs8Qi2i7XhN5Qj-nOkrPRRHOlRdHL6R_jGDFD3ajqHQgf9qPxDbLQhRMMi-sm16iiadpPgPxjoMzHHUmwh6Y7A0d
EWdPxEuGtz0JdVzKLHSyRm
}

!procedure Gnusocial($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/G/Gnusocial', $name, $tech, $desc)
!endprocedure
