@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsLooks5 element
include('elements/materials/Image/MaterialsLooks5')
MaterialsLooks5('element', 'Looks5', 'an optional tech field')
@enduml
