@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsFilter7 element
include('elements/materials/Image/MaterialsFilter7')
MaterialsFilter7('element', 'Filter7', 'an optional tech field')
@enduml
