@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsPanorama element
include('elements/materials/Image/MaterialsPanorama')
MaterialsPanorama('element', 'Panorama', 'an optional tech field')
@enduml
