@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsFilterFrames element
include('elements/materials/Image/MaterialsFilterFrames')
MaterialsFilterFrames('element', 'Filter Frames', 'an optional tech field')
@enduml
