@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsExposure element
include('elements/materials/Image/MaterialsExposure')
MaterialsExposure('element', 'Exposure', 'an optional tech field')
@enduml
