@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsCrop32 element
include('elements/materials/Image/MaterialsCrop32')
MaterialsCrop32('element', 'Crop32', 'an optional tech field')
@enduml
