@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsExposurePlus1 element
include('elements/materials/Image/MaterialsExposurePlus1')
MaterialsExposurePlus1('element', 'Exposure Plus1', 'an optional tech field')
@enduml
