@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsCrop75 element
include('elements/materials/Image/MaterialsCrop75')
MaterialsCrop75('element', 'Crop75', 'an optional tech field')
@enduml
