@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsSlideshow element
include('elements/materials/Image/MaterialsSlideshow')
MaterialsSlideshow('element', 'Slideshow', 'an optional tech field')
@enduml
