@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsFilter element
include('elements/materials/Image/MaterialsFilter')
MaterialsFilter('element', 'Filter', 'an optional tech field')
@enduml
