' definition of the Item aws-q1-2022/Architecture/AppIntegration/AwsStepFunctions

sprite $AwsStepFunctionsXs [10x10/16z] FSR50S0m54Cn5puyP_zvourE0lfMnQndRIAMo7kPWcUzDH3N987euOkuZBlXUrTlS08

sprite $AwsStepFunctionsSm [12x12/16z] JOo53S1054BFlk-_Ru5OYJqa59HKHDJFj7ZBD4sQceOnitV5foeAQpA2eXvuc-4DFgUnEkjWMKEZDx2CoumC1FC1

sprite $AwsStepFunctionsMd [16x16/16z] NOvN0e0m24ExMVU_hv3uHPpl4Msjeenah0bhmidp2OLJh4jMBx7M6dcHRMRG-VcA78ETwAi-oIaRoGclLiGVe-Ot5HiQKGsH-Uyj87puCoGetd8dGp3W9Zu

sprite $AwsStepFunctionsLg [20x20/16z] {
RSy76iGW24HXku3tl-yEV0xRygU_DDKWj9q-H7s8IcjaDBOkZT4OwnnoMSG95TlA9jBs5bVOneAYRcNhWDPSpNUx29h2lCy955mEwBSLfyxt8kSOr07nLOWM
Tb4w4ArR_skOXcLZLMnVZTXOCxu
}

!procedure AwsStepFunctions($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2022/Architecture/AppIntegration/AwsStepFunctions', $name, $tech, $desc)
!endprocedure

!procedure AwsStepFunctionsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsStepFunctionsLg>', 'AppIntegration', $funcName, $content)
!endprocedure

!procedure AwsStepFunctionsGroup($id, $name='Aws Step Functions', $tech='')
  IconGroupElement($id, 'AppIntegrationFamily', '<$AwsStepFunctionsLg>', $name, $tech)
!endprocedure
