' definition of the Item simpleicons-14/K/Kofi

sprite $KofiXs [10x10/16z] JSd50K0X30FGVC4b-qzRE_L17TbNolzOvGUtkQstXzAjk8VVnB1c-ANw4lTwxnY9YqIc

sprite $KofiSm [12x12/16z] TS630KHH0C2mVZoZ-qzxDXB-cJfFr6KTtEc2TXiovh9uXiowepfXSHaiAZX1841Bm2f0aRD5jVBX2

sprite $KofiMd [16x16/16z] XSZ50GD14C0m7_Eu_seNmXmznLz3U14JeFiqzCKmRDgqyc3n23WSLbUmGuDPgvPoHh1fDR1JAcYqej1UM2rwq021KTlQ515SbAlSgLetpjG8dRaPfealCW

sprite $KofiLg [20x20/16z] {
bSy5aW8m5C3GL9VQp_rlkuF3EA-UqVABL6fhhTQIkDj-sK1u2YzbQyfslYHZ2rmS3Fy06nSLfdhKITBh4dpYsehnrIWGJc5uDm26emk4Lm4bT8CTy0e88mCA
qA81kBWgNdWAkTiExixxJqlTw-WxGRfMO_2ZVm
}

!procedure Kofi($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/K/Kofi', $name, $tech, $desc)
!endprocedure
