@startuml
sprite $AzureDatabaseMigrationServicesLg [40x20/16z] {
rOw7WSGW40FPAAtxB_W5vuiTl9o7mQjrnvj4-VfCW8BnYLBa5nR2bWNoMslE3DzYjQReQM_HGGbrARH3p1oscdd4pQo0ews769ir8ANXhCrp8-vvxUUtykfC
CeqCKgSMekMIbp8ZFgCtiRuBoTVNmmFdUB3bF9wTFYUtbsthh27ypFN4DKmyB4ycm-K10Nbj4MfaALqL2PSLGBFOsDMTmMjafJpNFL9UjJPH9IKkQwWfLyv8
krCbhrQXQj2rINCoktSDhowb6sYlEDKQvYcOxconase5Extk6BxU_eUNBozVhDjjMz6rNl6iabNnHbRWphtr3m
}

sprite $AzureDatabaseMigrationServicesMd [28x14/16z] {
fP17WWGn20C52iR-_uFNlNdEKuvG9uI7pamQtp0NVXUzPisU_bQkGlbJLcVKwvp1fQzI6d2XChCDz9pJA4lKqXH4PFOv-xxt8Tm0oXP0ub6JXZ8dRJpO19HU
UxjPQ7AT2L3oIipgQ0-bBaewOvNJIdEw0fgsx4JXhTPJM8dvFUkw51xKlyyRhbyTSIdNJuBN_QHRJfm8m0S
}

!procedure AzureDatabaseMigrationServices($id, $name="Database Migration Services", $tech="")
  CloudElement($id, 'azure/MigrateServiceColor/AzureDatabaseMigrationServices', $name, $tech)
!endprocedure
!procedure AzureDatabaseMigrationServicesCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureDatabaseMigrationServicesMd>', 'Database Migration Services', $funcName, $content)
!endprocedure
@enduml
