' definition of the Item aws-q1-2025/Resource/ArtificialIntelligence/AmazonRekognitionImage

sprite $AmazonRekognitionImageXs [10x10/16z] LSQn0G0G30311_p-2qDIkUhuL30dPPQNgL9zxTHYexpvTgFIXOaWcToGT

sprite $AmazonRekognitionImageSm [12x12/16z] NSQ5OGH030F1ERBLVyF9CmdNhthCFFaamyRKK0Eh3Ii4nHAxhtp5EvzIvsHenWZiUKKPNTUtHAyA99xw1m

sprite $AmazonRekognitionImageMd [16x16/16z] ROe50a9120M7vludbiNMFnlmWaky1-E7vacKQXdr5KZkeXZLWwiOKFGyR6E79jUpC-gXc_RSbJYs03ch0j8pXwqFZIP38RwI5Ayo99yo1QIKrKTWneFYani

sprite $AmazonRekognitionImageLg [20x20/16z] {
VOw5OGCm30HF_FilNB1SRd96yVE4RAc37_YvL7mdkXDylZmb1rDZwpJeu2PJ3Y2iqO5q1D08Iw3S40EGzFhy-CB0ZS8I5J8QDx3D4wsyURUV0BxwYKfq81C1
K3NEmOQ8useOmTwpMQj_fkpspOPGSD3iSx8elL4iLIL-OyOlNW4
}

!procedure AmazonRekognitionImage($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Resource/ArtificialIntelligence/AmazonRekognitionImage', $name, $tech, $desc)
!endprocedure

!procedure AmazonRekognitionImageCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonRekognitionImageLg>', 'ArtificialIntelligence', $funcName, $content)
!endprocedure

!procedure AmazonRekognitionImageGroup($id, $name='Amazon Rekognition Image', $tech='')
  IconGroupElement($id, 'ArtificialIntelligenceFamily', '<$AmazonRekognitionImageLg>', $name, $tech)
!endprocedure
