@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2025/bootstrap')

' loads the Item which embeds the element AmazonRekognitionImageCard
include('aws-q1-2025/Resource/ArtificialIntelligence/AmazonRekognitionImage')

' renders the element
AmazonRekognitionImageCard('AmazonRekognitionImageCard', 'Amazon Rekognition Image Card', 'an optional description')
@enduml