' definition of the Item simpleicons-7/E/Eljueves

sprite $EljuevesXs [10x10/16z] NOc30S1054DVxMR_QS_-21b6HQYANxgqoGzYvmQkqAKbHF34C3uvjW

sprite $EljuevesSm [12x12/16z] ROk50O0m4CI2Ezb_MbpRvbsE10KtjTxjwDtCQAQ3iypkPCY8x9mvHoIx9OoSp9-C9QNyMG4

sprite $EljuevesMd [16x16/16z] ZSZ5bSHG34JHP_ipLVxPpgbfqBQlMFogQ47Gq2H8iQTCzhsb8ywHsSHzqwIUkvJXue0IzWYiLBByB0NhK8IoDtikk71BO0UBUPthsr-wf4u8Vm

sprite $EljuevesLg [20x20/16z] {
dSW5WiGm243HJoffs8P__zEkkyyy7AwWVBPhyi5XLpvObSzKeBGxQPJEKCz3RQSEPVDLe-dK8BL7H2y73-OE9a-6F3iJ76H1Jfu8MFWut_-IVF_BnekuuLdn
TTlaYHkleYgFh0e-wDdvnHq
}

!procedure Eljueves($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/E/Eljueves', $name, $tech)
!endprocedure
