' definition of the Item aws-q1-2024/Resource/GroupIcons/PrivateSubnet

sprite $PrivateSubnetXs [10x10/16z] uy01s3cOEOW1R4Ie0G

sprite $PrivateSubnetSm [12x12/16z] uy07c9ZPuKmaOMOa9YCp441KiQ6GZCWYh6Yo4BtCSBq8

sprite $PrivateSubnetMd [16x16/16z] uo0IiAFmc808LH95W1K_dnaAsA1yB3GB6f-P7SudJ3EpG02GJn

sprite $PrivateSubnetLg [20x20/16z] uw02O6DcPaCJOcK74in80Z0k6vfM24c660iR3214SR6OMTbGnS281LCTCwPUTeHvfB4GpYC5

!procedure PrivateSubnet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2024/Resource/GroupIcons/PrivateSubnet', $name, $tech, $desc)
!endprocedure

!procedure PrivateSubnetCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$PrivateSubnetLg>', 'GroupIcons', $funcName, $content)
!endprocedure

!procedure PrivateSubnetGroup($id, $name='Private Subnet', $tech='')
  IconGroupElement($id, 'GroupIconsFamily', '<$PrivateSubnetLg>', $name, $tech)
!endprocedure
