@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsGolfCourse element
include('elements/materials/Places/MaterialsGolfCourse')
MaterialsGolfCourse('element', 'Golf Course', 'an optional tech field')
@enduml
