@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsFreeBreakfast element
include('elements/materials/Places/MaterialsFreeBreakfast')
MaterialsFreeBreakfast('element', 'Free Breakfast', 'an optional tech field')
@enduml
