' definition of the Item fontawesome-6/Regular/Bookmark

sprite $BookmarkXs [7x10/16z] O-2700OGO8TGR4HHNFpyJ6py_DmCG2C

sprite $BookmarkSm [9x12/16z] O-2705v-NWumuEVdP0032XZyF606Dpy7Bpyxq70-Y0m

sprite $BookmarkMd [12x16/16z] lSP50G0n4CNGFylO-5TR1WTDBay_hJDnfDPyVvpL5tom9aT91YwEARL1

sprite $BookmarkLg [15x20/16z] rS-r0O004C30nvtRVrhSD-2wb8dMGzRwY5ltusp8hyp0k6Swq4OwqdIFvHmwYZWqp

!procedure Bookmark($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Bookmark', $name, $tech)
!endprocedure
