' definition of the Item fontawesome-6/Regular/ChessKnight

sprite $ChessKnightXs [7x10/16z] Ou02VY1WOE1c0J61a0T8WmIW52zOb9yH8ic0H7610G

sprite $ChessKnightSm [9x12/16z] FKk30S104AlnolxJdgrWgu36Bhl9y-FVLdTyns_N0_mf5U3LOtEF73-SaepZzUFz4C4

sprite $ChessKnightMd [12x16/16z] JSc55S0W4C1Gf6xPVzjUgWJxzqXjqn4jMSuynRIJh3WSsi3z_bGGne4Uz0uQlP5WudM2NUfAhxJxyzwuwU3l1

sprite $ChessKnightLg [15x20/16z] {
NSg54S0m5CDG_PGfsd_QCklmdSslgFVIIQ_gJTbc6vjH9s2mkMzvMuEpoGwbyzvHeZhPMIbtfTt1DW2I_K4l9krIVvDMTU0YapbnCnGUrZPlDbPl4jn5qB_h
9Zyj
}

!procedure ChessKnight($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/ChessKnight', $name, $tech)
!endprocedure
