' definition of the Item fontawesome-6/Regular/CircleDown

sprite $CircleDownXs [10x10/16z] BSE30SG00C30UwF8_jFM0VnwWthuzACHz1BdlmT2KJKRtXyg4jU_G7ZLKAm

sprite $CircleDownSm [12x12/16z] BKs50O003B8R-VzR2LadWt7p60eI9yYaMpeF__IM0GCLfYxSa1-RyvGp50xrRwMpykn33v8_2hFJNOOollQWuEu7

sprite $CircleDownMd [16x16/16z] {
LOu55WGn34BJSUs__stt0Mj39H0lOxuvMtrm4wnM3JQJYri6FdaJbvBTuDI_C5IIEnKpVqXBmltG1UI7i5F_OJb8Dp8QPWUAoojcENejJ69ZqXnQn2sNcBwu
zXCOCBhu2m
}

sprite $CircleDownLg [20x20/16z] {
PP05WaKX30DnXxd_QLTA-pLF21EqJjKFguXJLLGx6W9ErAWRMfPc61z8UlblWg8sWqBvrBUR_RMSLoQc4x_OaQaX9HWf_ViDmhYITIPBM5Vc__oXK9s4m5qQ
x2mBoB8qs-rhtRaJf1_iqD5A9EihL2Jjm8uRDaIh4B3dWTSf3OJVxNu1
}

!procedure CircleDown($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/CircleDown', $name, $tech)
!endprocedure
