' definition of the Item fontawesome-6/Regular/Clipboard

sprite $ClipboardXs [7x10/16z] Os1Wu69X008sVduWany263Y1W1ae00HuAMvUBY3W1m

sprite $ClipboardSm [9x12/16z] Om02NWu6CE3dv-U6K8oy_430pWybsI7oP3BO-A4

sprite $ClipboardMd [12x16/16z] jSQ50S0m4CD0bRdQVzf2S8BSWyrljIEvrF4lqtbwe-V9v6yomffq0Q5dpJjMBm

sprite $ClipboardLg [15x20/16z] pSU50O1034FHu72Ll_-qk6x0gqQxDbsFmgg-8vGaj0as4fk-m9Uc-olRqdGOZdZxRJIot439oxG

!procedure Clipboard($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Clipboard', $name, $tech, $desc)
!endprocedure
