' definition of the Item fontawesome-6/Regular/FaceLaughWink

sprite $FaceLaughWinkXs [10x10/16z] BS450SG0000XtcLo_TFE0NwzxUhXquz6krvowlSGmwnSXlT7Eycd8h_imgk6OWK

sprite $FaceLaughWinkSm [12x12/16z] DSY53S100CD0bp7r_jjMJoS8K3oUD9eZIgaRnMklHO9WVvz0O6T63mRFS5dCY611wI-qUe2Xy0E8nG4_

sprite $FaceLaughWinkMd [16x16/16z] {
NSv50aGn2C3GV9TISl_JZZ7-gjd1mz9j0o_TibM-Fc6lX38PqELjSS0DpXbOPaWN0GKrcErIYlvr4yOiW8EmM0PsCI2z2p1PdU2iQKEWkr32jPwSWTrA67n8
W2i
}

sprite $FaceLaughWinkLg [20x20/16z] {
PP07aiH02CJQEGte_x-z0ehR9AT6u3HISJbZrniR53Qr0doHT01Ngz7T6UvtLS0MpshLiWvfKNDo2i_c8bt06lcAgeRzaT-H7NrXyECUHhsYYKUmSzJJYrc2
VFn4KTbaqJjebVMKQUbLERAyG4sgu8Qpp6GmlosfFLvFR4uIgw4_
}

!procedure FaceLaughWink($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceLaughWink', $name, $tech, $desc)
!endprocedure
