' definition of the Item fontawesome-6/Regular/FaceSmileBeam

sprite $FaceSmileBeamXs [10x10/16z] BS450GGn0C2mZddrh_Rn4e1XvKiJpG5klYp8WX9n99ACW_9OjJ61WiXKGOPy2HHT2cy

sprite $FaceSmileBeamSm [12x12/16z] HSR50KCn0CKm5uCltd_QuWUTnDUmygSfqLyVV4sFGeBSlH714HQBGaCBEslE8nVhPVhxX6a72nY-N03ngy0R

sprite $FaceSmileBeamMd [16x16/16z] {
NSU50GD120NHEPU5dVwhZH5_wETXITl0IrgsYgydp8fG9WDIU5aSS0E3Mjr5wEcCwSHi2YiijL0fnVQN1s4GO1LsCK0DRM1dTOAr6mE4GBfGmhLEdu7TYZ3u
q06k
}

sprite $FaceSmileBeamLg [20x20/16z] {
NT25OK0X303H0xuXuVQVjfRwmrqWzUsw-ENK50MIkXjmg_shQq6gElvr0Nh2cLs_EZCnTnvLuV713Ls5fXRGRWCRLbOdEkWMo5kLJA7optJ9FzlB6nZPR2UW
A5IjG5Se1c65OOAFTb6W38qd_-5hHVhgWg5FzfJG-kjBOsxzlUJnG-IaLm
}

!procedure FaceSmileBeam($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceSmileBeam', $name, $tech, $desc)
!endprocedure
