' definition of the Item fontawesome-6/Regular/FaceMehBlank

sprite $FaceMehBlankXs [10x10/16z] FSR50OC0002nrBst_xGuv1LuTGTryUX5Nz1DLhqkkkglR3xtnxPqxDKMRlKfHW

sprite $FaceMehBlankSm [12x12/16z] DSR50G90402nuBfC_zNYbrV0hJEWvZ857S4zgyo84mvq6s8NTR5q7jO5w_VL4mte0TF7YHS

sprite $FaceMehBlankMd [16x16/16z] NOk55O0m50E3ExV_jhoK-bL_H87buHgKUFZPP0ROPMuUFv1oCxV3ogoCSZZpif0gl0w4E4U-G3LStJmqyucugvbNAtCURuSVrZok__FwFV5eHWAl_ny

sprite $FaceMehBlankLg [20x20/16z] {
NO-50GGn20Jtt4Ac_sfVzfo9ug23fL96FPWuY4u7GEqEqtAgYWu6M9FAqY1DLZsLFYzcPb4bBVOTehNZGkUtzrtbsw6ZMsXTCm0bDWfAL4Qcf0Fbu9PGCEY1
vVRjE5bS8Aka5MQPDg2J6G1Ygm3FmKqCbhu
}

!procedure FaceMehBlank($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceMehBlank', $name, $tech)
!endprocedure
