' definition of the Item fontawesome-6/Regular/FaceKissWinkHeart

sprite $FaceKissWinkHeartXs [10x10/16z] DSI50OC000Inr1Lk_sbnyWAVdbPry-f3VwiUikjpqrqfXz_pXT3vtNmYh-9Hlunc

sprite $FaceKissWinkHeartSm [12x12/16z] FSQ5RGG1400n_p6jflzk8un51cyNeEQSWdRmzLzcn8w5tY7wFdK2w1e84lRee0zHqLXHOQgkapy

sprite $FaceKissWinkHeartMd [16x16/16z] {
JSV5eSDG0C0mbKCltd_Q3sMTR7UNqNhmCdgukNl5re3YuTJ6Y9TB1ztmidS9nLPdvqPe8PU9ohVMm9Ix3g-uiHrEQOCHQ-7Q2PhTgXXTs1SytjP-ngH7E7Ht
X5y
}

sprite $FaceKissWinkHeartLg [20x20/16z] {
NP25jG0X3C1oRj3iF-sNFaw31o-DBImp3oORjJkL6WEmgDkf2erUzu_AqGIJfpfbbXUhAmQmrnmUIoxS7B8TGVDeZTowxC3OqNTGLJuSbjF5-OTmTcdIQAte
kMNyhwIVgFRfQhkw7w3JUwy9R9hA3fRcs7KbETzzXhGUOI43UNuygII_
}

!procedure FaceKissWinkHeart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/FaceKissWinkHeart', $name, $tech, $desc)
!endprocedure
