' definition of the Item fontawesome-6/Regular/Folder

sprite $FolderXs [10x10/16z] Oq00VY20CC046C3akC4yD37yB0Qu1W

sprite $FolderSm [12x12/16z] Oq06_4303MLoWmW-PY1WuES4Yq009q8r16284yNcuUE00Nu6RZuOO0C

sprite $FolderMd [16x16/16z] Oq07h7n0m0tdil5308mFP44e7X3WPeB9G9KXLCA5UP41N1KEzLJdCsBOneWC6

sprite $FolderLg [20x20/16z] nSp55S1G449HufxNVxLnvSp-tzq8A5GVCdrmgVGOQVUt1fhFc_r3_knoFcG683S3iS7CKL-oNGFp7sZ4bGgi

!procedure Folder($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Folder', $name, $tech)
!endprocedure
