' definition of the Item fontawesome-6/Regular/HandPointLeft

sprite $HandPointLeftXs [10x10/16z] Oy06-C60Zv-H3ynZO0HYi1281elmS_0pS0DPpBmW0Mwe9eWiY02nu88

sprite $HandPointLeftSm [12x12/16z] TSn50aGX3C3GV3Texd_RGPVpa6PL_beg2rQR0-A9ZyAIY4N88W9lmh1y5ERBOFIrH1wDw-en-ppCtZGvwkuV

sprite $HandPointLeftMd [16x16/16z] ZSVL0O103C3Gu5R8_jFYUb-yapRyDaJaG3R4pir0xca2Qb5s3XGrMZdkrWuffNC5HoEhVbkiZAqt7hXwsDVyxje8dUvcDCyBAq9s-xGBQmxkjami

sprite $HandPointLeftLg [20x20/16z] {
hSc5aSGm0C10XMDK_zN-7tZ2mxTccTy8lat0v45LEthTyAPKQHGwI2xPfVjIQ4itMoEaL1tPtadUeZte6irRwxJfjiPW0HIEBTuQDjiFq6lVzyc9RckOWTw0
pbkprkfRO6F3ity
}

!procedure HandPointLeft($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/HandPointLeft', $name, $tech, $desc)
!endprocedure
