' definition of the Item fontawesome-6/Regular/HandPeace

sprite $HandPeaceXs [10x10/16z] 9Ok50G0W3CEAE_d_MdI-YcwCDoSHoxqGgB_BzjGXF50murymn8KYmBri_CwC_d6vKJjJ6m

sprite $HandPeaceSm [12x12/16z] 7Ss54G0X50FHdE6m_NTxaopsnlXotrQwu6KJyq0NiN5_HmalPzTtWTPS4c2FTbIM_t8nJAcVdJc9HsA77T-79Fq

sprite $HandPeaceMd [16x16/16z] {
HSa70eGW4C30s1LOyl_Vtfvrg04kDNYCiM1wKjqTSEGKKXNaiWXw7XSRJKAjTG0seQEbgYIZcwQbu01XYgzTIQOsd3rHrA5tlRj56KZJsGkF8g3FmsWbDUF-
bTFYfG4_
}

sprite $HandPeaceLg [20x20/16z] {
JT05aWKX4C3GOEDqxd_QLRh-fFpXaCrP-DIsGbUjPA5kqrOrgJbtLVZOviRvRqzQCK0dmurCAuyxZseRQw9WGGtLFvrsBb09D_srOSQyY3zJDU9jQmVKmnib
hxfDLscgbhBrbzLxOvNsgXh0ySQSSUjOKi8xlqRdTLsF6gpguse3-0O
}

!procedure HandPeace($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/HandPeace', $name, $tech)
!endprocedure
