' definition of the Item fontawesome-6/Regular/Handshake

sprite $HandshakeXs [12x10/16z] TOR50O0m0CI2Ezb_skeBwMbeIsTrp22h550GP-WgEzeLbYmJ7tPczBxpz-h1In4

sprite $HandshakeSm [15x12/16z] XOc54GD158KuzwN_RhC-4kChy_XBa4SbibsN3mOOlU9l6F7X94P6Rf374MYgE1HzA9XrY5qqiZA2WyEjmDW3Fl42

sprite $HandshakeMd [20x16/16z] bSYr0S0m4C10XUbjxJzj6CjSUVmp3fJZLFFG8BjXqqtJf0LQ0ZgjL3CeL43oK1uLiedx4bdZSw7MdUbzL0FGEHtNgvn68-pCsfxPTswob0KejgW5RB5pnqyB

sprite $HandshakeLg [25x20/16z] {
hSl5WKDH3CLGXH-DrN-r-SpBoLbUsVnSqGTPjR2dtd76w5Dxcc4-Jbe7ZbxSD35wkmBG3rGPVRRm6lRGzMaBYJyrpW77jUavt5eae1gxu9DLCy-Xe6PM3WAh
obYsDKBbTWSqOUMbLc0OPywuQ95Aj1l_q04
}

!procedure Handshake($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Handshake', $name, $tech, $desc)
!endprocedure
