' definition of the Item fontawesome-6/Regular/Message

sprite $MessageXs [10x10/16z] ZOgr0G0X00ClhpZxJulJSqsKb2S-iKXvEt_gqYk1f8onuSdMsXVuvgC2

sprite $MessageSm [12x12/16z] O-3XXm4s7dvs6E3dPsU00Qgn6K2sCB22BGCByF8Z9A5C

sprite $MessageMd [16x16/16z] pST50S0m0C30Z7dnhtPOaj3x7QEbq1AbwewlXS4VD4rpk7aqBpwxZXHsYMu

sprite $MessageLg [20x20/16z] tSlL0SL0449Hrdrl_zK-ZQU3dByPG7PorcIvcHDTJ40NxJ6_IJ0V-Z8_8Fwam698kPJIyGtAJz1VvCFe9FuMPu6atHi

!procedure Message($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/Message', $name, $tech, $desc)
!endprocedure
