' definition of the Item fontawesome-6/Regular/PaperPlane

sprite $PaperPlaneXs [10x10/16z] DSl50OG034JHjuhp---MKpmPCR7FKRCBIh_OU-cI3gxeLVxXGdqvuDzO_o4F

sprite $PaperPlaneSm [12x12/16z] JOp50OLG0CC2ppNxJ_jTwAdE7_l7gdxOeL-kX-F5bmKNGd71bY3wIc3qrpmBx1FAvy7FY_F2XtuvS1Rk

sprite $PaperPlaneMd [16x16/16z] {
LOw55KCn30Fr8Got_xRrKpdeCqf_wzX_2FnGvvSpz2yVC0NhnHiKg6qUSCispONDAKVm9V3C5MPmk0c_2ZNU2wUJRuOLkDsvtdFVuoR0AJ5-61hvmvTVapJS
tUi1
}

sprite $PaperPlaneLg [20x20/16z] {
PS-54SD030NHDREt_sf3VqmN3JynVp4lfVHgGLhQQccpsZ-iLJkqToLHgGjeLpiTWtxPtOdEvXXK0Rh1OfMB-XId5jGSlcMXifiY9dU8LQe3z4fi0-fLNGvg
7KYVQWl0OYYxTG8iJAsVjZ7i-ZJ8TuUbvOWt
}

!procedure PaperPlane($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/PaperPlane', $name, $tech, $desc)
!endprocedure
