' definition of the Item fontawesome-6/Regular/RectangleList

sprite $RectangleListXs [11x10/16z] Oq02_0W05-FWP-1dWGXn42FAX27AYMGk

sprite $RectangleListSm [13x12/16z] ZScr0G0X00F0lE9a_sbnxRWgWWrNSjq_QDm5FB-BO94BXbIUm-SQZ_NVG1W_Y0W

sprite $RectangleListMd [17x16/16z] bSjL0e1G44BHQxViVxLs-_BypG3ybEFJGAclaPVrKJIGxlQ7nA0T62Tv0_acYvaakx29FW_qmTSC

sprite $RectangleListLg [22x20/16z] VSp50OH05C3Gu4xwhtOL7td7Bo6X2fHWn3BRLK-hIg3_JRiHYdAtJxN6mpuTPYZhJRLFuzrPwCTTlbjsGB7BTxLaSNUTXbsAME5fiDFrILaCDKIz0G

!procedure RectangleList($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/RectangleList', $name, $tech, $desc)
!endprocedure
