' definition of the Item fontawesome-6/Regular/SquareCaretDown

sprite $SquareCaretDownXs [8x10/16z] Ou01VYY0y9ZWD4G2I8COO75MVhWyWeRf1m

sprite $SquareCaretDownSm [10x12/16z] Oq00VZXWXukmG5byo2nMi2Am65Wrc0Layi3KyQ3guE5bXG1-1cu-2607

sprite $SquareCaretDownMd [14x16/16z] Oq05h7nmmCl0oeyAaDGHuZ7pWW4FXCSEDm1CS8CvZ31zF42A6M4ABpyxifcCXErZm70b0W

sprite $SquareCaretDownLg [17x20/16z] ZSx50O1044FHuCxllrfSrzznDB8LNxd4tpJI51ypeAycjP1TxWAt_YeCNFAh84xbUtHcKt-_70U-1J5OEP8B3SmVe8cVIgOL

!procedure SquareCaretDown($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/SquareCaretDown', $name, $tech, $desc)
!endprocedure
