' definition of the Item fontawesome-6/Regular/SquareCaretLeft

sprite $SquareCaretLeftXs [8x10/16z] Ou01VYY0y5X1D1iNc6RZXz3yK9e1HZEm0sceUfX-

sprite $SquareCaretLeftSm [10x12/16z] HSY55K0X34FHVCN9_jFYX8Vqdk94PRNv-tY0F4GkSSjBI1AYrCinsHaHyinK

sprite $SquareCaretLeftMd [14x16/16z] NSV50O1044MnXpk__sfnTYIt47LxiLMz8anPvxUgiMros-NMoeynZ3wCLjKtarR9Wyfm0W

sprite $SquareCaretLeftLg [17x20/16z] TSY53OG04031_STr---M-0bXuiFRd4rWTPskStAhP5kAgON-Izmjj8OjrXuSFJXwiFLWbHhm4OlUYN9PJ7GF

!procedure SquareCaretLeft($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'fontawesome-6/Regular/SquareCaretLeft', $name, $tech)
!endprocedure
