' definition of the Item gcp/Item/ManagementTools/CloudMonitoring

sprite $CloudMonitoringXs [10x10/16z] Oy0FsA205SnYP82oE3Wu680i3YXWWwZ5PGW

sprite $CloudMonitoringSm [12x12/16z] ZSQr0G0W30J0ZsV_XN5AvAh33_EDrtaVZk1vIiqCQO_S618R1Wt5HGK

sprite $CloudMonitoringMd [16x16/16z] fSV50S0m30ImCtl_XSlCJVGJQf5ltH-y7d2aydoAH6QAz0UHvKY8kkOM9kBOKWiLb6W1

sprite $CloudMonitoringLg [20x20/16z] lSY53SC050DHVtAz_y8DCucIfnCTFi6TUdhkssTj0Ly_9C8bZ-KP9LCBCRnMQkB3q0vFNcAMT6nvybU9TpG

!procedure CloudMonitoring($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'gcp/Item/ManagementTools/CloudMonitoring', $name, $tech)
!endprocedure

!procedure CloudMonitoringCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudMonitoringMd>', 'ManagementTools', $funcName, $content)
!endprocedure

!procedure CloudMonitoringGroup($id, $name='Cloud Monitoring', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudMonitoringMd>', $name, $tech)
!endprocedure
