@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-19/bootstrap')

' loads the Item which embeds the element ServiceMicrosoftDefenderEasmCard
include('azure-19/Item/Security/ServiceMicrosoftDefenderEasm')

' renders the element
ServiceMicrosoftDefenderEasmCard('ServiceMicrosoftDefenderEasmCard', 'Service Microsoft Defender Easm Card', 'an optional description')
@enduml