' definition of the Item homecloud-2/Brand/Backup

sprite $BackupXs [10x10/16z] DOk54S0m3CHKxb6q_xOvazuC11S4h_vQ1H31Oac8YDTVLOi_eWEu-XTwiW4

sprite $BackupSm [12x12/16z] DSZ5OS00002XYtlOVzfwUTAFgJylBtiLLPFdPstNWZbXmo1jAcLwkxRAbBJyVoQ_Dkre2aCzXcgrLityxYS

sprite $BackupMd [16x16/16z] {
HS770SCm3C10E9IR6lRVDkJBTq0vWazesK1PxWOyUfAcTehQ84pz7RS5tDrImXSRtG5ei3o4LzBFWySGXXI3IuHRqYbqyK7zSMfdo_RJRM2A8-WcuDIWTAKq
NVVLjvBAQscaFm
}

sprite $BackupLg [20x20/16z] {
NSi7ZaKX3CLG1pI8l8BtlzjHqEz7_JhXAJfVud1RWwUXclDKVKofoHPgUrq5PQhkjlqTvqpB3OTfULZQKA9gZw5U31E5Fs-A0gumwxzJBXjeTy9fKBAQuWdJ
GLcoDwqkL39eNYmZLQzSgf4EXhy0oqNhX6MmHnTRx5gQZzYofeVRxT4UMYxrUYp_
}

!procedure Backup($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'homecloud-2/Brand/Backup', $name, $tech)
!endprocedure

!procedure BackupCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$BackupLg>', '', $funcName, $content)
!endprocedure

!procedure BackupGroup($id, $name='Backup', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$BackupLg>', $name, $tech)
!endprocedure
