' definition of the Item homecloud-2/Brand/Ubuntu

sprite $UbuntuXs [10x10/16z] FSY50S0W3031htj__sbnk7X8BdSoYwikvu8RolamwwNOYaVzT1y_T05-vJBP4DZC808

sprite $UbuntuSm [12x12/16z] FSY5OGC1302nopDh_sdBZSpkssdhbr_lzOd2LSl07LFVy-7yETd3rW0UDhenleYhynb3K5UivKUUgXi_tqy

sprite $UbuntuMd [16x16/16z] {
JKw50GGn3ABkoVxR_b7UE6cH22xAyHNmmN6XYRwP7J-Y8hnjXNS5qF9p2o35sZQKBC-dco6v-_7Oi9s8QWL4KqyUoyqntWORyWETSMLSns96O3j3VMyQRlnl
UtBkXUq2wKKGCzvV
}

sprite $UbuntuLg [20x20/16z] {
NOq55W8n34IdhcdkVrjUXBKFQsE5CmxlYWU57Gfm-C7uI2I5-P1cfwGVvRzrnAKuvDrZYBsj14JvwAe5PBCmvV5CyqRG8MveeQjqcm3YSesEnlcaW_JArMUb
sy5c02P1kWIIhpGW79sB2Am401FmGmV_AQf1c9TOIPfAuHjST1F8GZy
}

!procedure Ubuntu($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'homecloud-2/Brand/Ubuntu', $name, $tech, $desc)
!endprocedure

!procedure UbuntuCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$UbuntuLg>', '', $funcName, $content)
!endprocedure

!procedure UbuntuGroup($id, $name='Ubuntu', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$UbuntuLg>', $name, $tech)
!endprocedure
