' definition of the Item simpleicons-7/C/Chakraui

sprite $ChakrauiXs [10x10/16z] Om02Jdus1X3W1mCkA8E5dvyLp08Jd206Dpy4G1MpmMKP81X4SY7Ki48P

sprite $ChakrauiSm [12x12/16z] JKo30G1H5EhiQ_zflvwD2jqUdX2ZM1f96v-Mdypm0_5-NsBr-PGjwaAVVncFqF-5fjSA

sprite $ChakrauiMd [16x16/16z] NO-55S0m24JZBljFMxiYBp-AW_c8StThYBb1XhYPHI8nnHbwQrW4yHSjHK3anAVOMONNugb7NiiTPQf2cUOM4er3ueTLqzm

sprite $ChakrauiLg [20x20/16z] {
PO-50S0W30I3E-m_RJKyzYrsSMA5shAbIQQnYkYeJOf0CroH_dOpvMhKJnh8yoM0JTO0bC0gexdH1Td_bS4DYjYE4WL4uH8nD1L68uaayPs-B0KZMW9YE4MU
dKA1A_vEDm
}

!procedure Chakraui($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/C/Chakraui', $name, $tech, $desc)
!endprocedure
