' definition of the Item simpleicons-7/C/Codeceptjs

sprite $CodeceptjsXs [10x10/16z] HOk30S0m44LV6tl_QMESxmDUs5GeunWZZF4JrzSP56MSOWdaMX_E3CWxSPpSmu3kHmC

sprite $CodeceptjsSm [12x12/16z] LS570GD1400WRdiV_sxp3lXNEz6X5dn1Oq4if4aYxCyDM2zGCaPWomBFkv_30mW0TWTm3jYbtFZu0G

sprite $CodeceptjsMd [16x16/16z] TSmv0WH120B0SkwhvV-_tR2ZhL01_oG5LA-i4c3xm9cLGe04RljfW-pWRRoCE1GPq7BveDSB4jHB2wolibs4PWg-kp3dKS0QJ6jsvlTB0JpToGO_

sprite $CodeceptjsLg [20x20/16z] {
VP250GCn24MZ5qFsd_O4-kjjF0yd_1zLzV7fogGrY4wG9D4VfbODmM2vwJetaAavJ182kJuxuqZZ2d9kqZI8ahtofLClKxXHqmipDos1LpAMtOjuXE9HOM29
HMF8xyfxK3lFV8AAEf2dM0GT9HUKQfd0zb4Ena-Kdb2pSrFl8DnrObwtE0S
}

!procedure Codeceptjs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/C/Codeceptjs', $name, $tech, $desc)
!endprocedure
