' definition of the Item simpleicons-7/C/Crystal

sprite $CrystalXs [10x10/16z] Om02DWOeu0S120FA16CWu693oFF3MK3416CXQO4RmmbX

sprite $CrystalSm [12x12/16z] JSV50S104CD0Eypklzii7EarWiK9DSfw2ql9wmpp8m1vosmi5iJ1Da_nQwDY51Yx4Ks5Fm

sprite $CrystalMd [16x16/16z] LSg53S0m40J12tE-_swZUsKDQnpPoYvrXTigwOMq_7pt8pBp7EedtNBLYiwx8ipJSFBoCzwyOQuJ7EqCwkqfBMybxV03

sprite $CrystalLg [20x20/16z] {
NSq73WGn24DHQthQ-lwddMgj1K_z9m0-nuQiyDQcbAJ59CF9dFfQr9GARfIAKYPyFBmLfSaDBFdu12h-w8LDaOQPRvne0DyudBg6IlY6ng3ZmG2lddv9eI2O
wl_N1G
}

!procedure Crystal($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/C/Crystal', $name, $tech, $desc)
!endprocedure
