' definition of the Item simpleicons-7/C/Csswizardry

sprite $CsswizardryXs [10x10/16z] O-Ad1c1WOE1dO0DZ48yBY7aP83903

sprite $CsswizardrySm [12x12/16z] jS470O000C2W-R_qRsiAOVIlinwLjw8twz4hgC5LiU8Oy04

sprite $CsswizardryMd [16x16/16z] pSc50S0W4C30rF7iFoqsHG_UJt-kbfr3LLiiJ8yN1uUHIJDIzN0Un0MEg3T7mAsSCFErCzAKJD81

sprite $CsswizardryLg [20x20/16z] vOh50GCn0CDq68xtdpPS7g7w67VzaFLld6ocYT_0DhrXexCfGaksLNlJsAywaBGTecb60mU-wyQUX2O7z3flNVN4hN0H-qSx6ahN2W

!procedure Csswizardry($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/C/Csswizardry', $name, $tech, $desc)
!endprocedure
