' definition of the Item azure-19/Item/Iot/ServiceWindows10CoreServices

sprite $ServiceWindows10CoreServicesXs [10x10/16z] LSor0G0m30F13nYq_y0XLxdAA3xcPXn-s2iZ6CGjWzdcAMlqAf8vX-Mj4cRwgPIIAiOks

sprite $ServiceWindows10CoreServicesSm [12x12/16z] NOW50W0n2CFAqIB_V_2vRPaGWfa8IPVuwvb9knUcaOkdjAkJJcHgVqR3vQW0ITJXNcSk7VtYo11LVTGJxHow0G

sprite $ServiceWindows10CoreServicesMd [16x16/16z] {
ROq50WGn309XGqBx_m_VScvJ7Ih1VwO34Oxun14quHNGzXGxWHBO1GaOtovuA1qIxHPiawAKRVVTWRfxUmaYgx3MwJWN8DVxuGagEb6k1xxLtrixJ6uZg3i8
3_Iq2m
}

sprite $ServiceWindows10CoreServicesLg [20x20/16z] {
VS-54SGm34JH5IlzDtmhmtZmNlY7RFoJQMRkZYSoOs3JL4XIa9wthXYsMr6eUBstXGbG0w8cdmOFfxcxMvM3ry8Dqmn5mgPcgsNuRGO8stuvkrjF0xhdEI2w
02T3J3DGjqzK2D-90CrPWPmdkLlrKn42wk_ZkfpvKa5Y9fqlKLm2F1RXXkq7
}

!procedure ServiceWindows10CoreServices($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Iot/ServiceWindows10CoreServices', $name, $tech, $desc)
!endprocedure

!procedure ServiceWindows10CoreServicesCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceWindows10CoreServicesLg>', 'Iot', $funcName, $content)
!endprocedure

!procedure ServiceWindows10CoreServicesGroup($id, $name='Service Windows10 Core Services', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceWindows10CoreServicesLg>', $name, $tech)
!endprocedure
