' definition of the Item simpleicons-7/F/Files

sprite $FilesXs [10x10/16z] Oq05JBn0mC0F18pyC03cWeKOu28G9Kn0m8yB80m5

sprite $FilesSm [12x12/16z] Oy07s1ZvOO23dn71P6Q0C_dve6nsVcukVWYRYPqN2FZuyG5U93QobG

sprite $FilesMd [16x16/16z] dSor0S0m34JHKvZ__jE6oMuChnAU8XLSr1yCuwUXCgTbqDVMxEIqzTUNC9RVlkph9-EpBEJIufZasG

sprite $FilesLg [20x20/16z] jSg35GKm04FHrExRVzflc_SmqDlis4dQQvOziL78XdDbaCn51NHTlYZeyeL15o_wHEUlfWawLZsdnffZpnYxmzzahkb5Im

!procedure Files($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/F/Files', $name, $tech, $desc)
!endprocedure
