@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the AzureAdFs element
include('elements/azure/FlatSymbols/CneEnterprise/AzureAdFs')
AzureAdFs('element', 'Ad Fs', 'an optional tech field')
@enduml
