@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the style
include('styles/azure')

' loads the AzurePowershellScriptFile element
include('elements/azure/FlatSymbols/CneEnterprise/AzurePowershellScriptFile')
AzurePowershellScriptFile('element', 'Powershell Script File', 'an optional tech field')
@enduml
