@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../../"

' loads the library
!include ../../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureWebServer element
include('elements/azure/FlatSymbols/CneEnterprise/AzureWebServer')
AzureWebServer('element', 'Web Server', 'an optional tech field')
@enduml
