@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-11/bootstrap')

' loads the Item which embeds the element ServiceSecurityCenterCard
include('azure-11/Item/Security/ServiceSecurityCenter')

' renders the element
ServiceSecurityCenterCard('ServiceSecurityCenterCard', 'Service Security Center Card', 'an optional description')
@enduml