' definition of the Item simpleicons-14/S/Saudia

sprite $SaudiaXs [10x10/16z] Oy01EFWve2nk1dOGnS_FpmCY-85CHdu6VcP-Y2W88LWGm8ng5W

sprite $SaudiaSm [12x12/16z] VSZL0O0m04F1Xtko_xIuGtkVHqobWbrgTG1vSqv7Orju1WnjOvmh1z3w5QlCT3Kx9-AKyJO1

sprite $SaudiaMd [16x16/16z] ZS7N0OKm3C106TCXrlxJlbxup1sTWgjTQ-BlgFBWAG5YMdaRKDj4GAnD5_05dtO0zrIieHelQf1QV7Wab7p4Nk9wy3CPShKaVUu

sprite $SaudiaLg [20x20/16z] {
hSv5OaGn3C1G_J3h_gSjSpU5UTl4jhY5qWEVpQQdPJxgq-EuldnSv9fuvXdn0Y8XmbMdYyidAr9z1WIVB7nodYiSrtQZBHvvrlIaGcxgUuaAHVrGir8uB3u6
DfUYmy07UjdumZZu9l1Rzm
}

!procedure Saudia($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Saudia', $name, $tech, $desc)
!endprocedure
