' definition of the Item simpleicons-14/S/Spreadshirt

sprite $SpreadshirtXs [10x10/16z] JSWn4a1G50J1_lKoiFS_BMnaegxnxy0g4idwuCh8seF1Dq16MPH5MK3n

sprite $SpreadshirtSm [12x12/16z] NSUt0S1048H0vBtelrgPt-o81aeTC8Mt7RjREBdR_QCm2PtxQ4ywPB9ht8KsOIRCX1cflG

sprite $SpreadshirtMd [16x16/16z] ZSi52iG050FH-TXkTUv_sdgmQj0t43wiBA2LK8jM3KjRXxyU11rX2nj1sCBch5KImeIL8oIi7824C25Co3UJwyq

sprite $SpreadshirtLg [20x20/16z] {
bSn55WH1309GsgM4-zzsNafWjiqczb_mANbfvLsWlEJIoof5nl9jHMhFP9JIP5C7K4bkG6doZLKxxL529l94ozPB9P7rLy_ROVbVXPUK0YIj9AqihIojBAqi
hHmhn_a1
}

!procedure Spreadshirt($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Spreadshirt', $name, $tech, $desc)
!endprocedure
