' definition of the Item simpleicons-14/S/Standardjs

sprite $StandardjsXs [10x10/16z] Om01RWO8uE3dvmSp-240o80188k9cO69cOqV8iOEnAWi5aOMk1QOEH0Q

sprite $StandardjsSm [12x12/16z] FOr70i0m2CFSaUtY__-scIW1T1Cc3OSYwPvsQz5LJeLOIQCO6lI4nq8BUhftiaBVoy7lkFLLX_Tbr4cO1YUzIlW1

sprite $StandardjsMd [16x16/16z] LO-50S0W40DJrpJxRzlWSEWz-iWyw7aaBTKs9QPeaogqtkg9HnbdCf_zU9_jt83rvXFSqSyjTefk3krsLSTD3YxCpVdYUX4zXMzNnlVCgKHBWT5ELAQmDV83

sprite $StandardjsLg [20x20/16z] {
PT3L0SKW04FHuDQI_QTzWilvl3WO4aw9fDsAPpMBvF2WuYQMIQVQClyK_qnfDdeNZNVYjIuONHkJrCf0IgbeQplD5XZSsMIIBf-DkESnIxqrQ2MKbgsXRF94
CiMI0duqLzjN5GhJMuh3HhoCQBu
}

!procedure Standardjs($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Standardjs', $name, $tech, $desc)
!endprocedure
