' definition of the Item aws-20210730/Resource/ApplicationIntegration/AmazonSimpleQueueServiceMessage

sprite $AmazonSimpleQueueServiceMessageXs [10x10/16z] Oq00JWOM18kRWPi5pcA5iDWPs9aXBE9qCB6nCx43nG

sprite $AmazonSimpleQueueServiceMessageSm [12x12/16z] ZKo50GGn3A9jFFlF-t_k5XS0MwkrkbJXKe4kF12EQLumtKmWGfanRbSOWJ3AHvq8pqXZmHy

sprite $AmazonSimpleQueueServiceMessageMd [16x16/16z] jOs30G1H34FVDxh_l6URDHDM8ZcBSjbgyIGWrTPBrok5qedTlUxs-Sv-YH_vXLygmOabUm8b

sprite $AmazonSimpleQueueServiceMessageLg [20x20/16z] nG_50SD0w3YqiF--HUgIRt2NzHCq4j1tR4SNy8fTzbf4pvfdJAjZOvhFMAGLLQv7lVSwVgk3jE3N3imT_8nPMlOHEzvnwX-uj-IEdNyGpCqe2S3GZ1Mx0W

!procedure AmazonSimpleQueueServiceMessage($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/ApplicationIntegration/AmazonSimpleQueueServiceMessage', $name, $tech)
!endprocedure

!procedure AmazonSimpleQueueServiceMessageCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleQueueServiceMessageMd>', 'ApplicationIntegration', $funcName, $content)
!endprocedure

!procedure AmazonSimpleQueueServiceMessageGroup($id, $name='Amazon Simple Queue Service Message', $tech='')
  IconGroupElement($id, 'ApplicationIntegrationFamily', '<$AmazonSimpleQueueServiceMessageMd>', $name, $tech)
!endprocedure
