@startuml
sprite $MaterialsAddAlertLg [20x20/16z] {
VT055e10201HIPF7_M_h9hPZVtk7lvWVX6Pu8vhS9xgGcgTCJoG9jYsj90YtH4Hv7S_aV1b0CkTucY-g0AgBQrZVrRFDmkaHCfyjddSrn8kDdbhNl1uRYNba
KeYsIvGDi4HKjt0Uc1YM24HW-6a7
}

!function MaterialsAddAlert($id, $name="Add Alert", $tech="")
  CloudElement($id, 'materials/Alert/MaterialsAddAlert', $name, $tech)
!endfunction
!function MaterialsAddAlertCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsAddAlertLg>', 'Add Alert', $funcName, $content)
!endfunction
@enduml
