' definition of the Item aws-q3-2022/Architecture/Storage/AwsSnowballEdge

sprite $AwsSnowballEdgeXs [10x10/16z] FSR70KCn048nTtXu_tcJttKI-2I9hp1qAWhGkpoTiC1wnxmMeEXOA-NOyCw92lif_04

sprite $AwsSnowballEdgeSm [12x12/16z] JSU73SD03CLGHFLJj_--SRSV6Wberni-0_BJtcQ-xozwi0Oa2yrO9-2V3fqza5dQMnAYMsjsc0pMDRlrcJy

sprite $AwsSnowballEdgeMd [16x16/16z] NSXR0a8X30DHc-9D0llVhz3wdhyptgdZoN_3VsCZCj6DCf71L6Q4EBTfaPS4I7Dk8wkFVSAlDVIo9Tq6DxSd0u0HTwACaoC6qrgpyoPah_VGPMz_Xij_um4

sprite $AwsSnowballEdgeLg [20x20/16z] {
RStN0KGX24HHbJXi__tk-7AwdqS1iDoBDR1JdtRY8Z7pfSrSYLlULbCC4JM99jADLjC241QPmoAZQbhgsc9PLJJFxTRBy6LgULegisxII9iLcA0rtypWp22M
4GqqDjeCW_z2QRzVRK4bR0I0qmhedK9Z9-9bTThhvny
}

!procedure AwsSnowballEdge($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q3-2022/Architecture/Storage/AwsSnowballEdge', $name, $tech, $desc)
!endprocedure

!procedure AwsSnowballEdgeCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsSnowballEdgeLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AwsSnowballEdgeGroup($id, $name='Aws Snowball Edge', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AwsSnowballEdgeLg>', $name, $tech)
!endprocedure
