@startuml
sprite $MaterialsLocalCafeLg [20x20/16z] ZT350OGm443HKLpwhtO5ulvlFE8m7aaOFQQtwpgE3HFRI4vAR0NAR6FDx3xF1RDnz51ewojb4s-BkyVcZYpWSDcVLe4WV4k_CN3QmmvzXadoLEDz0G

sprite $MaterialsLocalCafeMd [14x14/16z] PSx50G0X30J03UxqN-q9BlEB1mTYtH_950jhvH_bId2zH4gkaTLyxGIkYASI18P2c4yPAkY7GffER8yH3Yy

!procedure MaterialsLocalCafe($id, $name="Local Cafe", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsLocalCafe', $name, $tech)
!endprocedure
!procedure MaterialsLocalCafeCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsLocalCafeMd>', 'Local Cafe', $funcName, $content)
!endprocedure
@enduml
