@startuml
sprite $MaterialsLocalLibraryLg [20x20/16z] {
jS-t5KGX34HHFCWSJV_TBjzxidsHvcPoeq9mzufgkL4qmEBDqBkP9u3yCSDq-vJyFbmoQTEUl8cbsT3Zr0-UhiDWjHfkDlK_Yurr0-KMjqyoJK8vU7VaisgU
u5ACRjGF
}

sprite $MaterialsLocalLibraryMd [14x14/16z] ZKu30W112BncZUh_hptRsKrp9VAUjiofkjiC_P2r_JY6f9Q0teLI1yUgxDnWvsoW7rdcESaOWC1brUn0TyWswW

!procedure MaterialsLocalLibrary($id, $name="Local Library", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsLocalLibrary', $name, $tech)
!endprocedure
!procedure MaterialsLocalLibraryCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsLocalLibraryMd>', 'Local Library', $funcName, $content)
!endprocedure
@enduml
