@startuml
sprite $MaterialsLocalParkingLg [20x20/16z] fP235K1H34EVLUq_xRUDUrWtKM-mhiNgHKfdwG2lbxc1iChb63C9sKMEso1qZNFEjAT4uddVl8_RVVkxj_-5MSVghlgTcxtIwZqr

sprite $MaterialsLocalParkingMd [14x14/16z] VSc53GD150DH-ozp_zKcHnOTZF1fe1HjYv8VMpL8QxGsbfSowLUH4c2zyb8D8Q-ajrTDQYa6GafGtw8HZ_q1

!procedure MaterialsLocalParking($id, $name="Local Parking", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsLocalParking', $name, $tech)
!endprocedure
!procedure MaterialsLocalParkingCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsLocalParkingMd>', 'Local Parking', $funcName, $content)
!endprocedure
@enduml
