@startuml
sprite $MaterialsEditLocationLg [20x20/16z] {
bS-53GCn40LHCyet_LSRMEM7wKRePtPVyY7u9obZhL7kDNIi7cwhsXcs2StB8kTQQ11bvKmbn0f5Lh510-hTkghLiWJ96v5aVZB7TgRfdSfSoX9RQ8txZoJk
Jhl_YNwXmeGPt6DfhUIUozdjxGW
}

sprite $MaterialsEditLocationMd [14x14/16z] RSf50iCm30LHewWmzpzjwIUhPZQsfDV-wijizNC8W3Z63KImDINutAHWuNq-AD5WpZk4vABkmDBK4o1xK-i9pzdE75m_MRcZCTf5Rm

!procedure MaterialsEditLocation($id, $name="Edit Location", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsEditLocation', $name, $tech)
!endprocedure
!procedure MaterialsEditLocationCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsEditLocationMd>', 'Edit Location', $funcName, $content)
!endprocedure
@enduml
