@startuml
sprite $MaterialsLocalMallLg [20x20/16z] {
jSf75W8m30DHATrs4jt_jFGEMsRvt-0UYOzIZ-ZfdS9gjNZ3RWHe_MshEDKU8vlv3ZiLswtnR5cADdHgj93osOfaI4jQ2IQLcys4wbwHvjCq218SUZ5P8Olf
pQIrf7SxzqTBljUZxGddc5uYVdS4
}

sprite $MaterialsLocalMallMd [14x14/16z] XSh50GHH20FG46oCJ__Lhhk-MmH7eYguaYbpkiLmm0Cdj2NCOZ4URsl5t3r7hGAmDcgLSYiUKuUG4dr98yroNDF5txHTqtP8yBnmlDW3

!function MaterialsLocalMall($id, $name="Local Mall", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsLocalMall', $name, $tech)
!endfunction
!function MaterialsLocalMallCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsLocalMallMd>', 'Local Mall', $funcName, $content)
!endfunction
@enduml
