@startuml
sprite $MaterialsHotelLg [20x20/16z] {
hSg54G8m343HUEhPVrlIud0El_wkyEVG-Tk6v8QvRjtCUcFmqNTDZt54DFAufTiqB_Df3TDeH1HyMDy6R8Rmi95cH9opllwBTOfNc_sjCT8Ktz9j0cz9cjAx
aIByq0K
}

!function MaterialsHotel($id, $name="Hotel", $tech="")
  CloudElement($id, 'materials/Maps/MaterialsHotel', $name, $tech)
!endfunction
!function MaterialsHotelCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsHotelLg>', 'Hotel', $funcName, $content)
!endfunction
@enduml
