' definition of the Item aws-q2-2024/Resource/SecurityIdentityCompliance/AwsWafBotControl

sprite $AwsWafBotControlXs [10x10/16z] HS770OH0000Xr4tJVy4NNe9NL23Y087qPybA9DSZ1fxnFC-50mAhGLy

sprite $AwsWafBotControlSm [12x12/16z] JSU73S0m4CD0khwq_y91t8d6uyr0k4yeGm5-PkPNuAUdXVNN0ATmneemdV-bu4_nrpfJf3czPeAEc1d07m

sprite $AwsWafBotControlMd [16x16/16z] {
NKw70GCm218paFyVBgdfnBsDV-XjBih1384Cx4uOzZfir3Wwx-HRpnPW3G5tD1WD7ayAbZoh9EG6EFRCncQmkzxzUkfDoiHCX75KcIwmivFv_dJM6K2ycpxU
0m
}

sprite $AwsWafBotControlLg [20x20/16z] {
HSy75W8n24NHHmZbxt_37jGPRdeFhENyYIM0reXtJtCJI3YQxkvC0To6SHdoop36xXxzLdXtCm90K7eOblyv7WK2AQcK08b2El-p2Cpz5FJ_hCa1DOLT80vj
ZwGOcbCtNUwEvGPY1x5kiyJmn1I6i4hO3PPINuPOXyS7
}

!procedure AwsWafBotControl($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/SecurityIdentityCompliance/AwsWafBotControl', $name, $tech, $desc)
!endprocedure

!procedure AwsWafBotControlCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsWafBotControlLg>', 'SecurityIdentityCompliance', $funcName, $content)
!endprocedure

!procedure AwsWafBotControlGroup($id, $name='Aws Waf Bot Control', $tech='')
  IconGroupElement($id, 'SecurityIdentityComplianceFamily', '<$AwsWafBotControlLg>', $name, $tech)
!endprocedure
