@startuml src1-diag1
!include ../../.gdiag/plantuml-libs/cloud/library.puml
include('styles/aws')
include('elements/aws/Analytics/AwsAnalytics')
AwsAnalyticsCard('card', 'an optional functional name', 'Molestiae praesentium aut natus dolorem. Aut consequatur fugiat a consequatur ut.')
@enduml