@startuml src2-diag1
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.gdiag/plantuml-libs/dist"
!include $LIB_BASE_LOCATION/bootstrap.puml
include('aws-20200430/style')
include('aws-20200430/Item/Analytics/Analytics')
AnalyticsCard('card', 'an optional functional name', 'Molestiae praesentium aut natus dolorem. Aut consequatur fugiat a consequatur ut.')
@enduml