@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/azure')

' loads the AzureApiForFhir element
include('elements/azure/IntegrationServiceColor/AzureApiForFhir')
AzureApiForFhir('element', 'Api For Fhir', 'an optional tech field')
@enduml
