' definition of the Item simpleicons-5/R/Reasonstudios

sprite $ReasonstudiosXs [10x10/16z] NOd50S0m4CDKvch_QGjnNZamyezaL0zWrHiLj1QuHKHfeumAHS0OVW4

sprite $ReasonstudiosSm [12x12/16z] PSY55O0m40JHnPtjlri6Yqxa_ZizcVU9jaShcdW3IyHcim-ifm5yjb-_gjm4d_RvUfHQl-bfH2tp0W

sprite $ReasonstudiosMd [16x16/16z] ZOx50SKW40KNTwR_Qhy4FMRGzIS3YrmeWBRDnY0yLWI8KW7i2DQ_NmDeUQw10o-dKU2s5TmslBP9j-q1tBB_ZJkBB0zcM5t98cwLNm

sprite $ReasonstudiosLg [20x20/16z] {
dT2r0GGX00NHl-vC_zqUhjczS72KdCngRLXVNIUY9vSRvyFPuqQEaHOyctPVbcfOSWit9IymktOfUuPsGTSsw1lyqvwnMLsRSPxIZAmFvuffbpSRablPcfVL
hkehVW
}

!procedure Reasonstudios($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/R/Reasonstudios', $name, $tech)
!endprocedure
