' definition of the Item simpleicons-5/R/Reebok

sprite $ReebokXs [10x10/16z] uwS3

sprite $ReebokSm [12x12/16z] unza

sprite $ReebokMd [16x16/16z] un_X

sprite $ReebokLg [20x20/16z] unzKO1G

!procedure Reebok($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/R/Reebok', $name, $tech)
!endprocedure
