' definition of the Item simpleicons-5/R/Revolut

sprite $RevolutXs [10x10/16z] 9Oa50S104CCoviM_sgSU587jywMFppBj2WW7HA4iDvYRahEaZULU-GHpeSyC5G

sprite $RevolutSm [12x12/16z] DKo54GD1429v5vR-ktquOGOzWN5IN10iAhAad_Cg15li820pcQTTvizSpJrxP-pj-Jz--5bgFCqWa-utUuPoPm8V

sprite $RevolutMd [16x16/16z] {
JOu50aGX44AnM-v_szt1Ny-S1aOUcxlXel76oTw4I3mVFLw_hdlTpiNZlUrnx0paD-xfWSaAEDhCUBgQgL-xxUyu1g3GoPvoFkFLwMtl6AsdtPv5ybnS97te
N1BrfoKQm0y
}

sprite $RevolutLg [20x20/16z] {
NOu74eGm30DjEcdx_z_Uo3Fn0QBkAiqY-zq7e-sMQMJQT53FrNqvEf3EPYhzwKv_z1xT1jhYqbjKD8mOiWf4bvaLg3gLGAJX7GJW5hG4dB4EtwEii7_SWbPB
vpphDVOxumn5__7Tdjk6cy0IrV5oLvubtPCwxrZAvZxqxQlP3m
}

!procedure Revolut($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/R/Revolut', $name, $tech)
!endprocedure
