' definition of the Item simpleicons-5/R/Rockylinux

sprite $RockylinuxXs [10x10/16z] FSV70S1020D1ELil-g-M37k10HxbHIGP4zcp4kQFgrV0-IQ2IEJ7H71X

sprite $RockylinuxSm [12x12/16z] JOkr0O100CH2WqFsdnPzkLIdl6pE_FWJKaDwX7QBFdzpbI2_hDK0hVobPvSJt

sprite $RockylinuxMd [16x16/16z] LOy73e0m54BvxitzRsl0bDId7OzkcFdcMMZS_5XjnV38sN5fSiy0_fdJmwxwZi91L1pasQc2Yd9MW2WTO2NBse9RLQuZeaiqhta1

sprite $RockylinuxLg [20x20/16z] {
LSy53iLG20NHgNlP_sg_4kRrn6zGqdR7EOEMIDT0YiPcfDr8axDacTP7DkUU40pnTHjrm1GF0F_AiwtYNpctLVk_4gkwV6BagghwZDugmyqgGwhgQwYi8ihw
3ww9hpS
}

!procedure Rockylinux($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/R/Rockylinux', $name, $tech)
!endprocedure
