' definition of the Item simpleicons-5/R/Roku

sprite $RokuXs [10x10/16z] Oo0Iy3FmCxAmCh2pC_3pS_3pSOFuGCpFpmqYyEi5

sprite $RokuSm [12x12/16z] bS450S0m44MnN-O-_sh74t29Z6fr-d7TlSSvwkJY6BJK5g8DHYI2Z4u

sprite $RokuMd [16x16/16z] jOUt0G9054Av7Fbl_sszrbx9wCy0_FL35BWd2WC1c2KEg248ntNb1BUHy9Mx8-_N-xL-Z0y

sprite $RokuLg [20x20/16z] pSY53GDH3C1GVyvHlF-qPL4NQ2so7dzKPXxVfgIKlJCMhBKAIzcT7kw7cCDMV1PAFjZaOyEPuiCksyEgol5WNOTSTX-r1gsMKQdFQup2hxe3

!procedure Roku($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/R/Roku', $name, $tech)
!endprocedure
