' definition of the Item azure-20/Item/Identity/ServiceUserSettings

sprite $ServiceUserSettingsXs [10x10/16z] JSR70SCW40319Um1rt-_jh8qh-5BdsYkPvb0ZmZ82POch4GjsXBKhexMumIS4Vu

sprite $ServiceUserSettingsSm [12x12/16z] NSV50GH038LG9fxVVy7h-ax07tTUyie4LvPNhTLvjhFYggu0BNYQ9I0HcUTaCeBCzEkdPAUUW7pruSS5

sprite $ServiceUserSettingsMd [16x16/16z] ZSr50aCX30HG8fCFS_y35wVUlbKywGyEm5FeJ0sDiSmS0rd8amD1NYstQAn6pAdfUGl60Y0ki9MZvYBje_3gALnGPRAC73r7BamIZU-JY4DghjUHthW1

sprite $ServiceUserSettingsLg [20x20/16z] {
bOw50SCm3C3CWVyFNarZgegH4KwX1oygvDnuKyNU2y2UtLvxpoVdtEUPLraxiO3zlsfBvZApgbMH6LNyVuKZFHmYvTgT5LBymrafvUBZtQmNOSclZCs05gWb
jpLke3iT3uG3jJiKFd41
}

!procedure ServiceUserSettings($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-20/Item/Identity/ServiceUserSettings', $name, $tech, $desc)
!endprocedure

!procedure ServiceUserSettingsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceUserSettingsLg>', 'Identity', $funcName, $content)
!endprocedure

!procedure ServiceUserSettingsGroup($id, $name='Service User Settings', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceUserSettingsLg>', $name, $tech)
!endprocedure
