@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-17/bootstrap')

' loads the Item which embeds the element ServiceDefenderEngineeringStationCard
include('azure-17/Item/Other/ServiceDefenderEngineeringStation')

' renders the element
ServiceDefenderEngineeringStationCard('ServiceDefenderEngineeringStationCard', 'Service Defender Engineering Station Card', 'an optional description')
@enduml