' definition of the Item azure-17/Item/Other/ServiceContainerAppsEnvironments

sprite $ServiceContainerAppsEnvironmentsXs [10x10/16z] XKkr0O0m0CDZ_z-BB7ZRBF6k0M2HUIW2ikTT2V2bacLNi-Ny_Fk-7pO

sprite $ServiceContainerAppsEnvironmentsSm [12x12/16z] JKk50SCm35FCyF-_2wrjm1RYUsICeM0YCj3aZ36dBamMSh65PLLEhEpX4nSR04-lUIRYZRjxvtDZsXYpZNaEPXnigcfd_W

sprite $ServiceContainerAppsEnvironmentsMd [16x16/16z] XO-50G0n20EhaEJtd_VThLV58TonXUDTjBzlB0xiSdOtewIwoCNSPrcpF4fmruJR55rsUSvG5titudMEt-KrFmcCSZdwY42pp-MzpLS7

sprite $ServiceContainerAppsEnvironmentsLg [20x20/16z] {
bSy54iH024HHo2uDTEv_thZx_3Bg9MDorHzJWgbAC7t3CbcPwSyyKZVcNV0a6Oi5C1bfixc7xmp8te930PXqRMs0zR-wBu5XlwrXEYDZiP39BCdCph1_cqR4
_NlVJOSg4xKfMOOM
}

!procedure ServiceContainerAppsEnvironments($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/Other/ServiceContainerAppsEnvironments', $name, $tech, $desc)
!endprocedure

!procedure ServiceContainerAppsEnvironmentsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceContainerAppsEnvironmentsLg>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceContainerAppsEnvironmentsGroup($id, $name='Service Container Apps Environments', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceContainerAppsEnvironmentsLg>', $name, $tech)
!endprocedure
