' definition of the Item gcp/Item/CloudScheduler

sprite $CloudSchedulerXs [10x10/16z] JOc50O0020Hfs7zYFKpYKtvZW09UnPsgH6PnrQnob5_PaA68qr4CxJi7

sprite $CloudSchedulerSm [12x12/16z] LKg50G0W29i2W_yVjfDSuQzyhsIsKXc4gHtbXX6mr34wTl3WMBX36rWLlY0ohRkEaKaa-t-h0W

sprite $CloudSchedulerMd [16x16/16z] XKh50S1024C3-qzShEz3O_GkKIBpEdgK0VTQMO5Xyu7D3yquKAzFPX8FCZzkw_ZFiLphSj6KvNsR1kbohsUGCdXuO80YfAcXfei5zAmF

sprite $CloudSchedulerLg [20x20/16z] {
bOy74iCm20JNd3Zp_m-d8bAc9MTBsg737mfjEZGWbkyAr4OfR4jf-zZ6iBy0dbJd8ApdMrMn6O-jm7hQDBO3vxTDRNi-givTKyyFqmcEdYg8DgLdlhrgMcqh
TvNqEVE5MnelW39N04lyh2i
}

!procedure CloudScheduler($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudScheduler', $name, $tech, $desc)
!endprocedure

!procedure CloudSchedulerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudSchedulerLg>', '', $funcName, $content)
!endprocedure

!procedure CloudSchedulerGroup($id, $name='Cloud Scheduler', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudSchedulerLg>', $name, $tech)
!endprocedure
