' definition of the Item gcp/Item/CloudIds

sprite $CloudIdsXs [10x10/16z] PSYr0GD100Cm7Nl_XSDvL6F0tHmKPK9hIVTfHV9vcYdLfylYKnE5yVbDkoS

sprite $CloudIdsSm [12x12/16z] TOk54S0m30DVfjF-2vURmxmPn9RyQbzHLBhxgXUHQHlU7l7qebA3QwdBlDp_hr8bMLbiEG4

sprite $CloudIdsMd [16x16/16z] bSp50GG124FH3o5C-czuNMuhxuI6lytmvBtsngKSrVSUIbAIWuUM2YUFhbfLvWXz7upOBMSGDsgAX2T9JXRUWtTyxuZEu2a3Rfwc-UOC

sprite $CloudIdsLg [20x20/16z] {
fSr7WWD134BHBw32_Kyygd6sb_rsYd1D_LQJeKTHcg8DcqZUoodMuCvjj_0ajtcQ7xq2NhrITOynY-vPDEDOp9dkHN0KPLD1vxRUSZcjnMVmHso0MqzGecrM
1dWFQYHLm5ZYPKuk-GC
}

!procedure CloudIds($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/CloudIds', $name, $tech, $desc)
!endprocedure

!procedure CloudIdsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$CloudIdsLg>', '', $funcName, $content)
!endprocedure

!procedure CloudIdsGroup($id, $name='Cloud Ids', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$CloudIdsLg>', $name, $tech)
!endprocedure
