' definition of the Item gcp/Item/DataLossPreventionApi

sprite $DataLossPreventionApiXs [10x10/16z] TKg30G1H5AfExR_mwLkF2OlQ7O6nxTyN3S8Vaabeqs_xIhbKH5SF

sprite $DataLossPreventionApiSm [12x12/16z] ZS770O0m3C10fTdQVs4w_83SCMbabrs39913gMKW9ql1og6fNEHH6zzM

sprite $DataLossPreventionApiMd [16x16/16z] dOZ70SD03CEWplqNJjpjzq4LP8sehvawPsu16KKN192WU--Ec-XsPFZkWJ2pFJ8ENEaZNgOxlkfyyM6PFm

sprite $DataLossPreventionApiLg [20x20/16z] jSx90GD024BH3pCg_JUSVSyrUMS5-9ET3EycjIVcHGAB7MwCYQY6QP018mKGLBWoIs5r5nqlTFyjdH1xoLmf1VvOu-HhOFYIvfF3D_4hHm

!procedure DataLossPreventionApi($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/DataLossPreventionApi', $name, $tech, $desc)
!endprocedure

!procedure DataLossPreventionApiCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$DataLossPreventionApiLg>', '', $funcName, $content)
!endprocedure

!procedure DataLossPreventionApiGroup($id, $name='Data Loss Prevention Api', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$DataLossPreventionApiLg>', $name, $tech)
!endprocedure
