' definition of the Item gcp/Item/Datapol

sprite $DatapolXs [10x10/16z] PKk50G101DJiF_5tQYxW3kRMuv9Wfdff_QasiDGU75Tkd5GxUxNoM2-iD14K

sprite $DatapolSm [12x12/16z] NOe50W1120AHyUB_7xxS7blGWbsR0lO3-FxmFRvrKmLgao5FOFrB6se4P8ukVtld1W

sprite $DatapolMd [16x16/16z] ZOw30G0n303RNBJ_mc-pLyGeBG3RFo20PJ1mYTVPzb7kX6xgddOi9dFyd-EbEkE_znH5vimb0L1LGBRzF6xxoV3Vw04

sprite $DatapolLg [20x20/16z] bO_L0K0X30Df6sJ_XP_YJdukEAUE8YASqtSX8dxffxuEv_2Iits9VxIldAQCwpmApp15_oMUwNunpaasH_ddEX8gnRgbRxeIWDI-sllIn9UOFx9dcni

!procedure Datapol($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/Datapol', $name, $tech, $desc)
!endprocedure

!procedure DatapolCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$DatapolLg>', '', $funcName, $content)
!endprocedure

!procedure DatapolGroup($id, $name='Datapol', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$DatapolLg>', $name, $tech)
!endprocedure
