@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element IdentityAwareProxy
include('gcp/Item/IdentityAwareProxy')

' renders the element
IdentityAwareProxy('IdentityAwareProxy', 'Identity Aware Proxy', 'an optional tech label', 'an optional description')
@enduml