' definition of the Item gcp/Item/Looker

sprite $LookerXs [10x10/16z] JKg30G113ClL-o_yh1LXrJa935aw41O9ufalISa0-L5Urmm6V_y6

sprite $LookerSm [12x12/16z] LKk30G102CpT_Wk_ZJhIV_YWq8FzaTdrpGC7UViyCpc4sTMBgUkyC9Bjb0MnK0K

sprite $LookerMd [16x16/16z] TS_50G0X40F0iDv_mwUuvCK4noOfJKLlC-gf1Ei8aT5GdOupH0HLUhnTr3MHsqpnN6Vhv3omQd-Fqk629tpwpWq

sprite $LookerLg [20x20/16z] VOu50a0X2CN0WDt_mh_3VlQioImwGjeIxPYPIPES3pndvLr9qiSWDxTT04A14duAGU63FoCV2kyqV-oVwdyvlIpzJ7YCdL8ktQXK1Cp0Qcc0AEli

!procedure Looker($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'gcp/Item/Looker', $name, $tech, $desc)
!endprocedure

!procedure LookerCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$LookerLg>', '', $funcName, $content)
!endprocedure

!procedure LookerGroup($id, $name='Looker', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$LookerLg>', $name, $tech)
!endprocedure
