@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element OsInventoryManagementCard
include('gcp/Item/OsInventoryManagement')

' renders the element
OsInventoryManagementCard('OsInventoryManagementCard', 'Os Inventory Management Card', 'an optional description')
@enduml