' definition of the Item azure-17/Item/ManagementGovernance/ServiceManagedApplicationsCenter

sprite $ServiceManagedApplicationsCenterXs [10x10/16z] RSQt5S90500m_V0kxJymLmAsAdcNrM4Vz6t3Y6nxJoB6ZJ1656ifOiJOI3NIZmy

sprite $ServiceManagedApplicationsCenterSm [12x12/16z] VOi54W9030Ettlx_msHW5DkJIXB-aPbul3fpp-3Keiu2DLIxYhOBrjxgPg2hQUtKujghxsSIh5jRqSBvu04

sprite $ServiceManagedApplicationsCenterMd [16x16/16z] ZSa5aWL02CJG04qpS_y3htxtbBuAdnMwOae2x_MdNoHI4Vl_9aKfWWMuAKa_c7-R9bcznm8mDdlrQ21m_tbOSvmgSda6ik7tnx8DA05iZ_dB5TNku5WfUTut

sprite $ServiceManagedApplicationsCenterLg [20x20/16z] {
hSe7KaKn34DHoKM9sV-2aUam5VZtrPmH7b1KvGz1LXM9c7d2njhH-curs6mMVzQmnlOhruamt3N91vidCpXwCnbuQOjZMZJB8yx1eSMGU3FgXAbiOgGDlEV2
oVToe4UwQzcxfUn7ce0hcokvIpYdsBKb6kzHhXD_w1a
}

!procedure ServiceManagedApplicationsCenter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-17/Item/ManagementGovernance/ServiceManagedApplicationsCenter', $name, $tech, $desc)
!endprocedure

!procedure ServiceManagedApplicationsCenterCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceManagedApplicationsCenterLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure ServiceManagedApplicationsCenterGroup($id, $name='Service Managed Applications Center', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceManagedApplicationsCenterLg>', $name, $tech)
!endprocedure
