' definition of the Item aws-20210131/Resource/Storage/AmazonSimpleStorageServiceGeneralAccessPoints

sprite $AmazonSimpleStorageServiceGeneralAccessPointsXs [10x10/16z] 1S490O0m000XTE_rBpm00F4j29b0qm070FeHs91SG0221m

sprite $AmazonSimpleStorageServiceGeneralAccessPointsSm [12x12/16z] NOk50GC12CI2m_u3j-yMN8uF4rB9HcxHm9P4mO28aYfd02k4YEs-gLItFW0yX4CyIB1XESL9JdCnM_u3

sprite $AmazonSimpleStorageServiceGeneralAccessPointsMd [16x16/16z] RSc5WGGm202mr67_WLyubxIuRrf6vEPghohHbLKrEKgLDeA0eOqkJxBL-VHGPbEpOEUn6heITS0rhzpNRWwi-u4rIQ9njLl6yYpxwvZ7Yqtv1G

sprite $AmazonSimpleStorageServiceGeneralAccessPointsLg [20x20/16z] {
TSw5aG9044JHlpQIVy1tG5VZl9ALKNvRKPrdyAG3OFJ1HetR0ITmbevgE5ltFPKTkN3Snzu5IosJh4hM1Q2EGJ8J99rt8c57XFCQAMYc-cbzvJb1fypm9HrP
YSsUq135arFqYObzTBLQdHzfrOiF6_i7
}

!procedure AmazonSimpleStorageServiceGeneralAccessPoints($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Storage/AmazonSimpleStorageServiceGeneralAccessPoints', $name, $tech)
!endprocedure

!procedure AmazonSimpleStorageServiceGeneralAccessPointsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceGeneralAccessPointsMd>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceGeneralAccessPointsGroup($id, $name='Amazon Simple Storage Service General Access Points', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceGeneralAccessPointsMd>', $name, $tech)
!endprocedure
