' definition of the Item simpleicons-6/P/Pexels

sprite $PexelsXs [10x10/16z] O-0d11WOO6guWHmuYml6WW56Hbmc

sprite $PexelsSm [12x12/16z] O-0d7R1pSB0nmzX0p82TpGHNpy30IQpP

sprite $PexelsMd [16x16/16z] O-170NpyL04C883C1s9k9YG-d43msPbH-0nCgFePqSo7yWa3_1u4

sprite $PexelsLg [20x20/16z] lSYt0S0m30CmkdVp_sjJDakQ4um0ZSx_EBowlBRtRbZY1XyPzWhieUi34irHSZ5dVTuz-95EwmO

!procedure Pexels($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Pexels', $name, $tech)
!endprocedure
