' definition of the Item simpleicons-6/P/Pinterest

sprite $PinterestXs [10x10/16z] 9Oi50G0n30FpZDlvLrlc1XJnp4CPLDnrI0liSKNDw3iEFUXavlMnhUoyPolQeRok_FhT_ZuS

sprite $PinterestSm [12x12/16z] DOh50S0W0CHIzyl-qzQ0V4xvEB9Gi51jpX8qq8EUA5_Re_iN6HMDHo_7xnV5TjRZ967zlKFViUiCIbG3SA9_-m

sprite $PinterestMd [16x16/16z] {
FKw50GGn24lr5DX_sm-vRuCx4BhvZGsB3nD2RDWAdz76I_kgsPcjP2Pgbh-UIubEXs4B2fmJwgbPUt17C5Lg0Cy_9fzWgywpg7s6lPOYTzuwRHZwomggPq7P
kNuU8DxePOL2xTcgj_43
}

sprite $PinterestLg [20x20/16z] {
JOu73iGW30INtk7_lxqREKXCschb3DP7stiaFPJpiVojpaEzrKlJhGR9RMAKyl-pdUHG9Kh9tf7FfaJ9YmgcZTHlM6eaeLeannd1_3ZeF1kCVmhoB67_hdiO
BknTUSezQ_1AguZWnSZKFC32FEI8b75D9nNB11DT10r5lLMG8FoxTyeePbf9y0C
}

!procedure Pinterest($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Pinterest', $name, $tech)
!endprocedure
