' definition of the Item simpleicons-6/P/Powerautomate

sprite $PowerautomateXs [10x10/16z] Ou039bum037v8G31P88nEO6YO1OVM9uR8it3m0pN0cSW

sprite $PowerautomateSm [12x12/16z] LOk55S1G309Jzzx-s_ObKBil4I2-j2BRWM8YXoNRtEImgzrgO0HEAvXFkwhTywcTCn1nG6M9FnS

sprite $PowerautomateMd [16x16/16z] XSxL0GD1549HriVflziyYFlvuguE_kYyoYlacZivgoVQnZ0XB5ehfK1stPL4Gl9nVmNYN7djuUyxy_K8sLaZYuUpHoQDvXoHcqTtGpr27e9FJW

sprite $PowerautomateLg [20x20/16z] {
bOu54WCn3CJkmhp__st7LS73hGBhKV3waR0T2JVruJGrvFwuOWCfGPOHaLuft3nZTK9LwGAfeBfDkDoEZF6CxQyyYtIVt0FLKDnFB5FKoav5UIMd4d7SaqNk
oSFrXExh7nu
}

!procedure Powerautomate($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Powerautomate', $name, $tech)
!endprocedure
