' definition of the Item simpleicons-6/P/Processingfoundation

sprite $ProcessingfoundationXs [10x10/16z] HSR50O0m0C30u4xsdnRglTS172v49aUDBgXueKUQc23ecgPAtw49i9Jy

sprite $ProcessingfoundationSm [12x12/16z] NOp50O003CI2Ezb_Mkpw8dNbPNCc698M44UZ1weeeswLDuC1EzGv-GU_l1vFO74275Rt1W

sprite $ProcessingfoundationMd [16x16/16z] LOz50a0X44AnM-v_sX-sRyNqW8OfJ0AJmevhaU2YueC7kJS3860_9NjPWVG8dp8h9ZJ9SiIEZHxRlZdDM8Icn8m7kEFQbkodczXOVEGZRCZ3pGi

sprite $ProcessingfoundationLg [20x20/16z] {
PSs53S0m30J03tD-_scBLcsfLumHBzSsPu9HA9Q7eD4qfBg6L99PznO6eBq7FZOSEO11iZeJOq5wzjXOHtmEDXRGA2JM8DEdneAhV6IDVV2FBIpvQYp1tn_S
P0m1MQzmwxG27eaAdoeR4sud
}

!procedure Processingfoundation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Processingfoundation', $name, $tech)
!endprocedure
