' definition of the Item simpleicons-6/P/Processwire

sprite $ProcesswireXs [10x10/16z] 9SR50SC0000XwetU_jD6UG537r2dFmNwY9ffJkcbDL6IZ17ov1VYZaxi

sprite $ProcesswireSm [12x12/16z] 7Oe75eK03CBoXzkQ-z_M1-ak42vtoaSBNG4MXQvVmFaOktuv7C4D1HzPfEMl-yViJ7O7HiWE_5tRWN48XXLU

sprite $ProcesswireMd [16x16/16z] {
FOm73WH12CEolSo0___R4q6tLiD08dC4Gnz9SzfMOEphcH3bCDK7Jp0iVLe5tS0j7N3pI9YZXwM2bKufIEfjE5n-_VsfUoBEyk6WG9Vl-tWalOHaLx63sgTy
vP21c8dLF1JE_W
}

sprite $ProcesswireLg [20x20/16z] {
LSe5be0m4C3GrD0fkVzfLt02jV-6epHlHkFLv5daQyPNqqsztlCpW3fmfJPOzXrIlX1q1Ofg73XLpJjT61eAg9Mk1GPLeUmlT8Eicq9JTdEt-R6i7QfoMLrK
O7gPQWKqWCF82M3KzjXULVdQU1D5fvpAf5euyuwdhcfK07u1
}

!procedure Processwire($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Processwire', $name, $tech)
!endprocedure
