' definition of the Item simpleicons-6/P/Producthunt

sprite $ProducthuntXs [10x10/16z] HOg34G0m40HZZBR_QiCtJk7Kf8LRl9eAe5xqZNdH6xuMeQ52S3InI1Mm0G

sprite $ProducthuntSm [12x12/16z] HOo50G0W3CDmb_-_XNcGQUk0UPiZBc7f1zESKlvXG-vZ3X0dvEDUMVKiQv3xa53CEvAlWsar_mEgBTq7

sprite $ProducthuntMd [16x16/16z] LO-50S0W30H3STz_sv8FUjKNZ82jFIjQr2vuADKtZNM_A59EPX3P-107OZJ_Mj7yXwXkdQ3xwKDdwBEksds1Njt8yJilZTqV70tA9S5tdUO7

sprite $ProducthuntLg [20x20/16z] {
PSq73W0X24HHrjwv_sqtbad6-DA_0dBaeIq8YNfqYwGa8x62n3nskIaCdV2DDoT1gxNw4pCQJOsd0VPzEZLkLfU0naDlwzAVviNeLEjrB-jDfgBCokAlNv3E
HI_J3m
}

!procedure Producthunt($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/P/Producthunt', $name, $tech)
!endprocedure
