' definition of the Item simpleicons-14/W/W3Schools

sprite $W3SchoolsXs [10x10/16z] LS6r0GDH040XphvKR_zjKyN0ntMTpkiYfO9ThO9AJGW5OVaNdDpAupnV

sprite $W3SchoolsSm [12x12/16z] TOZ50O1G34FVTs_sdnRd1csSxpCaTr0PEaio7OTDk89q9AXdvYItlTcFQ-7d4hxsEDrq8_QPRNXNw-opXnq

sprite $W3SchoolsMd [16x16/16z] {
VKg50GCn42BkkVstBR7wFwS8xg2y117Xmzqf50j-SuaO2dbQJYRW2hFhDnmFOWlpB5xNnvrFeA-J5e-oSzZOEO-_U1cEerbLGuqlmuHWW6QWaqFBElcE7kXB
uysgFG
}

sprite $W3SchoolsLg [20x20/16z] {
ZSe9ZWGX28NX7-n9Az35_Myx4aBsMRugbUNn7n6vBWMq2aeAULLL790di5kVkWibEd6l1eybd6oxBgLDP7MmT9shb-y9bYcWJMbJN94nIs7CTWUCznJ2hpP3
PAfagCBUOlkLvv48V9jg7lprWIGNyXLyLFKHHtqPnZaiLv5jtm
}

!procedure W3Schools($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/W/W3Schools', $name, $tech, $desc)
!endprocedure
