' definition of the Item simpleicons-14/X/Xmpp

sprite $XmppXs [10x10/16z] Oy02EFdPmJGlFmC_Fny30v3a1s4mYmT4C809C0bXG1L1MK283

sprite $XmppSm [12x12/16z] TOo50O0m40CFTsx_QN6dVPSaH6pehd54NOUj7tEoza9BeDzE7hLXQpcjmw4brXpMc1nJkjuwtZO3

sprite $XmppMd [16x16/16z] ZOo54G0X40E3E-c_sdTN5etCuGTxqP55RCAGu82Ob2SNhPSgMU18fabFyVO0Qx1el_fgwm6huL4tEMMH1GUcKHic2xWgq40F

sprite $XmppLg [20x20/16z] {
fOw72iGW40LtqsER___RO-4Xor6kP5BK4KRj0QFucrdQ3Pn9TC08cXI1tCZkjeCWEuroZZehm6P1cTlt38RIrRgc1JX2IAeifL2r0OibTfJFkCv9NEpMyMHM
TPPBzZjU
}

!procedure Xmpp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/X/Xmpp', $name, $tech, $desc)
!endprocedure
