' definition of the Item aws-q1-2023/Resource/ManagementGovernance/AwsSystemsManagerDistributor

sprite $AwsSystemsManagerDistributorXs [10x10/16z] Oq05t706DokI03S8SOCPZ0niK64k1WOcTaQWE0jSBuZ52M8nGtHpWaq1

sprite $AwsSystemsManagerDistributorSm [12x12/16z] PSNL0SLG3CFGKxYGUFzv7txM87aa01ov0TSfZXD2rNQ5JJWQ6W8XPVn5EKUQGYCekBQe4t3bW3S

sprite $AwsSystemsManagerDistributorMd [16x16/16z] VOjL0WGX34DVSCZzpxlIhdpDG2t6nVCjBithZ-gc6NO990EIe9n8oYcCem5D82iIR3108cW7cWNR8YzGjQRTZpQ1eMGiSGSI7uZL0lU4eJQlF_f7uGa

sprite $AwsSystemsManagerDistributorLg [20x20/16z] {
dOy54WCW40CNXyl__zjY0oFLu4lcXBVItqn9bcuG14KU-bha6EgAO8fWJtbejQtOiLEWzHWEV8LE0yNSyYX3LzdnUmW_QPkiDZS_L7150bcSRWDlGi4g7BPY
SvYxM9cCfitkbeevH5BcLfEMvvPdwm4
}

!procedure AwsSystemsManagerDistributor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/ManagementGovernance/AwsSystemsManagerDistributor', $name, $tech, $desc)
!endprocedure

!procedure AwsSystemsManagerDistributorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsSystemsManagerDistributorLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsSystemsManagerDistributorGroup($id, $name='Aws Systems Manager Distributor', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsSystemsManagerDistributorLg>', $name, $tech)
!endprocedure
