@startuml
sprite $GcpCloudTestLabLg [20x20/16z] {
TP050iGW30GXifl_l_Y8dBTJPP38ka4SWykeZNY1tSxY0-jb_7IiXPv_h3kbPm0UvPwtvYayOH3bSEwj5MPfRI1oB_g_LPXGbUuTvihzxmrznH2PTUXS0aup
Ej99v_o9NzLsruEryRMi4JGaPDtm
}

sprite $GcpCloudTestLabMd [14x14/16z] LOw50G0m2CEAy__3SyqKBm3Y0G7Ty1ZuC3KNsWoERGK3bkaDQwz1ubhHZRI6Uy_zhPcvB85Tozy9oUzqEygQ4GJygYi

!procedure GcpCloudTestLab($id, $name="Cloud Test Lab", $tech="")
  CloudElement($id, 'gcp/DeveloperTools/GcpCloudTestLab', $name, $tech)
!endprocedure
!procedure GcpCloudTestLabCard($id, $funcName="", $content="")
  CloudCard($id, '<$GcpCloudTestLabMd>', 'Cloud Test Lab', $funcName, $content)
!endprocedure
@enduml
