@startuml
sprite $GcpCloudTasksLg [23x20/16z] VP7L0S0m24Hns7_XUZpqVUBSmOru55oWG4-qnAc4BNhqYx8FOUSdYYLQC7psnOpC-zfMYnNzzaruYKvO4aw692kp0q4tx-JF0qzXtWfhFpOaffq

!function GcpCloudTasks($id, $name="Cloud Tasks", $tech="")
  CloudElement($id, 'gcp/DeveloperTools/GcpCloudTasks', $name, $tech)
!endfunction
!function GcpCloudTasksCard($id, $funcName="", $content="")
  CloudCard($id, '<$GcpCloudTasksLg>', 'Cloud Tasks', $funcName, $content)
!endfunction
@enduml
