' definition of the Item c4k8s/Boundary/MutatingWebhookConfigurationBoundary

!procedure MutatingWebhookConfigurationBoundary($id, $name, $tech="")
  C4Boundary('K8s/MutatingWebhookConfiguration', 'Boundary', $id, $name, $tech)
!endprocedure
