' definition of the Item simpleicons-8/Q/Qubesos

sprite $QubesosXs [10x10/16z] Om01FWO8u0S23Y3DnGy1814-Y3WGWvNWOe6Ol60IhfS1nWO

sprite $QubesosSm [12x12/16z] XOt50S0W34L_lVZ-qyPpva7SO4maIoZcjUMSW9ik-X6_HMCLEVU-1rtzieHVbLMTk2sE1Wm

sprite $QubesosMd [16x16/16z] dOx50G8m54DJzsR_RI7Kxhpgzs0H9_0m_DAkERa848KF0moz0qWKW6uBqPOjS_6lNQ-gPQ-CnfzjA6RcrQplOc0ndk3Rga8sFW

sprite $QubesosLg [20x20/16z] lSt50S0W50FGrF7iFotk0_HTu3iQvR1v66bC3bO2ZU5mbaLSkBofJLqi0DcAqJlbNZGZT_wGQuSFLtA26IBRluwPhaKUY6xEK4bENbHswsmd7voCFWG

!procedure Qubesos($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/Q/Qubesos', $name, $tech, $desc)
!endprocedure
