@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsTimeToLeave element
include('elements/materials/Notification/MaterialsTimeToLeave')
MaterialsTimeToLeave('element', 'Time To Leave', 'an optional tech field')
@enduml
