@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsConfirmationNumber element
include('elements/materials/Notification/MaterialsConfirmationNumber')
MaterialsConfirmationNumber('element', 'Confirmation Number', 'an optional tech field')
@enduml
