@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsTapAndPlay element
include('elements/materials/Notification/MaterialsTapAndPlay')
MaterialsTapAndPlay('element', 'Tap And Play', 'an optional tech field')
@enduml
