' definition of the Item simpleicons-7/T/Teamspeak

sprite $TeamspeakXs [10x10/16z] FOk50S0m3CFSCUl_RzU650QhCrzDWuUcZT6X0TuCxkg0y_Lk1nWAniJmOiq6z0C

sprite $TeamspeakSm [12x12/16z] HSc50O0W503HizlRVrgbUV2RQ3bdCZsNnml0ZUXzWOlCzBDn7QHIsyLRT8LOwqsXs-ZwuNNW1m

sprite $TeamspeakMd [16x16/16z] NSg50OGm5C3GuFNiF-q93g_obSsIPax1JSTAbpNMBOwoczVCdaDEq3KkGfsvs4LxBbNjEvT77LI0OQ6ANQTMrcvf-rP3BRorLrcVfPpwg09V

sprite $TeamspeakLg [20x20/16z] {
POy55WGX3CK-xkJ-jztNjR7WeKZr9THUdKwunOVsLnEMnMJWgmPBniSw6Q0_Zc93GoSIrbDqXY5vT24ZxPlpbCdDEGmrriDPznNENFawldcOam-AvgRMPoiu
6HN8rjFaz6G_LUAfk3iF-7D4Mq2twGi
}

!procedure Teamspeak($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Teamspeak', $name, $tech, $desc)
!endprocedure
