' definition of the Item simpleicons-7/T/Thesoundsresource

sprite $ThesoundsresourceXs [10x10/16z] FSd50O0m44JHMTn__zK2oSexZHWi4zrp8Ky7IGsbnxcdgRysY5kxVmABD37sT07t1m

sprite $ThesoundsresourceSm [12x12/16z] HKo50GD124FQzv3zfprt8QeazU5OKiuUVOmgmRq0FA9j_BhpRc-VfR_lgsN2FRikMuxYHv_VyiRYYoEK6G

sprite $ThesoundsresourceMd [16x16/16z] LOw30G0n5CLIks__QSzCyGsZ3OS-KCJhc9plXksDrpHK_IXkmqBGZt6tZEwKcRlV9U6KPafA55q429EiORmXFSMLJNQUbJqQJpUQPAjU-vRzcUPxDL5Q0G

sprite $ThesoundsresourceLg [20x20/16z] {
PP254GH120HxxSzW9_zilpYNBiDbae8VLISkgQTYzHQC41Q5TWijuJck6ynwayYkDuM3RyEIeElDIDwjTcRjl95shJk2xAVDS9i2938HyW9JHBjPfAGf_7Pk
4eECieqz9tGjfD1fEc8vZ6rlEMALwPJkL993G5odA1booIM4-0C
}

!procedure Thesoundsresource($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Thesoundsresource', $name, $tech, $desc)
!endprocedure
