@startuml


include('domainstorytelling/bootstrap')
include('domainstorytelling/Actor/User')
include('domainstorytelling/Actor/Users')
include('domainstorytelling/Object/Circle')
include('domainstorytelling/Object/Cube')
include('domainstorytelling/Object/Cubes')
include('domainstorytelling/Object/Shapes')
include('domainstorytelling/Object/Square')
include('domainstorytelling/Group/SolidGroup')
include('domainstorytelling/Group/DashedGroup')
include('domainstorytelling/Group/DottedGroup')
include('domainstorytelling/Group/SolidFrost10Group')
include('domainstorytelling/Group/DashedFrost10Group')
include('domainstorytelling/Group/DottedFrost10Group')
include('domainstorytelling/Group/SolidAurora11Group')
include('domainstorytelling/Group/DashedAurora11Group')
include('domainstorytelling/Group/DottedAurora11Group')
include('domainstorytelling/Group/SolidAurora12Group')
include('domainstorytelling/Group/DashedAurora12Group')
include('domainstorytelling/Group/DottedAurora12Group')
include('domainstorytelling/Group/SolidAurora13Group')
include('domainstorytelling/Group/DashedAurora13Group')
include('domainstorytelling/Group/DottedAurora13Group')
include('domainstorytelling/Group/SolidAurora14Group')
include('domainstorytelling/Group/DashedAurora14Group')
include('domainstorytelling/Group/DottedAurora14Group')
include('domainstorytelling/Group/SolidAurora15Group')
include('domainstorytelling/Group/DashedAurora15Group')
include('domainstorytelling/Group/DottedAurora15Group')



@enduml