' definition of the Item aws-20210730/Resource/Compute/AmazonEc2M5DnInstance

sprite $AmazonEc2M5DnInstanceXs [10x10/16z] Oq0576n876OC5YE8nS70ni02P05fg2mRiZfcC615CWy

sprite $AmazonEc2M5DnInstanceSm [12x12/16z] LOs70SGm20FFDWZjl_1_UaBl4bqqyKG0rYKWSOh5lEkQe5YQWC1QOmIPTh-vwuu3vJei6kyV

sprite $AmazonEc2M5DnInstanceMd [16x16/16z] RK-50S0m38f2_hzurNar3iZFWb2gNKpNs7QDTxXXUx6ve5sDGClV_7PvptFaAH7DcVagSuI681DLFU_Y56R4j_yx_ujFx5KVFSj7yp7y0m

sprite $AmazonEc2M5DnInstanceLg [20x20/16z] {
bP250GD020EFJv3z5wwxzrs02EzQaJ1KK1_UicVNpuiERyrDau6gkNlhyikupFkuIjt6nJaE-j03ULc7jvb19S8EaPh9GvpGyagBVCibue5B_AL3Dorz2c-N
FMwx_SbJ8qWS7CAs
}

!procedure AmazonEc2M5DnInstance($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Resource/Compute/AmazonEc2M5DnInstance', $name, $tech)
!endprocedure

!procedure AmazonEc2M5DnInstanceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEc2M5DnInstanceMd>', 'Compute', $funcName, $content)
!endprocedure

!procedure AmazonEc2M5DnInstanceGroup($id, $name='Amazon Ec2 M5 Dn Instance', $tech='')
  IconGroupElement($id, 'ComputeFamily', '<$AmazonEc2M5DnInstanceMd>', $name, $tech)
!endprocedure
