@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsIotDeviceJobsResource element
include('elements/aws/InternetOfThings/AwsIotDeviceJobsResource')
AwsIotDeviceJobsResource('element', 'Iot Device Jobs Resource', 'an optional tech field')
@enduml
