@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/aws')

' loads the AwsIotSitewise element
include('elements/aws/InternetOfThings/AwsIotSitewise')
AwsIotSitewise('element', 'Iot Sitewise', 'an optional tech field')
@enduml
