' definition of the Item aws-20210131/Resource/QuantumTechnologies/AmazonBraketChandelier

sprite $AmazonBraketChandelierXs [10x10/16z] Oq0270oCG98Lp6Q42m81CmDS38t51WHC3EY06QuEh1

sprite $AmazonBraketChandelierSm [12x12/16z] XSh50G0n30F1DVTVyJ53CX-3n8sIXQWoayjE12AiRCPYxN_iEgEZIfxx2

sprite $AmazonBraketChandelierMd [16x16/16z] PSk74S0m34BHRt92td_XzCJjNPK0LaPARBGzTqYLJFAvuRr_HIQYtRwrXsJQkUoN6mg59cz1aqCEmSWUFvKSxsfk1m

sprite $AmazonBraketChandelierLg [20x20/16z] dSm5WWCW34JH7naszx_mrelL7qw49meIHmIk_lTdeb3_Kzx_vDpS_qQof94CwYeOs7aPNU_toryIvpLeLqvdPcbkngn8LerW5U4ih6LjVsd5IX9N1m

!procedure AmazonBraketChandelier($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/QuantumTechnologies/AmazonBraketChandelier', $name, $tech)
!endprocedure

!procedure AmazonBraketChandelierCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonBraketChandelierMd>', 'QuantumTechnologies', $funcName, $content)
!endprocedure

!procedure AmazonBraketChandelierGroup($id, $name='Amazon Braket Chandelier', $tech='')
  IconGroupElement($id, 'QuantumTechnologiesFamily', '<$AmazonBraketChandelierMd>', $name, $tech)
!endprocedure
