@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsRestaurant element
include('elements/materials/Maps/MaterialsRestaurant')
MaterialsRestaurant('element', 'Restaurant', 'an optional tech field')
@enduml
