@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsLocalPostOffice element
include('elements/materials/Maps/MaterialsLocalPostOffice')
MaterialsLocalPostOffice('element', 'Local Post Office', 'an optional tech field')
@enduml
