' definition of the Item aws-20210730/Category/Containers

sprite $ContainersXs [10x10/16z] JSP50G1140InuMh_XezXymghkVJLFijNC7SVhq7q13R7zCt4eOyTkEZj3W

sprite $ContainersSm [12x12/16z] NOpL0G0n349haVqdlWOuw_k9877Wm8p7mC6zhphsLgBFsZFahZrjzUqVvnu3zAX_cGtj2GBaUrm

sprite $ContainersMd [16x16/16z] RSV70SKW34H1aDYtzD-m0-57pstyX4Mg7a3Szaqoh4FzV62J3GZRgct8ShyxOwcwtorGbCXWlCj_9oDRU3pRalY-GPF71z_6b_tuKau

sprite $ContainersLg [20x20/16z] {
ZSo70GCX34DHx4WM-qySqzDp_ogFeayvLhUP2ShYH7gthhxmc3Dcsm0BFbkH8cWFvbXdObcnKUI3Pgmotnc7LP6UlouKZsdreX4S0HOQLdAfHi5faN6Mtcsa
qRJPksNR_Bqx
}

!procedure Containers($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210730/Category/Containers', $name, $tech)
!endprocedure

!procedure ContainersCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ContainersLg>', '', $funcName, $content)
!endprocedure

!procedure ContainersGroup($id, $name='Containers', $tech='')
  IconGroupElement($id, 'Containers', '<$ContainersLg>', $name, $tech)
!endprocedure
