@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q3-2022/bootstrap')

' loads the Item which embeds the element AmazonEc2Is4GenInstanceCard
include('aws-q3-2022/Resource/Compute/AmazonEc2Is4GenInstance')

' renders the element
AmazonEc2Is4GenInstanceCard('AmazonEc2Is4GenInstanceCard', 'Amazon Ec2 Is4 Gen Instance Card', 'an optional description')
@enduml