' definition of the Item simpleicons-14/F/Flipkart

sprite $FlipkartXs [10x10/16z] Os3W1mDU1XYB7yY00GmM0up5m074SDL0pC40130nDh0OZ

sprite $FlipkartSm [12x12/16z] ROh50K0X08NudUh-qzgjd5u0GWN0viXZeqeigCmnoJ_aRAFDAORy06d_hXMsmR487fSD

sprite $FlipkartMd [16x16/16z] bOkr0O100CI2E-m_BVxkgKw1GpBWerKyxj0fySki-mNODFyfwLlG_liExD9FlFn-NyQcXhhJ_jjtbxwpFC9V

sprite $FlipkartLg [20x20/16z] hSw53GGW343HZpliF-svb4PENwof0t49Wmlh92x6aYn0LGAmjF_b3AXS1KXx3iXgDaBG-u0kSirPQm5hHL_cvf4RhNXh05ltVGcY_jd05BbteYC

!procedure Flipkart($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Flipkart', $name, $tech, $desc)
!endprocedure
