' definition of the Item simpleicons-14/F/Fusionauth

sprite $FusionauthXs [10x10/16z] FSc50O0m40F0mvtiForENw9W1qGCC8Eyjxyi6YbL2aSlf0en0Nhg89m

sprite $FusionauthSm [12x12/16z] 1S670S0W00CWkjoQ_xyj00VWpXt0_i0gr8UxOH5oAPjuDRR2GGZLm2Ikor48mYMLaKh20O1r7bykVW

sprite $FusionauthMd [16x16/16z] {
BSZ7eOKm30J0aNbaqFPVxO-UomPJW-buEX-caOET2bXZMWA1vHZpw8LFZd47xn04AeZcBbjuYhW95RQTm8jm3WBZPVRsXBlBo4TbaM2ykR3bfYvC1LS3YwcI
xiuBtm
}

sprite $FusionauthLg [20x20/16z] {
POq5ji0m408dLjzm_zD-uTKxqJM0dTPvCI4jt0c9K8EnWKdQEByhvZ7av9vAPSeuR92rAtRzXuvZ17hWi06g22Y-zfbbHU3UK8R_api2dycVSO-WbtrUvSpD
WaK9XyC62T00G6n0ogpQ0AccMU5V8jG1fj2MSIx3p8DYcQRAXooLtJzpCibO4Nu1
}

!procedure Fusionauth($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/F/Fusionauth', $name, $tech, $desc)
!endprocedure
