' definition of the Item aws-20210131/Resource/NetworkingAndContentDelivery/AmazonVpcFlowLogs

sprite $AmazonVpcFlowLogsXs [10x10/16z] JOo30G0n302lYFUVzurUJ5RgCPeVa6TL1us0Enj-93Vzx9bPeqvf1ypxmUF3UnsT7G

sprite $AmazonVpcFlowLogsSm [12x12/16z] LSU5SGGm5CN0DVwCN__rvfXsIFAhPVKAM0tiHclwLHJ1d3EKHTjxPxReUJdAOxl8inbiVrTnq0eSe78oS04

sprite $AmazonVpcFlowLogsMd [16x16/16z] {
RSh5OGKm3C1G6KBE_lC6sy_lAl6BzHuzX4kwikN69e4VAi7I8UbMaGAcu7sn2kraF2rI0IC0OLE2HaX_ihX_NgHweX20irKmGJ9uNRHoOXDQFKZ64iALCaTf
B1R6FsjHX6q2
}

sprite $AmazonVpcFlowLogsLg [20x20/16z] {
TSs5TG0n30DG6OBQVzy-XSh_C4Ryh_J9sU9hX0aPD1opuXhbX0pz06QknWhGbsR0L8nw6gKQ40CekUEYcFuxljPveCVkTooc7L50D7xZTTSr3qbpQa5JZDba
xp3jLgpAZjt75iLgQja0s9Tfi0b9uZ5YondOwiGpsCEJJ7mLfQPX-m
}

!procedure AmazonVpcFlowLogs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/NetworkingAndContentDelivery/AmazonVpcFlowLogs', $name, $tech)
!endprocedure

!procedure AmazonVpcFlowLogsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonVpcFlowLogsMd>', 'NetworkingAndContentDelivery', $funcName, $content)
!endprocedure

!procedure AmazonVpcFlowLogsGroup($id, $name='Amazon Vpc Flow Logs', $tech='')
  IconGroupElement($id, 'NetworkingAndContentDeliveryFamily', '<$AmazonVpcFlowLogsMd>', $name, $tech)
!endprocedure
