' definition of the Item aws-20210131/Resource/NetworkingAndContentDelivery/AwsCloudMapResource

sprite $AwsCloudMapResourceXs [10x10/16z] JS710G0G00IW0BZzz_LLViq1BdAWq0d0TaZ4DHmqBX21NDdnUG

sprite $AwsCloudMapResourceSm [12x12/16z] LOg70GCW20HVwR3_lW7IJ-c7VqnllTexgUHimI9ZKAViP0UCXamA2Jw7sglithj1vZhe2NBFkaTu7C6GRbpu46iy

sprite $AwsCloudMapResourceMd [16x16/16z] {
RG-30GH0gEiKzj_tupiRy0U6YjutbrngUMqXITLGAeGzNFCEENsEcH99oQuzoaTXC0As-1cMKz_gimuk9lEtJ_VY2TJzR9mARRHekdj7Fz0UxHzKahNw0Plj
1U-WbNm
}

sprite $AwsCloudMapResourceLg [20x20/16z] {
TSJLeHqW50J0GI-SxR_U23_HDok-j2ft-aC6xl6Rwc0l7KyldkI6PtUUpXgUQc12pthVGAq2-t9uuiFPt27OWv6FFJvTtugq89mgrhG-CeFqMhrfmUqkQWGg
F0Tf1GtFHSim4pnPQOJTrkI9MdhsIGfFFsibplANkFxMziJp7G
}

!procedure AwsCloudMapResource($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/NetworkingAndContentDelivery/AwsCloudMapResource', $name, $tech)
!endprocedure

!procedure AwsCloudMapResourceCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsCloudMapResourceMd>', 'NetworkingAndContentDelivery', $funcName, $content)
!endprocedure

!procedure AwsCloudMapResourceGroup($id, $name='Aws Cloud Map Resource', $tech='')
  IconGroupElement($id, 'NetworkingAndContentDeliveryFamily', '<$AwsCloudMapResourceMd>', $name, $tech)
!endprocedure
