@startuml
sprite $AzureDatabricksLg [19x20/16z] {
NT050i0W30F05Yff___VMUQPSZZ2g8Mfl3CZCsC-C3mP8k6EZnyG2py2kZw8gjvouGME6u4TuA9UEu9GhY8wysX-F9McOi4nxkvX-uTu_tLVlmyqyOQkcSGR
SefSM4NOGppOv8vXGtpFLHr-mGe
}

sprite $AzureDatabricksMd [13x14/16z] HOw30G0m3C1g_V_lZ0mrO28c21isTpUUAgblbC3yOvbnr1XgZRVLIjJnHSJu5L5y-aRS1NVsgQmbTbLv7dD81vxcKjSE4bKL0XlKK9nA1m

!function AzureDatabricks($id, $name="Databricks", $tech="")
  CloudElement($id, 'azure/AnalyticsServiceColor/AzureDatabricks', $name, $tech)
!endfunction
!function AzureDatabricksCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureDatabricksMd>', 'Databricks', $funcName, $content)
!endfunction
@enduml
