@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2023/bootstrap')

' loads the Item which embeds the element AwsIoTSiteWiseAssetCard
include('aws-q1-2023/Resource/LoT/AwsIoTSiteWiseAsset')

' renders the element
AwsIoTSiteWiseAssetCard('AwsIoTSiteWiseAssetCard', 'Aws Io T Site Wise Asset Card', 'an optional description')
@enduml