' definition of the Item simpleicons-5/V/Vapor

sprite $VaporXs [10x10/16z] DOo50S0m40AXhhdzfus_6w1cjwO1COpHhIwjF7q7wsWx_9PtcgLJUk6URBXIoFYfjG

sprite $VaporSm [12x12/16z] FSg50GCn30J1CwEq_LURF8z1gClG1_p90YUT2ZKt84ZxxW55uyjTaRCm9ajbCiy5fweth3065gHeTEf25-OgfeVtTeO_

sprite $VaporMd [16x16/16z] {
LOu50aGX50AnM-v_s-Njxx4O6oSD7yZzia3Zri83V-XKIcMHpARNrg6n0zayoBq51qOD4yT2BzhM59fftxKWxxu7ZSHuxCygfbhAm6mxCws-HjyPeYWjLkRh
Gq4x8yl63HF7m8l5U8GV
}

sprite $VaporLg [20x20/16z] {
NT034WH1343Hj17y-zzsQx2QLso4yh7aAOCzhXe7-RMu5Fbmk7Mv922NDXHWVwveTns8JtQLGzoLnkRmpPkAB3f0Fkw066HPdNnbpC3sur-divHB3viaqKI3
mQ4o8qQHoeYzQM2J5ilypAnAfosdKjboKXyqq1MD9hT1fK-FHPAFmd2cFJQ89hOyw3VL2m
}

!procedure Vapor($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/V/Vapor', $name, $tech)
!endprocedure
