' definition of the Item simpleicons-5/V/Vk

sprite $VkXs [10x10/16z] DSgt0OG0542XTz4i-szhzQcfvSRrAsCnRXy-FZiYmI-pAt7XofwVaV4

sprite $VkSm [12x12/16z] RSh50S0m5CDGbRdQVzeo9dcN3pRae-ey0BvoNwDV5SuueZeSEvsgZ3F7UfHA9agTrOwZvk2BzDwj

sprite $VkMd [16x16/16z] NOp50GD158KOZN_whpRhokqfqB_XH7mAyFHCmYlzfhyt7PgIvgJFjFp2yWFE56BI48l-aas06z0I5VPlODilcrT6ltJzU2NVD5SPfAiS

sprite $VkLg [20x20/16z] {
PS-5OSKm303H2yUast_QzZFfcTa2E7fuDze6CFcZWic1sM7MpKBxigZB4jUgFhQ22c603w-vYVKzToYSdv_TG04Mts0M9Y1yQi3zFloU38LT7TwDbNZ6tyms
CqmwrLyp73-xPlu1
}

!procedure Vk($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/V/Vk', $name, $tech)
!endprocedure
