' definition of the Item simpleicons-14/I/I3

sprite $I3Xs [10x10/16z] Om01VWOOu02J445-28NEvEM4CP4fVZ0JeHggWn_40G

sprite $I3Sm [12x12/16z] JOl50O1G08MmM_QVrlZDwIK1gTmqd3O3e-bf3FvMh_-sHGCRi3e4hS5qaoGpu4eoenS1zKzV

sprite $I3Md [16x16/16z] NKw54G0X0EBJblsdjRkLEj06iGzUE8Ou5HmlbKyv0FTZ1-3i04gkfykN8btLi0AMkB40FxDBLelDHw541TwRn0JagCHYkSXlTBMVBzy1i8eZ

sprite $I3Lg [20x20/16z] RSx50SGm44DHXHFJxx_QPP11npUeNr2NYwl7KwF0m1oXHnXrQkdn1CFtLnD_pFdxgg62tfc1hqa5xtmR5EkyACsgGx1BrZbTellVwDjv0hCCtv6d01nwvWu

!procedure I3($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/I/I3', $name, $tech, $desc)
!endprocedure
