' definition of the Item simpleicons-14/I/Imessage

sprite $ImessageXs [10x10/16z] Os3W1mDU60F6XV8Pm80RpcB0oe8nWHhv-LaXHY3C0m

sprite $ImessageSm [12x12/16z] TSkr0S0m34JH2tF-_jEQBLL-ZV2aX-gGS6LxhFquAxjokwhw07M3_iQ6YI9tENd0JoFC7m4

sprite $ImessageMd [16x16/16z] XSt50O004CJ0u4xwhnPtdT_fGjYwge6fsiIXPzEu2O74rLYDYdC9rNJ1RgpJd_gyV_vtpvimYXtLQjMumJFYSza3

sprite $ImessageLg [20x20/16z] PSx50SD044FHRsQh_sf3Nb1std5Gm2fp3S2WnWqAZhMqB_sxWEPEJxRb4kPuIYlEncmxrlfGoxyxtFxankanKzrArhRqdEo0_hcbIn_R93SeyWlrvH5ARm

!procedure Imessage($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/I/Imessage', $name, $tech, $desc)
!endprocedure
