' definition of the Item c4model/Element/DeploymentNode

!procedure DeploymentNode($id, $name, $desc="", $tech="")
  C4Element('rectangle', 'Node', 'Deployment Node', $id, $name, $desc, $tech)
!endprocedure
