@startuml
sprite $GcpAppEngineLg [20x20/16z] {
TP214a0m34DPscJ__yFGvG0UiEtTjSrKp6OwQ3neaoNs0rgDVY66fbfaraSbfWNhkHSeJGbmY5kP-bCW4yEa2oIq0PzhVmLIJ2IYriVU_a8L4ge48JIw2jpA
hOPxwOpmYEte-I2FsGuq_sJWh0xjdgca8zDNzYi
}

!function GcpAppEngine($id, $name="App Engine", $tech="")
  CloudElement($id, 'gcp/Compute/GcpAppEngine', $name, $tech)
!endfunction
!function GcpAppEngineCard($id, $funcName="", $content="")
  CloudCard($id, '<$GcpAppEngineLg>', 'App Engine', $funcName, $content)
!endfunction
@enduml
