@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-11/bootstrap')

' loads the Item which embeds the element ServicePreviewFeaturesCard
include('azure-11/Item/General/ServicePreviewFeatures')

' renders the element
ServicePreviewFeaturesCard('ServicePreviewFeaturesCard', 'Service Preview Features Card', 'an optional description')
@enduml