' definition of the Item simpleicons-14/A/Anilist

sprite $AnilistXs [10x10/16z] Oy0E-FdP-24C8C1WyN7mCy65-A4iA0U8W9WHIC41

sprite $AnilistSm [12x12/16z] TShL0OK03CNGzha0P_zfSPTyNKbSKrBv3nclCIUCcJU_COjgp7UB0tXaPd3Fv8yNxVa5iQ81

sprite $AnilistMd [16x16/16z] ZSUt0G91300m-tEqzf-M35VowXGNp5MrLlqEAzdErBw0TXIJzXfPlzyO0zyZ0sCxsDy_VHrLTGRwpCG4YNWeTeW_xW

sprite $AnilistLg [20x20/16z] fSY35KG1302mVhlPVzgpZJmd_ZLXWJW3hSih7nnWUN2TyrLeq3lVWa3c-P3HepnTYoe2u-cSJG-kErJlR0G2gc83vlF55XHWpCmXjfhCd7ChFhG6

!procedure Anilist($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Anilist', $name, $tech, $desc)
!endprocedure
