' definition of the Item simpleicons-14/A/Anytype

sprite $AnytypeXs [10x10/16z] NSQ52GC1002nWwArx3_jkmTB0R_YLFMS5y6_4dJCjX--VCXk1

sprite $AnytypeSm [12x12/16z] JSY50S002CJ0gpliFstTWeLdoekE_3ZIsBdV0V87put7uVQ0nfSljq-KUNYN7pwD3G

sprite $AnytypeMd [16x16/16z] ROu30W0X54Gdk-v_saNMYzy3q9WQ3a2sEfocbJ_i-O_eFeDCjuFCKBvM0jCOEjduKTqMo7HRRdRCfhptSrrbYl-Dj0AscYy

sprite $AnytypeLg [20x20/16z] bSt50S0m509GuXxsdxRktdVx2W3FZQ80A1vKW2V9yqR0AFxe7SbTf57fq3FerMslOY2sFKpUUlAYnx4bTxqqjkPUcQBpKAJ4Zk8PAeyia4wj5W

!procedure Anytype($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Anytype', $name, $tech, $desc)
!endprocedure
