' definition of the Item simpleicons-14/A/Arxiv

sprite $ArxivXs [10x10/16z] Oq077306Cp-C1MEmCi15E5cWB4v-HWY34QOEeOKBoWG

sprite $ArxivSm [12x12/16z] HSR50O1G0CMmuaxtdnRdlvm28r5ttEJH0WwyAjnAT_cjX5C-MFDfg2GQYK5YaXC

sprite $ArxivMd [16x16/16z] LKu30a0n56hsklzflz7y581ei2p_HVR-ufDsBlNA3tW6cK58N6AJrC8JcazupGSBh1R8gca0QPJkBAoUjU1kZl60xnH6BTq5Xnq

sprite $ArxivLg [20x20/16z] {
RP3L0SL0408dSYxqN-tJw5xcSnK0CW-ufz9HZ6B3uxUk6gQuIBTrRqimuP7kpsReIgEUWa459cvCKcBbJf02XXGbixj06kGnaKsH5QZg7CnRCatv-BcLe1_F
isT7cXcGu0q
}

!procedure Arxiv($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Arxiv', $name, $tech, $desc)
!endprocedure
