' definition of the Item simpleicons-7/W/Webauthn

sprite $WebauthnXs [10x10/16z] TS750K0n242nLrTW_sc_owa9AoaYN1oaX96u6ARMGeoHXEFZm3CvQQ3msm4

sprite $WebauthnSm [12x12/16z] VSl50SGm402nMOhPxh_QOuReBtP5BOMhYd5J15F4Q1KHBXPbpbKyt9qfYF48WGYYwPhL8BZP4k-E

sprite $WebauthnMd [16x16/16z] dSd50GCX443HFxeE_LSRGQwHVJ3EJOUYMpAej2B7dDsYRLT4OGMi7y9awxC3IeLQIgrRhkQU_fg43TAkTczi12JDwcBjB8o5Wg3655ii6zyz0G

sprite $WebauthnLg [20x20/16z] {
hSp5OGGn50KmFTj_u-7-gmtZBQG2v7-CPLcQpvOow4Uysy7Gn_1g6WbKogk1F28M-xLI411z6MvbqMasa8jSvtbUrr9z6qygUplOpCmuGIZaypUzcEWjBPho
8Ybej9rNLGr3dpuvRvtjpbU97ta
}

!procedure Webauthn($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/W/Webauthn', $name, $tech)
!endprocedure
