' definition of the Item simpleicons-7/W/Wegame

sprite $WegameXs [10x10/16z] 5S710K00542X02V_xJyj52m1wYoOGH30Ud4Hmr75lK0X43fGq8yN

sprite $WegameSm [12x12/16z] FOk54G0n409vzz_-guqmJ3Po0gYpiIZ03scV_bszlNuDIBtJ_xTm5IyTURz9dEcD-zFjt_kPEws792i

sprite $WegameMd [16x16/16z] FSw50SGm3CLGbRdQVzg37tXXj25ET-Ws_oQgmmU6lZ5wPNndmfSknpH3hlNZDJzu0kY0-SYPOx42NE1-uMxhcsXJxT-x0ajF_JM3sOR7ar3lxT67wb7hhIy

sprite $WegameLg [20x20/16z] {
PP255OGm50JZdap_rPuGVom-x5Sn90jPt2e0DmMYgy21kaD2dAZHvayvqozqvfSlTcQMFRF2Fv--_6wr6rAt6K0wEcl_Ux5ChNJnNzi3zM5rbpN8xWlNcF3g
HIqM5cjZOWTsxsSlhoZHwwvwcIbrfAx0sjuN
}

!procedure Wegame($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/W/Wegame', $name, $tech)
!endprocedure
