' definition of the Item simpleicons-7/W/Wix

sprite $WixXs [10x10/16z] Oy0BEC441nk8ukTdOE1cPk07Ce1CRY03WhXvWGHU

sprite $WixSm [12x12/16z] bOR50O0m00Elxit-q-Bmfj5ZKHdciRCQn8WX3OIAGxg25H_BLfp7Usg7mW_j

sprite $WixMd [16x16/16z] hSc50OD050FGXyDPzf-sla7v4dNpb9cLkLITrqTD5QjZ68V8z7fXz90btsVEmfccvVIho6eDqKxNOF7vvIV-d2S

sprite $WixLg [20x20/16z] nOZ5OKCn40L7p9h-gqqC9rVmTn_pq8t0zy88lLU0cONZ0VEEMC21u1HaBf8imH75EEGks0fCXpYSdorw-UXaNkDdSza1_SfxErBzsLeomBeyTFy

!procedure Wix($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/W/Wix', $name, $tech, $desc)
!endprocedure
