' definition of the Item simpleicons-7/W/Wizzair

sprite $WizzairXs [10x10/16z] Oo0C6Bcus1Y0Y861Xvc1aO6HdvUH6oh5miW8Ki0AOhFYD

sprite $WizzairSm [12x12/16z] ZOW70G0X24MVogP_tXia4Fxc-lPe-nOMW6e8I2IaopepucCWTGZSK1HqZejx0G

sprite $WizzairMd [16x16/16z] hS490GCX40Imx37y_lss8aYyKH-WHOjC-Iik2aa3KsSmQPQlE0n26O2uEXCccGkmWH6F_

sprite $WizzairLg [20x20/16z] lS75OGH140GmLG-Qyu_MVFnVoP5I7bIUVqoywCJqhrMDPtEAyDeQ2MlQwRPtmx0jMtnuaxomB56WB-RC4fe2rKKAI1_Ds5Ahr5dy6ykXlW

!procedure Wizzair($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/W/Wizzair', $name, $tech)
!endprocedure
