' definition of the Item simpleicons-7/W/Wpengine

sprite $WpengineXs [10x10/16z] O-0d1BZv6Q2A680CA8iV8SJ03M61L687

sprite $WpengineSm [12x12/16z] TOp50S0m24NnUl_-suROaOSh0NZI0fqwjpJklOGwrzF7wAcZqtDGx3pHVX_1vA4ICTQkul-zyWO

sprite $WpengineMd [16x16/16z] ZOx50S0m4CDSvch_QSFuYuB7rWqS51vwcn5x3vLN-7fckKlQt1tZyimrtnaIZJtJsvwgIUeSLsWLp8rwZ-kTwjS2

sprite $WpengineLg [20x20/16z] hT3L0O0W04NHQqllFwr5mwSyaqF3vd9E__5Kc_jludlFfZJK-u8ImSVsLiXhi-XDkCvyUWBb5_Pc9kOGGlYLMzzB-Rwxxslykev1vsAfx0O

!procedure Wpengine($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/W/Wpengine', $name, $tech)
!endprocedure
