@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-6/bootstrap')

' loads the Item which embeds the element ServiceAzureObjectUnderstanding
include('azure-6/Item/AiMachineLearning/ServiceAzureObjectUnderstanding')

' renders the element
ServiceAzureObjectUnderstanding('ServiceAzureObjectUnderstanding', 'Service Azure Object Understanding', 'an optional tech label', 'an optional description')
@enduml