' definition of the Item aws-q1-2023/Resource/ManagementGovernance/AwsOrganizationsManagementAccount

sprite $AwsOrganizationsManagementAccountXs [10x10/16z] HSY54S0m0810watOVzwuSFO7EmCtfHFrwxfF18jGIXOD5hLi-Zukdl74atDqPm

sprite $AwsOrganizationsManagementAccountSm [12x12/16z] LSd70SLG308mfUV1_lF-NdMn0N_6gEak9baynBxDYbcqZw53M0EJEIPjtTt_0UVs-Sjs_wTf4exx_v2AVFGA

sprite $AwsOrganizationsManagementAccountMd [16x16/16z] PSk50O0m30J0ZrIp_xxaSUXLOrXuI03p490AH-34IX_IdpYN5ZG0fenxLsaTQKR6VAKnD55bV9d7D9y4q14Ff2MUsloCHGoTgIEMz8uFKwx-HyRnqJO

sprite $AwsOrganizationsManagementAccountLg [20x20/16z] {
TSY54GGX54J1no1_OVBFzmhELhkykTU2aMZ-4hXsuyANve487K-ktc9_VIqz0GojKyaAP2QFTKGjk3I0ZKZhIBPPEdXUusTihJb96F34n-Swq1xEzlay-tiZ
8ZhAG4sVInEgG7pkoo1pF684wtHIX2vu0G
}

!procedure AwsOrganizationsManagementAccount($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/ManagementGovernance/AwsOrganizationsManagementAccount', $name, $tech, $desc)
!endprocedure

!procedure AwsOrganizationsManagementAccountCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsOrganizationsManagementAccountLg>', 'ManagementGovernance', $funcName, $content)
!endprocedure

!procedure AwsOrganizationsManagementAccountGroup($id, $name='Aws Organizations Management Account', $tech='')
  IconGroupElement($id, 'ManagementGovernanceFamily', '<$AwsOrganizationsManagementAccountLg>', $name, $tech)
!endprocedure
