' definition of the Item simpleicons-8/R/Researchgate

sprite $ResearchgateXs [10x10/16z] Ou02VWI32SO2iVaPUFZ1B2ZYOe2me4hu-E6A4ImEc2mGSG1f

sprite $ResearchgateSm [12x12/16z] LOk50S0m20Glhi3-qzOr0g_Sfye3awFTU813HBN3zcn_nnzU7toSF_QM7oo36n_lmV7RrOEi

sprite $ResearchgateMd [16x16/16z] TSk50GGX40F0ELT8_zM-ky1QpCkRqx_2RRQ_4l7-ejisfPHQounSkmG9jJKlp84i9CK3L_34_HjEF75D1Y-OJEzu2__oQz2a0CPaxUXJ6pW2

sprite $ResearchgateLg [20x20/16z] {
NSu55iCm30FGm21etV-scznNa1soVZ5fDSmKodRfKChCHQr0ysb0I_jVPhRUvtreRDWjttqLRZZ-Ol1Atqnkvr77EwcTTOQ24Osx60maiV9n2iykb63d5gmf
7ccZH-FHJfa0RB8pxBVJ3m
}

!procedure Researchgate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/R/Researchgate', $name, $tech, $desc)
!endprocedure
