' definition of the Item simpleicons-8/R/Retropie

sprite $RetropieXs [10x10/16z] Om01VY26CFZvCLYOW0sLnmaY6O6OXO4Fn6BavkQ4I44b

sprite $RetropieSm [12x12/16z] TOo35G0134DJzp7xJtisVatCA750nfuQoKk_iIFun_OaJMikT2vgrhc9tU_u_UC8

sprite $RetropieMd [16x16/16z] NSx50SGW443H7zpflzgLuBmBCahZwyEcr8fWgJ_fUdiMMMjXvpXv3YeYPtyvykM-W0FDdwPvf8ILfXNOTZCqXaa_UlLJD7EYMOs_

sprite $RetropieLg [20x20/16z] {
XO-55GD120NdhqlUqN-ryNERLHmOwHPO8pDJOqLxwxgnuc4VjD9b-y3UKR36uTdhtBrEJWd_lXb9lqimvOm0UQW3KO5ryP9gpGG-XB7l43HA4ap6OPmXyKVp
3z5BJnKS8s8aC1BtHd3-g_dRNW
}

!procedure Retropie($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/R/Retropie', $name, $tech, $desc)
!endprocedure
