' definition of the Item simpleicons-7/F/Fauna

sprite $FaunaXs [10x10/16z] Oq00VYuuYvyVH049RZ0JpEK2CY7YJ70M0uZ1nW0LXEc66SCCfG4

sprite $FaunaSm [12x12/16z] JSY52S004CNGG5sp_xJrVkvX8LIknAflD3sjEi3i3dX3kUtUtdvpAfzNbmHtaiIOEW4

sprite $FaunaMd [16x16/16z] LSxL0GKX44FHhEEt_sgVB3fySH9av6INntg7VRM0M7TRf1fgWRfnUkgv7fHIQ-cwQz8jI2zzjwsb_78RFe5aHWgBPAMy6Lv6Nm

sprite $FaunaLg [20x20/16z] {
PSlL0GD130FHEUQR_giDB0Iyxy-Mn4YhjoVgT2TIBtuC-QSJsQ7KdqUgg7E9aXAJMAopUfBjVb5S-z7yUhtCDgemJGwB6U9tuaUlUl17NVbtDn-EWsWUQ7G4
Jm
}

!procedure Fauna($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/F/Fauna', $name, $tech, $desc)
!endprocedure
