' definition of the Item simpleicons-7/F/Flathub

sprite $FlathubXs [10x10/16z] LKY30G0n4CkZHlQVjkPTZFl-6LwuvgoBKbYd-TIrB6JbNuLBW5YeGUpB

sprite $FlathubSm [12x12/16z] VKk30G113ClPpVxJlerJ6w9tAig6h9h70ikorRJzmitYSvwqSN8uuK1QW9on8Ts28JDMPS8Pq3BtAt4x8m

sprite $FlathubMd [16x16/16z] ZKu50iGW3AlEj_p_jJYSIz08jFGVz7oWHrAcmSpBiGzJoocofjqjRPnOZQ1O8po3yZy6ApvG_0kmv3agLnHEoE3AryPftJC_6OLBbfToh0iEAkYT2hqY0W

sprite $FlathubLg [20x20/16z] {
bOq5WiCm4CHa2Dix_t_jNJjbRfMOjCJFr0UJjxJTgPw1RRmkEwQaVbOg5SoqJ3x75SXEIv0Q4EUn0sQULKzkuKZ85I1L9gT9SjcelQEGGdPGPEVqLwwTdCwE
gcAtffZi8W4zTWwFH9emMGicHUS7_W4
}

!procedure Flathub($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/F/Flathub', $name, $tech)
!endprocedure
