' definition of the Item simpleicons-7/R/Remix

sprite $RemixXs [10x10/16z] O-070Hu68E270WO6PX00ilY0eb0P10kX3iPYXqhom9KnG6LPG2Gp

sprite $RemixSm [12x12/16z] NSor0S1030J1DREl_sgVUHAnKF3jEChE9XUPow-SFzBTz47PN_C7M8Bn3snEUvjo2m

sprite $RemixMd [16x16/16z] VOu30W0X50Kdk-v_shNHnEz7RYirIMPMUyK-x6R0fvNIPZYH3vk-hThCepytsppr54x4x92dlIHcJjorFs0UjbxU4G

sprite $RemixLg [20x20/16z] VS_50S0m243HkCl-qzOR1VxnHM6Yjf9ZRw-r163L0LRPbVnphnKsbTh6di0DFjlUyFK9-8lTB71W3ljO_4elQlpBBSf4Vkh6sxkgcGJj1

!procedure Remix($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/R/Remix', $name, $tech, $desc)
!endprocedure
