' definition of the Item simpleicons-7/R/Rockylinux

sprite $RockylinuxXs [10x10/16z] FSV70S1020D1ELil-g-M37k10HxbHIGP4zcp4kQFgrV0-IQ2IEJ7H71X

sprite $RockylinuxSm [12x12/16z] POl70O0W00FpiclsdrQ5etElL0LERm83qe246mtdrFFRa04BYKVc4kcdobNw

sprite $RockylinuxMd [16x16/16z] LO-53G0X0CJktV_sdnQd2OtHuYfidvz9dS-LewhXRmflMmoJFB8nqkN4Xwe4D7FR3rh3X7hDGQXBq86sy7Nb67H7-Kq4

sprite $RockylinuxLg [20x20/16z] PSq52WH134JH6jVktF-qQwai7-RZZuZSqUDUXPPmRIWAT1IniuWjTOlL6DjfCViFI9hYMoT9dYJbv4tov4ewSrAWY4Gra543gV0e8fhS-2JzsnDQ3hq1

!procedure Rockylinux($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/R/Rockylinux', $name, $tech, $desc)
!endprocedure
