' definition of the Item simpleicons-7/R/Ros

sprite $RosXs [10x10/16z] LKg54G0n3EAbBkm_RLrp5nm4sdj3WbJbgr_VRlkFnywMp9HNz-uf7wZRJfJF

sprite $RosSm [12x12/16z] TKl50G0X30lkPFzfSJudzKPG102E3iwJusITOnOgpRh_OaepvTI4wnNZg1wG5K0fRvDOKsrzckFSPOuE

sprite $RosMd [16x16/16z] ZSs50G0X30F0u4xsd_RT5JkqBLp5q0n71OKYEMv6CUYddPh4QAK6KEW74nF-cZ2ZM1LaMJ9DXccdzwfa0B3_QcnYbKmOhQ_vyx5-3m

sprite $RosLg [20x20/16z] {
fOw53KGn3CNUftBh_RSz9STC5ZWAQo7AICpktYGWIwg0fO2H0Jp61YRp33GREVUXQ2bF1ZVeBoguePWMc5QWUmhcWn_z9pnMFl_NfRB8MBDBCUfpfhEF09uv
k4EEd7zP3qwSSzl10YPx1ORDDiWx
}

!procedure Ros($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/R/Ros', $name, $tech, $desc)
!endprocedure
