@startuml
sprite $AzureNetworkWatcherLg [20x20/16z] {
PSk7hMH1449He81wat_2gvxUxw_yGU0ZfRiryPNZZkFe6s462DKFdDeLwJZXjGYkVGROE2c4vpqIpBrkToD97KqlRP9zQZVsdkT69DNo_Is0L0Jl5c82S4t9
CygcdkZOq7O4RwGQnpoo1FY9OfnQWcViqyoHCzyjEyHDp-l9QBg33zhNu-vkz4NF2Y29poxzh7y9_m
}

sprite $AzureNetworkWatcherMd [14x14/16z] JOm75WCW3489o_R-5-vJkxup2O23qeQuM2ObdO9MoCZSbR5d9WnWckxAp2caBjqg6Sp4LrbIfXfPc6e_N981n1WWw-PtQSOTRFnisjmY3sChBoluumK

!procedure AzureNetworkWatcher($id, $name="Network Watcher", $tech="")
  CloudElement($id, 'azure/ManagementAndGovernanceServiceColor/AzureNetworkWatcher', $name, $tech)
!endprocedure
!procedure AzureNetworkWatcherCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureNetworkWatcherMd>', 'Network Watcher', $funcName, $content)
!endprocedure
@enduml
