@startuml
sprite $AzureGuestAssignmentsLg [18x20/16z] TSq54W0X34DHI9kitV--wpX_Z7b0ItgE7a9WBBke5NaZTd-DJVm5g0MKY59u9I6BYLUBDQ9Ie0kq84kqvSghNTk-RwXaFuvUzafifnhnwvWbDnDw5Na2

sprite $AzureGuestAssignmentsMd [12x14/16z] HSY54GDH30FHs98-zbzlw0mxz6Q5YFQ2HQILdOHL-1aImYvfkBMH7YE_SMzQMFUszrOQ3eGp29K-

!function AzureGuestAssignments($id, $name="Guest Assignments", $tech="")
  CloudElement($id, 'azure/ManagementAndGovernanceServiceColor/AzureGuestAssignments', $name, $tech)
!endfunction
!function AzureGuestAssignmentsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureGuestAssignmentsMd>', 'Guest Assignments', $funcName, $content)
!endfunction
@enduml
