' definition of the Item simpleicons-5/E/Ea

sprite $EaXs [10x10/16z] uwS3

sprite $EaSm [12x12/16z] unza

sprite $EaMd [16x16/16z] un_X

sprite $EaLg [20x20/16z] unzKO1G

!procedure Ea($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/E/Ea', $name, $tech)
!endprocedure
