' definition of the Item simpleicons-5/E/Edotleclerc

sprite $EdotleclercXs [10x10/16z] uwS3

sprite $EdotleclercSm [12x12/16z] unza

sprite $EdotleclercMd [16x16/16z] un_X

sprite $EdotleclercLg [20x20/16z] unzKO1G

!procedure Edotleclerc($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/E/Edotleclerc', $name, $tech)
!endprocedure
