' definition of the Item simpleicons-5/E/Erlang

sprite $ErlangXs [10x10/16z] Oy02-7b010Y32GY9a0LXC82n-80ic48U7gWo7eHv

sprite $ErlangSm [12x12/16z] TSQ50O0m50FHmvtRVrhSQT-NX8WylwjhLvS_heyqJPUVoStjxOAzetHaqLj0HyGC

sprite $ErlangMd [16x16/16z] bOo30S0m54GlTcx_QMkxxvluIQsg3zAAFeJAsaTD4Ztas8yncc6TMBceytIsCguTwi01KScq7cX0aVEZBFg-rXehIkE55W

sprite $ErlangLg [20x20/16z] hOu53e1G34E_u3I_zpyjFi5Yy2BpjU5dIEn9pquwf6NZbhLaloMPVfmVteNtNZIarzAGNar3DAAKXHGlGLghUHMnJwCk9h1qktq05zT0-C0C

!procedure Erlang($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/E/Erlang', $name, $tech)
!endprocedure
