' definition of the Item simpleicons-5/E/Eyeem

sprite $EyeemXs [10x10/16z] uwS3

sprite $EyeemSm [12x12/16z] unza

sprite $EyeemMd [16x16/16z] un_X

sprite $EyeemLg [20x20/16z] unzKO1G

!procedure Eyeem($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/E/Eyeem', $name, $tech)
!endprocedure
