@startuml
sprite $MaterialsConfirmationNumberLg [20x20/16z] fP253G1H24E_Ex3_jET-ZV9Y3KwD2XzV-2NakhpeRedn9Ya4sWJViU7Sk6D7kbQ-OZRkUTfp8rgpa3Vj_PRBIm34SA_Zrmvy2xmP_OOyK343

sprite $MaterialsConfirmationNumberMd [14x14/16z] Oy07c5Y1W8qDH38nCB3p0m4d9uXaX_9OMA0yDX3DpGqYsHWWacniO2bK7gfAL5DGRK2p7Hy

!function MaterialsConfirmationNumber($id, $name="Confirmation Number", $tech="")
  CloudElement($id, 'materials/Notification/MaterialsConfirmationNumber', $name, $tech)
!endfunction
!function MaterialsConfirmationNumberCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsConfirmationNumberMd>', 'Confirmation Number', $funcName, $content)
!endfunction
@enduml
