@startuml
sprite $MaterialsPhoneMissedLg [20x20/16z] {
bSx7bSKm241HC1dZG__TZdFGQlxRwIe1FqIy1bk8brc7AcxaV5iwmau2jx4uNdGPmOeV0a9OSQKn6UaUusbYzGXNdYuXhmfJjQXosk_OqaNdRlLY29JTFUFv
vhmkSgN1JYov1whr007DIN17iT8u64xmx_u
}

sprite $MaterialsPhoneMissedMd [14x14/16z] VSpL0SGm30DGIp64i_-qntnjzVTaaD-GV0Cr6owTtHNE2nnt6Pmtt2dm1nx56yaZv_1q-v-74w2FJB6-9c_jNDtoMkskjbP6v0jkp04vo1a

!procedure MaterialsPhoneMissed($id, $name="Phone Missed", $tech="")
  CloudElement($id, 'materials/Notification/MaterialsPhoneMissed', $name, $tech)
!endprocedure
!procedure MaterialsPhoneMissedCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPhoneMissedMd>', 'Phone Missed', $funcName, $content)
!endprocedure
@enduml
