' definition of the Item azure/Item/NewIcons/ServiceAzureLinux

sprite $ServiceAzureLinuxXs [10x10/16z] FSR50S0m34Mn5p9yxpzlkT59t0OVir9-AN5p_zRst1leRW1F-pj4x6LxwGG

sprite $ServiceAzureLinuxSm [12x12/16z] JOk35G0m44DJ7VUVjzP_2Z594Pj8nA9fQY9nioa3axkjc9cxva_RqYCgquZC98-754nw4GKBDkZHwBg43JS

sprite $ServiceAzureLinuxMd [16x16/16z] JSk54S0m241HeaZttxU4m_xfGy1R2rhtTP9RzNqYuKSrEGUYURaF8ZvVD_fUocXUGRiKFo1QVcU3GGYUVH1jWn-eNNggdisWPjvbPFLemGy

sprite $ServiceAzureLinuxLg [20x20/16z] {
PSu74eGW44JH0KewSF_phfcm_ifFWOvUAV5NlVfIiwrEso5efws_jTFGAG6LbvLk6m1TjdL3D_QZmznVm9azRpabnL4-i5wKY3v1ThwEacFLSoLPeyThOoPB
ZAuz96CnVQpQaQKyMp42KbfoX5HMox43
}

!procedure ServiceAzureLinux($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure/Item/NewIcons/ServiceAzureLinux', $name, $tech, $desc)
!endprocedure

!procedure ServiceAzureLinuxCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureLinuxLg>', 'NewIcons', $funcName, $content)
!endprocedure

!procedure ServiceAzureLinuxGroup($id, $name='Service Azure Linux', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureLinuxLg>', $name, $tech)
!endprocedure
