' definition of the Item simpleicons-14/O/Onstar

sprite $OnstarXs [10x10/16z] BSQ30SG00CNGTqQH_QUjFmE_tdRLhfyBXbxAjpJyzhdnhXv5UcSsIBhqzhi8hweFAm

sprite $OnstarSm [12x12/16z] HOo50SCm3C0qJcBG_zUEsygCV0W7_BCttRnP_eWjRUuMxm2woX6Y0owKYWezBWuPdguuBw8dxkAw3SgDn_6_U9EXZdVt1G

sprite $OnstarMd [16x16/16z] {
LSY70GGX20NHlqaN5QR_RW-z_8o3bilfczv69OrUj7HUkl-buKCQl9mgsAPAR583tu6uG1gNMWmCgdC9s6LAzFa5xkoyy4wVhTbpRx0fyMePZ6BWjhPAy6MI
nZTRKUhlYHKjczUWtwxq
}

sprite $OnstarLg [20x20/16z] {
NSn7ee0m30FHePCuoTp_jB_GuIrjIHnIiymyJ2L7RILoxJYuUag9JQdUKWRmSGfD4qpfldJCMY7K1RR93ZLMiesDMhQTaeeTHOEkiS2iqHJy0mrwQ8RAi6yr
1bUAKTeZjvh-RtEuGAiGrusiCq3ol1N2ZxcdMtof0Ydx5F0vjjopcQxZ8fSrTdle5m
}

!procedure Onstar($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/O/Onstar', $name, $tech, $desc)
!endprocedure
