' definition of the Item simpleicons-14/O/Opencv

sprite $OpencvXs [10x10/16z] LSV50O1G081Gx9RzfpL_SdfGfKOGQ1zrxdo8_w81mLFurTaehhEeCEfy0m

sprite $OpencvSm [12x12/16z] NSk50OG030F0lEBS_jFYNcyaZoYnt_pPuRNdU2l3hacQQbUVHlDiKcjMeI9_dMHgdtm4zXcwpJO2

sprite $OpencvMd [16x16/16z] RO-50GCW30HnXzj_spPV5pGNZ_kx5X1UUB0L7-XDtl3W9l75oSJmOfasyyd1n8Uvm7QVjQgIc4_sqBDoCDo0_N1M-Zj7UF3rp0hB0Vc0HhdR02_dgWpJEhe

sprite $OpencvLg [20x20/16z] {
VP350SKm34FB3R_zf_qWbo4wc55D1H5oTmuXn7i8XZtK0QjSuSovnePhh9KN83Sx2abrv_Cakhq8Q4yLFQopyTfdvrfP10rDCuJz6PDbNsPP3zaQ8V-xR4Al
QO3xYz0uG9VOvc4dX-sOIPOJKyvrwx6k_yal
}

!procedure Opencv($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/O/Opencv', $name, $tech, $desc)
!endprocedure
