' definition of the Item aws-20210131/Architecture/Containers/AmazonEksCloud

sprite $AmazonEksCloudXs [10x10/16z] FSZ70G0m3C90fuhz9mvfvdK8c7jZaDogOnE2Q3Fcb5CrBLdkMmegiDkUZtPisrktBm

sprite $AmazonEksCloudSm [12x12/16z] HSa74W9H409H9z7__YTsq0rTwL40-ZV3E_wEb5kcGjqsGQb6UvqriR2FpOVBwg32BX5ilVOJ6nmddErmNm

sprite $AmazonEksCloudMd [16x16/16z] NSZ70SC03CD0gv3G_XCdxWM_0u3F9C5pM7p6pd3qxMnin-c4NDNrzu3M8wLpzM24J3oTHF2m5rWEQvHge7hrg8Q5jS2pbdAi2MQBC7jpzl1p_

sprite $AmazonEksCloudLg [20x20/16z] {
RSZ50O00302n-fNz1yOTyWoBkkICTzPn_1sUSUvUOfdoE7CigypEIm4alQeazdC8Wz8vRBbUpp04FwxtCsxNsoacnVDOnizh99S7bEqYcb9bKS9wZG3Eog1w
5KReoe7UYJg7Fi3ZtZlyv0G
}

!procedure AmazonEksCloud($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/Containers/AmazonEksCloud', $name, $tech)
!endprocedure

!procedure AmazonEksCloudCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEksCloudLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure AmazonEksCloudGroup($id, $name='Amazon Eks Cloud', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$AmazonEksCloudLg>', $name, $tech)
!endprocedure
