' definition of the Item aws-q1-2025/Architecture/Containers/AmazonEksDistro

sprite $AmazonEksDistroXs [10x10/16z] TOcr0G0W30Glll_4E7H4Nkip6fifhDYH3dcKmQkFBF3SmjZYJ0S

sprite $AmazonEksDistroSm [12x12/16z] VOkr0G1H5CAUGVQV-5owdmfbHTQhoebqXxHRrAt9ygyxEcxjYSmnq2OdxNdUeKU2UUJF3W

sprite $AmazonEksDistroMd [16x16/16z] dSv70WH12090eGN-_-BDEzucTRGuaJlBC3MaudVsv_iWqVfQxqGlyMz53ZmELhbgx0hK_fijf8ElcR3K4AT0TTIUWWhe7Ayd

sprite $AmazonEksDistroLg [20x20/16z] {
hSl5WGGm34DHnPBz-wzuTnXo6df14p_WQJQgRl6eJ3NONBK0jKytPuOKp0hKFLSKmdkkODMMMvP6scSxT6uvXL8RZJX9eDUQWF1m9c24b0nNBb0FIRZJSkG9
k-4j_m
}

!procedure AmazonEksDistro($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Architecture/Containers/AmazonEksDistro', $name, $tech, $desc)
!endprocedure

!procedure AmazonEksDistroCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonEksDistroLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure AmazonEksDistroGroup($id, $name='Amazon Eks Distro', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$AmazonEksDistroLg>', $name, $tech)
!endprocedure
