' definition of the Item aws-q1-2025/Architecture/Containers/RedHatOpenShiftServiceOnAws

sprite $RedHatOpenShiftServiceOnAwsXs [10x10/16z] TS450S10402WUwL_uhaB-D5qG8XS4HaLeYAQJG_a9jcKoAv6

sprite $RedHatOpenShiftServiceOnAwsSm [12x12/16z] VSQ53S1034FHyDz_uygAg7GlO7CIxgmU6cgxmZDLQQ0SzJ308lNrA0P86-yWG9ozDJnT

sprite $RedHatOpenShiftServiceOnAwsMd [16x16/16z] dSQ74GD134BHHHBy_ZlsN9vi-vu2y4RK7eMJ1nmyOTV8H1gn6OgDn4wi0AR2PjLUeYesMkmA0SJf0MpCfhITWZYL0Ol7r8HVV

sprite $RedHatOpenShiftServiceOnAwsLg [20x20/16z] {
hSp5OKK124JHmURsNt64_tITd0qE_y1LDRne08lR97WCrSCXGCt8gREP9ZRfYZ9Bv95qS4WhZn_Li9J7F9NZpPmoow9OGSDgepDhLHggw86Llrb70Scbqm1L
F9MavE--0G
}

!procedure RedHatOpenShiftServiceOnAws($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Architecture/Containers/RedHatOpenShiftServiceOnAws', $name, $tech, $desc)
!endprocedure

!procedure RedHatOpenShiftServiceOnAwsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$RedHatOpenShiftServiceOnAwsLg>', 'Containers', $funcName, $content)
!endprocedure

!procedure RedHatOpenShiftServiceOnAwsGroup($id, $name='Red Hat Open Shift Service On Aws', $tech='')
  IconGroupElement($id, 'ContainersFamily', '<$RedHatOpenShiftServiceOnAwsLg>', $name, $tech)
!endprocedure
