@startuml
sprite $AwsCodepipelineLg [20x20/16z] {
RSYtOSG030F0XYI2zj_N3ok7Ayy_kYBfZzpkAiU-W2JR3GK3lPqS2bvEgSjLppJ1wUwgzQPdbPlrp0A9AEXdIOujWrPBkUHegCPmk-IWpL5Xk-GO719g-JmB
jdFUhhN9MKlCfiUn_FD5RdEzZ_m3
}

sprite $AwsCodepipelineMd [14x14/16z] RSct0S0W34JHIfUq_xuMgVCdFaZYbtHrcGWtsWdU1tvK08cgMlB2eknEomubUjGjOYQOetbVwyfnCigIkOAIz9JRqkxg0m

!procedure AwsCodepipeline($id, $name="Codepipeline", $tech="")
  CloudElement($id, 'aws/DeveloperTools/AwsCodepipeline', $name, $tech)
!endprocedure
!procedure AwsCodepipelineCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsCodepipelineMd>', 'Codepipeline', $funcName, $content)
!endprocedure
@enduml
