' definition of the Item azure-4/Item/Security/ServiceSecurityCenter

sprite $ServiceSecurityCenterXs [10x10/16z] LSW50G0m20J0n-bVUAw7WvStqgP61BKQ6mB_9gtHs92vcsT7MAjYiF6f

sprite $ServiceSecurityCenterSm [12x12/16z] NOo50G0X202FPl-5lqCzEbd80xkpboElAaGEV-TMlBchaKyk27RdBOUtpilNyQJwVjedpbSO3rQSx

sprite $ServiceSecurityCenterMd [16x16/16z] RSk50OKm30JGYrxsNnYeV-5LOtYLZvX_jPn2UusF33Onuu3WCqPIxJCc_IDsQJvYG03s3s8yFHvlZRXgn54J1LtEs37bPpX7gFWWEJyt

sprite $ServiceSecurityCenterLg [20x20/16z] {
VSW50i0m20J19GBy_yELg-jMSXc-Cv_g5_Ar2ghwDQPQg6fTvyd0Q5VhH3GkfhlBujSmjLdLc11sOnyor_BCN6rQLQl4j5JBT52UUs7SCHfx_YJeeigb7kd6
BMlx704
}

!procedure ServiceSecurityCenter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-4/Item/Security/ServiceSecurityCenter', $name, $tech, $desc)
!endprocedure

!procedure ServiceSecurityCenterCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceSecurityCenterLg>', 'Security', $funcName, $content)
!endprocedure

!procedure ServiceSecurityCenterGroup($id, $name='Service Security Center', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceSecurityCenterLg>', $name, $tech)
!endprocedure
