' definition of the Item aws-q1-2023/Resource/LoT/AwsIoTThingVibrationSensor

sprite $AwsIoTThingVibrationSensorXs [10x10/16z] JOp50KCn3CNK9WRjF_1dqiNmW2_PwdiE20Ho18M9FGg1NuyXudPwR7y8XZ37Jd_wLW

sprite $AwsIoTThingVibrationSensorSm [12x12/16z] LSr70SKm50Cm9Htsum_uprD5G9uMKw3vErdnrqMMszw2G2zXCjlQCgE1dAPadOWY_eApwKppVDy

sprite $AwsIoTThingVibrationSensorMd [16x16/16z] RSyvWcKn30B0mcz1ll-1PtfpzYkI8C87KLlgpyhOrldl78Ei4Dmq8Kd1LdHY3TVQsYBhgKcsOkziCp7QFOYd-Ekp8kzjPpJHnWJletqHHy7qc8zxpl_2Vm

sprite $AwsIoTThingVibrationSensorLg [20x20/16z] {
TP07SWGn3CD0UsM9__zmmjIhu5GCjjYyGqNZxCOTvjvfndzh2CCDMwaKj_zSP9N1HV1XTwKSr0oSmfyTq9rE9nd3dlxkhhEcBATRW6qIM3NQlUtOGP7r_Qn-
Egm6ZFdl6i6A_U-M0ShyT_-a2ttjV-RRaL-OPMLwVt-HY4KMFW
}

!procedure AwsIoTThingVibrationSensor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/LoT/AwsIoTThingVibrationSensor', $name, $tech, $desc)
!endprocedure

!procedure AwsIoTThingVibrationSensorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsIoTThingVibrationSensorLg>', 'LoT', $funcName, $content)
!endprocedure

!procedure AwsIoTThingVibrationSensorGroup($id, $name='Aws Io T Thing Vibration Sensor', $tech='')
  IconGroupElement($id, 'LoTFamily', '<$AwsIoTThingVibrationSensorLg>', $name, $tech)
!endprocedure
