@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsMoreHoriz element
include('elements/materials/Navigation/MaterialsMoreHoriz')
MaterialsMoreHoriz('element', 'More Horiz', 'an optional tech field')
@enduml
