@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/materials')

' loads the MaterialsLastPage element
include('elements/materials/Navigation/MaterialsLastPage')
MaterialsLastPage('element', 'Last Page', 'an optional tech field')
@enduml
