@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the AWS style
include('styles/aws')

' loads the MaterialsFirstPage element
include('elements/materials/Navigation/MaterialsFirstPage')
MaterialsFirstPage('element', 'First Page', 'an optional tech field')
@enduml
