' definition of the Item simpleicons-14/M/Metrodelaciudaddemexico

sprite $MetrodelaciudaddemexicoXs [10x10/16z] uuS0RWO6VXXWOe0248U1dvU1duK1n08ZSbW

sprite $MetrodelaciudaddemexicoSm [12x12/16z] uuS2FaO61du4O6240YOG1mv0Ka2Ibm58iGBPZ406TTa

sprite $MetrodelaciudaddemexicoMd [16x16/16z] uqS07aO61WP-503Z8mIG0Ji_Fn-A01S_FrW8ef4NgXl6vn-CV

sprite $MetrodelaciudaddemexicoLg [20x20/16z] vSc50S0W0C2mpdtz_zgvmWa4B_uC6Hj3-TxYsF_CUoIGgJs1maEs_qxGQGaUkkC2zR5FxlghbIcq5G

!procedure Metrodelaciudaddemexico($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Metrodelaciudaddemexico', $name, $tech, $desc)
!endprocedure
