' definition of the Item simpleicons-14/M/Microsoftvisio

sprite $MicrosoftvisioXs [10x10/16z] BOa74W0n20BbUkV_lprtmYOgfK0Lh3EY2lcvkMVsQX_VJkKnKSyiLFDmY3CS8Nu

sprite $MicrosoftvisioSm [12x12/16z] FSV50GGW0CJ0uCxsN-q9Dg-4nV2ePOvfgMkCASc0Z35QUe_6H0aXHS2UDhkZh-gnhnPIPu3l-Ykau1p00CIMD5P-0G

sprite $MicrosoftvisioMd [16x16/16z] LSU5SKKn0C0mXteDUlzfFptMeTW57hHoiphMMnlWFryXX6e8WE73tS0Toud30h2KQ8Zwn_w1pDkbedDwF55qaDV-5VqUQwqEDnKiAIM085zoc0CmS-fgukiD

sprite $MicrosoftvisioLg [20x20/16z] {
PSm50e0W44JHeLc3V__JskrJQaiNfvz6rGSux5ibXNSbQ75LkeNXdPDKSGirJhq29xDz6oBf64GIe4gZw8mXe-p9Hqp80VQ8cGRrqDez3_PpKC0zOd6BoRXY
DFQOOpDmCacai90M7cqokj7lHz43H6UCUkcWPUrc
}

!procedure Microsoftvisio($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Microsoftvisio', $name, $tech, $desc)
!endprocedure
