' definition of the Item simpleicons-14/M/Mozilla

sprite $MozillaXs [10x10/16z] VOQ30S100CHIkzb_sjhuOmohH9ASNgKMErJsd5H6aLCe_T08

sprite $MozillaSm [12x12/16z] uoSLy3500I-GmyJ0pmz2pBZO4FNyOCH7ZF4

sprite $MozillaMd [16x16/16z] hOUr0O1G34JVTq_stvQW7HMSd_uE801xp_qNY6i_6NJ7NecqZ-TNojltu5V53OLW7y0-NG7zYWq

sprite $MozillaLg [20x20/16z] nOZ50SH008GuYGlzTvlr1c8yHl0rHa3WPnzoRoxnvnFIn0Apfhl1Mbt83v-G5xYHmCTFI0qn6jmdyFKVihdxEG

!procedure Mozilla($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Mozilla', $name, $tech, $desc)
!endprocedure
