' definition of the Item simpleicons-14/M/Myob

sprite $MyobXs [10x10/16z] Oo0Ay0CHFpCGy_7pWzaSZ3py32mC38nS38mCpEpuTGC

sprite $MyobSm [12x12/16z] dOI10G0G08C20Fn_BNW0jehl2LHhBJ6pBGBl2rvGLngs4WjhcUiD

sprite $MyobMd [16x16/16z] jSV50O1034JHlwx9z5yjTkCEBphyoQufAPKGIDI8LLRRktSXnPtlGqrXUkaYT6S-UKJH9NJDuyelaw-S

sprite $MyobLg [20x20/16z] pSWt0W8X00319HmPzl-lDRVMEkNm9_nsEZK9PZseRHSCoTM2isCneWa9HaVRWTM4OtmTocKtkeOP8WJ6Wb0XnSf7CV1pTm

!procedure Myob($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Myob', $name, $tech, $desc)
!endprocedure
