' definition of the Item simpleicons-8/N/Namecheap

sprite $NamecheapXs [10x10/16z] Oo00-FdvsHaOUFZ1B309Gdpy7BpyN40ML9WNo00ASd9YDGC

sprite $NamecheapSm [12x12/16z] ZKZ50G0X33l58VjlI-s9jV7hx1p0baaR88K5UDag2OJDvfibsCoviRMBhxNtcbu7

sprite $NamecheapMd [16x16/16z] fOt30KL154FpZC7flzenjX_NJFI_h2TGgvB1Wr6fa3Pe1sj9mE71rafx7yxgaF81iEi06jJTrblh3NigN65AsVjDtqi4

sprite $NamecheapLg [20x20/16z] lOn50e0020Inc_d_RvMmpiPUO5D-mj02cYG_5A0JmmniPuGAUmtsv9aj63v3f8SY_TjHe9S564Kc8sdTq-d5sf8nyKpl_e8TWrg8mJjQsV5FxNyVAm

!procedure Namecheap($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/N/Namecheap', $name, $tech, $desc)
!endprocedure
