' definition of the Item simpleicons-8/N/Nextcloud

sprite $NextcloudXs [10x10/16z] Oo08-Fdv81G_0mCd6uZYuWVn6TY1OhnSG0PG20ZO-76P

sprite $NextcloudSm [12x12/16z] ZSMr0SH00CH0FPXX-k_McUDRa1hEv_M6Jzy-N2hmZuhkM5HkgZveC0y

sprite $NextcloudMd [16x16/16z] hSUr0GGn44DHcLc__seFeytz1gLBmYCP6F_tm6UaJArG6icWZm7jCrRuvmGI0JYKJxO15CzGPsOJjBV-AZZeXZS

sprite $NextcloudLg [20x20/16z] lSwrbGGn40N0FonuKkKVxJ7k-bDUS-TMorC2PhxLjhwdMXb6KjgMGEMZweJU747BEvoPI1hbEvTS3gDWv9rf5jAn3E_3f6BvUco0y_-R9pCtUWK

!procedure Nextcloud($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/N/Nextcloud', $name, $tech, $desc)
!endprocedure
