' definition of the Item simpleicons-8/N/Norco

sprite $NorcoXs [10x10/16z] Oy01-FbX332BZu61aP-10yZb1M9ETf0u6BCXguHhvaOn2m

sprite $NorcoSm [12x12/16z] VOQ30S100CHIkzb_sjhuOmZ9zi1MTqni1TmcRG_ieJA7pWZ17X8RY7jbrmKnuw4H

sprite $NorcoMd [16x16/16z] ZOt50SGm0CDK34VxJtlCMF_CR8F34ytwI2UVkMOdeEYPIkymwxqiQ3gN1oIX0cTLg5VQ0PTP1s1Q5ixBXkVBpZFd2HEViGS

sprite $NorcoLg [20x20/16z] {
bO-30GKn341pTjx-qtwSwpOsf1HQDpGosg4Ai6C0RcWvcrLrrnEee6UsVOQD_-OLjgkp-QjM1ZWw5IOP9bcVxVDU3gzXzP7hsKFpDQpQzT8xDswUixjzk_FB
8ZRe9eNm1G
}

!procedure Norco($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/N/Norco', $name, $tech, $desc)
!endprocedure
