@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2024/bootstrap')

' loads the Item which embeds the element AwsIoTGreengrassDeploymentCard
include('aws-q1-2024/Resource/GroupIcons/AwsIoTGreengrassDeployment')

' renders the element
AwsIoTGreengrassDeploymentCard('AwsIoTGreengrassDeploymentCard', 'Aws Io T Greengrass Deployment Card', 'an optional description')
@enduml