' definition of the Item simpleicons-14/O/Omadacloud

sprite $OmadacloudXs [10x10/16z] Oo01y361AMOWPcLWP-VWO-3dvsVWPs0de0y

sprite $OmadacloudSm [12x12/16z] dS6r0G91002m_BdV_jlIqIA9VuIplEqSeAX59cfNfXdP8kE9Zo3vmWi

sprite $OmadacloudMd [16x16/16z] jOc50O1030FlhORjFork0y1La_0JjV1274PUn3YbCm9DbPQf9PKou8wbGe9KGHW2WxPkpwPyp08

sprite $OmadacloudLg [20x20/16z] pSYt0GCX5C1GaU77_QTrwfZ0fzU91pPI92jNGIqutBFD13f0Qx0-60DMMsnsBIFvMAKUfI_Z19pVEv06IwcOeJ-cWibe9lofDm

!procedure Omadacloud($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/O/Omadacloud', $name, $tech, $desc)
!endprocedure
