' definition of the Item simpleicons-14/O/Opensearch

sprite $OpensearchXs [10x10/16z] DKg50S0m20lpLV-_5dTYq9eDKLihKK1AV2AD_UEh45KAkecwxlsu59cjYW

sprite $OpensearchSm [12x12/16z] DSd50S0W04FHZplPVziMUwS8owmy-kMN5tjoqGBfrBQoP4uJCKiQAtS6MlfviXR0DN0d8XxtOXngm0S

sprite $OpensearchMd [16x16/16z] HSd50O0m0CNGu4xsdnRgVQSl9BidTA_gIsFI1xE3OZ83ffLaA_sHOj21Mrqe17UZcUW6CHk12UGn8tfEU7iV13ZRxKGo3Faze7lYMzpgIVG3

sprite $OpensearchLg [20x20/16z] {
RP054i0W30Ilxkp_Vzi9WyDMYLyK-BXLis6uIGK4EfiniZqobj2Y29pkgWqMSgF40PpItDQz91psJLWk9qOIyKeJ8k1axDABldPUpax3HYysI7bBaqkxklPW
GjqQdIgcDwmbO1gzLiyF
}

!procedure Opensearch($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/O/Opensearch', $name, $tech, $desc)
!endprocedure
