' definition of the Item material-4/File/CloudQueue

sprite $CloudQueueXs [10x10/16z] uwS3

sprite $CloudQueueSm [12x12/16z] unza

sprite $CloudQueueMd [16x16/16z] un_X

sprite $CloudQueueLg [20x20/16z] unzKO1G

!procedure CloudQueue($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'material-4/File/CloudQueue', $name, $tech)
!endprocedure
