' definition of the Item simpleicons-7/L/Leaflet

sprite $LeafletXs [10x10/16z] Ou00HWOeuEU7C_XX37P-BgW8H923dn-8-E52760MBrG75pyVJ2yhX04

sprite $LeafletSm [12x12/16z] PSs50O0m40D0tE7sdnQtjk-QPAdKXgTazfPuo-wkP-0RNtNkcpUCtlbPJzVz12yf-Put

sprite $LeafletMd [16x16/16z] TS_L0OK020NG5tQT_QUrnUOFkFbvdL9nNEdiMmxxtg3QznhmNTOV5CYM7K0-hz_jBTlPxSw7okuNSE7MW2QY9l6U_TiEnpgxsG

sprite $LeafletLg [20x20/16z] PT254OKm4411t67xh_OhSZTvunjFbQgheaLVvLficLOE4i6Uh77MvLb6B8dEBfh1aWpOearW4arOkaURWIbV1AGd7ANLY7-mi9tJdW_SDM7QMJ-1eueryHvl

!procedure Leaflet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Leaflet', $name, $tech, $desc)
!endprocedure
