' definition of the Item simpleicons-7/L/Lemmy

sprite $LemmyXs [10x10/16z] 1S470G0X00GWVhgz_cq5003m1wG7kF0taCqDWlLo0-bKG0200m

sprite $LemmySm [12x12/16z] VS650SCm000Wwl7yV-tSfU2VPN0r3v5Ifd4k2v4HH9JWQbs9NdMq4K8IPiDG8UYA7KS

sprite $LemmyMd [16x16/16z] bSSbOWGm002mbBdz_szd1dON5vzQU_YnTntOSyGOvoY4YmdOq2m_Wil--wim_HXWkmil2w0t1Dm0IHYgwm3qC8eNcp-X-Pyl

sprite $LemmyLg [20x20/16z] {
hSZ5WGD1300mBGo3-w_s6D-9pFPiExVmuuxSQuDPPpdFywqdr83joz5ntXVBZ-jaw5dpA-o3evz-HGB7ln-Wgm4fM83b3ZX31Sm-CMOYjLryYQjJZEf7lQv5
QvOVDqPSk3pe5G
}

!procedure Lemmy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/L/Lemmy', $name, $tech, $desc)
!endprocedure
