@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2022/bootstrap')

' loads the Item which embeds the element General
include('aws-q1-2022/Resource/GeneralIcons/General')

' renders the element
General('General', 'General', 'an optional tech label')
@enduml