@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('simpleicons-14/bootstrap')

' loads the Item which embeds the element Hootsuite
include('simpleicons-14/H/Hootsuite')

' renders the element
Hootsuite('Hootsuite', 'Hootsuite', 'an optional tech label', 'an optional description')
@enduml