@startuml
sprite $AwsIotAnalyticsPipelineLg [20x20/16z] hOy30aHH24Kls_-EnpR-USo5fI752qaaFEtmfDfAJe3fYG6IUAEp92URlT5vfoi1g5NKIzqUVgqRwu1tDHxrygZdkzasqjAi0G

sprite $AwsIotAnalyticsPipelineMd [14x14/16z] ZOt50G0W24NvmVuhstNpALtn3MqUpsJQbfIiCL1_osJrgglQXkgUgA8HrOzL6rigRSjx8Ruf

!procedure AwsIotAnalyticsPipeline($id, $name="Iot Analytics Pipeline", $tech="")
  CloudElement($id, 'aws/InternetOfThings/AwsIotAnalyticsPipeline', $name, $tech)
!endprocedure
!procedure AwsIotAnalyticsPipelineCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsIotAnalyticsPipelineMd>', 'Iot Analytics Pipeline', $funcName, $content)
!endprocedure
@enduml
