@startuml
sprite $AwsIotButtonLg [20x20/16z] {
RSx70O0m34FHY-Is_y0es7G-_G59SXNttFC7BxgIa8nc1pZckWmwnYAxXMpJtSgKBcrEwmZ0P7NxbvIwhDnsS3Wp26khPS6RlVwDPHMq2O1dM_fPZ35BpR8P
kLja7kJKMMQqg9cRrZRbMVrW_U06
}

sprite $AwsIotButtonMd [14x14/16z] DSf90WC014FHZXdS_y0DvUyUSTB5nMO3Sj-_tv5sFHAl-R73vvDV2Rq3Ofwugkp_IoYIkBNWAYT1pXAg0HnDdbR77m

!procedure AwsIotButton($id, $name="Iot Button", $tech="")
  CloudElement($id, 'aws/InternetOfThings/AwsIotButton', $name, $tech)
!endprocedure
!procedure AwsIotButtonCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsIotButtonMd>', 'Iot Button', $funcName, $content)
!endprocedure
@enduml
