' definition of the Item aws-q1-2023/Resource/Storage/AmazonSimpleStorageServiceGlacierArchive

sprite $AmazonSimpleStorageServiceGlacierArchiveXs [10x10/16z] Oq02h70M6nXm0bcS482cW1KcmWYbGIhPEM1CTWOK

sprite $AmazonSimpleStorageServiceGlacierArchiveSm [12x12/16z] LOo50G0n30AX2liF_5hBLQA0IETBUrED5f-N1by--lvdtPovghLoeQIHLwYiVNQiVFbeODm

sprite $AmazonSimpleStorageServiceGlacierArchiveMd [16x16/16z] ROs50KGn349fdFq7FgbzVTKOu0NMe8qmCCb-jns3_PQ3tcMRx34sEkCMvOJlM4aQZtgq1iOH6qgYZXZykvnYj7uVCVmMOyV10-0B

sprite $AmazonSimpleStorageServiceGlacierArchiveLg [20x20/16z] XSZ50SG030CmX-Fz1pueS_KKxXHdc8LZDgSq5beOC3Sem-aE1jo9uH9Rs_CuN4gBf5bk3WmowDYS6856xIxEXmPfeRipQcLZTu2Mu7Wed0zl5pi2V04

!procedure AmazonSimpleStorageServiceGlacierArchive($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2023/Resource/Storage/AmazonSimpleStorageServiceGlacierArchive', $name, $tech, $desc)
!endprocedure

!procedure AmazonSimpleStorageServiceGlacierArchiveCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonSimpleStorageServiceGlacierArchiveLg>', 'Storage', $funcName, $content)
!endprocedure

!procedure AmazonSimpleStorageServiceGlacierArchiveGroup($id, $name='Amazon Simple Storage Service Glacier Archive', $tech='')
  IconGroupElement($id, 'StorageFamily', '<$AmazonSimpleStorageServiceGlacierArchiveLg>', $name, $tech)
!endprocedure
