' definition of the Item simpleicons-7/J/Jenkins

sprite $JenkinsXs [10x10/16z] DKi50G0W31lkqByjT_y47ET2el9ut9DN4uu7ds426ubc5-X6QjRk1Ol8tf7FU_S-nrRx

sprite $JenkinsSm [12x12/16z] 1S690SCW30GmDO2Tx-Z-sqO2iYUW1awm3l17600BceKrCJm007TGupSWbgiz49g4UHX3RhO2hdPz

sprite $JenkinsMd [16x16/16z] {
9SN5eKCn300mXHFxmVxJVcXr4Q3URmAmpaPz00dmW9ERWt8FwBO4BbJQDoRSkw0tvLgupmnW6OW2u2Ji2Lnz792mnZK1mI3I0zo3zNbZTttbVdUsrPONt6JO
kWSKfhFv1G
}

sprite $JenkinsLg [20x20/16z] {
HSy50XWf30302Iluyl_NthLDPN0dICy-NvNIs0Db3gJwlb8SwRaYI4y7pZk84uXwmABnI7bai_rJOOS5caOVS69bk-YN0MNNGIfldhsQVpu5bf1QRN79jJpg
xBNdb3QDUAFGf8e7Jt58UnCLiSi7PdT_UvyVllKvN1bxwun-cw9OKaKlfihzn2zDxBZRylaV
}

!procedure Jenkins($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/J/Jenkins', $name, $tech, $desc)
!endprocedure
