' definition of the Item simpleicons-7/J/Jordan

sprite $JordanXs [10x10/16z] Oq03_70MAmCwO8HBil7361pyS4b-29EV4KZmy39mmMJu0G

sprite $JordanSm [12x12/16z] PSY53O105C1GtA7xJukTV6kiUKsCNlvKlebEeb1tlH3VvNj0wSRuNflfE9hz-k_3wm4

sprite $JordanMd [16x16/16z] TOv50WCX34M3E-_-fwrBqiwm8j_bx7Ni7RAzapq5SmqPbiKR6fo-5tHzogReKm2z1JGmg0_iESanH7tILhKx-oIcw0e

sprite $JordanLg [20x20/16z] {
VP035aGn54DJktV_gnsp7pb-Y7GEGzxCB5KRbEt8Xkri--d5EahqlZM2MqOEDaw8CFz7tGl6lxEelCwyjG1vKNtYPzJeLh83tl42cBVMYpJ_yZYQLsM9EUao
cyfq1G
}

!procedure Jordan($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/J/Jordan', $name, $tech, $desc)
!endprocedure
