' definition of the Item simpleicons-7/J/Jsonwebtokens

sprite $JsonwebtokensXs [10x10/16z] 5SI55OG044IndEBy_hlbRKQC62tIZjAx3sded6VUvus5jTfyAryD6oLT-9631m

sprite $JsonwebtokensSm [12x12/16z] BSs55OG030FGubh-_jEUv57NfFwogrUaJdleNqtctDgPwh0s5oFkZ7BLkRn-XkLNFYZNOCNGSdfQFPNj5lmbJNZtgYy

sprite $JsonwebtokensMd [16x16/16z] {
FSw5hS1G34DHbxbd_sa_H57lmx2JWYCVJzlx5-kZx9k1us9A0MxECcm3iJ1Sh72ioJo2ZBhFWIj_34-AwT_ghFwv1pXaNjuROi_CPY73MPcyNBmf48wn1UKn
blxRreDITl4B
}

sprite $JsonwebtokensLg [20x20/16z] {
PP055eKm30HJGMgP-v_sopwSWTg-kEs0svNbqE8kmR9fK4tCG91MWSCE33m2wNIcWxExmceHA6HvTeeSVJYs15e7-GWJw_w83IZI1h06NTE8U_5DH-uSTW3K
k8VuYpaW31Zgn0FK0WppR5QGatgqebOIaC7zCY-WQGPo50KmQKdUOcAVQSF4U_PV
}

!procedure Jsonwebtokens($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/J/Jsonwebtokens', $name, $tech, $desc)
!endprocedure
