@startuml
!procedure AzureGroupDotted($id, $name="Dotted", $tech="")
  CloudGroup($id, "AzureGroupDotted", "", $name, $tech)
!endprocedure
skinparam Rectangle<<AzureGroupDotted>> {
  StereotypeFontColor $FONT_COLOR
  BorderThickness 1
  BorderColor $AZURE_GROUP_BD_DARK
  BorderStyle dotted
  FontStyle none
  FontColor $FONT_COLOR
  FontSize $FONT_SIZE_MD
  BackgroundColor transparent
  shadowing false
}
@enduml
