@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('gcp/bootstrap')

' loads the Item which embeds the element ForsetiLockup
include('gcp/Item/OpenSourceIcons/ForsetiLockup')

' renders the element
ForsetiLockup('ForsetiLockup', 'Forseti Lockup', 'an optional tech label')
@enduml