@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-6/bootstrap')

' loads the Item which embeds the element ServiceAzureHybridCenter
include('azure-6/Item/AzureEcosystem/ServiceAzureHybridCenter')

' renders the element
ServiceAzureHybridCenter('ServiceAzureHybridCenter', 'Service Azure Hybrid Center', 'an optional tech label', 'an optional description')
@enduml