' definition of the Item aws-q2-2024/Resource/GeneralIcons/Database

sprite $DatabaseXs [10x10/16z] Oq02t2n0WfKJIF02COYa4F2oix033G4

sprite $DatabaseSm [12x12/16z] fOZ50S0m30CDPLtt7xSCoJkssEfZIizPLtoczU0IOa6XCpzxQwR8bY1minq

sprite $DatabaseMd [16x16/16z] nKwr0G0X34IZj_-wE5JVVznpuOCo01yITuhZGy9oVkVYpbCok3aqvPs7I__avUMqh5ZSSqONE9bfNTKE

sprite $DatabaseLg [20x20/16z] tKl50SGm34jYjkNznptcQnUeFkAnY-K987szaW8_b7JSXVDuG_K-Qtb7Zs6D5K1b0R76C_l0mJBATpAn7WfTninM_VMPQwtvq6S

!procedure Database($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2024/Resource/GeneralIcons/Database', $name, $tech, $desc)
!endprocedure

!procedure DatabaseCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$DatabaseLg>', 'GeneralIcons', $funcName, $content)
!endprocedure

!procedure DatabaseGroup($id, $name='Database', $tech='')
  IconGroupElement($id, 'GeneralIconsFamily', '<$DatabaseLg>', $name, $tech)
!endprocedure
