' definition of the Item simpleicons-7/T/Tether

sprite $TetherXs [10x10/16z] Oq02_130mC3C3-53XA047vY0S3aOEC4AeR8GpK04DmTk98W

sprite $TetherSm [12x12/16z] LS65OGC0402XQ-Fsx3zjNA4VEy1VPGutrCQk6meci69Cd0Z7TTj1OSAfYebZT-mSUcBVsxQR2m

sprite $TetherMd [16x16/16z] ROu50WCX40DpXiFy_xMLKEyDkXxzKzkJtJPlxcOdBnDO7SwQ0FSm7-_YwbAbKYj0W_qPxnqS7raw70xI-AW_TAEzx5scshOvAUGCcruKhErDHETS0G

sprite $TetherLg [20x20/16z] {
VSo53GD130NHVxYyqt-r8SlAyHEFGJV6BKiJMzPWQxKraXosoBRPueZv_vNQgSq2UlJM0q06nWmCmmejL42PhnAb8TcVGKhRVvQaoBR9X4sJM_4cRMDAbQwj
nNzjZVZMne2Ul04
}

!procedure Tether($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Tether', $name, $tech, $desc)
!endprocedure
