' definition of the Item simpleicons-7/T/Tistory

sprite $TistoryXs [10x10/16z] POgr0G0X0CJohf3zjwN2qvmI0M7vegAY-7CBIiTHibRBXExTBm4

sprite $TistorySm [12x12/16z] ROg50O0m4CI2Ezb_MbpRlfunre2mWL4pL7gj5LGg9GF8ZerAXm_smOCvgSe6adcT0LO

sprite $TistoryMd [16x16/16z] Os3ZPm02ACa7PF03cQnWafqV0XWPUC0aDqWKBCE8J08r8aWSW9K7IGfgFW90pKS0HcHvgCbu0HitcUO3

sprite $TistoryLg [20x20/16z] dSo53KD130JH-Npi_hlDhY3CJp3oWPb7nKeipgHn3W6S3HPb30yJX45rwjMx0Tdrq82a8ag12NCl-StcVNT2-lsPFJaxkDDzzATSL-w4t1-6VN6MhevE

!procedure Tistory($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Tistory', $name, $tech, $desc)
!endprocedure
