' definition of the Item simpleicons-7/T/Tmux

sprite $TmuxXs [10x10/16z] O-070aP-4A0oYvSJ1W

sprite $TmuxSm [12x12/16z] O-070KOGmSkFOFCJpsRW0m5aSLBPt0m8

sprite $TmuxMd [16x16/16z] O-3b1mD62CKEv4BvK40ZFWCKeClJci_EW0e

sprite $TmuxLg [20x20/16z] O-3YXm9668CPA0GNWuD1ASR020FyWzpDl9oOW9a10x

!procedure Tmux($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Tmux', $name, $tech)
!endprocedure
