' definition of the Item simpleicons-7/T/Treehouse

sprite $TreehouseXs [10x10/16z] Om01VY06qq00ehaX37ucg0Y8029s68i9f0OY1eRyO764OfWvh10Q

sprite $TreehouseSm [12x12/16z] 9Sor0GC14C0mXJdUVzgdSwNAG9YgHf-g9sSwebBlqud7-FQuq3WmFajEPIwzVusfUdDgWlcTi08

sprite $TreehouseMd [16x16/16z] JOw54G0X30Jl_T7hlreaCh1ZsJYKczWuE5XQkNkaa6VR2T20X9zugM5ealIQf7jDPNTlkDqFF4J-y7d_om0M7EA2twtwJdG_xFdaFqxEzQ8HXfqITG

sprite $TreehouseLg [20x20/16z] {
PSu56eGm30NXmUll_gTTI_8jykC3j2KapLoj-gYSoV3NF2s4AZU0NPgXA4o0NHNmfELtMJ7pgKrC1q0wDVKEm7HkCwQU_wLLvc7HsiwXWw49h3cGClklZKZ8
BQoF1lYNgvVaonyA5SBcYOjyMlaR
}

!procedure Treehouse($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/T/Treehouse', $name, $tech)
!endprocedure
