@startuml
sprite $MaterialsReplayLg [20x20/16z] {
bL150iD020osFit_NrjVhOOZCBfz6trTMNnTxOdMrMc7DtxPnGnFAvOq1thHaEnUlLZX5takJvlKIIXPfQANdQ2HCAGUVTtvbaPHMT2RS0Z2B06ZFOqe1N7k
YrY4QJis5m
}

!function MaterialsReplay($id, $name="Replay", $tech="")
  CloudElement($id, 'materials/Av/MaterialsReplay', $name, $tech)
!endfunction
!function MaterialsReplayCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsReplayLg>', 'Replay', $funcName, $content)
!endfunction
@enduml
