@startuml
sprite $MaterialsCallToActionLg [20x20/16z] lT0r0e0m343HVEgQ-vyMsN2O-hPALFx2dY14FObGpdS5wlcktlqRSrUr7sozL3yT-EtEoe7TxXm7ha9ivQ15xdRrrm8

sprite $MaterialsCallToActionMd [14x14/16z] dSwb0S104031PpZilzj47TWVjsvBLfkffI4RR4E3yLvY_ZhDd35sCNkqUynj-Ipx

!procedure MaterialsCallToAction($id, $name="Call To Action", $tech="")
  CloudElement($id, 'materials/Av/MaterialsCallToAction', $name, $tech)
!endprocedure
!procedure MaterialsCallToActionCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCallToActionMd>', 'Call To Action', $funcName, $content)
!endprocedure
@enduml
