@startuml
sprite $MaterialsSkipPreviousLg [20x20/16z] Ow0NO6U1q8mW6ihaP0FJJ1oSZ6XYBDpyQ6ACx7pyQ6BCNFpyXCGGUWdPWUaM1dPMk9lf1G

sprite $MaterialsSkipPreviousMd [14x14/16z] Oo05C391A0YFXGt4PcT1y9Wv-H4yLbv-D1w6IanJc60sa08

!procedure MaterialsSkipPrevious($id, $name="Skip Previous", $tech="")
  CloudElement($id, 'materials/Av/MaterialsSkipPrevious', $name, $tech)
!endprocedure
!procedure MaterialsSkipPreviousCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSkipPreviousMd>', 'Skip Previous', $funcName, $content)
!endprocedure
@enduml
