@startuml
sprite $MaterialsPlayCircleFilledLg [20x20/16z] {
VP253GH130CJBtF_rVuVetKZYWmBaGyKqBjWOscjH7lAY6CZOfVoECYhg75SY4lTpcFtQHFjhCL5WuQ-1kTgMJKHL-Ufg0ZQhecPxGQciIwvWxs5lPdyZUo0
xOhlbFC7
}

sprite $MaterialsPlayCircleFilledMd [14x14/16z] POw54S0m30F3ODn_sZBf-a6pmezKUw_fCghuXjJJy8lTJ5k4nX5DPwZ7AcUmxrO8cOy7BCp4BZW1fwCoP0K

!procedure MaterialsPlayCircleFilled($id, $name="Play Circle Filled", $tech="")
  CloudElement($id, 'materials/Av/MaterialsPlayCircleFilled', $name, $tech)
!endprocedure
!procedure MaterialsPlayCircleFilledCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPlayCircleFilledMd>', 'Play Circle Filled', $funcName, $content)
!endprocedure
@enduml
