@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2022/bootstrap')

' loads the Item which embeds the element AmazonMemoryDbForRedisCard
include('aws-q2-2022/Architecture/Database/AmazonMemoryDbForRedis')

' renders the element
AmazonMemoryDbForRedisCard('AmazonMemoryDbForRedisCard', 'Amazon Memory Db For Redis Card', 'an optional description')
@enduml