' definition of the Item simpleicons-6/O/Octanerender

sprite $OctanerenderXs [10x10/16z] POo50O0m4CGETxB_j53NlAiiemAGCctd837Wk3N15EREfnIRuPXNkZU67m

sprite $OctanerenderSm [12x12/16z] FOo30GGm5CLUxMR_QGzLlgc5rMFoqeZJeWUn2ShilFndW6HWBQq0QNynIcjQ1mjXLG0wNSLe0Nhiz0i

sprite $OctanerenderMd [16x16/16z] LSz50eKm303HQHiSClS_xLVqRQenTfK7BTmi9ZTLeKK568Nq0DKDTvc0faQPZfIZ6a0U5_utayfNqHbGRNo5vgIk2iN3IWfjLSrL6sNaeCcTSZSSyxq1

sprite $OctanerenderLg [20x20/16z] {
ZP350KDH3CFy7xFsdxQKCkiK1kkAqmkBz1m2daC5ojkot5hUTC0pfCuTac0JTmnhYy3i05wovei3D1a0ys9LYqMWNs9i5cp0TSgGKG4BOTcKoWHZUlk7Eu8I
I5jR08nXVJte1f3_KAkzXfJn5tCF
}

!procedure Octanerender($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Octanerender', $name, $tech)
!endprocedure
