' definition of the Item simpleicons-6/O/Ohdear

sprite $OhdearXs [10x10/16z] Oo06y4CfVY3YX_21D3Cd9oU41GAC85disW4

sprite $OhdearSm [12x12/16z] bOR50S0W00Elxit-qrRXWnCzAZICFcyIWoIWEq73md6UfuQNHpPuOJyiCtRGF8xe1W

sprite $OhdearMd [16x16/16z] hOi30W1124MdMklT_xHhMxaFzryG7F_DIPZ6tPS1XOCScjUQYK_DqaNzvrdZd_71-DV-el6FlzFGwY5rkuTH0G

sprite $OhdearLg [20x20/16z] lSZL0KCX5C3GFCCX-qzRry_gGM_uEyCRBQWJU7H9pLPqGMDmSBGOWI5cMBm0Y680p4VD2SXU6Xmv9ZRxKvjK1qyDjhW0ytIy-B8z

!procedure Ohdear($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Ohdear', $name, $tech)
!endprocedure
