' definition of the Item simpleicons-6/O/Oneplus

sprite $OneplusXs [10x10/16z] Ou02VWO4Yny8e2H23Ag65KJoWbXCS35-P1P21nS4y3C

sprite $OneplusSm [12x12/16z] POo30S0m44L_6tl_QMFddOc14TZpK06lGPCCFc8L2Mhjr3oWK7DNyW-hltRUVFyp4KW

sprite $OneplusMd [16x16/16z] dOk35S1G00ElThF_jBNnTKyX5ng1oRS2hLnKiW19qavQklzN7_KtNnwhrNVzkeetJw5r7-hXtr-14G

sprite $OneplusLg [20x20/16z] jOm30i0m40GtTkx_hwrjJXlT0dC2CU3gp0qqzqpUEHe0nhle0AejaXA2QDtNpwHSpxfJgE4UQUWOPYbrCyQnojPzFyrgpcP-Icvc2-fP2G

!procedure Oneplus($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Oneplus', $name, $tech)
!endprocedure
