' definition of the Item simpleicons-6/O/Onnx

sprite $OnnxXs [10x10/16z] 1S670S0W00CWkjoQ_xyj082G0kzXwV1SG75XI0M23vGSzuqxi1o-1ybwXHy

sprite $OnnxSm [12x12/16z] 1S610G0H402Wm3t0_jj-GGN0ocUa15OYhmT1VBG6BqCgd38xq3-cJEBO0gawNLRWba11Rrt1I0jrWXpphfdu0G

sprite $OnnxMd [16x16/16z] {
LSgtOGLH200m0PVX_jj_MrTEgWN2V-zypl1Z7wXt0Ou3U-i08zpdppjD5qY9cXbGZ5oxnmixwZnv6DnONavSeSMKO8EgldBG4XnB1ew4w_PeqB8tz06iJu7d
yYFoV5RX2m
}

sprite $OnnxLg [20x20/16z] {
5Sd5WG0n400WuhgP_gizuGkW002mOlSC00YOyVK3u3oWdm2evS6-p0MahSfxG5i9NBr40h8DCzSuWCP0wizE6zW8CmPRlY1GwhZO-20WB4oucKF_cjJeODD5
UWWAC6PV9kIS4v0Zc60FCCz_Vi2wf3UWbGAacAS2wm34YxYp8Z808DSH6Nu1
}

!procedure Onnx($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Onnx', $name, $tech)
!endprocedure
