' definition of the Item simpleicons-6/O/Opentelemetry

sprite $OpentelemetryXs [10x10/16z] Ou00VWOeuEA7CVbveKn-VY0JncA5AcTcW8amSCCOO4MipFpePW8

sprite $OpentelemetrySm [12x12/16z] HSh70S0m2CNGdzwZ_QTr1tInWQVH9c-2-3y-dEmsd507qqOUj0nymozKEoe-1m437_AGbm4

sprite $OpentelemetryMd [16x16/16z] LSZ50GDH58LGnltJVxNH6tdi3lowA3KjFYnZhcFLBYDyZzXNR646gNU7ZX_TbklSmq4TX1QhRkX0qWDIXnShtqQTI1c5Tm

sprite $OpentelemetryLg [20x20/16z] {
PSo53KGn30HHXpdJVxN74FkF-6crea8kmRBK0ImExB8Y2q0HKo-V1CWwXebdhsMKR_0goR_Ww6Km3deDWXmv80KcQWL2bZOKuUTmAnkJpJplddIM24xJMj35
j5zaiLcv0m
}

!procedure Opentelemetry($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Opentelemetry', $name, $tech)
!endprocedure
