' definition of the Item simpleicons-6/O/Openaccess

sprite $OpenaccessXs [10x10/16z] BScr0SG0000XtYLo-qyRfmNk0UhT24BWWO0g49-Wb_H47Xa6rmIg9bO

sprite $OpenaccessSm [12x12/16z] FSU75O103CDGqJlQVrkU0znFDJ7Ryz5RAMUk8-6SjTDuK6xr-nMw_uU1GI3xTgB-JhepExopJefQ-G4

sprite $OpenaccessMd [16x16/16z] HS-50GGX34JH1FVVVxKdwAp0mv6LIfINp3_cq35431oFMRDtokwXRAikLpdnVJHzPkOQylnlEz9RTfvj3V7OwJuznEAc4qP2Kydej39MmRjEyetPFHE0pIy

sprite $OpenaccessLg [20x20/16z] {
NP052aH134F7jJkv_ssNaTBm7nBgeUuH17qhiR0PdDfnMO1OgcDjIK2WjdHKq2XtjT766AzMp2sKzv-SO2EK2r0iXtkaKgxgtGnOMzw-upLgziAPdvYKYvQZ
MKasIpSAGDzRyTRi1nwFdoC6DkK6Vm
}

!procedure Openaccess($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Openaccess', $name, $tech)
!endprocedure
