' definition of the Item simpleicons-6/O/Openstack

sprite $OpenstackXs [10x10/16z] Os270NxiW044iBEukBZ0B2ukX1W2yC5P

sprite $OpenstackSm [12x12/16z] Os270rO-Vfo00GpOG0m4W8ip0Laus6niR10s8niRK9o33GHuK0tdHc83

sprite $OpenstackMd [16x16/16z] Os1bHmOCNFoa0mOeO0EomOP00IEGpG44S3wGZQoU2SWcn6T00zZKSx1100yHRcL6umC

sprite $OpenstackLg [20x20/16z] Os1YHmSCRFmq00nmm8P5Z0d2nGJOr54YnWK2235649SH193i175nciV11WCyf7YV3uiO8wOG3m

!procedure Openstack($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Openstack', $name, $tech)
!endprocedure
