' definition of the Item simpleicons-6/O/Org

sprite $OrgXs [10x10/16z] Ou007WOCm0-Z-VcXD0i_200P8C3E1HA2IC9Ow4nE9h0n

sprite $OrgSm [12x12/16z] RSY50O0m3031nvtVVrfSsruy9Cmyik9vZdAgPcrjonpKqGFgf0xr1EUNWuFFNar-3Zy7sLuZh

sprite $OrgMd [16x16/16z] VOo55G0n24CvDnxPVzkhU_bL80bb3gfvrP9G5OmdL-i10ySPO6hFvKgmhyHa20ml3EVvtMxiv9JT9ugQGzYM6vutEvg607nUaYsnRyuF

sprite $OrgLg [20x20/16z] {
RO-50S0W3C0wtFF_jNE7uC5Q-L2amvZUqIlTNmsudwW5VjVOUKJ8D205Q3ddJR5Xk36dmf-YnYXoBDpUD-zIsTBPJrLWkhFOdFrzci2qdzFFyu-iZWjro-FS
xteUoId6_PebIa_QkWK
}

!procedure Org($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/O/Org', $name, $tech)
!endprocedure
