' definition of the Item simpleicons-14/T/Taipy

sprite $TaipyXs [10x10/16z] Oy06-6601yu2Ya8f51OZ8oD24oeB0G

sprite $TaipySm [12x12/16z] Oy05-140cStE2GTiG5MS836u3WIR5mZOaCo2CpcGs3oyh1ZM0W

sprite $TaipyMd [16x16/16z] Oo0LyAC2T3ulAfSLcn4yO2a-D2DPO5n629-08vZG-CXSBfZfX04

sprite $TaipyLg [20x20/16z] fOs50O0m40E3E-m_BL1tl-fRWXR6om6FYoTtd6wkH-S0oiGxPitxvhbEoqb3nSPJEpGqRPtZE1RoMkDsZZiaSttVevWF

!procedure Taipy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/T/Taipy', $name, $tech, $desc)
!endprocedure
