' definition of the Item simpleicons-6/T/Thewashingtonpost

sprite $ThewashingtonpostXs [10x10/16z] NOQ50G0X00Bvj6N_QUqc3rCyw884iszQTX9KWr2T2Ju3xOyg2an5

sprite $ThewashingtonpostSm [12x12/16z] LKs50S0m369rv_zlLvUu0cxvhffthVcLM9CaQ2n1f0n-DBhMWdNbH_sbMcFKwBMc8b5lM314rVcMv5xw7m

sprite $ThewashingtonpostMd [16x16/16z] POx50GGn30CLvap_rHuiWtwsK2-O-zaUDFslC8TmOCc6fa2mJ5LCnpKaclVyRWLCMcuhCllDSfS7h-TTQ96PiXnjMgI64a5_FvXZirdqLp3kTvVU-08

sprite $ThewashingtonpostLg [20x20/16z] {
ZSi5ZWGn5CHGTnJOtYJVzp_jCBD5fISLF-SppHUcXGmKW0NuW-geJbOxXANkHrPKDATc7oZPGR4pp1HdGrclbhJlhNirvz7MVBLKZiQDSRMW60ovsA8sjKFM
hWuW0XJmtpwit7Ryyekb-cIyRGi
}

!procedure Thewashingtonpost($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/T/Thewashingtonpost', $name, $tech)
!endprocedure
