' definition of the Item simpleicons-6/T/Tomorrowland

sprite $TomorrowlandXs [10x10/16z] 5SQ50OG040F1lE9C_zroyKsrJAiD-_nxvbeYmQRRUYjzq8hmSqH-Rq96Ijk_-7UPUm

sprite $TomorrowlandSm [12x12/16z] BSe50G0W40J1nPthtnOTv9KhyHahJSFH9wqDCpfKjO3sbK6RbPFKcThGvXWtI6e9OQGWWT_dxrXWlZnNjXajnNUk_3SM

sprite $TomorrowlandMd [16x16/16z] {
JSs50O0m34JH7-fw-q-BsqCRvPRuCwdncihEkQPax6hDz22hL2rtQIrY80cgThQtfFE7feFlGzSPdPuFQT71wR10u6m9aY8PB72qklCyW6blFnLmMT8ypdbo
IAN9o8hN4PmIM3kFbtBjscq
}

sprite $TomorrowlandLg [20x20/16z] {
NSc5OG0W4CNGuCxVVzl2KNzuu5lXFxVL-AqtcTazJqNTrJv7Y7iug_uK5dsbal0IXwJ1Y4kfnPFK8EXoJH9L5sIPbkMt37WznKiFi6GsUZo4C6M2J1BuHjhl
SGmGjfmrIzzDbtriIW9IzJeMkX3NibQnVKQCReGYjPxXcJrvJamxyIrBUvt57_MKoFC1
}

!procedure Tomorrowland($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/T/Tomorrowland', $name, $tech)
!endprocedure
