@startuml
sprite $AzureDevtestLabsLg [20x20/16z] {
PSr70W0X24DHL229zp_mCBtzbJuBTZII8hez2agQKtwJQwCdTkvKiTM-1KXTDaSHf5kgCCkJa02ecMOyIE6UcMNDheVqo6GTSk0qRRQlz3TpxiZBqgoxnrfP
5J7ihFjc1LVDtREATbileSZqnxK4rv7CVje8G2eJuheMaTZBSGtroBso1G
}

sprite $AzureDevtestLabsMd [14x14/16z] JKs53S0m34l9aFyFNb5Q6ErOKccphMeriZEzsx8sEKMpXkJJPGrurQBaRB6RP1zGefmpZu6PrF-Tem4avYLvAKllm2YFVctGugwudd2MRN11iz-lWIKZFW

!procedure AzureDevtestLabs($id, $name="Devtest Labs", $tech="")
  CloudElement($id, 'azure/DevopsServiceColor/AzureDevtestLabs', $name, $tech)
!endprocedure
!procedure AzureDevtestLabsCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureDevtestLabsMd>', 'Devtest Labs', $funcName, $content)
!endprocedure
@enduml
