' definition of the Item simpleicons-8/C/Cloudways

sprite $CloudwaysXs [10x10/16z] Oo00E3av-O40o0AIO1OVa80okJYve2ouF3Op

sprite $CloudwaysSm [12x12/16z] Oo0EC0C17pydZCiF120EEpixFnW09H40f88FYSq4PtD30HTEYm

sprite $CloudwaysMd [16x16/16z] fS750O0m0C30u4xsdnRN7xHtn4kpLQSDksJXgcUHzIit71eF-UWRgznBekADpUXX0BfRnbyp

sprite $CloudwaysLg [20x20/16z] lSl50S1G309GldlOVzgwzrXvjmJ0JymiaKnOf0bdE32SMOnu8bXfxgpm3hFpB-USaCy_Ouo6aTFlFbO0V3bAU5qF

!procedure Cloudways($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/C/Cloudways', $name, $tech, $desc)
!endprocedure
