' definition of the Item azure-19/Item/Other/ServiceAzureA

sprite $ServiceAzureAXs [10x10/16z] JSP50G0n40ImEUYoVxjboYkuUKhf7miYQddSvxmlZO6OWRUDsshCwWXcXbRfWub80G

sprite $ServiceAzureASm [12x12/16z] NOfL0e0W44J7shx_UTtwuYamXOFuaf6FyqSqsZs8w5tjb9HyKt-hFG4nlwCDdFJ4pAIrUPlKX7mLfKLA8rj9VW

sprite $ServiceAzureAMd [16x16/16z] RSe74iD024DHjWc2zlxdZKYFxJ_rQMHNCPOQNsyHUDEveJucUIlFhtyFJlLZLgCylpR0tJ_tPTBJKkQSAA-trUiGLFvrAjfy3W5PcVNCg2oKgHOAwmu

sprite $ServiceAzureALg [20x20/16z] {
TStN0S0W24NHPqTW_ta3fBVxbHmLy5ldxjMhYRReWacKJUpcQIIYBbSJit6VcCJYVhl8RdetYLPhvrChXOrZgqLm6UFwDA4DBpRdrO0qedqhHwU9Tx4E59RN
HLh_C7UZ18uI76cGrJQ3HJmfGieMelXC2Gi
}

!procedure ServiceAzureA($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure-19/Item/Other/ServiceAzureA', $name, $tech, $desc)
!endprocedure

!procedure ServiceAzureACard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceAzureALg>', 'Other', $funcName, $content)
!endprocedure

!procedure ServiceAzureAGroup($id, $name='Service Azure A', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceAzureALg>', $name, $tech)
!endprocedure
