' definition of the Item simpleicons-14/E/Envato

sprite $EnvatoXs [10x10/16z] JOgr0S0m40ELhsAy_QSrqpL23JwlYS5gs0vicm1k69urh_ykwHLwg

sprite $EnvatoSm [12x12/16z] ROg50S0m3CCqvkd_QyVOLk7ONCY3-bcxTosIXftFMkvxLZ8_fbnj9rkW_lWppM7cfihslW8

sprite $EnvatoMd [16x16/16z] LOs50G0n30AhxuJzftrlvAenICgAv15IOaXQY2Si6XvQrN2FOStzW8O_-OqrRB-LB7aFUkME4FH-t7pKEtfgJ84ZH93llG

sprite $EnvatoLg [20x20/16z] {
PS_L0KKX30FGu4xsd_R9LMZF7zInCBD2S2GxDfP_AeiSMoyUT671YdzMPSsZnPxLrdBBHSIXy-LnIkIihXqjDrHVvMXlh2jjlu7habm4h7ype1EtF9ix5XYG
F9H1NBu
}

!procedure Envato($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/E/Envato', $name, $tech, $desc)
!endprocedure
