' definition of the Item simpleicons-14/G/Gatling

sprite $GatlingXs [10x10/16z] XS450S0m0C2mdZ-iVxSJC4hO4hn0pw1O451F2L8K1Vu4CJ3I

sprite $GatlingSm [12x12/16z] ZS750GD100GWpcLb-gys_eo1VwnJQHYy15b8qh8YfBCcgOapJP_dIS0Kb1DdUwXbzy4L

sprite $GatlingMd [16x16/16z] fSl50GCn40Gm7ODX-gysd7z0nYN_6lQfPCA0zvqTQnQeVJ7aPh_Tz3nitFyaAt9NpyGMo0Gj65UMvqZYOSu0EM4kxQMMS_QbAm

sprite $GatlingLg [20x20/16z] {
lSl5WGGn34JHCZN9sfz_jjirV1zuHf5-OXqjE6H5hy1tWoPPhKvcEobOdULKwuuvIca3_ZAJNRPvEa06DYk4EY5Zo0PTqex74fDytJIETbBdg997j16oWrrM
zfbtSyQnDttOFm
}

!procedure Gatling($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Gatling', $name, $tech, $desc)
!endprocedure
