' definition of the Item simpleicons-14/G/Gimp

sprite $GimpXs [10x10/16z] VSJ50S8004MnXplPVrge7vilxJYfF8lnEtJ5rJD13_YYZDBeGsdp1m

sprite $GimpSm [12x12/16z] RSR50SD00C0m1ux1-qzRvaOlSMpzgC1S0Bgo8Is3EcZRc9YgHdkj4vtAujNQLV1k5w0wOfW4FiY7Cm

sprite $GimpMd [16x16/16z] {
VS_L0SCm34NHPsRT_QSjSvESFrkiO_7xwVZwzDpULk_FoVsDzP7lJxogfdoGK-CgatoQGopQxKdfmgk10UeJUiQa2YnfyUGUxHzIm-kgGysveXTNMhl6uESS
zECC
}

sprite $GimpLg [20x20/16z] {
ZSm55WCX00FHuCxS_xOjfUv_5y-B_cFqYjSK-wxeoi6-c_qIwbpkWBgQAoToVhTE8siDIvMcifAnib5qbZ7nLc1LW3M8Ari5GHQO06faI78a6PS0ibIuc3kd
eycDMIKB5rs1gAq2ASRGXkIDjFa1K7QJdbdGgoAzEW
}

!procedure Gimp($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Gimp', $name, $tech, $desc)
!endprocedure
