' definition of the Item simpleicons-14/G/Googlenearby

sprite $GooglenearbyXs [10x10/16z] DSZ54G1020D0_bZ_rPv4q9t4hmdLxXf_21303h357EZu93u14BW

sprite $GooglenearbySm [12x12/16z] HOk54G0n20JVDT9_jTWoKJXTuhHbdDxxXFuICfXtXmG4j9XEDbh0Gj3XdsKW19Ya-58

sprite $GooglenearbyMd [16x16/16z] JSe54iHG20JHterht_-qKQWmNzyKH7PgVchXNpUjR5Yr4XPD_kdDugSDWsQX_uSAg-vku9CT55t1v1fNS85uFiP4C8ja5i4wyUG4

sprite $GooglenearbyLg [20x20/16z] PSo54OK040FHVC4b_LUBaqKo_cRlTAuOzLnb-qr1QFY071v89GMfofIfIiwf31QfmD7-I3xMIwqj6smtwdGWrI05gK0ga0ga0jljunsfG7xD

!procedure Googlenearby($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Googlenearby', $name, $tech, $desc)
!endprocedure
