' definition of the Item simpleicons-14/G/Grocy

sprite $GrocyXs [10x10/16z] HKo30G1047eR-q_xE1kL-TPtWRx1U919VhwquVzKnYiHRgdldKqcHX5kKxqB

sprite $GrocySm [12x12/16z] JSc55G0X30JHFHUi_sgH-63_4L2f9GOQ5KYkmVHov-Jzrhe-qZGo3ScNU5_F1Z8QnTw3iIa7

sprite $GrocyMd [16x16/16z] NS-54O1044FHu4xwhnRBoh1_ZCSvh8td0g-bsiI5bcQCzARFZDgNgmrvXRBDOdWlFluUxSFDVQ5vfcL6DPAzFLPQ0Tm

sprite $GrocyLg [20x20/16z] {
PSe73i0m24DHToT0m_rFsrs6yhMi9-DlP5Kf21NzCrBFg3VjhKHg-GPlUeKG-b_JMYgnjCbi1-dRR5OWdorcRBQQATRAxHwR6m6WtpRD5TZHgkYFX3lHs8md
3ZJWQ_YkCkBg1
}

!procedure Grocy($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Grocy', $name, $tech, $desc)
!endprocedure
