' definition of the Item simpleicons-14/G/Gstreamer

sprite $GstreamerXs [10x10/16z] Oo0MS3126MpyhDnSh4pyV7mC33n4QGK

sprite $GstreamerSm [12x12/16z] Ow08SC9PRFnitEmih8oilApCG2u78nC30n0paceY

sprite $GstreamerMd [16x16/16z] jSYr0S103C309pFjlstI1Nghqutk2F07QQz3hsLe0SuOIdhJ95RbnI88CPgx

sprite $GstreamerLg [20x20/16z] pKZL0OD033sDo_xJji0FEi0bpylgroZhnogyoMK0Jfkg836bQNfm-B736BLRIr49RRHlXcNP-mC

!procedure Gstreamer($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Gstreamer', $name, $tech, $desc)
!endprocedure
