@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2022/bootstrap')

' loads the Item which embeds the element AmazonEc2H1InstanceGroup
include('aws-q1-2022/Resource/Compute/AmazonEc2H1Instance')

' renders the element
AmazonEc2H1InstanceGroup('AmazonEc2H1InstanceGroup', 'Amazon Ec2 H1 Instance Group', 'an optional tech label') {
    note as note
        the content of the group
    end note
}
@enduml