@startuml
sprite $MaterialsRadioButtonUncheckedLg [20x20/16z] {
VL055eKm3FkLIVRQ-n_t6mw1-Qf9NWz3LELeS4Hcm3Up8fkRUKleOXgmwMKOar60DKNG_szFsofR-k_gRT-kzLzu-DxcyKtMANLBLcPZkRG7noBzY9bpunfi
MdKNekdz-
}

!function MaterialsRadioButtonUnchecked($id, $name="Radio Button Unchecked", $tech="")
  CloudElement($id, 'materials/Toggle/MaterialsRadioButtonUnchecked', $name, $tech)
!endfunction
!function MaterialsRadioButtonUncheckedCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsRadioButtonUncheckedLg>', 'Radio Button Unchecked', $funcName, $content)
!endfunction
@enduml
