' definition of the Item aws-20210131/Architecture/Analytics/AmazonKinesisVideoStreams

sprite $AmazonKinesisVideoStreamsXs [10x10/16z] BSR70S0m24MnD7XyU_zzOufEqX47LAfBuTqbtCoTd7r7Bn5Ru1Xexu3PaixZxFoGVW

sprite $AmazonKinesisVideoStreamsSm [12x12/16z] DOgr0S0m40D3B_B--yPuZT0TJSXfTuXDxfW8uFOcK8FLrzSvlhugp0y1Wjst6VG1SckHUkBmFSJgkFiU9lOF

sprite $AmazonKinesisVideoStreamsMd [16x16/16z] JSk53KDH34FHaYbl_tsRVBRmNCcP-PYa7E5fwmurndsfYadwQP00kceiQlZhRIvpmzCTvk5sqsIZW-nL2IM4j1YlLHRR-AgTrI4CB9bgJt2PCuydx4iEFy8V

sprite $AmazonKinesisVideoStreamsLg [20x20/16z] {
NSf1KaGn30DH0CkIykz_NvI4CipqybNxf8d9W--cbtCTmy6nWw2jQGNPB5qSKwaBJOwvnKYZTdq_LlF8M5Ba-_lL74lOyHh1XFdqhDKMcYLH8hO53P6mlYjc
wmbkqJN57Ci96JPb_bgmlL2er6CxJv7HtTWR_W
}

!procedure AmazonKinesisVideoStreams($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Architecture/Analytics/AmazonKinesisVideoStreams', $name, $tech)
!endprocedure

!procedure AmazonKinesisVideoStreamsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonKinesisVideoStreamsMd>', 'Analytics', $funcName, $content)
!endprocedure

!procedure AmazonKinesisVideoStreamsGroup($id, $name='Amazon Kinesis Video Streams', $tech='')
  IconGroupElement($id, 'AnalyticsFamily', '<$AmazonKinesisVideoStreamsMd>', $name, $tech)
!endprocedure
