' definition of the Item simpleicons-14/A/Airbnb

sprite $AirbnbXs [10x10/16z] DOk33K1H5CKQVAFxR_joxGCYfEEUqtmYZk55FoxW13uaweYnyyTpnHYtE6C1

sprite $AirbnbSm [12x12/16z] 9SZ50GHH0CBGD_wT_gjTlK0Ii0V0-GX0i81hnm02bdzEZG7_suNZqBYP14imJRIn8HPA8EeurYDzZpS

sprite $AirbnbMd [16x16/16z] JKk50G0X4CBEa_sd_U9RfQ6lCUBtSGQsJoOxlLUAbl76K-u_Lk6DRNNvYXam3FKgH8EtsuRGKTYEaL_YmOHq1xQXxin2S8uJ76zTJv2k1tPgnt1SBXg43Ji

sprite $AirbnbLg [20x20/16z] {
LL073aKX37hkBVU_xPV6cb_SIe7uAGRAP-6nEc3lq3dL_wiib0X3Ayf-I4Amn6U9PjISDqJISB0UKHxdOiRuY8mbspKqOy2dTrqZYCGkt0LEcIgQCBpTt5TK
FU7P2OVxo2TDsU7qZic8YebFQvt8BBZxqu0e7KonvExa_W4
}

!procedure Airbnb($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Airbnb', $name, $tech, $desc)
!endprocedure
