' definition of the Item simpleicons-14/A/Arduino

sprite $ArduinoXs [10x10/16z] Oy0FUFdveGGt0mC_7nkGu0SX8EJc0f8C_CmW0YmC9J01

sprite $ArduinoSm [12x12/16z] ZKd50S0W44kBQ_QV5eVtMHIY-TH3CZ0j3BeiRw47_ex387C0CMIk4v4ukeKV1DC1

sprite $ArduinoMd [16x16/16z] fON50SKm08Men8Nzf_qklUS9i9xzk7fNdN1yR05qDmFEAW1QeR3fH1DDq0s309iAWI0AsOxk91CCDG3zvTNS0G

sprite $ArduinoLg [20x20/16z] lSY5aOHG0C3G0Dyj_LTxjsu5aB4tuQJsO_lHLFL31yE-RraFbkEc3JlNT9dkcbtkQOFGOAcWNhcnQwTPv5RH1Ni1HUzh7NTL2q57Lo7UjG1KCzVMNMVq3m

!procedure Arduino($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Arduino', $name, $tech, $desc)
!endprocedure
