' definition of the Item simpleicons-14/A/Azuredataexplorer

sprite $AzuredataexplorerXs [10x10/16z] BSe54i1024FHaEeO__wtRM2w0WzHpt6-Ni0KA7GyKk52qNI3Y2L7OC833Le5Yrtu4Nu

sprite $AzuredataexplorerSm [12x12/16z] BOo54SCm40JNR8ks_supznFX7x9gKS-ZYYilTqPfcRdHLyaSfVtdBna-5-I-wfeuwI-FixjFci3LbHhTghfdlAkjnekivmS

sprite $AzuredataexplorerMd [16x16/16z] {
HSq5WWD144BHF-vLzx_j3h19sXzjF9KoP69hbw4omwffh2vksS7uQDangpZer6spT1-yPedpXWS3_NAp_xD0Qp_vyW6TC3li0LQnCKTMeELmqx7L3WiS_9ZW
U8cPu0y
}

sprite $AzuredataexplorerLg [20x20/16z] {
HSy73WCW34DHi-d2zxzjYUEgqK9VZuLrVhEg5nZqx4OFi9qgUOeRffM06xPKJBKBcUhu26XA61IPR3upBtkv5H--jNq1eIqRhbfTwG2MDpKwjI8PYioK3zXI
v5FA1yzG9FPLIgS0_Y-itl-_I-shbF9sDAMNawJFocJPG-6jvAbV
}

!procedure Azuredataexplorer($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Azuredataexplorer', $name, $tech, $desc)
!endprocedure
