' definition of the Item aws-20210131/Resource/Analytics/AwsGlueDataBrew

sprite $AwsGlueDataBrewXs [10x10/16z] PSQ53S0m300mbwla_tl7mbbaVvMSoAmisL0fYA5YAlLTo5fgXIv4zScgVlO9

sprite $AwsGlueDataBrewSm [12x12/16z] JS770KCn20KmWN_pO_zzSqcJ_BlwOzGgq7SKOSeHrPSCrmuAsK_7waLbxmvcJ78d2gb6r3C7Pa-KZvXyp0i

sprite $AwsGlueDataBrewMd [16x16/16z] {
NSx7GGKm30JHSPPs--yN6VXnRizHV6UzDn6lEaQHkrsq7Mvbu1o83SdrKXihElJUJLuZ8azqcRsf1YA3iiqOqCfvNRaMGifKMT3rlm6_ffNS7lE4DzLsFkPv
57oQqlHRuWS
}

sprite $AwsGlueDataBrewLg [20x20/16z] {
RP05OaGX4CM2ZRtxtxTVAtI31ny-CRLH83QwxKwtasIt24drhbjgi6g0skrS84RyFa_BQE6qHfGETz0245Qr0Z-SQS21Otq-hd26WRNJvUMQGIunpInMMXuk
0PM1Mk_jAE_xEZcdRt_J12-WRXUfQ1oChAFx8GRzl-iShlf6JB2DoHS
}

!procedure AwsGlueDataBrew($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'aws-20210131/Resource/Analytics/AwsGlueDataBrew', $name, $tech)
!endprocedure

!procedure AwsGlueDataBrewCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsGlueDataBrewMd>', 'Analytics', $funcName, $content)
!endprocedure

!procedure AwsGlueDataBrewGroup($id, $name='Aws Glue Data Brew', $tech='')
  IconGroupElement($id, 'AnalyticsFamily', '<$AwsGlueDataBrewMd>', $name, $tech)
!endprocedure
