@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://github.com/tmorin/plantuml-libs/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q3-2021/bootstrap')

' loads the Item which embeds the element AmazonDynamoDbAttributesCard
include('aws-q3-2021/Resource/Database/AmazonDynamoDbAttributes')

' renders the element
AmazonDynamoDbAttributesCard('AmazonDynamoDbAttributesCard', 'Amazon Dynamo Db Attributes Card', 'an optional description')
@enduml