' definition of the Item simpleicons-14/I/Interactiondesignfoundation

sprite $InteractiondesignfoundationXs [10x10/16z] BS650OGm00ImL73Qst_QLn8unkhhNAfM3ivEM1SBIouStH0PvP8beoPjOSzzHFSLNqVl7ek_Dm

sprite $InteractiondesignfoundationSm [12x12/16z] DOd50GH13CFaP9ZIVxK72_eO1C3SZPSaerxDe80BS6PuAtYxNXzB1XCeXEBWCqKRQtliuIqHe_XimOLnxf9TqfHG0H1M4bUjjuSl

sprite $InteractiondesignfoundationMd [16x16/16z] {
3SA75SCm40KWlfhbUljlc_00nlFU0N1ArrX0Ca1tG3fM8GvEFADwtJHXqlhpzTlMvennrjfLAfgdipo-PfIufzgxjVTSzHOtgeqknpuHnFYgtPaw1YYGRP9a
tabqMFJ87nEMblp713B0XXy
}

sprite $InteractiondesignfoundationLg [20x20/16z] {
HSlNeUqW300m6Kmx8TVxJ_jwqR_ySTxtJlxB3bZXZu-XDQqB1qZD7wrRy97mL2AcGUgilBT_-Q05RK2CAi_ZIfFqoPgdtNKbUfv8uZtUMghEAzm8hbbsxEwI
dl3M7gtQUrlLMz4zY6VqVUoOVOPfGErUNxTErai64xRx5G9C4x0Bw9hGn0_xwH4XB1mf-UFVT_eoSiyG3HZ-MVuP7M8qy1q
}

!procedure Interactiondesignfoundation($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/I/Interactiondesignfoundation', $name, $tech, $desc)
!endprocedure
