@startuml
sprite $MaterialsPermMediaLg [20x20/16z] {
TSY50S0m30D1oM7q_jkMkRcW7mEoUYHJUfjvuk9q4zr6jlQGajtQWnkt5kkd1SvFp-tM4e6WKVpLgW70860wMhSuIDbRTVQKzlPKvyQGxgATsmC9Q927EI7K
zk0maoVYtmG
}

sprite $MaterialsPermMediaMd [14x14/16z] NSV50O1040ImMSVflrhqFBzWmF6GF3iVgzj3v5sshVGk-xRxV9v7deEtiFtVH80Gx9_nHzPdUkx9kQu4qOmtvOm0ZK8nk04

!function MaterialsPermMedia($id, $name="Perm Media", $tech="")
  CloudElement($id, 'materials/Action/MaterialsPermMedia', $name, $tech)
!endfunction
!function MaterialsPermMediaCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPermMediaMd>', 'Perm Media', $funcName, $content)
!endfunction
@enduml
