@startuml
sprite $MaterialsSettingsBackupRestoreLg [20x20/16z] {
bP254OKm44Hp6a_wh_RBuZ36GkpDUNWdObMc2x7IM-l5w42fkp2BzqGxgX8WgHkq1WJOR34hVaJs0aFkC5E5OMSy6l_tEV-Gss-Nt4QDT68mcvaVleaVEGBs
QotGKVFHtBKtw343MB9WLg_q1G
}

sprite $MaterialsSettingsBackupRestoreMd [14x14/16z] POw30G0m30G_jVSVj_OLCV13ZD4of2d8OMZD0APrZ-ZXh54oh7m4C5C_MpvZK3u6RfEcPK5OXiB81E7eKk37X9Ayfk_DVZ8

!function MaterialsSettingsBackupRestore($id, $name="Settings Backup Restore", $tech="")
  CloudElement($id, 'materials/Action/MaterialsSettingsBackupRestore', $name, $tech)
!endfunction
!function MaterialsSettingsBackupRestoreCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSettingsBackupRestoreMd>', 'Settings Backup Restore', $funcName, $content)
!endfunction
@enduml
