@startuml
sprite $MaterialsGTranslateLg [20x20/16z] {
RSu55e0W44NH-LCqx7-rTX-VVLM0VWEluKMnjzQ6FetRM8juMj-ikcsvRbPTnAjXptYngWGWE-tfQe6qvDWIY2ypIecPetioazD2Lb2CpEhOBG5cu59i6t-p
7jTp72r4ezD6YR6CqMFIsuuIJ0-hfsMGOZFIi5L6FzTtPSFfQvnDrnpqm3tGRpC
}

!function MaterialsGTranslate($id, $name="G Translate", $tech="")
  CloudElement($id, 'materials/Action/MaterialsGTranslate', $name, $tech)
!endfunction
!function MaterialsGTranslateCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsGTranslateLg>', 'G Translate', $funcName, $content)
!endfunction
@enduml
