@startuml
sprite $MaterialsTurnedInNotLg [20x20/16z] rOg53S10202Byxx_j7MD4-_X5wO8n2TqA-crxDGkbpD7s46ts_rW0nRuE2SjjHObVzneMH0bj_4uPzWcyFEtYcSDi

sprite $MaterialsTurnedInNotMd [14x14/16z] jOV50G0n3CF2iF_0nrZwLG5RK89qWATv7FWX63WZK0HlIm-py3pDTKjKHnYo0W

!procedure MaterialsTurnedInNot($id, $name="Turned In Not", $tech="")
  CloudElement($id, 'materials/Action/MaterialsTurnedInNot', $name, $tech)
!endprocedure
!procedure MaterialsTurnedInNotCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsTurnedInNotMd>', 'Turned In Not', $funcName, $content)
!endprocedure
@enduml
