@startuml
sprite $MaterialsPermPhoneMsgLg [20x20/16z] {
ZSv50WGX34JHAX9SSl_RphG2ktxuNu7FAAe2GFJ4eucP5GB5JlgqnhsvRZPaRwp7RM-8Peb76xtteJZecL2gkZ_Ym1AF8maMse-dmoRM8-oOyn6fGkBXSXKm
sMX5y63iCTb1CUdyyqIDTPW9TdGYn6S_
}

sprite $MaterialsPermPhoneMsgMd [14x14/16z] NSo5RGLG34FHQpycPVzfsyzqH47pmnR85u3MwJ3EESlNBgOO4N4CZDX-TpKApDbQ4-0fQEQX5X1FwXcm7grxKTcpFthLUMwP3wvZB_CcyUCV

!procedure MaterialsPermPhoneMsg($id, $name="Perm Phone Msg", $tech="")
  CloudElement($id, 'materials/Action/MaterialsPermPhoneMsg', $name, $tech)
!endprocedure
!procedure MaterialsPermPhoneMsgCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPermPhoneMsgMd>', 'Perm Phone Msg', $funcName, $content)
!endprocedure
@enduml
