@startuml
sprite $MaterialsPowerSettingsNewLg [20x20/16z] {
bO-50WCn24FNfFGC_lzpPuIvvgxsyDs_8f_PFDyz6ugX5PhdbYnl9vcp_EYMRkkuvXlhsH71AsFWT7J7bS7x3JCJgrX9iQeXgOPwaPjRzRnHQ9klWyGWm169
4jeQxh6Qa2XwXyZFEW
}

sprite $MaterialsPowerSettingsNewMd [14x14/16z] ROu53W0W30DfawNx_uTnXqFd3H-0tJARVaEnOCsl5bCnuMmM7UKQTSvkaSrgcGKwMfUAh3qg1TAOxHbRmaY4bmG

!function MaterialsPowerSettingsNew($id, $name="Power Settings New", $tech="")
  CloudElement($id, 'materials/Action/MaterialsPowerSettingsNew', $name, $tech)
!endfunction
!function MaterialsPowerSettingsNewCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsPowerSettingsNewMd>', 'Power Settings New', $funcName, $content)
!endfunction
@enduml
