' definition of the Item simpleicons-14/P/Playstation2

sprite $Playstation2Xs [10x10/16z] Oo0IiBAoCW498E1cOM422R2m4AiN

sprite $Playstation2Sm [12x12/16z] Ow00i001Y0Gnk45i8604qan0cfaPJ32JQYO

sprite $Playstation2Md [16x16/16z] OnW8m8XWShC00OJ93c9oW5ZCG24edzPE0G

sprite $Playstation2Lg [20x20/16z] pSX50G0W04FHZrl_l3XasBjC41SsUzfTR1aiN_EBlL_Ogx0PuvcSMH0t

!procedure Playstation2($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Playstation2', $name, $tech, $desc)
!endprocedure
