' definition of the Item simpleicons-14/P/Primefaces

sprite $PrimefacesXs [10x10/16z] FSR50O1G00KWxFRjFwtjvmIINc2wbdqWkPTincyqaNxthCaDyM_mnLJ6cnC

sprite $PrimefacesSm [12x12/16z] HOo30S0m54IlYF7sdxQ8-O-IFDYC_cMviV03W3PZPDOiwHopaSIjQ8ng3oJWsc5SczNd-e-AhP0sbyPVRMwj__y2

sprite $PrimefacesMd [16x16/16z] NSd50GCm34DHXJdQVziQoj-d9qFgh7ANa8oyua8RvkebKNnZ7Hi8j2ej0Fzk7zyeviOojq2ekMi541AVPgAstoxcuGuV7zZmye1LfpiGtkk_yIoR2zvTOOJs

sprite $PrimefacesLg [20x20/16z] {
RSpL0O0m54FH07NB_jFMYz_FymGjmq0gWiJADA1YIaoJDXlf1oUdkt2cEAlujlXZHpNpCjGE9VnfHhbk922R9S0oJKjUc7q_Wd4yZSVvyZ8C2ylmD8_UtJH6
EfucCADR9hZCSXbFWpaDjrAt7OyQMOmA
}

!procedure Primefaces($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Primefaces', $name, $tech, $desc)
!endprocedure
