' definition of the Item simpleicons-14/P/Protondb

sprite $ProtondbXs [10x10/16z] FSQr0G0n50MWTouHzjystQSYAE6FEf3tXnrzxlz0UcmQ6wutu5CEm8_10W

sprite $ProtondbSm [12x12/16z] LSpLOKCn50N1S_KIas3whzQCi_yRFzO9UtTDzPC2cxuZ8AcM5DhQHUpMiHlqP1OnjbQcqGErI-Nm-iZxSw_vSG4

sprite $ProtondbMd [16x16/16z] {
PO_70GGn2CG4csrZzL_jXSz5lSZCu1T3_s6dF6Cxr2UBRZ6KTnvxV-Tn1a6szCa9CrHwCZNB2w7rqAr43G5HqvxkUpLSjpbHNTYe6YoS-YIjw6Yy_pTy_q-b
nxk_iwb9-M_m3W
}

sprite $ProtondbLg [20x20/16z] {
TS-reK0n5CMmS_CO4kq_xMS6bUwSxgUz-yUH1cVYG-crgCretarOCv1lBUlyhJMox3afhtfBPJslCotPGOict4PhzvdEV73bb9GAqWNYJk8eN8UhXdrTL5O9
Po0LWUNObyn0JoLLbRJohd4iykjZpltpGwRlRpdd34VMRV7X17e7kzyU0G
}

!procedure Protondb($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Protondb', $name, $tech, $desc)
!endprocedure
