@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure-11/bootstrap')

' loads the Item which embeds the element ServiceLabAccountsCard
include('azure-11/Item/Devops/ServiceLabAccounts')

' renders the element
ServiceLabAccountsCard('ServiceLabAccountsCard', 'Service Lab Accounts Card', 'an optional description')
@enduml