@startuml
sprite $AzureFolderLg [23x20/16z] xSX50S0m402mSe_zknqp2rYUSHxKEih9RNKxakrNjHd7jSLM39CQx1BRLp-ztggNsm8

sprite $AzureFolderMd [16x14/16z] Os3dvUFZus5bW00m5oJ03EK3kH013Z1WvKC5GEc11RneN2vKFXS

!procedure AzureFolder($id, $name="Folder", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneGeneralsymbols/AzureFolder', $name, $tech)
!endprocedure
!procedure AzureFolderCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureFolderMd>', 'Folder', $funcName, $content)
!endprocedure
@enduml
