@startuml
sprite $AzureAudioLg [20x20/16z] {
TT053WGn20NGZrI1kVzjrmqsysFDgm7uX2TgQ5ibteVzqyD84psinG1OX9xqF3UZmoCMvl4o1YtdsthJVXbPWyHCXcM4RTd41JEoiIj6iUwCvUMF0VOLgHO5
Xiij_AtvsKZfJMDHdO4CEfdL5vFLsLy1
}

sprite $AzureAudioMd [14x14/16z] NKw30S103CpbpVstRTzMTA2-jAIzL99daYMX582MrCnR2a6BajICWyhPbbioTj1-PUGanvrPTMJieK88fhE0uNLLq4s1hCEXhl4ukrt_

!procedure AzureAudio($id, $name="Audio", $tech="")
  CloudElement($id, 'azure/FlatSymbols/CneGeneralsymbols/AzureAudio', $name, $tech)
!endprocedure
!procedure AzureAudioCard($id, $funcName="", $content="")
  CloudCard($id, '<$AzureAudioMd>', 'Audio', $funcName, $content)
!endprocedure
@enduml
