' definition of the Item simpleicons-5/T/Tasmota

sprite $TasmotaXs [10x10/16z] JOp50G0W54AnlRtzfxNZTm6QLdKCpaWKzGnQ8z41OwpZTVn4a9tERrhO8Xq

sprite $TasmotaSm [12x12/16z] LOg50G0X30CFTxB_jEzwI1lX8FCmzOZPkSLii8bxTOSu2Xjp4taWYwWD0Relc77lVvys478S96Gii08

sprite $TasmotaMd [16x16/16z] LOY50SGm482eUzX_sfV6YTm1H7Owj0l1qRrLcDnRZQ5e2L5lzOX16NHqrN_O1I-8OnAO1IGAS3pHSG1W3xrFHfybuWE2EqGy4MyA4p82y0K

sprite $TasmotaLg [20x20/16z] {
TOm72WGn30ErFLt__-qXXzNr0H9x60oJyCNWboHfwUf0UvVa7czwhyHTki9TkZfoIQjBLGk34UMi3euZSKbab4ctD2S2Esiiwrpdq_GiST4Et31Xj-Efzq-N
xQeUX-4sDhkJGsudhHJ8fO4tv1PC7W
}

!procedure Tasmota($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/T/Tasmota', $name, $tech)
!endprocedure
