' definition of the Item simpleicons-5/T/Teradata

sprite $TeradataXs [10x10/16z] Om02Jdus1X3W1mCkC0FCOGMH40bEi1WOm5diS1P47Gk8v0CpkVWP6HYuGL901W

sprite $TeradataSm [12x12/16z] JOs50S1020DJzsR_QT_GUy49EWzF21J4VINihlcV-DBuM7uG_fNyRdvive_L1tdBXllyoT1zW0e

sprite $TeradataMd [16x16/16z] NSw53O1G5CNGuixTVrjI7CxNHX-eMJ8LNDOSEbGacUTejVruQu7bRfL-R2YZ-kugMixEvTVphyjVSpRp6B4__JLs0T48nPGC0BcOQiuiW0q

sprite $TeradataLg [20x20/16z] {
ROw55S0W5CGETsx_QQkVAgdbfHXELEgi7Wy2XMP6ueDy9w_KCnxcZk_GS3VXqAFjrCFZf37nDvTzqZXfRTB2f8bwe8pKfIK0tjPpAfoCtz53-oFcJTJZz6nT
Ljufl54GL9OT0tPM
}

!procedure Teradata($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/T/Teradata', $name, $tech)
!endprocedure
