' definition of the Item simpleicons-5/T/Thewashingtonpost

sprite $ThewashingtonpostXs [10x10/16z] uwS3

sprite $ThewashingtonpostSm [12x12/16z] unza

sprite $ThewashingtonpostMd [16x16/16z] un_X

sprite $ThewashingtonpostLg [20x20/16z] unzKO1G

!procedure Thewashingtonpost($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/T/Thewashingtonpost', $name, $tech)
!endprocedure
