' definition of the Item simpleicons-5/T/Tinder

sprite $TinderXs [10x10/16z] uwS3

sprite $TinderSm [12x12/16z] unza

sprite $TinderMd [16x16/16z] un_X

sprite $TinderLg [20x20/16z] unzKO1G

!procedure Tinder($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/T/Tinder', $name, $tech)
!endprocedure
