' definition of the Item aws-q2-2023/Resource/Database/AmazonAuroraMariaDbInstanceAlternate

sprite $AmazonAuroraMariaDbInstanceAlternateXs [10x10/16z] Oq00LYZDoS30pCpCoC3An0JYSJApSR8pmLKHp-9aWW1E

sprite $AmazonAuroraMariaDbInstanceAlternateSm [12x12/16z] fSQr0S002031ns7_WUFMvwhZQ-IYZc2W1Dv8HBcLQctdzk_wkVUD5G

sprite $AmazonAuroraMariaDbInstanceAlternateMd [16x16/16z] lOa55S103CLovVeNF6O1Ip7lmvUk1ulonAd4WG6s6XNfAYoDR6we3sHDD-V1xvvlrm5UDy8C

sprite $AmazonAuroraMariaDbInstanceAlternateLg [20x20/16z] rSY54G803CNGzDVt7nXtM81tEGi_nUohFg_atSBmPEVSMCRJvRAWqvGIIqwg5bUrbDTdvFRfTStIr_VXJr_peGpMzQgM4zChWoC

!procedure AmazonAuroraMariaDbInstanceAlternate($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q2-2023/Resource/Database/AmazonAuroraMariaDbInstanceAlternate', $name, $tech, $desc)
!endprocedure

!procedure AmazonAuroraMariaDbInstanceAlternateCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AmazonAuroraMariaDbInstanceAlternateLg>', 'Database', $funcName, $content)
!endprocedure

!procedure AmazonAuroraMariaDbInstanceAlternateGroup($id, $name='Amazon Aurora Maria Db Instance Alternate', $tech='')
  IconGroupElement($id, 'DatabaseFamily', '<$AmazonAuroraMariaDbInstanceAlternateLg>', $name, $tech)
!endprocedure
