@startuml
sprite $AwsElementalMedialiveLg [20x20/16z] {
hT3L0GGX54FHZvVaJlyLRzRT1-VWB2i44cv93Ln944qvgwTcryP7KvkMwQ1Ebg2f9ISBE-ziSZIig2QPeydHZEk-s8_oWhZOJ-fMO2cNTyQ6w-VH3SMRF_Wr
R
}

sprite $AwsElementalMedialiveMd [14x14/16z] XSsd0K110C9G0ydjl_3lLLqKJp5c2JvRMlH4kwlnK30CBY5jvLJtqbuYjTmgIklzaA2_zrah

!procedure AwsElementalMedialive($id, $name="Elemental Medialive", $tech="")
  CloudElement($id, 'aws/MediaServices/AwsElementalMedialive', $name, $tech)
!endprocedure
!procedure AwsElementalMedialiveCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsElementalMedialiveMd>', 'Elemental Medialive', $funcName, $content)
!endprocedure
@enduml
