@startuml
sprite $AwsElementalDeltaLg [20x20/16z] jSwr0G1124JHWE4F_JTyxXRTldM5-fyvyB8NkObrJ_PotzhsO1p9H5zl6MKUOqoGg0EK2Zk6WME2CLLS1vPSLr0tThNI0m

sprite $AwsElementalDeltaMd [14x14/16z] bOp50OHG5CHsWKcc_uPnEVyyrmvWRkmEGONmLYJXsuJOWtE2Tq6Mx8hVM_kX7MG3

!function AwsElementalDelta($id, $name="Elemental Delta", $tech="")
  CloudElement($id, 'aws/MediaServices/AwsElementalDelta', $name, $tech)
!endfunction
!function AwsElementalDeltaCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsElementalDeltaMd>', 'Elemental Delta', $funcName, $content)
!endfunction
@enduml
