@startuml
sprite $AwsElementalMediatailorLg [20x20/16z] hOwt0G90008BE73_XStwgLHAykKVI0uAcuKeSUlG4JCLgFXRu1HBfl7WH9EYmRKuRUnsS96DbS4nieo-PmndzE4qKXgp78JdlO4caBmN1Zs8Nt03

sprite $AwsElementalMediatailorMd [14x14/16z] XOt50S0W5CLgBs7_XUl8ZS1tApC4Xo2feVdnYyWDiVPfxTKSkR_MEHZcU6Fh0KY_w4sPSG4

!procedure AwsElementalMediatailor($id, $name="Elemental Mediatailor", $tech="")
  CloudElement($id, 'aws/MediaServices/AwsElementalMediatailor', $name, $tech)
!endprocedure
!procedure AwsElementalMediatailorCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsElementalMediatailorMd>', 'Elemental Mediatailor', $funcName, $content)
!endprocedure
@enduml
