' definition of the Item simpleicons-8/P/Playstation5

sprite $Playstation5Xs [10x10/16z] Oo0IyF3mC33my_3pyB2niO44cDdOM1aOMC6O5RzU

sprite $Playstation5Sm [12x12/16z] Ow0CS30mi30m0XbiR6oiG0h4OES3Kjoy88ARXrG30G

sprite $Playstation5Md [16x16/16z] jSS50G1124JHltOk_TEY6NZeK6oO7hVtOJ2ziGCFPZksRH6PRTk-d_2IJeef

sprite $Playstation5Lg [20x20/16z] pSW50G0X343HVu9R_xOm2S6RZyjriO2mUcTrWVWB38w5Y2t66F3V5u-r7im4LmCY19_YvI8R

!procedure Playstation5($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-8/P/Playstation5', $name, $tech, $desc)
!endprocedure
