' definition of the Item simpleicons-14/O/Openscad

sprite $OpenscadXs [10x10/16z] LS710KC0002nQm4W-s_hIzB7T0_jrN_7Gc65Te1cAoQnuZmLY0AhNXu

sprite $OpenscadSm [12x12/16z] TOc50GGn20Jd_om6st-rvowJ02jy4pIHrK6da88bcK0xa0uTbskZdFRKU1RDU4OPJ0PI7lKOCQ8m5Oah0m

sprite $OpenscadMd [16x16/16z] {
ZSq53W80241HRAN-_MyhOBT_-JP2_ccLG4Ym7T84DzWqCOczRm85aJLLninacRiEvRtdXJKaFHYZ7PYCPi3G-kVj6SWDY2m0HujkRPb9Aw-BNLcfL8VJEXYz
TWG
}

sprite $OpenscadLg [20x20/16z] {
bSf7LWCn00MmdqppkEd-j-MP3hjehRpewBDlIMe-FOeFvwHaUQe-N1FFjPXxUcdzOZ2JJ4ijpT98uez9KlsNr36QBxMDUyyyKNmu64cdOLgQGWA51hrq93TB
XwFXJWAD9Gr9qj4CU7JsB6Wg51xvqERZCIntNl86
}

!procedure Openscad($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/O/Openscad', $name, $tech, $desc)
!endprocedure
