@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../../"

' loads the library
!include ../../../library.puml

' loads the style
include('styles/gcp')

' loads the GcpCloudCode element
include('elements/gcp/DeveloperTools/GcpCloudCode')
GcpCloudCode('element', 'Cloud Code', 'an optional tech field')
@enduml
