' definition of the Item simpleicons-14/K/Ktor

sprite $KtorXs [10x10/16z] Oq06_Fmm1X106J0cX88o8GIK3rU0eWl9I

sprite $KtorSm [12x12/16z] HKg50O1040AxsNzQzV-wAFor8ElHMb1633fPVZ2Id9pmVrTtLiCoOjZ8T5q_b60nWqa8hwMf7m

sprite $KtorMd [16x16/16z] NSr10a0W64JXVmLWxdzQLBsfcfNleI9j3LOeJIH01rDFp-lVMK9cVgfVs29W3dqmuS3-Ghwr1iYW1xt23m

sprite $KtorLg [20x20/16z] PSwt3KKn5CDGvvRxJ_lZ4q3uijEfrFxrTZUW8Dmue23SEA0WAkOrWZQwiFoK6MF6c77yEkLIEYsPX24b4eRSGsy

!procedure Ktor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/K/Ktor', $name, $tech, $desc)
!endprocedure
