' definition of the Item simpleicons-5/U/Uikit

sprite $UikitXs [10x10/16z] Om013WOeuEVdPu015X0R8SpF0sK24JOMFqmxFnZm8Pa7

sprite $UikitSm [12x12/16z] VSd50S0W5C3GrBtPVrgSAm--KvnqXqgtl9pIxUhDGVNueFqowl_SJlfmgpU_kW8MDxIxkKO

sprite $UikitMd [16x16/16z] dOwr0S1058LUt8_zfpsNNuSEAbGvPNc0sVWBdsJBh1rU4oO7C6dgPSt-k5xsxF3NZ-gSTIhvIcBJ3U1IlsYiAhXiXxdlxm4

sprite $UikitLg [20x20/16z] hSyr0e105CJGu4xkVrhS_jQyCjKCjxmbDQWLWGUYMcleHnAbQa_GUo2wMjLdlDgpwSYZlfj_juRR-3GjFgCXczrDEOs7xhxvcBbqJobupUugWdAsvR82

!procedure Uikit($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/U/Uikit', $name, $tech)
!endprocedure
