' definition of the Item simpleicons-5/U/Unilever

sprite $UnileverXs [10x10/16z] 3Oe50G0W30GFXsd_jipVU3Helc4jQwHqn_Pkw4hX3E3Dl8nqA0KgMyTwungjUbuEPBpx5gnnwII0hLuA7m

sprite $UnileverSm [12x12/16z] 5Oh7OGCW300FK4SA-qyRsyyhzCq4IRb1BMdOhgkGLeMbvmYshS6zBCbK-taJOUyesFejJEJ0UT-No1W8jpdiTjDp-_2OOvRJMGEKomiDQG1xp-RlmWS

sprite $UnileverMd [16x16/16z] {
7Oh70KCn24Fb9fhXxxzjS8wleCQnum1ujqaWvNAkPld8lAZavUDIZtmzAU-FvUA6VHOrtoyUD93WqUOj5lPXaHxHpBFpzg_BWisZ1i_0vsudcxCuP47FblNd
U_OYOfWSdUs7olfW5MfqlplyqC1XvDKi5Sy2O66xFtUXxMPaAizdstC-1CRrNS5Q07u
}

sprite $UnileverLg [20x20/16z] {
FSi5WWGW243HZq4PtF-swsmza-A64x9vnCxGHNBCAiG7l78QfsryzYdx2b2Msjf9Kkx92XvrDqq7sw9R4M3TMTKpKBMtzm2oawl78enU94_eo3f-CQ-PHtdK
KfU-aT6byl1HBIU2Ccrczjw0a1eLTt9FQ50y9xSsbSQw6ghHWRklPpkBuQzA2I2N6CixDivSx17KiTQFbhFiKbJ5NR5yHqoXdHwwOi_ZuPAv-8ZfVVjbjqDK
yB4ZttzUjRRLEh_sdDNY5Gx_viuianN2ymK
}

!procedure Unilever($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/U/Unilever', $name, $tech)
!endprocedure
