' definition of the Item simpleicons-5/U/Unity

sprite $UnityXs [10x10/16z] LSUr0GDH040Xufwt_xHVogF3KHkUZvjNKKWANVMeZOjR-F_iX6JhT2gswZi1

sprite $UnitySm [12x12/16z] FOe50e0W40JFec7-_rkN70MsxE3M-o3k8I-AN9Cgz0MVdee9BR0sP6kodebyrV3L6sJqVyFWfBlvp6vK3Q10jiaBN3y

sprite $UnityMd [16x16/16z] {
POu53i0W00EBE_t_RvUEP08teOBXYwruC8qa7olpUEVO0mm7Wsndrp09yhMUKH76idUNYSaPHQDHcFXmBq9S0eu9CCGJQ6YIGKfTKxO20vMM0q9wPDtP7lT_
C5d-0W
}

sprite $UnityLg [20x20/16z] {
NSo55OH034NHZuxdzT_jXfn5Bup5z5NqCgSER8y89-dKWBu_OZadsuvXk4M7_hzCuFSizyXLxTYZIZD4RLJD2h36hW7Mmc38rPnuI7BB90_Q4ZQGCw_sQrMm
Q8xC3aq1PYqHqt864wPCrs4xWx0PkquUdZJX9frsdE7qK0bTRwl79_q
}

!procedure Unity($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/U/Unity', $name, $tech)
!endprocedure
