' definition of the Item c4k8s/Boundary/ControllerRevisionBoundary

!procedure ControllerRevisionBoundary($id, $name, $tech="")
  C4Boundary('K8s/ControllerRevision', 'Boundary', $id, $name, $tech)
!endprocedure
