' definition of the Item c4k8s/Boundary/ValidatingAdmissionPolicyBoundary

!procedure ValidatingAdmissionPolicyBoundary($id, $name, $tech="")
  C4Boundary('K8s/ValidatingAdmissionPolicy', 'Boundary', $id, $name, $tech)
!endprocedure
