' definition of the Item simpleicons-6/E/Emberdotjs

sprite $EmberdotjsXs [10x10/16z] uyS1U1YOe2m6NWOeWu4Vp6BZO6222l42nO3YO5aGm6uM

sprite $EmberdotjsSm [12x12/16z] VSor0O1040NHmPtflrha7odtalMrQZlz7C1g0T8P9uSSoPgUbj7eeSbYsQ47Z2L__jq

sprite $EmberdotjsMd [16x16/16z] dOkr0G0m20JZBljF6nTekUgrqh1S5M3Pv5izZ609r6LapwQvPVoMHg4xNouCfKxcvxy6zYyRTIzbEfahWGu

sprite $EmberdotjsLg [20x20/16z] jOx30G0n50LdZQZ_QcFVCxUF1xC82UpZwY5m3Zj0NT2lDb11Fhq5VMyeu34VgBAuUK_OWS6hXNxbDoHIVA-ky2lU8wuA57xJE0ayPWaE

!procedure Emberdotjs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/E/Emberdotjs', $name, $tech)
!endprocedure
