' definition of the Item simpleicons-6/E/Espressif

sprite $EspressifXs [10x10/16z] 7S650SC0402XgskU_QUDGOVvTU8VzUo2A4I63t5T_bp8fI93BmEc2ZhykvSs

sprite $EspressifSm [12x12/16z] 7Op7OGDG58FulJ_sdpQnBS4LVel7RwjhoXyXK1M5d7VZQjB-KNTMZ2jLu-DyMKMxaYYXQ7Oo6Kb334R-9KmFkA1Rw40v02_p3m

sprite $EspressifMd [16x16/16z] {
FOg5eGL12CIoSh82wR_QBqykE3DyoBnvC2gt-ZvGzIIqm89xgSfK2Cvv5RPQbgkMKCtILDA5RwwgYHOjLFKujMQWlbse71Hz7-jG6C3GFXKj9CqQMXG5rdIS
Rt6VGByxRpDqWBPf1lF-pnSpEzGTm2y
}

sprite $EspressifLg [20x20/16z] {
HSk5bGGX403Hwc4ChVoZFG7UxaVR-1ZM15_tcuYYPXOPgetvhbJWadbMyhs1o4wSAWXlUHD7KurRBp9Ex-oHOd_FuNQ4sj4HQih-ur2lGr7Vj0RZLHazcZDa
3nhdSz7zTytuqG45U5J9Eb1X047J7khAtG-xliy0FBwnqHh_fFB9iOI9j7DG2bDlS9q0oOljA2FVzrl70_0B
}

!procedure Espressif($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/E/Espressif', $name, $tech)
!endprocedure
