' definition of the Item simpleicons-6/E/Express

sprite $ExpressXs [10x10/16z] RS710K0000IW083RVri-0ELNNG9w8gmra4YxeorLJY5cmjS6

sprite $ExpressSm [12x12/16z] PS750SGm000WshZlF-t9E-1sUtjSR1m1YwB9WFYyJlx38GEEGyNMKTXZyI01joy

sprite $ExpressMd [16x16/16z] dS450GD1302mF1wt_jKE5Mo9F-m08ChP1W7RbB1t4iaEWcsOTA3X7YTvVs5FD012uWP1i4rYmtKf1yf9NICk6XX-z0G

sprite $ExpressLg [20x20/16z] {
jSF5ZGDH500m3to6rt-rotXFBDaJtENqNrtvBlkYDJ2oMa4Sn8sqMJvD13PtzYbmXJYO-VgqeEuRKVCNo75YN7wTMnnSnQVukh_YxAmRjPC2Zg1C43Vdd6Dt
J9-M1ti5
}

!procedure Express($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-6/E/Express', $name, $tech)
!endprocedure
