' definition of the Item simpleicons-7/K/Klarna

sprite $KlarnaXs [10x10/16z] Ou03Vdxy10I3I23YXhEu691bEO0aL8A71yZY0P8y

sprite $KlarnaSm [12x12/16z] ROo30S1054DJks__QOkplf54YLtNOMh_LRXCLMicpZl8pS3XvmbwF-i6vLpmceVJzVO2

sprite $KlarnaMd [16x16/16z] XSt50K8130MmXplPVrhuxbBFgTa9d9gzvHlleN4S-8NqVkBG6rxf_KO63WmTF4eT6b_hVrygrrUYS_3DWqpY3m

sprite $KlarnaLg [20x20/16z] ZOu54e0m30Hnb___bZ2BH90Uqkj6iqIjeikDZkLYUiTACQLZavZSCOoodArb0wTcutwKcicFvJHRT2MC_-1O4_knCTLLP_PRCZQ0tKj3OBIaoIIYyuJjk7fj

!procedure Klarna($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-7/K/Klarna', $name, $tech, $desc)
!endprocedure
