' definition of the Item simpleicons-14/D/Daisyui

sprite $DaisyuiXs [10x10/16z] 9SE30S1000J1YV6u_giD5o102rjcgl0Va0902Ck03J1AG2bcGG65iN03

sprite $DaisyuiSm [12x12/16z] BS674SCW400mSTYcy_jFcqOaS8M_lZ4BF5BkfaMtmS1EZgjTicC9FG-4S5pebpaTaHG3P5Yk5JriqBWItW

sprite $DaisyuiMd [16x16/16z] {
HSU5SGKW5031nOPWZ_whZNtRiJl0lDL7EhYUeaRqjFRe6uB19we0qd98CNZQbnC-LanTwP2tgbr9kL-uqwHQ52b8YY6sZpiOaG1z1xhrt2AmsUeijfPXdBjm
8xAdQCO0Fm
}

sprite $DaisyuiLg [20x20/16z] {
LSX9OkiW00Km0Pumu7V_q_wnRH8jvTlCvTDz5pMLRoi9d4asu2cYFrbjhwuEioZnNnWGvV7b64f74hwrhC4T7tggM_SkCej7AnEKqDqXMaxOKsYkgrhqpNaM
_M2OSZRlLXrgTc_AN4ZDuTipwa0OxRkQRSVM2L060NsKrTFRMBDkgNnjeAwnurlDVStXlzy
}

!procedure Daisyui($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/D/Daisyui', $name, $tech, $desc)
!endprocedure
