' definition of the Item simpleicons-14/D/Delphi

sprite $DelphiXs [10x10/16z] 5SY50S0m3CH0XSlQVzlcpsosmq5esWbMme4SkjI3_D2S77KzEXKQXw8MqZdLmIqm3FW1

sprite $DelphiSm [12x12/16z] 9Sl50S0m509GuXxstxRGlDCNW2rsF6IDW_p7a03aHez0ZFuUpNcx8QjXG3eb1o341etzrBzPDMjlLQypF5k1xWrlIPaNScYgVG

sprite $DelphiMd [16x16/16z] {
DS-5ZKH13C1G3trEt7-tfunkdz1YiytmRVo4Pge7ctRMd9p6pcYDqeOVX5Mzmr0RTiYldtwMwKJAOOdigxE59GbWzdEqojTMtOzqLJULRHwfedxl733oqkIq
n8971TBomlb_y5ckBrripIq0_W
}

sprite $DelphiLg [20x20/16z] {
HSu5ZWKX0C3GulmHUl_RRf3il5ZZvUZ3fy2dUBo1GsrCh_vOj982478ONW0Q2nnL2nHh0MACG5S53QTjmwbZJTmZ0FpSkX07MtCPPlokZeP0Jx4r7gV7Ya2j
jwC4fwf3fjImEw6QKcJwnLjzULr20QfTZGItNY0vVQUM0BVATBcbL9j6bkA7VztbZKn_
}

!procedure Delphi($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/D/Delphi', $name, $tech, $desc)
!endprocedure
