' definition of the Item simpleicons-14/P/Pandoc

sprite $PandocXs [10x10/16z] Os3W1m46CE05OWYJbPs10ohA3yNCS1OtN0y_H3aQYm_EOWNJ

sprite $PandocSm [12x12/16z] HSR50OH000ImuB0s_LTxBdc5lCn0Sn4W1Wc8i2pnFUN_QOSXJnCK0PWM1M2RvXMWs0141Tm1

sprite $PandocMd [16x16/16z] XSZ50GGn08LGufxVVxNhEihj0UWLhy8eGI5ynpG8fF6oU5hjryuv_Hhus2qS1u1zsaow7lM7OsFaS8z79JFvQJZqQvc5ERFz-We

sprite $PandocLg [20x20/16z] {
PSu50e0W44JHMPQkkVzjNRk-_LG0GELPmLbfawtPtfXnDGP006Iyp7voPfwaN1QGp38VQ3Tj0gAg3AVPtezRzx1w_RAbPiSoXDXBlFvnfxLfTdGQ6uIzRPNN
ajynG7_ca7ycg1yJ0ds-pPdD-ZOrOtXRffayO04
}

!procedure Pandoc($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Pandoc', $name, $tech, $desc)
!endprocedure
