' definition of the Item simpleicons-14/P/Pantheon

sprite $PantheonXs [10x10/16z] Oq01p7067roCWmFAu6TXOu6oEBcue2n-Ldu661EkXHVLL

sprite $PantheonSm [12x12/16z] Oq03ZCWSVYGcFo-SpGC4C3OVApSV4qmD7nSNdCt6n0PJmyBEpu9a41-c1GW

sprite $PantheonMd [16x16/16z] PSjL0e1G449HR7rrzxzQkz3pDmDeKydy7rckniu4rcY7OQZhvmOwUDqnO7T88OJNJLczxyxs2f6WDy3k5hceZr6x1G

sprite $PantheonLg [20x20/16z] TO-54GGm20JZdcp_rRuR3B_Zo8dxJpDc9Hf3l9x4UD2p2cmzR3VKDy22A6OrKLAITul9bfBGwnYZobaxm98pLbOUSywovWnPz0LmYWaqFJowsnsSGJLcdsfN

!procedure Pantheon($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/P/Pantheon', $name, $tech, $desc)
!endprocedure
