' definition of the Item simpleicons-5/A/Abbrobotstudio

sprite $AbbrobotstudioXs [10x10/16z] Oq007duM28C9YFcXc863dntAX51G1Z-O2PJYWOenGiHXJ6w8A3i_q3

sprite $AbbrobotstudioSm [12x12/16z] LKg30G0m3ElivVzhPvOHVPNTHa4G8HCPJ0x8TkqaqO_m91w9TW4hhXwy7lKOqmDoEMvNWbmsuwpT2W

sprite $AbbrobotstudioMd [16x16/16z] POy55i0m24CpLyZzRxkNrTjVnG4ZKoCzptAzM06UCjpIBKuzzuE0awlUsOEyEa-8vK1atJOzJ3990t1LCkMcinHvHt8oq-tXofYkoPB8yCmU7kPHBfhnmCW7

sprite $AbbrobotstudioLg [20x20/16z] {
ZO-5bGGW34G7TwR_Rk_XtFf7umb-9fFKkD4qJUyLWP0OcqwYKqWqL7CPf1DVbjAJT1WG2naJ1YhYG9Rntggfp5TJZVRhiLMrX5lN4pkxvhdoZTnIuvAom873
97YKVfVTobIm4BbO9NMWmuqhJ1Bl-0C
}

!procedure Abbrobotstudio($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Abbrobotstudio', $name, $tech)
!endprocedure
