' definition of the Item simpleicons-5/A/Acm

sprite $AcmXs [10x10/16z] uwS3

sprite $AcmSm [12x12/16z] unza

sprite $AcmMd [16x16/16z] un_X

sprite $AcmLg [20x20/16z] unzKO1G

!procedure Acm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Acm', $name, $tech)
!endprocedure
