' definition of the Item simpleicons-5/A/Acm

sprite $AcmXs [10x10/16z] BOY55KKn58Fu-khiFssTA-64HU2YL_sHjrhLLrYDcn3aZuKi8Ri1mklaKlCrdYq3

sprite $AcmSm [12x12/16z] HSV50G0X4C30nPtqN-q9cjT4Hb5EdNXvfXl0naC8yIDKw3qH8pqQWTv08em2IYJQuVhncv1Qg5f60L13OmPV

sprite $AcmMd [16x16/16z] {
LSd50K0n3CFGb2cDzf_sC-hcPxcgyWj-OFp0hEN-WaK5Ig_tv4Zr03FbBB81jE7C9U-TGgsGQ-kJ86KQIAMZDcpqsK142eMpW9EjslMO-PmRQDJP0bwk2XZN
Uy4rNv2p5G
}

sprite $AcmLg [20x20/16z] {
PSq53iGm30NHdpRWLMBF_M-xAjC8_GBMcUbJy47WZS47eKZgTmoh03x7YPYpbOwRGUKeRmY5iyQ20HejjL8qPmq7Cq1M9T3uoJlBl0mvUxRYFIyqIKRtsmwq
PCm7XJ5fmqWx2HqPkGtlURjr8jl6Uusbf0_gNRjk_G4
}

!procedure Acm($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Acm', $name, $tech)
!endprocedure
