' definition of the Item simpleicons-5/A/Aeroflot

sprite $AeroflotXs [10x10/16z] Oo09C8C8VcvE5dv-BXv-89kTcOE1YP0k

sprite $AeroflotSm [12x12/16z] Oo0BC2AnkJZ153yl9oS3FmiN5nyVaCVCoyx7piS4LSB6m4AioG

sprite $AeroflotMd [16x16/16z] jS750O10402nmM6r_sfn_rz28JK_mbkRLEmYR9gSP1Bnx84XHAsEIQBc8X8KiG

sprite $AeroflotLg [20x20/16z] pSP50W8n4031ZcU4pFzVYplST-jKx5FdZy9DBZVOmX_NE9Y8L89GLL-HWMukRZM9cFgit0sApKNDl1DeREm4

!procedure Aeroflot($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Aeroflot', $name, $tech)
!endprocedure
