' definition of the Item simpleicons-5/A/Aeroflot

sprite $AeroflotXs [10x10/16z] uwS3

sprite $AeroflotSm [12x12/16z] unza

sprite $AeroflotMd [16x16/16z] un_X

sprite $AeroflotLg [20x20/16z] unzKO1G

!procedure Aeroflot($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Aeroflot', $name, $tech)
!endprocedure
