' definition of the Item simpleicons-5/A/Affinity

sprite $AffinityXs [10x10/16z] Oq01_Fpy21QCmGTbyhC1ESn01eZF32A06AA26ym30J09OS41

sprite $AffinitySm [12x12/16z] NSk30S1G34NH_Dfd_sbhtnWl_k3LAiv-T1yI6TtvSYk6VUNSd9eKbEUdHD_tTc9o4mVLbXO

sprite $AffinityMd [16x16/16z] ROw50S0m20IXxhV_jetxHV6N8IzSXQaOdcmlM3JPgxE_PCDx0cimpT_u3C66NMG6Zc0I7iAi9Gpb5ScDRq1NFtZU31WKk0q4vAFaCMMFutEt98Bw7m

sprite $AffinityLg [20x20/16z] {
VOw50GCX40GNTxR_RfFZtPXNvXGJMcjHNrMcS7KSX1V7DrUlAdUHnnWpoiIrSve7eaYpAa_slUckQBSMZ5kqOz3MH7_QIwzn-IIir36cR6cL6rt9g_mv755u
9qFbkyC9Xma_
}

!procedure Affinity($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Affinity', $name, $tech)
!endprocedure
