' definition of the Item simpleicons-5/A/Alfaromeo

sprite $AlfaromeoXs [10x10/16z] uwS3

sprite $AlfaromeoSm [12x12/16z] unza

sprite $AlfaromeoMd [16x16/16z] un_X

sprite $AlfaromeoLg [20x20/16z] unzKO1G

!procedure Alfaromeo($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Alfaromeo', $name, $tech)
!endprocedure
