' definition of the Item simpleicons-5/A/Alpinelinux

sprite $AlpinelinuxXs [10x10/16z] Oq06_200OK2P7FpyJ10Ma06HuEPdP00Y89C1o0Rn-VWHEX0iX7a

sprite $AlpinelinuxSm [12x12/16z] LSm50SH00C2mRiTO_sgVCGB2Fxth0C4d05ysD1MxUg1o0kfGkWSdYc6T6deO4dpxUVfFobqVTn6k

sprite $AlpinelinuxMd [16x16/16z] RSc54SGW00NHZUE__sfFS6RoS9ONrXSdsQw6J9q1k3IqRBso2Fx_XB3ba7V3jNEHF_o_tl_WymVoN4ZQ2Q38gHcWoGDiQuQWvYHhpmJPLW5y0G

sprite $AlpinelinuxLg [20x20/16z] {
TSu50e0W04FHgNJj_gSrPjUpzGlWZx6x3ZiUAZQD9mEnl8Bm9c0MTDjVmqut5ZqRwZPDLdLTmA3Cp9L1vw2oBLa759qZL4ALTMiTbpB1aNDRILrRqyHyS7Y_
n2BpQe2yCo2-Nrt3Y1yJ
}

!procedure Alpinelinux($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Alpinelinux', $name, $tech)
!endprocedure
