' definition of the Item simpleicons-5/A/Anchor

sprite $AnchorXs [10x10/16z] Oq05_0WM1vm54UJZ1xB072u-8CN13r8D4s9au82oUFZv644ie00F1mDO4G

sprite $AnchorSm [12x12/16z] NSQ50G0n4091ufxjlzjtFO7HVoAFE_LsWLF8RlPZSnKqmMQ4mwnSqHp2hcvb1QAjdcpsYTLav4bQFH7QBWuj

sprite $AnchorMd [16x16/16z] {
RSc5TKHH203HUVOTflzgatN7xu7V4RvRzm_xwVx01ga1j0fqDmv3s1KOUkhgGFFoTq6CuW6suYHMhKwWYCLbTZZ0RDP80xsu7VQgUNDW35I6DjZAQgUPe9K8
s86vSJd-0G
}

sprite $AnchorLg [20x20/16z] {
VSo55SGm3C1GbUs2jV-sbtVCnUW7-7TjswTfVZ6_MNmndxk_Ml-WD47J0CgTyqyu7FH-H4jNLdlFLWlGicHsqkWKo6o9ys0qxCzM3eZYnjrono5Q7PHnjhqJ
0rDfShPSQd7dNDtLbhrHdHEkDeeMb49_7iOckm630hi9yzp11D0Fq1eu0G
}

!procedure Anchor($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Anchor', $name, $tech)
!endprocedure
