' definition of the Item simpleicons-5/A/Angular

sprite $AngularXs [10x10/16z] uwS3

sprite $AngularSm [12x12/16z] unza

sprite $AngularMd [16x16/16z] un_X

sprite $AngularLg [20x20/16z] unzKO1G

!procedure Angular($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Angular', $name, $tech)
!endprocedure
