' definition of the Item simpleicons-5/A/Angularuniversal

sprite $AngularuniversalXs [10x10/16z] Om01NWOmuE470NO61Y390271Y1_AmYd61MQ1-8n02Ye90X0Q

sprite $AngularuniversalSm [12x12/16z] HOY74G0X383uNjNzj_MmeaauG0ADBya5f8cED3zwc_rdzeCm-igb9nrMryRYiKX0R4Oo

sprite $AngularuniversalMd [16x16/16z] NSc53S0m50FHAtEz_xQDBPNoWgSFqHpO7RAPnABN02gErMHfOfIqfNCTxh7gbiqz5eExORpdPtuqlkFNpTta7lJj1ZgOfODYqsqacZErmgsHJk82

sprite $AngularuniversalLg [20x20/16z] {
RP255SKm24LVtCF-qtv1JlMsCHnWnELm8GxwqpoCIGVbBwXqOqKG0oRolM8T8e1b2ODbdL-Uzu36CaaJDKv--6fSrF77gyo_-88F7__Wa5tZzKCMXzxp8HiK
vEu0RYG228V-FWK7ePEHSR1r8XV2fWxb2m
}

!procedure Angularuniversal($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Angularuniversal', $name, $tech)
!endprocedure
