' definition of the Item simpleicons-5/A/Apachekylin

sprite $ApachekylinXs [10x10/16z] JOE50OH0083GwsJ_QRz3WWl7Z6Vl04E1rr4oZrGwKd23ImWYDcqWAH4Fe5T-MCk4Em

sprite $ApachekylinSm [12x12/16z] LKo30G0m3ElivVzhPxCX_OiJyr7rYG6n_uct1qW3vCvxc8ZG8U0veUt0INKAPeGoL6eF8XAHxcMhtaUwABa19kB8sRQ_0W

sprite $ApachekylinMd [16x16/16z] {
RSO54WH124FH3ptI0kJ-jzqQAzs79FpJmCnu3EdaaeFBNDB6vH20IahZqWFOSuPiM-lgO4efWL5OTewiW2DxamS7I0kwDYdWnAfSXvUQfDICS3CYeZKSm0et
txoPmqK15-DXwZo-L3NWw7oivsfSVW
}

sprite $ApachekylinLg [20x20/16z] {
TOi5aaGn44BvSN_tl-rsgdfzXWWKehV8_vodBgKSqc2umqNmFiNT2HEVK2yb3dGy3tX60kFotFbTxzCFxDpQ95Xo7vFEa4RKGPhrc3VskNNp8CKao-5CynPn
mzAZTSSdiLe0p9nvd0W8kZfqY5TQxv4k6NzZ8QLiK4hPWyJIDzmSj6-lE3U6NENl56YvdgLVIAL4bny
}

!procedure Apachekylin($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Apachekylin', $name, $tech)
!endprocedure
