' definition of the Item simpleicons-5/A/Apacherocketmq

sprite $ApacherocketmqXs [10x10/16z] uwS3

sprite $ApacherocketmqSm [12x12/16z] unza

sprite $ApacherocketmqMd [16x16/16z] un_X

sprite $ApacherocketmqLg [20x20/16z] unzKO1G

!procedure Apacherocketmq($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Apacherocketmq', $name, $tech)
!endprocedure
