' definition of the Item simpleicons-5/A/Appletv

sprite $AppletvXs [10x10/16z] Oo00s1aO-C4CVdv-1ducVWPMVX0B39c0BB0i2rYM1yB11

sprite $AppletvSm [12x12/16z] ZSgr0O100CNGu4xsdnQNwkHrNyZJy6l1ieG23yW4guSIOS3swR5vFmMzF0eYTW

sprite $AppletvMd [16x16/16z] hOc54S0m3CGKvdZ_QSjuN91Hz_o0kwjjWEmMggs58E8542ipIxxuGbd49wh9HpxF_Cp4nRjfK9QSNXrED0UALum

sprite $AppletvLg [20x20/16z] lSs5WG9130NGj-xp-w_s3bXj0Dwu9F4h7QWy387qBfMvgHYoJkC0ivAtZOpr47GPyb6JWSywPiT-Dv5gtU-g_Qw98UhizZjHMeyQ0-Ons3zYJMYoUAfyoJy

!procedure Appletv($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Appletv', $name, $tech)
!endprocedure
