' definition of the Item simpleicons-5/A/Archlinux

sprite $ArchlinuxXs [10x10/16z] uwS3

sprite $ArchlinuxSm [12x12/16z] unza

sprite $ArchlinuxMd [16x16/16z] un_X

sprite $ArchlinuxLg [20x20/16z] unzKO1G

!procedure Archlinux($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Archlinux', $name, $tech)
!endprocedure
