' definition of the Item simpleicons-5/A/Arkecosystem

sprite $ArkecosystemXs [10x10/16z] uwS3

sprite $ArkecosystemSm [12x12/16z] unza

sprite $ArkecosystemMd [16x16/16z] un_X

sprite $ArkecosystemLg [20x20/16z] unzKO1G

!procedure Arkecosystem($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Arkecosystem', $name, $tech)
!endprocedure
