' definition of the Item simpleicons-5/A/Artstation

sprite $ArtstationXs [10x10/16z] Oq05_FmGcXt8ue28G0H193y8WraGGIZWG30XIY3o33nW5Yy3Bm

sprite $ArtstationSm [12x12/16z] NSd50O100C2muaxtdnRdBDzGsfL0DnxrmAGLDmKLeDETMbj0G_JJ3NJYjshl2nHV4uCGWXC

sprite $ArtstationMd [16x16/16z] ROw55O0m34I1kcR_ROcyUdyrVi-L5m3UsL7GiMIW7Tl_mr2OAYfeJYXYQgvLUAjM2a4UCZqGCjDAM1pfCZFDjgCAQ5XEQELj9efheDxwufpEW_m

sprite $ArtstationLg [20x20/16z] {
VSw55OGm403HmPtflzkxVRZbeqdMI6ZQjYcuyQ_YQeXDJferi3ssSZFerFYk9iSrS3Z2D8Vg76Wulg4nD90TyxWuppEkUyDwt77LtWVdFi-gZCtQ4s2EZoSj
e1F5BR0tZraE4p3nvWS
}

!procedure Artstation($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Artstation', $name, $tech)
!endprocedure
