' definition of the Item simpleicons-5/A/Aseprite

sprite $AsepriteXs [10x10/16z] uwS3

sprite $AsepriteSm [12x12/16z] unza

sprite $AsepriteMd [16x16/16z] un_X

sprite $AsepriteLg [20x20/16z] unzKO1G

!procedure Aseprite($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Aseprite', $name, $tech)
!endprocedure
