' definition of the Item simpleicons-5/A/Azuredataexplorer

sprite $AzuredataexplorerXs [10x10/16z] uwS3

sprite $AzuredataexplorerSm [12x12/16z] unza

sprite $AzuredataexplorerMd [16x16/16z] un_X

sprite $AzuredataexplorerLg [20x20/16z] unzKO1G

!procedure Azuredataexplorer($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/A/Azuredataexplorer', $name, $tech)
!endprocedure
