' definition of the Item simpleicons-14/G/Googleassistant

sprite $GoogleassistantXs [10x10/16z] Oq00Fdv-VWYB7mJW37uGWmb8GpbWaXU84G2k3OF536G1

sprite $GoogleassistantSm [12x12/16z] ROo30S1054DJks__QOkpzKDb2vZZ2ACPTpFpZznklX0o8xFHZ231yVkc_-c6jBcF8xHc_UCB

sprite $GoogleassistantMd [16x16/16z] PO-50K0X20NjrhV_j3zDEFDC41m0OPd7nzhzoLqJEfzbOBcpeY9CxuUwXk5w75-FjARViJLnODGc_Jo9qouFtUdvHNopl04

sprite $GoogleassistantLg [20x20/16z] {
ZSy34WGn503HQ1Zq_K-xniTYkfHwSVXSt7kRD0rkHK6LHyB0uMuj0jOID6b03qj9mW38xwT0kTicBjv3w03fTVMu3HkiuK3LhmC4oXyeIyBqtgOjYsLY--sP
Pm
}

!procedure Googleassistant($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/G/Googleassistant', $name, $tech, $desc)
!endprocedure
