' definition of the Item simpleicons-5/I/Icons8

sprite $Icons8Xs [10x10/16z] umS11WOUJWO8Yny6UE0iJX21a2LT1m

sprite $Icons8Sm [12x12/16z] umS31WOsVaO6A9iV0TZuiGD693O37q8XvUO

sprite $Icons8Md [16x16/16z] uuS21WO6Bdus1WOudmrC8VZyg82B7pzWWz9e-daHze6v30DjFm

sprite $Icons8Lg [20x20/16z] tS-r0SG00810NkB2_jF6tUjSIuKJu9kR04wWj1NZXD9UwEJhNkupYNiuA9mGJt42eMe1R_ce0G

!procedure Icons8($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/I/Icons8', $name, $tech)
!endprocedure
