' definition of the Item simpleicons-5/I/Imagej

sprite $ImagejXs [10x10/16z] Os1WuETd006SB222iLZWB0Oq5Yy_a0aJOmMoeKmG2m

sprite $ImagejSm [12x12/16z] Om02Vdu6CC3F1Y9-h6m60cn6882By_8YgG41FhW5O64

sprite $ImagejMd [16x16/16z] Om01Vdv-1YWWcyyF1AJm6KZWSt1m8F6PE400MPwNbnTTFpSt4f-57mnOuGvc0t7PGIm

sprite $ImagejLg [20x20/16z] hSg52S005CJGrFLp-qzRjwDOvU4XB2IrkBd5xqspbotFxmr-QpDleKNXNqIqa5fRjaJMCcqwJhrMNDLpwLcC

!procedure Imagej($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/I/Imagej', $name, $tech)
!endprocedure
