' definition of the Item simpleicons-5/I/Itchdotio

sprite $ItchdotioXs [10x10/16z] uwS3

sprite $ItchdotioSm [12x12/16z] unza

sprite $ItchdotioMd [16x16/16z] un_X

sprite $ItchdotioLg [20x20/16z] unzKO1G

!procedure Itchdotio($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/I/Itchdotio', $name, $tech)
!endprocedure
