@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q1-2024/bootstrap')

' loads the Item which embeds the element AwsCloudWanTransitGatewayRouteTableAttachmentCard
include('aws-q1-2024/Resource/NetworkingContentDelivery/AwsCloudWanTransitGatewayRouteTableAttachment')

' renders the element
AwsCloudWanTransitGatewayRouteTableAttachmentCard('AwsCloudWanTransitGatewayRouteTableAttachmentCard', 'Aws Cloud Wan Transit Gateway Route Table Attachment Card', 'an optional description')
@enduml