' definition of the Item simpleicons-14/A/Abusedotch

sprite $AbusedotchXs [10x10/16z] Oo0Hi30my74mC30oiBCWYU47

sprite $AbusedotchSm [12x12/16z] Ow04CB6miBAoC760s1mSl5oSZ6n0DaK

sprite $AbusedotchMd [16x16/16z] lST70G0W302nOqENVxbKHVCBjJg1sUJ5NXlQ0TppBVO1EEoRvQvnAV01

sprite $AbusedotchLg [20x20/16z] pSZ50G0n2031HUBMVxKdxpJ0u12OSlF_FH6RA7g4BhZ--vQw_YcBMN2WKgGrUgTrHiEvER6y

!procedure Abusedotch($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Abusedotch', $name, $tech, $desc)
!endprocedure
