' definition of the Item simpleicons-14/A/Ankermake

sprite $AnkermakeXs [10x10/16z] OsI00Nv-2CtA3mGG1XY06L0cZC42OpA0C5GP247reh8

sprite $AnkermakeSm [12x12/16z] VSUr0S1030D0FLGXxJ_jcrt6U1he6kHEFgI5P0PZXIRNkbDOB_UDCEoK1z46VYq

sprite $AnkermakeMd [16x16/16z] dSWn0a003C30T06G_xyMW7QLxH91BdH9L7NEp4FBq3BCjPKZInfCw3vuZEh4vr199gGOVde3

sprite $AnkermakeLg [20x20/16z] jSi52i1044FHJ0Mh_FkVjgvhW-r7yo1c2ZFWBpr70RqO40JqOa0Gqu4TlisRx3W-ecEpU_IJlgROZZ4gD4E1xLMp5G

!procedure Ankermake($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Ankermake', $name, $tech, $desc)
!endprocedure
