' definition of the Item simpleicons-14/A/Apachehbase

sprite $ApachehbaseXs [10x10/16z] Oy01-14iNXW3180q9vZ12cJoyt5pyJ4oSB9my_FpWkMuuTeu46O1

sprite $ApachehbaseSm [12x12/16z] VOkr0S1030EVpTR-qmRBm5N2yWVUjG3PBkMuEVMjPiGf2OavbfM9oBmMZKp6VQlbanq

sprite $ApachehbaseMd [16x16/16z] ZOw50KCn24I1k77xJzj-TtjH_EWRUMyozdOzs82crHACZ9OMp71ljybGsz2PQJAj-E1JtoeICXfrH7GRrTMvct8fpigiIXBJdaWl_04

sprite $ApachehbaseLg [20x20/16z] {
hSkr0GGn00InCREt_sgVcU6KYmM4oHqrxgXpoqd3SYLffniEEbD7dPqmT66mLNIImr04Z8u6ngGeO4gJfbfdCRlbiP9ixLtIJ6mCqRJ1cDfWgpPQJzvRZaoq
8N0dU-vPFhG6
}

!procedure Apachehbase($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Apachehbase', $name, $tech, $desc)
!endprocedure
