' definition of the Item simpleicons-14/A/Apacheparquet

sprite $ApacheparquetXs [10x10/16z] LOQ50O1008ImM_QVrloyX5fZ_CCVFR5HQ5nrjnMaGmIm2m2s4YILRW

sprite $ApacheparquetSm [12x12/16z] VSY53S100CF059x1-szRPd04f-WlJDtKOxmfeqekETTn63cwSO5QaC1a8T0Ou-z6paNQaLid2jqR

sprite $ApacheparquetMd [16x16/16z] ZSUr0SLG3CNG6p04_BJ_j9_1PLJfw5f6rqACYgycZi3ip7gnXcCxwy1mnNDMC2hP3XJ4IHGMUB5A0Wc1m2J94kONNQ_EtJgbR7orJn1gZHTRdRqx

sprite $ApacheparquetLg [20x20/16z] {
bSe5hWGm30DHDqcvpTp_j9znXVjaqSXwMjEZIL_s_yFzs6ynqZ9hFMtVhmIHgKuMCDvgESn1Hj8dro7sqYtG5nGu5UoIAXnFPeCe5qjIRpQeEKgQ0Bsp5J0D
RW7q1QR34Rz9LYOi0_G7zCSajmhemM_w5UXPhm
}

!procedure Apacheparquet($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/A/Apacheparquet', $name, $tech, $desc)
!endprocedure
