@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../"

' loads the library
!include ../../library.puml

' loads the MaterialsMail element
include('elements/materials/MaterialsMail')
MaterialsMail('element', 'Mail', 'an optional tech field')
@enduml
