' definition of the Item simpleicons-14/M/Microsoftexcel

sprite $MicrosoftexcelXs [10x10/16z] Oq06_100P741EJ01JdvEJawGA3zKZ8677meOuMBy67eHmW

sprite $MicrosoftexcelSm [12x12/16z] LOo55S0m24I1nktstxPn-JmSZbu29hLErKrrrZ6M66EkdW1RRSm1ycRN86meyPuNPB1ZPaKYMKHyTNthL__Av0S

sprite $MicrosoftexcelMd [16x16/16z] TOu54WH120F3xhZb_x-zCEVMHU667nphYSSZ7eAkhh6vfgiLU-zhTC6jxfZHn2AZEYVl_Ih13hx6nVKBo7Yjuo3QCxunXaGAUcg6__-vwjFXLlZW0W

sprite $MicrosoftexcelLg [20x20/16z] {
VT250KCX40FGS5T3i_-s9T_zuIwuvJkGp1r8IH0wvBBldRlMih2EnIf6bYWaAn8zaElQBg0X7lhgM9hnOpBTf_0WmS33MWJ2zttHoT-XxmpMrMmodVlq1q7u
7Wj8uWuk_04
}

!procedure Microsoftexcel($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Microsoftexcel', $name, $tech, $desc)
!endprocedure
