' definition of the Item simpleicons-14/M/Mingww64

sprite $Mingww64Xs [10x10/16z] JSe50GH130J1saH0-rVx31SSWi52ZIrKdzKscQ_2j4bpoRqowUm_Lqo7Em

sprite $Mingww64Sm [12x12/16z] FSo50O0m44FHZplPVrjo0MglSa8ROvJ26Fsu2uIjHqUzGqUxz_3dTAVuQu-2su_kC3lIZHF4nYZ_OZPWJ0Sdm0C

sprite $Mingww64Md [16x16/16z] NOs54GGm408PZKF_tVuHtcCxsJFSDO8UO8Z6r46-ifXI15NhZK6mE8znaqjWEPUfBJ7rNOm9NKGukGHsnYOPjX7dPzwa1LR6Eha4Te3-Fy_51GOM8OC7

sprite $Mingww64Lg [20x20/16z] {
HOu73eGm0CDox9t___PaHG5hLIQubSAWCEh57WMJ_IcRvSYX2aPMhpnxDEmSJXtseycZ7aVPI8scMOLCAxSFpHvjvNfQ_8wwkjHecYYQB6aXDnHDI7FJthWc
ZSdlDDaXQDAYwL_UzMX46Scg2HGIdhJuc1P4YIQjyA1uPrT_
}

!procedure Mingww64($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Mingww64', $name, $tech, $desc)
!endprocedure
