' definition of the Item simpleicons-14/M/Minimax

sprite $MinimaxXs [10x10/16z] Oq01_Cmi_10MCpy_2rW4mk97YF4ZPBbWBB0i0pyJ0qGBFr0DL90PI

sprite $MinimaxSm [12x12/16z] NSor0S1008LGufw__xJdJlKg6FlXIvpGnZdw-QFF0sP5lwZn98h1UskiZUl8puCX2m

sprite $MinimaxMd [16x16/16z] ZOh50G0n0CAeUzb_sdFNvWS9cg0geDFx1f7X7xTcs3OvkNLBhQ-Rbnt2jSVZnh23L3Zwa30XgvZs4LQ59te

sprite $MinimaxLg [20x20/16z] bSZ50GCn0C0m7uRZ_QSjCrTFyIUTcFMsuZo8mnflBas8p9ykEz_SOWOgtfmq83zS2JoVm_FLDSN7esIU3axNpnUl1p8MXEk9aEfukgWWyiZn-QO-yTuM

!procedure Minimax($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/M/Minimax', $name, $tech, $desc)
!endprocedure
