@startuml
sprite $AwsRedshiftLg [20x20/16z] fSt50SKW40JGBpks_VSRu18zPl27zUjO12YVI71c11rMp1h2EWphvWfEbavYwcep-kDYKTPF5vjdMChLIhZQEjFjVbfVpUaLdqmb9vv37p5H1RfVPm

sprite $AwsRedshiftMd [14x14/16z] XSsd0S0m4CLGzDljls_YRcYnXrIFh9OtcAfmKL0BMd8bv54IN16WjuZOH-3Od4EBUoYI3Oz-

!procedure AwsRedshift($id, $name="Redshift", $tech="")
  CloudElement($id, 'aws/Analytics/AwsRedshift', $name, $tech)
!endprocedure
!procedure AwsRedshiftCard($id, $funcName="", $content="")
  CloudCard($id, '<$AwsRedshiftMd>', 'Redshift', $funcName, $content)
!endprocedure
@enduml
