@startuml
sprite $MaterialsSpeakerGroupLg [20x20/16z] {
NT3LOK0X44JHdJMSwR_QU9vmFm-E_0ReJv0hrFbRryjqaTLpaN7Rvb2HSfddjtM8v6NPlcsd-ZYCgqyULXGQwsciNs8IBtDqRiFCnrfLaecUhtcDqtG-rpR0
5Fa-jxbQsKzR93V9XucNtnB_1ZcB4VuRBjCs_rAvWhu__XC
}

sprite $MaterialsSpeakerGroupMd [14x14/16z] HOw50S0m20JX8Hxw-qzRRtCHNEJ2_CHKRZ3PQZ2z5eTAORxqPE24rYUM7HjhYMLbm6P-hORIaJ-hOjBzimOyeNuMcrlvkcZjuppsMA8tSk4jNxnRgld5RHq

!procedure MaterialsSpeakerGroup($id, $name="Speaker Group", $tech="")
  CloudElement($id, 'materials/Hardware/MaterialsSpeakerGroup', $name, $tech)
!endprocedure
!procedure MaterialsSpeakerGroupCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsSpeakerGroupMd>', 'Speaker Group', $funcName, $content)
!endprocedure
@enduml
