@startuml
sprite $MaterialsComputerLg [20x20/16z] nS-r5SD0403HXQEbv_whjPXIuGyd6xY4Szd9t2So4rs96VKj670576CZsA5FczUyKxrlM7y75K54Zqr5Xks3Fi057G

!function MaterialsComputer($id, $name="Computer", $tech="")
  CloudElement($id, 'materials/Hardware/MaterialsComputer', $name, $tech)
!endfunction
!function MaterialsComputerCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsComputerLg>', 'Computer', $funcName, $content)
!endfunction
@enduml
