@startuml
sprite $MaterialsCastLg [20x20/16z] {
ZP250SKm24JliFZ-wtwNUbuRmm6pq5OGpACj69dipWNUxpB30hlBN3OotDdQcMnafO-iQrzQ6RwKoLti8nQ-jJhlGlktq-YPI9MBMhG5PDYVRnBO49G0VhtL
PtzH89yPGEs-1ABWPrQpt
}

sprite $MaterialsCastMd [14x14/16z] LOx50K012481U_-1V-VpOWF-K0-4fXz6NdWebxrLElYjhCk-C-laNId5pBkYZxFjhgYHvwNWmt0rur2dG6ABmzcV5G

!function MaterialsCast($id, $name="Cast", $tech="")
  CloudElement($id, 'materials/Hardware/MaterialsCast', $name, $tech)
!endfunction
!function MaterialsCastCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsCastMd>', 'Cast', $funcName, $content)
!endfunction
@enduml
