@startuml
sprite $MaterialsGamepadLg [20x20/16z] dP053i1040Ax4o9L_l_RkljDV1N8xWawOb-JwzewrZeIQnHsmV9H7NJ5heGwkkyq7aPW67R3K1kBG-ckThLxzUD2IwgtwwokCxsc1G

sprite $MaterialsGamepadMd [14x14/16z] TKx50K1H2E9Wt63_QN_7AxiLp6IPzcSXHPKPQKyKON2_FLAY0quf-woVxAxK_tfaC-q

!function MaterialsGamepad($id, $name="Gamepad", $tech="")
  CloudElement($id, 'materials/Hardware/MaterialsGamepad', $name, $tech)
!endfunction
!function MaterialsGamepadCard($id, $funcName="", $content="")
  CloudCard($id, '<$MaterialsGamepadMd>', 'Gamepad', $funcName, $content)
!endfunction
@enduml
