@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure/bootstrap')

' loads the Item which embeds the element ServiceMultifactorAuthenticationCard
include('azure/Item/Security/ServiceMultifactorAuthentication')

' renders the element
ServiceMultifactorAuthenticationCard('ServiceMultifactorAuthenticationCard', 'Service Multifactor Authentication Card', 'an optional description')
@enduml