@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('aws-q2-2024/bootstrap')

' loads the Item which embeds the element AmazonFSxForNetAppOntap
include('aws-q2-2024/Architecture/Storage/AmazonFSxForNetAppOntap')

' renders the element
AmazonFSxForNetAppOntap('AmazonFSxForNetAppOntap', 'Amazon F Sx For Net App Ontap', 'an optional tech label', 'an optional description')
@enduml