' definition of the Item fontawesome/Brands/Btc

sprite $BtcXs [7x10/16z] Os3W1q86ACN93mH0cX68WJIS0W88Znqc217ZW-e3

sprite $BtcSm [9x12/16z] HOo30S104C1Ikzb_sk9rEHCGIUHaCz7JZReUVuR2u9MIP9WuMnN9hlkfpYRM-Fm2

sprite $BtcMd [12x16/16z] PKw50S0m26Drp__Vhgwu4oBY82HgjCTon1Q3FlfuTjR6R5idMxF5UiH29S3jsop7euiHqnsxR9oBsIQEGNxWUN3-

sprite $BtcLg [15x20/16z] {
XKy54i0m28FviFp_jNENDfKSJcW2G2Kwsf0m6n41rE0DJsQF2uYub8dxNcOprbBCP1jlLDxDE4rLdtwdpToncSnS-jPwy-x5ksbtSocMsIcYCLizumAd-b3K
brdv8m
}

!procedure Btc($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/Btc', $name, $tech, $desc)
!endprocedure
