@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element Cuttlefish
include('fontawesome/Brands/Cuttlefish')

' renders the element
Cuttlefish('Cuttlefish', 'Cuttlefish', 'an optional tech label', 'an optional description')
@enduml