' definition of the Item fontawesome/Brands/Dev

sprite $DevXs [8x10/16z] Ou023duSW9c7cPyPI0D91duEVY39pCJFWAuABW8

sprite $DevSm [10x12/16z] VSQt0O103C10kI63zfyM-5ZwgcCAS_6iSRZhSu7kj25b9zoocUFfxWy

sprite $DevMd [14x16/16z] bOc54S1G38MeUzX_shgUzXFb7b-cU6Z3_qJii-tLW20JssepiyWr6xFfD738SJUsJ0uZtx-iDu7kOtnO

sprite $DevLg [17x20/16z] jSgr0GD150FHESRLz5-jcHqPxYKV9DxKpPDgT1CJz0AYnECZY8f1Zmy9grR3yF3Wk5J3_Q46SdvKI5qhUBGsNHoQHjVLhyGNl1PujGS

!procedure Dev($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/Dev', $name, $tech, $desc)
!endprocedure
