' definition of the Item fontawesome/Brands/InternetExplorer

sprite $InternetExplorerXs [10x10/16z] 9Oo50G0X4CFwYjFzfyMISnNSldVmGYGR4jp5X1Aq3PBtWyTkwWolB4MUJ

sprite $InternetExplorerSm [12x12/16z] HOo50S0W40DRt6__QN4vv3Nv3f4LC_JixvbY8degA4nwl-IvETSCPMf7pcMaHIr6FlV__zScJOiCyGdAftLttUuD

sprite $InternetExplorerMd [16x16/16z] JSXH0a0W0C3G0L2r-v-M2dX_6p_1ZTiGaWQGQhL9q54a7ws3kuy0v4NhZ-e6OQXPMG0gpQP2zWyiyWihFgxgJcKnYKNi62owlDFxMiahtvW0OLjcDOyK9m

sprite $InternetExplorerLg [20x20/16z] {
PSq54WCW30318rJGtlz_sqbTTWJYy2ccEtWfKQTUMfsDkxDt00kIBmFE93zCsZtLV3kVWMvLAt0o5M2ZGYgFbGMrSxSVnqSkYRlvoFaB_4EOAf-sQVB9RWfI
pMyxoi4q2cMOsCB5JmKti7ohC0HeFYoIkvvd46tq5f2k
}

!procedure InternetExplorer($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/InternetExplorer', $name, $tech, $desc)
!endprocedure
