' definition of the Item fontawesome/Brands/Paypal

sprite $PaypalXs [7x10/16z] Ou02JduWO63W1m4k2CMEJ3608H0m0Y5GFIy_5uW2wW1H

sprite $PaypalSm [9x12/16z] HOh50S0m08IktYZxJniNNYTeG-MO0SdCGESUmJ5SQd0rZYM--WYWmlsTe4uF6G

sprite $PaypalMd [12x16/16z] LSk50S0W00F15FVilsrn-Gg7uIco5Rev4vVvMYoM3ByiYCNajp_FRXbYlr2TCWUhNOLM02mfgj7ATLok2T9Y9ILwFm

sprite $PaypalLg [15x20/16z] NSlL0K0X34FHu4xsd_OfVhyuj0NE_9UMlmnxvcNYw2LdTgVRAGB4GX1gAYGY32L98ZTKyUxXUqcflgtuCcIsy5BN7maGxI3ZopNgdwKHCxipJnxT

!procedure Paypal($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/Paypal', $name, $tech, $desc)
!endprocedure
