@startuml
' configures the library
!global $LIB_BASE_LOCATION="https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution"

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element SquareKickstarter
include('fontawesome/Brands/SquareKickstarter')

' renders the element
SquareKickstarter('SquareKickstarter', 'Square Kickstarter', 'an optional tech label', 'an optional description')
@enduml