@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('fontawesome/bootstrap')

' loads the Item which embeds the element SquareWebAwesome
include('fontawesome/Brands/SquareWebAwesome')

' renders the element
SquareWebAwesome('SquareWebAwesome', 'Square Web Awesome', 'an optional tech label', 'an optional description')
@enduml