' definition of the Item fontawesome/Brands/SquareKickstarter

sprite $SquareKickstarterXs [8x10/16z] Ou01VdJ02nLam4BpWXbSI9fWJ

sprite $SquareKickstarterSm [10x12/16z] Oq00Vgo0XucV2SA2AC9auPRbv-Nd0P8W35N4pGS1x

sprite $SquareKickstarterMd [14x16/16z] Oq05h7nmmCl0oeyVy36nypCpmtXG4_3mE51ugFeOiUfZP61W1YAOKXwWdNoOxc10vQ4

sprite $SquareKickstarterLg [17x20/16z] ZO-50G0X24Mnsx__jDVMzJDfe2kYXnDX94Ny8d61o2KAcGwAmXT5FXJwx54K_gHWE2cAvYP7E2kmZhWSXKfAGCounPmLb32WwCmC

!procedure SquareKickstarter($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'fontawesome/Brands/SquareKickstarter', $name, $tech, $desc)
!endprocedure
