' definition of the Item azure/Item/Iot/ServiceEventGridSubscriptions

sprite $ServiceEventGridSubscriptionsXs [10x10/16z] Oq00DXXWO8E9G4WMX1fE2CNCo01bG6bMA8yLeHTX7W

sprite $ServiceEventGridSubscriptionsSm [12x12/16z] JSl50G1124FHZqF_1Q_Bl1EIiCeVQQzZvdLFWGFlw3FFY2WFNMOYml_sFUMFnGu

sprite $ServiceEventGridSubscriptionsMd [16x16/16z] XOw54S0m30DLLVPTzX-ut31ym0nOuILm8c6j_M8cvVxx4vFfaa989hQKJXfPbEEkt8M2DwFTHqouD_jNd

sprite $ServiceEventGridSubscriptionsLg [20x20/16z] ZT350GCn40F05GNwBpWvPjBF8tCzpMkV4rklmojBmsZplZRMIveIsb6xxljU4Wb0hSsaWbSByqfYivPHEsHXXNIVSU7SM2tu-cspFVmhrq7-

!procedure ServiceEventGridSubscriptions($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'azure/Item/Iot/ServiceEventGridSubscriptions', $name, $tech, $desc)
!endprocedure

!procedure ServiceEventGridSubscriptionsCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$ServiceEventGridSubscriptionsLg>', 'Iot', $funcName, $content)
!endprocedure

!procedure ServiceEventGridSubscriptionsGroup($id, $name='Service Event Grid Subscriptions', $tech='')
  IconGroupElement($id, 'IconGroupElement', '<$ServiceEventGridSubscriptionsLg>', $name, $tech)
!endprocedure
