@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('azure/bootstrap')

' loads the Item which embeds the element ServiceMachineLearningStudioWebServicesCard
include('azure/Item/Iot/ServiceMachineLearningStudioWebServices')

' renders the element
ServiceMachineLearningStudioWebServicesCard('ServiceMachineLearningStudioWebServicesCard', 'Service Machine Learning Studio Web Services Card', 'an optional description')
@enduml