' definition of the Item simpleicons-7/N/Nintendo3Ds

sprite $Nintendo3DsXs [10x10/16z] NSR50O100C2muaxtdnRdBA_WPvEVuArOUmCZO1W69Xn5XLvunyRl1

sprite $Nintendo3DsSm [12x12/16z] O-3ZXm5EFWO4u6TWu06BCk9b8zGZ0HHn40G2BXuGcmt2Pk02iY5wE80q9v9w

sprite $Nintendo3DsMd [16x16/16z] ZOs30G0n54EFDVQVjhPV-PLSM9Oy-AhufBa0yTY4ZPdqt8SnRU8IsTBMZVk5GyLjyo4-zkj-VHphXXWF_9wl2ha6

sprite $Nintendo3DsLg [20x20/16z] hSor0GGX503HmHtwh_Pa7GbtmlS5quOAnZ1M6bDoizJEn6NvPKEVSTgGRAkOEc_Tbe6mcMaDpYDfbVYPVrh5sfzXn6rKUVsx32vBMv7D2bEE8eTS-W8

!procedure Nintendo3Ds($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/N/Nintendo3Ds', $name, $tech)
!endprocedure
