' definition of the Item simpleicons-14/S/Shadow

sprite $ShadowXs [10x10/16z] Om02Jdus1X3W1mDE80CAM44ig2W_9c23inZuOTePEA4c0KaO0m

sprite $ShadowSm [12x12/16z] RSt50S0m0810wbxsdxQkINZT3_O6Myuy-r0_TFhOmNJjnoXmEmFodStxcrysi08

sprite $ShadowMd [16x16/16z] VS_L0O0m40FGu1go_xJrm-7zjUT8EcgfOAXio4_jjlBShILvLq5NtUrD_LjkxqeIstv_eworRpG8KPtV07ZQkeSPha_ODHu

sprite $ShadowLg [20x20/16z] ZSZ50SGm0C0m5yFn_jCUCrPFSP6wTUN1uaKRkF11UY_DxwKBBBu2tqHybtpNtQRwRlKTgWDGlMeqvSIhaS74oUW5a2RExWNFD_B04nvbjOqSxG4

!procedure Shadow($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Shadow', $name, $tech, $desc)
!endprocedure
