' definition of the Item simpleicons-14/S/Sharex

sprite $SharexXs [10x10/16z] DOY50G0X3CJohf3zfyLfpu77zVk0rtwWLo-nMgMt_e1wQkn9B-Vss0_dmGmP

sprite $SharexSm [12x12/16z] 7Sk50GH124DHrdLu_LTxaezBwiVe-Uhw8mpIXjQR1nSlYIrdAw9wsBd-_JI4-zVlHAacAU0QdlI3y5JHQS_w0W

sprite $SharexMd [16x16/16z] 9S65WOG040ImEGTMqd-rhqb-bRu_T_8FK4Zo0D18e1iqzQBWH6Cjr2r03pO_NY2GFowySTxpQmOBykiDQ6v92XmCda0Bu2ngoL8070aQeFDZ6U2PV0C

sprite $SharexLg [20x20/16z] {
NO-50GCn30Fz30RjlsrTASLxp2Kc8rV1vydXDbWmo7vgUgeRRmfDgmrVf2JtZtsSzdxEFXP1Vw7HBsw8UyQWIebO3k9asZ3YemZLBZU1INSqLvdWkNwHuSwt
Elh-A5JIyU0AuintwR2uLLTSTw4yq2vu_9lTJAK-fDcV_8pKicJcNZy
}

!procedure Sharex($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Sharex', $name, $tech, $desc)
!endprocedure
