' definition of the Item simpleicons-14/S/Singaporeairlines

sprite $SingaporeairlinesXs [10x10/16z] JSP50G0n00InFOR2-5TRfhoYrK4V73qxRIVK_lI9hwwg1x0vrZYdJue

sprite $SingaporeairlinesSm [12x12/16z] NKo50S0W3CEXcl-ldIlUQ9WM-1dBm3DZM_TOjrrksZ-2R7C-vmv--81aO7kAAA3lerBfbi-cSMZRNG4

sprite $SingaporeairlinesMd [16x16/16z] LSnL0aKX201HxCJP_sfVtCJvEmh8KP2joEw6Miu1rf30iC2YtGme5DZ7AthRmGGpe3GOzY8A_NLd9Ig4opyH4ER9r2YAr76lZm9LkAVN-8V_umi

sprite $SingaporeairlinesLg [20x20/16z] {
PT1LeeKm30N02WvXzh_Q9rUXFVsRMfBqJ4bzh1rLMiepqHWJjRNZv2h5Hc6xs6d6oiM2WTKLC_7quOiR4y9--zVERBlzR6LswpfWbsgzeESIFdHiDeifYVnv
Rx9OfEFytgogLShov-Qnhn5ndMm644_u1G
}

!procedure Singaporeairlines($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Singaporeairlines', $name, $tech, $desc)
!endprocedure
