' definition of the Item simpleicons-14/S/Soriana

sprite $SorianaXs [10x10/16z] Oq005dv-VWWBo601atn036RmSu9uO2QOom5aGbZyt0nSO2rmtH0MbCq49

sprite $SorianaSm [12x12/16z] LOl50G0n3CDqZAttdxQC-YGc9XGOtXKUQJ-BhKJ_at-NbRhWI-A3leA5AbOoJ_8hsVO

sprite $SorianaMd [16x16/16z] PSo50O0m34JHZpkt_xQGkZoaZTAx9KqaCZk_POsXWC7EUPMvVI6vKdpx8yMZF-QOGDxk4pURHMabyCfRuS8e86fZRWjVikcF1qfp23y

sprite $SorianaLg [20x20/16z] {
TOs55KGX4CJotO3flzfJN89dvx4CE8qp2pchVjXMYI_FfpQ1Lok4-xndiTFVNURKSPU_XzDbGPGrcNrPWJCaTrO5xhzqlptm0BUWa1Ci4wKyIMG_Dl8WP_iv
Agmqqp3XUGC
}

!procedure Soriana($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'simpleicons-14/S/Soriana', $name, $tech, $desc)
!endprocedure
