' definition of the Item simpleicons-5/Q/Qiskit

sprite $QiskitXs [10x10/16z] 1S670S0W00CWkjoQ_xyjGCi7yXfq0lY43QtjelHFQu70TsKb6M72IxGE--0LUVW1

sprite $QiskitSm [12x12/16z] 9SI55SGm30KmrUchmzb_saDzy3LEzJUjqsmulIF6OLFyBFPTLit86MC7rtLHrl7r_rfdbDfhb1tkX8UUjfz6ijUesVPOC2FKv-4D

sprite $QiskitMd [16x16/16z] {
JSw50SKW34311wHePFzflzHlWcCd5YjniJPhMMZbBra9TVTLYm54HzcbgM00WqF9TCjGsTNbGd6FdOPIJNb97Xo2m_B6Nwf0MZsHpCpTmiqR0wiS5g16pHma
7G-pKVYBvHk0vYJXaMlVs6Lt43M0Bm
}

sprite $QiskitLg [20x20/16z] {
JSw5iKDH24NHVTs0qt-rN_9aiaPnkAJfiiQN4ICIDPPdRYeLvgx0MNTgkNPljOrbPljA0OD7D1WDOFCIX1A0SvjpfaxNMKVXxdkwPNncLuVIjKQ3D3MNRowr
SiaX7kBMpJktURNjQ2Mvt7JPqkImYi-SQn-ZgwIw3uOV7hK0g94FBmEIWAd5hNYv7rcZRtFtyAFcvTuJe4GJHRncH6zJLW7u1G
}

!procedure Qiskit($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/Q/Qiskit', $name, $tech)
!endprocedure
