' definition of the Item simpleicons-5/Q/Qiskit

sprite $QiskitXs [10x10/16z] uwS3

sprite $QiskitSm [12x12/16z] unza

sprite $QiskitMd [16x16/16z] un_X

sprite $QiskitLg [20x20/16z] unzKO1G

!procedure Qiskit($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/Q/Qiskit', $name, $tech)
!endprocedure
