' definition of the Item simpleicons-5/Q/Qzone

sprite $QzoneXs [10x10/16z] LOU50G0X00BvJhtzfxMJHZDeWrS96n3gIAaRT07dd_wTdWhkj1w0j59ooGC

sprite $QzoneSm [12x12/16z] POk30G0n34NFgDx-qzPkd8zj2RgJlvmxa8xV449_WJ_sFUg80fupoGu_JN6OE9ypJ59i-RxpVRA7wMy7

sprite $QzoneMd [16x16/16z] TOs55GGn44A9U-Y_stl3-SgFZW5ku25a-Gq3oVyoETw1ovD6Jm3qdS41OPFSi73lLPwb2b1alUqjXYW524wphCEgXeLmiJ50Fxw1Y8UuIiXjqYbURvqTWGS

sprite $QzoneLg [20x20/16z] {
VP350S0W40IFu3hzLnjtcnUSxyeVccUiuUyX2znZ0EaQ2aoewuAPiloKYnMWvXZB70_60kJh2F6ib4xiDdKBEYcmNBG5EzNMgcrAsLAoWTjUocytBdTreS7j
uajlV8cjfyHRJ6yDcudLo4QO_1e
}

!procedure Qzone($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-5/Q/Qzone', $name, $tech)
!endprocedure
