' definition of the Item aws-q1-2025/Architecture/CloudFinancialManagement/AwsBillingConductor

sprite $AwsBillingConductorXs [10x10/16z] OyS9cE4iDYYJbPKLAiB4m01HmyhAmW8LOsHaX31OG03P9

sprite $AwsBillingConductorSm [12x12/16z] TSQ50G0W2011clqdjZjUWVD_X2chnhArUsnZCyDgPm0Onc5X4MbUjqh9jo8

sprite $AwsBillingConductorMd [16x16/16z] dSS50iH020H1kDlf-V-Bu-v9hq3vGwcsO7B_5wqivUHiOx1a8WAbnrfhCWRmw7-21AETBceRlPs_x0lVLmC

sprite $AwsBillingConductorLg [20x20/16z] fSY54KG120DH80dfl-BlSguxjlFyRyJQfQMNa0_CfLjh82wjbvmNbfghmxgAMLE1oSwoOkhImFKl351A52_CxGGIUMdfoBauxV5nxpJtdhzf1

!procedure AwsBillingConductor($id, $name="", $tech="", $desc="")
  IconElement($id, 'IconElement', 'aws-q1-2025/Architecture/CloudFinancialManagement/AwsBillingConductor', $name, $tech, $desc)
!endprocedure

!procedure AwsBillingConductorCard($id, $funcName="", $content="")
  IconCardElement($id, 'IconCardElement', '<$AwsBillingConductorLg>', 'CloudFinancialManagement', $funcName, $content)
!endprocedure

!procedure AwsBillingConductorGroup($id, $name='Aws Billing Conductor', $tech='')
  IconGroupElement($id, 'CloudFinancialManagementFamily', '<$AwsBillingConductorLg>', $name, $tech)
!endprocedure
