' definition of the Item simpleicons-7/I/Ipfs

sprite $IpfsXs [10x10/16z] LSQ50G0n40B1VPS8_NSRjpa14aFnKkqaVroHA8Kkt8yZ4Imj_NnZaqiU2

sprite $IpfsSm [12x12/16z] HOp50G0X40C7T-Y_sXDiyuepKJY8OFLasjredDGcKkgJ3fr9C7Be6IOd33YSpSlbHNodWJfvPY6F-Vi2

sprite $IpfsMd [16x16/16z] TSV50GGn00GWrZMP_gizT-67cyshhPkNxh5X1gK1pUwcsR0KJs6TCzosfMLbJuCX8vUJckmyBfczNlpvrhnyeIqlhp0FjsyjO6_4E7jeQWfm1

sprite $IpfsLg [20x20/16z] {
VT250S0W40F0nvtilsr9tLFbS6HFaNjoRiLV92wDS8Yksv_V1kZwCWORmLo6AHYMWKCiG1ljaHPH7LeQRGHmuzt0mMXx7rJ-7SQcJUwMe1-c8V-s_5-_pLoi
9BuD3dFOZoejfhgH8yqDwrukKTpOcWa
}

!procedure Ipfs($id, $name="", $tech="")
  IconElement($id, 'IconElement', 'simpleicons-7/I/Ipfs', $name, $tech)
!endprocedure
