@startuml
' configures the library
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.."

' loads the library's bootstrap
!include $LIB_BASE_LOCATION/bootstrap.puml

' loads the package bootstrap
include('eventstorming/bootstrap')

' loads the Item which embeds the element Saga
include('eventstorming/Element/Saga')

Saga('Saga') [
Saga
--
A saga is a long-lived business transaction.
]
@enduml